### ISSUE TITLE
executor snapshot testing: the ordering of rows in output chunks

### ISSUE THREAD

**Issue by richardchien** [risingwavelabs/risingwave#10005]
Executors like `HashAgg` produces chunks in which the order of rows does not matter, so previously we just sort them before `assert_eq!`. However, some other executors like `Sort` produces rows in order, we may want snapshot tests to detect wrong ordering in such cases.

What do you think? @xxchan

**Comment by xxchan** [comment]
You may add a param in `run_until_pending` to specify whether to sort results.
