### ISSUE TITLE
bug(meta): can not compact L0 files after split a new compaction group

### ISSUE THREAD

**Issue by Little-Wallace** [risingwavelabs/risingwave#10014]
### Describe the bug

<img width="996" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/16376959/d24841d3-86d2-4bc9-877f-205b690a9759">

in above picture, we found that the number of files in group5-level0 increase. 

Because after split, if there are still some files left in overlapping-level, they may not wait enough files because we would flush all files as a non-overlapping level.

**Comment by lmatz** [comment]
It is fixed by #10015, right?

**Comment by fuyufjh** [comment]
> It is fixed by https://github.com/risingwavelabs/risingwave/pull/10015, right?

@Little-Wallace Please confirm

**Comment by Little-Wallace** [comment]
closed by https://github.com/risingwavelabs/risingwave/pull/10015
