### ISSUE TITLE
main-cron: pulsar source check failed due to result mismatching

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#10034]
<img width="619" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/25862682/554f7546-f77e-4ac5-a439-4afdaf45f28e">

https://buildkite.com/risingwavelabs/main-cron/builds/522#018859b2-5de7-4ee1-a7fa-627a532c4b57
https://buildkite.com/risingwavelabs/main-cron/builds/523#01885ed0-6572-4fb8-9594-b36c890825e9
https://buildkite.com/risingwavelabs/main-cron/builds/524#018863f6-ac92-472a-bf8f-2c15eecae1cb

**Comment by lmatz** [comment]
closed #9948 

@tabVersion is working on it

**Comment by tabVersion** [comment]
@Honeta changed the data on the remote side by mistake. Will fix it soon.

**Comment by Honeta** [comment]
fixed. sorry for that :(

**Comment by tabVersion** [comment]
> fixed. sorry for that :(

keep an eye on tomorrow's test results and make sure if it fixes the bug

**Comment by lmatz** [comment]
i can trigger the main-cron test on Buildkite if the fix PR is opened

**Comment by Honeta** [comment]
> Member

The problem is in astra streaming, not risingwave. I have made changes at the remote end, please run main-cron again.

**Comment by Honeta** [comment]
> i can trigger the main-cron test on Buildkite if the fix PR is opened

The problem is in astra streaming, not risingwave. I have made changes at the remote end, please run main-cron again.

**Comment by lmatz** [comment]
https://buildkite.com/risingwavelabs/main-cron/builds/525

**Comment by lmatz** [comment]
It passed.
