### ISSUE TITLE
ProjectSet should have at least one table function

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#10040]
### Describe the bug

Since it is a query from a user, we keep it confidential and link it to the slack channel:
https://risingwave-labs.slack.com/archives/C048771BGKF/p1685077317730769

**Comment by TennyZhuang** [comment]
Reproduce without user secrets:

```sql
with cte as (SELECT 1 as v1, unnest(array[1,2,3,4,5]) AS v2) select v1 from cte;
```

It’s likely that we wrongly assumed the output of ProjectSet must be used.
