### ISSUE TITLE
Support `current_setting`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#10051]
### Describe the bug

```
2023-05-29T11:40:41.350829Z ERROR risingwave_frontend::session: failed to handle sql:
SELECT CAST(current_setting('server_version_num') AS INT) / 100 AS version:
    Bind error: failed to bind expression: CAST(current_setting('server_version_num') AS INT) / 100
    Caused by:
      Feature is not yet implemented: unsupported function: "current_setting"
      Tracking issue: https://github.com/risingwavelabs/risingwave/issues/112
```
when connecting from Grafana by creating `RW` as a PostgreSQL data source.

See #8345

### Additional context

Don't know if we should customize a plugin of Risingwave for Grafana though

**Comment by fuyufjh** [comment]
[Materialize plugin for Grafana](https://grafana.com/grafana/plugins/bsull-materialize-datasource/)

**Comment by lmatz** [comment]
> For 9.4.10, somehow it triggers a invalid memory access in Grafana. It worked well with the official postgres.

It is likely to be the fact that some queries is unsupported, so no result is returned to Grafana, and thus it null errored.
