### ISSUE TITLE
Have antlr4 syntax file?

### ISSUE THREAD

**Issue by melin** [risingwavelabs/risingwave#10067]
### Describe the solution you'd like

Want to use java parsing sql syntax, obtain table information

**Comment by TennyZhuang** [comment]
Sorry, currently we use a hand-written parser which originally forked from https://github.com/sqlparser-rs/sqlparser-rs, so we don't have any syntax file. If you think some parser generator is more suitable for our project, you can create a discussion and we can discuss about the feasibility and workload.

**Comment by xxchan** [comment]
RisingWave is PostgreSQL compatible. You may find a PostgreSQL ANTLR (maybe some minor modifications are needed), e.g., here's cratedb's ANTLR (PG compatible) https://github.com/crate/crate/blob/7f4ccfe32b56cac0bbcde5b39db3661462d188f4/libs/sql-parser/src/main/antlr/SqlBaseParser.g4
