### ISSUE TITLE
bug: Missing rows in the output of the table function

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#10080]
### Describe the bug

The fix in #10068 is wrong

### To Reproduce

```sql
with cte as (SELECT 1 as v1, unnest(array[1,2,3,4,5]) AS v2) select v1 from cte;
```

```
 v1
----
  1
(1 row)
```

### Expected behavior

In pg

```
 v1
----
  1
  1
  1
  1
  1
(5 rows)
```

**Comment by xxchan** [comment]
It seems the corret fix should be: we cannot prune table functions when doing column pruning.

**Comment by xxchan** [comment]
BTW, it seems that even if the fix may be simple, it might be better to include a test. 😄
