### ISSUE TITLE
bug: No route to host error encountered in docker compose env

### ISSUE THREAD

**Issue by findpather** [risingwavelabs/risingwave#10097]
### Describe the bug
```
meta-node-0    | 2023-05-31T07:07:55.857637Z  INFO risingwave_meta::rpc::election_client: client meta-node-0:5690 start election
meta-node-0    | 2023-05-31T07:07:56.881619Z ERROR risingwave_meta::rpc::server: election error happened, Election failed: grpc request error: status: Unavailable, message: "error trying to connect: tcp connect error: No route to host (os error 113)", details: [], metadata: MetadataMap { headers: {} }
meta-node-0    | 2023-05-31T07:07:56.881669Z  INFO risingwave_meta::rpc::election_client: client meta-node-0:5690 start election
meta-node-0    | 2023-05-31T07:07:57.905639Z ERROR risingwave_meta::rpc::server: election error happened, Election failed: grpc request error: status: Unavailable, message: "error trying to connect: tcp connect error: No route to host (os error 113)", details: [], metadata: MetadataMap { headers: {} }
meta-node-0    | 2023-05-31T07:07:57.905688Z  INFO risingwave_meta::rpc::election_client: client meta-node-0:5690 start election
```

### To Reproduce

git clone https://github.com/risingwavelabs/risingwave.git

cd docker
docker compose up -d

**Comment by yezizp2012** [comment]
Hi @findpather , I tried on the newest commit in the main branch and it works for me. The errors you posted indicates that meta can't connect the etcd instance. Did the etcd container restart at this point in time? If so did the cluster recover as expected after the etcd restart?

**Comment by findpather** [comment]
I completely follow the official documents, deployment operation, I do not know why there are so many problems.

**Comment by yezizp2012** [comment]
Hi @findpather , the etcd logs don't look like a problem, and I'm also running into an unhealthy status, but it looks like a false alarm, and the cluster I started is working fine. In your environment, can you use `psql` connect to the cluster and run some ddl and query?

**Comment by findpather** [comment]
Hi @yezizp2012 
[root@mhost ~]# psql -h localhost -p 4566 -d dev -U root
psql: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

[root@mhost ~]# psql -h 192.168.100.36  -p 4566 -d dev -U root
psql: could not connect to server: Connection refused
        Is the server running on host "192.168.100.36" and accepting
        TCP/IP connections on port 4566?
[root@mhost ~]# telnet 192.168.100.36 4566
Trying 192.168.100.36...
telnet: connect to address 192.168.100.36: Connection refused
                         
[root@mhost ~]# ss -pnlt |grep 4566
LISTEN 0      65535               *:4566             *:*    users:(("docker-proxy",pid=1107605,fd=4))                   

What software package do you use over there? Can you send it to me?

**Comment by yezizp2012** [comment]
I just simply cloned the repo, and started it with `docker compose up -d`. Then I can connect it using psql as follows:
```shell
psql -h localhost -p 4566 -d dev -U root
```

Could you please provide more details about your local environment? Like you system specs, docker version etc.

**Comment by findpather** [comment]
[root@mhost ~]# cat /etc/redhat-release 
CentOS Linux release 8.5.2111
[root@mhost ~]# docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

docker-compose.yml

version: "3"
services:
  compactor-0:
    image: "ghcr.io/risingwavelabs/risingwave:latest"
    command:
      - compactor-node
      - "--listen-addr"
      - "0.0.0.0:6660"
      - "--advertise-addr"
      - "compactor-0:6660"
      - "--prometheus-listener-addr"
      - "0.0.0.0:1260"
      - "--metrics-level"
      - "1"
      - "--meta-address"
      - "http://meta-node-0:5690"
      - "--config-path"
      - /risingwave.toml
    expose:
      - "6660"
      - "1260"
    ports: []
    privileged: true
    depends_on:
      - meta-node-0
      - minio-0
    volumes:
      - "./risingwave.toml:/risingwave.toml"
    environment:
      RUST_BACKTRACE: "1"
      # If ENABLE_TELEMETRY is not set, telemetry will start by default
      ENABLE_TELEMETRY: ${ENABLE_TELEMETRY:-true}
    container_name: compactor-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/6660
      interval: 1s
      timeout: 5s
      retries: 5

  compute-node-0:
    image: "ghcr.io/risingwavelabs/risingwave:latest"
    command:
      - compute-node
      - "--listen-addr"
      - "0.0.0.0:5688"
      - "--advertise-addr"
      - "compute-node-0:5688"
      - "--prometheus-listener-addr"
      - "0.0.0.0:1222"
      - "--metrics-level"
      - "1"
      - "--meta-address"
      - "http://meta-node-0:5690"
      - "--connector-rpc-endpoint"
      - "connector-node:50051"
      - "--config-path"
      - /risingwave.toml
    expose:
      - "5688"
      - "1222"
    ports: []
    privileged: true
    depends_on:
      - meta-node-0
      - minio-0
    volumes:
      - "./risingwave.toml:/risingwave.toml"
    environment:
      RUST_BACKTRACE: "1"
      # If ENABLE_TELEMETRY is not set, telemetry will start by default
      ENABLE_TELEMETRY: ${ENABLE_TELEMETRY:-true}
    container_name: compute-node-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/5688
      interval: 1s
      timeout: 5s
      retries: 5

  etcd-0:
    image: "quay.io/coreos/etcd:v3.5.7"
    command:
      - /usr/local/bin/etcd
      - "--listen-client-urls"
      - "http://0.0.0.0:2388"
      - "--advertise-client-urls"
      - "http://etcd-0:2388"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2389"
      - "--initial-advertise-peer-urls"
      - "http://etcd-0:2389"
      - "--listen-metrics-urls"
      - "http://0.0.0.0:2379"
      - "--name"
      - risedev-meta
      - "--max-txn-ops"
      - "999999"
      - "--max-request-bytes"
      - "10485760"
      - "--auto-compaction-mode"
      - periodic
      - "--auto-compaction-retention"
      - 1m
      - "--snapshot-count"
      - "10000"
    expose:
      - "2388"
    ports:
      - "2388:2388"
      - "2389:2389"
    depends_on: []
    volumes:
      - "etcd-0:/etcd-data"
    environment: {}
    container_name: etcd-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/2388
      interval: 1s
      timeout: 5s
      retries: 5

  frontend-node-0:
    image: "ghcr.io/risingwavelabs/risingwave:latest"
    command:
      - frontend-node
      - "--listen-addr"
      - "0.0.0.0:4566"
      - "--meta-addr"
      - "http://meta-node-0:5690"
      - "--advertise-addr"
      - "frontend-node-0:4566"
      - "--config-path"
      - /risingwave.toml
      - "--prometheus-listener-addr"
      - "0.0.0.0:2222"
      - "--metrics-level"
      - "1"
    expose:
      - "4566"
    ports:
      - "4566:4566"
    privileged: true
    depends_on:
      - meta-node-0
    volumes:
      - "./risingwave.toml:/risingwave.toml"
    environment:
      RUST_BACKTRACE: "1"
      # If ENABLE_TELEMETRY is not set, telemetry will start by default
      ENABLE_TELEMETRY: ${ENABLE_TELEMETRY:-true}
    container_name: frontend-node-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/4566
      interval: 1s
      timeout: 5s
      retries: 5

  meta-node-0:
    image: "risingwavelabs/risingwave:v0.18.0"
    command:
      - meta-node
      - "--listen-addr"
      - "0.0.0.0:5690"
      - "--advertise-addr"
      - "meta-node-0:5690"
      - "--dashboard-host"
      - "0.0.0.0:5691"
      - "--prometheus-host"
      - "0.0.0.0:1250"
      - "--backend"
      - etcd
      - "--etcd-endpoints"
      - "etcd-0:2388"
      - "--connector-rpc-endpoint"
      - "connector-node:50051"
      - "--state-store"
      - "hummock+minio://hummockadmin:hummockadmin@minio-0:9301/hummock001"
      - "--data-directory"
      - "hummock_001"
      - "--config-path"
      - /risingwave.toml
    expose:
      - "5690"
      - "1250"
      - "5691"
    ports:
      - "5690:5690"
      - "5691:5691"
    privileged: true
    depends_on:
      - "etcd-0"
    volumes:
      - "./risingwave.toml:/risingwave.toml"
    environment:
      RUST_BACKTRACE: "1"
      # If ENABLE_TELEMETRY is not set, telemetry will start by default
      ENABLE_TELEMETRY: ${ENABLE_TELEMETRY:-true}
    container_name: meta-node-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/5690
      interval: 1s
      timeout: 5s
      retries: 5

  minio-0:
    image: "quay.io/minio/minio:latest"
    command:
      - server
      - "--address"
      - "0.0.0.0:9301"
      - "--console-address"
      - "0.0.0.0:9400"
      - /data
    expose:
      - "9301"
      - "9400"
    ports:
      - "9301:9301"
      - "9400:9400"
    privileged: true
    depends_on: []
    volumes:
      - "minio-0:/data"
    entrypoint: "

      /bin/sh -c '

      set -e

      mkdir -p \"/data/hummock001\"

      /usr/bin/docker-entrypoint.sh \"$$0\" \"$$@\"

      '"
      
    environment:
      MINIO_CI_CD: "1"
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_PROMETHEUS_URL: "http://prometheus-0:9500"
      MINIO_ROOT_PASSWORD: hummockadmin
      MINIO_ROOT_USER: hummockadmin
    container_name: minio-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/9301
      interval: 1s
      timeout: 5s
      retries: 5
      
  connector-node:
    image: ghcr.io/risingwavelabs/risingwave:latest
    entrypoint: "/risingwave/bin/connector-node/start-service.sh"
    ports:
      - 50051
      - 50052
    container_name: connector-node
    privileged: true

  message_queue:
    image: "docker.vectorized.io/vectorized/redpanda:latest"
    command:
      - redpanda
      - start
      - "--smp"
      - "1"
      - "--reserve-memory"
      - 0M
      - "--memory"
      - 4G
      - "--overprovisioned"
      - "--node-id"
      - "0"
      - "--check=false"
      - "--kafka-addr"
      - "PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092"
      - "--advertise-kafka-addr"
      - "PLAINTEXT://message_queue:29092,OUTSIDE://localhost:9092"
    expose:
      - "29092"
      - "9092"
      - "9644"
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9644:9644"
      - "8081:8081"
    depends_on: []
    volumes:
      - "message_queue:/var/lib/redpanda/data"
    environment: {}
    container_name: message_queue
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/9092
      interval: 1s
      timeout: 5s
      retries: 5
volumes:
  etcd-0:
    external: false
  grafana-0:
    external: false
  minio-0:
    external: false
  prometheus-0:
    external: false
  message_queue:
    external: false

**Comment by findpather** [comment]
My server has been successfully deployed, and I need to modify docker-compose.yml file with the following parameters

privileged: true

ports:

- "192.168.1.36:29092:29092"

- "192.168.1.36:9092:9092"

- "192.168.1.36:9644:9644"

- "192.168.1.36:8081:8081"

networks:

app_net:

ipv4_address: 10.10.0.107

**Comment by findpather** [comment]
My server has been successfully deployed, and I need to modify docker-compose.yml file with the following parameters
