### ISSUE TITLE
Tracking: PG server version compatibility

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#10099]
> Currently, our pg version is inconsistent and also too high to make it compatible with JDBC. (e.g. JDBC PostgreSQL connector will use over-window sql to fetch columns metadata). So downgrade the server version to 8.3 is more appropriate right now.

Related PR: https://github.com/risingwavelabs/risingwave/pull/10024

- [ ] After our system support over window batch queries in the future, we can change the server version back to 9.5. https://github.com/risingwavelabs/risingwave/issues/9124

**Comment by xxchan** [comment]
(not) fun fact
![EFB6ACF1-F19F-4035-A161-DAF05F14A97B](https://github.com/risingwavelabs/risingwave/assets/37948597/0da2412c-778e-4c81-b2dd-00c2415d3975)

**Comment by xxchan** [comment]
Well .... https://github.com/risingwavelabs/risingwave/issues/11178

![image](https://github.com/risingwavelabs/risingwave/assets/37948597/61bb3942-7d17-42c5-9da0-a2555e53b8ec)
