### ISSUE TITLE
feat(meta): optimize the complexity of MinOverlappingPicker

### ISSUE THREAD

**Issue by Little-Wallace** [risingwavelabs/risingwave#10109]
### Background

The complexity of meta-service select a new compaction-task from base-level to bottom level is O(N^3). Because we would calculate the overlap-size of every range.  Although we limit the size of every task, the complexity is till O(k*N^2), in where k equals `max_select_bytes/sstable_file_size`.

If we reduce the size of sstable file, the complexity would increase.  Since we must select compaction task with holding a mutex of hummock-manager, we do not hope it cost too much time.

 You  can see more details in `MinOverlappingPicker::pick_compaction` .

### Describe the solution you'd like

We can partition the files in `select-level` to several size close groups. 
and then we can calculate the balance for each group by  `sum(files of group in select level)/sum(overlap files in target level)`.

We can see that the complexity of this partition-algorithm is O(N^2).

And then we would select a group which has the largest in-balance score., we can calculate it with a complexity of O(k^3) where k represents the size of each group.

**Comment by fuyufjh** [comment]
@Little-Wallace Please feel free to reassign

**Comment by Little-Wallace** [comment]
I think this issue is not urgent at the moment, we will solve it in the next version
