### ISSUE TITLE
[editing]discussion(optimizer): consider state table's primary key column order to achieve better spatial locality

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#10105]
We have found the state key's column order can affect performance during the previous explorations. This issue is to clarify the problem and discuss some potential ways to solve it.

## introduction
Here is the query of nexmark q17
```SQL
    SELECT
      channel,
      to_char(date_time, 'yyyy-MM-dd') AS day,
      max(to_char(date_time, 'HH:mm')) AS minute,
      count(*) AS total_bids,
      ... other agg functions ...
    FROM bid
    GROUP BY channel, to_char(date_time, 'yyyy-MM-dd');
```

The Aggregate executor needs to get the agg result of the group key during the processing. In other words, the executor will query the internal table many times like this 
```SQL
SELECT * from agg_result_table WHERE channel = $1 AND day = $2;
```

##

**Comment by BugenZhao** [comment]
Is the edit done? 😄
