### ISSUE TITLE
bug: compaction task stuck for hours

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#10209]
### Describe the bug

Rencently we have seen a small cg3 (MV compaction group) L0->L0 compaction task getting stuck for hours, which cause L0->base level compaction to block for the corresponding compaction group. Some findings:
- The stuck compaction task contains 60 SSTs with total size=~13MB so it is a relatively small task.
- Compactor is alive and can handle tasks from both the same and different compaction groups as usual.
- We saw "Ready to handle compaction task" [log](https://github.com/risingwavelabs/risingwave/blob/572780bbca08c25a5d2f71016b915733e146df04/src/storage/src/hummock/compactor/mod.rs#L279) but not "Finished compaction task" [log](https://github.com/risingwavelabs/risingwave/blob/572780bbca08c25a5d2f71016b915733e146df04/src/storage/src/hummock/compactor/mod.rs#L374). This means compactor indeed received the task but not finished it.
- The task progress and heartbeat of the stuck task is continously reported to meta node. We use a [guard](https://github.com/risingwavelabs/risingwave/blob/572780bbca08c25a5d2f71016b915733e146df04/src/storage/src/hummock/compactor/mod.rs#L257) to make sure the task progress is cleared if the task finishes or errors out so that means the task is indeed stuck in the compactor side.
- Metric "Compacting SSTable Count" reported by meta node stays at 60 for cg3 level0. This means meta indeed didn't receive ReportCompactionTasksRequest from the compactor.

### Additional context

![image](https://github.com/risingwavelabs/risingwave/assets/5518566/c8aeb10c-9bbf-427a-a47b-50e57ca1e075)
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/9efdc762-d236-40d6-835b-fcda68aedd0c)
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/3dffef44-a3ba-48a4-888b-81ae83e38007)

[log.csv](https://github.com/risingwavelabs/risingwave/files/11672843/log.csv)

**Comment by hzxa21** [comment]
cc @Li0k @Little-Wallace

**Comment by Little-Wallace** [comment]
We have temporarily fixed this issue by cancel a long task by https://github.com/risingwavelabs/risingwave/pull/10183.
but we have not found why the task hung out.

**Comment by Li0k** [comment]
> We have temporarily fixed this issue by cancel a long task by #10183. but we have not found why the task hung out.

Might fixed by https://github.com/risingwavelabs/risingwave/pull/10584 ?
