### ISSUE TITLE
Support for protobuf / varint?

### ISSUE THREAD

**Issue by peter-eht** [risingwavelabs/risingwave#10200]
### Describe the bug

Hello,

I am trying to integrate RisingWave into our existing tech stack, in order to consume Protobuf messages from a Kafka host. I have converted the `.proto` definition file, and have successfully created a source:

```sql
CREATE SOURCE IF NOT EXISTS message_source 
WITH (
   connector='kafka',
   topic='my_topic',
   properties.bootstrap.server='kafka:9092',
   scan.startup.mode='latest',
   scan.startup.timestamp_millis='140000000'
)
ROW FORMAT PROTOBUF MESSAGE 'my_scope.MyMessage'
ROW SCHEMA LOCATION 'http://localhost/protodef.pb';
```

When I try to read from the table:

```sql
SELECT * FROM message_source;
```

...I get the following error:

```
ERROR:  QueryError: Internal(BatchError: BatchError: Protocol error: parse message failed: failed to decode Protobuf message: invalid wire type: Varint (expected LengthDelimited))
```

When compiling my `.proto` file to a Go format (i.e. `protodef.pb.go`), I can see that `int32` is being compiled to a `varint`. I tried switching `int32` to `string`, but the error persists (perhaps because Kafka contains previously-sent messages which contain `int32` throughout).

I haven't found issues or discussions related to `Varint` or `LengthDelimited`.

Is it possible for RisingWave to parse messages containing "varint" `int32` rather than expecting length-delimited fields? What am I doing wrong?

Kind regards,
- Peter

### To Reproduce

* create a `.proto` file which contains integer datatypes (e.g. int32)
* compile the `.proto` file to binary `.pb`
* provide this `.pb` file to a RisingWave connector via any web service accessible through HTTP
* create a connector to Kafka
* attempt to select from the connector "table"

### Expected behavior

I expect RisingWave will parse protobuf messages with integer datatypes (int32, int64, etc).

### Additional context

Versions of various things:
* Ubuntu 22.04 running in WSL2
* risingwave Docker images
	* @latest (`d796876abbf07c792589dc7f8e6d3e79cfd8fcdd7380c619d85995e7711d7bcf`)
	* @50e9e018d47fcee54d1b1d8618eb00b6a19e4e7a-x86_64 (`74e51cd5c33dbcf3dca194bed4ab19482fdb4ff3e9ec11e616a4956c7a3a6f54`)
* protoc
	* 3.20.2
	* 23.2
* Go 1.20.4
* protoc-gen-go, Python's protobuf

Edit 1: removed an incomplete reference to `protoc` usage.
Edit 2: a word.

**Comment by BugenZhao** [comment]
Hi Peter, thanks for your interest in RisingWave. The error you reported occurred during the parsing of a binary record in Kafka with `prost`, a library for handling protobuf in Rust.

`invalid wire type: Varint (expected LengthDelimited))` indicates that some field is defined as a "string, bytes, embedded messages, packed repeated fields" in the `.pb` descriptor, but the incoming data is actually in the format of "int32, int64, uint32, uint64, sint32, sint64, bool, enum". So could you please check whether the binary data and the message descriptor match each other?

**Comment by fuyufjh** [comment]
Closed due to inactivity. Feel free to reopen.
