### ISSUE TITLE
improve observability for compaction group split

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#10218]
There are two observability issues related to compaction group split:
1. We don't have metrics for compaction group split
2. Compaction group split will modify metadata of hummock inclduing compaction metadata and version metadata but won't update the compaction/version metrics immediately. For example, `trigger_sst_stat` is not triggered.

**Comment by Little-Wallace** [comment]
What metrics do we need for group split?

Here's what I can think of that needs to be collected:

* group split check frequency.
* write throughput of every group and state-table.
* the number of state-table of every group.
* the number of sstable files which have several reference in different group.

Welcome more suggestion for metrics.

**Comment by Little-Wallace** [comment]
closed by https://github.com/risingwavelabs/risingwave/pull/10337
