### ISSUE TITLE
bug(CI): e2e source test flaky 

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#10221]
### Describe the bug

CI pipeline sometimes fails in `end-to-end source test`

[This pipeline run failed](https://buildkite.com/risingwavelabs/pull-request/builds/24854#018895a6-bb6a-4ad2-a8b1-0247721c6abf), while [the next one](https://buildkite.com/risingwavelabs/pull-request/builds/24856) succeeded. 

```
[cargo-make] INFO - Running Task: check-logs
--
[cargo-make] INFO - Execute Command: "/usr/bin/env" "bash" "/tmp/fsio_Aa3C1vO2bp.sh"
log size is significantly large (3.2M). Please disable unnecessary logs.
[cargo-make] ERROR - Unable to execute script.
[cargo-make] WARN - Build Failed
```

### Log from failed pipeline source test

[pull-request_build_24854_end-to-end-source-test.log](https://github.com/risingwavelabs/risingwave/files/11676989/pull-request_build_24854_end-to-end-source-test.log)

**Comment by StrikeW** [comment]
close as the issue doesn't come out for a long time.
