### ISSUE TITLE
Bug(integration-test): debezium-mongo case timeout

### ISSUE THREAD

**Issue by huangjw806** [risingwavelabs/risingwave#10231]
This debezium-mongo case of integration testing always has a timeout error：

<img width="1080" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/29391315/49655455-3996-4ee0-9f4c-fd4b6ff31f03">

https://buildkite.com/risingwavelabs/integration-tests/builds?branch=main

**Comment by huangjw806** [comment]
@neverchanje debugged into the problem before. He think the query handling did got stuck. He suspect there is some deadlock or pg protocol issue.

**Comment by tabVersion** [comment]
close as not reproduced
