### ISSUE TITLE
Discussion: replace minstant and minitrace with the standard instant and tracing library

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#10236]
minitrace relies on minstant.

We have seen two issues related to the portability of `minstant` in different platforms: #4547 and #10235. 

IMO, the bottleneck won't be in the tracing and timing library in a foreseeable future. Fixing ande debugging portability issues in minstant and potentially minitrace can be a headache. I suggest we consider using more widely used libraries like tokio tracing and std time instead.

Discussions are welcomed.

**Comment by BugenZhao** [comment]
Related: #10000

**Comment by BugenZhao** [comment]
> Do we have any remaining issue regarding minstant/minitrace?

After https://github.com/risingwavelabs/risingwave/pull/10417, all related stuff will be cleaned-up.
