### ISSUE TITLE
Cannot handle postgres numeric/decimal type with scale unspecified in Postgres Debezium CDC

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#10247]
Currently we cannot handle postgres numeric/decimal type with scale unspecified in Postgres Debezium CDC. For example, Debezium CDC messages of table `t` will be skipped because we cannot parse the decimal type correctly but we can handle table `t2` without any issue.
```sql
# all messages of this table will be skipped.
create table t (price numeric);

# all messages of this table will be prased and handled.
create table t2 (price numeric(4, 2));
```

This is because [debezium maps the decimal types with and without scale specified to different avro types](https://www.postgresql.org/docs/current/datatype-numeric.html) and we currently can only parse the standard avro decimal type, not the composite type `io.debezium.data.VariableScaleDecimal`. Example decimal type schema fetched from schema registry:
- table t (variable scaled decimal i.e. `NUMERIC`)
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/fea8a025-6baa-40af-bfa7-fb15ec533c03)

- table t2 (fixed scaled decimal i.e. `NUMERIC(p,s)`)
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/6c739c7b-4a8c-492e-9e2c-0fc1a31d3b63)

I found it somehow difficult to handle the table `t` case since our decimal data type seems to have a fixed scale while the pg decimal type with scale unspecified can [have a changing scale](https://www.postgresql.org/docs/current/datatype-numeric.html).

**Comment by hzxa21** [comment]
> our decimal data type seems to have a fixed scale

Discussed offline. @fuyufjh found that we use rust decimal as the underlying type and rust decimal supports variable scale.

**Comment by fuyufjh** [comment]
> I found it somehow difficult to handle the table t case since our decimal data type seems to have a fixed scale while the pg decimal type with scale unspecified can [have a changing scale](https://www.postgresql.org/docs/current/datatype-numeric.html).

Yes. Currently, we are using an 128-bit variable decimal implementation backed by [rust_decimal](https://docs.rs/rust_decimal/latest/rust_decimal/). 

Personally, I think rounding (loss of precession) is better than `NULL`, and of course, better than dropping the whole row.

cc. @xiangjinwu
