### ISSUE TITLE
Discussion: `SELECT * EXCEPT` syntax

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#10265]
This is an interesting feature supported by BigQuery. https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax

<img width="535" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/9161438/711ef2e9-deff-43c1-ac97-661ad2d2051f">

## Why do we need that?

The feature is very useful to us since we don't support output rank in the common pattern Group TopN, see https://www.risingwave.dev/docs/current/sql-pattern-topn/

It can be very frustrating if we use the existing syntax and the table has a large number of columns (We've seen about 30-100 columns in user queries).

```sql
SELECT c1, c2, c3, c4, c5, c6
  FROM (
    SELECT c1, c2, c3, c4, c5, c6, 
      row_number() OVER (PARTITION BY grp
        ORDER BY sk) AS rank
    FROM t1)
WHERE rank <= N;
```

If we use `*` in the outer query, then the query will fail by:

```
fail to transform overAgg to groupTopN: the rank cannot be included in the outer select_list, see https://www.risingwave.dev/docs/current/sql-pattern-topn/ for more information
```

If we support the `* EXCEPT [column_list]` syntax, we can simply write the following query:

```sql
SELECT * EXCEPT rank
  FROM (
    SELECT c1, c2, c3, c4, c5, c6, 
      row_number() OVER (PARTITION BY grp
        ORDER BY sk) AS rank
    FROM t1)
WHERE rank <= N;
```

**Comment by xiangjinwu** [comment]
#9092

**Comment by TennyZhuang** [comment]
> #9092

In all well-known database, only BigQuery supports that, but they use `EXCEPT` keyword :(

**Comment by st1page** [comment]
> > #9092
> 
> In all well-known database, only BigQuery supports that, but they use `EXCEPT` keyword :(

Sorry it is my typo :hot_face: :crying_cat_face:

**Comment by xxchan** [comment]
Let's discuss in https://github.com/risingwavelabs/risingwave/issues/9092
