### ISSUE TITLE
discussion(streaming): default parallelism 

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#10263]
Currently, we use number of total cores of all CN as the default parallelism of streaming, because this ensures a streaming job can utilize the CPU resource in the cluster.

(Random thoughts when discussing with @st1page) As we are going to support a more user-friendly scaling user interface, shall we adapt to a more conservative stratety of choosing parallelism?

May need some investigation on other systems.

**Comment by lmatz** [comment]
Flink's default parallelism can be set by users.
And the user can also override it when submitting the job.

**Comment by xxchan** [comment]
related https://github.com/risingwavelabs/risingwave/issues/9504

**Comment by BugenZhao** [comment]
We've supported changing per-session default parallelism with `set streaming_parallelism`, which will be scheduled to all compute nodes in a round-robin manner.

> conservative stratety of choosing parallelism

I'm a little bit confused about this. 😕 As we're going to hide the concept of "parallelism" with the new-proposed high-level scaling interface, will this go against our original idea?

**Comment by fuyufjh** [comment]
> We've supported changing per-session default parallelism with set streaming_parallelism, which will be scheduled to all compute nodes in a round-robin manner.

Yes. What I am thinking is the default behavior, that is, when users didn't set (and probably never heard of) `streaming_parallelism`

> > conservative stratety of choosing parallelism
>
> I'm a little bit confused about this. 😕 As we're going to hide the concept of "parallelism" with the new-proposed high-level scaling interface, will this go against our original idea?

That makes a lot of sense 🤣 Seems we should keep that principle

**Comment by fuyufjh** [comment]
closed by #10447
