### ISSUE TITLE
bug: risectl reschedule should forbid remove all parallel units from a fragment

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#10286]
### Describe the bug

```
 create table t (a int);
```

Let's assume that table t has a parallel unit consisting of [0, 1, 2, 3]. We should reject this request.
```
export RW_META_ADDR="http://localhost:5690"
target/debug/risingwave risectl meta reschedule --plan "2-[0,1,2,3]"
```

**Comment by BugenZhao** [comment]
https://github.com/risingwavelabs/risingwave/blob/eae365cfd87c7e79876780285c48c97dd81191a6/src/meta/src/stream/scale.rs#L641-L646

So this check does not take effect? 👀

**Comment by chenzl25** [comment]
> if new_actor_ids.is_empty() {

It seems not work.
