### ISSUE TITLE
Provide java udf server instead of libs.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#10322]
Currently user needs to setup udf server by themselves. Another approach is that we can provide a udf server to the user, and loads user provided jar when startup. This way user only needs to focus on udf development.

**Comment by xxchan** [comment]
I'm also thinking about this when considering https://github.com/risingwavelabs/risingwave/issues/9002. 

This might be a larger problem for cloud. If we allow arbitrary UDF server, we need extensive defensive checks. If we host the servers, and let users to register functions, we can at least ensure **the protocol is correct**... (avoid problems like https://github.com/risingwavelabs/risingwave/issues/10828, https://github.com/risingwavelabs/risingwave/issues/11022) But of course that might limit flexibility and increase operation burden. 🤔️

**Comment by xxchan** [comment]
Btw, isn’t that Flink’s solution for Python UDF? i.e., the Python runtime
process is fully managed by Flink.

I think there are different solutions and each has different advantages:
- Fully external (current): maximal flexibility, users can have any
dependencies, and can have their own middlewares/gateway (to achieve
scaling/observability/failover). Snowflake/Redshift supports this (Mainly
deployed as Lambda function, and they both use JSON as the protocol).
- Sidecar runtime process managed by RisingWave: User submits jar/py. I
guess dependencies & debugging are not as good.
- Separate server but manually deployed (like connector node) (can be
deployed both by user and us?) : Looks like a tradeoff between the above
two. Does any other product support this? 🤔️
