### ISSUE TITLE
support setting application_name for each session

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#10339]
### Is your feature request related to a problem? Please describe.

Required by DataGrip.

Upon establishing a session, the client will set `application_name` in the FeStartupMessage. For psql, the application name is `psql`. For DataGrip, it is "DataGrip 2023.1.2".

In addition, Postgres allows dynamically setting the variable via `set application_name to my_application;`. We may also support it in the future.

**Comment by TennyZhuang** [comment]
A workaround: use `assumeMinServerVersion=9.0.0` in the connection string, and wait #10356 to be merged.

**Comment by TennyZhuang** [comment]
![mermaid-diagram-2023-06-26-081656](https://github.com/risingwavelabs/risingwave/assets/9161438/4e5a8145-64c7-4d93-b44e-570c5bb6b55d)

**Comment by TennyZhuang** [comment]
Fixed in latest main, tested.
