### ISSUE TITLE
Potential bug: node may fail to join cluster when meta marks the node as expired

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#10336]
### Describe the bug

IIUC, the current behavior of our worker node membership management is:
- A node only registers itself to meta on startup
- The node keeps heartbeat meta when it is up. If heartbeat fails, it [retries endlessly](https://github.com/risingwavelabs/risingwave/blob/4d6bc592a0590ebf8bfdbeba25f2017a5167458c/src/rpc_client/src/meta_client.rs#L612).
- Meta [expires ](https://github.com/risingwavelabs/risingwave/blob/4d6bc592a0590ebf8bfdbeba25f2017a5167458c/src/meta/src/manager/cluster.rs#L262) a node when it hasn't received a heartbeat within certain amount of time.
- Meta returns the `invalid_worker` [error ](https://github.com/risingwavelabs/risingwave/blob/4d6bc592a0590ebf8bfdbeba25f2017a5167458c/src/meta/src/manager/cluster.rs#L223) if it receives a heartbeat from a node that is not in its state.

Based on the behavior above, there can be a corner case causing a node not able to join the cluster forever. Consider the following sequence of events:
1. A node registers itself to meta and starts the heartbeat process
2. There is a temporary network partitioning between the node and meta lasting for more than the node expired TTL. (This can also be caused by meta failure when the new meta node is not up before node expired TTL).
3. Meta expires the node since it hasn't received heartbeat for more than expired TTL.
4. After 2, the node will send heartbeat and receive the error endlessly. The node won't re-register itself to the meta until a manul restart is triggered.

**Comment by hzxa21** [comment]
I found this issue when reading the heartbeat codes. I don't think we have seen this issue actually happening and I haven't done a repro so I may be wrong. cc @yezizp2012

**Comment by yezizp2012** [comment]
> After 2, the node will send heartbeat and receive the error endlessly. The node won't re-register itself to the meta until a manul restart is triggered.
When the node receives a `invalid_worker` error, it will automatically exit. When it get restarted manually or by k8s, it will re-register itself to meta to join in, and meta will treat it as a new node.
https://github.com/risingwavelabs/risingwave/blob/e3fe51b83a1db20d70c6feffaba44b84ea029a87/src/rpc_client/src/meta_client.rs#L285-L290

**Comment by hzxa21** [comment]
> > After 2, the node will send heartbeat and receive the error endlessly. The node won't re-register itself to the meta until a manul restart is triggered.
> 
> When the node receives a `invalid_worker` error, it will automatically exit. When it get restarted manually or by k8s, it will re-register itself to meta to join in, and meta will treat it as a new node.
> 
> https://github.com/risingwavelabs/risingwave/blob/e3fe51b83a1db20d70c6feffaba44b84ea029a87/src/rpc_client/src/meta_client.rs#L285-L290

I see. I missed the implementation in `send_hearbeat`. Thanks for the explanation :)
