### ISSUE TITLE
bug: TPC-H Q2 OOM

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#10330]
### Describe the bug

TPC-H Q2 (without filter condition, scale factor = 50) will OOM for several times during test.

<img width="933" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/58fef5df-bf1b-4eb2-953f-3ef3733fbfeb">

Full query and plan here: [tpch_q2.txt](https://github.com/risingwavelabs/risingwave/files/11742213/tpch_q2.txt)

### Error message/log

OOM. No error log.

### To Reproduce

Running TPC-H Q2 in our [tpch-benchmark pipeline](https://buildkite.com/risingwave-test/tpch-benchmark/builds?branch=main) .

**Comment by lmatz** [comment]
```
TPC-H Q2 (without filter condition, scale factor = 50)
```

When this setting is used for Flink, the query does not OOM. 
But taking a checkpoint will spend more than 10 minutes, and thus the job fails by exceeding its default checkpoint timeout, i.e. 10 minutes. 
Although not OOM, the job never really makes any progress as each checkpoint fails.
During the 10 minutes, the throughput peaks at 800 rows/s when it just starts and then quickly drops to double-digits rows/s.

**Comment by fuyufjh** [comment]
An interesting observation is that when I ran this locally, the memory curve is much more stable i.e. less spikes

<img width="923" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/019bd64d-a8c6-436f-95a1-557208a96095">

Now I suspect that something caused severe but quick memory fluctuation in storage. Still investigating.

**Comment by fuyufjh** [comment]
**Updates**: I have successfully reproduced the problem on my EC2 machine and got some accurate heap profiling results. 🎉

Tested on branch [eric/test_disable_operator_cache](https://github.com/risingwavelabs/risingwave/compare/eric/test_disable_operator_cache), which has 

- **disabled streaming operator cache** 
- disabled cache refilling on write

See that link for details.

## Results

I captured 2 dumps at 10:50:41 and 10:43:24 respectively, which are 2 obvious spike in memory statistics. 

[flamegraph.zip](https://github.com/risingwavelabs/risingwave/files/11752332/flamegraph.zip)

<img width="924" alt="Screen Shot 2023-06-15 at 11 15 06" src="https://github.com/risingwavelabs/risingwave/assets/10192522/c5ad8a9e-cc57-4c03-81a3-0e56c76eb7e8">

Tips: When reading the flamegraph, keep in mind:

> A heap profiler records the **stack trace of the allocation** of each **live object**, so it’s possible that function A allocates something and then hand over it to struct B, in this case, the allocation will still be counted on A.



## Analysis

It turns out that most memory are consumed by streaming module.

Take the dump at 10:43:24 as an example:

- StreamChunks use ~3.7 GB memory
- State table use ~1.67 GB memory

Considering that Q2 (w/o filtering condition) has many Join executors inside, I suspect some join have bad selectivity and produced large amount of data. This is a known issue but previously we didn't realize that this will cause lots of StreamChunk in a single epoch.


## Misc.

Another interesting observation is that, previously I cannot reproduce the problem because I used parallelism = 4 in my environment. In that case, the job runs smoothly with stable memory consumption. This also inspires me that **a mass of data heaped in the streaming graph** is probably another cause of the problem.

**Comment by fuyufjh** [comment]
After limiting the exchange channel capacity, the memory usage looks much more somooth.

```yaml
[streaming.developer]
stream_chunk_size = 20
stream_exchange_initial_permits = 100
stream_exchange_batched_permits = 20
stream_exchange_concurrent_barriers = 2
```

![image](https://github.com/risingwavelabs/risingwave/assets/10192522/db9f2401-455b-45f2-95fa-2d0a1bd64fb1)

Meanwhile, the performance become worse (9min30s -> 14min44s)

**Comment by fuyufjh** [comment]
Tried to run with less exchange buffer size:

```toml
[streaming.developer]
stream_chunk_size = 256     // default: 1024
stream_exchange_initial_permits = 2048   // default: 8192
stream_exchange_batched_permits = 256    // default: 1024
stream_exchange_concurrent_barriers = 1  // default: 2
```

And it succeeded: https://buildkite.com/risingwave-test/tpch-benchmark/builds/858

For the next step, I will try to find a better set of parameters to balance between stability and performance.
