### ISSUE TITLE
Bug: Scale-in of actors containing DMLExecutors

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#10355]
### Describe the bug

```sql
create table t (a int);

-- Scale-in via the risectl reschedule

-- Sometimes the insert statement fails
dev=> insert into t values (1);
ERROR:  QueryError: internal error: BatchError: internal error: BatchError: internal error: no reader for dml in table `TableId { table_id: 1001 }`

-- Sometimes the insert statement succeeds
dev=> insert into t values (1);
INSERT 0 1

```

Before scale-in, the fragment 2 containing the `DMLExecutor` has 12 actors across 3 CN.
```
+------------------+---------------+--------+--------+
| Compute Node     | Parallel Unit | Frag 1 | Frag 2 |
+====================================================+
| 1@127.0.0.1:5688 | 0             | 1      | 13     |
|------------------+---------------+--------+--------|
|                  | 1             | 2      | 14     |
|------------------+---------------+--------+--------|
|                  | 2             | 3      | 15     |
|------------------+---------------+--------+--------|
|                  | 3             | 4      | 16     |
|------------------+---------------+--------+--------|
| 2@127.0.0.1:5687 | 4             | 5      | 17     |
|------------------+---------------+--------+--------|
|                  | 5             | 6      | 18     |
|------------------+---------------+--------+--------|
|                  | 6             | 7      | 19     |
|------------------+---------------+--------+--------|
|                  | 7             | 8      | 20     |
|------------------+---------------+--------+--------|
| 3@127.0.0.1:5689 | 8             | 9      | 21     |
|------------------+---------------+--------+--------|
|                  | 9             | 10     | 22     |
|------------------+---------------+--------+--------|
|                  | 10            | 11     | 23     |
|------------------+---------------+--------+--------|
|                  | 11            | 12     | 24     |
+------------------+---------------+--------+--------+
```

Run scale-in
```
risingwave risectl meta reschedule --plan "2-[0,1,2,3,4,5,6,7,8,9,10]" --revision 0
```

After scale-in, the fragment 2 containing the `DMLExecutor` has one actor in CN `3@127.0.0.1:5688`.
```
+------------------+---------------+--------+--------+
| Compute Node     | Parallel Unit | Frag 1 | Frag 2 |
+====================================================+
| 1@127.0.0.1:5689 | 0             | 1      | -      |
|------------------+---------------+--------+--------|
|                  | 1             | 2      | -      |
|------------------+---------------+--------+--------|
|                  | 2             | 3      | -      |
|------------------+---------------+--------+--------|
|                  | 3             | 4      | -      |
|------------------+---------------+--------+--------|
| 2@127.0.0.1:5687 | 4             | 5      | -      |
|------------------+---------------+--------+--------|
|                  | 5             | 6      | -      |
|------------------+---------------+--------+--------|
|                  | 6             | 7      | -      |
|------------------+---------------+--------+--------|
|                  | 7             | 8      | -      |
|------------------+---------------+--------+--------|
| 3@127.0.0.1:5688 | 8             | 9      | -      |
|------------------+---------------+--------+--------|
|                  | 9             | 10     | -      |
|------------------+---------------+--------+--------|
|                  | 10            | 11     | -      |
|------------------+---------------+--------+--------|
|                  | 11            | 12     | 24     |
+------------------+---------------+--------+--------+
```

It seems our frontend nodes don't know the table topology has been changed and they still schedule the DMLs statement to the CN `1@127.0.0.1:5689` or `2@127.0.0.1:5687`.

**Comment by BugenZhao** [comment]
Looks like we're selecting the worker node according to the fragment mapping of the `Materialize` executor. However, there could be an `Exchange` after `Dml` so they're not in the same fragment.

https://github.com/risingwavelabs/risingwave/blob/c3091f0f5a77d007e857d688f3cf4e3e831d237e/src/frontend/src/scheduler/local.rs#L484-L495

**Comment by chenzl25** [comment]
> Looks like we're selecting the worker node according to the fragment mapping of the `Materialize` executor. However, there could be an `Exchange` after `Dml` so they're not in the same fragment.
> 
> 
> 
> https://github.com/risingwavelabs/risingwave/blob/c3091f0f5a77d007e857d688f3cf4e3e831d237e/src/frontend/src/scheduler/local.rs#L484-L495
> 
> 
> 
> 
> 
> The update logic on the meta node after scaling:
> 
> 
> 
> https://github.com/risingwavelabs/risingwave/blob/c3091f0f5a77d007e857d688f3cf4e3e831d237e/src/meta/src/manager/catalog/fragment.rs#L845-L851

Yes. The read and the write path should choose different workers, but we just have a table fragment mapping right now.

**Comment by BugenZhao** [comment]
Seems not that easy to fix. 🤔 We must maintain the mapping from the DML target table ID to the `StreamDML` fragment ID in some sense in the frontend.

**Comment by chenzl25** [comment]
> Seems not that easy to fix. 🤔 We must maintain the mapping from the DML target table ID to the `StreamDML` fragment ID in some sense in the frontend.

Or can we ensure that `StreamDML` and `StreamMaterialize` fragments are always scheduled to the same nodes together? It seems also hard to guarantee this scheduling policy.

**Comment by BugenZhao** [comment]
> Or can we ensure that StreamDML and StreamMaterialize fragments are always scheduled to the same nodes together?

Currently, there's no support on the scheduler and scaler for this. I'm afraid this approach is not easier than maintaining the mapping on the frontend. 🥵
