### ISSUE TITLE
duplicate table name prompt error when create new table

### ISSUE THREAD

**Issue by wcy-fdu** [risingwavelabs/risingwave#10448]
### Describe the bug
create a new (IF NOT EXIST) table will notice table_name already exists. 

https://github.com/risingwavelabs/risingwave/blob/ec7a0890f0cb7706ad1d698a7f2bad2b4ae20301/src/frontend/src/handler/create_table.rs#L660
### To Reproduce

```
CREATE TABLE IF NOT EXISTS s1.t1 (v1 int);
```

**NOTICE:  relation "s1.t1" already exists, skipping**

### Expected behavior

```
schema "s1" does not exist
```

**Comment by xxchan** [comment]
What's wrong? I don't think there are any problems.

congyi wang ***@***.***> 于2023年6月20日周二 12:49写道：

**Comment by TennyZhuang** [comment]
> What's wrong?

We'll treat all error as "table already exists", e.g. we should report `schema not found` in some case.

**Comment by wcy-fdu** [comment]
> NOTICE is not an error

But users may treat it as an error.

**Comment by xxchan** [comment]
> But users may treat it as an error.

Is this a user's request? What's the expected behavior?

**Comment by TennyZhuang** [comment]
I've updated the issue description.
