### ISSUE TITLE
debezium + postgres: support for TimeMillis

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#10460]
Eventually, we need to add the following test case to our integration tests.

```sql
--- The Postgres table
CREATE TABLE IF NOT EXISTS user_specified_precision (
    id BIGINT PRIMARY KEY,
    decimal_column DECIMAL(1000),
    timestamp_column TIMESTAMP(3),
    interval_column INTERVAL(3),
    time_column TIME(3),
    char_column CHAR(512),
    varchar_column VARCHAR(512)
);

INSERT INTO user_specified_precision (id, decimal_column, timestamp_column, interval_column, time_column, char_column, varchar_column)
VALUES 
    (1, 123.456, '2023-06-19 10:30:45.123', INTERVAL '1 2:3:4.567', '10:30:45.678', 'Sample char value', 'Sample varchar value'),
    (2, 789.012, '2023-06-19 11:30:45.456', INTERVAL '2 3:4:5.678', '11:30:45.789', 'Another char value', 'Another varchar value'),
    (3, NULL, '2023-06-19 12:30:45.789', INTERVAL '3 4:5:6.789', NULL, 'Null char value', 'Null varchar value'),
    (4, 999.999, '2023-06-19 13:30:45.999', INTERVAL '4 5:6:7.999', '13:30:45.999', 'Decimal value test', 'Varchar value test'),
    (5, 135.791, '2023-06-19 14:30:45.000', INTERVAL '5 6:7:8.000', '14:30:45.000', 'Empty string test', '');

--- The RisingWave table
CREATE TABLE user_specified_precision (PRIMARY KEY (id)) WITH (
    connector = 'kafka',
    kafka.topic = 'postgres.public.user_specified_precision',
    kafka.brokers = 'message_queue:29092',
    kafka.scan.startup.mode = 'earliest'
) ROW FORMAT DEBEZIUM_AVRO ROW SCHEMA LOCATION CONFLUENT SCHEMA REGISTRY 'http://message_queue:8081';
```

`time_column TIME(3)` is unsupported in this case. The CREATE SOURCE command will return an error 'TimeMillis is unsupported'.

I also notice that we will turn `interval_column` into a bigint type, which is somewhat counter-intuitive. It's even worse that bigint cannot cast to interval...

**Comment by StrikeW** [comment]
I may not have bandwidth to look into this issue. Seems it is related to the `DEBEZIUM_AVRO` format, maybe @idx0-dev can take a look. cc @tabVersion

**Comment by tabVersion** [comment]
> I may not have bandwidth to look into this issue. Seems it is related to the `DEBEZIUM_AVRO` format, maybe @idx0-dev can take a look. cc @tabVersion

I will take a look. Expect to fix in next week.

**Comment by tabVersion** [comment]
#11157 handles type mapping rw `Time` from avro schema as it has logical type

```
{\"name\":\"time_column\",\"type\":[\"null\",{\"type\":\"int\",\"connect.version\":1,\"connect.name\":\"org.apache.kafka.connect.data.Time\",\"logicalType\":\"time-millis\"}
```

but we cannot do the same thing to `interval` type, we cannot tell the difference between `interval` and `long`. 

```
{\"name\":\"interval_column\",\"type\":[\"null\",{\"type\":\"long\",\"connect.version\":1,\"connect.name\":\"io.debezium.time.MicroDuration\"}
```

we should suggest [interval.handling.mode](https://debezium.io/documentation/reference/2.3/connectors/postgresql.html#postgresql-property-interval-handling-mode) set to `string` for this case.

**Comment by tabVersion** [comment]
close as completed
