### ISSUE TITLE
s3 CI tests on lyvecloud keep failing

### ISSUE THREAD

**Issue by tabVersion** [risingwavelabs/risingwave#10498]
### Describe the bug

https://buildkite.com/risingwavelabs/main-cron/builds/613#0188e676-148e-4e69-b93d-1c6939c64730 
https://buildkite.com/risingwavelabs/main-cron/builds/610#0188df92-8323-4ebf-83f5-be253b1ed169

we observed the failure on CI but few message available from cloud.

we need to collect risedev log along with logs from python code

**Comment by kwannoel** [comment]
Seems like it still fails on main-cron: one commit after: https://risingwave-labs.slack.com/archives/C03N6EP8ZA7/p1687758921082329.

**Comment by lmatz** [comment]
Probably the free credit given by lyvecloud is completely used up.
We can disable this pipeline.

**Comment by tabVersion** [comment]
> Probably the free credit given by lyvecloud is completely used up. We can disable this pipeline.

Is it confirmed? I cannot figure out whats going on inside.
