### ISSUE TITLE
Better hdfs state backend support.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#10575]
### Is your feature request related to a problem? Please describe.

Hdfs is widely used in on-prem deployment and many users want to use it as a state backend. Currently, we only allow users to specify namenode's ip and port, which is over simplified in real use cases. For example, user may need to configure ha of name node. What's more, user may want to use patched hdfs client rather than standard hdfs client.

### Describe the solution you'd like

We should allow user to set following environments:

1. Allow the user to set `HADOOP_CONF_DIR` so that the user can put all customized hadoop configurations in it.
2. Allow the user to set `HADOOP_HOME`, in case the user have a customized hadoop client. 

### Describe alternatives you've considered

No.

### Additional context

We need to figure out how to make it easier to use in k8s environment.

**Comment by wcy-fdu** [comment]
I will use AWS EMR to test whether current implementation is suitable for HA.

**Comment by wcy-fdu** [comment]
Update:
If user sets the HA of the namenode, RisingWave cannot connect directly through the ip:port of the namenode, and need:
1.  give the conf files under `$HADOOP_HOME/etc/hadoop`
2. set the `HADOOP_CONF_DIR`  to the copied conf file directory
3. set `CLASSPATH`
4. add `HADOOP_CONF_DIR`  to `CLASSPATH`
5. get the cluster_name from `$HADOOP_HOME/etc/hadoop/core-site.env`

After these steps, RisingWave can connect to hdfs with namenode HA enabled.

**Comment by arkbriar** [comment]
> In summary:
> 
> 1. To allow user to override hadoop configuration, we need to allow user to give us their configuration directory, and _**remember to add it to classpath**_
> 2. To allow user to further override hadoop jar files, we need to allow user to give us their hadoop installation.
> 
> Please help to make it possible in k8s. cc @arkbriar

IIUC, it's about the deployment of the HDFS rather than the RisingWave itself, right? Then it should be the operator's responsibility to do the configuration. The operator focuses only on the deployment of RisingWave processes. I think what we need here is a guide to deploy HDFS in k8s. cc @yufansong We might also need help from our document folks. cc. @CharlieSYH

**Comment by arkbriar** [comment]
> > In summary:
> > 
> > 1. To allow user to override hadoop configuration, we need to allow user to give us their configuration directory, and _**remember to add it to classpath**_
> > 2. To allow user to further override hadoop jar files, we need to allow user to give us their hadoop installation.
> > 
> > Please help to make it possible in k8s. cc @arkbriar
> 
> IIUC, it's about the deployment of HDFS rather than RisingWave itself, right? Then it should not be the operator's responsibility to do the configuration. The operator focuses only on the deployment of RisingWave processes. I think what we need here is a guide to deploy HDFS in k8s. cc @yufansong We might also need help from our document folks. cc. @CharlieSYH

Sorry, seems I was wrong. 



> Update: If user sets the HA of the namenode, RisingWave cannot connect directly through the ip:port of the namenode, and need:
> 
> 1. give the conf files under `$HADOOP_HOME/etc/hadoop`
> 2. set the `HADOOP_CONF_DIR`  to the copied conf file directory
> 3. set `CLASSPATH`/`HADOOP_CLASSPATH`
> 4. add `HADOOP_CONF_DIR`  to `CLASSPATH`
> 5. get the cluster_name from `$HADOOP_HOME/etc/hadoop/core-site.env`
> 
> After these steps, RisingWave can connect to hdfs with namenode HA enabled.

I see.

**Comment by arkbriar** [comment]
> Allow the user to set HADOOP_CONF_DIR so that the user can put all customized hadoop configurations in it.

It's possible to mount configs as files and set this env var in k8s.

> Allow the user to set HADOOP_HOME, in case the user have a customized hadoop client.

But this would require mounting of an entire external Hadoop library folder, right? It's not easy to do so in k8s. The operator allows user to mount any volumes and set any non-reserved environments. So it's possible for users to do it by themselves. Or they can build an customized image on their own. I'm highly against that we support such unofficial behaviours.

**Comment by arkbriar** [comment]
The problem of executable and depending libraries should be resolved in images, not by k8s.
