### ISSUE TITLE
feat(meta): Add transactions to cordon

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#10598]
Cordoning multiple CNs should be atomic. Either all should be cordoned or none. We should avoid having dirty writes. 

Relevant cordon PR: https://github.com/risingwavelabs/risingwave/pull/10382/files 
Comment by @yezizp2012: https://github.com/risingwavelabs/risingwave/pull/10382/files#r1243328111

CC @shanicky

**Comment by yezizp2012** [comment]
Resolved by #10640 .
