### ISSUE TITLE
bug(binder): natural join should ignore the hidden columns

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#10617]
thanks @stdrc find the bug

```SQL
dev=> create table t(v int);
CREATE_TABLE
dev=> create materialized view mv1 as select v from t where v > 10;
CREATE_MATERIALIZED_VIEW
dev=> create materialized view mv2 as select v from t where v < 10;
CREATE_MATERIALIZED_VIEW
dev=> explain select * from mv1 natural join mv2;
                                          QUERY PLAN                                           
-----------------------------------------------------------------------------------------------
 BatchExchange { order: [], dist: Single }
 └─BatchLookupJoin { type: Inner, predicate: mv1.t._row_id = mv2.t._row_id AND mv1.v = mv2.v }
   └─BatchExchange { order: [], dist: UpstreamHashShard(mv1.t._row_id) }
     └─BatchScan { table: mv1, columns: [v, t._row_id] }
(4 rows)
```

**Comment by stdrc** [comment]
This also interestingly caused e2e-in-memory failure https://buildkite.com/risingwavelabs/pull-request/builds/26661#01891acf-a6ca-4c84-ac1c-e5d31dc319e6

**Comment by stdrc** [comment]
> This also interestingly caused e2e-in-memory failure [buildkite.com/risingwavelabs/pull-request/builds/26661#01891acf-a6ca-4c84-ac1c-e5d31dc319e6](https://buildkite.com/risingwavelabs/pull-request/builds/26661#01891acf-a6ca-4c84-ac1c-e5d31dc319e6)

This seems not directly caused by current issue, so I raised another issue to track that. https://github.com/risingwavelabs/risingwave/issues/10721
