### ISSUE TITLE
crc32 function

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#10629]
### Is your feature request related to a problem? Please describe.

We'd better to have a crc32 function to do crc32 checksum to help the data verification.

### Describe the solution you'd like

https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_crc32

https://github.com/srijs/rust-crc32fast

**Comment by lmatz** [comment]
One thing is that `crc32` is MySQL-only and returns a 32-bit unsigned integer

But PG does not have unsigned integer

**Comment by fuyufjh** [comment]
Not needed now.
