### ISSUE TITLE
source: risingwave crashes when creating pg source fails because of too many replication slots

### ISSUE THREAD

**Issue by WillyKidd** [risingwavelabs/risingwave#10653]
### Describe the bug

- By default, postgres allows a maximum of 10 replication slots (for performance considerations).
- Creating a new risingwave source will create a new postgres replication slot.
- When the number of replication slot is above the limit, creating a new source will fail (as it cannot create new replication slots), and we should report this error to the user. However, risingwave also crashed due to this failure.

![image](https://github.com/risingwavelabs/risingwave/assets/57129289/57885fb9-12ec-45b4-8daf-43d5d719c3e1)

### To Reproduce

To reproduce: 
create many postgres source tables

### Expected behavior

Report the error to the user, everything should still be fine

**Comment by StrikeW** [comment]
Would you mind attach the logs to show which line of code it crashed?

**Comment by StrikeW** [comment]
We can check whether we can create new slot when creating a new table to avoid the CN crashes.

**Comment by StrikeW** [comment]
We have fixed the crash problem and designed a solution to share a pg slot among multiple CDC tables, use https://github.com/risingwavelabs/risingwave/issues/11079 to track the progress.
