### ISSUE TITLE
python udf test failed in ci

### ISSUE THREAD

**Issue by yuhao-su** [risingwavelabs/risingwave#10677]
### Describe the bug

https://buildkite.com/risingwavelabs/pull-request/builds/26579#01890c85-b8aa-46e5-9cdb-72a18dab5f53

<img width="818" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/31772373/3b9bdaff-99f9-45b7-a25e-1af2828afb4e">

**Comment by wangrunji0408** [comment]
cc @jon-chuang Is it a flaky case?

**Comment by jon-chuang** [comment]
Does it fail anywhere else? This function was always at risk of flakey-ness. It is possibly due to CPU contention that interrupts the thread from other tests.

If it is not super flakey, I propose to ignore it at ask the user to run again. We don't track test flaky-ness anywhere, do we?

**Comment by yuhao-su** [comment]
> Does it fail anywhere else?

Not that I know of.

I guess a rerun is good enough since it rarely happens.
