### ISSUE TITLE
Improve per MV granularity observability

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#10693]
Currently we have different kinds of metrics, CLI tools and SQL commands for monitoring. However, most of them are tracked and displayed either in per Node level or per Table level. From users' perspecitve, they generally care more about the overall state, resource utilization, alerts/errors on the streaming job (i.e. MV) they created as a whole. Therefore, we should consdier improving the per MV granularity observability.

Some ideas on what we should display:

- [x] Per MV storage size
- [x] Per MV (streaming/storage) memory usage
~~- [ ] Per MV CPU usage (not sure whether it can be done under our actor model)~~
- [x] Per MV remote I/O bytes/s
- [x] Per MV streaming throughput
~~- [ ] Per MV barrier latency~~

**Comment by wcy-fdu** [comment]
For CPU usage, seems that we only have node level CPU usage. I think it‘s a bit hard to monitor the cpu usage of each materialized view🤔.
