### ISSUE TITLE
can we have more explicit error hint in batch execution mode

### ISSUE THREAD

**Issue by zhougit86** [risingwavelabs/risingwave#10709]
### Is your feature request related to a problem? Please describe.

this problems can be reproduced by running 
```
select ('"{"b":\"{}\"}"'::jsonb->>'b')::jsonb;
```

the terminal just tell 
```
ERROR:  QueryError: Internal(Expr error: Parse error: risingwave_common::array::jsonb_array::JsonbVal
```

can we have more explicit hint to enable fast locate of the error data?

**Comment by TennyZhuang** [comment]
Let's refine the error message step by step.

The first problem: the original error was eaten in https://github.com/risingwavelabs/risingwave/blob/598e53190e6c8414060687d040f7b6854c58f2b3/src/expr/src/vector_op/cast.rs#L83, at least we should report it here.

After the fix, the error message should be: `QueryError: Expr error: Parse error: trailing characters at line 1 column 4`. 

In the later step, I'll try to log arguments here.
