### ISSUE TITLE
bug: `generate_series` maybe blocking and consume a lot of memory.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#10769]
### Describe the bug

When we run following sql:
```
select count(*) from generate_series(1, 500000000);
```
It may consume a lot of memory and blocking.

### Error message/log

```text
No
```

### Expected behavior

It should be easy to cancel and should not consume so much memory.

**Comment by wangrunji0408** [comment]
Table functions should not be blocking now. I'll investigate it later. 👀
