### ISSUE TITLE
q16 has high data cache miss rate but the state is small and memory is not fully utilized

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#10777]
Metabase: http://risingwave-perf-test-dashboard-metabase.us-west-2.elasticbeanstalk.com/question/3272-nexmark-q16-blackhole-medium-1cn-affinity-avg-source-output-rows-per-second-rows-s-history-thtb-179?start_date=2023-05-19

Grafana Dashboard: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1688576918000&to=1688578721000&var-namespace=nexmark-bs-15-105-affinity-daily-20230705

This is a 16 GB machine

![SCR-20230706-ezk](https://github.com/risingwavelabs/risingwave/assets/5791930/70a3b6c6-3ca2-4b3f-b407-f81c3b9fb02f)

![SCR-20230706-eyu](https://github.com/risingwavelabs/risingwave/assets/5791930/95df14fc-b90a-4441-b32c-abe6f8d08524)
![SCR-20230706-ez8](https://github.com/risingwavelabs/risingwave/assets/5791930/d149e024-77fd-4514-940c-9bd71bc2733d)

1. the 16GB memory is not entirely used. Adding CN and Compactor together (they deploy on the same machine), still under 10GB.
2. The state (all the SST file sizes added together) is smaller than the current memory usage, confused why the cache miss rate is so high?

1 and 2 seem to contradict each other

link #7271 
RW is worse than Flink, e.g. 1/2, for this query.

**Comment by lmatz** [comment]
is it because the memory is split between CN and compactor node? cc @huangjw806 
CN takes 13 GB and compactor node takes 3 GB?

**Comment by lmatz** [comment]
But it suggests that if we want to put components together in the future to further reduce cost and improve performance-cost efficiency, static memory allocation is not ideal.

**Comment by huangjw806** [comment]
> CN takes 13 GB and compactor node takes 3 GB?

CN takes 12 GB and compactor node takes 3 GB.

**Comment by lmatz** [comment]
I see, so the total memory usage << 16GB is expected

but the data cache miss rate so high still unexplained 🤔

**Comment by yuhao-su** [comment]
I noticed the data cache size in the grafana shows 1.15GiB. But I'm not sure where the value comes from (I noticed some calculation in `storage_memory_config`).

**Comment by lmatz** [comment]
@huangjw806 
let's try one more time, with Compactor 1GB and Compute Node 14GB, and reserved memory = 10% instead of 20%.

**Comment by lmatz** [comment]
14GB CN and reserved memory = 10%:
https://buildkite.com/risingwave-test/nexmark-benchmark/builds/1398#01892a0d-1879-4c36-8d43-fc675590a367

Grafana:
https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1688630109000&orgId=1&to=1688631912000&var-datasource=Prometheus%3A+test-useast1-eks-a&var-namespace=nexmark-bs-15-105-affinity-reserve-10-percents-memory-test

![SCR-20230707-j2c](https://github.com/risingwavelabs/risingwave/assets/5791930/ea4b4c77-8b87-4f2b-aa0f-2e6ee31a5b8e)
![SCR-20230707-j2i](https://github.com/risingwavelabs/risingwave/assets/5791930/aef3966a-7469-4fd0-91ed-54afc139f1ae)
![SCR-20230707-j2r](https://github.com/risingwavelabs/risingwave/assets/5791930/a260f503-293b-46fd-ad68-aaf14f36a5d2)

**Comment by lmatz** [comment]
![SCR-20230707-w9c](https://github.com/risingwavelabs/risingwave/assets/5791930/305ab8a3-6313-4229-abd1-5464911743fa)
![SCR-20230707-w90](https://github.com/risingwavelabs/risingwave/assets/5791930/defe671b-8217-4254-995c-696cbfedf257)
![SCR-20230707-w96](https://github.com/risingwavelabs/risingwave/assets/5791930/7eac8e1d-2243-47b0-ba1d-8494d450c152)

Why distinct agg cache miss rate so high?

**Comment by lmatz** [comment]
The `object total size` is after compression.
We should look at the KV size and it is larger than the memory of Compute node.

The performance right now for 1 machine deployment is close to 100K/s.
It is acceptable since it is inevitable to encounter cache misses and fetch things from S3 (which induces much higher latency than EBS).

We can benchmark again when the file cache is enabled.
