### ISSUE TITLE
connector: support parsing "string containing JSON"

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#10772]
Sometimes users may provide us JSONs that are not that normalized. For example, a JSON object can be first serialized into a string, then nested as a field of the parent object:

```json
{
  "nested": "{\"v1\": 10, \"v2\": \"hello\"}"
}
```

But users actually want it to be:
```json
{
  "nested": {
    "v1": 10,
    "v2": "hello"
  }
}
```

Currently, they have to specify the data type for `nested` as `varchar` in the source schema and then manually convert it into `jsonb` as a workaround. However, manipulating the `JsonbArray` can be inefficient, especially for nested `jsonb` since we currently have to allocate a new `JsonbArray` for the intermediate accessing result.

It'll be better if we can be more flexible on parsing these "strings containing JSON" so that users can specify these nested fields seamlessly just as usual.

There's a [`serde_with::json::JsonString`](https://docs.rs/serde_with/latest/serde_with/json/struct.JsonString.html) which has a similar idea to this.

**Comment by BugenZhao** [comment]
cc @tabVersion @st1page @neverchanje Would appreciate your ideas.

**Comment by st1page** [comment]
when we have a clear datatype hint for the field, it is easier. I think we can support it first :thinking: 
```json
{
  "nested": "{\"v1\": 10, \"v2\": \"hello\"}"
}
```
```SQL
CREATE SOURCE s(nested: jsonb) FORMAT plain ENCODE json;
CREATE SOURCE s(nested: STRUCT<v1 INT, v2 INT>) FORMAT plain ENCODE json;
```
But It is difficult to decide a field is a json object or string without datatype hint
```json
{
  "nested": {
    "nestednested": "{\"v1\": 10, \"v2\": \"hello\"}"
  }
}
```
```SQL
CREATE SOURCE s(nested: jsonb) FORMAT plain ENCODE json;
```

**Comment by BugenZhao** [comment]
> But It is difficult to decide a field is a json object or string without datatype hint

Yeah. In this approach, there's nothing to do with `JSONB`. Users still annotate the value with `struct` type and we can do this automatically for them _as if_ there's a nested object.
