### ISSUE TITLE
Make frontend compute runtime configurable.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#10782]
In #10733 we added a compute runtime in the frontend for compute-intensive tasks to avoid block io threads, we should make it configuration, e.g. the number of worker threads, etc.

**Comment by fuyufjh** [comment]
Hi, any updates?

**Comment by liurenjie1024** [comment]
Not yet, I'll make it good first issue.

**Comment by yufansong** [comment]
If we want to make it configurable, should we add a parameter at here? 
https://github.com/risingwavelabs/risingwave/blob/9162478ffa642825f4c6981ea11bf84403b22c75/src/common/src/config.rs#L136

If yes, I can help to add it.

**Comment by liurenjie1024** [comment]
> If we want to make it configurable, should we add a parameter at here?
> 
> https://github.com/risingwavelabs/risingwave/blob/9162478ffa642825f4c6981ea11bf84403b22c75/src/common/src/config.rs#L136
> 
> If yes, I can help to add it.

Yes, thanks!
