### ISSUE TITLE
Provide an option to print SQL logs to stdout

### ISSUE THREAD

**Issue by arkbriar** [risingwavelabs/risingwave#10793]
### Is your feature request related to a problem? Please describe.

For now, the SQL logs are redirected to a separate file, which is controlled by the `RW_QUERY_LOG_PATH` option. It makes things easier when someone wants to review the executed SQL by simply searching through the file. But there are two problems in a Kubernetes deployment:

1. In order not to fully occupy the disk, it's commonly agreed that logs of long running services need to be rotated regularly. SQL logs are also in this case. This requires us to either implement the rotating in our program, or adopt another services to rotate it regularly, i.e., additional efforts to support.
2. Log collection wouldn't be trivial when logs are in a file. 

### Describe the solution you'd like

For the reasons above, I think it would be better to have SQL logs printed to stdout so that we can leverage the existing solutions to support both rotating and collection. Despite of the mixed format, it's quite easy to separate the SQL logs by prefix matching. 

Regarding implementation, we can make it an option: either log to file or stdout.

### Additional context

cc. @Nebulazhang

**Comment by BugenZhao** [comment]
Just FYI, we’ve also included the SQL statement in the tracing span of the frontend handler. If we are going to enable tracing in production, not sure whether it’s somehow duplicate with the query log. Note that the tracing span contains much more information than a pair of `start` and `complete` logs. 🤔️

**Comment by arkbriar** [comment]
> Just FYI, we’ve also included the SQL statement in the tracing span of the frontend handler. If we are going to enable tracing in production, not sure whether it’s somehow duplicate with the query log. Note that the tracing span contains much more information than a pair of `start` and `complete` logs. 🤔️

Thanks for the notice. I think it doesn't matter unless it shares the same pattern with the normal SQL logs.

**Comment by xxchan** [comment]
It's already possible via 
```
RUST_LOG="pgwire_query_log=info" risingwave playground
```

**Comment by xxchan** [comment]
BTW, this also reminds me of the problem that we create `slow_query.log` under no condition (not sure why cc @lmatz), and may cause some friction.

https://risingwave-community.slack.com/archives/C03BW71523T/p1687369224584299

**Comment by arkbriar** [comment]
> It's already possible via
> 
> ```
> RUST_LOG="pgwire_query_log=info" risingwave playground
> ```
> 
> since it's just a normal tracing event now 🤪

Sounds good! cc. @Nebulazhang PTAL to see if there's a way to match the SQL logs.

**Comment by fuyufjh** [comment]
Closed according to https://github.com/risingwavelabs/risingwave/issues/10793#issuecomment-1625205763
