### ISSUE TITLE
PG char type padded with spaces via debezium json

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#10803]
### Describe the bug

PG Table:
```sql
CREATE TABLE IF NOT EXISTS nation (
    N_NATIONKEY BIGINT NOT NULL,
    N_NAME CHAR(25) NOT NULL,
    N_REGIONKEY BIGINT NOT NULL,
    N_COMMENT VARCHAR(152),
    PRIMARY KEY (N_NATIONKEY)
)
```

Source Table:
```sql
create table nation (
      N_NATIONKEY BIGINT,
      N_NAME VARCHAR,
      N_REGIONKEY BIGINT,
      N_COMMENT VARCHAR,
      PRIMARY KEY (N_NATIONKEY)
    )
    with (
      connector = 'kafka',
      topic = 'postgres.public.nation',
      kafka.brokers = '${BENCHMARK_KAFKA_NAME}.${BENCHMARK_NAMESPACE}:9092',
      scan.startup.mode = 'earliest'
    ) row format debezium_json;
```

We can verify it's been padded by the following SQL:
```sql
dev=> select count(1) from nation where n_name in ('CHINA                    ');
 count
-------
     1
(1 row)
```

<img width="551" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/34391b72-488c-4166-81e2-a2e79eb2fa31">

**Comment by lmatz** [comment]
Because RW does not have char, both char and varchar means varchar. How about using varchar also in the PG table?

**Comment by cyliu0** [comment]
> Because RW does not have char, both char and varchar means varchar. How about using varchar also in the PG table?

Yeah, of course we can do this in the ch benchmark test. But this product behavior is still a data consistency issue.

**Comment by fuyufjh** [comment]
+1 for "using varchar also in the PG table"

> But this product behavior is still a data consistency issue.

Not a big deal. We can mark it on documents if necessary

**Comment by cyliu0** [comment]
> +1 for "using varchar also in the PG table"

Need to modify the go-tpc to change the DDLs inside.

> 
> > But this product behavior is still a data consistency issue.
> 
> Not a big deal. We can mark it on documents if necessary

Is it possible to raise an error for the char type when creating a source? Now it's like an issue you can only realize when you hit it already.

**Comment by lmatz** [comment]
feeling `error` is not necessary. 
Padding on the RW side is the best way in the long term. DBZ must have this information.
So no extra learning curve for users.

**Comment by cyliu0** [comment]
Converting the char types to varchar. https://github.com/risingwavelabs/go-tpc/pull/10 @lmatz @fuyufjh

**Comment by fuyufjh** [comment]
As discussed above, we'll use `varchar` instead.
