### ISSUE TITLE
Support DATETIME type

### ISSUE THREAD

**Issue by jiacheng-celonis** [risingwavelabs/risingwave#10806]
### Is your feature request related to a problem? Please describe.

I need to maintain a materialized view whose output column type is a DATETIME type.

A simple repro. `KDATB` is a DATE type.

```
dev=> create materialized view test_datetime as select CAST(KDATB AS DATETIME) from "EKKO";
ERROR:  QueryError: Bind error: failed to bind expression: CAST(KDATB AS DATETIME)

Caused by:
  Feature is not yet implemented: unsupported data type: DATETIME
```

**Comment by fuyufjh** [comment]
Yes, there is no `DATETIME` in PostgresQL. 

But we may improve the error message, which seems to imply a missing feature rather than wrong usage.

```
Caused by:
  Feature is not yet implemented: unsupported data type: DATETIME
```

Postgres:

```
test=# create table t_datetime (v datetime);
ERROR:  type "datetime" does not exist
LINE 1: create table t_datetime (v datetime);
                                   ^
test=#
```

**Comment by jiacheng-celonis** [comment]
Changing to TIMESTAMP works.

The error message could be improved.

Closing this FR. Feel free to follow up on the error message.
