### ISSUE TITLE
Scheduler error: Serving vnode mapping not found for fragment

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#10808]
### Describe the bug

Occurrences:
https://buildkite.com/risingwavelabs/main/builds/4811#01892ccb-edd8-43ff-a53a-3a5cff083109
https://buildkite.com/risingwavelabs/main/builds/4807#01892aaa-5fe8-4e58-8af0-0528177bff49
https://buildkite.com/risingwavelabs/main/builds/4797#0189294c-8d93-4a87-bee3-ecf7e956f037
https://buildkite.com/risingwavelabs/main/builds/4794#01892563-e2ae-4bab-b3d6-1fcfcae72de0

Basic observations:
* part of `end-to-end test (parallel) (dev mode)`
* always in file `e2e_test/visibility_mode/../batch/./basic/table_with_default_columns.slt.part`
* may fail on line 37 or 56
* may fail in local mode or distributed mode

@zwang28 Do you have any clue on this?

**Comment by zwang28** [comment]
Seems it appear after #9762. Investigating.
