### ISSUE TITLE
`pg_relation_size()` not working

### ISSUE THREAD

**Issue by abhyuday26** [risingwavelabs/risingwave#10816]
### Describe the bug

As per #9013, All the Size of Object Functions (`pg_table_size`, `pg_relation_size`, `pg_indexes_size`) should have worked but pg_relation size is not working

### Error message/log

```text
ERROR:  QueryError: Bind error: failed to bind expression: pg_relation_size('employees')

Caused by:
  Feature is not yet implemented: unsupported function: "pg_relation_size"
```

### To Reproduce

CREATE TABLE employees (
    name VARCHAR,
    age INT,
    salary INT
);
INSERT INTO employees (name, age, salary)
VALUES ('John Doe', 30, 50000),
       ('Jane Smith', 35, 60000),
       ('Mark Johnson', 28, 45000);
SELECT pg_relation_size('employees');

### Expected behavior

 pg_relation_size 
------------------
             8192

### The version of RisingWave

                                     version                                      
----------------------------------------------------------------------------------
 PostgreSQL 8.3-RisingWave-1.0.0-alpha (f8b2849a2e1cfb4cf34c3ff71c0d39292e49ac62)

**Comment by lmatz** [comment]
As specified by https://www.postgresql.org/docs/9.4/functions-admin.html


> pg_total_relation_size accepts the OID or name of a table or toast table, and returns the total on-disk space used for that table, including all associated indexes. This function is equivalent to pg_table_size + pg_indexes_size.



> pg_table_size accepts the OID or name of a table and returns the disk space needed for that table, exclusive of indexes. (TOAST space, free space map, and visibility map are included.)



> pg_indexes_size accepts the OID or name of a table and returns the total disk space used by all the indexes attached to that table.


> pg_database_size and pg_tablespace_size accept the OID or name of a database or tablespace, and return the total disk space used therein. To use pg_database_size, you must have CONNECT permission on the specified database (which is granted by default). To use pg_tablespace_size, you must have CREATE permission on the specified tablespace, unless it is the default tablespace for the current database.


> pg_relation_size accepts the OID or name of a table, index or toast table, and returns the on-disk size in bytes of one fork of that relation. (Note that for most purposes it is more convenient to use the higher-level functions 


> pg_total_relation_size or pg_table_size, which sum the sizes of all forks.) With one argument, it returns the size of the main data fork of the relation. The second argument can be provided to specify which fork to examine:
    'main' returns the size of the main data fork of the relation.
    'fsm' returns the size of the Free Space Map (see [Section 59.3](https://www.postgresql.org/docs/9.4/storage-fsm.html)) associated with the relation.
    'vm' returns the size of the Visibility Map (see [Section 59.4](https://www.postgresql.org/docs/9.4/storage-vm.html)) associated with the relation.
    'init' returns the size of the initialization fork, if any, associated with the relation.

**Comment by hzxa21** [comment]
> As specified by https://www.postgresql.org/docs/9.4/functions-admin.html
> 
> > pg_total_relation_size accepts the OID or name of a table or toast table, and returns the total on-disk space used for that table, including all associated indexes. This function is equivalent to pg_table_size + pg_indexes_size.
> 
> > pg_table_size accepts the OID or name of a table and returns the disk space needed for that table, exclusive of indexes. (TOAST space, free space map, and visibility map are included.)
> 
> > pg_indexes_size accepts the OID or name of a table and returns the total disk space used by all the indexes attached to that table.
> 
> > pg_database_size and pg_tablespace_size accept the OID or name of a database or tablespace, and return the total disk space used therein. To use pg_database_size, you must have CONNECT permission on the specified database (which is granted by default). To use pg_tablespace_size, you must have CREATE permission on the specified tablespace, unless it is the default tablespace for the current database.
> 
> > pg_relation_size accepts the OID or name of a table, index or toast table, and returns the on-disk size in bytes of one fork of that relation. (Note that for most purposes it is more convenient to use the higher-level functions
> 
> > pg_total_relation_size or pg_table_size, which sum the sizes of all forks.) With one argument, it returns the size of the main data fork of the relation. The second argument can be provided to specify which fork to examine:
> > 'main' returns the size of the main data fork of the relation.
> > 'fsm' returns the size of the Free Space Map (see [Section 59.3](https://www.postgresql.org/docs/9.4/storage-fsm.html)) associated with the relation.
> > 'vm' returns the size of the Visibility Map (see [Section 59.4](https://www.postgresql.org/docs/9.4/storage-vm.html)) associated with the relation.
> > 'init' returns the size of the initialization fork, if any, associated with the relation.
> 
> It seems RW does not have the concept of `main`, `fsm`, `vm` and `init`.

I think we can use the table size as the output of `pg_relation_size(xxx)` and `pg_relation_size(xxx, 'main')`. For `fsm`, `vm`, `init`, we can leave them empty. Anyway, this should not block the release.

**Comment by fuyufjh** [comment]
We can close this after completing the case of `main`
