### ISSUE TITLE
optimizer: Common Sub-Expression (CSE)

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#10812]
Common Sub-Expression (CSE) optimization is a common optimization technique in query execution optimization.

In our usecase, it's very useful to extract the unnecessary duplicated `cast(varchar) -> jsonb`.

CSE is the reverse process of ProjectMerge, and we need to consider their conflicts.

**Comment by xxchan** [comment]
Just a note: for CSE we need to consider purity 🤪 https://github.com/risingwavelabs/risingwave/issues/9030.
