### ISSUE TITLE
panic when counting a jsonb value

### ISSUE THREAD

**Issue by docteurklein** [risingwavelabs/risingwave#10838]
### Describe the bug

Hey there, had to observe the logs to understand that I can't count a jsonb value. In the meantime I can `count(*)`, but not `count(pv.*)`, `pv` being an alias for a mat view.

### Error message/log

```text
thread 'thread 'risingwave-streaming-actor' panicked at 'streaming agg state not implemented: Count
Jsonb Int64', src/stream/src/executor/aggregation/agg_impl/mod.rs:157:13
```

### To Reproduce

everything is reproducible at https://github.com/docteurklein/risingwave-demo

```sql
create schema pim1;

create table pim1.product (
  uuid bytea,
  family_id int,
  product_model_id int,
  family_variant_id int,
  id int,
  is_enabled bool,
  identifier text,
  raw_values jsonb,
  created timestamptz,
  updated timestamptz,
  quantified_associations jsonb,
  primary key (uuid)
) with (
 connector = 'mysql-cdc',
 hostname = 'mysql',
 port = '3306',
 username = 'root',
 password = 'root',
 database.name = 'pim1',
 table.name = 'pim_catalog_product',
 server.id = '1'
);

drop sink if exists product_stats;
drop materialized view if exists pim1.product_value;

create materialized view pim1.product_value as
  with by_raw_value (product_id, rest) as (
    select id, jsonb_each(raw_values) from pim1.product
  ),
  by_attr (product_id, attribute, rest) as (
    select product_id, (rest).key, jsonb_each((rest).value)
    from by_raw_value
  ),
  by_channel (product_id, attribute, channel, rest) as (
    select product_id, attribute, nullif((rest).key, '<all_channels>'), jsonb_each((rest).value)
    from by_attr
  ),
  by_locale (product_id, attribute, channel, locale, value) as (
    select product_id, attribute, channel, nullif((rest).key, '<all_locales>'), (rest).value
    from by_channel
  )
  select * from by_locale
;

create sink product_stats as
select coalesce(p.family_id, 0) family, count(*) as num_values
from pim1.product_value pv
inner join pim1.product p on (pv.product_id = p.id)
group by 1
with (
    connector='jdbc',
    jdbc.url='jdbc:mysql://mysql:3306/pim1?user=root&password=root',
    table.name='product_stats',
    type='upsert'
);

```

### Expected behavior

I expected a better error message, and optionaly to be able to do that like in postgres.

### How did you deploy RisingWave?

using docker-compose but with a single `playground` service`

### The version of RisingWave

select version(); -- PostgreSQL 8.3-RisingWave-1.0.0-alpha (2b6d7d65d05012d96b1636ffea636ef725a8fb84)
docker image: risingwavelabs/risingwave:nightly-20230709

**Comment by xiangjinwu** [comment]
Thanks for the bug report!

Regarding the panic on `count(jsonb)` in streaming (mat view), it would not be an issue after the refactor mentioned in https://github.com/risingwavelabs/risingwave/pull/10752#issuecomment-1621139237 . But we can also do a quick fix.

As for `count(pv.*)`, it is [equivalent](https://www.postgresql.org/docs/15/rowtypes.html#:~:text=does%20not%20change%20the%20value) to `count(pv)` and we would enhance our support as part of #9694. Before that you can use `count(*)` as long as there are no outer joins.

**Comment by xiangjinwu** [comment]
`count(jsonb)` in streaming has been fixed. `count(pv.*)` in outer join will be tracked by #10847
