### ISSUE TITLE
Investigate performance regression of json parser

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#10840]
*Originally from slack:*
> Fyi seems like json micro-bench recently regress on 15th june 2023. Execution duration jumped from ~450M ns to ~600M ns.
Maybe can take a look at the PRs merged then. https://github.com/risingwavelabs/risingwave/pulls?q=is%3Apr+merged%3A2023-06-14..2023-06-15+is%3Aclosed

![image](https://github.com/risingwavelabs/risingwave/assets/47273164/f0f94dc7-e9e1-497a-9d03-2275fc475995)

> @tabVersion I think it might be https://github.com/risingwavelabs/risingwave/pull/10096

**Comment by BugenZhao** [comment]
May worth checking https://github.com/risingwavelabs/risingwave/pull/10096.

**Comment by lmatz** [comment]
Suspect some unnecessary `clone` `copy` is introduced...

**Comment by lmatz** [comment]
![SCR-20230710-ny1](https://github.com/risingwavelabs/risingwave/assets/5791930/40956672-d79a-4b2c-a1af-fdf821628aee)
using flame graph from q0: https://buildkite.com/risingwavelabs/cpu-flamegraph-weekly-cron/builds/18#_

**Comment by lmatz** [comment]
https://github.com/risingwavelabs/risingwave/pull/10919

We also need to track other parser...

**Comment by kwannoel** [comment]
> #10919
> 
> We also need to track other parser...

Good point. Opened a separate issue for it.

**Comment by kwannoel** [comment]
Btw after https://github.com/risingwavelabs/risingwave/pull/10971

It seems like another introduced cost is from `catch_unwind`.
The flamegraph does not provide sufficient information on the source of `catch_unwind` however. Not too sure how to identify the underlying cost.

Before:
<img width="852" alt="Screenshot 2023-07-17 at 2 48 14 PM" src="https://github.com/risingwavelabs/risingwave/assets/47273164/dabee37e-64a4-4dce-94df-833aa2f4be01">


Current cost:
<img width="852" alt="Screenshot 2023-07-17 at 2 47 46 PM" src="https://github.com/risingwavelabs/risingwave/assets/47273164/31cb5e3b-7b69-442b-a4df-c3e404f5b3b8">

**Comment by kwannoel** [comment]
q0 shows it's more or less back to normal.
