### ISSUE TITLE
feat: test and document `distinct on ... [group by] ... [order by]` under EOWC

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#10859]
### Is your feature request related to a problem? Please describe.

It is used to order the events (by group keys, optionally) and output the first one (ordering by given timestamp column)

Corresponds to [Deduplication in Flink](https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/dev/table/sql/queries/deduplication/)

**Comment by TennyZhuang** [comment]
The behavior is implemented, I'll create an issue in doc team.
