### ISSUE TITLE
Flamegraph generation for microbenchmarks

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#10863]
Easier to debug perf issues.
- [x] ~Write some script / tool to easily gen flamegraph on linux machines.~ No need just use `cargo-flamegraph`.
- [x] Write some docs on how to setup the machine for it on ec2.
- [x] ~Write some docs on how to setup the script.~
- [ ] Create some workflow where users can trigger it adhoc.

**Comment by BugenZhao** [comment]
I'm not sure if profiling a process hurts the performance. If so, we need a separate run to obtain accurate results.

**Comment by kwannoel** [comment]
Workflow will take more time. I think it is easy enough to run it in ec2. Leave it for future work.
