### ISSUE TITLE
bug(oom): rdkafka uses too much memory

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#10888]
### Describe the bug

https://buildkite.com/risingwave-test/longevity-kubebench/builds/429#0188fb4e-838b-45f3-85ad-ae0b0e6f9277

**Comment by fuyufjh** [comment]
Reproduced with MemTable statistics. Seems that MemTable is not the cause.

<img width="949" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/b28edcfa-550f-4f19-9e2c-662abce31812">

<img width="943" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/f1f6896c-4f4a-400a-af2e-8afe733eed60">

[Grafana Link](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=now-1h&orgId=1%5Cu0026var-datasource%3DPrometheus:%20test-useast1-eks-a&to=now&var-namespace=usrlngvty-20230720-072327&var-datasource=Prometheus:%20test-useast1-eks-a&var-instance=benchmark-risingwave&var-node=10.0.46.161:1222&var-job=All&var-table=All)

**Comment by fuyufjh** [comment]
`rdkafka` takes so much memory? 

<img width="917" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/16b72102-fcaa-49c6-b255-8b967f9a63a4">

[cn.1.15.i15_04-47-01.heap.collapsed.zip](https://github.com/risingwavelabs/risingwave/files/12116436/cn.1.15.i15_04-47-01.heap.collapsed.zip)

**Comment by fuyufjh** [comment]
After I tweaked some [rd_kafka parameters](https://github.com/risingwavelabs/risingwave/compare/f7af1e..fa08be), the memory usage became quite stable:

<img width="947" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/c6f9084b-30bf-4ffd-9252-bd005a135bf2">

(However, another bug #11170 came out... 🤣)

I am going to make it configurable in production.

**Comment by fuyufjh** [comment]
Let me explain the problem and solution here.

The problem was discussed in https://github.com/confluentinc/librdkafka/issues/2076. In short, `rdkafka` keep the buffered messages in fetchq (fetch queue) more than `queued.min.messages`, while during this, the memory usage explodes.

I tried to [decrease the `queued.min.messages` to 1/5 of default value](https://github.com/risingwavelabs/risingwave/compare/d1342e5..97caa05) but that reduced the performance drastically (basically 1/5). 

I have a few ideas to continue the tweak, but that would be very time-consuming. Better to do it after we have statistics (#11187). For now, if users encounter this issue, they may use https://github.com/risingwavelabs/risingwave/pull/11203 as a work-around.

**Comment by tabVersion** [comment]
since https://github.com/risingwavelabs/risingwave/pull/11273 is merged, let's see if it helps

**Comment by fuyufjh** [comment]
> since #11273 is merged, let's see if it helps

Reran here: https://buildkite.com/risingwave-test/longevity-kubebench/builds/542

**Comment by fuyufjh** [comment]
During the last test, it seems that CN can run without OOM, so let me close this for now. 

https://buildkite.com/risingwave-test/longevity-kubebench/builds/550
