### ISSUE TITLE
compute node OOM while create ch benchmark q3 with 100 warehouses

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#10899]
### Describe the bug

<img width="429" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/cdc7fab1-1476-49b8-8169-73f6892afea3">

The environment is still alive on the test k8s test-useast1-eks-a. The namespace is `ch-pipeline-test`.

ch benchmark q3:
```
create materialized view ch_benchmark_q3
    as
    select   ol_o_id, ol_w_id, ol_d_id,
             sum(ol_amount) as revenue, o_entry_d
    from 	 customer, new_order, orders, order_line
    where 	 
      -- c_state like 'a%' and
      c_id = o_c_id
      and c_w_id = o_w_id
      and c_d_id = o_d_id
      and no_w_id = o_w_id
      and no_d_id = o_d_id
      and no_o_id = o_id
      and ol_w_id = o_w_id
      and ol_d_id = o_d_id
      and ol_o_id = o_id
      and o_entry_d > '2007-01-02 00:00:00.000000'
    group by ol_o_id, ol_w_id, ol_d_id, o_entry_d
```

log: https://grafana.test.risingwave-cloud.xyz/d/liz0yRCZz1/log-search-dashboard?orgId=1&var-data_source=Logging:%20test-useast1-eks-a&from=1689126840000&to=1689128453000&var-namespace=ch-pipeline-test&var-pod=benchmark-risingwave-compute-c-0&var-search=
grafana: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1689126840000&orgId=1%5Cu0026var-datasource%3DPrometheus:%20test-useast1-eks-a&to=1689128453000&var-namespace=ch-pipeline-test&var-datasource=Prometheus:%20test-useast1-eks-a&var-instance=benchmark-risingwave&var-node=All&var-job=All&var-table=All 

### Error message/log

```text
ERROR:  QueryError: internal error: failed to finish command: channel closed
ERROR:  QueryError: Catalog error: table or source not found: ch_benchmark_q3

ERROR:  QueryError: internal error: Service unavailable: The cluster is starting or recovering
ERROR:  QueryError: Catalog error: table or source not found: ch_benchmark_q4
```

### To Reproduce

Run ch-benchmark with

```
BENCH_NAMESPACE="ch-100-warehouses"
BENCH_SKU="medium"
CH_BENCHMARK_QUERY="q3"
CH_BENCHMARK_WAREHOUSES="100"
CH_BENCHMARK_THREADS="4"
RW_CNS="1"
RW_VERSION="<put your image tag>"
SKIP_DASHBOARD="true"
ENABLE_PG_SINKS=true
QUERY_RUNTIME=60
```

### The version of RisingWave

v1.0-rc1

**Comment by fuyufjh** [comment]
Hi, I ran the test again yesterday and it seemed to work as expected.

<img width="950" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/661a28ec-0e6f-45ef-ae49-9b964c6cd030">

Previously I thought the curve is abnormal, but later I realized that this is exactly how our Memory Manager work.

```	
2023-07-26T13:07:53.152641974Z  INFO risingwave_compute::server: 
Memory outline:
> total_memory: 16.00 GiB
>     storage_memory: 5.12 GiB
>         block_cache_capacity: 1.54 GiB
>         meta_cache_capacity: 1.79 GiB
>         shared_buffer_capacity: 1.54 GiB
>         file_cache_total_buffer_capacity: 262.00 MiB
>         compactor_memory_limit: Not enabled
>     compute_memory: 7.68 GiB
>     reserved_memory: 3.20 GiB

2023-07-26T13:07:53.175612411Z  INFO risingwave_compute::memory_management::memory_manager: memory control policy:
JemallocMemoryControl { threshold_stable: 9620726742, threshold_graceful: 10995116277, threshold_aggressive: 12369505812 }
```

In short, it 

- Do no eviction before `threshold_stable`
- Do eviction between `threshold_stable` and `threshold_graceful` by incresing LRU watermark constantly 1 second per second
- Do aggressive eviction after `threshold_graceful` by incresing LRU watermark 2,3,4,5 seconds ... per second
- Do even more aggressive eviction after `threshold_aggressive` by incresing LRU watermark 2,4,8,16 seconds ... per second

And, as we know the LRU watermark has somewhat latency, it results in

<img width="1898" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/ba7c08a9-c043-4701-8911-2ff863664a7e">



Grafana: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=ch-100-warehouses&var-instance=risingwave&var-node=All&var-job=All&var-table=All&from=1690377461751&to=1690377839170

**Comment by fuyufjh** [comment]
Perhaps we can reduce the fluctuation by adding more space between `threshold_aggressive` and `threshold_graceful`, because the *double-steps-if-not-work* policy seems to be too aggressive and often results in cleaning all the caches.

Propose:

```diff
+   const THRESHOLD_AGGRESSIVE: f64 = 0.95;
-   const THRESHOLD_AGGRESSIVE: f64 = 0.9;
    const THRESHOLD_GRACEFUL: f64 = 0.8;
    const THRESHOLD_STABLE: f64 = 0.7;
```

What do you think of it? @yuhao-su @TennyZhuang

**Comment by yuhao-su** [comment]
I'm not quite sure whether this change can help. Reaching `THRESHOLD_AGGRESSIVE ` can be caused by some memory usage from components other than operator cache. Maybe wait for our memory profile result (coming soon)?

**Comment by fuyufjh** [comment]
No, I've got a memory profiling yesterday.




[cn.1.0.i0.heap.collapsed.zip](https://github.com/risingwavelabs/risingwave/files/12181365/cn.1.0.i0.heap.collapsed.zip) (Not perfectly before OOM, but still makes some sense.)





<img width="1920" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/685b4f68-155b-48f7-97b2-92c1f9397e0d">

**Comment by fuyufjh** [comment]
> Perhaps we can reduce the fluctuation by adding more space between `threshold_aggressive` and `threshold_graceful`, because the _double-steps-if-not-work_ policy seems to be too aggressive and often results in cleaning all the caches.
> 
> Propose:
> 
> ```diff
> +   const THRESHOLD_AGGRESSIVE: f64 = 0.95;
> -   const THRESHOLD_AGGRESSIVE: f64 = 0.9;
>     const THRESHOLD_GRACEFUL: f64 = 0.8;
>     const THRESHOLD_STABLE: f64 = 0.7;
> ```

Anyway, since currently the Q3 did not OOM (the highest memory usage is around 12 GB, which is under the total_memory=16GB), I tend to keep it as is now.
