### ISSUE TITLE
make playground mode's meta and storage durable

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#10908]
And run longevity test for it.

**Comment by fuyufjh** [comment]
Background: it's for single node deployment. Eventually, we hope to provide a way for users to run RisingWave in a single binary.

**Comment by xxchan** [comment]
btw, we might need a better name for that instead of playground, e.g., monolithic mode. (I found loki has the term https://grafana.com/docs/loki/latest/fundamentals/architecture/deployment-modes/#monolithic-mode)

**Comment by lmatz** [comment]
How about going through `risedev` and enhance it? just like `tiup`.

IIRC, we didn't make `risedev` a `tiup` because of commercialization purposes, i.e. discourage production deployment via binary(source build).

**Comment by xxchan** [comment]
Btw, isn’t etcd an overkill for single node deployment? 😢

**Comment by fuyufjh** [comment]
> What do you plan to do with etcd? I recall we once tried sled but soon abandoned the implementation.

Yes, sled performs worse and I guess the current interface is not comptaible with it any more.

> I discussed it with @skyzh in the early days and he thought that risedev was designed for developement purposes only. 🐶 Perhaps we need a new tool.

Agree. I remember that we have `risingwave playground` (not `risedev playground`), [entrance here](https://github.com/risingwavelabs/risingwave/blob/d32bf13adea25e6ea1ba953c8e9d9f610e99f7dd/src/cmd_all/src/bin/risingwave.rs#L191). It does not depend on risedev.

**Comment by BugenZhao** [comment]
> It does not depend on risedev.

Yes. `risedev playground` is simply an alias of `cargo run --bin risingwave -- playground`.

**Comment by lmatz** [comment]
![SCR-20230720-h4p](https://github.com/risingwavelabs/risingwave/assets/5791930/bdc6a497-d19b-45ca-83bc-cef477773eb9)

not necessarily `risedev` I agree, 
the point is that it is better if the user only needs to know and learn one tool, i.e. downloaded once and all functions and including documentation just in one place.


![SCR-20230720-i59](https://github.com/risingwavelabs/risingwave/assets/5791930/dfc5bfc7-6e12-44a1-acd3-e87caf72ef26)

`risectl` is a tool that we use to operate an existing cluster, debug or even manually get the cluster out of some abnormal behaviors. We can make it the name of a tool that can do all sorts of things, or it becomes a component under a larger tool/name, like `tiup`.


And since `playground` is no longer considered a mere playground any more and is considered a more serious deployment that can work for production,
I imagine there will be more tools such as the components in `tiup` figure that do a lot of other stuff that we haven't done.

From this point of view, `risedev` for deployment also looks like a component of a bigger name for the sake's `all-in-one`.

**Comment by BugenZhao** [comment]
> `risectl` is a tool that we use to operate an existing cluster, debug or even manually get the cluster out of some abnormal behaviors. We can make it the name of a tool that can do all sorts of things, or it becomes a component under a larger tool/name, like `tiup`.

I don't think so. 😕 There's also `tidb-ctl` and `tikv-ctl`. It's not intended to be used as a deployment tool.

- https://github.com/pingcap/tidb-ctl
- https://github.com/tikv/tikv/tree/master/cmd/tikv-ctl

**Comment by xxchan** [comment]
But it seems redpanda’s rpk is deployment + operate
https://docs.redpanda.com/docs/reference/rpk/

**Comment by kwannoel** [comment]
Left longevity test.
