### ISSUE TITLE
udf: provide vectorized API in Python UDF

### ISSUE THREAD

**Issue by wangrunji0408** [risingwavelabs/risingwave#10916]
### Is your feature request related to a problem? Please describe.

Currently we only expose a scalar API (a row at a time) to users for simplicity. But its performance would be much lower than vectorization. We should also provide a vectorized API (a chunk at a time) for cases where users care more about performance. This should not be hard because it is already vectorized at the RPC level. 

### Additional context

https://nightlies.apache.org/flink/flink-docs-release-1.17/docs/dev/python/table/udfs/vectorized_python_udfs/
https://duckdb.org/2023/07/07/python-udf.html#built-in-python-vs-pyarrow shows the vectorized function is way faster than the scalar version.

**Comment by fuyufjh** [comment]
Vectorization only works for simple computations, which can be helpful for DuckDB in some cases (think about NumPy), but I can hardly imagine any meaningful cases for streaming. 👀

**Comment by wangrunji0408** [comment]
Reasonable. The cases I know so far are all too complex to use vectorization. Seems that we can pause this feature until we find a really useful case.
