### ISSUE TITLE
bug: e2e read_only_multi_conn.slt fails

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#10928]
### Describe the bug

https://buildkite.com/risingwavelabs/pull-request/builds/27263#01894d6f-30b2-4f16-a265-5c223519d0e7

\| e2e_test/visibility_mode/../batch/transaction/read_only_multi_conn.slt .. [FAILED]
  |  
  | failed to run `e2e_test/visibility_mode/barrier.slt`
  |  
  | Caused by:
  | query result mismatch:
  | [SQL] select count(*) from t;
  | [Diff] (-expected\|+actual)
  | -   2
  | +   0
  | at e2e_test/visibility_mode/../batch/transaction/read_only_multi_conn.slt:19
  | at e2e_test/visibility_mode/barrier.slt:4
 

<br class="Apple-interchange-newline">

**Comment by chenzl25** [comment]
cc @BugenZhao

**Comment by BugenZhao** [comment]
In parallel mode, we have multiple frontends so the connection `other` may randomly choose a different frontend to connect to. In this case, we cannot ensure the snapshot from the default connection has been synchronized to the `other`. Luckily, `FLUSH` is always done with a checkpoint barrier, so maybe we can call `FLUSH` before `select`ing in the `other` connection.

**Comment by BugenZhao** [comment]
This reminds me that in the worst case, we can even get the `table not found` error from the `other` connection as the catalog subscription is also asynchronous. This can be resolved after the changes in https://github.com/risingwavelabs/risingwave/pull/10874/files#diff-c3dc8f0f19bfa874cc5175ca189e6d8458b5c582f6890bb83a9e1f820a60ac51, as we will then **wait** for the notification to be applied, where the linearizability of the observer queue ensures the order.
