### ISSUE TITLE
optimizer: plans for CH-benCHmark is not stable

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#10934]
<img width="1999" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/25862682/de130cf4-f2d2-426c-9f3a-e9c9bc66a304">

This causes the unit tests in our CI flaky. cc @lmatz 

- https://buildkite.com/risingwavelabs/pull-request/builds/27290
- https://buildkite.com/risingwavelabs/pull-request/builds/27286

**Comment by BugenZhao** [comment]
link #10927

**Comment by lmatz** [comment]
Does it mean that the join ordering is non-deterministic?

**Comment by BugenZhao** [comment]
> Does it mean that the join ordering is non-deterministic?

I guess so but not that sure. Need help from optimizer experts: do we utilize something like `HashMap::iter` that is indeterministic during the optimization? cc @st1page @chenzl25

**Comment by chenzl25** [comment]
It seems this rule `LeftDeepTreeJoinOrderingRule` is not deterministic.
