### ISSUE TITLE
storage: estimated_size of SstableMeta is too small

### ISSUE THREAD

**Issue by Little-Wallace** [risingwavelabs/risingwave#10973]
### Describe the bug

The type of `SstableMeta::estimated_size` is `u32`. 

But if there are several version of one large key-value (for example, each of version has a 10MB, and there are 400 versions of one user-key), we can not cut them by `target_file_size_base`.
If the size of this file exceed u32::MAX, it would cause a number-overflow bug.

**Comment by hzxa21** [comment]
cc @Little-Wallace  Is this fixed?

**Comment by hzxa21** [comment]
Fixed by #11734. Now we have decieded that we should panic on u32 overflow. In other words, it is invalid to have SST larger than 4GB.
