### ISSUE TITLE
Test other components that relying on S3-compatible storage

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#10995]
- S3 source
- Java connector 

Already mentioned in https://github.com/risingwavelabs/risingwave/issues/8266.

For storage, I guess it generally works, and we just want to test maturity https://github.com/risingwavelabs/risingwave-test/issues/285. 

But I guess other components are not tested yet, as it's not functional, e.g., https://github.com/risingwavelabs/risingwave/issues/10994.

Note that now each component has it own logic of AWS config handling, and they are inconsistent. This might be the root of the problems.

**Comment by fuyufjh** [comment]
This is a reminder from the past. Can you please help with this once S3 source & sink completed? cc. @tabVersion @xiangjinwu
