### ISSUE TITLE
Optimize backfill snapshot read

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#11007]
Our backfill executor has two input streams. One is called snapshot read and the other one is called upstream read. Backfill executors always prefer the upstream read side. Whenever a barrier arrives, it will start a new snapshot read. There is an assumption right now which is the snapshot read side could read `chunk_size` data between two barriers. If this assumption is broken, no progress can proceed for the backfill. Our users have encountered this issue. A solution is to increase the barrier interval as a workaround, but the ideal solution is to refine the snapshot read. Even if the rows read between barriers are less than `chunk_size`, we should still send them downstream.

**Comment by StrikeW** [comment]
Add some explanations for the problem (credit from @kwannoel)

> There is an assumption right now which is the snapshot read side could read chunk_size data between two barriers. 

- Suppose there’s 1024 rows in object store ready to be read, but there’s some latency from object store.
- Then the stream will not end yet, but it will wait for the store to return the rows.
- The result is that snapshot chunk will not be returned yet.
- Concurrently, suppose there’s a barrier received.
- Now the stream will re-compute snapshot, losing any progress.
