### ISSUE TITLE
Describe the meaning of each setting in `pg_settings`

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#11014]
I agree that we need descriptions somewhere for these settings. But in order to reduce our efforts, I suggest documenting them through `pg_settings` https://www.postgresql.org/docs/current/view-pg-settings.html, which is the system table for all settings. @yezizp2012 There is a column named 'short_desc' that will provide users their meaning.

<img width="1499" alt="Screenshot 2023-07-18 at 16 08 03" src="https://github.com/risingwavelabs/risingwave-docs/assets/6970676/b72c3f79-f367-4987-9ca6-b2209db3a288">

https://crate.io/docs/crate/reference/en/5.3/config/session.html CrateDB indeeds maintain a doc. But not all databases did the same.

_Originally posted by @neverchanje in https://github.com/risingwavelabs/risingwave-docs/issues/1058#issuecomment-1639726394_

**Comment by yezizp2012** [comment]
Completed by #15108 .
