### ISSUE TITLE
support `client_min_messages`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#11048]
From community users, it is required by `pgAdmin` tool.
https://www.pgadmin.org/

https://postgresqlco.nf/doc/en/param/client_min_messages/

link #11014 

Need a new `ConfigEnum` type?

**Comment by lmatz** [comment]
cc: @abhyuday26 
once this is supported, the test for `pgAdmin` is able to continue

**Comment by fuyufjh** [comment]
@lmatz I guess we are going to make a mock version, right? Rather than actually affecting anything.

**Comment by lmatz** [comment]
Yes, just for the sake of running `pgAdmin`.

**Comment by xiangjinwu** [comment]
> I think this is a valid requirement. Could you help on this task? @xiangjinwu

When I get a chance. Guess it is not blocking anything right? Just a good-to-have if it is easy to achieve rather than requiring large refactors.
