### ISSUE TITLE
Clarify JSONB insert bug

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#11059]
### Describe the bug

```
drop table sales;
DROP_TABLE
dev=> create table sales (
    id integer primary key,
    info jsonb
);
CREATE_TABLE
dev=> insert into sales values (1, '{name: "Alice", paying: true, tags: ["admin"]}');
ERROR:  QueryError: Expr error: Parse error: key must be a string at line 1 column 2
```

I was a bit confused, because I thought the error referred to the key `id`. Could we maybe clarify this error so it reads `json key must be a string`? 

Correct insert would be 

```
insert into sales values (1, '{"name": "Alice", "paying": true, "tags": ["admin"]}');
```

### The version of RisingWave

On main branch on `6d1ed9ea6229494650b7d2d0b2a6d2f7b05d903f`

**Comment by xiangjinwu** [comment]
Sample solution here:
https://github.com/risingwavelabs/risingwave/compare/fix-11059-expr-parse-err?expand=1
```
dev=> insert into sales values (1, '{name: "Alice", paying: true, tags: ["admin"]}');
ERROR:  QueryError: Expr error: Parse error: risingwave_common::types::jsonb::JsonbVal key must be a string at line 1 column 2
```

The error message is from:
https://docs.rs/serde_json/1.0.107/src/serde_json/error.rs.html#371
We can append or prepend more context to it, but as of now accessing `DataType` in expr requires a trick https://github.com/risingwavelabs/risingwave/pull/10234#issuecomment-1582060669

If the `risingwave_common::types::jsonb::JsonbVal` from `type_name` looks good to you, feel free to open a PR on that branch.
