### ISSUE TITLE
bug: compactor generate a big sstable file with a lot of delete-range-tombstone

### ISSUE THREAD

**Issue by Little-Wallace** [risingwavelabs/risingwave#11085]
### Describe the bug

In some case, if watermark state does not insert any new data, it would still generate delete-range for every watermark. And a large number of range-tombstone all locate in one big sstable file because compactor-node does not cut them by size.

It would cause another problem that is the meta of this sstable file is also very large because all range-tombstones store in meta-block instead of data-block. So compute-node will evict this large file again and again because there is not enough meta-cache for it.

**Comment by Li0k** [comment]
After discussing this with wallace, we think we need to customize a tombstone selector, in which case we can push the sst to the last_level as far as possible and recycle it
I'll be tracking this requirement
