### ISSUE TITLE
Reached the max connections for PG sinks

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#11116]
### Describe the bug

When I try to create the 15th PG sink on RW, the meta log shows it hits the PG error `too many clients already`. By default, the PG max_connections is 100. RW will create a new connection for each concurrency of each sink. In my case, the concurrency might be 8. So I reached the limit when I try to create the 15th sink.

PG connections:
```
postgres=# SELECT application_name, count(1) as total FROM pg_stat_activity group by application_name order by total desc;
    application_name    | total
------------------------+-------
 PostgreSQL JDBC Driver |    98
                        |     5
 Debezium General       |     1
 psql                   |     1
 Debezium Streaming     |     1
(5 rows)
```

### Error message/log

```text
in risingwave_meta::barrier::failure_recovery with err: Rpc error: gRPC error (Internal error): Actor 1738 exit unexpectedly: Executor error: Sink error: Remote sink error: gRPC error (Internal error): Error when exec 53300, message FATAL: sorry, too many clients already
2:24
```

**Comment by fuyufjh** [comment]
Shall we allow users to configure the parallelism for a particular sink?

Or shall we support connection pool inside RW?

**Comment by StrikeW** [comment]
Use a connection pool in connector node may not work. Since each sink executor holds one jdbc connection for the whole time, it won't close the connection. I think we should suggest user configure the parallelism for sink and default to 1 parallelism if user doesn't specify explicitly.
