### ISSUE TITLE
config: override `actor_runtime_worker_threads_num` with `--parallelism`

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#11115]
Recently we found some users are deploying 2 compute nodes on an 8-core machine with each configured with `--parallelism 4`, and then expect each compute node to take no more than 400% CPU usage.

This is not true as the parallelism is a per-fragment concept, so the CPU usage is actually bounded by the number of threads. If `actor_runtime_worker_threads_num` is not set, tokio will determine this value based on the number of CPU cores (acquired with `num_cpus` crate), which is 8 in this case. So there could be resource contention between two compute node processes.

This also reminds me that we've managed to be aware of the limitation set by the container when deciding the default `parallelism`. As talked above, it seems that we also have to apply this to the worker thread number.

cc @fuyufjh @lmatz @hzxa21

**Comment by fuyufjh** [comment]
Makes sense to me. Since `--parallelism` is the CN's command-line argument, I cannot image why users set it manually but expect higher CPU utilization.
