### ISSUE TITLE
bug: panic when all over-window functions are pruned

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#11132]
```sql
create table t (k int, v int);

with cte as (
  select *, row_number() over (
    partition by k order by v rows between unbounded preceding and current row
  )
  from t
) select k, v from cte;
```

It turns out `window_functions` is empty after column pruning, but we still construct a `LogicalOverWindow`. Then `any(..)` in the below rule returns `true` and we try to index into `window_functions`.

https://github.com/risingwavelabs/risingwave/blob/a7aee09d87ee05dcb86c903c39aa6211c5ac10c7/src/frontend/src/optimizer/rule/over_window_to_agg_and_join_rule.rs#L35-L47

We may directly return `input` if all window functions are pruned here.

https://github.com/risingwavelabs/risingwave/blob/a7aee09d87ee05dcb86c903c39aa6211c5ac10c7/src/frontend/src/optimizer/plan_node/logical_over_window.rs#L674-L677

**Comment by lmatz** [comment]
link #10834
