### ISSUE TITLE
feat: Add a metric to report delete range tombstones number

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#11144]
### Is your feature request related to a problem? Please describe.

This metric could catch potential performance issues since a large number of delete range tombstones could cause a large SST meta currently. The temporal filter will generate delete range tombstones constantly right now, but after we introduce a cache we should expect this metric could have a significant decrement.

**Comment by hzxa21** [comment]
Is this done?

**Comment by Little-Wallace** [comment]
No. I will finish it in next week
