### ISSUE TITLE
Bug: Compactor is failing with oom and s3 access

### ISSUE THREAD

**Issue by Li0k** [risingwavelabs/risingwave#11142]
### Describe the bug

Recently, Compactor has been experiencing a lot of abnormal memory usage and s3 access issues, with s3 accesses failing when we need to maintain a large number of connections for a compact_task, so we suspected that it was related to streaming reads.

Scenario description.
1. Compactor nodes are using more memory than the estimated size of the task, e.g. a 300mb task with 4g of RAM.
2. Compactor fails to access s3 when issuing in a compact task with a large number of ssts, for example UnexpectedEof + IncompleteBody, ConnectionReset

We need to track down the above problems and come up with ways to deal with them.

**Comment by Li0k** [comment]
cc @zwang28

**Comment by zwang28** [comment]
@Li0k and I have identified one cause of OOM: tcp receive buffer.

By default, tcp receive buffer is dynamic between [4 KB, 6 MB]. So if there is a compaction task with 100 L0 files as input and 4 parallelism (aka. sub-compaction), its tcp connections will use at most 100 x 4 x 6MB = 2.4GB memory, which is not ever considered by compactor's memory management. (We have a simple demo code to illustrate the issue.)

```
cat /proc/sys/net/ipv4/tcp_rmem
4096    131072  6291456
cat /proc/sys/net/ipv4/tcp_moderate_rcvbuf
1
```

By reducing the recv buffer size, we have been able to fix an OOM case.
We're still discussing about an general solution.

**Comment by zwang28** [comment]
@Li0k and I have identified another source of significant memory footprint: bloom filter builder:

As the memory footprint of a bloom filter builder is proportional to number of unique user keys in the SST, the compactor may face OOM when there are lots of concurrent compaction tasks that generates lots of unique user keys. We observe this issue in Nexmark Q16, bloom filter builders from 10 concurrent tasks result in 2GB memory overhead.

![flamegraph 1 190 i190 heap](https://github.com/risingwavelabs/risingwave/assets/70626450/a2e01dc6-1d31-40f9-806f-5bf5d4526318)

**Comment by Li0k** [comment]
https://github.com/risingwavelabs/risingwave/issues/11434#issuecomment-1713241589
