### ISSUE TITLE
Add a split reduction switch for the S3 connector source.

### ISSUE THREAD

**Issue by shanicky** [risingwavelabs/risingwave#11150]
### Is your feature request related to a problem? Please describe.

For the S3 file source, after #11092, an accidental file deletion will not cause a risingwave recovery failure, but expired offset data will still be stored in the state store. 
Normally, the logic should be that the split enumerator pushes a delete update to prompt the source executor to clear the state.

**Comment by tabVersion** [comment]
will do with the new s3 source

**Comment by tabVersion** [comment]
actually s3 will discard non-exist files, no need doing it with config change
