### ISSUE TITLE
Starting 2 playgrounds will make both terminated

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#11169]
### Describe the bug

As title. Just report this issue. Not sure if it's a problem/fixable.

### Error message/log

```text
2023-07-24T15:59:55.872806+02:00 DEBUG risingwave_common_service::observer_manager: re-subscribe success
thread 'risingwave-main' panicked at 'error type notification', src/compute/src/observer/observer_manager.rs:35:17
```

**Comment by fuyufjh** [comment]
It would be normal if the second one get killed (because of port occupied, etc). 

This error looks like there is something wrong in the leader election. May take a look if have time. cc. @Gun9niR @yezizp2012

**Comment by yezizp2012** [comment]
Will take a look later when I have time. 🥵

**Comment by BugenZhao** [comment]
I used to have this problem, but it doesn't happen anymore.

**Comment by xxchan** [comment]
🤡

https://github.com/risingwavelabs/risingwave/assets/37948597/e1f51dfa-cf6a-4224-b802-86cc68fccbb6

**Comment by BugenZhao** [comment]
I think a quick hack is to add a file lock specifically to the `playground` mode.
