### ISSUE TITLE
feat: support alter database/schema/relations owner to syntax

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#11162]
### Is your feature request related to a problem? Please describe.

```sql
ALTER TABLE table_name OWNER TO new_owner;
ALTER MATERIALIZED VIEW materialized_view_name OWNER TO new_owner;
ALTER SOURCE source_name OWNER TO new_owner;
ALTER VIEW view_name OWNER TO new_owner;
```

In Postgres, we can use `ALTER TABLE` to modify the owner of the relations to a new owner, even though it's a materialized view or view. In spite of that, we still need to implement 
- ALTER VIEW
- ALTER MATERIALIZED VIEW
- ALTER SOURCE
- ALTER SINK,

while the very first version can only support ALTER TABLE. Apart from them, we also need to support:

- ALTER DATABASE
- ALTER SCHEMA

We may also need to ensure that users can check the owner of the database object via:

```sql
SELECT 
    pg_class.relname AS table_name, 
    pg_roles.rolname AS owner 
FROM 
    pg_class 
    JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace 
    JOIN pg_roles ON pg_roles.oid = pg_class.relowner 
WHERE 
    pg_namespace.nspname NOT LIKE 'pg_%' 
    AND pg_namespace.nspname != 'information_schema'
    AND pg_class.relname = 'your_table_name';  -- replace with your table name
```

### Additional context

https://www.postgresql.org/docs/current/sql-altermaterializedview.html
https://www.postgresql.org/docs/current/sql-alterview.html
https://www.postgresql.org/docs/current/sql-altertable.html
https://www.postgresql.org/docs/current/sql-alterdatabase.html

**Comment by Rossil2012** [comment]
> We may also need to ensure that users can check the owner of the database object via:
> 
> ```sql
> SELECT 
>     pg_class.relname AS table_name, 
>     pg_roles.rolname AS owner 
> FROM 
>     pg_class 
>     JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace 
>     JOIN pg_roles ON pg_roles.oid = pg_class.relowner 
> WHERE 
>     pg_namespace.nspname NOT LIKE 'pg_%' 
>     AND pg_namespace.nspname != 'information_schema'
>     AND pg_class.relname = 'your_table_name';  -- replace with your table name
> ```

Do you mean `database` or `relations` here? For now, [system table `pg_class`](https://github.com/risingwavelabs/risingwave/blob/main/src/frontend/src/catalog/system_catalog/pg_catalog/pg_class.rs#L41) do not have entries for database or schema, but only relations.

**Comment by yezizp2012** [comment]
> > We may also need to ensure that users can check the owner of the database object via:
> > ```sql
> > SELECT 
> >     pg_class.relname AS table_name, 
> >     pg_roles.rolname AS owner 
> > FROM 
> >     pg_class 
> >     JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace 
> >     JOIN pg_roles ON pg_roles.oid = pg_class.relowner 
> > WHERE 
> >     pg_namespace.nspname NOT LIKE 'pg_%' 
> >     AND pg_namespace.nspname != 'information_schema'
> >     AND pg_class.relname = 'your_table_name';  -- replace with your table name
> > ```
> 
> Do you mean `database` or `relations` here? For now, [system table `pg_class`](https://github.com/risingwavelabs/risingwave/blob/main/src/frontend/src/catalog/system_catalog/pg_catalog/pg_class.rs?rgh-link-date=2023-11-07T05%3A05%3A57Z#L41) do not have entries for database or schema, but only relations. @yezizp2012

That was edited and added by @neverchanje , I guess he was referring to the objects(relations) in the database.
