### ISSUE TITLE
feat: support WITH ORDINALITY when using unnest()

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#11166]
### Is your feature request related to a problem? Please describe.

# Syntax

``` sql
UNNEST(anyarray) WITH ORDINALITY → SETOF anyelement, bigint
```

# Description

The `unnest` function is used to expand an array to a set of rows. When
used with the `WITH ORDINALITY` modifier, it returns a second column
with a one-based index, which represents the position of each element in
the original array.

# Parameters

- `anyarray`: This is the array you want to expand to a set of rows.

# Returns

The function returns a set of rows, each containing two columns: - The
first column is of the type of the elements in the input array. - The
second column is a `bigint` that represents the position of the element
in the original array.

# Examples

``` sql
SELECT * FROM UNNEST(ARRAY['A', 'B', 'C']) WITH ORDINALITY;
-- Returns: A 1, B 2, C 3
```

In this example, the `unnest` function with `WITH ORDINALITY` expands
the input array to a set of rows and assigns a one-based index to each
element.

# Compatibility

The `unnest` function with `WITH ORDINALITY` modifier is a part of the
standard PostgreSQL distribution.

**Comment by xxchan** [comment]
dup w/ #11167
