### ISSUE TITLE
Integration test: Citus connector

### ISSUE THREAD

**Issue by StrikeW** [risingwavelabs/risingwave#11183]
We have supported Citus connector previously, add an integration test to ensure new features won't break its functionality.

**Comment by fuyufjh** [comment]
Btw, consider adding this to https://www.risingwave.dev/docs/current/rw-integration-summary/

**Comment by StrikeW** [comment]
OK, we can add it after the integration test is added.

**Comment by xiangjinwu** [comment]
Citus support removed #25534 in v3.0
