### ISSUE TITLE
frontend: support array constructing subquery `array(select ...)`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#11202]
### Describe the bug

```
2023-07-25T16:18:17.011348+08:00 ERROR pgwire::pg_protocol: failed to parse sql:

SELECT
    roles.oid as id, roles.rolname as name,
    roles.rolsuper as is_superuser,
    CASE WHEN roles.rolsuper THEN true ELSE roles.rolcreaterole END as
    can_create_role,
    CASE WHEN roles.rolsuper THEN true
    ELSE roles.rolcreatedb END as can_create_db,
    CASE WHEN 'pg_signal_backend'=ANY(ARRAY(WITH RECURSIVE cte AS (
    SELECT pg_roles.oid,pg_roles.rolname FROM pg_roles
        WHERE pg_roles.oid = roles.oid
    UNION ALL
    SELECT m.roleid,pgr.rolname FROM cte cte_1
        JOIN pg_auth_members m ON m.member = cte_1.oid
        JOIN pg_roles pgr ON pgr.oid = m.roleid)
    SELECT rolname  FROM cte)) THEN True
    ELSE False END as can_signal_backend
FROM
    pg_catalog.pg_roles as roles
WHERE
    rolname = current_user:
```
```
sql parser error: Expected [, found: ( at line:9, column:51
Near " CASE WHEN 'pg_signal_backend'=ANY(ARRAY"
2023-07-25T16:18:17.011387+08:00 ERROR pgwire::pg_protocol: error when process message error=QueryError: sql parser error: Expected [, found: ( at line:9, column:51
Near " CASE WHEN 'pg_signal_backend'=ANY(ARRAY"
```

### To Reproduce

use pgAdmin 4 to connect to Risingwave
![SCR-20230725-mqz](https://github.com/risingwavelabs/risingwave/assets/5791930/04bbd623-1b09-4797-9ed5-c02eeb80b8f2)

### Additional context

The tricky thing is `recursive cte`...
But the good side is that it is a batch query and it is fetching some catalog info, so no need to be super efficient.

And probably returning an empty result set for the `CTE` is good enough.

**Comment by fuyufjh** [comment]
This is exactly https://github.com/risingwavelabs/risingwave/issues/7199 🥲

`WITH RECURSIVE CTE` is difficult. Is there any way to go around this?

**Comment by lmatz** [comment]
Don't know if we have ever discussed batch's `recursive cte` before. 🤔 

Just purely for the sake of discussing the possibilities of implementing one in the future:

from this SQL only(Comprehensive support according to the standard may be overkill and extremely difficult), a basic implementation seems doable, i.e. not caring about performance or resource usage at all.

It seems the part we need to change is that:
the task executors are no long scheduled all at once in advance, but gradually scheduled at runtime.
(we don't really have a cyclic execution graph to deal with)

**Comment by xiangjinwu** [comment]
* Array constructing subquery has been supported.
* Recursive CTE is WIP.
