### ISSUE TITLE
make `rw-static-link` default feature

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#11201]
I bring this up because now risedev and VSCode rust analyzer uses different feature set, which results in frequent recompiling.

risedev: `RISINGWAVE_FEATURE_FLAGS=--features rw-static-link`

while VSCode use no additional feature flags

> I considered make `rw-static-link` default feature, and add `--no-default-features` for dynamic linking. But not sure.

_Originally posted by @xxchan in https://github.com/risingwavelabs/risingwave/pull/9626#discussion_r1186310348_

**Comment by xxchan** [comment]
It’s already default feature. 👀

**Comment by xxchan** [comment]
https://github.com/risingwavelabs/risingwave/blob/5cdc28d381accd4d80ecfe4c9327625c81385aff/src/cmd_all/Cargo.toml#L13

**Comment by xxchan** [comment]
I will check if there’s recompilation issue later.

**Comment by fuyufjh** [comment]
Anyway, let's close this first.
