### ISSUE TITLE
implement `to_timestamp(varchar, varchar)` -> timestamptz

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#11227]
https://www.postgresql.org/docs/current/functions-formatting.html

to_timestamp ( text, text ) → timestamp with time zone

Converts string to time stamp according to the given format. (See also to_timestamp(double precision) in [Table 9.33](https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-TABLE).)

```
to_timestamp('05 Dec 2000', 'DD Mon YYYY') → 2000-12-05 00:00:00-05
```

**Comment by lmatz** [comment]
RW:
```
dev=> select to_timestamp('05 Dec 2000', 'DD Mon YYYY');
       to_timestamp        
---------------------------
 2000-12-05 00:00:00+00:00
(1 row)

dev=> select to_timestamp(1284352323);
       to_timestamp        
---------------------------
 2010-09-13 04:32:03+00:00
(1 row)
```

PG:
```
martin=# select to_timestamp('05 Dec 2000', 'DD Mon YYYY');
      to_timestamp      
------------------------
 2000-12-05 00:00:00+08
(1 row)

martin=# select to_timestamp(1284352323);
      to_timestamp      
------------------------
 2010-09-13 12:32:03+08
(1 row)
```

If the difference between `+00:00` in RW and `+08` in PG is expected, then this function has been implemented and we can close this issue.

**Comment by xiangjinwu** [comment]
> If the difference between `+00:00` in RW and `+08` in PG is expected, then this function has been implemented and we can close this issue.

Yes. You can `set timezone to "Asia/Singapore"` in RisingWave or `set timezone to utc` in PostgreSQL to make the result looks closer, although their textual representation would still be different in whether a trailing `:00` is included.
