### ISSUE TITLE
`rw_ddl_progress` show 99% several seconds after create, but takes a few minutes to reach 100%

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#11236]
Is this a known issue?

Don't think it is super urgent, 
just record this issue, and see if we can improve it later with more statistics at hand, or tone down the expectation a bit

**Comment by chenzl25** [comment]
Which version do you use? Recently I have refined it. https://github.com/risingwavelabs/risingwave/pull/10881

**Comment by lmatz** [comment]
v1.0.0
let me try a newer version later
