### ISSUE TITLE
refactor: consolidate PostgreSQL version constant

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#11265]
https://github.com/risingwavelabs/risingwave/blob/0d549d70370c4bb1eb1b23cb0756bbe633bbc423/src/utils/pgwire/src/pg_protocol.rs#L844
https://github.com/risingwavelabs/risingwave/blob/0d549d70370c4bb1eb1b23cb0756bbe633bbc423/src/common/src/session_config/mod.rs#L405
https://github.com/risingwavelabs/risingwave/blob/0d549d70370c4bb1eb1b23cb0756bbe633bbc423/src/common/src/session_config/mod.rs#L302
https://github.com/risingwavelabs/risingwave/blob/0d549d70370c4bb1eb1b23cb0756bbe633bbc423/src/frontend/src/binder/expr/function.rs#L965

**Comment by xiangjinwu** [comment]
* The frontend `version()` function now binds to `risingwave_common::current_cluster_version`
* The pgwire implementation shall read from `session.config` rather than hardcoding, for all ParameterStatus message not limited to server_version.

**Comment by yufansong** [comment]
Disscussed offline, 2 TODO:
1. `function` / `streaming job` / `ddl controller` should get version from the same place, which currently is `current_cluster_version`. Need to set a const in `common` as the single source of truth. All previous and the `ConfigMap` should read from there: function/streaming/ddl -> current_cluster_version -> hardcode const in common <- ConfigMap <- pgwire/show. Need to figure out how to read const in ConfigMap
2. Need add a code path in pgwire for ParameterStatus, `server version / client encoding / StandardConformingString / ApplicationName` need read from config map.
