### ISSUE TITLE
Create ch benchmark q5 MV failed

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#11293]
### Describe the bug

https://buildkite.com/risingwave-test/ch-benchmark-consistency-only/builds/17#01899afa-72d8-4957-af71-f97b719cb3f6/1085-1161

Grafana: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1%5Cu0026var-datasource%3DPrometheus:%20test-useast1-eks-a%5Cu0026from%3D1688576344000%5Cu0026to%3D1688576946000%5Cu0026var-namespace%3Dnexmark-bs-0-14-daily-20230705&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=ch-consistency-only-pipeline&var-instance=benchmark-risingwave&var-node=All&var-job=All&var-table=All&from=1690522505411&to=1690523067531
Log: https://grafana.test.risingwave-cloud.xyz/d/liz0yRCZz1/log-search-dashboard?orgId=1&var-data_source=Logging:%20test-useast1-eks-a&from=1690522505000&to=1690523067000&var-namespace=ch-consistency-only-pipeline&var-pod=benchmark-risingwave-meta-m-0&var-search=

```
dev=> create materialized view ch_benchmark_q5
    as
    select       n_name,
           sum(ol_amount) as revenue
    from         customer, orders, order_line, stock, supplier, nation, region
    where        c_id = o_c_id
    and c_w_id = o_w_id
    and c_d_id = o_d_id
    and ol_o_id = o_id
    and ol_w_id = o_w_id
    and ol_d_id=o_d_id
    and ol_w_id = s_w_id
    and ol_i_id = s_i_id
    and mod((s_w_id * s_i_id),10000) = s_suppkey
    and ascii(substr(c_state,1,1)) - 65 = s_nationkey
    and s_nationkey = n_nationkey
    and n_regionkey = r_regionkey
    and r_name = 'EUROPE'
    and o_entry_d >= '2007-01-02 00:00:00.000000'
    group by n_name;
ERROR:  QueryError: internal error: MetadataModel error: Meta store error: internal error: grpc request error: status: InvalidArgument, message: "etcdserver: request is too large", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }
```

### Error message/log

```text
ERROR:  QueryError: internal error: MetadataModel error: Meta store error: internal error: grpc request error: status: InvalidArgument, message: "etcdserver: request is too large", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }
```

### To Reproduce

Run with ch-benchmark-consistency-only pipeline on branch ch-benchmark-consistency-only with following parameters
```
RW_VERSION="nightly-20230727"
```

### Additional context

link #11072

**Comment by huangjw806** [comment]
`etcdserver: request is too large`

maybe you should increase etcd params `--max-request-bytes`.

**Comment by fuyufjh** [comment]
Hey, can we close this?

**Comment by cyliu0** [comment]
Close this since it's a duplicated https://github.com/risingwavelabs/risingwave/issues/11072
