### ISSUE TITLE
storage: remove unnecessary `async_trait`s

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#1132]
- [x] StateStore @lmatz #1266 
- [x] StateStoreIter @BowenXiao1999 #1370 
- [ ] ObjectStore
- [x] #1334 

For such traits, we don't need to use `async_trait` on it. We can always use GAT + generics for them.

**Comment by BowenXiao1999** [comment]
Progress update: 

> Currently, the async trait refactor gives me some feelings
> 
> * makes the traits its self complicated (Luckily it do not expose to users).
> * some lifetime problem we have to hack. For example, expand some function.
> * we do not have bench to show the performance gained from this, although in theory it indeed better.

#1787 Blocked by a compiler problem (seems
