### ISSUE TITLE
Catalog error: table or source not found: pg_depend

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#11321]
The latest Dbeaver `23.1.3` requires this when creating a table

link https://github.com/risingwavelabs/risingwave-docs/issues/1073

**Comment by xxchan** [comment]
I remembered (not sure) this error doesn't affect functionalities, and disappered after #11179

**Comment by lmatz** [comment]
![SCR-20230801-fa5](https://github.com/risingwavelabs/risingwave/assets/5791930/ecee7208-4650-491c-b35e-957830df2592)

It right now cannot bypass the issue when, e.g. create table
