### ISSUE TITLE
ci/docker: use `cargo chef` to prepare dependencies.

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#11378]
https://github.com/LukeMathWalker/cargo-chef

It can speed up docker build by building all dependencies in one layer, and then we can reuse it as docker image cache.

**Comment by xxchan** [comment]
For docker build, I think alternatively we can also use `sccache` for it (with a different S3 prefix).

But maybe we can also use `cargo chef` (and maybe sunset `sccache`) in CI to achieve #11097

**Comment by xxchan** [comment]
For java, it seems we can simply use `pom.xml` https://stackoverflow.com/questions/42208442/maven-docker-cache-dependencies

A writeup about rust's problem, and many solutions https://hackmd.io/@kobzol/S17NS71bh#Better-support-of-Docker-layer-caching-in-Cargo

**Comment by BugenZhao** [comment]
Seems worthwhile as our folks now often build docker images manually for the purpose of benchmarking, and speeding up the build process could result in a smoother experience and significant cost savings. 🤔
