### ISSUE TITLE
feat(system params): declare whether each system parameter can be ignored

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#11382]
### Is your feature request related to a problem? Please describe.

For system parameters, currently we will panic if meta encountered some unrecognized parameters when the user rollback the version of rw. The user experience is not very good. But also It's very dangerous if we ignore some unrecognized parameters that might be added in newer version directly. We'd better declare whether each parameter can be ignored explicitly.

**Comment by fuyufjh** [comment]
Seems we have discussed this topic before. Shall we warn users instead of panic on inexistent system parameters?

**Comment by yezizp2012** [comment]
> Seems we have discussed this topic before. Shall we warn users instead of panic on inexistent system parameters?

I guess not, Some of the parameters in the new version may have affected some of the data in the system, and rolling back may cause inconsistencies and data errors.

**Comment by fuyufjh** [comment]
> > Seems we have discussed this topic before. Shall we warn users instead of panic on inexistent system parameters?
> 
> I guess not, Some of the parameters in the new version may have affected some of the data in the system, and rolling back may cause inconsistencies and data errors.

Even in such cases, I think ignoring is better than panic 🥵
