### ISSUE TITLE
feat: allow passing an existing private link endpoint in create sink/source statement

### ISSUE THREAD

**Issue by wjf3121** [risingwavelabs/risingwave#11397]
### Is your feature request related to a problem? Please describe.

The detailed motivation is described in this RFC:
https://www.notion.so/risingwave-labs/RFC-Private-Service-Connect-Support-for-RisingWave-Cloud-on-GCP-dfadc39a71fe49d887a1456ac57181a8

### Describe the solution you'd like

As title.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by StrikeW** [comment]
Hi @wjf3121, would you mind sharing the progress of the cloud platform?

**Comment by wjf3121** [comment]
> Hi @wjf3121, would you mind sharing the progress of the cloud platform?

We are starting the work this week, @lukeraphael will be working on it. I think it has been stated several times already: the kernel side of the work doesn't really depend on cloud's work. Is there anything particular that you need from cloud apart from the final integration?

**Comment by wjf3121** [comment]
This is the tracking issue: https://linear.app/risingwave-labs/issue/CLOUD-1708/private-link-support-on-gcp
