### ISSUE TITLE
`failed to fetch meta info for source` due to listing S3 files taking too much time

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#11391]
### Describe the bug

https://github.com/risingwavelabs/risingwave/blob/main/src/meta/src/stream/source_manager.rs#L790-L799

~It turns out that the user failed to add `/` at the beginning of the `match_pattern` option.~
(because the pattern does not match anything)

Actually it is still not working.

But the current error message fails to remind the user to do so.

Maybe we also validate the pattern a bit before sending to S3.

### Additional context

Feel free to reassign

**Comment by lmatz** [comment]
It is likely that the user has about 1 million files in the path that matches the pattern.

Listing all of files may take longer than expected.

Optimization such as pagination may be needed.

**Comment by tabVersion** [comment]
> Listing all of files may take longer than expected.
> Optimization such as pagination may be needed.

actually, one `list_objects` call can only return 1k filenames. We have already supported pagination but listing 1M files takes more time than 10s (as a hard code upper time limit).

**Comment by BugenZhao** [comment]
> Listing all of files may take longer than expected.

If I understand correctly, we still have to list all files in an S3 source every "tick" to find what changes. 🤔 So this is inevitable under the current design.

https://github.com/risingwavelabs/risingwave/blob/587a8c74390a208c6e5516fae80c191de5725966/src/meta/src/stream/source_manager.rs#L162-L185

**Comment by lmatz** [comment]
`pagination` over multiple barriers if necessary and possible? i.e. an ultimate solution

**Comment by tabVersion** [comment]
we may try a lazy strategy when fetching object names. We will never fetch the next page unless all objects in the catalog have been read.
This allows us to control the task queue length and we don't have to fetch all pages in one call. For the first tick when creating a table/source, we fetch the first page and the timeout would not result in creation failure. cc @shanicky

**Comment by tabVersion** [comment]
#12595

**Comment by fuyufjh** [comment]
@tabVersion As https://github.com/risingwavelabs/risingwave/pull/12595 has been merged, can we close this issue now?
