### ISSUE TITLE
Failed to query any int using golang pgx driver

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#11419]
### Error message/log

```text
2023/08/03 17:18:27 convert field 0 failed: strconv.ParseInt: parsing "\x00\x00\x00\x01": invalid syntax
exit status 1
```

### To Reproduce

```sql
CREATE TABLE t1 (v1 int);
```

```go
package main

import (
	"database/sql"
	"log"

	_ "github.com/jackc/pgx/v4/stdlib"
)

func main() {
	connectionString := "postgres://root@localhost:4566/dev"

	// Connect to the database
	db, err := sql.Open("pgx", connectionString)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	// Execute the query
	rows, err := db.Query("SELECT * FROM t1")
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()

	// Fetch the results
	for rows.Next() {
		var v1 int
		if err := rows.Scan(&v1); err != nil {
			log.Fatal(err)
		}
		log.Println(v1)
	}

	// Check for any error during rows iteration
	err = rows.Err()
	if err != nil {
		log.Fatal(err)
	}
}

```

**Comment by xiangjinwu** [comment]
Looks like RW returns the integer in binary format but pgx tries to parse it as text format.

**Comment by TennyZhuang** [comment]
How do the client and server reach an agreement on the format? Do we forget to support such protocol?

**Comment by xiangjinwu** [comment]
Found the issue:
* pgx -> rw: `Bind` proposes to use binary format, which is effective in rw
* pgx -> rw: `Describe` asks result format
* rw -> pgx: `RowDescription` answers it would be text format (bug here)
* rw -> pgx: `DataRow` sends the result in binary, as requested during `Bind`

**Comment by TennyZhuang** [comment]
> Found the issue:
> 
> * pgx -> rw: `Bind` proposes to use binary format, which is effective in rw
> * pgx -> rw: `Describe` asks result format
> * rw -> pgx: `RowDescription` answers it would be text format (bug here)
> * rw -> pgx: `DataRow` sends the result in binary, as requested during `Bind`
> 
> https://github.com/risingwavelabs/risingwave/blob/bac048757258c9ab7f9a75aca4eb9c26be4ff8d1/src/frontend/src/session.rs#L1037
> 
> 
> `infer` sets the format to default (text) and the actual format from `Bind` in `portal.result_formats` are unused here.
> Broken by #8919, after which `PgFieldDescriptor::set_to_binary` is dead code and never called in the code base.

Awesome! It looks easy to fix, would you like to submit a fix?
