### ISSUE TITLE
New syntax for create sink

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#11451]
### Is your feature request related to a problem? Please describe.

Similar to [RFC: New Source DDL #64](https://github.com/risingwavelabs/rfcs/pull/64), we hope to  make the syntax of `create sink` clearer and more consistent with `source`. 

Take Kafka sink for example:

```sql
CREATE SINK sink1 FROM mv1 
WITH (
   connector='kafka',
   type='append-only'
   properties.bootstrap.server='localhost:9092',
   topic='test'
);
```

(Currently, Kafka sink only supports JSON format.)

If we adapt the new source syntax here, it will be like

```sql
CREATE SINK sink1 FROM mv1 
WITH (
   connector='kafka',
   properties.bootstrap.server='localhost:9092',
   topic='test'
)
FORMAT plain ENCODE json;
```

This syntax is also applicable to any other sources with multiple format/encode options, such as S3 or Iceberg.

**Comment by fuyufjh** [comment]
It seems to be a prerequisite of supporting other formats than JSON for Kafka Source. So let me assign to @xiangjinwu for now.

**Comment by xiangjinwu** [comment]
Minor concern: `append only` is spelled as two words when used on table. #7965, although they do mean slightly different things:
* On table, it is more like a constraint on what a table is allowed to do.
* On sink, it is a type/format about how input would be transformed into output.
