### ISSUE TITLE
pg_dump failed on catalog resolution

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#11470]
### Error message/log

```text
pg_dump: error: query failed: ERROR:  QueryError: Bind error: failed to bind expression: pg_catalog.pg_is_in_recovery()

Caused by:
  Catalog error: first valid schema not found: no schema has been selected to create in
pg_dump: detail: Query was: SELECT pg_catalog.pg_is_in_recovery()
```

### To Reproduce

```
pg_dump --username=root --no-password --host=127.0.0.1 --port=4566  dev
```

**Comment by LonwoLonwo** [comment]
Hello @TennyZhuang 

Does it mean that RisingWave supports the pg_dump tool? 

I see this error using different pg_dump versions:

```
pg_dump: ERROR:  Failed to run the query
Caused by these errors (recent errors listed first):
  1: Failed to get/set session config
  2: Invalid value `off` for `synchronize_seqscans`
  3: provided string was not `true` or `false`
pg_dump: SET synchronize_seqscans TO off
```

**Comment by BugenZhao** [comment]
> Does it mean that RisingWave supports the pg_dump tool?
> 
> I see this error using different pg_dump versions:

Hi. There's still a long way for RisingWave to go in supporting a subset of the features from `pg_dump`. By subset I mean the functionalities for backing-up data in tables are not planned in the near future, since RisingWave uses a completely different storage system and architecture from Postgres.

**Comment by LonwoLonwo** [comment]
Thanks for the answer @BugenZhao
