### ISSUE TITLE
java udf: could not resolve parent

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#11476]
### Describe the bug

deleting `<parent>` section can fix it. Install the parent pom by `mvn clean install -N` can also fix it.

What's the best practice?

### Error message/log

```text
[ERROR] Failed to execute goal on project udf-example: Could not resolve dependencies for project com.example:udf-example:jar:1.0-SNAPSHOT: Failed to collect dependencies at com.risingwave.java:risingwave-udf:jar:0.0.1: Failed to read artifact descriptor for com.risingwave.java:risingwave-udf:jar:0.0.1: Could not find artifact com.risingwave.java:java-parent:pom:1.0-SNAPSHOT -> [Help 1]
```

### To Reproduce

```
cd java/udf
mvn install
cd ../udf-example
mvn package
```

**Comment by xxchan** [comment]
It seems we should use Maven Aggregation instead of Inheritance https://stackoverflow.com/questions/1725579/maven-making-child-projects-that-can-be-independent-of-their-parent

**Comment by wenym1** [comment]
Run `mvn clean package --pl udf --am` instead of entering the `udf` directory to build it can fix.
