### ISSUE TITLE
better error prompt for unmatched columns in UNION

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#11509]
UNION is frequently used in the context of dbt.

QueryError: Invalid input syntax: UNION types VARCHAR and DOUBLE cannot be matched

The error doesn't contain the name of unmatched columns. Adn I will be unable to know specifically how to fix it.

**Comment by chenzl25** [comment]
I just removed columns' information last week so that we can throw an error exactly like PostgreSQL. Let me add them back.
