### ISSUE TITLE
bug: CI cannot run on different AWS instance types.

### ISSUE THREAD

**Issue by huangjw806** [risingwavelabs/risingwave#11519]
At present, our ci seems to only run on the `m5.4xlarge` instance type, and we will encounter some problems when we want to use other instance types. for example:

- `m6i.4xlarge`: https://buildkite.com/risingwavelabs/main/builds/5211#0189d1a7-7576-4a64-bef0-6511e7f5121d
- `m5a.4xlarge`： https://github.com/risingwavelabs/risingwave/issues/8134

We want to use multiple instance types to run CI, which can alleviate the resource limitation of spot instance, but it is difficult to do it now.

**Comment by kwannoel** [comment]
> At present, our ci seems to only run on the `m5.4xlarge` instance type, and we will encounter some problems when we want to use other instance types. for example:
> 
>     * `m6i.4xlarge`: https://buildkite.com/risingwavelabs/main/builds/5211#0189d1a7-7576-4a64-bef0-6511e7f5121d


![Screenshot 2023-08-08 at 10 02 20 AM](https://github.com/risingwavelabs/risingwave/assets/47273164/086dea17-9e29-4e7e-8389-b28104a58624)

Seems like ports 1250, 5691 are in use.

**Comment by huangjw806** [comment]
> Seems like ports 1250, 5691 are in use.

The kill cluster is not cleaned up? Not sure why m5.xlarge works.

<img width="610" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/29391315/f3e83a40-604b-48d5-922a-405e311dbfe2">

**Comment by fuyufjh** [comment]
> > Seems like ports 1250, 5691 are in use.
> 
> The kill cluster is not cleaned up? Not sure why m5.xlarge works.

The CI script kill cluster using  `risedev ci-kill`

```
[cargo-make] INFO - Task: ci-kill
```

I am not sure about `tmux kill-session` but `kill` command is async i.e. it won't wait for process to exit. Perhaps you need add some `sleep` here or https://stackoverflow.com/a/29281720

**Comment by huangjw806** [comment]
Maybe m6i.4xlarge is faster than m5.4xlarge.

**Comment by huangjw806** [comment]
```
tmux kill-session -t risedev &
kill_session_pid=$!
wait $kill_session_pid
```
Maybe this can achieve synchronous waiting for kill, I will try it.
