### ISSUE TITLE
Feature request: Reuse connector WITH parameters

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#11545]
(requested by a user)

e.g., for PostgreSQL CDC, users need to repeatedly enter hostname, port, username, password, ... for all tables. It might be better if there are some ways to reuse the common parameters.

At the same time, are there any existing workarounds?

**Comment by fuyufjh** [comment]
For CDC sources, @StrikeW is working on [RFC: Share a change log stream for multiple CDC tables](https://www.notion.so/risingwave-labs/RFC-Share-a-change-log-stream-for-multiple-CDC-tables-1f1581d76da2458ba6fafca0c5252226) (@StrikeW Please help migrate this doc to [RFC repo](https://github.com/risingwavelabs/rfcs/pulls)), which introduces a new syntax to define multiple tables from one upstream DB.

For other things, we don't have a solution yet. Welcome for any discussions & proposals.

**Comment by tabVersion** [comment]
> e.g., for PostgreSQL CDC, users need to repeatedly enter hostname, port, username, password, ... for all tables. It might be better if there are some ways to reuse the common parameters.

actually, I have proposed the `connection` syntax for this case, https://github.com/risingwavelabs/rfcs/pull/35 but we only adopt the private link part. Maybe it is time to review the design.

**Comment by xxchan** [comment]
BTW, I also feel that this request is somewhat similar to https://github.com/risingwavelabs/risingwave/issues/10151, where code reusability is wanted, instead of a new "capability". 

One typical argument is that we can simply use global string substitution, or dbt macros.

**Comment by ly9chee** [comment]
I'm also interested in this feature, repeatedly enter hostname, port, username, password is not just verbose and it may cause sensitive information leaks. [crdb](https://www.cockroachlabs.com/docs/stable/create-external-connection) provides the `create external connection` syntax that allows you to encapsulate network and authentication settings into a connection object. a user with higher privileges (such as root) can manage these connections by defining the necessary connection parameters. Once the connection object is created, normal users can reference it to create sources and sinks without needing to specify the network and authentication settings each time, also normal users cannot extract any sensitive information from the connection object without grants.

**Comment by StrikeW** [comment]
We will introduce `Connection` to support this feature. close as stale.
