### ISSUE TITLE
Support partitioned checkpoint

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#1157]
To improve our checkpoint strategy, we decide to support checkpoint in MView granularity with configurable consistency. In other words, each MView can complete its checkpoint independently.

- [ ] Introduce hummock group in hummock manager to track MaxCommittedEpoch (MCE) of each MView
- [ ] Support reads/writes with hummock group
- [ ] Support group based barrier injection/collection and epoch commit
- [ ] Support group based failover

Discussion:
- How to ensure query consistency after failover (rollback MCE or not? If not, frontend waits or storage waits?)

**Comment by wenym1** [comment]
Tracked by https://github.com/risingwavelabs/risingwave/issues/14041
