### ISSUE TITLE
bug(expr): `coalesce` doesn't work as expected in streaming

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#11586]
### Describe the bug

`coalesce(...)` is often used to eliminate NULLs from inner expression. 

For example, in `coalesce(v::bigint, -1)`, I expect the result to be `-1` instead of NULL when casting `v` to bigint failed.

### To Reproduce

```
dev=> create table t ( k int, v varchar, primary key(k));
CREATE_TABLE
dev=> insert into t values (1, '123'), (2, 'fooo');
INSERT 0 2
dev=> create materialized view mv as select k, coalesce(v::bigint, -1) from t;
CREATE_MATERIALIZED_VIEW
dev=> select * from mv;
 k | coalesce
---+----------
 1 |      123
 2 |
(2 rows)
```

This log is expected:

```
2023-08-10T15:08:52.222621+08:00 ERROR actor{otel.name="Actor 26" actor_id=26 prev_epoch=4876935542079488 curr_epoch=4876935607484416}:executor{otel.name="MaterializeExecutor 1A00000002 (actor 26, operator 2)" actor_id=26}:executor{otel.name="ProjectExecutor 1A00000001 (actor 26, operator 1)" actor_id=26}: risingwave_stream::executor::actor: Compute error: Parse error: invalid digit found in string, executor: ProjectExecutor 1A00000001
```

### Expected behavior

Should get the next value in `coalesce` (here `-1`) instead of NULL

### How did you deploy RisingWave?

risedev

### The version of RisingWave

main branch

**Comment by fuyufjh** [comment]
@wangrunji0408 can you please take a look? Please feel free to reassign

**Comment by BugenZhao** [comment]
> I expect the result to be `-1` instead of NULL when casting `v` to bigint failed.

This seems not to be the behavior of Postgres. :(

```sql
postgres=# create table teric ( k int, v varchar, primary key(k));
CREATE TABLE
postgres=# insert into teric values (1, '123'), (2, 'fooo');
INSERT 0 2
postgres=# select k, coalesce(v::bigint, -1) from teric;
ERROR:  invalid input syntax for type bigint: "fooo"
postgres=# 
```

**Comment by fuyufjh** [comment]
> The reason is that in default non-strict mode, the cast v::bigint on fooo caused an error, so the whole expression coalesce(v::bigint, -1) was set to NULL. This seems to be consistent with the current definition of non-strict mode. If we want the expected result, eval_infallible should be called on every inner expression instead of only on the upper level. Should we adjust this behavior?

Yes, this is exactly what I am proposing. (but I am not sure how much work it will take) 

In my own experience, a more intuitive way is returning `NULL` for the failed expressions only, instead of the whole expression, and continue the normal execution for external expression.

Additionally, from another perspective, the "whole expression" is actually a kind of expression. The optimizer can push down expressions through operators, for example,

```
-- before
Project [ t1.a * t1.b + sqrt(t2.c) ]
  Join
    TableScan t1
    TableScan t2

-- after
Project [ $expr1 + $expr2 ]
  Join
    Project [ t1.a * t1.b as $expr1 ]
      TableScan t1
    Project [ sqrt(t2.c) as $expr2  ]
      TableScan t2
```

**Comment by fuyufjh** [comment]
> > I expect the result to be `-1` instead of NULL when casting `v` to bigint failed.
> 
> This seems not to be the behavior of Postgres. :(
> 
> ```sql
> postgres=# create table teric ( k int, v varchar, primary key(k));
> CREATE TABLE
> postgres=# insert into teric values (1, '123'), (2, 'fooo');
> INSERT 0 2
> postgres=# select k, coalesce(v::bigint, -1) from teric;
> ERROR:  invalid input syntax for type bigint: "fooo"
> postgres=# 
> ```

Yes, our batch query's behavior follows that style, but streaming queries require some more design because it can never fail (otherwise the stream stops)

**Comment by xiangjinwu** [comment]
Let's discuss in one place: #4458

**Comment by xiangjinwu** [comment]
I do not want to close this as duplicate, because the other one is a feature request while this one is a bug of existing implementation. But we can still keep discussion in one place and see if they are resolved by a common solution or separately.

> Additionally, from another perspective, the "whole expression" is actually a kind of implementation. The optimizer can push down expressions through operators

It is actually possible to achieve the desired behavior in issue description with `CommonSubExprExtractRule` now. To clarify I am not suggesting we abuse the bug this way...
```
dev=> create materialized view mv as select k, coalesce(v::bigint, -1) from t order by v::bigint;
NOTICE:  The ORDER BY clause in the CREATE MATERIALIZED VIEW statement does not guarantee that the rows selected out of this materialized view is returned in this order.
It only indicates the physical clustering of the data, which may improve the performance of queries issued against this materialized view.

CREATE_MATERIALIZED_VIEW

dev=> select * from mv;
 k | coalesce 
---+----------
 2 |       -1
 1 |      123
(2 rows)
```
