### ISSUE TITLE
Add system column `rw_timestamp` for any tables

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#11629]
### Is your feature request related to a problem? Please describe.

Expose `rw_timestamp` on any tables.

Because our subscription already exposed a timestamp `rw_timestamp` based on epoch, I think there isn’t any concern about exposing the internal epoch using a hidden column. 

Besides, I think vnode and epoch is also useful in some cases. How about do them together?

### Additional context

Slack discussion https://risingwave-labs.slack.com/archives/C048771BGKF/p1691737477347599?thread_ts=1691732764.258889&cid=C048771BGKF

**Comment by st1page** [comment]
Some additions: they can only be referenced by a batch query and not by a streaming query.

**Comment by chenzl25** [comment]
`_rw_epoch` and `_rw_vnode` look reasonable. However, do we need `_rw_raw_value` and `_rw_raw_key`?

**Comment by fuyufjh** [comment]
> `_rw_epoch` and `_rw_vnode` look reasonable. However, do we need `_rw_raw_value` and `_rw_raw_key`?

Sorry, please ignore them. Let's start from `rw_timestamp` now. Please check this [Slack thread](https://risingwave-labs.slack.com/archives/C04S2HVU99V/p1723696743918329?thread_ts=1723660625.432849&cid=C04S2HVU99V) for context.

**Comment by st1page** [comment]
> `_rw_epoch` and `_rw_vnode` look reasonable. However, do we need `_rw_raw_value` and `_rw_raw_key`?

The requirements come from the debugging and trouble shooting for the tricky bugs such as https://risingwave-labs.slack.com/archives/C048771BGKF/p1691736276987669?thread_ts=1691732764.258889&cid=C048771BGKF
