### ISSUE TITLE
Enable deploy multiple compute node clusters on one datastore with resource isolation

### ISSUE THREAD

**Issue by curiosityyy** [risingwavelabs/risingwave#11649]
### Is your feature request related to a problem? Please describe.

The current configuration of the RisingWave doesn't allow the deployment of two separate compute node clusters with resource isolation. This limitation makes it challenging to have one cluster solely dedicated to serving online queries without being affected by other batching/streaming tasks. This could potentially lead to delays or bottlenecks, especially in high-demand environments.

**Comment by zwang28** [comment]
We do have a doc for dedicated serving cluster WIP, @CharlieSYH .

**Comment by curiosityyy** [comment]
Yeah! That would be nice. Will try it later.

**Comment by zwang28** [comment]
Doc: https://www.risingwave.dev/docs/current/dedicated-compute-node/
Please let me know if any problems.
