### ISSUE TITLE
Tracking: support `pgbouncer`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#11674]
- [x] #10789
- [ ] support prepared statement (?)

> Several levels of brutality when rotating connections:

> Session pooling
Most polite method. When a client connects, a server connection will be assigned to it for the whole duration it stays connected. When the client disconnects, the server connection will be put back into pool. This mode supports all PostgreSQL features.

> Transaction pooling
A server connection is assigned to a client only during a transaction. When PgBouncer notices that the transaction is over, the server will be put back into the pool.
This mode breaks a few session-based features of PostgreSQL. You can use it only when the application cooperates by not using features that break. See the table below for incompatible features.

> Statement pooling
Most aggressive method. This is transaction pooling with a twist: Multi-statement transactions are disallowed. This is meant to enforce “autocommit” mode on the client, mostly targeted at PL/Proxy.

The user currently uses `prepared statements` in `Transaction pooling`.
We can consider supporting the part requested by the user first. And leave the rest for future work.

Need to investigate the difficulty of supporting the `prepared statement`. If the implementation is too hard/tedious, we can also choose to support the part that the user is using.

https://jpcamara.com/2023/04/12/pgbouncer-is-useful.html#prepared-statements:
> PgBouncer says it doesn’t support prepared statements in either PREPARE or protocol-level format. What it actually doesn’t support are named prepared statements in any form. That’s because named prepared statements live in the session and in [transaction mode](https://jpcamara.com/2023/04/12/pgbouncer-is-useful.html#transaction-mode) you can switch sessions.

Add Server-side Prepared Statements Cache
https://github.com/pgbouncer/pgbouncer/pull/757

**Comment by zwang28** [comment]
> We can consider supporting the part requested by the user first. And leave the rest for future work.
protocol level prepared plans had already been supported in #5485.

To further support [PREPARE SQL command](https://www.postgresql.org/docs/current/sql-prepare.html), there is considerable refactor to be done @ZENOTME
