### ISSUE TITLE
source: Preserve other fields when parsing failed on a certain field

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#11694]
### Is your feature request related to a problem? Please describe.

Currently, the source parser will drop the whole line when encountering one corrupted field

```
2023-08-15T06:50:34.233772659Z  WARN risingwave_connector::parser: message parsing failed internal error: failed to parse all columns: [internal error: AccessError: TypeError { expected: "Some(Int32)", got: "string", value: "0181448105" }
```

This behavior makes it **fragile** to "dirty" data. From my own experience, it's very common that some dirty data was mixed in for JSON data sources.

### Describe the solution you'd like

Preserve the line when parsing failed on a certain field. The field can be filled with `NULL` or any other reasonable value (e.g. converting number from string implicitly)

**Comment by st1page** [comment]
Can you give a case for this? I remember for Json we will fill NULL value. :thinking: But we had some issues with Protobuf and Avor. So for different encoding we have diffent behavior currently? c.c. @tabVersion

**Comment by fuyufjh** [comment]
> I remember for Json we will fill NULL value. 🤔

Me, too, but it seems not? 

Check the case here: https://risingwave-community.slack.com/archives/C03BW71523T/p1692083823696229

**Comment by fuyufjh** [comment]
@tabVersion Can you please take a look? Also feel free to reassign

**Comment by tabVersion** [comment]
close as done
