### ISSUE TITLE
connector: support sinking jsonb as dynamic type

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#11699]
### Is your feature request related to a problem? Please describe.

As an analogy to #10772, there are 2 styles to sink a `jsonb` value out:

Always as a JSON-encoded string:
* `1` -> `"1"`
* `true` -> `"true"`
* `null` -> `"null"`
* `"foo"` -> `"\"foo\""`
* `[1, true, "foo"]` -> `"[1, true, \"foo\"]"`
* `{"k": 2}` -> `"{\"k\": 2}"`

As different types based on `jsonb_typeof`:
* `1` -> `1`
* `true` -> `true`
* `null` -> `null`
* `"foo"` -> `"foo"`
* `[1, true, "foo"]` -> `[1, true, "foo"]`
* `{"k": 2}` -> `{"k": 2}`

Currently the kafka sink uses the former style, because each RisingWave data type always maps to a **single data type in output**. But the latter form may be preferred in certain cases.

**The latter style should report an error when the sink column is not dynamic type.**

### Describe the solution you'd like

Introduce a new sink option to switch between the 2 styles, similar to existing `TimestampHandlingMode`. The default can be used to retain backward compatibility.

### Additional context

https://github.com/risingwavelabs/risingwave/blob/26edff41e1caf0122a35f96799fa1c433efde1d0/src/connector/src/sink/utils.rs#L355-L357

cc @StrikeW @tabVersion @BugenZhao

**Comment by maingoh** [comment]
I think I am facing a similar issue. I am trying to sink jsonb values from a materialized view into an avro schema in kafka, with map and record types. I am getting the following errors:
```
Encode error: encode foo error: cannot encode jsonb column as {"name":"foo","type":"record","fields":[{"name":"id","type":"string"},{"name":"name","type":"string"}]} field
```
Or 
```
Encode error: encode foo error: cannot encode jsonb column as {"type":"map","values":"string"} field
```

**Comment by yuhao-su** [comment]
Do we need this for DebeziumJson?

**Comment by xiangjinwu** [comment]
> Do we need this for DebeziumJson?

According to [Debezium](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-data-types) the `jsonb` data type is always mapped to Kafka Connect `string` type. It is never a dynamic type
