### ISSUE TITLE
bug: move table to an existing compaction group can violate can_concat for non-overlapping level

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#11703]
### Describe the bug

commit: `4a5bf065b8d3c119393856e2390763e62499e765`
The following scenario can happen:
- Compaction Group A contains tables [T1, T2, T4]
- Compaction Group B contains tables [T3, T5]
- T3 is moved from Group B to Group A.

When that happen, it is possible that SST1 with [T1, T2, T4] and SST1 with [T3] are in the same non-overlapping level while they actually overlap with each other.

**Comment by hzxa21** [comment]
@Little-Wallace IIUC, this is fixed by #11683. Shall we close the issue?

**Comment by Little-Wallace** [comment]
fix by https://github.com/risingwavelabs/risingwave/pull/11683
