### ISSUE TITLE
All-in-one deployment for RisingWave

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#11736]
1. Allow users to pass in their own options for meta, frontend and compute. e.g. --meta-node-opts="..."
2. Allow users to pass in `--config-path` for system level configurations. Made possible by 1. as well.
3. Playground’s meta does not connect to an etcd (etcd will be separate deployed). Should be made possible by 1.
4. Playground should be able to connect to object store. Should be made possible by 1.

--

Further changes for stability:
- [ ] Ensure the meta process exits cleanly.
- [ ] Hummock can't seem to shutdown cleanly, if it is in the middle of checkpoint.

Testing requirements:
- [x] Run the binary standalone, without risedev and cargo. Make sure it works.
- [x] Test meta connect to etcd.
- [x] Test connect to minio.
- [x] Test connect to compactor.

**Comment by xxchan** [comment]
duplicate (or part of) https://github.com/risingwavelabs/risingwave/issues/10908?

**Comment by kwannoel** [comment]
> duplicate (or part of) https://github.com/risingwavelabs/risingwave/issues/10908?

I think if this issue is complete, #10908 will just be a matter of passing in the right configurations, and demo-ing that it can be done.
