### ISSUE TITLE
Ban update fields that can affect primary key(which includes generated column) 

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#11742]

**Comment by yuhao-su** [comment]
What is the purpose of this issue?
If It is to prevent errors caused by batch (non-point) update, we can make a change in our update execution by sending all deletes before inserts instead of sending (updateDelete, UpdateInsert)s

**Comment by chenzl25** [comment]
I don't get the motivation for this issue as well. Maybe you should add some description cc @st1page.

>If It is to prevent errors caused by batch (non-point) update, we can make a change in our update execution by sending all deletes before inserts instead of sending (updateDelete, UpdateInsert)s.

Currently, the update executor sends updateDelete before UpdateInsert for each row. If we change it to send all delete before insert. Does it solve the problem?

**Comment by st1page** [comment]
> I don't get the motivation for this issue as well. Maybe you should add some description cc @st1page.
>> If It is to prevent errors caused by batch (non-point) update, we can make a change in our update execution by sending all deletes before inserts instead of sending (updateDelete, UpdateInsert)s.
>
> Currently, the update executor sends updateDelete before UpdateInsert for each row. If we change it to send all delete before insert. Does it solve the problem?

LGTM, I think we can change it to send all delete before insert to solve this issue. I think we did not do that because we did not have transactions. In that case, losing all the data without the new value is unacceptable. So we Banned the update on the pk columns. 
Now we have transactions to ensure the transaction's atomicity. So we can allow the update on the pk columns such as `do update set pk = pk +1`;

**Comment by BugenZhao** [comment]
> Now we have transactions to ensure the transaction's atomicity.

The atomicity cannot hold if the changes is too large. 😂 As a contrast, by sending `UpdateDelete` with `UpdateInsert`, we can at least guarantee row-level atomicity as we never split the pair into different chunks.
