### ISSUE TITLE
Feat: Support variable input of System Administration Functions

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#11752]
## Background
We have supported some PG's System Administration Functions https://www.postgresql.org/docs/9.1/functions-admin.html. But we only support literal input now.

In PG
```SQL
dev=# create table t_names(name varchar);
CREATE TABLE
dev=# insert into t_names values ('a'), ('t');
INSERT 0 2
dev=# select pg_table_size(name) from t_names;
 pg_table_size 
---------------
         16384
         16384
(2 rows)
```
In RW
```SQL
dev=> select pg_table_size(name) from t_names;
ERROR:  QueryError: Bind error: failed to bind expression: pg_table_size(name)

Caused by:
  Expr error: Expected an integer or varchar literal
```

The usage is found in bytebase's PG connector currently.
https://github.com/bytebase/bytebase/blob/b871987854e842d2adf21e7278594af38a3b1b6f/backend/plugin/db/pg/sync.go#L414-L423

## implementation

We can bind it with nested subquery
```
dev=> explain (trace) select 
    name, 
    (select total_key_size + total_value_size from rw_catalog.rw_table_stats 
        where rw_catalog.rw_table_stats.id = (
            select id from rw_catalog.rw_tables where rw_catalog.rw_tables.name = t_names.name limit 1
        )
    ) as pg_table_size
from t_names;
```

## Alternative
Another solution is to implement a special `SystemProject` executor in LocalExecution(Frontend) which can read from the catalog during processing.

**Comment by st1page** [comment]
Not sure if it can cover all Administration Functions. I am only sure it can solve "xxx_size" functions.
c.c. @yezizp2012 @xiangjinwu

**Comment by TennyZhuang** [comment]
#11522

**Comment by st1page** [comment]
need discuss if we still need this after https://github.com/risingwavelabs/rfcs/pull/75
