### ISSUE TITLE
too hacky: check if an executor is sink or mv or not

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#11772]
https://github.com/risingwavelabs/risingwave/blob/main/src/stream/src/executor/wrapper/trace.rs#L42

Now it checked by the identity string, better enforced by type.

Was doing for a quick fix

**Comment by taytzehao** [comment]
I would like to take on this please

**Comment by lmatz** [comment]
@taytzehao thanks a lot, please go ahead

**Comment by taytzehao** [comment]
Create another unit variant enum that aggregates all the types of executors, create a `kind` key in `ExecutorInfo` and inject the respective variants into each initialization of `ExecutorInfo`.  My concern here is that it would add more boilerplate, any concern from this approach?

**Comment by lmatz** [comment]
Hi @taytzehao 

I just found there is a new PR: #12622, which seems to eliminate the need for refactoring, as it introduces two independent metrics
