### ISSUE TITLE
feat(compaction): support batch get compact task

### ISSUE THREAD

**Issue by Li0k** [risingwavelabs/risingwave#11790]
### Is your feature request related to a problem? Please describe.

The computing resource consumption of Picker is proportional to the number of files. Therefore, when the amount of files is large, it will cause a large waste of resources to perform a complete calculation and only obtain one task.

### Describe the solution you'd like

Based on the Pull Based model, it is possible to specify the number of compact tasks required at a time. Therefore it is possible to batch fetch tasks directly in a round of computation to reduce the consumption of resources.

**Comment by hzxa21** [comment]
@Li0k  Is this issue still planned?

**Comment by Li0k** [comment]
> @Li0k Is this issue still planned?

move it to next release

**Comment by hzxa21** [comment]
@hzxa21 Any updates?

**Comment by Li0k** [comment]
The batch get task across compaction groups has been implemented, further implementation of the batch get task within compaction groups will require code refactoring, and I would like to keep this issue.
