### ISSUE TITLE
perf(expr): switching jsonb to flat representation

### ISSUE THREAD

**Issue by wangrunji0408** [risingwavelabs/risingwave#11805]
### Is your feature request related to a problem? Please describe.

Currently, we use [`serde_json::Value`](https://docs.rs/serde_json/latest/serde_json/enum.Value.html) as the internal representation of our JSONB data type. For deeply nested JSON values, this representation results in many memory allocations. Borrowing the idea from array storage, we can store the content of a JSON value or many JSON values within an array in a flat, continuous buffer. This approach can significantly reduce memory allocation, improve data locality, and consequently improve performance.

The nested and flat representation of a JSON value can be shown as below:

![flat-json1](https://github.com/risingwavelabs/risingwave/assets/15158738/54f55c99-2e62-4c14-a043-16966a8d38f2)

### Describe the solution you'd like

I have already developed a [flat-json](https://github.com/wangrunji0408/flat-json/tree/main) library as a demo, and then written some microbenchmarks to compare its performance with serde-json and the [jsonb](https://github.com/datafuselabs/jsonb) library from Databend. The result shows that the overhead of access operations can be only 30% of serde-json. Therefore, this optimization should be beneficial in scenarios with heavy json operations.

```
[json['key'] for json in array]/flat_json
                        time:   [30.070 µs 30.231 µs 30.877 µs]

[json['key'] for json in array]/serde_json
                        time:   [95.857 µs 95.935 µs 96.249 µs]

[json['key'] for json in array]/jsonb
                        time:   [80.281 µs 81.080 µs 84.278 µs]
```

Besides, using a single buffer to store a column of JSON values can lead to further optimization. Redundant strings within these JSONs can be deduplicated and stored only once. Since a column of JSON values often shares a similar schema, this optimization should effectively save space.

![flat-array](https://github.com/risingwavelabs/risingwave/assets/15158738/2536896a-ef0e-4522-bb18-254c2775bf54)

### Describe alternatives you've considered

We could also consider using datebend's [jsonb](https://github.com/datafuselabs/jsonb) library. However, after some investigation, I found it might be necessary to do some adjustment before using it. For example, their function API does not support writing generated values to a provided buffer, leading to additional memory allocation. I am also not sure whether they followed the jsonb specification of PostgreSQL. But this doesn't seem important since we only use it for internal representation. Personally, I prefer using their jsonb library if possible.

### Additional context

cc @xiangjinwu @TennyZhuang

**Comment by b41sh** [comment]
Hi, @wangrunji0408 I'm the maintainer of databend jsonb, thanks for your research.
The implementation of databend jsonb is basically the same as the PostgreSQL specification. Functions are still under development, and the API can be modified according to actual needs. We also plan to optimize performance and add more documentation. If you decide to use databend jsonb, I'm willing to help with the migration if needed.

**Comment by b41sh** [comment]
> Wondering if you have benchmarked accessing nested fields, e.g. json->>'key1'->>'key2' and if the performance improves as well.

Good advice, I will add some benchmarks for jsonb

**Comment by wangrunji0408** [comment]
Hi @b41sh. Thank you for making this crate! Looks like we can build the jsonb library together since our goals are the same. I may propose some designs and PRs later. Please help review then. 🥰

**Comment by wangrunji0408** [comment]
> @wangrunji0408 Wondering if you have benchmarked accessing nested fields, e.g. json->>'key1'->>'key2' and if the performance improves as well.

Not yet. But I think the optimizer should rewrite it to a single access via jsonpath, so that the intermediate result can be avoided to improve performance.
