### ISSUE TITLE
Improve streaming `Union`'s implementation for large fields

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#11821]
Original title: Discussion: How to process large fields (e.g. JSONB) in `UNION`?

Currently, `union` is implemented with `HashAgg` using all columns as group key. However, because `HashAgg` must hold all "dirty" data in the current epoch, if some of the fields contain large values such as JSON, text or binary, the memory consumption can be too large.

> In case that you are not familiar: `union` basically means `union all` and then `distinct`

Here are some possible solutions

1. Prohibit `union` at all and force users to use distinct
   - Besides, prohibit any JSON columns in `distinct`
2. Move large fields from key into value and use some 128/256-bit hash as key. Unfortunately, this **can't solve the problem** because values are also held in memory.
3. Use a dedicated operator to execute `Union` and `Distinct` and now it can store the key only, because the upstream incomming event always know the values.

**Comment by fuyufjh** [comment]
Well, the "dedicated operator" mentioned in 3 is actually pretty similar with [`AppendOnlyDedupExecutor`](https://github.com/risingwavelabs/risingwave/blob/297417aa175188fe6c0c7f75cb4d8b2597a80e0c/src/stream/src/executor/dedup/append_only_dedup.rs#L39).

We can improve the `AppendOnlyDedupExecutor` by

1. Let it non-"append-only" by introducing an additional `count` column in the state. If a row appears in multiple times, we can record its count so that the deduplication can work correctly.
2. For long keys such as JSONB we may just store a 128/256-bit hash instead of the real values. This can reduce the state & cache size a lot and solve the OOM problem.
3. Additionally, we can prohibit any JSON columns in `group by`. Because `distinct` and `union ` are processed by this `DedupExecutor`, plus the point 2, there is no problem for large keys.

**Comment by st1page** [comment]
LGTM:
Tracking: 
- [ ] make `AppendOnlyDedupExecutor` can handle non-append only stream https://github.com/risingwavelabs/risingwave/blob/151ffd2ac21f8d0b260b4dc38ba3772cf8324b24/src/stream/src/executor/dedup/append_only_dedup.rs#L50
- [ ] 256-bit hash optimization: implement an `IrreversibleHashKey` which just supports `serialize` but not `deserialize`. use current `HashKey` implementation for most of the datypes. Use 256-bit hash signiture for large `jsonb`, `bytea`, `text` and `varchar`. https://github.com/risingwavelabs/risingwave/blob/151ffd2ac21f8d0b260b4dc38ba3772cf8324b24/src/common/src/hash/key_v2.rs#L221
- [ ] use `IrreversibleHashKey` in `StreamDedupExecutor`
- [ ] implement a `AggToDedup` rule, change `LogicalAgg` to `LogicalDedup` when there is no aggregator.
- [ ] add non-append-only version `LogicalDedup::to_stream` https://github.com/risingwavelabs/risingwave/blob/54928c73fb603b2c721a1f1d88f15900f13b81dc/src/frontend/src/optimizer/plan_node/logical_dedup.rs#L110

**Comment by stdrc** [comment]
I'll do this https://github.com/risingwavelabs/risingwave/issues/11849 soon. Seems it can help?

**Comment by fuyufjh** [comment]
> I'll do this #11849 soon, which introduces memory-consumption-based HashAgg flushing. Seems it can help?

I think both can be done. This issue focuses on `distinct` operator and it will be a new streaming executor, separated from `HashAgg`.

> Use a dedicated operator to execute Union and Distinct and now it can store the key only, because the upstream incomming event always know the values.

**Comment by stdrc** [comment]
> 1. Let it non-"append-only" by introducing an additional `count` column in the state. If a row appears in multiple times, we can record its count so that the deduplication can work correctly.

I found an issue of this: For our existing AppendOnlyDedup, the state table need not to contain all of its upstream fields, though it does, but only need to contain the distinct key columns, given that we don't implement any "conflict behavior" for it. While OTOH, the to-be-introduced general Dedup, need all upstream fields and `row count` column in its state table, and also in its executor cache. So the performance may degrade, hence we cannot simply replace AppendOnlyDedup with Dedup, IMO we can only introduce general Dedup to replace GroupTopN and HashAgg and the performance improvement in this latter case is still to be doubted.

**Comment by fuyufjh** [comment]
> While OTOH, the to-be-introduced general Dedup, need all upstream fields and `row count` column in its state table, and also in its executor cache.

Why? I thought the general dedup only needs the hash (and a `count`) as well, because the incoming event always carries all columns.

**Comment by stdrc** [comment]
> > While OTOH, the to-be-introduced general Dedup, need all upstream fields and `row count` column in its state table, and also in its executor cache.
> 
> Why? I thought the general dedup only needs the hash (and a `count`) as well, because the incoming event always carries all columns.

For instance, if we have `distinct_columns = [0]` (it seems that we have e2e tests going the path where `distinct columns != all columns`, and to me it makes sense to not depend on the equality), then we have a chunk:

```
+ 1 10 100 -> + 1 10 100
+ 1 11 101 -> no update
- 1 10 100 -> no update
- 1 11 101 -> - 1 10 100 
```

We must know the previously emitted `Insert` row so that we can correctly emit the `Delete`.

**Comment by fuyufjh** [comment]
Indeed. I overlooked the case that `distinct_columns` is a subset of all columns i.e. `distinct on (<column_list>)`

Actually, in your example, the 3rd event should emit an update

```
+ 1 10 100 -> + 1 10 100
+ 1 11 101 -> no update
- 1 10 100 -> - 1 10 100 , + 1 11 101
- 1 11 101 -> + 1 11 101
```

But to achieve this, it needs to remember `1 11 101`, which leads to the same conclusion.

**Comment by stdrc** [comment]
> Actually, in your example, the 3rd event should emit an update
> 
> ```
> + 1 10 100 -> + 1 10 100
> + 1 11 101 -> no update
> - 1 10 100 -> - 1 10 100 , + 1 11 101
> - 1 11 101 -> - 1 11 101
> ```

So basically you mean we need have the `keep the latest` semantics in Dedup?

**Comment by fuyufjh** [comment]
> So basically you mean we need have the `keep the latest` semantics in Dedup?

No 👀  `1 10 100` was deleted so it needs to replaced `1 10 100` to `1 11 101` for downstream, right?

**Comment by stdrc** [comment]
> > So basically you mean we need have the `keep the latest` semantics in Dedup?
> 
> No 👀 `1 10 100` was deleted so it needs to replaced `1 10 100` to `1 11 101` for downstream, right?

Ohhh, got it. Yes! But, if we have

```
+ 1 10 100 -> + 1 10 100
+ 1 11 101 -> no update
+ 1 12 102 -> no update
- 1 10 100 -> ?
```

Which one should be uses as the new value?

**Comment by fuyufjh** [comment]
> > > So basically you mean we need have the `keep the latest` semantics in Dedup?
> > 
> > 
> > No 👀 `1 10 100` was deleted so it needs to replaced `1 10 100` to `1 11 101` for downstream, right?
> 
> Ohhh, got it. Yes! But, if we have
> 
> ```
> + 1 10 100 -> + 1 10 100
> + 1 11 101 -> no update
> + 1 12 102 -> no update
> - 1 10 100 -> ?
> ```
> 
> Which one should be uses as the new value?

Either is okay, I think.

By the way, this example inspires me that we need to keep all rows (instead of one row + count). In this way, it's basically the same cost of `HashAgg`.

**Comment by stdrc** [comment]
> By the way, this example inspires me that we need to keep all rows (instead of one row + count). In this way, it's basically the same cost of `HashAgg`.

Yes, also almost the same as GroupTopN for normal `distinct` cases.

**Comment by fuyufjh** [comment]
Anyway, it's still doable for `union` as well as `distinct` without `on (<column_list>)`
