### ISSUE TITLE
bug(test): minio error due to insufficient resource

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#11863]
### Describe the bug

When I was trying to merge a trivial PR into main branch, the e2e sink test failed.

[minio.txt](https://github.com/risingwavelabs/risingwave/files/12425624/minio.txt)

[compute-node-5688.txt](https://github.com/risingwavelabs/risingwave/files/12425623/compute-node-5688.txt)

https://buildkite.com/risingwavelabs/pull-request/builds/30177#018a25db-4102-4f7f-81ce-cd2ce0b11d81

### Error message/log

```text
from compute node:
`risingwave_stream::task::stream_manager: actor exit actor=114 error=Executor error: Storage error: Hummock error: ObjectStore failed with IO error Internal error: streaming error.`

from minio:
`Error: Unable to write all the data to client: Storage resources are insufficient for the read operation hummock001/hummock_001/7/211.data (*fmt.wrapError)`
```

**Comment by zwang28** [comment]
@wenym1

**Comment by wenym1** [comment]
Looks like caused by temporarily unstable CI env.

**Comment by wenym1** [comment]
Retry the CI can pass.

https://buildkite.com/risingwavelabs/pull-request/builds/30177#_
