### ISSUE TITLE
Validate delete/update message on MaterializeExecutor for table sources

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#1186]
Design doc: https://singularity-data.quip.com/KlRvAysabUma/Handle-Concurrent-Writes-Correctly

- [ ] Add a boolean flag `validate` in the plan of `MaterializeNode`
- [ ] Support validation in `MaterializeExecutor`

**Comment by fuyufjh** [comment]
Any updates? @wcy-fdu @BugenZhao

**Comment by skyzh** [comment]
Already done with state table sanity check.

**Comment by skyzh** [comment]
... which is enabled by default in debug mode.

**Comment by fuyufjh** [comment]
> Already done with state table sanity check which is enabled by default in debug mode.

Maybe somehow different. This issue tries to automatically silently "fix" the conflicts without any consistency guarantee.

**Comment by wcy-fdu** [comment]
completed
