### ISSUE TITLE
bug: cannot define watermark on protobuf source

### ISSUE THREAD

**Issue by tabVersion** [risingwavelabs/risingwave#11877]
### Describe the bug

is it possible to use watermarks with kafka source and protobuf format ? watermark seems to be defined in the user defined schema but I can't define it when using protobuf.

ERROR: ExecuteError: Protocol error: User-defined schema is not allowed with FORMAT PLAIN ENCODE PROTOBUF

https://risingwave-community.slack.com/archives/C03BW71523T/p1692623840478209

**Comment by wugouzi** [comment]
User used wrong sql.
