### ISSUE TITLE
Saving CI costs by reducing tests run per PR

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#11879]
If we are more selective towards which tests run per PR.
- We can save CI costs.
- We can reduce CI runtime.
- Less likely to hit job cancellations.

I propose the following changes:
1. Consolidate a list of critical PRs to run.
2. These tests can still be triggered if labels are added for the PR. Or if PR title contains `feat(XXX) component`. e.g. `feat(sink): some new feature` or `ci/run-sink-tests` label.
3. These tests will still run in `main-cron`.

To me here are the most critical, seems like the rest can be made to run as needed:
- end-to-end test
- unit test
- check
- docslt
- regress test

Feel free to edit it if you feel some test is important, as I may not have full knowledge of it, e.g. connector node tests. I think the rest can be enabled automatically based on PR title / files modified.

And when a new test is added to PR workflow, we should reconsider if it can be made to run on demand instead.

**Comment by lmatz** [comment]
As we started to use merge queue, CI per PR and CI on the `main` branch is sort of duplicated.

Thinking if we just merge them into one (pick the one with more tests with longer duration)

Orthogonal to the ideas in the this post
