### ISSUE TITLE
The nexmark q19 & q20 performance degradation in last two days

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#11884]
### Describe the bug

The last two days daily performance execution results show we have the nexmark q19 & q20 performance degradation more than 20% comparing to the avg source throughput of last 10 days.

image nightly-20230824
```
| BENCHMARK NAME                                                  | EXECUTION ID | STATUS     | FLUCTUATION OF BEST | FLUCTUATION OF LAST 10 DAYS |
| nexmark-q19-blackhole-medium-1cn                                |         9637 | Negative   | -66.50%             | -21.07%                     |
| nexmark-q20-blackhole-medium-1cn                                |         9645 | Negative   | -44.90%             | -22.96%                     |
```

image nightly-20230823
```
| BENCHMARK NAME                                                  | EXECUTION ID | STATUS     | FLUCTUATION OF BEST | FLUCTUATION OF LAST 10 DAYS |
| nexmark-q19-blackhole-medium-1cn                                |         9533 | Negative   | -68.28%             | -27.74%                     |
| nexmark-q19-blackhole-medium-1cn-affinity                       |         9534 | Negative   | -59.71%             | -10.30%                     |
| nexmark-q20-blackhole-medium-1cn                                |         9539 | Negative   | -42.81%             | -22.72%                     |
| nexmark-q20-blackhole-medium-1cn-affinity                       |         9540 | Negative   | -38.22%             | -15.80%                     |
```

You can check this [avg source throughput history dashboard](http://metabase.risingwave-cloud.xyz/dashboard/241-nexmark-blackhole-1cn-anti-affinity-rw-avg-source-throughput?namespace=daily) for more historical data.

**Comment by lmatz** [comment]
![SCR-20230824-hxv](https://github.com/risingwavelabs/risingwave/assets/5791930/3349beb8-ebc6-4259-8356-f97e2e35fda6)
![SCR-20230824-hxy](https://github.com/risingwavelabs/risingwave/assets/5791930/e34cde52-710e-4768-b47e-afdc45f073c6)
![SCR-20230824-i36](https://github.com/risingwavelabs/risingwave/assets/5791930/83ae3fd5-a16c-4a71-9715-59c0a3e04dd2)
![SCR-20230824-i39](https://github.com/risingwavelabs/risingwave/assets/5791930/d81c49f6-a6f6-4e63-a5df-f6977f42f595)


Likely to be changes in the compaction strategy.
The slower ones have large size of L0.

**Comment by cyliu0** [comment]
Another [huge performance degradation happened on nexmark q19](http://metabase.risingwave-cloud.xyz/question/872-nexmark-q19-blackhole-medium-1cn-avg-source-output-rows-per-second-rows-s-history-thtb-210?start_date=2023-07-08).

**Comment by lmatz** [comment]
> Another [huge performance degradation happened on nexmark q19](http://metabase.risingwave-cloud.xyz/question/872-nexmark-q19-blackhole-medium-1cn-avg-source-output-rows-per-second-rows-s-history-thtb-210?start_date=2023-07-08).

yesterday two perf-related PR:
1. https://github.com/risingwavelabs/risingwave/pull/11576
2. https://github.com/risingwavelabs/risingwave/pull/11950

Likely to be 1, as 2 has been verified with turning off `cache refill`: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1693888963878&to=1693892335149&var-namespace=benchmark-yao&var-instance=benchmark-risingwave&var-node=All&var-job=All&var-table=All

**Comment by stdrc** [comment]
> > Another [huge performance degradation happened on nexmark q19](http://metabase.risingwave-cloud.xyz/question/872-nexmark-q19-blackhole-medium-1cn-avg-source-output-rows-per-second-rows-s-history-thtb-210?start_date=2023-07-08).
> 
> yesterday two perf-related PR:
> 
> 1. [perf(over window): locality-based range cache for general over window executor #11576](https://github.com/risingwavelabs/risingwave/pull/11576)
> 2. [feat(hummock): refill cache before apply version delta #11950](https://github.com/risingwavelabs/risingwave/pull/11950)
> 
> Likely to be 1, as 2 has been verified with turning off `cache refill`: [grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1693888963878&to=1693892335149&var-namespace=benchmark-yao&var-instance=benchmark-risingwave&var-node=All&var-job=All&var-table=All](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1693888963878&to=1693892335149&var-namespace=benchmark-yao&var-instance=benchmark-risingwave&var-node=All&var-job=All&var-table=All)

The Sep 4th degradation is indeed cause by #11576, and I've fixed it in #12093.

**Comment by lmatz** [comment]
Thanks, the second degradation is clear and fixed now.

We now wait for the fix of compaction strategy.

**Comment by Li0k** [comment]
In recent tests, we have found that base level compaction is unstable.

Intuitively, the base level compaction has a parallelism of 1, which corresponds to a partition misalignment between l0 and base level sst.

This https://github.com/risingwavelabs/risingwave/pull/12280 removes the "direct convert of tier compaction picker", which ensures that overlapping -> non-overlapping has gone through compaction at least once. After compaction, the new sst is cut according to the configured patrition, which ensures that the partitions are aligned to each other, thus improving parallelism.

**Comment by hzxa21** [comment]
@Li0k  Can we verify that this issue has been resolved with the recent fixes?

**Comment by cyliu0** [comment]
@hzxa21 According to the daily performance benchmark testing, it might be fixed.
<img width="484" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/cda68d6d-84c7-4f6a-9958-fc84caecbd47">
