### ISSUE TITLE
Performance regression of `block_iter` benchmark

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#11885]
### Describe the bug

<img width="1248" alt="Screenshot 2023-08-25 at 10 23 07 AM" src="https://github.com/risingwavelabs/risingwave/assets/47273164/c401474d-df70-447e-ae73-fa6c106c22c4">

http://metabase.risingwave-cloud.xyz/question/2524-micro-benchmark-block-iter-next-10-tables-x-100-keys-execution-duration-ns-history-tltb-241?start_date=2023-07-08

**Comment by kwannoel** [comment]
`block_iter_prev` as well http://metabase.risingwave-cloud.xyz/question/2510-micro-benchmark-block-iter-prev-10-tables-x-100-keys-execution-duration-ns-history-tltb-242?start_date=2023-07-08

**Comment by hzxa21** [comment]
I have been monitoing the results of the microbench for two weeks. The results fluctuates by nature so I believe this is not a regression. I will close the issue for now.
