### ISSUE TITLE
Parse error: cannot cast jsonb null to type number

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#11881]
### Describe the bug

Too many lines in logs. Should this not be an error? 

### Error message/log

```log
{"timestamp":"2023-08-24T13:41:10.828743568Z","level":"ERROR","fields":{"message":"Compute error: Parse error: cannot cast jsonb null to type number, executor: ProjectExecutor 179200000002"},"target":"risingwave_stream::executor::actor","span":{"actor_id":6034,"otel.name":"ProjectExecutor 179200000002 (actor 6034, operator 2)","name":"executor"},"spans":[{"actor_id":6034,"curr_epoch":4957750568484864,"otel.name":"Actor 6034","prev_epoch":4957750502948864,"name":"actor"},{"actor_id":6034,"otel.name":"MaterializeExecutor 179200000003 (actor 6034, operator 3)","name":"executor"},{"actor_id":6034,"otel.name":"ProjectExecutor 179200000002 (actor 6034, operator 2)","name":"executor"}]}
```

[Explore-logs-2023-08-25 00_34_10.txt.zip](https://github.com/risingwavelabs/risingwave/files/12431642/Explore-logs-2023-08-25.00_34_10.txt.zip)

**Comment by xiangjinwu** [comment]
> Should this not be an error?

It is an error in PostgreSQL:
```
test=# select 'null'::jsonb::int;
ERROR:  cannot cast jsonb null to type integer
```

For now, a case-when on `jsonb_typeof` can be used.
To provide a shorter syntax, we may support #4458 `try_cast` or `err_as_null`

**Comment by fuyufjh** [comment]
I see. Then we might need a way to suppress warnings (as a mitigation). More importantly, the Cloud UI side needs a way to report the errors to users.
