### ISSUE TITLE
`table is in creating procedure` but `rw_ddl_progress` does not show its progress

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#11898]
### Describe the bug

I cannot reproduce it, but I did see it several times in the users' case.
And it will be completed successfully at the end.

**Comment by BugenZhao** [comment]
`table is in creating procedure` is managed by `DatabaseManager`, while `rw_ddl_progress` is provided by `CreateMviewProgressTracker`. There could be some races due to different sources of truth, but I guess records `rw_ddl_progress` should eventually appear as it determines when the creation is done. 🤔

Fortunately, this might be solved fundamentally after the SQL backend refactor from @yezizp2012 .

**Comment by KeXiangWang** [comment]
@lmatz @yezizp2012 Any progress on this bug? One user is complaining about this.

**Comment by kwannoel** [comment]
Do we have some more details about this bug? Like what sort of queries can lead to it? If it is create table with source I don't think there's `CreateMaterializedViewProgress` for it, which is the underlying mechanism we use to record ddl progress. We only apply that to those which use `StreamTableScan`.

**Comment by kwannoel** [comment]
```
dev=> EXPLAIN (verbose) CREATE TABLE IF NOT EXISTS kafka_source
(
 action varchar,
 user_id integer,
 obj_id integer,
 name varchar,
 page_id integer,
 age integer
)
WITH (
 connector='kafka',
 topic='backwards_compat_test_kafka_source',
 properties.bootstrap.server='localhost:29092',
 scan.startup.mode='earliest',
) FORMAT PLAIN ENCODE JSON;
                                                                             QUERY PLAN                                                                              
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 StreamMaterialize { columns: [action, user_id, obj_id, name, page_id, age, _row_id(hidden)], stream_key: [_row_id], pk_columns: [_row_id], pk_conflict: Overwrite }
 └─StreamExchange { dist: HashShard(_row_id) }
   └─StreamRowIdGen { row_id_index: 6 }
     └─StreamDml { columns: [action, user_id, obj_id, name, page_id, age, _row_id] }
       └─StreamSource { source: kafka_source, columns: [action, user_id, obj_id, name, page_id, age, _row_id] }
(5 rows)
```

**Comment by yezizp2012** [comment]
> @lmatz @yezizp2012 Any progress on this bug? One user is complaining about this.

Was the job eventually completed in the user's case?
Actually this's not a bug as explained by @BugenZhao before. Creating a streaming job involves several steps. Progress will only be made when the job is reading upstream data. There will be no progress before issuing a barrier or after completing data retrieval.

**Comment by KeXiangWang** [comment]
With my experiment, I created a table on a source that contains 10M events. The `CREATE TABLE` message is returned immediately. But It took a while to really consume all the data in the source. And within this period, I got no info within `rw_ddl_progress`.

**Comment by KeXiangWang** [comment]
The user is asking for a method to show the progress of data consumption of `CREATE TABLE`. It may not be this issue and can be more complicated, as it needs to know how many events are left in the source.

**Comment by yezizp2012** [comment]
> With my experiment, I created a table on a source that contains 10M events. The `CREATE TABLE` message is returned immediately. But It took a while to really consume all the data in the source. And within this period, I tried serveral times but got no info within `rw_ddl_progress`. Is this expected?

Yes, this is expected. The ddl progress tracker is only available for `Materialized view` and `Sink`. `Table` and `Table` with a source connector will be created and return immediately. Then it will starts to consume the data.

> The user is asking for a method to show the progress of data consumption of CREATE TABLE. It may not be this issue and can be more complicated, as it needs to know how many events are left in the source.

For this case, now we can get the split information by query the source internal table of it.

**Comment by KeXiangWang** [comment]
Is there an available API or tool for now?

**Comment by yezizp2012** [comment]
> Is there an available API or tool for now?

Yes, you can get the internal table list by `SHOW INTERNAL TABLES LIKE '__internal_{table_name}%'` and directly query on the source state table.

**Comment by lmatz** [comment]
> Was the job eventually completed in the user's case?

It was completed. Everything is normal besides no info in the rw_ddl_progress.

I cannot remember exactly the case, but I think we did wait for some minutes, e.g. 5~10 minutes, before we can query the MV.

We can re-open when the issue happens again.
