### ISSUE TITLE
bug: actor exit on aggretate or table (set-returning) function error

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#11915]
### Describe the bug

We implemented error tolerance in streaming for normal expressions in #4625. However, special expr-like structures including aggregate or set-returning functions can also produce evaluation errors. These are currently not tolerated and cause actor exit.

### To Reproduce

```
create table t (v decimal);

create materialized view mv1 as select generate_series(1.0, 2.0, v) from t;
insert into t values (0); -- Invalid parameter step: step size cannot equal zero

create materialized view mv2 as select sum(v) from t;
insert into t values (4e28);
insert into t values (4e28); -- Numeric out of range
```

### Expected behavior

Not sure. For set-returning function, maybe output 0 rows. For aggregate function, maybe return `null`.

### Additional context

Inspired by #11905, which signifies the difference in evaluation of normal exprs and special expr-like ones.

#11586 points out a limitation / error in existing error tolerance of normal expr.

**Comment by xiangjinwu** [comment]
Seems same as #11256

**Comment by fuyufjh** [comment]
related #12474

**Comment by fuyufjh** [comment]
See https://github.com/risingwavelabs/risingwave/issues/12474 https://github.com/risingwavelabs/risingwave/issues/11256

**Comment by fuyufjh** [comment]
As the table (set-returning) function's has been fixed by https://github.com/risingwavelabs/risingwave/pull/17156, let me close this issue now. While for aggretate functions, let's create another issue to note down.

**Comment by xiangjinwu** [comment]
Normal ExprErrors inside ProjectSet are not handled by #17156:

```
create table t(x varchar);

create materialized view mv as select x, generate_series(1, 2, x::int) from t;

insert into t values ('a');
```
