### ISSUE TITLE
refactor(state table): use memcpmarble's max value to encoding instead hack with NULL byte+1

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#11912]
https://github.com/risingwavelabs/risingwave/blob/615f873f85f2e2241be76b92d6676055b371f2c2/src/stream/src/common/table/state_table.rs#L1033-L1065

**Comment by fuyufjh** [comment]
?

**Comment by st1page** [comment]
close after https://github.com/risingwavelabs/risingwave/pull/14526
