### ISSUE TITLE
bug(test): test_task_abort_for_block seems stuck

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#11979]
### Describe the bug

`test_task_abort_for_block` is flaky.

https://buildkite.com/risingwavelabs/pull-request/builds/30598#018a4970-5820-4268-9068-19956e2c67b9

  | SLOW [>510.000s] risingwave_batch task::task_manager::tests::test_task_abort_for_block
  | SLOW [>515.000s] risingwave_batch task::task_manager::tests::test_task_abort_for_block
  | SLOW [>520.000s] risingwave_batch task::task_manager::tests::test_task_abort_for_block
  | SLOW [>525.000s] risingwave_batch task::task_manager::tests::test_task_abort_for_block
  | SLOW [>530.000s] risingwave_batch task::task_manager::tests::test_task_abort_for_block
  | SLOW [>535.000s] risingwave_batch task::task_manager::tests::test_task_abort_for_block

**Comment by zwang28** [comment]
@ZENOTME

**Comment by BugenZhao** [comment]
This is interesting. An async task running a busy `loop {}` cannot be canceled in theory, no matter how we implement the shutdown logic. So the only possibility of previous successes is that the `execute` is not actually called.

Maybe we should remove this test.

**Comment by zwang28** [comment]
also test_task_abort_for_busy_loop

**Comment by liurenjie1024** [comment]
I will take a look

**Comment by zwang28** [comment]
To reproduce stuck `test_task_abort_for_busy_loop`, add `tokio::time::sleep(Duration::from_secs(3)).await;` after `manager.fire_task_for_test(&task_id, plan).await.unwrap();`

**Comment by xxchan** [comment]
This occurs very frequently. 

<img width="1674" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/9416e0a4-7543-4439-a7f0-e253d44b26d9">

**Comment by BugenZhao** [comment]
I've confirmed that the task is actually stuck at sending data chunks to the downstream. The size of the channel is by default 64 chunks, and we don't have a "blackhole sink" in this test.

https://github.com/risingwavelabs/risingwave/blob/13905e2314ffe2844a2f31923166b07d97c3c7fc/src/batch/src/task/task_execution.rs#L609

**Comment by BugenZhao** [comment]
> To reproduce stuck `test_task_abort_for_busy_loop`, add `tokio::time::sleep(Duration::from_secs(3)).await;` after `manager.fire_task_for_test(&task_id, plan).await.unwrap();`

I guess this is necessary for a correct test case. Actually, every successful run now does not even start the executor.
