### ISSUE TITLE
bug(sink): debezium format hardcodes `RisingWave` as db and table name

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#11989]
### Describe the bug

https://github.com/risingwavelabs/risingwave/blob/b70aa1770cc876b91eadc413e8d61f3ca35ab59b/src/connector/src/sink/utils.rs#L50-L53

https://debezium.io/documentation/reference/2.3/connectors/postgresql.html#postgresql-change-events-key
https://github.com/risingwavelabs/risingwave/blob/b70aa1770cc876b91eadc413e8d61f3ca35ab59b/src/connector/src/sink/utils.rs#L139

### Expected behavior

For db name, just get the real db name.

For table name, it may be a little bit tricky. Currently we support sink from a table, materialized view or an query. Maybe in the last case we can use the sink name instead. Not sure if sink name is less preferred compared to table/mv name when available.

### Additional context

Found this by reading the code. No one is complaining about it yet.

**Comment by fuyufjh** [comment]
@wugouzi Please take a look ❤️
