### ISSUE TITLE
Risingwave doesn't throw error when `server.id` in mysql cdc is incorrect.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#12025]
### Describe the bug

When creating a mysql cdc table, user fills in an incorrect `server.id`, risingwave failed silently in background, but didn't report any error. 

### Expected behavior

It's expected to report this error to user explicitly when `server.id` is misconfigured rather forcing user to find it in connector log.

**Comment by hzxa21** [comment]
@StrikeW Any updates?

**Comment by StrikeW** [comment]
> @StrikeW Any updates?

No yet.

**Comment by StrikeW** [comment]
https://github.com/risingwavelabs/risingwave/pull/13031#discussion_r1372777527

**Comment by hzxa21** [comment]
Done by #13031
