### ISSUE TITLE
Clickhouse Sink: cannot create sink to clickhouse table with materialized column

### ISSUE THREAD

**Issue by PierreNowak** [risingwavelabs/risingwave#12042]
### Describe the bug

let's say we have:
- a clickhouse table with (col1,col2,col3)
- a rw mv with (col1,col2,col3)

CREATE SINK works !

now we add a Materialized column to clickhouse:

    ALTER TABLE table1 ADD COLUMN created_at DateTime64(0) MATERIALIZED now()

SINK still works !

now we do:
- a clickhouse table with (col1,col2,col3)
- create the materialized column
- create the rw sink fails with:

    ERROR:  QueryError: internal error: Sink error: ClickHouse error: Schema len not match

### Error message/log

```text
ERROR:  QueryError: internal error: Sink error: ClickHouse error: Schema len not match
```

### To Reproduce

in rw
```sql
CREATE TABLE t6 (v1 int primary key, v2 bigint, v3 varchar);

CREATE MATERIALIZED VIEW mv6 AS SELECT * FROM t6;

```

in clickhouse
```sql
CREATE table demo_test(
    user_id Int32,
    target_id String,
    event_timestamp DateTime64,
)ENGINE = ReplacingMergeTree
PRIMARY KEY (user_id);

ALTER TABLE demo_test  ADD COLUMN created_at DateTime64(6) MATERIALIZED now()

```

back in rw

```sql
CREATE SINK s6 AS select mv6.v1 as v1, mv6.v2 as v2, mv6.v3 as v3 from mv6 WITH (
    connector = 'clickhouse',
    type = 'append-only',
    force_append_only='true',
    clickhouse.url = 'http://127.0.0.1:8123',
    clickhouse.user = 'default',
    clickhouse.password = '',
    clickhouse.database = 'default',
    clickhouse.table='demo_test',
);
```

    ERROR:  QueryError: internal error: Sink error: ClickHouse error: Schema len not match

### Expected behavior

I expect the sink to be created successfully no matter the number of materialized columns in the downstream table.

seems to work already when the SINK is created before MATERIALIZED COLUMNS are created.

### How did you deploy RisingWave?

tested on k8s & locally with risdev

### The version of RisingWave

                         version
    -------------------------------------------------
     PostgreSQL 9.5-RisingWave-1.1.0-alpha (unknown)

**Comment by lmatz** [comment]
> I expect the sink to be created successfully no matter the number of materialized columns in the downstream table.

For the columns specified in the downstream table without a `default `value but not in the materialized view, do you expect them to be filled in with `NULL`?

**Comment by PierreNowak** [comment]
hmm unsure here, clickhouse seems to fill unspecified columns on its own (see below). also Clickhouse can have different types like:  UInt32 or Nullable(UInt32). so if it's not Nullable you won't be able to fill with NULL.
    
    ip-192-168-1-208.ec2.internal :) insert into demo_test (v2,v3) VALUES (10000,10000)
    
    INSERT INTO demo_test (v2, v3) FORMAT Values
    
    Query id: 301f903c-1ad9-4c05-bc46-d41e7ae0aae4
    
    Ok.
    
    1 row in set. Elapsed: 0.004 sec.
    
    ip-192-168-1-208.ec2.internal :) SELECT * FROM demo_test where v2=10000
    
    SELECT *
    FROM demo_test
    WHERE v2 = 10000
    
    Query id: 2a6ad267-a6c9-491a-bf70-dc45bd4e8fdd
    
    ┌─v1─┬────v2─┬─v3────┐
    │  0 │ 10000 │ 10000 │
    └────┴───────┴───────┘
    
    1 row in set. Elapsed: 0.003 sec.
    
    ip-192-168-1-208.ec2.internal :) DESCRIBE TABLE demo_test;
    
    DESCRIBE TABLE demo_test
    
    Query id: 4569657f-0d49-4d97-93ed-228c98d24bc4
    
    ┌─name───────┬─type──────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
    │ v1         │ Int32         │              │                    │         │                  │                │
    │ v2         │ Int64         │              │                    │         │                  │                │
    │ v3         │ String        │              │                    │         │                  │                │
    │ created_at │ DateTime64(6) │ MATERIALIZED │ now()              │         │                  │                │
    └────────────┴───────────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘
    
    4 rows in set. Elapsed: 0.001 sec.

**Comment by xxhZs** [comment]
fix it https://github.com/risingwavelabs/risingwave/pull/12123.
