### ISSUE TITLE
Support `WITH ORDINALITY AS` with table functions

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#12043]
### Is your feature request related to a problem? Please describe.

https://www.postgresql.org/docs/current/queries-table-expressions.html#:~:text=If%20the%20WITH%20ORDINALITY%20clause%20is%20specified%2C%20an%20additional%20column%20of%20type%20bigint%20will%20be%20added%20to%20the%20function%20result%20columns.

examples:
```
SELECT * from unnest(array[array[14,41,7],array[54,9,49]]::int[])
   WITH ORDINALITY AS t(elts, num);
 elts | num 
------+-----
   14 |   1
   41 |   2
    7 |   3
   54 |   4
    9 |   5
   49 |   6
(6 rows)
```

The combination with `unnest` is the most urgent, if supporting `with ordinality` with different table functions make a difference and requires different implementation

**Comment by fuyufjh** [comment]
In streaming, there is no definition for ordering except explicitly specified `ORDER BY`. However, according to SQL standard, `ORDER BY` actually applies to the output of `WITH ORDINALITY AS t(elts, num)`:

```
test=# SELECT * from unnest(array[array[14,41,7],array[54,9,49]]::int[])
   WITH ORDINALITY AS t(elts, num);
 elts | num
------+-----
   14 |   1
   41 |   2
    7 |   3
   54 |   4
    9 |   5
   49 |   6
(6 rows)

test=# SELECT * from unnest(array[array[14,41,7],array[54,9,49]]::int[])
   WITH ORDINALITY AS t(elts, num) order by elts;
 elts | num
------+-----
    7 |   3
    9 |   5
   14 |   1
   41 |   2
   49 |   6
   54 |   4
(6 rows)
```

Let's ask for their original requirement.

**Comment by lmatz** [comment]
`num` output by `WITH ORDINALITY AS` is used in `ARRAY_AGG`'s `order by` clause

**Comment by fuyufjh** [comment]
> `num` output by `WITH ORDINALITY AS` is used in `ARRAY_AGG`'s `order by` clause

What's the input of their table functions?

**Comment by lmatz** [comment]
https://github.com/risingwavelabs/risingwave-customer-testcases/blob/main/e2etest/rippling/with_ordinality_as.sql#L14-L20

**Comment by fuyufjh** [comment]
I see... It's like a lateral join: for every outer side, the inner side will be a table generated by `UNNEST(...) WITH ORDINALITY`

Previously I was wondering what's the semantics of `WITH ORDINALITY AS` when input is not a constant. Should it be numbered since 1,2,3,... for all output or for output of one input row? Now I seem to have an answer:

If I understand correctly, after `ApplyProjectSetTransposeRule`, the `ProjectSet` carrying `UNNEST()` with be transposed through `Apply` and become a parent node, thus, its input will be multiple rows instead of a single value (i.e. an expression with correlated variable)

This implies that the correct way to number the ORDINALITY column is to restart for every row, for example

```
input
-----
[a,b,c]
[d,e,f]

unnest  ordinality
------------------------------
    a   1
    b   2
    c   3
    d   1
    e   2
    f   3
```

Cool, this would be simple to implement. It's still stateless.

cc. @chenzl25 Can you please help to review the part about unnesting? And if you have time, can you please take this issue ☺️

**Comment by chenzl25** [comment]
It seems like this `unnest` table function can refer to another table's column just like a lateral join but without the `lateral` syntax. Currently, RW would panic if the table function use other columns from the other arms of join directly. 

```sql
select * from t cross join unnest(t.arr)  WITH ORDINALITY AS x(elts, num);
```

I am not sure whether the above problem could be solved easily. Maybe users can rewrite their sql in this way.

```
select * from t, lateral ( select * from unnest(t.arr)) x;
```

The left one is to support `WITH ORDINALITY AS` for the table function. IIUC, `WITH ORDINALITY` can only be used with a table function. Our table function could be converted into a `ProjectSet` and it has an implicit row `projected_row_id`, it seems we can reuse this hidden column. I will investigate it later.

**Comment by xiangjinwu** [comment]
> It seems like this `unnest` table function can refer to another table's column just like a lateral join but without the `lateral` syntax.

Yes. It is [always](https://www.postgresql.org/docs/15/sql-select.html#:~:text=LATERAL%20can%20also%20precede%20a%20function%2Dcall%20FROM%20item%2C%20but%20in%20this%20case%20it%20is%20a%20noise%20word%2C%20because%20the%20function%20expression%20can%20refer%20to%20earlier%20FROM%20items%20in%20any%20case.) implicitly lateral.

> Currently, RW would panic if the table function use other columns from the other arms of join directly.

#9590 #11167

**Comment by chenzl25** [comment]
@xxchan it seems you have been following `WITH ORDINALITY AS` this issue https://github.com/risingwavelabs/risingwave/issues/11167 long time. Do you have any implementation ideas? 
The hidden column `projected_row_id ` of `ProjectSet` seems could be used to support this feature.

**Comment by chenzl25** [comment]
> > It seems like this `unnest` table function can refer to another table's column just like a lateral join but without the `lateral` syntax.
> 
> Yes. It is [always](https://www.postgresql.org/docs/15/sql-select.html#:~:text=LATERAL%20can%20also%20precede%20a%20function%2Dcall%20FROM%20item%2C%20but%20in%20this%20case%20it%20is%20a%20noise%20word%2C%20because%20the%20function%20expression%20can%20refer%20to%20earlier%20FROM%20items%20in%20any%20case.) implicitly lateral.
> 
> > Currently, RW would panic if the table function use other columns from the other arms of join directly.
> 
> #9590 #11167

Cool. It seems both issues already have been discovered and assigned. Let's do it recently, as users requested this feature.

**Comment by fuyufjh** [comment]
@chenzl25 @xiangjinwu Hey, may I ask what's the remaining work?

**Comment by chenzl25** [comment]
> @chenzl25 @xiangjinwu Hey, may I ask what's the remaining work?

We have encountered some issues in lateral join https://github.com/risingwavelabs/risingwave/issues/12258 , however, it is an independent issue with `WITH ORDINALITY AS`. We could support `WITH ORDINALITY AS` and fix the lateral join issue in parallel.

**Comment by xxchan** [comment]
I'm taking a look .

**Comment by chenzl25** [comment]
@xxchan would take the `WITH ORDINALITY` issue https://github.com/risingwavelabs/risingwave/issues/11167. 
After @xiangjinwu fixes the prerequisite issue https://github.com/risingwavelabs/risingwave/issues/12258. 
I would try to fix the left issues https://github.com/risingwavelabs/risingwave/issues/12238 related to the lateral join (even if this issue is not requested by our users).
