### ISSUE TITLE
Discussion: Auto streaming_parallelism

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#12058]
Noted down the discussion with @neverchanje here.

### Is your feature request related to a problem? Please describe.

The current design is that streaming tasks never scale up or scale out. The reason of such design is that we allow users to specify a particular parallelism for a materialized view, or even set parallelism for a certain fragment.

However, this also results in several cases that might be confusing to users:

- **(This is the one that @neverchanje wants to improve)** When a compute node is upgraded with more CPU cores, it will not be scheduled more parallelism (thus, no performance improvement in cluster level because of laggers)
- When a compute node shutdown deliberately, the cluster can not recover because the total parallelism is not enough.
- When a new compute node joined the cluster, it will not be scheduled any tasks unless new MV is created.

### Describe the solution you'd like

In order to handle the 2 conflicting requirements above, there is one way to let users choose between them.

We can reuse the `streaming_parallelism` session variable.

- **(New)** If `streaming_parallelism` is set to 0 i.e. `AUTO`, this MV will be auto-scaled in the future
- If `streaming_parallelism` is set to a positive integer number, it will be used as the parallelism and won't be auto-scaled.

An MV with `streaming_parallelism = AUTO` will always be scaled to max available CPU cores in cluster. Any manual scaling operations will change the `AUTO` to some other value.

Note that it slightly changed the semantic of `set streaming_parallelism = AUTO`. Currently, it means the `streaming_parallelism` is determined at creation (correct me if wrong); while afterwards, `streaming_parallelism` never determined but always guaranteed to fully utilize all CPU cores.

Furthermore, based on #11929, users are allowed to change the behavior after MV creation.

### Describe alternatives you've considered

I can't come up with any better ideas to reconcile the 2 requirements.

### Additional context

One controversy might be the choice of the global default streaming_parallelism. See also 
 https://github.com/risingwavelabs/risingwave/issues/10263. I prefer `Auto` here.

**Comment by hzxa21** [comment]
I am not opposed to doing auto scalling in the kernel side but there are several issues that struggle me:
1. What will the actor placment policy look like? Placing all paralliesms of a fragment evenly across all cores seems the simplest one but are we going to introduce more complicated ones in the kernel side in the future upon requests?
2. (somehow related to 1) Will cloud use the auto scalling and actor placement policy implemented in the kernel side by setting `streaming_parallelism = auto`? Or will cloud set `streaming_parallelism = const` and  has its own policy implemented? If it is the latter and `streaming_parallelism` is exposed to the user, what happen if the cloud scaling policy and kernel scaling policy conflict with each other.

**Comment by fuyufjh** [comment]
> 1. What will the actor placment policy look like? Placing all paralliesms of a fragment evenly across all cores seems the simplest one but are we going to introduce more complicated ones in the kernel side in the future upon requests?

AFAIK, most AP systems use this policy ("evenly across all cores"). At the moment, I don't think there will be any more strategy.

> 2. (somehow related to 1) Will cloud use the auto scalling and actor placement policy implemented in the kernel side by setting streaming_parallelism = auto? Or will cloud set streaming_parallelism = const and has its own policy implemented? If it is the latter and streaming_parallelism is exposed to the user, what happen if the cloud scaling policy and kernel scaling policy conflict with each other.

To be honest, the cloud team's progress is not as optimistic as we expected at one year ago when we designed the low-level scheduling API. From today's perspective, it may take a long time to accomplish that delicate design, and that's why I am thinking about simplifying it.

In my mind, if we adopt this RFC finally, the cloud platform's work would be very simple:

1. notify the beginning of scaling to meta node
   - pause stream
   - migrate out some actors
2. do the scaling in Kubernetes side
3. notify the end of scaling to meta node
   - resume stream

1 & 3 are optional, but may help to avoid interrupting streaming in some cases.

**Comment by fuyufjh** [comment]
Changed the title to make it more accurate and less terrifying 😄

**Comment by fuyufjh** [comment]
By the way, [From Parallel Unit to Ensemble](https://www.notion.so/risingwave-labs/From-Parallel-Unit-to-Ensemble-b0b780a332f147be8ca469162c43d3e6) is related and I think it should have higher priority, because 

1) It can also solve the customer's complaints “why my streaming is stopped?”
2) It's a refactoring of a defective design and can potentially fix some related issues

**Comment by twocode** [comment]
The proposal looks good to me. 

1. Even distribution is enough. Right now the manual scaling for cloud is also event distribution.
2. Cloud's scaling is more concerned about the strategy: timing to scale, repartitioning for individual fragments, and runtime placement.
    2.1 timing is about analyzing the metrics using some algorithms like DS2.
    2.2 repartitioning is about granular control based on back pressures and target throughput.
    2.3 runtime placement is about bin packing actors to specific pods.

Cloud does not have efforts to implement a decent strategy but `set stream_parallelism = auto` basically simplies the above three to a minimum level.

**Comment by BugenZhao** [comment]
I just want to confirm whether we will still insist on the low-level interfaces that support fine-grained placements based on fragment-level scheduling. Auto `streaming_parallelism` sounds like the most naive scaling strategy, and I believe it may only be suitable for certain deployments (for example, some users create hundreds of lightweight streaming jobs). I am concerned that incorporating this design into the RisingWave kernel may hinder us from implementing a more intelligent scaling strategy.

> To be honest, the cloud team's progress is not as optimistic as we expected at one year ago when we designed the low-level scheduling API.

> Cloud's scaling is more concerned about the strategy: timing to scale, repartitioning for individual fragments, and runtime placement.

I would say that in some sense, a better scaling strategy does not have to be coupled with Cloud deployment. Based on the metrics we collect on the kernel side, we can do almost everything except ask for physical resources from Kubernetes. If we decide to introduce a high-level scaling to the RisingWave kernel, I'd suggest making it a standalone service and we can evolve the strategy there.

**Comment by fuyufjh** [comment]
Regarding of the implementation, Here are some conclusion from offline discussions with @yezizp2012 and @BugenZhao:

- The whole design is similar to Flink's [Reactive Mode](https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/elastic_scaling/)
- We will keep the current design of low-level scheduling API
  - Note that the low-level scaling API is and will **never** be user-facing. The users are supposed to use high level APIs or simply set `streaming_parallelism = auto` to let RisingWave decide everything
- We will design an "auto scaler" **outside** the existing scheduling module. The auto scaler will 
  - Receive notifications of cluster configuration change such as worker heartbeat lost, worker join, etc.
  - Reschedule the actors accordingly by calling Meta's low-level scheduling API
