### ISSUE TITLE
feat: JDBC sink should updates rows in a batch way

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#12061]
### Is your feature request related to a problem? Please describe.

https://github.com/risingwavelabs/risingwave/blob/9c9c4a2815e68bfbd08c2fa6fb0f71a89442e058/java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java#L205-L234

For example, if we have 1024 rows per `write`, the current implementation would cause 1024 remote SQL executions sequentially.

**Comment by StrikeW** [comment]
Do you mean merge multiple insert/update statement to one statement? For example, `insert into t values (1); insert into values t (2);` => `insert into t values (1), (2);`

**Comment by chenzl25** [comment]
Yes. https://stackoverflow.com/questions/3784197/efficient-way-to-do-batch-inserts-with-jdbc
