### ISSUE TITLE
Fail to execute select and report incorrect error message

### ISSUE THREAD

**Issue by QuantumBear** [risingwavelabs/risingwave#12064]
### Describe the bug

**dev=> select * from business_custom_mv limit 10;
ERROR:  QueryError: internal error: Storage error: Hummock error: Barrier read is unavailable for now. Likely the cluster is recovering.

But cluster status is healthy.

```bash
(base) ➜  sql git:(main) ✗ docker compose ps -a
NAME                IMAGE                                                COMMAND                   SERVICE             CREATED             STATUS                 PORTS
compactor-0         ghcr.io/risingwavelabs/risingwave:nightly-20230828   "/risingwave/bin/ris…"    compactor-0         2 hours ago         Up 2 hours (healthy)   1260/tcp, 6660/tcp
compute-node-0      ghcr.io/risingwavelabs/risingwave:nightly-20230828   "/risingwave/bin/ris…"    compute-node-0      2 hours ago         Up 2 hours (healthy)   1222/tcp, 5688/tcp
connector-node      ghcr.io/risingwavelabs/risingwave:nightly-20230828   "/risingwave/bin/con…"    connector-node      2 hours ago         Up 2 hours             0.0.0.0:62727->50051/tcp, 0.0.0.0:62728->50052/tcp
etcd-0              quay.io/coreos/etcd:v3.5.7                           "/usr/local/bin/etcd…"    etcd-0              2 hours ago         Up 2 hours (healthy)   2379-2380/tcp, 0.0.0.0:2388-2389->2388-2389/tcp
frontend-node-0     ghcr.io/risingwavelabs/risingwave:nightly-20230828   "/risingwave/bin/ris…"    frontend-node-0     2 hours ago         Up 2 hours (healthy)   0.0.0.0:4566->4566/tcp
grafana-0           grafana/grafana-oss:latest                           "/run.sh"                 grafana-0           2 hours ago         Up 2 hours (healthy)   3000/tcp, 0.0.0.0:3001->3001/tcp
message_queue       docker.vectorized.io/vectorized/redpanda:latest      "/entrypoint.sh redp…"    message_queue       2 hours ago         Up 2 hours (healthy)   0.0.0.0:8081->8081/tcp, 0.0.0.0:9092->9092/tcp, 0.0.0.0:9644->9644/tcp, 0.0.0.0:29092->29092/tcp, 8082/tcp
meta-node-0         ghcr.io/risingwavelabs/risingwave:nightly-20230828   "/risingwave/bin/ris…"    meta-node-0         2 hours ago         Up 2 hours (healthy)   1250/tcp, 0.0.0.0:5690-5691->5690-5691/tcp
minio-0             quay.io/minio/minio:latest                           "/bin/sh -c '\nset -e…"   minio-0             2 hours ago         Up 2 hours (healthy)   0.0.0.0:9301->9301/tcp, 9000/tcp, 0.0.0.0:9400->9400/tcp
prometheus-0        prom/prometheus:latest                               "/bin/prometheus --c…"    prometheus-0        2 hours ago         Up 2 hours (healthy)   9090/tcp, 0.0.0.0:9500->9500/tcp
```

### To Reproduce

Can't reproduce

**Comment by fuyufjh** [comment]
```
ERROR: QueryError: internal error: Storage error: Hummock error: Barrier read is unavailable for now. Likely the cluster is recovering.
```

This error implies the cluster is under recovery. Some unexpected things (including network jitter, source/sink temporary unavailable, S3 storage issue, etc.) interrupted the streaming and RisingWave is trying to recover from last checkpoint. 

If that happens occasionally, you may ignore it. Otherwise, please check the logs from all nodes to find any suspicious events.

**Comment by liurenjie1024** [comment]
Some errors from meta logs(unable to attach full logs since it's too large), seems like caused by network error:

> 2023-09-04T13:45:16.54064689Z  WARN risingwave_meta::barrier: Failed to complete epoch 5020052064370688: Rpc error: gRPC error (Internal error): Actor 2028 exit unexpectedly: Executor error: Channel closed: exchange from actor 2029 to actor 2028 closed unexpectedly
>   backtrace of `StreamExecutorError`:
>    0: <risingwave_stream::executor::error::Inner as core::convert::From<risingwave_stream::executor::error::ErrorKind>>::from
>              at ./risingwave/src/stream/src/executor/error.rs:40:10
>    1: <T as core::convert::Into<U>>::into
>              at ./rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/convert/mod.rs:717:9
>    2: <risingwave_stream::executor::error::StreamExecutorError as core::convert::From<risingwave_stream::executor::error::ErrorKind>>::from
>              at ./risingwave/src/stream/src/executor/error.rs:143:34
>    3: <T as core::convert::Into<U>>::into
>              at ./rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/convert/mod.rs:717:9
>    4: risingwave_stream::executor::error::StreamExecutorError::channel_closed
>              at ./risingwave/src/stream/src/executor/error.rs:101:47
>    5: <risingwave_stream::executor::merge::SelectReceivers as futures_core::stream::Stream>::poll_next
>              at ./risingwave/src/stream/src/executor/merge.rs:332:49
>    6: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
>              at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
>    7: futures_util::stream::stream::StreamExt::poll_next_unpin
>              at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
>    8: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
>              at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:21
>    9: risingwave_stream::executor::merge::MergeExecutor::execute_inner::{{closure}}
>              at ./risingwave/src/stream/src/executor/merge.rs:122:49
>   10: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
>              at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.7/src/lib.rs:493:33
>   11: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
>              at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
>   12: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
>              at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
>   13: futures_util::stream::stream::StreamExt::poll_next_unpin
>              at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
>   14: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
