### ISSUE TITLE
warpstream + rw negative timestamp error

### ISSUE THREAD

**Issue by yufansong** [risingwavelabs/risingwave#12077]
### Describe the bug

According to this [docs](https://docs.warpstream.com/warpstream/how-to/use-warpstream-with-risingwave), deploy wrapstream and rw will meet problem. 
After check it locally, in risingwave, it will throw error because the timestamp is a negative one. The log shows below:
```
kafka_meta: Some(-6795364578871)
thread 'risingwave-streaming-actor' panicked at 'called `Result::unwrap()` on an `Err` value: "Can't cast negative integer to timestamp"', src/connector/src/parser/mod.rs:467:54
```

But in the cmd log shows by warpstream, the timestamp is a positive one. 
Not sure the bug is in warpstream or risingwave.

**Comment by richardartoul** [comment]
warpstream bug, resolved in `v505`. Sorry about that!
