### ISSUE TITLE
feat: backfill resuming for sink

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#12080]
`Sink into table` requires the backfilling to have resuming ability at any time because `sink into table` would return success to users immediately and there is no way to cancel the sink in the middle. We have to finish backfilling. If a system recovery happens during backfilling in `sink to table`, we need the resuming ability to provide exactly-once semantics.

_Originally posted by @chenzl25 in https://github.com/risingwavelabs/rfcs/issues/52#issuecomment-1706068958_

**Comment by chenzl25** [comment]
A description of the issue is outdated. Create sink statement returns ok to users only after backfill is finished.

**Comment by kwannoel** [comment]
Some updates from offline discussion:
1. All sink should immediately return to users once their actors are built.
2. Back-filling should be recoverable for all sinks.

**Comment by kwannoel** [comment]
This feature requires backfill recovery, which is a work in progress.
