### ISSUE TITLE
Don't use transaction in JDBC sink

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#12089]
### Is your feature request related to a problem? Please describe.

It many cause unnecessary deadlocks

**Comment by StrikeW** [comment]
Do you mean enable auto-commit or set the isolation level to the lowest level for the session?

**Comment by fuyufjh** [comment]
> Do you mean enable auto-commit or set the isolation level to the lowest level for the session? I think we can do both in the at-least-once semantic.

+1. Good point!

**Comment by StrikeW** [comment]
As discussion in https://github.com/risingwavelabs/risingwave/pull/12250, transaction (RC level) still preserved for consistency.
