### ISSUE TITLE
`err=Rpc error: gRPC error (Internal error): Failed to decode prost: field not found `cache_policy`

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#12095]
### Describe the bug

The only `proto` with `cache_policy` I could find is in `OverWindowNode::cache_policy`. I'm still trying to figure out if that's the actual cause.

cc @stdrc 

This came up in backwards compatibility test.

### To Reproduce

```sh
git fetch
git checkout kwannoel/repro-bug
./backwards-compat-tests/scripts/run_local.sh
```

After that take a look at the meta node log.

**Comment by kwannoel** [comment]
But it should not be right? 🤔 I mean proto should substitute the "missing field" with a default value as described here:

<img width="921" alt="Screenshot 2023-09-05 at 7 22 13 PM" src="https://github.com/risingwavelabs/risingwave/assets/47273164/0ee5c416-7dd2-4589-b2a7-d046ca18034b">

**Comment by stdrc** [comment]
Yes it looks strange. Should have default value on that field for legacy protobuf messages.

**Comment by stdrc** [comment]
I guess it's because I used `node.get_cache_policy()?` in `from_proto/over_window.rs`. Will fix it tomorrow.

**Comment by kwannoel** [comment]
> I guess it's because I used `node.get_cache_policy()?` in `from_proto/over_window.rs`. Will fix it tomorrow.

Yeah I guess we defer from default behaviour 🤣 .

See this testcase:
https://github.com/risingwavelabs/risingwave/blob/74c96fc8c546b54d2d38550864257f5b260e1d28/src/prost/src/lib.rs#L195-L200

And the implementation:
https://github.com/risingwavelabs/risingwave/blob/74c96fc8c546b54d2d38550864257f5b260e1d28/src/prost/helpers/src/generate.rs#L98-L100

**Comment by kwannoel** [comment]
> I guess it's because I used `node.get_cache_policy()?` in `from_proto/over_window.rs`. Will fix it tomorrow.

Fixed it first, since it's blocking backwards compat tests see https://github.com/risingwavelabs/risingwave/pull/12110
