### ISSUE TITLE
support ScyllaDB sink

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#12112]
ScyllaDB claims to be compatible with Cassandra, the Cassandra sink is supposed to also work for ScyllaDB.

But it needs to be tested before delivering to the user.

**Comment by racevedoo** [comment]
Wasn't this covered by https://github.com/risingwavelabs/risingwave/pull/11878?

**Comment by lmatz** [comment]
> Wasn't this covered by #11878?

True, it has been tested now, thanks for reminding me!
