### ISSUE TITLE
pgwire: correctly handle GSSAPI-encrypted connection

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#12124]
Found by @stdrc:

Some users find the error when connecting with `psql -h localhost -p 4566 -d dev -U root`, if they have configured something like `kerberos` in the system.

```
psql: error: connection to server at "localhost" (127.0.0.1), port 4566 failed: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

The problem appears to be that `psql` tries to establish a GSSAPI-encrypted connection once it find GSSAPI credentials, according to the default parameter `gssencmode=prefer`.

> https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-GSSENCMODE
> 
> if there are GSSAPI credentials present (i.e., in a credentials cache), first try a GSSAPI-encrypted connection; if that fails or there are no credentials, try a non-GSSAPI-encrypted connection. This is the default when PostgreSQL has been compiled with GSSAPI support.

Users can use `psql -h 127.0.0.1 -p 4566 -d "dbname=dev gssencmode=disable" -U root` as a workaround. However, I believe we should correctly handle GSSAPI-encrypted connection to avoid this confusion. **At least, we should gracefully fallback to a non-GSSAPI-encrypted connection.**

**Comment by fuyufjh** [comment]
This is probably a first step when users try RisingWave. Hope to be fixed asap

**Comment by liurenjie1024** [comment]
Do we really need this? GSS-API is not easy to use.

**Comment by fuyufjh** [comment]
@TennyZhuang Any updates? Today a user encountered this issue.

**Comment by TennyZhuang** [comment]
I will take a look
