### ISSUE TITLE
discussion: should we use a dedicated config file (like RiseDev profiles) for standalone deployment?

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#12142]
UPDATE: See https://github.com/risingwavelabs/risingwave/issues/12142#issuecomment-1754840299

----

That is to say, instead of taking raw CLI arguments of each node, let the standalone binary directly take a RiseDev profile file in `yaml` format with the same schema as the entries in `risedev-profiles.user.yml`.

Benefits:
- Utilize RiseDev's syntax and experience.
- No need to fill in the addresses for inter-node communication.
- Better for maintenance.

Actually, this is how the `playground` used to be. We decoupled them since we found there was no strong demand for specifying custom profiles for the playground launch. However, I guess it might still be suitable for `standalone` use.

cc @kwannoel @xxchan

**Comment by kwannoel** [comment]
+1 for local development, in fact I had a PR which was working on this. But the primary usecase is for cloud. Hence that's independent, and we expect to just pass cli args directly.

**Comment by BugenZhao** [comment]
I am primarily referring to cloud deployment. 🥹 For local development, I guess `risedev dev` should be sufficient.

**Comment by fuyufjh** [comment]
@kwannoel PTAL

**Comment by kwannoel** [comment]
> I am primarily referring to cloud deployment. 🥹 For local development, I guess `risedev dev` should be sufficient.

I'm not sure why standalone mode should be different from normal nodes.

Why provide risedev.yml just for standalone mode, but not for distributed nodes?

**Comment by kwannoel** [comment]
I sort of get the motivation for risedev.yml. But I don't think it is really needed, for other nodes we don't provide configuration files as well.

**Comment by kwannoel** [comment]
Feel free to change the priority / add it to release-1.4, if there's some compelling reason, perhaps I missed the point of it.

**Comment by BugenZhao** [comment]
This is because distributed nodes are designed to be deployed independently and users are able to randomly permute or combine them, so we give the maximum freedom to users.

While the "all-in-one" binary has already achieved starting different services with a single binary, I guess the main motivation for "standalone" binary is to start more than one services in a single process. The current implementation seems quite simple, just like starting multiple nodes together is a bash command separated with `;`. 🤣

There's definitely room for improvement for such an experience. For example, if we have specified the listen address of the meta service, then we don't need to specify the meta address again for compute and frontend services. That's why I propose this issue: perhaps we need a (cluster-level ?) configuration file for this as a better replacement for raw command-line arguments. `risedev.yml` is just a possible candidate.

**Comment by BugenZhao** [comment]
> But I don't think it is really needed

I agree. Feel free to close this issue as not planned perhaps.
