### ISSUE TITLE
Support concatenate (`||`) for jsonb arrays

### ISSUE THREAD

**Issue by ly9chee** [risingwavelabs/risingwave#12143]
### Is your feature request related to a problem? Please describe.

`select '["1","2","3"]'::jsonb::varchar[];`
this sql will cause a bind error

**Comment by xxchan** [comment]
You may try
```sql
select array_agg(x) from jsonb_array_elements( '["1","2","3"]'::jsonb) as t(x);
```

**Comment by ly9chee** [comment]
@xxchan Hi, thanks for your reply! My actual needs is to concatenate two json array into a single array, just like bellow:
```sql
SELECT x || y as concated
FROM (
    VALUES ('["1","2","3"]'::jsonb, '["4","5","6"]'::jsonb)
) AS t (x, y);
```
the expected result is:
`["1","2","3","4","5","6"]`
but I found currently only normal array can do the concatenation (through || operator) so I'm wondering if there is a more convenient approach to doing this.

according to the example you provided above, the sql should change to:
```sql
select array_agg(u.a) || array_agg(u.b) as concated from (
  select jsonb_array_elements_text(x) as a, jsonb_array_elements_text(y) as b
    from (
        values ('["1","2","3"]'::jsonb, '["4","5","6"]'::jsonb)
    ) as t (x, y)
) as u;
```
it looks like more verbose(and maybe it is not performant? I think). 
it is very common to do a concat with two json array in business logic, so is there a better way to accomplish this?

**Comment by xxchan** [comment]
We can support the `||` operator, which concatenates 2 jsonb values

```
xxchan@/tmp:postgres> select  '["a", "b"]'::jsonb || '["c", "d"]'::jsonb;

+----------------------+
| ?column?             |
|----------------------|
| ["a", "b", "c", "d"] |
+----------------------+
```

**Comment by ly9chee** [comment]
exactly! I would be appreciated if this `||` operator could be supported

**Comment by xiangjinwu** [comment]
will be tracked by #12180
