### ISSUE TITLE
Compaction strategy not stablized yet as shown by q102 q105

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#12151]
[http://metabase.risingwave-cloud.xyz/question/170-nexmark-q102-blackhole-medium-1cn-avg-so[…]r-second-rows-s-history-thtb-126?start_date=2023-07-09](http://metabase.risingwave-cloud.xyz/question/170-nexmark-q102-blackhole-medium-1cn-avg-source-output-rows-per-second-rows-s-history-thtb-126?start_date=2023-07-09)

q102 in the recent two days 0906, 0905:
[https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-da[…]20000&var-namespace=nexmark-bs-15-105-daily-20230906](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1694031918000&to=1694033720000&var-namespace=nexmark-bs-15-105-daily-20230906)
[https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-da[…]18000&var-namespace=nexmark-bs-15-105-daily-20230905](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1693946015000&to=1693947818000&var-namespace=nexmark-bs-15-105-daily-20230905)

![SCR-20230907-nyz](https://github.com/risingwavelabs/risingwave/assets/5791930/e6513542-0996-4804-9708-eb6fdba5c40b)
![SCR-20230907-nz4](https://github.com/risingwavelabs/risingwave/assets/5791930/d4ef6249-f7bd-4380-b2e7-f46d0fb1975b)
![SCR-20230907-nza](https://github.com/risingwavelabs/risingwave/assets/5791930/280bc088-beb2-41fb-820b-8d6c9f996113)
![SCR-20230907-nzf](https://github.com/risingwavelabs/risingwave/assets/5791930/144cb806-1853-41bc-aa68-c6294d8b1d83)

@Little-Wallace is working on a new compaction strategy to stabilize the behaviors.

Just leave a record for visibility.

**Comment by lmatz** [comment]
q105: http://metabase.risingwave-cloud.xyz/question/374-nexmark-q105-blackhole-medium-1cn-avg-source-output-rows-per-second-rows-s-history-thtb-129?start_date=2023-08-06

https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1694037981000&to=1694039784000&var-namespace=nexmark-bs-15-105-daily-20230906

https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1693952021000&to=1693953824000&var-namespace=nexmark-bs-15-105-daily-20230905

**Comment by lmatz** [comment]
link #11884

**Comment by hzxa21** [comment]
@Li0k @Little-Wallace Any updates?

**Comment by fuyufjh** [comment]
@Li0k @Little-Wallace  Any updates?

**Comment by Little-Wallace** [comment]
For q102:
<img width="699" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/16376959/b40ebbf4-7e05-44df-8482-3cec7ad0ef40">
<img width="741" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/16376959/e6b6e8da-2295-4368-b093-f44e60722c99">

For q105:
<img width="723" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/16376959/8ff5e8b9-619e-4ad5-83c3-502a3dc5c264">

We can found that the CPU usage has decrease a lot, I think this problem has been solved, does it ?

**Comment by Little-Wallace** [comment]
We will keep optimizing for CPU cost and stability in the future but this issue has been solved in current test case.
