### ISSUE TITLE
integration test: nats source and sink connector

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#12165]

**Comment by yufansong** [comment]
Talked with @wenym1 , this test is not very urgent. We already manuelly done some basic and recovery test on nats. So I guess the priority maybe not very high?

**Comment by lmatz** [comment]
Yeah, it is not in a hurry,
but still recommend adding it to the integration tests folder when you got the bandwidth, just in case.

And also it makes easier for others to communicate with clients who want to use nats. It shows more confidence.

Mimicking the other tests under the same folder should be easy as nats also provides a docker image.

**Comment by yufansong** [comment]
Finished in #12471. Closed.
