### ISSUE TITLE
watermark e2e test failed

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#12172]
### Describe the bug

The issue was found by [this branch](https://github.com/risingwavelabs/risingwave/compare/wangzheng/patrick/fix-table-id-filter-and-reorg-hummock-panel). It only modified metric and batch-availability code, so it shouldn't affect correctness.

failed to run `e2e_test/streaming/watermark.slt`
--
  |  
  | Caused by:
  | query result mismatch:
  | [SQL] select * from mv1;
  | [Diff] (-expected\|+actual)
  | -   2023-05-06 16:51:00 1
  | -   2023-05-06 16:51:00 2
  | -   2023-05-06 16:51:00 3
  | at e2e_test/streaming/watermark.slt:27

https://buildkite.com/risingwavelabs/pull-request/builds/31234#018a739c-a2d8-45a4-ac9d-dd5758ae21b1

**Comment by zwang28** [comment]
@yuhao-su

**Comment by yuhao-su** [comment]
The test is flaky as expected. Rerun will be fine. Please let me know if it happens again.

**Comment by zwang28** [comment]
> e2e_test/streaming/temporal_join/temporal_join_watermark.slt .. [FAILED]

This test case has failed for two consecutive days in main-cron.
https://buildkite.com/risingwavelabs/main-cron/builds/877#018ad843-59e3-4243-9e9d-17f31884f1e1
