### ISSUE TITLE
concat `jsonb || jsonb` → `jsonb`

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#12180]
https://www.postgresql.org/docs/15/functions-json.html#:~:text=jsonb%20%7C%7C%20jsonb%20%E2%86%92%20jsonb
> Concatenates two `jsonb` values. Concatenating two arrays generates an array containing all the elements of each input. Concatenating two objects generates an object containing the union of their keys, taking the second object's value when there are duplicate keys. All other cases are treated by converting a non-array input into a single-element array, and then proceeding as for two arrays. Does not operate recursively: only the top-level array or object structure is merged.
> ```
> '["a", "b"]'::jsonb || '["a", "d"]'::jsonb → ["a", "b", "a", "d"]`
> '{"a": "b"}'::jsonb || '{"c": "d"}'::jsonb → {"a": "b", "c": "d"}
> '[1, 2]'::jsonb || '3'::jsonb → [1, 2, 3]
> '{"a": "b"}'::jsonb || '42'::jsonb → [{"a": "b"}, 42]
> ```
> To append an array to another array as a single entry, wrap it in an additional layer of array, for example:
> ```
> '[1, 2]'::jsonb || jsonb_build_array('[3, 4]'::jsonb) → [1, 2, [3, 4]]
> ```

**Comment by taytzehao** [comment]
I would like to take this please
