### ISSUE TITLE
ingest unstructured json records or capture unrecognized fields

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#12207]
In a discussion with @fuyufjh that is inspired by a user's question

When a user has some rows in JSON format, he would like to:
1. Ingest some/all the columns by defining a concrete data type for each column.
2. Ingest the entire row as a JSONB column.

Right now, when (1), if a JSON field is in the row data but is not defined in the table schema, it will not be parsed and ingested into Risingwave.

For (2), right now, the user has to wrap the entire row by another field in JSON, e.g. `'data': {the original data}`. Therefore, from time to time, it requires the user to do another transformation before ingesting data into Risingwave. However, the user may not have control of the data format in the source as the source data is collected by some other data team.
By enabling users to do so, they can do more ETL workload all in RW instead of bringing up another system.

If we give the option that users can group all the JSON fields undefined in the table schema as one field, (2) is naturally solved.

Also, the user often wants to take the `primary key` out as a single column to be the primary key to duplicate the source stream of the table but keep everything else in a huge `data` JSONB column.

Welcome more observations and counter-examples

**Comment by fuyufjh** [comment]
Will be tracked on User-requested issues (Notion)

**Comment by BugenZhao** [comment]
> Also, the user often wants to take the `primary key` out as a single column to be the primary key to duplicate the source stream of the table but keep everything else in a huge `data` JSONB column.

IIUC, this can be done by defining a generated column accessing that JSONB.

**Comment by BugenZhao** [comment]
FYI, this is somehow similar to `#[serde(flatten)]`:

```rust
#[derive(Serialize, Deserialize)]
struct S {
    a: u32,
    b: String,
    #[serde(flatten)]
    other: Map<String, Value>,
}
```
from https://github.com/serde-rs/serde/issues/941#issuecomment-375486935

We need to find a way to mark the column.

**Comment by fuyufjh** [comment]
We are enhancing the schemaless features recently. Shall we work out this out based on `include columns`?

**Comment by xiangjinwu** [comment]
Related: #17959
```
create source foo (
  raw bytea,
  data jsonb as convert_from(raw, 'utf-8')::jsonb
) with (...) format plain encode bytes;
```

**Comment by fuyufjh** [comment]
> Related: #17959
> 
> ```
> create source foo (
>   raw bytea,
>   data jsonb as convert_from(raw, 'utf-8')::jsonb
> ) with (...) format plain encode bytes;
> ```

Yeah, this leverages `generated column`, which is like a work-around to me. Now I am considering making it a more "formal" usage.

**Comment by lmatz** [comment]
https://github.com/risingwavelabs/risingwave/pull/17650#issue-2400936095 proposed another variant of syntax
```
FORMAT DYNAMODB_CDC ENCODE JSON (
    single_blob_column = 'data'
)
```

**Comment by tabVersion** [comment]
> [#17650 (comment)](https://github.com/risingwavelabs/risingwave/pull/17650#issue-2400936095) proposed another variant of syntax
> 
> ```
> FORMAT DYNAMODB_CDC ENCODE JSON (
>     single_blob_column = 'data'
> )
> ```

I prefer this approach because the new collecting column has to be JSON type. `Encode json` guarantees a jsonb column can ingest the raw data losslessly. I am not sure JSONB also works for other encodes.

**Comment by fuyufjh** [comment]
When we talk about 'semi-structured data' or 'schemaless data', in 95% cases we are actually saying JSON. I'd like to prioritize `ENCODE JSON` and `JSONB` column than a more general but useless `BLOB/BYTEA` column. 

Unless you can do both of them.

**Comment by fuyufjh** [comment]
I still vote for `INCLUDE PAYLOAD AS payload JSONB` because `include` is exactly the syntax to to introduce a new column. I'd like to keep this style consistent.

Conversely, if we choose `( single_blob_column = 'data' )`, why not use `( kafka_headers_column = 'headers' )` to add Kafka message headers as well?

**Comment by tabVersion** [comment]
> I still vote for `INCLUDE PAYLOAD AS payload JSONB` because `include` is exactly the syntax to to introduce a new column. I'd like to keep this style consistent.

From the impl side, this approach is more doable. 

> Conversely, if we choose `( single_blob_column = 'data' )`, why not using `( kafka_headers_column = 'headers' )` to add Kafka message headers as well? 😄

In the original design, `additional` means the field comes from places other than the message payload.
But `PAYLOAD` exactly means the message payload, which is out of the `additional`'s scope. So I object to the idea at the moment.
