### ISSUE TITLE
feat: define generated column on table/source whose schema is externally defined

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#12209]
Currently, we do not allow user to define schema in column clause
```
CREATE SOURCE(a int, b int) FORMAT PLAIN ENCODE PROTOBUF;
 ERROR: ExecuteError: Protocol error: User-defined schema is not allowed with FORMAT PLAIN ENCODE PROTOBUF
```

When the user wants to define a generated column, he must specify columns in the create source/table statement. We might need to introduce another syntax.
```
CREATE SOURCE(*, proc_time timestampz AS proctime()) FORMAT PLAIN ENCODE PROTOBUF;
```

**Comment by yuhao-su** [comment]
Should we allow writing filed names apart from * ?

Should we allow * written in other parts other than the very beginning?

**Comment by st1page** [comment]
> Should we allow writing filed names apart from * ?
> 
> Should we allow * written in other parts other than the very beginning?

I think we can disallow them currently.
