### ISSUE TITLE
fix: reject unrecognized option in datagen

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#12237]
### Is your feature request related to a problem? Please describe.

To avoid wrong default option being used unexpectedly.

https://github.com/risingwavelabs/risingwave/pull/12213#issuecomment-1715110984

**Comment by BugenZhao** [comment]
- #7034

**Comment by xxchan** [comment]
dup with https://github.com/risingwavelabs/risingwave/issues/9450
