### ISSUE TITLE
`regproc` and `regclass` shouldn't be KEYWORD

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#12274]
`regproc` (and `regclass` above) does not need to be a [keyword](https://www.postgresql.org/docs/current/sql-keywords-appendix.html) and recognized by sqlparser. They can just be a `Custom(ObjectName)` like `int2` or `timestamptz`.

_Originally posted by @xiangjinwu in https://github.com/risingwavelabs/risingwave/pull/12272#discussion_r1324195251_

**Comment by xiangjinwu** [comment]
Resolved by #16933
