### ISSUE TITLE
Metrics `partition_input_bytes` for data generator source is not recorded.

### ISSUE THREAD

**Issue by MrCroxx** [risingwavelabs/risingwave#12278]
### Describe the bug

When using nexmark source generator, `Source Throughput(MB/s)` is not shown on Grafana, which queries metrics `partition_input_bytes`.

<img width="1458" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/22407295/45b319ca-db94-4471-90ab-2c281d5288a4">

`partition_input_bytes` is updated by `into_chunk_stream` in `src/connector/src/source/common.rs`, but nexmark source generator doesn't call the function.

**Comment by MrCroxx** [comment]
The row-level source throughput metrics `source_output_row_count(stream_source_output_rows_counts)` is held by `StreamingMetrics` but byte-level source throughput metrics `partition_input_count` is held by `SourceMetrics`. Is this by design? @tabVersion

**Comment by tabVersion** [comment]
> The row-level source throughput metrics `source_output_row_count(stream_source_output_rows_counts)` is held by `StreamingMetrics` but byte-level source throughput metrics `partition_input_count` is held by `SourceMetrics`. Is this by design? @tabVersion

Sorry for late reply. I think no, the metrics are added separately. I will submit a fix. 

> `partition_input_bytes` is updated by `into_chunk_stream` in `src/connector/src/source/common.rs`, but nexmark source generator doesn't call the function

IIRC, necmark source generates stream chunk directly, shall we use the chunk's size for this metric?

**Comment by MrCroxx** [comment]
> IIRC, necmark source generates stream chunk directly, shall we use the chunk's size for this metric?

It's okay for me. But I think it will be better to use the same function for source data gen and normal source.
