### ISSUE TITLE
enhancement(optimizer): merge common aggregation functions

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#12305]
> Discussed with @st1page 

For example,

```
select avg(x) a, sum(x) s, count(x) c from t;
```

will be executed as 

```
select expr1 / expr2, s, c from 
  (select sum(x) as expr1, count(x) as expr2, sum(x) s , count(x) c from t);
```

Here, the two `sum(x)` and two `count(x)` can be simply reused.

Another example is NexMark Q15

https://github.com/risingwavelabs/risingwave/blob/0259125649a7494e4d58d83f1c8f7d5d1d3cdd7f/src/frontend/planner_test/tests/testdata/output/nexmark_source.yaml#L1126

```
StreamHashAgg [append_only] {
  group_key: [$expr1, bidder, auction, flag],
  aggs: [
    count, 
    count filter((price < 10000:Int32)), 
    count filter((price >= 10000:Int32) AND (price < 1000000:Int32)), 
    count filter((price >= 1000000:Int32)),
    count filter((price < 10000:Int32)), 
    count filter((price >= 10000:Int32) AND (price < 1000000:Int32)), 
    count filter((price >= 1000000:Int32)),
    count filter((price < 10000:Int32)), 
    count filter((price >= 10000:Int32) AND (price < 1000000:Int32)), 
    count filter((price >= 1000000:Int32))] 
```

Obviously the 9 `count` agg functions can be merged to 3, so that we reduce the aggregation state size to 1/3.

**Comment by st1page** [comment]
We do not need to implement it in Agg executor but implement it as an optimizer rule we can write a project ahead :thinking:
