### ISSUE TITLE
bug(metrics) source_status_is_up still reporting after drop source

### ISSUE THREAD

**Issue by Gogomoe** [risingwavelabs/risingwave#12343]
### Describe the bug

I created a source and then drop it. But the `source_status_is_up` is still reporting.

- 1003 1004 1005 are created after the previous one deleted, But currently all of them are exist.
![image](https://github.com/risingwavelabs/risingwave/assets/12986936/809435dd-2964-4d62-8510-3d3bf51d0364)

https://grafana.test.risingwave-cloud.xyz/explore?orgId=1&left=%7B%22datasource%22:%22P2453400D1763B4D9%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P2453400D1763B4D9%22%7D,%22editorMode%22:%22builder%22,%22expr%22:%22source_status_is_up%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%221694736000000%22,%22to%22:%221694764800000%22%7D%7D

### The version of RisingWave

v1.1.4

**Comment by tabVersion** [comment]
https://github.com/risingwavelabs/risingwave/blob/f304ed214295b26fd068ef4e408524ef095a9c7f/src/meta/src/stream/source_manager.rs#L828-L835

we abort the async handler here but it does not mean the async context is stopped immediately.
