### ISSUE TITLE
Rename `risingwave::common::array::Datachunk.cardinality()`

### ISSUE THREAD

**Issue by Babbleshack** [risingwavelabs/risingwave#12356]
Cardinality is used by rising wave to describe the capacity of a row batch. However the term is used incorrectly:
From wikipedia:
```
the term cardinality refers to the uniqueness of data values contained in a particular column (attribute) of a database table. 
```

This should be updated to `capacity`

**Comment by fuyufjh** [comment]
cc. @st1page
