### ISSUE TITLE
feat: support reverse scan for hummock

### ISSUE THREAD

**Issue by Little-Wallace** [risingwavelabs/risingwave#12367]
### Is your feature request related to a problem? Please describe.

In past scenes, we only need forward scan in all of state executor.  So we remove backward scan of hummock because it is hard to implement reverse iterator of delete-range.

 @st1page propose a expanded range cache to store part of keys in memory. Sometimes we may need to load more data from  hummock, and if we want to load data from the left side of cache, we need to a reverse-scan.

### Describe the solution you'd like

The interface shall support range bound and item limit.

### Describe alternatives you've considered

Maybe I need some time to think of how to implement reverse iterator of delete range.

**Comment by st1page** [comment]
c.c. @stdrc

**Comment by hzxa21** [comment]
This can be simplified with #13148

**Comment by hzxa21** [comment]
#13148 is done. I think we can continue to support reverse scan based on vnode watermark. @Little-Wallace @wenym1

**Comment by fuyufjh** [comment]
Ping. Window function is still waiting for this.

**Comment by hzxa21** [comment]
Done in #12570
