### ISSUE TITLE
support set allow.auto.create.topics property in kafka sink

### ISSUE THREAD

**Issue by ly9chee** [risingwavelabs/risingwave#12365]
### Is your feature request related to a problem? Please describe.

with allow.auto.create.topics=true, the topic currently being produced to is automatically created, saving a lot of time when there are hundreds of tables that need to be sunk.

when the broker already enabled allow.auto.create.topics=true, creating kafka sink will result in the following error
```
QueryError: internal error: Sink error: config error: failed to fetch metadata from kafka (127.0.0.1:9092), error: topic xxx not found
```

**Comment by fuyufjh** [comment]
Thanks for the feedback! We'll look into it.
