### ISSUE TITLE
larger than 100% cache miss rate

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#12376]
### Describe the bug

https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1694770947921&orgId=1&to=1694774528242&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=nexmark-bs-105-without-limit-affinity-daily&var-instance=benchmark-risingwave&var-node=All&var-job=All&var-table=All

![SCR-20230918-m3q](https://github.com/risingwavelabs/risingwave/assets/5791930/e4444d21-4dbf-401a-a1a5-1d492db90a07)

should be 100% at max

**Comment by fuyufjh** [comment]
@MrCroxx Are you working on this?
