### ISSUE TITLE
feat: support uuid type

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#12387]
### Is your feature request related to a problem? Please describe.

- We should first be able to map Postgres UUID type to RisingWave correctly during CDC and sink.
   The previous discussion regarding this issue is here: https://github.com/risingwavelabs/risingwave/issues/11373
   Suppose we can only use VARCHAR in the pipeline where RW consumes PG uuid from a source and sink to another PG.
   Since we disallow implicitly casting from `varchar` to `uuid` in create sink https://github.com/risingwavelabs/risingwave/issues/11373#issuecomment-1663328706, the destination PG would have to use VARCHAR instead. This would lead to a large migration effort.

- uuid_generate_v4()

- For sinking uuid to 3rd party data stores:
   - Postgres: UUID
   - MySQL: varchar
   - Clickhouse: UUID https://clickhouse.com/docs/en/sql-reference/data-types/uuid
   - Iceberg: string
   - ...

- Casting from varchar to uuid

**Comment by fuyufjh** [comment]
We'll do https://github.com/risingwavelabs/risingwave/issues/11373 instead
