### ISSUE TITLE
more meta miss when using 3 machine than 1 machine in a number of queries

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#12395]
1CN: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1694770947921&orgId=1&to=1694774528242&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=nexmark-bs-105-without-limit-affinity-daily&var-instance=benchmark-risingwave&var-node=All&var-job=All&var-table=All

![SCR-20230918-u2d](https://github.com/risingwavelabs/risingwave/assets/5791930/5b3531a4-44d6-46c0-aabb-fcb1e6a179a8)

3CN: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1695009521093&orgId=1&to=1695013628676&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=nexmark-3cn-3cm-compactor-3cpu-q105-without-limit&var-instance=benchmark-risingwave&var-node=All&var-job=All&var-table=All

![SCR-20230918-u2m](https://github.com/risingwavelabs/risingwave/assets/5791930/6da7e55f-fe36-4ba5-a334-866809cfd3b5)

both images: `nightly-20230914`
query: https://github.com/risingwavelabs/kube-bench/blob/main/manifests/nexmark/nexmark-sinks.template.yaml#L607-L615

**Comment by lmatz** [comment]
query Q4: https://github.com/risingwavelabs/kube-bench/blob/main/manifests/nexmark/nexmark-sinks.template.yaml#L76-L88

1CN: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1694625170000&to=1694626973000&var-namespace=nexmark-bs-0-14-affinity-daily-20230913

image: `nightly-20230913`

![SCR-20230918-u48](https://github.com/risingwavelabs/risingwave/assets/5791930/a3b5f1c8-a77d-4f55-8c5e-6b1a64e6f07b)



3CN: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1695013578000&to=1695015381000&var-namespace=nexmark-3cn-3cm-compactor-3cpu-30min-bad-queries-lmatz

image: `nightly-20230914`

![SCR-20230918-u4b](https://github.com/risingwavelabs/risingwave/assets/5791930/511290ea-9d77-4aea-911d-6c324c483e3f)

**Comment by lmatz** [comment]
q5: https://github.com/risingwavelabs/kube-bench/blob/main/manifests/nexmark/nexmark-sinks.template.yaml#L96-L131

1CN: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1694627202000&to=1694629005000&var-namespace=nexmark-bs-0-14-affinity-daily-20230913

image: `nightly-20230913`
![SCR-20230918-ua9](https://github.com/risingwavelabs/risingwave/assets/5791930/6d756900-8a21-4279-8c56-a25166566df8)

3CN: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1695015921000&to=1695017724000&var-namespace=nexmark-3cn-3cm-compactor-3cpu-30min-bad-queries-lmatz

image: `nightly-20230914`
![SCR-20230918-uac](https://github.com/risingwavelabs/risingwave/assets/5791930/08ee9426-aa13-4991-9df2-52cc36c7a98a)

And especially in this Q5's 3CN setting, the compactor does not use much CPU. It seems the issue has nothing to do with too few CPU resources for compactor.

![SCR-20230918-ubh](https://github.com/risingwavelabs/risingwave/assets/5791930/b0bed614-b940-4d83-9aa2-73bb88cef094)

**Comment by lmatz** [comment]
q13: https://github.com/risingwavelabs/kube-bench/blob/main/manifests/nexmark/nexmark-sinks.template.yaml#L278-L296

1CN: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1694639615000&to=1694640578000&var-namespace=nexmark-bs-0-14-affinity-daily-20230913

image: `nightly-20230913`
![SCR-20230918-ugg](https://github.com/risingwavelabs/risingwave/assets/5791930/45d96aa2-b52b-444d-a153-4d6c488e8529)

3CN: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1695018281000&to=1695018824000&var-namespace=nexmark-3cn-3cm-compactor-3cpu-30min-bad-queries-lmatz

image: `nightly-20230913`
![SCR-20230918-ugj](https://github.com/risingwavelabs/risingwave/assets/5791930/4741397e-0a87-4b2e-8b7a-3c57f78fe033)

**Comment by lmatz** [comment]
Can investigate more queries, but I suspect the pattern is the same

**Comment by hzxa21** [comment]
Each CN will at least flush one SST to L0 per checkpoint. This means the number L0 overlapping SSTs is proportional to number of CNs in the cluster. Currently we haven't implemented a good way to filter out L0 SSTs written by the non-writer CN in the read path but instead rely on bloom filter to filter out the irrelevant overlapping L0 SSTs. Since bloom filter sits in SST meta, I think it is expected that we will see more meta misses with more CNs in the cluster.

@MrCroxx is working on refilling meta to file cache on storage version update. This can help alleviate meta miss.

**Comment by lmatz** [comment]
I see, now it adds up.

I was wondering if there is any difference between RW and other non-shared state systems in terms of 1CN -> 3CN, 
and was thinking the number of L0 SST could make a difference, e.g.: when reading

other system 1 CN: X L0 SST
other system 3 CN: X L0 SST as they are local only

RW 1 CN: X L0 SST under 1 CN 
RW 3 CN: Y (where X < Y < 3*X because compaction may help a bit so not exactly 3X) L0 SST as they are shared


And @Little-Wallace told me that it is not the number of L0 SSTs but the number of overlapping L0 SSTs that matters.

**Comment by lmatz** [comment]
>  is working on refilling meta to file cache on storage version update.

If the file cache is not enabled, can we do the same, i.e. refilling meta to meta cache?

**Comment by MrCroxx** [comment]
> @lmatz  If the file cache is not enabled, can we do the same, i.e. refilling meta to meta cache?

The meta cache refill is always on no matter if file cache is enabled. New meta will be refilled into in-memory meta block cache.

**Comment by fuyufjh** [comment]
@MrCroxx How to deal with this issue? Shall we close it?

**Comment by MrCroxx** [comment]
Fixed via #17513 #17459 #17540
