### ISSUE TITLE
Implement state table try_flush for non-checkpoint barrier

### ISSUE THREAD

**Issue by wcy-fdu** [risingwavelabs/risingwave#12419]

**Comment by hzxa21** [comment]
@wcy-fdu I think this is done?

**Comment by hzxa21** [comment]
Feel free to reopen if not done.

**Comment by wcy-fdu** [comment]
> @wcy-fdu I think this is done?

Just rebase main today, and there is something wrong with the CI of this [pr](https://github.com/risingwavelabs/risingwave/pull/12418), I will fix it later.
