### ISSUE TITLE
Tracking: new file source 

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#12410]
To maintain compatibility, the old code for the file source will be preserved.

- Stream Executors && proto
    - [ ] FsListSourceExecutor (need to check if we can reuse the SourceExecutor's logic)
    - [ ] FsFetchExecutor
- Optimizer: 
    - add a StreamFsFetch PlanNode
    - add a StreamFsListSource PlanNode, to prevent potential compatibility issues, we do not reuse StreamSource here
    - change LogicalSource::to_stream
      - StreamFsListSource->Exchange(file_name)->StreamDedup->StreamFsFetch->StreamProject(pruning the file names)

FsListSource
 - no input
 - output schema: (file_name: Varchar)
 - append-only
 - state table: schema(file_name, offset), pk(file_name), dist key should in pk

FsFetch
 - Dist::single
 - params: 
     - file name col idx: the file name column in the input
     - source Catalog
 - state table: schema(file_name), pk(file_name), dist key(None)
 - input schema: any
 - output schema: source catalog schema + input schema

**Comment by tabVersion** [comment]
resolved by https://github.com/risingwavelabs/risingwave/pull/12595
