### ISSUE TITLE
bug: scalar expressions in `StreamProjectSet` are not evaluated non-strictly

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#12474]
### Describe the bug

Scalar expressions in `StreamProjectSet` are not evaluated non-strictly, where failure will lead to recovery. This is inconsistent with the behavior of `Project`.

### Error message/log

failed to execute barrier: Rpc error: gRPC error (Internal error): Actor 72 exit unexpectedly: Executor error: Chunk operation error: Division by zero

### To Reproduce

```sql
create table t(x int[]);
insert into t values (array[1,2]);

create materialized view mv as select x[1]/0 as bomb, unnest(x) as unnest from t;
```

### Expected behavior

```sql
dev=> select * from mv2;
 bomb | unnest 
------+--------
      |      1
      |      2
```

**Comment by xiangjinwu** [comment]
And agg #11256 (maybe we can close #11915 and keep these 2 individual issues?)

**Comment by BugenZhao** [comment]
> And agg #11256 (maybe we can close #11915 and keep these 2 individual issues?)

Good catch 🥵

**Comment by fuyufjh** [comment]
From my understanding, here we got 2 choices:

1. Return `[]`, and the whole row will be dropped in `ProjectSetExecutor`
2. Return `[None]`, and the row will be kept with a `NULL` in the column of set-returning function.

(Plus: In either way a warning message need to be reported to user via Web UI)

I would vote for 2. Option 1 seems to be a bug from users's perspective.

**Comment by BugenZhao** [comment]
> From my understanding, here we got 2 choices:

I suppose you're referring to the opposite part of this issue, i.e., when the set-returning function fails to evaluate. +1 for Option 2.

**Comment by BugenZhao** [comment]
@wangrunji0408 You now have more expertise in expression error handling than I do. Would you be willing to take over this issue? 🥺

**Comment by BugenZhao** [comment]
Not only scalar expressions but also the set-returning functions are not evaluated non-strictly as well. We should reopen #11915 to track it.
