### ISSUE TITLE
Creating mycsql cdc gives an error, but the user has privileges

### ISSUE THREAD

**Issue by caohb1985** [risingwavelabs/risingwave#12499]
### Describe the bug

SQL 错误 [XX000]: ERROR: ExecuteError: internal error: source cannot pass validation: INVALID_ARGUMENT: MySQL user doesn't have enough privileges: [RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT, SELECT]

**Comment by StrikeW** [comment]
Hi could you provide the log of connector node and the version of your mysql version?

**Comment by fuyufjh** [comment]
Please reopen if have any updates

**Comment by liweilun1** [comment]
I have the same problem 
mysql version: 5.7.44
risingwave image tag: nightly-20231031
risingwave-operator image tag: latest

i use this command to grant user privilege
GRANT ALL ON *.* TO 'szxy_test'@'%';
FLUSH PRIVILEGES;

and use this command create table 
CREATE TABLE kubelog_mysql_cdc_source (
   container_log_count bigint,
   container string,
   PRIMARY KEY (container)
) WITH (
 connector = 'mysql-cdc',
 hostname = 'mysql1.mysql',
 port = '3306',
 username = 'szxy_test',
 password = 'xxx.',
 database.name = 'kubelog_count',
 table.name = 'kubelog_count',
 server.id = '5454'
);

**Comment by StrikeW** [comment]
This is a known issue of the ambiguity of the GRANT ALL in mysql 5.7 and 8.0. Please grant the required privilege explicitly according to our document.
