### ISSUE TITLE
refactor(optimizer): split stream key and unique key

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#12514]
Currently, we have the `pub fn logical_pk()` method on plan Node.
But now we find stream_key is a very special concept, so we need to clarify here.
finally, we will have two different method
```rust
pub fn stream_key(&self) -> Option<&[usize]>;
pub fn unqiue_key(&self) -> Vec<Vec<usize>>;
```

**Comment by BugenZhao** [comment]
Related #9375
