### ISSUE TITLE
optimizer: dedup columns

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#1252]
- [x] rewrite plan node with input_col_change mapping

in offline discussion@likg227 propose to implement them in col_prune
<del> - [ ] dedup column for `LogicalScan` </del>
- [ ] dedup column for `LogicalAgg`
- [x] dedup column for `LogicalProject` by project builder

**Comment by st1page** [comment]
In the streaming part, the issue might be not only about the performance when the expression appears in order by clause. When creating an MV, the user can control the primary key of the MV with an `order by` clause. Unfortunately, without dedup the expression, we can hardly bind the two on one column and produce a confusing plan for the user.

```SQL
- sql: |
    CREATE TABLE t (a INTEGER, b INTEGER);
    SELECT a+b as expr_alias FROM t ORDER BY a+b;
  batch_plan: |
    BatchProject { exprs: [(t.a + t.b)] }
    └─BatchExchange { order: [(t.a + t.b) ASC], dist: Single }
      └─BatchSort { order: [(t.a + t.b) ASC] }
        └─BatchProject { exprs: [(t.a + t.b), (t.a + t.b)] }
          └─BatchScan { table: t, columns: [t.a, t.b], distribution: SomeShard }
  stream_plan: |
    StreamMaterialize { columns: [expr_alias, (t.a + t.b)(hidden), t._row_id(hidden)], pk_columns: [t._row_id], order_descs: [(t.a + t.b), t._row_id] }
    └─StreamProject { exprs: [(t.a + t.b), (t.a + t.b), t._row_id] }
      └─StreamTableScan { table: t, columns: [t.a, t.b, t._row_id], pk: [t._row_id], dist: UpstreamHashShard(t._row_id) }
```
 though they can write SQL with alias in `order by`, I think it is not friendly
 ```SQL
    SELECT a+b as expr_alias FROM t
    ORDER BY expr_alias; 
```

And the same issue can appear on aggregator too.
```SQL
- sql: |
    CREATE TABLE t (
            a INTEGER,
            b INTEGER,
    );
    SELECT max(a) as max_a, b
    FROM t
    GROUP BY b
    ORDER BY max(a);
  logical_plan: |
    LogicalProject { exprs: [max(t.a), t.b] }
    └─LogicalProject { exprs: [max(t.a), t.b, max(t.a)] }
      └─LogicalAgg { group_key: [t.b], aggs: [max(t.a), max(t.a)] }
        └─LogicalProject { exprs: [t.b, t.a] }
          └─LogicalScan { table: t, columns: [t.a, t.b, t._row_id] }
  batch_plan: |
    BatchProject { exprs: [max(t.a), t.b] }
    └─BatchExchange { order: [max(t.a) ASC], dist: Single }
      └─BatchProject { exprs: [max(t.a), t.b, max(t.a)] }
        └─BatchSort { order: [max(t.a) ASC] }
          └─BatchHashAgg { group_key: [t.b], aggs: [max(t.a), max(t.a)] }
            └─BatchExchange { order: [], dist: HashShard(t.b) }
              └─BatchScan { table: t, columns: [t.a, t.b], distribution: SomeShard }
  stream_plan: |
    StreamMaterialize { columns: [max_a, b, max(t.a)(hidden)], pk_columns: [b], order_descs: [max(t.a), b] }
    └─StreamProject { exprs: [max(t.a), t.b, max(t.a)] }
      └─StreamHashAgg { group_key: [t.b], aggs: [count, max(t.a), max(t.a)] }
        └─StreamExchange { dist: HashShard(t.b) }
          └─StreamTableScan { table: t, columns: [t.a, t.b, t._row_id], pk: [t._row_id], dist: UpstreamHashShard(t._row_id) }

```

**Comment by xiangjinwu** [comment]
> I think it is not friendly

Actually this is the preferred syntax, especially when the expression is more complex than `a+b` or `max(a)`.

**Comment by st1page** [comment]
> > I think it is not friendly
> 
> Actually this is the preferred syntax, especially when the expression is more complex than `a+b` or `max(a)`. Even after we improved this part, we'd better stick to the preferred form in docs and tutorials.

Yes, I agree. My point is that when users do not use that syntax, we should give them a more intuitive behavior. especially in cases where the expression is simple and just to get a field, such as https://github.com/risingwavelabs/risingwave/issues/6917.
