### ISSUE TITLE
Use standalone mode in docker-compose.yml

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#12538]
### Is your feature request related to a problem? Please describe.

As title. This makes it more compact and light-weighted.

**Comment by hengm3467** [comment]
Thanks for opening this issue! I love the idea of using standalone mode in docker-compose. @kwannoel Please let me know if this is going to be included in v1.3 release. I'll update our documentation accordingly. Thanks.

**Comment by kwannoel** [comment]
> Thanks for opening this issue! I love the idea of using standalone mode in docker-compose. @kwannoel Please let me know if this is going to be included in v1.3 release. I'll update our documentation accordingly. Thanks. 

Not in 1.3 sorry. I don't plan to work on this so soon.

**Comment by hengm3467** [comment]
@kwannoel Thanks for the update! If not in docker compose file, maybe we can describe this mode in the docs first. Do you happen to have some notes about how to start RW in this mode? Not sure if @lmatz has already summarized something.

**Comment by kwannoel** [comment]
> @kwannoel Thanks for the update! If not in docker compose file, maybe we can describe this mode in the docs first. Do you happen to have some notes about how to start RW in this mode? Not sure if @lmatz has already summarized something. 

Not meant to be user-facing actually. Only when docker compose is complete it will be. Used by cloudside, can pm for more details.
