### ISSUE TITLE
delete range test timeout

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#12549]
### Describe the bug

end-to-end test (release) 

https://buildkite.com/risingwavelabs/main-cron/builds/873#018acdf5-9413-4329-a928-7730f8485013

**Comment by zwang28** [comment]
@Little-Wallace @Li0k

**Comment by Li0k** [comment]
<img width="1058" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/15023748/648e6d85-62ed-4632-a95e-4c5825d30670">

<img width="673" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/15023748/10f1f15f-b5ab-4d1c-8d85-16bbaaa268de">

I found the cause of the delete-range-test timeout.
1. The write limit was triggered
2. The reason why write limit is triggered is that we cannot complete compaction (report failure)

MockHummockMetaClient is used in delete range test, and only the subscribe operation is mocked. Therefore, the logic of report cannot be processed. We should fix this problem, for example
1. Like compaction test, start a separate meta node
2. Mock the logic of report compact task

@Little-Wallace
