### ISSUE TITLE
Decimal type mismatch error only output in meta node log

### ISSUE THREAD

**Issue by QuantumBear** [risingwavelabs/risingwave#12548]
### Describe the bug

In psql client, it reports channel closed.

### Error message/log

```text
Can find this error log in meta node log

Json parse error: rw Decimal's precision is large than doris max decimal len is 12, doris max is 11
```

### The version of RisingWave

```
dev=> select version();
                                     version
----------------------------------------------------------------------------------
 PostgreSQL 9.5-RisingWave-1.3.0-alpha (5ab1f7a2fb8bf1e0b984598d95b69b50c6410c33)
(1 row)
```

**Comment by fuyufjh** [comment]
@xxhZs Please take a look

**Comment by xxhZs** [comment]
Hello, can you provide the table creation statements for Doris and RW?

**Comment by xxhZs** [comment]
Hello, can you provide the decimal data associated with the error?

**Comment by QuantumBear** [comment]
It happens when the length of decimal in mv is larger then the correspond field in Doris, easy to reproduce.

**Comment by xxhZs** [comment]
> It happens when the length of decimal in mv is larger then the correspond field in Doris, easy to reproduce.
Thanks！This is because Doris has a decimal precision limit, exceeding which will result in the data insertion failure. Here, we will adopt a more explicit approach to throw this error.
