### ISSUE TITLE
bug: source data generator exit when error without output reason or retry

### ISSUE THREAD

**Issue by MrCroxx** [risingwavelabs/risingwave#12552]
### Describe the bug

Source data generator exit when error without output the inner error reason or retry.

https://github.com/risingwavelabs/risingwave/blob/0726b590765e3325fbeb07dde4065579f852b87a/src/connector/src/source/data_gen_util.rs#L41-L49

**Comment by MrCroxx** [comment]
@tabVersion Is this behavior as expected? IMO, data generator should retry if error, or at least print its error reason.

**Comment by BugenZhao** [comment]
I introduced the behavior here. Would you please elaborate more on the situations in which the data generator will temporarily fail?

**Comment by MrCroxx** [comment]
Discussed with @tabVersion offline. It's expected behavior. It will be handle upper layer.
