### ISSUE TITLE
Table definition and json schema

### ISSUE THREAD

**Issue by yufansong** [risingwavelabs/risingwave#12609]
### Describe the bug

Sometimes the difference between the provided table definition and the actual json scheme in the kafka topic would create invisible failures, there would be no way for me to know exactly what failed and due to what.

**Comment by yufansong** [comment]
Update communication with customer:
We ask:  

> Do you mean this situation: you define one data schema, but the data in Kafka is in a different schema, actually? Could you please also provide the symptoms of these invisible failures, like do you find them in logs? It would be better if you could provide the schema or table definitions.


customer reply:

> Concrete example: A debezium json kafka topic, but the inline schema has been removed from the message structure to minimize overhead:
> ```
> {
>   "before": null,
>   "after": {
>     "id": 11713450,
>     "station_id": "6sQyb3N",
>     "domain_type": "series",
>     ...
>   },
>   "source": {
>     "version": "2.4.0.Beta1",
>     "connector": "postgresql",
>     ...
>   },
>   "op": "r",
>   "ts_ms": 1694530452993,
>   "transaction": null
> }
> 
> ```
> The create table command will fail by running for a few minutes until timing out:
> ```
> CREATE TABLE IF NOT EXISTS cdc_domain_airings_deb (
>     id text primary key,
>     station_id text,
>     ...
> )
> WITH ( connector='kafka',
>    ...
> ) FORMAT debezium ENCODE JSON;
> ```
>

**Comment by tabVersion** [comment]
close by mistake

**Comment by yufansong** [comment]
No feedback recently. Close it. Will reopne it if anyone can provide more details.
