### ISSUE TITLE
Question about time filter

### ISSUE THREAD

**Issue by yufansong** [risingwavelabs/risingwave#12608]
### Describe the bug

Basic things like a time-filter (where start_time > now()) did not work, saying that the feature to compare timestamps has not been implemented yet, even though this capability was documented in examples. (ran on version 1.20)

**Comment by kwannoel** [comment]
Do we have the link to the example / query?

**Comment by yufansong** [comment]
I still try to communicate with costumer to get their queries. WIll update here if get more information.

**Comment by BugenZhao** [comment]
I would guess there's some confusion between `timestamp` and `timestamp with time zone`(`timestamptz`). Note that `now` is with time zone.

**Comment by yufansong** [comment]
Update some feedback from costumer:
We send question to costumer: 2. Could you please provide the type of your `start_time` field and the document you refer to? We support multiple date types like timestamp, timestampz, date, time, and interval. It would be better if you can provide the schema and queries.

Costumer reply:
The `start_time` field is in `timestamp` format and backed by a unix timestamp in microseconds coming from kafka-connect.

**Comment by BugenZhao** [comment]
> This query is supported in Postgres. Should we handle it as well?

We did support that. 🤪

```
❯ psql -h localhost -p 4566 -d "dbname=dev gssencmode=disable" -U root
psql (14.9 (Homebrew), server 9.5.0)
Type "help" for help.

dev=> select '2023-10-09 14:44:25'::timestamp > now();
NOTICE:  Your session timezone is UTC. It was used in the interpretation of timestamps and dates in your query. If this is unintended, change your timezone to match that of your data's with `set timezone = [timezone]` or rewrite your query with an explicit timezone conversion, e.g. with `AT TIME ZONE`.

 ?column? 
----------
 f
(1 row)
```

I guess what we're talking about is the derivation of the streaming temporal filter. The logic is kind of ad-hoc here. https://github.com/risingwavelabs/risingwave/blob/6ef7fcd1e1455699852109d4f09d2fa735b08b0a/src/frontend/src/expr/mod.rs#L703-L737
