### ISSUE TITLE
Qustion about the execution speed of MV

### ISSUE THREAD

**Issue by yufansong** [risingwavelabs/risingwave#12607]
### Describe the bug

Queries and commands to create MVs would often run without ending (i would terminate them after a few minutes) and without producing an error. They would not complete or succeed, but fail silently.

### Expected behavior

1. I wondering how should we expect the execution speed?
2. Should we give any prompt when stop the MV execution?

**Comment by kwannoel** [comment]
> They would not complete or succeed, but fail silently.

How is "fail silently" observed? Is it because it takes a long time and is assumed to have failed?

> Queries and commands to create MVs would often run without ending

When checking the mv progress with `SHOW JOBS`, does it show MV does not have progress?

Will be helpful to get RW logs as well and the original query which caused this for further debugging.

**Comment by yufansong** [comment]
already recommand user use `SHOW JOBS` and ask for more details. Let's waiting for the feedback.

**Comment by BugenZhao** [comment]
This seems not to be considered as a https://github.com/risingwavelabs/risingwave/labels/type%2Fbug. Would you please edit the issue body and labels instead?

**Comment by yufansong** [comment]
Closed, discussed at #12366.
