### ISSUE TITLE
Too much log for user

### ISSUE THREAD

**Issue by yufansong** [risingwavelabs/risingwave#12610]
### Is your feature request related to a problem? Please describe.

Logs produce too much noise (I saw thousands of records per second in one case), even when setting the log-level to WARN. This has the potential to create a large bill in Google's Logging system.

### Describe the solution you'd like

Should we seperate the log into several level and make sure in some case, our kernel can only generate the least useful log?

**Comment by kwannoel** [comment]
I guess we need to add some tests for log-size when there's non-trivial dataload, and define what is acceptable.

E2e tests do check log-size, but I think data load is not much, and may not test cases which lots of data.

**Comment by xxchan** [comment]
> Logs produce too much noise (I saw thousands of records per second in one case), even when setting the log-level to WARN.

Can you share what's the typical logs under the default setting and `WARN` level? We can see what's unintended logs. I think the points are generally correct, but not actionable. We can only handle it case by case. 🤔️

Note that we can already have fine-grained control by e.g.,

```
RUST_LOG='risingwave_frontend::scheduler::snapshot=off' risingwave playground
```
to close a log like
```
2023-10-03T21:22:14.052352+08:00  INFO risingwave_frontend::scheduler::snapshot: unpin snapshot with RPC min_epoch=5184168463564800
```

> I guess we need to add some tests for log-size when there's non-trivial dataload, and define what is acceptable.

Can longevity test be used for this purpose? 🤔️

**Comment by yufansong** [comment]
> Can you share what's the typical logs under the default setting and WARN level? We can see what's unintended logs. I think 
> the points are generally correct, but not actionable. We can only handle it case by case. 🤔️

This is the feedback from the user and I still try to get more details from them. 
Should we make a rules from our side? We should determine which log should show in which level. Do we have a rules or RFC in our level?

**Comment by xxchan** [comment]
> I think it maybe actionable. Can check the code and just search all the logs code to see whether some of them are useless?

What about analyzing a sample of the logs from a deployment (benchmark or longevity?). e.g., calculate total count/size by log target (prefix)? That might be more efficient than reviewing all logs.

**Comment by yufansong** [comment]
>   risingwave_frontend::scheduler::snapshot:: 14995 lines

it seems   `risingwave_frontend::scheduler::snapshot:: 14995 lines` take most of the data. Is this normal?

**Comment by xxchan** [comment]
> > risingwave_frontend::scheduler::snapshot:: 14995 lines
> 
> it seems `risingwave_frontend::scheduler::snapshot:: 14995 lines` take most of the data. Is this normal?

To clarify this is my local log, not one from a meaningful deployment. I just included it to show an example..

BTW that line is `unpin snapshot with RPC`. It's normal for an idle cluster to only have this log. It seems to be useful, but also indeed a little excessive (actually, only once every 10s (`UNPIN_INTERVAL_SECS`),  not that many). @BugenZhao how do you think about the usage of this line?

**Comment by BugenZhao** [comment]
> BTW that line is unpin snapshot with RPC. It's normal for an idle cluster to only have this log.

From my perspective, in production we should never include logs that are triggered automatically and periodically, unless they're user-facing. Also applies to the `DEBUG` logs in hummock event handler.

**Comment by yufansong** [comment]
> actually, only once every 10s (UNPIN_INTERVAL_SECS), not that many
I think this is not much compared with what cosumer mentioned. 
> I saw thousands of records per second in one case
But that user have not provide his log to us.

**Comment by xxchan** [comment]
Look at one example from longevity  (12h)

https://grafana.test.risingwave-cloud.xyz/d/liz0yRCZz1/log-search-dashboard?from=1698851271000&orgId=1&to=1698894601000&var-data_source=PE59595AED52CF917&var-namespace=reglngvty-20231101-150220&var-pod=benchmark-risingwave-compactor-c-6cc98796f5-54hz9&var-search=

 (I'm not familiar with Grafana queries. Hope I'm not wrong 🥵)

compactor: 15 MB

compute-0: 124 MB

meta: 5.7 MB

frontend: 148 KB


---

Notice meta/compute has a peak, which is strange. Sounds like the issue met by the user.



<img width="642" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/6be468e4-da0f-442a-912a-004313b18c1b">

<img width="636" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/fdb235da-2147-4d6c-9f75-7eb35251277f">

For compute, It seems to be rate-limiter

<img width="1674" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/edf1ff70-a101-4bda-b33d-5e14a5aa8363">

For meta, it seems to be 
<img width="1674" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/978ec8f6-c2f7-44f6-bf80-92ae4984014d">

**Comment by xxchan** [comment]
cc @zwang28 any ideas about the reason and/or how to mitigate?

**Comment by zwang28** [comment]
> Look at one example from longevity (12h)

Both the example lines you listed for meta node and compute node are caused by storage back-pressure.
If the cluster is healthy, these logs won't exist. So I doubt whether they're the root cause.
Anyway I'll make these log as DEBUG, because the info can be read from Grafana instead.

**Comment by xxchan** [comment]
> If the cluster is healthy, these logs won't exist.

But should we avoid excessive logs even when the cluster is unhealthy? 🤔️
If there are too many logs, it also obstruct diagnosing. Can we keep useful logs, but don't produce them repeatedly at the same time?...
