### ISSUE TITLE
dashboard UI indicate issue

### ISSUE THREAD

**Issue by yufansong** [risingwavelabs/risingwave#12611]
### Describe the bug

The dashboard UI did not indicate any issues even when the cluster became unstable: when a command to create a materialize view failed, but would not run again because it believed the command was still running.

**Comment by fuyufjh** [comment]
This is supposed to be provided in Cloud UI (console) instead of Kernel Dashboard. The later one doesn’t depend on Prometheus.

BTW, will do https://github.com/risingwavelabs/risingwave/issues/12366 on kernel side.
