### ISSUE TITLE
Create MV Stuck

### ISSUE THREAD

**Issue by yufansong** [risingwavelabs/risingwave#12639]
### Describe the bug

1. When user execute sql to create MV, it should be asynchronous. But currently we will block over there. Many customer will think we are crashed.
2. When try to cancel the sql, I try to press the contrl+c, it will show "send cancel reqeust" but still blocked.
3. Another wired thing hanppends today, when try to create mv, stucked at 0.0% via the result `show jobs`. Then try to cancel it by press contrl+c, but after that, there is some progress in `show jobs`

**Comment by BugenZhao** [comment]
> When user execute sql to create MV, it should be asynchronous.

This is a matter of personal opinion, and rare RDBMS does this. But yes, background DDL is indeed a work in progress. We may provide an option for this in the future.

**Comment by kwannoel** [comment]
> When user execute sql to create MV, it should be asynchronous. But currently we will block over there. Many customer will think we are crashed.

Currently user can do `SET BACKGROUND_DDL=true`. But this is experimental still, and the backfill progress is not recoverable (yet).

**Comment by yufansong** [comment]
Solved at #12644 and provide a hotfix.
