### ISSUE TITLE
test: simulate SQL-backend meta store

### ISSUE THREAD

**Issue by wangrunji0408** [risingwavelabs/risingwave#12707]
As we are migrating meta store backend from ETCD to SQL #12449, deterministic test should also be adapted.

There are 2 possible solutions for this task:
1. We may use temporary-file-based sqlite backend in the simulation. If we are lucky, there will be no need to hack any code.
2. If the above method doesn't work, or there are still uncertainties inside, we have to patch the `sqlx` crate or mock a backend using in-memory sqlite, like we did for `etcd-client` before.

**Comment by fuyufjh** [comment]
Basically done but there is one remaining issue: https://github.com/madsim-rs/madsim/issues/228
