### ISSUE TITLE
Create MV progress fall back

### ISSUE THREAD

**Issue by yufansong** [risingwavelabs/risingwave#12713]
### Describe the bug

When use `show jobs`, sometime the progress will fall back. For example from `14.51%` -> `14.49%`. 
This situation always appears when create MV stucked and maybe more data comes, then the data size increase and progress fall back.

For create MV stuck problem, record at here #12639

**Comment by BugenZhao** [comment]
This is expected because the workload may increase over time due to new changes from upstream.

**Comment by yufansong** [comment]
Sounds good, colsed.
