### ISSUE TITLE
feature request: print a error message including the failed `create materialized view` statement when recovery

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#12712]
Motivation: it would be helpful both for us and users:

- For users: we will pop-up an alter to user on our Cloud UI to inform him about the failure
- For us: the full `create materialized view` will help us to diagnose the problem

**Comment by xxchan** [comment]
We might need to also consider https://github.com/risingwavelabs/risingwave/issues/12673

**Comment by yezizp2012** [comment]
@kwannoel could you please help to di this after you finish recoverable background ddl?
