### ISSUE TITLE
bug: meta node suddenly hang

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#12769]
During longevity test, sometimes the meta will suddenly hang. No logs, no RPC, no metrics.

Example of metrics:

<img width="954" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/02b679d6-4851-401f-9896-7db185a1d405">

Example of logs:

<img width="539" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/8144a561-cfc9-4ae5-a4bb-c239ecbf0bb8">

**Comment by huangjw806** [comment]
v1.3-rc encountered the same problem after running for 10 hours.
https://buildkite.com/risingwave-test/longevity-kubebench/builds/717

**Comment by fuyufjh** [comment]
closed by https://github.com/risingwavelabs/risingwave/pull/12801
