### ISSUE TITLE
perf: scan concurrently in `RowSeqScanExecutor`

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#12783]
When no key ranges predicate on the iterator, the code will create as few as possible numbers of iterator, which could decrease the scan concurrency. So when scanning the whole table, it could be bounded by the iterator.

https://github.com/risingwavelabs/risingwave/blob/80f1d58b866b022fd2d5aac92dd2e5bae2c6ceb7/src/storage/src/table/batch_table/storage_table.rs#L421-L438

**Comment by lmatz** [comment]
Yes, multiple iterators are better than the explicit parallelism adjustment in #12741, with less change.

**Comment by BugenZhao** [comment]
Actually, this only affects the concurrency for **creating** the iterators. For actual scanning, we're always in a single-threaded manner.

https://github.com/risingwavelabs/risingwave/blob/80f1d58b866b022fd2d5aac92dd2e5bae2c6ceb7/src/storage/src/table/batch_table/storage_table.rs#L492-L499

**Comment by st1page** [comment]
> Actually, this only affects the concurrency for **creating** the iterators, which has been confirmed (IIRC) to be CPU-intensive in most cases. For actual scanning, we're always in a single-threaded manner.
> 
> https://github.com/risingwavelabs/risingwave/blob/80f1d58b866b022fd2d5aac92dd2e5bae2c6ceb7/src/storage/src/table/batch_table/storage_table.rs#L492-L499

It affects the number of iterators in the `futures::stream::iter(iterators)` in Line 496, which is also the number of futures awaited at the same time. Single-threaded manner here is ok and we only want to make the IO concurrency.

**Comment by st1page** [comment]
Oh, I get it now, So `futures::stream::iter().flatten()` will only concat all the iterators but not join the iterators together? So we need to make it concurrent too 🤔

**Comment by xxchan** [comment]
> When no key ranges predicate on the iterator, the code will create as few as possible numbers of iterator

I saw https://github.com/risingwavelabs/risingwave/pull/6927, where we intentionally to create fewer iterators, so I'm a little confused. 🤡

**Comment by st1page** [comment]
> > When no key ranges predicate on the iterator, the code will create as few as possible numbers of iterator
> 
> I saw #6927, where we intentionally to create fewer iterators, so I'm a little confused what to optimize for. 🤡

we need to scan concurrently for IO bound scan by polling multiple iterators at one time. So we need to split the range into multiple pieces.
