### ISSUE TITLE
Enhancement: show hidden column in `rw_columns`

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#12808]
### Is your feature request related to a problem? Please describe.

There is no reason to hide these columns in system table `rw_columns`. 

### Describe the solution you'd like

1. Need to show hidden columns in `rw_columns`
2. May add a `hidden boolean` column in `rw_columns` to show whether it's hidden.
3. By the way, do we have any way to know the primary key of a table? If not, probably we need a `primary_key boolean` column, too.

### Describe alternatives you've considered

Shall we show hidden columns in `show columns from <table>` as well? Either LGTM.

**Comment by fuyufjh** [comment]
Btw*2, is it possible to show distribution key here, too?

**Comment by yezizp2012** [comment]
> Btw*2, is it possible to show distribution key here, too?

Yeah, I think it's feasible. I will add a `distribution_key boolean` for it as well.
