### ISSUE TITLE
Panicked when processing: insert at index 4 exceeds fixbitset size 2

### ISSUE THREAD

**Issue by YuanchengJiang** [risingwavelabs/risingwave#12819]
### Describe the bug

This may related to #12818 

### To Reproduce

```
CREATE TABLE test1 (c_0 TIMESTAMP, c_1 INT, c_2 FLOAT);
CREATE TABLE test2 (c_0 TIMESTAMP, c_1 INT, c_2 FLOAT);
SELECT max(T1.c_0) OVER(PARTITION BY T2.c_0<>T1.c_0) FROM test1 AS T1 INNER JOIN test2 AS T2 ON T1.c_0>T2.c_0 group by T1.c_0,T2.c_0;
```

### How did you deploy RisingWave?

Docker

### The version of RisingWave

PostgreSQL 9.5-RisingWave-1.2.0 (f27f085e4433eb4b3b9e8df61b3f94406f654d89)

**Comment by xxchan** [comment]
duplicate with #10666, already fixed in main
