### ISSUE TITLE
feat(observability): a command check cluster information & status

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#12826]
As requested by users, we need a command to quickly tell the status of cluster, including

- Nodes and their heartbeats e.g. the number/IP/resource/etc. of all registered nodes
- Brief runtime info e.g. Current epoch, latency, etc. 
- Brief catalog info e.g. How any MVs or actors are running?
- Misc. RW version, uptime, etc.

**Comment by zwang28** [comment]
> Nodes and their heartbeats e.g. the number/IP/resource/etc. of all registered nodes
Brief runtime info e.g. Current epoch, latency, etc.
Brief catalog info e.g. How any MVs or actors are running?
Misc. RW version, uptime, etc.

The above-mentioned info are now available through several system tables.
Are we supposed to further add another new command to summarize them?

**Comment by fuyufjh** [comment]
related https://github.com/risingwavelabs/risingwave/pull/13764

**Comment by zwang28** [comment]
TODO: add table catalog after redaction is supported.
