### ISSUE TITLE
Integration test failure and unstable cases

### ISSUE THREAD

**Issue by huangjw806** [risingwavelabs/risingwave#12893]
There are some failed and unstable cases in daily integration tests：

- [x] iceberg-sink timeout;
- [x] citus-cdc failed;
- [x] #14541

Here is a typical pipeline：
https://buildkite.com/risingwavelabs/integration-tests/builds/303
<img width="1206" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/29391315/c48165a9-0526-40aa-a70b-7326e98bd957">

**Comment by StrikeW** [comment]
>=> CANCELED [spark-worker spark 3/6] RUN rm -r /opt/bitnami/spark/jar  1642.2s

The iceberg case timeout due to pulling the image of `spark-worker`, PTAL @xxhZs

**Comment by StrikeW** [comment]
@tabVersion  PTAL the `kinesis-s3-source` case, it has been unstable for a period.

**Comment by StrikeW** [comment]
citus-cdc start to fail on Monday, investigating.

**Comment by tabVersion** [comment]
> @tabVersion PTAL the `kinesis-s3-source` case, it has been unstable for a period.

Yes, I am looking into it

**Comment by tabVersion** [comment]
found massive error logs from source

```
compute-node-0  \| 2023-10-16T14:19:03.11352992Z ERROR actor{otel.name="Actor 52" actor_id=52 prev_epoch=5258001957584896 curr_epoch=5258001966956544}:executor{otel.name="RowIdGenExecutor 3400000006 (actor 52)" actor_id=52}:executor{otel.name="SourceExecutor 3400002807 (actor 52)" actor_id=52}:source_parser{actor_id=52 source_id=1002}:parse_one{split_id="data-1697465850283" offset="6085"}: risingwave_connector::parser: failed to parse message, skipping error=Protocol error: Eof at character 0
compute-node-0  \| 2023-10-16T14:19:03.116833657Z ERROR actor{otel.name="Actor 209" actor_id=209 prev_epoch=5258001957584896 curr_epoch=5258001966956544}:executor{otel.name="Materialize D100000003 (actor 209)" actor_id=209}:executor{otel.name="ProjectExecutor D100000002 (actor 209)" actor_id=209}:executor{otel.name="RowIdGenExecutor D100000001 (actor 209)" actor_id=209}:executor{otel.name="SourceExecutor D100002736 (actor 209)" actor_id=209}:source_parser{actor_id=209 source_id=1002}:parse_one{split_id="data-1697465830183" offset="6027"}: risingwave_connector::parser: failed to parse message, skipping error=Protocol error: Eof at character 0
```

suspect `localstack` service is not that stable

**Comment by StrikeW** [comment]
> citus-cdc start to fail on Monday, investigating.

The citus test case should be modified. https://github.com/risingwavelabs/risingwave/pull/12898

**Comment by huangjw806** [comment]
> > citus-cdc start to fail on Monday, investigating.
> 
> The citus test case should be modified. #12898

any updates for citus test case?

**Comment by huangjw806** [comment]
> kinesis-s3-source unstable

any update about this case？cc @tabVersion
