### ISSUE TITLE
Cannot connect to connector when starting up risingwave with risedev

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#12922]
### Describe the bug

Hit `environment variable CONNECTOR_LIBS_PATH is not specified` when trying to CREATE TABLE for mysql-cdc with risingwave started up via risedev

### Error message/log

```text
dev=> set cdc_backfill='true';

CREATE TABLE lineitem_rw (
   k int primary key,
   v int
) WITH (
    connector = 'mysql-cdc',
    hostname = '127.0.0.1',
    port = '8306',
    username = 'root',
    password = '123456',
    database.name = 'test',
    table.name = 'test',
    server.id = '2'
);
SET_VARIABLE
ERROR:  QueryError: internal error: internal error: environment variable CONNECTOR_LIBS_PATH is not specified
```

### To Reproduce

1. `risedev configure` to enable connector build
2. `risedev d` to start dev playground
3. Start up a local mysql instance and create a test table.
4. Run the following query in psql
```
dev=> set cdc_backfill='true';
SET_VARIABLE

dev=>CREATE TABLE lineitem_rw (
   k int primary key,
   v int
) WITH (
    connector = 'mysql-cdc',
    hostname = '127.0.0.1',
    port = '8306',
    username = 'root',
    password = '123456',
    database.name = 'test',
    table.name = 'test',
    server.id = '2'
);

ERROR:  QueryError: internal error: internal error: environment variable CONNECTOR_LIBS_PATH is not specified

```

**Comment by hzxa21** [comment]
I tried the following and none work:
1.
```
export CONNECTOR_LIBS_PATH=.risingwave/bin/connector-node/libs/
./risedev d
```

2.
```
CONNECTOR_LIBS_PATH=.risingwave/bin/connector-node/libs/ ./risedev d
```

**Comment by BugenZhao** [comment]
> I tried the following and none work:

We should definitely handle this in RiseDev.

**Comment by chenzl25** [comment]
Could you please check this file `./risedev-components.user.env`? It should contain `CONNECTOR_LIBS_PATH=.risingwave/bin/connector-node/libs/` if risedev configures to enable connector build.

**Comment by hzxa21** [comment]
Just remember that risedev uses risedev. It is fixed in #12928

**Comment by hzxa21** [comment]
> Could you please check this file `./risedev-components.user.env`? It should contain `CONNECTOR_LIBS_PATH=.risingwave/bin/connector-node/libs/` if risedev configures to enable connector build.

The env is set in risedev-components.user.env but it didn't work in my local box

**Comment by hzxa21** [comment]
The problem goes away today in my local box. The only thing that is different than yesterday is I have restarted my local box. I think this is related to when tmux reads the env of the host:
> When the server is started, tmux copies the environment into the
     global environment; in addition, each session has a session
     environment.
https://man7.org/linux/man-pages/man1/tmux.1.html#GLOBAL_AND_SESSION_ENVIRONMENT

That means if tmux server is started after `risedev configure` when `CONNECTOR_LIBS_PATH` is exported, all tmux sessions will see this env. Otherwise, if my tmux server has already started before I enable connector build (I think this is why happened yesterday), all tmux sessions won't see this env.
