### ISSUE TITLE
bug: cannot load history data when creating cdc from the same table in second time

### ISSUE THREAD

**Issue by tabVersion** [risingwavelabs/risingwave#12923]
### Describe the bug

1. create a table t1 with connector `mysql-cdc`
2. cancel t1 when creating 
3. create a table t2 with connector `mysql-cdc` (load the same table from the upstream MySQL as t1)
4. observe RW will not load history data from upstream MySQL

**Comment by SevenLM361** [comment]
## Describe the bug
1. create a table t1 with connector mysql-cdc
2. drop table t1 when data type error is found
3. recreate a table t1 with connector mysql-cdc (load the same table from the upstream MySQL as t1)
4. observe RW will not load history data from upstream MySQL

**Comment by tabVersion** [comment]
close as false alarm
