### ISSUE TITLE
bug: insert null as pk causing jdbc sink panic

### ISSUE THREAD

**Issue by tabVersion** [risingwavelabs/risingwave#12933]
### Describe the bug

![image](https://github.com/risingwavelabs/risingwave/assets/14017336/bae989b3-540e-4f1a-86e7-ead5a890d14a)

the above sql will result in a channel close error, which users can not understand

the root casue found in CN, the pk is null and make sink exec panic

```
	
{"timestamp":"2023-10-18T03:03:34.181682374Z","level":"ERROR","fields":{"message":"failed to collect barrier: Actor 29 exit unexpectedly: Executor error: Sink error: Remote sink error: gRPC error (Internal error): Error when exec INSERT INTO public.room_user_visit_1min(report_ts, uv, room_id) VALUES (NULL, 1, '1364688900') ON CONFLICT (report_ts, room_id) DO UPDATE SET report_ts=EXCLUDED.report_ts, uv=EXCLUDED.uv, room_id=EXCLUDED.room_id
RETURNING *, message ERROR: null value in column \"report_ts\" of relation \"room_user_visit_1min\" violates not-null constraint
  Detail: Failing row contains (null, 1364688900, 1).
  backtrace of `StreamExecutorError`:
   0: <risingwave_stream::executor::error::Inner as core::convert::From<risingwave_stream::executor::error::ErrorKind>>::from
             at ./risingwave/src/stream/src/executor/error.rs:40:10
   1: <T as core::convert::Into<U>>::into
             at ./rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/convert/mod.rs:717:9
   2: <risingwave_stream::executor::error::StreamExecutorError as core::convert::From<risingwave_stream::executor::error::ErrorKind>>::from
             at ./risingwave/src/stream/src/executor/error.rs:143:34
   3: <T as core::convert::Into<U>>::into
             at ./rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/convert/mod.rs:717:9
   4: <risingwave_stream::executor::error::StreamExecutorError as core::convert::From<risingwave_connector::sink::SinkError>>::from
             at ./risingwave/src/stream/src/executor/error.rs:209:33
   5: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at ./rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/result.rs:1961:27
   6: risingwave_stream::executor::sink::SinkExecutor<F>::execute_consume_log::{{closure}}
             at ./risingwave/src/stream/src/executor/sink.rs:279:25
```

**Comment by StrikeW** [comment]
kernel version 1.2.0.
Sink error causes the Actor exit, then trigger the recovery procedure which will reset the compute node.

**Comment by tabVersion** [comment]
had a discussion with @st1page, the expected behavior is to discard the record with NULL pk. This rule applies to all `connector x format` with the required `primary_key`.

The only problem left is `kinesis x append-only`, kinesis requires a message key but it does not mean anything in append-only, what do you think @xiangjinwu

**Comment by xiangjinwu** [comment]
You meant as a natural extension `kinesis x append-only` would also discard records with `null`s in pk, but it is also okay (maybe preferred) not to discard them?

As long as it writes to a message queue, having nulls in some pk columns (including all nulls) is not as severe as inserts into a DB. The actual meaning is partition key #9768.

**Comment by tabVersion** [comment]
After some discussion, I think it is a expected behavior. We've proposed log store to handle such case. And we don't need to add extra behavior than let it stuck on.
