### ISSUE TITLE
optimizer: bool expression folding "self equal" as always true 

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#12931]
https://github.com/risingwavelabs/risingwave/blob/34ec26075cf45cd2679f0e30aaa4d4e52eb5187d/src/frontend/planner_test/tests/testdata/output/ch_benchmark.yaml#L693-L694

**Comment by xzhseh** [comment]
It's worth noticing that this does not only happen to `StreamFilter`, but also the predicates of `StreamHashJoin` and `BatchHashJoin`.
https://github.com/risingwavelabs/risingwave/blob/34ec26075cf45cd2679f0e30aaa4d4e52eb5187d/src/frontend/planner_test/tests/testdata/output/ch_benchmark.yaml#L3333

https://github.com/risingwavelabs/risingwave/blob/34ec26075cf45cd2679f0e30aaa4d4e52eb5187d/src/frontend/planner_test/tests/testdata/output/ch_benchmark.yaml#L3351

https://github.com/risingwavelabs/risingwave/blob/34ec26075cf45cd2679f0e30aaa4d4e52eb5187d/src/frontend/planner_test/tests/testdata/output/ch_benchmark.yaml#L3370
