### ISSUE TITLE
perf: kafka source performance regression due to tracing

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#12959]
![image](https://github.com/risingwavelabs/risingwave/assets/5791930/32704ca7-70cd-453e-b89b-f8c650d9fb24)

To verify if it is the environment's impact, we re-run a `nightly-20231001` image as the last data point, its performance is good.

The first drop happens between `nightly-20231008` and `nightly-20231009`, the second drop happens between `nightly-20231012` and `nightly-20231015`

commits between 1008 and 1009
```

## nightly-20231009
- 5ae9a360daeeefba400e44d066c76e2bc2526ff0 chore: Update Slack link to a permanent one in README (#12700) https://github.com/risingwavelabs/risingwave/pull/12700
- 2fef0544a7ec4c4fe9921e35f421793c6e68b29a fix: add "ts_ms" in source (#12703) https://github.com/risingwavelabs/risingwave/pull/12703
- 0c4013cc3a95caa465c51028c5d80c1f33ca413b chore(deps): bump etcd-client to v0.12.1 (#12705) https://github.com/risingwavelabs/risingwave/pull/12705
- 9db52aab732b4a851ec397e91c2182b7f5e58056 ci: fix disk out of space for GHA (attempt 2) (#12671) https://github.com/risingwavelabs/risingwave/pull/12671
- bfdafe1b65741b11c8d998b052c1ae1bbff697dd refactor(common): refine `Row` changes in #11070 (#12652) https://github.com/risingwavelabs/risingwave/pull/12652
- da5099bbcc1a26670d7e040dd1b65070f03e1652 perf(stream agg): flush dirty agg groups according to heap size (#12453) https://github.com/risingwavelabs/risingwave/pull/12453
- 2a7ef0d808f17a0e82ee72e6376e7f77c2ba07aa fix(log-store): handle unaligned epoch after recovery (#12407) https://github.com/risingwavelabs/risingwave/pull/12407
- 456f3e98d7a00e3c383f8b03ee40b5da09af58d9 chore(storage): upgrade write limit (#12658) https://github.com/risingwavelabs/risingwave/pull/12658
- 54e8c759a295ff9ac6888b34520bdb1c48a6c363 chore: Update Slack link in README.md (#12697) https://github.com/risingwavelabs/risingwave/pull/12697
- b4f357c22d825a6caad31011e718ab88c41f1bc2 feat(connector): structural logging for parsing error (#12659) https://github.com/risingwavelabs/risingwave/pull/12659
- fbd54d89b05a27f9f8da803e0e29d3b0c4b2e366 fix(storage): fix block format comment (#11664) https://github.com/risingwavelabs/risingwave/pull/11664
- da1e7bed1a6eaf2180ec4f5c57d189227ff08a99 chore: update cherry pick action version (#12692) https://github.com/risingwavelabs/risingwave/pull/12692
- 31cf3f8f1b827fad5572a6a188507a01f5b396ba fix(storage): fix compact_fast_runner_bytes unused (#12655) https://github.com/risingwavelabs/risingwave/pull/12655
- fcdc3a112bb64ac151d44cc48f0bb143d92d456d perf(expr): avoid parsing unit every time on `extract` and `date_part` (#12398) https://github.com/risingwavelabs/risingwave/pull/12398
- ca2509546d056c863752bd4b7568cf0aa5559fe6 chore(deps): Bump byteorder from 1.4.3 to 1.5.0 (#12666) https://github.com/risingwavelabs/risingwave/pull/12666
- a8b25ac3133c1f65bffa467bcfc884b949cca23d fix(doc): fix debian-like installation guide (#12684) https://github.com/risingwavelabs/risingwave/pull/12684
- 8b082dea901084c5f9a6462789e18f77dbe3efc0 chore(deps): Bump similar from 2.2.1 to 2.3.0 (#12668) https://github.com/risingwavelabs/risingwave/pull/12668

## nightly-20231008
```

We notice that q0 is a stateless query that does no computation and no state access, so likely to be some issue related to `parsing` I guess?

**Comment by huangjw806** [comment]
cc @st1page

**Comment by st1page** [comment]
q0
`nightly-20231008` compute CPU 620%~640% higher source throughput, I guess it is source-bound.
`nightly-20231009` compute CPU 780% less source throughput,I guess it is CPU bound.

So we need to check the CPU perf flame graph to find out which part consumes the CPU

**Comment by lmatz** [comment]
q0:
![perf-nexmark-q0](https://github.com/risingwavelabs/risingwave/assets/5791930/f38c4519-8cb7-4a10-b4ba-bfeb5f1b74cd)

**Comment by lmatz** [comment]
`nightly-20231009`: https://buildkite.com/risingwavelabs/cpu-flamegraph/builds/28#018b46f5-a8ac-4f67-9149-848a297897f0

**Comment by st1page** [comment]
nightly-20231008
git-8b18a7e7746613ff5fe056d7b4fd15e6747bc02e
nightly-20231009
git-5ae9a360daeeefba400e44d066c76e2bc2526ff0

**Comment by lmatz** [comment]
![SCR-20231019-naq](https://github.com/risingwavelabs/risingwave/assets/5791930/02bc82be-7a91-4aad-9266-a43ee721143e)
![SCR-20231019-nau](https://github.com/risingwavelabs/risingwave/assets/5791930/e6781db3-5fad-4d00-99a0-ee32203285c7)


`do_action` +6%

**Comment by BugenZhao** [comment]
Could it be #5214 again?

**Comment by st1page** [comment]
> Could it be #5214 again?

No, they are balanced :thinking:

**Comment by fuyufjh** [comment]
[flamegraph_.zip](https://github.com/risingwavelabs/risingwave/files/13067997/flamegraph_.zip)

**Comment by lmatz** [comment]
The flamegraph can be downloaded or directly examined in the Buildkite URL, under the `artifacts` tab.

**Comment by xxchan** [comment]
> nightly-20231009 compute CPU 780% less source throughput,I guess it is CPU bound.


However for the second drop, the CPU usage dropped back, but the perf is even worser.

<img width="438" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/505b19a2-cb6b-4674-9c2d-0cfc439b44db">


commits between 12-15

```

## nightly-20231015
- b441341d3ced9cb155de2a1b9a5dabe67a9f7c2b chore(deps): bump rdkafka to v0.34.0 and librdkafka to v2.2.0 (#11232) https://github.com/risingwavelabs/risingwave/pull/11232
- 387d251b722a65dd7147b04aff611a2381c44bf4 feat(optimizer): optimize join stream key (#12831) https://github.com/risingwavelabs/risingwave/pull/12831
- 103826b8dcbe9528d826a77504bf4cf5851d44d7 chore(deps): Bump zstd from 0.12.4 to 0.13.0 (#12794) https://github.com/risingwavelabs/risingwave/pull/12794

## nightly-20231013
- c9840edd3ef3da07ce97d69ec558dd8fb7bf7bb7 fix(compaction): fix can not pick task when there are many files overlap (#12790) https://github.com/risingwavelabs/risingwave/pull/12790
- 369c1f30a39a57eac5ec43b1fa628b188e99e846 doc(cmd_all): add docs on standalone mode (#12828) https://github.com/risingwavelabs/risingwave/pull/12828
- ac4ae56441ac6448edfd19d548606a7b6b5fb678 refactor(memory): use 0.7 * system memory as default `total_memory_bytes` (#12832) https://github.com/risingwavelabs/risingwave/pull/12832
- 7761c4ff18b19718d8dbde5e862505e8bbdef74e feat(storage): filecache lazy load, unit-level refill, reduce insert latency (#12714) https://github.com/risingwavelabs/risingwave/pull/12714
- 0364affce14b26a6cf43b15f2a5915bb9b698142 fix: Revert "feat: use seperated runtime for source manager (#12571)" (#12801) https://github.com/risingwavelabs/risingwave/pull/12801
- f27182f35cad6831b5751f677f32645aa1321613 fix(state table): add the accidentally deleted prefix_hint back (#12817) https://github.com/risingwavelabs/risingwave/pull/12817

## nightly-20231012
```

Only #11232 looks suspicious to me.

**Comment by xxchan** [comment]
Just confirmed that the second drop is caused by rdkafka bump 

387d251b722a65dd7147b04aff611a2381c44bf4's performance is better

<img width="379" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/6587d3ef-a5bc-4d63-8417-1d0e32d5f7e2">

**Comment by xxchan** [comment]
First regression is #12659 cc @BugenZhao 

<img width="415" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/81e9d1fe-81e9-4ff8-886f-3d2834024fec">

cpu 

<img width="399" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/0aadea05-d308-4829-99ee-700209483f2f">

**Comment by BugenZhao** [comment]
> First regression is #12659 cc @BugenZhao

But why the flamegraph shows that `risingwave` takes less CPU in 1009? 😕

**Comment by xxchan** [comment]
I tried to revert #12659 on latest main (https://github.com/risingwavelabs/risingwave/tree/xxchan/revert-12659), it seems this also cancelled the affect of rdkafka bump. 🤡

<img width="1133" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/15995571-c757-46ba-8f38-60d85dcf3a99">

**Comment by BugenZhao** [comment]
I cannot observe anything useful from the flame graphs provided above, perhaps the files for 10/08 and 10/09 are incorrect?

However, in #13073 I can clearly find `tracing::info_span!` introduced in #12659 leads to an overhead of 30% (😨).

https://github.com/risingwavelabs/risingwave/blob/1ca0a8030cf631886e599894d688d1768501b2a2/src/connector/src/parser/mod.rs#L540-L544  

<img width="995" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/25862682/d9e1b7e2-e010-4700-9f1d-fd0204b3e143">
(27% parse, 19% chunk building, 30% tracing)

----

Why it takes so much CPU time: 

The `fmt` layer in `tracing-subscriber` **eagerly** formats the given fields on span creation, possibly because it only receives references to the fields. However, the span is only used to provided more context when a parsing error occurs, which means that in most of time this work is wasted.

**Comment by BugenZhao** [comment]
> perf: kafka source performance regression due to tracing

So what about #11232?

**Comment by xxchan** [comment]
> > perf: kafka source performance regression due to tracing
> 
> So what about #11232?

According to 

> I tried to revert https://github.com/risingwavelabs/risingwave/pull/12659 on latest main ([xxchan/revert-12659](https://github.com/risingwavelabs/risingwave/tree/xxchan/revert-12659?rgh-link-date=2023-10-25T05%3A38%3A21Z)), in order to see what's the rdkafka's impact on its own, but it seems this also cancelled the impact of rdkafka bump. 🤡

I'm not sure whether we need to investigate rdkafka further. 🤡
