### ISSUE TITLE
construct and pass in distinct mininput `order_col_indices` and `order_types`

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#13044]
https://github.com/risingwavelabs/risingwave/pull/13015/files#r1369627023

**Comment by fuyufjh** [comment]
Hi, any progress?

**Comment by KeXiangWang** [comment]
Going to work on this today.

**Comment by KeXiangWang** [comment]
finished in https://github.com/risingwavelabs/risingwave/pull/13376
