### ISSUE TITLE
the documented `type` option of elasticsearch sink doesn't exist

### ISSUE THREAD

**Issue by docteurklein** [risingwavelabs/risingwave#13074]
### Error message/log

```text
ERROR:  QueryError: internal error: Sink error: Remote sink error: sink cannot pass validation: unknown field `type`
```

### To Reproduce

https://github.com/docteurklein/risingwave-demo/blob/main/rw/product.sql#L76

```
create sink product_to_es
-- as select product_id, attribute, channel, locale, value::text from pim1.product_value
from pim1.product_value
with (
  connector = 'elasticsearch',
  type = 'upsert',
  index = 'product',
  url = 'http://es:9200',
);
```

### Expected behavior

I want to have `upsert` behaviour.

### The version of RisingWave

 PostgreSQL 9.5-RisingWave-1.3.0-alpha (bb2319e460cac272803837f39ac70b1c40268b9b)

**Comment by hzxa21** [comment]
ES sink is in `upsert` mode by nature since ID is required to update the ES doc so the `type` option is not needed.

It seems that the documentation is inconsistent with the current implementation. We will fix it. Thanks for reporting the issue.

**Comment by hengm3467** [comment]
Just want to update here that the documentation has been updated.
