### ISSUE TITLE
include connector-node's jar and dependency libs in the release package

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#13089]
### Is your feature request related to a problem? Please describe.

As connector node is now embedded in the binary, it should be shipped together as well.

**Comment by chenzl25** [comment]
For v1.3.0, I think we can merge this connector [risingwave-connector-v1.3.0.tar.gz](https://github.com/risingwavelabs/risingwave/releases/download/v1.3.0/risingwave-connector-v1.3.0.tar.gz) one into the [risingwave-v1.3.0-x86_64-unknown-linux.tar.gz](https://github.com/risingwavelabs/risingwave/releases/download/v1.3.0/risingwave-v1.3.0-x86_64-unknown-linux.tar.gz)

**Comment by chenzl25** [comment]
After that users should prepare `CONNECTOR_LIBS_PATH` for the `risingwave` binary. 
CONNECTOR_LIBS_PATH=/the/path/to/connector/libs/
