### ISSUE TITLE
`ColIndexMapping::without_target_size` is error-prone

### ISSUE THREAD

**Issue by stdrc** [risingwavelabs/risingwave#13100]
https://github.com/risingwavelabs/risingwave/pull/13090#issuecomment-1782219418

`ColIndexMapping` is used to represent column change mapping in optimizer, the concept `src_size` and `target_size` of `ColIndexMapping` means schema length before change and schema length after change respectively. While in many occurrence we use `ColIndexMapping::without_target_size` to derive `target_size` from the mapping itself, which will lead to smaller `target_size` than the real schema length that it should be. If any code relies on the correctness of `target_size`, it will fail very subtly.

**Comment by st1page** [comment]
https://github.com/risingwavelabs/risingwave/issues/7234
