### ISSUE TITLE
Discussion: create/alter sink without backfill

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#13102]
Currently the only way for user to modify the definition or query of an existing sink is to drop and re-create the sink. Although there is no correctness issue if user only needs at-least-once delivery for its sink, this approach generates excessive duplicates because a backfill step is required in CREATE SINK, which is worth optimizing.

Ideas:
1. Support `CREATE SINK` without backfilling. This is basically sink from latest and it may cause data loss if there are data ingested after `DROP SINK` and before `CREATE SINK`.
2. Support `ALTER SINK`. This is basically performing a transactional DDL with `DROP SINK` + `CREATE SINK` without backfilling.

**Comment by fuyufjh** [comment]
+1 for both. 

> Support CREATE SINK without backfilling

This is super useful especially when user recreate a sink, mostly because the depending pipeline is recreated.

> Support ALTER SINK. This is basically performing a transactional DDL with DROP SINK + CREATE SINK without backfilling.

Agree

**Comment by chenzl25** [comment]
Sounds good. We can simply change the `ChainType` of `StreamTableScan` to implement this feature.

**Comment by st1page** [comment]
How about the syntax of the temporal table?
https://learn.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables?view=sql-server-ver16#how-do-i-query-temporal-data

```SQL
CREATE SINK s AS SELECT * FROM t FOR SYSTEM FROM TIMESTAMP '1999-01-01 01:23:34' TO now();
```

And for the too-old data, we can reject it.

**Comment by hzxa21** [comment]
> How about the syntax of the temporal table? https://learn.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables?view=sql-server-ver16#how-do-i-query-temporal-data
> 
> ```sql
> CREATE SINK s AS SELECT * FROM t FOR SYSTEM FROM TIMESTAMP '1999-01-01 01:23:34' TO now();
> ```
> 
> And for the too-old data, we can reject it.

This syntax basically means sink can consume from a user provided timestamp (i.e. seek from timestmap), which is more generic yet more complicated than my original ideas. However, table/MV currently doesn't provide a changelog so I wonder how we can implement that. Some immature options in my mind:
- Backfill snapshot read is still enabled but using our internal epoch to filter by time. Note that tombstones also need to be exposed.
- Backfill snapshot read is disable and only support seek from timestamp if log store is enabled

**Comment by st1page** [comment]
> Backfill snapshot read is still enabled but using our internal epoch to filter by time. Note that tombstones also need to be exposed.

In theory, we can achieve that by maintaining the L0 files within a certain time.

**Comment by fuyufjh** [comment]
> Sounds good. For `create sink from a mv` We can simply change the `ChainType` of `StreamTableScan` to implement this feature. For `create sink from a complex sql`, it will break the sanity check.

Good point. Need some extra thought for the case of complex SQL. 🤔

-----------

I am thinking about using "create-new -> rename -> drop-old" way to "alter" sink:

Image that we have `MV1_v1`, `MV2_v1` and it was recreated to `MV1_v2` and `MV2_v2`.

```
MV_a_v1 ----
            |---> Sink_ab_v1
MV_b_v1 ----

MV_a_v2 ----
            |---> Sink_ab_v2
MV_b_v2 ----
```

Now we want to swith from Sink_ab_v1 to Sink_ab_v2. Ideally, at some moment, Sink_ab_v1 should stop outputting and Sink_ab_v2 start outputting automatically. 

But this seems to diverge from @hzxa21's initial idea because it requires backfilling... Let me consider more.

**Comment by kwannoel** [comment]
I don't see why we can't support ALTER SINK with backfill. Currently backfill will persist the backfilled offset. I'm thinking that even if we alter sink, we can still use the backfill state to recover our progress.

**Comment by BugenZhao** [comment]
> For `create sink from a complex sql`, it will break the sanity check.

Agree. This is simply a specialized form of "Alter MV", without reusing any states. So sanity check inside a streaming job can be easily broken.

**Comment by BugenZhao** [comment]
> we can still use the backfill state to recover our progress, so there will be no duplicates

IIUC, this only holds if the epoch does not advance, i.e., the upstream does not make any progress during the "recovery". To achieve this we need to introduce a new barrier command to combine `DROP` and `CREATE`, so that they can be done in a single epoch. If we make it simply a sugar in the frontend (still issuing two RPCs to meta), then we have to first pause the data sources.

**Comment by BugenZhao** [comment]
Actually what we're talking about here is **exactly the same** as "Alter MV" that we've discussed before.

> this approach generates excessive duplicates because a backfill step is required in CREATE SINK

This also applies to materialized views in RisingWave, where we should avoid duplicate change logs to downstream sinks or materialized views.

So I would suggest directly implementing the general case of "Instant State Mapping" approach mentioned in this [doc](https://www.notion.so/risingwave-labs/The-Impossible-Trinity-of-Alter-Materialized-Views-8beb3c7707eb46f1aed45c92312ef42a), while we can selectively enable it on sinks first as it does not suffer from the definition soundness of materialized views (which is going to be resolved by `CREATE SINK INTO TABLE`).

**Comment by hzxa21** [comment]
> Support ALTER SINK. This is basically performing a transactional DDL with DROP SINK + CREATE SINK without backfilling.

> If we make it simply a sugar in the frontend (still issuing two RPCs to meta), then we have to first pause the data sources.

> So I would suggest directly implementing the general case of "Instant State Mapping" approach mentioned in this [doc](https://www.notion.so/risingwave-labs/The-Impossible-Trinity-of-Alter-Materialized-Views-8beb3c7707eb46f1aed45c92312ef42a), while we can selectively enable it on sinks

I think my original idea of supporting ALTER SINK without backfilling is very similar or even equivalent to applying "Instant State Mapping" approach only to sink. Here are the steps of ALTER SINK I imagined before:
1. Inject a pause barrier to enforce a checkpoint and pause data source before plan changes
2. Stop the sink actors (can be done along with 1 as an optimization) 
3. Inject a resume barrier to conduct sink plan changes (with the new sink schema or new sink graph) and resume data source, without destroying the sink's upstream state tables / executors.

**Comment by fuyufjh** [comment]
https://github.com/risingwavelabs/risingwave/issues/12080

**Comment by hzxa21** [comment]
> After discussing with @hzxa21 offline, it was thought that alter might be a more complicated thing to do, and that there might be alter mv bindings when used. And a similar effect can be achieved by drop sink + parse source + create mv without backfill. So tend to do create mv without backfill first. Regarding create sink without backfill, there are two cases.
> 
> 1. create mv from mv . In this case, we just need to pause the snapshot read of the backfill.
> 2. create mv from select xxx, in which case we need to take into account state padding and  sanity check for some operators.
>    2.1. Here, we can differentiate between streaming data and snapshot data during backfill and have the sink operator delete filter out the snapshot data from being sent down the line.
>    2.2. or we include a semantics, create mv from select xxx without backfill means start over with a new sink, all stock data is disregarded. This way we only need to flag not doing sanity check, but it may lead to inconsistent results with create mv from mv and not be used in the link of the alter
> 
> Prefer 1+2.1

I think there is a typo here. By 1, you mean **CREATE SINK FROM MV** and by 2 you mean **CREATE SINK AS <query>**. IIUC, 2.1 means create sink **with** backfill but only sink changes after backfill to downstream. In this case, sanity check can be enabled without issues. 2.2 means create sink **without** backfill and disable sanity check. I also prefer 1 + 2.1. Implementation-wise, I think we can do 1 first since it is more trivial and leave 2 to further discussions. Note that CREATE SINK AS <query> can be easily converted to CREAT SINK FROM <mv> with extra storage cost so I believe with 1 implemented, we at least have a workable solution for most use cases.

**Comment by BugenZhao** [comment]
> Here, we can differentiate between streaming data and snapshot data during backfill

Is this true? By backfilling the streaming data will be interleaved with the snapshot data, so it seems not possible for the sink executor to distinguish between them. In the contrast, it sounds possible for the plain old `Chain` while streaming data is always consumed after all the snapshot has been ingested.

> CREATE SINK FROM MV

May I ask what we are going to alter for a `SINK FROM MV` job? 😢 The only meaningful changes I can come up with is the sink properties.

> In this case, sanity check can be enabled without issues.

As mentioned in https://github.com/risingwavelabs/risingwave/issues/13102#issuecomment-1784448866, this seems not true even if the source is paused. Any workloads that relies on the real-world time (like Temporal Filter) could still be problematic.

**Comment by xxhZs** [comment]
> > Here, we can differentiate between streaming data and snapshot data during backfill
> 
> Is this true? By backfilling the streaming data will be interleaved with the snapshot data, so it seems not possible for the sink executor to distinguish between them. In the contrast, it sounds possible for the plain old Chain while streaming data is always consumed after all the snapshot has been ingested.

Here as a whole, it does look like it's all mixed up, but by backfill's PK split buckets, it seems to be all about consuming the snapshots first, then consuming the streaming data

> > CREATE SINK FROM MV
> 
> May I ask what we are going to alter for a SINK FROM MV job? 😢 The only meaningful changes I can come up with is the sink properties.
Yes, we have chain operators in our system that don't do backfill, we just need to set up different operators (backfill and chain) on the front end depending on the sink type

**Comment by fuyufjh** [comment]
> > > Here, we can differentiate between streaming data and snapshot data during backfill
> > 
> > 
> > Is this true? By backfilling the streaming data will be interleaved with the snapshot data, so it seems not possible for the sink executor to distinguish between them. In the contrast, it sounds possible for the plain old Chain while streaming data is always consumed after all the snapshot has been ingested.
> 
> Here as a whole, it does look like it's mixed , but by backfill's PK split buckets, it seems to be all about consuming the snapshots first, then consuming the streaming data

At `backfill` executor, yes, it's easy to tell whether a row is from snapshot or from upstream; however, after flowing through some executors, this become tricky. For example, if a `count(*)` aggregation is added by a "new" row (i.e. from upstream) first, then added by a "old" (i.e. from snapshot) row, does the second update belongs to "new" or "old"?

**Comment by BugenZhao** [comment]
> > > > Here, we can differentiate between streaming data and snapshot data during backfill
> 
> > > 
> 
> > > 
> 
> > > Is this true? By backfilling the streaming data will be interleaved with the snapshot data, so it seems not possible for the sink executor to distinguish between them. In the contrast, it sounds possible for the plain old Chain while streaming data is always consumed after all the snapshot has been ingested.
> 
> > 
> 
> > Here as a whole, it does look like it's mixed , but by backfill's PK split buckets, it seems to be all about consuming the snapshots first, then consuming the streaming data
> 
> 
> 
> At `backfill` executor, yes, it's easy to tell whether a row is from snapshot or from upstream; however, after flowing through some executors, this become tricky. For example, if a `count(*)` aggregation is added by a "new" row (i.e. from upstream) first, then added by a "old" (i.e. from snapshot) row, does the second update belongs to "new" or "old"?
> 
> 
> 
> 
> 
> 

That's my point. The finest grain for telling whether data is from the snapshot or upstream is the epoch.

**Comment by fuyufjh** [comment]
> * Support `CREATE SINK` without backfilling. This is basically sink from latest and it may cause data loss if there are data ingested after `DROP SINK` and before `CREATE SINK`.

I tend to use and guide users to `CREATE (new) SINK` before `DROP (old) SINK`. This can avoid data loss, and also easy to rollback if something is wrong with the new sink.

During this process, when the new sink and old sink coexist, both will write to target and may follow a first-write-win or last-write-win manner. Either looks good to me because either data is valid data. Besides, to avoid panics, the sink connectors must be idempotent, which is aligned to our original design.

**Comment by kwannoel** [comment]
I still don't get the `without backfill` part.

It seems like we can simply pause backfill snapshot read, similar to how we pause source when we receive the barrier.

---

Apart from that, if we want to avoid using backfill, we can just use `chain` executor I suppose. As mentioned by @BugenZhao https://github.com/risingwavelabs/risingwave/issues/13102#issuecomment-1857364077.

**Comment by kwannoel** [comment]
Will we support recovery for `Chain` then? If not when snapshot read partially completes, and we restart, seems like we will flush lots of duplicates downstream again.

**Comment by xxhZs** [comment]
> > * Support `CREATE SINK` without backfilling. This is basically sink from latest and it may cause data loss if there are data ingested after `DROP SINK` and before `CREATE SINK`.
> 
> I tend to use and guide users to `CREATE (new) SINK` before `DROP (old) SINK`. This can avoid data loss, and also easy to rollback if something is wrong with the new sink.
> 
> During this process, when the new sink and old sink coexist, both will write to target and may follow a first-write-win or last-write-win manner. Either looks good to me because either data is valid data. Besides, to avoid panics, the sink connectors must be idempotent, which is aligned to our original design.

alter sink seems to involve a ddl to a downstream external table, which means that there may not be a scenario where both writes occur at the same time.

**Comment by kwannoel** [comment]
Okay thanks to @fuyufjh I understood it. https://github.com/risingwavelabs/risingwave/pull/13947 we just process latest data only, snapshot data is entirely ignored.

**Comment by st1page** [comment]
> alter sink seems to involve a ddl to a downstream external table, which means that there may not be a scenario where both writes occur at the same time.

IIRC, we have support create sink to write only a part of the downstream table's column?

**Comment by fuyufjh** [comment]
> alter sink seems to involve a ddl to a downstream external table, which means that there may not be a scenario where both writes occur at the same time.

I think it's common practice that the target table's schema must change in a compatible manner, such as adding a new column (with default value), so that both old and new writes can execute.

**Comment by hzxa21** [comment]
#13947 introduced CREATE SINK without backfill, which is good enough for common use cases. I will close this issue for now. Feel free to reopen if one thinks that there is a strong need for ALTER SINK without backfill as well.
