### ISSUE TITLE
`show columns` reports error on any tables

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#13111]
### Describe the bug

`SHOW COLUMNS` cannot work. I am quite shocked why our e2e tests still passed.

### Error message/log

```text
unexpected field count in "D" message
```

### To Reproduce

The psql history:

```
dev=> create table if not exists t3 (v1 int, v2 int, v3 int) append only;
NOTICE:  APPEND ONLY TABLE is currently an experimental feature.
CREATE_TABLE
dev=> show columns from t3;
unexpected field count in "D" message
```

`./risedev slt -d dev -p 4566 -u root e2e_test/ddl/show.slt` somehow returns ok for the test.
```
[cargo-make] INFO - Execute Command: "sqllogictest" "-d" "dev" "-p" "4566" "-u" "root" "e2e_test/ddl/show.slt"
e2e_test/ddl/show.slt                                        .. [OK] in 4139 ms
```

### The version of RisingWave

 PostgreSQL 9.5-RisingWave-1.3.0-alpha (unknown)
31d6dc01b543631ed13888760d1fc8ee365d649a

**Comment by yezizp2012** [comment]
@neverchanje I will fix it.

**Comment by yezizp2012** [comment]
> I am quite shocked why our e2e tests still passed.

That's because `sqllogictest` only checks the return rows against to the row desc in the response.
