### ISSUE TITLE
feat: introduce several sql functions as sql interface for risectl

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#13142]
### Is your feature request related to a problem? Please describe.

Currently, when we are investigating and resolving some user issues, we often rely on `risectl` to execute certain commands, such as `pause`, `resume`, `scale`, `unregister_worker`, etc. However, `risectl` is only introduced as a debug tool for us and has poor usability for users. After supporting capturing context in expression, we can introduce some SQL functions to replace them.
1. `pause(force(optional))`: issues a `pause` command on meta, if force enabled, it will trigger recovery and force issue a pause command on meta, it's useful when barrier latency is too high. This is equivalent to `pause_on_next_bootstrap`, but does not require a meta restart. https://github.com/risingwavelabs/risingwave/pull/16259
2. `resume()`:  issues a `resume` command on meta.
3. `unregister_worker(addr/worker_id)`: unregister a CN with target addr or id.
4. `reschedule_jobs(mode, exclude-workers, include-workers, ...)`: mode:(horizon/vertical), refer to `risectl` for other parameters. Note that, this could be deprecated when we fully complete auto-scaling.

For these functions, we should add privilege check. These commands should only be allowed to be executed by users with super privileges.

**Comment by BugenZhao** [comment]
The name of `run_command_on_meta` sounds too general to me, since the only possible "command" to run is `pause` and `resume`. What about simply introducing `pause` and `resume`  separately (or even make them expressions in Postgres style)?

**Comment by yezizp2012** [comment]
> The name of `run_command_on_meta` sounds too general to me, since the only possible "command" to run is `pause` and `resume`. What about simply introducing `pause` and `resume` separately (or even make them expressions in Postgres style)?

👍 LGTM, I used to think the same way before. The reason for using "run_command_on_meta" is to add optional force parameters as suggested by @shanicky .
