### ISSUE TITLE
optimizer: introduce 2 new operators for scanning sys table / CDC table 

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#13146]
Recommend to introduce a new physical operator `CdcTableScan`, because scanning from RW table, sys table or CDC table are completely different in terms of implementation.

Here the `if self.predicate().always_true()` actaully implies a huge difference in implementation, which should be reflected by different phyiscal operators, instead of such `if-else` branch. 

I guess this might be introduced by `sys table` before, so it's acceptable for me too keep it as is now and do refactor later.

_Originally posted by @fuyufjh in https://github.com/risingwavelabs/risingwave/pull/12535#discussion_r1364865050_

**Comment by kwannoel** [comment]
+1. Arrangement backfill now requires full `TableCatalog`, not just the `TableDesc`. This creates yet another branch between RW Table, Sys Table.

I think we should refactor it before adding full `TableCatalog` for arrangement backfill to avoid making it even more complicated.

**Comment by kwannoel** [comment]
Additionally, they should have their own respective proto definitions as well, rather than rely on the same `Chain` definition.

**Comment by kwannoel** [comment]
- [ ] Unify some common functionality between different scan nodes: https://github.com/risingwavelabs/risingwave/pull/13332#issuecomment-1805191654

**Comment by st1page** [comment]
>  Separate logical scan for cdc table.
 
I guess it is not needed for the logical scan, actually, I do not think there are many branches in the logical phase currently. I  think just separate the physical operator is enough

**Comment by kwannoel** [comment]
From https://github.com/risingwavelabs/risingwave/issues/13146#issuecomment-1805229754

> Unify some common functionality between different scan nodes:

It does not seem there's much in common, both between `stream_table_scan` and `stream_cdc_scan`, and also their core parts (`generic::TableScan`, `generic::CdcScan`).
