### ISSUE TITLE
Make the data dispatch more elegant of tables that sharing a CDC source

### ISSUE THREAD

**Issue by StrikeW** [risingwavelabs/risingwave#13147]
https://github.com/risingwavelabs/risingwave/pull/12535#discussion_r1375782490

> To be honest, I don't see any need to hack the `Hash` dispatcher. 😕 It's just like a normal MV on MV, except that there's an extra `Filter` executor before the `Backfill`.
> 
> ![image](https://user-images.githubusercontent.com/25862682/278972300-8b1be114-e204-4ccf-a96d-c48e348e6caa.png)
> 
> > but I found it is difficult to manually construct filter expression like `payload->>'source'->>'table'='table1'` in the optimizer
> 
> I can understand, but it's at least self-contained and much easier to maintain compared to a new dispatcher type. For example, there'll be no changes required on the meta's scheduler part. So if possible, I would still suggest this approach.

**Comment by StrikeW** [comment]
I update the dispatcher from `Filter` to `Backfill` to `Simple`. Because the cdc backfill should be singleton right now, and we should allow `Backfill` to be scheduled to a different CN. What do you think? @BugenZhao 

![image](https://github.com/risingwavelabs/risingwave/assets/7338536/aaccd206-7473-43a3-9a6f-6477f8854de9)

**Comment by BugenZhao** [comment]
> Because the cdc backfill should be singleton right now

Looks good to me!
