### ISSUE TITLE
Reimplement delta lake sink with rust sdk

### ISSUE THREAD

**Issue by wenym1** [risingwavelabs/risingwave#13152]
### Is your feature request related to a problem? Please describe.

Delta lake has its own rust sdk. https://github.com/delta-io/delta-rs

The current java implementation will introduce the `hadoop-aws` dependency, which is about 200M and occupies most of the jar files (https://github.com/risingwavelabs/risingwave/issues/13113). Currently we have the java iceberg sink and delta lake sink depending on `hadoop-aws` for writing data files to S3. Java iceberg sink can be deprecated since we have already implemented a rust one. If we reimplement the delta lake sink rust rust, we can get rid of the `hadoop-aws` dependency.

**Comment by hzxa21** [comment]
Assign to @xxhZs first. Feel free to re-assign.
