### ISSUE TITLE
Support (ignore) `collate "c"` 

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#13171]
### Is your feature request related to a problem? Please describe.

This syntax is used in Dreamio - Postgres connector. 

Basically, `encode "UTF-8" collate "c"` means comparing string by their UTF-8 encoded bytes, without any collation.

> When lc_collate is "C" (or "POSIX"), the comparison is done internally by PostgreSQL. In that case, it compares the byte representations of the strings using memcmp.

This is the same as Rust string's comparison, which is also the behavior of RisingWave. So we can safely ignore it.

> Strings are compared [lexicographically](https://doc.rust-lang.org/std/cmp/trait.Ord.html#lexicographical-comparison) by their byte values.

References:

- https://dba.stackexchange.com/questions/240930/postgresql-difference-between-collations-c-and-c-utf-8
- https://doc.rust-lang.org/std/primitive.str.html

### Describe the solution you'd like

Support it in parser but ignore the `collate "c"` in binder. For other `collate`, may throw an error.

We may limit the scope to `collate "c"` in `select` queries only, ignore the `create table` with collate.

### Describe alternatives you've considered

No idea.

**Comment by BugenZhao** [comment]
Related: https://github.com/risingwavelabs/risingwave/issues/13135#issuecomment-1784754229
