### ISSUE TITLE
feat: support array containment `@>`, `<@`

### ISSUE THREAD

**Issue by thexiay** [risingwavelabs/risingwave#13180]
### Is your feature request related to a problem? Please describe.

This is a subfunction of #7117 

This is appropriate as my good first issue

**Comment by thexiay** [comment]
Infact pgsql has type range but risingwave does not have , but this operator  usage like this:
![image](https://github.com/risingwavelabs/risingwave/assets/37214832/17026b07-c21e-4480-9b62-1387a00c2243)
Is there necessary to add `array contains element `? I try it in pgsql and it;s not ok:
![image](https://github.com/risingwavelabs/risingwave/assets/37214832/bafa4aa5-4323-4f7e-95f1-36a08c8d396e)
Or Just Keep the behavior consistent with pgsql？
cc @

**Comment by wangrunji0408** [comment]
Hi. We'll keep consistent with pg and we are going to add `array @> array` soon. This should be able to support array containment. There will be no `array contains element` operation for this.

**Comment by thexiay** [comment]
> Hi. We'll keep consistent with pg and we are going to add `array @> array` soon. This should be able to support array containment. There will be no `array contains element` operation for this.

I have done this and I will push a mr soon

**Comment by stdrc** [comment]
Closed by https://github.com/risingwavelabs/risingwave/pull/13253
