### ISSUE TITLE
Introduce Nexmark benchmark

### ISSUE THREAD

**Issue by KeXiangWang** [risingwavelabs/risingwave#132]
[Nexmark](https://web.archive.org/web/20100620010601/http://datalab.cs.pdx.edu/niagaraST/NEXMark/) is a good choice to enrich our test and benchmark. Its source generator for Flink in Java is in https://github.com/nexmark/nexmark.

The SQL sentences can be found [here](https://github.com/nexmark/nexmark/tree/master/nexmark-flink/src/main/resources/queries). q1 ~ q8 are from original [NEXMark queries](https://web.archive.org/web/20100620010601/http://datalab.cs.pdx.edu/niagaraST/NEXMark/), q0 and q9 ~ q13 are from [Apache Beam](https://beam.apache.org/documentation/sdks/java/testing/nexmark), others are extended to cover more scenarios.

An example of Rust source for Nexmark is in [Flock](https://github.com/flock-lab/flock), although it only supports q0-q13.

To support Nexmark, we need to finish three parts:

Part one: 

- [x] #2291
- [x]  Nexmark data source for q14-q22.

Part Two:

- [x] #2319
- [x] #2756
- [ ]  Nexmark q6.
- [x]  Nexmark q7.
- [x]  Nexmark q8.
- [x]  Nexmark q9.
- [x]  Nexmark q10.
- [ ]  Nexmark q11.
- [ ]  Nexmark q12.
- [ ]  Nexmark q13.

Part Three:

- [x]  Nexmark q14.
- [x]  Nexmark q15.
- [x]  Nexmark q16.
- [x]  Nexmark q17.
- [x]  Nexmark q18.
- [ ]  Nexmark q19.
- [x]  Nexmark q20.
- [x]  Nexmark q21.
- [x]  Nexmark q22.

**Comment by fuyufjh** [comment]
The work has been stopped for a few months. Shall we continue? @TennyZhuang @KeXiangWang

**Comment by fuyufjh** [comment]
@TennyZhuang @KeXiangWang How about the state of Q21 and Q22?

**Comment by KeXiangWang** [comment]
> @TennyZhuang @KeXiangWang How about the state of Q21 and Q22?

Q21 has finished in 
https://github.com/risingwavelabs/risingwave/pull/4940

Will submit a PR for Q22 today.

**Comment by fuyufjh** [comment]
Since the remaining queries (see https://github.com/risingwavelabs/risingwave/issues/132#issuecomment-1223863082) need further features to support, I'll unpin this issue for now.

**Comment by xxchan** [comment]
Group TopN: Q9 Q18 done, Q19 won't do it now
