### ISSUE TITLE
Failed to create kafka upsert table in v1.3 but succeed in v1.2

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#13225]
### Describe the bug

See Slack messages https://risingwave-labs.slack.com/archives/C0606NNR74P/p1698943472668989

### Error message/log

```text
internal error: Meta data fetch error: BadMessage (Local: Bad message format)
```

**Comment by tabVersion** [comment]
cc @wcy-fdu, close as not reproduced

**Comment by tabVersion** [comment]
and duplicate with #13245
