### ISSUE TITLE
bug: Kafka connector reports error when creating two sources to the same broker.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#13245]
### Describe the bug

When user creates two sources to the same kafka instance, it reports error:
ERROR:  QueryError: internal error: Meta data fetch error: BadMessage (Local: Bad message format)

### How did you deploy RisingWave?

Local playground

### The version of RisingWave

1.3.0

### Additional context

It works in 1.2.0, only failed in 1.3.0

**Comment by liurenjie1024** [comment]
For more details, please ping @liurenjie1024 in private.

**Comment by wcy-fdu** [comment]
Neither @tabVersion  nor I could reproduce this problem later, so this shouldn't be a bug in RisingWave playground, but some issue from kafka side. What a coincidence😅
