### ISSUE TITLE
bug: JDBC connector error may lead to recovery of risingwave.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#13244]
### Describe the bug

According to report from user, when jdbc connector has been killed(maybe due to inactivity), risingwave may recover. 

### Expected behavior

Risingwave should handle connection error and retry.

**Comment by StrikeW** [comment]
Will support connection pool to keep the connection alive https://github.com/risingwavelabs/risingwave/issues/13170. btw decouple JDBC sink with log store is also on going.

**Comment by StrikeW** [comment]
We agree to recreate a new connection when the connection is broken instead employ a connection pool.
