### ISSUE TITLE
Discussion: naming convention of session variables

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#13265]
off-topic: We should really review the naming of these variables. 😕
- Some are prefixed with `RW` while others are not.
- Some are prefixed with `STREAMING` (or `BATCH`) while others are not.

For example, why `SINK_DECOUPLE` but not `RW_STREAMING_SINK_DECOUPLE`?

_Originally posted by @BugenZhao in https://github.com/risingwavelabs/risingwave/pull/13262#discussion_r1382895382_

**Comment by TennyZhuang** [comment]
We need to unify them, but before that, we have to introduce session variable alias to keep backward compatibility.

**Comment by fuyufjh** [comment]
Sounds good to me. Can you take a look? @yuhao-su

**Comment by yuhao-su** [comment]
Do we have any conclusion about what is the name convention?

**Comment by fuyufjh** [comment]
>  Do we have any conclusion about what is the name convention?

Indeed. Not yet, I guess.

Personally, I prefer the ones without `RW_` prefix, because most session variables are specific to RW, and we don't plan to port many session variables from PG.

As for `STREAMING`/`BATCH`, I think it's optional and depends on the specific variables.

**Comment by xxchan** [comment]
Maybe we should prioritize. I feel very confused and don't know which one to choose when I want to add a new config in https://github.com/risingwavelabs/risingwave/pull/18749 🤣
