### ISSUE TITLE
fix(stream): ensure correct executor schema

### ISSUE THREAD

**Issue by stdrc** [risingwavelabs/risingwave#13292]
Although we already inferred output schema in each plan node in optimizer, and passed schemas to backend through protobuf, some of our streaming executors still infer schemas again with their own logic. This is likely to reduce maintainability and introduce bug. We should add some assertion and try to directly use the schemas passed in through pb to ensure correctness.

Tracking:

- [x] `HashAgg`, `SimpleAgg`, `StatelessSimpleAgg` https://github.com/risingwavelabs/risingwave/pull/13289
- [x] `Project`, `ProjectSet` https://github.com/risingwavelabs/risingwave/pull/13342
- [x] `CdcBackfillExecutor`, `ChainExecutor`, `BackfillExecutor`, `RearrangedChainExecutor` https://github.com/risingwavelabs/risingwave/pull/13347
- [x] Source, `Dml`, `RowIdGen` https://github.com/risingwavelabs/risingwave/pull/13380
- [x] `GroupTopN`, `TopN`, `OverWindow`, `EowcOverWindow` https://github.com/risingwavelabs/risingwave/pull/13383
- [x] `Lookup`, `DynamicFilter`, `HashJoin` https://github.com/risingwavelabs/risingwave/pull/13389
- [x] Other misc executors https://github.com/risingwavelabs/risingwave/pull/13435
- [ ] Assertion https://github.com/risingwavelabs/risingwave/pull/13288

**Comment by xiangjinwu** [comment]
seems related: #2063
