### ISSUE TITLE
Support convert_from(b: bytea, src_encoding: text) -> text

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#13306]
### Is your feature request related to a problem? Please describe.

The motivation is to convert a hex bytea to an ASCII-encoded text.

This feature can be considered as a nice-to-have because we can workaround using encode('escape') in most cases

### Describe the solution you'd like

Postgres's doc:
https://www.postgresql.org/docs/9.1/functions-string.html

`convert_from(string bytea, src_encoding name) -> text` 
Convert string to the database encoding. The original encoding is specified by src_encoding. The string must be valid in this encoding.

Example:
```
postgres=# select convert_from('\x4346464558'::bytea, 'utf8');
 convert_from
--------------
 CFFEX
(1 row)
```

**Comment by xiangjinwu** [comment]
If not intentionally being PG 9 compatible, the latest doc is here:
https://www.postgresql.org/docs/16/functions-binarystring.html#FUNCTIONS-BINARYSTRING-CONVERSIONS

Which of the encodings do we intend to support?
https://www.postgresql.org/docs/16/multibyte.html#MULTIBYTE-CONVERSIONS-SUPPORTED
