### ISSUE TITLE
bug: Pulsar source failed when parsing avro message.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#13318]

**Comment by xiangjinwu** [comment]
FYI #12871 unless using confluent schema registry, which is unlikely the case for pulsar, because pulsar has its own schema registry.

**Comment by liurenjie1024** [comment]
Duplicated #12871

**Comment by xiangjinwu** [comment]
> > FYI #12871 unless using confluent schema registry, which is unlikely the case for pulsar, because pulsar has its own schema registry.
> 
> Yes, according to our debug with pulsar team, this is caused by wrong api usage.

Which usage do we intend to support then? (1) No header; (2) Single-object encoding header; (3) pulsar schema registry?

**Comment by liurenjie1024** [comment]
> > > FYI #12871 unless using confluent schema registry, which is unlikely the case for pulsar, because pulsar has its own schema registry.
> > 
> > 
> > Yes, according to our debug with pulsar team, this is caused by wrong api usage.
> 
> Which usage do we intend to support then? (1) No header; (2) Single-object encoding header; (3) pulsar schema registry?

If no schema registry, we should use single-object encoding.
I've not tested what's the behavior of pulsar java api when there is schema registry, we should test it first.
