### ISSUE TITLE
Kafka-cdc-sink bytea type dosen't work with JDBC connector

### ISSUE THREAD

**Issue by xuefengze** [risingwavelabs/risingwave#13327]
### Describe the bug

Create table with `bytea` type will cause this pipeline test fail, crate table with other types will success.
`Risingwave -(Debezium Json)-> Kafka -(Debezium Json)-> JDBC connector -> Postgresql`.

### Error message/log

```text
select * from types
relation “types” does not exist
```

### To Reproduce

integration_tests/kafka-cdc-sink

```SQL
-- risingwave.sql
CREATE TABLE kafka_types(
id int,
c_bytea bytea,
);
CREATE SINK IF NOT EXISTS types_sink
FROM kafka_types
WITH (
connector = 'kafka',
properties.bootstrap.server='message_queue:29092',
topic = 'types',
primary_key = 'id'
) FORMAT DEBEZIUM ENCODE JSON;

INSERT INTO kafka_types VALUES (1, '\x00');
```
```
# Makefile.toml
[tasks.setup-kafka]
script = """
docker compose exec message_queue \
    /usr/bin/rpk topic create -p 1 types
"""
[tasks.check-com-pg]
script = '''
docker exec postgres bash -c 'psql -U $POSTGRES_USER $POSTGRES_DB -c "select * from types"'
'''
```
```
// jsons/pg-sink.json
        "topics": "counts, types",
```
```
cargo make setup
cargo make check-com-pg
```

**Comment by lmatz** [comment]
Just checked kafka-connect-jdbc repo, found:
https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java#L330-L331
and
https://github.com/confluentinc/kafka-connect-jdbc/issues/404

Is it because RW needs to sink data of the `bytes` type to kafka first?

**Comment by xiangjinwu** [comment]
Does `INSERT INTO kafka_types VALUES (1, '\x000000');` work? (instead of `'\x00'`)

**Comment by xiangjinwu** [comment]
From debezium postgresql [tutorial](https://github.com/debezium/debezium-examples/tree/1.x/tutorial#using-postgres):
```
{"id":1,"c_bytea":"AA=="}
```
From our `FORMAT DEBEZIUM ENCODE JSON` sink:
```
{"c_bytea":"AA","id":1}
```
My guess is that we are missing the base64 padding by using `STANDARD_NO_PAD`:
https://github.com/risingwavelabs/risingwave/blob/e0ff37f3b2b50ee585715a3719dcb78924f01bd2/src/connector/src/sink/encoder/json.rs#L246

**Comment by xuefengze** [comment]
> Does `INSERT INTO kafka_types VALUES (1, '\x000000');` work? (instead of `'\x00'`)

It worked.

**Comment by xiangjinwu** [comment]
> > Does `INSERT INTO kafka_types VALUES (1, '\x000000');` work? (instead of `'\x00'`)
> 
> It worked.

Thank you. This confirms it is a padding issue.
