### ISSUE TITLE
Compute Node OOM in longevity test with 20000 throughput

### ISSUE THREAD

**Issue by wcy-fdu** [risingwavelabs/risingwave#13326]
### Describe the bug

CN oom in longevity test with 2w throughput. We originally thought it was caused by the mem table of the materialized operator being too large, but now it turns out that it is caused by the memory consumed by rdkfaka being too high.

Currently the memory of  materialized executor is no longer very high. We need to further solve the problem of rdkafka.
heapfile
[2w-oom-cn1-0918.collapsed.zip](https://github.com/risingwavelabs/risingwave/files/13315117/2w-oom-cn1-0918.collapsed.zip)

Related to #11977 #13060

**Comment by fuyufjh** [comment]
Previously, I tried to fix this by adjusting the parameters of fetch queue of rdkafka, but didn't work.

https://github.com/risingwavelabs/kube-bench/compare/main...eric/limit_rdkakfa_fetch_queue_size

If anyone is interested, my continue to work on this

also related #10888

**Comment by wcy-fdu** [comment]
Update: the occasional oom under 1w throughput is also caused by this(rdfaka).
[1w-oom-1109-1034.heap.collapsed.zip](https://github.com/risingwavelabs/risingwave/files/13315105/1w-oom-1109-1034.heap.collapsed.zip)

**Comment by wcy-fdu** [comment]
Can we close this issue? cc @fuyufjh
