### ISSUE TITLE
sha family hash function errors when meetting '\'

### ISSUE THREAD

**Issue by NiuBlibing** [risingwavelabs/risingwave#13334]
### Describe the bug

When using sha family hash with input containing '\', it will failed.

### Error message/log

```text
ERROR:  QueryError: Expr error: Parse error: invalid input syntax for type bytea
```

### To Reproduce

``` sql
-- sha family hash failed
select sha1('\');
select sha224('\');
select sha256('\');
select sha384('\');
select sha512('\');

-- MD5 success
select md5('\');
 ```

### Expected behavior

I expect sha family functions work well with '\'.
Or support `convert_to` so we can convert the varchat to utf8 bytes.

### How did you deploy RisingWave?

via docker risingwave playground: `./bin/risingwave playground`

### The version of RisingWave

PostgreSQL 9.5-RisingWave-1.3.0 (unknown)
risingwavelabs/risingwave             latest    11a43456396f   2 weeks ago   4.81GB

**Comment by fuyufjh** [comment]
Thanks for reporting this. Let me take a look.

**Comment by fuyufjh** [comment]
The behavior is consistent with PostgresQL:

```
test=# select sha384('\');
ERROR:  invalid input syntax for type bytea
LINE 1: select sha384('\');
                      ^
test=# select md5('\');
               md5                
----------------------------------
 28d397e87306b8631f3ed80d858d35f0
(1 row)
```

This is because `sha` functions accept a `bytea`, so you need to cast a string to bytea:

```
sha256 ( bytea ) → bytea
```

https://pgpedia.info/s/sha256.html 

example:
```
postgres=# SELECT sha256('foo'::bytea);
                               sha256                               
--------------------------------------------------------------------
 \x2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae

```

**Comment by NiuBlibing** [comment]
But convert `'select '\'::bytea;` will failed also.

**Comment by xiangjinwu** [comment]
> But convert `'select '\'::bytea;` will failed also.

There are two ways to input a [bytea](https://www.postgresql.org/docs/current/datatype-binary.html) value of a single byte 0x5c (`\`):
```
test=# select '\\'::bytea;
 bytea 
-------
 \x5c
(1 row)

test=# select '\x5c'::bytea;
 bytea 
-------
 \x5c
(1 row)

test=# select '\\'::bytea = '\x5c'::bytea;
 ?column? 
----------
 t
(1 row)
```

**Comment by NiuBlibing** [comment]
Is there a way to convert it in table so that I can use sha family hash?
```sql
-- create table
create table test (
    test varchar
);

-- insert data
insert into test values ('\=');

-- this will failed
-- ERROR:  QueryError: Internal(Expr error: Parse error: invalid input syntax for type bytea)
select test::bytea from test;
select sha512(test::bytea) from test;
```

**Comment by xiangjinwu** [comment]
`replace(test, '\', '\\')::bytea`

**Comment by NiuBlibing** [comment]
Thanks, it worked for me.
