### ISSUE TITLE
allow &[u8] as range bound in state store interface

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#1334]
LGTM! Would you please create a new issue to track "allow &[u8] as range bound in state store interface"?

_Originally posted by @skyzh in https://github.com/singularity-data/risingwave/pull/1266#pullrequestreview-922794247_

The current implementation requires `B: AsRef<[u8]>` to be a value but not a reference to bypass the lifetime error.

Related: #1132

**Comment by skyzh** [comment]
will be resolved by https://github.com/risingwavelabs/risingwave/pull/5980, we only allow `Vec<u8>` now.
