### ISSUE TITLE
MySQL cdc table sql in rw_tables syntax error

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#13354]
### Describe the bug

The sql in rw_tables cannot create table successfully due to syntax error. The following should be `FROM sbtest TABLE 'mydb.sbtest10'`

```
dev=> select definition from rw_tables limit 1;
                                                          definition
-------------------------------------------------------------------------------------------------------------------------------
 CREATE TABLE sbtest10 (id INT PRIMARY KEY, k INT, c CHARACTER VARYING, pad CHARACTER VARYING) FROM sbtest TABLE mydb.sbtest10
(1 row)

dev=>  CREATE TABLE sbtest10 (id INT PRIMARY KEY, k INT, c CHARACTER VARYING, pad CHARACTER VARYING) FROM sbtest TABLE mydb.sbtest10;
ERROR:  QueryError: sql parser error: Expected end of statement, found: . at line:1, column:118
Near "VARYING) FROM sbtest TABLE mydb"
```

### The version of RisingWave

nightly-20231108

**Comment by StrikeW** [comment]
Why the single quote (`FROM sbtest TABLE 'mydb.sbtest10'`) is eliminated? 👀  @yezizp2012

**Comment by yezizp2012** [comment]
> Why the single quote (`FROM sbtest TABLE 'mydb.sbtest10'`) is eliminated? 👀 @yezizp2012

I believe it was eliminated by the parser, let me take a look.

**Comment by xiangjinwu** [comment]
Quote should be included in `Display`:
https://github.com/risingwavelabs/risingwave/blob/1abe9e82eb17d61aa9279a5cb8275af90083f504/src/sqlparser/src/ast/mod.rs#L1574-L1577

Add a test here and you can see whether quotes are preserved or not in `formatted_sql`
https://github.com/risingwavelabs/risingwave/tree/main/src/sqlparser/tests/testdata

**Comment by StrikeW** [comment]
Oh, that is my bad. 🥵
