### ISSUE TITLE
bug: `schema.registry.username` and `schema.registry.password` are not correctly consumed

### ISSUE THREAD

**Issue by tabVersion** [risingwavelabs/risingwave#13365]
### Describe the bug

described in https://github.com/risingwavelabs/risingwave/pull/13362

**Comment by BugenZhao** [comment]
Duplicated with #13367?

**Comment by tabVersion** [comment]
> Duplicated with #13367?

partly, I'd like to keep this on as a tracking issue.
#13367 describes a bug found in the fix process that we misuse the connector props and encode props.
