### ISSUE TITLE
Bug: Too many CN WARN logs causing node disk exhaustion

### ISSUE THREAD

**Issue by huangjw806** [risingwavelabs/risingwave#13378]
#### Describe the bug
In the pipeline of nightly performance and longevity tests, the cn node was evicted due to disk exhaustion.

pipeline：
- nexmark： https://buildkite.com/risingwave-test/nexmark-benchmark/builds/2440
- longevity：https://buildkite.com/risingwave-test/longevity-test/builds/786

<img width="1794" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/29391315/f4b60e4c-47ba-4cf5-b469-7c8ed305d98d">

#### Bug analysis

Running the performance or longevity test CN on the image of **`nightly-20231112`** will continuously output this log.

log link: https://grafana.test.risingwave-cloud.xyz/d/liz0yRCZz1/log-search-dashboard?orgId=1&var-data_source=PE59595AED52CF917&var-namespace=nexmark-bs-15-105-daily-20231112&var-pod=benchmark-risingwave-compute-c-0&var-search=&from=1699805772919&to=1699816749582

<img width="1913" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/29391315/7c32aa59-20fd-4013-b584-bc5fa02204a6">
<img width="1892" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/29391315/5a527c2b-ae5d-4c27-a20a-d4d53a2436e9">

#### Additional context

Although this is a kernel bug, it seems that cloud's log retention is also unreasonable. Do we need to increase the retention mechanism of log file size? 
cc @arkbriar @Nebulazhang

**Comment by huangjw806** [comment]
It seems to be caused by [this issue](https://github.com/risingwavelabs/risingwave/pull/13278), please take a look. cc @keven-huang @st1page

**Comment by keven-huang** [comment]
This is a bug which will caused by format plain encode Json and encode Csv. In the feature we add a default column `_rw_key` to `Format::Plain` and add `PlainParser` to parse column.
But in `Encode Json` and `Encode Csv`, it will run different parser.
https://github.com/risingwavelabs/risingwave/blob/9f78e712c9022044bc846fa7d5f2df67b846bc17/src/connector/src/parser/mod.rs#L731
