### ISSUE TITLE
bug: Database/Schema update does not modify [database | schema]_by_name in catalog.

### ISSUE THREAD

**Issue by Rossil2012** [risingwavelabs/risingwave#13374]
### Describe the bug

In `SchemaCatalog`:
```rust
pub fn update_self(&mut self, prost: &PbSchema) {
    self.id = prost.id;
    self.database_id = prost.database_id;
    self.name = prost.name.clone();
    self.owner = prost.owner;
}
```
In `DatabaseCatalog`:
```rust
pub fn update_self(&mut self, prost: &PbDatabase) {
    self.id = prost.id;
    self.name = prost.name.clone();
    self.owner = prost.owner;
}
```
Need to check if the name is modified and update catalog correspondingly. Meanwhile, as [schama | database]_by_name is owned by [Database | Root]Catalog, the functions need to be moved into higher level of catalog.

**Comment by Rossil2012** [comment]
cc @yezizp2012.

**Comment by yezizp2012** [comment]
Good catch, please help to fix it.
