### ISSUE TITLE
Bug: fail to use force_append_only for new sink syntax

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#13388]
### Describe the bug

```sql
create table t (id int);

insert into t select i from generate_series(1, 100) i;

CREATE SINK sink_t FROM t
WITH (
   connector='kafka',
   properties.bootstrap.server='127.0.0.1:29092',
   topic='my_topic2',
   force_append_only='true',
)
FORMAT PLAIN ENCODE JSON;


```

```
ERROR:  QueryError

Caused by these errors (recent errors listed first):
  1: Sink error
  2: The sink cannot be append-only. Please add "force_append_only='true'" in options to force the sink to be append-only. Notice that this will cause the sink executor to drop any UPDATE or DELETE message.

```

**Comment by xiangjinwu** [comment]
The `force_append_only` option is part of `format plain`, so written after it:
```
FORMAT PLAIN ENCODE JSON (force_append_only='true');
```

I have expected such confusion because there are now 2 places to write options: https://github.com/risingwavelabs/risingwave-docs/pull/1371#issuecomment-1758919812

* Do you have any suggestion on the [doc site](https://docs.risingwave.com/docs/current/create-sink-kafka/) to make it clearer?
* Maybe I should use different error messages for old syntax and new syntax.
* The e2e tests will also be updated as examples of new syntax #13066

**Comment by chenzl25** [comment]
This one looks confusing. `FORMAT PLAIN ENCODE JSON (force_append_only='true');` 😢 I think most users don't know the exact syntax of `CREATE SINK`, so they would follow the doc, however, our doc seems still telling users to put `force_append_only` to the `WITH` place. **I think we can support both of these two syntaxes if possible.** BTW, the docs and the error message should be updated timely.

**Comment by xiangjinwu** [comment]
> however, our doc seems still telling users to put `force_append_only` to the `WITH` place.

Do you mean the doc today, or the doc on the v1.3 release day? If it is still unclear today, could you open a doc issue?

> **I think we can support both of these two syntaxes if possible.**

That goes against the separation of 2 sets of options https://github.com/risingwavelabs/rfcs/pull/64
> Furthermore, placing all properties within the 'with clause' is not an elegant solution, despite this being Flink's approach. In a stream system, there are numerous configuration items, and it is necessary to fill in the configurations based on the configured entities to reduce the cognitive burden on the users.

Personally I agree the separation actually increased the cognitive burden in this case. But I prefer to keep it consistent first. Having a better error message should be helpful enough here, and I will keep this issue open until the error message is updated.

**Comment by chenzl25** [comment]
![Uploading image.png…]()

**Comment by xiangjinwu** [comment]
> @xiangjinwu We should update the docs for v1.4 and onwards. Right? v1.3 should stay as they are.

I have opened https://github.com/risingwavelabs/risingwave-docs/pull/1516 and v1.3 should also be included.
