### ISSUE TITLE
connector: allow customization on the prefix of `group.id` for Kafka readers

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#13386]
Currently we hardcode it to be `consumer-`. Users may want to customize it to be `consumer_` or something else.

https://github.com/risingwavelabs/risingwave/blob/e723f6a66ea9b02b79efed40306bb6317006c1ae/src/connector/src/source/kafka/source/reader.rs#L79-L90

Note that specifying the whole group id is not expected as described in https://github.com/risingwavelabs/risingwave/pull/13223#issuecomment-1791798953. So maybe we should remove `consumer_group` from properties to avoid confusion.

cc @shanicky @tabVersion

**Comment by tabVersion** [comment]
> So maybe we should remove consumer_group from properties to avoid confusion.

We've removed the `group.id` from the dev doc to avoid unexpected behavior. 

> Users may want to customize it to be `consumer_` or something else.

I am afraid of bringing up more confusion for normal users that we have to explain how RW uses the low-level API and how splits are distributed to different actors. `group.id` is required by the kafka client but we don't necessarily need it.

**Comment by xxchan** [comment]
#17657
