### ISSUE TITLE
Test backwards compat against latest 4 versions

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#13403]
Currently we test against 4 versions before. i.e. 1.1 vs latest.

I think we should also test versions in-between. There could be bugs there. e.g. 1.3 vs latest.

**Comment by lmatz** [comment]
> I don't think backwards compat test is transitive.

because we cannot cover all the cases in the backwards compact test, or due to other reasons?

**Comment by kwannoel** [comment]
This case should have been covered, by the nexmark tests.

However it is not, because we only cover 1.1 upgrade to 1.4 currently (4 versions before vs latest version).

We should test 1.3 against 1.4 as well.

**Comment by kwannoel** [comment]
Now backwards compat test does this.
