### ISSUE TITLE
Proposal: `#[Catalog]` derive proc macro

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#13433]
I'd like to propose a `[Catalog]` derive proc macro to simplify the implementation of our system catalog.

There are three current pain points:

1. We have to construct the schema manually.
2. We must ensure the returned `OwnedRow` is consistent with the schema.
3. We have to register it manually.

## Type of row

```rust
#[derive(Catalog)]
#[catalog(reader, rw_catalog.rw_schemas)]
pub struct RwSchemasRow {
    id: i32,
    name: String,
    owner: i32,
    acl: String,
}
```

This will generate a static method on it:

```rust
impl RwSchemaRow {
    pub fn columns() -> Vec<SystemCatalogColumnsDef<'static>> { ... }
}
```

## `[catalog]` macro attribute

The `catalog` macro will do three things:

1. Generate a `BuiltinView` or `BuiltinTable` based on given information.
2. Register it to the global `SYS_CATALOGS`.

## Reader

We can implement the reader now with type safety.

```rust
#[derive(Catalog)]
#[catalog(reader, rw_catalog.rw_schemas)]
pub struct RwSchemasRow {
    id: i32,
    name: String,
    owner: i32,
    acl: String,
}

impl RwSchemasRow {
/// A read method is necessary for a Reader.
pub fn read(reader: &SysCatalogReaderImpl) -> Result<Vec<RwSchemasRow>> {
    let catalog = reader.catalog_reader.read_guard();
    let schemas = catalog.iter_schemas(&reader.auth_context.database)?;
    let user_reader = catalog.user_info_reader.read_guard();
    let users = user_reader.get_all_users();
    let username_map = user_reader.get_user_name_map();

    Ok(schemas
        .map(|schema| {
            RwSchemasRow {
                id: schema.id() as i32,
                name: schema.name().into(),
                owner: schema.owner() as i32,
                acl: get_acl_items(&Object::SchemaId(schema.id()), false, &users, username_map).into(),
            }
        })
        .collect_vec())
}

}
```

## View

Only the column types need to be provided in the function signature.

```rust
#[derive(Catalog)]
#[catalog(view, pg_catalog.pg_indexes,
  r#"SELECT s.name AS schemaname, \
        t.name AS tablename, \
        i.name AS indexname, \
        NULL AS tablespace, \
        i.definition AS indexdef \
    FROM rw_catalog.rw_indexes i \
    JOIN rw_catalog.rw_tables t ON i.primary_table_id = t.id \
    JOIN rw_catalog.rw_schemas s ON i.schema_id = s.id"#
)]
pub struct PgIndexesRow {
   // ...
}
```

## Dummy

Similar to View:

```rust
#[derive(Catalog)]
#[catalog(dummy, pg_catalog.pg_aggregate)]
pub struct PgAggregateRow {
   // ...
}
```

**Comment by BugenZhao** [comment]
```rust
#[catalog(reader, rw_catalog.rw_schemas)]
pub fn read_rw_schemas(reader: &SysCatalogReaderImpl) { .. }
```

What about directly attribute on the `Row` struct? So that we don't need dummy functions for views and dummy tables.

----

> Generate a BuiltinView or BuiltinTable based on given information.

Can you elaborate more on what information should be given?

**Comment by liurenjie1024** [comment]
Is it possible to solve this with some orm framework?

**Comment by TennyZhuang** [comment]
> Is it possible to solve this with some orm framework?

Impossible. The framework should be aware of our type system.

**Comment by TennyZhuang** [comment]
> What about directly attribute on the Row struct? So that we don't need dummy functions for views and dummy tables.

Updated
