### ISSUE TITLE
kafka-cdc-sink: Missing `name` field in debezium json

### ISSUE THREAD

**Issue by xuefengze** [risingwavelabs/risingwave#13450]
According to [debezium data type mapping](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-data-types), semantic type(aka. name) describes how the Kafka Connect schema captures the meaning of the field using the name of the Kafka Connect schema for the field.

Example:
In the `Risingwave -(Debezium Json)-> Kafka -(Debezium Json)-> JDBC connector -> PostgreSQL` pipeline of our implementation, the `DATE` type in the message event appears like this:
```json
{
  "field": "c_date",
  "optional": true,
  "type": "int32"
}
```
Well in [Debezium PG connector](https://debezium.io/documentation/reference/stable/connectors/postgresql.html), it appears like this:
```json
{
  "field": "c_date",
  "optional": true,
  "type": "int32",
  "name": "io.debezium.time.Date"
}
```
If we use [debezium jdbc connector](https://debezium.io/documentation/reference/2.4/connectors/jdbc.html), it can automatically  convert `c_date` type to `DATE` by name. Currently, we are only seeing the `c_date` type as an `integer` in PostgreSQL. And we need additional configuration in the JDBC connector to parse `c_date`, so that we can see the `DATE` type in PostgreSQL.

**Comment by fuyufjh** [comment]
I am confused by the issue description? 👀

> Missing `name` field in debezium json

So are you proposing to add the `name` field in the output of kafka debezium sink, right?
