### ISSUE TITLE
Sysbench performance bottleneck analysis

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#13458]
Recently, I investigated the bottleneck of the Sysbench benchmark, because it is the most straightforward way to show our system serving performance. It was found that the frontend node first becomes the bottleneck (its CPU utilization first reaches 100%) and the corresponding flame graph was taken. 

According to the flame graph, `gen_batch_plan_by_statement` takes about 26.4% CPU, however, some optimization rule definitely could be skipped, since most sysbench workloads are point-select and lots of optimization like subquery unseating, inline_now_proc time could be skipped. Meanwhile, one `predicate_pushdown` is enough for this query, but actually, our optimization could apply four `predicate_pushdown` in different stages currently. It is not a big deal in streaming queries, but for serving queries, it is too heavy.

Technically, we could apply a plan cache to avoid optimization for the same query pattern multiple times, but personally, I prefer not to introduce at this moment for the following reasons:
- Plan cache needs us to separate the plan and the parameters which means in optimization, we cannot apply optimization like common sub-expression/plan when the plan contains parameters. 
- Theoretically, different parameters actually should match different plans.
- Plan cache could be missed when the SQL templates become too many.
- Plan cache will hide optimization time which should be improved ASAP.

![flamegraph](https://github.com/risingwavelabs/risingwave/assets/9352536/651f1583-ec6d-43c1-9c4c-1bc684514805)

**Comment by BugenZhao** [comment]
#13459
