### ISSUE TITLE
Sysbench performance bottleneck analysis -- point select

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#13459]
Recently, I investigated the bottleneck of the Sysbench benchmark, because it is the most straightforward way to show our system serving performance. It was found that the **frontend node first becomes the bottleneck** (its CPU utilization first reaches 100%) and the corresponding flame graph was taken. 

According to the flame graph, `gen_batch_plan_by_statement` takes about 26.4% CPU, however, some optimization rule definitely could be skipped, since most sysbench workloads are point-select and lots of optimization like subquery unseating, inline_now_proc time could be skipped. Meanwhile, one `predicate_pushdown` is enough for this query, but actually, our optimization could apply four `predicate_pushdown` in different stages currently. It is not a big deal in streaming queries, but for serving queries, it is too heavy.

Technically, we could apply a plan cache to avoid optimization for the same query pattern multiple times, but personally, I prefer not to introduce at this moment for the following reasons:
- Plan cache needs us to separate the plan and the parameters which means in optimization, we cannot apply optimization like common sub-expression/plan when the plan contains parameters. 
- Theoretically, different parameters actually should match different plans.
- Plan cache could be missed when the SQL templates become too many.
- Plan cache will hide optimization time which should be improved ASAP.

![flamegraph](https://github.com/risingwavelabs/risingwave/assets/9352536/651f1583-ec6d-43c1-9c4c-1bc684514805)

**Comment by st1page** [comment]
Also, I guess there is too many stages in the optimization which might introduce overhead such as `HeuristicOptimizer::new`. Maybe we can merge some rules into the same stages. https://github.com/risingwavelabs/risingwave/blob/3b7036ca19638206d94b986163170462a65a9fb0/src/frontend/src/optimizer/logical_optimization.rs#L626-L630

**Comment by liurenjie1024** [comment]
I think there are two other optimizations:
1. For prepared statement, we can generate plan only once
2. If we identified simple plan after binder, we can exclude many rule

**Comment by xxchan** [comment]
> Also, I guess there is too many stages in the optimization which might introduce overhead 

BTW, do we have any tracing info to see how long each optimization stage takes? 🤔️

**Comment by chenzl25** [comment]
According to the flame graph, plan cloning is relatively costly. Maybe we should check before actually applying some optimizations.

**Comment by fuyufjh** [comment]
Can you upload the flamegraph with `gz`? GitHub will compress the `.svg` file and make it unreadable 🥵

**Comment by chenzl25** [comment]
> Can you upload the flamegraph with `gz`? GitHub will compress the `.svg` file and make it unreadable 🥵

You need to click the edit and then copy the svg URL in a new browser tab. `https://github.com/risingwavelabs/risingwave/assets/9352536/651f1583-ec6d-43c1-9c4c-1bc684514805`

**Comment by chenzl25** [comment]
Update a new flame graph from the frontend (running in our cloud environment) which has applied above PRs optimizations.
![flamegraph](https://github.com/risingwavelabs/risingwave/assets/9352536/5eb5ae93-0c4c-4c73-8210-e3085017c651)

**Comment by chenzl25** [comment]
Let's close this issue because most frontend bottleneck has been removed.
