### ISSUE TITLE
`rdkafka` consumes too much memory during longevity test and OOM

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#13493]
Just leave another data point for visibility if we want to test if the problem is solved later.

The following setting makes it easier to reproduce the problem:
https://buildkite.com/risingwave-test/longevity-test/builds/779#018bb714-096f-442e-905f-3af721bb056a
i.e. repeat the nexmark query 8 times and run them all together concurrently. 25*8=150 with only 1000 rows/s throughput.

Please take a look at the `Environment` tag in Buildkite when trying to reproduce.

![SCR-20231116-ort](https://github.com/risingwavelabs/risingwave/assets/5791930/c83edd31-63d9-433b-8601-9708284663fb)

It is an inherent issue of `rdkafka`.

**Comment by fuyufjh** [comment]
Duplicated #13326 #11977

**Comment by fuyufjh** [comment]
Kept as known issue. Removed from milestone.

**Comment by lmatz** [comment]
will create new issue if happened again, bypass it by using a shared materialized view as the source table for all the MVs
