### ISSUE TITLE
Bug: customer reported cannot create a Table with kafka connector in DEBEZIUM AVRO format

### ISSUE THREAD

**Issue by StrikeW** [risingwavelabs/risingwave#13505]
### Describe the bug

customer reported cannot create a Table with kafka connector in `DEBEZIUM AVRO` format.
```
CREATE TABLE data_item  WITH ( CONNECTOR = 'kafka', TOPIC = 'data_item', PROPERTIES.BOOTSTRAP.SERVER = 'xxx', SCAN.STARTUP.MODE = 'earliest' )  FORMAT DEBEZIUM ENCODE AVRO (schema.registry='xxx');
```

### Error message/log

```text
SQL ERROR: ExecuteError: Protocol error: Avro schema parse error One union type Date must match the `default`'s value type Long
```

### To Reproduce

The schema which is suspected to be causing this problem:
```
{
	"name": "first_insert_dt",
	"type": [
		{
			"type": "int",
			"connect.version": 1,
			"connect.default": 0,
			"connect.name": "org.apache.kafka.connect.data.Date",
			"logicalType": "date"
		},
		"null"
	],
	"default": 0
},

```

### The version of RisingWave

risingwave:nightly-20231102

**Comment by xiangjinwu** [comment]
Yet another upstream (`apache_avro`) bug: #12562 / #13030

It has been fixed in v0.14.0

**Comment by tabVersion** [comment]
> I am working on migration from our fork to the official version. 

we introduce our crate to handle ref type in Avro, without handling cycle dependency. I am not sure the official sdk has fixed that.

**Comment by xiangjinwu** [comment]
> we introduce our crate to handle ref type in Avro, without handling cycle dependency.

Yes. I have a prototype solution for both ref type and decimal, using the official version rather than our fork.
