### ISSUE TITLE
Bug: unable to insert data into an upsert avro table

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#13503]
### Describe the bug

create table:

```sql
CREATE TABLE t () WITH (CONNECTOR = 'kafka', TOPIC = 'xxx', 
PROPERTIES.BOOTSTRAP.SERVER = 'localhost:9092', SCAN.
STARTUP.MODE = 'earliest') FORMAT UPSERT ENCODE AVRO (schema.registry = 'http://localhost:8081');
```

insert:
```sql
INSERT into t values (...);
```

### Error message/log

Compute Node crashes, because hidden column `_rw_key` can not be generated for the insert statement.

**Comment by fuyufjh** [comment]
Note down the conclusion from Slack channel `#wg-new-source-ddl`

The behavior of `CREATE TABLE ... WITH (CONNECTOR = 'kafka') FORMAT ... ENCODE AVRO`

- `FORMAT PLAIN`
  - If no primary key is specified, an automatic row-id is assigned.
If a primary key is specified, it is treated the same as an "on conflict" handling:
    - When creating a table, the current behavior is to overwrite existing rows.
    - When creating an append-only table, the behavior is to ignore subsequent rows.
- `FORMAT UPSERT`
  - The `include key as` clause must be present, and the included columns are used to parse the Kafka message key
