### ISSUE TITLE
OOM for sysbench select random limits (Hummock read duration seems abnormal)

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#13506]
### Describe the bug

https://buildkite.com/risingwave-test/sysbench/builds/554#018be963-e823-4393-aad6-38255d87bcdd/1121
image is `20231119`

https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1700429709000&to=1700430303000&var-namespace=sysbench-daily-test-20231119

Dashboard:
![SCR-20231120-is9](https://github.com/risingwavelabs/risingwave/assets/5791930/6fd12f21-6959-4b10-9935-62a32ab3bcd7)
![SCR-20231120-isi](https://github.com/risingwavelabs/risingwave/assets/5791930/1f3001cc-4006-46fa-a26a-bd909925b82b)

The read duration seems abnormal.

The previous tests are all good, e.g. the latest successful one is image `20231116`
https://buildkite.com/risingwave-test/sysbench/builds/553#018bd9f0-9c26-4472-a129-e0cb237ecf39

Dashboard:
https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1700169909000&orgId=1&to=1700171403000&var-datasource=P2453400D1763B4D9&var-namespace=sysbench-daily-test-20231116&var-instance=benchmark-risingwave&var-pod=All&var-component=All&var-table=All

According to https://github.com/risingwavelabs/rw-commits-history#nightly-20231119, it does not seem to be affected by a PR between `20231116` and `20231119`.

### Additional context

IIUC, we have implemented the mechanism at the executor level to kill a batch query that risks going OOM.
Therefore, OOM is unexpected, although the root cause of OOM is not necessarily this mechanism.

I saw https://github.com/risingwavelabs/risingwave/pull/13132 merged in `20231115`, wonder if it may have some impact?

**Comment by lmatz** [comment]
![SCR-20231120-j8b](https://github.com/risingwavelabs/risingwave/assets/5791930/795f5879-b584-4da3-8120-5699adc3a68e)

![SCR-20231120-jc3](https://github.com/risingwavelabs/risingwave/assets/5791930/239b31ee-e142-422e-be55-59c6f0b53f18)

As the compactor deems itself to have no left work to do, I suppose the LSM tree is in good shape.
If it is in good shape, the read duration should not increase to such extent.

**Comment by lmatz** [comment]
The sysbench workload is a customed one, see: https://github.com/risingwavelabs/sysbench/blob/master/src/lua/select_random_limits.lua#L26-L31

aka select the same with limit 10 repetitively

**Comment by lmatz** [comment]
![SCR-20231121-lvl](https://github.com/risingwavelabs/risingwave/assets/5791930/27d4a8dd-e8cd-4e7f-84be-f33e963e15ef)
483347725eacbe39a9a60b0817ac145aaf205f80 https://github.com/risingwavelabs/risingwave/pull/13444


Since the error is reproducible every time, I suppose we need to find the wrong commit between `1106` and `1109`
`itertool` seems to be the only suspicious one here? and need to test it to verify.

**Comment by lmatz** [comment]
We notice that the latest change in our `sysbench` repo: https://github.com/risingwavelabs/sysbench/commits/master
is two weeks ago, which should not have any effect on 11/19's tests. Otherwise, it should be found out two weeks ago.

**Comment by lmatz** [comment]
![SCR-20231122-kmj](https://github.com/risingwavelabs/risingwave/assets/5791930/a29cb954-ec10-4add-89c4-227706208d14)
![SCR-20231122-kr2](https://github.com/risingwavelabs/risingwave/assets/5791930/b2484b20-1b75-4003-b0f0-2d585719f9e5)


...... somehow the CN in sysbench has always been. configured to 
```
request 15Gi
limit 11Gi
```
cc: @huangjw806  I know it may have been configured by others before, but do you have any idea why it is configured this way?

But still confused as to why it did not fail before 11/16. Also checked that the memory configuration is the same as previously.


Do you have any ideas? @liurenjie1024 @fuyufjh

**Comment by lmatz** [comment]
The sysbench CN memory configuration is as such:
![SCR-20231122-kr2](https://github.com/risingwavelabs/risingwave/assets/5791930/8ab59c80-f537-44af-bb08-fcd0d94e9458)
![SCR-20231122-kvb](https://github.com/risingwavelabs/risingwave/assets/5791930/400a046f-afab-46bd-a129-718b6792a70e)

In principle, CN should not OOM until 15Gi. But it exceeds 11Gi and then OOM. This is weird. cc: @huangjw806 is trying another new configuration to see if this behavior would be gone or not.

But, we remark that this is a separate issue. It does not explain why the memory usage reaches 11Gi.
![SCR-20231122-kur](https://github.com/risingwavelabs/risingwave/assets/5791930/dd52af8a-9cb6-4334-9aef-35afeb5967cd)

Previously, it used only about 6GB at most:
![SCR-20231122-le4](https://github.com/risingwavelabs/risingwave/assets/5791930/626da00e-cb8d-4629-934c-33ec02e6170f)
https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=P2453400D1763B4D9&var-namespace=sysbench-daily-test-20231115&var-instance=benchmark-risingwave&var-pod=All&var-component=All&var-table=All&from=1700080822882&to=1700086015129

**Comment by huangjw806** [comment]
The sysbench 32c64g all pods affinity configuration is as such:
<img width="1130" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/29391315/8771ad22-4720-4331-befb-9f3734b266cf">
<img width="662" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/29391315/43d7f70c-e49e-414c-a472-18be1f0fd591">

CN still OOM! However, we did not see the mem metric exceeding the limit on grafana. I guess it is because the rapid increase of cn mem caused us to not collect useful metrics.

<img width="948" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/29391315/807eeae0-87db-4358-b7e5-4dc6b9086520">

**Comment by liurenjie1024** [comment]
> Lots of memory hold by Hummock iteration
> 
> <img alt="image" width="730" src="https://user-images.githubusercontent.com/10192522/284206795-f247feed-5a44-434b-ae99-dc8915e6516b.png">
> [1700467603-2023-11-20-08-06-42.auto.heap.collapsed.zip](https://github.com/risingwavelabs/risingwave/files/13409769/1700467603-2023-11-20-08-06-42.auto.heap.collapsed.zip)
> 
> Seems leaks somewhere. This is critical and let’s prioritize it.
> 
> Might be related #9732

How am I supposed to see the flamegraph? Is this a svg?

**Comment by fuyufjh** [comment]
> > Lots of memory hold by Hummock iteration
> > <img alt="image" width="730" src="https://user-images.githubusercontent.com/10192522/284206795-f247feed-5a44-434b-ae99-dc8915e6516b.png">
> > [1700467603-2023-11-20-08-06-42.auto.heap.collapsed.zip](https://github.com/risingwavelabs/risingwave/files/13409769/1700467603-2023-11-20-08-06-42.auto.heap.collapsed.zip)
> > Seems leaks somewhere. This is critical and let’s prioritize it.
> > Might be related #9732
> 
> How am I supposed to see the flamegraph? Is this a svg?

Drop the `.collapsed` file into https://www.speedscope.app/ and click the top-left "Left Heavy" button.

**Comment by liurenjie1024** [comment]
I agree with @lmatz This more like an environment change rather code change. Same image failed with different schedules.

**Comment by huangjw806** [comment]
It seems that v1.4.0 does not have this issue.
https://buildkite.com/risingwave-test/sysbench/builds/569

**Comment by lmatz** [comment]
Actually, I think env and kernel are still both likely to have an issue.

> But, we remark that this is a separate issue. It does not explain why the memory usage reaches 11Gi.
> Previously, it used only about 6GB at most:

Since the workload is not changed, this behavior is hard to be explained by env but only the kernel.

However, the `request 15, limit 11` setting is also concerning and needs to be fixed.

**Comment by liurenjie1024** [comment]
One interesting observation of frontend qps for failed `select_random_limit`:
<img width="658" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/2771941/803ebdad-347c-435c-aa33-950947152b2a">
<img width="930" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/2771941/a1321663-bc79-4c63-ba60-3b9051121afe">

The succeeded one's qps is always 200+, while the failed one's qps starts with 800+

**Comment by liurenjie1024** [comment]
The latency of succeeded ones are 150+ms:
<img width="918" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/2771941/9760ae9a-1901-44b4-8a96-7dd92034d18a">

While it speed up to 5ms for failed ones:
<img width="937" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/2771941/f565c894-d345-47a8-b16e-ec0ef2d9cb62">

Any changes in storage to speed up this? cc @hzxa21

**Comment by liurenjie1024** [comment]
I see a lot of errors in failed query:
<img width="1760" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/2771941/42f40d88-40be-4b20-a7ec-7e1bf1cb4317">

I think this is reasonable since this may cause a lot scans while frontend is already failed this query.

**Comment by liurenjie1024** [comment]
Let's wait to see this: https://buildkite.com/risingwave-test/sysbench/builds/572#018bfbef-a682-42d5-bc57-36fad5bce88f

**Comment by chenzl25** [comment]
It seems it is related to this PR https://github.com/risingwavelabs/risingwave/pull/13132 . It uses a streaming read to prefetch.

**Comment by liurenjie1024** [comment]
Let's see if this one without config can succeeded. https://buildkite.com/risingwave-test/sysbench/builds/575

**Comment by liurenjie1024** [comment]
> Let's see if this one without config can succeeded. https://buildkite.com/risingwave-test/sysbench/builds/575

It failed.

**Comment by hzxa21** [comment]
There are still streaming read ops in the last query run.
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/73dc0b49-a05b-494a-ab54-ca48d963be9c)

**Comment by liurenjie1024** [comment]
> There are still streaming read ops in the last query run. ![image](https://user-images.githubusercontent.com/5518566/285345751-73dc0b49-a05b-494a-ab54-ca48d963be9c.png)

Which one?

**Comment by hzxa21** [comment]
> > There are still streaming read ops in the last query run. ![image](https://user-images.githubusercontent.com/5518566/285345751-73dc0b49-a05b-494a-ab54-ca48d963be9c.png)
> 
> Which one?

select_random_limits

There are ~2w connections created: 
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/9fbe694c-5656-4707-9f49-779c78ee7ffa)

**Comment by liurenjie1024** [comment]
https://buildkite.com/risingwave-test/sysbench/builds/576

In this run I've adjusted `large_query_memory_usage_mb` to 1024, let's see if it can succeeded.

**Comment by liurenjie1024** [comment]
> https://buildkite.com/risingwave-test/sysbench/builds/576
> 
> In this run I've adjusted `large_query_memory_usage_mb` to 1024, let's see if it can succeeded.

Succeeded.
