### ISSUE TITLE
Frontend unexpected end of file error all the time

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#13515]
### Describe the bug

When I test with `nightly-20231116` image, I got the following error in the frontend logs all the time

```
ERROR pgwire::pg_server: error when reading message error=unexpected end of file
```

[Log](https://grafana.test.risingwave-cloud.xyz/d/liz0yRCZz1/log-search-dashboard?orgId=1&var-data_source=PE59595AED52CF917&var-namespace=sysbench-mysql-cdc&var-pod=benchmark-risingwave-frontend-f-6998cff55d-9qmc9&var-search=&from=1700467441984&to=1700467630220)

<img width="872" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/6cde4ea6-8857-454f-9e6e-08c2cb5ef322">

### The version of RisingWave

nightly-20231116

**Comment by lmatz** [comment]
How is the cluster started?

According to the timestamp, It looks like some service connects to Risingwave periodically

**Comment by cyliu0** [comment]
> How is the cluster started?

Via kube-bench

> 
> According to the timestamp, It looks like some service connects to Risingwave periodically

There are upstream MySQL Direct CDC, sysbench, psql client.

**Comment by xiangjinwu** [comment]
maybe health check similar to #12899?

**Comment by fuyufjh** [comment]
How can we reproduce? It seems a client is keeping connecting the frontend

**Comment by chenzl25** [comment]
According to the log, it seems `127.0.0.1` will connect to the frontend 1 time per 5s and `10.0.48.11` 2 times per 10s.

**Comment by cyliu0** [comment]
```
dev=> show processlist;
 Id | User |       Host        | Database |   Time    |         Info
----+------+-------------------+----------+-----------+-----------------------
 24 | root | 10.0.34.194:41750 | dev      | 7741800ms | DELETE FROM backfill;
 25 | root | 127.0.0.1:49326   | dev      | 0ms       | show processlist;
```

**Comment by chenzl25** [comment]
I think it is highly possible that some outer programs use `telnet 127.0.0.1 4566` to connect to the frontend.

**Comment by chenzl25** [comment]
Maybe k8s also has some health checks to the frontend? cc @arkbriar

**Comment by arkbriar** [comment]
> Maybe k8s also has some health checks to the frontend? cc @arkbriar

Yes. There's a probe checking TCP connectivity of the SQL port. K8s will kill the process if the proce failed for 3 times continuously.

**Comment by arkbriar** [comment]
Looks like the connections were started by the kubelet because of probing. Is it possible to hide the error when a TCP connection closed without sending anything? It also makes sense since a client hasn't been initialized and can fail silently.
