### ISSUE TITLE
deprecate nologin/login options in CREATE USER

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#13522]
option | description
-- | --
LOGIN | Grants the user the ability to log in when establishing connection with RisingWave. LOGIN is the default value.
NOLOGIN | Denies the user the ability to log in when establishing connection with RisingWave. LOGIN is the default value.

Following PG's design, we provided the above two options when creating users. However, the user in RW is basically a **role** in PG, which doesn't have the LOGIN/CONNECT privilege by default. PG's motivation is to prevent users connecting via a role, while we don't have such a concept at the moment.

My proposal is to deprecate LOGIN/NOLOGIN and allow all users to login, so that new users will not have unexpected connectivity issues. We can put them back in the future when there is a clear plan to support roles. Even if we do, I believe we still have plenty of ways to ensure people cannot login via roles.

Essentially, roles are distinct concept from users. It never makes sense to use roles to login. In other words, the following PG behavior should never be supported in RW:

```sql
CREATE ROLE test_user LOGIN;
```

```
psql -h localhost -p 5432 -d postgres -U test_user;
psql (16.0, server 14.8 (Homebrew))
Type "help" for help.

postgres=>
```

In the above example, I used a "role", a group of privileges, for connection. This seems pretty weird IMO. Please share your opinions on this proposal, thanks! @fuyufjh @xiangjinwu @yezizp2012

**Comment by yezizp2012** [comment]
I would prefer to make `LOGIN` default for `CREATE USER`, which is compatible with PG's behavior of `CREATE USER` syntax as well.

> LOGIN
> NOLOGIN
> These clauses determine whether a role is allowed to log in; that is, whether the role can be given as the initial session authorization name during client connection. A role having the LOGIN attribute can be thought of as a user. Roles without this attribute are useful for managing database privileges, but are not users in the usual sense of the word. If not specified, NOLOGIN is the default, except when CREATE ROLE is invoked through its alternative spelling [CREATE USER](https://www.postgresql.org/docs/current/sql-createuser.html).

**Comment by fuyufjh** [comment]
+1 for making `LOGIN` default for `CREATE USER`

**Comment by yezizp2012** [comment]
Oh, I found that we have already make `LOGIN` default for `CREATE USER`:
https://github.com/risingwavelabs/risingwave/blob/2133b82c09d8c23643561fc5cc87f24b2147bad9/src/frontend/src/handler/create_user.rs#L62-L68

Actually in the case @neverchanje  mentioned offline, `test_user` doesn't have `CONNECT` privilege to the new created database `test_db`, it's not about the create `LOGIN` option for user.

```sql
psql -h localhost -p 4566 -d dev -U root
> create database test_db
> create user test_user;

psql -h localhost -p 4566 -d test_db -U root
> CREATE TABLE orders (); # owner is root, database is test_db
> alter database test_db owner to test_user;

psql -h localhost -p 4566 -d test_db -U test_user
ERROR：User does not have CONNECT privilege.
```


After some local test on PG, the altering will success and `test_user` is able to connect to `test_database`. So I think for this case, here are two solutions to make rw behavior consistent with PG:
1. check whether the user is the owner of the database when connecting.
2. automatically assign `CONNECT` privilege for new owned user when altering the owner of database.

Cc @Rossil2012 , please help to fix it.
