### ISSUE TITLE
bug: performance spike without recovery or s3 failure

### ISSUE THREAD

**Issue by MrCroxx** [risingwavelabs/risingwave#13584]
### Describe the bug

grafana (test-eks-a, q20, nightly-20231120, 2cn + 2cm): 
https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1700576924291&orgId=1&to=1700581960496&var-datasource=P2453400D1763B4D9&var-instance=benchmark-risingwave&var-job=benchmark-risingwave-compute&var-namespace=benchmark-yao-manual&var-node=All&var-table=All

~https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4a/risingwave-dev-dashboard-foyer?from=1700576924291&orgId=1&to=1700581960496&var-datasource=P2453400D1763B4D9&var-instance=benchmark-risingwave&var-job=benchmark-risingwave-compute&var-namespace=benchmark-yao-manual&var-node=All&var-table=All~
 

There is no recovery or s3 failure during the period.

<img width="1465" alt="Untitled" src="https://github.com/risingwavelabs/risingwave/assets/22407295/5c408fbc-7ea3-4803-805e-6fbb671dcbd9">

**Comment by hzxa21** [comment]
This is the link for the original grafana dashboard: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1700576924291&orgId=1&to=1700581960496&var-datasource=P2453400D1763B4D9&var-instance=benchmark-risingwave&var-job=benchmark-risingwave-compute&var-namespace=benchmark-yao-manual&var-node=All&var-table=All

**Comment by st1page** [comment]
Not sure what happened. The cached entry count in hash join sudden dropped and no metrics for a time.
![image](https://github.com/risingwavelabs/risingwave/assets/40830455/a8bc5f5a-fd88-47b3-9f30-ebfadf7c22a1)

**Comment by MrCroxx** [comment]
<img width="957" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/22407295/d2f9d305-4870-4e59-90f0-25b7e65faf97">

09d312c108394fa48b6747e62a03c3f77d3d4ed2 vs 234b99b61734c9193234aebfbf58659775d52873

The bug may be introduced via #13286
