### ISSUE TITLE
MySQL CDC `datetime` and RW `timestamp` type incompatibility

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#13582]
### Describe the bug

I tried to use RW `timestamp` to sync MySQL `datetime` from MySQL CDC. But I got the following result. Other normal values like `2001-01-01 23:59:59` can be synced properly.

In MySQL:
```
mysql> select c_datetime from mysql_all_types;
+---------------------+
| c_datetime          |
+---------------------+
| 1000-01-01 00:00:00 |
| 1000-01-01 00:00:00 |
| 9999-12-31 23:59:59 |
+---------------------+
3 rows in set (0.00 sec)
```

In RW:
```
dev=> select c_datetime from mysql_all_types;
       c_datetime        
-------------------------
 
 1978-01-11 21:31:40.799
 
(3 rows)
```

### The version of RisingWave

nightly-20231121

**Comment by lmatz** [comment]
cc: @xiangjinwu,

Is it related to the PG CDC's ce/epoch issue https://github.com/risingwavelabs/risingwave/issues/13486?

**Comment by xiangjinwu** [comment]
No. It is related to https://github.com/risingwavelabs/risingwave/issues/8359#issuecomment-1455769049 (#6318)

> Other normal values like 2001-01-01 23:59:59 can be synced properly.

https://github.com/risingwavelabs/risingwave/issues/8359#issuecomment-1455769049
> Note that if you are ingesting data of type `timestamp` or `timestampz` in RisingWave, the upstream value must be in the range of `[1973-03-03 09:46:40, 5138-11-16 09:46:40] (UTC)`. The value may be parsed and ingested incorrectly without warning.
