### ISSUE TITLE
Record the original system version + commit ID when users created database objects

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#13614]
### Is your feature request related to a problem? Please describe.

- materialized views
- indexes
- views
- databases
- schemas
- sinks
- tables
- sources

Theoritically, all these objects require recording the versions.

This will allow us to quickly diagnose in which version upgrade the breaking change happened.
cc @stdrc

**Comment by fuyufjh** [comment]
cc. @st1page @yezizp2012
