### ISSUE TITLE
Proposal: replace RwError::InternalError with anyhow::Error

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#1367]
MemoryError - 9 results
InternalError - 309 results
ProstError - 5 results
NotImplementedError - 38 results
IoError - 26 results
StorageError - 4 results
ParseError - 10 results
BindError - 3 results
CatalogError - 21 results
NumericValueOutOfRange - 12 results
ProtocolError - 32 results
TaskNotFound - 8 results
ItemNotFound - 17 results
InvalidInputSyntax - 11 results
MemComparableError - 7 results
MetaError - 7 results

Considering everyone is using `InternalError`, we'd better make it anyhow::Error to avoid complexity in programming.

**Comment by TennyZhuang** [comment]
LGTTM
