### ISSUE TITLE
feat(optmizer): generate an constant filter in plan for temporal filter

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#13679]
rewrite `WHERE ts > now() - INTERVAL '5m'`
to 
```
WHERE ts > now() - INTERVAL '5m'
AND      ts > epoch_when_create - INTERVAL '5m'
```

Not sure if https://github.com/risingwavelabs/risingwave/issues/13680 can cover this method.

**Comment by BugenZhao** [comment]
Once the very first value comes from the right side of Dynamic Filter, the optimization introduced in #13985 should apply and we don't need to persist that record in the state table.

https://github.com/risingwavelabs/risingwave/blob/c791c8d22a2d1889c09c26f59c03503497703288/src/stream/src/executor/dynamic_filter.rs#L175-L179

As explained in https://github.com/risingwavelabs/risingwave/issues/13680#issuecomment-1980274923, the worst case now is that we receive the data of an entire epoch from the left side before receiving the very first `NOW()` value in Temporal Filter. This doesn't sound like a big deal anymore. So perhaps it's not necessary to do such optimization.
