### ISSUE TITLE
Please use `cargo install sccache --locked` to install sccache

### ISSUE THREAD

**Issue by Xuanwo** [risingwavelabs/risingwave#13670]
For more context, please visit: https://github.com/mozilla/sccache/issues/1989

https://github.com/risingwavelabs/risingwave/blob/98639aece6f96a60cb7eb9bb41fa34b157f34f5e/ci/Dockerfile#L52

**Comment by BugenZhao** [comment]
cc @xxchan

**Comment by xxchan** [comment]
https://github.com/risingwavelabs/risingwave/pull/12311#issuecomment-1719209699 @BugenZhao you removed it 😁

**Comment by BugenZhao** [comment]
Actually I believe `--locked` is a double-edged sword. It is by default disabled, and in the official reference it says...

> The downside to using `--locked` is that you will not receive any fixes or updates to any dependency.

For example, if a vulnerability is discovered in a locked dependency and the upstream is cannot fix it in time, it will still be a potential security concern.

**Comment by Xuanwo** [comment]
> For example, if a vulnerability is discovered in a locked dependency and the upstream is cannot fix it in time, it will still be a potential security concern.

Wow, makes sense too. Would you like to post this comment to https://github.com/mozilla/sccache/issues/1989 for discussion?

**Comment by xxchan** [comment]
> It is by default disabled,

related `cargo` issue https://github.com/rust-lang/cargo/issues/7169

**Comment by Xuanwo** [comment]
This is merely a suggestion, not a mandatory action. Let's close if it yields no positive outcome.
