### ISSUE TITLE
send a now value at the beginning though it is paused

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#13680]
otherwise, when creating the MV with a temporal filter during the pause, the dynamic filter will consider all records to satisfy the condition. And when the first now() vlaue comes, it will produce many delete.

https://github.com/risingwavelabs/risingwave/blob/6fe26b46b399e5831a6927fdf859a84b02432da4/src/stream/src/executor/now.rs#L71-L114

alternative https://github.com/risingwavelabs/risingwave/issues/13679

**Comment by BugenZhao** [comment]
> the dynamic filter will consider all records to satisfy the condition

Interesting. Why an MV created with paused will have records? Does it mean that we should pause `Backfill` as well?

**Comment by BugenZhao** [comment]
> Does it mean that we should pause `Backfill` as well?

This has been done in #14745.
