### ISSUE TITLE
sysbench: `connection error received: detected excessive load generating behavior `

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#13708]
### Describe the bug

https://buildkite.com/risingwave-test/sysbench/builds/596#018c17bd-2613-465e-9e64-6359cf9e3e3a

https://grafana.test.risingwave-cloud.xyz/d/liz0yRCZz1/log-search-dashboard?orgId=1&from=now-12h&to=now&var-data_source=PE59595AED52CF917&var-namespace=sysbench-daily-test-20231128&var-pod=benchmark-risingwave-frontend-f-6d47fdb6d5-grd9r&var-search=

![SCR-20231129-eqa](https://github.com/risingwavelabs/risingwave/assets/5791930/20401ec5-3385-45d7-b51a-67a07e9de17b)

Same error yesterday: https://buildkite.com/risingwave-test/sysbench/builds/595

But if we look at the successful tests a few days ago: https://buildkite.com/risingwave-test/sysbench/builds/576#018bff4b-2891-4a64-ab7e-12f4b56815ba
the QPS is low.

### Additional context

cc: @chenzl25  @liurenjie1024, could you help take a look? Thanks

**Comment by liurenjie1024** [comment]
I will ses see.

**Comment by liurenjie1024** [comment]
After some investigation, this is caused by early stop of grpc stream, and we didn't handle grpc stream cancel correctly. I'll submit a pr to fix it.
