### ISSUE TITLE
Discussion: Create downstream schemas when creating the sink

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#13718]
### Is your feature request related to a problem? Please describe.

This requirement will involve non-trivial development efforts, so let's have a discussion first.

In general, when users create a sink, which possibly contains dozens of columns, someone will need to create the schema in the sink system. The duty of the schema creation is currently left to the users for the simplicity of our system. The issue still remains, although not our concern. The user will have to manually write create table statement, mapping each risingwave data type to the sink's data type. Apparently, it causes inconvenience as well as some data faults if the user doesn't strictly follow our type mapping rules. As an enhancement, I propose to let RisingWave automatically create the downstream schema when a new sink is defined.

On the other hand, it’s possible that the downstream has a predefined schema, e.g, in the case where multi-sinks streaming into one table. In this case, the auto creation should be optional:

```sql
create sink s1 from t with (
  auto.schema.create = ‘false’ 
)
```

I propose that `auto.schema.create` should be false by default, meaning that we don't do additional steps unless necessary.

Ultimately, I expect the cloud portal should provide this option to users as well. cc @wyhyhyhyh 

### Describe the solution you'd like

- [ ] `auto.register.schemas` for Kafka Protobuf/Avro sink https://github.com/risingwavelabs/risingwave/issues/13139
- [x] #14254
- [ ] `auto.register.schemas` for Postgres sink
- [ ] `auto.register.schemas` for MySQL sink
- [ ] `auto.register.schemas` for Clickhouse sink
- [ ] `auto.register.schemas` for Doris sink

**Comment by fuyufjh** [comment]
Basically +1 for this.

Notice that this question should be discussed for each different sink **respectively**. Some cases actually doesn't need any discussion.

- Kafka sink: It will automatically create missing topics, which is the default behavior of Kafka producer
- Cassandra/Redis: They don't have concept of "Table"

While,

- For relational databases such as PG, MySQL, ClickHouse, Doris, etc., +1 for providing `auto_schema_create` and `false` by default
- For data lakes such as Iceberg & Delta Lake, I am afraid the mapping of schema and data types might be a problem because they are not natively relational data model. We may discuss them case by case.

**Comment by xiangjinwu** [comment]
It is not enough to just add one option. A lot of auxiliaries options may be necessary eventually and we need a plan how to support them gradually without incurring too much burden on backward compatibility. The auxiliaries options I have in mind mostly deal with the misalignment between RisingWave data types and sink data types, when more than 1 candidate mappings are possible. For example:
* When there is no `date` type in downstream (eg json), do we represent it as string or a number?
* When there is no `int64` type in downstream (again json), do we represent it as number (lossy) or a string ([proto-json](https://protobuf.dev/programming-guides/proto3/#json:~:text=int64%2C%20fixed64%2C%20uint64))?
* When `varchar` can map to multiple types in downstream (eg MySQL `tinytext`/`text`/`mediumtext`/`longtext`), which option do we use?
* When `decimal` is fixed scale in downstream (eg avro), what `(precision, scale)` value do we use?
* When `struct` requires a name in downstream (eg avro / proto), what name do we use?

**Comment by xiangjinwu** [comment]
Will focus on writing schema registry for avro first, and I will update later with a list of options for tuning type mapping from risingwave to avro.
