### ISSUE TITLE
Metrics: split a independent "barrier" section?

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#13720]
We have a "streaming" section but there are many "source throughput" panels which could be large and need time to load when the cluster is big. And the barrier latency and barrier number is a very important metrics when we want to check a cluster's status. So maybe we need to make barrier metrics independent?

**Comment by wcy-fdu** [comment]
Agree.

**Comment by hzxa21** [comment]
+1. Btw, should we have a separate section for all important metrics?
