### ISSUE TITLE
udf: improve parallelism of Python UDFs

### ISSUE THREAD

**Issue by wangrunji0408** [risingwavelabs/risingwave#13744]
### Describe the bug

Python UDF has poor parallelism now, making it easy to become the bottleneck of the stream.

There are 2 problems: 
1. Python UDF server can not use multicores due to the GIL limit.
2. One compute node can only have one TCP connection to the UDF server, because of gRPC HTTP2 multiplexing.

### Expected behavior

For problem 1, we should explore Python multiprocessing pool.
For problem 2, the UDF client should accept multiple addresses so that one CN can setup multiple connections to UDF server.
https://docs.rs/tonic/latest/tonic/transport/channel/struct.Channel.html#method.balance_list

**Comment by BugenZhao** [comment]
> docs.rs/tonic/latest/tonic/transport/channel/struct.Channel.html#method.balance_list

This reminds me of our trivial implementation of `RpcClientPool` load balancing: 

https://github.com/risingwavelabs/risingwave/blob/3fd4a57496aecad12878ebb474fbc51469576aac/src/rpc_client/src/lib.rs#L111-L127

I'm not sure if it's possible to switch to `balance_list` approach as well. 🤣

**Comment by NiuBlibing** [comment]
UDF server is usually deploy on k8s and exposes with a service, `balance_list` may not work because the service url is only one.

**Comment by NiuBlibing** [comment]
Maybe run multiple rpc clients is better?

**Comment by xxchan** [comment]
> Maybe run multiple rpc clients is better?

This can't help since the server is bound by GIL.

**Comment by xxchan** [comment]
> UDF client should accept multiple addresses

Do you mean users will also need to create UDF with multiple addrs? I doubt that's not very user-friendly and flexible. A balancer at the UDF server side which is transparent to the kernel might be better.

BTW, I think solving 1 can already give us a lot of improvements.
