### ISSUE TITLE
Bug(batch): Zombie batch query runs for a long time in the system

### ISSUE THREAD

**Issue by Li0k** [risingwavelabs/risingwave#13761]
### Describe the bug

We have observed an unintended batch task that continues to execute in the system. This task lasts longer than 10h, thus affecting the execution of compaction in storage.

![image](https://github.com/risingwavelabs/risingwave/assets/15023748/7ea88020-f054-47fa-aabf-1022b743de49)

The reason for this is that the batch query will hold a snapshot, which is the basis for the compaction task to clean up the data, and we will determine the safe epoch of the task based on the snapshot.

![image](https://github.com/risingwavelabs/risingwave/assets/15023748/9a43c771-b31e-4198-82a7-288024d79a1b)

Since the safe epoch cannot be raised, the compaction task cannot reclaim the expired data, resulting in a large number of tombstones in the system.

![image](https://github.com/risingwavelabs/risingwave/assets/15023748/fa6eb505-ec1c-42aa-bb1b-78c921376b3e)

<img width="1749" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/15023748/904aea6d-86f7-492a-9165-0cefe52fa4ba">

### The version of RisingWave

nightly-20231123

**Comment by Li0k** [comment]
@liurenjie1024

**Comment by liurenjie1024** [comment]
Duplicated with #9732
