### ISSUE TITLE
nexmark q19 and q20 blackhole performance degradation on affinity testbed between 1130-1203

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#13773]
### Describe the bug

The daily performance test shows we have performance degradation on nexmark q19 and q20 with affinity testbed. https://buildkite.com/risingwave-test/nexmark-benchmark/builds/2583#018c306a-745d-4244-9b94-8a9234f74a42

http://metabase.risingwave-cloud.xyz/question/7039-nexmark-avg-source-throughput?start_date=2023-11-01&workload=q20-blackhole
<img width="1577" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/132dbdf6-875f-4277-b05d-1943e7fe636b">

```md5
+-----------------------------------------------------------------+--------------+------------+---------------------+-----------------------------+
| BENCHMARK NAME                                                  | EXECUTION ID | STATUS     | FLUCTUATION OF BEST | FLUCTUATION OF LAST 10 DAYS |
+-----------------------------------------------------------------+--------------+------------+---------------------+-----------------------------+
| nexmark-q19-blackhole-medium-1cn-affinity                       |        15919 | Negative   | -18.25%             | -13.15%                     |
| nexmark-q20-blackhole-medium-1cn-affinity                       |        15927 | Negative   | -29.25%             | -22.28%                     |
```

### The version of RisingWave

nightly-20231203

**Comment by fuyufjh** [comment]
> Is it possible that #13075 caused this? cc @Li0k

I'm also suspecting this commit. Additionally, the bloom-filter positive rate differs a lot, which may indicate that the compactor cannot catch up with writes.

1130:

<img width="945" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/9ee59021-7623-444b-911e-7d546932bc76">

https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1701371750000&to=1701373554000&var-namespace=nexmark-bs-15-105-affinity-daily-20231130

1203:

<img width="947" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/82a4bf84-de38-4442-8b6a-899dfea1f23f">

https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1701630923000&orgId=1&to=1701632727000&var-datasource=Prometheus%3A+test-useast1-eks-a&var-namespace=nexmark-bs-15-105-affinity-daily-20231203

**Comment by Li0k** [comment]
Yes, I guess it has negative effects, do I need to revert it immediately?

**Comment by cyliu0** [comment]
Is the PR in nightly-20231204? According to the test result, the perf is not totally recovered.
<img width="1906" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/c3a00984-a39c-4507-9b67-a19d40c56b64">

**Comment by Li0k** [comment]
> Is the PR in nightly-20231204? According to the test result, the perf is not totally recovered. <img alt="image" width="1906" src="https://private-user-images.githubusercontent.com/35356271/287892203-c3a00984-a39c-4507-9b67-a19d40c56b64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NDk0NTMsIm5iZiI6MTcwMTc0OTE1MywicGF0aCI6Ii8zNTM1NjI3MS8yODc4OTIyMDMtYzNhMDA5ODQtYTM5Yy00NTA3LTliNjctYTE5ZDQwYzU2YjY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA0MDU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNGZkOTY1MzY5MWRkMTkwM2Y4NTc5OGE0OGFmY2YwMDFhNDQyYzQzOWY2M2I3ZDU4MmM0NDdkODgzMTQzMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NLQLDaYoClMy5Z1j5nxeb-wbNuv0yy8oPbN8XzpWo1I">

Unfortunately, Should I need to run the nexmark manually?

**Comment by Li0k** [comment]
### Compare affinity

#### CPU

before

<img width="953" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/15023748/331faf4a-49f5-4f00-920e-e35c9b0b70cf">

after

<img width="952" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/15023748/6a92d1bb-44dc-47cc-8c87-9febdab2d684">

#### throughput

before 

<img width="1511" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/15023748/59d3285d-457b-4ef8-8453-7c0961655ff5">

after

<img width="1510" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/15023748/a47c49d5-7641-4e57-8ef4-c1ec3365270a">

**Comment by cyliu0** [comment]
According to the test result, it's fixed by https://github.com/risingwavelabs/risingwave/pull/13790. But in the daily perf test, we found some new perf degradations https://github.com/risingwavelabs/risingwave/issues/13821
<img width="1899" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/0a3c4a58-0904-4aa8-b811-bafed180cad1">
