### ISSUE TITLE
Do not block barrier when rate limiting with smaller than chunk_size

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#13799]
- [ ] Add test for rate limit on source. https://github.com/risingwavelabs/risingwave/pull/13800
- [x] Add test for rate limit on snapshot read. https://github.com/risingwavelabs/risingwave/pull/13837
- [ ] Add test for rate limit on DML. #13902 
- [ ] Support partition in non-transaction source by `rate_limit` https://github.com/risingwavelabs/risingwave/pull/13800
- [x] Support partition in snapshot read by `rate_limit`. https://github.com/risingwavelabs/risingwave/pull/13837
- [ ] Support partition in transaction source by `rate_limit`
- [ ] Support rate limit on DML. #13902

**Comment by BugenZhao** [comment]
What's the plan for not blocking the barrier? I guess for those "source-like" executors such as `Source` or `DML`, it's natural. For other executors, we have to do "barrier stealing/rearrangement" and the consistency could be broken.

**Comment by kwannoel** [comment]
> What's the plan for not blocking the barrier? I guess for those "source-like" executors such as `Source` or `DML`, it's natural. For other executors, we have to do "barrier stealing/rearrangement" and the consistency could be broken.

Yeah actually it's just for `Source` / `DML`.

The plan is to just throttle stream reader. I have a WIP PR where I will add more details soon.

**Comment by kwannoel** [comment]
Source is pending https://github.com/risingwavelabs/risingwave/pull/14215#issuecomment-1884839655
