### ISSUE TITLE
perf bug: barriers pile up due to temporal filter

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#13807]
Longevity `reglngvty-20231204-140246` failed 

```
!!! longevity Result!!!
Today's date:2023-12-05
Result               FAIL                
Pipeline Message     1@Monday nexmark q8 q9 q15 q16 with 200000 throughput
TestBed              kubebench/3264g-medium-all-affinity
RW Version           nightly-20231204    
Test Start time      2023-12-04 14:08:16 
Test End time        2023-12-05 02:10:30 
Namespace            reglngvty-20231204-140246
Queries              nexmark_q8,nexmark_q9,nexmark_q15,nexmark_q16
Grafana Metric       https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=reglngvty-20231204-140246&from=1701698896000&to=1701742230000
Grafana Logs         https://grafana.test.risingwave-cloud.xyz/d/liz0yRCZz1/log-search-dashboard?orgId=1&var-data_source=Logging:%20test-useast1-eks-a&var-namespace=reglngvty-20231204-140246&from=1701698896000&to=1701742230000
Buildkite Job        https://buildkite.com/risingwave-test/longevity-test/builds/840
Crash Container logs https://rw-qa-artifacts-public.s3.us-east-1.amazonaws.com/longevity/840_logs.txt
Report               https://rw-qa-artifacts-public.s3.us-east-1.amazonaws.com/longevity/840_report.txt
```
The barriers were blocked by something per 30 minutes... Meanwhile, we do a `select limit 1` check every 30 minutes. Is it an coincident?

![image](https://github.com/risingwavelabs/risingwave/assets/10192522/c89a2aab-6dde-49f8-a744-d19458a5f481)

```
Running command SELECT * FROM nexmark_q16_1 LIMIT 1
```

**Comment by fuyufjh** [comment]
[await-tree-dump-2023-12-05-15-33-16.txt](https://github.com/risingwavelabs/risingwave/files/13556566/await-tree-dump-2023-12-05-15-33-16.txt)

**Comment by st1page** [comment]
It is very similar with the performance issue @Little-Wallace is investigating these days with temporal filter, which is related to this issue.

**Comment by fuyufjh** [comment]
Triggered by https://github.com/risingwavelabs/kube-bench/pull/336. After it, a materialized view `bid_filtered` is always created, no matter used or not in the specified queries.

**Comment by fuyufjh** [comment]
Similar issue happened during ch-benchmark test.

![image](https://github.com/risingwavelabs/risingwave/assets/10192522/8d94a078-0795-4c04-9706-74347832f1c7)

With 

```sql
CREATE MATERIALIZED VIEW backfill_watermark_mv AS SELECT * FROM backfill WHERE now() - interval '5' minute < p_time;
```

**Comment by cyliu0** [comment]
For the record, the backfill test detail https://risingwave-labs.slack.com/archives/C05AZUR6Q5P/p1701856381580449?thread_ts=1701755324.736659&cid=C05AZUR6Q5P

**Comment by fuyufjh** [comment]
The root cause of the problem is: the speed of `DynamicFilterExecutor` reading rows to delete can not catch up with `now()`

Specifically,

1. `NowExecutor` emits a timestamp row for every epoch, and this is not affected by the back-pressure mechanism.
2. When `DynamicFilterExecutor` receives this timestamp and it needs to scan all rows expired by it. This might cost more than 1 second, especially when data is not cached. Let's say that the scan operation cost 5s to complete.
3. Every 1 seconds, a new barrier is generated; while every 5 seconds, a barrier can be passed, obviously, more and more barriers accumulated, forming the increasing barrier latency in the Grafana. 
4. In `reglngvty-20231204-140246`, finally, all rows in `DynamicFilterExecutor`'s state table are deleted after a while. Afterwards, the `DynamicFilterExecutor` scans nothing, so that's prettty fast, allowing it to catch up with `Now`
5. Then, new events come from source, which previously was backpressured. After some while, back to 4.1 again.

**Comment by fuyufjh** [comment]
After careful consideration, I think that we should make a back-pressure mechanism in `NowExecutor` similar with other source executors. Instead of inserting the timestamp row per epoch strictly, it should generate the timestamp row **only for the latest epoch**, skipping the accumulated barriers in the `barrier_receiver` channel.

I mentioned this is "similar with other source executors" because other source executors will always prioritize barrier events than data events. Here is the same. The only difference is that the "delayed" data events is not static, but changing according to the last passed barrier.

The downside of this approach, as pointed by @BugenZhao, is that the batch query will not get consistent results once the epoch it reads was just skipped. However, it seems complicated to fix this, and I tend to put this aside.

**Comment by fuyufjh** [comment]
> Can this help #10744? Perhaps now it's time to work on it.

Agree that we can work on it to see the improvement. Don't know how much it can improve.

**Comment by hzxa21** [comment]
> After careful consideration, I think that we should make a back-pressure mechanism in `NowExecutor` similar with other source executors. Instead of inserting the timestamp row per epoch strictly, it should generate the timestamp row **only for the latest epoch**, skipping the accumulated barriers in the `barrier_receiver` channel.
> 
> I mentioned this is "similar with other source executors" because other source executors will always prioritize barrier events than data events. Here is the same. The only difference is that the "delayed" data events is not static, but changing according to the last passed barrier.
> 
> The downside of this approach, as pointed by @BugenZhao, is that the batch query will not get consistent results once the epoch it reads was just skipped. However, it seems complicated to fix this, and I tend to put this aside.

IIUC, there are two benefits of this approach:
1. Storage iterator will be created less frequently and there will be more data involved in each scan
2. There will be less range tombstones generated

Essentially, we reduce the frequency of scan, while the total amount of data to be scanned is the same with and without this optimization. Therefore, it will help only if the bottleneck lies in creating the storage iterator, not in the actual row scan. Have we verified that is the case?

**Comment by st1page** [comment]
https://github.com/risingwavelabs/risingwave/pull/13832#issuecomment-1853390021

**Comment by fuyufjh** [comment]
Thanks to #13271, In `nightly-20231212` the problem is significantly mitigated:

https://buildkite.com/risingwave-test/longevity-test/builds/855#018c6212-e727-45e6-bbe9-5a501c2d707b

![image](https://github.com/risingwavelabs/risingwave/assets/10192522/4aae2e3d-a040-4467-8355-eb5f21925ee6)

**Comment by fuyufjh** [comment]
Let me close this first. If new problems found, will create new issues then.
