### ISSUE TITLE
Tracking: Support TPC-H Queries (in Rust Frontend)

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#1380]
Currently, our new frontend in Rust can work for basic queries. Let's start to port TPC-H queries to it! See also #110 for the support of Java frontend.

**A query is marked as supported if it has been added to the end-to-end test.**

## SQL Features in Queries

| Query | Group-by (Aggregation) | Order-by (Sort/TopN) | Join | Subquery in `from` | Non-Correlated Subquery | Correlated Subquery | CTE / View |
|---|---|---|---|---|---|---|---|
| Q1 | ✔️ | ✔️ |  |  |  |  |  |
| Q2 |  | ✔️ | ✔️ |  |  | ✔️ (value in filter) |  |
| Q3 | ✔️ | ✔️ | ✔️ |  |  |  |  |
| Q4 | ✔️ | ✔️ |  |  |  | ✔️ (exists) |  |
| Q5 | ✔️ | ✔️ | ✔️ |  |  |  |  |
| Q6 | ✔️ (simple) |  |  |  |  |  |  |
| Q7 | ✔️ | ✔️ | ✔️ | ✔️ (table) |  |  |  |
| Q8 | ✔️ | ✔️ | ✔️ | ✔️ (table) |  |  |  |
| Q9 | ✔️ | ✔️ | ✔️ | ✔️ (table) |  |  |  |
| Q10 | ✔️ | ✔️ | ✔️ |  |  |  |  |
| Q11 | ✔️ | ✔️ | ✔️ |  | ✔️ (value in filter) |  |  |
| Q12 | ✔️ | ✔️ | ✔️ |  |  |  |  |
| Q13 | ✔️ | ✔️ | ✔️ (outer) | ✔️ (table) |  |  |  |
| Q14 | ✔️ (simple) |  | ✔️ |  |  |  |  |
| Q15 | ✔️ | ✔️ | ✔️ |  | ✔️ (value in filter) |  | ✔️ |
| Q16 | ✔️ | ✔️ | ✔️ |  | ✔️ (not in) |  |  |
| Q17 | ✔️ (simple) |  | ✔️ |  |  | ✔️ (value in filter) |  |
| Q18 | ✔️ | ✔️ | ✔️ |  | ✔️ (in) |  |  |
| Q19 | ✔️ (simple) |  | ✔️ |  |  |  |  |
| Q20 | ✔️ | ✔️ | ✔️ |  | ✔️ (in) | ✔️ (value in filter) |  |
| Q21 | ✔️ | ✔️ | ✔️ |  |  | ✔️ (exists) |  |
| Q22 | ✔️ | ✔️ |  | ✔️ (table) | ✔️ (value in filter) | ✔️ (not exists) |  |

## Batch

- [x] Batch: TPC-H Q1
- [x] Batch: TPC-H Q2
- [x] Batch: TPC-H Q3
- [x] Batch: TPC-H Q4
- [x] Batch: TPC-H Q5
- [x] Batch: TPC-H Q6
- [x] Batch: TPC-H Q7
- [x] Batch: TPC-H Q8
- [x] Batch: TPC-H Q9
- [x] Batch: TPC-H Q10
- [x] #2152
- [x] Batch: TPC-H Q12
- [x] Batch: TPC-H Q13
- [x] Batch: TPC-H Q14
- [x] Batch: TPC-H Q15
- [x] Batch: TPC-H Q16
- [x] #1865 
- [x] Batch: TPC-H Q18
- [x] Batch: TPC-H Q19
- [x] Batch: TPC-H Q20
- [x] Batch: TPC-H Q21
- [x] Batch: TPC-H Q22

## Streaming

- [x] #1456
- [x] #1851
- [x] #1457
- [x] #1852
- [x] #1411
- [x] Streaming: TPC-H Q6 https://github.com/singularity-data/risingwave/pull/1404
- [x] Streaming: TPC-H Q7
- [x] #1853
- [x] #1854
- [x] #1458
- [x] #1855
- [x] #1872
- [x] Streaming: TPC-H Q13
- [x] #2019
- [x] Streaming: TPC-H Q15
- [ ] Streaming: TPC-H Q16
- [x] Streaming: TPC-H Q17
- [x] Streaming: TPC-H Q18
- [x] Streaming: TPC-H Q19
- [x] Streaming: TPC-H Q20
- [ ] Streaming: TPC-H Q21
- [x] Streaming: TPC-H Q22

**Comment by skyzh** [comment]
For streaming TPC-H, the last two blocking issues on generating plan are
* https://github.com/singularity-data/risingwave/issues/1866
* https://github.com/singularity-data/risingwave/issues/2027

After that, we can see if executors would work correctly, and finish migrating to the Rust frontend.

**Comment by fuyufjh** [comment]
Update: Today, here are the related on-going works:

- Support unnesting correlated `NOT IN` subquery to anti-semi join @likg227 
- Support semi join in join executor (both batch and streaming) @yuhao-su 
- #1866

**Comment by likg227** [comment]
We have to support Substring for tpch q22.

**Comment by BowenXiao1999** [comment]
> According to our e2e tests we should be able to close everything on the streaming side except q16 and q21 (once #3681 is merged).

Thanks for this info. Update some issue status. 

It seems we indeed do not includes q16 and q21, but what about q15?
https://github.com/singularity-data/risingwave/blob/093addfaf4cf6c728cc8c20c15a7aa2616617794/e2e_test/streaming/tpch_snapshot.slt#L45-L46
