### ISSUE TITLE
Add a new derive macro `#[derive(Fields)]`

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#13851]
### Background

Sometimes, we may want to construct a `Row` or `DataChunk` with type safety. To achieve that, we can create a struct, and then do one of the following thing:

1. convert it to an `OwnedRow`
2. impl `Row` for the struct directly (not covered by the macro now)
3. Encode it to a chunk (not covered by the macro now)

There is one fundamental prerequisite, which is to know the data_types or schema corresponding to this struct.

The macro can help to do that.

Related https://github.com/risingwavelabs/risingwave/issues/13433

### Design

First of all, we'll introduce a new trait `Fields` in common crate.

```rust
pub trait Fields {
    pub fn fields() -> Vec<Field>;
}
```

Then we'll introduce a derive macro to help struct to implement it:

```rust
#[derive(Fields)]
struct PgShadowRow {
  usename: String,
  usesysid: i32,
  usecreatedb: bool,
  usesuper: bool,
  userepl: bool,
  usebypassrls: bool,
  passwd: String,
  valuntil: Timestamptz,
  useconfig: Vec<String>,
}
```

Here is the type mapping table:

|rust type|rw type|
|---|---|
|bool|Boolean|
|i16|Int16|
|i32|Int32|
|i64|Int64|
|f32/F32|Float32|
|f64/F64|Float64|
|&'static str/String|Varchar|
|Date|Date|
|Time|Time|
|Timestamp|Timestamp|
|Timestamptz|Timestamptz|
|Interval|Interval|
|Vec<u8>/Bytes|Bytea|
|Jsonb|Jsonb|
|Int256|Int256|
|Decimal|Decimal|
|Vec<T>|DataType::List(mapping(T))|
|Option<T>|mapping(T)|
|`T impl Fields`| Struct(T::fields)| 

### Future Optimizations

We can support more field level options such as `alias`, `unnamed`, `ignore` or `repr` in `field` attribute, as needed.

**Comment by xxchan** [comment]
What's the difference between `#[derive(Fields)]` and `#[derive(Catalog)]`(#13433)? The examples look alike.

```rust
#[derive(Fields)]
struct PgShadowRow {
  usename: String,
  usesysid: i32,
  usecreatedb: bool,
  usesuper: bool,
  userepl: bool,
  usebypassrls: bool,
  passwd: String,
  valuntil: Timestamptz,
  useconfig: Vec<String>,
}

#[derive(Catalog)]
#[catalog(reader, rw_catalog.rw_schemas)]
pub struct RwSchemasRow {
    id: i32,
    name: String,
    owner: i32,
    acl: String,
}
```

**Comment by xxchan** [comment]
Do you have any other usages beside assisting `Catalog` in mind for `Fields`?
