### ISSUE TITLE
risingwave panicked when running sink example

### ISSUE THREAD

**Issue by wangrunji0408** [risingwavelabs/risingwave#13865]
### Describe the bug

When I tried to follow the example in https://tutorials.risingwave.com/docs/basics/sink, RisingWave panicked.
I have started a Kafka on localhost:9092. But the error message showed `Failed to resolve 'bogon:9092'`.

### Error message/log

The first error seems to be:
```
2023-12-08T11:11:30.426349+08:00 ERROR librdkafka: librdkafka: FAIL [thrd:bogon:9092/0]: bogon:9092/0: Failed to resolve 'bogon:9092': nodename nor servname provided, or not known (after 19ms in state CONNECT)
```

Eventually it panicked with:
```
thread 'risingwave-main' panicked at src/meta/src/barrier/mod.rs:1049:13:
failed to execute barrier: gRPC request to stream service failed: Internal error: Actor 33 exited unexpectedly: Executor error: Sink error: Kafka error: Message production error: MessageTimedOut (Local: Message timed out)
```

### To Reproduce

```sql
CREATE TABLE t1 (v1 int, v2 int)
WITH (
     connector = 'datagen',
     fields.v1.kind = 'sequence',
     fields.v1.start = '1',
     fields.v2.kind = 'random',
     fields.v2.min = '-10',
     fields.v2.max = '10',
     fields.v2.seed = '1',
     datagen.rows.per.second = '10'
) ROW FORMAT JSON;

CREATE SINK test_sink
FROM t1 
WITH (
        properties.bootstrap.server = 'localhost:9092',
        topic = 'test_sink_topic',
        connector = 'kafka',
        primary_key = 'v1'
)
FORMAT UPSERT ENCODE JSON;
```

### Expected behavior

RisingWave should not panic in this case.

### How did you deploy RisingWave?

`./risedev p`

### The version of RisingWave

The main branch 7fd2a0eb.

### Additional context

[risingwave.log](https://github.com/risingwavelabs/risingwave/files/13608532/risingwave.log)

**Comment by tabVersion** [comment]
will take a look

**Comment by tabVersion** [comment]
I didn't find the name resolve issue but found a panic inside. 🤣

**Comment by tabVersion** [comment]
https://github.com/confluentinc/librdkafka/issues/2035#issuecomment-426524544

---

Summary: Message production error: MessageTimedOut (Local: Message timed out) basically stands for the producing rate is too high. Consider this case, we may have many parallelisms producing to a single partitioned topic. 
Tested locally, if setting the parallelism to 1, everything goes well.

We may consider automatically setting the sink parallelism align with the downstream broker.
