### ISSUE TITLE
The PG CDC sync latency is too large after upgrade from v1.4.0 to v1.5.0-rc-1

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#13860]
### Describe the bug

Start a ch-benchmark-pg-cdc test with 280 warehouses on RW v1.4.0.
Upgrade to v1.5.0-rc-1 with kubectl edit image during data syncing. In this case, it's 15:45

According to the below pg panels, the upstream PG stopped inserting and updating before 16:55

<img width="1911" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/8d5394a1-702f-4af2-a2bb-130ccef764f9">

<img width="1909" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/97358ce3-5116-4af7-aeff-5bd6d5ccce16">

But the RW grafana and query result show that the sync is still in progress after one hour.

https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1701934243000&orgId=1&to=now&var-component=All&var-datasource=P2453400D1763B4D9&var-instance=benchmark-risingwave&var-namespace=ch-benchmark-pg-cdc-20231207-025440&var-pod=All&var-table=All&refresh=10s

<img width="1913" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/0dd2f01a-86de-48cf-98e4-48ef2afb54a2">

The namespace is `ch-benchmark-pg-cdc-20231207-025440`. And it's alive for now

### The version of RisingWave

v1.5.0-rc-1

**Comment by StrikeW** [comment]
Let me run a benchmark of pg-cdc for v1.5-rc to check the performance number.

**Comment by StrikeW** [comment]
And do we have run this pipeline before for v1.4.0 and also have a grafana it? @cyliu0

**Comment by cyliu0** [comment]
No this is a new one. Before we usually didn't test data with this size.

**Comment by hzxa21** [comment]
> The source of `order_line` table continuously received data from upstream until about 23:00.
> 
> ```
> 2023-12-07 08:28:02,074 INFO  [rw-dbz-engine-runner-1020] common.BaseSourceTask:186 - 3368497 records sent during previous 00:16:48.149, last recorded offset: {transaction_id=null, lsn_proc=15081076232, lsn_commit=15081068688, lsn=15081076232, txId=54933, ts_usec=1701935297061221} |  
> -- | --
>   | 2023-12-07 09:11:00,936 INFO  [rw-dbz-engine-runner-1020] common.BaseSourceTask:186 - 8151786 records sent during previous 00:42:58.856, last recorded offset: {transaction_id=null, lsn_proc=18371834072, lsn_commit=18371786048, lsn=18371834072, txId=73445, ts_usec=1701935781531098} |  
>   | 2023-12-07 11:10:24,427 INFO  [rw-dbz-engine-runner-1020] common.BaseSourceTask:186 - 28496937 records sent during previous 01:59:23.497, last recorded offset: {transaction_id=null, lsn_proc=31707283672, lsn_commit=31707730792, lsn=31707283672, txId=121243, ts_usec=1701937417479487} |  
>   | 2023-12-07 13:10:24,231 INFO  [rw-dbz-engine-runner-1020] common.BaseSourceTask:186 - 32255747 records sent during previous 01:59:59.804, last recorded offset: {transaction_id=null, lsn_proc=49270236200, lsn_commit=49270071944, lsn=49270236200, txId=180133, ts_usec=1701938721133379} |  
>   | 2023-12-07 15:11:05,197 INFO  [rw-dbz-engine-runner-1020] common.BaseSourceTask:186 - 8782804 records sent during previous 02:00:40.966, last recorded offset: {transaction_id=null, lsn_proc=57218941128, lsn_commit=57218941128, lsn=57218941128, txId=222368, ts_usec=1701939241430446}
> ```
> 
> I checked CN's log, the snapshot phase of postgres cdc has been done on 15:50 (07:50 UTC), so the connector is consuming wal events from upstream for a long time.
> 
> ```
> 2023-12-07 07:49:57,801 INFO  [debezium-postgresconnector-RW_CDC_1020-change-event-source-coordinator] relational.RelationalSnapshotChangeEventSource:397 - 	 Exported 3201025 records for table 'public.order_line' after 00:04:48.304 |  
> -- | --
>   | 2023-12-07 07:50:03,370 INFO  [debezium-postgresconnector-RW_CDC_1020-change-event-source-coordinator] relational.RelationalSnapshotChangeEventSource:415 - 	 Finished exporting 3306652 records for table 'public.order_line'; total duration '00:04:53.873' |  
>   | 2023-12-07 07:50:03,370 INFO  [debezium-postgresconnector-RW_CDC_1020-change-event-source-coordinator] source.AbstractSnapshotChangeEventSource:88 - Snapshot - Final stage |  
>   | 2023-12-07 07:50:03,371 INFO  [debezium-postgresconnector-RW_CDC_1020-change-event-source-coordinator] pipeline.ChangeEventSourceCoordinator:156 - Snapshot ended with SnapshotResult [status=COMPLETED, offset=PostgresOffsetContext [sourceInfoSchema=Schema{io.debezium.connector.postgresql.Source:STRUCT}, sourceInfo=source_info[server='RW_CDC_1020'db='postgres', lsn=LSN{3/30000000}, txId=42613, timestamp=2023-12-07T07:45:09.387128Z, snapshot=FALSE, schema=public, table=order_line], lastSnapshotRecord=true, lastCompletelyProcessedLsn=null, lastCommitLsn=null, streamingStoppingLsn=null, transactionContext=TransactionContext [currentTransactionId=null, perTableEventCount={}, totalEventCount=0], incrementalSnapshotContext=IncrementalSnapshotContext [windowOpened=false, chunkEndPosition=null, dataCollectionsToSnapshot=[], lastEventKeySent=null, maximumKey=null]]] |  
>   | 2023-12-07 07:50:03,371 INFO  [debezium-postgresconnector-RW_CDC_1020-change-event-source-coordinator] pipeline.ChangeEventSourceCoordinator:236 - Connected metrics set to 'true' |  
>   | 2023-12-07 07:50:03,438 INFO  [debezium-postgresconnector-RW_CDC_1020-change-event-source-coordinator] postgresql.PostgresSchema:103 - REPLICA IDENTITY for 'public.order_line' is 'DEFAULT'; UPDATE and DELETE events will contain previous values only for PK columns |  
>   | 2023-12-07 07:50:03,439 INFO  [debezium-postgresconnector-RW_CDC_1020-change-event-source-coordinator] pipeline.ChangeEventSourceCoordinator:173 - Starting streaming
> ```
> 
> And I notice that the read performance of hummock for the `order_line` table (id=1019) is quite bad compared to a the `stock` (id=1022) table which is ingested much faster. The mview executor need to do a `get` to handle conflict. <img alt="image" width="768" src="https://private-user-images.githubusercontent.com/7338536/288944443-6d975772-3dc8-4cad-871e-5a545222a6f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDM1MTYsIm5iZiI6MTcwMjAwMzIxNiwicGF0aCI6Ii83MzM4NTM2LzI4ODk0NDQ0My02ZDk3NTc3Mi0zZGM4LTRjYWQtODcxZS01YTU0NTIyMmE2ZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDhUMDI0MDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWU2OTgwYTg2NmVkNTE5ODVkNjQ1Nzc0ZmQ2OGM4MzNiOWRmYjc0NGNiZjMwYjk2NDI3YjM2OTJlMDFlNDIwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sxxoIN94f54ndUF9UnnfGkKKdObmXvsOUI78Sq-CX3I">
> 
> Also the read ops of S3 is about 3K/s, which is abnormal. So I think the reason of slow performance of `orders_line` is probably bounded by the slow read of hummock. @hzxa21 Could you please take a look of hummock performance?
> 
> <img alt="image" width="861" src="https://private-user-images.githubusercontent.com/7338536/288943991-323e0c34-73e0-46c1-9832-5abed4ace793.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDM1MTYsIm5iZiI6MTcwMjAwMzIxNiwicGF0aCI6Ii83MzM4NTM2LzI4ODk0Mzk5MS0zMjNlMGMzNC03M2UwLTQ2YzEtOTgzMi01YWJlZDRhY2U3OTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDhUMDI0MDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODI2NTMxYjUyZDczMmQ3NTAxMTQ3ZGExNzQ4ZjYzMmIzOGU3MThmNjFjNDM0M2QxY2FkMDQyOGQzMjMxYWQ1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-X_xdjGkMy7dvX8C_fbvWIp3QLu3ai8BVqP2xbUrUDU">

The read comes from hash join (all the tables shown below are hash join stat table). There are block cache misses as well but it can be due to CN pod restart upon image update.
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/b2f0bab9-91fe-4e5a-a414-3693adab0daa)
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/66770c01-f527-4584-80ac-afcb86a93110)



However, I don't see any suspicious thing and I am suspecting this is an expected behavior. Can we try running the same workload without the upgrade to see how good it can be?

**Comment by hzxa21** [comment]
Also I found in the log that the memory allocated for storage and compute are smaller in 1.5 than 1.4. Not sure whether it can be a contributing factor:

Before:
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/6b3747d8-f787-486d-a35f-75a42add74fa)

After:
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/0c065ba5-3551-4d13-834e-e69b363d8cde)

**Comment by cyliu0** [comment]
Running with 280 warehouses in https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/111

**Comment by StrikeW** [comment]
This is not an issue introduced by upgrade, see [link](https://risingwave-labs.slack.com/archives/C03KED89H88/p1702015819713209?thread_ts=1701327951.764949&cid=C03KED89H88) for detail.
