### ISSUE TITLE
Meta node panics when insert unsupported type data in Elasticsearch-sink

### ISSUE THREAD

**Issue by xuefengze** [risingwavelabs/risingwave#13866]
### Describe the bug

In out implement [StreamChunkDeserializer.java](https://github.com/risingwavelabs/risingwave/blob/main/java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/deserializer/StreamChunkDeserializer.java#L179), `array` only support `int16`, `int32`, `int64`, `float`, `double`, `varchar` type. 
However, when an unsupported type is inserted, the meta node will panic.

### Error message/log

```text
thread 'risingwave-main' panicked at src/meta/src/barrier/mod.rs:1049:13:
failed to execute barrier: gRPC request to stream service failed: Internal error: Actor 10 exited unexpectedly: Executor error: Sink error: Remote sink error: INVALID_ARGUMENT: stream_chunk: unsupported array with field type BYTEA

[risedev]: Program exited with 134
```

### To Reproduce

```sql
Create table es_types (
    types_id INT, 
    arr bytea[], 
    PRIMARY KEY (types_id)
);
INSERT INTO es_types values (1, array[]::bytea[]);

CREATE SINK es_sink
FROM
    es_types WITH (
    connector = 'elasticsearch',
    index = 'test',
    url = 'http://elasticsearch:9200',
    username = 'elastic',
    password = 'risingwave'
);
```

### How did you deploy RisingWave?

cargo make ci-start ci-1cn-1fe

**Comment by wangrunji0408** [comment]
Seems related to #13865 . Both were caused by sink and panicked at the same location.

**Comment by BugenZhao** [comment]
Just a friendly reminder: panicking here is expected if recovery is disabled. Perhaps we should consider improving the message.

**Comment by wangrunji0408** [comment]
Humm but it sounds not cool that a sink error eventually results in kernel panic. It should report this error somewhere and drop the sink. Do we plan to improve the error handling and avoid trigger recovery? 🤔

**Comment by BugenZhao** [comment]
> Humm but it sounds not cool that a sink error eventually results in kernel panic. 

You're right. It would be better if we can directly reject the streaming job when creating.

In production, this won't panic but lead to a recovery loop. Users have to drop the sink manually with SQL interface in this case.

**Comment by xuefengze** [comment]
Closed by https://github.com/risingwavelabs/risingwave/pull/14231
