### ISSUE TITLE
Enable CI test for memtable spill and EpochWithGap

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#13884]
We added feature `enable_test_epoch` to avoid changing existing test cases after introducing `EpochWithGap` for memtable spill. This not only makes unit test but also e2e test and simulation test not testing the EpochWIthGap with spilled offset. In this case, we will miss some obvious bugs like #13882.

I suggest we remove the usage of feature `enable_test_epoch` and enable all tests to use the real EpochWithGap. Though it is cumbersome to modify existing test cases, I think it is still worthwhile to do so. Looking for better ideas as well.

**Comment by wcy-fdu** [comment]
All random epochs in unit test need to be corrected, which may be a bit troublesome and requires a lot of work.
Let's think about whether there are other workarounds. If not, we can only change it. The owner of UT may be required to participate.

**Comment by wcy-fdu** [comment]
Can we just remove this debug assert as current usage is relatively clear?

**Comment by hzxa21** [comment]
> Can we just remove this debug assert as current usage is relatively clear?

What do you mean? The issue is not about the debug_assert but about low coverage on the release build with the real `EpochWithGap` being used. Removing the debug_assert may make things worse because bugs like #13882 can happen silently.

**Comment by wcy-fdu** [comment]
> > Can we just remove this debug assert as current usage is relatively clear?
> 
> What do you mean? The issue is not about the debug_assert but about low coverage on the release build with the real `EpochWithGap` being used. Removing the debug_assert may make things worse because bugs like #13882 can happen silently.

Oh, I misunderstood, you can ignore this comment.
