### ISSUE TITLE
Bug:  build_actors panic -- backward compatibility 

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#13883]
### Describe the bug

stderr F called `Option::unwrap()` on a `None` value 

thread 'risingwave-main' panicked at /risingwave/src/stream/src/task/stream_manager.rs:670:59:

Related #13702

**Comment by hzxa21** [comment]
Another relevant PR #13456 is in the 1.5-rc branch. Will that break backward-compat as well?

**Comment by kwannoel** [comment]
https://buildkite.com/risingwavelabs/main-cron/builds/1295#018c4a29-c812-49a1-8a81-22487ff9cc1e
