### ISSUE TITLE
Support all kinds of iceberg catalog.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#13900]

**Comment by thexiay** [comment]
Could you add more description and i think i can handle this issue.😕

**Comment by liurenjie1024** [comment]
> Could you add more description and i think i can handle this issue.😕@liurenjie1024

Hi, @thexiay Thanks for you interest, I've already started working on this. Feel free to pick other `good first issue`

**Comment by thexiay** [comment]
> > Could you add more description and i think i can handle this issue.😕@liurenjie1024
> 
> Hi, @thexiay Thanks for you interest, I've already started working on this. Feel free to pick other `good first issue`

fine.
