### ISSUE TITLE
The total_memory_bytes of cn displayed in meta is not the cn config total_memory_bytes 

### ISSUE THREAD

**Issue by yuhao-su** [risingwavelabs/risingwave#13927]
### Describe the bug

https://github.com/risingwavelabs/risingwave/blob/19f4254921c66bf83b9ceb2ba6f5a9d5f31c939a/src/rpc_client/src/meta_client.rs#L253

It uses the cn host memory limit

**Comment by fuyufjh** [comment]
Ping?

**Comment by yuhao-su** [comment]
It's means to aim at getting the host resources. What will this information used for? Anyway we can tell users it's host resources instead of system config? cc @yezizp2012 @zwang28

**Comment by zwang28** [comment]
> It's means to aim at getting the host resources. What will this information used for?

`system_memory_available_bytes()` is the one related to OOM, while `total_memory_bytes of cn` can be set arbitrarily.
