### ISSUE TITLE
14 nexmark benchmark skus performance degradation

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#13931]
### Describe the bug

```
+-----------------------------------------------------------------+--------------+------------+---------------------+-----------------------------+
| BENCHMARK NAME                                                  | EXECUTION ID | STATUS     | FLUCTUATION OF BEST | FLUCTUATION OF LAST 10 DAYS |
+-----------------------------------------------------------------+--------------+------------+---------------------+-----------------------------+
| nexmark-q18-blackhole-medium-1cn                                |        16377 | Negative   | -23.47%             | -11.33%                     |
| nexmark-q8-blackhole-watermark-medium-1cn-affinity              |        16381 | Negative   | -23.73%             | -13.39%                     |
| nexmark-q19-blackhole-medium-1cn                                |        16382 | Negative   | -30.59%             | -25.84%                     |
| nexmark-q9-blackhole-watermark-medium-1cn-affinity              |        16386 | Negative   | -22.56%             | -13.23%                     |
| nexmark-q20-blackhole-medium-1cn                                |        16389 | Negative   | -19.53%             | -12.72%                     |
| nexmark-q18-blackhole-watermark-medium-1cn-affinity             |        16392 | Negative   | -20.35%             | -13.29%                     |
| nexmark-q101-blackhole-medium-1cn                               |        16394 | Negative   | -21.85%             | -14.95%                     |
| nexmark-q6-group-top1-blackhole-watermark-medium-1cn-affinity   |        16397 | Negative   | -23.22%             | -10.88%                     |
| nexmark-q5-many-windows-blackhole-watermark-medium-1cn-affinity |        16403 | Negative   | -38.80%             | -18.74%                     |
| nexmark-q103-blackhole-medium-1cn                               |        16404 | Negative   | -16.32%             | -11.45%                     |
| nexmark-q104-blackhole-medium-1cn                               |        16409 | Negative   | -23.97%             | -15.64%                     |
| nexmark-q5-many-windows-blackhole-medium-1cn                    |        16412 | Negative   | -49.41%             | -14.18%                     |
| nexmark-q105-blackhole-medium-1cn                               |        16413 | Negative   | -22.20%             | -14.24%                     |
| nexmark-q5-many-windows-blackhole-medium-1cn-affinity           |        16414 | Negative   | -50.40%             | -15.86%                     |
```

### The version of RisingWave

nightly-20231211

### Additional context

Please find the commit history here: https://github.com/risingwavelabs/rw-commits-history#commit-history

52632ae065921fd9219d9a15f8a11e03f69e42c0 https://github.com/risingwavelabs/risingwave/pull/13926
ad2073fb2e88b6e1dbd91e6c1f79f184ca732ab2 https://github.com/risingwavelabs/risingwave/pull/13925
1d4cac8fd1b82be801887cefd733226a10cf2c57 https://github.com/risingwavelabs/risingwave/pull/13921
2fffc1315bb08d7bab5b03095e8beb68e8c54982 https://github.com/risingwavelabs/risingwave/pull/13558
7c77553a4d41e2e4e8015bb98af0b66d81933f63 https://github.com/risingwavelabs/risingwave/pull/13769
98b0ebdca8266a1c32a30a34f48dd74d448fee00 https://github.com/risingwavelabs/risingwave/pull/13491
ccf8be58c37737d77a8ac061a58d43f9a5070afa https://github.com/risingwavelabs/risingwave/pull/13870
7b410c01c84821519ec140d12f2ec637610f9e82 https://github.com/risingwavelabs/risingwave/pull/13853
c3e21a8be93ce84624df26b122c955ec226abe5d https://github.com/risingwavelabs/risingwave/pull/13915
92f3b5850d8b4814bf2243c2145c1c32fd1696ec https://github.com/risingwavelabs/risingwave/pull/13862
c8d351b81458507fe31e3ce86b8fce87284370ca https://github.com/risingwavelabs/risingwave/pull/13909
fb1bf0a5ba8c40aa631e645eb2949b3ab2f61030 https://github.com/risingwavelabs/risingwave/pull/13525
4d525e2b95359607f025bca5dd6ff918d6cdbbc9 https://github.com/risingwavelabs/risingwave/pull/13901
a3c71aa388eeccd5ee5a61a5240c9421c9e932e7 https://github.com/risingwavelabs/risingwave/pull/13854
d270f10d43d3f87af3afe4d6ef35ed7075b1c7f5 https://github.com/risingwavelabs/risingwave/pull/13692
ddbd74b75f985d219bac0c8ac2722bf74b866933 https://github.com/risingwavelabs/risingwave/pull/13877
5d7f3276ffd83714de4b75cd7cab9fc515d85669 https://github.com/risingwavelabs/risingwave/pull/13849
e513e6b894add9c71b4f41050678bd400dcadf9f https://github.com/risingwavelabs/risingwave/pull/13881

![SCR-20231212-kzt](https://github.com/risingwavelabs/risingwave/assets/5791930/6491de5e-54d0-46cd-99ac-6852e82b06d5)

**Comment by cyliu0** [comment]
And the sysbench prepare job failed to check completion in 5 retries with an interval of 60 seconds. So I think there might be insertion performance as well on `nightly-20231211`. But the prepare finished on time with same configuration when running on `nightly-20231210`
https://buildkite.com/risingwave-test/sysbench/builds/620#018c5aaf-b799-4cd2-9e4e-d2b89cd4b7e0

**Comment by cyliu0** [comment]
For backfill test, it was failed to create watermark mv for 1h timeout on `nightly-20231211`. https://buildkite.com/risingwave-test/backfill/builds/72#018c5b1d-515e-49ac-aedf-4da032ee503f
```
  | 2023-12-12 07:26:13 | create watermark mv for backfill table
  | 2023-12-12 07:26:13 | Timing is on.
  | 2023-12-12 08:26:11 | ❌ backfill test timeout
```

The backfill test step for creating watermark mv succeed on `nightly-20231210` in 2 minutes
```
  | 2023-12-09 07:25:54 | create watermark mv for backfill table
  | 2023-12-09 07:25:54 | Timing is on.
  | 2023-12-09 07:27:35 | NOTICE:  Your session timezone is UTC. It was used in the interpretation of timestamps and dates in your query. If this is unintended, change your timezone to match that of your data's with `set timezone = [timezone]` or rewrite your query with an explicit timezone conversion, e.g. with `AT TIME ZONE`.
  | 2023-12-09 07:27:35 | CREATE_MATERIALIZED_VIEW
  | 2023-12-09 07:27:35 | Time: 103637.007 ms (01:43.637)
```

**Comment by kwannoel** [comment]
Starting a new flamegraph job for nexmark: https://buildkite.com/risingwavelabs/cpu-flamegraph-weekly-cron/builds/56

Can compare against sunday: https://buildkite.com/risingwavelabs/cpu-flamegraph-weekly-cron/builds/55

**Comment by lmatz** [comment]
From the commit history, it looks like only https://github.com/risingwavelabs/risingwave/pull/13558 is possible to affect the performance, cc: @Little-Wallace , do you think the PR is possible to introduce such a big change?

**Comment by st1page** [comment]
q19 1210:
<img width="843" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/40830455/acced180-50ee-46c9-84cc-a1a85d0f6f58">
https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1702233594000&to=1702235397000&var-namespace=nexmark-bs-15-105-daily-20231210
q19 1211:

<img width="850" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/40830455/4eb9320a-818b-4122-88c2-23542de96b27">

https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1702319995000&to=1702321799000&var-namespace=nexmark-bs-15-105-daily-20231211

**Comment by st1page** [comment]
looks like the memory usage of some component increase and the executor cache evicts more

<img width="846" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/40830455/6fc1fc2b-efa4-46f8-beb1-3beae98b4e23">

<img width="847" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/40830455/6dd666d0-6a0c-47db-af64-62f524b5f8ee">

<img width="847" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/40830455/998900a4-b400-423f-a79f-a9a209379e94">

**Comment by st1page** [comment]
For q20, no spike, just 400000 vs 340000 rows/s the create_iter_p99 is different. do not sure if it is related.

q20 1210:  
https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1702235615000&orgId=1&to=1702237419000&var-datasource=Prometheus%3A+test-useast1-eks-a&var-namespace=nexmark-bs-15-105-daily-20231210

<img width="856" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/40830455/a8637e86-83f9-43c4-9344-402fca8ed5f9">


<img width="851" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/40830455/581b9420-d280-4b17-a846-bc7bce6253ab">

q20 1211:
https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1702322018000&orgId=1&to=1702323822000&var-datasource=Prometheus%3A+test-useast1-eks-a&var-namespace=nexmark-bs-15-105-daily-20231211

<img width="841" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/40830455/2c6f6a38-2172-412e-817d-962b3271ec10">


<img width="848" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/40830455/82d2b34f-7f1b-4990-a649-1236fdce734d">

**Comment by st1page** [comment]
> From the commit history, it looks like only #13558 is possible to affect the performance, cc: @Little-Wallace , do you think the PR is possible to introduce such a big change?

run the queries before #13558
https://buildkite.com/risingwave-test/nexmark-benchmark/builds/2660#018c5da3-654f-4867-ad3e-2931f0aa82c2

(build the image in a seperate branch, to include the fix https://github.com/risingwavelabs/risingwave/pull/13925 ) https://buildkite.com/risingwavelabs/docker/builds/14875#018c5d85-6b70-4b1f-b4f7-8adc4b4c655a

**Comment by st1page** [comment]
> | nexmark-q5-many-windows-blackhole-medium-1cn                    |        16412 | Negative   | -49.41%             | -14.18%                     

This is because the revert in https://github.com/risingwavelabs/risingwave/issues/13821

<img width="1181" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/40830455/9fd03b4b-d250-4eaa-acb8-23302a24ff4c">

**Comment by cyliu0** [comment]
For nightly-20231212
```
+-----------------------------------------------------------------+--------------+------------+---------------------+-----------------------------+
| BENCHMARK NAME                                                  | EXECUTION ID | STATUS     | FLUCTUATION OF BEST | FLUCTUATION OF LAST 10 DAYS |
+-----------------------------------------------------------------+--------------+------------+---------------------+-----------------------------+
| nexmark-q18-blackhole-medium-1cn                                |        16450 | Negative   | -24.54%             | -10.97%                     |
| nexmark-q5-many-windows-blackhole-medium-1cn                    |        16488 | Negative   | -52.12%             | -16.54%                     |
```

**Comment by st1page** [comment]
> > From the commit history, it looks like only #13558 is possible to affect the performance, cc: @Little-Wallace , do you think the PR is possible to introduce such a big change?
> 
> run the queries before #13558 ~~https://buildkite.com/risingwave-test/nexmark-benchmark/builds/2660#018c5da3-654f-4867-ad3e-2931f0aa82c2~~(wrong affinity) https://buildkite.com/risingwave-test/nexmark-benchmark/builds/2662#018c5eba-37f7-469e-8d17-20f3ef206bb8
> 
> (build the image in a seperate branch, to include the fix #13925 ) https://buildkite.com/risingwavelabs/docker/builds/14875#018c5d85-6b70-4b1f-b4f7-8adc4b4c655a

 It has a similar performance with the 1210

**Comment by st1page** [comment]
> For nightly-20231212
> 
> ```
> +-----------------------------------------------------------------+--------------+------------+---------------------+-----------------------------+
> | BENCHMARK NAME                                                  | EXECUTION ID | STATUS     | FLUCTUATION OF BEST | FLUCTUATION OF LAST 10 DAYS |
> +-----------------------------------------------------------------+--------------+------------+---------------------+-----------------------------+
> | nexmark-q18-blackhole-medium-1cn                                |        16450 | Negative   | -24.54%             | -10.97%                     |
> | nexmark-q5-many-windows-blackhole-medium-1cn                    |        16488 | Negative   | -52.12%             | -16.54%                     |
> ```

🤔 I rerun the 20231211 to see if the degradation can be reproduced
https://buildkite.com/risingwave-test/nexmark-benchmark/builds/2670

**Comment by st1page** [comment]
> > For nightly-20231212
> > ```
> > +-----------------------------------------------------------------+--------------+------------+---------------------+-----------------------------+
> > | BENCHMARK NAME                                                  | EXECUTION ID | STATUS     | FLUCTUATION OF BEST | FLUCTUATION OF LAST 10 DAYS |
> > +-----------------------------------------------------------------+--------------+------------+---------------------+-----------------------------+
> > | nexmark-q18-blackhole-medium-1cn                                |        16450 | Negative   | -24.54%             | -10.97%                     |
> > | nexmark-q5-many-windows-blackhole-medium-1cn                    |        16488 | Negative   | -52.12%             | -16.54%                     |
> > ```
> 
> 🤔 I rerun the 20231211 to see if the degradation can be reproduced https://buildkite.com/risingwave-test/nexmark-benchmark/builds/2670

q18 and q20 good, q19 bad :innocent: So the issue can not be reproduced stably.
