### ISSUE TITLE
failed to parse json message from source

### ISSUE THREAD

**Issue by caohb1985** [risingwavelabs/risingwave#13937]
### Describe the bug

```
2023-12-12T06:41:59.771086181Z ERROR actor{otel.name="Actor 1190" actor_id=1190 prev_epoch=5578951995162624 curr_epoch=5578952055324672}:executor{otel.name="DmlExecutor 4A600000001 (actor 1190)" actor_id=1190}:executor{otel.name="FlowControlExecutor (actor 1190)" actor_id=1190}:source_parser{actor_id=1190 source_id=2035}: risingwave_connector::parser: failed to parse message, skipping error=Protocol error: InternalError(TapeError) at character 0 ('S') split_id="0" offset="1564766"
```

**Comment by lmatz** [comment]
May I ask what is the raw data?

**Comment by caohb1985** [comment]
{
  "after": {
    "abnormalInfo": "{}",
    "agentId": "",
    "classId": "CLASS20231109010000000009",
    "classtypeId": "CLASSTYPE20231109000000000002",
    "corpId": "",
    "ctapId": "CTAP20231109000000000002",
    "dcTime": "2023-12-12 17:56:58",
    "groupEnums": "",
    "groupExists": "N",
    "isAbnormal": 2,
    "isPhysicsDel": 2,
    "projectId": "PROJECT20191126010000000272",
    "remainServiceCount": "",
    "serviceCount": "1",
    "studentId": "STUDENT20211020800000000023",
    "studentclassBizsrcid": "1184071315274280960",
    "studentclassBizsrctype": "O",
    "studentclassBusinesstype": "I",
    "studentclassCategory": "GEN",
    "studentclassCoownerid": "USER20200409010000005776",
    "studentclassCreateddate": "2023-12-12 17:56:57",
    "studentclassCrossproject": "N",
    "studentclassExpiredate": "2024-11-30 23:59:59",
    "studentclassGift": "N",
    "studentclassGoodsstatus": "N",
    "studentclassId": "STUDENTCLASS20231212810000000012",
    "studentclassModifieddate": "2023-12-12 17:56:58",
    "studentclassMulpdstatus": "M",
    "studentclassOpendate": "2000-01-01 00:00:00",
    "studentclassOpenstatus": "P",
    "studentclassOrderno": "ZC2023121217564054234991",
    "studentclassOrdersource": "OP",
    "studentclassOrdertype": "",
    "studentclassPrice": 6700,
    "studentclassSertype": "B",
    "studentclassServicestatus": "Y",
    "studentclassSourceid": "7dbf725a-9f78-47e2-bfea-0b7feef3e514",
    "studentclassStatus": "GEND",
    "studentclassType": "CG",
    "studentclassYear": "2023",
    "userId": "USER20211020700000000017"
  },
  "before": {
    "agentId": null,
    "classId": "CLASS20231109010000000009",
    "classtypeId": "CLASSTYPE20231109000000000002",
    "corpId": null,
    "ctapId": "CTAP20231109000000000002",
    "groupEnums": null,
    "groupExists": "N",
    "projectId": "PROJECT20191126010000000272",
    "remainServiceCount": null,
    "serviceCount": "1",
    "studentId": "STUDENT20211020800000000023",
    "studentclassBizsrcid": "1184071315274280960",
    "studentclassBizsrctype": "O",
    "studentclassBusinesstype": "I",
    "studentclassCategory": "GEN",
    "studentclassCoownerid": "USER20200409010000005776",
    "studentclassCreateddate": "2023-12-12 17:56:57",
    "studentclassCrossproject": "N",
    "studentclassExpiredate": "2024-11-30 23:59:59",
    "studentclassGift": "N",
    "studentclassGoodsstatus": "N",
    "studentclassId": "STUDENTCLASS20231212810000000012",
    "studentclassModifieddate": "2023-12-12 17:56:57",
    "studentclassMulpdstatus": "M",
    "studentclassOpendate": null,
    "studentclassOpenstatus": "P",
    "studentclassOrderno": "ZC2023121217564054234991",
    "studentclassOrdersource": "OP",
    "studentclassOrdertype": null,
    "studentclassPrice": 6700,
    "studentclassSertype": "B",
    "studentclassServicestatus": null,
    "studentclassSourceid": "7dbf725a-9f78-47e2-bfea-0b7feef3e514",
    "studentclassStatus": "GEND",
    "studentclassType": "CG",
    "studentclassYear": "2023",
    "userId": "USER20211020700000000017"
  },
  "op": "u",
  "source": {
    "connector": "mysql",
    "db": "studentservice",
    "dbAlias": "studentservice",
    "file": "mysql-bin.005103",
    "gtid": "b6772431-061f-11ea-8208-000c29292114:1571302988",
    "layerName": "ss",
    "name": "mysql_binlog_source",
    "pos": 286377,
    "primaryKey": "studentclassId",
    "query": null,
    "row": 0,
    "sequence": null,
    "server_id": 2033306,
    "shortName": "dwd",
    "snapshot": "false",
    "table": "BdStudentclass",
    "targetDbName": "datawarehouse",
    "thread": null,
    "ts_ms": 1702375018000,
    "version": "1.6.4.Final"
  },
  "transaction": null,
  "ts_ms": 1702375018473
}

**Comment by xiangjinwu** [comment]
Thanks for sharing the details.
```
InternalError(TapeError) at character 0 ('S')
```
This error is from json parser (simd-json), which attempts to match the 0th character against `{` (object), `[` (array), `t`/`f` (boolean), `n` (null), `"` (string) or `-`/`0`..`9`, but actually encounter `S`.

I have confirmed the message above can be parsed by `simd-json`, which is also obvious because it starts with `{` rather than `S`.

Is this happening to just some of the messages, or all of the messages?

You may be able to locate the specific ill-formed message with the help of this info:
```
split_id="0" offset="1564766"
```

Alternatively, you could also ingest the data without parsing to locate the ill-formed message:
```
create source foo (raw bytea) with (connector = 'kafka', properties.bootstrap.server = 'bar', topic = 'baz') format plain encode bytes;
select encode(raw, 'escape') from foo where substr(raw, 1, 1) = 'S'; 
```

**Comment by caohb1985** [comment]
select encode(raw, 'escape') from foo where substr(raw, 1, 1) = 'S';     can not query anything.

**Comment by fuyufjh** [comment]
Hi, @caohb1985 any further updates?

**Comment by kwannoel** [comment]
Add another case for discoverability:
```
InternalError(TapeError) at character 123 ('N')
```

Which happens when user passes in something like:
```
a: 'NaN'
```

Instead of a number, when the schema expects a `numeric` value.
