### ISSUE TITLE
bug: LabelGuardedCounter metrics report incorrect value 

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#13948]
### Describe the bug

Related https://github.com/risingwavelabs/risingwave/pull/13080

![Screenshot 2023-12-12 at 20 04 00](https://github.com/risingwavelabs/risingwave/assets/10192522/d0c5e576-6d29-4061-8ef4-4e21ef0e8917)

### The version of RisingWave

main

**Comment by hzxa21** [comment]
cc @wenym1

**Comment by wenym1** [comment]
Is there any query to reproduce the bug?

**Comment by fuyufjh** [comment]
> Is there any query to reproduce the bug?

Try this:

```
CREATE TABLE t1 (k int, v1 struct<v2 int, v3 double>, t1 timestamp, c1 varchar) 
WITH (
     connector = 'datagen',
  
     fields.k.kind = 'sequence',
     fields.k.start = '1',
  
     fields.v1.v2.kind = 'random',
     fields.v1.v2.min = '-10',
     fields.v1.v2.max = '10',
     fields.v1.v2.seed = '1',
  
     fields.v1.v3.kind = 'random',
     fields.v1.v3.min = '15',
     fields.v1.v3.max = '55',
     fields.v1.v3.seed = '1',
  
     fields.t1.kind = 'random',
     fields.t1.max_past = '2h 37min',
     fields.t1.max_past_mode = 'relative',
     fields.t1.seed = '3',

     fields.z1.kind = 'random',
     fields.z1.max_past = '2h 37min',
     fields.z1.max_past_mode = 'relative',
     fields.z1.seed = '3',

     fields.c1.kind = 'random',
     fields.c1.length = '16',
     fields.c1.seed = '3',
  
     datagen.rows.per.second = '10'
 ) FORMAT PLAIN ENCODE JSON;


create materialized view mv1 as select (v1).v2, count(k) from t1 group by 1;
```

**Comment by fuyufjh** [comment]
I am suspecting

https://github.com/risingwavelabs/risingwave/blob/71f08edcef1b42c27c1faac4933c269da6027a79/src/common/src/metrics/guarded_metrics.rs#L189

might incorrectly deleted metrics from the inner Counter, thus, some `inc_by()` was actually lost.

Didn't fully understand the logic around `uncollected_removed_labels`...

**Comment by wenym1** [comment]
> I am suspecting
> 
> [risingwave/src/common/src/metrics/guarded_metrics.rs](https://github.com/risingwavelabs/risingwave/blob/e8f4a8a0841dddd5b3069182095d50da3f94304b/src/common/src/metrics/guarded_metrics.rs#L189)
> 
> Line 189 in [e8f4a8a](https://github.com/risingwavelabs/risingwave/commit/e8f4a8a0841dddd5b3069182095d50da3f94304b)
> 
>  .remove_label_values(&labels.each_ref().map(|s| s.as_str())) 
> might incorrectly deleted metrics from the inner Counter, thus, some inc_by() was actually lost.
> 
> Didn't fully understand the logic around uncollected_removed_labels...

The logic before using `uncollected_removed_labels` is, when the label is not used anywhere, we call remove_label_values on the unused label immediately, which may cause a loss of metrics because the label is removed before being collected. 

After introducing `uncollected_removed_labels`, the unused label will be first added to this list, and on `collect`, we first call `inner.collect()` to collect metric of all labels, and then we call remove_label_values to really remove the label. In this way, we can avoid losing the metrics.
