### ISSUE TITLE
Discussion: make `The size of mem table is 4 Mb and it exceeds 4 Mb and spill occurs.` log not INFO

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#13942]
Under intensive workload, this message gets logged a lot.
Wonder if we should make it `WARN` or `DEBUG`?

![SCR-20231212-n2k](https://github.com/risingwavelabs/risingwave/assets/5791930/ab0032f6-0ad5-45c0-8f77-75b3ddce889f)

**Comment by hzxa21** [comment]
I think we can make it a debug log given that we have grafana metric already.

**Comment by lmatz** [comment]
![SCR-20231213-l41](https://github.com/risingwavelabs/risingwave/assets/5791930/96e75e29-53e7-49f4-ade1-d665322f0bf0)


Is it suitable to make this log also debug?

**Comment by hzxa21** [comment]
> ![SCR-20231213-l41](https://private-user-images.githubusercontent.com/5791930/290105259-96e75e29-53e7-49f4-ade1-d665322f0bf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTI0NTAsIm5iZiI6MTcwMjQ1MjE1MCwicGF0aCI6Ii81NzkxOTMwLzI5MDEwNTI1OS05NmU3NWUyOS01M2U3LTQ5ZjQtYWRlMS1kNjY1MzIyZjBiZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDcyMjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWEzZWY3YTYwODRjODMyNzdiNTU3YWYxZWE1YzhiZWI5ZGUyYzZlOGI5NTBhZjk0ZDkxMzA2OWRlODhmODQ1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3HjPez_tzo5JmmzURQUzh8y8cXK3sVNgAukAEHK9pdw)
> 
> Is it suitable to make this log also debug?

This log will only be printed when there are new state tables created. I think it is not a high-frequency operation so that is why I didn't change it before. However, I have no objection in changing it to debug because it doesn't give useful information anyway.

**Comment by wcy-fdu** [comment]
I have removed this log in https://github.com/risingwavelabs/risingwave/pull/13833 as we can monitor spill metrics, seems not included in v1.5?

**Comment by lmatz** [comment]
> I have removed this log in https://github.com/risingwavelabs/risingwave/pull/13833 as we can monitor spill metrics, seems not included in v1.5?

true, I just searched code and found nothing, thanks!
