### ISSUE TITLE
Discussion: avoid periodical logs

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#13953]
> BTW that line is unpin snapshot with RPC. It's normal for an idle cluster to only have this log.

From my perspective, in production we should never include logs that are triggered automatically and periodically, unless they're user-facing. Also applies to the `DEBUG` logs in hummock event handler.

_Originally posted by @BugenZhao in https://github.com/risingwavelabs/risingwave/issues/12610#issuecomment-1752311968_
            

These seems verbose even for developers.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/37948597/289910702-9a6127da-4904-4081-8abd-4f67a3a787cd.png">

**Comment by fuyufjh** [comment]
+1. Previously I opened such an issue but nobody cares 🥹


https://github.com/risingwavelabs/risingwave/issues/7872
