### ISSUE TITLE
Hard to debug in standalone mode due to logs of different components being in the same file

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#13988]
> use standalone mode.
> 
> We will recommend users to use standalone mode by default once it is integrated into the test pipelines and we found no problem

@lmatz After change the integration pipeline to use standalone mode, all logs printed by different components (cn, compactor, etc) are interleaved. And we cannot easily grep by component name, since there is no component name prefix in the log, only crate prefix. That makes it hard to analyze the failed test case.

So what about change the docker-compose.yml of integration test to inherit from `docker-compose-distributed.yml` instead of `docker-compose.yml`.

_Originally posted by @StrikeW in https://github.com/risingwavelabs/risingwave/issues/13235#issuecomment-1855070293_

**Comment by kwannoel** [comment]
Hmm isn't crate prefix mostly sufficient (`risingwave_meta`, `risingwave_stream`, etc...)? Could you share some examples @StrikeW ?

**Comment by StrikeW** [comment]
IMO the extent of interleave depends on the workload. In the integration test scenario, workload is usually light, so it is still acceptable. But if we run complex workload e.g. [ch-benchmark](https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/112), I think it would be hard to analyze issue specific to a component.

**Comment by kwannoel** [comment]
> Some crates are shared by multiple components. IMO the extent of interleave depends on the workload. In the integration test scenario, workload is usually light, so it is still acceptable. But if we run complex workload e.g. [ch-benchmark](https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/112), I think it would be hard to analyze issue specific to a component.

What I'm thinking is if the solution can be as simple as providing a script or tool to partition the logs by crate.

**Comment by BugenZhao** [comment]
IIRC, most of our workloads run under their specific runtimes, where the custom thread names are set.

https://github.com/risingwavelabs/risingwave/blob/9dcad747a462f9dd1df571f8812ffa5f36596197/src/stream/src/task/stream_manager.rs#L424-L434

Do you think including the thread name in the logs will help?

https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/format/struct.Format.html#method.with_thread_names

**Comment by StrikeW** [comment]
> Do you think including the thread name in the logs will help?

This one seems better to me.

Do we will use standalone on the cloud? I am not sure whether the plugin can collect the logs belonging to different components with the above solutions.

**Comment by lmatz** [comment]
> Do we will use standalone on the cloud? 

Yes, for dev tier

**Comment by fuyufjh** [comment]
Closed by https://github.com/risingwavelabs/risingwave/pull/14114
