### ISSUE TITLE
Sink: elasticsearch sink get error with `decimal` type

### ISSUE THREAD

**Issue by xuefengze** [risingwavelabs/risingwave#13992]
### Describe the bug

When creating an `ES sink` with `decimal` type data as shown below, error messages appear in the log, but the sink is successfully created and we can see the expected data in ES. 
However, if we try to create two ES sinks(one is es7, and the other is es8) at the same time, the second creation will fail. But, trying to create the second sink again will succeed.

### Error message/log

```text
sink writer error: io.grpc.StatusRuntimeException: INTERNAL: Error message Es writer error: Bulk of 1 actions failed. Failure: failure in bulk execution:
[0]: index [test_types], type [doc], id [1], message [ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=mapper [c_decimal] cannot be changed from type [float] to [long]]]]
```

### To Reproduce

```sql
CREATE TABLE test (
  types_id INT,
  c_decimal decimal,
  PRIMARY KEY (types_id)
);

INSERT INTO test VALUES (1, 0);
INSERT INTO test VALUES (2, -10.001);

CREATE SINK types_sink
FROM
    test WITH (
    connector = 'elasticsearch',
    index = 'test',
    url = 'http://elasticsearch:9200/',
    username = 'elastic',
    password = 'risingwave'
);
```

### The version of RisingWave

risingwave:nightly-20231213

**Comment by xuefengze** [comment]
It seems that es will [dynamic detects data type](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html):
- `0` -> `long`
- `-10.001` -> `float`

Maybe we should create the index with an explicit mapping or add fields type to an existing index before write data?

**Comment by xxhZs** [comment]
> It seems that es will [dynamically detect data type](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html):
> 
> * `0` -> `long`
> * `-10.001` -> `float`
> 
> And Elasticsearch will create a mapping depending on the first document it indexes if not provide one. Maybe we should create the index with an explicit mapping or add fields type to an existing index before write data?
> 
> cc: @hzxa21 @xxhZs @xiangjinwu
> 
> update: I attempted to create the index with an explicit mapping. Despite setting the `INT32` type to the es `integer` type, an error still occurs: `cannot be changed from type [integer] to [long]]`. Regarding the `decimal` type, could we convert it to `text` to resolve this issue? It appears that es does not support the `decimal` type.

It does seem that decimal is not supported, is it possible to convert it to scaled_float to write to
https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html

**Comment by hzxa21** [comment]
> When creating an ES sink with decimal type data as shown below, error messages appear in the log, but the sink is successfully created and we can see the expected data in ES.

Does it mean the error message is just a warning and it won't skip any message?

> However, if we try to create two ES sinks(one is es7, and the other is es8) at the same time, the second creation will fail. But, trying to create the second sink again will succeed.

What do you mean by create two ES sinks at the same time? Do you mean you have two ES instances, one for es7 and one for es8?

**Comment by wenym1** [comment]
We have a rough plan to replace our current es sink implementation with the flink's es sink https://github.com/apache/flink-connector-elasticsearch

How does the flink's es sink handle this case? If it can correctly handle it, maybe we can prioritize the migration so that we don't have to reimplement the fix by ourselves.

**Comment by xxhZs** [comment]
> We have a rough plan to replace our current es sink implementation with the flink's es sink https://github.com/apache/flink-connector-elasticsearch
> 
> How does the flink's es sink handle this case? If it can correctly handle it, maybe we can prioritize the migration so that we don't have to reimplement the fix by ourselves.

Looking at the flink code it doesn't seem to do anything extra, then going to google it seems that flink has the same problem

**Comment by xuefengze** [comment]
> It does seem that decimal is not supported, is it possible to convert it to scaled_float to write to https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html

>`scaled_float` A floating point number that is backed by a `long`, scaled by a fixed double scaling factor.

rw `decimal`'s precision is 28 decimal digits. I  think `scaled_float` can't support it?

**Comment by xuefengze** [comment]
> Does it mean the error message is just a warning and it won't skip any message?

Yes, I can see both tuples of data in `es`.
 
> What do you mean by create two ES sinks at the same time? Do you mean you have two ES instances, one for es7 and one for es8?

same time: create two sinks with `-f` by SQL file, and the second command will fail. 
```sql
CREATE SINK types_sink
FROM
    test WITH (
    connector = 'elasticsearch',
    index = 'test1',
    url = 'http://elasticsearch:9200/',
    username = 'elastic',
    password = 'risingwave'
);

CREATE SINK types_sink
FROM
    test WITH (
    connector = 'elasticsearch',
    index = 'test2',
    url = 'http://elasticsearch:9200/',
    username = 'elastic',
    password = 'risingwave'
);
```

**Comment by xxhZs** [comment]
> Yes, I can see both tuples of data in es.

you mean we can find (1, 0) and (2, -10.001) in es?

**Comment by xuefengze** [comment]
> you mean we can find (1, 0) and (2, -10.001) in es?

Yes.
