### ISSUE TITLE
expr: don't fallback to evaluation by row on error

### ISSUE THREAD

**Issue by wangrunji0408** [risingwavelabs/risingwave#14027]
### Is your feature request related to a problem? Please describe.

Currently, the expression `eval` method will return an error immediately if any row of the data chunk returns an error. This is suitable for batch query. But in streaming, error should not break the stream, so now we have an `eval_infallible` which will fall back to evaluation by each row once `eval` returns an error.

There are 2 problems with this fallback strategy:
1. Evaluation by row is inefficient. Especially for UDFs where the overhead per RPC is significant.
2. Some kinds of errors are not caused by specific rows. A typical one is the UDF connection error. When an UDF server is unavailable, the fallback strategy is not only helpless, but also amplifies useless requests, causing the entire stream to be slow down.

### Describe the solution you'd like

I would like to propose a new `eval` API which returns errors also in a batch:
```rust
trait Expression {
    fn eval(&self, input: &DataChunk) -> Result<
        ArrayRef,               // if success
        (ArrayRef, EvalError)   // if fails, error rows are NULL in the array
    >;
}
```

and introduce a new variant in `ExprError` to collect multiple errors in batch evaluation:
```rust
pub enum ExprError {
    /// A collection of multiple errors in batch evaluation.
    #[error("multiple errors: {0}")]
    Multiple(Vec<ExprError>),
    ...
}
```

This API change requires all function implementations to be modified. Fortunately most of them are generated by the macro. So we only need to modify the code generation and a few special expressions.

### Describe alternatives you've considered

To quickly fix the error amplification issue in UDF, we can simply disable the row fallback i.e. remove the `NonStrict` wrapper for `UdfExpression`s.

### Additional context

cc @BugenZhao @TennyZhuang @yuhao-su

**Comment by fuyufjh** [comment]
I think the logic of "if the whole chunk fails, eval row by row" should be done on UDF Server side instead of RisingWave side.

**Comment by TennyZhuang** [comment]
Generally eval row by row is stupid. It’s just a workaround for our framework limitation. It’s meaningless to users.

**Comment by fuyufjh** [comment]
> Generally eval row by row is stupid

Perhaps it's inevitable for vectorized execution. What we can do is to optimize and hide it from users.

**Comment by wangrunji0408** [comment]
> I think the logic of "if the whole chunk fails, eval row by row" should be done on UDF Server side instead of RisingWave side.

Yes, the API I proposed should be applied to the entire call stack, including the UDF server. This means that the RPC protocol between the kernel and the UDF server also needs to be modified.

**Comment by TennyZhuang** [comment]
> > Generally eval row by row is stupid
> 
> Perhaps it's inevitable for vectorized execution. What we can do is to optimize and hide it from users.

Why it’s necessary? Vectorization engine also calculate the result one by one, but no need to box it into a datum.

We only need a flag during evaluation.
