### ISSUE TITLE
The sysbench select random limits performance is not stable

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#14022]
### Describe the bug

Received a performance degradation with nightly-20231217. The sysbench select random limits performance is not very stable after nightly-20231206.

```
+-----------------------------------------------------------------+--------------+------------+---------------------+-----------------------------+
| BENCHMARK NAME                                                  | EXECUTION ID | STATUS     | FLUCTUATION OF BEST | FLUCTUATION OF LAST 10 DAYS |
+-----------------------------------------------------------------+--------------+------------+---------------------+-----------------------------+
| sysbench-select-random-limits-medium-3cn                        |        16818 | Negative   | -39.61%             | -15.56%                     |
```

http://metabase.risingwave-cloud.xyz/dashboard/511-sysbench-select-random-limits-medium-3cn-history?start_date=2023-11-06&namespace=daily

![image](https://github.com/risingwavelabs/risingwave/assets/35356271/0a4d371b-2bdd-40f0-96b1-11eabc5c07d0)

### The version of RisingWave

nightly-20231217

**Comment by lmatz** [comment]
BTW, I remember there was a discussion of changing the sysbench's generator thread number and also Risingwave's configuration, Have they been changed already?

**Comment by cyliu0** [comment]
The sysbench thread has been changed to 16 to 64. And for he RW's config, I didn't remember we have changed anything.

**Comment by chenzl25** [comment]
It Is much better now.
