### ISSUE TITLE
feat(storage):  Avoid emergency picker causing base level sst accumulation

### ISSUE THREAD

**Issue by Li0k** [risingwavelabs/risingwave#14034]
### Background
We introduced an emergency picker for hummock as a solution in case of write-stop. 
The emergency picker pushes the sst of l0 to the base level as much as possible to mitigate a write stop. However, when the compactor's resources are insufficient, this can cause data to pile up at the base level, which further worsens the efficiency of the base-level compaction, and makes it difficult to recover, which we don't want to see.

### Improve
1.  Need to consider stacking of levels in LSM (refer to level picker)
2.  Based on 1, still remove the restriction on task picking, and make sure to push the file down as far as possible during write-stop

**Comment by hzxa21** [comment]
WIP. See #15954

**Comment by Li0k** [comment]
No new issues to report, close this issue first
