### ISSUE TITLE
PG CDC doesn't sync all 100 tables.

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#14055]
### Describe the bug

There are only 16 tables with source throughput according to the [grafana](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1702929552330&orgId=1&to=1702935459583&var-datasource=P2453400D1763B4D9&var-namespace=sysbench-cdc-20231218-200347-20231218&var-instance=&var-pod=All&var-component=All&var-table=All)

And the data check failed after the source throughput down to zero. Some tables has no data at all. https://buildkite.com/risingwave-test/sysbench-cdc/builds/93#018c7e85-4c8b-4d25-8d25-6c666ca4c5e2

![image](https://github.com/risingwavelabs/risingwave/assets/35356271/d3cadc22-a407-483e-ab22-62b2e421d650)

**Comment by cyliu0** [comment]
Reproduced with 20 tables in test env namespace sysbench-cdc-20231214-230349-20231214

![image](https://github.com/risingwavelabs/risingwave/assets/35356271/23af75da-5cca-4500-b3d2-81782ca80bba)

**Comment by StrikeW** [comment]
The PG `max_wal_senders` limit has been reached, which is 16.

> 2023-12-19 11:58:48.902 | Caused by: org.postgresql.util.PSQLException: FATAL: number of requested standby connections exceeds max_wal_senders (currently 16)

**Comment by cyliu0** [comment]
Not a bug
