### ISSUE TITLE
bug(dashboard): await tree dump shows empty result

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#14075]
### Describe the bug

Check Slack thread: https://risingwave-labs.slack.com/archives/C0606NNR74P/p1703038689015519?thread_ts=1703038374.870559&cid=C0606NNR74P

![image](https://github.com/risingwavelabs/risingwave/assets/10192522/c2b0cddf-9a4c-4dca-9fc1-95b14f45b33c)

**Comment by kwannoel** [comment]
False positive, I run a local cluster, and was accessing the meta dashboard for the local cluster, instead of the port forwarded cluster.
