### ISSUE TITLE
Received resultset tuples, but no field structure for them

### ISSUE THREAD

**Issue by sheltonsuen** [risingwavelabs/risingwave#14108]
### Describe the bug

When excute some sql, the client rise: 
Received resultset tuples, but no field structure for them

### The version of RisingWave

14.0 is fine, but 15.1 rise those errors

**Comment by lmatz** [comment]
May I ask which client is it?

**Comment by BugenZhao** [comment]
Is this the same issue as #14102?

**Comment by sheltonsuen** [comment]
intellj idea, postgre sql data source plugin

**Comment by sheltonsuen** [comment]
> Is this the same issue as #14102?

yes same issue, close current one

**Comment by lmatz** [comment]
Thanks for reporting @sheltonsuen we will fix asap

**Comment by sheltonsuen** [comment]
> Thanks for reporting @sheltonsuen we will fix asap

It's fine, revert to 1.4.0 will solve my problem, thanks
