### ISSUE TITLE
frontend node restarts when run sysbench bulk insert

### ISSUE THREAD

**Issue by xuefengze** [risingwavelabs/risingwave#14107]
### Describe the bug

https://buildkite.com/risingwave-test/sysbench/builds/634#018c8686-9e3a-4b87-928e-741cccc4fae7

After run `sysbench prepare`, sysbench create two tables.
```sh
sysbench \
--db-driver=pgsql \
--pgsql-host=xxx  \
--pgsql-port=xxx  \
--pgsql-user=xxx \
--pgsql-password=xxx \
--pgsql-db=xxx \
--threads=2 \
--report-interval=1 \
--events=0 \
--time=300 \
--percentile=99 \
/usr/local/share/sysbench/bulk_insert.lua \
prepare
```

<img width="856" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/73645462/6d7ae828-9bca-4114-bb4e-ec500f6ffeb6">

But `frontend` restarted after run `sysbench run`

```sh
sysbench \
--db-driver=pgsql \
--pgsql-host=xxx  \
--pgsql-port=xxx  \
--pgsql-user=xxx \
--pgsql-password=xxx \
--pgsql-db=xxx \
--threads=2 \
--report-interval=1 \
--events=0 \
--time=300 \
--percentile=99 \
/usr/local/share/sysbench/bulk_insert.lua \ run
```
<img width="1059" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/73645462/5a3a30b8-82c8-4d8a-81ef-8afc5e6de898">

<img width="985" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/73645462/b0e2ec3a-26ee-48ad-84fe-a674765651a2">

And here is resources config:
<img width="335" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/73645462/cbca527d-0278-4c00-9d70-16c9dceb2ab5">

**Comment by xuefengze** [comment]
`threads=1` is successful.
<img width="1010" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/73645462/8002849b-ade3-416a-bce3-dcf962d57a68">

**Comment by lmatz** [comment]
There is a core dump, 
but the collector of core dump is not enabled on Cloud right now.

**Comment by xuefengze** [comment]
After set `frontend = { limit = "2Gi", request = "2Gi" }`, `threads=2` is also successful.

<img width="1008" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/73645462/639b1810-5c3d-4bf6-b74c-3011f68d020c">

**Comment by chenzl25** [comment]
@xuefengze I think the frontend node is killed by OOMKiller. Could you please change `--threads=2` to `--threads=1`? or give the frontend node more memory?

**Comment by xuefengze** [comment]
> I think the frontend node is killed by OOMKiller.

yes.
> or give the frontend node more memory?

have already set the frontend memory to `2Gi`.
