### ISSUE TITLE
feat: support dynamic filter with `or` condition

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#14112]
### Is your feature request related to a problem? Please describe.

> A lot of users find it cumbersome to be restricted by `now()` cannot be used with `OR` or other clauses. Can this be improved? 

### Describe the solution you'd like

![image](https://github.com/risingwavelabs/risingwave/assets/10192522/dbcded72-ea65-40ae-b4fa-ab18f5d639a7)

### Describe alternatives you've considered

User may manually rewrite query as 

> (select * from t1 WHERE t < now() - INTERVAL '5 minutes') union (select * from t1 WHERE t > xxx)

But note that this `union` query requires distinct (dedup), which is expensive; while this approach doesn’t need this.

### Additional context

Can replace #10743

**Comment by st1page** [comment]
without "conditional dispatcher" we can implement it in optimizer 

> User may manually rewrite query as
(select * from t1 WHERE t < now() - INTERVAL '5 minutes') union (select * from t1 WHERE t > xxx)
But note that this union query requires distinct (dedup), which is expensive; while this approach doesn’t need this.

Or we can rewrite it with 

(select * from t1 WHERE t < now() - INTERVAL '5 minutes'  AND !(t > xxx))
union all
 (select * from t1 WHERE t > xxx)
