### ISSUE TITLE
support redact SHOW CREATE on demand

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#14115]
### Is your feature request related to a problem? Please describe.

Sensitive properties of source/sink, e.g. `s3.credentials.secret` and `schema.registry.password`, should be redacted first before included in text that may be shared, e.g. show create source/sink/table, diagnostic report.

#12673

**Comment by xxchan** [comment]
How is this related with https://github.com/risingwavelabs/risingwave/issues/7034?

**Comment by zwang28** [comment]
> How is this related with https://github.com/risingwavelabs/risingwave/issues/7034?

Pls ignore that. Previously I thought changes on persisted catalog was required, but it turns out to be wrong.

**Comment by fuyufjh** [comment]
Hi, @zwang28 any progress?

**Comment by zwang28** [comment]
> Hi, @zwang28 any progress?

#14760 adds a helper function to redact a SQL string. It's under review.

With regards to its call site. I intended to:
- Always redact in diagnostic report.
- Because I think sometimes user does want to view the secrets, should `show create` be optionally redact, e.g. based on user role?

**Comment by stefannegele** [comment]
As SECRETS will be premium feature (https://docs.risingwave.com/docs/dev/manage-secrets/), can we reopen this?

**Comment by xxchan** [comment]
I think we are not going to support this and you can use the premium edition.

**Comment by mrayees** [comment]
@stefannegele Thanks for your feedback. Let me look into it.
