### ISSUE TITLE
feat: Support expression simplify rule

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#14133]
Interestingly, we got a `not(others) or others` which equals true. We could use another rule to simplify this condition.

_Originally posted by @chenzl25 in https://github.com/risingwavelabs/risingwave/pull/14127#discussion_r1433817332_

**Comment by chenzl25** [comment]
Both of the following examples can be simplified into true. 
```
StreamFilter { predicate: (Not((t1.ts > '2023-12-18 00:00:00+00:00':Timestamptz)) OR (t1.ts > '2023-12-18 00:00:00+00:00':Timestamptz)) }
```

```
StreamFilter { predicate: (((Not((t1.ts > '2023-12-18 00:00:00+00:00':Timestamptz)) AND Not(IsNull(t1.ts))) OR (t1.ts > '2023-12-18 00:00:00+00:00':Timestamptz)) OR IsNull(t1.ts)) }
```

**Comment by xiangjinwu** [comment]
> Both of the following examples can be simplified into true.
> 
> ```
> StreamFilter { predicate: (Not((t1.ts > '2023-12-18 00:00:00+00:00':Timestamptz)) OR (t1.ts > '2023-12-18 00:00:00+00:00':Timestamptz)) }
> ```

This predicate can be simplified to `IsNotNull(t1.ts)` rather than `true`. Right?

**Comment by xzhseh** [comment]
For batch plan, something like below could also be optimized, e.g.,
![image](https://github.com/risingwavelabs/risingwave/assets/91381303/235fdda4-ec38-46d1-bc73-9ff43f8b7dbd)
