### ISSUE TITLE
test: extended query mode / 3rd-party tools are not well tested

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#14141]
Recently there was a regression (#14102) for not being able to connect RisingWave with 3rd-party tools, which primarily relies on the extended query mode. Despite the timely release of the quick fix in v1.5.2, we still didn't conduct any testing on it. As a result, it could be easily broken again in the future (https://github.com/risingwavelabs/risingwave/pull/14105#pullrequestreview-1792130091).

As shown in `e2e_test/extended_mode`, very limited cases are tested with extended mode.

https://github.com/risingwavelabs/risingwave/blob/d5a81841eef0939e632d1cc042728ed343960517/e2e_test/extended_mode/type.slt#L21-L28

I would suggest adding more tests for extended mode query by focusing on the real cases. Possible approaches:

- Integrate 3rd-party tools in CI and emulate some basic operations. For GUI tools, use GUI automation.
- Manually emulate basic operations with 3rd-party tools, then dump the queries into a `sqllogictest` case.
  However, it's worth noting that `sqllogictest-rs` does not have full support on postgres extended mode: only `prepare` and `query` is [covered](https://github.com/risinglightdb/sqllogictest-rs/blob/0919ca0d6a57daef89e2a7122019f7d8bf811d6e/sqllogictest-engines/src/postgres/extended.rs#L191-L195). Improvements need to be made to support `parse`, `bind`, `execute`, `describe` and so on.

**Comment by xxchan** [comment]
https://github.com/risingwavelabs/risingwave/issues/9958

**Comment by TennyZhuang** [comment]
https://github.com/risingwavelabs/risingwave/issues/14116

**Comment by wangrunji0408** [comment]
Would simulation test help? I once created an issue #5552 but thought it was low priority.

**Comment by BugenZhao** [comment]
> Would simulation test help? I once created an issue #5552 but thought it was low priority.

I believe we should first make `sqllogictest-rs` support more extended-mode messages. Alternatively, we can bypass using `slt` as the intermediate representation and program directly in simulation tests.

**Comment by BugenZhao** [comment]
Opened an issue in `sqllogictest-rs`: https://github.com/risinglightdb/sqllogictest-rs/issues/205

**Comment by fuyufjh** [comment]
@xuefengze Can you take a look? Perhaps query with different (go/java/...) clients can also solve this. May need more discussion.

**Comment by fuyufjh** [comment]
Duplicated #8213
