### ISSUE TITLE
The file cache rate limit filter over-filters insertion than expected.

### ISSUE THREAD

**Issue by MrCroxx** [risingwavelabs/risingwave#14156]
### Describe the bug

The insert rate limit is set to 480MB/s (based on flush rate) and no more admission policy is enabled. But there are writers dropped even the flush throughput only reaches 400MB/s.

<img width="953" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/22407295/481aaf33-3a46-4f6e-96bd-39afef45294e">

**Comment by hzxa21** [comment]
Any findings?

**Comment by MrCroxx** [comment]
Working on reproducing the workload with `foyer-storage-bench` tool, https://github.com/MrCroxx/foyer/pull/230 .

**Comment by hzxa21** [comment]
@MrCroxx Is this issue resolved?

**Comment by MrCroxx** [comment]
There is no observation with the new foyer engine, but the algorithm has not been changed. 

I'm going to close the issue for now. It the bug appears again, feel free to reopen it.
