### ISSUE TITLE
Provide structured output for `explain`

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#14168]
Sometimes the query plans are very large, making it hard to read in stdout.

If we output as `json` / `protobuf` and other formats, we can further graph it in some visualization software, and interact with it.

**Comment by xxchan** [comment]
BTW PG also supports `EXPLAIN (FORMAT JSON/YAML/XML)`

**Comment by st1page** [comment]
please follow the old explain statement styles to implement it. https://docs.risingwave.com/docs/current/sql-explain/#syntax
