### ISSUE TITLE
`postgres-sink` data is incorrect for the `date/time` type

### ISSUE THREAD

**Issue by xuefengze** [risingwavelabs/risingwave#14198]
### Describe the bug

`pg-sink` data is incorrect for the `date/time` type.

rw:
![image](https://github.com/risingwavelabs/risingwave/assets/73645462/75180419-f74f-4799-bad3-7e885d3d2e81)

pg:
![image](https://github.com/risingwavelabs/risingwave/assets/73645462/3ad4ca6c-99ed-4d83-91cb-1cb3651568be)

### To Reproduce

pg:
```sql
CREATE TABLE test (
  id INT,
  d DATE,
  PRIMARY KEY (id)
);
```

rw:
```sql
CREATE TABLE test (
  id INT,
  d DATE,
  PRIMARY KEY (id)
);
INSERT INTO test VALUES (1, '0001-01-01');
INSERT INTO test VALUES (2, '1550-12-31');
INSERT INTO test VALUES (3, '9999-01-01');
INSERT INTO test VALUES (4, '1970-01-01');
INSERT INTO test VALUES (5, '1000-01-01');

CREATE SINK test_sink
FROM
    test WITH (
    connector = 'jdbc',
    jdbc.url = 'jdbc:postgresql://postgres:5432/mydb?user=myuser&password=123456',
    table.name = 'test',
    type='upsert',
    primary_key = 'id'
);
```

**Comment by xiangjinwu** [comment]
Resulted from usage of legacy java class: #13684

**Comment by xuefengze** [comment]
- `mysql-sink` has the same problem.
- `cassandra` also has the same problem by calling [toLocalDate()](https://github.com/risingwavelabs/risingwave/blob/main/java/connector-node/risingwave-sink-cassandra/src/main/java/com/risingwave/connector/CassandraUtil.java#L148).
