### ISSUE TITLE
print the connecting IP whenever possible for better diagnosis into network issues

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#14207]
```
2023-12-26T06:56:37.992865433Z ERROR pgwire::pg_protocol: error when process message error=Failed to run the query: Scheduler error: gRPC request failed: Unknown error: transport error error.sources=[Scheduler error: gRPC request failed: Unknown error: transport error, Scheduler error: gRPC request failed: Unknown error: transport error, gRPC request failed: Unknown error: transport error, transport error, connection error: host unreachable, host unreachable]
```

One user reported this. We are not sure what led to this error yet, but it is likely to be some network glitch caused by environmental issues or possibly even the cloud vendor. Haven't seen this error before.

The `host unreachable` error makes it unclear to tell which host it is, which makes it harder to debug.

**Comment by MrCroxx** [comment]
Close via #14227 #14229

**Comment by hzxa21** [comment]
Do we still need #14227 given that #14229 is merged? I noticed that there are many logs related to `hyper::client::connect::http: connecting to xxx` shown up even when the cluster is running happily.

**Comment by lmatz** [comment]
True, observed the same a while ago

>Do we still need https://github.com/risingwavelabs/risingwave/pull/14227 given that https://github.com/risingwavelabs/risingwave/pull/14229 is merged?

technically I am not so sure if the latter covers the former? 🤔  @MrCroxx do you know

**Comment by hzxa21** [comment]
> The latter one reports all resolved DNS addresses. The former reports reports the exact address that the client actually used.
> 
> Disable one of them is okay if the information is enough for debugging.

+1 for disabling this hyper log because hyper is used in gRPC/aws-sdk/opendal and the connection creation log can flood the log file.
