### ISSUE TITLE
Metrics: add more info for UDF

### ISSUE THREAD

**Issue by KeXiangWang** [risingwavelabs/risingwave#14200]
### Is your feature request related to a problem? Please describe.

Currently, we have no labels for UDF functions. It would be better if we could add `ActorId`/`FragmentId` as labels to help locate the UDF. It also provides a more detailed view of the UDF function runtime, especially when there are multiple MV using one UDF.

**Comment by xxchan** [comment]
This seems not easy, as exprs are not aware of its actor/fragment 🤔

**Comment by xxchan** [comment]
Oh... `expr_context`?

**Comment by KeXiangWang** [comment]
> Oh... expr_context?

`expr_context` is for session value like timezone. But theoretically it can be used to provide  `ActorId` and `FragmentId`. Let's consider think of methods first. 🤔

**Comment by yufansong** [comment]
It seems this suggestion already include in #14199. Can we close this one and only keep #14199?

**Comment by KeXiangWang** [comment]
They are actually different. This issue is for grafana dashboard, while the other one is for meta dashboard. OK to close it now, as adding `ActorId/FragmentId` in grafana dashboard may be complicated. Instead, present them in meta dashboard is more appropriate.
