### ISSUE TITLE
bug: temporal_join_watermark CI fails randomly

### ISSUE THREAD

**Issue by MrCroxx** [risingwavelabs/risingwave#14238]
### Describe the bug

https://buildkite.com/risingwavelabs/pull-request/builds/38205#018caa49-b4fe-49b1-a145-fbcc775b735e

```
e2e_test/streaming/temporal_join/temporal_join_watermark.slt .. [FAILED]
--
  |  
  | failed to run `e2e_test/streaming/temporal_join/temporal_join_watermark.slt`
  |  
  | Caused by:
  | query result mismatch:
  | [SQL] select * from eowc_mv;
  | [Diff] (-expected\|+actual)
  | -   2023-09-14 06:00:00+00:00 1
  | at e2e_test/streaming/temporal_join/temporal_join_watermark.slt:42
```

**Comment by stdrc** [comment]
Also encountered here: https://github.com/risingwavelabs/risingwave/pull/14221#issuecomment-1869922622

**Comment by stdrc** [comment]
Seems to be a known issue: https://github.com/risingwavelabs/risingwave/issues/12172

cc @yuhao-su

**Comment by yuhao-su** [comment]
You can simply rerun. Or you can increase the wait time https://github.com/singularity-data/risingwave/blob/f8a024f3111c6369f613aad3adaadaec7c3816d3/e2e_test/streaming/temporal_join/temporal_join_watermark.slt#L33
