### ISSUE TITLE
`auto.register.schemas` for Iceberg sink

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#14254]

**Comment by liurenjie1024** [comment]
After a second thought, I don't think this is a practical idea. Creating an iceberg table has many options:
1. Partition spec
2. Sort order spec
3. A lot of configurations: https://iceberg.apache.org/docs/latest/configuration/

For auto schema registration, what we have is only schema, which is far from enough for creating a heavily optimized table. So I would suggest not to do this.

cc @neverchanje
