### ISSUE TITLE
improper metric usage `batch_row_seq_scan_next_duration`

### ISSUE THREAD

**Issue by mikechesterwang** [risingwavelabs/risingwave#14269]
Seems `batch_row_seq_scan_next_duration` stores `query_id` in the label. This means every query will produce a new time series, this is a bad practice when using metric. 

IMHO, the better idea is to use log to record this information. In this case, we can check the exact query id in the log when we find a surge in the abnormal metric graph.

![image](https://github.com/risingwavelabs/risingwave/assets/52522981/717e8f26-9865-4b67-a89d-934972fd586e)

**Comment by fuyufjh** [comment]
@liurenjie1024 Please take a look, thanks!

**Comment by liurenjie1024** [comment]
It may cause high cardinality metrics in highly frequent distributed query, but our system assumes that no frequent distributed query happens, so I think it's ok to work. Metrics are disabled for high qps serving queries.
