### ISSUE TITLE
feature request: use RisingWave as Postgres-FDW

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#14318]
### Is your feature request related to a problem? Please describe.

I want my primary postgres to connect to risingwave using the postgres_fdw.
But it's giving me this error

```
postgres=# import foreign schema public limit to (s1) from server risingwave into public;
ERROR:  Failed to run the query

Caused by:
  Feature is not yet implemented: ISOLATION LEVEL
Tracking issue: https://github.com/risingwavelabs/risingwave/issues/10376

CONTEXT:  remote SQL command: START TRANSACTION ISOLATION LEVEL REPEATABLE READ
```

**Comment by fuyufjh** [comment]
After the setting `ISOLATION LEVEL` the FDW will `DECLARE` a cursor and `FETCH` from the cursor repeatively. Need to support `DECLARE` & `FETCH` command. 

See also:
- https://blog.csdn.net/davidzwb/article/details/51803760
- Materialize: https://materialize.com/docs/sql/declare/

**Comment by VoVAllen** [comment]
You can also write a custom fdw wrapper like https://github.com/supabase/wrappers/tree/main/supabase-wrappers

**Comment by KeXiangWang** [comment]
I'm actively working on it, implementing a naive cursor.
