### ISSUE TITLE
recent nexmark daily tests OOM incidents

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#14324]
OOM occurs on the day we used the following images:
`nightly-20231219`
`nightly-20231226`
`nightly-20231228`
`nightly-20231231`
`nightly-20240101`
`nightly-20240102`

- [ ] #14078 
- [ ] #14280 
- [ ] #14293 
- [ ] #14294 

Pass: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=reglngvty-20231225-150220&from=1703517276000&to=1703560610000
![SCR-20240103-kj5](https://github.com/risingwavelabs/risingwave/assets/5791930/d9eb903a-5173-49ad-bf8e-1c0a0389d45a)

OOM: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=reglngvty-20231226-150247&from=1703603901000&to=1703647230000
![SCR-20240103-kj8](https://github.com/risingwavelabs/risingwave/assets/5791930/f786fe89-5ce0-4cc9-acc7-e7c9022072d9)

Pass: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=reglngvty-20231227-150231&from=1703690146000&to=1703733479000
![SCR-20240103-kja](https://github.com/risingwavelabs/risingwave/assets/5791930/78ba3935-d608-4996-a75b-e6cd9c76c668)

OOM: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=reglngvty-20231228-150237&from=1703776532000&to=1703812055000
![SCR-20240103-kjd](https://github.com/risingwavelabs/risingwave/assets/5791930/f65a9387-4704-45a4-983c-71be956a3c38)

OOM: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=reglngvty-20231231-150225&from=1704035771000&to=1704071314000
![SCR-20240103-kjg](https://github.com/risingwavelabs/risingwave/assets/5791930/c9957bc8-c8a1-495b-860f-b237bcf1188c)

OOM: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=reglngvty-20240101-150239&from=1704122122000&to=1704160677000
![SCR-20240103-kjl](https://github.com/risingwavelabs/risingwave/assets/5791930/47699404-789a-49c9-aa1e-b9d2a6e1cb82)

OOM: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1704208355000&orgId=1&to=1704242680000&var-datasource=Prometheus:+test-useast1-eks-a&var-namespace=reglngvty-20240102-150244
![SCR-20240103-kjn](https://github.com/risingwavelabs/risingwave/assets/5791930/b6c99d10-cef9-46c1-946c-69fbce169ed5)

When three CNs' memory usage is uneven, it will be OOM.
Need to rule out any impact from the environment. @huangjw806  is helping to confirm if https://github.com/risingwavelabs/kube-bench/pull/345 has any impact on this

But we have an OOM case where the CNs memory usage is even.

**Comment by fuyufjh** [comment]
> When three CNs' memory usage is uneven, it will be OOM.

Yeah. I'd like to focus on this abnormality first. It began since `reglngvty-20231228-150237`

**Comment by huangjw806** [comment]
> Need to rule out any impact from the environment. @huangjw806 is helping to confirm if https://github.com/risingwavelabs/kube-bench/pull/345 has any impact on this

This issue does not affect the pipeline environment.

**Comment by fuyufjh** [comment]
> > When three CNs' memory usage is uneven, it will be OOM.
> 
> Yeah. I'd like to focus on this abnormality first. It began since `reglngvty-20231228-150237`, whil `reglngvty-20231227-150231` looked normal.

Number of actor per node is even...🤔

<img width="1104" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/8c101411-c22e-45ac-a3ab-8149f367c9c4">

**Comment by fuyufjh** [comment]
> > > When three CNs' memory usage is uneven, it will be OOM.
> > 
> > 
> > Yeah. I'd like to focus on this abnormality first. It began since `reglngvty-20231228-150237`, whil `reglngvty-20231227-150231` looked normal.
> 
> Number of actor per node is even...🤔

The source split is not even since nightly-20231228

```
count(source_partition_input_bytes{namespace=~"$namespace",risingwave_name=~"$instance",risingwave_component=~"$component",pod=~"$pod"}) by (pod)
```

`reglngvty-20231228-150237` (`nightly-20231228`)

<img width="1104" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/1c8d657f-b282-4d17-b487-1a216ee89f3f">

`reglngvty-20231227-150231` (`nightly-20231227`)

<img width="1105" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/c96c8b42-d384-4812-bcea-5ca30f43d78b">

Code diff: https://github.com/risingwavelabs/risingwave/compare/4695ad1239b1c160228dd7bf6f473634f57c9834...aa9dcac98985f9650595ef4b67e43d2601e41a44

Any ideas? cc. @shanicky

**Comment by lmatz** [comment]
Forgot to post the easiest OOM on `nightly-20231219`

https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1702998973000&orgId=1&to=1703042305000&var-datasource=Prometheus:+test-useast1-eks-a&var-namespace=reglngvty-20231219-150239:
![SCR-20240103-nkq](https://github.com/risingwavelabs/risingwave/assets/5791930/0c7bada8-db84-4aa4-8eba-ac1bd97b25b7)

**Comment by xxchan** [comment]
`count(source_partition_input_bytes{namespace=~"$namespace",risingwave_name=~"$instance",risingwave_component=~"$component",pod=~"$pod"}) by (pod)`
for `20231219` is 13,8,3

**Comment by huangjw806** [comment]
It seems that it should be caused by PR between 20231227-20231228.
<img width="613" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/29391315/afab3b35-3720-4184-b354-de0d84316f2e">

**Comment by xxchan** [comment]
After https://github.com/risingwavelabs/risingwave/pull/14346, latest nightly test passed. We can close these issues but keep https://github.com/risingwavelabs/risingwave/issues/14333 open.
