### ISSUE TITLE
bug: ```show jobs``` displayed a dropped sink

### ISSUE THREAD

**Issue by ly9chee** [risingwavelabs/risingwave#14341]
### Describe the bug

creating a sink and immediately drop it seems not correctly handled in ```show jobs``` the progress of this dropped sink still displayed until the cluster is restarted.

### To Reproduce

prepare test data
```sql
create table t1(
    id bigint primary key,
    v bigint
);

insert into t1 select generate_series(1, 1000000) as id, generate_series(1, 1000000) as v;
```

create kafka sink and immediately drop it
```sql
create sink s1 from t1
with(
    connector='kafka',
    topic='topic_s1',
    properties.bootstrap.server='192.168.0.124:9092',
    primary_key='id',
    allow.auto.create.topics='true'
) FORMAT UPSERT ENCODE JSON;

drop sink s1;
```

now execute ```show jobs``` will display the progress of a dropped sink and its progress will never advance

### The version of RisingWave

PostgreSQL 9.5-RisingWave-1.5.4 (49a6b42514a0bafea36049fd9a30643f8bbebe48)

### Additional context

also tried with ```cancel jobs``` after this command success the progress still displayed in ```show jobs```

**Comment by thexiay** [comment]
Can you assign this issue to me?

**Comment by tabVersion** [comment]
> Can you assign this issue to me? I would like to solve it.

Sure. Thanks for your contribution.

**Comment by kwannoel** [comment]
> Can you assign this issue to me? I would like to solve it.

Hi, I have opened a PR earlier today, sorry about that https://github.com/risingwavelabs/risingwave/pull/14388.
