### ISSUE TITLE
The list of nodes in the streaming graph UI should be left aligned.

### ISSUE THREAD

**Issue by mingfang** [risingwavelabs/risingwave#14352]
https://github.com/risingwavelabs/risingwave/blame/c8cdb9f59ff12554085d4261d4d2e6a617854196/dashboard/pages/streaming_graph.tsx#L100

<img width="223" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/821695/11fadc27-8fc3-4450-a907-ec2aba06269e">

instead of center aligned(current)

<img width="210" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/821695/14ac7bd5-30c5-4ba4-9e22-2ce24f90b026">

**Comment by BugenZhao** [comment]
Thanks for your feedback. #14356 should already fix that!
