### ISSUE TITLE
feat: support `BEGIN ISOLATION LEVEL READ COMMITTED`

### ISSUE THREAD

**Issue by jetjinser** [risingwavelabs/risingwave#14368]
### Is your feature request related to a problem? Please describe.

Hasura uses the following sql statement when connecting through the `PostgreSQL` driver:
`BEGIN ISOLATION LEVEL READ COMMITTED, READ ONLY;`

### Describe the solution you'd like

For compatibility, accept but ignore `ISOLATION LEVEL READ COMMITTED` transaction_mode in BEGIN clause.
Just like `SET TRANSACTION`, throws a notice to the user.

**Comment by fuyufjh** [comment]
I think we can ignore the isolation level

**Comment by fuyufjh** [comment]
Hi, any progress? @jetjinser

**Comment by jetjinser** [comment]
it should be resolved by #15911.
