### ISSUE TITLE
refactor: deprecate `StreamChunkWithState` for source state

### ISSUE THREAD

**Issue by tabVersion** [risingwavelabs/risingwave#14384]
# Background and Motivation

In previous implementations, we use `StreamChunkWithState`, containing the payload as `StreamChunk` and an offset mapping (from `split_id` to the latest offset per partition). We truncate the offset per batch and only keep the last one, which brings us the limitation that we cannot do truncation anywhere after going into source exec while maintaining the semantic of exactly once.

based on additional columns(#14215), I propose to derive `partition` (`file` for fs source) and `offset` for all sources and read the partition and offset info from the stream chunk itself rather than a separate struct. It allows not to treat the chunk as a whole, both throttling (#13800) and reusable source (https://github.com/risingwavelabs/rfcs/pull/72) can benefit from it. 

After the refactor, we load split_id and offset from spec columns and no longer need `StreamChunkWithState`.

# Compatibility

I don't want to make breaking changes to the table catalog, but additional columns are required to be part of the schema.
@BugenZhao and I found a way that we can do it when building source schema, manually adding the two columns into it and pruning the columns before yielding.
Note that if users specify `include partition` or `include offset` in SQL, then they are in the table schema. We don't have to manually add them and prune them. 

This approach does not require changing data in meta, all changes happen in runtime and the new "hidden columns" do not have to be materialized, ie. a table with connector.

# Implementation

* manually add the two columns (`SourceDesc::column_catalogs_to_source_column_descs`)
  * cover both `SourceDesc` and `FsSourceDesc`
* for both trad_source and fs_source, change load the state from chunk 
https://github.com/risingwavelabs/risingwave/blob/7c84d06ff4f8b705117b862619a1f6766ca2d4c0/src/stream/src/executor/source/source_executor.rs#L571-L589
* prune the added columns before yielding (don't forget to check if the column is user requested. If so, no need to prune)
https://github.com/risingwavelabs/risingwave/blob/7c84d06ff4f8b705117b862619a1f6766ca2d4c0/src/stream/src/executor/source/source_executor.rs#L609

**Comment by xxchan** [comment]
If I understand it correctly, the motivation is: Since we can (and will always) include `partition` and `offset` in the chunk payload, the additional offset state in `StreamChunkWithState` and thus the whole struct isn't necessary any more.

I think it's a good to have refactoring but not urgent. It's also easy to change.

The compatibility issue is also mainly about whether always including `partition` and `offset` in the chunk is problematic, less related with `StreamChunkWithState` itself.
