### ISSUE TITLE
Discussion support a restart/kill meta statement through psql

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#14438]
<@U030W13SZKN> <@U034X02TB28> <@U030W140JEQ> are discussing if we can support a restart/kill meta statement through pgwire. We are finding the similar function in PG

[Slack Message](https://risingwave-labs.slack.com/archives/C069QSGTB9R/p1704786056582269?thread_ts=1704785641.097229&cid=C069QSGTB9R)

**Comment by st1page** [comment]
It is for the users who have no control of deployment and their k8s cluster

**Comment by lmatz** [comment]
I love <@U030W13SZKN> <@U034X02TB28> <@U030W140JEQ>  you all

**Comment by xxchan** [comment]
Since we already have https://github.com/risingwavelabs/risingwave/issues/12999, this is less urgent for now.

**Comment by CAJan93** [comment]
I kinda like the idea. I think it is great for people who host their own RW instance this sounds useful to me.

In our cloud operation, I think we should be mindful with this. Giving customers a `kubectl` via `psql` sounds like a security risk to me, even if this is read-only. Unless we limit this somehow to their own tenant ns.

If the customer is able to kill meta via `psql` we provide a tool to shoot themselves in the foot. If we provide this, I think we should make it clear in the docs to use this carefully. 

CC @wjf3121

**Comment by lmatz** [comment]
That's a good point, one approach is to disable these "in-sql" functionalities in the RW image for RW Cloud.

I imagine my points above are only applicable to users who deploy RW in their private cluster as RW Cloud/BYOC both have nice GUI for users to do all kinds of admin stuff.

**Comment by wjf3121** [comment]
> In our cloud operation, I think we should be mindful with this. Giving customers a kubectl via psql sounds like a security risk to me, even if this is read-only. Unless we limit this somehow to their own tenant ns.

As long as these features are flag protected and turned off on our managed cloud, we should be good.

**Comment by BugenZhao** [comment]
This may also help continuously integrate the tests for the error reporting for cluster recovery. 😄

**Comment by lmatz** [comment]
Is this sort of overlapped with #13142

**Comment by xxchan** [comment]
I think it's duplicated with #14700, and already done
