### ISSUE TITLE
Feature request: support fixed consumer name in source config , Kafka or Pulsar

### ISSUE THREAD

**Issue by sheltonsuen** [risingwavelabs/risingwave#14463]
### Is your feature request related to a problem? Please describe.

Yes, a problem of current prod env, once we create a table based on kafka source, we got a random consumer name registerd, 
The problem is when we reinstall or upgrade the risingwave application, we got a new consumer  and the original one will remain, this is unexpected behavior, although the offset seem correct.

### Describe the solution you'd like

We can config a fixed consumer name in the source connector

**Comment by xxchan** [comment]
> we got a new consumer and the original one will remain, this is unexpected behavior

We've fixed this and will reuse existing consumer groups instead. https://github.com/risingwavelabs/risingwave/pull/13856 It will be available in the next release v1.6.0

Regarding custom consumer group id, it has some technical issues and we haven't planned to support it yet. Is the behavior mentioned above good enough for you?

**Comment by sheltonsuen** [comment]
Nice, I didn't care the topic name right now, but a meanful name would be better
