### ISSUE TITLE
Feature request: support sink TIMESTAMPTZ to doris

### ISSUE THREAD

**Issue by sheltonsuen** [risingwavelabs/risingwave#14462]
### Is your feature request related to a problem? Please describe.

Yes, as we mentioned in wechat, once we receive timestamp from mysql CDC, then it will be convert to timestamptz in risingwave, but finally we can't sink it to doris/starrocks

### Describe the solution you'd like

Support timestamptz to timestamp map somewhere in the sink config of doris

**Comment by xiangjinwu** [comment]
Note that MySQL supports both `DATETIME` and `TIMESTAMP`, which corresponds to `TIMESTAMP WITHOUT TIME ZONE` and `TIMESTAMP WITH TIME ZONE` in RisingWave/PostgreSQL. However, Doris/StarRocks only has a `DATETIME` type. It is a limitation of Doris/StarRocks.

Depending on how you are using Doris/StarRocks, a `timestamptz` value can be converted to `timestamp without time zone` (MySQL/Doris/StarRocks `DATETIME`) with the following expression:
```
event_at AT TIME ZONE 'UTC'
event_at AT TIME ZONE 'Asia/Shanghai'
```
