### ISSUE TITLE
a variable to control the batch scan parallelism for better scan performance

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#14506]
> Only by changing the RW_PARALLELISM to have many more partitions for a table or an MV (which normally users are not aware of), e.g. 32, the users can fully benefit from these two optimizations.

Yes, currently our batch scan is coupled with the materialize operator fragment parallelism which could be a bottleneck. I think we can introduce another variable to control the batch scan parallelism as long as we can ensure it won't violate the cache locality of streaming queries.

_Originally posted by @chenzl25 in https://github.com/risingwavelabs/risingwave/issues/12741#issuecomment-1882650957_

**Comment by chenzl25** [comment]
I just found we have an alter statement to change the parallelism of a table which could be used to achieve the same purpose.
```sql
 alter table t set parallelism = 32;
```

**Comment by fuyufjh** [comment]
> Yes, currently our batch scan is coupled with the materialize operator fragment parallelism which could be a bottleneck

This is by design. The target is to align the data distribution of streaming and batch queries (storage access), so that they may perform better because of better block cache locality.
