### ISSUE TITLE
Iceberg sink with REST catalog error

### ISSUE THREAD

**Issue by dowands** [risingwavelabs/risingwave#14523]
### Describe the bug

Can not create iceberg sink with REST catalog, same catalog endpoint working well in other software like airbyte and starrock

### Error message/log

```text
Failed to run the query

Caused by these errors (recent errors listed first):
  1: gRPC request to meta service failed: Internal error
  2: Sink error: Iceberg error: IcebergDataInvalid => Can't encode empty namespace in url!
```

### To Reproduce

CREATE SINK test_sink FROM test
WITH (
  	type = 'upsert',
  	catalog.type = 'rest',
  	catalog.uri = 'http://host.docker.internal:8181',
    connector = 'iceberg',
    s3.access.key = 'xxx',
    s3.secret.key = 'xxx',
  	s3.region = 'us-east-1',
    database.name='iceberg',
  	primary_key = 'id',
  	warehouse.path = 's3://xxx/iceberg',
    table.name='test'
);

### Expected behavior

successful creation

### How did you deploy RisingWave?

same result on docker on mac and k8s on aws linux

### The version of RisingWave

PostgreSQL 9.5-RisingWave-1.5.0 (0bc2da252ca1402ca4c5a25fc34468f3f61bc184)

**Comment by xxchan** [comment]
@liurenjie1024 Can you take a look?

**Comment by liurenjie1024** [comment]
> @liurenjie1024 Can you take a look?

It's an known bug, please change table name to `iceberg.test`
