### ISSUE TITLE
Is `hyper::client::connect::http: connected to 172.19.0.5:4566` `debug` level log?

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#14539]
![SCR-20240112-oz1](https://github.com/risingwavelabs/risingwave/assets/5791930/e9ccf030-264f-4fa7-8f8f-f5cc0b43975c)

This log seems to generate forever in a very frequent way

**Comment by BugenZhao** [comment]
Originated from https://github.com/risingwavelabs/risingwave/pull/14227 😄

**Comment by hzxa21** [comment]
This log entry seems to be flooding the logs and it is rarely used during troubleshooting. Should we avoid this log?

**Comment by MrCroxx** [comment]
Is it still helpful when there is DNS issue? If not, I'll remove it. Otherwise, I'll add a config to switch it.

**Comment by hzxa21** [comment]
> Is it still helpful when there is DNS issue? If not, I'll remove it. Otherwise, I'll add a config to switch it.

I don't have a context for the previous DNS issue? Is it DNS issue inside RW cluster or between RW and user?

**Comment by MrCroxx** [comment]
> > Is it still helpful when there is DNS issue? If not, I'll remove it. Otherwise, I'll add a config to switch it.
> 
> I don't have a context for the previous DNS issue? Is it DNS issue inside RW cluster or between RW and user?

@lmatz has used the log as evidence to show the user that some connection error is caused by its DNS, not RW.

**Comment by lmatz** [comment]
yes, a really rare case I suppose, it was added per the user's request. I think it's fine to remove it now if it is annoying. No complaints about the incident after that

**Comment by BugenZhao** [comment]
We can still enable it by setting the `RUST_LOG` env var without making it enabled by default.
