### ISSUE TITLE
feat: reduce stream barrier body and only send one copy of it to each CN

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#14533]
When the parallelism in the cluster is relatively high and there are many multi-way join streaming jobs, the barrier body `BarrierMutation` on the stream will be amplified multiple times. When flowing between different compute nodes, it will cause a significant amount of memory usage for prost message decoding and may result in OOM. Here is a solution to fix it, details described as bellow: 

> Some thoughts discussed with @st1page , there is one feasible optimization solution to change the process of the barrier:
> Before sending the barrier, it can be sent to the local barrier manager on compute node first. When injecting the barrier, we can provide the id (`epoch`) only and let the actors to read specific mutation information from local barrier manager if necessary.  By this way, `BarrierMutation` only needs to be decoded once on each compute node.
> 
> _Originally posted by @yezizp2012 in https://github.com/risingwavelabs/risingwave/issues/13060#issuecomment-1876766151_

**Comment by BugenZhao** [comment]
+1 for this. In this way the `Stashed` state can also be removed. 😄

https://github.com/risingwavelabs/risingwave/blob/da05733c1db0c449803674ed9556478889736105/src/stream/src/task/barrier_manager/managed_state.rs#L36-L41

**Comment by kwannoel** [comment]
Maybe related @fuyufjh
