### ISSUE TITLE
Help Wanted: Not able to upgrade to 1.6.0

### ISSUE THREAD

**Issue by sheltonsuen** [risingwavelabs/risingwave#14556]
### Describe the bug

When tring to upgrade from 1.5.4 to 1.6.0

the compute node keep crash due to probe failed, but no other error logs in compute node and meta node 

<img width="669" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/44127430/1c430de0-94f5-4afd-96e1-7426c4f12564">
<img width="1272" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/44127430/717f600e-46ce-4de1-a22a-b438cecdbd13">
<img width="1364" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/44127430/44d136e5-7be6-4260-93d5-7c8d54185838">
<img width="988" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/44127430/571a683b-bc3a-4ca5-a438-087ef2bb2c5c">

### How did you deploy RisingWave?

helm upgrade

### The version of RisingWave

1.6.0

**Comment by sheltonsuen** [comment]
and k8s version:
<img width="1008" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/44127430/71d5fdf5-0d43-42e3-8e6c-8f58aea370bd">

**Comment by sheltonsuen** [comment]
It's a cluster issue not related to risingwave, close it

**Comment by sheltonsuen** [comment]
Still have this issue, the compute pods keep crash with exist code 1 after startup, no other message collected

**Comment by sheltonsuen** [comment]
I have try to enlarge the probe timeout and delay time, but not help

**Comment by lmatz** [comment]
>  the compute pods keep crash with exist code 1 after startup

what's the log of RW
If RW crashes, there must be some error or panic logs.


what's the status of pods, what does it say in the `REASON` field?

**Comment by lmatz** [comment]
I just rerun the upgrade test for `v1.5.4` and `v1.6.0`, and it works as expected.

Normally, if the upgrade fails, there should be some logs about certain inconsistencies, e.g.:
1. key values in the old meta cannot be recognized by the new meta
2. key values in the state of old operators cannot be recognized by the new operators

They must trigger some panic and will be shown in the log.

**Comment by sheltonsuen** [comment]
> I just rerun the upgrade test for `v1.5.4` and `v1.6.0`, and it works as expected.
> 
> Normally, if the upgrade fails, there should be some logs about certain inconsistencies, e.g.:
> 
> 1. key values in the old meta cannot be recognized by the new meta
> 2. key values in the state of old operators cannot be recognized by the new operators
> 
> They must trigger some panic and will be shown in the log.

Thank you for the test,

I didn't collect any panic log from compute node, maybe it's another new instance up, or somthing

Based on your test, later today(once our tester not using current env) I will start another upgrade to see if there any usefull log

**Comment by lmatz** [comment]
Hi @sheltonsuen 

could you check if "connector node" is still set to replica "1" in the yaml file? 

If it is, please delete it or set the replica to 0.

The connector node is embedded into compute node, and no longer need to be set explicitly.

**Comment by sheltonsuen** [comment]
> Hi @sheltonsuen
> 
> could you check if "connector node" is still set to replica "1" in the yaml file?
> 
> If it is, please delete it or set the replica to 0.
> 
> The connector node is embedded into compute node, and no longer need to be set explicitly.

It's working after setting replica to 0, thanks

**Comment by zwang28** [comment]
FYI, connector node should be disabled via
```
connectorComponent:
  enabled: false
```
