### ISSUE TITLE
Support `pause_on_next_bootstrap` for snapshot read

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#14589]
Support this in `backfill` executors.

Thanks @StrikeW for mentioning it.

**Comment by xxchan** [comment]
QQ: since we already supported "Drop during recovery", what's the usage of `pause_on_next_bootstrap` now?

**Comment by TennyZhuang** [comment]
We may need to scale up the nodes

**Comment by BugenZhao** [comment]
> We may need to scale up the nodes

Can you elaborate more?

**Comment by StrikeW** [comment]
It's a quick approach to stall injecting data, which will take effect after meta restart instead of waiting for a conf change barrier to complete.
