### ISSUE TITLE
The number of rows of UDF input chunk is too small

### ISSUE THREAD

**Issue by StrikeW** [risingwavelabs/risingwave#14605]
### Describe the bug

<img width="480" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/7338536/1a7ee79d-ffb9-4107-bd8c-29fa8116394d">

https://grafana.prod.risingwave.cloud/d/EpkBw5W4k/risingwave-dev-dashboard?from=1705143551000&orgId=1&to=1705159885000&var-component=All&var-datasource=P7AEF1E9BD6C1839A&var-instance=risingwave&var-namespace=rwc-g1hhgcv4t0f0k8cr19qbl8coqk-test&var-pod=All&var-table=All

### The version of RisingWave

v1.6-da175e8

### Additional context

https://risingwave-labs.slack.com/archives/C0606NNR74P/p1705155772714269?thread_ts=1705135558.026809&cid=C0606NNR74P

**Comment by BugenZhao** [comment]
I suppose this issue is not exclusive to UDF. It actually depends on the chunk size from the upstream executor. For instance, if there's an aggregation with few groups in the upstream, then small chunks for evaluation is inevitable.

May I ask about the throughput of the UDF?

**Comment by StrikeW** [comment]
You can check the grafana link to see the udf throughput and other metrics.

**Comment by wangrunji0408** [comment]
Is it worthy to merge small chunks into bigger ones at the entry of ProjectionExecutor?
