### ISSUE TITLE
Create multiple table CDC  use Postgres-cdc Failed, not support format Plain with encode Json

### ISSUE THREAD

**Issue by ediconss** [risingwavelabs/risingwave#14625]
### Describe the bug

use Postgres-cdc  Create multiple table CDC;

CREATE SOURCE pg_mydb  WITH (
    connector = 'postgres-cdc',
    hostname = '192.168.10.233',
    port = '5434',
    username = 'test',
    password = 'test',
    database.name = 'data_warehouse',
    slot.name = 'mydb_slot'
);

### Error message/log

```text
Caused by:
  Protocol error: connector postgres-cdc does not support format Plain with encode Json
```

**Comment by xxchan** [comment]
What's your RisingWave version? I cannot reproduce this issue.

**Comment by ediconss** [comment]
> What's your RisingWave version? I cannot reproduce this issue.

PostgreSQL 9.5-RisingWave-1.5.4

**Comment by ediconss** [comment]
> What's your RisingWave version? I cannot reproduce this issue.

sorry, i forgot, i upgrade to 1.6.0 it's okay, thanks
