### ISSUE TITLE
alert users in the log(or something else?) that which row in which join produced an abnormally high number of joined results

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#14643]
because 
1. There could be some unexpected changes from the user side. Only uses have information about it.
2. It can be a hint to optimize SQL queries further to avoid such changes.
3. It makes the diagnosis of the root cause of phenomena such as barrier piling up or OOM much easier. The person who investigates the issue may not relate the observation to potential root causes easily.

**Comment by fuyufjh** [comment]
Regarding of the threshold, what do you think? I propose 10k i.e. print a warning log with the current join key values if it produces more than 10k rows for a single input row.

**Comment by lmatz** [comment]
https://github.com/risingwavelabs/risingwave/pull/16799 done here by @kwannoel 
close now

**Comment by kwannoel** [comment]
> https://github.com/risingwavelabs/risingwave/pull/16799 done here by @kwannoel 
> close now
> 
> edit:
> BTW, is 
> >Please make sure to use LogSuppressor to avoid flooding logs.
> used?

Not necessary. The approach here is to only enable logs on demand, by setting RUST_LOG. May checkout the PR description for more info.
