### ISSUE TITLE
Clickhouse Enum support

### ISSUE THREAD

**Issue by HurricanKai** [risingwavelabs/risingwave#14658]
### Is your feature request related to a problem? Please describe.

I'm trying to efficiently insert a risingwave String into a Clickhouse table which uses Enum8.

### Describe the solution you'd like

I'd like it to be possible to sink Risingwaves String into Clickhouse Enum8s.

### Describe alternatives you've considered

If an equivalent risingwave type existed, converting to that and inserting that into clickhouse would be fine also, but I'm not aware of such a type.

### Additional context

[Clickhouse Enum Docs](https://clickhouse.com/docs/en/sql-reference/data-types/enum)

Current Error:
```
Caused by these errors (recent errors listed first):
  1: gRPC request to meta service failed: Internal error
  2: Sink error: ClickHouse error: Column type can not match name is "region", risingwave is Varchar and clickhouse is "Enum8(...)"
```

**Comment by HurricanKai** [comment]
After digging a bit into this, it seems like there's no easy way to support inserting Strings into Enums.
From my understanding the risingwave clickhouse connector uses the RowBinary format, which does not support this.

Instead allowing Int16s to be inserted into Enum8/16 is pretty easy, PR following. For my use cases this is fine, although a little annoying.
Alternatives to insert strings include
- Using a different format where necessary, ie CSV, TSV, plain Values, where clickhouse does the conversion
- Parsing the type (in code `ck_column.r#type`) string to understand which string corresponds to which value. This is fairly straightforward, but relies on parsing clickhouse DDL...

**Comment by HurricanKai** [comment]
See PR for further info - I've only managed to get Enum16 working. My dataset isn't that huge so this is fine for me. Supporting Enum8 would be more work and I'm not sure how critical. 
IMO this issue could be closed if the above PR is merged, if any of the other features are desired (ie Enum8 support or String insertion), that could be tracked in another issue.

**Comment by xxhZs** [comment]
Currently enum16 has been implemented, enum8 can't correspond to int8 because rw doesn't have a int8, so all close this issue
