### ISSUE TITLE
nightly-20240118 frontend node OOM in backfill test

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#14669]
### Describe the bug

[buildkite job](https://buildkite.com/risingwave-test/backfill/builds/128#018d1e2a-38c4-430b-9a0e-c7629cca75e7)

<img width="1009" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/01dbbff1-dc3b-4b9a-9ff7-cd82d0685304">

## nightly-20240118
- `186703dbc4595325d7e98734809f70d0c859e899` [feat: Introduce jni catalog to support all catalogs (#14264)](https://github.com/risingwavelabs/risingwave/pull/14264)
- `c902aada5c89d38411df85585f37381c2f058dee` [fix(compactor): drop delete range by compaction filter (#14480)](https://github.com/risingwavelabs/risingwave/pull/14480)
- `db7b8eb19ecac87fd8c4b7b4a6af42f895bd17c2` [test: add php client test into ci pipeline (#14649)](https://github.com/risingwavelabs/risingwave/pull/14649)
- `5df707d4aea438d52895b8b37052fafd59adcb37` [fix(ci): remove installation of mysql from integration test (#14638)](https://github.com/risingwavelabs/risingwave/pull/14638)
- `023a7fdba716d229614d266d884b3262c4370f1f` [fix(memtable): parallel flush does not generate split keys correctly (#14520)](https://github.com/risingwavelabs/risingwave/pull/14520)
- `de3cb2f17351931d2b7b1a1a6c369f8b266b307c` [chore(storage): enable check compaction result on dedicated compaction (#14637)](https://github.com/risingwavelabs/risingwave/pull/14637)
- `49e43c5c1bdc8d532cf461c787bd751d34ae5fca` [chore(deps): Bump tracing from 0.1.39 to 0.1.40 in /integration_tests/feature-store/simulator (#14632)](https://github.com/risingwavelabs/risingwave/pull/14632)
- `2f8ae6c9caaf18b7ff52b72bb79cc61754903210` [chore(deps): Bump tracing from 0.1.39 to 0.1.40 in /integration_tests/feature-store/server (#14633)](https://github.com/risingwavelabs/risingwave/pull/14633)
- `1399fcb736386566a6f3c115d46d22cf54db679e` [refactor(log-store): introduce pk info to handle different version of log store pk schema (#14561)](https://github.com/risingwavelabs/risingwave/pull/14561)
- `78d69e6b5d1ed36f1de5befca8f02b536f9743bf` [fix(batch): fix batch default scheduler parallelism (#14623)](https://github.com/risingwavelabs/risingwave/pull/14623)
- `fbfc9127e2cf1007239c2025e6c40349783a4ff2` [fix: incorrect batch sort agg on ordered input when group key is not prefix of input order columns (#14621)](https://github.com/risingwavelabs/risingwave/pull/14621)

### The version of RisingWave

nightly-20240118

**Comment by lmatz** [comment]
@cyliu0 does the test OOM again with heap profiler enabled in the frontend node?

**Comment by cyliu0** [comment]
> @cyliu0 does the test OOM again with heap profiler enabled in the frontend node?

The daily docker pipeline failed to build the nightly image last night. So it didn't run yet. According to the backfill pipeline history, we didn't hit the frontend OOM again after nightly-20240118.
<img width="1164" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/28d9bfaf-3064-4a8d-b917-c8b3e6a96f78">

**Comment by lmatz** [comment]
Thanks, then I will close it right now, if it occurs again, we can open a new one.

Next time OOM, there should be a memory dump for easier investigation.
