### ISSUE TITLE
main-cron: end-to-end clickhouse sink test failed

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#14674]
```
testing sinks
e2e_test/sink/clickhouse_sink.slt                            .. [OK] in 743 ms
The output is not as expected.
```

https://buildkite.com/risingwavelabs/main-cron/builds/1539#018d184a-efe8-4ffb-a1dd-22d9b5d62905

cc @xxhZs Would you please help to take a look?

**Comment by xxhZs** [comment]
after https://github.com/risingwavelabs/risingwave/pull/14711 , no more failures, so close this issue. If necessary, please reopen it
