### ISSUE TITLE
feat(expr): an expr impl(maybe only function call) back compatibility mechanism. 

### ISSUE THREAD

**Issue by KeXiangWang** [risingwavelabs/risingwave#14678]
### Is your feature request related to a problem? Please describe.

Currently, we use function call signature to identify a function call based on the persisted proto files.
When we have a new implementation on a function call, if the new impl does not changed it signature, the new function call will be triggered with old proto files.

One example, assume we have a function `f(a int) -> int`. The old implementation was `f(a) = a + 1`. After a fix/change, the new implementation is `f(a) = a + 2`. The same input will produce different output before and after the fix, which cause potential inconsistent state.

Now, when we have a fix on function calls, we need to tag the PR as a break change, which means users should recreate the MV containing the function call after cluster upgradation. But this a loose constraint. The user may not realize that and will not recreate and ask our engineer to fix the caused inconsistency. 

So we need to find a way to provide back compatibility mechanism for expression or function calls fixes.

### Describe the solution you'd like

Maybe add a `version` field in the `function` macro and it works like the existing `AggVersion`. Will provide a detailed design later.

**Comment by BugenZhao** [comment]
Just FYI: It should be noted that a breaking change on the expression can be introduced **_accidentally_** by developers, e.g., a bug. So I guess any mechanism that let the developer to bump the version field **_manually_** is unsound. On the contrary, always recording a (release) version may help.

See also https://github.com/risingwavelabs/risingwave/pull/14221#pullrequestreview-1796703852.

**Comment by KeXiangWang** [comment]
> always recording a (release) version may help.

Yeah. Make sense. 👍
