### ISSUE TITLE
Provide a command to trigger recovery manually 

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#14700]
### Is your feature request related to a problem? Please describe.

Sometimes in testing we also hope to test the recovery path beside the normal path. 

For example, when creating a streaming job:

- Normal path uses mutation barrier to update the streaming actors and their topology
- Recovery path updates the persisted metadata, which would be used to construct the graph upon any recovery

With a SQL (?) command to trigger recovery manually, we may cover this cases better.

**Comment by BugenZhao** [comment]
Somehow related to https://github.com/risingwavelabs/risingwave/issues/14438#issuecomment-1903128629.

**Comment by kwannoel** [comment]
Not just in testing, but trigger recovery under high barrier latency to let alter rate limit / drop stream job take effect immediately.
