### ISSUE TITLE
test debezium-mysql and debezium-postgres with more data types

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#14716]
Seems nowhere have we tested data types for debezium. We've only tested direct CDC.
Let's add tests in integration_tests/debezium-mysql and integration_tests/debezium-postgres.
We can copy tests from  integration_tests/postgres-sink/postgres_prepare.sql where there is a comprehensive data type testing for both direct PG sink and source.

An issue that's probably due to the lack of tests https://github.com/risingwavelabs/risingwave/issues/14704

**Comment by lmatz** [comment]
cc: @xuefengze  could you take a look?

**Comment by xuefengze** [comment]
Closed by https://github.com/risingwavelabs/risingwave/pull/14891, https://github.com/risingwavelabs/risingwave/pull/14862
