### ISSUE TITLE
bug: merge imm can truncate incorrect imm in read version when I/O is slow

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#14743]
### Describe the bug

When merge imm happens, it assumes that the merged imms must be the oldest imms in local hummock storage's read version so we use `self.staging.imm.truncate(staging_imm_count - merged_imm_ids.len());` to truncate the imms in read version. However, when there are slow in-flight uploading task, this assumption can break and cause imms that are not merged to be deleted from read version mistakenly. Example sequences:
1. Shard 1 flush `imm1` in `epoch1`. Shard1 read_version = `[imm1]`
2. Shard 1 flush `imm2` in `epoch2`. Shard1 read_version = `[imm2, imm1]`
3. Shard 1 flush `imm3` in `epoch3`. Shard1 read_version = `[imm3, imm2, imm1]`
4. Generate `imm_merge_task1 = [imm3, imm2, imm1]`.
5. Before `imm_merge_task1` finishes, spill/sync happens. `imm_merge_task1` is dropped and `upload_task1 = [imm3, imm2, imm1]` is generated
6. Shard 1 flush `imm4` in `epoch4`. Shard1 read_version = `[imm4, imm3, imm2, imm1]`
7. Shard 1 flush `imm5` in `epoch5`. Shard1 read_version = `[imm5, imm4, imm3, imm2, imm1]`
8. Generate `imm_merge_task2 = [imm5, imm4]`
9. `upload_task1= [imm3, imm2, imm1]` fails. 
10. `imm_merge_task2 = [imm5, imm4]` finishes. 
11. Shard1 read_version becomes `merged imm [imm5, imm4] + staing imm [imm5, imm4, imm3]`. However, the correct read version should be `merged imm [imm5, imm4] + staing imm [imm3, imm2, imm1]`. Data from `imm2` and `imm1` becomes invisible for read until upload_task1= [imm3, imm2, imm1]` finishes.

~~Note that **this bug will not cause data loss in storage/S3** because the all IMMs can still be uploaded to S3 and added to hummock version. However, **this bug will cause some newly flushed data to be invisible for state table reads** (including `iter` and `get`) when S3 upload is in progress.~~

**This bug will only cause panic (can be recovered after recovery) and won't cause any correctness issue because checkpoint must fail when this bug is triggered.**

We have a [debug assert check](https://github.com/risingwavelabs/risingwave/blob/82e9af37c04d8529a462014dec38796866dc8f7e/src/storage/src/hummock/store/version.rs#L462) but it is not enabled for release build so truncation can still happen.

### Error message/log

```text
thread 'rw-main' panicked at src/storage/src/hummock/store/version.rs:470:17:
assertion `left == right` failed: merged_imm_ids: [102, 101]
  left: 81
 right: 102
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panicking.rs:297:5
   4: risingwave_storage::hummock::store::version::HummockReadVersion::add_merged_imm
             at ./src/storage/src/hummock/store/version.rs:470:17
```

### To Reproduce

#14722 adds rate limit to minio for backfill test and can reproduce this issue.

**Comment by hzxa21** [comment]
@wenym1 @StrikeW Can you help verify whether the analysis is correct?

**Comment by kwannoel** [comment]
Related https://github.com/risingwavelabs/risingwave/issues/14724

**Comment by StrikeW** [comment]
> Shard1 read_version becomes merged imm [imm5, imm4] + staing imm [imm5, imm4, imm3]. However, the correct read version should be merged imm [imm5, imm4] + staing imm [imm3, imm2, imm1]. Data from imm2 and imm1 becomes invisible for read until upload_task1= [imm3, imm2, imm1]` finishes.

I don't get why `imm2` and `imm1` are absent from the `read_version` in this case since `upload_task1` are still ongoing. Only after the upload task finished, imm3~imm1 will be removed from `read_version`. https://github.com/risingwavelabs/risingwave/blob/82e9af37c04d8529a462014dec38796866dc8f7e/src/storage/src/hummock/store/version.rs#L284

**Comment by StrikeW** [comment]
> > 10. Shard1 read_version becomes merged imm [imm5, imm4] + staing imm [imm5, imm4, imm3]. However, the correct read version should be merged imm [imm5, imm4] + staing imm [imm3, imm2, imm1]. Data from imm2 and imm1 becomes invisible for read until upload_task1= [imm3, imm2, imm1]` finishes.
> 
> I don't get why `imm2` and `imm1` are absent from the `read_version` in this case since `upload_task1` are still ongoing. Only after the upload task finished, imm3~imm1 will be removed from `read_version`. Could you elaborate a bit?
> 
> https://github.com/risingwavelabs/risingwave/blob/82e9af37c04d8529a462014dec38796866dc8f7e/src/storage/src/hummock/store/version.rs#L284

Offline discussed. `imm2` and `imm1` are mistakenly truncated by the finished `imm_merge_task2`.

**Comment by wenym1** [comment]
I have successfully reproduced the panic locally.

Some related logs
```
assertion `left == right` failed: merged_imm_ids: [287, 286], [295, 294, 287, 286, 279, 278, 271, 267, 261, 257]
```

Search imm_id `279` we can get the related logs
```
uploading: [273, 277, 276, 279, 272, 275, 274, 278, ...
...
upload task failed UploadTaskInfo { task_size: 453546, epochs: [...], imm_ids: [273, 277, 276, 279, ...
```

The failed upload task is unable to replace the old imm at the queue back with sst. After the upload task finishes (no matter success or not), the merging task can be polled, and the input imms of the merging task are not at the queue back, and then panic happens.

**Comment by hzxa21** [comment]
> I have successfully reproduced the panic locally.
> 
> Some related logs
> 
> ```
> assertion `left == right` failed: merged_imm_ids: [287, 286], [295, 294, 287, 286, 279, 278, 271, 267, 261, 257]
> ```
> 
> Search imm_id `279` we can get the related logs
> 
> ```
> uploading: [273, 277, 276, 279, 272, 275, 274, 278, ...
> ...
> upload task failed UploadTaskInfo { task_size: 453546, epochs: [...], imm_ids: [273, 277, 276, 279, ...
> ```
> 
> The failed upload task is unable to replace the old imm at the queue back with sst. After the upload task finishes (no matter success or not), the merging task can be polled, and the input imms of the merging task are not at the queue back, and then panic happens.


Given that we will always wait for in-progress upload task to finish (including sync task and spill task) before merge imm task can be polled, that means **the only chance this bug can be triggered is when the upload task fails**. In this case, the checkpoint must fail. Although this bug will can potentially cause panic in the streaming side, it will not cause any correctness issue because the incorrect intermediate states are discarded due to checkpoint failure and recovery.

**Comment by StrikeW** [comment]
> Given that we will always wait for in-progress upload task to finish (including sync task and spill task) before merge imm task can be polled, that means the only chance this bug can be triggered is when the upload task fails.

Yes, poll those upload tasks before merge imm tasks.
https://github.com/risingwavelabs/risingwave/blob/82e9af37c04d8529a462014dec38796866dc8f7e/src/storage/src/hummock/event_handler/uploader.rs#L1115-L1123

**Comment by kwannoel** [comment]
> This bug will only cause panic (can be recovered after recovery) and won't cause any correctness issue because checkpoint must fail when this bug is triggered.

Why will this not trigger data inconsistency issues in production? IIUC, the issue will only cause crash in debug mode.

To me, this means that in release mode (production), the issue can be silently ignored, and cause inconsistencies.

Why must the checkpoint fail?

**Comment by kwannoel** [comment]
> Given that we will always wait for in-progress upload task to finish (including sync task and spill task) before merge imm task can be polled, that means the only chance this bug can be triggered is when the upload task fails. In this case, the checkpoint must fail. Although this bug will can potentially cause panic in the streaming side, it will not cause any correctness issue because the incorrect intermediate states are discarded due to checkpoint failure and recovery.

Nevermind, got it
