### ISSUE TITLE
bug(source): schema registry header of protobuf is not skipped properly

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#14773]
> This is skipping `i` **bytes** rather than skipping `i` **variable-length zig-zag encoded integers**. ~~For `i` within `1..=63`, the encoding outputs a single byte so this happens to work.~~
> 
> > prefixed by the length of the array (which is also variable length, Zigzag encoded)
> 
> `i` itself is also encoded so the decoded length shall be `i / 2`.

_Originally posted by @xiangjinwu in https://github.com/risingwavelabs/risingwave/pull/14057#discussion_r1464511298_

> Got it, so the correct implementation is
> ```
>         Some(i) => Ok(&remained[(1 + *i / 2) as usize..]),
> ```

_Originally posted by @Rossil2012 in https://github.com/risingwavelabs/risingwave/pull/14057#discussion_r1464561640_

### Impact

In the common case where a message is defined at top level (i.e. not nested within another message's definition), and the message index is <= 63, the current implement happens to work correctly because `i == 2` implies `i == 1 + i/2`.

Example: `UserWithNewType` in the PR is at top level with index 2, so its indexes array `[2]` would be encoded as `02 04` (`02` for the length `1` and `04` for the element `2`). Skipping `02` (first byte read as `i`) bytes happens to skip the encoded sequence exactly.

**Comment by Rossil2012** [comment]
Note here:
As nesting depth of message and no. of messages can be larger than 2^6 - 1 (in varint encoding, only 7b out of 1B is for zig-zag encoding, so 63 is the max number that can be encoded in 1 byte), we need to check more bytes if the highest bit is 1.
The correct implementation may be:
if the first byte is not 0, decode one int as i with varint & zig-zag, and then decode i ints with varint & zig-zag. The remaining part is the actual payload.
