### ISSUE TITLE
perf: bulk insert performance degradation

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#14774]
> Meanwhile, there is a performance degradation for bulk insert

The problem still continues for the past days. Need to take a look cc. @chenzl25 

<img width="779" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/56a8c637-422a-425a-b3d1-9a7341fb6e6c">

_Originally posted by @fuyufjh in https://github.com/risingwavelabs/risingwave/issues/14634#issuecomment-1907784019_

**Comment by chenzl25** [comment]
![Image](https://github.com/risingwavelabs/risingwave/assets/9352536/dd4bcfe2-1e33-41c1-9ab7-5e5a9bf11b74)

The performance is coming back.
