### ISSUE TITLE
only allow TTL(retention_seconds) on append only table

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#14791]

**Comment by hzxa21** [comment]
Do we allow TTL on index of append only table?

**Comment by BugenZhao** [comment]
Will the consistency still be a problem if the state of this append-only table is shared by other operators? For example, doing a delta-join on the append-only table with TTL.

**Comment by st1page** [comment]
> Do we allow TTL on index of append only table?

I think it should be the same with the base append only table?
