### ISSUE TITLE
bug: dirty ddl progress for dropped backfilling sink (into table)

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#14803]
### Describe the bug

Found in one of our client's environment in version v1.6.0. If we drop a sink (into table) that is still under backfilling, the drop will success but the ddl progress will be left uncleaned. It looks very confusing. Cc @kwannoel @shanicky , PTAL.

**Comment by kwannoel** [comment]
Fixed here, but did not cherry pick https://github.com/risingwavelabs/risingwave/pull/14388.

**Comment by yezizp2012** [comment]
Oh, I remembered that the sink progress is no longer tracked in ddl progress after #14388 , but this PR is not included in v1.6.0.
