### ISSUE TITLE
bug(PostgreSQL CDC): use PostgreSQL multiple CDC , Only partial data was Ingested

### ISSUE THREAD

**Issue by ediconss** [risingwavelabs/risingwave#14805]
### Describe the bug

```sql
CREATE SOURCE pg_mydb  WITH (
    connector = 'postgres-cdc',
    hostname = '192.168.10.34',
    port = '5434',
    username = 'rep',
    password = 'xxxxxx',
    database.name = 'data_warehouse',
    slot.name = 'mydb_slot_dim'
);

CREATE TABLE ods.ods_hl_stock_record
(record_id int8  
, request_id varchar
, record_type int2
, before_change_unit_quantity numeric
, before_change_total_quantity numeric
, unit_quantity numeric
, total_quantity numeric
, batch_id int8
, create_time timestamp with time zone
, create_by int8
, update_time timestamp with time zone
, deleted int2
, note varchar
, is_batch int4
, business_id int8 
, PRIMARY KEY (record_id)
)  FROM pg_mydb TABLE 'ods.ods_hl_stock_record';
```

in postgresql have 7 million data, but rw only have 4 ten thousand。

bu use single cdc it's ok
```sql
CREATE TABLE ods.ods_hl_stock_record
(record_id int8  
, request_id varchar
, record_type int2
, before_change_unit_quantity numeric
, before_change_total_quantity numeric
, unit_quantity numeric
, total_quantity numeric
, batch_id int8
, create_time timestamp with time zone
, create_by int8
, update_time timestamp with time zone
, deleted int2
, note varchar
, is_batch int4
, business_id int8 
, PRIMARY KEY (record_id)
)
WITH (
    connector = 'postgres-cdc',
    hostname = '192.168.10.34',
    port = '5434',
    username = 'rep',
    password = 'xxxxxx',
    database.name = 'data_warehouse',
    schema.name = 'ods',
    table.name = 'ods_hl_stock_record'
);
```

### The version of RisingWave

docker
PostgreSQL 9.5-RisingWave-1.6.0

**Comment by ediconss** [comment]
not find error

**Comment by StrikeW** [comment]
Hi @ediconss, there is an internal table to track the progress of snapshot loading, could you also take a look of it? The instructions is here:

> To check the progress of backfilling historical data, find the corresponding internal table using the [SHOW INTERNAL TABLES](https://docs.risingwave.com/docs/current/sql-show-internal-tables/) command and query from it. For instance, the following SQL query shows the progress of a CDC table named orders_rw.
> 
> SELECT * FROM __internal_orders_rw_4002_streamcdcscan_5002;
> 
> -[ RECORD 1 ]-----+---------------------------------------------------------------
> split_id          | 5001
> o_orderkey        | 4024320
> backfill_finished | f
> row_count         | 1006080
> cdc_offset        | {"MySql": {"filename": "binlog.000005", "position": 60946679}}

**Comment by ediconss** [comment]
```sql
{
"select * from __internal_ods_hl_stock_record_3_streamcdcscan_1004\r\n": [
	{
		"split_id" : "4294967294",
		"record_id" : 32848,
		"backfill_finished" : false,
		"row_count" : 32768,
		"cdc_offset" : "{\"Postgres\": {\"lsn\": 10732191096576, \"txid\": 960144396}}"
	}
]}
```

**Comment by StrikeW** [comment]
> ```sql
> {
> "select * from __internal_ods_hl_stock_record_3_streamcdcscan_1004\r\n": [
> 	{
> 		"split_id" : "4294967294",
> 		"record_id" : 32848,
> 		"backfill_finished" : false,
> 		"row_count" : 32768,
> 		"cdc_offset" : "{\"Postgres\": {\"lsn\": 10732191096576, \"txid\": 960144396}}"
> 	}
> ]}
> ```
> 
> Will we pull the full of data when creating this table?

Thank you. Based on this state, the backfilling is not finished (`false` in the output) and it should continue to load the historical data. And I notice that you are using the v1.6.0 version which actually has some bugs, I am not quite sure whether the bug will cause your problem. But I suggest you can upgrade to the `risingwave:git-55ebf241c3639f05b240695b37a60c0bc73870c2` image to have a try, which contains bug fixes.

**Comment by ediconss** [comment]
pull access denied for risingwave

**Comment by ediconss** [comment]
okey, i pulled , but still no full data

**Comment by StrikeW** [comment]
> okey, i pulled , but still no full data

Is there any MV built on top of the table? And you can take a look of the grafana dashboard on localhost:3001, and check if the  Barrier Latency is normal.

**Comment by ediconss** [comment]
I found the reason, it's due to network issues. I used an SSH tunnel，

**Comment by ediconss** [comment]
Thank you for your help！
