### ISSUE TITLE
bug(standalone): all compute metrics only shown on meta port

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#14802]
### Describe the bug

See repro and expectation below.

### To Reproduce

https://docs.risingwave.com/docs/current/risingwave-docker-compose/
```
docker compose up -d

psql -h localhost -p 4566 -d dev -U root

create table t (at timestamptz, v int, cat varchar) with (connector = 'datagen');
```

http://127.0.0.1:9500/
Query the following in prometheus:
```
stream_source_output_rows_counts
{job="standalone-compute"}
{job="standalone-meta"}
```

### Expected behavior

As compared to non-standalone mode:
```
docker compose -f docker-compose-distributed.yml up -d
```
And query for:
```
stream_source_output_rows_counts
{job="compute"}
{job="meta"}
```

We can see `stream_source_output_rows_counts` is part of `compute` in this mode, but part of `standalone-meta` in standalone mode.

### How did you deploy RisingWave?

docker compose

### The version of RisingWave

PostgreSQL 9.5-RisingWave-1.6.0 (71898b4873a32b9df911a8157864100c0dfab27d)

### Additional context

Maybe because the metrics registry is a global static?

**Comment by BugenZhao** [comment]
I guess it's inevitable after we use the single global registry for metrics in #11812. If multiple service is running in the same process, it's hard to distinguish between them.

**Comment by xiangjinwu** [comment]
> I guess it's inevitable after we use the single global registry for metrics in #11812. If multiple service is running in the same process, it's hard to distinguish between them.

If we do not intend to replace the global registry with separated ones, as it may increase code complexity greatly, at least we shall not give an illusion of such separation in prometheus config:
https://github.com/risingwavelabs/risingwave/blob/57d0b0e903d31d3870e43d530481bfdb25a6e8b4/docker/prometheus.yaml#L40-L54

Shall we replace it with a single `risingwave-standalone` entry? Similarly there is no need to expose ports 1222, 1260, 2222 as nothing is there. Do we want to move towards this direction?

cc @fuyufjh

**Comment by kwannoel** [comment]
> > I guess it's inevitable after we use the single global registry for metrics in #11812. If multiple service is running in the same process, it's hard to distinguish between them.
> 
> If we do not intend to replace the global registry with separated ones, as it may increase code complexity greatly, at least we shall not give an illusion of such separation in prometheus config:
> https://github.com/risingwavelabs/risingwave/blob/57d0b0e903d31d3870e43d530481bfdb25a6e8b4/docker/prometheus.yaml#L40-L54
> 
> Shall we replace it with a single `risingwave-standalone` entry? Similarly there is no need to expose ports 1222, 1260, 2222 as nothing is there. Do we want to move towards this direction?
> 
> cc @fuyufjh 

I will take a look at it.
