### ISSUE TITLE
perf: throughput of stateless query with no computation drops 20% over time

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#14815]
Nexmark Q0 does 0 computation: https://github.com/risingwavelabs/kube-bench/blob/main/manifests/nexmark/nexmark-sinks.template.yaml#L14-L18

http://metabase.risingwave-cloud.xyz/question/36-nexmark-q0-blackhole-medium-1cn-affinity-avg-source-output-rows-per-second-rows-s-history-thtb-169?start_date=2023-08-28

![SCR-20240126-klc](https://github.com/risingwavelabs/risingwave/assets/5791930/2b4ccea3-7588-4198-a73e-3b60dfbb55a2)

Based on the CPU flame graph generated weekly, there seems to be significant refactoring in the source/parser:
https://buildkite.com/risingwavelabs/cpu-flamegraph-weekly-cron/builds?branch=main

**Comment by StrikeW** [comment]
Is it run against the nightly image? May related to this PR https://github.com/risingwavelabs/risingwave/pull/14524

**Comment by lmatz** [comment]
> Is it run against the nightly image? May related to this PR #14524

This one seems to be fine by looking at the recent two data points.
(although we cannot determine whether #14524 will not become a bottleneck if other aspects improve to what they used to be)

the drop of throughput mostly happens a while ago

**Comment by lmatz** [comment]
Nexmark `q0, q3, q7-rewrite, q13` are high-throughput queries, i.e. >= 900K/s, that are limited by this performance degradation. cc: @fuyufjh 
They used to be better than the same queries run on other systems.

**Comment by xxchan** [comment]
From the commit history of some spikes, I couldn't find any useful insights. 😟 It's also mysterious that after 0106 it's quite smooth.

**Comment by lmatz** [comment]
2024/02/04:
https://buildkite.com/risingwavelabs/cpu-flamegraph-weekly-cron/builds/64#018d75b8-769f-4b82-8de8-8ddd00c8ef70
![SCR-20240207-hwf](https://github.com/risingwavelabs/risingwave/assets/5791930/e7396f83-3efa-4607-917e-ba68ab7e1c14)


2024/12/12:
https://buildkite.com/risingwavelabs/cpu-flamegraph-weekly-cron/builds/56#018c5cde-51bb-4c01-8ab9-df855978ec61

![SCR-20240207-hwy](https://github.com/risingwavelabs/risingwave/assets/5791930/b32bb110-4943-4caa-b852-56b0cc6c0999)

![SCR-20240207-hxv](https://github.com/risingwavelabs/risingwave/assets/5791930/e3d4d138-73ce-4a76-95fb-b983a4acbdda)
`access_field` was not taking such a large portion?

![SCR-20240207-hxy](https://github.com/risingwavelabs/risingwave/assets/5791930/8eb5097d-bde8-4f1d-bfc4-b0192dcfe5cb)
There is no `generat_accessor` function.

**Comment by tabVersion** [comment]
may relate to https://github.com/risingwavelabs/risingwave/pull/13707/files#r1495536048
it changes parse path to unify parsing the key part for all connectors. 🤔

**Comment by lmatz** [comment]
FYI:
The flame graph comes from the weekly generation pipeline:
https://buildkite.com/risingwavelabs/cpu-flamegraph-weekly-cron

**Comment by lmatz** [comment]
also, execute q0 with an old image `nightly-20230927` (which reach 1.27M/s on 2023-09-27) three times to rule out the possible impact from the testing environment

As we can see from http://metabase.risingwave-cloud.xyz/question/36-nexmark-q0-blackhole-medium-1cn-affinity-avg-source-output-rows-per-second-rows-s-history-thtb-169?start_date=2023-08-28

![SCR-20240221-nad](https://github.com/risingwavelabs/risingwave/assets/5791930/1edd5c7a-ba3e-4676-bb1a-1719ae4b60ec)

the latest three execution of `nightly-20230927` can stably achieve 1.1M/s

**Comment by tabVersion** [comment]
> may relate to [#13707 (files)](https://github.com/risingwavelabs/risingwave/pull/13707/files#r1495536048) it changes parse path to unify parsing the key part for all connectors. 🤔

a more detailed explanation

We use a dedicated json parser for `format plain encode json` before #13707 
https://github.com/risingwavelabs/risingwave/blob/beabcb2b9f8d1380f7b516041fe3b2c0cab5dacc/src/connector/src/parser/mod.rs#L757-L759
It serves as a shortcut as it builds a json parser directly, which does not need to impl the `access` trait. 
https://github.com/risingwavelabs/risingwave/blob/d616c1c677af0f1e9029ef55daee695ee14f82a8/src/connector/src/parser/json_parser.rs#L112-L144 

---

Other parsers, behave like the following 
https://github.com/risingwavelabs/risingwave/blob/beabcb2b9f8d1380f7b516041fe3b2c0cab5dacc/src/connector/src/parser/mod.rs#L775-L779 
which requires concat a `[&str]` to find the right path to each field, leading to some serialization overhead
https://github.com/risingwavelabs/risingwave/blob/beabcb2b9f8d1380f7b516041fe3b2c0cab5dacc/src/connector/src/parser/unified/upsert.rs#L105-L124

after #13707, I deprecate the dedicated plain json parser and unified all format plain parts, resulting in the pref issue.

**Comment by fuyufjh** [comment]
I see. Agree that migrating from `JsonParser` to `PlainParser` is necessary for better code structure.

I am investigating the performance gap between `JsonParser` (faster) and `PlainParser` (slower). Interestingly, both `JsonParser` and `PlainParser` calls `JsonAccess` once to parse the payload.

https://github.com/risingwavelabs/risingwave/blob/6a144670a58d47bbc26ac5748a06d4fdd4227bf9/src/connector/src/parser/json_parser.rs#L127-L128

https://github.com/risingwavelabs/risingwave/blob/6a144670a58d47bbc26ac5748a06d4fdd4227bf9/src/connector/src/parser/plain_parser.rs#L117

Thus, the only `explanation` is that `PlainParser` has additional overhead beyond parsing JSON. I think we need to conduct some micro-benchmarks and CPU profiling to investigate this issue.

**Comment by lmatz** [comment]
Please check the micro-benchmark results in https://github.com/risingwavelabs/risingwave/pull/16526

**Comment by lmatz** [comment]
https://github.com/risingwavelabs/risingwave/pull/16526#issuecomment-2082003260

Is it possible to refactor the code path into a chunk-based one?

We have a delicate vectorized execution engine to amortize constant overhead but the source connector/parser is not part of it.

**Comment by lmatz** [comment]
link #17196 and #12959

**Comment by fuyufjh** [comment]
> link #17196 and #12959

Yes, subsequent investigation was handed over to @xxchan @BugenZhao. Any updates?

**Comment by fuyufjh** [comment]
Resolved by https://github.com/risingwavelabs/kube-bench/pull/453
