### ISSUE TITLE
perf: source throughput & barrier latency of longevity-test is worse than before 

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#14828]
> Summarized from Sack thread: https://risingwave-labs.slack.com/archives/C034TRPKN1F/p1706079713814969

## Background

The recent failures of longevity test all nexmark (8 sets of nexmark queries) with 10k throughput), including

- https://github.com/risingwavelabs/risingwave/issues/14736
- https://github.com/risingwavelabs/risingwave/issues/14712
- https://github.com/risingwavelabs/risingwave/issues/14613

In short, in the past we can pass the test, but recently, it sometimes OOMed. This indicates that RW consume a bit more memory with same workload.

#### 1. Barrier latency became higher

As we know, the barrier latency is an important cause of OOM.

Before: ![before](https://github.com/risingwavelabs/risingwave/assets/10192522/e230c380-335f-42f1-b5c5-55ced899ec20)

After: ![after](https://github.com/risingwavelabs/risingwave/assets/10192522/5f285792-2d67-4325-b22d-c1224afc68ea)

#### 2. Source throughput became lower

The source throughput went down from 6.21 MB/s to 4.x ~ 5.x MB/s

- `nightly-20231225` 6.18 MB/s (18277 rows/s)  [BuildKite](https://buildkite.com/risingwave-test/longevity-test/builds/872)   [Grafana](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=reglngvty-20231225-150220&from=1703525911587&to=1703560610000)
- `nightly-20240122` 15109 rows/s (5.10 MB/s) **(-18% even when q6-group-top1 was EXCLUDED)** [BuildKite](https://buildkite.com/risingwave-test/longevity-test/builds/980)   [Grafana](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=usrlngvty-20240124-085008&from=1706086766000&to=1706130105000)

## Code History

:white_check_mark: **nightly-20240107**  https://buildkite.com/risingwave-test/longevity-test/builds/891
Source throughput: 6.21 MB/s  18400 rows/s
Commit: a01a30dece65f0391210c1a60e6ef17d4270581a

:x: **nightly-20240108** https://buildkite.com/risingwave-test/longevity-test/builds/895
Source throughput: 3.57 MB/s  10566 rows/s
Commit: 414c6ec1c05e3d13aa4842d30624c13b83b9692c

~~Comparing: https://github.com/risingwavelabs/risingwave/compare/a01a30dece65f0391210c1a60e6ef17d4270581a...414c6ec1c05e3d13aa4842d30624c13b83b9692c~~ (see next comment)

**Comment by fuyufjh** [comment]
Wait, this diff includes [feat: embed trace collector & jaeger ui to dev dashboard #14220](https://github.com/risingwavelabs/risingwave/pull/14220)...

The performance impact caused by [#14220](https://github.com/risingwavelabs/risingwave/pull/14220) was expected to be eliminated by [chore: remove some periodical logs #14427](https://github.com/risingwavelabs/risingwave/pull/14427)
but it turns out not.

:x: **nightly-20240109**  https://buildkite.com/risingwave-test/longevity-test/builds/897
Source throughput: 4.66 MB/s    13791 rows/s
Commit: d21d42f9a8ab63a78f67241480c2009ec6f1f61b (including #14427)

It’s slightly better than 20240108 but still worse than before (6.2MB/s)

-----

I am still suspecting distributed tracing. To verify it, I ran [a longevity test](https://buildkite.com/risingwave-test/longevity-test/builds/989) with `nightly-20240125-disable-embedded-tracing` (Commit: 95b4cd3f0b9763c1ac69e5d95904d9f19c4e0cd1).

Sadly, with tracing disabled, the performance is still bad:
- source throughput: 4.75 MB/s (expected: ~6.2MB/s)
- barrier latency was high and laggy (see screenshot below)
[BuildKite](https://buildkite.com/risingwave-test/longevity-test/builds/989#018d44cf-06d0-49f5-b0b0-4a63697b3884)   [Grafana](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=usrlngvty-20240126-080721&from=1706256914000&to=1706300246000)

![image](https://github.com/risingwavelabs/risingwave/assets/10192522/8568aeb5-8a44-4e1e-af2e-71a97da0a7c9)

-----

**Summary at this moment**:

The problem is introduced between https://github.com/risingwavelabs/risingwave/compare/a01a30dece65f0391210c1a60e6ef17d4270581a...d21d42f9a8ab63a78f67241480c2009ec6f1f61b, and it is **not** caused by the distributed tracing (assuming it was truly disabled in the last test.)

**Comment by hzxa21** [comment]
When comparing the grafana metrics between [`reglngvty-20240107-150238`](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1704638311000&orgId=1&to=1704691010000&var-datasource=P2453400D1763B4D9&var-namespace=reglngvty-20240107-150238&var-instance=benchmark-risingwave&var-pod=All&var-component=All&var-table=All) and [`reglngvty-20240108-150225`](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1704724711000&orgId=1&to=1704777410000&var-datasource=P2453400D1763B4D9&var-namespace=reglngvty-20240108-150225&var-instance=benchmark-risingwave&var-pod=All&var-component=All&var-table=All), I didn't see significant differences in barrier latency. Somehow the barrier latency in 0108 was better than 0107
reglngvty-20240107-150238:
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/4599f975-d34b-4b3c-997b-bb704c703bfa)
reglngvty-20240108-150225:
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/1bac571c-fd00-4da7-a360-267236001ddf)


However, the compactor cpu usage and task number was different:
reglngvty-20240107-150238:
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/37be5a62-9fb3-4775-944e-c04ad2b9cff7)
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/e473f3aa-3c87-408e-b728-9c149afe7f13)
reglngvty-20240108-150225:
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/2bd7a63d-a4aa-4008-8a83-1cae016c1bc1)
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/09ab54fa-09d8-4a7d-a1d1-a0cc7a5c7f0b)



I didn't see compactor related changes in https://github.com/risingwavelabs/risingwave/compare/a01a30dece65f0391210c1a60e6ef17d4270581a...414c6ec1c05e3d13aa4842d30624c13b83b9692c. Wonder whether there are changes in the test pipeline.

**Comment by hzxa21** [comment]
May be related: CN OOM very quickly in 0108's test but not in 0107's test. CN OOM can lead to less L0 SSTs generated and thus reduce compaction load. 
reglngvty-20240107-150238:
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/720b0b34-18ca-4cc5-9a3e-abceaed7b6ff)


reglngvty-20240108-150225:
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/ed5a1c63-d35c-48bd-bde9-8b4f72aefe2a)

**Comment by BugenZhao** [comment]
> CN OOM very quickly in 0108's test but not in 0107's test.

Just FYI, this was expected: https://github.com/risingwavelabs/risingwave/issues/14424#issuecomment-1882425498

**Comment by fuyufjh** [comment]
> When comparing the grafana metrics between [`reglngvty-20240107-150238`](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1704638311000&orgId=1&to=1704691010000&var-datasource=P2453400D1763B4D9&var-namespace=reglngvty-20240107-150238&var-instance=benchmark-risingwave&var-pod=All&var-component=All&var-table=All) and [`reglngvty-20240108-150225`](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1704724711000&orgId=1&to=1704777410000&var-datasource=P2453400D1763B4D9&var-namespace=reglngvty-20240108-150225&var-instance=benchmark-risingwave&var-pod=All&var-component=All&var-table=All), I didn't see significant differences in barrier latency. Somehow the barrier latency in 0108 was better than 0107

> May be related: CN OOM very quickly in 0108's test but not in 0107's test. CN OOM can lead to less L0 SSTs generated and thus reduce compaction load.


@hzxa21 Yes, today I just ran a longevity test with [`nightly-20240108-revert-tracing`](https://github.com/risingwavelabs/risingwave/commits/nightly-20240108-revert-tracing/)

So far it runs for about 2 hours, and both the source throughput and barrier latency looks good. [Grafana](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=now-2h&orgId=1&to=now&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=reglngvty-20240128-150208)

<img width="951" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/69ae149b-21f6-465c-b70e-521c9ca73785">

This means that the root cause might be introduced in `nightly-20240109`. https://github.com/risingwavelabs/risingwave/compare/414c6ec1c05e3d13aa4842d30624c13b83b9692c...d21d42f9a8ab63a78f67241480c2009ec6f1f61b

**Comment by fuyufjh** [comment]
The previous conclusion is incorrect. 

The performance impact is expected for versions between `nightly-20240108` (inclusive) and `nightly-20240115` (exclusive), because of the B and E below.

> nightly-20240108
> (A): Accidentally add verbose logs, could affect performance: [feat(cdc): support transaction for shared cdc source](https://github.com/risingwavelabs/risingwave/commit/10f7b7736c1c6f783730e66f6ab1fc0ccd6ea39d) 10f7b7736c1c6f783730e66f6ab1fc0ccd6ea39d
> (B): Tracing introduced. Together with the commit above, will OOM: [feat: embed trace collector & jaeger ui to dev dashboard](https://github.com/risingwavelabs/risingwave/commit/4f6295a3da86cfc4ca3e08667e53f76ed6ecff8f) 4f6295a3da86cfc4ca3e08667e53f76ed6ecff8f
>
> nightly-20240109
> (C): Temporarily fix OOM: [chore: remove some periodical logs](https://github.com/risingwavelabs/risingwave/commit/babfdc9a4650e1b5d78a3676257b8dcc1f182e73) babfdc9a4650e1b5d78a3676257b8dcc1f182e73
> (D): Thoroughly fix OOM, with potential perf overhead of creating more spans. Does no good as long as there’s no parsing failure since (C) already fixes verbose logs: [fix(connector): avoid long-lived tracing span](https://github.com/risingwavelabs/risingwave/commit/fd768daa31f1f7f79965f62eed1e47574f0b85e3) fd768daa31f1f7f79965f62eed1e47574f0b85e3
>
> nightly-20240115:
> Disabled tracing: [feat: enable or disable tracing with system params](https://github.com/risingwavelabs/risingwave/commit/240416f43bae35c11d1d8a6d9e081fdd42fcc6bb) 240416f43bae35c11d1d8a6d9e081fdd42fcc6bb

However, the true cause is shadowed, and is very likely to be between `nightly-20240108` and `nightly-20240115`. I am not doing a binary search to find out it.
