### ISSUE TITLE
panic: some epoch 5851784562212864 older than epoch to seal 5851806452875264

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#14858]
### Describe the bug

The panic happens when running a longevity test with commit `ee444e0e4c54e4fdb5765d123bbfd5a68c9e3eaa`

[Buildkite](https://buildkite.com/risingwave-test/longevity-test/builds/994)
[Grafana metric](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1706516955258&orgId=1&to=1706527465714&var-component=All&var-datasource=P2453400D1763B4D9&var-instance=benchmark-risingwave&var-namespace=usrlngvty-20240129-052314&var-pod=All&var-table=All) 
[Log](https://grafana.test.risingwave-cloud.xyz/explore?orgId=1&panes=%7B%22UAL%22:%7B%22datasource%22:%22PE59595AED52CF917%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22usrlngvty-20240129-052314%5C%22,%20component%3D%5C%22compute%5C%22%7D%20%7C%3D%20%60panicked%20at%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22PE59595AED52CF917%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221706524221616%22,%22to%22:%221706527406968%22%7D%7D%7D&schemaVersion=1)

### Error message/log

```text
2024-01-29 19:18:35.496	
thread 'rw-main' panicked at src/storage/src/hummock/event_handler/uploader.rs:816:13:

2024-01-29 19:18:35.496	
some epoch 5851784562212864 older than epoch to seal 5851806452875264
```

**Comment by hzxa21** [comment]
The panic happened on 19:18 but we did saw another log 7mins ago in 19:11 on the same compute node with prev epoch == the epoch in the above log
```
2024-01-29T19:11:10.832 INFO risingwave_storage::hummock::event_handler::hummock_event_handler: handle clear event. max_committed_epoch: 5851779319136256, max_synced_epoch: 5851779319136256, max_sealed_epoch: 5851781940707328

2024-01-29T19:11:10.905 ERROR risingwave_stream::task::stream_manager: actor exit with error actor_id=20070 error=failed to send message to actor 20065: Barrier(
    Barrier {
        epoch: EpochPair {
            curr: 5851785872736256,
            prev: 5851784562212864,
        },
        mutation: None,
        kind: Barrier,
        tracing_context: TracingContext(
            Context {
                entries: 0,
            },
        ),
        passed_actors: [
            20253,
            20070,
        ],
    },
)
```

**Comment by wenym1** [comment]
The panic never happens again. May have been resolved in the bidi-stream refactor. Close the issue for now. May reopen it when we see the panic again.
