### ISSUE TITLE
Better hint display for sql udf creation

### ISSUE THREAD

**Issue by xzhseh** [risingwavelabs/risingwave#14853]
PostgresSQL has a fairly readable and precise hint if any invalid parameter is used during sql udf's definition time, as shown below.

```
create function better_hint(INT, a INT, INT) returns varchar language sql as $$select $1 + aa + $3$$;
ERROR:  column "aa" does not exist
LINE 1: ...NT) returns varchar language sql as $$select $1 + aa + $3$$;
                                                             ^
```

Our current sql udf implementation does have some hint on the missing item, but the overall error message looks large and heavy, which is also not readable and precise as postgres's, as follows.

```
create function better_hint(INT, a INT, INT) returns varchar language sql as $$select $1 + aa + $3$$;
ERROR:  Failed to run the query

Caused by:
  Invalid input syntax: failed to conduct semantic check, please see if you are calling non-existence functions: Failed to bind expression: $1 + aa + $3: Item not found: Invalid column: aa
```

Thus, it's better that we could have a better hint display especially when an error happens during sql udf's definition time, to help users better understand what's happening under the hood.

**Comment by BugenZhao** [comment]
There has been a similar discussion before on this topic: https://github.com/risingwavelabs/risingwave/pull/14322#issuecomment-1874945974
