### ISSUE TITLE
Delete range tests failed in CI `main-cron`

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#14872]
### Describe the bug

![Screenshot 2024-01-30 at 5 15 11 PM](https://github.com/risingwavelabs/risingwave/assets/47273164/3b093944-b5e1-4ab4-ba7e-24dd4b042d16)
![Screenshot 2024-01-30 at 5 15 21 PM](https://github.com/risingwavelabs/risingwave/assets/47273164/45fdea7b-97bf-455f-bd95-96821c5f6883)

It has failed for a few days now. See Main Cron's e2e test (release).

https://buildkite.com/risingwavelabs/main-cron/builds/1665#018d5626-2f02-47f6-8212-e2d3aede7808

### To Reproduce

Just create a new main-cron build.

**Comment by Little-Wallace** [comment]
Which PR this failure occurs in?

**Comment by kwannoel** [comment]
First buildkite job which failed in main-cron https://buildkite.com/risingwavelabs/main-cron/builds/1623#018d415a-55b3-4b9d-a3a7-cecf4e317ad8
