### ISSUE TITLE
PrivateLink related attributes are denied as unknown fields

### ISSUE THREAD

**Issue by StrikeW** [risingwavelabs/risingwave#14879]
### Describe the bug

```
CREATE SOURCE IF NOT EXISTS live_stream_metrics (
  client_ip varchar,
  user_id varchar,
  report_timestamp timestamp,
)
WITH (
  connector='kafka',
  topic='live_stream_metrics',
  privatelink.endpoint='xxx',
  privatelink.targets='[{"port": 9092}]',
  properties.bootstrap.server='b0-kafka.demosrc.risingwave.internal:9092',
  scan.startup.mode='latest'
) ROW FORMAT JSON
```
`privatelink.targets` is denied as an unknown field.

### Error message/log

```text
"msg": "ERROR: Failed to run the query\n\nCaused by these errors (recent errors listed first):\n  1: gRPC request to meta service failed: Internal error\n  2: Unknown fields in the WITH clause: {\"privatelink.targets\": \"[{\\\"port\\\": 9092}]\"}\n (SQLSTATE XX000)"
```

**Comment by xiangjinwu** [comment]
Related: #13362 (can be similarly as a temporary workaround)

Our current approach of rejecting unknown fields (in `create_source.rs`) is still WRONG - and to be honest I do not have a solution either ... Certain properties (e.g. the one in this issue) are only **used** in compute node but the **check** happens in frontend, assuming most properties shall be used/checked in frontend - which is wrong or hard to maintain. 🥲

**Comment by StrikeW** [comment]
We can try to make these private link attributes as "known" fields to fix this issue.
