### ISSUE TITLE
Build and publish RisingWave binaries for linux arm64

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#14898]

**Comment by kwannoel** [comment]
I think this could be a blocker before we can publish the install script. Otherwise other common architectures will not be supported.

Marking it as priority:high

**Comment by huangjw806** [comment]
Do we need to release the binary of osx?

**Comment by kwannoel** [comment]
> Do we need to release the binary of osx? 

Yes, many users may try it out on their local machine.
Any difficulties?

**Comment by huangjw806** [comment]
> Any difficulties?
@BugenZhao has compiled a binary for mac os before, but he said it doesn’t necessary. I think one of the reasons is that cloud costs more.

**Comment by kwannoel** [comment]
> > Any difficulties?
> 
> @BugenZhao has compiled a binary for mac os before, but he said it doesn’t necessary. I think one of the reasons is that cloud costs more.

We run it once per release, so should be fine?

**Comment by BugenZhao** [comment]
I'm not sure what the motivation of this feature request is... 😕 Can you elaborate more? From my understanding...

- For macOS, users can install RisingWave directly with `brew install risingwave` to download the prebuilt binaries. If one doesn't want it to be in the `PATH`, run `brew unlink`.
- For aarch64 Linux, I guess it's worth to have as we only need to duplicate the workflow for x86_64 linux.

Regarding the installation script, it appears to be an os/arch detector that redirects users to different download targets. I haven't found much necessity for this. macOS users can `brew install`, while Linux users I believe are accustomed to finding and downloading the binary directly. 🤣

**Comment by kwannoel** [comment]
> I'm not sure what the motivation of this feature request is... 😕 Can you elaborate more? From my understanding...
> 
>     * For macOS, users can install RisingWave directly with `brew install risingwave` to download the prebuilt binaries. If one doesn't want it to be in the `PATH`, run `brew unlink`.
> 
>     * For aarch64 Linux, I guess it's worth to have as we only need to duplicate the workflow for x86_64 linux.
> 
> 
> Regarding the installation script, it appears to be an os/arch detector that redirects users to different download targets. I haven't found much necessity for this. macOS users can `brew install`, while Linux users I believe are accustomed to finding and downloading the binary directly. 🤣

Single install script seems most convenient.

@huangjw806 we can just use `brew` for `macOS` users, so it should be fine. We just need the intel arm image.

**Comment by huangjw806** [comment]
> We just need the intel arm image.

Okay, this release will include it.

**Comment by kwannoel** [comment]
Left with releasing the binary itself, that's blocked by:
1. https://github.com/risingwavelabs/risingwave/pull/14951
