### ISSUE TITLE
Regression in bench_table_iterator

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#14908]
reported by @kwannoel 

http://metabase.risingwave-cloud.xyz/dashboard/269?start_date=2023-12-15

![Screenshot_2024-02-01-12-01-24-52_abb9c8060a0a12c5ac89e934e52a2f4f.jpg](https://github.com/risingwavelabs/risingwave/assets/5518566/deca66fa-cd1f-4027-8fa6-2538184b4263)

**Comment by hzxa21** [comment]
@Li0k Can you help take a look?

**Comment by Little-Wallace** [comment]
It just down to 1.5ms 
<img width="1068" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/16376959/8f2a8ab6-c471-4545-930e-f8f94622c0a0">

**Comment by kwannoel** [comment]
Looks to be from an older commit 2 weeks ago, I think @fuyufjh is debugging `main-cron`.

https://buildkite.com/risingwavelabs/main-cron/builds/1769

<img width="1208" alt="Screenshot 2024-02-02 at 6 10 41 PM" src="https://github.com/risingwavelabs/risingwave/assets/47273164/4c2ba90f-ddaf-45a7-908d-fb18c84840bf">

**Comment by Li0k** [comment]
<img width="1182" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/15023748/de9f50ba-7a43-4f54-8683-7133da970d7b">

It looks always unstable after Feb.5 (merge #15002)
