### ISSUE TITLE
Refactor: reuse `single_node` mode for `playground` and `standalone`

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#14997]
- Add a profile for `playground`.
- Add a profile for `standalone` mode.
- Cloud needs to use the new `standalone` profile.
- Docs need to be updated to use the new `playground` profile via `single_node`.
- Docker needs to use the new `standalone` profile.

**Comment by xxchan** [comment]
What about the naming? I quite like `--preset in-memory/local-disk` (or `--profile`) proposed here https://github.com/risingwavelabs/risingwave/pull/14951#pullrequestreview-1861839079.

And maybe we can reuse `standalone` as the command name? (just like implement the `map_opts` feature directly on top of old `standalone` mode.

**Comment by kwannoel** [comment]
> What about the naming? I quite like `--preset in-memory/local-disk` (or `--profile`) proposed here [#14951 (review)](https://github.com/risingwavelabs/risingwave/pull/14951#pullrequestreview-1861839079).

Yes, `profile`.

> And maybe we can reuse `standalone` as the command name? (just like implement the `map_opts` feature directly on top of old `standalone` mode.

Yes, after we deprecate `standalone`, we can use `single-node` as an alias, and rename it to `standalone`.

**Comment by xxchan** [comment]
> Yes, `profile`.

I mean the profiles' names. e.g., I like `in-memory` better than `playground` 🥺

**Comment by kwannoel** [comment]
> > Yes, `profile`.
> 
> I mean the profiles' names. e.g., I like `in-memory` better than `playground` 🥺

Yes, I prefer:
- in-memory (playground)
- persistent (single-node)


For `standalone` mode, can just choose either and supply `extra-args` for further configuration.

**Comment by fuyufjh** [comment]
We may remove playground mode in the future. Users who want to take a try of RW can just use single-node mode.

Discussing here https://risingwave-labs.slack.com/archives/C05TXGYUL6N/p1708578235388599?thread_ts=1707372310.943919&cid=C05TXGYUL6N
