### ISSUE TITLE
Forbid changes to protobuf structs' field names that are persited in meta

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#15030]
SQL meta store relies on the name of fields. (serialized to JSON)

https://github.com/risingwavelabs/risingwave/blob/64b4cc30a46c8fb461cf46d2c6c0709d062f1495/src/meta/model_v2/src/lib.rs#L193-L227

We need to ~~revert this change and~~ set the check level back to `WIRE_JSON`
<https://github.com/risingwavelabs/risingwave/pull/8365>

[Slack Message](https://risingwave-labs.slack.com/archives/C0340PNL68P/p1707202561980249?thread_ts=1707201402.341129&cid=C0340PNL68P)

Maybe we can only change the level for `meta.proto` without changing others'. (That may need us to split the proto into modules and apply different `buf.yaml`?)

**Comment by xiangjinwu** [comment]
https://protobuf.dev/programming-guides/dos-donts/#text-format-interchange
> **Don’t** use Text Format Messages for Interchange
> Use binary serialization when possible for data interchange, and use text format for human **editing** and **debugging** only.
