### ISSUE TITLE
OOMKilled  during backfill test with no tombstones

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#15047]
buildkite: https://buildkite.com/risingwave-test/backfill/builds/319#018d7fcc-2073-40c6-b9f6-69022747fed4
Sql for backfill tests: https://github.com/risingwavelabs/kube-bench/blob/main/manifests/backfill/backfill-sql.template.yaml

K8s Describe Pods Before Delete Namespace:

![Screenshot 2024-02-07 at 5 38 22 PM](https://github.com/risingwavelabs/risingwave/assets/47273164/62e4f896-7df7-4ce9-8da0-83afb5ca4748)

**Comment by kwannoel** [comment]
All these batch selects return too many results perhaps?

https://github.com/risingwavelabs/kube-bench/blob/main/manifests/backfill/backfill-sql.template.yaml

```
stat.sql: |
    SELECT * FROM backfill_stat;
  batch-query.sql: |
    SELECT * FROM backfill;
  mv-query.sql: |
    SELECT * FROM backfill_mv;
```

**Comment by cyliu0** [comment]
So is this expected? @kwannoel

**Comment by kwannoel** [comment]
> So is this expected? @kwannoel

Sorry, didn't have time to look at it. But I think it is OOM. Could you change the `select *` from backfill and backfill_mv into `select count(*)` instead?

**Comment by kwannoel** [comment]
https://buildkite.com/risingwave-test/backfill/builds/346#018dd231-e9dc-4192-bd06-6cd663d61585

Can see from the most recent logs:

<img width="1076" alt="Screenshot 2024-02-23 at 12 04 31 PM" src="https://github.com/risingwavelabs/risingwave/assets/47273164/bf39dd26-8285-4950-a712-9803c10e4903">


It fails when we run the batch queries.

**Comment by kwannoel** [comment]
I don't think we need to `select * from backfill_stat` as well. That's to view tombstone metrics. We can avoid running that command as well.
