### ISSUE TITLE
Make storage micro benchmarks stable

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#15061]
Currently, in the microbenchmarks workflow, there are several benchmarks which fluctuate quite a bit.

We should either:
1. Disable them entirely.
2. Make them run stably.

Examples:
- http://metabase.risingwave-cloud.xyz/dashboard/257
- Full dashboard http://metabase.risingwave-cloud.xyz/dashboard/273-micro-benchmark-execution-duration?start_date=2023-12-01

**Comment by lmatz** [comment]
https://github.com/risingwavelabs/risingwave-test/issues/607
will add the notification to slack @XXX and open GitHub issues once the assignee is determined
