### ISSUE TITLE
Discussion: Can UDF expression cause inconsistency when UDF server fails?

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#15092]
When UDF server fails, we insert null values.
Consider that this is updatable stream, in that case when running updates / deletes, the `null` value can lead to panics due to inconsistent state:
```
insert udf(1) -> null (fails initially)
delete udf(1) -> 3 (succeeds later) this can cause panic due to inconsistent state, since no such value (3) exists.
```

Not sure how to deal with this case yet.

We also need a reproduction of it first. I think can just create a UDF server, kill it to force null values being emitted, restart it, update some values.

**Comment by kwannoel** [comment]
Seems we have to drop and recreate mv in that scenario.

**Comment by BugenZhao** [comment]
This may apply to all expressions that are impure, whether deliberate or accidental (like `NULL` padding on temporary failures). There's an unimplemented RFC for this: https://github.com/risingwavelabs/rfcs/pull/24

**Comment by kwannoel** [comment]
Can we add a config to always retry on UDF server error? I.e. block the entire stream graph, until UDF server is back online.

**Comment by kwannoel** [comment]
Added the config #15303
