### ISSUE TITLE
bug(storage): barrier read may return duplicate full key

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#15099]
### Describe the bug

Root cause found by @Little-Wallace 

Let's say there are read version 1 = [imm1], and read version 2 = [imm2]. Full key 1 is in imm 2.
1. imm1 and imm2 are compacted into SST1. So full key 1 is in SST1 too.
2. read version 1's imm1 is [replaced by SST1](https://github.com/risingwavelabs/risingwave/blob/90aa90a48b0534002eb4e37a0a102532ce12fc65/src/storage/src/hummock/store/version.rs#L277), so read version 1 = [SST1].
3. A barrier read will visit [SST1, imm2], where SST1 is from version 1 and imm2 is from read version 2. 
4. Full key 1 will be read twice, which violates [Epoch from the same user key should be monotonically decreasing](https://github.com/risingwavelabs/risingwave/blob/90aa90a48b0534002eb4e37a0a102532ce12fc65/src/storage/hummock_sdk/src/key.rs#L1036).

The root cause is [read versions are not updated atomically](https://github.com/risingwavelabs/risingwave/blob/90aa90a48b0534002eb4e37a0a102532ce12fc65/src/storage/src/hummock/event_handler/hummock_event_handler.rs#L318).

### Impact of the bug

The issue is revealed by the FullKeyTracker introduced in #14488. It'll panic whenever the issue occurs.

Before FullKeyTracker is introduced, UserIterator will only expose one kv entry with the latest epoch. **So there will be no correctness issue**, CMIIW

**Comment by hzxa21** [comment]
Some ideas to resolve the issue:
1. Disable barrier read completely.
2. Atomically update all read versions.
3. Use only one read version for each storage table read. The storage table implementation already guarantees that only one vnode will be touched in each iter: https://github.com/risingwavelabs/risingwave/blob/4197ad50c766c8d086d29948ef34e13582e72251/src/storage/src/table/batch_table/storage_table.rs#L468

**Comment by hzxa21** [comment]
@zwang28 @Little-Wallace Where did we see this issue happening? Given that the default visibility mode is checkpoint, I guess it is from some tests where visibility mode is set to ALL explicitly?

**Comment by hzxa21** [comment]
> Some ideas to resolve the issue:
> 
> 1. Disable barrier read completely.
> 2. Atomically update all read versions.
> 3. Use only one read version for each storage table read. The storage table implementation already guarantees that only one vnode will be touched in each iter: https://github.com/risingwavelabs/risingwave/blob/4197ad50c766c8d086d29948ef34e13582e72251/src/storage/src/table/batch_table/storage_table.rs#L468



I am working on solution 3.

**Comment by wenym1** [comment]
@hzxa21 I think https://github.com/risingwavelabs/risingwave/pull/15289 has resolved this issue?
