### ISSUE TITLE
set nexmark benchmark for temporal join with high cache miss rate

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#15124]

**Comment by TennyZhuang** [comment]
This may be difficult because NEXMark has good locality since the data is generated, which is a business characteristic. Unless we use some tricks like limiting memory to a very small amount, I don't think this makes much sense. Perhaps we can write some queries or use cases with lower locality.

**Comment by st1page** [comment]
There are some NEXMark query not having good locality such as q20, I guess we can jsut change them to temporal join

**Comment by lmatz** [comment]
> There are some NEXMark query not having good locality such as q20, I guess we can jsut change them to temporal join

Great


I am also adding a new Kube-bench pipeline that uses RW's datagen to ingest data into Kafka first and then run customized queries reading from Kafka, I will try to finish the basics soon
so everyone can add more stuff into it.
