### ISSUE TITLE
bug: wrong results when doing aggregation on system tables without primary key

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#15125]
```sql
dev=> select count(oid) from pg_cast;
 count 
-------
    83
(1 row)

dev=> select oid from pg_cast group by oid;
 oid 
-----
  82
(1 row)

dev=> explain select oid from pg_cast group by oid;
                            QUERY PLAN                            
------------------------------------------------------------------
 BatchSimpleAgg { aggs: [internal_last_seen_value(pg_cast.oid)] }        <= ?!
 └─BatchScan { table: pg_cast, columns: [oid] }
(2 rows)
```

**Comment by fuyufjh** [comment]
Is this issue completed by https://github.com/risingwavelabs/risingwave/pull/15126?

**Comment by BugenZhao** [comment]
> Is this issue completed by #15126?

Kind of. #15126 only enforced the primary keys specified for all system tables. All system tables we've supported do have unique key columns so it was possible to do that.

However, if we're going to introduce a system table without primary key in the future, we still need to figure out how to resolve such issue, by either making the primary key field optional in `TableDesc`, or generating a `row_id` column for those tables.
