### ISSUE TITLE
Support client-side Load Balancer for external UDF service

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#15138]
https://github.com/risingwavelabs/risingwave/commit/13fc8cca0f214ca84a7c007d7c0e1db4784ee082
https://github.com/risingwavelabs/risingwave/commit/405765b92c4f0d9bb11fab87d7c9b243fe006150

It's already supported in a branch, thanks to work from @KeXiangWang and @arkbriar 's suggestions.

We should support in `main` as well.

**Comment by kwannoel** [comment]
We must only upgrade jindo's cluster to the release that has this patch OR create a special release for them which includes this.

**Comment by KeXiangWang** [comment]
Yes, I've reminded yufan(owner of cluster upgrading for the customer) to ping me before upgrading.
