### ISSUE TITLE
bug: inconsistency table info between catalog and hummock in meta node

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#15144]
### Describe the bug

We've encountered this bug several times:
1. Compactor nodes keep failing task because [inconsistency table info between catalog and hummock manager](https://github.com/risingwavelabs/risingwave/blob/be30f20e2c14b5d12efd5b33a4ac9e537602fc37/src/storage/src/hummock/compactor/compactor_runner.rs#L340).
2. After restarting meta node, the issue is gone. It works due to the [rectification process](https://github.com/risingwavelabs/risingwave/blob/be30f20e2c14b5d12efd5b33a4ac9e537602fc37/src/meta/src/hummock/manager/compaction_group_manager.rs#L152) during meta node startup.

In meta node, whenever a table is remove from catalog, it must [notify hummock manager](https://github.com/risingwavelabs/risingwave/blob/be30f20e2c14b5d12efd5b33a4ac9e537602fc37/src/meta/src/hummock/manager/compaction_group_manager.rs#L382) as well. Otherwise it could lead to the issue above. So I suspect there is a corner case that doesn't follow this rule, during dropping a stream job.

**Comment by hzxa21** [comment]
I found several suspicious things:
1. In ddl_controller_v2.rs [drop_object](https://github.com/risingwavelabs/risingwave/blob/4197ad50c766c8d086d29948ef34e13582e72251/src/meta/src/rpc/ddl_controller_v2.rs#L260), catalog is dropped first ([here](https://github.com/risingwavelabs/risingwave/blob/4197ad50c766c8d086d29948ef34e13582e72251/src/meta/src/rpc/ddl_controller_v2.rs#L286)) before `unregister_table_ids_fail_fast` is called ([here](https://github.com/risingwavelabs/risingwave/blob/4197ad50c766c8d086d29948ef34e13582e72251/src/meta/src/rpc/ddl_controller_v2.rs#L423)).
2. In [drop_streaming_jobs_v2](https://github.com/risingwavelabs/risingwave/blob/4197ad50c766c8d086d29948ef34e13582e72251/src/meta/src/stream/stream_manager.rs#L557), `unregister_table_ids_fail_fast` will not be called if `removed_actors` is empty
3. in drop_streaming_job_v1, catalog is dropped first ([here](https://github.com/risingwavelabs/risingwave/blob/4197ad50c766c8d086d29948ef34e13582e72251/src/meta/src/rpc/ddl_controller.rs#L1188)) before `unregister_table_fragments_vec` is called ([here](https://github.com/risingwavelabs/risingwave/blob/4197ad50c766c8d086d29948ef34e13582e72251/src/meta/src/stream/stream_manager.rs#L608))

**Comment by zwang28** [comment]
> I found several suspicious things:
> 
> 1. In ddl_controller_v2.rs [drop_object](https://github.com/risingwavelabs/risingwave/blob/4197ad50c766c8d086d29948ef34e13582e72251/src/meta/src/rpc/ddl_controller_v2.rs#L260), catalog is dropped first ([here](https://github.com/risingwavelabs/risingwave/blob/4197ad50c766c8d086d29948ef34e13582e72251/src/meta/src/rpc/ddl_controller_v2.rs#L286)) before `unregister_table_ids_fail_fast` is called ([here](https://github.com/risingwavelabs/risingwave/blob/4197ad50c766c8d086d29948ef34e13582e72251/src/meta/src/rpc/ddl_controller_v2.rs#L423)).
> 2. In [drop_streaming_jobs_v2](https://github.com/risingwavelabs/risingwave/blob/4197ad50c766c8d086d29948ef34e13582e72251/src/meta/src/stream/stream_manager.rs#L557), `unregister_table_ids_fail_fast` will not be called if `removed_actors` is empty
> 3. in drop_streaming_job_v1, catalog is dropped first ([here](https://github.com/risingwavelabs/risingwave/blob/4197ad50c766c8d086d29948ef34e13582e72251/src/meta/src/rpc/ddl_controller.rs#L1188)) before `unregister_table_fragments_vec` is called ([here](https://github.com/risingwavelabs/risingwave/blob/4197ad50c766c8d086d29948ef34e13582e72251/src/meta/src/stream/stream_manager.rs#L608))
> 4. `unregister_table_fragments_vec` is called at the end of [drop_streaming_jobs_impl](https://github.com/risingwavelabs/risingwave/blob/4197ad50c766c8d086d29948ef34e13582e72251/src/meta/src/stream/stream_manager.rs#L577). This means if there is an error happening earlier (e.g. `barrier_scheduler.run_command(Command::DropStreamingJobs)` fails due to CN failure or long barrier latency), we may miss to unregister table ids.


[The recovery process should always take care of the clean up](https://github.com/risingwavelabs/risingwave/blob/8323b17ff5e3e66e9f79eeba99971622c5908471/src/meta/src/stream/stream_manager.rs#L544), e.g. even if [drop_streaming_jobs_impl](https://github.com/risingwavelabs/risingwave/blob/4197ad50c766c8d086d29948ef34e13582e72251/src/meta/src/stream/stream_manager.rs#L577) returns early.

**Comment by zwang28** [comment]
refactored in #15852

**Comment by zwang28** [comment]
The issue still occurs in v1.8.
