### ISSUE TITLE
nightly-20240220 nexmark perf degradation

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#15169]
### Describe the bug

```
+---------------------------------------------------------------+--------------+------------+---------------------+-----------------------------+
| BENCHMARK NAME                                                | EXECUTION ID | STATUS     | FLUCTUATION OF BEST | FLUCTUATION OF LAST 10 DAYS |
+---------------------------------------------------------------+--------------+------------+---------------------+-----------------------------+
| nexmark-q17-blackhole-medium-1cn                              |        21038 | Negative   | -28.64%             | -14.31%                     |
| nexmark-q5-rewrite-blackhole-medium-1cn                       |        21047 | Negative   | -31.09%             | -19.14%                     |
| nexmark-q19-blackhole-medium-1cn                              |        21053 | Negative   | -23.29%             | -11.83%                     |
| nexmark-q105-blackhole-medium-1cn                             |        21088 | Negative   | -30.68%             | -12.06%
```
http://metabase.risingwave-cloud.xyz/dashboard/241-nexmark-blackhole-1cn-anti-affinity-rw-avg-source-throughput?start_date=2024-02-01&namespace=daily

## nightly-20240220
- `4197ad50c766c8d086d29948ef34e13582e72251` [feat(object store): introduce new s3 object store via OpenDAL (#14409)](https://github.com/risingwavelabs/risingwave/pull/14409)
- `06572cfe221cb127e94aef5b908931aee4be1ba9` [fix(cdc): enable cdc transaction for shared source only (#14946)](https://github.com/risingwavelabs/risingwave/pull/14946)
- `b1ffbafcd2d8a27297aebccb603e1c393f3b5c8f` [refactor: rename `TO_TIMESTAMP{,1}` in expr.proto for clarity (#15143)](https://github.com/risingwavelabs/risingwave/pull/15143)
- `6739733daa3de7c24261a94eec134f346e96b7e3` [fix(storage): remove unnecessary metadata io during list (#15133)](https://github.com/risingwavelabs/risingwave/pull/15133)

**Comment by lmatz** [comment]
I suppose #14409 OpenDAL is not enabled in the daily test yet, see: https://github.com/risingwavelabs/kube-bench/pull/368

Then the only PR (suppose the regression is indeed caused by kernel changes) can only be #15133. Do you think it is possible to lead to such a big regression? @zwang28 

The other two, #14946 affects the CDC source only, and #15143 is purely renaming.

**Comment by st1page** [comment]
The queries all are CPU intensive(more than 750/800 CPU usage) and I do not find any IO performance difference. We can generate the CPU flame graph later if we can not find the issue on the PR side.

**Comment by zwang28** [comment]
> Then the only PR (suppose the regression is indeed caused by kernel changes) can only be https://github.com/risingwavelabs/risingwave/pull/15133. Do you think it is possible to lead to such a big regression? 

No. This PR only affect openDAL.

**Comment by st1page** [comment]
> https://buildkite.com/risingwavelabs/cpu-flamegraph/builds/31 https://buildkite.com/risingwavelabs/cpu-flamegraph/builds/32

No significant difference between the two flame graph...

**Comment by st1page** [comment]
check if it can be reproduced 
```
BENCH_NAMESPACE="sts_rerun0220"
BENCH_TESTBED="medium-1cn"
CI="true"
ENABLE_BLACKHOLE="true"
LABELS="medium-1cn-anti-affinity"
NEXMARK_QUERY="q5-rewrite,q17,q19,q105"
RW_VERSION="nightly-20240220"
```

https://buildkite.com/risingwave-test/nexmark-benchmark/builds/3105

**Comment by st1page** [comment]
> check if it can be reproduced
> 
> ```
> BENCH_NAMESPACE="sts0220"
> BENCH_TESTBED="medium-1cn"
> CI="true"
> ENABLE_BLACKHOLE="true"
> LABELS="medium-1cn-anti-affinity"
> NEXMARK_QUERY="q5-rewrite,q17,q19,q105"
> RW_VERSION="nightly-20240220"
> ```
> 
> https://buildkite.com/risingwave-test/nexmark-benchmark/builds/3106

The reruned result comes back 😇

**Comment by lmatz** [comment]
q5:https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1708453098000&to=1708454903000&var-namespace=nexmark-bs-0-14-daily-20240220

![SCR-20240222-mp4](https://github.com/risingwavelabs/risingwave/assets/5791930/2780949f-3bdf-42e9-8a04-7e9365019cb2)
task failure

**Comment by lmatz** [comment]
nexmark-q17-blackhole-medium-1cn:
https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1708450421000&to=1708452226000&var-namespace=nexmark-bs-15-105-daily-20240220

![SCR-20240222-mre](https://github.com/risingwavelabs/risingwave/assets/5791930/11ed7665-deca-408e-9fec-6dd745b5362f) 

but this one occurs at the end I suppose should not have so much impact(-14%)?

**Comment by lmatz** [comment]
nexmark-q19-blackhole-medium-1cn:
https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1708454470000&to=1708456275000&var-namespace=nexmark-bs-15-105-daily-20240220

![SCR-20240222-mso](https://github.com/risingwavelabs/risingwave/assets/5791930/df1aa267-caec-4ecb-9449-13d509b05a19)

**Comment by lmatz** [comment]
q105:
https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1708507846000&to=1708509652000&var-namespace=nexmark-kafka-benchmark-20240221-075859

![SCR-20240222-muu](https://github.com/risingwavelabs/risingwave/assets/5791930/dcc261d0-04f9-4697-b88a-7e486582e834)
seems ok?

**Comment by Li0k** [comment]
q105

<img width="1511" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/15023748/eababf8f-68d1-4fe9-b007-9e01b139a4d4">

Base level compaction always skip.

<img width="1115" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/15023748/a9dc5cde-45ef-41ed-a44e-ce33bd1e226f">

I found that a task hangs for a long time without being canceled, which is why the task can't be picked.

<img width="1119" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/15023748/24821afc-103f-4a81-aade-fb0e18f9d8a5">


fix pr : https://github.com/risingwavelabs/risingwave/pull/15194

**Comment by lmatz** [comment]
I suppose #15194 only fixed the problem in q105, but not the compaction task failure shown in q17 and q19, right? @Li0k
