### ISSUE TITLE
feat: report streaming errors during backfilling to user's frontend session 

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#15179]
### Is your feature request related to a problem? Please describe.

For `create materialized view` on tables or materialized views, the user's frontend session is holding there, so we have a chance to return error to users directly beside printing in logs.

(PS. It will also help `create materialized view` on sources and `create sink` if they are running on foreground. We are considering whether we should make it default.)

### Describe the solution you'd like

https://github.com/risingwavelabs/risingwave/pull/13441 has sorted out the root cause of a failed streaming job. What we need to do is passing that error to user's frontend session.

### Additional context

Discussed in Slack: https://risingwave-labs.slack.com/archives/C06B3SEQQQ1/p1708504056642089?thread_ts=1708489235.143729&cid=C06B3SEQQQ1

**Comment by BugenZhao** [comment]
> so we have a chance to return error to users directly

If an unhandled error causes an actor to exit unexpectedly, a recovery process will be triggered. If everything goes well, the error message should be reported to all pending notifiers in the barrier manager and then sent back to the frontend. After #13441, the accuracy of the error message can be further improved.

So I'm wondering if you're talking about...

- some corner cases that this does not work as expected,
- or the errors that are tolerated under non-strict mode (IMO only expression errors in this case)

**Comment by yezizp2012** [comment]
#13441 will endeavor to collect and identify the errors responsible for causing the actor to exit unexpectedly. If such an error occurs during the collection stage of the DDL barrier, it can be accurately relayed to the frontend through notify_collection_failed. 
However, if it arises during backfill, the frontend will only receive a "channel closed" error. #13108 aims to rectify this by returning the actual error instead, but it is outdated due to recent refactorings that have been introduced. I will update it accordingly.

**Comment by BugenZhao** [comment]
> However, if it arises during backfill, the frontend will only receive a "channel closed" error.

Could you elaborate more on why it behaves differently?

**Comment by yezizp2012** [comment]
> > However, if it arises during backfill, the frontend will only receive a "channel closed" error.
> 
> Could you elaborate more on why it behaves differently?

https://github.com/risingwavelabs/risingwave/pull/13108/files#diff-ac2c1a39c20cb7f9efdf2e5422d7856c92c9b856098bc0c4580bccd0bb5597aa

Currently the finish channel will be dropped directly during recovery, and no further result info will be sent to stream manager and then passing to frontend.

**Comment by fuyufjh** [comment]
Duplicated #13035
