### ISSUE TITLE
feat: support `create index if not exist` statement

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#15189]
### Is your feature request related to a problem? Please describe.

It seems that since Postgresql 9.5, this statement is available:https://dba.stackexchange.com/questions/35616/create-index-if-it-does-not-exist

proposed by an existing customer

**Comment by xiangjinwu** [comment]
Supported by #5747 but not reflected in the doc https://github.com/risingwavelabs/risingwave-docs/issues/1869
