### ISSUE TITLE
Add info about primary keys in the pg_catalog.pg_constraint view

### ISSUE THREAD

**Issue by LonwoLonwo** [risingwavelabs/risingwave#15197]
### Is your feature request related to a problem? Please describe.

In the recent DBeaver version, we added support for the RisingWave connector.
In the database navigator tree, we can see table columns and indexes but not the primary keys.

![2024-02-22 13_09_02-DBeaver Ultimate 23 3 5 - pg_constraint](https://github.com/risingwavelabs/risingwave/assets/45152336/d7b3c679-0386-4993-b599-107fb347cb1d)

![2024-02-22 13_09_43-DBeaver Ultimate 23 3 5 - newtable](https://github.com/risingwavelabs/risingwave/assets/45152336/918659e7-38b7-4eaf-8ab5-e6da9e1bd058)

Because pg_catalog.pg_constraint view is empty. And we use it for primary keys metadata reading.

For now, I can only find my key in the DDL statement. I didn't find anything like the SHOW KEYS command in the documentation.

### Describe the solution you'd like

It will be helpful to have primary keys info in pg_catalog.pg_constraint view.

### Describe alternatives you've considered

The SHOW PRIMARY KEYS command. But it is usually not so convenient to use it for the whole schema.

### Additional context

My current database version: PostgreSQL 9.5-RisingWave-1.6.0

**Comment by fuyufjh** [comment]
> For now, I can only find my key in the DDL statement. I didn't find anything like the SHOW KEYS command in the documentation.

May use following commands

```
dev=> DESCRIBE newtable;
       Name        |   Type   | Is Hidden | Description
-------------------+----------+-----------+-------------
 column1           | bigint   | false     |
 primary key       | column1  |           |
 distribution key  | column1  |           |
 table description | newtable |           |
(4 rows)

dev=> select * from rw_catalog.rw_columns where relation_id = 17001;
 relation_id |  name   | position | is_hidden | is_primary_key | is_distribution_key | data_type | type_oid | type_len | udt_type
-------------+---------+----------+-----------+----------------+---------------------+-----------+----------+----------+----------
       17001 | column1 |        1 | f         | t              | t                   | bigint    |       20 |        8 | int8
(1 row)
```
