### ISSUE TITLE
bug(storage): read block seems to be stuck

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#15239]
### Describe the bug

In a cluster using Google Cloud Storage, according to await tree, 
- [fetch_block](https://github.com/risingwavelabs/risingwave/blob/be30f20e2c14b5d12efd5b33a4ac9e537602fc37/src/storage/src/hummock/block_cache.rs#L108) sometimes gets stuck for 5hours before manually terminating it. 
- And it's not uncommon fetch_block takes over 10 seconds to finish.

### Error message/log

Will keep the await tree when encountered next time.

### The version of RisingWave

v1.6.1

### Additional context

- Heavy workload. The barrier typically takes over one hour to finish, if the stuck issue doesn't occurs.
- Over 10k actors per compute node.
- 40 CPU and 200GB memory per. compute node.

**Comment by hzxa21** [comment]
What is value of object_store_read_timeout? By default it is 8mins. Like #15209, It seems that the timeout didn't trigger as well.

**Comment by zwang28** [comment]
> object_store_read_timeout

In v1.6.1, object_store_read_timeout is 1hour. But the specific fetch_block hangs for several hours.

**Comment by Xuanwo** [comment]
OpenDAL has native await-tree support, please enable it for more information.

**Comment by hzxa21** [comment]
Potential root cause found:
https://github.com/risingwavelabs/risingwave/issues/15209#issuecomment-1963618701
