### ISSUE TITLE
better query rewrite for TPC-H q17

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#15247]
Yes, I can not find a way to rewrite it... But it should ok for Q17 because the aggregator is an AVG,  we should choose one to optimize #14799 
- maintain the AVG and other similar aggregator in plan node and delay their rewriting(currently RW rewrites it when creating the Agg plan node)
- consider the project-agg together in the rule later

_Originally posted by @st1page in https://github.com/risingwavelabs/risingwave/pull/15026#discussion_r1480885874_
            

link #14799

**Comment by st1page** [comment]
> consider the project-agg together in the rule later

prefer this, because some predicate `sum(v) * 0.02 > count(v)` sounds reasonable to me.
