### ISSUE TITLE
pg_catalog.pg_user schema changed

### ISSUE THREAD

**Issue by huangjw806** [risingwavelabs/risingwave#15250]
This is the query cloud currently uses to retrieve RW users：
https://github.com/risingwavelabs/risingwave-cloud/blob/f284f602a5fe097d9e230a809546576ffdd6ee30/mgmt/internal/risingwave/rwdb/user.go#L102
```
SELECT * FROM pg_catalog.pg_user WHERE name != 'root' AND name != 'postgres';
ERROR:  Failed to run the query

Caused by these errors (recent errors listed first):
  1: Failed to bind expression: name <> 'root' AND name <> 'postgres'
  2: Item not found: Invalid column: name
```

schema of the current table：

```
SELECT * FROM pg_catalog.pg_user;
 usesysid | usename  | usecreatedb | usesuper |  passwd
----------+----------+-------------+----------+----------
        1 | root     | t           | t        | ********
        2 | postgres | t           | t        | ********
```

**If we change the scheme for system tables, I think we should try to synchronize it to the cloud, or have relevant documentation.**

**Comment by huangjw806** [comment]
caused by this pr:
https://github.com/risingwavelabs/risingwave/pull/14947

**Comment by huangjw806** [comment]
This may require version control for cloud to distinguish them.

**Comment by yezizp2012** [comment]
Oh, this should have been defined incorrectly when it was defined before. It should be consistent with PostgreSQL and has been fixed in the recent refactoring. We should be careful about the schema changes for system catalogs and should synchronize it to the cloud if necessary.

**Comment by huangjw806** [comment]
> Oh, this should have been defined incorrectly when it was defined before. It should be consistent with PostgreSQL and has been fixed in the recent refactoring. We should be careful about the schema changes for system catalogs and should synchronize it to the cloud if necessary.

This may require version control for cloud to distinguish them.

**Comment by wjf3121** [comment]
@yezizp2012, I left some question in the cloud linear issue: https://linear.app/risingwave-labs/issue/CLOUD-2423/bug-adapt-the-schema-change-of-the-pg-user-system-table#comment-e7c425aa

PTAL when you have time.
