### ISSUE TITLE
Sink to BigQuery with google pubsub sink

### ISSUE THREAD

**Issue by docteurklein** [risingwavelabs/risingwave#15306]
### Is your feature request related to a problem? Please describe.

Given the level of integration with pubsub between the different GCP components (cloud run, eventarc, dataflow, bigquery, workflows, ...), having a pubsub sink would be highly beneficial.
I'm currently missing this to take advantage of the pubsub bigquery CDC feature as documented here: https://cloud.google.com/pubsub/docs/bigquery.

### Describe the solution you'd like

I'd like a sink wose definition would look like: 

```sql
CREATE SINK sink1 FROM mv1
WITH (
   connector='google_pubsub',
   topic='topic1'
)
FORMAT PLAIN ENCODE JSON; -- possibly AVRO  [1]
```
[1] https://cloud.google.com/pubsub/docs/samples/pubsub-publish-avro-records

### Describe alternatives you've considered

I tried to use the native RW bigquery sink, but it's using the legacy [tabledata.insertAll](https://cloud.google.com/bigquery/docs/reference/v2/tabledata/insertAll) method, which is not compatible with the CDC message ingestion.

### Additional context

opening the issue here as discussed in https://github.com/orgs/risingwavelabs/discussions/15237

**Comment by neverchanje** [comment]
https://github.com/risingwavelabs/risingwave/pull/16363 will resolve this issue.
