### ISSUE TITLE
too aggressive and early cache eviction

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#15305]
> The eviction at the beginning of both tests is too aggressive.
The eviction starts even when there is still quite much memory.

first posted here TPC-H q20: https://github.com/risingwavelabs/risingwave/issues/14797#issuecomment-1966549273

will collect a few more examples when encountering

**Comment by lmatz** [comment]
TPC-H q4: https://github.com/risingwavelabs/risingwave/issues/14811#issuecomment-1970434260
has very similar observation

**Comment by lmatz** [comment]
TPC-H q17: https://github.com/risingwavelabs/risingwave/issues/14799#issuecomment-2002970895 also has a very similar observation

**Comment by lmatz** [comment]
Repost observation and experiments done by @MrCroxx  for better visibility:

[output.xlsx](https://1drv.ms/x/s!AiJJmrmsw_N2mw2I91hKxSoYJtHh?e=FDY5nF)


There are three observations:
1. uneven data among different epochs when that epoch gets evicted.

![SCR-20240325-ipl](https://github.com/risingwavelabs/risingwave/assets/5791930/861b8731-696f-4e22-88f8-624fde96f19a)


2. a single eviction of multiple epochs and the size of data evicted is huge
![SCR-20240325-iq5](https://github.com/risingwavelabs/risingwave/assets/5791930/7e3f2ab3-07dc-4f59-9d73-0e5243c0b058)


3. a single eviction of a single epoch and the size of data evicted is huge
![SCR-20240325-ir3](https://github.com/risingwavelabs/risingwave/assets/5791930/1edfba36-3825-4318-a90e-6f3694557779)


> For phenomena 1 and 2, there was a speculation that each time an entry is accessed, the entry's epoch is increased, causing older epoch data to gradually decrease, leading to evicting data with fewer older epochs first. After evicting several epochs and finding that memory did not decrease, a more aggressive exponential evicting of epochs began, ultimately resulting in the eviction of data from epochs with a larger amount of newer data.

> This speculation may explain the issue when the barrier frequency is high. However, for phenomenon 3 observed in the 10-second barrier experiment mentioned above, it seems more like there are too few epochs to adequately partition the eviction scope.

> In the future, I will try other strategies such as incorporating epochs and quotas, using quotas only without epochs, or exploring alternative strategies.

**Comment by MrCroxx** [comment]
The evicted bytes by epoch (summed by all LRUs):

https://1drv.ms/x/s!AiJJmrmsw_N2mxGoFZbGAYSRGstJ?e=B76XvA

<img width="1390" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/22407295/c8d765f9-3585-4174-827a-dc99fbf532d3">
