### ISSUE TITLE
chaos mesh daily test: ch-benchmark-pg-cdc data verification failed

### ISSUE THREAD

**Issue by xuefengze** [risingwavelabs/risingwave#15312]
Chaos-mesh test failed(ch-benchmark-pg-cdc). The experiment made the meta unavailable for 20 seconds.
```
================================================================================
chaos-mesh Result
================================================================================
Result               FAIL                
Pipeline Message     Nightly ch-benchmark-pg-cdc
Namespace            longcmkf-20240227-190312
TestBed              medium-arm-all-affinity
RW Version           nightly-20240227    
Test Start time      2024-02-27 19:07:23 
Test End time        2024-02-27 19:50:13 
Test Queries         q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q17,q18,q19,q20,q21,q22
Grafana Metric       https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=longcmkf-20240227-190312&from=1709060843000&to=1709063413000
Grafana Logs         https://grafana.test.risingwave-cloud.xyz/d/liz0yRCZz1/log-search-dashboard?orgId=1&var-data_source=Logging:%20test-useast1-eks-a&var-namespace=longcmkf-20240227-190312&from=1709060843000&to=1709063413000
Memory Dumps         https://s3.console.aws.amazon.com/s3/buckets/test-useast1-mgmt-bucket-archiver?region=us-east-1&bucketType=general&prefix=k8s/longcmkf-20240227-190312/&showversions=false
Buildkite Job        https://buildkite.com/risingwave-test/chaos-mesh/builds/629
```
Data verification fails:
```
revenue1 table/mv data checksum inconsistent
ch_benchmark_q4 table/mv data checksum inconsistent
order_line table/mv data checksum inconsistent
```
```
================================================================================
chaos-mesh Result
================================================================================
Result               FAIL                
Pipeline Message     Nightly ch-benchmark-pg-cdc
Namespace            longcmkf-20240227-195152
TestBed              medium-arm-all-affinity
RW Version           nightly-20240227    
Test Start time      2024-02-27 19:54:13 
Test End time        2024-02-27 21:53:46 
Test Queries         q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q17,q18,q19,q20,q21,q22
Grafana Metric       https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=longcmkf-20240227-195152&from=1709063653000&to=1709070826000
Grafana Logs         https://grafana.test.risingwave-cloud.xyz/d/liz0yRCZz1/log-search-dashboard?orgId=1&var-data_source=Logging:%20test-useast1-eks-a&var-namespace=longcmkf-20240227-195152&from=1709063653000&to=1709070826000
Memory Dumps         https://s3.console.aws.amazon.com/s3/buckets/test-useast1-mgmt-bucket-archiver?region=us-east-1&bucketType=general&prefix=k8s/longcmkf-20240227-195152/&showversions=false
Buildkite Job        https://buildkite.com/risingwave-test/chaos-mesh/builds/629
```

Data verification fails:
```
revenue1 table/mv data checksum inconsistent
ch_benchmark_q10 table/mv data checksum inconsistent
order_line table/mv data checksum inconsistent
stock table/mv data checksum inconsistent
```

**Comment by xuefengze** [comment]
link https://github.com/risingwavelabs/risingwave/issues/15245 https://github.com/risingwavelabs/risingwave/issues/15190 https://github.com/risingwavelabs/risingwave/issues/15279

**Comment by StrikeW** [comment]
There is a null ptr issue in the log, which has been [fixed](https://github.com/risingwavelabs/risingwave/pull/15834) in release-1.8, I suggest we rerun the pipeline with new image.
<img width="600" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/7338536/a99ec4b1-aa29-45d7-91ff-b69ad55cf3dc">

**Comment by xuefengze** [comment]
```
BENCH_TESTBED="medium-arm-all-affinity"
CH_BENCHMARK_QUERY="q1,q2,q3,q4"
RW_VERSION="nightly-20240331"
BENCHMARK_TYPE="tpcc-pg-cdc"
duration="10m"
experiments="[{'kind': 'PodChaos', 'actions': ['pod-failure'], 'duration': '20s', 'cases': [{'mode': ['one'], 'label': {'key': 'risingwave/component', 'value': 'meta'}}]}]"
```
test failed with share source.
https://buildkite.com/risingwave-test/chaos-mesh/builds/716

**Comment by StrikeW** [comment]
I found same [error logs](https://grafana.test.risingwave-cloud.xyz/explore?panes=%7B%22c82%22:%7B%22datasource%22:%22PE59595AED52CF917%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcomponent%3D%5C%22compute%5C%22,%20namespace%3D%5C%22longcmkf-20240401-034537%5C%22%7D%20%7C~%20%60%28Cannot%20seek%20to%20the%20last%20known%20offset%7Cadvance%29%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22PE59595AED52CF917%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221711944000000%22,%22to%22:%221711947599000%22%7D%7D%7D&schemaVersion=1&orgId=1) as in the #15141.
We are working a fix patch to try to fix the issue, tracked in #15464

**Comment by StrikeW** [comment]
Hi @xuefengze, please rerun the test with `RW_VERSION=cdc-commit-offset`, which is the image of https://github.com/risingwavelabs/risingwave/pull/16058

**Comment by xuefengze** [comment]
https://buildkite.com/risingwave-test/chaos-mesh/builds/730#018eb902-b9e8-44f1-83a4-058cc8232d99
compute-0 got panicked when running q3
<img width="1115" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/73645462/92a2422c-9864-4bb2-b20a-3dcbea37469b">

**Comment by StrikeW** [comment]
I run the chaos test with the image built by https://github.com/risingwavelabs/risingwave/pull/16058, the `Cannot seek to the last known offset` [WARN logs are gone](https://grafana.test.risingwave-cloud.xyz/explore?panes=%7B%22Iee%22:%7B%22datasource%22:%22PE59595AED52CF917%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcomponent%3D%5C%22compute%5C%22,%20namespace%3D%5C%22longcmkf-20240410-030746%5C%22%7D%20%7C~%20%60%28cannot%20seek%7Cadvance%29%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22PE59595AED52CF917%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221712718000000%22,%22to%22:%221712721599000%22%7D%7D%7D&schemaVersion=1&orgId=1), but [q4](https://buildkite.com/risingwave-test/chaos-mesh/builds/741#018ec5f9-120c-435e-8c76-863c3162c81e) still encounter source table inconsistent with upstream. Still investigating.

**Comment by hzxa21** [comment]
This time there are more rows in the RW tables:
```
<html>
<body>
<!--StartFragment-->
{
--
  | "consistent": false,
  | "table-checksums": [
  | {
  | "url": "postgres://postgres:postgres@localhost:5432/postgres",
  | "table-name": "history",
  | "table-checksum": 8546249372229983623,
  | "table-rows": 46500
  | },
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "table-name": "history",
  | "table-checksum": 1784133604083324500,
  | "table-rows": 46541
  | }
  | ]
  | },
  | {
  | "consistent": false,
  | "table-checksums": [
  | {
  | "url": "postgres://postgres:postgres@localhost:5432/postgres",
  | "table-name": "new_order",
  | "table-checksum": -758467578028615202,
  | "table-rows": 17
  | },
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "table-name": "new_order",
  | "table-checksum": -5196837531638814068,
  | "table-rows": 23
  | }
  | ]
  | },
  | {
  | "consistent": false,
  | "table-checksums": [
  | {
  | "url": "postgres://postgres:postgres@localhost:5432/postgres",
  | "table-name": "orders",
  | "table-checksum": 5892817120355204331,
  | "table-rows": 140849
  | },
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "table-name": "orders",
  | "table-checksum": 9047804123778707166,
  | "table-rows": 141184
  | }
  | ]
  | },
  | {
  | "consistent": false,
  | "table-checksums": [
  | {
  | "url": "postgres://postgres:postgres@localhost:5432/postgres",
  | "table-name": "order_line",
  | "table-checksum": 7067257756083074964,
  | "table-rows": 1408500
  | },
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "table-name": "order_line",
  | "table-checksum": 8647488982357384687,
  | "table-rows": 1412341
  | }
  | ]
  | },

<!--EndFragment-->
</body>
</html>
```

**Comment by StrikeW** [comment]
I also run against the nightly image ([750](https://buildkite.com/risingwave-test/chaos-mesh/builds/750)), the symptom is same: RW rows is more than upstream pg.

**Comment by stdrc** [comment]
During a previous refactor to source parser, I found a possible cause of cdc offset rewind, which according to @StrikeW is possibly a reason of this issue. The bug case is that, if there's always a transaction beginning in the middle of a source message batch, and ending in the next batch, we'll always yield stream chunks immediately when the transaction is committed. Then heartbeat messages to update offset can possibly be delayed forever. After a series of such transactions, the earliest heartbeat message may get emitted, but the offset may be invalid then.

I created a PR #16608 to fix this bug. Let's hope it can fix this issue🙏

**Comment by StrikeW** [comment]
> During a previous refactor to source parser, I found a possible cause of cdc offset rewind, which according to @StrikeW is possibly a reason of this issue. The bug case is that, if there's always a transaction beginning in the middle of a source message batch, and ending in the next batch, we'll always yield stream chunks immediately when the transaction is committed. Then heartbeat messages to update offset can possibly be delayed forever. After a series of such transactions, the earliest heartbeat message may get emitted, but the offset may already be invalid then.
> 
> I created a PR #16608 to fix this bug. Let's hope it can fix this issue🙏

I am building an image for the branch, let's see whether the issue can be fixed.

**Comment by StrikeW** [comment]
I run the chaos mesh test against the PR, but it fails in q3.
https://buildkite.com/risingwave-test/chaos-mesh/builds/816#018f5610-37ba-450c-8c59-067fa74e648e

But the [nightly](https://buildkite.com/risingwave-test/chaos-mesh/builds/815#018f560e-ac3b-4222-b4b3-614496357288) image can pass the test.

I think we should take a look before merge the PR.

**Comment by hzxa21** [comment]
@StrikeW Is the issue fixed?

**Comment by StrikeW** [comment]
> @StrikeW Is the issue fixed?

chaos mesh pipeline didn't fail for a long time, I think we can close this issue and open new issues if the pipeline fails.
