### ISSUE TITLE
`test_backfill_tombstone` failed in `main-cron` backfill tests: `key UserKey { 1004, TableKey { 0000008558294d8b000000 } } epoch EpochWithGap(6017238017507328) >= prev epoch EpochWithGap(6017238017507328)`

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#15324]
buildkite: https://buildkite.com/risingwavelabs/main-cron/builds/1899#018deb4c-29e0-4ad8-a9a9-bc7c5ea713a4

Compute node logs:
<img width="1282" alt="Screenshot 2024-02-28 at 1 33 23 PM" src="https://github.com/risingwavelabs/risingwave/assets/47273164/9d1d0180-0837-47c4-ab85-61a20c40938d">

You can run the tests locally, see `ci/scripts/run-backfill-tests.sh`.

The test which fails is:
```
e2e, test_backfill_tombstone
```

You can comment out the other tests at the bottom of the file while debugging.

**Comment by kwannoel** [comment]
```
2024-02-27T16:22:45.072413567Z  WARN risingwave_stream::executor::dml: txn_id=4294967296 Too many chunks for atomicity. Sent them to the downstream anyway.
thread 'rw-compaction' panicked at /risingwave/src/storage/hummock_sdk/src/key.rs:1047:21:
key UserKey { 1004, TableKey { 0000008558294d8b000000 } } epoch EpochWithGap(6017238017507328) >= prev epoch EpochWithGap(6017238017507328)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panicking.rs:72:14
   2: observe_multi_version<bytes::bytes::Bytes, bytes::bytes::Bytes, core::iter::adapters::map::Map<core::slice::iter::Iter<(risingwave_hummock_sdk::EpochWithGap, risingwave_storage::hummock::value::HummockValue<bytes::bytes::Bytes>)>, risingwave_storage::hummock::compactor::shared_buffer_compact::merge_imms_in_memory::{async_fn#0}::{closure_env#0}>>
   3: {async_fn#0}
             at ./src/storage/src/hummock/compactor/shared_buffer_compact.rs:335:38
   4: poll<risingwave_storage::hummock::compactor::shared_buffer_compact::merge_imms_in_memory::{async_fn_env#0}>
```

**Comment by hzxa21** [comment]
Is there any recent change to the test itself? I saw that the test can still pass [yesterday](https://buildkite.com/risingwavelabs/main-cron/builds/1896). I checked the diff commits and didn't see any suspicious changes.

The assertion should never be hit regardless.

**Comment by kwannoel** [comment]
> Is there any recent change to the test itself? I saw that the test can still pass [yesterday](https://buildkite.com/risingwavelabs/main-cron/builds/1896). I checked the diff commits and didn't see any suspicious changes.
> 
> The assertion should never be hit regardless.

Last change seems to be 28 days ago. I think it may not happen every run perhaps. It depends on compaction which may not happen deterministically.
