### ISSUE TITLE
feature request: default visibility_mode as a system parameter

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#15322]
### Is your feature request related to a problem? Please describe.

https://risingwave-community.slack.com/archives/C05U5NV4LHY/p1709036227434699

> Hi again, is it possible to set the visibility_mode runtime parameter to be “all” by default for all client sessions? In many of our use-cases we will have clients querying the latest real-time data from RisingWave MV’s and thus would need to set the visibility_mode to “all” to achieve this currently on each connection.

### Describe the solution you'd like

Provide a system parameter `visibility_mode`, which can override the default value of session variable `visible`

### Describe alternatives you've considered

The requirements also apply to many other session variables, such as `isolation_level`, `query_mode`, etc. Is it possible to build a common framework?

```
preset default value <-- system parameter <-- session variable
// Arrows mean overriding if set.
```

**Comment by xiangjinwu** [comment]
related: #8851 #13554

**Comment by BugenZhao** [comment]
> The requirements also apply to many other session variables, such as `isolation_level`, `query_mode`, etc. Is it possible to build a common framework?

This sounds like similar to the configuration framework in Postgres, which supports setting variables in different levels: https://www.postgresql.org/docs/current/config-setting.html#CONFIG-SETTING-SQL

The `context` column in `pg_settings` table also reflect that: https://www.postgresql.org/docs/current/view-pg-settings.html#VIEW-PG-SETTINGS
