### ISSUE TITLE
bug: assert_table_creating failed

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#15357]
### Describe the bug

[This assertion](https://github.com/risingwavelabs/risingwave/blob/8cb91531cb1e8a9a49d835aacd4fad441874ba2f/src/meta/src/manager/catalog/mod.rs#L800) failed, in a [PR](https://github.com/risingwavelabs/risingwave/pull/15355) that I'm confident is irrelevant.

https://buildkite.com/risingwavelabs/pull-request/builds/43236#018df385-918d-46ba-bb40-34488b551160

[recovery-ddl-8.log](https://github.com/risingwavelabs/risingwave/files/14443776/recovery-ddl-8.log)

**Comment by kwannoel** [comment]
Didn't get a chance to look at it this week. Look at this next week.

**Comment by kwannoel** [comment]
Oh this assertion occurs during `finish_create_stream_job`. Looks like a race condition. Where we should clean `6016`, however later `finish_create_stream_job` also triggers.

In this case we should just make `finish_create_stream_job` fail.

**Comment by kwannoel** [comment]
@yezizp2012 has already fixed it in `main`: https://github.com/risingwavelabs/risingwave/blob/786b10b98a7b6859b84c784313f919a5f0bb16f0/src/meta/src/manager/catalog/mod.rs#L800-L809.

So just need to rebase your PR on `main`.
