### ISSUE TITLE
Iceberg sink may not support upsert actually

### ISSUE THREAD

**Issue by MarkLeiSource** [risingwavelabs/risingwave#15393]
### Describe the bug

When I create an Iceberg sink with type "upsert", and do some delete query like "delete from users where name = 'Walker'; ", there is even no further invoke to Iceberg rest catalog service, not to mention anything changed on Minio S3 bucket.

### Expected behavior

Delete data may work as something like "tombstone for the key".

### The version of RisingWave

1.7.0

#### To create table by pyiceberg
from pyiceberg.catalog import load_catalog

catalog = load_catalog(
"rest_backend",
{
"s3.endpoint": "http://",
"py-io-impl": "pyiceberg.io.pyarrow.PyArrowFileIO",
"s3.access-key-id": "",
"s3.secret-access-key": "***",
}
)

catalog.create_tables()
catalog.create_namespace("demo")

from pyiceberg.schema import Schema
from pyiceberg.types import (
TimestampType,
StringType,
NestedField,
IntegerType,
)

schema = Schema(
NestedField(field_id=1, name="datetime", field_type=TimestampType(), required=True),
NestedField(field_id=2, name="name", field_type=StringType(), required=True),
NestedField(field_id=3, name="age", field_type=IntegerType(), required=False)
)

from pyiceberg.partitioning import PartitionSpec, PartitionField
from pyiceberg.transforms import DayTransform

partition_spec = PartitionSpec(
PartitionField(
source_id=1, field_id=1000, transform=DayTransform(), name="datetime_day"
)
)

from pyiceberg.table.sorting import SortOrder, SortField
from pyiceberg.transforms import IdentityTransform
sort_order = SortOrder(SortField(source_id=2, transform=IdentityTransform()))

catalog.create_table(
identifier="demo.users",
schema=schema,
location="s3://pyiceberg",
partition_spec=partition_spec,
sort_order=sort_order,
properties={'format-version': '2'}
)

#### To create table and sink on risingwave
CREATE public.users (
datetime timestamp,
name varchar,
age int4
);

CREATE SINK iceberg_sink FROM users
WITH (
connector = 'iceberg',
catalog.type = 'rest',
type='upsert',
s3.region='east-us',
warehouse.path = 's3://pyiceberg',
catalog.uri = 'http://',
s3.endpoint = 'http://',
s3.access.key = '',
s3.secret.key = '',
database.name='demo',
table.name='users',
primary_key='datetime'
);

-- insert some test data
insert into users values (now(), 'Walker', 12);
-- remove the test data
delete from users where name='Walker';
-- select the test data from risingwave
select * from public.users where name='Walker';

_Here I get no record from the table in RisingWave as expect._

#### To load table data by pyiceberg
from pyiceberg.catalog import load_catalog

catalog = load_catalog(
"rest_backend",
{
"s3.endpoint": "http://",
"py-io-impl": "pyiceberg.io.pyarrow.PyArrowFileIO",
"s3.access-key-id": "",
"s3.secret-access-key": "***",
}
)
table = catalog.load_table("demo.users")
con = table.scan(
).to_duckdb(table_name="users")

print(
con.execute(
"SELECT * from users"
).fetchall()
)

_The user Walker would not be deleted in Iceberg._

**Comment by liurenjie1024** [comment]
Yes, provide concrete reproducible step.

**Comment by MarkLeiSource** [comment]
> Could you please give a minimal reproducible code example to help us identify the issue? I think it is possible that your delete statement doesn't delete any records from the upstream, so nothing else needs to be sent downstream. cc @liurenjie1024

Added concrete reproducible steps.
