### ISSUE TITLE
bug: `cpu-flamegraph-weekly-cron` fails

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#15394]
### Describe the bug

```

promql
--
  | >>> Run Sanity check that PromQL is installed
  | promql version v0.2.1
  | >>> Installing Kafka
  | --2024-03-03 20:04:54--  https://downloads.apache.org/kafka/3.4.1/kafka_2.13-3.4.1.tgz
  | Resolving downloads.apache.org (downloads.apache.org)... 88.99.208.237, 135.181.214.104, 2a01:4f9:3a:2c57::2, ...
  | Connecting to downloads.apache.org (downloads.apache.org)\|88.99.208.237\|:443... connected.
  | HTTP request sent, awaiting response... 404 Not Found
  | 2024-03-03 20:04:55 ERROR 404: Not Found.
```

https://buildkite.com/risingwavelabs/cpu-flamegraph-weekly-cron/builds/68#018e05e8-6042-4415-af0b-eb4bb823c618

**Comment by lmatz** [comment]
guess it's better to have another(if there really is) URL to download the Kafka, so that we can choose the second option if the first one fails

**Comment by xiangjinwu** [comment]
It seems that
* https://downloads.apache.org/kafka/ contains the 3 most recent minor versions (currently 3.7.x, 3.6.x and 3.5.x, with 3.4.x too old)
* https://archive.apache.org/dist/kafka/ contains all versions including the most recent ones.
