### ISSUE TITLE
feat: hide credentials from `show create source/table`

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#15402]
### Is your feature request related to a problem? Please describe.

Hide credentials (passwords, secret keys, etc.) from the results of `show create source/table`. Otherwise, the plain-text password would be a terrible security issue for users.

### Describe alternatives you've considered

Furthermore, we should encrypt the stored credentials as well, but that's another issue.

**Comment by BugenZhao** [comment]
Seems duplicated with #14115. There's a work in progress for this issue: #14760

**Comment by fuyufjh** [comment]
Duplicated https://github.com/risingwavelabs/risingwave/issues/14115
