### ISSUE TITLE
pg-incompatibility(sqlparser/binder): `user` shall be reserved from being column name, and quoting shall switch its meaning

### ISSUE THREAD

**Issue by yuhao-su** [risingwavelabs/risingwave#15477]
Original title: bug: binding problem when struct field having the same name with system info function e.g. user 

```
CREATE TABLE t (
    user STRUCT < 
    id VARCHAR>
);
```

```
CREATE MATERIALIZED VIEW mv AS 
SELECT 
(user).id AS id FROM t;
ERROR:  Failed to run the query

Caused by these errors (recent errors listed first):
  1: Failed to bind expression: (user).id
  2: Bind error: column notation .id applied to type character varying, which is not a composite type
```

This happens because when binding `user`, it is seen as a system info function with return type character...

**Comment by xiangjinwu** [comment]
As a reference, this is the behavior of PostgreSQL 16 regarding builtin `user` vs column `user`:
```
test=# create table t (user int); -- word `user` is reserved
ERROR:  syntax error at or near "user"
LINE 1: create table t (user int);
                        ^

test=# create table t ("user" int); -- use reserved word by quoting
CREATE TABLE

test=# insert into t values (42);
INSERT 0 1

test=# select user + 1 from t; -- by default, resolves to builtin and reports data type error
ERROR:  operator does not exist: name + integer
LINE 1: select user + 1 from t;
                    ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

test=# select t.user + 1 from t; -- qualifying with table name works (quoting also works)
 ?column? 
----------
       43
(1 row)
```

**Comment by yuhao-su** [comment]
Postgres can work around this by adding double quote on `user`

```
SELECT 
("user").id AS id FROM t;
```
will work in pg but not risingwave

**Comment by xiangjinwu** [comment]
As shown above, the current workaround is to use `t.user`, which is valid in both PostgreSQL and RisingWave.

As for reserving `user` as a keyword and allow its usage with quoting (so that we are fully aligned with PostgreSQL), it would be a **breaking change**.

**Comment by xiangjinwu** [comment]
Closing as wont fix for now given a workaround exists, and a full fix would be trading PostgreSQL-RisingWave-compatibility at the cost of losing RisingWave-backward-compatibility. Will reconsider this when more cases arise.

We do need to provide extra help on troubleshooting these special parentheses-less "functions". Will open a doc issue for it.
