### ISSUE TITLE
Single node tests failing  `e2e_test/visibility_mode/../batch/./catalog/rw_depend.slt.part`

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#15482]
<img width="1032" alt="Screenshot 2024-03-06 at 2 36 15 PM" src="https://github.com/risingwavelabs/risingwave/assets/47273164/028e7dc6-52e7-4e05-b458-09cfdb2a427e">

https://buildkite.com/risingwavelabs/main-cron/builds/1968#018e0de1-7e1a-4451-b233-80e49b58f083

**Comment by yezizp2012** [comment]
Oh, we haven't support `rw_depend` in sql-backend yet. I will add it.

**Comment by fuyufjh** [comment]
Encountered the same error today

<img width="716" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/c359062c-a694-4db3-acb3-66c8a27af708">

https://buildkite.com/risingwavelabs/main-cron/builds/1998#018e1853-6ba2-4bd3-9692-41f724ab21f8
