### ISSUE TITLE
Support parquet format for file source

### ISSUE THREAD

**Issue by wcy-fdu** [risingwavelabs/risingwave#15509]
### Is your feature request related to a problem? Please describe.

We have introduced iceberg source, if user want to load file in iceberg, iceberg source is the best choice. 
For users who store some parquet file in object store instead of iceberg, they should use file source to load these parquet files. Batch reading file source is supported recently, and we need to support the parquet format as well.

**Comment by fuyufjh** [comment]
@wcy-fdu Any updates? cc. @chenzl25

**Comment by wcy-fdu** [comment]
> @wcy-fdu Any updates? cc. @chenzl25

Since we already have a relatively complete iceberg source, this requirement is not of high priority and will be implemented after more specific user requirements are met. I just forgot to remove the release milestone label.
