### ISSUE TITLE
MySQL CDC wide table backfill sync failed

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#15500]
### Describe the bug

Two 50k rows wide tables synced from MySQL CDC. One succeeded, and one failed. This is 100% reproducible. A strange phenomenon is that the detail table can be synced in streaming test.
```
dev=> select count(1) from realtime_waybill_detail;
 count
-------
     0
(1 row)

dev=> select count(1) from realtime_waybill_cost_fee;
 count
-------
 50000
(1 row)
```

Namespace: wide-table-mysql-cdc
[Grafana](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&from=1709713994057&to=1709714051399&var-datasource=ebec273b-0774-4ccd-90a9-c2a22144d623&var-namespace=wide-table-mysql-cdc&var-instance=benchmark-risingwave&var-pod=All&var-component=All&var-table=All)

<img width="1895" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/89f2b77b-a4e9-43dd-b223-7a835899500d">

### The version of RisingWave

nightly-20240229

### Additional context

Please contact @cyliu0 if you need the table schema which is confidential.

**Comment by StrikeW** [comment]
The problem should be the duration of snapshot read for external table is larger than the default barrier interval. I added logs to print out the duration (in ms) for yielding each snapshot chunk, which is larger than 1000ms.
<img width="640" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/7338536/a9da8093-58d1-43cb-9bdb-834325011875">

I change the  [barrier interval to 5mins](https://buildkite.com/risingwave-test/wide-table/builds/28#018e1cf7-f849-40e1-9ed7-12fbea88b131), then the `detail` table can be synced into RW.

```
dev=> select * from __internal_realtime_waybill_detail_7_streamcdcscan_1006;
 split_id | waybill_no | backfill_finished | row_count |                           cdc_offset
----------+------------+-------------------+-----------+-----------------------------------------------------------------
 1005     | 9999       | t                 |     50000 | {"MySql": {"filename": "binlog.000004", "position": 140841043}}
(1 row)

dev=> select count(*) from realtime_waybill_detail;
 count
-------
 50000
(1 row)

dev=> select * from __internal_realtime_waybill_cost_fee_3_streamcdcscan_1004;
 split_id | waybill_no |    creater_time     | backfill_finished | row_count |                           cdc_offset
----------+------------+---------------------+-------------------+-----------+-----------------------------------------------------------------
 1003     | 9999       | 2024-01-01 23:06:33 | t                 |     50000 | {"MySql": {"filename": "binlog.000004", "position": 140841043}}
(1 row)

dev=> select count(*) from realtime_waybill_cost_fee;
 count
-------
 50000
(1 row)
```

We need to devise a new approach to backfill historical data which can tolerate high latency of snapshot read.

**Comment by cyliu0** [comment]
@StrikeW Another problem is that the users can recognize the historical data is not syncing when they try to compare it with the upstream data only. Should we find a way to tell the users we have some problems with the data sync?

**Comment by StrikeW** [comment]
> @StrikeW Another problem is that the users can recognize the historical data is not syncing when they try to compare it with the upstream data only. Should we find a way to tell the users we have some problems with the data sync?

Right now user can query the internal table of `_streamcdcscan_` to know the progress of backfilling, not need to count the table.

**Comment by cyliu0** [comment]
> Right now user can query the internal table of `_streamcdcscan_` to know the progress of backfilling, not need to count the table.

Need to enhance the doc? Or provide the metrics in the Grafana dashboard?

**Comment by lmatz** [comment]
> Need to enhance the doc? Or provide the metrics in the Grafana dashboard?

I imagine something similar to the existing Kafka consumer lag size on Grafana should work for users, but wonder if it is possible.

I guess the current CDC latency cannot work for this case because it requires at least one row successfully CDCed from upstream to RW so that it then can calculate, right?

**Comment by cyliu0** [comment]
> I guess the current CDC latency cannot work for this case because it requires at least one row successfully CDCed from upstream to RW so that it then can calculate, right?

The current CDC latency is for streaming instead of backfill

**Comment by StrikeW** [comment]
> > Right now user can query the internal table of `_streamcdcscan_` to know the progress of backfilling, not need to count the table.
> 
> Need to enhance the doc? Or provide the metrics in the Grafana dashboard?

We have a paragraph describing how to check the backfilling progress.
https://docs.risingwave.com/docs/current/ingest-from-mysql-cdc/#create-multiple-cdc-tables-with-the-same-source
