### ISSUE TITLE
Config source not to warn when a field does not exists and fail to parse

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#15525]
Currently, when parsing data from an external system, if some fields do not exist in the message, RW will warn in the log like `risingwave_connector::parser: failed to parse non-pk column, padding with NULL error=Undefined field xxx at `` split_id="0" offset="12345678" column="xxx"`.

But in some cases, as a semi-structured data source, missing some fields in the message could be expected. In that case, the warning log is confusing and tons of warnings might make the user miss something important

Maybe we can have a config in the WithOption to let user declare that the case is expected and RW does not need to warn.

**Comment by splix** [comment]
I can add some context, as I originally raised this question.

In my case, it's a Kafka topic with JSON messages. One of the fields is optional, so I expect it to be `null` in queries and views. And it works like that, but it's confusing to see this warning in the logs every second and especially with the `WARN` level.

**Comment by xiangjinwu** [comment]
Previous discussion: #13328 It ended up with log rate limit, but not completely suppressed.

**Comment by st1page** [comment]
> > in the WithOption
> 
> Shall be format encode option?

Oh, sure. format encode option is more reasonable

**Comment by tabVersion** [comment]
Will lower the log level to `info`
