### ISSUE TITLE
improve coverage of with_options_sink.yaml

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#15537]
I just realized that with options for cassandra sink are not included in this yaml. Let's revisit other sinks as well to ensure all sinks are covered.
_Originally posted by @hzxa21 in https://github.com/risingwavelabs/risingwave/pull/15516#discussion_r1517132044_

**Comment by xxhZs** [comment]
Here it's because we only support similar logic for rust's sinks, and given that we have fewer and fewer java implementations of sinks, it's not clear if we'll still have to implement this check for java_sink

**Comment by hzxa21** [comment]
Fair enough. I will close this issue for now.
