### ISSUE TITLE
bug(metrics): multiple actor of the same fragment report the same kafka partition's `report_latest_message_id` when parallelism > partition count.

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#15540]
But actually, only one actor works and provides the real offset.
![image](https://github.com/risingwavelabs/risingwave/assets/40830455/b5f2bd1a-fc6a-4b9f-9420-78707ad8a69e)

**Comment by st1page** [comment]
There is the same issue on the source throughput.
![image](https://github.com/risingwavelabs/risingwave/assets/40830455/5e6cffdd-d7c4-40fc-84c4-ac3557366f0e)

**Comment by st1page** [comment]
There is a similar issue in the source throughput
![image](https://github.com/risingwavelabs/risingwave/assets/40830455/ba67184f-da60-424f-9bde-69c91254abfa)

**Comment by xxchan** [comment]
What's the expected behavior?
