### ISSUE TITLE
Use blocking (foreground) DDL for source and sinks

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#15587]
## Background

We know that `create mv on table/mv` must wait until the backfilling completed by default, otherwise, the newly created MV cannot be consistent with its upstream, which breaks RisingWave's consistency guarantee as well as PG compatibility.

However, regarding of sink and sources, we have to define the behavior. The acceptable options include:

1. `create mv on table/mv` blocks until backfilling completed. `create mv on source` and `create sink` returns immediately. 
2. `create mv on table/mv/source` blocks until backfilling completed. `create sink` returns immediately. 
3. `create mv on table/mv/source` and `create sink` all block until backfilling completed. 🥇

According to [a poll in Slack channel](https://risingwave-labs.slack.com/archives/C03A2PSS8KU/p1708502509138489), option 3 wins.

Another advantage of blocking DDL is that the errors can be explicitly returned to users. On the contrary, a failure during background DDL happens after the object becomes available to users, thus, it can only be printed to logs, which is much more difficult for users. 

Initial motivation: https://risingwave-labs.slack.com/archives/C06B3SEQQQ1/p1708499966310609?thread_ts=1708489235.143729&cid=C06B3SEQQQ1

## Tasks

We have already report the errors during DDL to frontend sessions. https://github.com/risingwavelabs/risingwave/pull/13108

The remaining task is to adjust the default behavior - Use blocking (foreground) DDL for source and sinks for both `create mv on table/mv/source` and `create sink` by default.

Note that this task only changes the default behavior. If users specify `set background_ddl = true` manually, we should follow it as usual.

**Comment by BugenZhao** [comment]
Is #14172 a prerequisite for this task?

**Comment by lmatz** [comment]
will `background ddl` support `create index`?

**Comment by kwannoel** [comment]
> will `background ddl` support `create index`?

Yes eventually.

**Comment by kwannoel** [comment]
I think https://github.com/risingwavelabs/risingwave/issues/13035 is a prerequisite for this.

To me this is the main benefit:
> Another advantage of blocking DDL is that the errors can be explicitly returned to users. On the contrary, a failure during background DDL happens after the object becomes available to users, thus, it can only be printed to logs, which is much more difficult for users.

> Is https://github.com/risingwavelabs/risingwave/pull/14172 a prerequisite for this task?
I suppose so. I think only sources with backfill will support it. For source created w/o backfill, we can just return immediately.
So for now it will just be supported for cdc backfill.

**Comment by xxchan** [comment]
+1 that "errors can be explicitly returned to users" is the largest benefit.

> I think https://github.com/risingwavelabs/risingwave/issues/13035 is a prerequisite for this.

Similarly for sources, we also tolerate errors extensively. e.g.,

https://github.com/risingwavelabs/risingwave/blob/e3f3fb8f89bbb4879855297f65965fdcc4f8eb9d/src/stream/src/executor/source/source_executor.rs#L438-L443

Note that sometimes the errors are tolerated very deep. e.g., I previously tested that when Kafka broker is killed, `rebuild_stream_reader_from_error` will not even be called. I guess this is because rdkafka performs retrying internally. This will make it very hard to report errors in a timely manner.

For sinks I'm not sure, maybe it can raise some errors.

**Comment by BugenZhao** [comment]
> Similarly for sources, we also tolerate errors extensively.

This reminds me of the consensus we reached earlier: sources should try their best to retry connection failures (even indefinitely) instead of causing the entire streaming graph to enter a recovery loop, at least before https://github.com/risingwavelabs/rfcs/pull/54 or https://github.com/risingwavelabs/rfcs/pull/84 being implemented.

So does it mean that we will now introduce a different behavior to let the source error fail the job specifically when it's being created?

**Comment by xxchan** [comment]
> So does it mean that we will now introduce a different behavior to let the source error fail the job specifically when it's being created?

I think if the goal is better UX (know errors earlier, and no need to check logs), maybe yes. Alternatively, maybe we can do more extensive validation when creating source (maybe even attempt to consuming some events?? not always do-able though). But the challenge I mentioned above (error are hidden very deep) still applies. 

Do you have any better ideas for this goal?

**Comment by fuyufjh** [comment]
Ping. Shall we start this?

**Comment by kwannoel** [comment]
> Ping. Shall we start this?

Okay I will take a look at it tomorrow.

**Comment by kwannoel** [comment]
Fyi, this task can lead to more complexity in the etcd backend, since we need to support background ddl now as well for source and sinks.

I may also take sometime to implement it in meta v2 backend since I'm unfamiliar.

I will start on it tomorrow, but unlikely to finish it that soon.

**Comment by kwannoel** [comment]
Working on blocking `sink` first + background_ddl on sink.

**Comment by kwannoel** [comment]
For kafka backfill, in 1.9 it won't be the default as mentioned by @xxchan offline.
So the `create mv on source` part will not be urgent to release.
Only when it is made default, we should have blocking kafka backfill.

Assigning this issue to @xxchan for the `blocking create mv on source` part.
I will work on the `blocking sink` part still.

**Comment by xiangjinwu** [comment]
Another minor benefit for blocking create-table-with-connector is to cleanup `sleep` in e2e sqllogictest. Not big enough to affect the plan, but if the feature was finally made possible, we could leverage it.

**Comment by kwannoel** [comment]
Remaining work is low priority.

**Comment by xxchan** [comment]
remaining tasks tracked in https://github.com/risingwavelabs/risingwave/issues/18338
