### ISSUE TITLE
e2e parallel tests failed: `Failed to send barrier with epoch 6107819919474688 to actor 9859: sender not found`

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#15703]
### Describe the bug

Failed to send barrier to actor

### Error message/log

```text
failed to run `e2e_test/streaming/temporal_join/temporal_join_multiple_rows.slt`
Caused by:
    statement failed: db error: ERROR: Failed to run the query
    Caused by these errors (recent errors listed first):
      1: gRPC request to meta service failed: Internal error
      2: gRPC request failed: Internal error: get error: Failed to send barrier with epoch 6107819919474688 to actor 9859: sender not found
```

### How did you deploy RisingWave?

https://buildkite.com/risingwavelabs/main-cron/builds/2042#018e3db1-f50b-485b-88bc-c8d6d91c6012

**Comment by BugenZhao** [comment]
Could this be related to #14887? cc @wenym1

**Comment by wenym1** [comment]
Related logs
```
2022-05-11T18:39:26.762104Z DEBUG risingwave_meta::manager::catalog: creating_tables ids: [
    402004,
    402005,
]
2022-05-11T18:39:26.762104Z DEBUG risingwave_meta::manager::catalog: cleaning table_id with initial state: 402004
2022-05-11T18:39:26.762104Z DEBUG risingwave_meta::manager::catalog: cleaning table_id for internal tables not reserved: 402005
2022-05-11T18:39:26.762104Z DEBUG risingwave_meta::manager::catalog: cleaning table_id: 402004
2022-05-11T18:39:26.762104Z DEBUG risingwave_meta::manager::catalog: cleaning table_id: 402005
2022-05-11T18:39:26.764603Z DEBUG risingwave_meta::manager::catalog: decrease ref for 402004
2022-05-11T18:39:26.764603Z DEBUG risingwave_meta::barrier::recovery: clean dirty table fragments: {TableId { table_id: 402004 }}
2022-05-11T18:39:26.779265Z  INFO risingwave_meta::barrier::recovery: recovering mview progress
2022-05-11T18:39:26.779265Z  INFO risingwave_meta::barrier::recovery: recovered mview progress
2022-05-11T18:39:26.779265Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: start resetting actors distribution
2022-05-11T18:39:26.779265Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: scaling actors succeed.
2022-05-11T18:39:26.838348Z  INFO risingwave_simulation::cluster: restart meta-1
2022-05-11T18:39:27.426717Z  INFO risingwave_simulation::cluster: restart frontend-2
2022-05-11T18:39:28.249582Z DEBUG risingwave_simulation::slt: Record Statement { loc: Location { file: "e2e_test/streaming/time_window.slt", line: 19, upper: None }, conditions: [], connection: Default, expected_error: None, sql: "create materialized view mv_hop as\nselect * from hop(t1, created_at, interval '15' minute, interval '30' minute);", expected_count: None } finished in 61.411263ms
2022-05-11T18:39:28.249582Z ERROR risingwave_simulation::slt: failed to run test: statement failed: db error: ERROR: Failed to run the query

Caused by these errors (recent errors listed first):
  1: gRPC request to meta service failed: Internal error
  2: The cluster is recovering

Backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: risingwave_stream::task::barrier_manager::LocalBarrierWorker::send_barrier
             at ./src/stream/src/task/barrier_manager.rs:540:28
   2: risingwave_stream::task::barrier_manager::LocalBarrierWorker::handle_streaming_control_request
             at ./src/stream/src/task/barrier_manager.rs:377:17
             at ./src/stream/src/task/barrier_manager.rs:351:34



[SQL] create materialized view mv_hop as
select * from hop(t1, created_at, interval '15' minute, interval '30' minute);
at e2e_test/streaming/time_window.slt:19

retry after 2s iteration=1
2022-05-11T18:39:28.249582Z DEBUG risingwave_simulation::slt: retry count iteration=2
thread '<unnamed>' panicked at /risingwave/src/storage/src/hummock/event_handler/hummock_event_handler.rs:485:9:
read version mapping not empty when clear. remaining tables: [TableId { table_id: 402004 }]
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: risingwave_storage::hummock::event_handler::hummock_event_handler::HummockEventHandler::handle_clear::{{closure}}
             at ./src/storage/src/hummock/event_handler/hummock_event_handler.rs:485:9
             at ./src/storage/src/hummock/event_handler/hummock_event_handler.rs:617:69
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
context: node=10 "compute-2", task=3375039 (spawned at /risingwave/src/storage/src/hummock/store/hummock_storage.rs:222:9)
note: run with `MADSIM_TEST_SEED=8` environment variable to reproduce this error

```

**Comment by wenym1** [comment]
> Related logs
> 
> ```
> 2022-05-11T18:39:26.762104Z DEBUG risingwave_meta::manager::catalog: creating_tables ids: [
>     402004,
>     402005,
> ]
> 2022-05-11T18:39:26.762104Z DEBUG risingwave_meta::manager::catalog: cleaning table_id with initial state: 402004
> 2022-05-11T18:39:26.762104Z DEBUG risingwave_meta::manager::catalog: cleaning table_id for internal tables not reserved: 402005
> 2022-05-11T18:39:26.762104Z DEBUG risingwave_meta::manager::catalog: cleaning table_id: 402004
> 2022-05-11T18:39:26.762104Z DEBUG risingwave_meta::manager::catalog: cleaning table_id: 402005
> 2022-05-11T18:39:26.764603Z DEBUG risingwave_meta::manager::catalog: decrease ref for 402004
> 2022-05-11T18:39:26.764603Z DEBUG risingwave_meta::barrier::recovery: clean dirty table fragments: {TableId { table_id: 402004 }}
> 2022-05-11T18:39:26.779265Z  INFO risingwave_meta::barrier::recovery: recovering mview progress
> 2022-05-11T18:39:26.779265Z  INFO risingwave_meta::barrier::recovery: recovered mview progress
> 2022-05-11T18:39:26.779265Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: start resetting actors distribution
> 2022-05-11T18:39:26.779265Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: scaling actors succeed.
> 2022-05-11T18:39:26.838348Z  INFO risingwave_simulation::cluster: restart meta-1
> 2022-05-11T18:39:27.426717Z  INFO risingwave_simulation::cluster: restart frontend-2
> 2022-05-11T18:39:28.249582Z DEBUG risingwave_simulation::slt: Record Statement { loc: Location { file: "e2e_test/streaming/time_window.slt", line: 19, upper: None }, conditions: [], connection: Default, expected_error: None, sql: "create materialized view mv_hop as\nselect * from hop(t1, created_at, interval '15' minute, interval '30' minute);", expected_count: None } finished in 61.411263ms
> 2022-05-11T18:39:28.249582Z ERROR risingwave_simulation::slt: failed to run test: statement failed: db error: ERROR: Failed to run the query
> 
> Caused by these errors (recent errors listed first):
>   1: gRPC request to meta service failed: Internal error
>   2: The cluster is recovering
> 
> Backtrace:
>    0: anyhow::error::<impl anyhow::Error>::msg
>    1: risingwave_stream::task::barrier_manager::LocalBarrierWorker::send_barrier
>              at ./src/stream/src/task/barrier_manager.rs:540:28
>    2: risingwave_stream::task::barrier_manager::LocalBarrierWorker::handle_streaming_control_request
>              at ./src/stream/src/task/barrier_manager.rs:377:17
>              at ./src/stream/src/task/barrier_manager.rs:351:34
> 
> 
> 
> [SQL] create materialized view mv_hop as
> select * from hop(t1, created_at, interval '15' minute, interval '30' minute);
> at e2e_test/streaming/time_window.slt:19
> 
> retry after 2s iteration=1
> 2022-05-11T18:39:28.249582Z DEBUG risingwave_simulation::slt: retry count iteration=2
> thread '<unnamed>' panicked at /risingwave/src/storage/src/hummock/event_handler/hummock_event_handler.rs:485:9:
> read version mapping not empty when clear. remaining tables: [TableId { table_id: 402004 }]
> stack backtrace:
>    0: rust_begin_unwind
>    1: core::panicking::panic_fmt
>    2: risingwave_storage::hummock::event_handler::hummock_event_handler::HummockEventHandler::handle_clear::{{closure}}
>              at ./src/storage/src/hummock/event_handler/hummock_event_handler.rs:485:9
>              at ./src/storage/src/hummock/event_handler/hummock_event_handler.rs:617:69
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> context: node=10 "compute-2", task=3375039 (spawned at /risingwave/src/storage/src/hummock/store/hummock_storage.rs:222:9)
> note: run with `MADSIM_TEST_SEED=8` environment variable to reproduce this error
> ```

This is an independent issue. Resolved by https://github.com/risingwavelabs/risingwave/pull/15738.

**Comment by wenym1** [comment]
After https://github.com/risingwavelabs/risingwave/pull/15776 is merged, the failure of this issue that happened frequently previously never happened again. 

Close it until the same failure happens again.
