### ISSUE TITLE
feat: add file-level scan api for iceberg source

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#15783]
### Is your feature request related to a problem? Please describe.

Currently, iceberg source does scan planning in the frontend node and sends the files needed to be scanned to compute nodes. Technically, we can use a file level scan API to scan those files. However, icelake lacks this API, so we need to reuse the table-level API and filter out the assigned files. I think we can add a file-level read API to icelake to avoid redundant scan planning.

**Comment by ZENOTME** [comment]
After https://github.com/apache/iceberg-rust/pull/377, I think the `iceberg-rust` can distribute the file scan task to different compute nodes.
