### ISSUE TITLE
bug: emergency picker can pick large l0 to base task

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#15856]
### Describe the bug

1. Emergency picker picks a big task (~100 sub-level as input, total file size > 500GB)
2. I/O failure happens during task execution
3. Similar task is picked again and go to 1, which goes in a loop causing compaction to get stuck

Not sure whether this is a bug in emergency picker only or it can happen in other picker as well.

Example (captured during the incident)
[example.log](https://github.com/risingwavelabs/risingwave/files/14716790/example.log)

**Comment by hzxa21** [comment]
Related: #15954

**Comment by hzxa21** [comment]
@Li0k Is this issue resolved?

**Comment by Li0k** [comment]
> @Li0k Is this issue resolved?

Close it first
