### ISSUE TITLE
feat/perf: make UDF invoked only once if the updates do not actually change value

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#15877]
A request from a user:
> I am not so sure how many times my UDF will be called though
> On every new row I think yes but how do I make sure it is called on an existing row only if it changed ?

Answer:
> n Update operation might become 2 rows UpdateDelete+UpdateInsert, so the UDF is called twice.

In theory, we can detect such no-op updates and compact them before invoking the UDF,
but since UDF is treated as a normal expression and is everywhere, it's hard to do it right now.

Link: https://github.com/risingwavelabs/risingwave/pull/14855#issuecomment-1916057244

IIRC, the join operator always detects and compacts because the join operator may yield too many intermediate results, which can be very bad. (will double check)

**Comment by BugenZhao** [comment]
Is this exactly #12201?

**Comment by xiangjinwu** [comment]
> IIRC, the join operator always detects and compacts because the join operator may yield too many intermediate results, which can be very bad. (will double check)

may be related: #14835
