### ISSUE TITLE
Streaming code cannot see environment variables set when using `risedev dev`

### ISSUE THREAD

**Issue by stdrc** [risingwavelabs/risingwave#15885]
### Describe the bug

`SOME_ENV_VAR=foo ./risedev d` cannot pass the environment variable to compute node. According to @BugenZhao, this is not expected.

**Comment by BugenZhao** [comment]
Maybe related: https://github.com/risingwavelabs/risingwave/pull/14228

**Comment by BugenZhao** [comment]
Could occur if there's already a tmux server running before launching `./risedev d`.

https://stackoverflow.com/questions/50506708/how-to-start-two-tmux-sessions-with-different-environments
