### ISSUE TITLE
allow configuring number of vnode per streaming job

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#15900]
In #3579, we discussed whether to adopt a vnode number other than 256 to achieve a better balance between scanning performance and maximal parallelism in a cluster. For quite some time afterwards, we find 256 works pretty well so the task was postponed.

Recently, we have observed some users running a RisingWave cluster with thousands of cores. While this is exciting, the performance of a single streaming job is unsurprisingly limited by the hardcoded vnode count of 256. I think instead of diving into the possibility of runtime dynamic or per-job vnode count, ~~a low-hanging fruit could be allowing users configuring the vnode count on cluster startup as an immutable system parameter.~~

~~Thanks to #6513 and #8385, this seems to be made easy. However, it's still worth noting that the vnode count is limited by the algorithm of row-id generator since #9135.~~

----

UPDATE: decide to support per-job vnode count, so that...

- users do not have to decide the max parallelism of the cluster for future workloads when a cluster is created initially
- existing clusters can also gain such capability for new jobs

**Comment by lmatz** [comment]
What's the current behavior of creating a materialized view with default parallelism in a cluster that has more than 256 CPUs? e.g. is it that more than 256 actors will be created but only 256 of them is actually working

**Comment by BugenZhao** [comment]
The parallelism was intended to be limited by the vnode count of 256, but there appear to be some edge cases. I will address that. 😄

https://github.com/risingwavelabs/risingwave/blob/1e848526ba487836d72a29b5390689f712b50e0d/src/meta/src/rpc/ddl_controller.rs#L1316-L1324

**Comment by BugenZhao** [comment]
Not resolved but only workarounded by #15941. Thus reopen.

**Comment by fuyufjh** [comment]
Time to work on this!

**Comment by fuyufjh** [comment]
It's worth mentioning that the `vnode` has already been written into the state table (as a prefix of the key), thus, I think the vnode number of existing jobs can't be changed anymore. We need to ensure that

1. The existing jobs can run properly with their correct vnode
2. The new jobs will be scheduled according to the new changed global vnode number

**Comment by BugenZhao** [comment]
Test plan:

- chaos test, checking that multiple streaming jobs with different vnode count settings can operate together
- backward-compatibility test, checking that we correctly handle the case where vnode count is not present

**Comment by BugenZhao** [comment]
Test is added in #19250. I believe we can close this issue now. 💋
