### ISSUE TITLE
compactor OOM in the longevity test

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#15903]
[sqlite](https://buildkite.com/risingwave-test/longevity-test/builds/1194) OOM after 8 hours, the longevity test with PostgreSQL and MySQL finishes successfully.

metric:
[https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-da[…]ll&var-table=All&from=1711360245686&to=1711409754716](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=P2453400D1763B4D9&var-namespace=usrlngvty-20240325-102416&var-instance=benchmark-risingwave&var-pod=All&var-component=All&var-table=All&from=1711360245686&to=1711409754716)

**Comment by lmatz** [comment]
slack: https://risingwave-labs.slack.com/archives/C06P9GXLQCS/p1711418115035389?thread_ts=1711362514.817799&cid=C06P9GXLQCS

**Comment by huangjw806** [comment]
This problem is related to opendal and has nothing to do with metastore
https://risingwave-labs.slack.com/archives/C0423G2NUF8/p1711682237083649

**Comment by Li0k** [comment]
switch the default s3 backend to aws-sdk https://github.com/risingwavelabs/risingwave/pull/16017

**Comment by Li0k** [comment]
@hzxa21

**Comment by hzxa21** [comment]
This issue is related to a buggy opendal version (0.45) and should be resolved now in main because we already upgraded to 0.49.
