### ISSUE TITLE
enhancement(compactor):  record potential oom risks in compactor components

### ISSUE THREAD

**Issue by Li0k** [risingwavelabs/risingwave#15946]
1. We adjust the tcp_recv_buffer for the s3 backend implementation. However, this will break when we switch to the opendal_s3 backend.
2. The memory usage estimation algorithm does not take into account different backend implementations.
3. The memory usage estimation algorithm is unable to estimate the memory usage of in-flight uploading sst. (https://github.com/risingwavelabs/risingwave/blob/1e848526ba487836d72a29b5390689f712b50e0d/src/storage/src/hummock/sstable/multi_builder.rs#L305)

**Comment by Li0k** [comment]
related to https://github.com/risingwavelabs/risingwave/issues/16685

**Comment by hzxa21** [comment]
#1682 introduced `compactor_concurrent_uploading_sst_count` to control the upload concurrency, which can reduce the memory footprint when the object store backend is slow. We decide to rely on this configuration to avoid OOM on non-standard s3 backend to ensure that we will not introduce performance overhead for compaction on s3 backend.
