### ISSUE TITLE
improve script for running e2e source tests

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#15995]
Yeah I encounter the same issue, and run my backfill tests separately from e2e tests in `run-backfill-tests.sh`

_Originally posted by @kwannoel in https://github.com/risingwavelabs/risingwave/pull/15602#discussion_r1540521984_

**Comment by xxchan** [comment]
I noticed there are both `ci/scripts/run-backfill-tests.sh` and `src/tests/simulation/tests/integration_tests/backfill_tests.rs`. This looks a little repetitive. Is this just to test in two different environments at the same time? Or are there any differences?

I'm thinking maybe we can use the same interface to write tests, and let it run in different environments. (In other words, support non-sim environment for the integration test. Or reuse `Cluster`, `Configuration` apis) @kwannoel How do you think?

**Comment by xxchan** [comment]
Some aspects I want to improve 
- we can run tests easily both in CI and locally
- we can use similar methods to setup tests, instead of writing shell scripts for each kind of tests..

**Comment by xxchan** [comment]
Thanks @BugenZhao 's idea

It can be as easy as
- Write `system` commands in scripts for setup. Use env vars to specify ports
  - We can further write e.g., `run_mysql.sh`, which uses envvars. Then in `slt`, we reuse the script, and don't need to copy-paste ports.
- The external services are started via `risedev`. Note that their env vars are stored in `risedev-env`. We use `risedev slt` to execute tests, which will load `risedev-env` first.
  - Ideally, CI can also use `risedev` to start services. But we can also just manually specify env vars.

**Comment by wangrunji0408** [comment]
Generally I think it's a good idea to have a unified interface for both sim and non-sim env. Maybe risedev can be used as a backend for this API. But I'm not sure how much work it would take.

**Comment by BugenZhao** [comment]
Related #12451

**Comment by kwannoel** [comment]
> I noticed there are both `ci/scripts/run-backfill-tests.sh` and `src/tests/simulation/tests/integration_tests/backfill_tests.rs`. This looks a little repetitive. Is this just to test in two different environments at the same time? Or are there any differences?
> 
> I'm thinking maybe we can use the same interface to write tests, and let it run in different environments. (i.e., support non-sim environment for the integration test. In other words, reuse `Cluster`, `Configuration` apis) @kwannoel @wangrunji0408 How do you think?

Madsim's environment has some quirks. Running those tests in `run-backfill-tests.sh` is intentional, I don't want to execute them in madsim's environment.
For instance things like `sleep` depends on IO, and time ticks randomly. So when there's sleep involved, I prefer to use a real-time environment, instead of one that is simulated.

**Comment by xxchan** [comment]
close in favor of #12451
