### ISSUE TITLE
BUG: Permission denied: cannot execute in a read-only transaction

### ISSUE THREAD

**Issue by huangjw806** [risingwavelabs/risingwave#16011]
image： nightly-20230328 

integration-test：
https://buildkite.com/risingwavelabs/integration-tests/builds/715

```

init_risingwave_mv(config)
--
  | File "/app/init.py", line 98, in init_risingwave_mv
  | cursor.execute(sql)
  | psycopg2.errors.InternalError_: Failed to run the query
  |  
  | Caused by:
  | Permission denied: cannot execute in a read-only transaction

```

chaos-mesh:
https://buildkite.com/risingwave-test/chaos-mesh/builds/711
https://buildkite.com/risingwave-test/chaos-mesh/builds/712

**Comment by BugenZhao** [comment]
Could be caused by https://github.com/risingwavelabs/risingwave/pull/15911#discussion_r1540555232

**Comment by chenzl25** [comment]
+1, cc @KeXiangWang. This change causes many CI pipeline failures. In `ReadOnly` transaction risingwave can't execute a ddl.
https://github.com/risingwavelabs/risingwave/blob/1e4f8471c9f91ce78351c904888ad7518c05204b/src/frontend/src/handler/transaction.rs#L57-L70
