### ISSUE TITLE
Write partition data in separate data dir for iceberg sink

### ISSUE THREAD

**Issue by ZENOTME** [risingwavelabs/risingwave#16022]
## Background

> I have an iceberg table partitioned by the Hour of a timestamp, but all the data from RisingWave doesn't seem to respect the partition. It's just writing straight to the /data folder. In contrast, if I write to the table from Spark it will create a partitioned folder and write data to that partition, under /data/timestamp_hour=2024-03-18-19 for example. 

### Describe the solution you'd like

1. This feature depends on the iceberg sdk to provide a convenient to custom the data dir.
2. Provide the config in risingwave

**Comment by chenzl25** [comment]
@ZENOTME Any updates?

**Comment by ZENOTME** [comment]
> @ZENOTME Any updates?

No, I don't make progress for this now. If it's not a high priority features, we can postpone it to next version of iceberg sink.
