### ISSUE TITLE
define generated column on CDC table

### ISSUE THREAD

**Issue by yuhao-su** [risingwavelabs/risingwave#16024]
this feature does not seem to work with Postgres CDC table

```sql
create table courses (*) from pg_mydb table 'public.courses';
ERROR:  Failed to run the query
```
```shell
Caused by these errors (recent errors listed first):
  1: gRPC request to meta service failed: Internal error
  2: failed to validate CDC table
  3: source cannot pass validation: INVALID_ARGUMENT: Primary key mismatch
```

_Originally posted by @mingfang in https://github.com/risingwavelabs/risingwave/issues/14644#issuecomment-2028542793_

**Comment by StrikeW** [comment]
Is this issue the same problem as to https://github.com/risingwavelabs/risingwave/issues/14693 ?

**Comment by yuhao-su** [comment]
> Is this issue the same problem as #14693 ?

Those are different issue

**Comment by st1page** [comment]
Also, the old CDC connector can not support that too. 

```
dev=> create table tt1 (
  pk int,
  v int, v1 int as v+v, 
  PRIMARY KEY (pk)
) with (
  connector = 'postgres-cdc',
  hostname = 'localhost',
  port = '5432',
  username = 'postgres',
  password = '123456',
  database.name = 'postgres',
  schema.name = 'public',
  table.name = 't',
  slot.name = 'tt1_slot',
);
ERROR:  Failed to run the query

Caused by these errors (recent errors listed first):
  1: gRPC request to meta service failed: Internal error
  2: failed to create source worker
  3: failed to create SplitEnumerator
  4: source cannot pass validation
  5: INVALID_ARGUMENT: The publication 'rw_publication' does not cover all columns of the table 'public.t'
```

**Comment by st1page** [comment]
> Also, the old CDC connector can not support that too.
> 
> ```
> dev=> create table tt1 (
>   pk int,
>   v int, v1 int as v+v, 
>   PRIMARY KEY (pk)
> ) with (
>   connector = 'postgres-cdc',
>   hostname = 'localhost',
>   port = '5432',
>   username = 'postgres',
>   password = '123456',
>   database.name = 'postgres',
>   schema.name = 'public',
>   table.name = 't',
>   slot.name = 'tt1_slot',
> );
> ERROR:  Failed to run the query
> 
> Caused by these errors (recent errors listed first):
>   1: gRPC request to meta service failed: Internal error
>   2: failed to create source worker
>   3: failed to create SplitEnumerator
>   4: source cannot pass validation
>   5: INVALID_ARGUMENT: The publication 'rw_publication' does not cover all columns of the table 'public.t'
> ```

fixed in https://github.com/risingwavelabs/risingwave/pull/16522
