### ISSUE TITLE
bug: interval join's state cleaning with watermark does not take effect

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#16045]
https://risingwave-community.slack.com/archives/C03BW71523T/p1711555567246409

**Comment by stdrc** [comment]
After reviewing related code, I found that interval join state cleaning never guarantee to fully clean outdated states🥵...It only cleans states that match new-coming rows. And also in our doc we never say anything about state cleaning for interval join. I guess we may need further revisiting and even reimplementation on that part.

**Comment by fuyufjh** [comment]
Related discussion: https://github.com/risingwavelabs/rfcs/pull/32/files#r1059266190

**Comment by fuyufjh** [comment]
cc. @chenzl25 for awareness. Perhaps we need to do some action, either by documenting this or fix the problem

**Comment by chenzl25** [comment]
The current implementation of interval join will clean the state when new messages come from upstream. I think we can document it clearly first.
