### ISSUE TITLE
bug(compaction): Some tasks continue to be canceled by Heartbeat due to ongoing trivial-move

### ISSUE THREAD

**Issue by Li0k** [risingwavelabs/risingwave#16050]
When Meta encountered some bugs and fell into a trivial-move loop, I found that the manual compaction task continued to be canceled by heartbeat.

record some issues
1. have separate the heartbeat event loop and task event loop
2. event loop latency is not high
![image](https://github.com/risingwavelabs/risingwave/assets/15023748/174283ba-f737-4179-bcc1-edcf617b2688)
3. tasks had been canceled by "CompactionHeartBeatExpiredCheck"
4. event loop p50 latency significantly reduced after bug fix
![image](https://github.com/risingwavelabs/risingwave/assets/15023748/efe2340d-350e-4b82-9bbd-179aecbdfdbd)

**Comment by Li0k** [comment]
ReportTask Event and PullTask Event are both forwarded to independent runtime execution. Therefore, when PullTask ​​falls into a loop, the execution of ReportTask will be blocked, causing the task to be Heartbeat Cancel.

Therefore, we also found a problem that can be improved. The compactor stopped heartbeat before the report was successful.

```
    let task_progress_guard =
        TaskProgressGuard::new(compact_task.task_id, context.task_progress_manager.clone())
```

https://github.com/risingwavelabs/risingwave/blob/bc4f7662bbc17a18876185d0832c766305599fd1/src/storage/src/hummock/compactor/compactor_runner.rs#L504

**Comment by Li0k** [comment]
This bug is not triggered frequently, after we fix the trivial-move bug and introduce batch ops for get/report task. 

After discussing offline with @hzxa21 , there is currently no ideal solution. Keep this Issue so that we can refer to it when similar problems arise. I will continue to track and find solutions.

**Comment by hzxa21** [comment]
> This bug is not triggered frequently, after we fix the trivial-move bug and introduce batch ops for get/report task.
> 
> After discussing offline with @hzxa21 , there is currently no ideal solution. Keep this Issue so that we can refer to it when similar problems arise. I will continue to track and find solutions.

We consider the issue has been mitigated and work around so I will remove it from the milestone.

**Comment by Li0k** [comment]
https://github.com/risingwavelabs/risingwave/pull/16479

This PR introduces new restrictions, limiting the number of trivial-move tasks selected in each loop, which can alleviate the problems mentioned in the issue.
