### ISSUE TITLE
bug: panic when UNIX epoch time out of i64 range

### ISSUE THREAD

**Issue by MrCroxx** [risingwavelabs/risingwave#16094]
### Describe the bug

In https://github.com/risingwavelabs/risingwave/blob/v1.7.1/src/connector/src/parser/unified/json.rs#L438-L449 , we convert the input into `i64` and parse the timestamp with it. RW will panic if the given range is out of `i64` range.

### Error message/log

```
2024-04-02 14:54:13 thread 'rw-streaming' panicked at src/connector/src/parser/unified/json.rs:447:52:
2024-04-02 14:54:13 called `Option::unwrap()` on a `None` value
```

### To Reproduce

```json
{
	"before": null,
	"after": {
	    "id": 12,
        "example_timestamp_tz": 12852202631933722624
    },
	"source": {
		"table": "pathmetadata"
	},
	"op": "c",
	"ts_ms": 1707225270445
}
```

### Expected behavior

The timestamp should be `Saturday, 9 April 2377`.

**Comment by tabVersion** [comment]
I don't quite get the problem here, for a real-world workload, the json format limits integers by 2^53, much smaller than `i64` range. The problem seems unreachable.

**Comment by xiangjinwu** [comment]
WIll not panic but will return err (and converted into `null`) after #16265

**Comment by xxchan** [comment]
> WIll not panic but will return err (and converted into `null`) after #16265

So this issue can be closed?
