### ISSUE TITLE
feat: Allow adjusting the parsing behavior of Debezium JSON format

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#16120]
> Notice that the solution only works for direct CDC. For those who use a self-deployed Debezium -> Kafka -> RW, we have to provide an option to adjust the parsing behavior for each column. Let me create another issue for that.

_Originally posted by @fuyufjh in https://github.com/risingwavelabs/risingwave/issues/16119#issuecomment-2033598889_

**Comment by xiangjinwu** [comment]
More details here: https://github.com/risingwavelabs/risingwave/issues/16097#issuecomment-2033945986

**Comment by BugenZhao** [comment]
For implementation: we already have an abstraction of `JsonParseOptions`, but only (compile-time) presets are used.

https://github.com/risingwavelabs/risingwave/blob/46325dfc97c899587cd5becf5e13bc9d1577ecd5/src/connector/src/parser/unified/json.rs#L94-L113

**Comment by xiangjinwu** [comment]
* When all columns use the same unit, an option `timestamptz.handling.mode` has been supported.
* When columns use different units, there are 2 options:
  * Decode kafka connect embedded `schema` (unsupported yet, and user may `schemas.enable=false`)
  * Use avro with schema registry
