### ISSUE TITLE
Switch from Ubuntu 22.04 to 24.04

### ISSUE THREAD

**Issue by rotten** [risingwavelabs/risingwave#16139]
Ubuntu 24.04 LTS is out now.

The base container for RisingWave could be updated from its current 22.04 base to the new 24.04 base.   In general it is better to keep on top of these things than to let them slide too far behind.

**Comment by lmatz** [comment]
How about we wait for the official release and then upgrade
![SCR-20240408-pis](https://github.com/risingwavelabs/risingwave/assets/5791930/6f30623f-a081-488b-9a8a-24e1b2fc180d)

I suppose the xz backdoor issue has delayed the process a bit

**Comment by lmatz** [comment]
Now https://ubuntu.com/download/desktop shows 24.04 LTS, let's do it
