### ISSUE TITLE
bug(source): unexpected warning on undefined-field-padding-null error

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#16191]
### Describe the bug

In kafka source with upsert format, it is a normal case where a message only has key but no value. This represents a delete event.

However, when ingesting such a message, a warning is printed:
```
WARN rw-streaming actor{otel.name="Actor 24" actor_id=24 prev_epoch=6246912290127872 curr_epoch=6246912308543488}:executor{otel.name="Source 1800002716"}:source_parse_chunk{actor_id=24 source_id=2}:
risingwave_connector::parser: failed to parse non-pk column, padding with `NULL` error=Undefined field `value` at `` split_id="0" offset="6" column="first_value_column_name"
```

### To Reproduce

Just create a kafka upsert source, with a delete event (kafka message with key only and no value) in the topic.

### Expected behavior

No warning printed. Because it is expected to have no value. It is misleading and may shadow/**suppress other real problems**.

When we already know it is a delete event, there should be no attempts to extract columns from its value.

### Additional context

`delete` calls into `do_action`

https://github.com/risingwavelabs/risingwave/blob/ff862dc97d05072dcb6b37a9be940ebd6a5221ad/src/connector/src/parser/mod.rs#L536-L541

`do_action` calls `wrapped_f` (field access) to on every column `self.descs.iter()`
https://github.com/risingwavelabs/risingwave/blob/ff862dc97d05072dcb6b37a9be940ebd6a5221ad/src/connector/src/parser/mod.rs#L498-L505

**Comment by tabVersion** [comment]
it may involve compatibility issue for users using upsert format before we introducing `include` clause. May need further investigation.

**Comment by BugenZhao** [comment]
May related to #15525.

**Comment by xiangjinwu** [comment]
> May related to #15525.

Related (same symptom) but need different solutions (different cause):
* That issue is to specify a subset of **columns** not to trigger warnings. This needs user input.
* This one is to avoid a subset of **rows** (delete ops) not to trigger warnings. This is purely internal and do less unnecessary work.
