### ISSUE TITLE
Use UDFs as sources

### ISSUE THREAD

**Issue by bakjos** [risingwavelabs/risingwave#16223]
### Background

With the amount of sources and how different is consumed by the clients, using UDFs could help to support more sources:
- Http long pooling  (Internal APIs)
- WebSockets/SSE (GraphQL/Rest)
- Grpc Endpoints

### Design

The UDFs are already supporting tables, and use yield to generate the values through streaming futures https://github.com/risingwavelabs/risingwave/blob/ed75502880af4fad364b9821ab85e7026188063d/src/expr/core/src/table_function/user_defined.rs#L93-L132. 

This functionality could be translated to tables/sources to emit records when a new value is received from the UDF, using a sintax like `CREATE [TABLE|SOURCE ] .. AS  <function_name> (param1, param2)`

### Future Optimizations

- Add support for async wasm UDFs
- Define a way to provide splits 
- Add support for local state (to keep things as the auth tokens)

**Comment by stdrc** [comment]
https://github.com/risingwavelabs/rfcs/pull/87#issuecomment-2333169493

**Comment by stdrc** [comment]
https://github.com/risingwavelabs/rfcs/pull/87#issuecomment-2333169493
