### ISSUE TITLE
Support rate limit of sink

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#16253]
We can rate limit backfill of sink to avoid downstream system being overwhelmed.

Requested by @zwang28 previously.

**Comment by kwannoel** [comment]
Not so important now that we have sink_decouple.

**Comment by kwannoel** [comment]
This is also to avoid the downstream system being overwhelmed in certain scenarios.

**Comment by zwang28** [comment]
decoupled sink won't "impact stream graph"
