### ISSUE TITLE
meta backup test (release) fails

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#16291]
### Describe the bug

https://buildkite.com/risingwavelabs/main-cron/builds/2327#_

![SCR-20240415-1vr](https://github.com/risingwavelabs/risingwave/assets/5791930/c5178d80-22e7-4374-bf6b-df5d1f3c80b4)

### Error message/log

[compactor-6660.log](https://github.com/risingwavelabs/risingwave/files/14971515/compactor-6660.log)
[compute-node-5688.log](https://github.com/risingwavelabs/risingwave/files/14971516/compute-node-5688.log)
[etcd-2388.log](https://github.com/risingwavelabs/risingwave/files/14971517/etcd-2388.log)
[frontend-4566.log](https://github.com/risingwavelabs/risingwave/files/14971518/frontend-4566.log)
[meta-node-5690.log](https://github.com/risingwavelabs/risingwave/files/14971520/meta-node-5690.log)
[minio.log](https://github.com/risingwavelabs/risingwave/files/14971521/minio.log)
[risedev.log](https://github.com/risingwavelabs/risingwave/files/14971522/risedev.log)

**Comment by fuyufjh** [comment]
@zwang28 Please take a look
