### ISSUE TITLE
feat: increamental `generate_series()`

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#16303]
```
CREATE TABLE t(key INT PRIMARY KEY, low INT, high INT);
CREATE MATERIALIZED VIEW mv AS 
SELECT key, generate_series(low, high, 1) AS serial_num FROM t;
INSERT INTO t VALUES (1000, 1, 10);
UPDATE t SET high = 20 WHERE key = 1000;
```
In the current implementation of SRF `generate_series` in RisingWave, it only calculates each input row, regardless of whether it is an insert or a delete. Therefore, in the example above, when the update statement occurs, it generates a delete and an insert statement, after which the projectSet operator of RisingWave will retract the existing 10 records and then reissue 20 records. However, we can perform calculations incrementally, that is, by feeding `generate_series` with a streamChunk and processing adjacent UpdateDelete and UpdateInsert statements together, thereby only calculating and outputting the incremental results.

And https://github.com/risingwavelabs/risingwave/issues/15830 will be a special case
```SQL
create materialized view xxx as generate_series(
    '2020-01-01 00:00:00'::TIMESTAMP, -- start 
    NOW(), -- end
    interval '1' minute  -- step
);
```

**Comment by st1page** [comment]
And this optimization is also meaningful for `unnest`

```SQL
create table t(x int[]);
create materialized view mv as select unnest(x) from t;
insert into t values (Array[1,2,3,4,5]);
update t set x = array_append(x, 100);
```

**Comment by wangrunji0408** [comment]
The ProjectSet operator should also be specialized to support incremental update. and only at most 1 table function is allowed in the ProjectSet. The situation with more than 1 table function is very complicated. Consider the following example:

```sql
INSERT INTO t VALUES (1000, 1, 3);

SELECT key, generate_series(low, high), generate_series(low*2, high*2) FROM t;
----
1000 1 2
1000 2 3
1000 3 4
1000 . 5
1000 . 6
```

**Comment by st1page** [comment]
Additionally, since this optimization relies on updateDelete and updateInsert, we need to ensure that the stream keys for updateDelete and updateInsert are consistent.

 https://github.com/risingwavelabs/risingwave/issues/12539

**Comment by fuyufjh** [comment]
Generally, to make a set-returning function incremental, we have to materialize the previous output rows (or input rows if the function is deterministic). This seems too expensive for some cases.

I'd like to focus on the requirement and take a specialized approach:

1. Only when the SRF is used in `from` clause rather than `select`.
   - So that the input rows are guaranteed to be only 1 row
2. Only for a selected set of SRFs such as `generated_series`
   - So that we don't need to write incremental version of all SRFs

**Comment by fuyufjh** [comment]
> And this optimization is also meaningful for `unnest`
> 
> ```sql
> create table t(x int[]);
> create materialized view mv as select unnest(x) from t;
> insert into t values (Array[1,2,3,4,5]);
> update t set x = array_append(x, 100);
> ```

IMO, this is "too expensive" (as mentioned in previous comment). Because

- There might be millions of rows in `t`, so the state of `unnest(x)` is also huge
- Meanwhile, assuming the `x` are mostly with around 10 elements, calculating them is lightweight
- Particularly, `x` might never be appended in its lifecycle, for example, the `lineitem` in `order` never changes because the order has been placed. This is pretty common.

**Comment by st1page** [comment]
> > And this optimization is also meaningful for `unnest`
> > ```sql
> > create table t(x int[]);
> > create materialized view mv as select unnest(x) from t;
> > insert into t values (Array[1,2,3,4,5]);
> > update t set x = array_append(x, 100);
> > ```
> 
> IMO, this is "too expensive" (as mentioned in previous comment). Because
> 
> * There might be millions of rows in `t`, so the state of `unnest(x)` is also huge
> * Meanwhile, assuming the `x` are mostly with around 10 elements, calculating `unnest(x)` is lightweight
> * Particularly, `x` might never be appended in its lifecycle, for example, the `lineitem` in `order` never changes because the order has been placed. This is pretty common.

Just thought the amplified output could introduce high pressure on the down stream plans

**Comment by wangrunji0408** [comment]
> Just thought the amplified output could introduce high pressure on the down stream plans

I can think of a more intuitive way to relieve this problem: introducing a new operator to compact stream chunks, removing the same U+ / U- pairs within a chunk or within a window of chunks. 🤔

**Comment by st1page** [comment]
> > Just thought the amplified output could introduce high pressure on the down stream plans
> 
> I can think of a more intuitive way to relieve this problem: introducing a new operator to compact stream chunks, removing the same U+ / U- pairs within a chunk or within a window of chunks. 🤔

This is feasible, but we cannot achieve it at a low cost because the `projectSet` operator cannot match the corresponding u- and u+ outputs(make them adjacent).

for the input
```
u- array(1,2)
u+ array(1,2,3)
```
unnnest will output 
```
- 1
- 2
+1
+2
+3
```

**Comment by BugenZhao** [comment]
In my very own opinion, the only reasonable (enough) use case for this feature appears to be https://github.com/risingwavelabs/risingwave/issues/15830. What about simply introducing some new operator to make that efficient?

**Comment by st1page** [comment]
> In my very own opinion, the only reasonable (enough) use case for this feature appears to be #15830. What about simply introducing some new operator to make that efficient?

Yeah... If so, I will simply enhance our `now` executor. And I will do a further discussion with the user who wants incremental `generate_series()` with the table's input.
