### ISSUE TITLE
Postgres-cdc: self-signed cert cannot pass the SSL/TLS validation 

### ISSUE THREAD

**Issue by StrikeW** [risingwavelabs/risingwave#16316]
### Describe the bug

See the log

### Error message/log

```text
Executor error: Connector error: Postgres error: error performing TLS handshake: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889:: unable to get local issuer certificate: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889:;
```

### Expected behavior

For `require` or `prefer` ssl.mode, we can skip the verification for self-signed cert.

### Additional context

https://github.com/risingwavelabs/risingwave/pull/15690

**Comment by hzxa21** [comment]
#16319 adopts this approach: "For require or prefer ssl.mode, we can skip the verification for self-signed cert."

**Comment by StrikeW** [comment]
> #16319 adopts this approach: "For require or prefer ssl.mode, we can skip the verification for self-signed cert."

nit: For require or prefer ssl.mode, we don't verify the peer certificate.
