### ISSUE TITLE
bug: schema search path is not followed in `SHOW TABLES`

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#16335]
Currently when running `SHOW TABLES` in RisingWave, the schema search path is not followed and the default schema `public` will always be used.

https://github.com/risingwavelabs/risingwave/blob/5be13a4c49248a4a299bbda1b7527c8783c5c481/src/frontend/src/handler/show.rs#L253-L256

Although `SHOW TABLES` is not a standard command in Postgres, users may still expect `SHOW TABLES` to behave the same as `\dt`. Besides, CockroachDB provide support for `SHOW TABLES` and it'll follow the search path.

https://www.cockroachlabs.com/docs/stable/show-tables#parameters
> `SHOW TABLES` will attempt to find a schema with the specified name first. If that fails, it will try to find a database with that name instead, and list the tables of its `public` schema. For more details, see [Name Resolution](https://www.cockroachlabs.com/docs/v23.2/sql-name-resolution).

----

Furthermore, should we delegate the implementation of 'SHOW' commands directly to the system tables for catalogs (i.e. `\dt`)?

**Comment by tabVersion** [comment]
@BugenZhao can you share more on the topic? 

> Currently when running SHOW TABLES in RisingWave, the schema search path is not followed and the default schema public will always be used.

Do you mean the fallback path should be `current schema` -> `current database` -> `other database`?

**Comment by BugenZhao** [comment]
> Do you mean the fallback path should be `current schema` -> `current database` -> `other database`?

Should follow the behavior described in the manual: https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PATH . We've implemented it before, so the only staff to do is to utilize it. https://github.com/risingwavelabs/risingwave/blob/90eb6f1de90eb589f3cee866f9d6e0d3dcdb788f/src/common/src/session_config/search_path.rs#L23-L40
