### ISSUE TITLE
Scale out fragment parallelism and actors in each CN is wrong 

### ISSUE THREAD

**Issue by xuefengze** [risingwavelabs/risingwave#16353]
https://buildkite.com/risingwave-test/longevity-test/builds/1306#018eea47-9cdb-4eef-89b1-ed8c1e05fec5/11516-20012
CN-2 has been running for 3 minutes since scale out.
<img width="1082" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/73645462/9f6bbe03-3798-41fd-b30c-fa06cf65cd35">
but some fragment's parallelism is still 2 * 8,and the number of actors in worker 7 is fewer than the other two workers.
<img width="1075" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/73645462/393f8891-244e-47d1-9a1f-023d5a117396">

**Comment by lmatz** [comment]
So it is because the period of time spent on scaling is long,

right now we will keep retrying if we found a certain MV is still not adapted to the latest parallelism setting.

In the future, we will rely on #16368
