### ISSUE TITLE
proxy subquery to source db

### ISSUE THREAD

**Issue by gshmu** [risingwavelabs/risingwave#16372]
### Describe the solution you'd like

```sql
select fields from risingwave.table where table.field in (select field from cdc_source.table) 
```

some base table not need duplicate, I want set some link table for cdc database.
first: run sql from source database, and then run the really query in risingwave.

**Comment by fuyufjh** [comment]
Now `cdc_source` doesn't have its own identifier, so it's impossible to refer to an "external" table in upstream.

**Comment by neverchanje** [comment]
This requirement seems a bit unclear. Please don't hesitate to reopen this issue if you can provide more context.
