### ISSUE TITLE
Rust client lib

### ISSUE THREAD

**Issue by jreuben11** [risingwavelabs/risingwave#16434]
### Is your feature request related to a problem? Please describe.

I see from the docs that there are client libs for go, python, java, node, even ruby https://docs.risingwave.com/docs/current/ruby-client-libraries/  - **but not Rust**. 
(Strange for an engine written in Rust)
I found this repo while looking for a Rust alternative for Spark / Beam on Flink
Would like to keep our codebase Rusty !

### Describe the solution you'd like

please provide a Rust client lib

### Describe alternatives you've considered

Fluvio https://fluvio.io/api/official/rust/examples/

**Comment by lmatz** [comment]
Use https://github.com/sfackler/rust-postgres should be fine,

RW compatible with Postgres, 
any Rust client for Postgres should work for RW.
