### ISSUE TITLE
Meta with mysql as backend got panic

### ISSUE THREAD

**Issue by xuefengze** [risingwavelabs/risingwave#16438]
```
thread 'rw-main' panicked at src/meta/node/src/server.rs:318:10:
Unable to start leader services: Execution Error: error returned from database: 1406 (22001): Data too long for column 'description' at row 9
```
version: `nightly-20240415`

**Comment by yezizp2012** [comment]
Could you please share the tests you're running? Seems like the data for `description` column reached the limit of the length in MySQL.

**Comment by fuyufjh** [comment]
May I ask about the background? We don't support MySQL as meta backend officially.

**Comment by yezizp2012** [comment]
> May I ask about the background? We don't support MySQL as meta backend officially.

We mentioned support in the document, so Sqlite, PostgreSQL and MySQL will all be tested. 🥵
