### ISSUE TITLE
Support creating table for CDC connectors with the * syntax

### ISSUE THREAD

**Issue by darkcofy** [risingwavelabs/risingwave#16443]
### Is your feature request related to a problem? Please describe.

When using a mysql cdc source after crfeating a source with 
```
CREATE SOURCE test WITH (
  connector = 'mysql-cdc',
  hostname = 'xxx,
  port = '3306',
  username = 'xxx',
  password = 'xxx',
  database.name = 'auto',
  server.id = 5888
);

```
To create a table from the data base you have to specify all the columns explicitly in table creation

```
CREATE TABLE IF NOT EXISTS my_products (
    id STRING,
    -- name of the product
    -- format: <group> <type> (<import/domestic>)
    -- e.g. KNOT Type III (import)
    name STRING, 
    price DECIMAL,
    PRIMARY KEY (id)
) FROM test TABLE 'auto.products'

```

### Describe the solution you'd like

I would like to able to create the table using a select * syntax to automatically detect the columns in the table and create downstream tables

```
CREATE TABLE IF NOT EXISTS my_products (
    PRIMARY KEY (id),
    *
) FROM test TABLE 'auto.products'
```

### Additional context

This is is that when we have a huge number of tables with 100+ columns we can avoid the tedium of write scripts to auto generate schema for create table syntax

**Comment by BugenZhao** [comment]
> I would like to able to create the table using a select * syntax to automatically detect the columns in the table and create downstream tables

There's a side effect that `*` looks to imply that the schema should _always_ be synced. May I ask about the desired behavior when there's a schema change in the source database (MySQL)? Would you like RisingWave to automatically sync the schema, or would you prefer to make manual schema changes? 



> This is is that when we have a huge number of tables with 100+ columns we can avoid the tedium of write scripts to auto generate schema for create table syntax

Do you think it would be helpful to have a script that fetches the schema and converts it to RisingWave DDL?

**Comment by fuyufjh** [comment]
> > I would like to able to create the table using a select * syntax to automatically detect the columns in the table and create downstream tables
> 
> There's a side effect that `*` looks to imply that the schema should _always_ be synced. May I ask about the desired behavior when there's a schema change in the source database (MySQL)? Would you like RisingWave to automatically sync the schema, or would you prefer to make manual schema changes?

Good point. 

Making it sync with upstream will introduce much more complexity. I suppose the direct requirement here is just pulling the schema *at this moment* from upstream DB, and we can work it out quickly. Furthermore, this is also consistent with the "external catalog" we were discussing recently, which makes a unified framework to read the upstream schema and create tables accordingly.

**Comment by neverchanje** [comment]
Agree with Eric's idea on only pulling the full schema at the first time setting up the CDC table.
After that, the table schema should be static unless manually updated.
Automatic schema change is another topic to concern.

**Comment by darkcofy** [comment]
In an ideal world schema change would be better appended automatically.

If it just syncs the first time , how would I add new columns in case of a schema change? 

Can I manually add changes? 

> Do you think it would be helpful to have a script that fetches the schema and converts it to RisingWave DDL?

This might be a good easy solution too!

**Comment by neverchanje** [comment]
Yeah, that's an ideal solution and also aligns with our vision.
However, automatic schema change might require substantial effort.
At least for now, we suggest manually managing schema changes via https://docs.risingwave.com/docs/current/sql-alter-table/#add-column, which is the common practice in most traditional databases.
