### ISSUE TITLE
Test more pg-types of postgres-cdc

### ISSUE THREAD

**Issue by KeXiangWang** [risingwavelabs/risingwave#16455]
Like enum, some of the postgres rows cannot be directly parsed by `String`. We need more tests to verify different types.
https://github.com/risingwavelabs/risingwave/pull/16423#discussion_r1575776831

**Comment by StrikeW** [comment]
More context:  in cdc backfill we use Rust client to scan the upstream table, and we need to covert those rows in postgres format into our `OwnedRow` to store in our storage.
For data types not supported in RW we will fallback to `VARCHAR`, which is supported in the `DebeziumJson` parser but need additional work to handle the format conversion.  Note that this requirement also apply to other cdc connector support cdc-backfill, e.g. mysql-cdc. cc @fuyufjh

**Comment by StrikeW** [comment]
We can create a cdc backfill table in https://github.com/risingwavelabs/risingwave/blob/adf13411bf652e30d62a08a7b0179de132611fe3/integration_tests/postgres-cdc/compatibility-rw.sql#L2 to cover the data type test.

**Comment by KeXiangWang** [comment]
> We can create a cdc backfill table in

Okk I can add this.

**Comment by KeXiangWang** [comment]
Done in https://github.com/risingwavelabs/risingwave/blob/20699d4103e2328e25fb937f432fd3bdfdcc7209/e2e_test/source/cdc/postgres_cdc.sql#L41
