### ISSUE TITLE
feat(dashboard): subscription is not displayed in kernel dashboard(catalog, streaming graph)

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#16469]

**Comment by xxhZs** [comment]
we currently do not have a subscription operator. Is it necessary to display it on dashboard. cc @wenym1

**Comment by wenym1** [comment]
> we currently do not have a subscription exec. Is it necessary to display it on dashboard. cc @wenym1

It should at least appear at the catalog. As for streaming graph, I think we can either display subscriptions as separate nodes with upstream as materialized view, or display as something like a property of the materialized view nodes.
