### ISSUE TITLE
Chaos-Mesh: create table t1 got stuck

### ISSUE THREAD

**Issue by xuefengze** [risingwavelabs/risingwave#16527]
https://buildkite.com/risingwave-test/chaos-mesh/builds/798#018f2615-dcdc-4eba-a7bf-515165cc169f/27437-27449
inject faults(duration is 10 min, so it was already end before running the SQL command):
<img width="861" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/73645462/f3dffa54-7c56-44b8-81c0-51506a8320b8">
```
2024-04-29T01:28:36.713887286Z  INFO handle_query{mode="simple query" session_id=2 sql=create table t1 (x int, y int);}: pgwire_slow_query_log: slow query elapsed=11160000ms
```

**Comment by fuyufjh** [comment]
Duplicated #16029 ?
