### ISSUE TITLE
set timezone globally (as a system parameter?)

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#16524]
Right now, we can set it per session: https://docs.risingwave.com/docs/current/view-configure-runtime-parameters/#how-to-view-runtime-parameters

It is reasonable to fix it for all the sessions as typically the user only cares about the time zone they are living in or dealing with.

Making it one of the system parameters should work. But I suppose it would require a system restart to take effect?
Not sure if there is a better way to do so.

**Comment by yuhao-su** [comment]
`alter system set timezone to xxx`? Start a new session should work

**Comment by lmatz** [comment]
you are right

I am actually a bit confused

https://docs.risingwave.com/docs/current/view-configure-system-parameters/#:~:text=You%20can%20configure%20mutable%20parameters,CLI%20of%20the%20meta%20node.:
![SCR-20240430-t9a](https://github.com/risingwavelabs/risingwave/assets/5791930/894d72be-44c3-436b-873b-719df34d5b79)

The page seems to imply that only variables mentioned above can be altered by `alter system set` statement.

But `timezone` is not in the list

**Comment by yuhao-su** [comment]
https://github.com/risingwavelabs/risingwave/pull/16062

**Comment by lmatz** [comment]
Thanks, let me file a doc issue to make it more clear.

User and I both get lost on this...
