### ISSUE TITLE
Delta Lake Sink: Add periodic checkpointing based on table configuration.

### ISSUE THREAD

**Issue by erikamundson** [risingwavelabs/risingwave#16546]
### Is your feature request related to a problem? Please describe.

With one write every second, a delta table's log files quickly become cumbersome to read, slowing down spark/trino queries that run on the tables. Periodic checkpointing greatly reduces the number of log files required to read to determine the table state, reducing that overhead on downstream jobs.

### Describe the solution you'd like

Recent updates to the delta-rs crate have added automatic checkpointing based on delta table configuration. I think adding these changes into the risingwavelabs/delta-rs fork should meet the requirements.

- https://github.com/delta-io/delta-rs/pull/2391
- https://github.com/delta-io/delta-rs/pull/2396

### Describe alternatives you've considered

We could potentially run a separate scheduled job on an interval to checkpoint the tables. I think a periodic optimize would also accomplish the same if we run it from spark.

**Comment by fuyufjh** [comment]
cc. @xxhZs PTAL

**Comment by erikamundson** [comment]
Hi @xxhZs , I think there might have been a miscommunication here, my apologies if the issue wasn't clear. I was referring to [delta lake checkpoints](https://docs.databricks.com/en/delta/best-practices.html#enhanced-checkpoints-for-low-latency-queries) which truncate the json table metadata files into parquet files periodically. 

Without these checkpoints calculating the table snapshot can become very slow, especially since Risingwave writes files with such high frequency.
