### ISSUE TITLE
iceberg sink: struct type with metadata doesn't work

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#16545]
Hi, I've recently been thinking about support for Struct type in Iceberg sink, since I'm testing if I can utilise RisingWave at work and such functionality is a necessity.  As of now when someone tries to sink struct data to iceberg catalog they receive an error
```Field response's type not compatible, risingwave converted data type Struct([Field { name: "responseStatus", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "statusCode", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]), iceberg's data type: Struct([Field { name: "responseStatus", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {"PARQUET:field_id": "17", "column_id": "17"} }, Field { name: "statusCode", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {"PARQUET:field_id": "18", "column_id": "18"} }])```
Looking at this it seems it is only a matter of a mismatch on `metadata` field in each `Field`. The code just does `left == right` comparison <https://github.com/risingwavelabs/risingwave/blob/main/src/connector/src/sink/iceberg/mod.rs#L1046>

Is Struct support in Iceberg sink just a matter of lack of correct comparison or is there more context to that?

[Slack Message](https://risingwave-community.slack.com/archives/C02T3F7UYM6/p1714404363778909?thread_ts=1714404363.778909&cid=C02T3F7UYM6)

**Comment by fuyufjh** [comment]
cc. @chenzl25

**Comment by chenzl25** [comment]
@ZENOTME Could you please check whether we support struct type in iceberg sink? IIUC, after this PR #16567 , we could support it directly.

**Comment by ZENOTME** [comment]
> @ZENOTME Could you please check whether we support struct type in iceberg sink? IIUC, after this PR #16567 , we could support it directly.

Sure, I test it later. BTW, there is also no test for struct type in icelake so I am not sure whether it's supported.

**Comment by xxchan** [comment]
This is not supported because when comparing the 2 struct types, `metadata` will be compared.
In iceberg, `metadata: {"PARQUET:field_id": "18"}` will be always present. But in RW we don't have the field id. Even if we have, the id may not match the iceberg one.
