### ISSUE TITLE
support `\dm` to show materialized view

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#16544]
### Is your feature request related to a problem? Please describe.

we have `show materialized views` already,
but users coming from the Postgres ecosystem may naturally try `\dm` first.

**Comment by TennyZhuang** [comment]
<img width="620" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/9161438/fc5fe194-7937-4e04-bce4-67ab54b4b865">

We have supported the use of `\dm` in earlier versions.
