### ISSUE TITLE
feat(dashboard): Display database & schema along with table names

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#16556]
Currently, there are only tables shown in dashboard. This was because when we develop dashboard in early stage, we don't care about schema & databases a lot. But today I think we need to fix it.

## Note

Currently we are using the internal table catalog message to pass the information from Meta node to dashboard web frontend.

Example:

https://github.com/risingwavelabs/risingwave/blob/3daa16077321a486d762b055da96d43ae0327ac4/proto/catalog.proto#L143-L182

Unfortunately, there are only database & schema IDs. This is reasonable because it's designed to be used internally in Meta service.

I think it's time to introduce a tailored message proto for dashboard display.

**Comment by BugenZhao** [comment]
Related https://github.com/risingwavelabs/risingwave/issues/15542
