### ISSUE TITLE
meta node OOM in longevity test with shared source

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#16577]
Execution URL: https://buildkite.com/risingwave-test/longevity-test/builds/1357
Grafana: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1714670735000&to=1714714072000&var-namespace=usrlngvty-20240502-171919
Log: https://grafana.test.risingwave-cloud.xyz/d/liz0yRCZz1/log-search-dashboard?orgId=1&var-data_source=Logging:%20test-useast1-eks-a&from=1714670735000&to=1714714072000&var-namespace=usrlngvty-20240502-171919

Quite strange

<img width="1103" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/9d5ada99-5b43-4f80-a39c-aa91e1e06409">

This test is triggered with
```
ENABLE_CREATE_MV_NEXMARK_TABLE="false"
ENABLE_SHARED_SOURCE="true"
```

**Comment by xxchan** [comment]
Hmmm, why meta node has hashjoin 🤣

https://buildkite.com/risingwave-test/generate-collapsed-heap-files/builds/48#018f3dbb-eecc-448c-b44e-d1e410383fb6
```
HEAPS_S3_URL="s3://test-useast1-mgmt-bucket-archiver/k8s/usrlngvty-20240502-171919/"
RW_VERSION="nightly-20240501"
INSTANCE_ARCH="x86"
```
<img width="1332" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/e7f9187e-9eff-4aa1-8a34-2bc28d3303a4">

**Comment by xxchan** [comment]
Hmmm, from nexmark, I see no much difference for whether or not shared source is enabled. It may be possibly caused by `ENABLE_CREATE_MV_NEXMARK_TABLE="false"`

**Comment by xxchan** [comment]
ColumnDesc of SouceBackfillNode is 300MB? 😮
<img width="815" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/c48897ce-778b-4a9c-9c95-bdb6f484d274">

**Comment by xxchan** [comment]
@yezizp2012 not sure if you have any quick thoughts about this. 🤔

**Comment by yezizp2012** [comment]
> @yezizp2012 not sure if you have any quick thoughts about this. 🤔

`ColumnDesc` shouldn't be very large. The parallelism of shared source streaming job should be 1, right?

**Comment by xxchan** [comment]
RW_META_STORE=postgresql seems ok...

https://buildkite.com/risingwave-test/longevity-test/builds/1400
