### ISSUE TITLE
feat(parser): support `emit on window close` in parentheses (DBT)

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#16592]
### Is your feature request related to a problem? Please describe.

Currently we parse `emit on window close` as part of the `create` statement rather than `select` . As a result, queries like `create materialized view ... as ( ... emit on window close )` can't be accepted because the parentheses explicitly include `emit on window close` as part of `select`. 

The parentheses were added by dbt to wrap any materialized view query. Thus, this problem affect all DBT users.

### Describe the solution you'd like

Is it possible to modify the parser to work around this?

**Comment by fuyufjh** [comment]
@chenzl25  Is it possible to fix this by modifying the DBT risingwave plugin?

**Comment by chenzl25** [comment]
Yes. I had fixed this problem in DBT. https://github.com/risingwavelabs/dbt-risingwave/pull/45
