### ISSUE TITLE
Upgrade to OpenDAL v0.46

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#16591]
OpenDAL just releases [v0.46.0](https://github.com/apache/opendal/releases/tag/v0.46.0). It contains Buffer Based IO which can make object store read/write more efficient and reduces the memory footprint so the upgrade is worth trying.

Note that v0.46.0 contains breaking changes including not only interface changes but also changes related to compilation feature flags. We need to carefully test this version to avoid breaking RW backward compatibility.

**Comment by hzxa21** [comment]
Currently blocked by #15722

**Comment by ZENOTME** [comment]
Is there progress on this PR? I'm trying to update arrow to 51 to integrate with [iceberg-rust](https://github.com/apache/iceberg-rust) and find that it need opendal 0.46 finally. If not yet I can send a PR to upgrade them together.

**Comment by hzxa21** [comment]
Done by #17563
