### ISSUE TITLE
support partial update for Cassandra sink

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#16607]
### Is your feature request related to a problem? Please describe.

Users may intend to write a Cassandra sink with a schema of partial columns to perform partial updates. However, we currently require the schema being exactly matched.

### Describe the solution you'd like

To perform an update in a Cassandra table, a `UPDATE ... SET ...` is executed. If a column is not included in the `SET` clause, it remains unchanged. This allows for partial updates to occur naturally.

Similar to https://github.com/risingwavelabs/risingwave/pull/14363, allow the sink schema to be a subset of the Cassandra table. 

### Additional context

The feature request is from community.

This is somehow a dual task of https://github.com/risingwavelabs/risingwave/issues/12709, which is about the Cassandra source.

**Comment by xxhZs** [comment]
For other sinks, if downstream sinks support partial updates, do we need to support them all? If so, do we need user specified options（like starrocks sink）, or is it supported by default（like clickhouse sink）
