### ISSUE TITLE
fragment running and present in `TableFragments` but not in catalog

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#16620]
<img width="630" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/25862682/3a3f8aa5-8965-4808-890f-953a54d7c011">

Job 3166 with its `Materialize` operator in fragment 3074 keeps reporting metrics. However, the job name is "unknown".

The actor is running, as confirmed by await-tree as well.

However, cannot find the job in the dev dashboard, including the pages for catalogs, dependency graph, and fragment graph.
Can still jump into its fragment graph through the `Goto` form. But the `Relations` section does not change accordingly.

<img width="180" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/25862682/79d47f4d-a9e2-4c04-ae3c-4a296f5c83c6">

----

Only after the throughput goes to zero (likely the backfill is finished), the jobs start to appear on the dashboard correctly.

**Comment by fuyufjh** [comment]
It looks like a backfilling job. During backfill, the Catalog is not written yet, while the `TableFragments` have been written.

It would be better to persit a catalog but marking as invisible

cc. @yezizp2012

**Comment by yezizp2012** [comment]
Should be resolved by #19134 .
