### ISSUE TITLE
PG CDC shared source throughput drops to 0 with ch-benchmark q3

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#16629]
### Describe the bug

This is a known issue refer to https://github.com/risingwavelabs/risingwave/issues/14943

https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc-shared-source/builds/41#018f5655-3749-4029-a4b8-cc0c321eb18a

![image](https://github.com/risingwavelabs/risingwave/assets/35356271/a2c141dc-0c83-476b-a7e4-a517ca21fa94)

### The version of RisingWave

nightly-20240507

**Comment by StrikeW** [comment]
background:
https://github.com/risingwavelabs/risingwave/issues/14943#issuecomment-2099841570

@hzxa21 could you take a quick look whether the state store behaves as expected in this workload?

**Comment by fuyufjh** [comment]
cc. @lmatz

**Comment by lmatz** [comment]
high join amplification, let's ignore modified q3 at the moment
