### ISSUE TITLE
bug(cassandra-sink): sink columns can be subset of target

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#16633]
### Describe the bug

The Cassandra sink asks the target table to have exactly the same set of columns as Sink. This is not consistent with other sinks: generally, the sink’s definition just need to be a subset of target table.

https://github.com/risingwavelabs/risingwave/blob/f6892e98e7c32e323263b2886817f0a0d34c61f4/java/connector-node/risingwave-sink-cassandra/src/main/java/com/risingwave/connector/CassandraUtil.java#L82-L86

### Error message/log

```
ERROR:  Failed to run the query

Caused by these errors (recent errors listed first):
  1: gRPC request to meta service failed: Internal error
  2: failed to validate sink
  3: sink cannot pass validation: FAILED_PRECONDITION: Don't match in the number of columns in the table
```

**Comment by BugenZhao** [comment]
Duplicated with #16607?
