### ISSUE TITLE
Deprecate File Source V1 

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#16645]
The new batch-reading feature was done for v2. https://github.com/risingwavelabs/risingwave/pull/15358

Time to deprecate the old file source.

We can keep the old code for existing users, but the default behavior should be using v2 i.e. No `_v2` prefix in `s3_v2`

**Comment by neverchanje** [comment]
https://github.com/risingwavelabs/risingwave/issues/16234

I once created a similar issue.

**Comment by fuyufjh** [comment]
#16234 was closed by #16337.

> We can keep the old code for existing users, but the default behavior should be using v2 i.e. No _v2 prefix in s3_v2

So, can we do this?

**Comment by tabVersion** [comment]
> #16234 was closed by #16337.
> 
> > We can keep the old code for existing users, but the default behavior should be using v2 i.e. No _v2 prefix in s3_v2
> 
> So, can we do this?

Yes, not a big deal. Which version should it be?
& We can just do the conversion in the frontend, keeping the connector name as `s3_v2` in both meta and CN.
