### ISSUE TITLE
MinPinnedVersionId not increase when there's no batch queries running

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#16644]
background:
https://risingwave-labs.slack.com/archives/C034TRN6A49/p1714528348327289

During oncall, we found MinPinnedVersionIdNotIncrease alert keeps firing for a cluster. The version id increase only every 3 hours. 

Grafana indicates that there were no batch queries running.
So it's weird that the version id has been pinned for such an extended period.

Not sure if this is a bug. If it's not, maybe we should remove this alert.

**Comment by xxchan** [comment]
@zwang28 @Little-Wallace randomly assigned to you. Feel free to find someone else to check this issue

**Comment by hzxa21** [comment]
Take a glance at grafana:
- Barrier latency and barrier number increases at 05/01 01:30 UTC+8:
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/79cae992-5747-4168-82dc-bc74ee1984b7)

- At around the same time, the delay in MinPinnedVersionId happened:
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/ae285d06-fd18-4694-a15c-8b24caaf02be)


I suspect the high barrier latency is the trigger of the issue.

**Comment by hzxa21** [comment]
Recovery triggered at the same time:
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/786a6739-b2d1-488a-a400-90bef01dc706)

I suspect that one CN stops receiving version update after recovery.

**Comment by zwang28** [comment]
> The version id increase only every 3 hours.
unpin every 3 hours is force by `max_version_pinning_duration_sec = 10800`

**Comment by fuyufjh** [comment]
Note down some observations of today's case: [Name: MinPinnedVersionIdNotIncrease Sev: [warning] Cluster: [prod-aws-euno1-eks-a]](https://risingwavelabs.pagerduty.com/alerts/Q0T0NRMT9PGDHP) at 10:04 AM.

Min-pinned version ID was stuck:

<img width="798" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/b5264c09-c2ca-4591-b2d2-86c2d885fbd9">


<img width="244" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/b76f6528-a5b3-4c8b-80cc-d09504154aee">

<img width="286" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/d7eed1e4-3305-4385-849b-d534d53cdf33">

Meanwhile, epoch ids are normal:

<img width="800" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/82741ae8-d80c-4711-b76d-4f48c46c8b01">

Barrier was abnormal but it's after the 1st min-epoch stuck:

<img width="1598" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/ffb5d6c5-8fb2-4856-9e62-601071cab2e3">

There was no heavy batch queries.

<img width="1599" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/3d2fd621-7066-4afb-9c18-8ae25a079cdd">

**Comment by zwang28** [comment]
The hummock version is pinned by log store.
https://risingwave-labs.slack.com/archives/C034TRN6A49/p1716526705213879?thread_ts=1716516350.612169&cid=C034TRN6A49
