### ISSUE TITLE
additional metadata when CDC via Debezium

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#16654]
### Is your feature request related to a problem? Please describe.

like this: https://nightlies.apache.org/flink/flink-cdc-docs-master/docs/connectors/cdc-connectors/mysql-cdc/#available-metadata

**Comment by StrikeW** [comment]
IMO `table_name` and `database_name` is only useful if the upstream comes from different table and database instance, we can postpone the support of these metadata right now.

**Comment by lmatz** [comment]
https://github.com/apache/flink-cdc/issues/1370#issue-1304131674

we try to keep the default value of `op_ts` the same as Flink so that users migrating from Flink does not change too much
aka, the default value of timestamptz `1970-01-01 00:00:00+00:00`

**Comment by neverchanje** [comment]
> > IMO table_name and database_name is only useful if the upstream comes from different table and database instance, we can postpone the support of these metadata right now.

Thanks for clarifying this. Indeed we can postpone it till when we implement regex matching of multiple tables.
