### ISSUE TITLE
CDC table missing features

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#16688]
- watermark
- append only
- generated column https://github.com/risingwavelabs/risingwave/issues/16024
- https://github.com/risingwavelabs/risingwave/issues/16443
- https://github.com/risingwavelabs/risingwave/issues/16359
- * https://github.com/risingwavelabs/risingwave/pull/16986
- alter table
  - add/drop column https://github.com/risingwavelabs/risingwave/issues/16287

_Originally posted by @fuyufjh in https://github.com/risingwavelabs/risingwave/issues/16513#issuecomment-2099641444_

**Comment by st1page** [comment]
after https://github.com/risingwavelabs/risingwave/issues/15267
