### ISSUE TITLE
bug: problematic Kafka sources prevent standalone instance from starting on Cloud

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#16693]
### Describe the bug

When a standalone instance on Cloud (with only 1 CPU core) restarts while there are many Kafka sources with brokers down in the catalog, it'll fail to enter the recovery phase, thus cannot function or serve any queries at all.

### Error message/log

There could be various types of errors that prevent the meta service from starting up, where almost all of them are some sort of "timeout", including...

- Unable to start leader services: BackupStorage error: s3 error: dispatch failure: other: identity resolver timed out after 5s
- lease ... keep alive timeout (lose leader)
- recover mview progress should not fail: Failed to acquire connection from pool: Connection pool timed out

### To Reproduce

1. `export TOKIO_WORKER_THREADS=1` to simulate the case for the resource limit of 1 CPU core in Cloud.
2. Start `risingwave` and a healthy Kafka cluster.
3. Create 10 Kafka sources.
4. Kill `risingwave` and the Kafka cluster.
5. Run `nc -k -l <broker-port>` to simulate a Kafka broker that never refuses a connection nor responses.
6. Start `risingwave` again.
7. Observe bunch of error logs from `rdkafka`.
8. Find it not be able to serve and panics after seconds.

### Expected behavior

Should at least start the meta service on `5690` port and then the frontend service, allowing users to run `DROP SOURCE` to drop the problematic sources.

### How did you deploy RisingWave?

- Single-node or standalone mode, with only 1 tokio worker threads.
- Or, free-tier in RisingWave cloud.

### Additional context

By setting `TOKIO_WORKER_THREADS` to a larger number (like 4), the problem is addressed.

By attaching the debugger, I believe it's caused by the synchronous interfaces in `rust-rdkafka` (issue: https://github.com/fede1024/rust-rdkafka/issues/358) called in `ConnectorSourceWorker::run`:

https://github.com/risingwavelabs/risingwave/blob/90eb6f1de90eb589f3cee866f9d6e0d3dcdb788f/src/meta/src/stream/source_manager.rs#L187-L191
Then
https://github.com/risingwavelabs/risingwave/blob/90eb6f1de90eb589f3cee866f9d6e0d3dcdb788f/src/connector/src/source/kafka/enumerator/client.rs#L376-L381

Note that `fetch_metadata` is actually a sync interface. It's marked as `async` to be compatible with `madsim` mocked interfaces. The timeout is also implemented in a sync way. When there's something wrong with the connection, the function call will block the thread.

Since there's only 1 tokio worker thread, a thread being blocked means that the whole RW service is blocked. As a result, there could be any kinds of weird timeout error to be happen.

- https://github.com/madsim-rs/madsim/pull/196 wraps some interfaces in `spawn_blocking`, which is in the right way for working around this problem. However, the remaining unwrapped interfaces could still be problematic. 
- #13462 could help
- #12571 could also help but was reverted due to unknown stuck

**Comment by tabVersion** [comment]
@wangrunji0408 shall we also make `fetch_metadata` spawn blocking?

**Comment by xxchan** [comment]
Let's retest this

**Comment by tabVersion** [comment]
close as completed
