### ISSUE TITLE
backfill test compactor OOM

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#16709]
### Describe the bug

<img width="1069" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/091d041b-09a8-4282-8cc6-33decb7cb898">
https://buildkite.com/risingwave-test/backfill/builds/532#018f6e64-ea79-4b01-b1d6-37ebccfe765d

### The version of RisingWave

nightly-20240512

### Additional context
https://github.com/risingwavelabs/rw-commits-history?tab=readme-ov-file#nightly-20240512

**Comment by hzxa21** [comment]
@Li0k Any updates?

**Comment by Li0k** [comment]
> @Li0k Any updates?

It didn't happen again.
