### ISSUE TITLE
Failed to upgrade from v1.8.0 to v1.9.0-rc

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#16702]
### Describe the bug

https://buildkite.com/risingwave-test/upgrade/builds/41#018f659e-91e9-4f7f-8b6f-b4dcbb377421

After upgrade
<img width="1090" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/9b3aff51-3456-4c28-b2ae-8c7c5b1e6445">

### The version of RisingWave

v1.9.0-rc

**Comment by zwang28** [comment]
caused by #16090

**Comment by cyliu0** [comment]
postgresql backend is not supported to upgrade to v1.9.0
