### ISSUE TITLE
Postgres source can segfault during recovery

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#16766]
### Describe the bug

Use https://github.com/risingwavelabs/risingwave/pull/16765 to repro.

```
Wed May 15 07:03:17 UTC 2024 [risedev]: Program exited with 139
```

**Comment by StrikeW** [comment]
Probably you are using openjdk 11 in your **mac**, please use java 17

**Comment by StrikeW** [comment]
I think we should confirm the problem first before create an issue to track it, otherwise there would be many one-shot/short-lived issues to clean.
