### ISSUE TITLE
perf: improve the performance of `column_aware_row_encoding::Deserializer`

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#16763]
The current implementation of `ValueRowDeserializer` is not efficient, which didn't fully utilize the performance of our row encoding format.

https://github.com/risingwavelabs/risingwave/blob/d1b4612fee0c05c1cb4c77bb757f58e5f3ff5092/src/common/src/util/value_encoding/column_aware_row_encoding.rs#L205-L259

> As shown in the figure below, the main time consumption is due to container operations.
>
> This encoding is rather friendly for random access, isn't it? The sorted column_id is obviously intended to facilitate binary search.

![image](https://github.com/risingwavelabs/risingwave/assets/10192522/dc9cb9eb-683d-40c5-9b04-dc9d9325443f)

https://github.com/risingwavelabs/rfcs/blob/75091f0c7f197f718b8343eb121932df5530ddb1/rfcs/0090-table-schema-change.md#column-aware-row-encoding

**Comment by BugenZhao** [comment]
Would you please share some backgrounds? For example, in which case does this become the bottleneck of the query or the job?

**Comment by zwang28** [comment]
> Would you please share some backgrounds? For example, in which case does this become the bottleneck of the query or the job?

I'll provide one case later.
