### ISSUE TITLE
flaky test: end-to-end cassandra sink test: Unable to connect to servers

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#16795]
Connection error: ('Unable to connect to any servers', {'172.16.0.11:9042': ConnectionRefusedError(111, "Tried connecting to [('172.16.0.11', 9042)]. Last error: Connection refused")})

https://buildkite.com/risingwavelabs/main-cron/builds/2476#018f7b8d-91ec-4ace-b9f1-b9d059b29fb4
https://buildkite.com/risingwavelabs/main-cron/builds/2508

**Comment by xxchan** [comment]
@xxhZs PTAL, thanks!

**Comment by xxhZs** [comment]
It worked after retrying, it seems that the cassandra's server is not running because of other tests, you can look at it again
