### ISSUE TITLE
nightly-20240518 weekly test perf degradation

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#16817]
### Describe the bug

Perf degrdation in weekly test. Those two SKUs  runs only in weekly test now.

https://buildkite.com/risingwave-test/tpch-benchmark/builds/1074

https://buildkite.com/risingwave-test/nexmark-benchmark/builds/3708

http://metabase.risingwave-cloud.xyz/question/4966-tpch-q8-bs-medium-1cn-affinity-avg-source-output-rows-per-second-rows-s-history-thtb-371?start_date=2023-09-24

http://metabase.risingwave-cloud.xyz/question/9112-nexmark-q7-rewrite-blackhole-4x-medium-1cn-affinity-avg-source-output-rows-per-second-rows-s-history-thtb-2808?start_date=2023-12-21

```
+----------------------------------------------------------+--------------+------------+-----------------------------------+---------------------+-----------------------------+-------------------------------+
| BENCHMARK NAME                                           | EXECUTION ID | STATUS     | KEY METRICS                       | FLUCTUATION OF BEST | FLUCTUATION OF LAST 10 DAYS | FLUCTUATION OF LAST EXECUTION |
+----------------------------------------------------------+--------------+------------+-----------------------------------+---------------------+-----------------------------+-------------------------------+
| nexmark-q7-rewrite-blackhole-4x-medium-1cn-affinity      |        28800 | Negative   | avg-source-output-rows-per-second | -28.78%             | -15.22%                     | -26.42%                       |
| tpch-q8-bs-medium-1cn-affinity                           |        28826 | Negative   | avg-source-output-rows-per-second | -49.35%             | -29.35%                     | -43.13%                       |
```

**Comment by st1page** [comment]
It seems because of the same issue with https://github.com/risingwavelabs/risingwave/issues/15142 
There is greater Imbalance in 5.18.

5.12: 
![image](https://github.com/risingwavelabs/risingwave/assets/40830455/59783f69-a340-47dc-a5e5-7b495ba48a1e)

5.18:
![image](https://github.com/risingwavelabs/risingwave/assets/40830455/d6602b25-e8ba-4b79-898c-54df509bff4f)

cc @lmatz

**Comment by st1page** [comment]
No conclusion has been reached regarding the reason for the performance degradation of TPCH Q8. 
The current phenomena:
1. From the perspective of backpressure, the bottleneck occurs at a certain append-only hash join
2. Both operator cache and block cache show higher miss rates on the 18th compared to the 12th.

**Comment by lmatz** [comment]
For nexmark q7, the network bandwidth between RW and Kafka is not the same:

Previously:
![SCR-20240520-l4q](https://github.com/risingwavelabs/risingwave/assets/5791930/8ee2b2ff-ebd4-4432-acf0-33679a47bcc7)

This time:
![SCR-20240520-l4t](https://github.com/risingwavelabs/risingwave/assets/5791930/5097b538-90c8-4e14-8628-ca0b7d90ddd7)

**Comment by st1page** [comment]
> No conclusion has been reached regarding the reason for the performance degradation of TPCH Q8. The current phenomena:
> 
> 1. From the perspective of backpressure, the bottleneck occurs at a certain append-only hash join
> 2. Both operator cache and block cache show higher miss rates on the 18th compared to the 12th.
> 
> rerun 0518 (slow): https://buildkite.com/risingwave-test/tpch-benchmark/builds/1075 test 0514 (fast): https://buildkite.com/risingwave-test/tpch-benchmark/builds/1076 test 0515 ( ) https://buildkite.com/risingwave-test/tpch-benchmark/builds/1077 test 0516 ( ) https://buildkite.com/risingwave-test/tpch-benchmark/builds/1078

Overall, there has been some fluctuation in the performance of the images on the 15th and 16th, but I believe the main performance drop is due to a change on the `nightly-20240517`. https://github.com/risingwavelabs/rw-commits-history?tab=readme-ov-file#nightly-20240517

http://metabase.risingwave-cloud.xyz/question/4966-tpch-q8-bs-medium-1cn-affinity-avg-source-output-rows-per-second-rows-s-history-thtb-371?start_date=2024-05-20

**Comment by st1page** [comment]
> > No conclusion has been reached regarding the reason for the performance degradation of TPCH Q8. The current phenomena:
> > 
> > 1. From the perspective of backpressure, the bottleneck occurs at a certain append-only hash join
> > 2. Both operator cache and block cache show higher miss rates on the 18th compared to the 12th.
> > 
> > rerun 0518 (slow): https://buildkite.com/risingwave-test/tpch-benchmark/builds/1075 test 0514 (fast): https://buildkite.com/risingwave-test/tpch-benchmark/builds/1076 test 0515 ( ) https://buildkite.com/risingwave-test/tpch-benchmark/builds/1077 test 0516 ( ) https://buildkite.com/risingwave-test/tpch-benchmark/builds/1078
> 
> Overall, there has been some fluctuation in the performance of the images on the 15th and 16th, but I believe the main performance drop is due to a change on the `nightly-20240517`. https://github.com/risingwavelabs/rw-commits-history?tab=readme-ov-file#nightly-20240517
> 
> http://metabase.risingwave-cloud.xyz/question/4966-tpch-q8-bs-medium-1cn-affinity-avg-source-output-rows-per-second-rows-s-history-thtb-371?start_date=2024-05-20

Unfortunately, it appears randomly... The degradation can happen in 0516's image but not happen in 0517's image...
http://metabase.risingwave-cloud.xyz/question/4966-tpch-q8-bs-medium-1cn-affinity-avg-source-output-rows-per-second-rows-s-history-thtb-371?start_date=2024-05-20

**Comment by fuyufjh** [comment]
cc. @cyliu0 Does this problem recur now?

**Comment by st1page** [comment]
It appears that the streaming performance of TPCH-Q8 is quite unstable. Before we focus on optimizing the streaming performance for TPCH, we will not conduct an in-depth investigation

**Comment by cyliu0** [comment]
Just like @st1page said, the tpch q8 fluctuation is quite relatively big. But for weekly test, it's relatively stable. And the low points are the release test for v1.9.2-rt.1 and v1.10.0-rt.1.
<img width="1905" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/4ca4a394-d8ea-43ad-9d50-b83696342a72">
