### ISSUE TITLE
feat(tolerate inconsistency): join match failure

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#16823]
This code branch seems not to be covered yet, nor did it been triggered by our TroubleMakerExecutor.

[https://github.com/risingwavelabs/risingwave/blob/1e848526ba487836d72a29b5390689f712b50e0d/src/stream/src/executor/managed_state/join/mod.rs#L4[…]63](https://github.com/risingwavelabs/risingwave/blob/1e848526ba487836d72a29b5390689f712b50e0d/src/stream/src/executor/managed_state/join/mod.rs#L461-L463)

> Logically, this situation should be covered by the exception injections in state_table.insert/delete/update.
> 
> Hmm, interesting. I've never encountered this issue locally.
> 
> Could it be because the join key is too random and didn't match up?
> 
> It's possible. With random data, some paths might be hard to encounter.
> 
> Yes, if it's purely random (from INT_MIN to INT_MAX), it might not work well.
> 
> It seems like a good idea to use a fixed value occasionally within the random range.
> 
> Yes, indeed.

**Comment by stdrc** [comment]
https://github.com/risingwavelabs/risingwave/blob/1e848526ba487836d72a29b5390689f712b50e0d/src/stream/src/executor/managed_state/join/mod.rs#L455-L488

The loop highly relies on the consistency of data in the two state table, no missing data or extra data is allowed in one of the table, because of the fact that it only checks pk equality in debug build.

I'm afraid that only tolerating the `panic` call will cause massive data corruption when inconsistency really happens. IMO we'd better change the loop logic to pair `row` and `degree` according to `pk`, but this may hurt performance. Any comments?

cc @yuhao-su

**Comment by stdrc** [comment]
Oh, we can only fallback to pk-based `row-degree` matching once after an inconsistency happened.

**Comment by yuhao-su** [comment]
We used to have something can tolerate the inconsistency
https://github.com/risingwavelabs/risingwave/pull/6159/files/c19529540ccc97cc5c860a279437bd787be949b1#diff-6e4d3950cf84ab354e5daa96879a733b1842693d1a6951773adbbb5abdd5f8dcL27-L28

**Comment by stdrc** [comment]
> We used to have something can tolerate the inconsistency
> https://github.com/risingwavelabs/risingwave/pull/6159/files/c19529540ccc97cc5c860a279437bd787be949b1#diff-6e4d3950cf84ab354e5daa96879a733b1842693d1a6951773adbbb5abdd5f8dcL27-L28

You mean `zip_by_order_key`?

**Comment by stdrc** [comment]
May I ask a dumb question? Why we need to separate data table and degree table? If they are always updated at the same time, and share the same pk, why we don't add a `degree` column to the data table?🥵

**Comment by yuhao-su** [comment]
> You mean zip_by_order_key?

Yes

> Why we need to separate data table and degree table? 

In case when we need the degree table, it is very common only degree table get updated, in which case we don't want update the whole row.

**Comment by stdrc** [comment]
> > Why we need to separate data table and degree table?
> 
> In case when we need the degree table, it is very common only degree table get updated, in which case we don't want update the whole row.

Oh, you're right. I was just kinda confused between the two join sides. Now I understand.
