### ISSUE TITLE
bug: thread 'rw-main' panicked at src/meta/src/hummock/compaction/picker/min_overlap_compaction_picker.rs:514:25

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#16835]
### Describe the bug

Panic when I manually run the previously disabled compact test q5 with RW version: 1.9.0-alpha (d3ff8f79d8ebe4339e8a6477e044aef52887228c)

```
COMPACTION_TEST_CHECK_GET_PER_LOOP="10"
COMPACTION_TEST_CHECK_INTERVAL_SEC="600"
COMPACTION_TEST_DURATION_MINUTES="60"
COMPACTION_TEST_QUERIES="q5"
```

[Buildkite](https://buildkite.com/risingwave-test/compaction-test/builds/153#018f9569-5395-435b-85a9-5269ff1affb1)
[Metric](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=P2453400D1763B4D9&var-namespace=compaction-test-20240520-095105&var-instance=benchmark-risingwave&var-pod=All&var-component=All&var-table=All&from=1716198938655&to=1716200471441)
[Log](https://grafana.test.risingwave-cloud.xyz/explore?schemaVersion=1&panes=%7B%22vln%22:%7B%22datasource%22:%22PE59595AED52CF917%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22compaction-test-20240520-095105%5C%22,%20app%3D%5C%22benchmark-risingwave-meta-m-0%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22PE59595AED52CF917%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221716199125887%22,%22to%22:%221716200225421%22%7D%7D%7D&orgId=1)

**Comment by lmatz** [comment]
How about including this test in the release testing pipelines: 

https://www.notion.so/risingwave-labs/1c99563c67db464c98a5fd779ae8ea74?v=b11ed9512c42437082fa6fd82c0f7268&pvs=4
