### ISSUE TITLE
Bug: Frontend hangs and can't accept new connection

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#16837]
### Describe the bug

PR https://github.com/risingwavelabs/risingwave/pull/15758 could cause the following query to run a very long time(e.g. 10s). 
During the major time of 10s, the execution has no await point.

```sql
select true and true and true and true and true and true and true and true and true and true and true and true and true  and true  and true  and true  and true and true and true and true and true and true and true;
```

During the above SQL execution period, the frontend node fails to accept a new connection which is unexpected, because we use a multi-thread tokio run time. I suspected that the tokio runtime fails to steal work from one thread to another in this case, because after using an additional runtime to run `listener.accept`, the new connection could be accepted timely.

**Comment by BugenZhao** [comment]
Could be related: https://github.com/risingwavelabs/risingwave/issues/9019
