### ISSUE TITLE
bug(cdc-connector): InstanceNotFoundException

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#16850]
### Describe the bug

Background: the users stopped the cluster and restarted after a night.  

This `InstanceNotFoundException` shouldn't be occurring, can you help me check it? There are too many of these in the logs, making it hard to find the real errors.

### Error message/log

```text
2024-05-21T01:51:19.330255272Z  WARN risingwave_connector_node: Failed to get streaming metrics: javax.management.InstanceNotFoundException: debezium.mysql:type=connector-metrics,context=streaming,server=RW_CDC_21
```

**Comment by StrikeW** [comment]
This warn log means the underlying Debezium connector doesn't ready. We are waiting the connector to become ready when we create the shared cdc source job. I'll remove this log in a PR.
https://github.com/risingwavelabs/risingwave/blob/6170d4cf36e17789888b976c4a9c56188595222d/java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/DbzSourceUtils.java#L157
