### ISSUE TITLE
Offer advice when ` Window function with empty PARTITION BY is not supported yet`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#16924]
```
dev=> create table t(v1 int);
CREATE_TABLE
dev=> create materialized view m as select sum(v1) over (order by v1) from t;
ERROR:  Failed to run the query

Caused by:
  Feature is not yet implemented: Window function with empty PARTITION BY is not supported yet
No tracking issue yet. Feel free to submit a feature request at https://github.com/risingwavelabs/risingwave/issues/new?labels=type%2Ffeature&template=feature_request.yml
```

But partition by constant works
```
dev=> create materialized view m as select sum(v1) over (partition by 1 order by v1) from t;
CREATE_MATERIALIZED_VIEW
```

Although I am not sure if we can use such a workaround to all the `window` functions?

**Comment by lmatz** [comment]
BTW, if the workaround works for most cases, shouldn't we just rewrite the query automatically?

**Comment by fuyufjh** [comment]
> BTW, if the workaround works for most cases, shouldn't we just rewrite the query automatically?

Had better not to do so. `partition by 1`, similarly to the nested-loop join trick, will make it impossible to process parallelly and thus easily become a performance bottleneck. Writing `partition by 1` also let users know what he is doing.

**Comment by fuyufjh** [comment]
> Feature is not yet implemented: Window function with empty PARTITION BY is not supported yet

@stdrc Do you think it's "not yet implemented"? I think we intended to forbid such thing, just like the case of nested-loop join.

**Comment by stdrc** [comment]
> > Feature is not yet implemented: Window function with empty PARTITION BY is not supported yet
> 
> 
> 
> @stdrc Do you think it's "not yet implemented"? I think we intended to forbid such thing to avoid bad query, just like the case of nested-loop join.


Yes we didn't support this because we don't want user to write such bad query very easily.
