### ISSUE TITLE
Unsupported cast when casting to a one field struct using the parenthesis syntax

### ISSUE THREAD

**Issue by maingoh** [risingwavelabs/risingwave#16979]
### Describe the bug

The following raise an error
```
SELECT (foo.my_id)::struct<id string> as foo FROM ...
```
However using the `row()` function it works:
```
SELECT row(foo.my_id)::struct<id string> as foo FROM ...
```

### Error message/log

```text
Unsupported function: cast(character varying) -> struct<id character varying>;
```
```


### To Reproduce

_No response_

### Expected behavior

The `()` syntax for creating struct should work with one field. When I add a second one it works. I currently explicitely use `row()` as a workaround.

### How did you deploy RisingWave?

K8s operator

### The version of RisingWave

v1.8.2

### Additional context

_No response_

**Comment by xiangjinwu** [comment]
> The `ROW` keyword is actually optional **as long as you have more than one field** in the expression

https://www.postgresql.org/docs/current/rowtypes.html#ROWTYPES-CONSTRUCTING

This is actually PostgreSQL behavior, which is essential to differentiate it from parentheses used for precedence: `(int_x + int_y) * int_z`.

If you know Python, it is also the case that `(int_x)` is an integer while `(int_x,)` with an awkward trailing comma is a tuple containing an integer field. The trailing comma syntax is not adopted by PostgreSQL, so does RisingWave.
