### ISSUE TITLE
weekly test: meta panicked during nexmark q4 cleanup

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#17061]
### Describe the bug

And led to the following queries failure.

```
Failed Execution List:
- nexmark-q5-many-windows-blackhole-4x-medium-1cn-affinity: 30319, https://buildkite.com/risingwave-test/nexmark-benchmark/builds/3839
- nexmark-q7-blackhole-4x-medium-1cn-affinity: 30324, https://buildkite.com/risingwave-test/nexmark-benchmark/builds/3839
- nexmark-q9-blackhole-4x-medium-1cn-affinity: 30327, https://buildkite.com/risingwave-test/nexmark-benchmark/builds/3839
```

https://buildkite.com/risingwave-test/nexmark-benchmark/builds/3839#018fd488-bc9b-4353-b0c2-07d7f649e16c

[meta log](https://grafana.test.risingwave-cloud.xyz/explore?schemaVersion=1&panes=%7B%22zmm%22:%7B%22datasource%22:%22PE59595AED52CF917%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22nexmark-lt-4x-1cn-affinity-weekly-20240601%5C%22,%20container%3D%5C%22meta%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22PE59595AED52CF917%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221716658217606%22,%22to%22:%221717263017606%22%7D%7D%7D&orgId=1)

<img width="1599" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/a2a7834b-35e8-494b-b77d-5199b597c645">

<img width="1586" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/7ac4e8d7-5a49-4f13-a7ac-2d648c5082c8">

<img width="1525" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/0608bc59-2038-4640-9413-a23f84622323">

<img width="788" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/5145641d-8e52-4305-94a7-81665f772ead">

### The version of RisingWave

nightly-20240601

### Additional context

https://github.com/risingwavelabs/rw-commits-history?tab=readme-ov-file#nightly-20240602

It failed in the weekly test. And there are not new commits for nightly-20240601 according to the history. We need to focus on the commits in the past week.

**Comment by lmatz** [comment]
cc @Little-Wallace @Li0k 

Could you take a look if it is directly caused by compaction group related issue or there is some deeper root cause?
