### ISSUE TITLE
ElasticSearch Sink to use `sink_decouple` by default

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#17073]
So it can isolate sink job failure.

**Comment by kwannoel** [comment]
Generalizing this further, which sink should have sink_decouple set and which should not? What's the criteria? cc @hzxa21 @xxhZs 

From our docs it seems like some support sink_decouple, and others do not. Why don't we enable it for all sinks that support sink_decouple?

https://docs.risingwave.com/docs/current/data-delivery/#sink-decoupling

**Comment by xxchan** [comment]
https://github.com/risingwavelabs/risingwave/issues/17095
