### ISSUE TITLE
bug(mongodb-cdc): fail to connect due to `not authorized on config to execute command`

### ISSUE THREAD

**Issue by KeXiangWang** [risingwavelabs/risingwave#17076]
### Describe the bug

As title. The user was using mongodb atlas on GCP.

### Error message/log

```text
# The source was created successfully but got this error in log
Caused by: com.mongodb.MongoCommandException: Command failed with error 13 (Unauthorized): 'not authorized on config to execute command { listCollections: 1, cursor: {}, nameOnly: true, $db: \"config\", $clusterTime: { clusterTime: Timestamp(1717438499, 9)
```

**Comment by StrikeW** [comment]
I cannot reproduce the issue with `Shared` Atlas cluster, we should check whether they have enable replica set in the cluster.
https://www.mongodb.com/docs/manual/tutorial/deploy-replica-set/#deploy-a-replica-set-in-the-mongodb-atlas-ui

**Comment by StrikeW** [comment]
The mongo user lacks `listCollections` for the `config` and `local` database, after adding the roles the problem is resolved.

```
listDatabases
@all databases(all collections)
listCollections
@config(all collections)
@local(all collections)
```
