### ISSUE TITLE
e2e test time increased from 15min to 20min in ci

### ISSUE THREAD

**Issue by yuhao-su** [risingwavelabs/risingwave#17138]
In recent PRs I noticed the end-to-end test time increase to over 20min. (The e2e parallel test time also increased)
https://buildkite.com/risingwavelabs/pull-request/builds/51224#018fe8e2-7ce9-435f-932c-9aaba0d17c9b
https://buildkite.com/risingwavelabs/pull-request/builds/51237#018fe93e-ea86-4e21-b900-8716cdcf164f

Previously it's 15min
https://buildkite.com/risingwavelabs/pull-request/builds/51137#018fe6d2-593f-4b90-8da6-431a643f1243

**Comment by xxchan** [comment]
It seems some slow stuff is added again.

![image](https://github.com/risingwavelabs/risingwave/assets/37948597/bf36fc51-a9e6-4b40-89f0-e55404b322e7)

It's not easy to tell which part of the tests becomes slower, we might need to upload JUnit data :(
