### ISSUE TITLE
bug(main-cron): pulsar source check: gRPC request to meta service failed: Unknown error

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#17143]
### Describe the bug

https://buildkite.com/risingwavelabs/main-cron/builds/2574#018fe921-e00e-4500-a96b-e376672a9538

### Error message/log

```text
Traceback (most recent call last):
  File "/risingwave/e2e_test/source/pulsar/astra-streaming.py", line 44, in <module>
    do_test(config)
  File "/risingwave/e2e_test/source/pulsar/astra-streaming.py", line 20, in do_test
    cur.execute(f'''CREATE TABLE t (v1 int, v2 varchar)
psycopg2.errors.InternalError_: Failed to run the query
Caused by these errors (recent errors listed first):
  1: gRPC request to meta service failed: Unknown error
  2: transport error
  3: connection error
  4: connection reset
```

Meta service's logs were not collected in the CI pipeline.

**Comment by tabVersion** [comment]
https://github.com/risingwavelabs/risingwave/pull/17152 may help. Will trigger another test for verification

**Comment by fuyufjh** [comment]
@tabVersion Does https://github.com/risingwavelabs/risingwave/pull/17152 resolve this?

**Comment by tabVersion** [comment]
https://github.com/risingwavelabs/risingwave/pull/17185 I opened another one for this. Seems a misalign in credentials. Will fix asap
