### ISSUE TITLE
sink to BigQuery error: `Request 'AppendRows' from role 'cloud-dataengine-globalrouting' throttled: Task is overloaded (memory-protection) go/tr-t.`

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#17214]
A user encountered the following error frequently when backfilling the historical data with high throughput to sink them into the downstream BigQuery:

```
Actor 114514 exited unexpectedly: Executor error: Sink error:
  BigQuery error:
    status: Unavailable,
    message: "Request 'AppendRows' from role 'cloud-dataengine-globalrouting' throttled:
      Task is overloaded (memory-protection) go/tr-t.",
    details: [],
    metadata: MetadataMap { headers: {} };
```

The error indicates that the external system is being throttled. Instead of throwing an error and causing the actor to fail, we should retry the request.

By enabling `sink_decouple`, the error got retried by the log store writer and not triggering the cluster recovery any more. However, it turns out that the effective write throughput is quite limited. The user needs to frequently rescale or pause and resume the cluster to increase the throughput, which is weird.

----

Questions:

1. Shall we have connector-specific retrying logic for such throttling error?
2. Why pausing and resuming increases the throughput?
3. There seems to be no pressure test that reflects the workload in production. Shall we improve the situation? Also applies to other connectors.
4. Based on the [documentation](https://cloud.google.com/bigquery/docs/write-api#overview) of BigQuery Write API...
   - Shall we adopt the "pending type" stream instead of the default stream (to potentially improve the performance)?
   - Why can we do to minimize the possibility to reach the quota / rate limit?

**Comment by fuyufjh** [comment]
Perhaps our write throughput/frequency is too high for these OLAP systems. I think we may always use sink_decouple and batching writes to reduce the load of target system.

**Comment by xxhZs** [comment]
So it seems that implementing decouple commit for bg can solve this problem

**Comment by xxhZs** [comment]
add retry in https://github.com/risingwavelabs/risingwave/pull/17237
