### ISSUE TITLE
Support decouple_commit for all olap sinks ?

### ISSUE THREAD

**Issue by xxhZs** [risingwavelabs/risingwave#17223]
### Is your feature request related to a problem? Please describe.

Do we need to support decouple_commit for all olap sinks? Currently, we support iceberg and deltalake and starrocks
from https://github.com/risingwavelabs/risingwave/issues/17214#issuecomment-2162301929
And do we need to support the alter parameter for dynamic adjustment from @neverchanje

**Comment by fuyufjh** [comment]
I think the answer should be "yes, let's do it"

Tracked in #17095
