### ISSUE TITLE
pg_index does not include primary keys

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#17252]
### Is your feature request related to a problem? Please describe.

Primary keys are automatically indexes in Postgres, specially tagged via the indisprimary column in [pg_index](https://www.postgresql.org/docs/current/catalog-pg-index.html);

In RisingWave, our pg_index only shows indexes created via `CREATE INDEX`.

Since we do not have other ways around to show all indexes and PKs within a database schema in a single query, we have to iterate over all tables and query through `show columns from <rel>`. This is very inconvenient and error-prone.

### Describe the solution you'd like

We should at least include primary keys in pg_index and consider adding them to rw_indexes;

**Comment by yezizp2012** [comment]
For PKs, what content should we fill in column `indexdef`? Should we leave it empty or construct a fake one like `CREATE UNIQUE INDEX XXXX_index ON public.XXXX USING btree (col1, col2)`?

**Comment by yezizp2012** [comment]
They all relies on `rw_indexes`, which contains a `definition` column. Well, let's leave it empty for now.
