### ISSUE TITLE
udf: `drop function` should perform dependency check

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#17263]
### Describe the bug

Currently, the DROP FUNCTION command does not check whether the function has dependencies with materialized views or sinks. This could cause undefined behaviors.

### To Reproduce

```
dev=> create table t (a int, b int);
CREATE_TABLE

dev=> CREATE FUNCTION add(a int, b int) RETURNS int LANGUAGE python AS $$
dev$> def add(x, y):
dev$>   yield a+b
dev$> $$;
CREATE_FUNCTION

dev=> create materialized view mv as select add(a, b) as c from t;                                                                                                                                                           CREATE_MATERIALIZED_VIEW

dev=> drop function add;
DROP_FUNCTION

dev=> insert into t values (1,1), (2,2), (3,3);
INSERT 0 3

dev=> select * from mv;
 c
---



(3 rows)
```

After the UDF `add` is dropped, all subsequent changes made to the MV fail to produce correct results.

### Expected behavior

1. There should be a way to check dependencies of a UDF
2. `drop function` should perform dependency checks and fail with errors when dependencies exist.

**Comment by fuyufjh** [comment]
+1. Today I was asked by a user, too. The behavior is confusing to users.

**Comment by wangrunji0408** [comment]
The current behavior is that UDFs can be dropped without any dependency check. Materialized views which are using these UDFs will not be affected, because the UDF body has been embedded into the MVs. I agree that this is not intuitive to users and a dependency check should be added before dropping.

However, the example shown above is not related to this issue. 

> ```sql
> dev=> create table t (a int, b int);
> CREATE_TABLE
> 
> dev=> CREATE FUNCTION add(a int, b int) RETURNS int LANGUAGE python AS $$
> dev$> def add(x, y):
> dev$>   yield a+b
> dev$> $$;
> CREATE_FUNCTION
> 
> dev=> create materialized view mv as select add(a, b) as c from t;                                                                                                                                                           CREATE_MATERIALIZED_VIEW
> 
> dev=> drop function add;
> DROP_FUNCTION
> 
> dev=> insert into t values (1,1), (2,2), (3,3);
> INSERT 0 3
> 
> dev=> select * from mv;
>  c
> ---
> 
> 
> 
> (3 rows)
> ```

The reason of the empty output is that `yield` is mistakenly used in a scalar function and variable name `a` mismatches input `x`. Therefore you should see this error in the log and the output was set to NULL:

```
risingwave_stream::executor::actor: failed to evaluate expression identity="Project 1700000001" 
error=TypeError: 'generator' object cannot be interpreted as an integer suppressed_count=2
```

A correct reproducible example of this issue should be:

```sql
dev=> create table t (a int, b int);
CREATE_TABLE

dev=> CREATE FUNCTION add(a int, b int) RETURNS int LANGUAGE python AS $$
dev$> def add(x, y):
dev$>   return a+b
dev$> $$;
CREATE_FUNCTION

dev=> create materialized view mv as select add(a, b) as c from t;                                                                                                                                                           CREATE_MATERIALIZED_VIEW

dev=> drop function add;
DROP_FUNCTION

dev=> insert into t values (1,1), (2,2), (3,3);
INSERT 0 3

dev=> select * from mv;
 c 
---
 4
 2
 6
(3 rows)
```

Unfortunately, due to the nature of Python language, it's hard for us to ensure the source code is workable on creation.

**Comment by xxchan** [comment]
> Materialized views which are using these UDFs will not be affected, because the UDF body has been embedded into the MVs.

BTW, similar things apply to logical `VIEW`s. The implementation just inlines them, so practically it's ok to drop them without affecting downstreams. But I implemented the dependency check (without much consideration though) https://github.com/risingwavelabs/risingwave/issues/6160

**Comment by fuyufjh** [comment]
Requested by user today.
