### ISSUE TITLE
feat(compatibility,catalog): missing columns in system catalog

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#17287]
Case 1.

`2024-06-17T18:39:16.246489366Z ERROR handle_query{mode="extended query parse" session_id=29 sql=SELECT reltuples FROM pg_class WHERE relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = $1) AND relname = $2}: pgwire::pg_protocol: error when process message error=Failed to prepare the statement: Failed to bind expression: reltuples: Item not found: Invalid column: reltuples<`

Case 2.

`2024-06-13T17:07:22.752019564Z ERROR handle_query{mode="extended query parse" session_id=1104 sql=SELECT att.attname, greatest(att.attndims, 1) AS attndims FROM pg_attribute AS att JOIN pg_type AS attyp ON att.atttypid = attyp.oid JOIN pg_class AS tbl ON tbl.oid = att.attrelid JOIN pg_namespace AS ns ON tbl.relnamespace = ns.oid WHERE ns.nspname = $1 AND tbl.relname = $2 AND attyp.typcategory = 'A'}: pgwire::pg_protocol: error when process message error=Failed to prepare the statement: Failed to bind expression: greatest(att.attndims, 1): Item not found: Invalid column: attndims`

**Comment by yuhao-su** [comment]
> Wondering which tool were you using when you found this issue?

It's found by a user using Trino

**Comment by fuyufjh** [comment]
Tried Trino and didn't meet the problem.
