### ISSUE TITLE
barrier manager state is too verbose in await-tree dump

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#17295]
Since we've added the dump of the barrier manager state in https://github.com/risingwavelabs/risingwave/pull/16562, the dump file inflates a lot and it's hard to browse.

<img width="343" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/25862682/60d47728-edeb-4e90-ae0a-6ea346bed1d2">

This is because
- We simply use alternate display representation to print out the internal structures, which can be less concise, especially with complex pipelines and a significant number of actor.
- We usually capture an await-tree when the cluster is stuck or processes slowly, at which time it's common to observe a lot of uncollected barriers, making the arrays too long.

I propose that we can only display the diffs of fields like `running_actors` or `remaining_actors` for each epoch compared to the preceding one. This not only ensures that each actor only appears once in the result, but also gives us a clear view of where and when the things start to go wrong.

cc @wenym1 @fuyufjh

**Comment by fuyufjh** [comment]
I am working on this.
