### ISSUE TITLE
support function `timezone(zone, timestamp)`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#17363]
### Is your feature request related to a problem? Please describe.

The function `timezone(zone, timestamp)` is equivalent to the SQL-conforming construct `timestamp AT TIME ZONE zone`.
https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-ZONECONVERT
We have the latter

**Comment by dttung2905** [comment]
Hi @lmatz, im new to this but interested in the issue. Do you have any pointers where to start?

**Comment by lmatz** [comment]
Hi @dttung2905


Appreciate your interest in contributing to RW!
https://github.com/risingwavelabs/risingwave/blob/main/src/expr/impl/src/scalar/extract.rs is a time-related function, you can mimic the way how it is integrated into the codebase.
