### ISSUE TITLE
bug(mysql-cdc-source): correctly propagate errors to frontend session

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#17389]
### Describe the bug

When the user creates a MySQL CDC table but failed, the actual cause of failure was not propagated to the frontend session.

The users can see:

```
ERROR:  Failed to run the query

Caused by these errors (recent errors listed first):
  1: gRPC request to meta service failed: Internal error
  2: get error from control stream: worker node {}, gRPC request to stream service failed: Internal error: Failed to send barrier with epoch {} to actor 1: channel closed;
```

But the actual cause must be found from logs.

We have met multiple related case reported recently, including:

- #16598
- [Slack message](https://risingwave-labs.slack.com/archives/C0606NNR74P/p1718951381565079?thread_ts=1718893827.636199&cid=C0606NNR74P)
- [Slack message](https://risingwave-labs.slack.com/archives/C0606NNR74P/p1718897272676819?thread_ts=1718893827.636199&cid=C0606NNR74P)

**Comment by StrikeW** [comment]
Fixed by https://github.com/risingwavelabs/risingwave/pull/17672
