### ISSUE TITLE
upgrade delta-rs to v0.18.0 and deltalake-arrow to 52

### ISSUE THREAD

**Issue by wenym1** [risingwavelabs/risingwave#17388]
### Is your feature request related to a problem? Please describe.

The latest delta-rs version 0.18.0 use arrow 52. After #17354, iceberg will also use arrow 52. If the arrow version used internally can also upgrade to 52, then we will be able to unify our multiple arrow version to possibly reduce the build time.

**Comment by xxchan** [comment]
kindly ping here

**Comment by hzxa21** [comment]
cc @xxhZs

**Comment by xxhZs** [comment]
> cc @xxhZs

Tried this before, but there was a bit of a problem with delta's dependencies at the time, which led to unnecessary arrow packages, will look at it again now!

**Comment by xxchan** [comment]
> unnecessary arrow packages

I think currently we are generally tolerant of multiple arrow versions, so it should be fine
