### ISSUE TITLE
retention_seconds rejected when connector specified in WITH clause

### ISSUE THREAD

**Issue by effnish** [risingwavelabs/risingwave#17380]
### Describe the bug

`retention_seconds` is only accepted as a valid parameter if no source (aka connector) is specified in the `WITH` clause.

### Error message/log

```text
Unknown fields in the WITH clause: {"retention_seconds": "86400"}
```

### To Reproduce

Works:

```sql
CREATE TABLE works(ts TIMESTAMPTZ, value int)
APPEND ONLY
WITH(
  retention_seconds='86400'
);
```

Fails:
```sql
CREATE TABLE fails(ts TIMESTAMPTZ, value int)
APPEND ONLY
WITH(
  retention_seconds='86400',
  connector='kafka',
  properties.bootstrap.server='localhost:6667',
  topic='test'
) FORMAT PLAIN ENCODE JSON;
```

### Expected behavior

Both tables are created with the desired retention period

### How did you deploy RisingWave?

`docker run -it --pull=always -p 4566:4566 -p 5691:5691 risingwavelabs/risingwave:latest single_node`

### The version of RisingWave

`PostgreSQL 13.14.0-RisingWave-1.11.0-alpha (8735194f600febf58aa09b6b89d5fc474b39c448)`

**Comment by fuyufjh** [comment]
Thanks for reporting this to us. `APPEND ONLY` table is an experimental feature and may be fragile at this moment. We'll fix it asap.
