### ISSUE TITLE
v1.10.0-rc.1 meta repeated logs

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#17390]
### Describe the bug

There are repeated logs for the meta node all the time.

<img width="1599" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/b7905015-7a29-48fb-a596-e8d9bfb3bc48">

### The version of RisingWave

v1.10.0-rc.1

**Comment by fuyufjh** [comment]
Fixed by https://github.com/risingwavelabs/risingwave/pull/17350
