### ISSUE TITLE
risectl/sql command to check cluster status

### ISSUE THREAD

**Issue by wjf3121** [risingwavelabs/risingwave#17522]
### Is your feature request related to a problem? Please describe.

Currently in RisingWave Cloud, we check whether we can ping the cluster (by sending a commented SQL query `-- ping`) as an indicator whether the cluster is healthy or not.

The problem with this approach is that when the cluster is under recovery, the frontend can still respond to a commented query as the parsed plan is empty but the meta is not responsive so real queries will fail.

### Describe the solution you'd like

A risectl/sql command (or anything else) to check cluster status

**Comment by BugenZhao** [comment]
> the frontend can still respond to a commented query as the parsed plan is empty but the meta is not responsive so real queries will fail

This does not seem to be true or there's something wrong. 🤔 Only DDLs are supposed to be rejected during recovery.

**Comment by yezizp2012** [comment]
> > the frontend can still respond to a commented query as the parsed plan is empty but the meta is not responsive so real queries will fail
> 
> This does not seem to be true or there's something wrong. 🤔 Only DDLs are supposed to be rejected during recovery.

I believe the scenario he encountered involves a cluster either starting up or rebooting, during which the ready timing of both frontend and compute nodes is unpredictable. Although the frontend may be ready to respond to a command query, the compute nodes might not yet be operational. This situation impacts regular queries as well. Regardless, we still require a command similar to `pg_is_in_recovery()` in PostgreSQL to verify the cluster's status.
