### ISSUE TITLE
bug: foyer OOM when flush buffer is too large

### ISSUE THREAD

**Issue by MrCroxx** [risingwavelabs/risingwave#17591]

**Comment by Li0k** [comment]
https://grafana.test.risingwave-cloud.xyz/d/LDL_mx9nz123/kubernetes-node-exporter?orgId=1&var-DS_PROMETHEUS=P2453400D1763B4D9&var-node=ip-10-0-85-244.ec2.internal&var-internal_ip=&var-diskdevices=%5Ba-z%5D%2B%7Cnvme%5B0-9%5D%2Bn%5B0-9%5D%2B%7Cmmcblk%5B0-9%5D%2B&from=1719861859407&to=1719957309686

**Comment by Li0k** [comment]
I suspect it's related to write latency, but the io latency doesn't look particularly high from the node-exporter.

![image](https://github.com/risingwavelabs/risingwave/assets/15023748/b77d40c7-9fe3-495d-a1ec-dbcea6565d19)

**Comment by MrCroxx** [comment]
> I suspect it's related to write latency, but the io latency doesn't look particularly high from the node-exporter.

The same with you. Better add more minitrace span on the write path.

**Comment by MrCroxx** [comment]
Fixed via #17595 . Reopen anytime if the bug reappears.
