### ISSUE TITLE
derive watermark for temporal filters with condition `ts >/>= expr(now())`

### ISSUE THREAD

**Issue by stdrc** [risingwavelabs/risingwave#17629]

**Comment by stdrc** [comment]
According to

https://github.com/risingwavelabs/risingwave/blob/5a56574cd9a602d3ade78b53a5f61c96684b1334/src/stream/src/executor/dynamic_filter.rs#L439-L442

and

https://github.com/risingwavelabs/risingwave/blob/5a56574cd9a602d3ade78b53a5f61c96684b1334/src/frontend/src/optimizer/plan_node/generic/dynamic_filter.rs#L111-L122

We already support deriving watermark for temporal filters with `ts >/>= expr(now())` conditions.

**Comment by st1page** [comment]
I guess it is still not open somewhere in the optimizer
```
dev=>     create table t1 (ts timestamp with time zone);
CREATE_TABLE
dev=> explain create materialized view mv as     select * from t1 where ts + interval '1 hour' > date_trunc('DAY',now());
ERROR:  Failed to run the query

Caused by:
  Conditions containing now must be of the form `input_expr cmp now() [+- const_expr]` or `now() [+- const_expr] cmp input_expr`, where `input_expr` references a column and contains no `now()`.
```

**Comment by stdrc** [comment]
Given that watermark can be derived in the following case after #17745

https://github.com/risingwavelabs/risingwave/blob/bd3b9a194efa1b78ab025f440147cba73ce20026/src/frontend/planner_test/tests/testdata/output/temporal_filter.yaml#L463-L475

I guess this issue can be closed as well.
