### ISSUE TITLE
Nodes restarted during MySQL CDC wide table streaming test

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#17647]
### Describe the bug

https://buildkite.com/risingwave-test/wide-table/builds/93#01909b5f-f10c-480b-a6d1-b15a239bc67e/1869-1870

![image](https://github.com/risingwavelabs/risingwave/assets/35356271/942bf38c-34ff-4ca1-903c-c3b96c7e21b1)

### The version of RisingWave

v1.10.0-rt.2

**Comment by cyliu0** [comment]
Maybe it's an occasional k8s error. The data sync is completed. Re-running the test.
![image](https://github.com/risingwavelabs/risingwave/assets/35356271/83eee6e9-96ff-4dcc-ad6e-9f474b0effe9)

**Comment by StrikeW** [comment]
I checked the [log](https://grafana.test.risingwave-cloud.xyz/explore?schemaVersion=1&panes=%7B%22xc2%22%3A%7B%22datasource%22%3A%22PE59595AED52CF917%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22A%22%2C%22expr%22%3A%22%7Bnamespace%3D%5C%22wide-table-ctn8w%5C%22%7D+%7C%3D+%60%60%22%2C%22queryType%22%3A%22range%22%2C%22datasource%22%3A%7B%22type%22%3A%22loki%22%2C%22uid%22%3A%22PE59595AED52CF917%22%7D%2C%22editorMode%22%3A%22builder%22%7D%5D%2C%22range%22%3A%7B%22from%22%3A%22now-6h%22%2C%22to%22%3A%22now%22%7D%7D%7D&orgId=1) of CN, there is no errors and CN get restarted indeed. If the data can fully sync into RW then I think we can close this issue.
