### ISSUE TITLE
bug: `s3_v2` connector cannot ingest new add files

### ISSUE THREAD

**Issue by tabVersion** [risingwavelabs/risingwave#17671]
### Describe the bug

originally posted by a user from the community https://risingwave-community.slack.com/archives/C03BW71523T/p1720701467609019

@wcy-fdu and I have identified the root cause that list exec just list the files once and does not keep looping, which causes the bug. 

https://github.com/risingwavelabs/risingwave/blob/1c65460c62f4bbb3e582f2a06edd2ea9951234d4/src/stream/src/executor/source/list_executor.rs#L82-L106

**Comment by st1page** [comment]
Maybe there should be some test for this case 🤔

**Comment by marceloneppel** [comment]
Using the RisingWave operator, is it safe to reschedule the compute node pod (by, for example, killing the current pod) to force the ingestion of the newly added files?
