### ISSUE TITLE
bug(catalog): `pg_stat_user_tables` is missing for metabase support

### ISSUE THREAD

**Issue by KeXiangWang** [risingwavelabs/risingwave#17753]
### Describe the bug

As title.

### Error message/log

```text
Catalog error: table or source not found: pg_stat_user_tables
```

**Comment by hzxa21** [comment]
https://github.com/metabase/metabase/pull/50102/files#diff-122d8f1486c5b97fd092fb98e7419b767c12d378bc6e668c16b1041cd965f9cb This changes in metabase causes RW MV columns cannot be reflected as well.
