### ISSUE TITLE
feat: merge small chunks for sink executor

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#17824]
### Is your feature request related to a problem? Please describe.

It has been found that the chunks of a Kinesis sink executor are too small, with an average cardinality of 1.5. Since the Kinesis sink sends one chunk at a time to the external Kinesis system, if the distance between RisingWave and Kinesis is too great, it will result in low sink throughput.

I think we can support a chunk merge executor for sinks to avoid small chunks.
<img width="672" alt="image" src="https://github.com/user-attachments/assets/4e726aaa-a55d-49c7-8661-82ecf6944932">

**Comment by fuyufjh** [comment]
IIUC, this problem eixsts for all internal operators: any chunk that passes an `Exchange` will be splitted into smaller chunks. Saying, the parallelism = 128, then every chunk will be divided by 128 = 8 rows

I am thinking that, since the problem was caused by `HashDispatcher`, shall we solve it in the `Merge`? For example, waiting for all `Ready` chunks and merge them into a single bigger chunk.

**Comment by chenzl25** [comment]
https://github.com/risingwavelabs/risingwave/issues/15713

**Comment by st1page** [comment]
> IIUC, this problem eixsts for all internal operators: any chunk that passes an `Exchange` will be splitted into smaller chunks. Saying, the parallelism = 128, then every chunk will be divided by 128 = 2 rows
> 
> I am thinking that, since the problem was caused by `HashDispatcher`, shall we solve it in the `Merge`? For example, waiting for all `Ready` chunks and merge them into a single bigger chunk.

It will hurt the latency so we need to make it configurable.

**Comment by chenzl25** [comment]
I tested the PR and it works great. There is no back pressure in the sink anymore. Let's discuss whether to apply the merging broadly (like for all types of sink or even the merge executor).

**Comment by chenzl25** [comment]
Let me add a histogram metric to monitor the input chunk rows for actor first to see in which workload, small chunks will appear. Because I think nexmark is not a good benchmark for this issue.
