### ISSUE TITLE
feat(batch): expression's error handling

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#17844]
Some users complains that they do not want some rows' expression error prevent the whole query's processing and result.
### `TRY()` function
presto and trino do this
https://trino.io/docs/current/functions/conditional.html#try
https://prestodb.io/docs/current/functions/conditional.html#try

NOTE: after https://github.com/risingwavelabs/risingwave/pull/12461, the rw's implementation of `eval_infallible` is not equal to the `try()` function in these systems

### implement your own try version of each function, such as `TRY_TO_DATE()`, `TRY_CAST()`.
duckdb, snowflake and databricks do this
https://duckdb.org/docs/sql/expressions/cast.html#try_cast (though it does not have other functions)
https://docs.snowflake.com/en/sql-reference/functions/try_to_date
https://docs.databricks.com/en/sql/language-manual/functions/try_cast.html

Personally, prefer the first one.

**Comment by lmatz** [comment]
I guess they chose the second one because their expression framework cannot be easily adapted for the first one 🤔 
The first one is composable, I believe strictly better than the second one.

**Comment by xiangjinwu** [comment]
Previous issue: #4458

**Comment by st1page** [comment]
> Previous issue: #4458

Thanks! I remember we did some discussion somewhere but I did not find it. So the issue is closed because we solved the streaming part but currently we can think about if we need to do something for the batch query.

**Comment by BugenZhao** [comment]
> Some users complains that they do not want some

...? 👀

**Comment by st1page** [comment]
> > Some users complains that they do not want some
> 
> ...? 👀

added.. Sorry, I lost this part

**Comment by fuyufjh** [comment]
As a streaming database, I hope to keep the SQL features consistent among streaming (i.e. `create materialized view as select`) and batch (i.e. `select`). For this case, I think you don't plan to add `TRY()` to streaming, right? If so, it breaks the aforementioned consistency.

Alternatively, shall we introduce a session variable to expose the expression's `strict_mode` to user? This was designed in https://github.com/risingwavelabs/risingwave/issues/4625 (See "Make it configurable") but not implemented yet.

**Comment by xxchan** [comment]
> Alternatively, shall we introduce a session variable to expose the expression's strict_mode to user? This was designed in https://github.com/risingwavelabs/risingwave/issues/4625 (See "Make it configurable") but not implemented yet.

IIUC, currently
- batch: only strict mode
- streaming: only non-strict mode

Do you mean to support non-strict mode for batch via a session var? We can't support strict mode for streaming easily. (Perhaps better to call it `batch_strict_mode`)

**Comment by fuyufjh** [comment]
> Do you mean to support non-strict mode for batch via a session var? We can't support strict mode for streaming easily.

Exactly
