### ISSUE TITLE
Postgres CDC: upstream table in different schema will sync into same Table

### ISSUE THREAD

**Issue by StrikeW** [risingwavelabs/risingwave#17890]
### Describe the bug

There are two tables named `t2` in different schema, both of them will be synced into the same RW table created via sql:
`create table t2a (...) from pg_source table 'public.t2'`. This is unexpected, since `t2a` only need data from `public.t2`.

```
mydb=#  select * from pg_publication_tables;
    pubname     | schemaname | tablename
----------------+------------+-----------
 rw_publication | abs        | t2
 rw_publication | public     | t2
(4 rows)
```

### The version of RisingWave

v1.9.2

**Comment by hzxa21** [comment]
@StrikeW Is this issue fixed?

**Comment by StrikeW** [comment]
> @StrikeW Is this issue fixed?

No yet.
