### ISSUE TITLE
source input throughput by rows/s does not match with source input throughput by MB/s

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#17907]
### Describe the bug

On 07/08, https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1720369513000&to=1720370477000&var-namespace=nexmark-bs-0-14-daily-20240707

![SCR-20240802-oed](https://github.com/user-attachments/assets/9b03877a-2a0a-4298-949a-f19804742796)

on 08/02 (recently in general multiple executions): https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1722529424000&to=1722530462000&var-namespace=nexmark-bs-0-14-daily-20240801

![SCR-20240802-nn9](https://github.com/user-attachments/assets/af28c080-6105-4455-9777-e9fafed4db73)

During this period, no change to the data generator.
Their throughput by rows/s generally matches each other.

On `main` branch,
`source_output_row_count` does not record metrics in the same place as `source_partition_input_bytes`, which could be the direct cause. But not clear yet what the root cause is.

**Comment by fuyufjh** [comment]
fixed by #17907
