### ISSUE TITLE
feat: add column in the source executor's state table to record its rate limit 

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#17916]
https://risingwave-labs.slack.com/archives/C034TRPKN1F/p1722842791017909

> My concern is that we can alter the streaming limit for MVs. So for a source in different Streaming Job, the streaming limit could be different

**Comment by fuyufjh** [comment]
I feel the the fact that “different streaming jobs are actually using different SourceExecutor” is too obscure to users, that’s why I proposed to reuse SourceExecutor.

-----

Anyway, storing them in state table sounds definitely a misuse to me. Even we need to work out this idea, I’d like to consider some other approaches
