### ISSUE TITLE
Support alter cdc backfill rate limit

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#17913]
Currently `alter table t1 set backfill_rate_limit = xx;` is not supported for cdc backfill tables.
They should support alter rate lmit as well for table.

Further we should have some tests for this case.

**Comment by StrikeW** [comment]
I think the syntax for cdc table should be consistent to https://github.com/risingwavelabs/risingwave/pull/17911, that is
```
alter table t1 set backfill_rate_limit = xx;
```
right?

**Comment by kwannoel** [comment]
> I think the syntax for cdc table should be consistent to #17911, that is
> 
> ```
> alter table t1 set backfill_rate_limit = xx;
> ```
> 
> right?

Yeah exactly. Let me amend the description.

**Comment by StrikeW** [comment]
Done in #17989
