### ISSUE TITLE
bug: backup compatible bug in v1.10

### ISSUE THREAD

**Issue by MrCroxx** [risingwavelabs/risingwave#17923]
### Describe the bug

When upgrading to v1.10, the meta node panics because of missing fields when parsing the manifest of backups.

### Error message/log

```text
thread 'rw-main' panicked at src/meta/node/src/server.rs:337:10:
Unable to start leader services: Encoding error: missing field `state_table_info` at line 1 column 77013
```

**Comment by hzxa21** [comment]
Duplicated with https://github.com/risingwavelabs/risingwave/issues/17926.
