### ISSUE TITLE
Support configure for barrier interval

### ISSUE THREAD

**Issue by Little-Wallace** [risingwavelabs/risingwave#1794]
### Problem Description

Now we use the const value for barrier interval. See code in https://github.com/singularity-data/risingwave/blob/main/src/meta/src/barrier/mod.rs#L177 
Frequently checkpoint will produce a lot of sst files in level 0.

barrier with 100ms (main branch)
<img width="728" alt="image" src="https://user-images.githubusercontent.com/16376959/162973461-c1c8e310-b3a1-4486-b64f-bc0c0cabf6f5.png">

barrier with 1 second
<img width="703" alt="image" src="https://user-images.githubusercontent.com/16376959/162973415-21a11991-d871-41cb-a715-98dcbbab97eb.png">

### Problem Solution

Support configuration for barrier interval and update the default value to 1 second

### Future Discussion

If the number of files left in level0 increases too large, it will cost more resource to compact or read hummock. Maybe we shall think about  adjusting the barrier interval  dynamically according to the increase or decrease of the total number of files in L0, or other factors.

**Comment by BugenZhao** [comment]
Previously we set the interval to 5000ms with debug profile and relies on manual `FLUSH` in the tests to make it run faster. However, the recent introduction of `RearrangedChain` has led us to set back to 100ms...

- After `RearrangedChain` is used, every MV creation will last for at least one epoch, which will make the test running much slower if we still use 5000ms. We may investigate it more in the next few days to find a better workaround.
- Some executors only yield outputs on the barrier. Several bugs were exposed with much more frequent barriers.

For production, I'd agree on setting a reasonable interval or finding some mechanism to decide one.

**Comment by Little-Wallace** [comment]
Already supported.
