### ISSUE TITLE
add streaming read retry for fast compaction

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#17962]
### Is your feature request related to a problem? Please describe.

Currently fast compaction will not try to recreate the read stream like normal compaction based on `compactor_iter_max_io_retry_times`

**Comment by Li0k** [comment]
Before implementing stream reconstruction at the object store level, I added stream reconstruction as a workaround fix to the fast compactor iterator.

**Comment by Li0k** [comment]
We can use a separate issue to track the changes to the object store behaviour and refactor the iterator-related code, but for now we can close the PR.
