### ISSUE TITLE
alias `round_digit` to `round`

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#17982]
To be compatible with pg. https://www.postgresql.org/docs/current/functions-math.html

**Comment by xiangjinwu** [comment]
Could you elaborate? `round_digit` is the internal name and `round` is the user-facing SQL name.
https://github.com/risingwavelabs/risingwave/blob/d00e2ebbeb0e814aaab1de687ea1c0dc7e4a2b0e/src/frontend/src/binder/expr/function/builtin_scalar.rs#L152-L158

**Comment by kwannoel** [comment]
Nevermind, seems like it's an issue on my part.
```
dev=> create table t(p_col double, grp_col int);
CREATE_TABLE
dev=> select round(sum(p_col), 2) from t;
ERROR:  Failed to run the query

Caused by these errors (recent errors listed first):
  1: Failed to bind expression: round(sum(p_col), 2)
  2: function round_digit(double precision, integer) does not exist

dev=> select round(sum(p_col)::numeric, 2) from t;
 round 
-------
      
(1 row)


```
