### ISSUE TITLE
Support `percentile_cont` via `approx_percentile`

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#18008]
Now that we support approx percentile, perhaps we can support streaming `percentile_cont` via `approx_percentile` too, by simply setting relative_error to 0.

Most of the work just needs to take place in the frontend.

**Comment by chagelo** [comment]
`SELECT percentile_cont(x) WITHIN GROUP (ORDER BY column1) FROM table1;` gets nonzero, while `SELECT approx_percentile(x, 0) WITHIN GROUP (ORDER BY column1) FROM table1;` always gets zero, but I'm not familar with "streaming" and hdr, and I'm not sure whether it's correct that `approx_percentile` return zero.

**Comment by kwannoel** [comment]
> `SELECT percentile_cont(x) WITHIN GROUP (ORDER BY column1) FROM table1;` gets nonzero, while `SELECT approx_percentile(x, 0) WITHIN GROUP (ORDER BY column1) FROM table1;` always gets zero, but I'm not familar with "streaming" and hdr, and I'm not sure whether it's correct that `approx_percentile` return zero.

It's a bug. Thanks for catching it. Will submit a PR to fix it shortly.

**Comment by kwannoel** [comment]
Actually it is tricky to support it via `approx_percentile`. That's because we will have to override the semantics of `bucket_id` to handle `relative_error = 0.0`. In order to keep the precision of original value when `relative_error = 0.0`, we have to store `bucket_id` (this is also the original value when relative_error = 0.0) as a `f64`. That means the range of values we can approximate a percentile for will be less.

To avoid this extra complexity and trade-off, we should implement `percentile_cont` first, and map `approx_percentile(x, 0.0)` to it instead. So it's the other way around.

Tracking issue to support `percentile_cont`: https://github.com/risingwavelabs/risingwave/issues/12857.

Closing this issue.
