### ISSUE TITLE
failed to install risingwave using homebrew in WSL or Linux

### ISSUE THREAD

**Issue by mikechesterwang** [risingwavelabs/risingwave#18056]
Got the following error:

```
Error: An exception occurred within a child process:
  MethodDeprecatedError: Calling `MacOS.sdk_path_if_needed` on Linux is disabled! There is no replacement.
Please report this issue to the risingwavelabs/homebrew-risingwave tap (not Homebrew/brew or Homebrew/homebrew-core):
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/risingwavelabs/homebrew-risingwave/Formula/risingwave.rb:46
```

Not sure if Linux is not supported. It is not mentioned in the [documentation](https://docs.risingwave.com/docs/current/get-started/#homebrew)

**Comment by BugenZhao** [comment]
There are some outstanding issues to be addressed to support Linux: https://github.com/risingwavelabs/homebrew-risingwave/issues/9

Currently it's not on the plan as we've already supported one-liner installation script for Linux.

```
curl https://risingwave.com/sh | sh
```

**Comment by mikechesterwang** [comment]
> There are some outstanding issues to be addressed to support Linux: [risingwavelabs/homebrew-risingwave#9](https://github.com/risingwavelabs/homebrew-risingwave/issues/9)
> 
> Currently it's not on the plan as we've already supported one-liner installation script for Linux.
> 
> ```
> curl https://risingwave.com/sh | sh
> ```

I see.The documentation might need this note.
