### ISSUE TITLE
Add a fast docker build buildkite workflow

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#18097]
Shared by @st1page previously.

-  @huangjw806 provision a dedicated stack for arm image.
-  @kwannoel add a dedicated pipeline which does not use LTO.

**Comment by huangjw806** [comment]
Using c7g.8xlarge instance can shorten the arm docker build to less than 25 minutes
https://buildkite.com/risingwavelabs/docker/builds/16276
