### ISSUE TITLE
bug: `store_flush` hangs for a long time

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#18207]
### Describe the bug

Barrier stuck

![image](https://github.com/user-attachments/assets/0dcba0c3-e255-4d8f-b492-9e77391ed0dc)

After we restart the cluster, the barrier was stuck for a while but dropped after several minutes.

### Error message/log

Saw lots of `store_flush` in the await tree. Such as

```text
>> Actor 40315
Actor 40315: `<redacted>` [17641.981s]
  Epoch 7018936306958336 [!!! 6725.054s]
    Project 9D7B00000017 [!!! 6725.054s]
      Now 9D7B0000289A [!!! 6725.054s]
        store_flush [!!! 6724.064s]
```

```
>> Actor 45668
Actor 45668: `<redacted>` [17459.033s]
  Epoch 7018936306958336 [!!! 6542.126s]
    Source B26400002712 [!!! 6541.256s]
      store_flush [!!! 6541.126s]
```

**Comment by Li0k** [comment]
`store_flush` cloud be blocked by acquiring memeory fail.

Have you observed any anomalies in the cluster's memory state, or have you found logs that contain the phrase ‘blocked at requiring memory’?

**Comment by wcy-fdu** [comment]
Solved and add into oncall KB.
