### ISSUE TITLE
v2.0.0-rt.1 tpch q15 performance degradation

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#18268]
### Describe the bug

http://metabase.risingwave-cloud.xyz/question/26990-rw-avg-source-throughput-release?start_date=2024-07-01&testbed=medium-1cn-affinity&workload=tpch-q15
<img width="1899" alt="image" src="https://github.com/user-attachments/assets/d8333e0a-3d9f-48b3-9276-2b6d893a1183">

**Comment by lmatz** [comment]
Is it an issue of recording the wrong end time due to some unknown reason?

![SCR-20240827-npt](https://github.com/user-attachments/assets/7585f603-3015-479f-9921-30f50b9c9a1f)


![SCR-20240827-npp](https://github.com/user-attachments/assets/91b435ba-6457-4522-a347-fac68ea2c2a2)

When clicking by the URL, the second screenshot has a period of 0 throughput at the second half period, but somehow it is still counted into the calulcation

**Comment by lmatz** [comment]
what are the criteria for determining the end time?

**Comment by cyliu0** [comment]
We use `Write Ops` = 0 as the end condition. https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1724158206000&orgId=1&to=1724160025000&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=tpch-benchmark-ngn0u&editPanel=128
<img width="1221" alt="image" src="https://github.com/user-attachments/assets/83b3f613-f51b-453e-8cba-a8ec3a521a72">

**Comment by hzxa21** [comment]
> Is it an issue of recording the wrong end time due to some unknown reason?
> 
> https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1723828156000&to=1723829176000&var-namespace=tpch-benchmark-wyw1vg
> 
> ![SCR-20240827-npt](https://private-user-images.githubusercontent.com/5791930/361731903-7585f603-3015-479f-9921-30f50b9c9a1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTg0NTUsIm5iZiI6MTcyNDgxODE1NSwicGF0aCI6Ii81NzkxOTMwLzM2MTczMTkwMy03NTg1ZjYwMy0zMDE1LTQ3OWYtOTkyMS0zMGY1MGI5YzlhMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMDQwOTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzNmN2IzYzA5MTJlNzZkNDc2ZWFlZDUzZTUyNWIxMzdjM2RlZTQ3MWZhMzRlNGY2MzkyODVlNDAyODNhNmRkMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gKYm8enuyK36bC-Z4y97d7Zja6pT5e-Ne6rpORNJRcY)
> 
> https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1724158206000&orgId=1&to=1724160025000&var-datasource=Prometheus:+test-useast1-eks-a&var-namespace=tpch-benchmark-ngn0u
> 
> ![SCR-20240827-npp](https://private-user-images.githubusercontent.com/5791930/361731885-91b435ba-6457-4522-a347-fac68ea2c2a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTg0NTUsIm5iZiI6MTcyNDgxODE1NSwicGF0aCI6Ii81NzkxOTMwLzM2MTczMTg4NS05MWI0MzViYS02NDU3LTQ1MjItYTM0Ny1mYWM2OGVhMmMyYTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMDQwOTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTNhOGI1MDBjYzQ5MjNmODMyMDRmYzMyZTk0NjY2N2FhOTI2NjBjODg0ZmQ1YjY0ZDM4MTIxYWVmOGQ0ZmE2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kAeV1Z1-Hucae9WlHO8D1ayM5xQrG0msRuinSrXeF2Q)
> 
> When clicking by the URL, the second screenshot has a period of 0 throughput at the second half period, but somehow it is still counted into the calculation
> 
> I think the system is ok, no regression if you exclude the second half period

From the second [grafana](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1724158206000&orgId=1&to=1724160025000&var-datasource=Prometheus:+test-useast1-eks-a&var-namespace=tpch-benchmark-ngn0u), I saw that there is actor throughput between fragment 135 and 141 after source throughput drops to 0:

![image](https://github.com/user-attachments/assets/9b13c147-8933-4309-888a-47aaa71974f4)
![image](https://github.com/user-attachments/assets/0328447b-af10-4eb7-a38e-d43fc8ecedab)

**Comment by lmatz** [comment]
solved by #18302
