### ISSUE TITLE
server crashed because of unsupported operator

### ISSUE THREAD

**Issue by ichn-hu** [risingwavelabs/risingwave#1829]
**Describe the bug**

was trying to create a mv containing a join

![image](https://user-images.githubusercontent.com/29735669/163307196-ecd46645-d3ed-4404-b6fa-bd83659b382c.png)

**To Reproduce**
Steps to reproduce the behavior.

```
create table t1(v1 int not null);
create table t2(v1 int not null);
create materialized view mv2 as select * from t1, t2;
```

**Expected behavior**

reporting error of operator not supported instead of crash

**Additional context**

**Comment by skyzh** [comment]
There isn't a join condition?

**Comment by ichn-hu** [comment]
> There isn't a join condition?

this is a natural join, where t1 and t2 will join on v1

**Comment by skyzh** [comment]
```
thread 'tokio-runtime-worker' panicked at 'not yet implemented: nested loop join', src/frontend/src/optimizer/plan_node/logical_join.rs:393:13
```

Our optimizer currently doesn't think it is a natural join. It recognized it as a NLJ, which is not supported in stream.

**Comment by ichn-hu** [comment]
> 

then certainly a bug?

I tried join with condition, and it worked

**Comment by skyzh** [comment]
Does Postgres recognize such cross join without condition as natural join?

**Comment by ichn-hu** [comment]
> Does Postgres recognize such cross join without condition as natural join?

well, it is not a natural join, it is a cross join... then the bug is only that the server paniced

**Comment by skyzh** [comment]
Yes, we should return an error instead of panic.

**Comment by xxchan** [comment]
Won't panic now
```
dev=> create materialized view mv2 as select * from t1, t2;
ERROR:  QueryError: Feature is not yet implemented: stream nested-loop join
```
