### ISSUE TITLE
v2.0.0-rt.3 tpch q3 perf degradation

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#18382]
### Describe the bug

![image](https://github.com/user-attachments/assets/9f677d5b-3fd0-487b-a681-e5d3196639da)

http://metabase.risingwave-cloud.xyz/question/26990-rw-avg-source-throughput-release?start_date=2024-03-01&testbed=medium-1cn-affinity&workload=tpch-q3

### The version of RisingWave

v2.0.0-rt.3

**Comment by fuyufjh** [comment]
Looks like an incidental jitter. As it doesn't block version releasing, we may run another time to see whether the issue recurs.

<img width="1095" alt="image" src="https://github.com/user-attachments/assets/7e9be3bb-1cd8-4e7f-a3e7-3ba8ea48c9b0">

**Comment by lmatz** [comment]
let's run it again: https://buildkite.com/risingwave-test/tpch-benchmark/builds/1132

**Comment by lmatz** [comment]
I suspect it is because kafka's ebs is different, let me run it again with the same configuration as weekly test
