### ISSUE TITLE
cannot restart a cluster if license key is invalid

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#18401]
### Describe the bug

Compute node will fail to start up if license key is invalid:
```
2024-09-04T13:56:29.941094867+08:00 ERROR risingwave_rpc_client::meta_client: failed to register worker, exiting... error=failed to add worker node: gRPC request to meta service failed: Internal error: cannot check CPU core limit due to license key error: invalid license key: InvalidToken
```

### To Reproduce

- ./risedev d full

- psql -h localhost -p 4566 -d dev -U root
Run in SQL: 
```
ALTER SYSTEM SET license_key TO 'invalid';
```

- ./risedev k
- ./risedev d full

**Comment by hzxa21** [comment]
@BugenZhao Is this a bug or a feature

**Comment by BugenZhao** [comment]
This is indeed a problem. But I suppose the frontend is still functional and users should be able to update their license key and fix that.

From another perspective, setting an invalid key should be a rare occurrence, unless the user fails to renew their license key on time. In this case, all paid features will no longer work, so it is expected that the user will update it as soon as possible.
