### ISSUE TITLE
[Dashboard] HTTP 404 for dependency_graph page

### ISSUE THREAD

**Issue by zoudan** [risingwavelabs/risingwave#18420]
### Describe the bug

I am using a branch which is checked out from `main` branch with this commit.
And I get 404 for `/api/fragments/job_id/xxx` and `/api/relation_id_infos`. I have tried the dashboard from https://github.com/risingwavelabs/risingwave/archive/refs/heads/dashboard-artifact.zip and the dashboard I built locally(On my mac), this error remains.
[da28570ab58385ca5850f659ed0f96e3d9843151](url)
![20240905-160029](https://github.com/user-attachments/assets/35c6a609-538a-41c4-bbcb-4b5a1fe30aba)

### How did you deploy RisingWave?

I deployed my RisingWave cluster in a K8s cluster.

### The version of RisingWave

PostgreSQL 13.14.0-RisingWave-1.9.0-alpha (unknown)

**Comment by fuyufjh** [comment]
May be related to https://github.com/risingwavelabs/risingwave/pull/18272.
 
The dashboard from https://github.com/risingwavelabs/risingwave/archive/refs/heads/dashboard-artifact.zip is built from the latest main, so the error is expected. 

> he dashboard I built locally(On my mac), this error remains.

This is wierd. Can you pls try to clean the browser cache? If the error persists, please paste the screenshot as well.

**Comment by zoudan** [comment]
@fuyufjh Thanks, it turns out that I did not use my local built dashboard correctly. After I use the right version, the error is gone. So this ticket could be closed.
