### ISSUE TITLE
v2.0.0-rt.4 creating mysql cdc source tables failed during wide table test

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#18500]
### Describe the bug

https://buildkite.com/risingwave-test/wide-table/builds/107#0191e434-7017-47a6-863a-098f2ece810a

```
[WARN] Using S3 as the storage backend! MinIO deployment is forcefully disabled!
--
  | [INFO] [workspace/k8s] [namespace: wide-table-op9kn] Happy benchmarking!
  | Generating realtime_waybill_detail data
  | Generating realtime_waybill_cost_fee data
  | Creating realtime_waybill_detail table
  | mysql: [Warning] Using a password on the command line interface can be insecure.
  | Creating realtime_waybill_cost_fee table
  | mysql: [Warning] Using a password on the command line interface can be insecure.
  | Creating RW source and tables
  | CREATE_SOURCE
  | ERROR:  Failed to run the query
  |  
  | Caused by these errors (recent errors listed first):
  | 1: Expr error
  | 2: Unsupported function: cast(timestamp with time zone) -> timestamp without time zone
  |  
  | ERROR:  Failed to run the query
  |  
  | Caused by these errors (recent errors listed first):
  | 1: Expr error
  | 2: Unsupported function: cast(timestamp with time zone) -> timestamp without time zone
```

### The version of RisingWave

v2.0.0-rt.4

**Comment by lmatz** [comment]
it worked before? sounds like a breaking change

**Comment by StrikeW** [comment]
cc @xiangjinwu to take a look. btw @cyliu0 can provide the table schema to you which is a customer scenario.

**Comment by xiangjinwu** [comment]
Note the following naming differences between MySQL and PostgreSQL (RisingWave):
* MySQL `datetime` is PostgreSQL `timestamp` (without time zone).
* MySQL `timestamp` is PostgreSQL `timestamptz`, which is number of s/ms/us passed since 1970-01-01 00:00:00 in UTC.

> Unsupported function: cast(timestamp with time zone) -> timestamp without time zone

This looks like we are trying to insert a `timestamptz` (MySQL `timestamp`) into RisingWave `timestamp`

**Comment by cyliu0** [comment]
@xiangjinwu But we have run this case for the past months. It never failed because of this. You can check the build history on the buildkite.

And we never use MySQL `timestamp` in the upstream tables according to the upstream table schemas https://github.com/risingwavelabs/kube-bench/blob/main/manifests/wide-table/wide-table-sql.template.yaml#L7-L1246.

And there is no `timestamptz` as well. You can check the source tables in the same file above.

**Comment by xiangjinwu** [comment]
Thanks for sharing the schema, which is mapping from MySQL `datetime` to RisingWave `timestamp` (without time zone) correctly. There should be no `timestamp with time zone` at all during this test. @StrikeW Is there any related change in MySQL CDC logic in the past 2 months?

**Comment by lmatz** [comment]
becaue 2.0.0-rc.1 passed the test, I suppose the buggy commit is in the following range:
https://github.com/risingwavelabs/risingwave/compare/v2.0.0-rc.1...release-2.0

**Comment by lmatz** [comment]
In the following range between `v2.0.0-rt.3` and `v2.0.0-rc.1`
https://github.com/risingwavelabs/risingwave/compare/dc8faba297a3e4a5da3ceaf8d8ca6456a00...v2.0.0-rc.1

**Comment by cyliu0** [comment]
After https://github.com/risingwavelabs/risingwave/pull/18322, we can't define column in CDC tables like this `update_time timestamp  DEFAULT CURRENT_TIMESTAMP,`. The correct definition should be `update_time timestamp  DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Singapore', -- or UTC`. We may support the former one in the future like MySQL and PG. But for now, we fixed our test cases to adapt to this in https://github.com/risingwavelabs/kube-bench/pull/457

**Comment by xiangjinwu** [comment]
#18513
