### ISSUE TITLE
Iceberg：utilize iceberg zonemap statistics to perform data skipping 

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#18645]
### Is your feature request related to a problem? Please describe.

https://github.com/apache/iceberg-rust/blob/cbbd086c92ef5a93d7dc98bbb1b26b9cf044910a/crates/iceberg/src/scan.rs#L98-L103

Iceberg-rust SDK has a method called `with_filter` for planning. We can use this method to pass predicates to perform data skipping.

**Comment by kwannoel** [comment]
1. impl predicate pushdown interface for iceberg scan.
2. Convert the predicate from rw to iceberg-rs predicate.
3. Pass the predicate to the sdk using `with-filter`.
4. They may use or / and conditions. First implementation just focus on `and` case. The `or` condition might be much more difficult to support.
5. Can also try directly convert the conditions: https://github.com/apache/iceberg-rust/blob/15b2a7aeea577b84044bda43e37bd7bc07c4a82c/crates/iceberg/src/expr/predicate.rs#L301
