### ISSUE TITLE
batch: pipelined table scan

### ISSUE THREAD

**Issue by MrCroxx** [risingwavelabs/risingwave#1870]
Currently, during table scanning, the workflow is:

```plain
s3 get -> read -> s3 get -> read -> ... -> s3 get -> read 
```

The workflow can be pipelined, and s3 get can be parallelized and blocks can be prefetched to optimize the latency:

```plain
s3 get -> read
s3 get --------> read
          s3 get -------> read
          s3 get --------------> read
```

**Comment by zwang28** [comment]
May be related: I'm wondering if block cache invalidation due to compaction will cause significantly compromise performance. If so, existent mitigations are either prefetch cache, or prevent hot cache from being invalidated (LSbM-tree). Though both methods have obvious trade-offs.

**Comment by zwang28** [comment]
And seems parallel IO can also benefit streaming when `Keyspace::scan(limit=None)`?

**Comment by BowenXiao1999** [comment]
I think we can close this? Looks like do not relates to execution layer. https://github.com/risingwavelabs/risingwave/pull/5436#discussion_r974916968
cc @BugenZhao @liurenjie1024 @xxchan.

If no, may I ask where the code snippet to start with?

**Comment by BugenZhao** [comment]
BTW, do we have prefetching in iterator now?

**Comment by BowenXiao1999** [comment]
> BTW, do we have prefetching in iterator now?

I think so. cc @hzxa21

**Comment by hzxa21** [comment]
> > BTW, do we have prefetching in iterator now?
> 
> I think so. cc @hzxa21

For CN, we will prefetch a block in the iterator so there will be at most one I/O per block.
