### ISSUE TITLE
Schema mismatch in source can lead to cluster panic

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#18715]
### Describe the bug

After two columns were added in the upstream source catalog in schema registry, the source started to panic.

```
thread 'rw-streaming' panicked at src/stream/src/executor/wrapper/schema_check.rs:48:29:
	
2024-09-25 23:06:09.896	
schema check failed on ExecutorInfo { schema: Schema { fields: [...] }, pk_indices: [34], identity: "Source 746F00002742" }: column type mismatched at position 35: expected Some(List(Varchar)), found Some("Timestamptz")
```

### Expected behavior

Should not panic.

**Comment by KeXiangWang** [comment]
Some additional information. The user is using a hotfix image derived from v1.9.1.

**Comment by xiangjinwu** [comment]
Sounds same as #16486/#17293 fixed since v1.10

**Comment by dimisjim** [comment]
this is still the case in v2.4, when using the MSSQL CDC source connector: https://docs.risingwave.com/integrations/sources/sql-server-cdc#automatically-map-upstream-table-schema

**Comment by KeXiangWang** [comment]
> when using the MSSQL CDC source connector

Could you please share more details about your setup and SQLs? cc @wcy-fdu

**Comment by dimisjim** [comment]
@KeXiangWang 

using the k8s operator, v0.10.0, with GCS as the state store and PSQL as the meta store

Just followed the guide at https://docs.risingwave.com/integrations/sources/sql-server-cdc#automatically-map-upstream-table-schema and tried to run CDC for one table

I did however enabled SQL Agent mode after first running the guide in the link above incompletely, because initially we were experiencing this log error in the compute node: 
```
2025-06-04T14:19:55.048904854Z ERROR risingwave_stream::task::stream_manager: actor exit with error actor_id=56 error=Executor error: Connector error: None is returned by `SELECT sys.fn_cdc_get_max_lsn()`, please ensure Sql Server Agent is running.
```

Could that be the reason?

**Comment by wcy-fdu** [comment]
@dimisjim  Can you share the upstream data type and your defined data type in RW?

**Comment by dimisjim** [comment]
The initial error we are getting in the compute node which causes the crashloop:

```
thread 'rw-streaming' panicked at /risingwave/src/common/src/array/mod.rs:504:29:
type mismatch, array builder type: Int32, scalar type: Int16
```

This is how it looks like on the MSSQL:
```
CREATE TABLE DbName.SchemaName.TableName (
	CREATE_DT datetime2(0) NOT NULL,
	CREATE_ID int NOT NULL,
	MUT_VON datetime2(0) NOT NULL,
	MUT_BIS datetime2(0) NOT NULL,
	KD_LNR_VIS numeric(22,0) NOT NULL,
	LOG_LNR_MUT numeric(22,0) NULL,
	VERS_VOR int NOT NULL,
	STAT_CD smallint NOT NULL,
	USERBK_NR smallint NOT NULL,
	VERS int NOT NULL,
	GF_NR smallint NOT NULL,
	TEXTC_LNR numeric(22,0) NOT NULL,
	STEUER_CD varchar(26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STEUER_CD_1 varchar(26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SORT_NR smallint NULL,
	OM_BER varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	GF_ART varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BUCHTYP_CD_DP smallint NULL,
	BUCHTYP_CD_KT smallint NULL,
	BUCH_AUSGL_CTL_CD smallint NULL,
	SH_CD_DP varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SH_CD_KT varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CHANGE_ART smallint NULL,
	GF_NR_GEGENSEITE smallint NULL,
	FILENAME_GF_SYM varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LIM_GF numeric(20,6) NULL,
	GF_NR_REVERSE smallint NULL,
	ANZ_EINH_RVAL int NULL,
	ZEIT_EINH_CD_RVAL smallint NULL,
	ANZ_EINH_RVAL_WARN int NULL,
	ZEIT_EINH_CD_RV_WA smallint NULL,
	MIG_GF_ID varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SPRACHE_CD smallint NOT NULL,
	BEZ_KURZ varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEZ_MITTEL varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEZ_LANG varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STEUER_CD_2 varchar(26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STEUER_CD_KB_TRA varchar(26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT AL1GF_AL1GF_PK PRIMARY KEY (CREATE_DT,CREATE_ID)
);
```

This is how we create the table and the source in RisingWave:
```
CREATE SOURCE source_name WITH (
    connector = 'sqlserver-cdc',
    hostname = 'mssql',
    port = '1433',
    username = 'sa',
    password = '',
    database.name = 'ODS'
);

CREATE TABLE "AL1GF" (
	"CREATE_DT" TIMESTAMP,
	"CREATE_ID" INTEGER ,
	"MUT_VON" TIMESTAMP ,
	"MUT_BIS" TIMESTAMP ,
	"KD_LNR_VIS" NUMERIC ,
	"LOG_LNR_MUT" NUMERIC ,
	"VERS_VOR" INTEGER ,
	"STAT_CD" INTEGER ,
	"USERBK_NR" SMALLINT ,
	"VERS" INTEGER ,
	"GF_NR" SMALLINT ,
	"TEXTC_LNR" NUMERIC ,
	"STEUER_CD" CHARACTER VARYING  ,
	"STEUER_CD_1" CHARACTER VARYING  ,
	"SORT_NR" SMALLINT ,
	"OM_BER" CHARACTER VARYING  ,
	"GF_ART" CHARACTER VARYING  ,
	"BUCHTYP_CD_DP" SMALLINT ,
	"BUCHTYP_CD_KT" SMALLINT ,
	"BUCH_AUSGL_CTL_CD" SMALLINT ,
	"SH_CD_DP" CHARACTER VARYING  ,
	"SH_CD_KT" CHARACTER VARYING  ,
	"CHANGE_ART" SMALLINT ,
	"GF_NR_GEGENSEITE" SMALLINT ,
	"FILENAME_GF_SYM" CHARACTER VARYING  ,
	"LIM_GF" NUMERIC ,
	"GF_NR_REVERSE" SMALLINT ,
	"ANZ_EINH_RVAL" INTEGER ,
	"ZEIT_EINH_CD_RVAL" SMALLINT ,
	"ANZ_EINH_RVAL_WARN" INTEGER ,
	"ZEIT_EINH_CD_RV_WA" SMALLINT ,
	"MIG_GF_ID" CHARACTER VARYING  ,
	"SPRACHE_CD" SMALLINT ,
	"BEZ_KURZ" CHARACTER VARYING  ,
	"BEZ_MITTEL" CHARACTER VARYING  ,
	"BEZ_LANG" CHARACTER VARYING ,
	"STEUER_CD_2" CHARACTER VARYING  ,
	"STEUER_CD_KB_TRA" VARCHAR  ,
	CONSTRAINT al1gf_al1gf_pk PRIMARY KEY ("CREATE_DT","CREATE_ID")
)
with (
    snapshot='true'
)
FROM source TABLE 'DbName.SchemaName.TableName'
```

**Comment by fmmmendes** [comment]
@wcy-fdu the original source (sql server) has the following schema structure:

`
CREATE TABLE DbName.SchemaName.TableName (
	CREATE_DT datetime2(0) NOT NULL,
	CREATE_ID int NOT NULL,
	MUT_VON datetime2(0) NOT NULL,
	MUT_BIS datetime2(0) NOT NULL,
	KD_LNR_VIS numeric(22,0) NOT NULL,
	LOG_LNR_MUT numeric(22,0) NULL,
	VERS_VOR int NOT NULL,
	STAT_CD smallint NOT NULL,
	USERBK_NR smallint NOT NULL,
	VERS int NOT NULL,
	GF_NR smallint NOT NULL,
	TEXTC_LNR numeric(22,0) NOT NULL,
	STEUER_CD varchar(26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STEUER_CD_1 varchar(26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SORT_NR smallint NULL,
	OM_BER varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	GF_ART varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BUCHTYP_CD_DP smallint NULL,
	BUCHTYP_CD_KT smallint NULL,
	BUCH_AUSGL_CTL_CD smallint NULL,
	SH_CD_DP varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SH_CD_KT varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CHANGE_ART smallint NULL,
	GF_NR_GEGENSEITE smallint NULL,
	FILENAME_GF_SYM varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LIM_GF numeric(20,6) NULL,
	GF_NR_REVERSE smallint NULL,
	ANZ_EINH_RVAL int NULL,
	ZEIT_EINH_CD_RVAL smallint NULL,
	ANZ_EINH_RVAL_WARN int NULL,
	ZEIT_EINH_CD_RV_WA smallint NULL,
	MIG_GF_ID varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SPRACHE_CD smallint NOT NULL,
	BEZ_KURZ varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEZ_MITTEL varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEZ_LANG varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STEUER_CD_2 varchar(26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STEUER_CD_KB_TRA varchar(26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT AL1GF_AL1GF_PK PRIMARY KEY (CREATE_DT,CREATE_ID)
);
`

**Comment by wcy-fdu** [comment]
Hi @dimisjim , we have open a pr to do schema check in frontend. And for your case, the schema defined in RisingWave table has some issue:
Type mismatch for column 'STAT_CD': upstream data type "smallint" should convert to Int16, but found Int32

**Comment by dimisjim** [comment]
Thank you, it was about STAT_CD after all. Issue is now gone.
