### ISSUE TITLE
storage: store meta and data in one object for small sst

### ISSUE THREAD

**Issue by Little-Wallace** [risingwavelabs/risingwave#1880]
### Problem Description

For every file we will store index-block and bloomfilter in meta object (with suffix `.meta`) and store key-values with block-based format in  data object (with suffix `.data`). But for those small files, which most of them are generated by checkpoint barrier in L0, we may cost at least two IO request to read them (once for meta while once for data).  
For cloud storage such as s3,  one request will cost tens milliseconds even if this object is very small and it's not necessary because we can store meta and data together.

### Problem Solution
When we compact a file from a shared buffer, if the file is small than 1MB, we can store meta and data in an object. Maybe we can use a plain format for small file to speed up read and scan.

**Additional context**

https://github.com/singularity-data/risingwave/issues/1110 need to seperate meta and data, but I think these two do not conflict because we just store them in a physical object, you can steal compact them as two part

**Comment by Little-Wallace** [comment]
As https://github.com/singularity-data/risingwave/issues/1794 mentioned, we may keep checkpoint barrier in a small number during a long time in the future, so the sst files generated in L0 will be small.....

**Comment by skyzh** [comment]
That's a good optimization! I'd +1 for this.

**Comment by skyzh** [comment]
> As https://github.com/singularity-data/risingwave/issues/1794 mentioned, we may keep checkpoint barrier in a small number during a long time in the future, so the sst files generated in L0 will be small.....

We can also checkpoint every x barriers, so as to produce fewer SSTs.

**Comment by wenym1** [comment]
> We can also checkpoint every x barriers, so as to produce fewer SSTs.

+1 for this, after concurrent checkpoint has been implemented. 

I think then we can decide whether to do checkpoint according to the number barrier on the flight and the number of previously uncheckpointed barriers.

**Comment by Little-Wallace** [comment]
> > As #1794 mentioned, we may keep checkpoint barrier in a small number during a long time in the future, so the sst files generated in L0 will be small.....
> 
> We can also checkpoint every x barriers, so as to produce fewer SSTs.

I do not understand. If we do not checkpoint for every barrier, it can not ensure data are presisted....

**Comment by skyzh** [comment]
> I do not understand. If we do not checkpoint for every barrier, it can not ensure data are presisted....

In the future, we can provide something like weak consistency to users, where they can directly query from shared buffer without wait_epoch. In this case, we don't need to persist data before serving data.

**Comment by skyzh** [comment]
Or we can make checkpoint interval and data freshness different. e.g., checkpoint interval = 100ms, and freshness = 1s (10 barriers produce one checkpoint).

**Comment by wenym1** [comment]
And what will be the read process if we merge the data and metadata in case of small data? One possible solution can be, in general we put the first data block together with the metadata in the metadata file, and the rest store in the data file. But this might cause read overhead when we fetch metadata.

**Comment by Little-Wallace** [comment]
finished
