### ISSUE TITLE
feat: explain a query and output a Graphviz representation of the query plan

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#18803]
In the case of a large complex query, a visualized representation can be clearer to diagnose problems, e.g. easier to know which two upstream are joined together if they are separated far away in the output of `explain <SQL>`.

https://github.com/risingwavelabs/risingwave/blob/main/src/frontend/src/scheduler/distributed/query.rs#L293-L294 output a task-level graphviz representation for debugging usage.

We can enable a query plan representation via the command `explain (graphviz) <SQL>`.

**Comment by kwannoel** [comment]
Related: https://github.com/risingwavelabs/risingwave/issues/14168

**Comment by kwannoel** [comment]
And also https://github.com/risingwavelabs/risingwave/issues/17218

**Comment by kwannoel** [comment]
Opening a tracking issue for these improvements to `explain`.

**Comment by kwannoel** [comment]
Currently we support structured output, so the major work is complete. We can support `graphviz` as well, via the `DOT` format.

This can be done in the following way:
1. Use `serde` to convert the IR into `petgraph::Graph`. https://docs.rs/petgraph/latest/petgraph/. Just enable `serde-1` feature flag.
2. From `petgraph::Graph`, this can be converted to `Dot` format: https://docs.rs/petgraph/latest/petgraph/dot/struct.Dot.html.

**Comment by lyang24** [comment]
Hi @kwannoel , I wound like to attempt on this issue - are we aiming to support logical plan and physical plan as dot format?

**Comment by kwannoel** [comment]
> Hi @kwannoel , I wound like to attempt on this issue - are we aiming to support logical plan and physical plan as dot format?

Yes, via `FORMAT DOT`.
 
> > Use serde to convert the IR into petgraph::Graph. https://docs.rs/petgraph/latest/petgraph/. Just enable serde-1 feature flag.
> 
> looking at the [code](https://github.com/petgraph/petgraph/blob/c32a86b1b8c5c198079efc9149ea2fcf956b8f6c/src/graph_impl/serialization.rs#L349) do we need to implement Deserialize for PrettySerde struct?

Yes, either implement Deserialize, or if you need more control over the way `PrettySerde` gets converted to `petgraph::Graph`, skip serde and manually convert it.

**Comment by lyang24** [comment]
send a draft - one more q which syntax is better `explain (format graphviz)` or `explain (graphviz)`?

**Comment by kwannoel** [comment]
> send a draft - one more q which syntax is better `explain (format graphviz)` or `explain (graphviz)`?

Missed this, replied here: https://github.com/risingwavelabs/risingwave/pull/19446#discussion_r1847798131. Thanks for your contribution!
