### ISSUE TITLE
storage: support variable vnode count in compation

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#18888]
Compactor is aware of vnode since #13075, where `table_vnode_partition` controls how a table's data is organized by `SstableBuilder` during compaction. As different tables have different vnode counts since #18444, we need more context in `SstableBuilder` to decide where to cut off the tables to be build.

Specifically, we need to address the `TODO` here:

https://github.com/risingwavelabs/risingwave/blob/e520bc66cca42e4d028caeb1af7ded8d95819770/src/storage/src/hummock/sstable/multi_builder.rs#L96-L97

**Comment by BugenZhao** [comment]
Can we close this issue as completed now?

**Comment by Li0k** [comment]
> Can we close this issue as completed now?

yes,I think we have completed the ability to support compaction of different table vnodes. I'll turn this PR back on when I run into other problems.
