### ISSUE TITLE
storage: slow down/stall writes when compaction can't keep up

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#1903]
**Is your feature request related to a problem? Please describe.**
Too many L0 SST files can compromise hummock read, and lead to compaction tasks handling a large number of input files. 

**Describe the solution you'd like**
Add backpressure for hummock write(`HummockManager::add_tables`).
However simply stall write can lead to checkpoint timeout, which should be taken care of.

**Comment by skyzh** [comment]
HummockManager::add_tables is a background job called by shared buffer sync. If we don't slow down the streaming computing process (which is the root cause), there will only be bigger problems.

Hummock meta / compaction can be an indicator for streaming back-pressure.

**Comment by zwang28** [comment]
> HummockManager::add_tables is a background job called by shared buffer sync. If we don't slow down the streaming computing process (which is the root cause), there will only be bigger problems.
> 
> Hummock meta / compaction can be an indicator for streaming back-pressure.

Could it be a cascading backpressure, e.g. meta->shared buffer->streaming?

**Comment by skyzh** [comment]
> Could it be a cascading backpressure, e.g. meta->shared buffer->streaming?

That could be possible. We can later benchmark to see if our current back pressure methods really work 🤣

**Comment by zwang28** [comment]
Open a new issue when considering to work on it.
