### ISSUE TITLE
feat(system table): add `properties map(varchar,varchar)` in rw_sources and rw_sinks

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#19072]
### Is your feature request related to a problem? Please describe.

Required for the source page of the cloud portal: https://linear.app/risingwave-labs/issue/CLOUD-3318/%5Bfeature-request%5D-source-details-page

**Comment by fuyufjh** [comment]
@xxchan Can you please help with this

**Comment by tabVersion** [comment]
dissussed with @neverchanje and @xuhui-lu

* for v2.1 and before, the cloud team will parse SQL and extract the props
* after v2.2, the the cloud relies on rw_catalog for resolved props (after resolving connection catalog)
  * had an agreement on value protocol
  * for normal value, it should be `{"some key": {"type": "plaintext", "value": "xxxx"}}`
  * for secret, it should be `{"some key": {"type": "secret", "value": "<secret name>"}}`
