### ISSUE TITLE
Provide a way to check backfilling rate (in rows/s).

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#19120]
We received a complaint from customer about the lack of the backfilling rate.
So far, we've planned to show "elapsed time" and "progress in percentage" on ui, but the backfilling rate is an essential metric to include as well.

Please comment within the issue about what's the approach I can use to obtain this data. cc @xxchan

**Comment by xxchan** [comment]
On Prometheus/Grafana, we have:
- Backfill Snapshot Read Throughput
- Backfill Upstream Throughput
- Snapshot Backfill Lag
- Source Backfill Throughput

With SQL `SHOW JOBS` or `select * from rw_ddl_progress`, there's a `progress` string, can be like:
- `MView Backfill: 99.99% (3/3), Source Backfill: 0 rows consumed`
- `Snapshot [32.08%]`

So there's no direct access to backfilled rows. If needed, we may add a column besides the `progress` string, as https://github.com/risingwavelabs/risingwave/pull/18112#discussion_r1741571151.

**Comment by fuyufjh** [comment]
Please check the [Grafana dashboard definition](https://github.com/risingwavelabs/risingwave/blob/87b7164b8029e779c7ccd5f6a475376c491ad0dc/grafana/risingwave-dev-dashboard.dashboard.py) for the PromQL query. These panels are exactly what you need:

- Backfill Snapshot Read Throughput (for MV backfilling)
- Source Backfill Throughput (for Source backfilling)
