### ISSUE TITLE
feat: support ingesting Timestamp(nanoseconds) from Iceberg

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#19163]
Right now
```
ERROR:  Failed to run the query

Caused by:
  DataInvalid => Unsupported Arrow data type: Timestamp(Nanosecond, None)
```
https://github.com/apache/iceberg/milestone/42?closed=1
https://github.com/apache/iceberg/issues/8657
https://github.com/apache/iceberg-rust/pull/542

**Comment by lmatz** [comment]
how about a struct of `timestamp` + `integer` (for the nanosecond part) as a workaround

**Comment by chenzl25** [comment]
@lmatz The Iceberg table currently doesn't contain a nano timestamp column type (because no engine can create such a table at least for now). The original time stamp issued came from the parquet file source.

**Comment by lmatz** [comment]
https://github.com/risingwavelabs/risingwave/pull/19221

**Comment by chenzl25** [comment]
After https://github.com/risingwavelabs/risingwave/pull/19221, it should be supported.
