### ISSUE TITLE
Avoid relying on barrier_interval_ms to increase operator cache eviction watermark

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#19403]
After #16087, we have switched to using sequence-based memory eviction policy instead of an epoch-based policy. This means we no longer need to rely on barrier to increase the watermark. However, it seems that we are still use `barrier_interval_ms` as the ticker interval [here](https://github.com/risingwavelabs/risingwave/blob/579cf6d437b6fd6b36ff5fcc5babd90b704491cb/src/compute/src/memory/manager.rs#L91). This may result in delay in cache eviction when `barrier_interval_ms` is increased.

**Comment by yuhao-su** [comment]
This is a long existing issue. We should first make sure all executors are not evicting cache on barrier basis.

**Comment by hzxa21** [comment]
> This is a long existing issue. We should first make sure all executors are not evicting cache on barrier basis.

I think we already did? Just checked hash join and hash agg.

**Comment by MrCroxx** [comment]
> This is a long existing issue. We should first make sure all executors are not evicting cache on barrier basis.

It had been done before the sequence-based operator cache eviction.
