### ISSUE TITLE
Use `explain (distsql, format dot)` for dashboard to visualize graph

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#19542]
https://risingwave-labs.slack.com/archives/C034U0NH5ND/p1732267878599779?thread_ts=1732168127.133129&cid=C034U0NH5ND

Current the RW dashboard has a graph for distributed plan:
![image](https://github.com/user-attachments/assets/f0f90f3f-ed5c-4e48-b9e7-79328b003055)

We can replace this with `explain (format dot, distsql)` and render it with graphviz.

We might not support `distsql + format dot` yet. This is a prerequisite for this task.

**Comment by lyang24** [comment]
got sometime this weekend, can i take this?

**Comment by kwannoel** [comment]
> can i take this?

Assigned, thanks!

**Comment by kwannoel** [comment]
You can open 2 separate PRs. One for explain format dot distsql. Another for the dashboard changes.

**Comment by lyang24** [comment]
May not relate to this issue directly, just checked out the explain function on dashboard, from a user point of view - I felt like its easier to  write the explain (distsql) xxx and get the graph output. Currently i have to paste the output json from terminal to the ui.

**Comment by kwannoel** [comment]
> May not relate to this issue directly, just checked out the explain function on dashboard, from a user point of view - I felt like its easier to write the explain (distsql) xxx and get the graph output. Currently i have to paste the output json from terminal to the ui.

We can change this panel to a more general "render graphviz" panel. It can be used to render all kinds of explain queries.
The dashboard cannot directly run the SQL, we will need to manage access to the DB.
