### ISSUE TITLE
PERCENTILE_CONT

### ISSUE THREAD

**Issue by rchui** [risingwavelabs/risingwave#19548]
### Is your feature request related to a problem? Please describe.

PERCENTILE_CONT is used to compute a given percentile value on a continuous distribution of an input column. This is useful for a variety of statistical calculations. It is also a standard Postgres function.

### Describe the solution you'd like

I would like PERCENTILE_CONT to be implemented (https://www.postgresql.org/docs/9.4/functions-aggregate.html) so that it is usable in RisingWave.

### Describe alternatives you've considered

Computing this value in SQL would be quite difficult.

You could potentially use the UDF server to work around this limitation.

**Comment by fuyufjh** [comment]
duplicated #12857
