### ISSUE TITLE
dashboard: show epoch on DAG

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#19652]
I found you once raised the idea to show the epoch on DAG. 🤔

https://github.com/risingwavelabs/risingwave/issues/13481#issuecomment-2301341892

_Originally posted by @xxchan in https://github.com/risingwavelabs/risingwave/pull/19639#discussion_r1865898939_

**Comment by fuyufjh** [comment]
Duplicated with https://github.com/risingwavelabs/risingwave/issues/19619 ?
