### ISSUE TITLE
PostgreSQL SQL compatibility: VARCHAR(N)

### ISSUE THREAD

**Issue by emarsden** [risingwavelabs/risingwave#19864]
### Describe the bug

SELECT 'foo'::varchar(20) triggers a parse error.

### Error message/log

```text
ERROR:  Failed to run the query

Caused by:
  sql parser error: expected end of statement, found: (
LINE 1: SELECT 'foo'::varchar(20);
                              ^
```

### To Reproduce

SELECT 'foo'::varchar(20);

### How did you deploy RisingWave?

Via the dockerhub image.

### The version of RisingWave

PostgreSQL 13.14.0-RisingWave-2.1.0 (d6e98acc5c1faf815855a313e2464d9a4876ff4f)

**Comment by lmatz** [comment]
Thanks @emarsden, 

in RW, the underlying implementation does not differentiate varchar(x), varchar(y), and varchar types.

So we chose to ban the varchar() ones to avoid users' confusion.

**Comment by emarsden** [comment]
OK, thanks. I see that this is documented at https://docs.risingwave.com/sql/data-types/overview. It would be useful for users to document the limitations in PostgreSQL compatibility more explicitly (I see for example that the obj_description() function from PostgreSQL does not return correct results for a "COMMENT ON TABLE ...").
