### ISSUE TITLE
Size of `AllOrNoneState<MemoryStateStore>` is huge

### ISSUE THREAD

**Issue by yuhao-su** [risingwavelabs/risingwave#214]
```rust
println!("{}", std::mem::size_of::<AllOrNoneState<MemoryStateStore>>());
```

176

It's too huge as a hash value, but we can optimize it later.

_Originally posted by @TennyZhuang in https://github.com/singularity-data/risingwave/issues/2114#issuecomment-998562004_

**Comment by xxchan** [comment]
seems fixed
