### ISSUE TITLE
streaming: MVCC arrange cache on replicate executor

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#2161]
* lower cost when failover -- only need to reset arrange cache
* lower memory footprint -- all lookups now share the same cache

**Comment by jon-chuang** [comment]
How are the current arrangement index MVCC currently represented in storage? Are they simply immutable indexed batches?

**Comment by skyzh** [comment]
Currently, they are simply stored in an LSM tree. The index has no difference from other materialized views. It is not represented as operations (like insertions and deletions). It provides access to an index of any given epoch. The storage layer directly supports MVCC read. See https://github.com/singularity-data/risingwave/blob/main/docs/state-store-overview.md for more information.

Therefore, in RisingWave, we can get all data of a specified epoch from the storage layer, as long as the epoch is above the watermark.

**Comment by jon-chuang** [comment]
I agree that maintaining a shared in-memory hashmap cache for the arrangement is more efficient. Currently we are telling every new operator using an arrangement to build the cache from S3. Can use existing data locality mechanisms to schedule actors on the same node for lookup when doing cross-MV.

**Comment by jon-chuang** [comment]
Could look into: https://docs.rs/concread/latest/concread/index.html

**Comment by skyzh** [comment]
Indeed, I’m thinking of simply using a RwLock. Here’s why.

Under current design, lookup can only start processing data when arrangement is ready (receive a barrier). So for shared index, only materialize executor performs write, and it only produces one single write batch. I guess a write-preferred RwLock could be enough.

I haven’t considered deep about the design, we can discuss more 🤪
