### ISSUE TITLE
states-store: different behaviours for HummockStateStore and MemoryStateStore

### ISSUE THREAD

**Issue by BowenXiao1999** [risingwavelabs/risingwave#2197]
**Describe the bug**
Seems like sql results of runing compute node in IDE (MemoryStateStore) or running in risedev (HummockStateStore) is different. Now the HummockStateStore one passed all tpch e2e tests while MemoryStateStore hang in specific tests. Test in current master commit and 9eef6b85caf2c9a389f336455fb2a70018e7a5fb

**To Reproduce**
* `./risedev dev dev-compute-node`. Remeber to change the config in risedev.yml to use `frontend` instead of `frontend-legacy`. 
* Start debug mode of compute node in IDE
* Run tests `./risedev slt -p 4566 './e2e_test/v2/streaming/*.slt'`
It will hang at specific tests.

**Expected behavior**
Should pass all tests

**Additional context**
This comes from I want to debug my changes to simple agg keyspace encoding. I found HummockStateStore runs different with MemoryStateStore

**Comment by skyzh** [comment]
The memory kv store is intended for writing unit tests. RiseDev by default uses Hummock + in-memory object store.

**Comment by skyzh** [comment]
But I'd like to know why memory state backend hangs... The design is to clone everything in memory every time we create an iterator.

**Comment by BowenXiao1999** [comment]
> The memory kv store is intended for writing unit tests. RiseDev by default uses Hummock + in-memory object store.

So if i run compute node in IDE, it is still using HummockStateStore + in-memory object store? That's fresh, object store may be another potential point.

**Comment by skyzh** [comment]
No, it's using kv store if directly started from IDE.

We can set

```
    #[clap(long, default_value = "in-memory")]
    pub state_store: String,
```

to be `hummock_memory` by default, instead of `in-memory`.

**Comment by BowenXiao1999** [comment]
> No, it's using kv store if directly started from IDE.
> 
> We can set
> 
> ```
>     #[clap(long, default_value = "in-memory")]
>     pub state_store: String,
> ```
> 
> to be `hummock+memory` by default, instead of `in-memory`.

I tried `hummock+memory` and it will not hang. Should be a problem of in-memory.

**Comment by skyzh** [comment]
Yes. Next time it hangs, you may use CLion to pause the program, and you may paste the stack here so that I can find the reason. I guess it would be something like deadlock, or it's not really dead-locked -- it's just running too slow.

**Comment by skyzh** [comment]
Maybe another PR to set state_store to hummock+memory by default? I think it's already stable enough.

**Comment by BowenXiao1999** [comment]
> Maybe another PR to set state_store to hummock+memory by default? I think it's already stable enough.

Yes let's quick fix this. I will put some breakpoints in future to see the reason.

**Comment by BowenXiao1999** [comment]
```
__psynch_cvwait 0x00000001bc69d0c0
_pthread_cond_wait 0x00000001bc6d5808
wait pthread_condvar.rs:82
wait condvar.rs:43
wait<()> condvar.rs:189
park thread.rs:112
{closure#0} thread.rs:281
{closure#0}<tokio::park::thread::{impl#6}::park::{closure_env#0}, ()> thread.rs:249
try_with<tokio::park::thread::ParkThread, tokio::park::thread::{impl#5}::with_current::{closure_env#0}<tokio::park::thread::{impl#6}::park::{closure_env#0}, ()>, ()> local.rs:442
with_current<tokio::park::thread::{impl#6}::park::{closure_env#0}, ()> thread.rs:249
park thread.rs:281
block_on<core::future::from_generator::GenFuture<compute_node::main::{async_block_env#0}>> thread.rs:267
block_on<core::future::from_generator::GenFuture<compute_node::main::{async_block_env#0}>> enter.rs:151
block_on<core::future::from_generator::GenFuture<compute_node::main::{async_block_env#0}>> mod.rs:81
block_on<core::future::from_generator::GenFuture<compute_node::main::{async_block_env#0}>> mod.rs:477
main compute_node.rs:32
call_once<fn(), ()> function.rs:248
__rust_begin_short_backtrace<fn(), ()> backtrace.rs:122
{closure#0}<()> rt.rs:145
[Inlined] core::ops::function::impls::_$LT$impl$u20$core..ops..function..FnOnce$LT$A$GT$$u20$for$u20$$RF$F$GT$::call_once function.rs:280
[Inlined] std::panicking::try::do_call panicking.rs:492
[Inlined] std::panicking::try panicking.rs:456
[Inlined] std::panic::catch_unwind panic.rs:137
[Inlined] std::rt::lang_start_internal::_$u7b$$u7b$closure$u7d$$u7d$ rt.rs:128
[Inlined] std::panicking::try::do_call panicking.rs:492
[Inlined] std::panicking::try panicking.rs:456
[Inlined] std::panic::catch_unwind panic.rs:137
lang_start_internal rt.rs:128
lang_start<()> rt.rs:144
main 0x00000001022c1030
start 0x000000010cde50f4
```

It looks indeed a dead lock. This is the stack I paused. Any useful info can get from this? I guess hard..

**Comment by skyzh** [comment]
Looks hard to debug with this stack trace 🤣

**Comment by skyzh** [comment]
Basically, the in-memory state backend has one single big lock

```
Arc<Mutex<BTreeMap<KeyWithEpoch, Option<Bytes>>>>,
```

We can refactor the code to hold it as fewer times as possible...

**Comment by skyzh** [comment]
Or we can change the lock to `std::sync::Mutex` or parking lot Mutex, then the backtrace should be easy to understand.

**Comment by BowenXiao1999** [comment]
It's solved After change to parking lot Mutex. However the backtrace seems not differ to above.

**Comment by xxchan** [comment]
Can we close now?

**Comment by BowenXiao1999** [comment]
Yes. I believe longetivty test may be better to find such bug.
