### ISSUE TITLE
streaming: ensure barriers are the same across inputs in Union executor

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#2223]
Currently, we are using tokio::sync::Barrier, and we cannot do sanity check about barrier equivalence. This check is better to be added.

**Comment by skyzh** [comment]
cc @wangrunji0408 if you are still interested in this 🤣

**Comment by skyzh** [comment]
No. Epoch has two properties: prev and curr. We can check if the new barrier's prev is the same as the previous barrier's curr. This check can also be done in DebugExecutor.

**Comment by BugenZhao** [comment]
> This check can also be done in DebugExecutor.

+1.
