### ISSUE TITLE
crd: need to update risingwave yaml files for separated components and config maps.

### ISSUE THREAD

**Issue by twocode** [risingwavelabs/risingwave#2509]
**Describe the bug**
The recent changes in kernel should be reflected in risingwave yaml configurations as well, including the components and configuartions.
```
test                         15s         Warning   Failed                    pod/test-risingwave-amd64-meta-node-6c9d4d7b4c-hb5jb           Error: failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/risingwave/bin/meta-node": stat /risingwave/bin/meta-node: no such file or directory: unknown
```
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: internal error: parse error unknown field `checksum_algo`, expected one of `sstable_size`, `block_size`, `bloom_false_positive`, `share_buffers_sync_parallelism`, `shared_buffer_threshold`, `shared_buffer_capacity`, `data_directory`, `async_checkpoint_enabled`, `write_conflict_detection_enabled`, `block_cache_capacity`, `meta_cache_capacity` for key `storage` at line 10 column 1
```

**To Reproduce**
Use docker & risingwave operator.

**Expected behavior**
A functioning kunernetes cluster.

**Comment by hzxa21** [comment]
Are you refering to `risingwave,toml`? I think changes are reflected to this toml file already. I think the problem is caused by not updating the [const](https://github.com/singularity-data/risingwave-operator/blob/3f54dd84a054a0c56bb945e5aa8f93fd377fed04/pkg/manager/consts.go#L57) in operator after recent changes.

**Comment by hzxa21** [comment]
Maybe we should do nightly build on the docker image and run CI against operator so we can capture the bugs sooner?

**Comment by skyzh** [comment]
Caused by https://github.com/singularity-data/risingwave/pull/2299, but it seems that nobody responds to my comments:

> cc @Nebulazhang I guess this is a big change in docker image packaging, and maybe risingwave-operator needs changing accordingly? We have an example docker-compose file here: https://github.com/singularity-data/risingwave/blob/main/docker/docker-compose.yml

> Also we have a new component compactor in cluster. Also need to add compactor.

> See https://github.com/singularity-data/risingwave/pull/2306 for more information.

**Comment by skyzh** [comment]
> Are you refering to `risingwave,toml`? I think changes are reflected to this toml file already. I think the problem is caused by not updating the [const](https://github.com/singularity-data/risingwave-operator/blob/3f54dd84a054a0c56bb945e5aa8f93fd377fed04/pkg/manager/consts.go#L57) in operator after recent changes.

We have changed `risingwave` image to use the single binary `risingwave` instead of meta node + compute node + frontend node.

**Comment by skyzh** [comment]
Let's transfer this to risingwave-operator repo later. I believe it's not a bug of risingwave kernel itself. 😇

**Comment by Nebulazhang** [comment]
> Caused by #2299, but it seems that nobody responds to my previous comments:
> 
> > cc @Nebulazhang I guess this is a big change in docker image packaging, and maybe risingwave-operator needs changing accordingly? We have an example docker-compose file here: https://github.com/singularity-data/risingwave/blob/main/docker/docker-compose.yml
> 
> > Also we have a new component compactor in cluster. Also need to add compactor.
> > See #2306 for more information.

I missed the comments...
And I will update the operator for `single binary feature` and `make risingwave.toml as configmap`

**Comment by skyzh** [comment]
Also add the compactor 🤣

**Comment by twocode** [comment]
> Maybe we should do nightly build on the docker image and run CI against operator so we can capture the bugs sooner?

+1. We should consider adding a slim test to run the image and run simple queries.

**Comment by skyzh** [comment]
Maybe operator should use tagged version of docker image instead of `latest` 🤪
