### ISSUE TITLE
Implement TEXT/STRING type as  alias of VARCHAR?

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#2535]
It's supported on legacy frontend.

Need some investigation.

**Comment by fuyufjh** [comment]
How about starting from `String`? AFAIK, `String` is an alias of `Varchar` in many systems. @TennyZhuang

**Comment by lmatz** [comment]
Did we come to a conclusion on this issue?
From https://stackoverflow.com/questions/4848964/difference-between-text-and-varchar-character-varying, it seems that `text` and `varchar` are the same in all aspects.

**Comment by fuyufjh** [comment]
I think we have. If you meet some cases using `STRING` or `TEXT`, please help to accomplish this feature 😁
