### ISSUE TITLE
Migrate regression tests to Rust frontend

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#2537]
Migrate regress tests `src/tests/regress/` to Rust frontend and enable [them](https://github.com/singularity-data/risingwave/pull/2519/files/2ef98f693fb42eeb1bf0df3facfa95549f4b35f2..bc070640072b16abd5f4afb276eb875dce97970a#diff-de94810cb4bba3cd527324abf6f643f708c92396756ea14c50de470beb643f22R118).

See also #2523

**Comment by fuyufjh** [comment]
Please take a look 🥰 @liurenjie1024

**Comment by liurenjie1024** [comment]
Sure, I'll try to set it up.

**Comment by liurenjie1024** [comment]
cc @sumittal  Please help to enable it.

**Comment by xxchan** [comment]
fixed https://github.com/risingwavelabs/risingwave/pull/3990
