### ISSUE TITLE
Discussion: How to handle `START TRANSACTION`?

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#2541]
`START TRANSACTION` is unavoidable for some pg clients, e.g. `psycopg2` will always send a `START TRANSACTION` statement on `execute_many`.

Fully support transaction is too hard and gives few benefits to us.

* Atomicity is guaranteed by barrier, but the barrier injection will not wait for `COMMIT`.
* Durability can be supported by insert an implicit `FLUSH` on `COMMIT`.

Another question is that, should we pin an epoch in a transaction?

The trivial idea is that we can just ignore it and return an empty response.

**Comment by yuhao-su** [comment]
For stream sources like kafka, maybe we should read one snapshot for all queries in a transaction. For table source, we might need more discussion since it involves `Insert`.

**Comment by fuyufjh** [comment]
+1 for ignoring it
