### ISSUE TITLE
create mv stuck for unknown reason

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#2580]
**Describe the bug**
Sometimes create MV would stuck without any reason. When create mv is initiated, CPU usage is low, and sql won't end.

**To Reproduce**
No idea how to reproduce. IIRC, CI sometimes would fail because of timeout. If there's any follow-ups, I'll post it here.

**Expected behavior**

**Additional context**

**Comment by xxchan** [comment]
Does it still occur?

**Comment by skyzh** [comment]
Need bench later to see if this still happens under heavy workload.
