### ISSUE TITLE
dashboard v2: migrate from JS to TS

### ISSUE THREAD

**Issue by Ad-Bean** [risingwavelabs/risingwave#2592]
#2368 migrate dashboard v2 from JS to TS, currently working in progress

**Comment by skyzh** [comment]
An alternative is only use ts for the proto part, but js for d3 part. IIRC, ts + d3 is extremely hard to use.

**Comment by skyzh** [comment]
e.g., we pass a ts struct for d3 to render, but the svg / canvas renderer will still be in js.

**Comment by Ad-Bean** [comment]
> An alternative is only use ts for the proto part, but js for d3 part. IIRC, ts + d3 is extremely hard to use.

I've already migrated the proto part to ts, and currently working on SVG engine.

If migrate d3 to ts will cause problems that cannot fix or hard to use, Im considering use [react-diagrams](https://projectstorm.cloud/react-diagrams) for alternative

**Comment by skyzh** [comment]
That's cool!
