### ISSUE TITLE
Pgwire write_message not work

### ISSUE THREAD

**Issue by cykbls01** [risingwavelabs/risingwave#2610]
**Describe the bug**
<img width="754" alt="image" src="https://user-images.githubusercontent.com/36026213/168886593-b8e8b87c-2fea-4f8c-8f6d-209520007096.png">
If we hidden this code, we can get the result.
<img width="289" alt="image" src="https://user-images.githubusercontent.com/36026213/168886784-09ea5435-76ae-4c1e-96e3-8ad525b78724.png">

<img width="764" alt="image" src="https://user-images.githubusercontent.com/36026213/168886474-6dca2989-9a8c-4f2c-bd01-269b2e8d3e57.png">
But if we open this code, we will just get the query result but not "SELECT 0".
<img width="272" alt="image" src="https://user-images.githubusercontent.com/36026213/168887067-f96ce9b4-749f-4231-abde-874775149b43.png">

**Expected behavior**
Make the code self.write_message_no_flush(&BeMessage::CommandComplete(BeCommandCompleteMessage { ... work rightly.

**Additional context**

**Comment by xxchan** [comment]
Is this issue still relevant? cc @BowenXiao1999

**Comment by BowenXiao1999** [comment]
I still can not understand the point. I think this is the expected behaviour.

**Comment by BowenXiao1999** [comment]
I got some idea. Maybe we should choose write_no_flush for RowDescription and DataRow. Submit a PR later
