### ISSUE TITLE
Support subquery and `FROM` in `UPDATE`

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#2672]
- Unnesting.
  ```sql
  UPDATE employees SET sales_count = sales_count + 1 WHERE id =
    (SELECT sales_person FROM accounts WHERE name = 'Acme Corporation');
  ```

- Subquery on the right side of multi-assignment.
  ```sql
  -- Update contact names in an accounts table to match the currently assigned salesmen:
  UPDATE accounts SET (contact_first_name, contact_last_name) =
      (SELECT first_name, last_name FROM salesmen
       WHERE salesmen.id = accounts.sales_id);
  ```

- `UPDATE ... SET ... FROM`.
  ```sql
  -- A similar result could be accomplished with a join:
  UPDATE accounts SET contact_first_name = first_name,
                      contact_last_name = last_name
    FROM salesmen WHERE salesmen.id = accounts.sales_id;
  ```

Related PR: #2602

**Comment by likzn** [comment]
@BugenZhao Hi,I want try this. May i ask, should we update `src/sqlparser` which mentioned in #2602 firstly? If sure, how to update.Directly copy paste?   And is the repo `andygrove / sqlparser-rs` or `sqlparser-rs / sqlparser-rs`?

**Comment by BugenZhao** [comment]
> @BugenZhao Hi,I want try this. May i ask, should we update `src/sqlparser` which mentioned in #2602 firstly? If sure, how to update.Directly copy paste? And is the repo `andygrove / sqlparser-rs` or `sqlparser-rs / sqlparser-rs`?

Cool! cc @neverchanje Do we have a plan for syncing sqlparser from the upstream?
Besides, this may not just be simply parser stuff. We may need to do some work on the optimizer as well. :)

**Comment by CAJan93** [comment]
> Cool! cc @neverchanje Do we have a plan for syncing sqlparser from the upstream? [...]

I think having a plan how to incorporate changes from [sqlparser-rs](https://github.com/sqlparser-rs/sqlparser-rs) into our project would make sense. I did another bug recently (see https://github.com/risingwavelabs/risingwave/pull/5673), which turned out to be already fixed in upstream. Do you think it makes sense to use the parser as a git submodule?
