### ISSUE TITLE
show progress of create mv

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#2691]
Create MV on existing data could be slow. If we can show progress, users will be happy.

May need to develop our own cli, or have some CRUD endpoints on dashboard, if we want to support this?

**Comment by BugenZhao** [comment]
With rearranged chain, the progress per parallel unit might be simply indicated by the currently consumed barrier and the latest rearranged barrier. :)

**Comment by BugenZhao** [comment]
#7914
