### ISSUE TITLE
frontend: support cancel command

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#2731]
When Ctrl+C in psql, RisngWave currently won't terminate a command. It will simply stuck.

**Comment by neverchanje** [comment]
https://github.com/singularity-data/risingwave/pull/1603/files We do have supported canceling, perhaps the malfunctioning is due to some bugs.

**Comment by TennyZhuang** [comment]
Cancel a query is non-trivial.

**Comment by skyzh** [comment]
> Cancel a query is non-trivial.

I think we can start with two commands: create MV and flush. Ctrl+C on create mv will simply move the create mv to the background (we can implement real cancel in the future). Ctrl+C on flush will simply end the flush RPC, which should not have any effect.

**Comment by fuyufjh** [comment]
> > Cancel a query is non-trivial.
> 
> I think we can start with two commands: create MV and flush. Ctrl+C on create mv will simply move the create mv to the background (we can implement real cancel in the future). Ctrl+C on flush will simply end the flush RPC, which should not have any effect.

This approach sounds like handling CANCEL as a nop? i.e. returns OK immediately

**Comment by skyzh** [comment]
Yes, I think it would be okay to implement it as NOP for now.

**Comment by fuyufjh** [comment]
+1 for NOP implementation

**Comment by hzxa21** [comment]
I encounter some issues related to this topic. If we don't support canceling MV creation, it is a potential threat to our system:
- User can make mistake and create a MV that hurts the performance and stability of our system. For example, user may create a MV to join two other MVs with large data volume. This MV creation may take long and even never succeeds if new MV's throughput cannot keep up with its upstream MVs. #3899 can help to avoid starvation on MV creation but will cause the backpressure on upstreaming MVs, hurting their freshness and availability (we cannot do scaling) . It is very useful if user/admin can cancel an ongoing MV creation to fix this unexpected user behavior.
- Also, if we don't cancel the MV creation, we cannot drop the upstream MV/Source/Tables this creating MV depends on.

**Comment by liurenjie1024** [comment]
I think we can support cancel batch query. cc @BowenXiao1999

**Comment by BowenXiao1999** [comment]
> https://github.com/singularity-data/risingwave/pull/1603 We do have supported canceling, perhaps the malfunctioning is due to some bugs.

The malfunction comes from some previous misunderstanding towards cancel. Cancel will open a new connection and send cancel request. Described in [here](https://postgrespro.com/docs/postgresql/12/protocol-flow#id-1.10.5.7.10:~:text=in%20the%20protocol.-,52.2.8.%C2%A0Canceling%20Requests%20in%20Progress,-During%20the%20processing).

> I think we can support cancel batch query. cc @BowenXiao1999

Yes, I was investigating. Maybe impl as a shutdown channel pattern.
