### ISSUE TITLE
frontend: support create index on source

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#2738]
Currently, create index is only expected to be done on tables. We may discuss how to extend it to other sources like Kafka. In this case, index can be also considered as a special kind of materialized view and materialized source.

**Comment by fuyufjh** [comment]
I think we should disable the index for non-materialized sources, otherwise the behavior looks weird and inconsistent.

**Comment by skyzh** [comment]
I would also +1 for forbidding it for now :)
