### ISSUE TITLE
Performance: prefetch data from S3

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#2860]
To improve performance and reduce cost (S3 charges money per GET request), it is time to think about a better prefetch strategy instead of only reading one block at a time from S3. 

For compactor, I think we can always prefetch the whole SST since we will read all its data anyway. #2630 has implemented simple prefetch for compaction.

For compute node, I think we need some heuristic to do the prefetch (e.g. size based with some exponential factors). Can the prefetch strategy adjust to the workload?

**Comment by fuyufjh** [comment]
For compute nodes, I think LRU is enough, and it may be hard to predict incoming data or user's query 🤔

**Comment by Little-Wallace** [comment]
We can not fetch the whole SST because it may hold the whole data of this compaction task in memory....

**Comment by Little-Wallace** [comment]
for big range queries,  it's hard for hummock to judge how much data we shall prefetch....
If the executor could know how large range it will read, it can pass prefetch flag to hummock and hummock could read this data

**Comment by lmatz** [comment]
Another form of prefetch:
if an SST/block named X that is going to be compacted has already been in the cache, then after compaction, the SST/blocks that overlap SST/block X can be used directly to replace X in the cache with some heuristics.

**Comment by hzxa21** [comment]
> Another form of prefetch: if an SST/block named X that is going to be compacted has already been in the cache, then after compaction, the SST/blocks that overlap SST/block X can be used directly to replace X in the cache with some heuristics.

Exactly. What I am thinking of is: after compaction, block cache (and disk-based secondary cache in the future) is refilled by some heuristics while the blocks of pre-compacted SSTs are still usable until the prefetch finish. In this way, we can reduce cache miss caused by compaction.

**Comment by hzxa21** [comment]
> We can not fetch the whole SST because it may hold the whole data of this compaction task in memory....

Yes, we should bound the working set of compactor to avoid OOM but try to prefetch as much as possible.

**Comment by Little-Wallace** [comment]
> Another form of prefetch: if an SST/block named X that is going to be compacted has already been in the cache, then after compaction, the SST/blocks that overlap SST/block X can be used directly to replace X in the cache with some heuristics.

we can refill this cache just after we pinned a new version.

**Comment by jon-chuang** [comment]
> If the executor could know how large range it will read, it can pass prefetch flag to hummock and hummock could read this data

There is actually count min sketch for this to do so space efficiently...

**Comment by skyzh** [comment]
If we can enable prefetch, we can set block size back to 64KB. Related PR: https://github.com/singularity-data/risingwave/pull/3463
