### ISSUE TITLE
storage: prioritize L0 flush I/O

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#2903]
Sometimes when we are writing to MinIO, the write throughput is constrained, and we should prioritize some operations. If compute nodes cannot flush tables to object store efficiently, barrier latency will be affected. Therefore, we should have some strategies to prioritize L0 flush I/O, by, for example:

* a separate prefix for L0 SSTs in object store
* limit compaction throughput based on some metrics
* ...

**Comment by Little-Wallace** [comment]
"based on some metrics` seems not accurately

**Comment by Little-Wallace** [comment]
The most difficult problem is how to limit the throughput for several compactor nodes....

**Comment by lmatz** [comment]
https://www.usenix.org/system/files/atc19-balmau.pdf 
Preempting higher-level compactions seems to be another option.
