### ISSUE TITLE
SetOp (e.g. union|intersect|except [all])

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#2911]
- [x] https://github.com/risingwavelabs/risingwave/issues/6392
- [x] Support INTERSECT https://github.com/risingwavelabs/risingwave/pull/9573
- [x] Support EXCEPT https://github.com/risingwavelabs/risingwave/pull/9666

**Comment by yinfredyue** [comment]
Just curious, by `SetOp`, are you referring to [this](https://doxygen.postgresql.org/structSetOp.html)?

**Comment by idx0-dev** [comment]
I'm working on the dbt adapter for RisingWave #7577. The EXCEPT operator, generated by dbt for testing the equality of two tables, is a requirement to pass the [adapter tests.](https://docs.getdbt.com/guides/dbt-ecosystem/adapter-development/4-testing-a-new-adapter#testing-your-adapter)

**Comment by fuyufjh** [comment]
`EXCEPT` is non-trivial but I guess the complexity is acceptable.

cc. @TennyZhuang @chenzl25

**Comment by chenzl25** [comment]
> `EXCEPT` is non-trivial but I guess the complexity is acceptable.
> 
> cc. @TennyZhuang @chenzl25

I think `except` can be implemented by a left anti join, while `intersect` can be implemented by a left semi join.

**Comment by chenzl25** [comment]
The `all` version of intersect and except is more complicated. We need to support a table function `replicate_row` and then use a rewrite rule to transform them to existing operators.

[https://github.com/apache/flink/blob/master/flink-table/flink-table-planner/src/ma[…]link/table/planner/plan/rules/logical/RewriteMinusAllRule.scala](https://github.com/apache/flink/blob/master/flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/logical/RewriteMinusAllRule.scala)

[https://github.com/apache/flink/blob/master/flink-table/flink-table-planner/src/ma[…]/table/planner/plan/rules/logical/RewriteIntersectAllRule.scala](https://github.com/apache/flink/blob/master/flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/logical/RewriteIntersectAllRule.scala)
