### ISSUE TITLE
Allow query on internal state table

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#2949]
We use a relational-table layer in both mview and internal state, and they share the same format, so it's easy enough to allow query on an internal table. It can be used only for debugging now.

We need a way to retrieve the table. Since it is used internally and can be changed later, I'd prefer to make it as simple as possible. A possible way is to add a new table function `__RW_TABLE(table_id)`.

A simple usage:

```sql
-- Get the count of entries in the internal state table.
SELECT count() FROM __RW_TABLE(2);
```

We can retrieve the table_id from the dashboard, or from the catalog later (cc @yezizp2012), and then inspect the state table.

To make it easier to use, we may need to create a meaningful name for every column in the state table, or support some new syntax to ref a column by index, but it will not block the issue.

**Comment by st1page** [comment]
although the state and mview have the same format in the storage, now all the "table catalog" of the state is inferred by the stream executor and meta just assigns the table id to the state but is not aware of the  table's chema and other information, storing it in catalog.
we should do the inference of the tableCatalog in frontend at first.

**Comment by fuyufjh** [comment]
See also the [Queryable State of Flink](https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/dev/datastream/fault-tolerance/queryable_state/).

**Comment by skyzh** [comment]
Flink Queryable State doesn't seem to maintain the same consistency level as we've done 😇

**Comment by st1page** [comment]
#
3053

**Comment by fuyufjh** [comment]
Any progress?

**Comment by skyzh** [comment]
We already support this in risectl, but not in SQL.

**Comment by fuyufjh** [comment]
How about support selecting data with SQL?  e.g. 

```sql
select * from __INTERNAL_tpch_q8_HashJoinRight_1034;
```

Alternative: as the issue description:

```sql
-- Get the count of entries in the internal state table.
SELECT count() FROM __RW_TABLE(2);
```

**Comment by BugenZhao** [comment]
Any updates on this? We already have the catalogs recorded in the meta store, while not syncing to the frontend. So we still can't query on internal state tables for now.

**Comment by yezizp2012** [comment]
IIUC, the internal tables have been synced to frontend after created in meta. So they're available and can be query now except syntax support. @cnissnzg  would you like to give it a try?

**Comment by cnissnzg** [comment]
> IIUC, internal tables have been synced to frontend after created in meta. So they're available and can be query now except syntax support. @cnissnzg would you like to give it a try?

Yes, I will try it.

**Comment by yezizp2012** [comment]
Since we will lower cast the input table name, the below SQL will report not found error.
```sql
dev=> select * from __INTERNAL_mv1_HashJoinLeft_1006;
ERROR:  QueryError: Catalog error: table or source not found: __internal_mv1_hashjoinleft_1006.
```

The following SQL works, but still got something wrong in compute node side:
```sql
dev=> select * from "__INTERNAL_mv1_HashJoinLeft_1006";
ERROR:  QueryError: internal error: error reading a body from connection: broken pipe.
```
Full panic message in CN:
```
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.remaining() >= dst.len()', /Users/august/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.2.0/src/buf/buf_impl.rs:253:9
stack backtrace:
2022-08-02T08:01:46.423874Z  WARN risingwave_batch::task::task_execution: Task receiver closed!
2022-08-02T08:01:46.423905Z  WARN risingwave_batch::task::task_execution: Task receiver closed!
2022-08-02T08:01:46.423996Z  WARN risingwave_batch::task::task_execution: Task receiver closed!
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:48:5
   3: bytes::buf::buf_impl::Buf::copy_to_slice
             at /Users/august/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.2.0/src/buf/buf_impl.rs:253:9
   4: bytes::buf::buf_impl::Buf::get_u64
             at /Users/august/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.2.0/src/buf/buf_impl.rs:494:9
   5: memcomparable::de::MaybeFlip<B>::get_u64
             at ./src/utils/memcomparable/src/de.rs:86:21
   6: <&mut memcomparable::de::Deserializer<B> as serde::de::Deserializer>::deserialize_i64
             at ./src/utils/memcomparable/src/de.rs:299:18
   7: serde::de::impls::<impl serde::de::Deserialize for i64>::deserialize
             at /Users/august/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.140/src/de/impls.rs:129:17
   8: risingwave_common::types::ScalarImpl::deserialize
             at ./src/common/src/types/mod.rs:773:38
   9: risingwave_common::types::deserialize_datum_from
             at ./src/common/src/types/mod.rs:418:22
  10: risingwave_common::util::ordered::serde::OrderedRowDeserializer::deserialize
             at ./src/common/src/util/ordered/serde.rs:144:25
  11: risingwave_storage::table::storage_table::DedupPkStorageTableIter<I>::into_stream::{{closure}}
             at ./src/storage/src/table/storage_table.rs:971:30
  12: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
```
