### ISSUE TITLE
Description of slow view query

### ISSUE THREAD

**Issue by wangdexinhp** [risingwavelabs/risingwave#2981]
**Describe the bug**
With the increase of inserted data, I found that the compute node has the problem of a sharp increase in memory, from 64G to 148G, is there any mechanism to control the memory growth.
As a result of the memory surge, queries become slow, For example, after 2600W data is inserted, it takes one and a half minutes for a view query with 4W data to return a result.

Below are the data fields for the view
![20220604-181808](https://user-images.githubusercontent.com/100552985/171995155-2154bf1e-30e2-461c-b177-48ac27a7b5ac.jpeg)

**To Reproduce**
Create a source, then create a materialized view, write the corresponding Kafka more than 20 million data, query the materialized view content, materialized view only more than 40 thousand data, check the response speed

**Expected behavior**
When the amount of data is too large, whether the amount of data in the memory is balanced with the amount of disks, and whether the persistent data memory is released in time.

**Additional context**
Maybe I'm not using it correctly, or maybe the database isn't perfect yet.Thank you very much

**Comment by skyzh** [comment]
>  I found that the compute node has the problem of a sharp increase in memory

Do you know when the sharp increate starts? e.g. when create materialize view, or when query the MV content?

**Comment by wangdexinhp** [comment]
> > 发现计算节点存在内存急剧增加的问题
> 
> 你知道尖锐的increate什么时候开始吗？例如，创建实体化视图时，或查询 MV 内容时？



> 

Increases as the amount of data increases, not just at query time.

**Comment by skyzh** [comment]
What's your configuration? Would you please paste your docker-compose file here?

**Comment by skyzh** [comment]
Also the full process of running this? e.g. what MV did you create, how's the source look like.

**Comment by wangdexinhp** [comment]
> 



> 你的配置是什么？你能把你的 docker-compose 文件贴在这儿吗？
docker-compose

**Comment by wangdexinhp** [comment]
> Also the full process of running this? e.g. what MV did you create, how's the source look like.

CREATE SOURCE IF NOT EXISTS source_py_gen (
   timestamp timestamp,
   host_id varchar,
   concentration_1 real,
   concentration_2 real,
   concentration_3 real,
   concentration_4 real,
   concentration_5 real,
   concentration_6 real,
)
WITH (
   'connector'='kafka', 
   'kafka.topic'='connector-distributed',
   'kafka.brokers'='broker:29092', 
   'kafka.scan.startup.mode'='earliest'  
)ROW FORMAT JSON;

**Comment by wangdexinhp** [comment]
Only when a view with max and min is created, the memory will explode, and the memory of other views is very stable？

**Comment by skyzh** [comment]
min / max's implementation is significantly different from other aggregators. I guess it is the root cause of your issue.

**Comment by skyzh** [comment]
Also, would you please upgrade to latest version? We've fixed some OOM issues yesterday.

**Comment by skyzh** [comment]
By the way, when are data ingested into Kafka? After all MVs created, or before MV creation?

**Comment by wangdexinhp** [comment]
> 顺便说一句，数据何时被摄入 Kafka？在创建所有 MV 之后，还是在创建 MV 之前？

After creating the view, write the kafka data

**Comment by xxchan** [comment]
I will close for now since it's been too long. Welcome to try again with the latest version of RisingWave and feel free to reopen if the problem persits. 😊
