### ISSUE TITLE
ci: reduce link parallelism

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#2994]
Recently we observed a lot of OOM during CI builds. So I propose the following way to build test artifacts:

* Firstly, use full CPU cores to build without test target
* Secondly, use half CPU cores' job concurrency to build test targets

Anyway, after some investigation, it seems that it's hard to modify cargo to limit link parallelism. So we should do manual tuning about link parallelism.

**Comment by xxchan** [comment]
Is this still a problem?

**Comment by skyzh** [comment]
Yes. We increased build EC2 to have 64GB memory.
