### ISSUE TITLE
streaming: eliminate usages of `RwError`

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#3116]
When we were refactoring the streaming executors with async-stream, we decided to also refactor the error type with the per-crate manner. For compatibility, we still capsulate some `RwError`s in the `StreamExecutorError`.

https://github.com/singularity-data/risingwave/blob/f2c5758789ddd22ba6edbfeb6d7f5279ac919f9c/src/stream/src/executor/error.rs#L35-L57

After #2366 was introduced, we can start to eliminate these usages now.

- [x] #3133
- [x] #3134
- [x] #3135
- [x] #3136

**Comment by skyzh** [comment]
Is this issue cleared? cc @BugenZhao

**Comment by BugenZhao** [comment]
> Is this issue cleared? cc @BugenZhao 

I'm not sure, as we still rely on it for executor builders & stream manager. 🤔
