### ISSUE TITLE
state_table: remove `pk_descs: &[OrderedColumnDesc]` from `iter_with_pk`

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#3203]
The ordered column data should already be passed when calling `CellBasedTable::new`, so there's no need to pass it again within `iter_with_pk`. It would be good if we can use existing data inside cell based table.

**Comment by skyzh** [comment]
cc @kwannoel do you have any ideas on this? Why did we introduce this parameter? 🤤

**Comment by kwannoel** [comment]
> cc @kwannoel do you have any ideas on this? Why did we introduce this parameter? :drooling_face:

I think currently only `Vec<ColumnDesc>` is passed. 
https://github.com/singularity-data/risingwave/blob/1b5fe561bc76ac073aa5d0db66d34acde2276364/src/storage/src/table/cell_based_table.rs#L87-L94

It is used to instantiate `OrderedRowDeserializer` in `DedupPkCellBasedTableRowIter`. `OrderedRowDeserializer` is used for deserializing pk vector into Row.

**Comment by skyzh** [comment]
`OrderedColumnDesc` should be inside `ordered_row_serializer`. We can modify the new function to let the upper layer to pass `OrderedColumnDesc` to us, and we can construct `ordered_row_serializer` by ourselves 🤣

**Comment by skyzh** [comment]
Also the function name `iter_with_pk` looks confusing. Maybe we should change it to `dedup_pk_iter()` instead?

**Comment by skyzh** [comment]
... because we now have `iter_with_pk_bounds`, `iter_with_pk_prefixes`. I believe the dedup-pk iterator's encoding / decoding scheme is completely different from the above two functions. So we'd better use `dedup_pk_iter` to avoid misusing.

**Comment by skyzh** [comment]
I've just done a big refactor, please base your changes on my PR 🤣

Also you may help separate DedupRowIterator to another file. I think `cell_based_table.rs` is already long enough 🤪

**Comment by kwannoel** [comment]
Will hold on this for now, and provide an update after https://github.com/singularity-data/risingwave/pull/3143#issuecomment-1154096261 is done.

**Comment by xxchan** [comment]
After this we can remove OrderedColumnDesc in common completely

**Comment by kwannoel** [comment]
> Will hold on this for now, and provide an update after #3143 (comment) is done.

Currently parameterizing StorageTableIter (previously CellBasedTableIter). After that is done DedupPkIter can be deprecrated, and this issue will be fixed too.

**Comment by kwannoel** [comment]
I think this can be closed. DedupPkCellBasedTableIter is removed. Currently state_table does not take in this any longer as well. Feel free to re-open if there is still existing issues.
