### ISSUE TITLE
streaming: auto create statistics MV

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#3231]
e.g. when user creates a materialize view, we also create

```
create materialized view _mv_stat as select count(*) from mv;
```

so that we can do some optimization based on this statistics

**Comment by skyzh** [comment]
Accelerate count(*), which looks like a common query? 🤪

**Comment by fuyufjh** [comment]
> Accelerate count(*), which looks like a common query? 🤪

Hmm, it didn't convince me.😇 If so, he can manually run `create materialized view _mv_stat as select count(*) from mv`.
