### ISSUE TITLE
test: fork sqllogictest binary runner to our own repo

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#3248]
In RisingWave, we might want to do something like trigger manual compaction. We might need to do some RPC inside sqllogictest (an alternative is to implement special SQL for such operations, but doesn't sound easy enough). In this case, we might need to modify sqllogictest binary runner.

We can have some special syntax for sqllogictest:

```
+operation do_manual_compaction
```

And our custom runner will read such operation lines, send RPC, etc.

**Comment by skyzh** [comment]
However, I don't think we have use cases convincing enough to introduce this feature. cc @hzxa21 may think about it 🤣

**Comment by skyzh** [comment]
But issuing such command will go through the whole executor layer, I think that would be too complex.

**Comment by liurenjie1024** [comment]
Why it can't be issued using sql, from example `trigger compaction`? I don't think we need to use batch executor for these, and we just need some special handler for these commands.

**Comment by skyzh** [comment]
> I don't think we need to use batch executor for these, and we just need some special handler for these commands.

Hmm, that sounds approachable!
