### ISSUE TITLE
streaming: memory-bound channel

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#3314]
Currently, our local channels are bound by number of chunks. This makes it hard to control the memory usage. We'd better implement a memory-bound channel and having a fixed amount of memory for each channel.

**Comment by lmatz** [comment]
One simple approach may be leveraging Tokio's semaphore and unbounded channel, i.e. `memory size` is the `number of permit`.

But on the second thought, I feel this memory-bound channel is more like a remedy. If people obey the memory-bound in all executors, then a number-bound channel also works
If people do crazy stuff in executors and do not obey the memory-bound, the channel helps but helps not much.
