### ISSUE TITLE
Support `pg_opclass`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#3431]
**Describe the bug**
> select opcname FROM pg_opclass:
> Catalog error: table or source not found: pg_opclass

**To Reproduce**

**Expected behavior**
The same as PG

**Additional context**
Try to make Sqlancer make. See #3364

**Comment by yezizp2012** [comment]
`pg_opclass` is a system table and not implemented yet. Besides, we don't support query on system table without specified `pg_catalog` schema name also. 😂

**Comment by lmatz** [comment]
> `pg_opclass` is a system table and not implemented yet. Besides, we don't support query on system table without specified `pg_catalog` schema name also. 😂 Ref: https://www.postgresql.org/docs/current/catalog-pg-opclass.html

Thanks for the info!  Running Sqlancer is not urgent and this issue can be addressed in the future. Right now, we focus on enhancing Sqlsmith.

**Comment by kwannoel** [comment]
Seems like couple more system tables needed:
- `pg_collation`
- `pg_operator`
- `pg_am`

See: https://github.com/sqlancer/sqlancer/blob/78506a83a4b77d2c9536980a4d3b4d47eb7e9317/src/sqlancer/postgres/PostgresGlobalState.java#L44-L94

**Comment by kwannoel** [comment]
Closing this first since it is already stubbed for sqlancer. We can reopen when planned again.
