### ISSUE TITLE
Use "order by id" to create a time window, and query by id returns wrong results.

### ISSUE THREAD

**Issue by databodys** [risingwavelabs/risingwave#3445]
I created a materialized view and created an index ad_id. There are about 2.5 million records in the materialized view. When I execute select * from ad_ctr_5min where ad_id=9; or any existing ad_id, I cannot find any matching records. When When I query select * from ad_ctr_5min where ad_id=0, all the records are queried, I think this is a very strange thing, do you have a similar experience? The following is my code to create the materialized view and related query statements:
1.
CREATE MATERIALIZED VIEW ad_ctr_5min AS
SELECT
    ac.ad_id AS ad_id,
    ac.clicks_count :: NUMERIC / ai.impressions_count AS ctr,
    ai.window_end AS window_end
FROM
    (
        SELECT
            ad_id,
            COUNT(*) AS impressions_count,
            window_end
        FROM
            TUMBLE(
                ad_impression,
                impression_timestamp,
                INTERVAL '1' MINUTE
            )
        GROUP BY
            ad_id,
            window_end
    ) AS ai
    JOIN (
        SELECT
            ai.ad_id,
            COUNT(*) AS clicks_count,
            ai.window_end AS window_end
        FROM
            TUMBLE(ad_click, click_timestamp, INTERVAL '1' MINUTE) AS ac
            INNER JOIN TUMBLE(
                ad_impression,
                impression_timestamp,
                INTERVAL '1' MINUTE
            ) AS ai ON ai.bid_id = ac.bid_id
            AND ai.window_end = ac.window_end
        GROUP BY
            ai.ad_id,
            ai.window_end
    ) AS ac ON ai.ad_id = ac.ad_id
    AND ai.window_end = ac.window_end order by ad_id;
2.
dev=> select * from ad_ctr_5min where ad_id=9;
 ad_id | ctr | window_end
-------+-----+------------
(0 rows)
3.
dev=> select * from ad_ctr_5min where ad_id=0;
 ad_id  |              ctr               |     window_end
--------+--------------------------------+---------------------
      1 |                           0.50 | 2022-06-22 12:58:00
      1 |                          0.375 | 2022-06-22 14:02:00
      1 |                           0.40 | 2022-06-22 17:51:00
      1 | 0.5384615384615384615384615385 | 2022-06-22 18:08:00
      1 |                           0.50 | 2022-06-22 18:11:00
      1 |                           0.80 | 2022-06-22 19:57:00
      1 |                          0.375 | 2022-06-22 20:13:00
      2 |                         0.4375 | 2022-06-22 14:44:00
      2 |                           0.50 | 2022-06-22 18:29:00
      2 |                           0.40 | 2022-06-22 20:25:00

**Comment by liurenjie1024** [comment]
I guess there is something wrong with encoding. I'll take a look at this.

**Comment by fuyufjh** [comment]
I just encountered a similar problem. Maybe related #3452

**Comment by liurenjie1024** [comment]
Can't reproduce, feel free to open it again if it still happens.
