### ISSUE TITLE
Indexing a field of a materialized view does not improve query performance.

### ISSUE THREAD

**Issue by databodys** [risingwavelabs/risingwave#3448]
Indexing a field of a materialized view does not improve query performance.
For example, I have two ad materialized views with 400,000 records respectively. One of the materialized views creates an index on ad_id, and the other does not. The query results are as follows:

```
dev=> DESCRIBE ad_ctr_5min;
    Name     |     Type
-------------+--------------
 ad_id       | Int64
 ctr         | Decimal
 window_end  | Timestamp
 ad_id_index | index(ad_id)
(4 rows)

EXEC: select * from  ad_ctr_5min where ad_id=1005
The first query cost:8.2s
The second query cost immediately: 1.3s

EXEC: explain select * from  ad_ctr_5min where ad_id=1005;
                               QUERY PLAN
-------------------------------------------------------------------------
 BatchExchange { order: [], dist: Single }
   BatchFilter { predicate: ($0 = 1005:Int32) }
     BatchScan { table: ad_ctr_5min, columns: [ad_id, ctr, window_end] }

dev=> DESCRIBE ad_ctr_5min_1;
    Name    |   Type
------------+-----------
 ad_id      | Int64
 ctr        | Decimal
 window_end | Timestamp
(3 rows)
EXEC: select * from  ad_ctr_5min_1 where ad_id=1005
The first query cost:8.3s
The second query cost immediately: 1.3s

EXEC: explain select * from  ad_ctr_5min_1 where ad_id=1005;
                               QUERY PLAN
-------------------------------------------------------------------------
 BatchExchange { order: [], dist: Single }
   BatchFilter { predicate: ($0 = 1005:Int32) }
     BatchScan { table: ad_ctr_5min_1, columns: [ad_id, ctr, window_end] }
```

**Comment by skyzh** [comment]
cc @xxchan @st1page looks like the condition is not pushed down. Any ideas?

**Comment by skyzh** [comment]
@databodys did you create index or create an order by MV?

**Comment by databodys** [comment]
@skyzh I create index by MV

**Comment by xxchan** [comment]
Does your MV have an order by clause? Could you share the CREATE statements?

**Comment by fuyufjh** [comment]
Please provide the `create table` statements as well as other DDLs to help to reproduce the problem

**Comment by databodys** [comment]
CREATE MATERIALIZED VIEW ad_ctr_5min_1 AS
SELECT
    ac.ad_id AS ad_id,
    ac.clicks_count :: NUMERIC / ai.impressions_count AS ctr,
    ai.window_end AS window_end
FROM
    (
        SELECT
            ad_id,
            COUNT(*) AS impressions_count,
            window_end
        FROM
            TUMBLE(
                ad_impression,
                impression_timestamp,
                INTERVAL '1' MINUTE
            )
        GROUP BY
            ad_id,
            window_end
    ) AS ai
    JOIN (
        SELECT
            ai.ad_id,
            COUNT(*) AS clicks_count,
            ai.window_end AS window_end
        FROM
            TUMBLE(ad_click, click_timestamp, INTERVAL '1' MINUTE) AS ac
            INNER JOIN TUMBLE(
                ad_impression,
                impression_timestamp,
                INTERVAL '1' MINUTE
            ) AS ai ON ai.bid_id = ac.bid_id
            AND ai.window_end = ac.window_end
        GROUP BY
            ai.ad_id,
            ai.window_end
    ) AS ac ON ai.ad_id = ac.ad_id
    AND ai.window_end = ac.window_end;

**Comment by databodys** [comment]
CREATE MATERIALIZED VIEW ad_ctr_5min AS
SELECT
    ac.ad_id AS ad_id,
    ac.clicks_count :: NUMERIC / ai.impressions_count AS ctr,
    ai.window_end AS window_end
FROM
    (
        SELECT
            ad_id,
            COUNT(*) AS impressions_count,
            window_end
        FROM
            TUMBLE(
                ad_impression,
                impression_timestamp,
                INTERVAL '1' MINUTE
            )
        GROUP BY
            ad_id,
            window_end
    ) AS ai
    JOIN (
        SELECT
            ai.ad_id,
            COUNT(*) AS clicks_count,
            ai.window_end AS window_end
        FROM
            TUMBLE(ad_click, click_timestamp, INTERVAL '1' MINUTE) AS ac
            INNER JOIN TUMBLE(
                ad_impression,
                impression_timestamp,
                INTERVAL '1' MINUTE
            ) AS ai ON ai.bid_id = ac.bid_id
            AND ai.window_end = ac.window_end
        GROUP BY
            ai.ad_id,
            ai.window_end
    ) AS ac ON ai.ad_id = ac.ad_id
    AND ai.window_end = ac.window_end;

**Comment by databodys** [comment]
CREATE INDEX ad_id_index ON ad_ctr_5min(ad_id);

**Comment by databodys** [comment]
CREATE SOURCE ad_impression (
    bid_id BIGINT,
    ad_id BIGINT,
    impression_timestamp TIMESTAMP
) WITH (
    'connector' = 'kafka',
    'kafka.topic' = 'ad_impression',
    'kafka.brokers' = '127.0.0.1:9092',
    'kafka.scan.startup.mode' = 'earliest'
) ROW FORMAT JSON;

CREATE SOURCE ad_click (
    bid_id BIGINT,
    click_timestamp TIMESTAMP
) WITH (
    'connector' = 'kafka',
    'kafka.topic' = 'ad_click',
    'kafka.brokers' = '127.0.0.1:9092',
    'kafka.scan.startup.mode' = 'earliest'
) ROW FORMAT JSON;

**Comment by fuyufjh** [comment]
Currently, indexes in RisingWave can only be used for delta join, other features of indexes such as speeding up point-select queries are under development. 

You may try to select from `ad_id_index` directly:

```
select * from ad_id_index where ad_id = ...
```

with the lastest version on `main` branch.

**Comment by lmatz** [comment]
> speeding up point-select queries are under development.

This issue should be solved now?
