### ISSUE TITLE
bug: panic when two sides of `EqJoinPredicate` have different types

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#3478]
**Describe the bug**
For `a = b`, we allow `a` and `b` to have different types, as long as they are castable to a more general type. This "cast" happens during evaluation of the `Equal` expression directly, without frontend binder inserting a cast expr.

However, this also makes **HashJoin** more complicated. It seems we have been assuming they are always the same type and may produce wrong result, runtime error, or even panic when they are not.

**To Reproduce**
```
-- batch: bigint works well
with a(a1) as (values (1)), b(b1) as (values (1::bigint)) select * from a, b where a1 = b1;
-- batch: decimal outputs wrong empty result
with a(a1) as (values (1)), b(b1) as (values (1::numeric)) select * from a, b where a1 = b1;
-- batch: smallint causes runtime error
with a(a1) as (values (1)), b(b1) as (values (1::numeric)) select * from a, b where a1 = b1;

-- streaming: panic
create table a(a1 int); create table b(b1 bigint); create table c(c1 smallint);
create materialized view big as select * from a, b where a1 = b1;
insert into a values (1);
```

**Expected behavior**
```
 a1 | b1 
----+----
  1 |  1
(1 row)
```

**Additional context**

* May also impact #3419. This is actually inspired by Question 2 in the issue.
* [PostgreSQL](https://github.com/postgres/postgres/blob/7201cd18627afc64850537806da7f22150d1a83b/src/include/catalog/pg_operator.dat#L20-L24) also allows direct cross-type comparison without cast exprs. And it is actually mixed style: sometimes it compares directly and sometimes it relies on implicit cast expr. In RW we always compare directly as of now.

Candidate solutions:
* HashJoin and DynamicFilter also implement direct cross-type comparison.
* Disallow direct cross-type comparison completely, and always insert implicit cast expr in frontend.
* Disallow direct cross-type equality inside `EqJoinPredicate`. Implicit cast expr should be inserted when creating `EqJoinPredicate`. However, `EqJoinPredicate` only accepts `InputRef` and it would need an extra `Project` to do the casting. Extending `EqJoinPredicate` to accept `ExprImpl` may also complicate other things.
* `EqJoinPredicate` (and `DynamicFilter`) carries the `DataType` that both sides should be casted to, and does the cast before using values. For example:
```diff
pub struct EqJoinPredicate {
    other_cond: Condition,

-   eq_keys: Vec<(InputRef, InputRef)>,
+   eq_keys: Vec<(InputRef, InputRef, DataType)>,

    left_cols_num: usize,
}
```

**Comment by xiangjinwu** [comment]
Seems also related: #3470

**Comment by liurenjie1024** [comment]
> EqJoinPredicate (and DynamicFilter) carries the DataType that both sides should be casted to, and does the cast before using values. 

This solution seems feasible to me for `HashJoin`, and we don't need to do much change.
