### ISSUE TITLE
streaming: two-phase TopN

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#3489]
Currently, our TopN is singleton. We already have some design RFCs on two-phase TopN, and we should finalize the RFC and decide the final way to implement this.

This issue will be updated later with implementation details.

- [x] Implement a singleton TopN that only uses one heap and no cache. @StrikeW 
- [x] Implement GlobalTopN
- [x] Implement LocalTopN based on existing TopN
- [ ] Support two-phase TopN on SQL frontend
- [x] https://github.com/singularity-data/risingwave/issues/4245
- [x] https://github.com/singularity-data/risingwave/issues/4246
- [x] https://github.com/singularity-data/risingwave/issues/4247
- [x] https://github.com/singularity-data/risingwave/issues/4248

**Comment by fuyufjh** [comment]
@Shmiwy Did you get started?

**Comment by Shmiwy** [comment]
Yes, I'm trying to break down tasks and write a proposal

**Comment by Shmiwy** [comment]
The next day or two

**Comment by fuyufjh** [comment]
FYI.  @StrikeW is going to refactor TopN's state into one table.

**Comment by skyzh** [comment]
I think we'd better implement a new TopN executor for 2-phase. The original 3-heap executor looks hard to maintain, and can be used only in singleton mode.

**Comment by xxchan** [comment]
Finished?

**Comment by skyzh** [comment]
Thanks for @shmiwy 's great work!
