### ISSUE TITLE
Track: Evaluation of impure functions

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#3552]
Opening an issue to track various special functions we have encountered so far. No proposals yet.

* Common
  * #2870
  * `random` ([pg](https://www.postgresql.org/docs/current/functions-math.html#FUNCTIONS-MATH-RANDOM-TABLE))
* Depends on session config:
  * cast `timestamp` to `timestamp with time zone` ([`TimeZone`](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-TIMEZONE) #5826)
  * cast `date` to string ([`DateStyle`](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-DATESTYLE) #3253)
  * cast `float` to string ([`extra_float_digits`](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-EXTRA-FLOAT-DIGITS) #3406)
* Depends on `pg_catalog` and used by psql `\d` ([pg](https://www.postgresql.org/docs/current/functions-info.html) https://github.com/singularity-data/risingwave/issues/2954#issuecomment-1144381985):
  * `pg_get_userbyid`
  * `pg_table_is_visible `
* `pg_sleep`: We already decided to remove it #2576

(Note that expression evaluation does not include aggregates and table functions.)

[PostgreSQL](https://www.postgresql.org/docs/current/xfunc-volatility.html) classifies functions into 3 categories: immutable, stable and volatile.

**Comment by fuyufjh** [comment]
+1. Perhaps we need a `context` when `eval`

**Comment by xxchan** [comment]
To summarize, I think we handle impure functions in these ways:
- common: materialization https://github.com/risingwavelabs/rfcs/pull/24
- session config related: some configs simply ignored. General mechanism is rewrite expr to deterministic in optimizer. e.g., `SessionTimezone`.
- systable related: generally hacked in frontend.

So we can close the issue now?
