### ISSUE TITLE
Broken query session consistency

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#3559]
## Bug description
Consider the following sql statements executed in the same session:
```sql
insert into t1 values (1), (2), (3);

flush;

# The newly inserted values (1), (2), (3) may not be returned in the following query.
select * from t1;
```

The [current mechanism](https://github.com/singularity-data/risingwave/blob/main/src/frontend/src/scheduler/hummock_snapshot_manager.rs) of determining the read epoch of a batch query in frontend may not guarantee read after write (with flush) in one session:
1. Meta notifies frontend nodes on max committed epoch bumps via **async** notification.
2. Frontend marks the latest pinned epoch as outdated on receiving the notification.
3. Frontend uses the latest pinned epoch (a new epoch is pinned if the previous one is marked outdated) as the read epoch for the batch query.
4. Successful flush **will not synchronously update the pinned epoch** in frontend. 

Due to 1) and 4), even though a flush is invoked, it is still possible for frontend to assign the read statement after flush an epoch smaller than flush epoch.

I suspect this may be one of the causes to the parallel e2e test failure but it is not verified. In theory, this can also cause single-threaded e2e to fail.

## Potential Fix
- Include the committed epoch of a flush statement in FlushResponse sent from meta node to frontend node.
- Before claiming success on the flush statement, frontend updates the latest pinned epoch if the flush epoch is larger 
- (optional) Adopt the push based mechanism for pinning the epoch/snapshot. This can avoid the explicit pin_snapshot rpc in fronetend to make epoch/snapshot more lightweight and thus make the above fixes more efficient. (https://github.com/singularity-data/risingwave/issues/3551#issuecomment-1169708977)

**Comment by BowenXiao1999** [comment]
When doing the pin refactor, we also found the push based is more easy to ensure epoch freshness. (Because pull based is hard to determine the timer strategy). 

We can also provide two modes. One ensures strickly consistency,  pin_snapshot for each query (This can be used as correctness test we needs data completely correct). This will not affect the bench performance too much, becasue we can distinguish the pin_snapshot and actual execution in different metrics level.

And the other do not guarantee strong read-after-write (Though it is very possible to read the data if we switched to push based, if user wait for more than 1/2 RTT between meta and frontend). Second case can be used for most scenarios I think.

**Comment by liurenjie1024** [comment]
> Before claiming success on the flush statement, frontend updates the latest pinned epoch if the flush epoch is larger

To fix the broken consistency issue, I would vote for this.

> (optional) Adopt the push based mechanism for pinning the epoch/snapshot. This can avoid the explicit pin_snapshot rpc in fronetend to make epoch/snapshot more lightweight and thus make the above fixes more efficient. (https://github.com/singularity-data/risingwave/issues/3551#issuecomment-1169708977)(optional) Adopt the push based mechanism for pinning the epoch/snapshot. This can avoid the explicit pin_snapshot rpc in fronetend to make epoch/snapshot more lightweight and thus make the above fixes more efficient. (https://github.com/singularity-data/risingwave/issues/3551#issuecomment-1169708977)

+1 for push based pin epoch, but I don't see how it resolves this broken consistency.

**Comment by BowenXiao1999** [comment]
> +1 for push based pin epoch, but I don't see how it resolves this broken consistency

Push-based can not completely solve the broken consistency, but it improve epoch freshness for fe. Because if we are using pull based, it's hard to determine the timer strategy to do the get epoch RPC.

**Comment by liurenjie1024** [comment]
So to we will apply a fix to flush command to resolve this broken consistency?

**Comment by BowenXiao1999** [comment]
Yes this LGTM.

**Comment by xxhZs** [comment]
I think this issue maybe cause to the parallel e2e test failure after https://github.com/singularity-data/risingwave/pull/3602

**Comment by ZENOTME** [comment]
> Due to 1) and 4), even though a flush is invoked, it is still possible for frontend to assign the read statement after flush an epoch smaller than flush epoch.

I am confused about this. 
```
insert into t1 values (1), (2), (3);           -> get epoch_A = get last_epoch

flush;

# The newly inserted values (1), (2), (3) may not be returned in the following query.
select * from t1;                                   -> get epoch_B = get last_epoch
```
assume that 
> Successful flush will not synchronously update the pinned epoch in frontend.

In this case, shouldn't epoch_A be equal to epoch_B？
for example:
```
  insert into t1 values (1), (2), (3);           -> get epoch_A = 3(last_epoch)
  flush -> no updated (so last_epoch isn't change)
  select * from t1;                                   -> get epoch_B = 3(last_epoch)
```
Because we get the epoch from the same frontend, so I think the epoch_B impossible smaller than epoch_A, it only can be equal to or greater than epoch_A.

So I think this bug caused by the case: epoch_B = epoch_A, so select can't read the result from insert. Is that right?

**Comment by hzxa21** [comment]
I am not sure what epoch_A is in your example.

INSERT is guarateed to be visible on epoch >= FLUSH epoch (i.e. the epoch when the FLUSH statement is completed). We don't have any visibility guarantee on epoch < FLUSH epoch. The problem is we don't make sure epoch_B in your example >= FLUSH epoch.

**Comment by BowenXiao1999** [comment]
I think his question is:

If the INSERT is tagged with epoch 3, then flush happend, the new insert data will be flushed. Then SELECT with epoch 3 why can not see the data, even if epoch 3 may < flush epoch.

**Comment by hzxa21** [comment]
> I think his question is:
> 
> If the INSERT is tagged with epoch 3, then flush happend, the new insert data will be flushed. Then SELECT with epoch 3 why can not see the data, even if epoch 3 may < flush epoch, but in theory epoch = 3 has been flushed to shared storage.

The epoch for writes is not tagged by frontend and epoch maintained in HummockSnapshotManager is only used for reads. For INSERT, frontend schedules InsertExecutor to insert data into the table source executor and the write epoch is determined by the barrier the table source executor received. Therefore, it is possible the epoch of the SELECT query epoch < the write epoch of the data since the SELECT query epoch is retrieved from the frontend cache.
