### ISSUE TITLE
Availability:  frontend and compute-node need to find new meta-node after the origin meta-node crash

### ISSUE THREAD

**Issue by Little-Wallace** [risingwavelabs/risingwave#3565]
### Background

The whole cluster of RisingWave need to heartbeat to meta-node and get some info from it. If meta-node crashed and started in a new physical node, the whole cluster will be out of service because they do not know the new address of meta-node.

### Solution

- every client of compute-node/compactor-node and frontend-node need to request the address of new meta-node from meta-storage (it may be ETCD or other database). It means that every node in RisingWave shall store the address info of ETCD in their launch parameters.

**Additional context**
- This issue seems to make our availability design more complex.

**Comment by BowenXiao1999** [comment]
I think the detail procedure to handle is (correct if wrong):
If frontend fails the heartbeat to meta, then we check ETCD whether there is a new meta.
1) if there is a new meta. Try heartbeat again. if the heartbeat also fails, then frontend's network is bad, frontend should kill itself.
2) if there is no new meta. The frontend's network is bad, frontend should kill itself.

**Comment by skyzh** [comment]
> If frontend fails the heartbeat to meta, then we check ETCD whether there is a new meta.

So now frontend will need to know all etcd nodes?

**Comment by yezizp2012** [comment]
I think in the case of k8s environment deployment, we will bind a domain name to Meta service, which will be used by other components. When meta-node crashed, a new node will be started and it will try to renew the lease and start serving. The work of domain name resolution will be handle by k8s, so other components don't have to know and connect to all etcd nodes.
