### ISSUE TITLE
RFC: keep track of SST order in meta node for supporting spill to S3

### ISSUE THREAD

**Issue by wenym1** [risingwavelabs/risingwave#3617]
# RFC keep track of SST order in meta node

## Background

In #2919 we have supported write any time and spill to disk. The order of spilled SSTs is tracked locally in the CN. Since remotely we haven't supported tracking the SST order, when we finish an epoch, we have to compact the spilled SSTs locally into key non-overlapped SSTs and then upload to S3 and commit to meta node, which increases the overall latency. 

If we are able to track the SST order in meta node, we don't have to compact the spilled SSTs and instead we only need to upload the SSTs directly to S3 and attach the order information of SSTs when we commit an epoch.

## Design

Currently, our `Level` definition is as followed:
```
message Level {
  uint32 level_idx = 1;
  LevelType level_type = 2;
  repeated SstableInfo table_infos = 3;
  uint64 total_file_size = 4;
}
```
where `LevelType` can either be `NONOVERLAPPING` and `OVERLAPPING`. Since we only need to keep track of SST order in L0, which is the only overlapping level in our current system, I will suggest separating the definition of non-overlapping and overlapping. For non-overlapping level, the definition remains the same.
```
message NonOverlappingLevel {
  uint32 level_idx = 1;
  repeated SstableInfo table_infos = 2;
  uint64 total_file_size = 3;
}
```
And for overlapping level, which is only L0 in our system, will have the following definition
```
message OverlappingLevel {
  message OrderedSstables {
    repeated Sstable ordered_table_infos = 1;
  }
  uint32 level_idx = 1;
  repeated OrderedSstables table_infos = 2;
  uint64 total_file_size = 3;
}
```

`OrderedSstables` is a list of SSTs with order dependency. In our system, the SSTs in the same `OrderedSstables` are generated within the same epoch from the same CN. Since SSTs generated from different epochs and different will not have overlapped full keys, they are order independent.

**Comment by wenym1** [comment]
Currently before we commit an epoch, we will have to compact all previous spilled SSTs because the spilled SSTs have order dependency while we are not able to keep track of the SST meta. 

If we can keep track of the SSTs order, we can upload the spilled SST files to S3, or even we can spill to S3 directly. When we commit an epoch, we don't have to compact the spilled SST again, and instead we only need to inform the meta about the SST id an order, which will reduce the commit latency. In this way, the previously uncommitted SSTs can be converted to committed SSTs directly.

**Comment by wenym1** [comment]
> Ok, I get your point. So would level_idx of all OverlappingLevel be zero?

I think we can assume that level_idx will all be zero for `OverlappingLevel`. We can do it even more aggressively, like removing the level_idx field in OverlappingLevel, and in HummockVersion, we have a separated field `OverlappingLevel L0 = 2`, and the other levels are `repeated OverlappingLevel levels = 1;`

**Comment by Little-Wallace** [comment]
I want to know what does `OrderedSstables ` look like so that we must split it to a single kind of structure.
