### ISSUE TITLE
feat(frontend): explain verbose

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#3621]
the PostgreSQL supports `explain verbose` which will give more information about the plan.

> Display additional information regarding the plan. Specifically, include the output column list for each node in the plan tree, schema-qualify table and function names, always label variables in expressions with their range table alias, and always print the name of each trigger for which statistics are displayed. The query identifier will also be displayed if one has been computed, see [compute_query_id](https://www.postgresql.org/docs/current/runtime-config-statistics.html#GUC-COMPUTE-QUERY-ID) for more details. This parameter defaults to FALSE.

 And in our system, especially for streaming operator, we can give more information about the stateTable.

**Comment by st1page** [comment]
> dev=# explain select max(v2) as max_v2, min(v3), v3 from test,test2 where v3>v6 and v1=v3 group by v3;
>                                QUERY PLAN                               
> ------------------------------------------------------------------------
>  HashAggregate  (cost=100.76..100.80 rows=4 width=96)
>    Group Key: test.v3
>    ->  Nested Loop  (cost=0.00..92.26 rows=1133 width=64)
>          Join Filter: (test.v3 > test2.v6)
>          ->  Seq Scan on test2  (cost=0.00..18.50 rows=850 width=32)
>          ->  Materialize  (cost=0.00..22.77 rows=4 width=64)
>                ->  Seq Scan on test  (cost=0.00..22.75 rows=4 width=64)
>                      Filter: ((v1)::numeric = v3)
> (8 rows)
> 
> dev=# explain verbose select max(v2) as max_v2, min(v3), v3 from test,test2 where v3>v6 and v1=v3 group by v3;
>                                   QUERY PLAN                                   
> -------------------------------------------------------------------------------
>  HashAggregate  (cost=100.76..100.80 rows=4 width=96)
>    Output: max(test.v2), min(test.v3), test.v3
>    Group Key: test.v3
>    ->  Nested Loop  (cost=0.00..92.26 rows=1133 width=64)
>          Output: test.v3, test.v2
>          Join Filter: (test.v3 > test2.v6)
>          ->  Seq Scan on public.test2  (cost=0.00..18.50 rows=850 width=32)
>                Output: test2.v4, test2.v5, test2.v6
>          ->  Materialize  (cost=0.00..22.77 rows=4 width=64)
>                Output: test.v2, test.v3
>                ->  Seq Scan on public.test  (cost=0.00..22.75 rows=4 width=64)
>                      Output: test.v2, test.v3
>                      Filter: ((test.v1)::numeric = test.v3)
> (13 rows)

**Comment by TennyZhuang** [comment]
explain vvv

**Comment by fuyufjh** [comment]
How about hide distribution keys, PKs, output_index, etc. in plain explain and show these info in this `explain verbose`?

**Comment by st1page** [comment]
> How about hide distribution keys, PKs, output_index, etc. in plain explain and show these info in this `explain verbose`?

we can print them as a part in the internal table catalogs.

**Comment by fuyufjh** [comment]
(except output_index)

**Comment by st1page** [comment]
> (except output_index)

I think it will give all the field name of the output columns of the plannode, so the output_index might be different?

**Comment by st1page** [comment]
https://github.com/singularity-data/risingwave/issues/3690

**Comment by BugenZhao** [comment]
Can we have the distribution key & distribution type in verbose explain? 🥰

**Comment by fuyufjh** [comment]
> Can we have the distribution key & distribution type in verbose explain? 🥰

It can be described in the `Exchange` operators.

**Comment by fuyufjh** [comment]
> > How about hide distribution keys, PKs, output_index, etc. in plain explain and show these info in this `explain verbose`?
> 
> we can print them as a part in the internal table catalogs.

This seems infeasible because when you do `explain`, the materialized view has not been created yet, so does these internal tables 😇

**Comment by st1page** [comment]
> > Can we have the distribution key & distribution type in verbose explain? smiling_face_with_three_hearts
> 
> It can be described in the `Exchange` operators.

further more, I think we should print the leaf plan nodes' distribution such as `BatchScan` and `StreamScan` in explain(even in normal explain)

**Comment by fuyufjh** [comment]
Hi, to summarize the above discussion, for `explain verbose`,

1. We want to show some detailed info about the plan node, including stream_key (aka. PK of output) and output columns, and some operator-specific information (if have)
2. We want to show some info about the internal state, including the columns, primary keys and distribution keys.

Here is an example proposed by me. Please comment if have any suggestions. 

```
psql> explain verbose ...

StreamMaterialize { columns: [o_orderkey, count(hidden), distinct_customers], pk_columns: [o_orderkey] }
  StreamHashAgg { group_key: [orders.o_orderkey], aggs: [count, count(orders.o_custkey) filter((flag = 0:Int64))], stream_key: [orders.o_orderkey], output: [orders.o_orderkey, count, distinct_customers] }
    StreamExchange { dist: [orders.o_orderkey] }
      StreamHashAgg { group_key: [orders.o_orderkey, orders.o_custkey, flag], aggs: [count], stream_key: [orders.o_orderkey, orders.o_custkey, flag], output: [orders.o_orderkey, orders.o_custkey, flag, count]}
        StreamExchange { dist: [orders.o_orderkey, orders.o_custkey, flag] }
          StreamExpand { column_subsets: [[orders.o_orderkey, orders.o_custkey]], stream_key: [orders.o_orderkey, orders.o_custkey], output: [orders.o_orderkey, orders.o_custkey] }
            StreamTableScan { table: orders, columns: [orders.o_orderkey, orders.o_custkey, orders._row_id], pk_indices: [2], key: [orders.o_orderkey], output: [] }

State #1 (StreamMaterialize):
  columns: [ o_orderkey, count, distinct_customers ]
  key: [ o_orderkey ]
  dist_key: [ o_orderkey ]

State #2 (StreamHashAgg):
  columns: [ o_orderkey, count, distinct_customers ]
  key: [ o_orderkey ]
  dist_key: [ o_orderkey ]

...(more state info)...
```
