### ISSUE TITLE
Meta node crashed when trying to create index on materialized view

### ISSUE THREAD

**Issue by sfu2** [risingwavelabs/risingwave#3666]
**Describe the bug**
Meta node crashed when trying to create index on materialized view with following sql:
```sql
dev=> create index last_idx on last(uid);
ERROR:  RPC error: GrpcStatus(Status { code: Unknown, message: "transport error", source: Some(tonic::transport::Error(Transport, hyper::Error(Io, Kind(ConnectionReset)))) })
```

**To Reproduce**
I'm using docker-compose with similiar configuration within [docker/docker-compose.yml](https://github.com/singularity-data/risingwave/blob/28904c2a4f55118d7e0ecc2d758a178555bd1acc/docker/docker-compose.yml), except that I'm using zookeeper and kafka rather than redpanda.

In psql, execute
```sql
create source tests(
  id int,
  uid int,
  util int,
  created_at timestamp
) with (
  'connector'='kafka',
  'kafka.topic'='test',
  'kafka.brokers'='kafka:9092'
) row format json;

create materialized view last as select * from tests order by id desc limit 100000;

select * from last limit 5;
```
All those query works fine, but when I execute
```sql
create index last_idx on last(uid);
```
It ends up with the above error, and meta node crashed with following log message:
```
thread 'tokio-runtime-worker' panicked at 'no entry found for key', src/meta/src/stream/stream_manager.rs:168:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**
Creating an index on `uid` field of materialized view `last`.

**Additional context**
In my schema, `id` represents a global unique identifier, `uid` is a int within [1, 128], `util` is also a int within [1, 512], `created_at` is a timestamp.

**Comment by skyzh** [comment]
Thanks for reporting the issue! Index is not a documented feature, and there are several refactors undergoing that may impact its functionality. We will fix this soon.

**Comment by xxchan** [comment]
It should have been fixed. Welcome to retry RisingWave and report if there are any other issues.
