### ISSUE TITLE
(Tracking):support JDBC client

### ISSUE THREAD

**Issue by ZENOTME** [risingwavelabs/risingwave#3675]
as title
- [ ] BEGIN  statement
- [ ] COMMIT statement
- [ ] ROLLBACK statement

**Comment by ZENOTME** [comment]
BEGIN statement tracking in #2541

**Comment by BowenXiao1999** [comment]
We already support this? 🤔

**Comment by ZENOTME** [comment]
We don't support these statement and just ignore these statement. 
I test simple query in JDBC and it works.

**Comment by ZENOTME** [comment]
I think we can close this issue because we have already can run query in JDBC.
