### ISSUE TITLE
compaction: task progress monitoring

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#3677]
**Is your feature request related to a problem? Please describe.**
Currently we won't cancel an assigned compaction task unless the compactor is removed from the cluster. It is possible a compactor is alive but the task has failed somehow (for example compactor has restarted). It can cause a task stuck.

**Describe the solution you'd like**
As mentioned in https://github.com/singularity-data/risingwave/blob/a75258e087d4e1fc0e35ac4d664fde9d7ca5430c/src/meta/src/hummock/compaction_scheduler.rs#L173
- Compactor reports progress of task
- Meta cancels potential stuck compaction task

**Describe alternatives you've considered**
With compactor spot instance, the compaction task scheduling strategy may undergo some changes too.

**Additional context**

**Comment by Li0k** [comment]
I think we need some refactor for `assign_compaction_task` and `send_task` (with some error handle to cancels potential stuck compaction task)

**Comment by zwang28** [comment]
> I think we need some refactor for `assign_compaction_task` and `send_task` (with some error handle to cancels potential stuck compaction task)

Yes it is one thing should be done here too.

**Comment by Li0k** [comment]
I am interested in this issue, and i will try to make a simple refactor about
- cancle task
- compactor retry
- report progress

**Comment by jon-chuang** [comment]
Hi @Li0k are you working on this? If not, I'd like to try to add the heartbeat logic. 

Should the heartbeat report the compaction task progress by looking and percentage of task completed in terms of 1. fraction of splits processed 2. simply report task status (running, completed)?

**Comment by jon-chuang** [comment]
Btw, could we not have compactor retry and just do a new `assign_compactor_task`?

**Comment by zwang28** [comment]
> Should the heartbeat report the compaction task progress by looking and percentage of task completed in terms of 1. fraction of splits processed 2. simply report task status (running, completed)?

I've considered "3. number of KV pairs a task has written", in case a splits may also take long time to finish.

**Comment by zwang28** [comment]
> Btw, could we not have compactor retry and just do a new `assign_compactor_task`?

+1 for not retry. Just assign the task to another compactor.
