### ISSUE TITLE
feat(fe): StreamFragmenterV2

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#3684]
now in our frontend, we have a stream `StreamFragmenter` which inputs a plan prost tree and then generates and outputs fragments prost. there is a visitor pattern when the planNode converts to prost tree. so it can not accept a DAG plan constructed with planNode.

we need a new StreamFragmenterV2 on frontend convert the plan node DAG/Tree to prost fragments directly. and there are some rewriting in the StreamFragmenter, which depend on rewrite on the prost tree. we can maintain it now and implement the v2.

@ice1000's plan:

+ [x] Removed struct `StreamFragmenter` (#5064)
+ [x] Assign `table_id` in `to_prost_body` methods (#5086)
+ [ ] Generate graphs in `to_prost_body` methods

**Comment by xxchan** [comment]
> Are we going to have two different prost trees?

Why are there 2 prost trees? We just need to remove an intermediate phase 🤔 (It exists because previously stream fragmenter is not in frontend) 

old: plan node dag -> prost node tree -> prost fragments dag
new: plan node dag -> prost fragments dag

**Comment by xxchan** [comment]
BTW, is currently plan node tree or DAG? 😇 @st1page https://github.com/singularity-data/risingwave/issues/2312

**Comment by skyzh** [comment]
It is still a tree. DAG can be represented with the current plan node definition, but I don't know whether there could be problems with that.

**Comment by ice1000** [comment]
The prost tree is still used in the test `TestCase::apply_query`, what to do with it?

**Comment by st1page** [comment]
> BTW, is currently plan node tree or DAG? 😇 @st1page #2312

It is a tree now. And generating a DAG plan is meaningless and expensive until we solve this issue.

**Comment by st1page** [comment]
> The prost tree is still used in the test `TestCase::apply_query`, what to do with it?

I think we can remove it. Instead, maybe we can use the prost fragments for test directly?

**Comment by st1page** [comment]
closed by https://github.com/risingwavelabs/risingwave/pull/6956
