### ISSUE TITLE
bug: comparison between struct/list has weak frontend check and may panic

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#3692]
**Describe the bug**
Refer to the test cases in reproduction steps below. They are all invalid in PostgreSQL, but passes our frontend type check, and may give incorrect result or panic during backend evaluation.

**To Reproduce**
```
select array[1] < row(1);
select array[1] < array[true];
select row(1) < row(true);
select row(1) < row(1, 1);
```

**Expected behavior**
Same as PostgreSQL **to a reasonable extent**.  It is not necessary to follow its premature support of multi-dimention array:
```
select array[array[1]] < array[2];
```
> The current implementation does not enforce the declared number of dimensions

> Arrays of a particular element type are all considered to be of the same type, regardless of size or number of dimensions.

via https://www.postgresql.org/docs/current/arrays.html

**Additional context**

Current implementation: #2796

Before implementation, it is better to clearly define the expected behavior, validate against PostgreSQL, and justify when diverging from it.

(Labeling as "difficulty/simple" but not "good first issue", as this requires mostly **PostgreSQL doc reading** without understanding of other parts of RisingWave. But it is not a quick one to get started.)

**Comment by skyzh** [comment]
Feel free to take over if this is urgent -- otherwise I expect to do this within the next release.

**Comment by skyzh** [comment]
```
select array[1] < row(1);
select array[1] < array[true];
```

are already banned in frontend.

```
select row(1) < row(true);
select row(1) < row(1, 1);
```

needs to be fixed on the frontend side. Looking into it...
