### ISSUE TITLE
Dedup `order_key` columns in state table

### ISSUE THREAD

**Issue by yuhao-su** [risingwavelabs/risingwave#3708]
Currently, our order_key indices in the state table may contain duplicated columns. For example, hash join uses join_key+input_pk as its table order key, but they may contain duplicated columns.

**Comment by BowenXiao1999** [comment]
You mean input_pk may already contains join_key? Or vice versa

**Comment by jon-chuang** [comment]
We should probably dedup in both frontend (tablecatalog) and statetable to be more robust.

**Comment by wcy-fdu** [comment]
completed
