### ISSUE TITLE
frontend: Explain for distributed query plan.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#3710]
**Is your feature request related to a problem? Please describe.**
Currently the explain result misses a lot of stuff, for example in our query engine, we want to know the parallism of each fragment, the plan of each fragment.

**Describe the solution you'd like**
Add `dist` option for explain, in which mode we generate fragments information for distributed query plan, including parallelism, dependencies, use can see trinodb as an example.

For example, when we execute `explain dist select * from t1, t2 on t1.a = t2.b`, we should call fragmenter to generate query graph, and generate a json(or sth else) according to this query graph to user. Then user can past it in our dashboard page to see visualization of the query graph.

This query graph contains serveral stuff:
1. Dependencies of stages.
2. Parallism of each stage.
3. Physical plan of each stage.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by chenzl25** [comment]
> @liurenjie1024 , could I ask why this was closed? It seems like we currently support `explain (distsql)` and it is even included in a planner test? Here are the PRs: #5048 #5295
> 
> Could you check if it satisfied the intended requirements, or are missing any features, and if the former, should we mark it as closed (completed)?
> 
> @st1page @chenzl25 it seems that `explain (distsql)` on batch will give json format, but stream will give a tree format. Is this good enough/stable so that we can include the `explain (distsql)` type in the docs?
> 
> Further, should it be `explain (dist)` or `explain (distsql)`?

I remember `distsql` is from cockroach db https://www.cockroachlabs.com/docs/stable/explain.html#distsql-option . A human-friendly format needs to be introduced instead of the JSON format.

**Comment by st1page** [comment]
according to https://singularity-data.quip.com/fek1AUiMz5lz/RFC-Option-based-Explain-Syntax, the `TYPE` and `FORMAT` should be independent options. But now we only have format JSON for the `distsql`. If one day we add a "TRADITIONAL" or "TREE" `TYPE`, we should distingush them.

**Comment by jon-chuang** [comment]
Ok, updated the tracking issue. Let's leave it as a TODO and ignore the distinction for now.

**Comment by fuyufjh** [comment]
> according to https://singularity-data.quip.com/fek1AUiMz5lz/RFC-Option-based-Explain-Syntax, the `TYPE` and `FORMAT` should be independent options. But now we only have format JSON for the `distsql`. If one day we add a "TRADITIONAL" or "TREE" `TYPE`, we should distingush them.

Actually we only have a TREE output for `explain distsql` now:

<details>

```
dev=> explain (type distsql) CREATE MATERIALIZED VIEW nexmark_q14 AS
SELECT
  auction,
  bidder,
  0.908 * price as price,
  CASE
    WHEN
      extract(hour from date_time) >= 8 AND
      extract(hour from date_time) <= 18
    THEN 'dayTime'
    WHEN
      extract(hour from date_time) <= 6 OR
      extract(hour from date_time) >= 20
    THEN 'nightTime'
    ELSE 'otherTime'
  END AS bidTimeType,
  date_time
FROM bid
WHERE 0.908 * price > 1000000 AND 0.908 * price < 50000000;
                                                                                                                                                                                                                              QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Fragment 0
   StreamMaterialize { columns: [auction, bidder, price, bidtimetype, date_time, _row_id(hidden)], pk_columns: [_row_id] }
       materialized table: 4294967294
     StreamExchange Hash([5]) from 1

 Fragment 1
   StreamProject { exprs: [Field(bid, 0:Int32), Field(bid, 1:Int32), (0.908:Decimal * Field(bid, 2:Int32)), Case(((Extract('HOUR':Varchar, Field(bid, 5:Int32)) >= 8:Int32) AND (Extract('HOUR':Varchar, Field(bid, 5:Int32)) <= 18:Int32)), 'dayTime':Varchar, ((Extract('HOUR':Varchar, Field(bid, 5:Int32)) <= 6:Int32) OR (Extract('HOUR':Varchar, Field(bid, 5:Int32)) >= 20:Int32)), 'nightTime':Varchar, 'otherTime':Varchar), Field(bid, 5:Int32), _row_id] }
     StreamFilter { predicate: ((0.908:Decimal * Field(bid, 2:Int32)) > 1000000:Int32) AND ((0.908:Decimal * Field(bid, 2:Int32)) < 50000000:Int32) AND (event_type = 2:Int32) }
       StreamRowIdGen { row_id_index: 4 }
         StreamSource { source: "nexmark", columns: ["event_type", "person", "auction", "bid", "_row_id"] }
             source state table: 0

  Table 0 { columns: [partition_id, offset], primary key: [$0 ASC], value indices: [0, 1], distribution key: [] }
  Table 4294967294 { columns: [auction, bidder, price, bidtimetype, date_time, _row_id], primary key: [$5 ASC], value indices: [0, 1, 2, 3, 4, 5], distribution key: [5] }
(14 rows)
```

</details>


As a result, the dashboard page `http://localhost:3000/explain_distsql/` is useless.

**Comment by st1page** [comment]
> Actually we only have a TREE output for explain distsql now:

Err.. It is a little confusing.

The stream distsql explanation is TREE output
the batch distsql explanation is json output

**Comment by liurenjie1024** [comment]
The json output was supposed to be visualized in our dashboard, but currently we don't have resources for this.

**Comment by fuyufjh** [comment]
> The json output was supposed to be visualized in our dashboard, but currently we don't have resources for this.

We have an HC for frontend dev☺️
