### ISSUE TITLE
frontend: give a notice in pgwire for error-prone features

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#3727]
@st1page: there are some features not fully supported in our system such as index and some conterintuitued features such as create mv order by. We can give a warning and return it with pgwire in these situation https://github.com/singularity-data/risingwave/blob/06b3c11faecf3773bcbcbe9247a4b79e7765ed04/src/utils/pgwire/src/pg_response.rs#L117

- [x] https://github.com/risingwavelabs/risingwave/pull/6915
- [ ] reports case insensitivity when the user provides an unquoted name with capital letters

**Comment by ZENOTME** [comment]
Is this issue solved? Pgwire will return the error message if unimplemented features return an error.

**Comment by st1page** [comment]
> Is this issue solved? Pgwire will return the error message if unimplemented features return an error.

No. And for the totally unimplemented features, I think we need to return an error. This issue is for those features half state which usually is undocumented and not exact as human intuition or other DB's behavior.
