### ISSUE TITLE
feat(hash-agg): yield chunk to downstream after `apply_chunk` instead of `flush_data`

### ISSUE THREAD

**Issue by BowenXiao1999** [risingwavelabs/risingwave#3772]
Previously, the Extreme State require flush data before get output (to avoid complex merge-on-read). Therefore, we only flush data   and build stream chunk when receive a barrier. 

By now, we have `StateTable` to support Write-Any-Time, so it should be safe to yield chunk when `apply_chunk`. 

Also will clean up some stale docs.

**Comment by BugenZhao** [comment]
Will yielding chunks immediately after each input chunk be beneficial to the computing? The result will tend to be eventually replaced by an updated one at the end of this epoch, unless we ensure that inputs with the same group key can be gathered well.

**Comment by BowenXiao1999** [comment]
> Will yielding chunks immediately after each input chunk be beneficial to the computing? The result will tend to be eventually replaced by an updated one at the end of this epoch, unless we ensure that inputs with the same group key can be gathered well.

Yes me and @st1page also have the same concern. So this refactor may need to reconsider and postpone until we figure out the bottleneck.
