### ISSUE TITLE
feat(scaling, executor): `HashDataDispatcher` should be able to update `hash_mapping`

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#3778]
Currently, we can only `add_outputs`. However, we also need to update upstream dispatcher of scaled fragment with the new vnodes hash mapping.

Related: https://github.com/singularity-data/risingwave/issues/3752

**Comment by BugenZhao** [comment]
Cool. This will be for the step "Support updating partition on configuration change for each operator".
