### ISSUE TITLE
frontend: Derive output column names

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#3812]
In PG
```sql
postgres=# select abs(1);
 abs
-----
   1
(1 row)

postgres=# select count(1);
 count
-------
     1
(1 row)
```

In risingwave
```sql
dev=> select abs(1);
 ?column?
----------
        1
(1 row)

dev=> select count(1);
 ?column?
----------
        1
(1 row)
```

related but seems different: https://github.com/singularity-data/risingwave/issues/3690

**Comment by xiangjinwu** [comment]
To clarify the difference from #3690: the field names mentioned in that issue is internal, while the output column name shown in this issue is part of SQL semantic. For historical context on how they were decoupled and derived independently, check #2465 and #1433

**Comment by xiangjinwu** [comment]
This affects the result comparison in regress tests (e.g. #5452)

PostgreSQL:
https://github.com/postgres/postgres/blob/86a4dc1e6f29d1992a2afa3fac1a0b0a6e84568c/src/backend/parser/parse_target.c#L1729

RisingWave:
https://github.com/risingwavelabs/risingwave/blob/4998ba94da6f85f1568fa36a399e21a5797b05b9/src/frontend/src/binder/select.rs#L163-L180
