### ISSUE TITLE
feat(frontend): Support lateral joins

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#3815]
Since we now have the ability to unnest arbitrary subqueries (https://github.com/singularity-data/risingwave/pull/2880), lateral joins (alongside correlated subqueries) can be written as dependent joins (logical apply with correlated columns).

**Comment by likg227** [comment]
Actually, we can't really unnest arbitrary subqueries........ Nevertheless, relatively simple correlated subquery(subquery ONLY with project, scan(join), aggregate and filter) can be solved.

**Comment by jon-chuang** [comment]
> Actually, we can't really unnest arbitrary subqueries

Oh, so is there a plan to be able to unnest arbitrary correlated subquery?

**Comment by likg227** [comment]
> Oh, so is there a plan to be able to unnest arbitrary correlated subquery with join inside?

Yes, we have, but I don't sure whether we can implement it perfectly for RisingWave......

**Comment by jon-chuang** [comment]
We have put this on hold due to lack of clear supportability of lateral joins and user need. Please let us know if you need this feature.
