### ISSUE TITLE
Sqlsmith: Generate INSERT statement.

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#3844]

**Comment by fuyufjh** [comment]
🤔 Do you mean `insert select` or simple `insert values`? It would be trivial to generate `insert value` statement as long as random expression generation is supported. Furthermore, I think it's not necessary to test `insert value` with sqlsmith...

**Comment by kwannoel** [comment]
> :thinking: Do you mean insert select or simple insert values? It would be trivial to generate insert value statement as long as random expression generation is supported. Furthermore, I think it's not necessary to test insert value with sqlsmith...

Making a guess here: This is not to test `insert value`, rather values need to be inserted in the database for some queries, materialized views (and other executors) to be fully tested?

**Comment by neverchanje** [comment]
I think Eric’s understanding was basically what I meant. I actually wanted to test casting, e.g. `INSERT INTO t VALUES ('2020/10/1 10:00:00')`. Suppose the corresponding column is a TIMESTAMP. Looks simple, right? But in fact, it's currently not supported. Because we don't yet support implicit casting from string to timestamp. There are a couple of such edge cases of INSERT that we don't cover in our e2e tests yet. I used to think they should be included in sqlsmith. But indeed, we should simply do it at e2e.

**Comment by kwannoel** [comment]
Will be able to catch:
- Assign cast issues, e.g. #7691 
- vnode mapping issues: e.g. https://github.com/risingwavelabs/risingwave/issues/7698
