### ISSUE TITLE
test facility: find a more ergonomic way to build executors

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#3847]
Updated: we may want to fix this style issue when enhancing test facilities.

--- 
Original issue:

- Stream executors have a `from_proto` directory for all builders, but batch executors have them in each executor's file.
- Stream executors all have a builder, which is an empty struct, but batch executors have mixed style (personally I slightly prefer impl ExecutorBuilder for executors directly without Builder structs, since it's just a single method. We can use the Builder trait, but avoid the Builder struct)
<img width="655" alt="image" src="https://user-images.githubusercontent.com/37948597/178741871-b53080e4-a03a-4190-9ee5-2198d5699ab5.png">

**Comment by liurenjie1024** [comment]
This also applies to expression, plan, etc.

**Comment by MrCroxx** [comment]
> Found the stream executor reorg PR #2289
> 
> And initial builder PR #462
> 
> > BTW, `Builder` seems not that necessary here. We can discuss it offline.
> > _Originally posted by @MrCroxx in [#462 (review)](https://github.com/risingwavelabs/risingwave/pull/462#pullrequestreview-895798885)_
> 
> 🤔

IIRC, the context is that when building stream executors, some executors needs some extra field but the others don't, then @cykbls01 introduced a builder trait to solve it. I think it's okay to remove it if it's not used anymore.
