### ISSUE TITLE
storage: enable sanity check on simple/hash agg

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#3885]
Currently, it doesn't call `update` interface, which might cause problems for the storage layer.

**Comment by jon-chuang** [comment]
I think it writes to same key instead of updating, but we guarantee we do this once per epoch. We don't want this? This is the same behaviour for DynamicFilter that I copied from hash agg.

**Comment by richardchien** [comment]
As @BugenZhao commented in https://github.com/risingwavelabs/risingwave/pull/5598#discussion_r985444852, after #5598 is merged, we can have a better way to check if an `insert` or an `update` is needed, that means we can enable sanity check and remove `upsert` introduced in #5565. I will do this soon.
