### ISSUE TITLE
planner: duplicated expressions after logical plan optimization

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#3897]
**Describe the bug**
There are sometimes duplicated expressions in logical plan. They continue to exist in stream and batch plan. They take up unnecessary space in storage and memory. We should deduplicate them in `LogicalProject` and `LogicalAgg` among others.

**Additional context**
_Originally posted by @jon-chuang in https://github.com/singularity-data/risingwave/issues/2655#issuecomment-1184314799_

Btw, regarding this issue:
Some questions (Q11): why are the agg calls duplicated in the plan:

```
LogicalAgg { group_keys: [0], agg_calls: [sum($1), sum($1)] }
```

Its not yet solved, and I seem to encounter it again on:
 
 ```
- sql: |
    create table product(p_id int, price int);
    create table user(user_id int, budget int);
    select * from user, lateral (select * from product where price = budget);
  optimized_logical_plan: |
    LogicalJoin { type: Inner, on: ($4 = $1), output_indices: [0, 1, 2, 3] }
      LogicalScan { table: user, columns: [user_id, budget] }
      LogicalProject { exprs: [$0, $1, $1] }
        LogicalScan { table: product, columns: [p_id, price] }
```

Take note the duplicated expr: `LogicalProject { exprs: [$0, $1, $1] }`. Maybe we need a dedup expr rule somewhere? It could be complicated as parent nodes may depend on one of the inputs, we need to rewrite all of that recursively. It would be better if duplicated expressions cannot be created in the first place? So we prevent this behaviour in Agg, Project, Order by operators? @xiangjinwu

**Comment by xiangjinwu** [comment]
We need to clarify the goal of this issue before proceeding https://github.com/singularity-data/risingwave/issues/2655#issuecomment-1185109136

Duplicates may come from different places. A general pass that removes duplicates may not be the best solution.

**Comment by xiangjinwu** [comment]
Update:

> As for the new example involving lateral, it looks like the duplication is from our binder/planner/optimizer rather than from user input.

We have deferred support of from-lateral-subquery, so there is no new duplicates generated from binder/planner/optimizer.

Next step: revisit current plans and update the goal of this issue, and possibly close if there are no duplicates that worth avoiding.

**Comment by xiangjinwu** [comment]
We can reopen when there is a concrete duplication we want to avoid. The original motivation from `from-lateral-subquery` is not valid yet.
