### ISSUE TITLE
storage: LRU cache failed to dedup requests

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#3901]
**Describe the bug**

<img width="642" alt="image" src="https://user-images.githubusercontent.com/4198311/179142947-0076e7c2-8a22-41b5-8d6f-4d50831b16f4.png">

<img width="897" alt="image" src="https://user-images.githubusercontent.com/4198311/179143007-5bb996bc-0568-4e0f-8d03-837d222179a3.png">

There're multiple pending requests to a single item.

**To Reproduce**
TPC-H Q18

**Expected behavior**

**Additional context**

**Comment by fuyufjh** [comment]
is it fixed?

**Comment by skyzh** [comment]
Not yet

**Comment by Little-Wallace** [comment]
Do you have more information to prove that there is no other thread evicted this cache entry.

**Comment by skyzh** [comment]
Let's hold this a little bit until we have a better tracing tool. By the way, I remembered that our LRU cache will issue more I/O requests than moka in `cargo bench`. We might start investigating from running micro benches instead of the full e2e test.
