### ISSUE TITLE
bug: SQL parser accepts everything as potential function.

### ISSUE THREAD

**Issue by ALeitert** [risingwavelabs/risingwave#3919]
If we call a function in SQL, we either get the result or that it is not implemented. The problem is that we also get a "not yet implemented" message for functions that are not actual SQL functions. For example:

```
dev=> Select abs(-3.14); Select sin(3.14); Select fakeFunction(3.14);
 ?column? 
----------
     3.14
(1 row)

ERROR:  Feature is not yet implemented: unsupported function: "sin", Tracking issue: https://github.com/singularity-data/risingwave/issues/112
ERROR:  Feature is not yet implemented: unsupported function: "fakefunction", Tracking issue: https://github.com/singularity-data/risingwave/issues/112
```
If I understand it correctly, the parser interprets the pattern `<identifyer> ( <expr>, ... )` always as function. It does not distinguish between functions we still need to implement and functions which are not defined in SQL.

**Comment by xiangjinwu** [comment]
What is the expected fix? The list of supported function can grow, and there may not be a clear boundary which ones are "todo"s and which ones are "never-do". PostgreSQL also reports the same error on `fakeFunction `:

```
test=# select fakeFunction(1);
ERROR:  function fakefunction(integer) does not exist
LINE 1: select fakeFunction(1);
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

test=# create function fakeFunction(int) returns bool return true;
CREATE FUNCTION

test=# select fakeFunction(1);
 fakefunction 
--------------
 t
(1 row)
```

**Comment by lmatz** [comment]
I think we cannot say "tracking issues" for wrong functions at least.

**Comment by xiangjinwu** [comment]
> I think we cannot say "tracking issues" for wrong functions at least.

But how do we define which ones are "wrong"? We can either never show it, or always show it.

**Comment by lmatz** [comment]
By "wrong", I mean it is not in the PG's specification. Then we show `HINT:  No function matches the given name and argument types. You might need to add explicit type casts.`

If it is in the PG's specification but is not supported, we can still show the current error message.
