### ISSUE TITLE
streaming: remove dirty flag for states

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#4035]
With flush status uniformly managed by the state table, there should be no dirty flag on each state; that is, we should be able to evict the entry at any time. With this property, we can make the cache in streaming more flexible. #3762

- [ ] Rewrite states to not store dirty data in itself.
- [ ] Remove `dirty` flag for all states.
- [ ] Remove `.flush()` (?)

**Comment by BowenXiao1999** [comment]
Thanks for bring this up. I was just planning to open this :)

**Comment by BowenXiao1999** [comment]
> Rewrite states to not store dirty data in itself
Do you mean the `prev_states` here?

https://github.com/singularity-data/risingwave/blob/0b7aea581774f70ddf91a811d7ad9ae68222a257/src/stream/src/executor/aggregation/agg_state.rs#L28-L34

I think no flush buffer just means no dirty data

**Comment by BowenXiao1999** [comment]
https://github.com/singularity-data/risingwave/blob/d3741f412b3cb0fc9a771dd36b7f03f66fde6d5b/src/stream/src/executor/managed_state/aggregation/mod.rs#L95

Dirty flag on `managed_state` is easy to remove.

However, the dirty flag on `AggState` relies on `prev_states` and `build_changes`. Currently no clue on how to remove this.

**Comment by BugenZhao** [comment]
#4127 removed the old `string_agg` implementation. There should be no references now.

> However, the dirty flag on AggState relies on prev_states and build_changes. Currently no clue on how to remove this.

We may let the simple state directly update and read from the state table instead of maintaining a result in memory?

**Comment by BowenXiao1999** [comment]
> #4127 removed the old `string_agg` implementation. There should be no references now.
> 
> > However, the dirty flag on AggState relies on prev_states and build_changes. Currently no clue on how to remove this.
> 
> We may let the simple state directly update and read from the state table instead of maintaining a result in memory?

Got some point. So this also requires #3772 right? Seems huge 😿

**Comment by BugenZhao** [comment]
For aggregation, the dirty state of the value states (Sum, Count, AppendOnlyMin/Max) is still stored in the state itself. Per some offline discussions, we decide to move it to the memory table and introduce the `Upsert` semantic for the memory table. cc @richardchien
