### ISSUE TITLE
maybe use isolated pg session for each slt in e2e test

### ISSUE THREAD

**Issue by yuhao-su** [risingwavelabs/risingwave#4038]
Currently all slt file in e2e test runs in one session. This might be a problem when we test `SET xxx`, all later slt test will use the earlier slt test parameters. 

Of course, we can set a parameter back after finishing using it, but it is error-prone.

**Comment by skyzh** [comment]
We already support this by setting -j 1.

**Comment by yuhao-su** [comment]
```
    -j, --jobs <JOBS>        Whether to enable parallel test. The `db` option will be used to create
                             databases, and one database will be created for each test file
```
It's one db for one file, but maybe one session for one file should be enough?

**Comment by skyzh** [comment]
Sounds good. May have a try.

**Comment by fuyufjh** [comment]
@BugenZhao We had encountered to the smae issue before, right? Did you do some fix?

**Comment by BugenZhao** [comment]
> @BugenZhao We had encountered to the smae issue before, right? Did you do some fix? 

I think this has been resolved in https://github.com/risingwavelabs/risingwave/pull/4902.
