### ISSUE TITLE
batch: Use determined test to test query manager.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#4051]
Query manager need to handle concurrent request, state changes, and I feel it's a good place to test with simulation framework.

**Comment by BowenXiao1999** [comment]
Current Query Manager logic is simple, and we already used parallel test or MADSIM_TEST_NUM to test it. So I think we can make it as unplanned now.

**Comment by liurenjie1024** [comment]
LGTM
