### ISSUE TITLE
Tracking: Eliminate usages of `RwError`

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#4077]
@BugenZhao (Nov 29, 2023): See motivation here https://github.com/risingwavelabs/risingwave/pull/13588#issuecomment-1831176611

---

Also I suggest avoiding using RwError everywhere. RwError is designed to have 1-1 correspondence with Postgres. However, not all our results will be reported to Postgres shell -- meta error, cli error, dashboard error, stream error, they won't have any interaction with Postgres.

I think the first step is to introduce per-crate error type.

_Originally posted by @skyzh in https://github.com/singularity-data/risingwave/issues/1367#issuecomment-1081379711_

- [x] #3116
- [x] #4368
- [ ] #2366
- [x] #4168 
- [x] storage: eliminate usages of `RwError`
- [x] #4105
- [x] #5272
- [x] #5273

**Comment by BugenZhao** [comment]
Related:
- #2366

**Comment by fuyufjh** [comment]
I decided to bring this back to milestone because `RwError` seems to be a potential performance killer and it's very hard to use any testing to eliminate. Refactoring seems the only way. 

Batch and Connectors seems to be the major blockers now. Please take a look ❤️ cc. @tabVersion @liurenjie1024

**Comment by liurenjie1024** [comment]
> I decided to bring this back to milestone because `RwError` seems to be a potential performance killer, and it's very hard to use any testing to eliminate. Refactoring seems the only way.
> 
> Batch and connector mod seems to be the major blockers now. Please take a look ❤️ cc. @tabVersion @liurenjie1024

Why `RwError` is a performance killer? Since it may use backtrace?

**Comment by fuyufjh** [comment]
Yeah, it always captures the stacktrace. 

I think we need to eliminate usage of `RwError` completely *inside* RisingWave, but only use it as a way to return Error to Users. Btw, @BugenZhao is working on a more sophisticated solution, but this is a good starting point.

**Comment by liurenjie1024** [comment]
> Yeah, it always captures the stacktrace.
> 
> I think we need to eliminate usage of `RwError` completely _inside_ RisingWave, but only use it as a way to return Error to Users. Btw, @BugenZhao is working on a more sophisticated solution, but this is a good starting point.

Hmm, then we will lose contexts.

**Comment by BugenZhao** [comment]
> Hmm, then we will lose contexts.

I guess providing contexts doesn't have to be done through backtrace. For errors triggered by users (like `ExprError`), the original input could be much more meaningful than a static backtrace. We can choose some of the error variants that are believed as internal errors and add the `backtrace` field specifically for them.

**Comment by fuyufjh** [comment]
> > Yeah, it always captures the stacktrace.
> > I think we need to eliminate usage of `RwError` completely _inside_ RisingWave, but only use it as a way to return Error to Users. Btw, @BugenZhao is working on a more sophisticated solution, but this is a good starting point.
> 
> Hmm, then we will lose contexts.

As Bugen mentioned, we can keep some backtrace for internal errors. But for user-facing errors such as parser error, it doesn't make sense to capture the stacktrace

**Comment by fuyufjh** [comment]
@BugenZhao PTAL

**Comment by BugenZhao** [comment]
Only the frontend crate remains to be refactored. I'd like to close this PR and let #2366 to track that.
