### ISSUE TITLE
RFC: Streaming object store + SSTable block stream

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#4096]
# RFC Template

## Background
Rather than reducing the number of concurrent tasks per node,we are trying to reduce per-task memory usage during compaction. See https://github.com/singularity-data/risingwave/issues/3921

To do so, we will download and process input sstables in a streaming fashion, instead of downloading them in their entirety in advance, as we do now.

## Design

The design consists of two parts:
1. Object store stream interface 
2. `SSTableStreamIterator`

The first part adds a new interface to object store. It will be unimplemented for other object stores, and implemented as a byte stream for S3, where we rely on TCP for flow control.

The interface looks like:
```rust
async fn streaming_read(&self, path: &str, block_loc: Option<BlockLocation>) -> Box<dyn ObjectStoreStream>;
```

Where the stream implements the following interface:
```rust
trait ObjectStoreStream {
  async fn next_bytes(num_bytes: usize) -> Bytes {..}
}
```

We depend on S3's/aws SDK's `ByteStream` actually streaming the bytes over the network with TCP/IP flow control rather than providing an async iterator over a preallocated array of bytes (apparently we can: https://github.com/awslabs/aws-sdk-rust/discussions/286#discussioncomment-2955857).

The second part creates a new `SSTableStreamIterator`. 
The pseudo code looks like the following:

```rust
struct SSTableStreamIterator {..}

impl SSTableStreamIterator {
    fn new(..) {
      self.sst_stream = self.store.streaming_read(sst_path, ..);
      ..
    }
    
    async fn next_block() {
      let next_block_meta in self.sst_meta.block_metas.next();
      let next_block_data = sst_stream.next_bytes(next_block_meta.block_len_bytes).await;
      next_block = Block::new_with_bytes(next_block_data);
      self.block_iterator = Some(next_block.into());
    }
    
    async fn next() {
      if self.block_iterator.is_consumed() {
        self.next_block().await;
      }
      ..
    }
}
```

## Future Optimizations

1. Concurrent object store download. Background threads run to replenish block queues for each SStable iterator. The concat iterator passes a parameter that increases queue length for its sstable iterators. This is so that we never have to yield due to unready iterators in our main compaction task. We expect to pull from `ConcatIterators` more often as the merge will rip through its blocks at a higher rate than individual SSTableIterators which may cover a comparatively larger range (?).
2. We can explore streaming and decoding KV-pairs at a finer granularity than blocks.

**Comment by wenym1** [comment]
> We can explore streaming and decoding KV-pairs at a finer granularity than blocks.

I don't think it's necessary to support decoding to such a fine-grain granularity. Decoding at a KV-pair granularity does not mean we are only holding or fetching data in a KV-pair granularity since the underlying TCP control is likely to fetch and hold data at such a fine-grain granularity.

More importantly, we will do block level compression to reduce the SST data size. So it's not likely to yield a single KV before we fetch the whole block.
