### ISSUE TITLE
bin: implement gRPC health-check protocol

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#41]
https://github.com/grpc/grpc/blob/master/doc/health-checking.md

In the future, compute-node might need to wait until meta-node is able to serve requests before start-up. Port open doesn't indicate that a service is ready. So we may need to implement such health-check protocol.

This can be done by add new RPC endpoints in each node's service. We can implement health check for each of the components:

- [ ] #5070
- [ ] #5071
- [ ] #5072
- [ ] #5073

**Comment by yinfredyue** [comment]
Hi, I am new to RisingWave and think this might be my first issue to work on. After reading the relevant pages, I have the following questions:

- What is the dependency graph between different components? From the architecture doc, it seems that compute, front-end, and compactor all depend on meta. Also, `xxxOpt` (argument of the `start` function` all contain a `meta_address`. Does this mean all three types of nodes depend on meta?

- What are the health/bootstrapping checks you are having in mind? Send a "are you ready?" message gRPC to the dependency (e.g. meta), and wait until this RPC succeeds before sending any real query/message?

**Comment by skyzh** [comment]
* Yes. All of them depend on meta.
* For now, we can make things simple. Once a node starts its tonic service, we can set health check to success. In the future, we can decide whether to report health based on whether meta is connected / storage is okay / etc.

**Comment by yinfredyue** [comment]
What's the expected behavior after this feature is implemented?

**Comment by skyzh** [comment]
gRPC will have an interface exposed to external services, and external services like Kubernetes can know if each node is up.
