### ISSUE TITLE
Tracking: dashboard v2.5

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#4137]
The current dashboard v2 is good enough, but few developers are using it. We should make it more suitable for developers.

- [x] better integration test
- [x] make the dashboard more responsive and tailored for developers' need
- [ ] #5255
- [ ] #5256
- [ ] #5257
- [x] #5258
- [x] #5259

**Comment by xxchan** [comment]
When to deprecate dashboard v1? 🤪

**Comment by skyzh** [comment]
By the end of this year, hopefully 🤤

**Comment by skyzh** [comment]
small issues left for someone else to solve, closing this for now
