### ISSUE TITLE
batch: singleton seq scan on local mode

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#4164]
**Describe the bug**
Currently, when scanning from a singleton mview, we still schedule multiple scans.

**To Reproduce**
```sql
create table t (v int);
create materialized view mv as select v from t order by v limit 10;

explain verbose select * from mv;
                          QUERY PLAN                          
--------------------------------------------------------------
 BatchExchange { order: [], dist: [Single] }
   BatchScan { table: mv, columns: [mv.v], distribution: [] }
```

The distribution is `[]`, that is, `HashShard` with empty keys. This is incorrect, we should use `Single` instead.

https://github.com/singularity-data/risingwave/blob/eb8109fc122ad51a8ccfcf4fc1efc03d79bfdb0a/src/frontend/src/optimizer/plan_node/batch_seq_scan.rs#L75-L93

#4153 introduced a fix while commented out, since it won't work on local mode now. We should fix this.

**Expected behavior**
```
                          QUERY PLAN                          
---------------------------------------------------------------
 BatchScan { table: mv, columns: [mv.v], distribution: Single }
```

**Additional context**
#4153 fixes the similar issue of `StreamScan`.
#3269 is related.

**Comment by BugenZhao** [comment]
@xxchan Could you please help to take a look?

**Comment by BowenXiao1999** [comment]
Well this problem is hard to find cuz the execution works fine and we can get the results. 👍

**Comment by BowenXiao1999** [comment]
Agreed that HashShard(vec![]) should not a valid expression in our system.

**Comment by liurenjie1024** [comment]
This is a known issue, another case the table scan maybe singleton is partition prunning.

**Comment by liurenjie1024** [comment]
I think we should fix it in fragmenter, since we will move root fragment execution into frontend later.
