### ISSUE TITLE
Authentication support in Kafka Connector

### ISSUE THREAD

**Issue by arjunsk** [risingwavelabs/risingwave#4200]
**Is your feature request related to a problem? Please describe.**
When using Kafka API of Azure Event Hub, we generally use SASL auth. It would be great if RisingWave supports SASL auth options. If it’s already supported, kindly update the docs.

**Describe the solution you'd like**
Add support for  WITH options,
```properties
sasl.mechanism=PLAIN
security.protocol=SASL_SSL
sasl.jaas.config=
```
In existing table syntax
```sql
CREATE MATERIALIZED SOURCE IF NOT EXISTS source_abc (
   column1 varchar,
   column2 integer,
)
WITH (
   connector='kafka',
   kafka.topic='demo_topic',
   kafka.brokers='172.10.1.1:9090,172.10.1.2:9090',
   kafka.scan.startup.mode='latest',
   kafka.time.offset='140000000',
   kafka.consumer.group='demo_consumer_name'
)
ROW FORMAT JSON;
```

**Describe alternatives you've considered**
[Flink SQL](https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/connectors/table/kafka/)

**Comment by TennyZhuang** [comment]
Thanks for the feature request!

The feature is useful and after some investigation I guess that it's not very hard for us to implement. The rdkafka crate allow us to pass configuration items directly to the C library.

There may be some little blocking by #4158 that we mistakely use some unnecessary `kafka` prefix here and we will introduce a breaking change for the renaming, but IMHO we can resolve it and implement this feature in a near future.
