### ISSUE TITLE
Panic when Apply encounters Limit.

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#4204]
```
create table t1 (x int, y int);
create table t2 (x int, y int);

// panic
select * from t1 where exists(select t2.x from t2 where t1.x = t2.x limit 10);
```

**Comment by likg227** [comment]
Maybe we can implement ApplyTopN instead of ApplyLimit, which will be useful. 
[blog for reference](https://materialize.com/lateral-joins-and-demand-driven-queries/)

**Comment by skyzh** [comment]
Yifan is working on groupByTopN (aka. localTopN). It would be good if we can use this executor for both two-phase topN and applyTopN.

**Comment by chenzl25** [comment]
The point I want to express is our subquery unnesting rely on pushing down `Apply` and then replace all `correldated_input_ref` , but for some operator like `Limit`, it seems to be impossible to transpose them.

**Comment by chenzl25** [comment]
We don't support transpose the apply operator and limit operator.
