### ISSUE TITLE
sink: don't concat SQL by hand

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#4217]
I see. 

https://github.com/blackbeam/rust_mysql_common/blob/974c13b5275f9fcdff01a286ca4678afb12a9375/src/value/mod.rs#L286-L295

But it still sounds like a bad practice to concat SQL by hand. It's inefficient than using the wire protocol to compose the values. I think we will eventually go for the way like:

```
    r"INSERT INTO payment (customer_id, amount, account_name)
      VALUES (?, ?, ?)"
        .with(vec![mysql_common::Value(x), mysql_common::Value(y), mysql_common::Value(z)])
        .batch(&mut conn)
        .await?;
```

LGTM for now.

_Originally posted by @skyzh in https://github.com/singularity-data/risingwave/pull/3877#discussion_r930187535_

**Comment by BugenZhao** [comment]
With params, `mysql_async` will use the binary protocol which should be more efficient. 🥰
