### ISSUE TITLE
frontend: do not check duplicated name when explaining

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#4260]
We may not check whether the provided name is duplicated when explaining `create materaialized view`, `create table`, or `create index`.

```
dev=> create table t (v int);
CREATE_TABLE
dev=> create materialized view mv as select v from t order by v limit 10;
CREATE_MATERIALIZED_VIEW
dev=> explain create materialized view mv as select v from t order by v limit 10;
ERROR:  QueryError: Catalog error: materialized view with name mv exists.
dev=> explain create materialized view mvvvv as select v from t order by v limit 10;
                                                 QUERY PLAN                                                  
-------------------------------------------------------------------------------------------------------------
 StreamMaterialize { columns: [v, t._row_id(hidden)], pk_columns: [t._row_id], order_descs: [v, t._row_id] }
   StreamTopN { order: "[t.v ASC]", limit: 10, offset: 0 }
     StreamExchange { dist: Single }
       StreamTableScan { table: t, columns: [v, _row_id] }
(4 rows)
```

**Comment by yinfredyue** [comment]
Is this still an open issue? Can I take it?

**Comment by skyzh** [comment]
You can have a try 😋

**Comment by yinfredyue** [comment]
Here's my thought.

**Background**: When explaining, we generate the plan first. `gen_create_mv_plan` generates the plan for creating materialized view. This function calls `Catalog::check_relation_name_duplicated` and generates err when there's a duplicated name. Note that `gen_create_mv_plan` is also called by `handle_create_mv` to create a new MV.

**My plan**: Change signature of `gen_create_mv_plan` from
```rust
fn gen_create_mv_plan(
    session: &SessionImpl,
    context: OptimizerContextRef,
    query: Box<Query>,
    name: ObjectName,
) -> Result<(PlanRef, ProstTable)>
```
to
```rust
fn gen_create_mv_plan(
    session: &SessionImpl,
    context: OptimizerContextRef,
    query: Box<Query>,
    name: ObjectName,
    ignore_duplicat_name: bool // new arg
) -> Result<(PlanRef, ProstTable)>
```
and call `check_relation_name_duplicated` only when `ignore_duplicat_name` is false.

Sounds good?

**Comment by skyzh** [comment]
I'd prefer having a new function gen_mv_plan_when_explain 🥰

**Comment by yinfredyue** [comment]
> I'd prefer having a new function gen_mv_plan_when_explain 🥰

If we create a new function, we should try to avoid duplicated code. Very roughly, `gen_create_mv_plan` does this:

```
fn gen_create_mv_plan(..) {
  1. resolve table name and check writable;
  2. read catalog to get database id and schema id, and check duplicate;
  3. other checks;
  4. actually generate the plan.
}
```
The new function will do exactly the same thing, except that it won't do the duplicate check at step 2. I cannot see an easy way to implement `gen_mv_plan_when_explain` without many duplicated code,  if we don't factor step 1, 3, and 4 into functions (which require quite some efforts).

Any thoughts?

**Comment by skyzh** [comment]
Then it looks okay to add a new arg on gen_mv_plan. But I have no idea why we need to check dup when generating plan. It would be good if we can split check dup and gen plan into two functions 🤣

**Comment by yinfredyue** [comment]
I agree it's probably better to split check dup and gen plan into two functions. I suggest we get the functionality right in this PR, and address the issue in another refactor PR. What do you think?

**Comment by skyzh** [comment]
Sounds good!
