### ISSUE TITLE
test: enable `PG` regress test `join_hash.sql`

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#4268]
Check https://github.com/risingwavelabs/risingwave/tree/main/src/tests/regress to see how we enable the test case

**Comment by lmatz** [comment]
Is the assignee still working on this?

**Comment by liurenjie1024** [comment]
> Is the assignee still working on this?

No, he has left.

**Comment by liurenjie1024** [comment]
Same as #4266
