### ISSUE TITLE
scalar: introduce Datum struct to have null-last Ord behavior

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#4272]

**Comment by skyzh** [comment]
while https://github.com/singularity-data/risingwave/pull/4263 only changes the key encoding, we should revisit all places that we store `Row` and `Datum`, so that it is consistent with the behavior of the storage. Normally this would happen in `BTreeMap<Row, Row>`.

**Comment by xiangjinwu** [comment]
I guess this means `Datum` should not have `Ord`, or we have to wrap them as `NullsLargestDatum` and `NullsSmallestDatum` to support `nulls first` and `nulls last` in the future. This does not take collation into account as well...

**Comment by skyzh** [comment]
Also sounds reasonable to me... We should rethink how we directly use `Row` / `Datum` to do comparisons...

**Comment by BugenZhao** [comment]
`Datum` contains the data type tag and it actually seems kind of meaningless to implement `Ord` on it, which allows comparing datums with different types, not to mention that we may not be able to customize that 🤣 #477.

I'm not sure whether there are many cases for comparing `Row`. With the new schemaless row format introduced by @yuhao-su, we'll always need the row schema to make comparisons. We may solve this issue at that time by the way.

**Comment by yuhao-su** [comment]
> I'm not sure whether there are many cases for comparing Row
Ideally no. But we may be using BtreeMap as a kv index in our system somewhere (we may replace them with other data structures like HashMap).  

The comparison between `Row`s should be avoided. If we want a order, we should encode it as `memcomparable`

**Comment by richardchien** [comment]
Working on `NULLS FIRST/LAST` in #8485, I feel that we'd better introduce a dedicated type for `Datum` (either `struct` or `enum` is OK). The key point is to disallow comparing on `Datum`s without an `OrderType`. If we don't, `NULLS FIRST/LAST` support can be easily broken by any unintentional comparison on `Datum`s which are actually `Option`s, and that cause a chaos in our system in regards to row ordering.

**Comment by richardchien** [comment]
> I feel that we'd better introduce a dedicated type for `Datum` (either `struct` or `enum` is OK).

Had a try on this, the result is that there're too many changes need to be made. Then I came up with another idea.

> The key point is to disallow comparing on `Datum`s without an `OrderType`.

Since the key point is to avoid automatical derivation of `Ord` caused by `Option`, **we can simply don't implement `Ord` for `ScalarImpl`**. The idea is actually quite consistent, we don't want `Datum` to be ordered without an `OrderType`, so we may also don't want `ScalarImpl` to be ordere without an `OrderType`. The difference is that the default impl of `Ord` for `Datum` is incorrect (ascending nulls first) but the one for `ScalarImpl` is correct (ascending).

**Comment by richardchien** [comment]
Any thoughts? cc @BugenZhao

**Comment by BugenZhao** [comment]
> so we may also don't want `ScalarImpl` to be ordered without an `OrderType`

Makes sense to me. 👍 We may introduce several thin wrappers instead for `ScalarImpl`, `Option<ScalarImpl>`, and `Vec<Option<ScalarImpl>>` to provide a default `ASC NULLS LARGEST` `Ord` implementation for convenience if the caller really don't care about the order.
