### ISSUE TITLE
clippy: workspace-level clippy configurations

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#4312]
Currently, we add a lot of clippy attributes at the root of each crate. It would be possible for us to forget to keep all crates consistent.

https://github.com/singularity-data/risingwave/blob/a15b40a28e86db1bb4d5c9b35f7303249d8102fd/src/stream/src/lib.rs#L16-L27

We may add them as rustc flags at `.cargo/config.toml`. An example:

https://github.com/EmbarkStudios/rust-ecosystem/blob/main/lints.toml

**Comment by xxchan** [comment]
upstream issue https://github.com/rust-lang/cargo/issues/5034 🙏

**Comment by xxchan** [comment]
I'm also hoping to use `#![feature]` at workspace level 🤪
