### ISSUE TITLE
CREATE TABLE ... AS ... not working

### ISSUE THREAD

**Issue by wzzzzd** [risingwavelabs/risingwave#4315]
**Describe the bug**
```sql
create table a (v int);
insert into a values (1), (2);
create table b as select * from a;
select * from b;
```

In RisingWave,
```
dev=> select * from b;
--
(0 rows)
```

In PostgreSQL,
```
postgres=# select * from b;
 v 
---
 1
 2
(2 rows)
```

**Expected behavior**
The query should output the same results as pg or print an error message (e.g. "not supported").

**Additional context**
```
dev=> explain create table b as select * from a;
                               QUERY PLAN                                
-------------------------------------------------------------------------
 StreamMaterialize { columns: [_row_id(hidden)], pk_columns: [_row_id] }
   StreamExchange { dist: HashShard(_row_id) }
     StreamSource { source: "b", columns: [_row_id] }
(3 rows)
```

**Comment by fuyufjh** [comment]
It seems that `create table` was treated as `create materialized view`.

But why `select * from b` got empty result? 😅

**Comment by xiangjinwu** [comment]
It has not been implemented ... We have a lot of places that simply ignores unsupported fields (e.g. `as query` of `create table`) rather than reporting errors ...

**Comment by BugenZhao** [comment]
> It seems that `create table` was treated as `create materialized view`.
> 
> 
> 
> But why `select * from b` got empty result? 😅

Do we plan to implement this way? 👀

**Comment by jon-chuang** [comment]
> Do we plan to implement this way? eyes

What are the alternatives? We could always let the created table have static data. So it depends what we think users want when they say create table as ... I get the feeling they want a materialized view.

**Comment by fuyufjh** [comment]
To clarify the semantics:

The [document of Postgres](https://www.postgresql.org/docs/current/sql-createtableas.html) says

> CREATE TABLE AS creates a table and fills it with data computed by a SELECT command. The table columns have the names and data types associated with the output columns of the SELECT (except that you can override the column names by giving an explicit list of new column names).

If users want to create an empty table with the same table definition, they may use

```sql
CREATE TABLE films2 AS
    TABLE films
    WITH NO DATA;
```

**Comment by fuyufjh** [comment]
> Do we plan to implement this way? 👀

I don't think we have a plan for `CREATE TABLE ... AS ...` at this stage. 

If it's already supported we may correct it to the right behavior (aligned with PG), otherwise, I would like to ban this syntax.
