### ISSUE TITLE
`generate_series` should check zero step size

### ISSUE THREAD

**Issue by wzzzzd** [risingwavelabs/risingwave#4318]
**Describe the bug**
```sql
select * from generate_series(0, 5, 0);
```

In RIsingWave, the server goes into an infinite loop and eats all the memory.

In PostgreSQL,
```
postgres=# select * from generate_series(0, 5, 0);
ERROR:  step size cannot equal zero
```

**Comment by xiangjinwu** [comment]
> Handling of special params (negative, zero, null, variable-length month) can be in a followup.

_Originally posted by @xiangjinwu in https://github.com/singularity-data/risingwave/pull/2624#pullrequestreview-976384163_ 🤦
