### ISSUE TITLE
feature: support MView with `order by` (without `limit`)

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#4330]
For example:

```
create materialized view mv as
select * from tb1 order by id
```

Generally, users want the MView to be ordered on query. Here is our proposal:

- On creating Mview
  1. Materialize the results into a distributed mview with primary_key = dist_key = [sort_key, stream_key]
  2. Record the sort_key in MView's catalog in a special field e.g. `rewrite_order_key`
  3. Record the stream_key in MView's catalog, so the MV-on-MV can know the correct stream_key instead of primary key. (IIRC, this should has been done and the field is called 'stream_pk')
- On executing batch query
  1. Rewrite the query implicity for users by adding `order by ...`, if
     - Only one table is selected
     - `rewrite_order_key` is set
  2. The `order by` clause should be optimized into an ordered Exchange aka. MergeSort.

## Q&A

Q. Is it possible to let the distribution key of MView to be upstream's `stream_key` only? So that the `Shuffle` before Materialize can be omitted.
A. Yes, but that would break an assumption - distribution key must be a prefix of primary key, which benefits the performance of compactor. I think it's not worth to break it for our little case.

## Related

Discussed at #4309

**Comment by lmatz** [comment]
Guess this is already supported as IIUC, `create index (XXX)` is exactly the same as `create MV ... order by XXX`?
