### ISSUE TITLE
Add tips for the Playground mode

### ISSUE THREAD

**Issue by CharlieSYH** [risingwavelabs/risingwave#4331]
**Is your feature request related to a problem? Please describe.**
After running the `./risedev p` command and waiting for the whole compiling process to be finished, there's no notice or hint shown on the terminal. And users have to open another terminal to connect to RisingWave. It's a little bit confusing and inconvenient:
<img width="682" alt="image" src="https://user-images.githubusercontent.com/100549427/182115556-c38b269d-0a79-423b-96d6-797b68d6a173.png">

**Describe the solution you'd like**
The dev mode is a good example.
<img width="682" alt="image" src="https://user-images.githubusercontent.com/100549427/182093600-539516cb-2639-404f-9295-e024eae99eb1.png">
For playground mode, I suggest something like:
```
RisingWave instance started.
* Open a new terminal window, run psql -h localhost -p 4566 -d dev -U root to connect to and communicate with RisingWave via psql.
* Run \q to quit psql.
* This RisingWave instance will be automatically terminated after 30 minutes of inactivity.
```

**Comment by skyzh** [comment]
Looks good to me. If this is not an urgent task, I might do some refactors later.

**Comment by CharlieSYH** [comment]
> Looks good to me. If this is not an urgent task, I might do some refactors later.

Great! Not urgent at all. Take you time and be cozy.☺️
