### ISSUE TITLE
batch: eliminate usages of `RwError`

### ISSUE THREAD

**Issue by wzzzzd** [risingwavelabs/risingwave#4368]

**Comment by BowenXiao1999** [comment]
Two difficult part
* implement a From<BatchError> for tonic::Status (Can refer to how RwError convert this)
* The `clone` on task failure. (Maybe we should use .take)

You can check whether this [branch](https://github.com/singularity-data/risingwave/tree/bw/eliminate_RwError_batch) help

**Comment by xxchan** [comment]
> implement a From for tonic::Status (Can refer to how RwError convert this)

https://github.com/singularity-data/risingwave/pull/4227 Here are also some discussions about this problem 🥸
