### ISSUE TITLE
batch: data chunk stream between batch executor should be a FusedStream

### ISSUE THREAD

**Issue by BowenXiao1999** [risingwavelabs/risingwave#4372]
Fused means : Once None, no more data chunk will be sent. 
But currently it is not restricted.

**Comment by liurenjie1024** [comment]
What's its `FusedStream` behavior if we still poll after returning `None`? It seems that we should we can't guarantee it using compiler.

**Comment by BowenXiao1999** [comment]
Among executors we can do like this: https://github.com/singularity-data/risingwave/blob/074daaf9f1d919c159ed8dd6434d54c9e9ce4377/src/batch/src/executor/filter.rs#L57-L60

For task execution like #4132 , seems like do not have a compiler way.

**Comment by liurenjie1024** [comment]
So you mean `for_await` generated code will stop poll `FusedStream` after `None`?

**Comment by skyzh** [comment]
> So you mean for_await generated code will stop poll FusedStream after None?

It will stop poll even if it's not a fused stream.
