### ISSUE TITLE
enhance: streaming HashJoin should maintain degree only for opposite of outer side(s)

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#4384]
Currently, our streaming HashJoin always maintains *degree*, which is an integer column to record the number of joined rows from the other side. This is useful for outer join to emit the NULL rows. For example,

```sql
A left join B on A.bid = B.id
```

For this case, whenever a B event comes, the Join operator needs to

- If B event is delete (-)
  - Check whether more than 1 AB events has been emitted yet (degree > 1), if so, a + NULL event needs to be emitted after this AB row is deleted
- If B event is insert (+)
  - Check whether any AB event has been emitted yet (degree < 1), if not, a - NULL event need to be emitted before this AB row is inserted

As we can see, actually degree only matters for outer joins. Specifically,

- Inner join: none
- Outer join: the inner side
- Full outer join: both sides
- Anti/Semi Join: the inner side

(Correct me if wrong)

I think this optimization should be done before splitting `degree` into a separate state.

**Comment by BugenZhao** [comment]
Related: #3254
