### ISSUE TITLE
parser: disallow JOIN without CROSS/ON/USING

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#4397]
Postgres does not parse the following statements:

```sql
select * from a join b;
select * from a join b where x=y;
```

Rather, only the following statements are accepted:

```sql
select * from a, b;
select * from a join b on x=y;
select * from a join b using (x);
```

Should we likewise disallow cross-joins that are not comma-separated?

CC: @xiangjinwu

**Comment by xiangjinwu** [comment]
PostgreSQL does allow the following:
```
select * from a cross join b;
select * from a cross join b where x=y;
```

So I guess it would just be a parser update, and would not make binder / planner simpler. Assigning low priority to it.
