### ISSUE TITLE
chore: alway use pluralized names for repeated fields in proto

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#4400]
Ref: [Style Guide | Protocol Buffers](https://developers.google.com/protocol-buffers/docs/style)
Repeated fields
Use pluralized names for repeated fields.

```proto
  repeated string keys = 1;
  ...
  repeated MyMessage accounts = 17;
```

**Comment by BugenZhao** [comment]
FYI, @xxchan renamed all `keys` to `key` in our system in #3700.
