### ISSUE TITLE
SqlSmith Bug hunt: Aggregate of Subquery results in panic

### ISSUE THREAD

**Issue by marvenlee2486** [risingwavelabs/risingwave#4434]
There is 1 out of 512 query that show this error which previous attempt to run 512 test that doesn,t fail. 

[error.txt](https://github.com/singularity-data/risingwave/files/9257514/error.txt)

it is error occur around here.
https://github.com/singularity-data/risingwave/blob/ae0388aeee470bb82b845e14df96220cf51e3d2a/src/frontend/src/expr/subquery.rs#L72
About hashing.

@xiangjinwu, Could you help me with this?

**Comment by jon-chuang** [comment]
Seems hash is just not implemented for subquery. Maybe let's implement all the derive(Hash, PartialEq, Eq) for Subquery and handle detection of subquery not unnested elsewhere.

**Comment by xiangjinwu** [comment]
Similar to https://github.com/singularity-data/risingwave/issues/4404#issuecomment-1204725871, `Hash` was purposely banned (https://github.com/singularity-data/risingwave/pull/1492#discussion_r840184919). It was not meant to be "detection of subquery not unnested", which should return error to user rather than panic.

As for `Clone`, we have a reason (`CTE`) to implement it as well as a way to avoid it (clone plan rather than bound query). For `Hash` and `Eq`, before deriving the traits, let's make sure we are clear on which situations it is needed, and if there are better alternatives.

**Comment by jon-chuang** [comment]
Here is a related query where the error is instead "subquery has not been unnested". The subquery is a nested subquery with an aggregate taking a subquery as input. 

```sql
create table t1 (x int);
select min((select x from t1)) from t1;
```

```
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code: Subquery Subquery { kind: Scalar, query: BoundQuery { body: Select(BoundSelect { distinct: false, select_items: [$1], aliases: [Some("x")], from: Some(BaseTable(BoundBaseTable { name: "t1", table_id: TableId { table_id: 1002 }, table_catalog: TableCatalog { id: TableId { table_id: 1002 }, associated_source_id: Some(TableId { table_id: 1001 }), name: "t1", columns: [ColumnCatalog { column_desc: ColumnDesc { data_type: Int64, column_id: #1000, name: "_row_id", field_descs: [], type_name: "" }, is_hidden: true }, ColumnCatalog { column_desc: ColumnDesc { data_type: Int32, column_id: #1001, name: "x", field_descs: [], type_name: "" }, is_hidden: false }], order_key: [$0 ASC], pk: [0], distribution_key: [0], is_index_on: None, appendonly: false, owner: 1, vnode_mapping: Some([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]), properties: {}, read_pattern_prefix_column: 0 }, table_indexes: [] })), where_clause: None, group_by: [], having: None, schema: Schema { fields: [x:Int32] } }), order: [], limit: None, offset: None, extra_order_exprs: [] } } has not been unnested'
```

However, I am unable to recreate subquery being hashed. 

@marvenlee2486 , is it possible for the tool to output the backtrace alongside the error so we know what codepath is triggering the hash?

**Comment by jon-chuang** [comment]
Anw, we should add the backtrace to the error log in the future. For this one, I've identified it as:

```
41: risingwave_frontend::optimizer::plan_node::logical_project::LogicalProjectBuilder::add_expr
             at ./src/frontend/src/optimizer/plan_node/logical_project.rs:47:28
  42: <risingwave_frontend::optimizer::plan_node::logical_agg::LogicalAggBuilder as risingwave_frontend::expr::expr_rewriter::ExprRewriter>::rewrite_agg_call::{{closure}}
             at ./src/frontend/src/optimizer/plan_node/logical_agg.rs:670:29
```

**Comment by marvenlee2486** [comment]
We can run the output query starting from the definition of tables to the failing query when we compiled `./risedev d`, and then we can get the log file from frontend.

Alternatively, probably can try see if https://github.com/singularity-data/risingwave/issues/4415 are able to do if, if no then stick with the first one

**Comment by xiangjinwu** [comment]
I'd rather not to support subquery expr together with agg. It is far from just enabling `Hash` and `Eq` derivation.

**Comment by jon-chuang** [comment]
@xiangjinwu I think agg of subquery is more or less rewritable as a subquery with agg.

It may not always be true, however, for instance, agg of CTE, where we want to use CTE elsewhere.

I think for CTE case we'd actually be pretty ok to support this, as we never need to unnest correlated vars from CTE, i.e. we can evaluate CTE once (batch) or as mview (stream).

**Comment by liurenjie1024** [comment]
cc @jon-chuang  Are you still looking at this?
