### ISSUE TITLE
Cannot check if a plan node is correctly using its upstream projection without column index in explain string

### ISSUE THREAD

**Issue by richardchien** [risingwavelabs/risingwave#4455]
I'm moving the second issue of #4283 here:

Without the column index, we cannot easily check if a plan node is correctly using its upstream projection. In the following example, for the BatchSimpleAgg after BatchProject, we can't know it's aggregating expression (t.b + 1:Int32) or the output column of BatchProject.

```
dev=> create table t (a varchar, b int);
CREATE_TABLE
dev=> explain verbose select sum(b + 1) from t;
                               QUERY PLAN
-------------------------------------------------------------------------
 BatchSimpleAgg { aggs: [sum(sum((t.b + 1:Int32)))] }
   BatchExchange { order: [], dist: Single }
     BatchSimpleAgg { aggs: [sum((t.b + 1:Int32))] }
       BatchProject { exprs: [(t.b + 1:Int32)] }
         BatchScan { table: t, columns: [t.b], distribution: SomeShard }
(5 rows)
```

**Comment by jon-chuang** [comment]
As pointed out in the other issue, this is not really the most confusing scenario, as it can still be inferred what the columns are. 

Rather, a scenario as follows may be more confusing:

```
LogicalAgg { agg: [sum(a+b)] }
  Project { exprs: [a+b, a, b] }
```

It's ambiguous which columns we are referencing as it's not necessary to alias the project columns, hence their name is derived. (I'm not sure if this will occur in a real query example, perhaps in a CTE or subquery table).

I believe the way to make this less confusing is to always have the positional argument be included alongside any optional column name.

So for instance, the above becomes:
```
LogicalAgg { agg: [sum(a+b:$0)] }
  Project { exprs: [a:$0+b:$1, a:$0, b$1] }
```

But maybe this is quite hard to read, so we should reserve it for `explain verbose`

**Comment by jon-chuang** [comment]
I suppose there is one more potential issue:

```
create table t (a int, b int);
explain verbose select sum(b + a) from t group by a, b;
                                   QUERY PLAN                                   
--------------------------------------------------------------------------------
 BatchExchange { order: [], dist: Single }
   BatchProject { exprs: [sum((t.b + t.a))] }
     BatchHashAgg { group_key: [t.a, t.b], aggs: [sum((t.b + t.a))] }
       BatchExchange { order: [], dist: HashShard(t.a, t.b) }
         BatchProject { exprs: [t.a, t.b, (t.b + t.a)] }
           BatchScan { table: t, columns: [t.a, t.b], distribution: SomeShard }

```

However, note that this is a nonsensical query, all the columns in the agg expression must appear in the group by keys.

**Comment by jon-chuang** [comment]
This one is actually ambiguous:

```sql
explain select a + v2, v1, v2 from (select v1 + v2 as a, 2* v1, v1 as v1, v2 as v2 from t1) join t1 using (v1, v2);
                                  QUERY PLAN                                   
-------------------------------------------------------------------------------
 BatchExchange { order: [], dist: Single }
   BatchProject { exprs: [((t1.v1 + t1.v2) + t1.v2), t1.v1, t1.v2] }
     BatchHashJoin { type: Inner, predicate: t1.v1 = t1.v1 AND t1.v2 = t1.v2 }
       BatchExchange { order: [], dist: HashShard(t1.v1, t1.v2) }
         BatchProject { exprs: [(t1.v1 + t1.v2), t1.v1, t1.v2] }
           BatchScan { table: t1, columns: [v1, v2] }
       BatchExchange { order: [], dist: HashShard(t1.v1, t1.v2) }
         BatchScan { table: t1, columns: [v1, v2] }
```

**Comment by BugenZhao** [comment]
Any ideas on this? cc @chenzl25

**Comment by chenzl25** [comment]
> ```sql
> explain select a + v2, ((t1.v1 + t1.v2) + t1.v2) from (select v1 + v2 as a, v1 as v1, v2 as v2 from t1) join t1 using (v1, v2);
> ```

For this case, join two table with same name is ambiguous. What PostgreSQL do is to prefix each tableScan with different table name. We can try to follow PostgreSQL behavior.

```
tpch=# explain verbose select a + v2, ((t1.v1 + t1.v2) + t1.v2) from (select v1 + v2 as a, v1 as v1, v2 as v2 from t1) a join t1 using (v1, v2);
                                  QUERY PLAN
------------------------------------------------------------------------------
 Merge Join  (cost=317.01..353.47 rows=128 width=8)
   Output: ((t1_1.v1 + t1_1.v2) + t1_1.v2), ((t1.v1 + t1.v2) + t1.v2)
   Merge Cond: ((t1_1.v1 = t1.v1) AND (t1_1.v2 = t1.v2))
   ->  Sort  (cost=158.51..164.16 rows=2260 width=8)
         Output: t1_1.v1, t1_1.v2
         Sort Key: t1_1.v1, t1_1.v2
         ->  Seq Scan on public.t1 t1_1  (cost=0.00..32.60 rows=2260 width=8)
               Output: t1_1.v1, t1_1.v2
   ->  Sort  (cost=158.51..164.16 rows=2260 width=8)
         Output: t1.v1, t1.v2
         Sort Key: t1.v1, t1.v2
         ->  Seq Scan on public.t1  (cost=0.00..32.60 rows=2260 width=8)
               Output: t1.v1, t1.v2
```

**Comment by chenzl25** [comment]
I think Project operator is the source of the ambiguity. Here is the example when I try to make project expression hidden. Is that better?



```sql
create table t (a varchar, b int);
explain verbose select sum(b + 1) from t;

                                   QUERY PLAN
--------------------------------------------------------------------------------
 BatchSimpleAgg { aggs: [sum(sum((t.b + 1:Int32)))] }
   BatchExchange { order: [], dist: Single }
     BatchSimpleAgg { aggs: [sum((t.b + 1:Int32))] }
       BatchProject
         BatchScan { table: t, columns: [t.b], distribution: SomeShard }

```

```sql
create table t (a int, b int);
explain verbose select sum(b + a) from t group by a, b;

                                   QUERY PLAN
--------------------------------------------------------------------------------
 BatchExchange { order: [], dist: Single }
   BatchProject
     BatchHashAgg { group_key: [t.a, t.b], aggs: [sum((t.b + t.a))] }
       BatchExchange { order: [], dist: HashShard(t.a, t.b) }
         BatchProject
           BatchScan { table: t, columns: [t.a, t.b], distribution: SomeShard }
```

**Comment by fuyufjh** [comment]
Propose to output `$1, $2, $3...` for (unnamed) expressions in Project, while keeping the same behavior for other operators and column-mapping-only expressions. 

For example:

![image](https://user-images.githubusercontent.com/10192522/216543074-840ae952-d725-467d-abbd-d97da8997983.png)

**Comment by fuyufjh** [comment]
After some consideration, I think the core problem is how to identify the expressions without aliases. 

1. (current approach) Derive a name that is actually the text representation of the expression.
   - Pros: The semantics is clear
   - Cons: It can become very complicated after multiple Projects or Aggregates
2. (the proposal above) Use the output index of this Project to identify it
   - Pros: The name is short
   - Cons: See the "oops" above

So, how about using a "global"-wide indexes like `$expr1, $expr2, ...` ? Here "global" refers to the scope of the current query, including all the Project operators.

Additionally, if users have named it with aliases, that name would be chosen. In another word, `$expr1, $expr2 ...` is like a default name for expressions.

**Comment by richardchien** [comment]
> * Pros: The semantics is clear

As mentioned by @jon-chuang https://github.com/risingwavelabs/risingwave/issues/4455#issuecomment-1205947690, the text repr of an expr may also be the source of ambiguity.

> So, how about using a "global"-wide indexes like `$expr1, $expr2, ...` ? Here "global" refers to the scope of the current query, including all the Project operators.

Then we also need to print the definitions of these expressions? I propose using some kind of naming convention to name each Project and each output of a Project, e.g. `$foo.1` for the first output of Project `foo` (assigned randomly).

**Comment by fuyufjh** [comment]
> Then we also need to print the definitions of these expressions?

Yes. It need to be denoted in the `Project` plan node e.g. `a + b AS $expr1`. 

> I propose using some kind of naming convention to name each Project and each output of a Project, e.g. `$foo.1` for the first output of Project `foo` (assigned randomly, may be from `a` to `z` or some rarely used words).

Agree. This can be an alternative. But I slightly prefer my way.
