### ISSUE TITLE
Replace serde-protobuf and rust-protobuf with prost?

### ISSUE THREAD

**Issue by ice1000** [risingwavelabs/risingwave#4456]
We're using 3 different protobuf crates at the very same time (🤯). Maybe we want to only use prost, as it's supported by:

+ https://github.com/tikv/grpc-rs
+ https://github.com/hyperium/tonic, the successor of tower-grpc

Plus, the code generated by prost is more friendly to move semantics.

P.S. PingCAP tried to migrate from rust-protobuf to prost in 2019, but the runtime performance didn't change much (*). However, there are still good reasons to migrate:

0. Less dependencies (faster build time)
1. Rust-protobuf generates bloated code that slows down compilation and takes lots of time to optimize (even faster build time)

*: I blame the migration strategy -- we wrapped the prost generated code with a rust-protobuf-like layer, and that's probably slowing down everything.

**Comment by skyzh** [comment]
I believe the dependency can be removed as long as we go through the protobuf decoding thing in connectors. cc @tabVersion may take a look if you have time :)

**Comment by BugenZhao** [comment]
Do we really use `rust-protobuf` in gRPC? I think it should be replaced with `prost` long ago. 🥵

**Comment by ice1000** [comment]
> Do we really use `rust-protobuf` in gRPC? I think it should have been replaced with `prost` long ago. 🥵

No. The dependency is only introduced in tikv's rust-prometheus (as an optional feature, which we enabled) and risingwave-source. I think we can supersede the usage in risingwave-source.

**Comment by ice1000** [comment]
Probably impossible

**Comment by skyzh** [comment]
There's https://docs.rs/prost-reflect/latest/prost_reflect/index.html, probably someone is working on this.

**Comment by tabVersion** [comment]
> There's https://docs.rs/prost-reflect/latest/prost_reflect/index.html, probably someone is working on this.

I am looking into this and I will take the issue

**Comment by ice1000** [comment]
So "probably impossible" is probably impossible then
