### ISSUE TITLE
RFC: Pull-based compactor task status

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#4457]
## Background

We want to periodically check status of compactor task. This is to facilitate recovery from failed tasks. 

Examples of failed tasks:
- compactor fails and recovers, but has no memory of in-progress tasks, so push-based reporting fails (https://github.com/singularity-data/risingwave/issues/4379)
- task fails, and compactor does not recover. (https://github.com/singularity-data/risingwave/issues/4365)
  - In this case we can speed up meta's rescheduling by returning task status - failed.

## Design

We define making progress as the increase in count of output SST or output SST blocks. The task can update its progress via channel to compactor task monitoring service. The meta service will ask each compactor's task monitoring service on progress of tasks. If no progress is being made, then meta will send cancel task request to compactor (compactor keeps a table of running task handles) and reschedule the task.

In more specific terms, we will get rid of a push-based reporting of task progress in compactor to pull-based reporting initiated by meta.

## Future Optimizations
NIL

## Q&A
1. Not sure if the scope includes heartbeat for compactor. (I guess there is already heartbeat and recovery for failed compactor, so no).

CC: @Li0k @zwang28

**Comment by Little-Wallace** [comment]
Streaming RPC is better. We do not need pull-based

**Comment by zwang28** [comment]
> Not sure if the scope includes heartbeat for compactor. (I guess there is already heartbeat and recovery for failed compactor, so no).

There is already heartbeat for compactor just like other cluster node. Alternatively we may piggyback task status via heartbeat RPC, like https://github.com/singularity-data/risingwave/pull/4435.

**Comment by jon-chuang** [comment]
> Streaming RPC is better. We do not need pull-based

Actually, I see no difference for pull-based v.s. stream if using gRPC. From what I know, gRPC would use the same open channel anyway.

I don't think the compactor needs to see meta have user-side acknowledgement that it has received the heartbeat/status update. The TCP already ensures reliable delivery.

**Comment by jon-chuang** [comment]
> Alternatively we may piggyback task status via heartbeat RPC, like https://github.com/singularity-data/risingwave/pull/4435.

Possibly. Maybe we should keep them separate first, as the granularity is different (per-task v.s. per-compactor), compared to linked PR, which is all per-worker.

**Comment by jon-chuang** [comment]
On second thought, we can just have push-based reporting. It does the job, and we also only push based report for task error or success (status), but not for task progress.
