### ISSUE TITLE
refactor: use a non-empty vector/slice type

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#4469]
By the way, I find many sakes for a non-empty immutable vector or slices in our system these days, like #4165. cc @st1page 

One candidate:
https://github.com/tesuji/rust-oom

_Originally posted by @BugenZhao in https://github.com/singularity-data/risingwave/issues/4466#issuecomment-1206187747_

**Comment by skyzh** [comment]
I don't think it's necessary to do this in type. Just assert vector not empty is enough?

**Comment by xxchan** [comment]
The problem is we don't necessarity know where to assert, so type-driven design can be safer.
