### ISSUE TITLE
refactor(meta): reduce the locks `MetaSnapshot` needs

### ISSUE THREAD

**Issue by HuaHuaY** [risingwavelabs/risingwave#4498]
When `ObserverManager` calls `subscribe` RPC, meta will send a `MetaSnapshot` and need to acquire different types of locks. For example, when a frontend calls this RPC, meta will acquire lock of `CatalogManagerCore`, `ClusterManagerCore` and `UserManagerInner` one by one. It is expected that meta will acquire more locks in the future. 
Acquiring too many locks has the risk of deadlock, and it will be inconvenient to write code in the future. We plan to merge multiple managers with low using frequency together, may named "MetaManager", and use a shared lock.

**Comment by BugenZhao** [comment]
`MetaManager` sounds like it includes all the managers in the meta service. I suggest naming it something else. 🥵

**Comment by fuyufjh** [comment]
Any updates?

**Comment by HuaHuaY** [comment]
We are discussing how to separate out the things related to actor in the fragment manager. We will solve this issue after refactoring the fragment manager.
