### ISSUE TITLE
sqlsmith bug hunt: supported `sum(interval)`

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#4508]
**Describe the bug**

Invalid agg should be caught in frontend.

**To Reproduce**
```
create table t (v int);
create materialized view m1 as select sum(INTERVAL '938796') as e from t;
```

output:
```
ERROR:  QueryError: internal error: transport error.
```

`compute.log`
```
thread 'tokio-runtime-worker' panicked at 'streaming agg state not implemented: Sum Interval Interval', src/stream/src/executor/aggregation/mod.rs:161:13
```

**Expected behavior**

Support `sum(interval)`. It should be similar to `sum(decimal)` and `sum(double)`.

**Additional context**

**Comment by fuyufjh** [comment]
Please fix the frontend

**Comment by TennyZhuang** [comment]
`sum(interval)` also failed on batch, will fix in the next PR.
