### ISSUE TITLE
bug(meta/hummock): `CompactionRequestChannel::try_send` needs to propagate error in order for task completion/failure compaction group rescheduling to be reliable

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#4511]
`CompactionRequestChannel::try_send` needs to propagate error in order for task completion/failure compaction group rescheduling to be reliable
 
 Change return type to `Result<bool>`
 
 See: https://github.com/singularity-data/risingwave/issues/4379#issuecomment-1208772404

**Comment by zwang28** [comment]
Closed by https://github.com/risingwavelabs/risingwave/pull/4496
