### ISSUE TITLE
Tracking: test failover on deterministic simulator

### ISSUE THREAD

**Issue by wangrunji0408** [risingwavelabs/risingwave#4527]
## Commands

```sh
./risedev sslt -- --kill-compute "e2e_test/streaming/**/*.slt"
./risedev sslt -- --kill-frontend "e2e_test/streaming/**/*.slt"
./risedev sslt -- --kill-meta "e2e_test/streaming/**/*.slt"
```

## PRs

- #4843
- #4969 
- #5077
- #5300

## Bugs

- Killing compute node
  - [x] #4782
  - [x] #4875
  - [x] #6093 
- Killing meta node
  - [x] #5206
  - [x] #5244
  - [x] #5726
- Killing frontend node
  - [x] #5543
- Killing compute/meta/frontend node
  - [x] #5755
  - [x] #6031

**Comment by BowenXiao1999** [comment]
I'm interested in how to write failover injection code to test. 

Working on the batch scheduler that should cancel other tasks when one task fail.

**Comment by wangrunji0408** [comment]
Madsim provides control APIs to kill/restart/pause/resume a node.

The code may look like this:

```rust
// start a compute node
let compute_node = handle
    .create_node()
    .name("compute-1")
    .init(move || async move {
        let opts = risingwave_compute::ComputeNodeOpts::parse_from([
            "compute-node",
            "--host",
            "0.0.0.0:5688",
            ...
        ]);
        risingwave_compute::start(opts).await
    })
    .build()
    .id();

// a background task to inject failures
tokio::task::spawn_local(async move {
    let handle = madsim::runtime::Handle::current();

    tokio::time::sleep(std::time::Duration::from_secs(5)).await;
    log::warn!("kill compute-1");
    handle.kill(compute_node);

    tokio::time::sleep(std::time::Duration::from_secs(10)).await;
    log::warn!("start compute-1");
    handle.restart(compute_node);
});
```

**Comment by twocode** [comment]
> Madsim provides control APIs to kill/restart/pause/resume a node.

Does pause/resume call any meta APIs underneath?

**Comment by wangrunji0408** [comment]
> Does pause/resume call any meta APIs underneath?

No. It will just stop running all async tasks of a node. The meta will lose heartbeat if we pause a compute node.

**Comment by jon-chuang** [comment]
Note that pause/resume is not sufficient to test all desired behaviour. We may want the compute node to continue running while unable to connect to meta node etc. i.e. network partition. Although, its argued that we should not worry about network partition since we are running on AWS internal network.

**Comment by wangrunji0408** [comment]
Don't worry. Our simulator supports network partition too!

**Comment by wangrunji0408** [comment]
Since we have required the recovery test to pass on CI, this tracking issue can be closed for now. Thanks @yezizp2012 and other guys for their remarkable work!
