### ISSUE TITLE
compaction: limit ongoing compaction task per compactor

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#4561]
**Is your feature request related to a problem? Please describe.**
When running the benchmark described in #4365 with 3-cn 1-compactor setting, I noticed that there can be more than 100 compaction task assigned to a single compactor. This can put excessive stress on compactor with no benefits since the compactor may get stuck or die causing all running compaction task to fail.

**Describe the solution you'd like**
 We should stop assigning task to an already overloaded compactor. A simple fix is to limit the number of ongoing compaction task on a single compactor node.

**Follow-up**
- In addition to number of ongoing tasks, use more granular indicators for compactor load.
- Compactor scaling: decide when to scale out/in compactor nodes

**Comment by jon-chuang** [comment]
Hi @hzxa21 , I wrote an issue proposing an abstraction over policies for task assignment/acceptance so we can tweak it in the future: https://github.com/singularity-data/risingwave/issues/4510

It proposes a compactor-side acceptance policy. 

Alternatively, the task acceptance decision can be in meta if we also send resource usage data along with heartbeats. I think the latter is preferable as it facilitates scale out.

I'll write an RFC proposing resource reporting, scale out/in policy, and meta-side task-assignment decision. 

There are some decisions to be made on granularity of reporting. I think we can stick with mem & cpu utilization as well as num of num_tasks and num_total_splits, and maybe also memory_usage_estimate (the latter two could be more indicative of load than num_tasks alone).

**Comment by zwang28** [comment]
https://github.com/risingwavelabs/risingwave/pull/4633 has provided a basic solution.
Track "Follow-up" in dedicated issue.
