### ISSUE TITLE
frontend: fragmenter test for `StreamFragmentGraph`

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#4610]
As we're going to refactor the fragmenter, it would be better if we could first introduce a fragmenter test like the planner test. So it'll be easier for us to see whether there're behavior changes or regressions.

The test content should be `StreamFragmentGraph`, that is, what we send to the meta service when creating materialized views.

https://github.com/singularity-data/risingwave/blob/c11176e78294e0d27b6d35272f4a9ccad4afb8d1/proto/stream_plan.proto#L444-L476

cc @st1page @ice1000

**Comment by ice1000** [comment]
I'll try but I don't guarantee a time. Feel free to take over

**Comment by skyzh** [comment]
For planner test, please refer to https://github.com/risingwavelabs/risingwave/tree/main/src/frontend/test_runner, where we use yaml files to do regression test on plans. We can do the same for fragmenter test.

**Comment by st1page** [comment]
https://github.com/risingwavelabs/risingwave/pull/5426
