### ISSUE TITLE
fragmenter: remove 1v1 exchange rule & move the optimization to compute node

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#4614]
We've introduced the "1v1 exchange rewrite" in #1745 that split multiple stateful operators into different fragments, then connect them with `no-shuffle` exchange. However, this breaks the assumption that _every fragment can be scheduled or scaled independently_: if we want to scale out one of the fragments, either we need to resolve the related upstream/downstream fragment and scale them alongside, or we need to replace all dispatchers with hash dispatchers. This lead to extra complexity for the meta service and the cloud manager.

Considering that our purpose is to increase the I/O concurrency, and the benchmark show that the compute parallelism is good enough, I suggest removing this rule(rewrite) from the fragmenter and letting the actor in compute nodes decide whether to do this optimization: multiple stateful executors are still in a single actor/fragment logically, while the actor may `join` multiple `ActorStage` to achieve I/O concurrency.

Any ideas are welcome. cc @skyzh @st1page @fuyufjh @shanicky  

Update:
A more detailed doc describing the issue: https://singularity-data.quip.com/GU2ZAhJdBhCJ/The-Future-of-No-shuffle-Exchange

**Comment by fuyufjh** [comment]
+1

**Comment by BowenXiao1999** [comment]
Any doc for `ActorStage`? This batch-streaming naming looks very interesting.

**Comment by skyzh** [comment]
dup w/ https://github.com/singularity-data/risingwave/issues/3607, I've proposed it long before!

**Comment by skyzh** [comment]
+1 No shuffle exchange looks bad when there's scale-in / scale-out. If we don't want to handle this as a special case when scale, this proposal looks good.

**Comment by skyzh** [comment]
may also close https://github.com/singularity-data/risingwave/issues/3607

**Comment by BugenZhao** [comment]
Closed via #5449.
