### ISSUE TITLE
Support `DISTINCT ON` for window deduplication

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#4617]
**Is your feature request related to a problem? Please describe.**

Window deduplication is a common demand in streaming processing. I found that PostgreSQL supports [DISTINCT ON](https://www.postgresql.org/docs/current/sql-select.html#SQL-DISTINCT) clause, which can meet the requirement.

**Additional context**

Currently, we support rewriting the `SELECT DISTINCT` to aggregation in frontend, and it's same for `DISTINCT ON`, except that we may need to select more columns in the aggregation.

We should rewrite the following query:

```sql
SELECT DISTINCT ON(v1) v2, v3 FROM t1;
```

to:

```sql
SELECT v2, v3 FROM t1 GROUP BY v1;
```

The latter query is invalid in pg:

```
ERROR:  column "t.v2" must appear in the GROUP BY clause or be used in an aggregate function
```

It's because `v2` and `v3` in the resultset is unpredictable, but at least, they should appear in one row.

We can add a special aggregate function for this, e.g. `first_value`.

```sql
SELECT first_value(v2), first_value(v3) FROM t1 GROUP BY v1;
```

The trivial `first_value` implementation can ensure that `v2`, `v3` belong to one row, except that we introduce some special designs, e.g. split the columns in aggregate operator and concat them later.

If there is an `ORDER BY` clause match the selection list, the result should be predictable. For the case, we can rewrite the query to grouping top-n, but we can forbid the clause first.

**Comment by fuyufjh** [comment]
> We should rewrite the following query:
> 
>     SELECT DISTINCT ON(v1), v3, v4 FROM t1;
> to:
>
>     SELECT v1, v2, v3 GROUP BY v1, v2;

Should it be 

```
SELECT v1, v3, v4 GROUP BY v1;
```

?

**Comment by fuyufjh** [comment]
similar to first value in flink?

**Comment by TennyZhuang** [comment]
@wangrunji0408 will work on this

**Comment by soundOfDestiny** [comment]
link #6593 for reference

**Comment by soundOfDestiny** [comment]
PG standard:
> SELECT DISTINCT ON ( expression [, ...] ) keeps only the first row of each set of rows where the given expressions evaluate to equal. The DISTINCT ON expressions are interpreted using the same rules as for ORDER BY (see above). Note that the “first row” of each set is unpredictable unless ORDER BY is used to ensure that the desired row appears first. For example:

SELECT DISTINCT ON (location) location, time, report
    FROM weather_reports
    ORDER BY location, time DESC;
retrieves the most recent weather report for each location. But if we had not used ORDER BY to force descending order of time values for each location, we'd have gotten a report from an unpredictable time for each location.

The DISTINCT ON expression(s) must match the leftmost ORDER BY expression(s). The ORDER BY clause will normally contain additional expression(s) that determine the desired precedence of rows within each DISTINCT ON group.
