### ISSUE TITLE
bug: must reuse SourceExecutor inside a streaming job

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#4618]
**Describe the bug**

For different streaming jobs aka. `create materialized view`, it's reasonable to let them create different SourceExecutors for one source.

However, things get different inside a streaming job: the optimizer implicitly assumes the data of multiple SourceExecutors are identical, but in fact, all data sources do not guarantee this. This may cause some SQL logical errors or event assertion failures.

**To Reproduce**

Hard to reproduce

**Expected behavior**

A streaming job should use identical SourceExecutors for one source. As a result, the plan tree will become DAG.

**Comment by skyzh** [comment]
may depend on fragmenter v2 :)

**Comment by st1page** [comment]
so if two or more stream jobs(`create MV`) are associated with one source, should we maintain the consistency?
e.g.
```
create source s;
create materialize A as select max(v) as max_v, k1 from s;
create materialize B as select count(distinct k2) as max_v, k1 from s;
create materialize C as select 
```

**Comment by fuyufjh** [comment]
> so if two or more stream jobs(`create MV`) are associated with one source, should we maintain the consistency?
> 
> e.g.
> 
> ```
> 
> create source s;
> 
> create materialize A as select max(v) as max_v, k1 from s;
> 
> create materialize B as select count(distinct k2) as uv, k1 from s;
> 
> create materialize C as select max_v, uv, k1 from A join B where A.k1 = B.k1
> 
> ```

I think not, because it's difficult for non-materialized source

**Comment by st1page** [comment]
blocking on https://github.com/risingwavelabs/risingwave/issues/3684 because we need express DAG in plan.

**Comment by chenzl25** [comment]
We already have supported the share operator now and we have used it to express the share source DAG.
