### ISSUE TITLE
bug: migrate from `from_proto_bytes` to value encoding (at least for struct/list)

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#4672]
`from_proto_bytes` is not well maintained and is majorly used to encode Literal data in proto, but our `List` and `Struct` data types use them as their value encoding, which may cause some bugs.

Furthermore, we may consider removing `from_proto_bytes` completely because it's so error-prone。

**Comment by fuyufjh** [comment]
Any updates?

**Comment by waruto210** [comment]
removed for struct/list by #5880

**Comment by waruto210** [comment]
done by #5961
