### ISSUE TITLE
feat: support group by output column ordinal or name

### ISSUE THREAD

**Issue by wzzzzd** [risingwavelabs/risingwave#4681]
**Describe the bug**
```
dev=> create table t (a int, b int);
CREATE_TABLE
dev=> INSERT INTO t VALUES (11, 22), (12, 21), (13, 22);
INSERT 0 3
dev=> select b % 2 as f, sum(a) from t group by f order by b % 2;
ERROR:  QueryError: Item not found: Invalid column: f.
```

**To Reproduce**
As above.

**Expected behavior**
```
postgres=# SELECT b % 2 AS f, SUM(a) FROM t GROUP BY f ORDER BY b % 2;
 f | sum 
---+-----
 0 |  24
 1 |  12
(2 rows)
```

**Additional context**

**Comment by xiangjinwu** [comment]
This is clearly documented as unsupported.

In [PostgreSQL](https://www.postgresql.org/docs/current/sql-select.html#SQL-GROUPBY):
> An expression used inside a grouping_element can be an input column name, or the name or ordinal number of an output column (SELECT list item), or an arbitrary expression formed from input-column values. In case of ambiguity, a GROUP BY name will be interpreted as an input-column name rather than an output column name.

In [RisingWave](https://www.risingwave.dev/docs/latest/sql-select/):
> grouping_expression Values can be:
> - Input column names
> - Input column expressions without subqueries or correlated columns

Note that PostgreSQL supports 3 different cases and we only support the first and third. But we can definitely add the support.
