### ISSUE TITLE
frontend: multiple frontends in e2e tests

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#4720]
We haven't tested our system with multiple frontends. An easy way is to start a load-balancing service for multiple frontends in e2e tests.

From @skyzh:

> IIRC, a session must complete in a single TCP connection. Simply port the parallel e2e with multiple frontends seems no problem.

If we want to run a single test case over only one connection, then it seems fine. To achieve this, we can allow specifying multiple Postgres URLs in sqllogictest command line args.

**Comment by skyzh** [comment]
(1) We'll need to establish multiple connections to different RisingWave instances, which seems a little bit weird.
(2) Without session-level consistency, commands like flush will act strangely.

**Comment by BugenZhao** [comment]
> (1) We'll need to establish multiple connections to different RisingWave instances, which seems a little bit weird.

Why different RisingWave instances? 👀

> (2) Without session-level consistency, commands like flush will act strangely.

IIRC, a session must complete in a single TCP connection. Simply port the parallel e2e with multiple frontends seems no problem.

**Comment by skyzh** [comment]
> Why different RisingWave instances?

I mean different frontend instances.

> IIRC, a session must complete in a single TCP connection. Simply port the parallel e2e with multiple frontends seems no problem.

If we want to run a single test case over only one connection, then it seems fine. To achieve this, we can allow specifying multiple Postgres URLs in sqllogictest command line.

**Comment by skyzh** [comment]
Sorry to mistakenly close the issue 🤣 Cmd+Ctrl now by default triggers close with comment instead of comment.

**Comment by BugenZhao** [comment]
> To achieve this, we can allow specifying multiple Postgres URLs in sqllogictest command line args.

Makes sense. 🥵

**Comment by wangrunji0408** [comment]
By the way, this feature has already implemented in deterministic testing. #4675

**Comment by BugenZhao** [comment]
> By the way, this feature has already implemented in deterministic testing. #4675

Do we enable this in CI?

**Comment by wangrunji0408** [comment]
Not yet. NTFS

**Comment by BugenZhao** [comment]
Closed via #4795.
