### ISSUE TITLE
Sqlsmith: Enable generate agg with distinct.

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#4737]
#4735 shows that the random queries generated by Sqlsmith do not cover the case of `STRING_AGG(DISTINCT s, ',')`.

Modify `Sqlsmith` to enable this kind of query, i.e. `aggregation with distinct`

**Comment by skyzh** [comment]
Please describe the steps for solving this issue in detail before marking it as "good first issue".
