### ISSUE TITLE
`NULLS {FIRST | LAST}` is recognized by frontend, but ignored by backend for now

### ISSUE THREAD

**Issue by richardchien** [risingwavelabs/risingwave#4743]
We may consider implementing `NULLS {FIRST | LAST}` after we resolve #4272.

**Comment by fuyufjh** [comment]
Shall we throw an error now?

**Comment by fuyufjh** [comment]
cc. @TennyZhuang

**Comment by richardchien** [comment]
> Shall we throw an error now?

I'm going to implement this feature soon.
