### ISSUE TITLE
feat(storage): remove FilterKeyExtractor trait for MultiFilterKeyExtractor

### ISSUE THREAD

**Issue by Li0k** [risingwavelabs/risingwave#4747]
**Is your feature request related to a problem? Please describe.**
Currently, `MultiFilterKeyExtractor` is a struct that impletement `FilterKeyExtractor` trait. We can provide a nested structure with this implementation, but this is not safe. We want `FilterKeyExtractor` to be stateless, but now `MultiFilterKeyExtractor` needs to hold mutable self in order to maintain state. (For borrow checker, we use need a `Mutex` even if it wont be competing). 

(https://github.com/singularity-data/risingwave/blob/main/src/storage/hummock_sdk/src/filter_key_extractor.rs)
simple conclusion:
1. `FilterKeyExtractor` to be stateless
2. `FilterKeyExtractor` no needs to hold mutable self for maintaining state

**Describe the solution you'd like**
1. use a new struct `FilterKeyExtractorContext` to replace `MultiFilterKeyExtractor` which maintain state. 
2. remove MultiFilterKeyExtractor for avoiding nested structure that it's uncontrollable
3. cached the `last_filter_key_extractor_state` for query optimization.
4. use separate `FilterKeyExtractorContext` for every compaction task split (Copy)

**Comment by ClSlaid** [comment]
May I take a look? I may be able to submit a PR next week...👀 Won't be fast...

**Comment by Li0k** [comment]
> May I take a look? I may be able to submit a PR next week...👀 Won't be fast...

Thanks, you can self-assign

**Comment by ClSlaid** [comment]
> 1. FilterKeyExtractor to be stateless
> 2. FilterKeyExtractor no needs to hold mutable self for maintaining state

wait...? a stateless structure but need to maintain state?🤯
