### ISSUE TITLE
style: should not display same error for mutiple times

### ISSUE THREAD

**Issue by BowenXiao1999** [risingwavelabs/risingwave#4748]
Now pgwire will display error in https://github.com/singularity-data/risingwave-dev/blob/6161ccb2828b2d5727c74bee31cf708ecb273b38/src/utils/pgwire/src/pg_protocol.rs.

So now sometimes same error message will be displayed mutiple times.  (Some error is traced in kernel, and forward the msg up to pgwire, then pgwire trace it again).

if we do not trace in pgwire, some error may not be printed to log.... Not sure how to do it correctly.

**Comment by xxchan** [comment]
What about ONLY tracing in pgwire?

**Comment by BowenXiao1999** [comment]
I think we do not need to display error in pgwire.

Have removed some in #5942  so close this
