### ISSUE TITLE
bug: panic when CorrelatedInputRef used in AggCall filter or order_by

### ISSUE THREAD

**Issue by nanderstabel** [risingwavelabs/risingwave#4762]
**Describe the bug**
When STRING_AGG in inner subquery refers to a table alias (`t`) from the outer query the following panic occurs in frontend:
`thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code: CorrelatedInputRef CorrelatedInputRef { index: 1, correlated_id: 0 } has not been decorrelated', src/frontend/src/expr/correlated_input_ref.rs:84:9`

**To Reproduce**
```
dev=> CREATE TABLE strings(v1 VARCHAR);
CREATE_TABLE
dev=> INSERT INTO strings VALUES ('a'), ('b'), ('c');
INSERT 0 3
dev=> SELECT (SELECT STRING_AGG(v1, ',' ORDER BY t.v1) FROM strings) FROM strings AS t;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

**Expected behavior**
```
dev=> SELECT (SELECT STRING_AGG(v1, ',' ORDER BY t.v1) FROM strings) FROM strings AS t;
 ?column?
------------
 a,b,c
 a,b,c
 a,b,c
(3 rows)
```

**Comment by xiangjinwu** [comment]
Potential cause:

`AggCall` as an expr variant has been enriched to contain more subexprs beyond `inputs`, such as `order_by` and `filter`.
https://github.com/singularity-data/risingwave/blob/0dacee5ae96fb3d97a5e7b4db16d900e0a002381/src/frontend/src/expr/agg_call.rs#L63-L70

However, the default implementation of visitor (and rewriter, mutator, etc) are only handling `inputs` recursively.
https://github.com/singularity-data/risingwave/blob/0dacee5ae96fb3d97a5e7b4db16d900e0a002381/src/frontend/src/expr/expr_visitor.rs#L47-L54

Besides adding these 2 fields in default implementation blindly, it is better to go thru all existing visitor usages to check whether `order_by` or `fields` needs special treatment. For example:
https://github.com/singularity-data/risingwave/blob/0dacee5ae96fb3d97a5e7b4db16d900e0a002381/src/frontend/src/optimizer/plan_node/logical_agg.rs#L748-L750

**Comment by xiangjinwu** [comment]
Update: usage in `order_by` has been fixed, but usage in `filter` needs more fixes.

**Comment by kwannoel** [comment]
We track this issue https://github.com/risingwavelabs/risingwave/issues/7574 here as well.
So labelling with `found-by-sqlsmith` to see status of bugs.
