### ISSUE TITLE
bug: `risedev ctl profile` doesn't work on Linux server

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#4765]
**Describe the bug**

When I run `risedev ctl profile` on my linux (Ubuntu) EC2 machine, it cannot produce a correct results.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/10192522/185658538-9a4c4507-345c-41d8-8599-96e0c9e08b82.png">

PS. 

1. The RisingWave instance is deployed with `risedev d full` so it's **not** running in Docker
2. `flamegraph-rs` works well.

Additionally, we should also profile compactor as well as the meta nodes.

**To Reproduce**

May try it an EC2 machine.

**Expected behavior**

Expect to work.

**Additional context**

**Comment by fuyufjh** [comment]
maybe related https://github.com/tikv/pprof-rs/issues/157

**Comment by mornyx** [comment]
Should be resolved by https://github.com/tikv/pprof-rs/pull/172.
