### ISSUE TITLE
batch: Use exchange to replace `UnionExecutor`

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#4766]
I think `HashAggExecutor` is good enough, we don't need to implement the dedup logic again. BTW, union all is some kind of exchange. I think we even can use a special exchange executor to replace `UnionExecutor`.

_Originally posted by @chenzl25 in https://github.com/singularity-data/risingwave/pull/4761#discussion_r950699302_

**Comment by st1page** [comment]
for batch execution maybe it is ok, but the stream Union executor might need to add a column to make sure the stream_key is unique.

**Comment by yinfredyue** [comment]
Is anyone working on this? If not, I can give it a try.

One question about #4761, what's the difference between `logical_union` and `batch_union`? More generally, what's the difference between a logical plan node and a batch plan node?

**Comment by st1page** [comment]
> Is anyone working on this? If not, I can give it a try.
> 
> One question about #4761, what's the difference between `logical_union` and `batch_union`? More generally, what's the difference between a logical plan node and a batch plan node?

Each logical plan node corresponds to a kind of logical operator of Relational Algebra, which input some relations(tables) and outputs a relation. And a batch plan node corresponds to a kind of batch executor. 
And I think this issue's description is not clear enough. in our system, the `exchange` node actually has no meaning as a logical relational operator, which only merges records from different pararellism. I agree it can be some kind of exchange node in the execution backend, but this implementation should not be in the optimizer as a plan node.

**Comment by yinfredyue** [comment]
Alright, I guess this issue is not for me... Still thanks!
