### ISSUE TITLE
bug(recovery): panicked at 'sender not exist' in compute node

### ISSUE THREAD

**Issue by wangrunji0408** [risingwavelabs/risingwave#4782]
**Describe the bug**

After killing a compute node and performing recovery, another compute node panicked in next query.
```
panicked at 'sender for actor 21 does not exist', ./stream/src/task/barrier_manager.rs:150:36
```

**To Reproduce**

This issue was found on the simulator. Checkout eb23ae2 and run:
```
MADSIM_TEST_SEED=1 RUST_LOG=info ./risedev sslt -- './e2e_test/streaming/basic.slt'
```

[full log](https://github.com/singularity-data/risingwave/files/9392087/1.log)

What's happening here is:
- start a meta, a frontend and 3 compute nodes
- client `create table t1 (v1 int, v2 int, v3 int);` and succeed
- kill compute-1
- compute-2&3 panicked at 'upstream closed unexpectedly' and then restarted immediately
- wait for 2s
- restart compute-1
- wait for 2s
- client `create table t2 (v1 int, v2 int, v3 int);` ...
- compute-3 panicked at 'sender for actor 21 does not exist'

**Expected behavior**
After recovery, the following query should succeed without panic.

**Additional context**

**Comment by wangrunji0408** [comment]
It turns out that the waiting time for recovery (2s) is not long enough. The test passes if we increase the [waiting time](https://github.com/singularity-data/risingwave/blob/eb23ae236aa512277c1f3a66da5334c7e53f23c6/src/tests/simulation/src/main.rs#L165) to 20s, or decrease the [recovery retry interval](https://github.com/singularity-data/risingwave/blob/eb23ae236aa512277c1f3a66da5334c7e53f23c6/src/meta/src/barrier/recovery.rs#L53) to 1s.

Thanks @yezizp2012 for debugging!

**Comment by jon-chuang** [comment]
so this issue can be closed?

**Comment by wangrunji0408** [comment]
Although this issue can be avoided by increasing the waiting time, I think at least the panic should never happen.
This problem may be solved by blocking the query or returning an error during the recovery.
So I prefer to keep this issue open until the panic is fixed?

**Comment by fuyufjh** [comment]
@wangrunji0408 Could you please reopen another issue?
