### ISSUE TITLE
discussion: shall we put into separate folders the test cases imported from other DBs

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#4784]
As discussed with @sumittal, 

it is likely that we will import test cases from multiple DBs and the test file name may conflict with each other.

And if other DBs have updates for their test cases, it is easier for us to recognize the file we need to change.

**Comment by liurenjie1024** [comment]
LGTM

**Comment by nanderstabel** [comment]
Would something like this suffice? So simply a folder per DB per test-topic.
```
.
└── e2e_test/
    ├── batch/
    │   ├── aggregate/
    │   │   ├── risingwave
    │   │   ├── duckdb
    │   │   └── ...
    │   └── basic/
    │       └── ...
    ├── stream
    └── ...
```

**Comment by BugenZhao** [comment]
Do we also need to put their LICENSE file?

**Comment by lmatz** [comment]
> Do we also need to put their LICENSE file?

Currently, we show the credits in the header of each test file:
> Copied from https://github.com/duckdb/duckdb (MIT licensed).
 Copyright 2018-2022 Stichting DuckDB Foundation 



Is a LICENSE file needed? Open source masters, please help

**Comment by lmatz** [comment]
> Would something like this suffice? So simply a folder per DB per test-topic.
> 
> ```
> .
> └── e2e_test/
>     ├── batch/
>     │   ├── aggregate/
>     │   │   ├── risingwave
>     │   │   ├── duckdb
>     │   │   └── ...
>     │   └── basic/
>     │       └── ...
>     ├── stream
>     └── ...
> ```

slightly worried that the test cases from other DBs may be not all organized in this way, i.e. `aggregate`, `join`, `...`
or we put it into a higher-level separate folder, i.e. moving all the existing RisingWave tests into a new huge folder `risingwave`, and create others `duckdb`, `postgres`, `cockroach`.....
but I have no strong opinion on this, and honestly I haven't checked a lot to verify whether it is really the case

**Comment by lmatz** [comment]
The folder is reorganized already, but may add a NOTICE file in the future.
