### ISSUE TITLE
Discussion: How should FE display the execution error? 

### ISSUE THREAD

**Issue by BowenXiao1999** [risingwavelabs/risingwave#4811]
Now FE scheduler do not correctly display the execution error, see

https://github.com/singularity-data/risingwave/blob/a50393a30b7830d392b0092af460871c8e9cede1/src/frontend/src/scheduler/distributed/stage.rs#L393

Should frontend aware of the detail reason like (ExprError, Divde by Zero error etc)? If yes, maybe we should consider how to encode this into proto.

cc @liurenjie1024. May relates to #3908

**Comment by liurenjie1024** [comment]
Currently we don't do fault tolerant of query execution, so I think frontend doesn't need to know the exact error kind, and just the error message.

**Comment by fuyufjh** [comment]
+1 for error message only, because it seems difficult to define all kinds of errors.

**Comment by fuyufjh** [comment]
cc. @TennyZhuang

**Comment by BowenXiao1999** [comment]
Now the solution is we wrap the execution err msg in string into a Err struct returned by streaming GRPC API. So when there is an execution failure in CN tasks, FE scheduler will imediately know and return Err.

https://github.com/risingwavelabs/risingwave/blob/6f1764f2bc913aae8c4c041654f9b2f59909f59f/src/frontend/src/scheduler/distributed/stage.rs#L374

https://github.com/risingwavelabs/risingwave/blob/6f1764f2bc913aae8c4c041654f9b2f59909f59f/proto/task_service.proto#L75

Now FE should be able to get the execution failure so I think we can close this issue now.
