### ISSUE TITLE
investigate the cause of the slowly-growing memory usage

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#4819]
Actually I am trying to figure out the cause of the slowly-growing memory usage when running NexMark Q5.

![image](https://user-images.githubusercontent.com/10192522/186102039-c2989d16-ff4e-4ed1-a4f4-6de33faa6db7.png)

I am considering a possibility: the Join operator only counts the number of JoinEntry (instead of the #rows inside of it), so it’s possible to continue to grow even if hits the limit

https://singularity-data.slack.com/archives/C034TRPKN1F/p1661231974375339

**Comment by yuhao-su** [comment]
Yes, I will add metrics later to show the total row number

**Comment by BugenZhao** [comment]
We may need a cache that supports customizing the weigher, so we can take the rows in `JoinEntry` or whole memory usage into account. #3762

**Comment by fuyufjh** [comment]
Appeared again:

<img width="936" alt="image" src="https://user-images.githubusercontent.com/10192522/186202656-71002a06-ab3b-4123-bf5c-a346b6369266.png">

Meanwhile, the cache size doesn't grow after hitting the limit

<img width="719" alt="image" src="https://user-images.githubusercontent.com/10192522/186203048-142e78e8-f556-48d0-9c15-01c7f3aeaaf8.png">

**Comment by fuyufjh** [comment]
Added the actor memory statistics.

After drop MV,

- the memory usage drops down, but still much more than block cache size.
- the memory released is much less than total actor memory

<img width="1845" alt="image" src="https://user-images.githubusercontent.com/10192522/186327047-d4634a58-8767-4501-993c-fb9a8b3998a6.png">

**Comment by jon-chuang** [comment]
> the memory released is much less than total actor memory

*much more?

**Comment by fuyufjh** [comment]
> > the memory released is much less than total actor memory
>
> *much more?

Yes. My bad, I'll add some specific number there

**Comment by fuyufjh** [comment]
@jon-chuang I was trying to use the `profiling` feature provided by jemalloc to find out the cause. Please help me if you are interested.

References:

- https://github.com/tikv/jemallocator/tree/main/jemalloc-sys#cargo-features
- https://en.pingcap.com/blog/troubleshooting-memory-leaks-deep-dive-into-common-heap-profilers/#htoc-jemalloc-heap-profiler

**Comment by jon-chuang** [comment]
Sure, do post any prof graphs that you obtain. Hopefully they are not too big...
