### ISSUE TITLE
Optimize VarTransaction for CompactStatus

### ISSUE THREAD

**Issue by Little-Wallace** [risingwavelabs/risingwave#4836]
**Is your feature request related to a problem? Please describe.**

Current every time we change CompactStatus in meta-service, we must convert the whole `CompactStatus` to `risingwave_pb::hummock::CompactStatus` and store it in ETCD. But `CompactStatus` is a large structure which include all pending compaction task and compaction files.

**Describe the solution you'd like**
We only hope to store new `RunningCompactTask` in ETCD. Of course, when process the result of compact task, we also only need to delete the finished `RunningCompactTask` rather than store the whole structure.

A suggestion is to merge `LevelHandler` of every level into one `LevelHandler`. And then we only need to store `pending_tasks: Vec<RunningCompactTask>` in ETCD. We can implement a `VectorTransaction` just like `BTreeMapTransaction`.

**Describe alternatives you've considered**

**Additional context**

**Comment by fuyufjh** [comment]
Any updates?

**Comment by Gun9niR** [comment]
The difficulty is that each `MetadataModel` object correspond to one kv pair in `MetaStore`. If we want to use multiple KV pairs to represent each `CompactStatus`, we need to change `MetadataModel`'s interface.

**Comment by fuyufjh** [comment]
@Little-Wallace Can we close it?
