### ISSUE TITLE
batch: Create executor level metrics.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#4844]
We can start with following metrics as example.

I think we should move it to executor, but as discussed offline, we can put it in another pr.

_Originally posted by @liurenjie1024 in https://github.com/singularity-data/risingwave/pull/4757#discussion_r952405853_

**Comment by ZENOTME** [comment]
```
let executor_labels = HashMap::with_capacity(5);
executor_labels.add_all(context.task_labels);
executor_labels.push("executor_id", executor_id);
let hash_map_size_opts = Opts::new("hash_agg_hash_map_size").const_labels(executor_labels);
let counter = register_counter(hash_map_size_opts);
```
I think it will cause conflict If there are multiple same executor in a task.

**Comment by liurenjie1024** [comment]
> I think it will cause conflict If there are multiple same executor in a task.

Different executors have different executor id, even if they are same kind of executor.
