### ISSUE TITLE
Discussion: Usage of single value agg

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#4866]
Previously we had a [discussion on usage of single value agg](https://app.slack.com/client/T030LTU38S2/C03G9HMLEBC/thread/C03G9HMLEBC-1653378232.953079).

As mentioned in discussion above, it could potentially be used to fix #1335 hence we leave it for now. 
But it doesn't seem to be used anywhere else.
If it isn't used to fix #1335 I think it should be removed.

Related: #4864

**Comment by xxchan** [comment]
BTW single value is added to FE recently https://github.com/singularity-data/risingwave/pull/2869

**Comment by chenzl25** [comment]
IIUC, there is no user cases that have to use `single_value` explicitly now. @kwannoel

**Comment by kwannoel** [comment]
I shall open a PR to remove this operator from our codebase.
