### ISSUE TITLE
Optimize the memory usage of streaming operators

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#4884]
See details on https://risingwave-labs.slack.com/archives/C03U9AB2P45/p1661360900296829

Profile results: https://risingwave-labs.slack.com/files/U030TMLQ1LJ/F0409NBGQ56/2_run_1h30min.svg

The memory used in streaming operators is:

```
- HashJoin
  - 2.4GB PK (Vec<Datum>)        
  - 1.5GB JoinRow (serialized) 
  - 2.7GB B-Tree data structure
- HashAgg
  - 1.6GB ExtremeState (Vec<OrderedDatum>)
```

- [x] Optimize PK (`VecDatum`) of streaming HashJoin
   - Can be replaced with memcomparable row
- [x] Optimize ExtremeState (`Vec<OrderedDatum>`) in streaming HashAgg
   - Can be replaced with memcomparable row
- [x] https://github.com/risingwavelabs/risingwave/issues/5526
- [ ] Optimize B-Tree in streaming HashJoin
   - Don't know how... need investigation

**Comment by Little-Wallace** [comment]
For `B-Tree data structure`, have we known which component memory is used for Key-Value and which component memory is just allocated for B-Tree Node?

**Comment by fuyufjh** [comment]
> For `B-Tree data structure`, have we known which component memory is used for Key-Value and which component memory is just allocated for B-Tree Node?

Yes, it can be seen in the heap profile results. 

<img width="753" alt="Screen Shot 2022-08-25 at 22 37 19" src="https://user-images.githubusercontent.com/10192522/186695030-b71d0aca-40e0-47a8-8af2-19daf2e0d6be.png">

**Comment by Gun9niR** [comment]
I'll start with the ExtremeState.
