### ISSUE TITLE
Compactor: Split sub-compaction by index-block

### ISSUE THREAD

**Issue by Little-Wallace** [risingwavelabs/risingwave#4907]
### Is your feature request related to a problem? Please describe.

Now use boundary of files to divide a large compact task into several sub-compaction jobs to speed up. But this method can not split task to average. It means that there may be some sub-compaction hold most data and other jobs are waiting it to end.

### Describe the solution you'd like

We can load index-block from meta-file and use the keys of index-block to divide tasks.

```
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct SstableMeta {
    pub block_metas: Vec<BlockMeta>,
    ....
}

#[derive(Clone, PartialEq, Eq, Debug)]
pub struct BlockMeta {
    pub smallest_key: Vec<u8>,
    ...
}

```

### Additional context

We must pay attention to one detail,  that is `BlockMeta::smallest_key` is also include `sequence number`. we must replace sequence number with a `MAX` to prevent it split one user key.

**Comment by Little-Wallace** [comment]
In method `Compactor::compact`, we shall preload all sstable before creating `CompactorRunner`.
For example,

```rust
let mut splits = vec![];
splits.push(KeyRange::new(Bytes::new(), Bytes::new()));
if total_file_size > XXXXX {
let tables = context.sstable_store.preload(sst_ids);
let mut indexes = vec![];
for table in tables {
     indexes.extend(table.meta.block_metas.iter().map(|block|  block.smallest_key.clone()).collect_vec());
}
indexes.sort();
// split indexes and replace sequence number.
} 

```

**Comment by fuyufjh** [comment]
Any updates?

**Comment by skyzh** [comment]
should have been fixed
