### ISSUE TITLE
Replace list operation of object store.

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#4912]
### Is your feature request related to a problem? Please describe.

> S3’s LIST operation can generally list the available objects in a bucket by lexicographic order of key, given a start key. This makes it possible to efficiently list
> the objects in a “directory” if using file-system-style paths, by starting a LIST request at the key that represents that directory prefix (e.g., warehouse/table1/). Unfortunately, these metadata APIs are generally expensive: for example, S3’s LIST only returns up to 1000 keys per call, and each call takes tens to hundreds of milliseconds, so it can take minutes to list a dataset with millions of objects using a sequential implementation.

## Reference:
[Delta Lake: High-Performance ACID Table Storage over Cloud Object Stores](https://www.databricks.com/wp-content/uploads/2020/08/p975-armbrust.pdf)

### Describe the solution you'd like

We can record all the sst files in a meta file and physically it can store in etcd or s3. 
List operation can be replaced by read the meta file content to find all sst files.
If we keep the sst files in an `version` order, we can even search files quickly when doing `VacuumTask`.

**Comment by hzxa21** [comment]
> We can record all the sst files in a meta file and physically it can store in etcd or s3.

This is exactly what we did before but this requires a 2PC protocol:
1. Before writing to S3, we need to contact meta to persist the intention to write as well as the SST id in etcd. This is one round of RPC and one write to etcd.
2. After writing to S3, we need to contact meta to persist the completion of write. This is another round of RPC and one write to etcd.

Note that not only CN but also compactor needs to adopt this 2PC protocol. We observe that the RPC and extra etcd write adds non-negligible overhead in the write path. The benefit is just to reduce the overhead of cleaning orphan objects, which can rarely happen and doesn't need to be done in a very timely manner. Therefore, we choose to optimize for the common cases by leveraging the object store list operation to find out and clean orphan objects. We will run object store list infrequently so the inefficiency for the list operations is accetable.

See #4037 for more details.
