### ISSUE TITLE
Fast ending for query with limit

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#4915]
### Is your feature request related to a problem? Please describe.

Suppose we have a large table t and user execute the following query.
```sql
select * from t limit 1
```
We expect this query would end up once the first row is fetched, but currently it seems this query will scan the whole table.

**Comment by liurenjie1024** [comment]
I think this is because limit is not pushed down. Similar question happens for top n.

**Comment by chenzl25** [comment]
Yes, I just introduce two phase limit in distributed mode before. Now I think local mode also need them.

**Comment by chenzl25** [comment]
Fixed by #4920.
