### ISSUE TITLE
Compute node should pause streaming when lost heartbeat from Meta 

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#4916]
### Is your feature request related to a problem? Please describe.

Otherwise, the compute node will continue to consume data without barriers until memory expoloded.

<img width="923" alt="Screen Shot 2022-08-26 at 14 55 20" src="https://user-images.githubusercontent.com/10192522/186841460-34cc4692-a4cc-4345-a716-2f02f337c8fb.png">

### Describe the solution you'd like

Compute node should pause streaming when lost heartbeat from Meta

**Comment by BugenZhao** [comment]
+1. For aggregations, the executor will batch all chunks until a new epoch starts. If there's something wrong with the meta service, the data generation will make compute node filled with data.

@skyzh has proposed a solution of source limit before in #2661 but removed after concurrent checkpointing. But I think it is still worthwhile now as we bench.

**Comment by yezizp2012** [comment]
After some offline discussion with @BugenZhao , in this situation we'd better rely on source limit as @skyzh proposed before to avoid memory exploded rather than pause and resume streaming by CN itself. Because it's dangerous to let CN control pause and resume by itself.

**Comment by fuyufjh** [comment]
> Because it's dangerous to let CN control pause and resume by itself.

Agree with you. 

Any better solution?

**Comment by fuyufjh** [comment]
My ideas:

1. Revert back #2661. Even when traffic is very high, this would explicitly prompt us to set a better epoch interval.
2. Double insurance: If a compute node lose connection to meta for too long (e.g. 10 min), it should kill itself. The reason is that meta should be recovered in less than 1 min, if it still failed to reach meta server after 10 min, it's possible that this node is network partitioned from others and it's better to shutdown.

**Comment by BugenZhao** [comment]
> 1. Put back [feat(streaming): limit source ingestion rate based on barrier #2661](https://github.com/risingwavelabs/risingwave/pull/2661) to limit the incoming events per epoch. Even when traffic is very high, this would explicitly prompt us to set a better epoch interval.

+1

**Comment by yezizp2012** [comment]
> My ideas:
> 
> 1. Put back [feat(streaming): limit source ingestion rate based on barrier #2661](https://github.com/risingwavelabs/risingwave/pull/2661) to limit the incoming events per epoch. Even when traffic is very high, this would explicitly prompt us to set a better epoch interval.
> 2. Double insurance: If a compute node loses connection to meta for too long (e.g. 10 min), it should kill itself. The reason is that the meta service should always be recovered in less than 1 min, if it still fails to reach meta server after 10 min, it's possible that this node is network partitioned from others and it's better to shut down.

Yes, totally agree 👍. I think source limit in [#2661](https://github.com/risingwavelabs/risingwave/pull/2661 will be helpful and I was suppose to revert it back but forgot. And the second solution is also feasible and necessary.
