### ISSUE TITLE
refactor: `QueryResultFetcher` should add a shutdown channel to listen on task failure

### ISSUE THREAD

**Issue by BowenXiao1999** [risingwavelabs/risingwave#4947]
Now, after all stages are scheduled, `QueryResultFetcher` will begin to work and use `get_data` to fetch results. 

According to #3908 , the executor can not throw error through channels. It's possible that `QueryResultFetcher` may already start to work (All stages are created), but some other task get execution failed later, in this case the `QueryResultFetcher` won't know it.

One solution is to add a shutdown channel channel when running `QueryResultFetcher`, if one task execution fail, this shutdown channel will receive the info and return error.

cc @liurenjie1024

**Comment by liurenjie1024** [comment]
LGTM
