### ISSUE TITLE
Object store error handling

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#4951]
### Is your feature request related to a problem? Please describe.

I observed S3 returned SlowDown error (caused by excessive delete requests to S3) in my recent benchmark. This caused both CN and compactor to panic and reveals two problems:
- We don't have fine-grain control on the GC background task and thus it can affect foreground read/write. #4728 can help to reduce the delete qps to be 1000 times smaller but I think we still have potential risk here because the amount of GC SSTs can be large with `min_sst_retention_time_sec` to be 7days.
- We don't have proper error handling for object store error. Specifically, for retriable and recoverable errors, we should trigger backoff + retry instead of panic to avoid crashing the cluster.

### Describe the solution you'd like

- Limit object store QPS for GC task.
- Proper retry + error handling for object store error.

### Additional context

![image](https://user-images.githubusercontent.com/5518566/187136927-9fb239c6-c911-4716-90ea-a27545f58234.png)
![image](https://user-images.githubusercontent.com/5518566/187136948-12c98692-84f1-4f53-b581-85f528bd0260.png)

**Comment by hzxa21** [comment]
I think aws-sdk may already implement backoff + retry internally. We can check whether there is a misconfiguration from our side.

**Comment by StrikeW** [comment]
Could you upload more logs? It seems that the logs in the screenshot don't contain functions related to storage.

**Comment by StrikeW** [comment]
This is what happens when we reach the S3 prefix QPS limitation ([link](https://aws.amazon.com/premiumsupport/knowledge-center/s3-resolve-503-slowdown-throttling/?nc1=h_ls)).  The problem should be mitigated after #4965 merged.

**Comment by StrikeW** [comment]
> I think aws-sdk may already implement backoff + retry internally. We can check whether there is a misconfiguration from our side.

The aws-sdk has built-in retry logic for [throttling errors](https://github.com/awslabs/aws-sdk-rust/blob/2113efb1af6fa5ce6ff9ba0f05b6a5e5c34bdbdc/sdk/aws-http/src/retry.rs#L90-L100) and server-side errors. And the [default retry times](https://github.com/awslabs/aws-sdk-rust/blob/2113efb1af6fa5ce6ff9ba0f05b6a5e5c34bdbdc/sdk/aws-smithy-types/src/retry.rs#L289-L297) are 2. So we can increase the retry times a bit to mitigate the `Slowdown` errors.  cc @hzxa21

**Comment by hzxa21** [comment]
Does S3 has any doc to talk about how long the throttling will last with sufficient number of prefixes?  I think we can adjust the retry time and backoff delay accordingly. Also, in our case, should upper layer (user of object store) see the throttling error?

**Comment by StrikeW** [comment]
As far as I know, I didn't find docs about how long S3 will take to finish the scaling for high QPS. And I think we should not rely on this. So we may need to choose the backoff delay by ourselves. The default value in aws-sdk is 1 second and the comment for it is "_Most services should work fine with the default duration of 1 second, but if you find that your requests are taking too long due to excessive retry backoff, try lowering this value_".

> should upper layer (user of object store) see the throttling error?

Since we cannot rely on the time needed by S3 to finish scaling, throttling errors still need to be thrown to upper layer. 
And currently we have wrapped the SDK errors in the `ObjectError`.

```
impl<E> From<aws_sdk_s3::types::SdkError<E>> for ObjectError
where
    E: std::error::Error + Sync + Send + 'static,
{
    fn from(e: aws_sdk_s3::types::SdkError<E>) -> Self {
        ObjectErrorInner::S3(e.into()).into()
    }
}
```
