### ISSUE TITLE
StreamSimpleAgg should output 1 row on empty input

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#4954]
### Describe the bug

By SQL semantic, aggregates without group by always output exactly 1 row. It is `null` for most aggregate functions (incl. `sum`) except `0` for `count`.

### To Reproduce

```
crate table t (v1 int);
create materialized view mv1 as select min(v1) as min1 from t;
select * from mv1;
```

Actual output:
```
 min1 
------
(0 rows)
```

### Expected behavior

```
 min1 
------
     
(1 row)
```

**Comment by TennyZhuang** [comment]
We know the bug long long ago, but to fix this, we have to send a message to downstream when the first time we set up an actor. The SimpleAgg is the only operator who has the behavior but the fix may introduce too many efforts. I'd prefer keep the bug until we find a elegant way.
