### ISSUE TITLE
move parser down to connector to avoid duplicate serialization overhead

### ISSUE THREAD

**Issue by tabVersion** [risingwavelabs/risingwave#4961]
### Background

When using a connecter that generates data internally, eg. datagen and nxtmark, the existing implementation need to serialize the generated data to json and deserialize it to datachunk in the upper layer, which causes unnecessary overhead. 

### Design

in prev design for datagen, connectors are informed with columns and schema, there is no difficulty in generating datachunk directly.

**Comment by lmatz** [comment]
Needed by stream executor's micro-benchmarks (executed in e2e style), i.e. prevent `datagen` source from becoming a bottleneck.
