### ISSUE TITLE
Support aggregate function as OVER window function

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#4978]
e.g., nexmark Q6

```sql
SELECT
    Q.seller,
    AVG(Q.final) OVER
        (PARTITION BY Q.seller ORDER BY Q.date_time ROWS BETWEEN 10 PRECEDING AND CURRENT ROW)
    as avg
FROM (
    SELECT MAX(B.price) AS final, A.seller, B.date_time
    FROM auction AS A, bid AS B
    WHERE A.id = B.auction and B.date_time between A.date_time and A.expires
    GROUP BY A.id, A.seller
) AS Q;
```

To support Grouping TopN #4847, we will first support special window functions `row_numer()` (or `rank()`, `dense_rank()`) only.

**Comment by xxchan** [comment]
https://github.com/risingwavelabs/rfcs/pull/8

**Comment by richardchien** [comment]
With #9110, #9248 and #9597 I guess we now support aggregating over window, though only for Emit-On-Window-Close mode. I'm closing this issue now, cuz later general version of over window executor is not really related to _aggregate over window_ support.
