### ISSUE TITLE
streaming: limit operator's memory usage by bytes

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#4987]
### Is your feature request related to a problem? Please describe.

Currently, our stateful streaming operators like HashJoin and HashAgg limit their LRU cache by the number of entries. This could be dangerous for HashJoin because there is no actual limit for the number of rows in each entry. When benchmarking NexMark, I found the servers crashed due to the unlimited memory usage.

See also [#4819](https://github.com/risingwavelabs/risingwave/issues/4819)

### Describe the solution you'd like

Make the LRU weighted and estimate the memory usage of data as the weight of LRU.

### Describe alternatives you've considered

We had explored to use a task-local allocator to count the memory usage (https://github.com/risingwavelabs/risingwave/pull/4785), but this approaches have 2 critical flaws:

1. It **cannot** count the memory usage at operator (or table) level, which is the basic unit for us to manage the memory pool
2. It **cannot** tell the memory usage of each entry of LRU cache, which must be known when evicting entries, so that the LRU cache knows how many entries to evict to release a certain amount of memory

That's why we need such a verbose and invasive `estimate_size` approach. 

### Additional context

No

**Comment by jon-chuang** [comment]
> It cannot count the memory usage at operator (or table) level, which is the basic unit for us to manage the memory pool

That being said, what we did observe from the flamegraphs is that the majority of the heap allocations specific to these operators (~90%) consists of their cache. Therefore, I believe we can still use the heap profiling (TaskLocalAlloc) as a proxy for the cache memory usage and hence determine eviction policy. We can use some empirically derived magic numbers (e.g. 0.9 * heap_alloc) to estimate the cache size.

**Comment by jon-chuang** [comment]
Ok, I guess, it makes more sense to have precise knowledge of each entry's bytes usage for the purpose of: https://singularity-data.quip.com/J9KYAQc2xIbr/RFC-Dynamic-Memory-Budget-of-Streaming-Operators

**Comment by fuyufjh** [comment]
duplicated with #5290

**Comment by sushantgupta** [comment]
Hi @fuyufjh @BugenZhao,

Do we have integration or unit-test for above fix?

**Comment by fuyufjh** [comment]
@sushantgupta Hi, please check https://github.com/risingwavelabs/risingwave/issues/5290 instead
