### ISSUE TITLE
feat: weighted LRU cache

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#4988]
### Is your feature request related to a problem? Please describe.

required by #4987

- Need to investigate and compare between lru-rs and moka.
- Need to replace the stateful operators one by one: HashJoin, HashAgg, etc.

**Comment by BugenZhao** [comment]
As we choose to try out memory management in a global manner in #5395, I'd like to defer this feature. :)

**Comment by fuyufjh** [comment]
Substituted by https://github.com/risingwavelabs/rfcs/pull/26. @BowenXiao1999 is woking on it.
