### ISSUE TITLE
batch: Enable distributed tracing to trace local execution.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#5015]
This issue consists of following issues:
1. Enable distributed tracing. In this branch https://github.com/risingwavelabs/risingwave/compare/main...renjie/batch_mini_trace I have enabled tracing, but distributed tracing and slow request filtering is missing.  You can see https://crates.io/crates/tracing-honeycomb for enabling distributed  tracing.
2. Implement `trace` statement:
https://docs.pingcap.com/tidb/stable/sql-statement-trace
You can refer to `Subscriber` api for reference.

**Comment by liurenjie1024** [comment]
cc @skyzh  @wangrunji0408   Any suggestions?

**Comment by liurenjie1024** [comment]
cc @BugenZhao

**Comment by BugenZhao** [comment]
Cool.

**Comment by liurenjie1024** [comment]
I took a look at mini tracing, and it seems that it works well with our requirement, but it can't be used in rpc, right?

**Comment by skyzh** [comment]
We'll need to implements things by ourselves if we want to carry tracing spans within RPCs.

**Comment by liurenjie1024** [comment]
Hmm, I think tracing has better support for this and I'm investigating it. Why we switch to minitrace? Just for performance?

**Comment by liurenjie1024** [comment]
https://docs.rs/tracing-jaeger/latest/tracing_jaeger/fn.current_dist_trace_ctx.html

**Comment by skyzh** [comment]
> Why we switch to minitrace? Just for performance?

Better API, better flexibility and allows us to read into spans. This is useful for filtering and tracing slow requests.

**Comment by liurenjie1024** [comment]
One concern with minitrace is the ecosystem. If we use minitrace, it would be difficult for use to inspect other libraries such tonic, object store api?

**Comment by skyzh** [comment]
tonic doesn't use tracing spans for now.

**Comment by liurenjie1024** [comment]
> tonic doesn't use tracing spans for now.

https://github.com/hyperium/tonic/blob/master/tonic/Cargo.toml 
They are using tracing library.

**Comment by skyzh** [comment]
They use it for logging, so it doesn't matter.

**Comment by liurenjie1024** [comment]
https://github.com/hyperium/h2/blob/e4cf88c1a19a7f7823dfaa9eb4c6a19a24f4ead8/src/server.rs

**Comment by skyzh** [comment]
Tracing provides little control over spans. e.g., we cannot filter slow requests and only report slow requests to jaeger. It would be fine to have two tracing facilities in the codebase. RisingWave itself will use minitrace in release mode. If it is necessary to trace libraries like h2, then it would be good to enable it on demand.

**Comment by liurenjie1024** [comment]
During my debugging process I feel tracing api is friendly to use and setup, and it has native support distributed tracing. But we do need to investigate it's subscriber/filter api to filter slow requests.

**Comment by fuyufjh** [comment]
Hi, what't the progress now?

**Comment by liurenjie1024** [comment]
I'll continue with this.

**Comment by xxchan** [comment]
#10637
