### ISSUE TITLE
Scalar subquery is lack of max one row detection

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#5019]
### Describe the bug

A scalar subquery is a subquery that selects only one column or expression and returns one row. A scalar subquery can be used anywhere in an SQL query that a column or expression can be used.
Example:
```sql
select t1.x, (select t2.y from t2 where t2.x = t1.x) from t1
```

However, it is lack of max one row detection for batch query which means when the subquery returns more than one row it should throw an error.

BTW, it that possible to support this kind of query in streaming mode?
Some operator like `SimpleAgg` and `limit 1` can provide max one row semantics.

### To Reproduce

```sql
create table t1 (x int, y int);
create table t2 (x int, y int);
insert into t1 values (1, 1), (2, 2), (1, null), (null, 2), (2, null), (null, 1), (null, null);
insert into t2 values (1, 2), (2, 2), (1, null), (null, 2), (2, null), (null, 1), (null, null);
select t1.x, (select t2.y from t2 where t2.x = t1.x) from t1;
```

Actual Result:
```
 x | y
---+---
 1 | 2
 2 | 2
 1 |
   | 2
 2 |
   | 1
   |
(7 rows)
```

### Expected behavior

```
ERROR:  more than one row returned by a subquery used as an expression
```

**Comment by xiangjinwu** [comment]
Existing issue: #1335

**Comment by chenzl25** [comment]
Any discussion about scalar subquery for streaming before?  For streaming, I think it is better to let user to provide the max one row semantics by using aggregation or limit 1 or some kind of pk constraint.

**Comment by likg227** [comment]
we may use `single_value` to solve this long-standing issue, but I prefer to use single join which was used in Hyper. 
BTW, as for scalar subquery for streaming cc @fuyufjh

**Comment by likg227** [comment]
BTW, we are also lack of mark join for `OR` condition e.g. `where t1.x = t2.x or true.`

**Comment by xxchan** [comment]
> Any discussion about scalar subquery for streaming before? For streaming, I think it is better to let user to provide the max one row semantics by using aggregation or limit 1 or some kind of pk constraint.

Basically we prefered this solution in early discussions, i.e., reject abnormal cases, but just didn't make a decision and postponed it 🤪

**Comment by jon-chuang** [comment]
> Any discussion about scalar subquery for streaming before? For streaming, I think it is better to let user to provide the max one row semantics by using aggregation or limit 1 or some kind of pk constraint. 

Currently, streaming cannot perform cross join. So we do not have this issue. 

equijoin and dynamic filter (join with inequality operator) do not have this issue (latter avoids it with a hack by only pattern matching on simple aggregation). We can add the single_row property to make this more robust.

> BTW, we are also lack of mark join for OR condition e.g. where t1.x = t2.x or true.

Isn't this solved by union i.e. group_by row_id?

**Comment by fuyufjh** [comment]
> > BTW, we are also lack of mark join for OR condition e.g. where t1.x = t2.x or true.
> 
> Isn't this solved by union i.e. group by PK (distinct agg)? Anw, we should add support for that.

Interesting, It seems to work. And it also works for other kinds of Join.

**Comment by chenzl25** [comment]
For scalar subquery, I think we can introduce an intermediate operator `MaxOneRow` and try to eliminate it in optimizer, if optimizer fails to eliminate it, just throws an error.

**Comment by likg227** [comment]
> Isn't this solved by union i.e. group by PK (distinct agg)? Anw, we should add support for that.

do you mean convert query like: `select * from t where v1 in (subquery) or v2 = v3;`to: 
```
select * from t where v1 in (subquery) 
union all 
select * from t where v2 = v3;
```

**Comment by chenzl25** [comment]
> > Isn't this solved by union i.e. group by PK (distinct agg)? Anw, we should add support for that.
> 
> do you mean convert query like: `select * from t where v1 in (subquery) or v2 = v3;`to:
> 
> ```
> select * from t where v1 in (subquery) 
> union all 
> select * from t where v2 = v3;
> ```

Yes, but replace `union all` with just `union`.

**Comment by chenzl25** [comment]
Close by #5147
