### ISSUE TITLE
batch: clean up query manager status when query done

### ISSUE THREAD

**Issue by BowenXiao1999** [risingwavelabs/risingwave#5028]
maintain a HashMap in QueryManager (queryId -> QueryExecution). When QueryResultFetcher finished a query, go to `QueryManager` and delete corresponding `QueryExecution`.

**Comment by liurenjie1024** [comment]
Could you provoid more details about this?

**Comment by BowenXiao1999** [comment]
> Could you provoid more details about this?

I'm thinking whethe we should store the QueryExecution in QueryManager. So that when ctrl-c cancel a query, we can have more information to operate on.

**Comment by liurenjie1024** [comment]
When ctrl-c is received, we should call the `cancel` method of query runner, which stops the running query.

**Comment by BowenXiao1999** [comment]
> When ctrl-c is received, we should call the `cancel` method of query runner, which stops the running query.

Yes. But the problem is how to find corresponding query. QueryManager is for one FE node, ctrl-c is for one session.

**Comment by liurenjie1024** [comment]
Just store the current running query id in session?

**Comment by BowenXiao1999** [comment]
Per [postgresql protocol](https://www.postgresql.org/docs/current/protocol-flow.html#id-1.10.5.7.10:~:text=in%20the%20protocol.-,53.2.8.%C2%A0Canceling%20Requests%20in%20Progress,-During%20the%20processing), ctrl-c will issue a new connection send the cancel request with PID. Therefore, it's not easy to let pg protocol aware of query id.

**Comment by BowenXiao1999** [comment]
> Just store the current running query id in session?

I think I get your point. Seems ok.

So the query execution will not be stored in Query Manager. For future we might need export some running info from frontend. I guess we still need it. But I agree that this issue is not meaningful now.
