### ISSUE TITLE
bin: implement gRPC health-check protocol for meta-node

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#5071]
Please refer to https://github.com/risingwavelabs/risingwave/issues/41 for more information.

**Comment by yinfredyue** [comment]
Here're are the services of meta:
```
cluster_service.rs
ddl_service.rs
heartbeat_service.rs
hummock_service.rs
notification_service.rs
scale_service.rs
stream_service.rs
user_service.rs
```
Which one does the health-check fit into? Or should I create a new `health_service.rs`?

**Comment by skyzh** [comment]
A new service looks fine to me.

**Comment by yinfredyue** [comment]
Just finished coding the new RPC for meta. Now I have the following question about testing:

- I am not sure how to test it locally. My rough guess is as follows: I can start RisingWave using Kubernetes locally. If there's some "dashboard" of Kubernetes, previously no health status should be reported. With my code, we have the health check, so the dashboard should show relevant info. Is this the approach I should follow?

- What's the common practice of testing RPCs here? Unit-test? Integration test?

**Comment by skyzh** [comment]
No need to test them for now. You can modify RiseDev to check liveness based on gRPC health protocol instead of just port open in separate PRs.

https://github.com/risingwavelabs/risingwave/blob/1c5425f08e5c7e95f6ada102e284fd5148729fb1/src/risedevtool/src/task/task_configure_grpc_node.rs#L35-L52

**Comment by yinfredyue** [comment]
I am reading the liveness checking code.

https://github.com/risingwavelabs/risingwave/blob/main/src/risedevtool/src/wait.rs#L24

https://github.com/risingwavelabs/risingwave/blob/main/src/risedevtool/src/task.rs#L169
```rust
pub fn wait(
    mut wait_func: impl FnMut() -> Result<()>,
    f: &mut impl std::io::Write,
    p: impl AsRef<Path>,
    id: &str,
    timeout: Option<std::time::Duration>,
    detect_failure: bool,
) -> anyhow::Result<()> {
    let p = p.as_ref();
    let start_time = std::time::Instant::now();

    writeln!(f, "Waiting for online")?;

    let mut last_error;

    loop {
        match wait_func() {
            Ok(_) => {
                return Ok(());
            }
            Err(err) => {
                last_error = Some(err);
            }
        }

        if let Some(ref timeout) = timeout {
            if std::time::Instant::now() - start_time >= *timeout {
                return Err(anyhow!("failed to connect, last error: {:?}", last_error));
            }
        }

        if detect_failure && p.exists() {
            ...
            return Err(anyhow!(
                "{} exited while waiting for connection: {}",
                style(id).red().bold(),
                buf,
            ));
        }

        sleep(Duration::from_millis(30));
    }
}
```


Is this a bug? `wait_tcp` calls `wait` with `detect failure` = true. Thus, the `detect_failure && p.exists()` becomes true and `wait` returns `Err` at the first unsuccessful TCP connection attempt. But I think the function is trying to retry until the specified timeout.

**Comment by skyzh** [comment]
The file will only exist when program exits abnormally.

**Comment by yinfredyue** [comment]
Can you elaborate on why the file exists when the program exits abnormally? 

status_dir` is created as a temp dir in `risedev-dev.rs` and `status_file` is created by `ExecuteContext::service` (but no file is created, only the path). When is the status file created?

**Comment by yinfredyue** [comment]
> The file will only exist when program exits abnormally.

Can you elaborate on why the file exists when the program exits abnormally? 

status_dir` is created as a temp dir in `risedev-dev.rs` and `status_file` is created by `ExecuteContext::service` (but no file is created, only the path). When is the status file created?

**Comment by skyzh** [comment]
We invoke this bash https://github.com/risingwavelabs/risingwave/blob/main/src/risedevtool/run_command.sh to track the status of the running process. It will create the status file when program exits.
