### ISSUE TITLE
bin: implement gRPC health-check protocol for compactor-node

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#5073]
Please refer to https://github.com/risingwavelabs/risingwave/issues/41 for more information.

**Comment by jon-chuang** [comment]
Could you explain how this is different from cluster heartbeats?

**Comment by skyzh** [comment]
Healthcheck is for some external services (e.g. Kubernetes) to know if a node is alive. If not, the external scheduler will take action to replace the node.

**Comment by skyzh** [comment]
Heartbeat looks more like something internally 🤣
