### ISSUE TITLE
Tracking(streaming): re-introduce no-cache e2e tests

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#5080]
Long ago we introduced a "clear cache mode" for e2e tests in #55, which clears the operator cache on each barrier, so the path of state recovery can be covered. As we migrate to the async stream for executors, we can no longer control the executor externally, so these tests are removed.

However, some operators are being refactored with a new design or integrated with the state table, we find that it's still worthwhile to test them with no-cache or clear-cache mode, as it's about the correctness and critical. Here're some examples.

- Top-N cannot recover: #4631 
- Agg cache hides a bug of state table: #5012 
- Hash join cache hides a bug of mem-table: #5020
- Inconsistent storage records: #4861, #4774 

By intentionally increasing the miss rate of the operator cache, we can test the correctness of the storage and the operator logic more finely.

Furthermore, for those grouping operators, we can make each access on the cache fail and fall back to the storage. This requires all dirty data should be stored in the mem-table, instead of the state itself (#4035), so that the cache can evict entries freely.

## Tracking to make sure all the caches are managed:
- [x] #6484 
- [ ] #6503
- [ ] #6504

**Comment by yuhao-su** [comment]
Any proposal about how to implement it?

**Comment by lmatz** [comment]
As `LRUManager` is enabled by default, can we now enable this by setting `total_memory_available_bytes` to 0?

**Comment by BugenZhao** [comment]
> As `LRUManager` is enabled by default, can we now enable this by setting `total_memory_available_bytes` to 0?

I've come up with this idea days before as well 🤩. It sounds like to work as expected, but there remain several problems.

- Only partial grouping executors use this managed cache. For example, GroupTopN still uses a plain `HashMap`, which cannot be covered by this.
- All singleton executors cannot be covered by this. However, this seems to be the most common case for the wrong implementation, as grouping executors are likely to consider recovery from day one.

I'm thinking about whether the chaos scaling test has achieved this goal. 🤔 However, not all executors are covered now, as we only have the nexmark cases and it even does not contain any outer-joins. 😄

**Comment by lmatz** [comment]
I see, didn't expect many corner cases.
Let me do some investigation as well and create issues to track each uncovered case if indeed necessary.

**Comment by fuyufjh** [comment]
Covered by the scaling test
