### ISSUE TITLE
Unspecified lock order is prone to dead lock

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#5089]
### Describe the bug

https://github.com/risingwavelabs/risingwave/blob/e1cacf0040bc8bf6463413f70e60a728989fde3e/src/meta/src/rpc/service/notification_service.rs#L71

Here we acquire multiple locks from catalog_manager, cluster_manager, fragment_manager and hummock_manager, without strict lock order. Therefore, if in other places some of these locks are acquired in different lock order, dead lock occur.

One example is in HummockManager, we acquire hummock versioning lock before cluster manager lock, however in code snippet above the lock order is reversed. We can fix this specific case by imposing lock order on hummock versioning lock and cluster manager lock. But it's error prone and hard to maintain when there are many locks to consider.

### To Reproduce

N/A

### Expected behavior

N/A

**Comment by zwang28** [comment]
@Li0k  @yezizp2012 @soundOfDestiny

**Comment by soundOfDestiny** [comment]
we can summarize a lock order here

**Comment by yezizp2012** [comment]
Yes, there're too many locks now and it's hard to maintain. Currently we started to do some refactor on these metadata managers to reduce the number of locks. And for notification services, it should only acquire all low level metadata managers which don’t acquire each others’ lock. Of course this will brings some dirty data check when initialized snapshot for subscribers but it’s acceptable for now.
For `HummockManager`, if it’s really necessary we can fix this specific case by imposing lock order and some comments.

**Comment by zwang28** [comment]
> For `HummockManager`, if it’s really necessary we can fix this specific case by imposing lock order and some comments.

Will be fixed by https://github.com/risingwavelabs/risingwave/pull/5042
