### ISSUE TITLE
Should allow concatenating arrays with compatible types

### ISSUE THREAD

**Issue by richardchien** [risingwavelabs/risingwave#5100]
### To Reproduce

```sql
select array[1]::int[] || array[1.2]::numeric[];
select 1::int || array[1.2]::numeric[];
select array[1.2]::numeric[] || 1::int;
```

### Expected behavior

Should successfully concatenate the two arrays.

### Additional context

https://github.com/risingwavelabs/risingwave/pull/5060#discussion_r961402491

**Comment by CAJan93** [comment]
PR is merged and issue is finished. Thank you very much for you help @xiangjinwu
