### ISSUE TITLE
table: KV-like interface for state table

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#5101]
- [x] add a `values` field in table catalog. be compatible with the current row interface
- [x] add a KV-style write interface on state-table 
    - [x] use it in stream hash-join's degree table
    - [x] use it in stream hash agg(https://github.com/risingwavelabs/risingwave/pull/5411 hold until stream agg uses correct vnode)
- [x] add value indices assert in batch mode
```rust
message Table {
  // columnDesces in the table, the table's schema
  repeated columns;
  // the pk_indices of the table, column index of the columns.
  repeated order_key;
  // the values of the table, column index of the columns.
  repeated values;
}
```

**Comment by wcy-fdu** [comment]
FYI: [design doc](https://singularity-data.quip.com/Q7UpAz1Giqi7/RFC-KV-like-interface-for-Row-based-Encoding)

**Comment by wcy-fdu** [comment]
hold until some refactor on stream agg is done

**Comment by wcy-fdu** [comment]
completed
