### ISSUE TITLE
frontend: Support metrics in frontend node.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#5107]
### Is your feature request related to a problem? Please describe.

We should have a `Registry` in frontend node to collect metrics, and a good start point is qps_local_exection(counter), latency_local_execution(histogram).

### Describe the solution you'd like

Setup metrics for frontend node.

### Describe alternatives you've considered

No.

### Additional context

No.

**Comment by ZENOTME** [comment]
We can close this issue if we don't have another metrics need to collect in frontend now.
