### ISSUE TITLE
Error reporting is very confusing with extra comma

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#5111]
### Describe the bug

Add an extra comma is a common mistake when the selection list is very long, e.g.:

```sql
create materialized view mv_sum as
select
    count(*) as count_all,
    count(v1) as count_v1,
    count(v2) as count_v2,
    count(v3) as count_v3,
    count(v4) as count_v4,
    sum(v1) as sum_v1,
    sum(v2) as sum_v2,
    sum(v3) as sum_v3,
    sum(v4) as sum_v4,
    min(v1) as min_v1,
    min(v2) as min_v2,
    min(v3) as min_v3,
    min(v4) as min_v4,
    max(v1) as max_v1,
    max(v2) as max_v2,
    max(v3) as max_v3,
    max(v4) as max_v4,
from t;
```

But the error reporting is very confusing:

```
ERROR:  QueryError: Item not found: Invalid column: v1
```

### To Reproduce

```
dev=> select count(v1) as count_v1, from t;
ERROR:  QueryError: Item not found: Invalid column: v1
dev=> select count(v1) as count_v1 from t;
 count_v1
----------
        6
(1 row)
```

### Expected behavior

A better error message

### Additional context

It should be handled in parser, but the error seems occurred in binder.

**Comment by TennyZhuang** [comment]
It's not simple enough to fix, remove from milestone.

**Comment by xxchan** [comment]
~~I have a simple idea: ban keyword as identifier😄.~~ Which doesn't work because data types are also regarded as keywords😅.

**Comment by xiangjinwu** [comment]
At least we can ban `FROM` so that common mistake like this has more friendly error message. I am working on a local branch which also attempts to take care of `select from t` and `select where true`.

The full fix may require grouping keywords into several categories in the future.

**Comment by xxchan** [comment]
Share a query which confused me quite a while 😅

```sql
SELECT *
FROM (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY window_start, window_end ORDER BY price DESC) as rownum
  FROM (
    SELECT window_start, window_end, supplier_id, SUM(price) as price, COUNT(*) as cnt
    FROM
      TUMBLE(Bid, bidtime, INTERVAL '10' MINUTES)
    GROUP BY window_start, window_end, supplier_id
  )
) WHERE rownum <= 3;
```

The error is `ParserError("Expected joined table, found: *")'`

The actual problem is `MINUTES` -> `MINUTE`... Since the subquery is failed to parse, `parse_table_and_joins` goes on and `SELECT` is viewed as a table name. It's quite disastrous to allow keyword as identifier...
