### ISSUE TITLE
feat(storage): use atomics to count `num_ssts_{sealed/uploaded}`

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#5121]
### Is your feature request related to a problem? Please describe.

Atomics are cheaper than mutex

### Additional context

See: https://github.com/risingwavelabs/risingwave/pull/4496#discussion_r963181710

**Comment by guzzit** [comment]
I'd like to work on this.

**Comment by fuyufjh** [comment]
@guzzit  any updates? cc. @jon-chuang

**Comment by guzzit** [comment]
Sorry for the delay @fuyufjh. I couldn't figure out a safe way to do this without any locks. I've unassigned myself.
