### ISSUE TITLE
overhead from json serde

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#5122]
Stateless streaming queries take a large percentage in real-world scenarios.

These queries take the input, do some simple transformation and filter out some records, and then output to some sink.

In essence, the query itself is not that cpu-intensive, and it is also not io-bounded in terms of state access.
An example is Nexmark q10:
```
CREATE SOURCE bid (
    "auction" BIGINT,
    "bidder" BIGINT,
    "price" BIGINT,
    "channel" VARCHAR,
    "url" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Bid',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '1000000'
) ROW FORMAT JSON;

CREATE MATERIALIZED VIEW mv_10 as SELECT auction, bidder, price, dateTime, extra, DATE_FORMAT(dateTime, 'yyyy-MM-dd'), DATE_FORMAT(dateTime, 'HH:mm')
FROM bid;
```

Therefore, JSON serde is likely to be the bottleneck of the query.
#4555 has discussed this issue.
For the purpose of benchmarking RisingWave itself, #4555 and #4961 proposed to generate in-memory data chunks to bypass JSON serde. This is the right way to go.

In reality, the query will read input from some other systems, and JSON deserialization is not avoidable.
Therefore, we need to benchmark some trustworthy JSON libraries as JSON deser is probably the most CPU-intensive part and takes most of the processing time in such stateless queries. 
And again, there are a lot of such queries.

**Comment by lmatz** [comment]
Different libraries make different tradeoffs and perform differently on different workloads.
Check out https://github.com/serde-rs/json-benchmark

**Comment by neverchanje** [comment]
We need to first trace the JSON parsing time and how much it occupies the e2e latency. I think whether JSON is the bottleneck is not confirmed yet.

**Comment by jon-chuang** [comment]
I think it is important to note the difference between static parsing e.g. serde library, and dynamic json parsing where the structure is unknown. The latter is what many of these benchmarks are based upon but is completely irrelevant to our actual requirement.

In our case, we can probably see some performance gains by leveraging a parser where the structure is known. This is probably as simple as implementing a serde library to directly parse to our in-memory datatype, using the serde-json implementation as a guide. (or find the equivalent library if it exists).

**Comment by lmatz** [comment]
I don't think we need to do what people have done years ago to verify again json parsing is the bottleneck:
databricks, data artisan, and some independent blog have all pointed out json parsing(only de) can decrease the throughput by a huge factor, up to 35X.

And the context is for simple stateless queries, there is honestly not much going on in RisingWave except json parsing.
