### ISSUE TITLE
metrics: report correct process metrics under macOS

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#5129]
Currently, the process metrics, i.e., CPU and memory usage, are dummy values under macOS. Considering that most of our developers are working on a Mac and may do some small tests or benchmarks directly on the local machine, it would be better to report correct process metrics under macOS.

https://github.com/risingwavelabs/risingwave/blob/d574cf586ab5e96696a445e82d69d2323848b79b/src/common/src/monitor/process_linux.rs#L113-L137

**Comment by tabVersion** [comment]
I gonna have a try 🤣
