### ISSUE TITLE
fix(expr): regex operator `~` / `!~` should return null when either input is null

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#5136]
This rewrite is not equivalent when either `left` or `right` is `null`. The operator returns `null` but this returns `false`. Let's open an issue to track the fix.

_Originally posted by @xiangjinwu in https://github.com/risingwavelabs/risingwave/pull/5127#discussion_r963355810_

**Comment by xiangjinwu** [comment]
This can be supported by forking the `regex_match` backend implementation, which may soon be replaced by an enhanced `prebuilt` attribute of the expression macro (see `regex_matches` in #9949). So deferring this until that is available.

Also note some other incompatibilities with PostgreSQL: #7136
