### ISSUE TITLE
feat(batch): vnode check for batch queries

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#5141]
### Is your feature request related to a problem? Please describe.

The vnode must be correct for Scan executors of batch queries. We should add an assertion here.

> I think the vnode check should be done in upper layer when creating the batch executor.
white_check_mark
>
> When creating the batch executor / batch storage table, we should check whether vnode info matches with MV.

See more on [Slack discussion](https://risingwave-labs.slack.com/archives/C034TRN6A49/p1662367573771939?thread_ts=1662366945.399309&cid=C034TRN6A49)

**Comment by fuyufjh** [comment]
@wcy-fdu Can we do this on state table layer? If not, please feel free to assign to others.

**Comment by hzxa21** [comment]
cc @xxhZs This issue is relevant to reading from non-checkpoint epoch.

**Comment by wcy-fdu** [comment]
Should be done on relational table layer.
