### ISSUE TITLE
fix(meta): Fix notification version synchronization problem after `re-subscribe`

### ISSUE THREAD

**Issue by HuaHuaY** [risingwavelabs/risingwave#5145]
Discussed in #5132.
Here are the steps that a frontend calls a ddl RPC.
1. frontend send a RPC request to meta.
2. meta send a notification to frontend in notification stream.
3. meta send a RPC response to frontend.
4. frontend wait a version which is sent by observer_manager after handling the notification.

If step 2's stream is broken, frontend will call `re-subscribe` to request catalog snapshot and catalog version, and send the version to step 4 to avoid request hang. But if meta reboots before `re-subscribe`, frontend will get a small init catalog version, and step 4 will wait until the new version is bigger than the value before meta reboots.

We plan to fix this after we de-couple ckpt and barrier.

**Comment by fuyufjh** [comment]
Any updates

**Comment by HuaHuaY** [comment]
We plan to fix this issue after we de-couple ckpt and barrier. So this issue will not be finished in 0.1.13.
