### ISSUE TITLE
test: add S3 simulator

### ISSUE THREAD

**Issue by wangrunji0408** [risingwavelabs/risingwave#5161]
Recently we've introduced the etcd simulator #5084 as a replacement for memory storage in simulation test.
It's time to do the same for object storage!

**Comment by wangrunji0408** [comment]
Note: we should simulate the `Broken pipe` error encountered in #5316.

**Comment by fuyufjh** [comment]
Any updates?

**Comment by fuyufjh** [comment]
Seems done

**Comment by wangrunji0408** [comment]
Not yet. 🥵 Still working in progress by @KveinAxel
