### ISSUE TITLE
test: long-running nexmark on madsim

### ISSUE THREAD

**Issue by wangrunji0408** [risingwavelabs/risingwave#5170]
We hope to run nexmark for a long period in deterministic simulation to find more stability issues.

Some potential challenges:
- limited compute resource: one test can only be run on 1 CPU core due to the determinism requirement.
- limited memory capacity: long-running task will generate a huge amount of data which exceeds the memory capacity. we may need to dump data to the disk.

**Comment by lmatz** [comment]
> limited compute resource: one test can only be run on 1 CPU core due to the determinism requirement.

For the set of computations without any side effects, i.e. pure expression evaluation, can they be executed concurrently on multiple cores?

**Comment by TennyZhuang** [comment]
Any updates?

**Comment by wangrunji0408** [comment]
After some rethinking, I decided to make this issue low-priority, as long-running also makes it slow to reproduce. We can't benefit much from it compared with existing longevity test. Instead, I was trying to add more short-term fault injection tests (e.g. #7623) so that problems would be found more efficient.
