### ISSUE TITLE
refactor(meta): reduce meta store write caused by pin/unpin snapshot

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#5177]
We can avoid two meta store write when run_command in barrier manager, because it's unnecessary for meta node to persist its pin snapshot state.
https://github.com/risingwavelabs/risingwave/blob/49834a8aeabad54841315496f193758be39c38b0/src/meta/src/barrier/mod.rs#L1024
https://github.com/risingwavelabs/risingwave/blob/49834a8aeabad54841315496f193758be39c38b0/src/meta/src/barrier/mod.rs#L1026

We don't need this line too, which exactly clean up aforementioned state on meta restart.
https://github.com/risingwavelabs/risingwave/blob/49834a8aeabad54841315496f193758be39c38b0/src/meta/src/hummock/manager/mod.rs#L205

**Comment by zwang28** [comment]
@Little-Wallace @BugenZhao @BowenXiao1999 Please take a look.
If there is no concern, we can specialize HummockManager's pin_snapshot and unpin_snapshot for meta node somehow.

**Comment by BowenXiao1999** [comment]
LGTM

**Comment by BugenZhao** [comment]
What do you mean by "meta node to persist pin snapshot state"? 👀

**Comment by zwang28** [comment]
> is it to say that the "pinned" state can be stored in the meta service's memory as we're not going to recover a failed mv creation

Yes I think so that a restarted meta doesn't need to restore any previous pinned snapshot. Is it true?

**Comment by BowenXiao1999** [comment]
> Yes I think so that a restarted meta doesn't need to restore any previous pinned snapshot. Is it true?

Hmmm I think meta should restore watermark max epoch level for each contextId?

**Comment by zwang28** [comment]
> Hmmm I think meta should restore watermark max epoch level for each contextId?

Sorry, I mean no need to restore for meta node.

**Comment by BowenXiao1999** [comment]
I remermbed that the pin_snapshot is refactored to be very lightweight by @Little-Wallace . So I doubt whether we can save a lot write cost.

FE needs persist the snapshot cuz batch query may keep running when meta fails (Or we show the data is inconsistent, in that case persist is no need). But yes, for mv on mv, if meta fails the job is also fail so I think this looks reasonable. 

Sounds good for me

**Comment by zwang28** [comment]
> So I doubt whether we can save a lot write cost.

Just realize run_command is not as I originally thought. So yes this optimization doesn't worth it.
