### ISSUE TITLE
improve `node_num` metrics

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#5186]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/10192522/189022363-3a2daeb1-c6e1-409a-a71e-75b513ca44fb.png">

Today I saw a `-1` node number. That implies that maintaining the node_num metric with `dec()`/`inc()` is not reliable.

I think it's better to report (a snapshot of) the current number of working to Prometheus in some fixed interval, for example, when collecting `process_resident_memory_bytes`, instead of incresing/decresing it when changes happen. 

_Originally posted by @fuyufjh in https://github.com/risingwavelabs/risingwave/issues/4933#issuecomment-1239196021_

**Comment by Gun9niR** [comment]
Is there any way to reproduce this bug? `-1` shouldn't  be observed unless `delete_worker_node` is called more times than it should be.

**Comment by fuyufjh** [comment]
> Is there any way to reproduce this bug? `-1` shouldn't be observed unless `delete_worker_node` is called more times than it should be.

My cluster crashed once.

**Comment by Gun9niR** [comment]
Which component? Frontend?

**Comment by fuyufjh** [comment]
> Which component? Frontend?

Forgot... Take a try to kill the whole cluster?

**Comment by Gun9niR** [comment]
After some tries I failed to reprduce the problem 😢. I suspect the cause is `node_num` is `inc()`ed in `activate_worker_node` instead of `add_worker_node`, so a worker node that is deleted before it is activated will result in incorrect metrics. 

In terms of the reliability of `inc()` and `dec()`, I think it mainly depends on `add_worker_node` and `delete_worker_node`. If these functions are the only way to modify the number of cluster workers and provided they are called properly, there should be no problem with `inc()` and `dec()`. I suspect if the cause of this issue is not what I mentioned above, changing the implementation to snapshot will just conceal the fact that cluster workers are not managed correctly. 

So, how about we first move `inc()` to `add_worker_node`, and see if anyone still encounters this problem?

**Comment by fuyufjh** [comment]
> In terms of the reliability of inc() and dec(), I think it mainly depends on add_worker_node and delete_worker_node. If these functions are the only way to modify the number of cluster workers and provided they are called properly, there should be no problem with inc() and dec(). I suspect if the cause of this issue is not what I mentioned above, changing the implementation to snapshot will just conceal the fact that cluster workers are not managed correctly.

Well. It seems that we have a different understanding to this "node number" metric. I consider it as an objective measurement of the processes, which means, similar to the CPU and memory usage, it should be reported by the operating system or some monitoring components instead of RisingWave itself. 

> changing the implementation to snapshot will just conceal the fact that cluster workers are not managed correctly.

I think that should be the job of the dashboard/API on meta node instead of our monitor system (Prometheus + Grafana)

**Comment by Gun9niR** [comment]
> It seems that we have a different understanding to this "node number" metric.

Yes. 

> it should be reported by the operating system or some monitoring components instead of RisingWave itself.

I think using additional monitoring components is a bit over-complicating things. 

1. OS does not know the worker type of these processes.
2. The monitoring component needs to be deployed on each physical node (AFAIK), which adds to deployment complexity. 
3. A process becomes a worker only when meta node knows of it. If it can contact the monitoring component but not meta node, the metric would be wrong.

> I think that should be the job of the dashboard/API on meta node instead of our monitor system (Prometheus + Grafana)

Of course. What I meant is assuming`add_worker_node` and `delete_worker_node` are called properly and node num metric is changed only in these two functions, the metric shouldn't be wrong. 

For example, let's say currently we don't check the deletion of non-existent workers (IIRC, we actually don't). By reporting

> (a snapshot of) the current number of worker

, the metric would be correct, as such deletion is just a no-op. However, by showing the correct metric on the dashboard, this incorrect deletion will be hidden.

**Comment by fuyufjh** [comment]
> I think using additional monitoring components is a bit over-complicating things.

Well it's not so complicated 🤣 Please take a look at the implementation of `process_resident_memory_bytes`:

https://github.com/risingwavelabs/risingwave/blob/79eb45b588608ee5c69c75639860e480983c176e/src/common/src/monitor/process_linux.rs

> , the metric would be correct, as such deletion is just a no-op. However, by showing the correct metric on the dashboard, this incorrect deletion will be hidden.

Yes I understand your meaning. But in my mind, this case could be revealed by inspecting the dashboard and the Grafana, and he will find out: Oh, these 2 numbers mismatched, so there must be something wrong!

In my mind the node number shown on the Grafana should be similar to `ps -ef | grep node` or `kubectl list pods | grep node`, so I expect the result to be as precise as possible.

**Comment by Gun9niR** [comment]
> Oh, the dashboard said there are 2 meta nodes, while the grafana shows only 1

I didn't realize the Risingwave dashboard already does this job 😢. Then a `ProcessCollector`-like implementation is doable. Still, I'd like to keep the worker type (distinguish them with labels), so we can observe how the number of different components change during scaling.
