### ISSUE TITLE
dashboard: layout not optimal for source graph

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#5205]
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/4198311/189033649-062f2695-bd9e-426d-b352-aa46cac918a8.png">

"person" would be better positioned at the right?

**Comment by skyzh** [comment]
code can be found at https://github.com/risingwavelabs/risingwave/compare/xxchan/source-graph?expand=1

cc @mikechesterwang do you have ideas? not urgent, but might be some bugs in the layout algorithm?

**Comment by skyzh** [comment]
Also if some part of the graph is not connected to another part (like TPC-H and NexMark are not connected), we can try position NexMark at the bottom of TPC-H?

**Comment by mikechesterwang** [comment]
> Also if some part of the graph is not connected to another part (like TPC-H and NexMark are not connected), we can try position NexMark at the bottom of TPC-H?

This is the idea, `getConnectedComponent` in `./lib/algo.ts` will help to group ActorBox

**Comment by skyzh** [comment]
I'm also thinking of aligning our API to https://github.com/erikbrinkman/d3-dag. I'll refactor everything later 🤤
