### ISSUE TITLE
bug(frontend): panicked in parallel e2e test

### ISSUE THREAD

**Issue by wangrunji0408** [risingwavelabs/risingwave#5210]
### Describe the bug

https://buildkite.com/risingwavelabs/pull-request/builds/7999#01831b88-7174-4196-956c-3929447eaa8c/2693-2793

```
thread 'risingwave-main' panicked at 'internal error: entered unreachable code', src/frontend/src/scheduler/distributed/stage.rs:460:22
```
full log: [frontend-4566.log](https://github.com/risingwavelabs/risingwave/files/9524321/frontend-4566.log)

**Comment by BowenXiao1999** [comment]
Discussed with @likg227 , seems can no reproduce so we decided to merge #5211 first and see whether it will happen again
