### ISSUE TITLE
bug(compaction): ManualCompactionPicker pick_l0_to_sub_level

### ISSUE THREAD

**Issue by Li0k** [risingwavelabs/risingwave#5217]
### Describe the bug

```
before

sublevel1: [SST1(KV1-epoch1)]
sublevel2: [SST2(KV1-epoch2)]
sublevel3: [SST3(KV1-epoch3)]

option.sst_ids=[SST1,SST3]

after 

sublevel1: [SST4(KV1-epoch1, KV1-epoch3)]
sublevel2: [SST2(KV1-epoch2)]
```
the select files of sublevel is SST1 and SST3. After compaction the epoch-3 will be compacted to sublevel1, At this point we will read old data in sublevel2

**Comment by fuyufjh** [comment]
Any updates?

**Comment by Li0k** [comment]
> Any updates?

There are currently no updates
