### ISSUE TITLE
micro-testing: Redpanda x JSON (Partition number: 16, Parallelism: 4)NOTE: Kafka/Redpanda is the highest priority

### ISSUE THREAD

**Issue by tabVersion** [risingwavelabs/risingwave#5221]

**Comment by fuyufjh** [comment]
waiting for Kafka simulator

**Comment by tabVersion** [comment]
@wangrunji0408 I think it has already been done?

**Comment by wangrunji0408** [comment]
Done in the simulation. But I think a real world testing is still necessary?

**Comment by tabVersion** [comment]
> Done in the simulation. But I think a real world testing is still necessary?

I think simulation should be enough. Close this issue
