### ISSUE TITLE
proposal: use concurrent BTree for in-memory state store

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#5227]
We currently still have the in-memory state store for testing purposes, which is implemented trivially. However, it'll be better if we replace it with a more efficient implementation. Some reasons:

- In-memory state store is now a `RwLock<BTreeMap>`. To start a snapshot read, the tree is cloned completely. This is okay for small data but problematic for a large amount of data.

- Our system can run correctly under a shared-nothing in-memory store for now without scaling, and it's tested that most e2e's can pass ([bz/allow-in-memory-state-store](https://github.com/risingwavelabs/risingwave/tree/bz/allow-in-memory-state-store)). As we are lack of tests without the inference of Hummock, this will be helpful for us to identify and resolve problems for both storage and streaming modules.

- We may want to add some micro benchmarks for streaming operators, and the purpose is to measure the pure computing performance. An efficient in-memory store will be suitable for this case.

Here're some candidates:
- https://crates.io/crates/concread
- https://crates.io/crates/sled
- https://crates.io/crates/rusqlite

**Comment by Little-Wallace** [comment]
@BugenZhao Does the `ConcurrentBtreeMap` need to implement the feature `Snapshot`? It seems that there are few lib which could support this feature.

**Comment by BugenZhao** [comment]
> @BugenZhao Does the `ConcurrentBtreeMap` need to implement the feature `Snapshot`? It seems that there are few lib which could support this feature.

Is SQLite with WAL mode suitable for this?

**Comment by Little-Wallace** [comment]
@BugenZhao  But SQLite is not a in-memory BTree and we can not maintain several SQLite without local ssd

**Comment by Little-Wallace** [comment]
🤔 I implemented one in-memory BTreeMap which support one-thread write and multi-thread read and also snapshot. But I have not run a benchmark to compare it with other BTreeMap. See code in https://github.com/rust-lib-project/calibur/blob/main/src/util/btree.rs

**Comment by BugenZhao** [comment]
> @BugenZhao But SQLite is not a in-memory BTree and we can not maintain several SQLite without local ssd

IIRC, SQLite can run in-memory though it might not be that memory-efficient. 🥵

**Comment by hzxa21** [comment]
> In-memory state store is now a RwLock<BTreeMap>. To start a snapshot read, the tree is cloned completely. This is okay for small data but problematic for a large amount of data.
> 
> We may want to add some micro benchmarks for streaming operators, and the purpose is to measure the pure computing performance. An efficient in-memory store will be suitable for this case.

Are we planning to measure computing performance without operator cache? If not, I think it is easier and more straight forward to use infinite size operator cache with a no-op state store for computing micro benchmark, because it is completely shared nothing without any contention.

I am uncertain about how hard it is to switch to MVCC data structure for in-memory state store. But since in-memory state store is only used for testing, I suggest we better spend less efforts on optimizing it unless we decide to adopt it in production.

**Comment by jon-chuang** [comment]
https://docs.rs/rdms/latest/rdms/mvcc/index.html

**Comment by BugenZhao** [comment]
> Are we planning to measure computing performance without operator cache?

I believe so. The correctness and performance of state recovery may also need to be tested. 😢

> I suggest we better spend less efforts on optimizing it unless we decide to adopt it in production.

Agree. It would be nice if we could find a suitable library and port the memory state store easily. However, it may not be worthwhile to put our efforts into it.

**Comment by st1page** [comment]
IIRC, there is no stream executor using the multi-version feature(read an old version's snapshot of state store). So, here is a potential method. we can just implement a "non-persistent" mode for the state table. in that mode, the state table will
- do not read or write anything into statestore
- do nothing when call it commit epoch
- panic if a read is not with the current epoch

**Comment by BugenZhao** [comment]
> we can just implement a "non-persistent" mode for the state table

We cannot create materialized view under this design. So we'll not be able to use it to run e2e tests. 😢

**Comment by BugenZhao** [comment]
With batched iterator introduced in #5322, we don't need to fully copy the kv pairs to create an iterator, and the only thing we miss is GC by the global version. As we've already added in-memory e2e tests into the CI workflow, we may also set up some micro benchmarks based on this in-memory state store to see whether the performance is sufficient. cc @lmatz 

Close this until there's more demand for performance.

**Comment by jon-chuang** [comment]
> As we are lack of tests without the inference of Hummock, this will be helpful for us to identify and resolve problems for both storage and streaming modules.

To be clear, this refers to the need for a shared concurrent in-memory store for testing of scaling and recovery, correct?

**Comment by BugenZhao** [comment]
> > As we are lack of tests without the inference of Hummock, this will be helpful for us to identify and resolve problems for both storage and streaming modules.
> 
> To be clear, this refers to the need for a shared concurrent in-memory store for testing of scaling and recovery (that is not bottlenecked by a single lock), correct?

Under multi-node configuration, we can't get shared storage with an individual embedded in-memory store. However, our system works well with shared-nothing storage now unless there's no scaling and recovery. So the purpose is mainly for basic e2e tests (already integrated now). But as we're testing scaling and recovery with deterministic simulation which actually run multiple nodes in a single process, a more efficient in-memory store may also benefit this.
