### ISSUE TITLE
meta: remove `WorkerType::Generic`

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#5238]
`WorkerType::Generic` is a generic worker type introduced by @Li0k in order to send notification to all nodes. But it seems like not needed anymore?

_Originally posted by @yezizp2012 in https://github.com/risingwavelabs/risingwave/pull/5212#discussion_r965597475_

Can we remove this? "send notification to all nodes" sounds like a flag or property, instead of a type.

**Comment by Li0k** [comment]
Currently `notify_all_nodes` not used, i gonna to remove it

**Comment by BugenZhao** [comment]
I think it's not removed yet?

https://github.com/risingwavelabs/risingwave/blob/43c35eafed404fdbf6b780ac17ce5587778125ca/proto/common.proto#L35
