### ISSUE TITLE
bug(frontend): mix START_TRANSACTION and BEGIN 

### ISSUE THREAD

**Issue by ZENOTME** [risingwavelabs/risingwave#5262]
### Describe the bug

In #2595 we ignore the START_TRANSACTION and return CommandComplete response with stmt_type START_TRANSACTION. I find the BEGIN statement with be consider as a START_TRANSACTION and it will also return CommandComplete response with stmt_type START_TRANSACTION. This seems incorrect. I run the JDBC which use the BEGIN statement and get the error `org.postgresql.util.PSQLException: Expected command status BEGIN, got START_TRANSACTION.`.

I try to return response with stmt_type BEGIN and it works. So I think we should distinguish the START_TRANSACTION and BEGIN because they have different return response.

### To Reproduce

import java.sql.*;

public class main {
    public static void main(String[] args) {
        Connection con = null;
        try {
            System.out.println("Start");

            Class.forName("org.postgresql.Driver");
            //con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/demo", "tom", "123456");
            con = DriverManager.getConnection("jdbc:postgresql://localhost:4566/dev","root","");
            con.setAutoCommit(false); // 把自动提交
            System.out.println("Opened database successfully");

            //query
            PreparedStatement pst=con.prepareStatement("select 1");
            ResultSet rs=pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();
            while (rs.next()) {
                System.out.print(rs.getString(1) + "\t");
            }

            con.close();
        } catch (Exception e) {
            System.exit(0);
        }

    }
}

### Expected behavior

Expected: 
run successfully 

Now:
```
exit with exception
org.postgresql.util.PSQLException: Expected command status BEGIN, got START_TRANSACTION.
```

**Comment by BowenXiao1999** [comment]
+1. Maybe in that early stage they do not see so far.

**Comment by ZENOTME** [comment]
I think we can separate it into two statement type.
