### ISSUE TITLE
`Failed to commit epoch` and `reset compute nodes failed`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#5274]
### Describe the bug

As the title, one WARN and one ERROR appear in the meta's log.
Then nothing keeps running, compute node seems to exit.

Compactor and Computer node's logs do not contain error/panic.

[meta-node-5690.log](https://github.com/risingwavelabs/risingwave/files/9545798/meta-node-5690.log)
[compute-node-5688.log](https://github.com/risingwavelabs/risingwave/files/9545801/compute-node-5688.log)
[compactor-6660.log](https://github.com/risingwavelabs/risingwave/files/9545802/compactor-6660.log)

Probably detected before in other issues

### To Reproduce

EC2 c5.4xlarge

Use `datagen` as the connector for nexmark's bid table and then run nexmark q10.
`work_node_parallelism = 12`
`checkpoint_interval_ms = 250`
`./risedev d`

```
CREATE SOURCE bid (                                       
    "auction" BIGINT,                                                                                                            
    "bidder" BIGINT,
    "price" BIGINT,
    "channel" VARCHAR,
    "url" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR
) with (
    connector = 'datagen',
    datagen.split.num = '12',
    datagen.rows.per.second = '2000000'
) 
ROW FORMAT JSON;

create materialized view mv_q10 as SELECT             
    auction,                                                                                                                     
    bidder,
    price,                
    date_time,
    TO_CHAR(date_time, 'YYYY-MM-DD') as date,
    TO_CHAR(date_time, 'HH:MI') as time
FROM                     
    bid;
```

Not necessarily produced every time, but high chance.

### Expected behavior

Not sure.
Seems something fails but is expected to be recovered?

### Additional context

commit 85722d34d22b3582c5f351bd54a2697f08790412

**Comment by lmatz** [comment]
Sometimes, the entire EC2 is stuck.
Cannot ssh to it.
If there is another bash session window, cannot issue commands and totally no feedback

**Comment by hzxa21** [comment]
I saw `Mon Sep 12 07:33:48 UTC 2022 [risedev]: Program exited with 137` in the compute node log.

I think exit code 137 means OOM.

**Comment by lmatz** [comment]
> I saw `Mon Sep 12 07:33:48 UTC 2022 [risedev]: Program exited with 137` in the compute node log.
> 
> I think exit code 137 means OOM.

I see, is it expected to OOM right now, i.e. a known issue, for a stateless query but with MV?
If so, maybe I close the issue now as memory management is not done yet.

**Comment by lmatz** [comment]
After #5416, this issue should not occur. 
Will check frequently in the near future.
