### ISSUE TITLE
panic when stream top N has a large limit

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#5285]
### To Reproduce

```sql
dev=> create table t(x int);
CREATE_TABLE
dev=> create materialized view mv as select generate_series(1,x,1) y from t;
CREATE_MATERIALIZED_VIEW
dev=> create materialized view mv2 as select * from mv order by y limit 5000;
CREATE_MATERIALIZED_VIEW
dev=> insert into t values (20000);
INSERT 0 1
```

```
thread 'risingwave-streaming-actor' panicked at 'assertion failed: `(left == right)`
  left: `904`,
 right: `5000`', src/common/src/array/stream_chunk.rs:90:13
```

**Comment by xxchan** [comment]
ProjectSet produced a large chunk, and TopN failed to handle large chunk & limit correctly, since here's an unused Option:

https://github.com/risingwavelabs/risingwave/blob/d82a95ec2b20ce3b4f6165b2a2cc73afa0d178f8/src/stream/src/executor/top_n_executor.rs#L129

**Comment by xxchan** [comment]
Look forward to https://github.com/rust-lang/rust/issues/71368 🤪

**Comment by BugenZhao** [comment]
We may mark the methods `#[must_use]` manually for now.

**Comment by xxchan** [comment]
> We may mark the methods `#[must_use]` manually for now.

It's `Result<Option<>>`. You can't mark it 😄
