### ISSUE TITLE
metrics(compaction): Huge compaction cancelled count showed in grafana

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#5303]
### Describe the bug

I saw a huge number of cancelled compaction task when running nexmark_q7, which looks abonormal. However, source throughput is not affected. If this is expected, I think we should have a separate panel for cancelled compaction task to avoid missing it up with success/ailed compaction task.

![image](https://user-images.githubusercontent.com/5518566/189859355-69a1671f-7b47-4eff-915c-5ae39a4705f8.png)

### To Reproduce

0. Use risedev-bench to start a 3-cn cluster.
1. Create sources:

```sql
CREATE SOURCE person (
    "id" BIGINT,
    "name" VARCHAR,
    "email_address" VARCHAR,
    "credit_card" VARCHAR,
    "city" VARCHAR,
    "state" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Person',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;

CREATE SOURCE auction (
    "id" BIGINT,
    "item_name" VARCHAR,
    "description" VARCHAR,
    "initial_bid" BIGINT,
    "reserve" BIGINT,
    "date_time" TIMESTAMP,
    "expires" TIMESTAMP,
    "seller" BIGINT,
    "category" BIGINT,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Auction',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;

CREATE SOURCE bid (
    "auction" BIGINT,
    "bidder" BIGINT,
    "price" BIGINT,
    "channel" VARCHAR,
    "url" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Bid',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;
```

2. Create MView:

```sql
CREATE MATERIALIZED VIEW nexmark_q7
AS
SELECT
    B.auction,
    B.price,
    B.bidder,
    B.date_time
from
    bid B
    JOIN (
        SELECT
            MAX(price) AS maxprice,
            window_end as date_time
        FROM
            TUMBLE(bid, date_time, INTERVAL '10' SECOND)
        GROUP BY
            window_end
    ) B1 ON B.price = B1.maxprice
WHERE
    B.date_time BETWEEN B1.date_time - INTERVAL '10' SECOND
    AND B1.date_time;
```

3. Wait for 20mins

**Comment by zwang28** [comment]
I think the cancellation is caused by no idle compactor, which is expected.

**Comment by hzxa21** [comment]
> I think the cancellation is caused by no idle compactor, which is expected.

I see. However, repeatedly triggering compaction and then cancelling it is kind of a waste of work if we don't have idle compactor. I think #5321 can help to reduce the cancellation count.

**Comment by Li0k** [comment]
I feel like we need to seperate the report label （TaskStatus）to distinguish the failure and cancelation in grafana. This helps us to find problems more directly.

**Comment by Li0k** [comment]
after #5405 

<img width="1854" alt="image" src="https://user-images.githubusercontent.com/15023748/190655109-26cb8af9-e47a-4fcc-819e-132365512e06.png">

Indeed, the reported issue has been fixed. But we can observe that the number of l0 sst is large, and duration of each compact is about 10s. IMO, the default config of `no_available_compactor_stall_sec` is a little longer.

revert the change and bench again

<img width="1897" alt="image" src="https://user-images.githubusercontent.com/15023748/190656067-ad7e1b8a-8828-4968-82ad-05fe8dbb8266.png">

Unfortunately, we found no significant change in l0 sst count

**Comment by Gun9niR** [comment]
> after #5405
> 
> <img alt="image" width="1854" src="https://user-images.githubusercontent.com/15023748/190655109-26cb8af9-e47a-4fcc-819e-132365512e06.png">
> 
> Indeed, the reported issue has been fixed. But we can observe that the number of l0 sst is large, and duration of each compact is about 10s. IMO, the default config of `no_available_compactor_stall_sec` is a little longer.
> 
> revert the change and bench again
> 
> <img alt="image" width="1897" src="https://user-images.githubusercontent.com/15023748/190656067-ad7e1b8a-8828-4968-82ad-05fe8dbb8266.png">
> 
> Unfortunately, we found no significant change in l0 sst count

But the `Compaction Throughput` has increased after revert? Also, the `Compactor Running Task Count` is much more stable before this PR.

**Comment by zwang28** [comment]
Initially I suspect the regression is related to https://github.com/risingwavelabs/risingwave/pull/5240, which changes scheduler's behavior from holding a task and waiting until an available compactor, to cancel a task if there is no available compactor. I ran a same bench as Li, the result shows https://github.com/risingwavelabs/risingwave/pull/5240 doesn't cause L0 fall behinds, as the L0 file numbers is under control. 

<img width="1461" alt="Screen Shot 2022-09-16 at 11 49 23 PM" src="https://user-images.githubusercontent.com/70626450/190680150-1fd57acf-b003-486c-9af7-f5320b103606.png">

**Comment by zwang28** [comment]
I ran a same bench as Li with an earlier commit f1a84e5d, which excludes recent refactor on compaction scheduler. The L0 file number piles up as well, though not as many as Li's result (are source throughputs in both cases close?).
```
./bin/bench --type=tpch-std --qps=800000 --scale 80.0 --query 20 --partition 12 \
    $(cat ~/risingwave-deploy/tpch-bench-args-kafka) \
    $(cat ~/risingwave-deploy/tpch-bench-args-frontend) \
    --prepare-sql ./assets/data/create_materialized_source.sql
```
<img width="1452" alt="f1a84e5d" src="https://user-images.githubusercontent.com/70626450/190837456-b7474409-8203-40ef-af7a-0e361d9f0003.png">

**Comment by zwang28** [comment]
I wonder if the L0 file piling up is caused by CPU contention, as we deploy compactor and source in the same EC2 instance.
Will confirm later.

**Comment by zwang28** [comment]
Note that there are several other commits between base version f1a84e5d and current version f903d4a6 that can affect compaction behavior. So we compare 1) f1a84e5d with 2) f1a84e5d + cherry pick 3afa7cfb and f903d4a6 (no_available_compactor_stall_sec). The result shows max L0 file number from both test are 600~800. So I think 3afa7cfb + f903d4a6 itself doesn't introduce regression.

**Comment by jon-chuang** [comment]
> But source throughput is lower.

What could be the cause of this?
