### ISSUE TITLE
refactor: functions of ArrayBuilder doesn't need to return`Result` 

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#5306]
It's impossible to fail.

https://github.com/risingwavelabs/risingwave/blob/e9a0a7b7cc6d07ba55361a4fa63203fab79ac21a/src/common/src/array/mod.rs#L103-L122

This may casues lots of consequent changes.

--------

To-do:

- [x] https://github.com/risingwavelabs/risingwave/pull/5315
- [x] https://github.com/risingwavelabs/risingwave/pull/5357
- [ ] DataChunkMerger
- [ ] Array::create_builder
- [ ] StreamChunk::from_rows
- [ ] DataChunkBuilder::append_chunk
- [ ] HashKey::deserialize_to_builders
- [ ] ListArrayBuilder:append_row_ref
- [ ] Expression::eval (?)
- [ ] Aggregator (?)

**Comment by xxchan** [comment]
The reason why the `Result` exists is:

> Previously we add Result to all functions containing memory allocation, so as to properly control memory usage. But I also find it tedious. So maybe it's a good idea to remove them.

_Originally posted by @skyzh in https://github.com/risingwavelabs/risingwave/issues/3561#issuecomment-1170649446_

> In fact, memory-control is very hard, we should reconsider them. Before that, LGTM

**Comment by fuyufjh** [comment]
And now it's clear: doing memory-control at such level is not a good practice.

**Comment by fuyufjh** [comment]
I found that the trouble caused by `ArrayBuilder`'s `Result` is more than I thought: 

`Expression::eval` seems also necessary to return a Result. The only reason for this `Result` is `ArrayBuilder`'s `Result`...

Don't know whether more cases will appear 😇

**Comment by TennyZhuang** [comment]
What a coincidence! I just talk with @liurenjie1024 at lunch today and we achieved some consensus that it's too hard to recover the state for any streaming job. 

The motivation is from #5260, in the function, I will do `builder.append()?` twice and have to recover the ChunkBuilder state in the case, so I have to record more information to do the rollback. The case is possible to handle with a simple counter, but I found that there are too many states in the steaming job to recover, e.g., append data to chunk failed so we have to rollback the previous operations in FlushBuffer, and then we may have to rollback the cache and the state table. What does it mean? If you are familiar with database transactions, you may know the terminology **flexible transaction**. For every transaction, you have to write three operations, `try`, `confirm` and `cancel`. It's similar to the failure handling in a long-running streaming job, every operation with multiple states needs to be handled carefully just like a flexible transaction, it's too hard in the streaming engine. Although we use `Result` based error handling style now, the state is definitely wrong and panic is better.

Another motivation is that allocator-based memory management can't reduce the quota of a specific executor, so we have to introduce other memory control mechanisms. If so, OOM means that there is some bug in our implementation, why not just let it panic?

As a conclusion, we will rename the original failable functions to try-prefixed, e.g. `try_append`, `try_finish` (it follows the naming conventions in the std library), and introduce the panic ones as `append`, `finish`. Feel free to use them in most cases, only use the failable one if you depend on the allocator-based OOM handling (e.g., specified in the batch engine).

**Comment by fuyufjh** [comment]
I am also doing the refactoring step-by-step. Now I am working on `finish()`

**Comment by TennyZhuang** [comment]
I'd prefer to do the renaming first, there will not be so many conflicts.

**Comment by TennyZhuang** [comment]
We have had too many pending PRs recently, so I'd prefer a fine-grained refactor with a better review.

**Comment by TennyZhuang** [comment]
> Expression::eval seems also unnecessary to return a Result. The only reason for this Result is ArrayBuilder's Result...

In fact it’s not the duty of ArrayBuilder. Just before last month, we will return many errors from Expr::eval, so I guess it’s necessary before that decision, which is much later than the ArrayBuilder using Result.

Another thing is that I still doubt that should we always eating all errors even in serving mode.

**Comment by liurenjie1024** [comment]
Why `Expression::eval` should not return `Result`? How do we handle mod 0 problem?

**Comment by fuyufjh** [comment]
Please ignore me. Let's refactor the `ArrayBuilder` first.
