### ISSUE TITLE
Prometheus OOM during sysbench testing.

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#5320]
### Describe the bug

Log:
```
[ 6572.178904] Out of memory: Killed process 44941 (prometheus) total-vm:26427276kB, anon-rss:24302176kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:47880kB oom_score_adj:0
```
![image](https://user-images.githubusercontent.com/9352536/189897038-98185443-2d4f-4da4-b082-14011d219a3b.png)

### To Reproduce

Try risingwave-bench.
https://github.com/risingwavelabs/risingwave-bench

**Comment by fuyufjh** [comment]
Too much metrics generated by batch queries?

**Comment by skyzh** [comment]
Related to https://github.com/risingwavelabs/risingwave/blob/main/src/batch/src/executor/monitor/stats.rs

**Comment by skyzh** [comment]
https://github.com/risingwavelabs/risingwave/pull/4964

**Comment by fuyufjh** [comment]
I think the executor-level stats should be disabled for local execution mode

**Comment by liurenjie1024** [comment]
>  I think the executor-level stats should be disabled for local execution mode

Agree, see #5013

**Comment by chenzl25** [comment]
> Too much metrics generated by batch queries?

Yes, it can generate hundreds of thousands of metrics during benchmarking with single thread.
