### ISSUE TITLE
compaction: improve compaction trigger

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#5321]
### Is your feature request related to a problem? Please describe.

Currently we have the following compaction triggers:
- On commit_epoch. It happens when the checkpoint process completes.
- On report_compact_task. It happens when there is a status change in a compaction task.
- On timer. It triggers every periodic_compaction_interval_sec.

This is sub-optimal because:
1. report_compact_task can happen when a compaction task is cancelled due to "no idle compactor". It is meaningless to try generating a compaction task and triggering the compaction repeatedly before compactors become available to accept compaction tasks.
2. Same as 1). It is meaningless to generate a compaction task on a timer trigger when compactors are not available to take tasks.
3. When a new compactor is added to the cluster, it needs to wait for the above triggers before it can take compaction work even though the LSM tree is already imbalance.

### Describe the solution you'd like

Modify the compaction triggers to be:
- On commit_epoch
- On compaction task status changing from PENDING to SUCCESS/FAILED
- On compactor availability changes. 

The timer trigger can still be kept as a safeguard but it is not required. 

Furthermore, we can unify get_compact_task and assign_compaction_task to avoid the overhead of cancelling the unassigned but generated compaction task when there is no available compactor.

### Additional context

> On compactor availability changes. 

Since we only limit number of ongoing compaction task on a compactor, for now, compactor availability changes simply mean an existing compactor finish a compaction task or a new compactor is added into the cluster.

In the future, if we adopt a more granular indicator for compactor load other than number of ongoing compaction task to limit compaction assignment, we also need to consider those indicators to see whether there is availability changes in compactor. For example, we may need to check whether we need to trigger a compaction on receiving the compaction task progress report.

**Comment by Gun9niR** [comment]
Also, triggering compaction on `report_compact_task` can quickly flood meta log with hundreds of thousands of lines of "no idle compactor", since the wait is removed after #5240.

**Comment by Gun9niR** [comment]
> On compaction task status changing from PENDING to SUCCESS/FAILED

We should also consider CANCELED, because after #4496, canceled tasks maybe already assigned, and we should use `compact_task_assignment` to check it.

**Comment by Gun9niR** [comment]
I'm also concerned about the fairness among compaction groups because when a task is completed, the next compaction task is triggered on the same group of that task. So it's possible that all the compactors will just be filled with tasks of one group, while another group seldom gets an available compactor because it can only request compaction on commit_epoch or timeout.

Currently fairness is kind of achieved, because compaction groups whose tasks get canceled due to "no idle compactor" will retry like crazy.

**Comment by hzxa21** [comment]
> I'm not sure if the new policy will cause a fairness problem among compaction groups because when a task is completed, the next compaction task is triggered on the same group of that task.

Good point. Only triggering compaction on one group when a compactor becomes available to take more tasks is problematic. I feel like we need a schedule state to mark whether the scheduling should pause or resume. When we have no available compactors, schedule state is changed from NORMAL to PAUSED and compaction request in the channel will not be polled. After compactor becomes available, the schedule state is changed from PAUSED to NORMAL and compaction request will be polled in order.

Note that this logic is independent of `try_send_compaction_request`, meaning that is okay to only call `try_send_compaction_request` on the same group of the task when a task is completed.

**Comment by Gun9niR** [comment]
Yes, the request channel can act as the queue. In that case, even if the task is canceled, it should still call `try_send_compaction_request` so that when compactors become available, the canceled group will be scheduled.

**Comment by StrikeW** [comment]
Please withhold this refactoring, especially the `CompactionRequestChannel`. Because the compaction testing tool which I am working on relies on existing mechanism. In short, I will use a mock channel to **swallow** all compaction requests in the phase of generating L0 SSTs. After that, I will use a dedicated channel between the testing tool and the `CompactionScheduler` to trigger compaction in a deterministic way. cc @zwang28

**Comment by Gun9niR** [comment]
> Please withhold this refactoring, especially the `CompactionRequestChannel`. Because the compaction testing tool which I am working on relies on existing mechanism. In short, I will use a mock channel to **swallow** all compaction requests in the phase of generating L0 SSTs. After that, I will use a dedicated channel between the testing tool and the `CompactionScheduler` to trigger compaction in a deterministic way. cc @zwang28

I don't think the aforementioned change involves any code change to `CompactionRequestChannel`. What will change is **when the CompactionScheduler` chooses to poll that channel**. Does your tool rely on some assumptions related to that?

**Comment by StrikeW** [comment]
It is not easy to discuss the changes I have made to the compaction scheduler here without code. I will submit a draft PR on Monday, then you can check it and see whether those changes would affect your decisions or not.

**Comment by soundOfDestiny** [comment]
so this issue has already been completely resolved by #5405 , hasn't it?

**Comment by zwang28** [comment]
> so this issue has already been completely resolved by #5405 , hasn't it?

No, https://github.com/risingwavelabs/risingwave/pull/5405 is a quick fix to avoid huge log.

**Comment by soundOfDestiny** [comment]
> > so this issue has already been completely resolved by #5405 , hasn't it?
> 
> No, #5405 is a quick fix to avoid huge log.

Which sub-optimal point remains after #5405 ?

**Comment by Gun9niR** [comment]
If wait too long, compactor will not be loaded with the maximum number of tasks. If wait too short, meta node will pick tasks that will be canceled later.

**Comment by soundOfDestiny** [comment]
> If wait too long, compactor will not be loaded with the maximum number of tasks. If wait too short, meta node will pick tasks that will be canceled later.

thank you! I was incorrect.
What if replacing #5405 with waiting until compactor available?

**Comment by Gun9niR** [comment]
> What if replacing https://github.com/risingwavelabs/risingwave/pull/5405 with waiting until compactor available?

I think that's the ideal scenario, and the schedule state is just a way to implement "waiting until compactor available".

**Comment by Gun9niR** [comment]
Actually I just took a look at the code and though about a simpler method: pick compactor then pick task. Then we can simply wait a short time (probably 1 or 2s). Because compactor picking is a relatively light-weight task (the only heavy thing about it is the compaction read lock), even if there's no idle compactor, there won't be a lot of wasted work.

**Comment by zwang28** [comment]
Alternatively, if we revert the scheduler to pick(and hold) task and wait until available compactor, then we don't need to worry about unnecessary cancellation due to NoAvailableCompactor.
The only downside is when there is finally an available compactor, it could have been assigned a better task than the previously picked one. But I think this doesn't hurt overall performance.

**Comment by zwang28** [comment]
> otherwise, we may pick the same compactor for 100 times then assign 100 tasks to it

Currently there is only one thread "compaction scheduler" that will pick/assign/send. So I think this won't be a problem?

**Comment by Gun9niR** [comment]
> > otherwise, we may pick the same compactor for 100 times then assign 100 tasks to it
> 
> Currently there is only one thread "compaction scheduler" that will pick/assign/send. So I think this won't be a problem?

Thanks for pointing out. Agree.

**Comment by Li0k** [comment]
> Actually I just took a look at the code and came up with a simpler (in terms of implementation) method: pick compactor then pick task. Then we can simply wait a short time (probably 1 or 2s). Because compactor picking is a relatively light-weight task (the only heavy thing about it is the compaction read lock), even if there's no idle compactor, there won't be a lot of wasted work.
> 
> A drawback of this approach is in order to make the whole _**pick compactor -> pick task -> assign task -> send task**_ process atomic (otherwise, we may pick the same compactor for 100 times then assign 100 tasks to it, because "pick" is a read-only process and does not update the number of tasks assigned to that compactor), we need to include _pick task_ into the compaction read lock, and I'm uncertain whether it's a good idea.

One more point to note, we set task pending after `pick_compact_task`, although make the whole process atomic, we also need to cacel the task that had been pick. Maybe we need to pay attention to the pending_task , and change the pending_status after `task_assign` ? But it is not very easy to modify here

**Comment by Gun9niR** [comment]
As pointed out by @StrikeW, his testing tool does not modify the logic of `pick_and_assign`. So I will implement a schedule state-based trigger that uses some notification mechanism instead of waiting for a fixed interval.
