### ISSUE TITLE
Compaction count on the dashboard shows meta node as instance.

### ISSUE THREAD

**Issue by Gun9niR** [risingwavelabs/risingwave#5325]
### Describe the bug

Because `compact_frequency` is now collected on meta node and the Grafana dashboard aggregate it by instance, all compaction tasks seem to be finished on meta node.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/52783948/190046167-16d49595-baf7-4ab2-a512-ee93c04b5f5b.png">

### To Reproduce

Run any query and check the dashboard.

### Expected behavior

The instance should be either the compactor's context ID or its host address. But I'm not sure which is better.

**Comment by hzxa21** [comment]
I think host address is better since worker id is an internal concept and we cannot get much from it.
