### ISSUE TITLE
Automate Longevity test setup 

### ISSUE THREAD

**Issue by sushantgupta** [risingwavelabs/risingwave#5330]
References:

1. https://singularity-data.quip.com/R9KpAwVblKYL/Proposal-Nightly-Longevity-Performance-Test
2. https://singularity-data.quip.com/UMptAO9C4J9D/Stability-Test-Guide

### Features
- [] [Automate Longevity test with 3 node cluster with TPC-H Query](https://github.com/risingwavelabs/risingwave/issues/5331)

**Comment by fuyufjh** [comment]
Hi, @sushantgupta any updates?

**Comment by sumittal** [comment]
Hi @fuyufjh , The longevity automation is already done. I will close this issue.
