### ISSUE TITLE
manual compaction misbehaves with certain user input

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#5336]
### Describe the bug

Consider this case:
L0 sublevel1: [ SST1 contains KV1-epoch1 ]
L0 sublevel2: [ SST2 contains KV1-epoch2 ]
L0 sublevel3: [ SST3 contains KV1-epoch3 ]

ManualCompactionPicker::pick_l0_to_sub_level picks SSTs from sub-levels based on `option.sst_ids`. When `option.sst_ids=[SST1,SST3]`，KV1-epoch3 will be compacted sublevel1, which will violate the KV1's epoch order.

### Expected behavior

Should pick consecutive sub-levels, or reject request if `option.sst_ids` is invalid.

**Comment by zwang28** [comment]
@Li0k @Little-Wallace

**Comment by Li0k** [comment]
> @Li0k @Little-Wallace

related to https://github.com/risingwavelabs/risingwave/issues/5217

**Comment by zwang28** [comment]
duplicate of https://github.com/risingwavelabs/risingwave/issues/5217
