### ISSUE TITLE
bug: SSTs not large enough after long-running compactions

### ISSUE THREAD

**Issue by soundOfDestiny** [risingwavelabs/risingwave#5350]
### Describe the bug

> The SST files in S3 are mostly only a few MB. Some of them are ~32MB and 64MB.
the compacted SST files should be 256MB

### To Reproduce

> You may reproduce it by running RisingWave with S3 for several hours

**Comment by soundOfDestiny** [comment]
in `MinOverlappingPicker::pick_tables`, we can only pick about `max_select_bytes` (which is 512MB) from one level.
We have 4 splits to do compaction parallel, so each split is less than 512MB/4
cc @fuyufjh 
`pub fn pick_tables(
        &self,
        select_tables: &[SstableInfo],
        target_tables: &[SstableInfo],
        level_handlers: &[LevelHandler],
    ) -> (Vec<SstableInfo>, Vec<SstableInfo>) {
        let mut scores = vec![];
        for left in 0..select_tables.len() {
            if level_handlers[self.level].is_pending_compact(&select_tables[left].id) {
                continue;
            }
            let mut overlap_info = self.overlap_strategy.create_overlap_info();
            let mut select_file_size = 0;
            for (right, table) in select_tables.iter().enumerate().skip(left) {
                if level_handlers[self.level].is_pending_compact(&table.id) {
                    break;
                }
                if select_file_size > self.max_select_bytes {
                    break;
                }`

**Comment by fuyufjh** [comment]
> We have 4 splits to do compaction parallel, so each split is less than 512MB/4

I don't quite understand this design. Counter-intuitive to me 😇

**Comment by soundOfDestiny** [comment]
> > We have 4 splits to do compaction parallel, so each split is less than 512MB/4
> 
> I don't quite understand this design. Counter-intuitive to me 😇

Input of compaction is 512MB.
We want to do compaction parallel so we start 4 threads and each thread handle 1/4 of compaction input.
We divide input key range into 4 part so that each thread can handle one part.
Each thread will generate its output SST itself.

**Comment by hzxa21** [comment]
Any updates? @Little-Wallace

**Comment by Little-Wallace** [comment]
@hzxa21  We would not split task with 4 parallel if the size of compaction files is not enough large. But it may still leave a small file if the total file size is just more than file cut size. For example, if the size of all files is 129MB, and the cut limit is 128MB, we would leave two files, one is 128MB while the other is only 1MB.

**Comment by fuyufjh** [comment]
I think this is acceptable at least for now. Just to confirm that we have fixed the original issue, right? If so, let's close the issue.
