### ISSUE TITLE
bug: CN panicked after restarting meta

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#5393]
### Describe the bug

CN panicked when restarting meta node:
```
thread 'risingwave-streaming-actor' panicked at 'assertion failed: `(left == right)`
  left: `3019594249469952`,
 right: `3019599018917888`', src/stream/src/executor/hash_agg.rs:431:21
stack backtrace:
2022-09-16T06:43:44.487858Z  WARN risingwave_connector::source::base: failed to send next event to reader, exit
thread 'risingwave-streaming-actor' panicked at 'assertion failed: `(left == right)`
  left: `3019594249469952`,
 right: `3019599018917888`', src/stream/src/executor/hash_agg.rs:431:21
thread 'risingwave-streaming-actor' panicked at 'assertion failed: `(left == right)`
  left: `3019594249469952`,
 right: `3019599018917888`', src/stream/src/executor/hash_agg.rs:431:21
thread 'risingwave-streaming-actor' panicked at 'assertion failed: `(left == right)`
  left: `3019594249469952`,
 right: `3019599018917888`', src/stream/src/executor/hash_agg.rs:431:21
```

### To Reproduce

0. Modify risedev.yml to use s3 and run `risedev dev full`
1. Create sources:

```sql
CREATE SOURCE person (
    "id" BIGINT,
    "name" VARCHAR,
    "email_address" VARCHAR,
    "credit_card" VARCHAR,
    "city" VARCHAR,
    "state" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Person',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;

CREATE SOURCE auction (
    "id" BIGINT,
    "item_name" VARCHAR,
    "description" VARCHAR,
    "initial_bid" BIGINT,
    "reserve" BIGINT,
    "date_time" TIMESTAMP,
    "expires" TIMESTAMP,
    "seller" BIGINT,
    "category" BIGINT,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Auction',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;

CREATE SOURCE bid (
    "auction" BIGINT,
    "bidder" BIGINT,
    "price" BIGINT,
    "channel" VARCHAR,
    "url" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Bid',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;
```

2. Create MView:

```sql
CREATE MATERIALIZED VIEW nexmark_q7
AS
SELECT
    B.auction,
    B.price,
    B.bidder,
    B.date_time
from
    bid B
    JOIN (
        SELECT
            MAX(price) AS maxprice,
            window_end as date_time
        FROM
            TUMBLE(bid, date_time, INTERVAL '10' SECOND)
        GROUP BY
            window_end
    ) B1 ON B.price = B1.maxprice
WHERE
    B.date_time BETWEEN B1.date_time - INTERVAL '10' SECOND
    AND B1.date_time;
```

3. Wait for 5mins and kill meta.

4. Wait for 2mins and restart meta.

### Additional context

commit: `dfc7a8a57e9efdb0851cc5019d3f56c38e23c225`

[log.tar.gz](https://github.com/risingwavelabs/risingwave/files/9581558/log.tar.gz)

**Comment by hzxa21** [comment]
@xxhZs and I discussed offline. We think this bug is caused by meta skipping one epoch in the recovery process on meta restart:
https://github.com/risingwavelabs/risingwave/blob/c441097b59a655ea2577a1eddfb8f646eb9b0b08/src/meta/src/barrier/mod.rs#L513

We think that this is unnecessary.

**Comment by wangrunji0408** [comment]
The same problem was found in #5244 and @yezizp2012 is fixing that.

**Comment by yezizp2012** [comment]
I'm working on this, there're several problems during recovery when meta restart. In current implementation, this assertion is not necessary since we already support epoch check in `WrapperExecutor`, which will ignore stop barrier when check. Anyway, I will change the implementation for stopping all actors and not through stop barrier. This assertion will works fine.

**Comment by hzxa21** [comment]
> I'm working on this, there're several problems during recovery when meta restart. In current implementation, this assertion is not necessary since we already support epoch check in `WrapperExecutor`, which will ignore stop barrier when check. Anyway, I will change the implementation for stopping all actors and not through stop barrier. This assertion will works fine.

Are you planning to use a control channel to force stop an actor?

**Comment by yezizp2012** [comment]
> > I'm working on this, there're several problems during recovery when meta restart. In current implementation, this assertion is not necessary since we already support epoch check in `WrapperExecutor`, which will ignore stop barrier when check. Anyway, I will change the implementation for stopping all actors and not through stop barrier. This assertion will works fine.
> 
> Are you planning to use a control channel to force stop an actor?

I was planning to do it in this way before, but now I found a way to let actor exit by itself when meet any errors without panic. Then for meta restarts, I will stop all actors by aborting actors directly, which will not cause any panics and any other problems I think.

**Comment by hzxa21** [comment]
> > > I'm working on this, there're several problems during recovery when meta restart. In current implementation, this assertion is not necessary since we already support epoch check in `WrapperExecutor`, which will ignore stop barrier when check. Anyway, I will change the implementation for stopping all actors and not through stop barrier. This assertion will works fine.
> > 
> > 
> > Are you planning to use a control channel to force stop an actor?
> 
> I was planning to do it in this way before, but now I found a way to let actor exit by itself when meet any errors without panic. Then for meta restarts, I will stop all actors by aborting actors directly, which will not cause any panics and any other problems I think.

I see. How about recovery be triggered by non-actor error? For example, global barrier manager will send BarrierCompleteReuqest to CN and try invoking a storage sync when barrier collection completes. If there is an error occurred when processing BarrierCompleteReuqest (e.g. storage sync error), the actor may not see this error in its loop but we still need to trigger the recovery process.

**Comment by yezizp2012** [comment]
> > > > I'm working on this, there're several problems during recovery when meta restart. In current implementation, this assertion is not necessary since we already support epoch check in `WrapperExecutor`, which will ignore stop barrier when check. Anyway, I will change the implementation for stopping all actors and not through stop barrier. This assertion will works fine.
> > > 
> > > 
> > > Are you planning to use a control channel to force stop an actor?
> > 
> > 
> > I was planning to do it in this way before, but now I found a way to let actor exit by itself when meet any errors without panic. Then for meta restarts, I will stop all actors by aborting actors directly, which will not cause any panics and any other problems I think.
> 
> I see. How about recovery be triggered by non-actor error? For example, global barrier manager will send BarrierCompleteReuqest to CN and try invoking a storage sync when barrier collection completes. If there is an error occurred when processing BarrierCompleteReuqest (e.g. storage sync error), the actor may not see this error in its loop but we still need to trigger the recovery process.

Well, recovery is triggered in two cases: 1. meta restarts; 2. failure occurrs when global barrier manager sends `InjectBarrierRequest` or `BarrierCompleteReuqest`. So if there's an error when processing `BarrierCompleteReuqest` (e.g. storage sync error) , the error will be returned to global barrier manager, and the recovery process will be triggered as well IIUC.

**Comment by hzxa21** [comment]
> > > > > I'm working on this, there're several problems during recovery when meta restart. In current implementation, this assertion is not necessary since we already support epoch check in `WrapperExecutor`, which will ignore stop barrier when check. Anyway, I will change the implementation for stopping all actors and not through stop barrier. This assertion will works fine.
> > > > 
> > > > 
> > > > Are you planning to use a control channel to force stop an actor?
> > > 
> > > 
> > > I was planning to do it in this way before, but now I found a way to let actor exit by itself when meet any errors without panic. Then for meta restarts, I will stop all actors by aborting actors directly, which will not cause any panics and any other problems I think.
> > 
> > 
> > I see. How about recovery be triggered by non-actor error? For example, global barrier manager will send BarrierCompleteReuqest to CN and try invoking a storage sync when barrier collection completes. If there is an error occurred when processing BarrierCompleteReuqest (e.g. storage sync error), the actor may not see this error in its loop but we still need to trigger the recovery process.
> 
> Well, recovery is triggered in two cases: 1. meta restarts; 2. failure occurrs when global barrier manager sends `InjectBarrierRequest` or `BarrierCompleteReuqest`. So if there's an error when processing `BarrierCompleteReuqest` (e.g. storage sync error) , the error will be returned to global barrier manager, and the recovery process will be triggered as well IIUC.

I see. I thought by "I found a way to let actor exit by itself when meet any errors without panic", you mean let actor exit by itself only if the error happens inside an actor lol.
