### ISSUE TITLE
array subscript doesn't have correct precedence

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#5409]
### To Reproduce

```sql
dev=> select 1 = (array[1])[1];
ERROR:  QueryError: Feature is not yet implemented: Equal[Int32, List]
Tracking issue: https://github.com/risingwavelabs/risingwave/issues/112
```

### Expected behavior

pg:
```sql
postgres=# select 1 = (array[1])[1];
 ?column?
----------
 t
(1 row)
```

**Comment by CAJan93** [comment]
To clarify, the desired precedence is as follows: 

`select 1 = (array[1])[1]` should evaluate `(array[1])[1]` first, resulting in `select 1 = 1`, which can be compared. 

The current behaviour is: 

`select 1 = (array[1])[1]` is evaluating `select 1 = array[1]` first, resulting in `Equal[Int32, List]`. 

We can achieve the desired behaviour if we give array access a higher precedence.

**Comment by CAJan93** [comment]
I did not find a RW documentation about what the desired operator precedence is. I assume that it is the same as in Postgres (see [PSQL Docs](https://www.postgresql.org/docs/7.2/sql-precedence.html)). Please correct me if I am wrong @xxchan @fuyufjh

**Comment by xxchan** [comment]
Yes, we try to be compatible with PG if not otherwise specified

**Comment by CAJan93** [comment]
Different ASTs for the working and broken query respectively 

```
select (array[1])[1] >= 1; # working
AST: [Query(Query { with: None, body: Select(Select { distinct: false, projection: [UnnamedExpr(BinaryOp { left: ArrayIndex { obj: Nested(Array([Value(Number("1"))])), index: Value(Number("1")) }, op: GtEq, right: Value(Number("1")) })], from: [], lateral_views: [], selection: None, group_by: [], having: None }), order_by: [], limit: None, offset: None, fetch: None })]

select 1 <= (array[1])[1]; # broken
AST: [Query(Query { with: None, body: Select(Select { distinct: false, projection: [UnnamedExpr(ArrayIndex { obj: BinaryOp { left: Value(Number("1")), op: LtEq, right: Nested(Array([Value(Number("1"))])) }, index: Value(Number("1")) })], from: [], lateral_views: [], selection: None, group_by: [], having: None }), order_by: [], limit: None, offset: None, fetch: None })]
```

As you can see the broken query has the array index operator as the root node, instead of the binary `>=` operator.

**Comment by CAJan93** [comment]
PR is merged (see [PR](https://github.com/risingwavelabs/risingwave/pull/5673))
