### ISSUE TITLE
Investigate skip keys count too large in nexmark Q7

### ISSUE THREAD

**Issue by Little-Wallace** [risingwavelabs/risingwave#5418]
### Describe the bug

Investigate skip keys increase quickly. It seems to slow the throughput of our system.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/16376959/190960137-315dbeb0-a75f-4e27-8b37-2e37d98c6729.png">

![image](https://user-images.githubusercontent.com/16376959/190961353-75753aee-ee51-41a3-b4ac-3be664efa1ab.png)

### To Reproduce

run Nextmark Q7

### Expected behavior

The number of skip keys shall be stable

**Comment by fuyufjh** [comment]
May caused by the `Max` aggregation. The maximum of each time window should be updated frequently, and the updates are streamed into HashJoin to update its state.

**Comment by Little-Wallace** [comment]
> Discussed offline. We think updating the metric in sstable iterator can be problematic.
> 
> https://github.com/risingwavelabs/risingwave/blob/18eed8fa8543f51c244aa8c0ee4c01049020ce7b/src/storage/src/hummock/sstable/forward_sstable_iterator.rs#L115

This bug has been fixed

**Comment by Little-Wallace** [comment]
The `skip_key_count` comes from ` __internal_nexmark_q7_1_hashjoinright_1007`. It was caused by `SELECT
        MAX(price) AS maxprice`

**Comment by hzxa21** [comment]
> The `skip_key_count` comes from ` __internal_nexmark_q7_1_hashjoinright_1007`. It was caused by `SELECT MAX(price) AS maxprice`

I think this is becuase we don't clean up the state after the window is closed.

**Comment by Li0k** [comment]
bench nexmark q7 with #5492  

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/15023748/191791218-1bc44a8a-0c63-42b2-8c47-dd7cf2f25468.png">

The multiplier of skip_key_multi_version and skip_key_delete gradually increases over time
