### ISSUE TITLE
fix: associate notification version with epoch

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#5446]
The notification mechanism is completely asynchronous for now, as it was initially introduced for catalog updates. However, we've found some cases where we must build an association between the notification version and the system epoch.

#### Batch query when scaling

We prefer to schedule the scan tasks to the corresponding worker(parallel unit) by vnode mapping of the `Materialize` executors. After we support the barrier and checkpoint decoupling (#4966), this assumption must be kept. Besides, the in-memory state store e2e (#5322) also tests this.

It's possible that a batch query is scheduled when scaling, where we get an epoch **after** the scaling, while the vnode mapping from the notification manager has not received updates yet. As the uncheckpointed data is invisible to other compute nodes, we will fail to scan the data from some migrated/rebalanced partitions.

#### Batch query when dropping

Similar to the above, we may be able to scan the dropped table whose data is being cleaned-up by the storage, due to asynchronous updates of catalog deletion in this frontend. This may cause wrong results or even break some assumptions in batch executors.

### Solution

As epoch maintains the sequential consistency of DDLs and configuration changes, we may associate a "minimal notification version" with each epoch. After the frontend pins an epoch for a batch task, it must wait for this version to be synced before scheduling.

cc @liurenjie1024 @yezizp2012 @zwang28 @st1page 🤩

**Comment by hzxa21** [comment]
Strong +1.

Btw, do we have a case that notification version increases without epoch increases? In other words, can we use epoch as the notification version?

**Comment by BugenZhao** [comment]
> Btw, do we have a case that notification version increases without epoch increases? In other words, can we use epoch as the notification version?

Yes, for those changes not relevant to materialized views, like `create/drop source`, `create/drop database`, or even hummock version updates?

**Comment by BugenZhao** [comment]
I think we must find a way to update & read a snapshot of the combination of Hummock snapshot (epoch) and the vnode mapping **atomically**. Currently, they're totally independent in both the frontend and the meta committing the barrier. However, any case of mismatch will lead to some problems.

- Old (`current`) snapshot, new mapping: we'll `try_wait_epoch` for a `Current` epoch on a wrong partition, which will fail on assertion.
https://github.com/risingwavelabs/risingwave/blob/75468b4104ede915588173b9b0373489a5ceb5d2/src/storage/src/hummock/local_version/local_version_manager.rs#L226-L235
- New (`current`) snapshot, old mapping: some data will be invisible remotely, which leads to wrong results.

So I guess some major refactoring might be necessary. 🤔 cc @hzxa21 @yezizp2012 @st1page

**Comment by fuyufjh** [comment]
@fuyufjh

**Comment by fuyufjh** [comment]
Is this closed by #5999?

**Comment by BugenZhao** [comment]
> Is this closed by #5999?

Nope. They're unrelated. I think this might be closed by #6250.

**Comment by zwang28** [comment]
Please correct me if I am wrong, for the "Batch query when dropping" case, I think even we have used a set of consistent but **stale** epoch + catalog + any other metadata, query anomaly can still happen. Because currently storage doesn't guarantee data availability or consistency of a dropped table. 
Specifically, once [drop_materialized_view](https://github.com/risingwavelabs/risingwave/blob/main/src/meta/src/rpc/service/ddl_service.rs#L268) has succeeded, related table ids are removed from "compaction group", and subsequent compaction is allowed to drop KVs of these tables. In other words, frontend pinning an old snapshot doesn't help here.
@hzxa21 @Little-Wallace

**Comment by BugenZhao** [comment]
Can we close it with #7042? cc @zwang28

**Comment by zwang28** [comment]
> Can we close it with https://github.com/risingwavelabs/risingwave/pull/7042? cc @zwang28

#7024 addresses the "Batch query when scaling" case.

I'm checking whether the "Batch query when dropping" case is correctly handled. Will open another tracking issue when required.
