### ISSUE TITLE
opt(source): Source performance does not seem to scale linearly with cores

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#5455]
Source performance seems not to scale linearly with 6 threads v.s. 12 threads with materialized view turned off. It could be due to SMT as the bench was run on 16vCPU x86 machine. We should test source throughput of 4T, 6T, 8T, 12T and 16T, 24T on a 32vCPU machine to see if there may be some non-linearity if SMT is not interfering.

CC @lmatz

**Comment by BugenZhao** [comment]
Which kind of source did you test? 🤔

**Comment by lmatz** [comment]
not Kafka source? It's the computation part that does not scale.

**Comment by tabVersion** [comment]
any update?

**Comment by jon-chuang** [comment]
No updates for now, we will continue to investigate alongside performance of Nexmark queries. Maybe this is better tracked in the performance-related docs. So I will close it for now.

**Comment by BugenZhao** [comment]
If you mean the nexmark datagen source, I think @wangrunji0408 is working on the optimization now. 🚀 https://github.com/risingwavelabs/risingwave/issues/4555
