### ISSUE TITLE
Better explain format: split fields into different lines

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#5460]
Currently all fields are in the same line, and it can be extremely long, e.g., the longest line length is 1293 in `nextmark.yaml` and 990 in `tpch.yaml`

Just one possible format (from databend):
![image](https://user-images.githubusercontent.com/37948597/191326183-913ae465-242e-4500-bd8f-c45fe3ae8e5b.png)

**Comment by ice1000** [comment]
Working on it!!!!!!!!!!!!

**Comment by stdrc** [comment]
@xxchan Is this really _completed_? AFAIK our explain string still print fields in one line.
