### ISSUE TITLE
Split planner test into smaller files

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#5461]
Discussion from https://github.com/risingwavelabs/risingwave/pull/5454

The tpch.yaml has 5463 lines and sized 418KB, but I'm not sure whether it is a problem.

Splitting can make it easier to locate a specific test case. But to support it, we may need to support cross-file `before` (just like sqllogictest `include`) to include create table statements.

**Comment by skyzh** [comment]
What about https://github.com/risinglightdb/sqlplannertest-rs 🥵

**Comment by xxchan** [comment]
> What about [risinglightdb/sqlplannertest-rs](https://github.com/risinglightdb/sqlplannertest-rs) 🥵

IIUC It's largest difference is separating test input and output, which can make it easier to modify tests. IMO we can adopt it whenever we want. Does it help to resolve the problem in this issue? 🤔

**Comment by xxchan** [comment]
> Does it help to resolve the problem in this issue?

Oh, we can generate outputs in different files for one input file! 🥸

**Comment by fuyufjh** [comment]
@xxchan Any updates? Shall we close it?

Assigned to you to make sure it's tracked.

**Comment by xxchan** [comment]
No progress yet. I don't have enough time recently and will postpone it. 🥵
