### ISSUE TITLE
Tracking issues: Support vscode-postgres plugin

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#5477]
[vscode-postgres](https://github.com/Borvik/vscode-postgres) is the most popular plugin for postgres in the vscode marketplace. It’s able to connect to a Pg instance, highlight the query syntax, and display results. It provides us with an entry-level UI to pg, while still useful in most cases.

This is a long-term task, but still, we expect it can be fully released before the GA stage.

- [ ] #5478
- [ ] #5479
- [ ] SQL: Support vscode-postgres query 3 ()

**Comment by fuyufjh** [comment]
... and I don't think vscode-postgres is a good choice for users to develop on RisingWave. It lacks of very basic functions for streaming, such as view the execution graph or monitoring. That should be the job of the cloud platform.

**Comment by xxchan** [comment]
Close as not planned now. Reopen if needed in the future.
