### ISSUE TITLE
failed to parse column 'date_time' from json

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#5481]
### Describe the bug

```
ERROR risingwave_source::parser::json_parser: failed to process value ({"_row_id":23957,"date_time":"2022-09-21 09:45:47.387344020"}): failed to parse column 'date_time' from json: Parse error: Can't cast string to timestamp (expected format is YYYY-MM-DD HH:MM:SS[.MS] or YYYY-MM-DD HH:MM or YYYY-MM-DD or ISO 8601 format)
```

### To Reproduce

On EC2,
`./risedev d full`

```
create source s1 (date_time Timestamp) with (connector = 'datagen') row format json;
create materialized view m1 as select * from s1;
```

commit 9520c748a90d201bc9c716feff45333f7aa49356

No error on my laptop..

@jon-chuang

**Comment by lmatz** [comment]
Test all data types generation(connector = datagen) in e2e tests

**Comment by jon-chuang** [comment]
I get the error on my Linux, x86 laptop. I guess the issue must be risedev build on mac.

**Comment by jon-chuang** [comment]
Actually, it is weird if you can't reproduce locally. Please try again to confirm.
