### ISSUE TITLE
test all data types generation(connector = `datagen`) in e2e tests

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#5482]
test all data types generation(connector = `datagen`) in e2e tests

_Originally posted by @lmatz in https://github.com/risingwavelabs/risingwave/issues/5481#issuecomment-1253508467_

**Comment by fuyufjh** [comment]
@jon-chuang any updates?

**Comment by jon-chuang** [comment]
Types:
- [ ] struct
- [ ] timestamp

**Comment by fuyufjh** [comment]
Any updates?
