### ISSUE TITLE
use cargo workspace inheritance

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#5507]
https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds

The feature is stabilized, and useful when we bump our version or edition.

**Comment by TennyZhuang** [comment]
It’s available on our toolchain, but I’d prefer to bump our toolchain first.

**Comment by xxchan** [comment]
blocked by https://github.com/risingwavelabs/risingwave/pull/5119

**Comment by xxchan** [comment]
close by https://github.com/risingwavelabs/risingwave/pull/6423
