### ISSUE TITLE
Insert into part of columns

### ISSUE THREAD

**Issue by doki23** [risingwavelabs/risingwave#5521]
### Is your feature request related to a problem? Please describe.

> The column where you want to insert corresponding values. Currently, you must provide all columns in the table in order or leave this field empty.

As the doc saying, we can't insert part of columns of tables. It's a little bit inconvenient.

### Describe the solution you'd like

support insert part of columns like
```sql
insert into table_a (col_0) values (0);
```
while table_a has col_1, col_2...

**Comment by lmatz** [comment]
Related: #4046

**Comment by fuyufjh** [comment]
duplicated https://github.com/risingwavelabs/risingwave/issues/4046
