### ISSUE TITLE
bug(test): handle pg connection error after killing frontend

### ISSUE THREAD

**Issue by wangrunji0408** [risingwavelabs/risingwave#5543]
After killing a frontend in the simulation, the pg client will panic at a connection error:

```
panicked at 'Postgres connection error: Error { kind: Closed, cause: None }', src/tests/simulation/src/main.rs:346:30
```

We should handle this error and add a retry.

**Comment by neverchanje** [comment]
+1. The failure is an expected behavior. You can retry with an exponential backoff policy and after a certain time limit it still needs to fail. Because it will indicate that the cluster could have been unrecoverable.
