### ISSUE TITLE
refactor(stream TopN): separate the actual order-by columns and the PK columns

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#5564]
https://github.com/risingwavelabs/risingwave/pull/4682 introduced `catalog.Table` in the proto and infer the table in fe. What's your idea? cc @shmiwy @skyzh

_Originally posted by @xxchan in https://github.com/risingwavelabs/risingwave/pull/5551#discussion_r979841297_

**Comment by skyzh** [comment]
We can record pk / order by information along with the state table 😋

**Comment by fuyufjh** [comment]
Any updates?

**Comment by fuyufjh** [comment]
@xxchan Since this has been delayed twice, can you help to work out or reassign it?

**Comment by xxchan** [comment]
Working on it. The code is indeed not easy to understand now (so many "keys"). 🤡
