### ISSUE TITLE
Should use different hash for exchange and operators

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#5579]
### Is your feature request related to a problem? Please describe.

We should use different hash for exchange and operators, both for streaming and batch queries. Otherwise, the hash collision rate in the operator's cache is likely to be much higher than expected.

### Describe the solution you'd like

A simple solution is to use the current hash function to generate the u64 hash value, but use the prefix for Exchange and suffix for Operator, rather than using suffix everywhere (which is mainly done by `hash mod 2^N`)

### Describe alternatives you've considered

Alternatively, you may also introduce a completed new hash function for the operators.

### Additional context

You may search for keyword `Crc32FastBuilder` to find out all the usage of hashing.

**Comment by BowenXiao1999** [comment]
Did not get this too much. Why use same hasher for exchange and other compute executor (for example, batch hash_agg) is bad? 🤔

**Comment by yuhao-su** [comment]
> Did not get this too much. Why use same hasher for exchange and other compute executor (for example, batch hash_agg) is bad? 🤔

Hashmap contains value shuffled from upstream. If we use the same hasher, the hash value in the operator hashmap is determined by the upstream dispatcher, in this case only part of the hash slot can be used.

**Comment by BowenXiao1999** [comment]
Suppose data: [1, 2, 3, 4, 5, 6, 7, 8, 1, 2], assume the hash shuffled from exchange divide them into PU1: [1, 3, 5, 7, 1],  PU2: [2,4, 6, 8, 2]. 

If we adopt same Hasher for opeartor, we get 4 hash entries for both PU1 and PU2. What magic will be if we adopt different hasher? 🤔

**Comment by fuyufjh** [comment]
> Suppose data: [1, 2, 3, 4, 5, 6, 7, 8, 1, 2], assume the hash shuffled from exchange divide them into PU1: [1, 3, 5, 7, 1], PU2: [2,4, 6, 8, 2].
> 
> If we adopt same Hasher for opeartor, we get 4 hash entries for both PU1 and PU2. What magic will be if we adopt different hasher? 🤔

The problem is inside the hash table. In this example, assume the hash table has 4 buckets aka. slots, then it will be like:

PU1:

```
bucket 0: <empty>
bucket 1: 1 5 1
bucket 2: <empty>
bucket 3: 3 7
```

PU2:

```
bucket 0: 4 8
bucket 1: <empty>
bucket 2: 2 6 2
bucket 3: <empty>
```

See. Half of these buckets are empty. 

The problem will be much more severe with more parallel units. For example, if there are 32 parallel units, then 31/32 (96.875%) buckets are empty.

**Comment by fuyufjh** [comment]
@skyzh Any progress?
