### ISSUE TITLE
RFC: add support for UNIX timestamp input

### ISSUE THREAD

**Issue by nanderstabel** [risingwavelabs/risingwave#5588]
### Background

Often by default streaming data will have DATE/TIME types converted to UNIX timestamp. For example, when creating a table in Postgres with a TIMESTAMP type field...
```
simple_db=# \d t
                           Table "public.t"
 Column |            Type             | Collation | Nullable | Default 
--------+-----------------------------+-----------+----------+---------
 id     | bigint                      |           | not null | 
 t      | timestamp without time zone |           |          | 
Indexes:
    "t_pkey" PRIMARY KEY, btree (id)
Publications:
    "dbz_publication"

simple_db=# select * from t;
 id |             t             
----+---------------------------
  1 | 2022-09-27 08:32:57.14096
(1 row)
``` 
...and having a debezium connector creating a topic with the following (read) event...
```
{"schema":{},"payload":{"before":null,"after":{"id":1,"t":1664267577140960},"source":{"version":"1.9.5.Final","connector":"postgresql","name":"postgres","ts_ms":1664268325363,"snapshot":"true","db":"simple_db","sequence":"[null,\"24558624\"]","schema":"public","table":"t","txId":1334,"lsn":24558624,"xmin":null},"op":"r","ts_ms":1664268325364,"transaction":null}}
```
...you can see that the `t` timestamp data is converted to a UNIX timestamp:
```
"after":{
   "id":1,
   "t":1664267577140960
}
```

This event will be skipped in RW since we do not accept parsing UNIX timestamps at the moment:
```
WARN risingwave_source::connector_source: message parsing failed internal error: failed to parse column 't' from json: expect timestamp, but found 1664267577140960, skipping
```

There are workarounds to deal with this, for example Kafka Connect has a [timestamp converter](https://docs.confluent.io/platform/current/connect/transforms/timestampconverter.html#example) that can convert the UNIX timestamp back to a formatted date string. However, in my opinion this is not very user friendly. That's why I suggest to add support for UNIX timestamp input (for TIMESTAMP, DATE and TIME) along our current formatted date string parsing.

### Design

Obviously, we already support casting str to TIMESTAMP/DATE/TIME:
```
#[inline(always)]
pub fn str_to_date(elem: &str) -> Result<NaiveDateWrapper> {
    Ok(NaiveDateWrapper::new(parse_naive_date(elem)?))
}

#[inline(always)]
pub fn str_to_time(elem: &str) -> Result<NaiveTimeWrapper> {
    Ok(NaiveTimeWrapper::new(parse_naive_time(elem)?))
}

#[inline(always)]
pub fn str_to_timestamp(elem: &str) -> Result<NaiveDateTimeWrapper> {
    Ok(NaiveDateTimeWrapper::new(parse_naive_datetime(elem)?))
}
```
In order to parse the UNIX style timestamps we can utilize the [unix-ts](https://crates.io/crates/unix-ts) crate. This crate supports parsing to `DateTime` and `NaiveDateTime`:

_"If the chrono feature is enabled, unix-ts also supports converting to chrono::DateTime and chrono::NaiveDateTime. This is done through the to_datetime and to_naive_datetime methods."_

This way we can simply add the following casting functions:
```
fn unix_to_date(elem: int32) -> Result<NaiveDateWrapper>
fn unix_to_time(elem: int64) -> Result<NaiveDateWrapper>
fn unix_to_timestamp(elem: int64) -> Result<NaiveDateWrapper>
```

**Comment by neverchanje** [comment]
1. Will Debezium convert date/time to UNIX timestamps (integers) as well? 
2. I think the function argument of unix_to_timestamp should be integer, since it uses json integer type.

```json
"after":{
   "id":1,
   "t":1664267577140960
}
```

**Comment by xiangjinwu** [comment]
As the json above suggests, that field is a number (`"t":1664267577140960`) rather than a string (`"t":"1664267577140960"`).

Shall we implement the `to_timestamp` [function](https://www.postgresql.org/docs/current/functions-datetime.html#:~:text=39%3A53.662522%2D05-,to_timestamp,-(%20double%20precision ) and invoke it automatically in source when the input is a json number?

**Comment by neverchanje** [comment]
> invoke it automatically in source when the input is a json number?

I don't think we should infer a timestamp from a number in normal JSON. But we can do that when it's Debezium JSON.

**Comment by nanderstabel** [comment]
> 1. Will Debezium convert date/time to UNIX timestamps (integers) as well?
> 2. I think the function argument of unix_to_timestamp should be integer, since it uses json integer type.
> 
> ```json
> "after":{
>    "id":1,
>    "t":1664267577140960
> }
> ```

1. Yes both TIME and DATE are converted to integers as well:
```
               {
                  "type":"int64",
                  "optional":true,
                  "name":"io.debezium.time.MicroTimestamp",
                  "version":1,
                  "field":"ts"
               },
               {
                  "type":"int32",
                  "optional":true,
                  "name":"io.debezium.time.Date",
                  "version":1,
                  "field":"d"
               },
               {
                  "type":"int64",
                  "optional":true,
                  "name":"io.debezium.time.MicroTime",
                  "version":1,
                  "field":"t"
               }
```
2. Indeed, I forgot to change the argument type to integers 😅 

> By the way, we should clearly define the unit: is it in seconds, milliseconds or microseconds?

That's right it should be clearly defined. The above example is for date/time/timestamp in Postgres. So, Postgres -> Debezium:
- `TIMESTAMP`: microseconds since epoch
- `DATE`: days
- `TIME`: microseconds

However, I am not sure yet how Debezium converts time/date datatypes from other relational databases. For example in MySQL, `DATETIME(3)` is in milliseconds, while `DATETIME(6)` is in microseconds.

**Comment by nanderstabel** [comment]
> I don't think we should infer a timestamp from a number in normal JSON.

Why not for JSON? Is it because for JSON in many cases there won't be a spec for converting timestamps to integers and vice versa? If so, then yes I also think that casting UNIX to TIMESTAMP should be limited DEBEZIUM JSON in the source connector. And then I guess implementing `to_timestamp` like @xiangjinwu suggested is the best solution 👍

**Comment by fuyufjh** [comment]
done
