### ISSUE TITLE
bug: streaming hash join `EntryState` OccupiedError when insert

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#5609]
### Describe the bug

compute-node-1  | thread 'risingwave-streaming-actor' panicked at 'called `Result::unwrap()` on an `Err` value: OccupiedError { key: [0, 128, 13, 6, 195, 1], old_value: EncodedJoinRow { row: [1, 195, 6, 13, 0, 0], degree: 853699 }, new_value: EncodedJoinRow { row: [1, 195, 6, 13, 0, 0], degree: 853699 } }', src/stream/src/executor/managed_state/join/join_entry_state.rs:66:44
compute-node-1  | stack backtrace:
compute-node-1  |    0: rust_begin_unwind
compute-node-1  |              at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
compute-node-1  |    1: core::panicking::panic_fmt
compute-node-1  |              at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
compute-node-1  |    2: core::result::unwrap_failed
compute-node-1  |              at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/result.rs:1814:5
compute-node-1  |    3: core::result::Result<T,E>::unwrap
compute-node-1  |              at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/result.rs:1107:23
compute-node-1  |    4: risingwave_stream::executor::managed_state::join::join_entry_state::JoinEntryState::insert
compute-node-1  |              at ./ebs/risingwave/src/stream/src/executor/managed_state/join/join_entry_state.rs:66:9
compute-node-1  |    5: risingwave_stream::executor::managed_state::join::JoinHashMap<K,S>::fetch_cached_state::{{closure}}
compute-node-1  |              at ./ebs/risingwave/src/stream/src/executor/managed_state/join/mod.rs:423:17
compute-node-1  |    6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
compute-node-1  |              at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
compute-node-1  |    7: risingwave_stream::executor::managed_state::join::JoinHashMap<K,S>::remove_state::{{closure}}
compute-node-1  |              at ./ebs/risingwave/src/stream/src/executor/managed_state/join/mod.rs:385:45
compute-node-1  |    8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
compute-node-1  |              at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
compute-node-1  |    9: risingwave_stream::executor::hash_join::HashJoinExecutor<K,S,_>::hash_eq_match::{{closure}}
compute-node-1  |              at ./ebs/risingwave/src/stream/src/executor/hash_join.rs:721:33
compute-node-1  |   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
compute-node-1  |              at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
compute-node-1  |   11: risingwave_stream::executor::hash_join::HashJoinExecutor<K,S,_>::eq_join_oneside::{{closure}}
compute-node-1  |              at ./ebs/risingwave/src/stream/src/executor/hash_join.rs:800:62
compute-node-1  |   12: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
compute-node-1  |              at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
compute-node-1  |   13: risingwave_stream::executor::hash_join::HashJoinExecutor<K,S,_>::into_stream::{{closure}}
compute-node-1  |              at ./ebs/risingwave/src/stream/src/executor/hash_join.rs:596:5

### To Reproduce

./bin/bench --type=tpch-std --qps=800000 --scale 80.0 --query 20 --partition 12 \
    $(cat ~/risingwave-deploy/tpch-bench-args-kafka) \
    $(cat ~/risingwave-deploy/tpch-bench-args-frontend) \
    --prepare-sql ./assets/data/create_materialized_source.sql

### Expected behavior

No panic.

### Additional context

Use large QPS seems make it easier to reproduce. In my case almost 100% when qps=800k.

I used commit https://github.com/risingwavelabs/risingwave/tree/wangzheng/5587. It's a874cfd7d4251d3e7545376208cad2693721f9d7 + more log. 

You can just use a874cfd7d4251d3e7545376208cad2693721f9d7 to reproduce.

[compute-0.log](https://github.com/risingwavelabs/risingwave/files/9662596/compute-0.log)
[compute-1.log](https://github.com/risingwavelabs/risingwave/files/9662597/compute-1.log)
[compute-2.log](https://github.com/risingwavelabs/risingwave/files/9662598/compute-2.log)
[meta.log](https://github.com/risingwavelabs/risingwave/files/9662599/meta.log)

risedev: compose-3node-deploy

**Comment by hzxa21** [comment]
https://github.com/risingwavelabs/risingwave/blob/9a4ac60d94c297e3036e9befae41cd9f26bc62de/src/stream/src/executor/managed_state/join/mod.rs#L394-L426

Looks like state table iterator gave back the same row twice?

**Comment by zwang28** [comment]
Encountered a vnode related panic in another run
`panicked at 'vnode 147 should not be accessed by this table', src/storage/src/table/mod.rs:152:5
`
[compute-0.log](https://github.com/risingwavelabs/risingwave/files/9662590/compute-0.log)

**Comment by BugenZhao** [comment]
I've also encountered this problem when testing scaling. Not sure whether it's the same issue.

**Comment by zwang28** [comment]
Caused by tiered cached, see https://github.com/risingwavelabs/risingwave/issues/5587#issuecomment-1263486972
