### ISSUE TITLE
refactor: concat table_id and key in state table layer and remove keyspace 

### ISSUE THREAD

**Issue by wcy-fdu** [risingwavelabs/risingwave#5610]
Now `keyspace` only works to concat `table_id` in front of key, and as we serialized key into vec<u8> before writing into `MemTable`, it's time to do this concat in relational table and remove keyspace.

**Comment by Li0k** [comment]
after `Source` intergrate with internal_table, shall we need the `t` prefix for the storage_key or only the `table_id` ?

**Comment by wcy-fdu** [comment]
I do agree the memory issue @BugenZhao mentioned, and previously, part of my motivation is to benefit the refactor of shared buffer, so that we do not need once more copy of data in `MemTable`.  After some offline discussion, the refactor of shared buffer and local state store will not ask `MemTable` to store full key, so I think compared with the increasing memory usage, there is not a strong motivation to remove `keyspace`. 

After the refactor of shared buffer is done, we can rethink whether to support "write anytime" to reduce the size of `MemTable`. cc @hzxa21 

Let's close this issue~
