### ISSUE TITLE
perf: reduced throughput after LRU manager is introduced.

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#5613]
It is already identified that there is a performance problem in #5605 

Just provide a data point of how bad the performance degradation is.

![before lru manager](https://user-images.githubusercontent.com/5791930/192722285-307dc5b4-86e3-48d3-b663-db21b4e30fd2.png)
![after lru manager](https://user-images.githubusercontent.com/5791930/192722296-7985aac6-e0ac-4055-99cf-e0cee49935a8.png)

Same query:
```
CREATE SOURCE ad_event (
    event_type VARCHAR,
    bid_id BIGINT,
    ad_id BIGINT,
    event_timestamp TIMESTAMP
) WITH (
    connector = 'kafka',
    kafka.topic = 'ad_event',
    kafka.brokers = 'localhost:9092',
    kafka.scan.startup.mode = 'earliest'
) ROW FORMAT JSON;

CREATE MATERIALIZED VIEW ad_ctr AS WITH ad_impression AS (
    SELECT
        *
    FROM
        ad_event
    WHERE
        event_type = 'impression'
),
ad_click AS (
    SELECT
        *
    FROM
        ad_event
    WHERE
        event_type = 'click'
)
SELECT
    ad_clicks.ad_id AS ad_id,
    ad_clicks.clicks_count :: NUMERIC / ad_impressions.impressions_count AS ctr
FROM
    (
        SELECT
            ad_id,
            COUNT(*) AS impressions_count
        FROM
            ad_impression
    ) AS ad_clicks ON ad_impressions.ad_id = ad_clicks.ad_id;
```

Run with one commit before the LRU Manager commit and run with the configuration being set to `enable-managed-cache: false`

cc: @yuhao-su @jon-chuang

**Comment by yuhao-su** [comment]
The hashmap in hash agg/join is wrapped by an enum now, but I'm surprised the performance can be significantly affected. 😭

**Comment by chenzl25** [comment]
BTW, this also affects sysbench point query performance.

**Comment by TennyZhuang** [comment]
We can write another stats_alloc

**Comment by TennyZhuang** [comment]
The following code snippet can get memory usage from global jemalloc.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=75ff4250d9bf6b7cf893a6cb50cad3a7

**Comment by lmatz** [comment]
![SCR-20220930-mnz](https://user-images.githubusercontent.com/5791930/193225388-7199e226-0108-456b-999e-3dd4f3530ac6.png)


It's back
