### ISSUE TITLE
Find a better way to calculate memory usage

### ISSUE THREAD

**Issue by yuhao-su** [risingwavelabs/risingwave#5615]
I think this is probably a very bad idea and potentially the source of contention. We may want to find a cheaper thread-local way collecting allocation stats than rely on a global atomic var.

_Originally posted by @jon-chuang in https://github.com/risingwavelabs/risingwave/pull/5395#discussion_r982079808_

**Comment by lmatz** [comment]
Is it considered done now?

**Comment by yuhao-su** [comment]
> Is it considered done now?

No but coming soon.
