### ISSUE TITLE
Bug(stream): `StreamingApproxCountDistinct` should persistent buckets

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#5616]
`StreamingApproxCountDistinct` use the `HyperLogLog` algorithm. In current implementation, its state is just the result and not persistent each value of bucket. so when failover or migration happens, the result might be wrong.

**Comment by chenzl25** [comment]
It seems there is an existing issue here. #3414

**Comment by soundOfDestiny** [comment]
In HashAgg and GlobalSimpleAgg:
- The state of updatable case is too large.
- Append-only case is resolved in #5976 
In 2-phase Agg:
- Updatable case introduces an extra shuffle and still needs large state (though much smaller than that in HashAgg). https://github.com/risingwavelabs/rfcs/pull/7
- If we do not shuffle, we will have too large change row, so append-only case can't be resolved, either. https://github.com/risingwavelabs/rfcs/pull/7
