### ISSUE TITLE
ci: speed-up the e2e tests with barrier/checkpoint decoupling

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#5617]
We need to ensure the barrier that finishes a mview creation is a checkpoint, but we cannot know it ahead of time. So we enforce it by forcing the next barrier to be a checkpoint when the progress is ready to be finished and defer the reporting to the next barrier.

> So creating an empty materialized view will last for 2 barrier intervals in most cases? 🤣 This may make the e2e tests much slower in CI. How about decreasing the barrier interval?

_Originally posted by @BugenZhao in https://github.com/risingwavelabs/risingwave/pull/4966#discussion_r977215729_

[streaming-ci-release e2e_test_streaming_tpch_snapshot_slt](https://buildkite.com/organizations/risingwavelabs/analytics/suites/sqllogictest/tests/124683930?branch=main)
<img width="382" alt="image" src="https://user-images.githubusercontent.com/25862682/192730864-f379dfd2-0741-40af-983b-efef3f69e50e.png">

Any ideas? 🥺 @xxhZs @hzxa21 @fuyufjh

**Comment by xxhZs** [comment]
We can reduce the time by increasing the `barrier_interval_ms`. barrier_interval_ms 250ms -> 350ms, e2e parallel 10min - 8min30s

**Comment by BugenZhao** [comment]
> barrier_interval_ms 250ms -> 350ms, e2e parallel 10min - 8min30s

This is interesting 🤔. But I believe the time usage of sequential e2e and all e2es under release profile should increase.

**Comment by xxhZs** [comment]
> > barrier_interval_ms 250ms -> 350ms, e2e parallel 10min - 8min30s
> 
> This is interesting 🤔. But I believe the time usage of sequential e2e and all e2es under release profile should increase.

yes, I think this means that the reason for the timeout is not the mv waiting for a barrier. And I run parallel test alone on ec2. It is so quick.

**Comment by BugenZhao** [comment]
#6196 speeded it up a lot. I think we can defer this issue for now. 🤤
