### ISSUE TITLE
Support version queries

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#5619]
Many third party clients use the server version to workaround incompatibility issues, so this may be a first blocker to support these clients. https://github.com/risingwavelabs/risingwave/pull/2636 has some previous dicsussions about this issue.

There are different ways to get version
- version in pg wire protocol (see discussion in #2636
- parameters `SHOW server_version`, `SHOW server_version_num`.
- `SELECT pg_catalog.version()`.

One problem is that clients might parse the numeric version from the version string, e.g., sqlalchemy's logic is:

https://github.com/sqlalchemy/sqlalchemy/blob/e708cfea0b/lib/sqlalchemy/dialects/postgresql/base.py#L3066-L3077

```python
    def _get_server_version_info(self, connection):
        v = connection.exec_driver_sql("select pg_catalog.version()").scalar()
        m = re.match(
            r".*(?:PostgreSQL|EnterpriseDB) "
            r"(\d+)\.?(\d+)?(?:\.(\d+))?(?:\.\d+)?(?:devel|beta)?",
            v,
        )
        if not m:
            raise AssertionError(
                "Could not determine version from string '%s'" % v
            )
        return tuple([int(x) for x in m.group(1, 2, 3) if x is not None])
```

test examples: 

https://github.com/sqlalchemy/sqlalchemy/blob/e708cfea0bdaae82ac30dd7d33f9442115b9af6d/test/dialect/postgresql/test_dialect.py#L96-L135

**Comment by BowenXiao1999** [comment]
https://github.com/risingwavelabs/risingwave/pull/2636#issuecomment-1363561572

**Comment by xxchan** [comment]
https://github.com/risingwavelabs/risingwave/pull/7314 added 👀
```
SELECT version();
----
PostgreSQL 13.9-RW-0.2.0-alpha
```

**Comment by BowenXiao1999** [comment]
> 👀 #7314 added
> 
> ```
> SELECT version();
> ----
> PostgreSQL 13.9-RW-0.2.0-alpha
> ```

cc @mikechesterwang
