### ISSUE TITLE
frontend: support concrete stream type rather than using BoxStream

### ISSUE THREAD

**Issue by ZENOTME** [risingwavelabs/risingwave#5624]
### Is your feature request related to a problem? Please describe.

as discuss in #5556 
We use BoxStream to transfer data now. But Boxstream will impact the performance because it's a dynamic bind. Boxstream is Box, it's a dynamic bind. So I guess every time we call 'stream.next()' to get a row, it needs to call by some mechanism like vtable. Hence if there are millions of rows in the result set, we may need to access vtable millions of times.

### Describe the solution you'd like

``The solution is to implement the concrete type which implements stream trait, such as:
```
struct LocalQueryStream {
 ...
}
impl Stream for LocalQueryStream{
  fn poll_next(){
   ...
  }
}
```
so that we can use the concrete result type instead of BoxStream to prevent dynamic binding. 
```
// original version
struct PgResponse{
  ...
  result: BoxStream<>
}

// new version 
struct PgResponse{
  result: LocalQueryStream
}
```

**Comment by Gun9niR** [comment]
Should we use enum dispatch for different concrete stream types?

**Comment by ZENOTME** [comment]
Yes, Because we have different stream: LocalQueryStream and DistributeQueryStream.

**Comment by Gun9niR** [comment]
I wonder how many generic params you have used in your previous attempt. I imagine they will appear in fn signatures containing `QueryResultSet`/`PgResultSet`, and `PgResponse`?
