### ISSUE TITLE
feat(state_store): optimize the number of merged iterator in shared-buffer

### ISSUE THREAD

**Issue by Little-Wallace** [risingwavelabs/risingwave#5634]
### Is your feature request related to a problem? Please describe.

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/16376959/192950787-2bf1c048-c6c9-4ae4-9102-578d240ee88d.png">
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/16376959/192950809-ec081f6f-2ec7-4d07-9fee-e150f69fe5d9.png">

When scan some data for one table, we need to merged iterators come from both sstable and shared-buffer. But there seems to be more than 60% of iterators comes from shared-buffer and sync-uncommitted-data. 

### Describe the solution you'd like

I guess that it is because we store too much epoch in shared-buffer. I would investigate it later.

**Comment by fuyufjh** [comment]
Any updates?

**Comment by StrikeW** [comment]
I have finished an [initial benchmark](https://www.notion.so/risingwave-labs/01-18-b7f1f4f5eb9b45c4b7575b6db2c134ab#1964ae41300847deb10314a3a8f8917d) of the optimization but the [PR](https://github.com/risingwavelabs/risingwave/pull/7368) has some unresolved problems. I will continue refining the PR and expect to finish it in next month.
