### ISSUE TITLE
Version: remote version observer and version delta propagation to LocalStateStore

### ISSUE THREAD

**Issue by Li0k** [risingwavelabs/risingwave#5665]
### Background
Now we update the `LocalVersion` of StateStore through `try_update_pinned_version` with `ObserverManager`, corresponds to the following two situations

1. HummockVersionDeltas (handle_notification)
2. PinnedVersion (handle_initialization_notification)

After notification, `ObserverManager` call the `try_update_pinned_version` via `LocalVersionManager `.
Note in particular that now initializing the first Version also relies on Notification to get from Meta

### Motivation
1. Currently `ObserverManager` directly depends on `LocalVersionManager`， and `VersionUpdate` via `LocalVersionManager`, we decided to remove this dependency and only interact through `Event`
2. EventHandler support `VersionUpdate` event to handle `HummockVersionDeltas` and `PinnedVersion`
3. remove the `LocalVersionManager` and `ReadVersion` dependency  of new StateStoreCore, and only interact through `Event`

**Comment by hzxa21** [comment]
Is this done?
