### ISSUE TITLE
feat(expr): higher precision of interval

### ISSUE THREAD

**Issue by ZENOTME** [risingwavelabs/risingwave#5675]
### Is your feature request related to a problem? Please describe.

```
pub struct IntervalUnit {
    months: i32,
    days: i32,
    ms: i64,
}
```
IntervalUnit only has the precision of milliseconds.
If we encounter an interval with seconds smaller than milliseconds, such as 
select '0:0:0.00001'::INTERVAL; 
Something wrong will happen.

After #5674, we will return the error if encounter the case described above.

But we may need to think about getting higher precision of interval.

**Comment by xiangjinwu** [comment]
#4514
