### ISSUE TITLE
Distinguish system config variables and cli options

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#5676]
Currently we have 2 kinds of configurations:
- *Config*: `src/common/src/config.rs` (configured by `risingwave.toml`)
- *Options*: `XxNodeOpts` (`clap` cli options, can be configured by `risedev.yml`). They usually also contain `config_path` option which is the path for `risingwave.toml`.

Intuitively, *Options* should contain basic user-facing options, e.g., addr & host and maybe some feature gates, while *Config* contains deep-dark internal system variables to fine-tune the  system performance. 

But currently the distinction is not very clear and made me confused. Specifically, *Options* contains some system variables, e.g., `vacuum_interval_sec`, `min_sst_retention_time_sec` in `MetaNodeOpts`. So I propose to put all of such variables into `Config` to avoid possible confusion both when developers want to add configurations and when users want to set configurations.

One outstanding problem is that currently `risedev.yml` do set some different system variables e.g., `min-sst-retention-time-sec` for different scenes. We'd need to either 1. support generate `risingwave.toml` in risedev, or 2. specify different `config_path` for different scenes in `risedev.yml`.

**Comment by lmatz** [comment]
Feeling (1) is better (the generated `risingwave.toml` replaces `src/config/risingwave.toml` I suppose?).

No matter what users want to do,
they just need to check this single place for truth.

**Comment by fuyufjh** [comment]
Strong +1. 

> `vacuum_interval_sec`, `min_sst_retention_time_sec` in `MetaNodeOpts`

These are really bad ideas and I am afraid they may lead to more and more deep-dive variables shown in Opts. 

Either 1 or 2 looks good to me, but 2 seems easier.

**Comment by xxchan** [comment]
I'm implementing (2). Finishing soon.
