### ISSUE TITLE
dev: collect all tracing *_max_level_* features into a separate feature

### ISSUE THREAD

**Issue by MrCroxx** [risingwavelabs/risingwave#5721]
### Background

Currently, risingwave enables `release_max_level_info` in crate `cmd` and `cmd_all`. Because we are using *hakari* for workspace hack, all crates depending on `workspace-hack.toml` will be infected. But crates like `bench` may need to use `release_max_level_trace` to enable `TRACE` level log of some interested targets.

### Design

Collect all `*_max_level_*` tracing features into a separate feature, and only enable it when building productional targets.

**Comment by MrCroxx** [comment]
@BugenZhao @skyzh @wangrunji0408 Any ideas?

**Comment by skyzh** [comment]
You can ignore risingwave_cmd_all for hakari.

**Comment by MrCroxx** [comment]
> You can ignore risingwave_cmd_all for hakari.

I'm afraid that may cause recompiling between unit tests and e2e tests, which is not friendly to developers.

**Comment by skyzh** [comment]
Also if something is really important in benches, set it to info level and filter by event name.

**Comment by MrCroxx** [comment]
> Also if something is really important in benches, set it to info level and filter by event name.

The thing is some events are in *storage* crate. 🤣

BTW, I tried to separate the features, but hakari still counts our self-defined features in the workspace-hack.

I'll try another way (e.g. let hakari exclude the features) first.

**Comment by MrCroxx** [comment]
@BugenZhao @skyzh I imitate `static-link` and write a PR #5725 . Will it help?
