### ISSUE TITLE
cannot build `rdkakfa-sys` with M1 Mac according to developer guide

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#5739]
We've added the support for ssl/sasl in #5693 and I found not able to build `rdkafka` with M1 Mac according to the developer guide. After some attempts, here's a possible solution:

- `brew install openssl@3`.
- No need to `brew install cyrus-sasl`.
- Before building, `export OPENSSL_ROOT_DIR="/opt/homebrew/opt/openssl@3"`.

Any ideas? cc @xx01cyx @skyzh @tabVersion 

Related: https://github.com/fede1024/rust-rdkafka/issues/491

**Comment by yuhao-su** [comment]
`brew link --force openssl` works for me

**Comment by tabVersion** [comment]
> `brew link --force openssl` works for me

agreed. I followed 2nd solution and fixed it https://stackoverflow.com/questions/29792009/cmake-osx-mac-openssl-brew

**Comment by BugenZhao** [comment]
`openssl@3` is a keg-only formulae, I'm afraid force-link it may break some other applications. 🤔

```
openssl@3 is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS provides LibreSSL.
```

**Comment by BowenXiao1999** [comment]
For me 
1. `brew link --force openssl`
2. export OPENSSL_INCLUDE_DIR=/path/to/openssl/include

**Comment by skyzh** [comment]
I don't think force-link is a good idea. What about changing to static link for all platforms? 🤣 We came back to the old path.

**Comment by skyzh** [comment]
... hopefully it won't hurt compile time too much, and won't burst target directory size. Considering we already have so many crates?

**Comment by skyzh** [comment]
... or make rdkafka's SSL an optional feature for dev profile?

**Comment by BugenZhao** [comment]
Or how about forking the `rdkafka-sys` to edit the cmake configuration until the upstream fixes that? 🤣 Note that we're already using the patch `madsim-kafka`.

**Comment by skyzh** [comment]
Looks good.

**Comment by skyzh** [comment]
Wait a minute. If we enable `dynamic-linking` feature of rdkafka, then users only need to install librdkafka?

**Comment by skyzh** [comment]
Doesn't work. Need some adjustments on openssl.

**Comment by tabVersion** [comment]
> I don't think force-link is a good idea. What about changing to static link for all platforms? 🤣 We came back to the old path.

I have the openssl in my PATH but cmake still cannot find the dep

**Comment by xxchan** [comment]
In case someone might need it, you can add them to `.vscode/settings.json` 🥸:
```
    "terminal.integrated.env.osx": {
        "OPENSSL_ROOT_DIR": "/opt/homebrew/opt/openssl@3"
    },
    "rust-analyzer.cargo.extraEnv": {
        "OPENSSL_ROOT_DIR": "/opt/homebrew/opt/openssl@3"
    },
```
