### ISSUE TITLE
BatchTaskMetrics uses unbounded memory

### ISSUE THREAD

**Issue by Gun9niR** [risingwavelabs/risingwave#5743]
### Is your feature request related to a problem? Please describe.

In #3832 and #4844, we have introduced task level metrics. To remove the metrics of a finished task, we create some new `Collector` for each new task, and `unregister` them when the task finishes. However, `prometheus::Registry::unregister` does not remove the data completely from the register - the `fq_name` (composed of the `Collector`'s help message and labels) remains in the registry.

https://github.com/tikv/rust-prometheus/blob/fc591fdee0ffc75cd26d8a7f82f8e2c4c66bb1ff/src/registry.rs#L93-L117

When the number of tasks is large, the `Collectors` can consume a lot of memory. (#5724) 

### Describe the solution you'd like

All the tasks should share the same `Collector`s, and distinguish themselves with variables label values. To avoid accumulating data from consuming too much memory, stale metrics should be cleaned by calling `remove_label_values` or `reset` on the `Collector`'s that has been set by a finished task. More specifically, we should clear all the metrics once they are collected.

### Describe alternatives you've considered

We might also maintain the metrics and labels modified by each task. However, there are several difficulties. 

- We do not know how many times a metric is modified.
- We do not know whether they are modified with the same label values. 
- The metrics may be of different types, so it's hard to maintain an `id -> metric` mapping. 

To achieve the deduplication of label values and the compatibility of different metric types, the implementation would be very complex.

**Comment by BugenZhao** [comment]
Will streaming actors encounter a similar problem? 🤔

**Comment by Gun9niR** [comment]
> Will streaming actors encounter a similar problem? 🤔

Seems not.

**Comment by liurenjie1024** [comment]
After checking the pr in #5770, I think the implementation is incorrect: if the batch task runs longer than metrics collection period, the metrics collected is incorrect.

> However, prometheus::Registry::unregister does not remove the data completely from the register - the fq_name (composed of the Collector's help message and labels) remains in the registry.

> https://github.com/tikv/rust-prometheus/blob/fc591fdee0ffc75cd26d8a7f82f8e2c4c66bb1ff/src/registry.rs#L93-L117

After unregistering a collector, prometheus will only it's fq_name, but the const labels and help messages are all removed, e.g. they are not part of desc id.

> When the number of tasks is large, the Collectors can consume a lot of memory.(https://github.com/risingwavelabs/risingwave/issues/5724)

This is correct, but we have implemented a way to disable collecting metrics in local mode tasks(high qps small tasks), which is assumed to consume much less memory.

**Comment by liurenjie1024** [comment]
cc @Gun9niR @ZENOTME

**Comment by Gun9niR** [comment]
If the metrics are written and cleaned between two `collect` calls, will they be lost?

**Comment by liurenjie1024** [comment]
> If the metrics are written and cleaned between two `collect` calls, will they be lost?

Yes, it's possible. A possible solution is to store the metrics and clean them until they are collected. We can have some marks for finished task labels.

**Comment by ZENOTME** [comment]
> A possible solution is to store the metrics and clean them until they are collected. We can have some marks for finished task labels.

To clean the related metrics when task ended, here is a more detail solution:  

For task level metrics,
1. when cancel the task, record ended TaskId in task metrics.
2. when task metrics collected, it will delete value according ended TaskId.
https://github.com/tikv/rust-prometheus/blob/36acf4753da7f188567ef2b735c53facc3d5798a/src/vec.rs#L73

For executor level metrics 
1. when create the executor, record (TaskId,executor identifier) in executor metrics 
2. when cancel the task, mark (TaskId,executor identifier) in executor metrics as ended.
3. when executor metrics collected, it will delete value according ended (TaskId,executor identifier).

（In this solution, comapre to current implementation, we should introduce a data struct using RwLock in metrics to record the ended task info. But seems it's inevitable.
