### ISSUE TITLE
Refactor hummock snapshot in frontend with RAII style

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#5754]
BTW, how about refactoring the snapshot ref count with `Arc` in the frontend (as what we do with `PinnedVersion` in compute node)?

_Originally posted by @BugenZhao in https://github.com/risingwavelabs/risingwave/issues/5711#issuecomment-1272525490_

**Comment by Gun9niR** [comment]
IIUC, the point is not the `Arc`, but the guard to make sure the snapshot is released.
