### ISSUE TITLE
bug(recovery): query result mismatch due to recovery of mview that did not finish creating

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#5755]
https://buildkite.com/risingwavelabs/pull-request/builds/9902#0183c136-80e2-4650-bde3-b32e34c86ad1

**Comment by wangrunji0408** [comment]
in-mem store in deterministic testing

**Comment by BugenZhao** [comment]
Is this related to #4709?

**Comment by yezizp2012** [comment]
> Is this related to #4709?

I guess not, will investigate it.
