### ISSUE TITLE
chore(ci): to seperate the exit status code for easier debug

### ISSUE THREAD

**Issue by Li0k** [risingwavelabs/risingwave#5769]
### Is your feature request related to a problem? Please describe.

<img width="313" alt="image" src="https://user-images.githubusercontent.com/15023748/194992288-3af3b43e-262f-4e91-b5cb-e64dfb41333c.png">

System has the same exit status code in different shell, and it is difficult to intuitively find the problem when it fails to exit. Like the issue (https://github.com/risingwavelabs/risingwave/issues/5753), we can't find out that the log size exceeds the limit at the first time.

### Describe the solution you'd like

to seperate the exit status code for the different errors

**Comment by skyzh** [comment]
What about set -x?

**Comment by skyzh** [comment]
I remembered that for log size issues, the warning is in bright yellow color…

**Comment by skyzh** [comment]
mark as won't fix for now, may reopen when someone has the need to fix it :) Or maybe https://github.com/risingwavelabs/risingwave/issues/6278 can be the remedy.
