### ISSUE TITLE
bug: dynamic filter yield wrong results if data comes first on the outer side

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#5771]
First, comment out this line (a known issue with `UpstreamHashShard` fragment and to be fixed soon).

https://github.com/risingwavelabs/risingwave/blob/9feb9b21e66ab2b0da875037246eb107ec9d3807/src/meta/src/stream/stream_manager.rs#L327

Then, run SQLs:

```sql
create table t1 (v1 int);
create table t2 (v2 int);
create materialized view mv as with tt2 as (select sum(v2) vv2 from t2) select v1 from t1, tt2 where v1 > vv2;

insert into t2 values (0);
flush;

insert into t1 values (233);
flush;

select * from mv;
==> 
 v1  
-----
 233
(1 row)
```

However, if we switch the order of `Insert`s, we'll get the wrong result.
```sql
create table t1 (v1 int);
create table t2 (v2 int);
create materialized view mv as with tt2 as (select sum(v2) vv2 from t2) select v1 from t1, tt2 where v1 > vv2;

insert into t1 values (233);
flush;

insert into t2 values (0);
flush;

select * from mv;
==> 
 v1 
----
(0 rows)
```

cc @jon-chuang Could you please help to take a look?

**Comment by jon-chuang** [comment]
Seems like an issue with handling the NULL case.

**Comment by jon-chuang** [comment]
To be clear, this does not happen without use of CTL?

**Comment by jon-chuang** [comment]
Seems a unit test corresponding to the same flow of events behaves as expected. This suggests that the behaviour of the executor in unit test is different than in e2e test...

**Comment by jon-chuang** [comment]
Turns out the actual issue is due to `#[derive(PartialEq)]` on `ScalarImpl`. Its actually quite a bad thing to have as there should not be any meaningful notion of PartialEq on ScalarImpl
