### ISSUE TITLE
fix:  improve the process of detecting duplicate relation names

### ISSUE THREAD

**Issue by HuaHuaY** [risingwavelabs/risingwave#5783]
Now there is a function `check_relation_name_duplicated` in frontend, which is used to detecting duplicate sources' and tables' names. It misses the process of detecting duplication of sinks' and tables' (not mvs') names. (When creating index, it will use the index table to detect this.)
And meta doesn't have the process. We should add it to meta to avoid conflicts between multiple frontends.

**Comment by Gun9niR** [comment]
Aren't the non-mv tables checked along with the sources?

**Comment by Gun9niR** [comment]
It seems for relation creation, meta node will return after all the frontend nodes are notified of the catalog change. So checking duplication might not be needed? cc. @yezizp2012

**Comment by yezizp2012** [comment]
> It seems for relation creation, meta node will return after all the frontend nodes are notified of the catalog change. So checking duplication might not be needed? cc. @yezizp2012

The duplication check mentioned here is to check name duplication among all relations. We already had this logic in frontend but lack of `Sink` and `Table`. For multi-frontend environment, this check is also needed in meta, which we don't have yet. Meta only have name duplicate check for same type of relation.

**Comment by HuaHuaY** [comment]
> It seems for relation creation, meta node will return after all the frontend nodes are notified of the catalog change. So checking duplication on meta node might not be needed? cc. @yezizp2012

Suppose one frontend sends a create source RPC. If another frontend sends a create mv RPC with the same relation name before it receives meta's notification, meta without duplicate name check will allow two create RPC request and create two relation with the same name.
