### ISSUE TITLE
bug(batch): cyclic reference in QueryRunner causes dangling tokio tasks

### ISSUE THREAD

**Issue by Gun9niR** [risingwavelabs/risingwave#5816]
### Describe the bug

When a `QueryRunner` is created, a `msg_receiver` is passed in to notify `QueryRunner` that all stages have been scheduled when it runs. However, the `msg_sender`s owned by `StageExecution`s (which are owned by `QueryRunner`) are never dropped, causing a cyclic reference.

```
QueryRunner::run (poll the receiver) -> StageExecution (contains the senders)
                            ⬆️                                      ⬇️ 
                            -----------------------------------------
```

We were not able to identify the bug until now, because the join handle of the task spawned to call `QueryRunner::run` is ignored. So even if the query finishes, there will be a tokio task dangling around.

https://github.com/risingwavelabs/risingwave/blob/6364145c5aae2b73d9277055ab06026906c23a4f/src/frontend/src/scheduler/distributed/query.rs#L172-L184

### Possible Solution 

- In `StageExecution`, drop the `msg_sender` when needed so that the cycle can be broken.
- Also, we need to join all the tasks that have been spawned.

### To Reproduce

Run the snippet in #5724 

### Expected behavior

All the tasks related to a query should be joined when it finishes.

### Additional context

This is one of the causes of #5724

**Comment by BugenZhao** [comment]
IIUC, even if every stage finishes, we still hold a copy of `msg_sender` in each `StageExecution`.

So we may align the lifetime of the sender to the stage execution itself by putting it into `StageState::Pending { <here> }` or use a `Option<Mutex<Sender>>` here?

https://github.com/risingwavelabs/risingwave/blob/c010fe662a0370218eacca535b747d9fece9a136/src/frontend/src/scheduler/distributed/stage.rs#L183-L193

**Comment by Gun9niR** [comment]
> IIUC, even if every stage finishes, we still hold a copy of msg_sender in each StageExecution.

Yes. But `StageExecution` does not use the sender directly. Instead, it is passed to the `StageRunner`, where the actual sending happens.

> So we may align the lifetime of the sender to the stage execution itself 

`StageExecution`s are owned by `QueryRunner`, so the sender's lifetime should be shorter than  `StageExecution` to break the loop. I think the stage runner should close the sender when it no longer needs it.

**Comment by xx01cyx** [comment]
> putting it into `StageState::Pending { <here> }`

There are actually `StageExecution` cloned elsewhere (e.g. `StageExecution.children`), so putting the sender into `StageState::Pending` here won't fix the problem.

> use a `Option<Mutex<Sender>>`

IIUC, some extra work will be required to `mem::take` the sender out of the `Option`. This requires `&self` to be changed to `&mut self`, which might be a bit complicated to implement (since we have to change a lot of code and struct fields to enable `&mut self`).

I (seem to) fix the problem by sending a new type of message to inform `QueryRunner` that all the stages have been scheduled, so that it could break the loop and thus drop `StageExecution`. I will submit a PR to verify it.

**Comment by xx01cyx** [comment]
> BTW, will any message arrive after root stage is scheduled? If not, we can use root stage as this message.

Seems not. Maybe we could ask Bowen to confirm this. Besides, we can not use root stage as this message, because the sender will be taken after the root message is sent to `QueryRunner`, so we must wait until it's taken and then break the loop.

**Comment by xx01cyx** [comment]
> But it is under `Arc` so there will be just one state for each stage?

Let me correct myself. This is indeed true, but we have to:
- either **make** the receiver jump out of the loop   
- or **drop all the senders beforehand** so that the receiver could jump out of the loop by itself

Maybe 
> putting it into `StageState::Pending { <here> }`

is a solution. I just haven't found out a way to put the sender into `StageRunner` and meantime satisfy at least one of the two conditions 🥺

**Comment by Gun9niR** [comment]
> I just haven't found out a way to put the sender into StageRunner and meantime satisfy at least one of the two conditions 🥺

https://github.com/risingwavelabs/risingwave/blob/b5f84f32e0f20b59f161bef803bbb1a4dfd51b8a/src/frontend/src/scheduler/distributed/stage.rs#L272-L285

Maybe just close the sender at the end of run?

**Comment by BowenXiao1999** [comment]
> This is also a solution. BTW, will any message arrive after root stage is scheduled? If not, we can use root stage as this message. cc @BowenXiao1999

No.

**Comment by BowenXiao1999** [comment]
> This is also a solution. BTW, will any message arrive after root stage is scheduled? If not, we can use root stage as this message. cc @BowenXiao1999

IIUC, There is already a ScheduledRoot (All fragment except root are scheduled, so no we can start root fragment task (in FE locally)) in QueryRunner. Even after we schedule all stages, the QueryRunner is not dropped: cuz there may be execution failure happen and QueryRunner needs to react to this and inform all StageExecution.

**Comment by xx01cyx** [comment]
> We need to join all the tasks that have been spawned.

This seems difficult to implement, cuz rust currently does not support `async Drop`, so we cannot join the tasks in `drop`. Besides, pgwire shouldn't be aware of the joining as well. Maybe we have to find somewhere else to join the tasks (or wait until rust supporting `async Drop`).
