### ISSUE TITLE
Error information improvement needed when creating mv w/ `limit` w/o `order by`

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#5824]
### Describe the bug

When creating a materialized view, if users need to use `limit`, they have to add `order by` before the `limit`. But the error information will not clear they are a must combo.

### To Reproduce

```
dev=> create materialized view mv as select * from t limit 1;
ERROR:  QueryError: Feature is not yet implemented: there is no limit stream operator
No tracking issue yet. Feel free to submit a feature request at https://github.com/risingwavelabs/risingwave/issues/new?labels=type%2Ffeature&template=feature_request.yml
```

### Expected behavior

Error information should be like "Must place `order by` before `limit`".

**Comment by st1page** [comment]
I am not sure what should we do here now. If a user writes a streaming SQL with 'limit', should we reject that query and hint that he has to add an `order by` before the `limit`, or give it implicit order `PK`? :thinking: @TennyZhuang
