### ISSUE TITLE
bug: risedev build in release mode compile error

### ISSUE THREAD

**Issue by MrCroxx** [risingwavelabs/risingwave#5829]
### Describe the bug

#5725 refactored feature `static-link` and `static-log-level`, then add a compile error if *risingwave_cmd* or *risingwave_cmd_all* is not compiled with these two features. But `./risedev d` in release mode won't enable these features and will raise a compile error.

### Expected behavior

As https://github.com/risingwavelabs/risingwave/pull/5725#issuecomment-1275533694 said, debug logs are too verbose in release mode even when developing. So `static-log-level` is needed but `static-link` isn't.

So, in total,

release when developing: `static-log-level`,

release for AWS: `static-link` + `static-log-level`.

**Comment by MrCroxx** [comment]
Should we turn off `compile_error!` or add a new feature to skip the check that only enabled when building with `risedev`? 🥲

**Comment by skyzh** [comment]
Users should install all required packages when compiling in release mode. Everything is expected to be statically-linked.

**Comment by skyzh** [comment]
I'd prefer using static-link for all release builds 🤣

**Comment by MrCroxx** [comment]
> Users should install all required packages when compiling in release mode?

Not sure of his scenario. Cloud you please describe your needs and could you statically link the needed lib? @StrikeW  🤔

**Comment by skyzh** [comment]
Or let's turn off compile_error. I feel it's okay to do so.

**Comment by MrCroxx** [comment]
> I don't understand. Release build shouldn't have such kinds of verbose log, don't you think so? I didn't add new lib yet.

I agree with that. I'm talking about if `static-link` should be enabled in release mode for developing.

**Comment by hzxa21** [comment]
Any updates? @MrCroxx

**Comment by BugenZhao** [comment]
This should be fixed already.
