### ISSUE TITLE
Tracking(approx_count_distinct): append-only approx_count_distinct

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#5871]
in discussion in #3414, we found the current design of detectable approx_count_distinct is too expensive to persist the state
- add an append-only approx_count_distinct aggregator with memory state
- design the schema of the append-only approx_count_distinct's state table
- implement different agg state type other than `ValueState` and `MaterializedInputState`
- Notice, all things above are just singleton for simple agg. So we need Investigate and explore the 2-phase agg of append-only approx_count_distinct

**Comment by jon-chuang** [comment]
> is too expensive to persist the state

I'm not sure I would agree with this. Its expensive in a group by with many groups. But it may be suitable to small groups or simple agg.

**Comment by jon-chuang** [comment]
> investigate and explore the 2-phase agg of append-only approx_count_distinct

Sounds like the approach here is to also maintain a hash table per vnode. One can do local agg in terms of in-memory state sharing the same hash buckets, then forward only differentials to the global agg.

**Comment by st1page** [comment]
> One can do local agg in terms of in-memory state sharing the same hash buckets, then forward only differentials to the global agg.

Yes, but we need more detailed design here.

**Comment by soundOfDestiny** [comment]
> * add an append-only approx_count_distinct aggregator with memory state
#5958 
> * design the schema of the append-only approx_count_distinct's state table
#5976 The state is all the buckets in HLL.
> * implement different agg state type other than `ValueState` and `MaterializedInputState`
#5976 The new state type is named `TableState`.
> * Notice, all things above are just singleton for simple agg. So we need Investigate and explore the 2-phase agg of append-only approx_count_distinct
https://github.com/risingwavelabs/rfcs/pull/7
The change row will be too large.
