### ISSUE TITLE
refactor(types): Do not derive e.g. `Ord` on `ScalarImpl`

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#5872]
Turns out the actual issue is due to `#[derive(PartialEq)]` on `ScalarImpl`. Its actually quite a bad thing to have as there should not be any meaningful notion of PartialEq on ScalarImpl. 

_Originally posted by @jon-chuang in https://github.com/risingwavelabs/risingwave/issues/5771#issuecomment-1280284092_
      

e.g. Int64(_) > Int32(_) is always true due to enum position rather than our actual comparison. 

This doesn't seem like behaviour we would want.

If we want, we can define manually semantically correct PartialEq on ScalarImpl that agrees with our expression framework.

**Comment by BugenZhao** [comment]
Agree. I guess what you mean is not to derive `Ord`. https://github.com/risingwavelabs/risingwave/issues/4272#issuecomment-1200355690

 BTW, could we borrow the idea of `PartialOrd` to return `None` when comparing different scalar types?

**Comment by jon-chuang** [comment]
Indeed. Not sure if it would be useful, but that seems the most broad statement that is still correct.
