### ISSUE TITLE
bug: deterministic test hang up when use ssl connection

### ISSUE THREAD

**Issue by BowenXiao1999** [risingwavelabs/risingwave#5874]
### Describe the bug

Use ssl config instead of NoTls in simulation test. However, the `./risedev sslt` will forever hang up. To find the root cause, I wrote a test use the same config to connect. 

### To Reproduce

test function:
run ./risedev p and run this function manually, the connection will be set up (print successfully in pg_protocol::ssl).
```rust
mod tests {
    use std::time::Duration;
    use openssl::ssl::{SslConnector, SslMethod};
    use postgres_openssl::MakeTlsConnector;
    use tokio_postgres::config::SslMode;

    #[tokio::test]
    async fn test_connect() {
        let host = "127.0.0.1";
        let dbname = "dev";
        // Replace this path to be the path in yours.
        let cert_path = "/Users/bowen/risingwave-dev/src/utils/pgwire/tests/ssl/demo.crt";
        let key_path = "/Users/bowen/risingwave-dev/src/utils/pgwire/tests/ssl/demo.crt";
        let mut builder = SslConnector::builder(SslMethod::tls()).unwrap();
        builder.set_verify_callback(openssl::ssl::SslVerifyMode::PEER, |_, _| true);
        builder.set_certificate_chain_file(cert_path).unwrap();
        let mut connector = MakeTlsConnector::new(builder.build());
        let (client, connection) = tokio_postgres::Config::new()
            .host(&host)
            .port(4566)
            .dbname(&dbname)
            .user("root")
            .connect_timeout(Duration::from_secs(5))
            .ssl_mode(SslMode::Require)
            .connect(connector)
            .await
            .expect("Failed to connect to database");
        println!("Make already connector done");
        if let Err(e) = connection.await {
            println!("postgres connection error: {e}");
        }
    }
}
```

However, run ./risedev sslt -- './e2e_test/batch/basic.slt.part' will hang up:
```rust
impl Risingwave {
    async fn connect(host: String, dbname: String) -> Result<Self, tokio_postgres::error::Error> {

        let mut builder = SslConnector::builder(SslMethod::tls()).unwrap();
        // Replace this path to be the path in yours.
        let cert_path = "/Users/bowen/risingwave-dev/src/utils/pgwire/tests/ssl/demo.crt";
        let key_path = "/Users/bowen/risingwave-dev/src/utils/pgwire/tests/ssl/demo.crt";
        builder.set_verify_callback(openssl::ssl::SslVerifyMode::PEER, |_, _| true);
        builder.set_certificate_chain_file(cert_path).unwrap();
        let mut connector = MakeTlsConnector::new(builder.build());
        let (client, connection) = tokio_postgres::Config::new()
            .host(&host)
            .port(4566)
            .dbname(&dbname)
            .user("root")
            .connect_timeout(Duration::from_secs(5))
            .ssl_mode(SslMode::Require)
            .connect(connector)
            .await
            .expect("Failed to connect to database");

        let task = tokio::spawn(async move {
            if let Err(e) = connection.await {
                tracing::error!("postgres connection error: {e}");
            }
        });
        Ok(Risingwave {
            client,
            task,
            host,
            dbname,
        })
    }
}
```

### Expected behavior

both work smoothly. If you add a println in pg_protocol::ssl, the test function will print however the simulation one dont. But they are the same in config so expected to behave the same. 

### Additional context

#5775

**Comment by BowenXiao1999** [comment]
cc @wangrunji0408 take some time for looking at this? Thanks!

**Comment by wangrunji0408** [comment]
I found the reason is that when SSL is enabled, the code turns into the OpenSSL library which has not been mocked in the simulation. Then the execution will get stacked because OpenSSL can't find a destination in the real world.

I can think of 3 possible ways to fix this problem:
1. Simulate SSL: We build a full-featured mock of OpenSSL. This allows us to test the correctness of SSL-related code in the simulation, but it takes time to do that.
2. Ignore SSL: We modify the code of tokio-postgres by simply ignoring any SSL configurations. This allows us to run the simulation test without any code modification at a small cost, but in contrast, SSL won't be covered in the test.
3. Forbid SSL: We declare that SSL will not be supported in the simulation and developers should avoid using SSL in the simulation test.

Given that SSL is not the main feature that simulation test targeted, I prefer solution 2 or 3. Any other ideas? 👀

**Comment by BowenXiao1999** [comment]
Both 2 or 3 LGTM 😄 . 3 looks semanticlly clearer.

**Comment by BowenXiao1999** [comment]
Closed as won't fixed
