### ISSUE TITLE
join the tokio tasks spawned by batch query execution

### ISSUE THREAD

**Issue by Gun9niR** [risingwavelabs/risingwave#5886]
Can we also store the `JoinHandle` in the query result fetcher, and `join` it when the stream is done? So that we can never worry about this issue in the future. 🤪

_Originally posted by @BugenZhao in https://github.com/risingwavelabs/risingwave/issues/5822#issuecomment-1276412834_
      
But we cannot `join` the tasks when the stream is done, because `drop` is not `async`. We need to join them a bit earlier than that.

**Comment by BowenXiao1999** [comment]
Sorry, I may have missed some thing. Why is it must required to join the handle?

**Comment by Gun9niR** [comment]
> Sorry, I may have missed some thing. Why is it must required to join the handle?

To avoid bugs like #5816 from happening again.

**Comment by liurenjie1024** [comment]
After the query execution is cleaned up, this is no longer necessary.
