### ISSUE TITLE
Discussion(meta): add a `fe_ddl_catalog_check` option to test meta's DDL

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#5895]
Now for the DDL statement, we have to place to check if it is illegal such as duplicated name.
1. check in the frontend with the catalog cache, it will be fast with the cache but might be wrong in a multi-frontend environment.
2. check in the meta with the catalog in metastore centralized.

The meta-check is more important and considered the single source of truth. But in our current test, we can hardly check that because of the frontend check.
So I propose adding a `fe_ddl_catalog_check` config option to control if check on the frontend, so that we can do the e2e test the check on meta.
c.c. @yezizp2012 @HuaHuaY

**Comment by HuaHuaY** [comment]
Some ddl statements depend on the results of the frontend catalog check. For example, `create index xxx on yyy` needs to check whether `yyy` is legal and then get a correct catalog of `yyy` to generate create index plan. So we cannot directly prohibit the frontend check. But in this case, if meta forgets to check whether `yyy` is legal, there will be a multi-frontend error. We need more discussion to design a plan to help test meta's DDL statements.

**Comment by BugenZhao** [comment]
I suggest hacking with an env var, as it's only for tests and not exposed to users. 🤔

**Comment by fuyufjh** [comment]
Not planned
