### ISSUE TITLE
Support Not Null constraint

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#5896]
### Describe the solution you'd like

A column should be not nullable if defined so by the user.

**Comment by skyzh** [comment]
We dropped not null support long time ago as we treat all values nullable. cc @fuyufjh any ideas?

**Comment by CAJan93** [comment]
Can I close this issue?

**Comment by xiangjinwu** [comment]
See #4513

Feel free to reopen if there are new reasons to support this.
