### ISSUE TITLE
Refactor meta DatabaseManager by BTreeMapTransaction

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#5917]
### Is your feature request related to a problem? Please describe.

I find a useful struct `BTreeMapTransaction` developed by @wenym1 which seems it can be used to refactor our meta 
 node `DatabaseManager`. Since we need to maintain a consistency between etcd and memory, that is what `BTreeMapTransaction` trying to solve. It can commit all operations into etcd before applying them to memory while keep its interface almost looking like `BTreeMap`. 

Pros: It can save us from error prone consistency between etcd and memory and speed up meta operation without accessing etcd every time. 

Cons: It consumes more memory than before.

**Comment by chenzl25** [comment]
#5918. Here is a draft of how to use `BTreeMapTransaction`  to refactor.

**Comment by yezizp2012** [comment]
Finished in #5918 .
