### ISSUE TITLE
Discussion: Push released version to docker hub.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#5926]
### Background

Some customers are trying to use our product and deploy it use docker. They are expected to use released version only but not nightly version.

### Design

1. Push released version to docker hub, and make it public.
2. We should mention only docker hub's images in user doc, and mention both images in developer doc.

**Comment by neverchanje** [comment]
I think it's not possible since the users will always have some feature requirements that we don't support ATM. There are generally two approaches:

- Create a side branch from the release branch and merge the new feature PRs into it.
- Rely on our daily CI for ensuring stability.

When

**Comment by neverchanje** [comment]
> Close public access of nightly version in github package.

I agree any companies that want to provide a service to a customer should use the well-tested release, but I disagree with that we should close the access to nightly releases. It's an open-source project and we don't guarantee stability except for the official releases. If the user insists to use an unstable version, we should permit it.

**Comment by liurenjie1024** [comment]
> I agree any companies that want to provide a service to a customer should use the well-tested release, but I disagree with that we should close the access to nightly releases. It's an open-source project and we don't guarantee stability except for the official releases. If the user insists to use an unstable version, we should permit it.

Sounds reasonable. And I think we should recommend user to use release images in docker hub, and mention github packages only in developer doc.

**Comment by skyzh** [comment]
We can set "latest" to latest release instead of latest nightly.

**Comment by liurenjie1024** [comment]
cc @hengm3467
