### ISSUE TITLE
Randomise leader election

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#5944]
### Is your feature request related to a problem? Please describe.

I noticed that we are currently always waiting for the same amount of time during leader election (see [here](https://github.com/risingwavelabs/risingwave/blob/c7a32dc74f48b0a1fc055ae77d3ec11a87f263ab/src/meta/src/rpc/server.rs#L139))

```
let mut tick_interval = tokio::time::interval(Duration::from_secs(lease_time / 2));
loop {
    tick_interval.tick().await;
```

Maybe it makes sense to randomise this a bit and give different instances a slightly different tick_interval. This way we would space out requests a bit. 

CC @yezizp2012 

### Additional context

[Raft](https://towardsdatascience.com/raft-algorithm-explained-a7c856529f40) also uses randomised timeouts during leader election to avoid collisions

**Comment by ArshErgon** [comment]
@CAJan93 whats the minimum value `lease_time` can have? and can you tell me how to test that particular file?

**Comment by yezizp2012** [comment]
Well, I think it's not that necessary to do this, because: 1. eventually we will replace it with APIs of etcd lib or (some big refactoring); 2. even in current implementation, etcd will guarantee only one node will register successfully, it will ensure sequential writing of each requests.

**Comment by CAJan93** [comment]
I agree, it is not needed, but it would still reduce the likelihood of simultaneous election-runs that may then be repeated. Therefore I introduced this randomisation in https://github.com/risingwavelabs/risingwave/pull/6466 
(it really is just very few lines of code)
