### ISSUE TITLE
column names in mv creation is ignored

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#5955]
### To Reproduce

```sql
create materialized view mv(a) as select x from t;
select * from mv;
 x
---
(0 rows)

create materialized view mv2(a,b) as select x from t;
select * from mv2;
 x
---
(0 rows)
```

### Expected behavior

```sql
create materialized view mv(a) as select x from t;
select * from mv;
 a
---
(0 rows)

create materialized view mv2(a,b) as select x from t;
ERROR:  too many column names were specified
```

**Comment by ZENOTME** [comment]
I'm trying to investigate it. 

https://github.com/risingwavelabs/risingwave/blob/1389854c6a4d143110018fcc12ad6f2ff0e9160d/src/frontend/src/handler/create_mv.rs#L92
From gen_create_mv_plan, we will return a table from StreamMaterialize and write the table to catalog later.
The column name in this table come from the query statement. So I think we can replace the column name in table with column name in mv.
