### ISSUE TITLE
storage: refactor full key from a concatenated &[u8] to a struct

### ISSUE THREAD

**Issue by wenym1** [risingwavelabs/risingwave#5960]
### Is your feature request related to a problem? Please describe.

Currently, for all the read and write on hummock, the keys passed in are all `user_key`, which is a concatenation of `table_id` and `table_key` (a temporary naming from myself). Before we process the logic, we will first concatenate the `user_key` and `epoch` into `full_key`, and we do the rest of processing. However, in many of our processing, we will split the `full_key` again to extract the `epoch`, `user_key`, and sometimes the `table_id`, which is unnecessary. 

Besides, currently the keys stored in `SharedBufferBatch` are all `full_key`, but all keys in a single `SharedBufferBatch` shares the same `table_id` and `epoch`, which wastes unnecessary spaces.

### Describe the solution you'd like

Currently we have a seldom used `FullKey` struct
```
pub struct FullKey<T: AsRef<[u8]>>(T);
```

We can refactor it as
```
pub struct FullKey<T: AsRef<[u8]>> {
    table_id: TableId,
    table_key: T,
    epoch: Epoch,
}
```

The following modification will be done accordingly
* For `get`, `iter` and `ingest_batch` in hummock, the key passed in will be `table_key` instead of `user_key`. `epoch` and `table_id` are already provided in the method input. `Keyspace` can be removed.
* Trait `HummockIterator` and `StateStoreIter` will return `FullKey` as the key, and Sstable builder will take `FullKey` struct as input.
* In `SharedBufferBatch`, we only store the individual `table_key`s. The `epoch` and `table_id` are shared.
* The `t` in the prefix of key encoding can be removed.

**Comment by Gun9niR** [comment]
Just a very rough estimation of memory improvement: running nexmark q5, the key + value size is roughly 80B. So by removing duplicated `epoch` and `table_id`, we should expect 16/80 = 20% of memory improvement in shared buffer data.

![image](https://user-images.githubusercontent.com/52783948/197129447-c81b96a8-737f-4a6a-ba4e-fa697004dc4a.png)

**Comment by Gun9niR** [comment]
We will need to remove `KeySpace` in the next PR.
