### ISSUE TITLE
storage: avoid storing a reversed epoch for full key

### ISSUE THREAD

**Issue by wenym1** [risingwavelabs/risingwave#5963]
### Is your feature request related to a problem? Please describe.

Currently, we store `u64::MAX - epoch` in the full key encoding. Initially, we do this to ensure that if we sort the key by dictionary order, the full key with a newer(greater) epoch comes first. However, such feature only works when the length of the keys are fixed. But currently, our keys are in variant length, and we can no longer simply compare the keys by dictionary order. We have to extract the epoch out, and then compare the epoch. Reversing the epoch seems unnecessary.

### Describe the solution you'd like

We can store the epoch directly in the full key as the last 8 bytes instead of `u64::MAX - epoch`.

**Comment by BugenZhao** [comment]
Do you mean to do this after #5960?
