### ISSUE TITLE
bug(streaming): Lru cache item might be evicted so `get().unwrap()` may fail

### ISSUE THREAD

**Issue by soundOfDestiny** [risingwavelabs/risingwave#5991]
### Describe the bug

Lru cache item might be evicted so `get().unwrap()` may fail
https://github.com/risingwavelabs/risingwave/blob/1389854c6a4d143110018fcc12ad6f2ff0e9160d/src/stream/src/executor/hash_agg.rs#L393

**Comment by BugenZhao** [comment]
I think the LRU cache will guarantee not to evict the data accessed in the current epoch? cc @yuhao-su

**Comment by soundOfDestiny** [comment]
> I think the LRU cache will guarantee not to evict the data accessed in the current epoch? cc @yuhao-su

It can be evicted here:
https://github.com/risingwavelabs/risingwave/blob/1389854c6a4d143110018fcc12ad6f2ff0e9160d/src/stream/src/executor/hash_agg.rs#L269

**Comment by yuhao-su** [comment]
> It can be evicted here:

A `LruCache::put` will not trigger any eviction. (`LruCache::push` does)

**Comment by soundOfDestiny** [comment]
> > It can be evicted here:
> 
> A `LruCache::put` will not trigger any eviction. (`LruCache::push` does)

I have read the source code of library.
A `LruCache::put` is POSSIBLE to trigger any eviction

**Comment by soundOfDestiny** [comment]
> > It can be evicted here:
> 
> A `LruCache::put` will not trigger any eviction. (`LruCache::push` does)

I have read the source code of library.
A `LruCache::put` is POSSIBLE to trigger eviction

**Comment by yuhao-su** [comment]
> let agg_group = agg_groups.put(key.to_owned(), None);

My bad. You are right. But the capacity of `LruCache` in `agg_groups` has been set to unlimited. The eviction will only be triggered at the end of an epoch

**Comment by soundOfDestiny** [comment]
> > let agg_group = agg_groups.put(key.to_owned(), None);
> 
> My bad. You are right. But the capacity of `LruCache` in `agg_groups` has been set to unbounded. The eviction will only be triggered at the end of an epoch

sorry. I forgot that its capacity is almost always usize::max
