### ISSUE TITLE
schema inconsistency with user input (case sensitivity)

### ISSUE THREAD

**Issue by tabVersion** [risingwavelabs/risingwave#6051]
### Describe the bug

```
dev=> create table t (Va int, Vb varchar) ;
CREATE_TABLE
dev=> select * from t;
 va | vb
----+----
(0 rows)
```

The schema we used to build the table does not match the one entered by the user
same behavior for materialized source

### To Reproduce

as above 

### Expected behavior

have schema exactly the same as user input 

### Additional context

case mismatch will cause the parser not to find the corresponding field in the received payload

**Comment by neverchanje** [comment]
I think we have just followed the pg behavior. It's acceptable to me that sacrifices a bit of convenience for pg compatibility.

https://stackoverflow.com/questions/20878932/are-postgresql-column-names-case-sensitive

**Comment by xxchan** [comment]
BTW, maybe we can include a notice (in pgwire) if the user provides an unquoted name with capital letters.

**Comment by xxchan** [comment]
feature not bug

**Comment by CAJan93** [comment]
> BTW, maybe we can include a notice (in pgwire) if the user provides an unquoted name with capital letters. https://github.com/risingwavelabs/risingwave/issues/3727

Really like this approach. We would still be compatible with PG, but also be transparent to users that they may encounter unexpected behaviour
