### ISSUE TITLE
storage: use slice as variable for `key_with_epoch`

### ISSUE THREAD

**Issue by Little-Wallace** [risingwavelabs/risingwave#6069]
### Is your feature request related to a problem? Please describe.

If we pass an variable `Vec<u8>` we must re-allocate this key if the capacity of this vector is less than the sum length of `user_key` and epoch. 
In most where we must convert slice to `Vec` and then pass it to `key_with_epoch`, and it means that we would allocate memory twice.

### Describe the solution you'd like

It is better to pass a slice and allocate the whole key in method `key_with_epoch`.

```rust
fn key_with_epoch(user_key: &[u8], epoch: HummockEpoch) -> Vec<u8> {

}
```

**Comment by BugenZhao** [comment]
FYI, we may use `Buf::chain` if we really care about the allocation and copying. 🤔
https://docs.rs/bytes/latest/bytes/trait.Buf.html#method.chain

**Comment by Little-Wallace** [comment]
It seems to be complex...

**Comment by Little-Wallace** [comment]
> FYI, we may use `Buf::chain` if we really care about the allocation and copying. 🤔 https://docs.rs/bytes/latest/bytes/trait.Buf.html#method.chain

key_with_epoch is also not convenient for unit test

**Comment by hzxa21** [comment]
After #6130, `key_with_epoch` is only used in tests so I think we can close this issue.
