### ISSUE TITLE
bug(binder): explicit cast of array constructor should propagate context inside

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#6077]
### Describe the bug

This is an edge case only when mixing elements of different type categories via an outer explicit cast. (low priority)

Working as expected:
```
select array[1, 2.5];  -- same type categories where implicit cast applies
select array[1, true];  -- expected error due to different type categories
select array[1::bool, true];  -- okay when explicit cast applied inside
```

The following is allowed by PostgreSQL but rejected in RisingWave, because `array[1, true]` is not a valid subexpr.
```
select array[1, true]::bool[];
```

### To Reproduce

```
select array[1, true]::bool[];
```

### Expected behavior

```
test=# select array[1, true]::bool[];
 array 
-------
 {t,t}
(1 row)
```

### Additional context

There was a similar issue for `insert values`, where extra external type info is preferred over usage of `align_types`:

https://github.com/risingwavelabs/risingwave/blob/87bf20c79e91d58dae3e7c19be055aec718455f2/src/frontend/src/binder/insert.rs#L56-L74

Another similar and related issue we already solved is the literal empty array, where `array[]` is an invalid subexpr but `array[]::int[]` as a whole is okay. We can just refactor/extend this part to solve this issue.

https://github.com/risingwavelabs/risingwave/blob/87bf20c79e91d58dae3e7c19be055aec718455f2/src/frontend/src/binder/expr/mod.rs#L391-L392

**Comment by ZENOTME** [comment]
I investigate it and find this caused by our process of bind_cast 
```
    pub(super) fn bind_cast(&mut self, expr: Expr, data_type: AstDataType) -> Result<ExprImpl> {
        let lhs = if matches!(&expr, Expr::Array(elements) if elements.is_empty())
            && matches!(&data_type, AstDataType::Array(_))
        {
            // The subexpr `array[]` is invalid and cannot bind by itself without a parent cast.
            // So we handle `array[]::T[]`/`cast(array[] as T[])` as a whole here.
            FunctionCall::new_unchecked(
                ExprType::Array,
                vec![],
                // Treat `array[]` as `varchar[]` temporarily before applying cast.
                DataType::List {
                    datatype: Box::new(DataType::Varchar),
                },
            )
            .into()
        } else {
            self.bind_expr(expr)?
        };
        lhs.cast_explicit(bind_data_type(&data_type)?)
    }
```
Looks like for `select <expr>::<type>`, we bind expr first, and cast expr to type.
But if \<expr\> is array[], maybe we should cast expr first.
