### ISSUE TITLE
sink: support print sink

### ISSUE THREAD

**Issue by wenym1** [risingwavelabs/risingwave#6078]
### Is your feature request related to a problem? Please describe.

Currently, we don't support print sink yet, while print sink can be a useful tool for debug.

### Describe the solution you'd like

Support print sink.

SQL will be like 
```
CREATE TABLE t (v1 int, v2 int, v3 int);

CREATE MATERIALIZED VIEW mv AS SELECT * FROM t;

CREATE SINK s FROM mv WITH (
    connector = 'print',
    prefix = 'my log prefix',
    suffix = 'my log suffix',
);
```

And then we run
```
INSERT INTO t3 VALUES (1, 2, 3), (1, 2, 3), (2, 2, 3), (3, 2, 3), (5, 2, 3), (8, 2, 3), (13, 2, 3), (21, 2, 3);
```

and we can see the insert record in the log of CN.

**Comment by fuyufjh** [comment]
Any updates?

**Comment by wenym1** [comment]
closed with https://github.com/risingwavelabs/risingwave/pull/6251
