### ISSUE TITLE
test: deterministic test fails on nightly-2022-10-16 toolchain

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#6088]
```
thread '<unnamed>' panicked at 'assertion failed: tv_nsec >= 0 && tv_nsec < NSEC_PER_SEC as i64', library/std/src/sys/unix/time.rs:66:9
--
  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  | note: run with `MADSIM_TEST_SEED=1666928543390955942` environment variable to reproduce this error
  | and make sure `MADSIM_CONFIG_HASH=C2F7CAF3EA64B636`
```

https://buildkite.com/risingwavelabs/pull-request/builds/11006#_

https://github.com/risingwavelabs/risingwave/pull/6025

All of them fail. Looks strange. Would you please take a look? @wangrunji0408 Thanks!

**Comment by wangrunji0408** [comment]
Weird. They all passed on my local environment. 🤯

**Comment by skyzh** [comment]
Yeah, you can start an EC2 in Singapore from risingwave AMI and see what's happening.

**Comment by wangrunji0408** [comment]
The memory layout of `std::time::{SystemTime, Instant}` was changed on Linux. 🥵
This will be fixed in https://github.com/madsim-rs/madsim/pull/88
