### ISSUE TITLE
Support a new schedule way for distributed LookupJoin

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#6089]
### Is your feature request related to a problem? Please describe.

https://github.com/risingwavelabs/rfcs/pull/6

<img width="863" alt="image" src="https://user-images.githubusercontent.com/9352536/198513912-dfd0fea5-baef-4ed1-98fb-996d158caa12.png">

### Describe the solution you'd like

Currently, we implement our distributed lookup join by scheduling them along with outer side table scan. In this feature request I propose to schedule distributed lookup join along with inner side table scan which can make it possible for each LookupJoin executor locally lookup their inner side data.

- We need to support a new kind of exchange type.
- We need to ensure distributed lookup join can do the lookup in the same CN.
- We need to support high efficient multi point lookup.

**Comment by liurenjie1024** [comment]
We're supposed to put rfcs to new repo, I would suggest to move the rfc from notion to https://github.com/risingwavelabs/rfcs

**Comment by chenzl25** [comment]
Close by https://github.com/risingwavelabs/risingwave/pull/6098.
