### ISSUE TITLE
feat(compute): Improve logging with actor_id, actor_id -> MV correspondence

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#6092]
We should add actor_id in logs (prefixing to anything that writes to stdout, e.g. println, info, error etc) to stream executors to improve the compute-node readability and debuggability.

As the next step, perhaps we should make it easy to determine the actor_id to MV correspondence from the logs. I.e., when we create a new actor, we can output 
```
creating actor with actor_id: XXX and node_type: `DynamicFilter` for mv: t1_gt_10 (query: `select * FROM t1 WHERE t1.x > 10`)
```

This is useful for etc deterministic tests where we do not have access to a live cluster environment and must decipher the logs.

Since actor_id may be recycled (?) we may have to use a u64 salt in addition to actor_id to give a unique_actor_id = (actor_id, random_salt).

**Comment by fuyufjh** [comment]
I think printing the actor_id would be fine. No need for u64 salt.

**Comment by fuyufjh** [comment]
Any updates?

**Comment by jon-chuang** [comment]
Actually, its straightforward to query the actor id from the executor `ActorContext` and output these in the logs/stdout. 

I tried to add such info to all logs by default, but somehow it does not make it past the async_stream macro.

As for actor <-> MV correspondence, I will make a debug level log as it can be quite verbose. Hopefully, it will be a little helpful.

**Comment by fuyufjh** [comment]
@jon-chuang Any updates?
