### ISSUE TITLE
support schema less debezium json format

### ISSUE THREAD

**Issue by waruto210** [risingwavelabs/risingwave#6094]
### Is your feature request related to a problem? Please describe.

debezium json message including schema is very verbose, flink recommends users use schema-less debezium json message.

```json
{
  "before": {
    "id": 111,
    "name": "scooter",
    "description": "Big 2-wheel scooter",
    "weight": 5.18
  },
  "after": {
    "id": 111,
    "name": "scooter",
    "description": "Big 2-wheel scooter",
    "weight": 5.15
  },
  "source": {...},
  "op": "u",
  "ts_ms": 1589362330904,
  "transaction": null
}
```

### Describe the solution you'd like

Add a property to specify if the debezium message includes schema.

**Comment by tabVersion** [comment]
up for the proposal. But we don't use the schema in the json for parse. we can make the field an option.

**Comment by waruto210** [comment]
> up for the proposal. But we don't use the schema in the json for parse. we can make the field an option.

Yes, we don't use the schema in the json for parsing, but to parse the schema-less message, we need to modify the debezium parser due to the different message structure.

including schema:
```json
{
  "schema": {...},
  "payload": {
    "before": {
      "id": 111,
      "name": "scooter",
      "description": "Big 2-wheel scooter",
      "weight": 5.18
    },
    "after": {
      "id": 111,
      "name": "scooter",
      "description": "Big 2-wheel scooter",
      "weight": 5.15
    },
    "source": {...},
    "op": "u",
    "ts_ms": 1589362330904,
    "transaction": null
  }
}
```

without schema:
```json
{
  "before": {
    "id": 111,
    "name": "scooter",
    "description": "Big 2-wheel scooter",
    "weight": 5.18
  },
  "after": {
    "id": 111,
    "name": "scooter",
    "description": "Big 2-wheel scooter",
    "weight": 5.15
  },
  "source": {...},
  "op": "u",
  "ts_ms": 1589362330904,
  "transaction": null
}
```

**Comment by neverchanje** [comment]
I don't think we should provide users an option, especially if we don't use the field at all.

```
if json["schema"] != null {
  if json.get("payload") == null {
    log.error("invalid debezium json message: {}", json);
    return;
  }
  json = json["payload"]
}
```

You can address this simply by peaking if there's a field named "schema", if there is, then extract the payload body.

**Comment by waruto210** [comment]
The solution will be discussed in the future.
