### ISSUE TITLE
streaming: imbalance between local and remote inputs

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#6099]
@KeXiangWang [discovers](https://singularity-data.quip.com/qKsrAnY98T4N/Problem-Description) that there's an imbalance between local and remote inputs.

To reproduce that, here's a simple workload.

```sql
create source bid (auction INTEGER, bidder INTEGER, price INTEGER, "date_time" TIMESTAMP)
with (
  connector = 'nexmark',
  nexmark.table.type = 'Bid',
  nexmark.split.num = '3',
  nexmark.min.event.gap.in.ns = '0'
) row format json;

create materialized view mv as select * from bid order by price desc limit 100;
```

Under 3 nodes configuration with `minimal_scheduling = true`, we have 3 source actors and 1 top-n actor. The top-n actor will be placed on a random worker.

Here're the metrics: the throughput of the source actor at the node where the top-n actor resides is significantly lower than others. That is, the local exchange is **more likely to be `Pending`** than the gRPC exchange. 🤯

<img width="1359" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/25862682/198558202-77a2a71a-dcad-44b1-a309-691b75a38d67.png">

I've confirmed it's caused by the different behavior of local and remote exchanges, and it seems to be...
- ~~not caused by #4505~~
- not caused by #4045, #4495
- not caused by `consume_budget` of tokio channel

Some attempts:
- Also use gRPC for local exchange:
<img width="688" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/25862682/198559014-bea95d05-1851-4077-975d-8b5d935d7c01.png">
- Increase buffer size from 16 to 128
<img width="688" alt="Pasted Graphic 3" src="https://user-images.githubusercontent.com/25862682/198560045-002d1de8-9bfe-472b-9914-813c40b16dbe.png">
- Increase buffer size from 16 to 1024
<img width="687" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/25862682/198560391-fe784354-d9dd-401f-ac81-fef1893b6f26.png">
- Increase local buffer size from 16 to 64, remote 16 to 32
<img width="692" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/25862682/198560339-32ef99c9-257f-482e-8973-1644bb4d42f2.png">

Some observations:
- By increasing the buffer size, the gap is decreased. So I guess that the upstream actor in the same runtime tends not to be scheduled, during the 16 buffered chunks consumed by the downstream, then the downstream will yield due to the empty channel. For remote exchange, however, there might be some background tasks (or even kernel I/O task?) continuously polling the gRPC stream, so we'll always get `Ready` and the upstream is blocked less.
- After killing the meta service and no barrier is injected, they'll become balanced again. 🤔

Some thoughts for workarounds:
- Always use gRPC for local exchange, except for no-shuffle. 🥵
- Try a size-bounded channel to give the exact same buffer configuration for local and remote.

UPDATE:

After reverting #4505, the throughput becomes balanced.

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/25862682/198581490-758c8637-fea2-4394-80e5-0de9fa660a53.png">

**Comment by yuhao-su** [comment]
After discussion will @BugenZhao, we found it might be caused the incorrect [initial_stream_window_size](https://docs.rs/tonic/latest/tonic/transport/struct.Endpoint.html#method.initial_stream_window_size) setting. The doc states it was set to 65536(64KB) by default, but it was actually set to 1MB... by default.

**Comment by StrikeW** [comment]
FYI. Actually the [doc](https://singularity-data.quip.com/ePLEAjCysb9l/Demystify-HTTP2-Flow-Control) I shared previously points out that the default stream window size configs in hyper library is 2MB. IIRC, 65535 is the default value in the HTTP2 specification ([link](https://datatracker.ietf.org/doc/html/rfc7540#section-5.2.1)).

**Comment by BugenZhao** [comment]
After #6170, the back-pressure looks much more balanced. Let's close this issue.
