### ISSUE TITLE
streaming: memory-size bounded channel for local exchange

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#6102]
We use a channel of 16 buffered chunks for both local and remote exchange, and an additional 65535-byte network window for the remote. The chunk number and size are actually not comparable, depending on the chunk cardinality and schema. We may use a memory-bounded channel in the future.

_Originally posted by @BugenZhao in https://github.com/risingwavelabs/risingwave/pull/6101#pullrequestreview-1160197258_

**Comment by BugenZhao** [comment]
We may make the remote exchange aware of row count instead of making the local channel size-bounded, as the size is also affected by the schema, which is hard to decide statically.

**Comment by lmatz** [comment]
We now have `estimated_(heap)_size`, does it make sense to make the channel memory size bounded

>as the size is also affected by the schema, which is hard to decide statically.
I suppose this issue is gone?

**Comment by BugenZhao** [comment]
Actually, the `estimated_size` interface was already introduced when this issue was opened. 🥵 But I'm still not sure whether it can work well for now.

- The estimated sizes for some types are still non-sense, like JSONB.
- We compact the chunk for remote exchange while not for local exchange. This can be unfair if we utilize the same size limit for them.
