### ISSUE TITLE
toolchain: revert workarounds and fix regressions in bumping

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#6103]
Too many workarounds are introduced when bumping toolchain to 2022-10-16 in #6025, including unnecessary `dyn`, `unsafe` and unnecessary allocation. We should revert them as soon as possible.

- [x] #6086
- [x] #6087
- [x] #6864
- [x] https://github.com/rust-lang/rust/issues/103423
- [ ] #6131
  - [x] #6205
  - [ ] https://github.com/rust-lang/rust/issues/104388

**Comment by skyzh** [comment]
It's 2022-10-16 indeed. Wrong title for the previous PR.

**Comment by fuyufjh** [comment]
@BugenZhao Just assigned you as the tracker. Please help to distribute the work
