### ISSUE TITLE
bug(frontend): `INSERT INTO t1 (v2, v1)` with support for NULL 

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#6128]
### Describe the bug

- Only work on this after https://github.com/risingwavelabs/risingwave/pull/5697 is merged, please. 
- Based on https://github.com/risingwavelabs/risingwave/issues/4046. See [issue discussion](https://github.com/risingwavelabs/risingwave/issues/4046#issuecomment-1293876393) 

```SQL 
create table t1 (v1 int, v2 int);
insert into t1 (v1) values (5); // raises error. should insert 5 into v1 Null into v2
```

**Comment by fuyufjh** [comment]
Can you help to fix it? 🥺

**Comment by CAJan93** [comment]
I will try to have a look into this as soon as the other PR is merged, but I will definitely need some help

**Comment by fuyufjh** [comment]
@CAJan93 Ping?

**Comment by CAJan93** [comment]
Sorry, I was/am focused on the meta HA setup 😢 Is this still a thing? You closed the issue @fuyufjh

**Comment by CAJan93** [comment]
Do we want to allow this? 

```SQL 
insert into t values (1, 2), (3, 4, 5);
```

On postgres I get `VALUES lists must all be the same length`, however I could also write it so that above statement defaults to `insert into t values (1, 2, NULL), (3, 4, 5);`

**Comment by fuyufjh** [comment]
> Do we want to allow this?
> 
> ```sql
> insert into t values (1, 2), (3, 4, 5);
> ```
> 
> On postgres I get `VALUES lists must all be the same length`, however I could also write it so that above statement defaults to `insert into t values (1, 2, NULL), (3, 4, 5);`

This rewriting is weird to me... Recommend following PG's behavior here.

**Comment by fuyufjh** [comment]
> Sorry, I was/am focused on the meta HA setup 😢 Is this still a thing? You closed the issue @fuyufjh

Sorry, that must be a mistake

**Comment by CAJan93** [comment]
When implicitly inserting nulls, I am currently assuming that every column is nullable. That is still the case, right?

**Comment by CAJan93** [comment]
PR is ready for review: #7667

**Comment by CAJan93** [comment]
PR is merged. Closing this issue.
