### ISSUE TITLE
Tracking: information_schema based on local execution mode

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#6149]
### Is your feature request related to a problem? Please describe.

For compatibility with [information_schema](https://www.postgresql.org/docs/current/information-schema.html) in postgreSQL and integration with some other tools, we'd better implement `information_schema` in RW based on local execution mode like what we have done for `pg_catalog`. Here are some views with high-priority:
- tables: https://www.postgresql.org/docs/current/infoschema-tables.html
- views: https://www.postgresql.org/docs/current/infoschema-views.html
- columns: https://www.postgresql.org/docs/current/infoschema-columns.html

**Comment by yezizp2012** [comment]
Cc @BowenXiao1999

**Comment by BowenXiao1999** [comment]
I suggest that For figuring our what we need most currently for system table

* For BI tools that use Python (e.g. Apache Superset): sqlalchemy, we are already able to provide a tool in here: https://github.com/risingwavelabs/sqlalchemy-risingwave. The tool can delegate some SQL requests. For you to better understand how this works: we override base.py (get_columns) and use `describe t` (it's risingwave dialect), so we do not need to handle the original sql query like [postgres](https://github.com/sqlalchemy/sqlalchemy/blob/af9d3ab9b8a0aaa43e9347fd251a087eebd71e1d/lib/sqlalchemy/dialects/postgresql/base.py#L3291) or [cockroach](https://github.com/cockroachdb/sqlalchemy-cockroachdb/blob/19e66cce1c1cafaf762cf587d46549dd6b43b3cf/sqlalchemy_cockroachdb/base.py#L191), as long as we return the required info. I will provide more docs and tools in sqlalchemy-risingwave repo.
* DuckDB has sample test:https://github.com/risingwavelabs/risingwave/issues/6115. But I doubt the efficiency of following this may not be so good. Blindly supporting it is a option, if we can add these tests very easily.
* Look at Metabase and JDBC. This is java system so sqlalchemy may not be able to use. But this will be a good place to discover what we miss for system_table or information_schema. @neverchanje and @nanderstabel seems investigating this, maybe can discuss with them for what we need most now.

Also we can do some enchancement for sqlalchemy-risingwave:
https://github.com/risingwavelabs/sqlalchemy-risingwave/issues

For example, fill get_columns, fill get_indexes, fill get_pk_constraint (now they are empty cuz they are not must-required info). Now seems we do not provide such "API" so I can not fetch the data from risingwave.

For example, now our `describe t` seems do not return detail type parameter. Like Decimal precision etc. This is not quite urgent I guess.

**Comment by yezizp2012** [comment]
Let's support functions like `get_columns` in sqlalchemy firstly, I believe that's much better to support it in `pg_catalog` and `information_schema` like others, rather than using `describe` or `show`.

**Comment by BowenXiao1999** [comment]
Oh there's also one point: 
Currently `show tables` can only show table instead of materialized view. However, we are expected to show mv cuz we want user to export it instead of directly on table.

Same for get columns on it. I think this is also important
