### ISSUE TITLE
explain ignores specified columns list

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#6156]
### Describe the bug

```sql 
create table t (v1 int, v2 int, v3 int);
explain insert into t (v3, v2, v1) values (1, 2, 3); 
                       QUERY PLAN                        
---------------------------------------------------------
 BatchExchange { order: [], dist: Single }
 └─BatchInsert { table: t }
   └─BatchValues { rows: [[1:Int32, 2:Int32, 3:Int32]] }
```

### Expected behavior

Should this not be `BatchValues { rows: [[3:Int32, 2:Int32, 1:Int32]] }`? I am aware that the values are still defined in the order `1, 2, 3`, but as a user I would not expect this behaviour. 

### Additional context

Relates to https://github.com/risingwavelabs/risingwave/issues/4046 https://github.com/risingwavelabs/risingwave/issues/6128
Please only work on this after PR is merged: https://github.com/risingwavelabs/risingwave/pull/5697

**Comment by fuyufjh** [comment]
closed by https://github.com/risingwavelabs/risingwave/pull/5697
