### ISSUE TITLE
test: enable `PG` regress test `json.sql`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#6176]
Check https://github.com/risingwavelabs/risingwave/tree/main/src/tests/regress to see how we enable the test case

**Comment by xiangjinwu** [comment]
https://www.postgresql.org/docs/current/datatype-json.html
> The `json` data type stores an exact copy of the input text, which processing functions must reparse on each execution; while `jsonb` data is stored in a decomposed binary format that makes it slightly slower to input due to added conversion overhead, but significantly faster to process, since no reparsing is needed.
>
> Because the `json` type stores an exact copy of the input text, it will preserve semantically-insignificant white space between tokens, as well as the order of keys within JSON objects. Also, if a JSON object within the value contains the same key more than once, all the key/value pairs are kept. (The processing functions consider the last value as the operative one.) By contrast, `jsonb` does not preserve white space, does not preserve the order of object keys, and does not keep duplicate object keys. If duplicate keys are specified in the input, only the last value is kept.
>
> In general, most applications should prefer to store JSON data as `jsonb`, unless there are quite specialized needs, such as legacy assumptions about ordering of object keys.

We do not support `json` type. If the text-preserving behavior is needed, it can just be stored as `varchar` and casted to `jsonb` before processing.
