### ISSUE TITLE
optimizer: optimize limit 0 to avoid execution.

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#6244]
### Is your feature request related to a problem? Please describe.

Running the following sql will take forever if there is no any optimization.
```sql
 SELECT SUM(i) FROM generate_series(0, 100000000000, 1) tbl(i) limit 0;
```

**Comment by fuyufjh** [comment]
`Limit 0` has been supported, but `generate_series` as a table function can only return all data at one time:

https://github.com/risingwavelabs/risingwave/blob/7b0f2d21d278013faca232d399d0366352b240e0/src/expr/src/table_function/mod.rs#L43

**Comment by fuyufjh** [comment]
This issue is misleading so let me close it for now.

**Comment by xiangjinwu** [comment]
> This issue is misleading

Could you elaborate on this?

My understanding is that this query returns nothing (0 rows), so it can just return immediately. But it does not need to happen in optimizer if the limit executor can stop earlier (#3481)

**Comment by fuyufjh** [comment]
> > This issue is misleading
> 
> Could you elaborate on this?
> 
> My understanding is that this query returns nothing (0 rows), so it can just return immediately. But it does not need to happen in optimizer if the limit executor can stop earlier (#3481)

Oh, got it.

**Comment by Dousir9** [comment]
Job done, PTAL. @chenzl25

**Comment by chenzl25** [comment]
#8013 has been merged. Thanks.
