### ISSUE TITLE
Support backfill operator for mv on mv

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#6275]
Based on the RFC: https://github.com/risingwavelabs/rfcs/pull/13
- [x] support in memory backfill operator. https://github.com/risingwavelabs/risingwave/pull/6341
- [ ] support persisting state backfill operator.
- [x] support uncommitted read from upstream mv. https://github.com/risingwavelabs/risingwave/pull/6341

**Comment by chenzl25** [comment]
Persisting the state of backfill executor is unnecessary now.

**Comment by kwannoel** [comment]
Hi I'm wondering if backfill operator is still required? I see the issue is re-opened. If yes, may I work on the outstanding task? (Persisting state of backfill executor)

**Comment by chenzl25** [comment]
> Hi I'm wondering if backfill operator is still required? I see the issue is re-opened. If yes, may I work on the outstanding task? (Persisting state of backfill executor)

Yes, of course. If the backfill executor can persist its state, we can scale even when creating mv on mv.

**Comment by chenzl25** [comment]
If you want to persist the backfill executor's state, I think this issue #8051 is related. @kwannoel
