### ISSUE TITLE
ci: fix codecov report on main

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#6277]
Currently codecov behaves strangely because cov reports on main is missing. It's because we do squash merge and do not run unit tests on main.

As mentioned [here](https://community.codecov.com/t/unable-to-determine-a-parent-commit-to-compare-against-in-base-branch-after-squash-and-merge/2480/14), one solution is:
- Save down the coverage report sent to Codecov using the -q option.
- Save that file as an artifact (GitHub Actions has upload-artifact)
- Trigger CI on merge, but only to download the above artifact and upload with the [-z 11](https://github.com/codecov/codecov-bash/blob/master/codecov#L150) option.

But I don't know how to do the artifact passing trick yet since we are using buildkite. Need some investigation. 🤪

Additional info: A previous different tiny attempt didn't seem to work https://github.com/risingwavelabs/risingwave/pull/6253.

**Comment by xxchan** [comment]
cc @huangjw806 any ideas?

**Comment by huangjw806** [comment]
The above method seems to be effective, buildkite supports uploading and downloading of artifacts, but buildkite does not seem to support triggering CI like github actions when PR is closed or merged, I will try to consult the official to see if there is any solution .

**Comment by huangjw806** [comment]
> Hi @huangjw806, is there any update from their side?

Unfortunately, Buildkite currently does not trigger CI steps when merging or closing a PR. I wonder if I should put unit-test back into the main pipeline, which seems to be cheap.

**Comment by xxchan** [comment]
Unit-test takes about 7 job minites. How much does it additionally cost? 🤔

**Comment by xxchan** [comment]
Well, what about using GHA to run unit tests on main and upload codecov reports? 😄

**Comment by huangjw806** [comment]
> Unit-test takes about 7 job minites. How much does it additionally cost? 🤔

Our current buildkite service is free, and the main cost is in aws ec2. We use spot instance, so the cost will not be too much.

**Comment by huangjw806** [comment]
> Well, what about using GHA to run unit tests on main and upload codecov reports?

If we use the GHA machine to run the unit-test, I guess it should be slow.
