### ISSUE TITLE
sink: support create sink on logical view

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#6285]
As suggested by @lmatz, since we have added the (initial) support for `VIEW` after #6023, we can expose this functionality with `CREATE SINK sink FROM logical_view` and everything sounds reasonable. We can make this feature experimental and develop it for benchmarking purposes first.

We have a lot of code logic reused by `CREATE SINK` with `CREATE MATERIALIZED VIEW`, so I believe we can support it without much effort.

1. Support binding any `TableFactor` in `FROM`.
2. Correctly handle the lifecycle of `SINK` without materialized view on meta service.
3. Resolve corner issues until #6160, #6161.

_Originally posted by @BugenZhao in https://github.com/risingwavelabs/risingwave/issues/5388#issuecomment-1308617133_

------

As the `VIEW` seems incomplete for now, how about extending the syntax also to support `CREATE SINK sink AS ...` (just like creating materialized views)?

**Comment by tabVersion** [comment]
Can we support sink directly from source without materializing anything after this?

**Comment by BugenZhao** [comment]
> Can we support sink directly from source without materializing anything after this?

Yes. That is exactly what it's for.
