### ISSUE TITLE
source: source reader will stall after replacing if previous reader has finished

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#6300]
The `SelectWithStrategy` maintains an internal state of termination for both sides. If one side is terminated, it'll never poll it in the future, for optimization.

```rust
match this.internal_state {
    InternalState::Start => {
        let next_side = (this.clos)(this.state);
        poll_inner(&mut this, next_side, cx)
    }
    InternalState::LeftFinished => match this.stream2.poll_next(cx) {
        Poll::Ready(None) => {
            *this.internal_state = InternalState::BothFinished;
            Poll::Ready(None)
        }
        a => a,
    },
    InternalState::RightFinished => match this.stream1.poll_next(cx) {
        Poll::Ready(None) => {
            *this.internal_state = InternalState::BothFinished;
            Poll::Ready(None)
        }
        a => a,
    },
    InternalState::BothFinished => Poll::Ready(None),
}
```

If the source reader has finished before split changing (or scaling), even if we replace it with a new active reader, the `SelectWithStrategy` still won't poll it anymore. So we can never get the chunks from this source! Actually, the `futures` has warned us about this.

> Note that care must be taken to avoid tampering with the state of the stream which may otherwise confuse this combinator.

https://github.com/risingwavelabs/risingwave/blob/5d8465af3fd406e3f742ba185ab176591d35f211/src/stream/src/executor/source/reader.rs#L88-L91

Since we set the event num for the Nexmark source in the deterministic scaling test, and it will finish after emitting all events, this is also why we get incorrect results if we allow scaling source in the chaos test.

- https://github.com/risingwavelabs/risingwave/pull/6062#discussion_r1006459041

https://github.com/risingwavelabs/risingwave/blob/5d8465af3fd406e3f742ba185ab176591d35f211/src/tests/simulation_scale/src/ctl_ext.rs#L101-L103

**Comment by tabVersion** [comment]
> If the source reader has finished before split changing (or scaling)

what does it mean "a source reader has finished"? The source abstraction always consumes an endless stream.

**Comment by BugenZhao** [comment]
> > If the source reader has finished before split changing (or scaling)
> 
> what does it mean "a source reader has finished"? The source always consumes an endless stream.

In production, yes. However, the nexmark source will "finish" if we set the event num for it.

https://github.com/risingwavelabs/risingwave/pull/5657#discussion_r990605544
