### ISSUE TITLE
feat: support `date_trunc` function

### ISSUE THREAD

**Issue by BowenXiao1999** [risingwavelabs/risingwave#6301]
### Is your feature request related to a problem? Please describe.

Mz: https://materialize.com/docs/sql/functions/date-trunc/
Pg: https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC:~:text=9.9.2.-,date_trunc,-The%20function%20date_trunc

We should support it cuz this is useful in temporal data (And also required by some BI Tools).

Just ask, cc @TennyZhuang , do we already support part of this or similar?

**Comment by fuyufjh** [comment]
Agree

**Comment by TennyZhuang** [comment]
We don't have a similar thing now, but LGTM

**Comment by BowenXiao1999** [comment]
Any progress 👀

**Comment by wangrunji0408** [comment]
I am working on this and it will be done tomorrow.
