### ISSUE TITLE
frontend:support to parse nest array like array[[],[]]

### ISSUE THREAD

**Issue by ZENOTME** [risingwavelabs/risingwave#6325]
### Is your feature request related to a problem? Please describe.

We can't support nest array like 'array[[1,2],[3,4]]'

In postgres 
```
test_db=> select array[[1,2],[3,4]];
     array
---------------
 {{1,2},{3,4}}
(1 row)
```

In risingwave 
```
dev=> select array[[1,2],[3,4]];
ERROR:  QueryError: sql parser error: Expected an expression:, found: [

dev=> select array[array[1,2],array[3,4]];
   ?column?
---------------
 {{1,2},{3,4}}
(1 row)
```

**Comment by BowenXiao1999** [comment]
Maybe this is by desgin. Cockroachdb also only support 1-dimensional: https://www.cockroachlabs.com/docs/v22.1/array.

**Comment by ZENOTME** [comment]
But we can support multi-dimension😂. We can support array[array[1,2],array[3,4]] but can't support array[[1,2],[3,4]]. So I think maybe it's just because parse can't support this syntax.

**Comment by fuyufjh** [comment]
@xiangjinwu Can you please take a look?

**Comment by xiangjinwu** [comment]
It is just a parser issue, as mentioned in [PostgreSQL](https://www.postgresql.org/docs/current/sql-expressions.html#SQL-SYNTAX-ARRAY-CONSTRUCTORS:~:text=In%20the%20inner%20constructors%2C%20the%20key%20word%20ARRAY%20can%20be%20omitted.):
> In the inner constructors, the key word `ARRAY` can be omitted.

Bowen is also right that multi-dimensional array can be tricky. But we can handle syntax and functionality issues separately.

**Comment by xiangjinwu** [comment]
Lowing priority because:
* There is a slightly verbose alternative to achieve the same functionality: `array[array[], array[]]`
* Multi-dimensional array won't be fully compatible with PostgreSQL anyways. See #3692

**Comment by gihong-park** [comment]
I know priority is low. but can i try this one? is just support multi-dimensional?

**Comment by xiangjinwu** [comment]
> I know priority is low. but can i try this one? is just support multi-dimensional?

Definitely yes, and thanks for your interest.

To be accurate, it is to support an additional syntax of multi-dimensional. As the example shows, we already support `array[array[1,2],array[3,4]]` but would like to support the more concise `array[[1,2],[3,4]]` as well.

**Comment by gihong-park** [comment]
okay, i'm on it. but we don't support `select [[1,2],[3,4]]`. right?

**Comment by xiangjinwu** [comment]
Right. `select [[1,2],[3,4]]` is considered invalid.
