### ISSUE TITLE
dashboard does not start along with meta node

### ISSUE THREAD

**Issue by tabVersion** [risingwavelabs/risingwave#6337]
### Describe the bug

on commit [001387d](https://github.com/risingwavelabs/risingwave/commit/001387d34b32c69ff4002b6e7640735dd5aaaf1d)
```
./risedev d full
...
✅ tmux: session risedev
✅ prepare: all previous services have been stopped
✅ minio: api http://127.0.0.1:9301/, console http://127.0.0.1:9400/
✅ etcd: api 127.0.0.1:2388
✅ meta-node-5690: api grpc://127.0.0.1:5690/, dashboard http://127.0.0.1:5691/
✅ compute-node-5688: api grpc://127.0.0.1:5688/
✅ frontend-4566: api postgres://127.0.0.1:4566/
✅ compactor-6660: compactor 127.0.0.1:6660
✅ prometheus: api http://127.0.0.1:9500/
✅ grafana: dashboard http://127.0.0.1:3001/
✅ zookeeper-2181: zookeeper 127.0.0.1:2181
✅ kafka-29092: kafka 127.0.0.1:29092
✅ dev cluster: done bootstrapping with config full
---- summary of startup time ----
minio: 0.20s
etcd: 0.36s
meta-node-5690: 1.30s
compute-node-5688: 3.89s
frontend-4566: 1.29s
compactor-6660: 2.74s
prometheus: 0.08s
grafana: 0.38s
zookeeper-2181: 1.79s
kafka-29092: 3.64s
-------------------------------
```

then got 404 when visiting http://127.0.0.1:5691/

### To Reproduce

mentioned above 

### Expected behavior

open the webpage normally

### Additional context

None

**Comment by BugenZhao** [comment]
Have you set `ENABLE_BUILD_DASHBOARD_V2` with `risedev configure` before? If so, please disable it and you should find there're artifacts downloaded under `.risingwave/ui`.

**Comment by tabVersion** [comment]
yes, after disable dashboard v2, everything goes well

**Comment by BugenZhao** [comment]
> after disable dashboard v2

I think we only have dashboard v2 now? The effect of this configuration is **`BUILD`**, that is, to build the React project locally, which I think is the reason.

**Comment by tabVersion** [comment]
Yes, I think so. since we have migrated to v2 completely, should we remove the dashboard option in risedev?.

**Comment by BugenZhao** [comment]
I guess nope. The option decides whether to build or download the dashboard artifacts. For dashboard developers, this might be useful.
