### ISSUE TITLE
SqlSmith Bug Hunt: Correlated Subquery group by a "Hop" relation outside the subquery

### ISSUE THREAD

**Issue by marvenlee2486** [risingwavelabs/risingwave#6350]
### Describe the bug

Some assertion error when I am trying to allow Correlated Subquery in EXISTS 

Error
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `LeftSemi`,
 right: `Inner`', src/frontend/src/optimizer/rule/apply_agg.rs:32:9

### To Reproduce

Please refer to next Comments for original query generated by sql smith

### Additional context

I have reduced the query as such

```
create table auction (date_time date);
select * from hop( auction, auction.date_time, INTERVAL '1', INTERVAL '3600' ) AS hop_1
where EXISTS (select hop_1.date_time group by hop_1.date_time);
```

The problem is with calling a group by of a relation generated with hop outside the subquery.

**Comment by marvenlee2486** [comment]
-- Failing SQL setup code:
CREATE TABLE supplier (
    s_suppkey INTEGER,
    s_name VARCHAR,
    s_address VARCHAR,
    s_nationkey INTEGER,
    s_phone VARCHAR,
    s_acctbal NUMERIC,
    s_comment VARCHAR,
    PRIMARY KEY (s_suppkey)
);

CREATE TABLE part (
    p_partkey INTEGER,
    p_name VARCHAR,
    p_mfgr VARCHAR,
    p_brand VARCHAR,
    p_type VARCHAR,
    p_size INTEGER,
    p_container VARCHAR,
    p_retailprice NUMERIC,
    p_comment VARCHAR,
    PRIMARY KEY (p_partkey)
);

CREATE TABLE partsupp (
    ps_partkey INTEGER,
    ps_suppkey INTEGER,
    ps_availqty INTEGER,
    ps_supplycost NUMERIC,
    ps_comment VARCHAR,
    PRIMARY KEY (ps_partkey, ps_suppkey)
);

CREATE TABLE customer (
    c_custkey INTEGER,
    c_name VARCHAR,
    c_address VARCHAR,
    c_nationkey INTEGER,
    c_phone VARCHAR,
    c_acctbal NUMERIC,
    c_mktsegment VARCHAR,
    c_comment VARCHAR,
    PRIMARY KEY (c_custkey)
);

CREATE TABLE orders (
    o_orderkey BIGINT,
    o_custkey INTEGER,
    o_orderstatus VARCHAR,
    o_totalprice NUMERIC,
    o_orderdate DATE,
    o_orderpriority VARCHAR,
    o_clerk VARCHAR,
    o_shippriority INTEGER,
    o_comment VARCHAR,
    PRIMARY KEY (o_orderkey)
);

CREATE TABLE lineitem (
    l_orderkey BIGINT,
    l_partkey INTEGER,
    l_suppkey INTEGER,
    l_linenumber INTEGER,
    l_quantity NUMERIC,
    l_extendedprice NUMERIC,
    l_discount NUMERIC,
    l_tax NUMERIC,
    l_returnflag VARCHAR,
    l_linestatus VARCHAR,
    l_shipdate DATE,
    l_commitdate DATE,
    l_receiptdate DATE,
    l_shipinstruct VARCHAR,
    l_shipmode VARCHAR,
    l_comment VARCHAR,
    PRIMARY KEY (l_orderkey, l_linenumber)
);

CREATE TABLE nation (
    n_nationkey INTEGER,
    n_name VARCHAR,
    n_regionkey INTEGER,
    n_comment VARCHAR,
    PRIMARY KEY (n_nationkey)
);

CREATE TABLE region (
    r_regionkey INTEGER,
    r_name VARCHAR,
    r_comment VARCHAR,
    PRIMARY KEY (r_regionkey)
);
CREATE TABLE person (
    id BIGINT,
    name VARCHAR,
    email_address VARCHAR,
    credit_card VARCHAR,
    city VARCHAR,
    state VARCHAR,
    date_time TIMESTAMP,
    extra VARCHAR,
    PRIMARY KEY (id)
);

CREATE TABLE auction (
    id BIGINT,
    item_name VARCHAR,
    description VARCHAR,
    initial_bid BIGINT,
    reserve BIGINT,
    date_time TIMESTAMP,
    expires TIMESTAMP,
    seller BIGINT,
    category BIGINT,
    extra VARCHAR,
    PRIMARY KEY (id)
);

CREATE TABLE bid (
    auction BIGINT,
    bidder BIGINT,
    price BIGINT,
    channel VARCHAR,
    url VARCHAR,
    date_time TIMESTAMP,
    extra VARCHAR
);
CREATE MATERIALIZED VIEW m0 AS SELECT 8957902997102223200 AS col_0, false AS col_1, true AS col_2 FROM bid AS t_0 GROUP BY t_0.bidder, t_0.date_time, t_0.extra;CREATE MATERIALIZED VIEW m1 AS SELECT INTERVAL '3600' AS col_0, 1 AS col_1, DATE '2022-11-07' AS col_2 FROM auction AS t_0 WHERE SMALLINT '0' <= 9223372036854775807 GROUP BY t_0.category, t_0.item_name, t_0.date_time, t_0.extra, t_0.initial_bid, t_0.description, t_0.seller, t_0.id;CREATE MATERIALIZED VIEW m2 AS SELECT FLOAT '2147483647' AS col_0 FROM region AS t_0 WHERE CAST(INT '1' AS BOOLEAN) GROUP BY t_0.r_regionkey HAVING false;CREATE MATERIALIZED VIEW m3 AS SELECT t_0.ps_suppkey + (INT '829576316' + DATE '2022-11-03') AS col_0 FROM partsupp AS t_0 WHERE FLOAT '2147483647' = INT '1604453012' GROUP BY t_0.ps_suppkey, t_0.ps_partkey;CREATE MATERIALIZED VIEW m4 AS SELECT 2836954130010584797 & char_length(t_0.l_returnflag) AS col_0, SMALLINT '1' AS col_1, REAL '355287522.8297138' * INTERVAL '604800' AS col_2, TIMESTAMP '2022-11-05 10:42:54' AS col_3 FROM lineitem AS t_0 GROUP BY t_0.l_extendedprice, t_0.l_tax, t_0.l_discount, t_0.l_shipmode, t_0.l_comment, t_0.l_commitdate, t_0.l_suppkey, t_0.l_quantity, t_0.l_receiptdate, t_0.l_returnflag;CREATE MATERIALIZED VIEW m5 AS SELECT SMALLINT '9893' - (SMALLINT '3616' | SMALLINT '0') AS col_0 FROM m3 AS t_0 GROUP BY t_0.col_0;CREATE MATERIALIZED VIEW m6 AS SELECT 3500603856389889228 AS col_0, INT '1094532497' AS col_1 FROM person AS t_0 GROUP BY t_0.date_time, t_0.credit_card, t_0.name, t_0.email_address, t_0.id HAVING false;CREATE MATERIALIZED VIEW m7 AS SELECT t_0.extra AS col_0 FROM auction AS t_0 WHERE false GROUP BY t_0.expires, t_0.category, t_0.reserve, t_0.extra, t_0.initial_bid, t_0.seller, t_0.date_time HAVING false;CREATE MATERIALIZED VIEW m8 AS SELECT t_0.reserve AS col_0, 1282303939.5576653 AS col_1 FROM auction AS t_0 WHERE 2032318120.3180583 >= REAL '1' GROUP BY t_0.expires, t_0.category, t_0.description, t_0.item_name, t_0.date_time, t_0.reserve, t_0.initial_bid, t_0.seller, t_0.id, t_0.extra;CREATE MATERIALIZED VIEW m9 AS SELECT DATE '2022-11-13' AS col_0, t_1.col_2 AS col_1 FROM lineitem AS t_0 JOIN m4 AS t_1 ON t_0.l_orderkey = t_1.col_0 GROUP BY t_1.col_3, t_1.col_2 HAVING true;

-- Failing SQL query:
SELECT TIMESTAMP '2022-11-14 08:02:09' AS col_0, INTERVAL '76307' AS col_1, INT '2147483647' AS col_2 FROM m4 AS t_0, m5 AS t_1, customer AS t_2, region AS t_3, supplier AS t_4, m6 AS t_5, m6 AS t_6, hop(m4, m4.col_3, INTERVAL '1', INTERVAL '1') AS hop_7, m1 AS t_8, person AS t_9, part AS t_10, lineitem AS t_11, m9 AS t_12, bid AS t_13, m6 AS t_14 JOIN customer AS t_15 ON t_14.col_1 = t_15.c_nationkey, hop(auction, auction.date_time, INTERVAL '1', INTERVAL '3600') AS hop_16 WHERE EXISTS (SELECT INT '243380385' AS col_0, OVERLAY(TRIM('OTX8ynjZO0') PLACING TRIM(TRAILING 'LyWPL74U5x' FROM t_4.s_address) FROM char_length('4lBawBcF08')) AS col_1, sq_44.col_0 IS NULL AS col_2, 'PapmOrR5vw' AS col_3 FROM lineitem AS t_17 JOIN m7 AS t_18 ON t_17.l_linestatus = t_18.col_0, m5 AS t_19, m4 AS t_20, partsupp AS t_21, region AS t_22, m3 AS t_23, hop(bid, bid.date_time, INTERVAL '1', INTERVAL '227499') AS hop_24, part AS t_25, orders AS t_26, (SELECT DATE '2022-11-13' AS col_0, t_42.o_custkey AS col_1 FROM part AS t_27, m3 AS t_28, lineitem AS t_29, part AS t_30, m4 AS t_31, lineitem AS t_32, m0 AS t_33, person AS t_34, m3 AS t_35, m6 AS t_36, m7 AS t_37, hop(bid, bid.date_time, INTERVAL '1', INTERVAL '604800') AS hop_38, customer AS t_39, m2 AS t_40, person AS t_41, orders AS t_42 JOIN part AS t_43 ON t_42.o_custkey = t_43.p_partkey WHERE true GROUP BY t_30.p_container, t_29.l_discount, t_29.l_extendedprice, t_32.l_shipinstruct, t_42.o_custkey, t_31.col_1, t_31.col_3, t_34.date_time, hop_38.extra, t_34.name, t_29.l_tax, t_32.l_shipdate, t_34.credit_card, t_41.extra, hop_38.price, t_41.name, t_32.l_suppkey, t_41.state, t_32.l_comment, t_29.l_quantity, t_32.l_orderkey, t_30.p_comment, t_28.col_0, t_33.col_0, hop_38.channel, t_29.l_partkey, t_43.p_type, t_39.c_acctbal, t_29.l_suppkey, t_30.p_size, hop_38.date_time, t_36.col_0, t_32.l_shipmode, t_31.col_0, t_43.p_name, t_32.l_linenumber, t_27.p_container, t_34.email_address, t_43.p_container, t_41.city, t_29.l_shipmode, t_42.o_clerk, t_29.l_shipdate) AS sq_44, person AS t_45 WHERE true GROUP BY t_11.l_returnflag, t_5.col_0, t_4.s_address, t_21.ps_comment, t_9.email_address, t_25.p_retailprice, t_25.p_container, t_8.col_0, hop_7.col_1, hop_16.item_name, t_11.l_discount, hop_24.price, hop_24.bidder, t_8.col_2, t_12.col_0, t_17.l_shipinstruct, t_21.ps_supplycost, t_20.col_1, t_26.o_shippriority, t_10.p_type, t_45.credit_card, hop_16.extra, t_25.p_partkey, t_9.extra, t_26.o_orderstatus, t_45.name, t_25.p_name, t_2.c_nationkey, t_15.c_acctbal, t_2.c_mktsegment, t_3.r_regionkey, sq_44.col_0, t_10.p_container, t_0.col_1, t_11.l_extendedprice, t_5.col_1, t_26.o_clerk, t_4.s_phone, t_17.l_partkey, t_10.p_size, t_10.p_mfgr, t_11.l_receiptdate, t_17.l_returnflag, t_15.c_nationkey, t_6.col_0, hop_16.seller, t_45.state, t_9.state, t_15.c_name, t_0.col_3, t_11.l_linenumber, t_9.name, t_11.l_partkey, t_17.l_shipdate, t_11.l_shipdate, hop_16.initial_bid, t_22.r_regionkey, t_23.col_0, t_25.p_size, t_17.l_shipmode, t_10.p_name, hop_7.col_3, t_17.l_tax, t_15.c_mktsegment, t_26.o_orderkey, t_13.date_time, t_3.r_name, t_26.o_orderpriority, t_25.p_comment, hop_7.col_0, sq_44.col_1, t_20.col_3, hop_24.extra, t_2.c_custkey, t_17.l_comment, t_20.col_2, t_21.ps_availqty, t_18.col_0, t_2.c_comment, t_45.date_time, t_13.channel, t_9.date_time, t_11.l_tax, t_45.email_address, hop_24.date_time, t_8.col_1, hop_7.col_2, t_2.c_acctbal, t_17.l_quantity, t_13.extra, t_9.id, hop_16.reserve, t_0.col_0, t_26.o_totalprice, t_21.ps_suppkey, t_0.col_2, t_22.r_comment, t_11.l_orderkey, hop_16.description, t_10.p_brand, t_17.l_receiptdate, t_19.col_0, t_4.s_name, hop_16.id, t_20.col_0, t_11.l_suppkey, t_13.auction, t_11.l_quantity, t_1.col_0, t_26.o_comment, t_2.c_address, t_14.col_0, t_17.l_orderkey, t_15.c_address, hop_16.category, t_45.id, t_13.price, t_13.bidder, t_10.p_comment, t_11.l_commitdate, t_25.p_brand, hop_24.url, t_26.o_orderdate, t_25.p_mfgr) GROUP BY t_4.s_nationkey, t_15.c_address, t_0.col_3, t_6.col_0, t_13.channel, t_10.p_name, t_5.col_0, t_0.col_1, t_4.s_phone, t_4.s_suppkey, hop_16.id, t_8.col_2, t_11.l_quantity, hop_16.reserve, t_11.l_linestatus, t_11.l_extendedprice, t_0.col_0, t_12.col_1, t_3.r_comment HAVING false;

---- END

thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `LeftSemi`,
 right: `Inner`', src/frontend/src/optimizer/rule/apply_agg.rs:32:9

**Comment by fuyufjh** [comment]
@chenzl25 Can you please take a look?

**Comment by chenzl25** [comment]
> @chenzl25 Can you please take a look?

Ok.
