### ISSUE TITLE
common: resolve stack symbols when format

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#6357]
https://docs.rs/backtrace/latest/backtrace/struct.Backtrace.html allows capture a backtrace without resolving symbols and resolve the symbols later. This can both make capturing stack backtrace faster, and potentially mitigate the backtrace segfault issue.

**Comment by BugenZhao** [comment]
I guess this is already the default behavior?

**Comment by skyzh** [comment]
I'm not sure :(

**Comment by BugenZhao** [comment]
https://doc.rust-lang.org/stable/src/std/backtrace.rs.html#133-137

The variant is `LazilyResolvedCapture`. 🥵
