### ISSUE TITLE
batch: Implement source executor in batch query.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#6359]
Implement batch source executor which reads data from source split.

**Comment by tabVersion** [comment]
will we reuse the streaming source executor for batch?

**Comment by ZENOTME** [comment]
I don't think so, using streaming executor in batch looks weird. We will implement a batch source executor.

**Comment by tabVersion** [comment]
Then is there any adjustment to the connecters' abstraction?

**Comment by liurenjie1024** [comment]
> Then is there any adjustment to the connecters' abstraction?

Currently no.

**Comment by ZENOTME** [comment]
closed by #6627
