### ISSUE TITLE
feat: enable state table for Sink to meet needs of recovery

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#6370]
### Is your feature request related to a problem? Please describe.

~~After that, even though we can only guarantee at-least-once, it's still better than multiplier growth of old data when recovery.~~

**Comment by BugenZhao** [comment]
What do you mean by "multiplier growth of old data"? 🤔

**Comment by yezizp2012** [comment]
When rebuild the sink executor, it will consumer and sink out all upstream data, because it have no persist status.

**Comment by yezizp2012** [comment]
> What do you mean by "multiplier growth of old data"? 🤔

Oh, the failure of my local recovery test on sink is cause by at-least-once, there's nothing to do with state table in Sink.

**Comment by tabVersion** [comment]
> there's nothing to do with state table in Sink

IIRC, sink has no state table inside
