### ISSUE TITLE
streaming: utilize a generic row type

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#6371]
Design doc: [RFC: My Secret Row Trait](https://singularity-data.quip.com/10j5As3BgMdP/RFC-My-Secret-Row-Trait)

Under this design, we can reduce the overhead of allocating, copying, and converting as much as possible, which is in favor of the new state table interface.

- [x] #6374
- [x] #6432
- [x] #6433
- [x] #6576
- [x] #6735
- [x] #5969

**Comment by fuyufjh** [comment]
> which is in favor of the new state table interface.

Could you elaborate it more?

**Comment by BugenZhao** [comment]
> > which is in favor of the new state table interface.
> 
> Could you elaborate it more?

cc @wcy-fdu @wenym1 @st1page  👀

**Comment by st1page** [comment]
> > which is in favor of the new state table interface.
> 
> Could you elaborate it more?

the caller should pass the pk or pk prefix parameters as a Row in the state table's interface. The row should support random access to compute vnode and get the bloom filter hint. Now we can only use `Vec<Datum>` there. But sometimes they are in Chunk and support random access naturally, so we do not need a copy to construct the `Vec<Datum>`.
