### ISSUE TITLE
bashboard: page crash when two mv rely on one source

### ISSUE THREAD

**Issue by tabVersion** [risingwavelabs/risingwave#6388]
### Describe the bug

as title

### To Reproduce

start a local cluster by `./risedev d full` and prepare some data `./scripts/source/prepare_ci_kafka.sh`

then run 

```sql
dev=> create source s6 (v1 int, v2 varchar) with (connector = 'kafka', topic = 'kafka_4_partition_topic_with_100_message', properties.bootstrap.server = '127.0.0.1:29092', scan.startup.mode = 'earliest') row format json;
CREATE_SOURCE
dev=>
dev=> create materialized view v1 as select * from s6 ;
CREATE_MATERIALIZED_VIEW
dev=> create materialized view v2 as select * from s6 ;
CREATE_MATERIALIZED_VIEW
```

the streaming graph page crashes
![image](https://user-images.githubusercontent.com/14017336/202088442-c2449aab-6fc1-4ee5-876d-480e0488c431.png)
![image](https://user-images.githubusercontent.com/14017336/202088519-c0730cd3-aed8-4a56-90b8-c7f901e8d571.png)

### Expected behavior

show dep graph

### Additional context

None

**Comment by BugenZhao** [comment]
It seems this page fails in most cases. 🥵

**Comment by fuyufjh** [comment]
> It seems this page fails in most cases. 🥵


+1
