### ISSUE TITLE
streaming: Now Executor for `TemporalFilter`

### ISSUE THREAD

**Issue by soundOfDestiny** [risingwavelabs/risingwave#6407]
Frontend:
  - [x] #6669

Streaming:
  - [x] #6408 
  - [x] #6501
  - [x] #6889
  - [ ] https://github.com/risingwavelabs/risingwave/issues/6790

Misc:
  - [ ] #6813 

Regarding TemporalFilter
> I'm not sure whether we achieve a consensus on the design meeting.
> 
> I'd prefer to introduce a now table function as the input of dynamic filter, instead of introduce the temporal filter explicitly.

https://github.com/risingwavelabs/risingwave/pull/6377#issuecomment-1316461934

**Comment by jon-chuang** [comment]
Could you link some of the design docs or context?

**Comment by soundOfDestiny** [comment]
> Could you link some of the design docs or context?

This is to implement temporal filter. ('Now' + projection) + dynamic filter == temporal filter

**Comment by jon-chuang** [comment]
Hmm, but actually, we will implement a standalone `TemporalFilter`, right? https://github.com/risingwavelabs/risingwave/pull/6377 So I guess this operator is as a fallback for when we cannot optimize `now()` into the standalone `TemporalFilter`?

Anw, it seems that the now executor will also produce `Watermark` messages? So is this executor the only part of our system responsible for emitting this message? Else, I am quite confused why `now` operator would need to emit these messages?

**Comment by soundOfDestiny** [comment]
> Hmm, but actually, we will implement a standalone `TemporalFilter`, right? (#6377) So I guess this operator is as a fallback for when we cannot optimize `now()` into the standalone `TemporalFilter`?
> 
> Anw, it seems that the now executor will also produce `Watermark` messages? So is this executor the only part of our system responsible for emitting this message? Else, I am quite confused why `now` operator would need to emit these messages?
> 
> Because it seems that in the case of standalone temporal filter the state cleaning can be performed based on the updated timestamp derived from the epoch, rather than the watermark? Furthermore, we will not need to use the `now` operator in the standalone temporal filter, so where does the watermark play a role?

They cannot stand together. We can either have a temporal filter executor or have a now executor. I implement both in case and we can choose one later :-)

**Comment by jon-chuang** [comment]
Oh, I see :sweat_smile: . Ok, I see the comments by others on introducing now operator instead. 

Anyway, I kind of agree, there is a lot of overlap of `DynamicFilter` with `TemporalFilter`. I think we can refactor `DynamicFilter` with append-only optimization...

Well, we should decide on the direction before investing further...

Also probably a good idea to link the comment where the idea was suggested. I've changed the OP.

**Comment by soundOfDestiny** [comment]
link #6670 as reference

**Comment by soundOfDestiny** [comment]
Let's wait for #6813 and contents (rather than `todo!`s) of watermark framework
