### ISSUE TITLE
deps: upgrade clap to 4

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#6416]

**Comment by 0xkelvin** [comment]
hello @fuyufjh , let me take this

**Comment by fuyufjh** [comment]
Sure, thanks! @0xkelvin

**Comment by TennyZhuang** [comment]
@0xkelvin Hi, any updates on the issue? If you have any problems or are busy with other things, I can take over the issue.

**Comment by 0xkelvin** [comment]
working on this, just a bit delay since on leave on year end.

**Comment by fuyufjh** [comment]
Note: May be heavily conflicted with #7523

**Comment by fuyufjh** [comment]
Hi, any updates so far?
