### ISSUE TITLE
source: introduce mock source for unit testing

### ISSUE THREAD

**Issue by xx01cyx** [risingwavelabs/risingwave#6427]
### Is your feature request related to a problem? Please describe.

Currently, there is no way to write unit tests for streaming source in source executor.

### Describe the solution you'd like

A `MockSource` could be introduced, which mocks the behavior of external source.

**Comment by tabVersion** [comment]
Then what is the expected behavior? I think datagen is what you are looking for.

**Comment by TennyZhuang** [comment]
> Then what is the expected behavior? I think datagen is what you are looking for.

datagen is not friendly for UT.

**Comment by xx01cyx** [comment]
Due to our code design, if we are to construct a mock source for source executor, we must pass a `Receiver` (or sth. alike) into connector properties (which impls `Serialization` & `Deserialization`) before the construction of the source executor. Via the offline discussion with @tabVersion , there are 2 solutions for now:

1. Pass an HTTP endpoint (not good to include such network stuff in unit testing)
2. Construct the `Receiver` beforehand and pass its memory address (seems hack)

Wonder if there's any better solution for this.

cc. @xxchan @fuyufjh @BugenZhao

**Comment by fuyufjh** [comment]
To test the streaming operators, I think "append-only table source" is enough, which allows you to insert values to form an append-only stream.

Can you please explain more about the motivation for this issue? 

By the way, Tao has once proposed to introduce an HTTP endpoint to allow users to POST data (e.g. JSON) into RisingWave. It sounds similar, but it's a user-facing feature rather than designed for testing.

**Comment by fuyufjh** [comment]
Just guess: If you are thinking about testing watermark, the append-only table source should support it after https://github.com/risingwavelabs/risingwave/issues/6952 is done.

**Comment by xx01cyx** [comment]
> To test the streaming operators, I think "append-only table source" is enough, which allows you to insert values to form an append-only stream.
> 
> Can you please explain more about the motivation for this issue?
> 
> By the way, Tao has once proposed to introduce an HTTP endpoint to allow users to POST data (e.g. JSON) into RisingWave. It sounds similar, but it's a user-facing feature rather than designed for testing.

This is just for testing source executor, and is not for testing watermark. For now, we use datagen for source executor ut, which generates data in a background task asynchronously following a predefined pattern. I'm actually thinking of a foreground way of generating source data, and this issue limits the scope to unit testing. 

Actually, datagen is working well in source executor ut (though not perfect). Maybe we can keep this as it is, and instead of implementing the mock source, we could broaden the scope beyond unit testing by introducing the HTTP source.
