### ISSUE TITLE
batch: Limit number of concurrent distribute batch query in frontend.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#6459]
Add a parameter in frontend node to limit number of concurrent distributed queries.

**Comment by ZENOTME** [comment]
I find that we will serve a query util it complete before serve next query in pgwire. So I think we don't have a case where a frontend node run multiple concurrent query?🤔

**Comment by xxchan** [comment]
You can have multiple concurrent connections?

**Comment by liurenjie1024** [comment]
Close by #7845
