### ISSUE TITLE
Is plan-fragments.svg represent correct?

### ISSUE THREAD

**Issue by ZENOTME** [risingwavelabs/risingwave#6469]
### Background

According our [implementation](https://github.com/risingwavelabs/risingwave/blob/709e1be6fc19445d16af78c86ddbfb5dd8d67209/src/frontend/src/scheduler/plan_fragmenter.rs#L526), I think exchange should be the last node in a stage. But in [plan-fragment.svg](https://github.com/risingwavelabs/risingwave/blob/main/docs/images/architecture-design/plan-fragments.svg), exchang node draw like the first node in a stage. Looks a little misleading I think🤔

**Comment by BugenZhao** [comment]
Yes. I guess the edge between `HashAgg` and another `Exchange` should be inverted.

**Comment by ZENOTME** [comment]
> Yes. I guess the edge between HashAgg and another Exchange should be inverted.

I run this query and get the result like:

stage 0:
 BatchProject { exprs: [sum(t.quantity)] }
└─BatchHashAgg { group_key: [t.company], aggs: [sum(t.quantity)] }
  └─BatchExchange { order: [], dist: Single }
                       
stage 1:          
    └─BatchProject { exprs: [t.company, t.quantity] }.    // connect to BatchExchange in stage0 
      └─BatchScan { table: t, columns: [quantity, company] }
