### ISSUE TITLE
Bug: watermark_time_ms attempt to add with overflow

### ISSUE THREAD

**Issue by Li0k** [risingwavelabs/risingwave#6500]
### Describe the bug

Executing nexmark_q7 for 30 minutes, it is found that `lru_manager` panic.

<img width="989" alt="image" src="https://user-images.githubusercontent.com/15023748/203038896-4a6e3a0a-06fe-4022-a58b-a2dfb351010e.png">

```rust
 watermark_time_ms += self.barrier_interval_ms as u64 * step;
```

### To Reproduce

1. single node ec2 (commit b4206153d1fcb59d36e4eb33b79dc9520a38499a)
2. change risingwave.toml  total_memory_available_bytes = 4294967290
3. run nexmark q7 30min

### Additional context

```rust
    last_total_bytes_used = cur_total_bytes_used;
            // watermark_time_ms += self.barrier_interval_ms as u64 * step;
            let diff = match (self.barrier_interval_ms as u64).checked_mul(step) {
                Some(x) => x,
                None => panic!(
                    "barrier_interval_ms {}, step {}",
                    self.barrier_interval_ms, step
                ),
            };

            watermark_time_ms = match watermark_time_ms.checked_add(diff) {
                Some(x) => x,
                None => panic!("watermark_time_ms {}, diff {}", watermark_time_ms, diff),
            };
```

add some panic log for `watermark_time_ms`, try to explore the cause of the failure, and find that the value of `step` has become very large.

<img width="992" alt="image" src="https://user-images.githubusercontent.com/15023748/203040319-5d106c18-a1e4-4a07-84d1-ee9ff400ca31.png">

```rust
 // The strategy works as follow:
            //
            // 1. When the memory usage is below the graceful threshold, we do not evict any caches
            // and reset the step to 0.
            //
            // 2. When the memory usage is between the graceful and aggressive threshold:
            //   - If the last eviction memory usage decrease after last eviction, we set the
            //     eviction step to 1
            //   - or else we set the step to last_step + 1
            //
            // 3. When the memory usage exceeds aggressive threshold:
            //   - If the memory usage decrease after last eviction, we set the eviction step to
            //     last_step
            //   - or else we set the step to last_step * 2

            step = if cur_total_bytes_used < mem_threshold_graceful {
                // Do not evict if the memory usage is lower than `mem_threshold_graceful`
                0
            } else if cur_total_bytes_used < mem_threshold_aggressive {
                // Gracefully evict
                if last_total_bytes_used > cur_total_bytes_used {
                    1
                } else {
                    step + 1
                }
            } else if last_total_bytes_used > cur_total_bytes_used {
                // Aggressively evict
                if step == 0 {
                    2
                } else {
                    step * 2
                }
            } else {
                step
            };
```

According to the calculation algorithm of `step`, it is suspected that the `evict` is not timely enough, the memory usage value has entered a certain state, and the branch is continuously hit, causing the step index to rise.

**Comment by Li0k** [comment]
@yuhao-su  PTAL

**Comment by lmatz** [comment]
@yuhao-su still thinking if there is any possibility to add some dedicated tests for LRU Manager, besides e2e tests.

Per the last discussion:
> since the managed lru are bounded by memory size, it is hard to find a way to do deterministic test to check whether those shouldn’t be evicted got evicted

Guess real memory usage can be mocked in some way?

**Comment by BowenXiao1999** [comment]
> According to the calculation algorithm of step, it is suspected that the evict is not timely enough, the memory usage value has entered a certain state, and the branch is continuously hit, causing the step index to rise.

`evict` is not timely enough: Which variable is `evict`? 🤔

And do you mean the Aggressively branch was continuously hit?

**Comment by BugenZhao** [comment]
There's another issue with the exponential increasing `step`: it can grows to a time in the future. If so, entries inserted will always be evicted immediately during this period even if there's enough memory.
