### ISSUE TITLE
bug: There should exists a way to cancel the MV Job

### ISSUE THREAD

**Issue by sushantgupta** [risingwavelabs/risingwave#6508]
### Describe the bug

Their should be a way to cancel the MV job, I have created a MV with very big interval and which got stuck.
So, I want to cancel the job, entered the CTL C, but this didn't help. the command got stuck for 12 hours.

### To Reproduce

`dev=> CREATE
MATERIALIZED VIEW y1 AS
SELECT B.auction,
       B.price,
       B.bidder,
       B.date_time
FROM bid B
         JOIN (SELECT MAX(price) AS maxprice,
                      window_end as date_time
               FROM
                   TUMBLE(bid, date_time, INTERVAL '1000000000000000' SECOND)
               GROUP BY window_end) B1 ON B.price = B1.maxprice
WHERE B.date_time BETWEEN B1.date_time - INTERVAL '1000000000000000' SECOND
          AND B1.date_time;

^CCancel request sent

^CCancel request sent

Scenario 2:
`
dev=> create source bid (auction INTEGER, bidder INTEGER, price INTEGER, "date_time" TIMESTAMP)
with (
  connector = 'nexmark',
  nexmark.table.type = 'Bid',
  nexmark.split.num = '3',
  nexmark.min.event.gap.in.ns = '0'
) row format json;

create materialized view mv as select * from bid order by price desc limit 10;
ERROR:  QueryError: Catalog error: source with name bid exists

^CCancel request sent
^CCancel request sent
^C^CCancel request sent
^CCancel request sent`

`

### Expected behavior

The command should not stuck or should be respond to CTL C.

**Comment by lmatz** [comment]
Related: #6488

**Comment by fuyufjh** [comment]
duplicated
