### ISSUE TITLE
test: enable `PG` regress test `strings.sql`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#6517]
Check https://github.com/risingwavelabs/risingwave/tree/main/src/tests/regress to see how we enable the test case

**Comment by lmatz** [comment]
Since #6355 and #6426, and this issue contains many test cases involving `bytea`, may use them to validate the implementation @BowenXiao1999

**Comment by BowenXiao1999** [comment]
Added some modified test from: https://github.com/risingwavelabs/risingwave/blob/b804479ff608f49f659df564f7b453d14bafdc08/src/tests/regress/data/sql/strings.sql#L69 

in the first pr of #6426

**Comment by lmatz** [comment]
#8952
