### ISSUE TITLE
for empty strings in struct not adding any value 

### ISSUE THREAD

**Issue by sushantgupta** [risingwavelabs/risingwave#6530]
### Describe the bug

while Adding a empty string in struct it is not adding any value.

### To Reproduce
```
dev=>  create table t2 (a struct<v1 int, v2 varchar>);
CREATE_TABLE
dev=> insert into t2 values ((1, '')), ((8, NULL)), ((2, ' '));
INSERT 0 3
dev=> select * from t2;
    a
----------
 (8,NULL)
 (2, )
 (1,)     <=======
(3 rows)

dev=>
```

### Expected behavior

(1,NULL) should be added for (1,)

**Comment by xiangjinwu** [comment]
We actually fixed a bug earlier that empty string `''` was treated as `null` (#4521 duplicates: #4768 #5842).

The actual expected output from PostgreSQL is:
```
test=# with t2(a) as (values ((1, '')), ((8, NULL)), ((2, ' '))) select * from t2;
    a    
---------
 (1,"")
 (8,)
 (2," ")
(3 rows)
```

This incompatibility of display (not the actual value stored) is a known issue tracked by https://github.com/risingwavelabs/risingwave/issues/4769#issuecomment-1290908459

**Comment by fuyufjh** [comment]
It's due to the way we display text. Wrapping with quotes would be clearer. Will be tracked in https://github.com/risingwavelabs/risingwave/issues/4769#issuecomment-1290908459
