### ISSUE TITLE
Container aware resource limitations

### ISSUE THREAD

**Issue by arkbriar** [risingwavelabs/risingwave#6536]
### Is your feature request related to a problem? Please describe.

Currently, some of the default cache sizes depend on the total available memory from `System::total_memory`, which, as expected, is the full memory of the host machine. But that might cause a problem with OOM when running RisingWave inside a container, where processes can be limited in CPU and memory not equal to the full size. 

### Describe the solution you'd like

A possible solution is that we can set the parameter `total_memory_available_bytes` before starting the RisingWave. Still, I think it would be better to be container-awareness, so we don't have to answer why unexpected OOM happens.

### Describe alternatives you've considered

As described above.

### Additional context

cgroups Linux manual: https://man7.org/linux/man-pages/man7/cgroups.7.html

**Comment by lmatz** [comment]
Checked this yesterday, and found one tricky issue:

the compute node does not strictly respect this parameter `total_memory_available_bytes` because the LRU Manager evicts entries from the operator cache periodically instead of doing this whenever an operator inserts some entry into the operator cache.

Correct me if I am wrong, cc @yuhao-su, shall we explicitly specify this parameter in the configuration when starting the nodes, otherwise, OOM still can happen even in a non-container environment.

**Comment by yuhao-su** [comment]
> shall we explicitly specify this parameter in the configuration when starting the nodes

The exceeding limit case can happen regardless you set the parameter `total_memory_available_bytes`
or not.

But if we set the `total_memory_available_bytes` as something smaller than the host memory capacity, it can be a workaround to prevent OOM. 

The final solution should be to allow eviction within an epoch. I think doing this in hash join can mitigate the problem in many cases. I'll try to do this first.

**Comment by lmatz** [comment]
> we hope to set the default total_memory_available_bytes in docker as the container memory size?

I think it is good for RisingWave to check whether the parameter really makes sense (<= real memory size available in a container or non-container environment) when starting.

If setting the parameter is too large, then RW can just panic and refuse to start.

**Comment by arkbriar** [comment]
Sorry for having no time on this issue. I asked for help from @sixletters, and he would like to take it. I am truly grateful! 

I have unassigned myself and re-assigned it to @sixletters.
cc. @fuyufjh

**Comment by fuyufjh** [comment]
Hi, how is the progress now?

**Comment by sixletters** [comment]
Hi Eric, the PR for this is ready and can be merged. Runji has approved it a few days ago.
