### ISSUE TITLE
inserting into w/ column names doesn't work properly

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#6542]
### Describe the bug

There are two problems right now on 0.1.14-rc:
1. The RisingWave doesn't insert a null by default for ignored columns
2. The data inserted is not aligned w/ the column names

### To Reproduce

On RisingWave 0.1.14-rc
```
dev=> create table t (v1 int, v2 int, v3 int);
CREATE_TABLE
dev=> insert into t (v1, v2, v3) values (1, 2, 3);
INSERT 0 1
dev=> insert into t (v2, v3) values (2, 3);
ERROR:  QueryError: Bind error: INSERT has more target columns than expressions
dev=> insert into t (v2, v3, v1) values (2, 3, 1);
INSERT 0 1
dev=> select * from t;
 v1 | v2 | v3
----+----+----
  1 |  2 |  3
  3 |  1 |  2
(2 rows)
```

### Expected behavior

On PG
```
postgres@192:postgres> create table t (v1 int, v2 int, v3 int);
CREATE TABLE
Time: 0.048s
postgres@192:postgres> insert into t (v1, v2, v3) values (1, 2, 3);
INSERT 0 1
Time: 0.031s
postgres@192:postgres> select * from t;
+----+----+----+
| v1 | v2 | v3 |
|----+----+----|
| 1  | 2  | 3  |
+----+----+----+
SELECT 1
Time: 0.041s
postgres@192:postgres> insert into t (v2, v3, v1) values (2, 3, 1);
INSERT 0 1
Time: 0.082s
postgres@192:postgres> select * from t;
+----+----+----+
| v1 | v2 | v3 |
|----+----+----|
| 1  | 2  | 3  |
| 1  | 2  | 3  |
+----+----+----+
SELECT 2
Time: 0.089s
postgres@192:postgres> insert into t (v2, v3) values (2, 3);
INSERT 0 1
Time: 0.064s
postgres@192:postgres> select * from t;
+--------+----+----+
| v1     | v2 | v3 |
|--------+----+----|
| 1      | 2  | 3  |
| 1      | 2  | 3  |
| <null> | 2  | 3  |
+--------+----+----+
SELECT 3
Time: 0.279s
```

**Comment by xiangjinwu** [comment]
* The first problem on null is an intentional intermediate step. #6128
* The second problem is likely a bug of #5697 @CAJan93 Could you please take a look?

**Comment by CAJan93** [comment]
Hey @xiangjinwu, I want to have a look, but am busy with the meta HA setup at the moment. How urgent is this? Is it okay if I have a look at it in some time?

**Comment by xiangjinwu** [comment]
Maybe we can consider this feature as not-yet-fully-supported in 0.1.14, which includes (1) updating `insert into t (v2, v3, v1)` to an unimplemented error in 0.1.14-rc and (2) resolving both issues in 0.1.15. What do you think? @cyliu0

**Comment by fuyufjh** [comment]
@xiangjinwu @CAJan93 Since `INSERT` is a very common statement in databases, really hope this could be fixed ASAP

**Comment by CAJan93** [comment]
I will work on the `INSERT` bug. Draft PR will be posted here: https://github.com/risingwavelabs/risingwave/pull/6590 
Atm I do not have capacity for the `null` feature.

**Comment by CAJan93** [comment]
I believe I fixed the bug. Please have a look at the PR: https://github.com/risingwavelabs/risingwave/pull/6590

**Comment by CAJan93** [comment]
https://github.com/risingwavelabs/risingwave/pull/6590 is merged. I hope that the bug is fixed and that the column is now alligned with whatever is defined in the `INSERT` statement. Thank you @chenzl25 for you approval

**Comment by cyliu0** [comment]
@fuyufjh @CAJan93 Do we need to cherrypick the fix into 0.1.14?

**Comment by fuyufjh** [comment]
> @fuyufjh @CAJan93 Do we need to cherrypick the fix into 0.1.14?

Yes, please do it

**Comment by CAJan93** [comment]
Thank you for cherry-picking @cyliu0. Cherry-picked commit on `v0.1.14-rc` is `4c508c2602e025108258b180c392b514dea1f44e`

**Comment by cyliu0** [comment]
Fixed in https://github.com/risingwavelabs/risingwave/pull/6590
