### ISSUE TITLE
CN crash due to dropping non-empty stream chunk builder

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#6551]
### Describe the bug

The issue was found when I was running a test that continuously adds new MVs (nexmark_q7) to a cluster. 

When there are 50+ MVs, 

1. Firstly compute node 1 encounters timeout when trying to read object store, subsequently causes actor exits.
2. Then compute node 1 crashes due to `dropping non-empty stream chunk builder`.
3. Thus meta cannot finish recovery.

### To Reproduce

Deploy a 3 compute node cluster and `bash run_tasks.sh` [here](https://github.com/risingwavelabs/risingwave/tree/wangzheng/test_lots_mv). (make sure meta:5690 and frontend:4566 are reachable specified in `run.sh`).
MVs will be continuously created. It will take minutes to trigger the issue (console running `bash run_tasks.sh` will receive error message).

### Expected behavior

- Transient object store error better not fail actor.
- CN shouldn't crash. ~~Recovery should succeed.~~

### Additional context

[cn-1-panic.log](https://github.com/risingwavelabs/risingwave/files/10080694/cn-1-panic.log)
[meta.log](https://github.com/risingwavelabs/risingwave/files/10080698/meta.log)
[cn-2.log](https://github.com/risingwavelabs/risingwave/files/10080696/cn-2.log)
[cn-0.log](https://github.com/risingwavelabs/risingwave/files/10080697/cn-0.log)
[compactor.log](https://github.com/risingwavelabs/risingwave/files/10080699/compactor.log)
[source.log](https://github.com/risingwavelabs/risingwave/files/10080701/source.log)

**Comment by soundOfDestiny** [comment]
😱

**Comment by fuyufjh** [comment]
I have encountered this before. I think the assertion of "dropping non-empty stream chunk builder" is a little bit too strict, especially for some exceptional path. How about just remove it?

**Comment by fuyufjh** [comment]
Check this logs of a failure of longevity test: [175_logs.txt](https://github.com/risingwavelabs/risingwave/files/10100812/175_logs.txt) ([CI Run](https://buildkite.com/risingwave-test/longevity-test/builds/178#0184ba43-97d6-45c0-8d82-a561b2cbd4eb))

The panic happened during `HashJoinExecutor::eq_join_oneside`.

```
  24:     0x55735e23b67b - core::ptr::drop_in_place<risingwave_stream::executor::hash_join::HashJoinExecutor<risingwave_common::hash::key::FixedSizeKey<4_usize>,risingwave_storage::monitor::monitored_store::MonitoredStateStore<risingwave_storage::hummock::HummockStorage>,0_u8>::eq_join_oneside<0_u8>::{{closure}}>::h34d87e375cee7a2a
```

Check the code of [eq_join_oneside](https://github.com/risingwavelabs/risingwave/blob/0128ff1b312ae22f51e979a73bd5cb9f61831c39/src/stream/src/executor/hash_join.rs#L768) and you will find lots of `?` are there. In theory, any one among them could cause the assertion failure `dropping non-empty stream chunk builder`.

@yuhao-su Do you have any better ideas than my proposal?

>  I have encountered this before. I think the assertion of "dropping non-empty stream chunk builder" is a little bit too strict, especially for some exceptional path. How about just remove it?

cc. @BugenZhao @TennyZhuang

**Comment by yuhao-su** [comment]
> How about just remove it?
Yes, I think we can remove it.

**Comment by fuyufjh** [comment]
> @yuhao-su Do you have any better ideas than my proposal?

I mean, in theory, a better solution should be eliminating the `?`s and handling the failures carefully (e.g. at least cleaning the ChunkBuilder), is it possible?

**Comment by BugenZhao** [comment]
> I mean, in theory, a better solution should be eliminating the `?`s and handling the failures carefully (e.g. at least cleaning the ChunkBuilder), is it possible?

I guess this is hard. Almost all errors that occur at `?` in streaming executors cannot be handled, and it's meant to throw directly. 🤔 Actually there are only a few "bomb"s in our system, like `heap::PeekMut` and `DataChunkBuilder`, I think ad-hoc fixes on them should be enough. For `DataChunkBuilder`, logging a `warn`, `debug_assertion` or simply remove the `Drop` all LGTM.

**Comment by yuhao-su** [comment]
> at least cleaning the ChunkBuilder.

It is possible to do this. But still, it is hard to handle other errors like bugen mentioned.
