### ISSUE TITLE
Error message on numbers-out-of-range is inconsistent.

### ISSUE THREAD

**Issue by huangjw806** [risingwavelabs/risingwave#6565]
### Describe the bug

The scientific notation of numbers error is inconsistent.

### To Reproduce

```
dev=> create table t (v1 int);
CREATE_TABLE
dev=> INSERT INTO t values (1e9);
INSERT 0 1

dev=> INSERT INTO t values (1e10);
ERROR:  QueryError: internal error: Expr error: Can't cast risingwave_common::types::decimal::Decimal to i32

dev=> INSERT INTO t values (1e30);
ERROR:  QueryError: internal error: Unable to bind 1e30 to a number
```

1e10 exceeds the maximum value of `int`, and 1e30 exceeds the maximum value of `decimal`.
Although the error behavior is inconsistent within the kernel, it is consistent for users.

### Expected

For reference, the error message from PostgreSQL is easier to understand:
```
test=# INSERT INTO t values (1e10);
ERROR:  integer out of range

test=# INSERT INTO t values (1e999999); -- 1e30 exceeds decimal in RW but not in PG, so we use a larger number here
ERROR:  value overflows numeric format
LINE 1: INSERT INTO t values (1e999999);
                              ^
```

**Comment by fuyufjh** [comment]
Didn't get the point actually. What's the expected behavior?

**Comment by huangjw806** [comment]
> Didn't get the point actually. What's the expected behavior?

@xiangjinwu gives an error message for PostgreSQL above, I expect it like this.
