### ISSUE TITLE
feat: Implement `create table as  select`

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#6569]
### Is your feature request related to a problem? Please describe.

Implement `create table as select` statement to support duckdb test.

**Comment by lmatz** [comment]
PG:
```
martin=# CREATE TABLE t AS SELECT 1/i FROM generate_series(5,-1,-1) tbl(i);
ERROR:  division by zero
martin=# \d
Did not find any relations.
```

Some sort of atomicity here 👀

**Comment by liurenjie1024** [comment]
Achieving this atomicity is easy, we just need to collect all select result before inserting to tables, but it would not be easy to rollback when insertion failed.

**Comment by liurenjie1024** [comment]
After checking the code, I'm afraid it's not easy, it's similar to `insert into select`, but we have to create table first.

**Comment by lmatz** [comment]
For the testing purpose,
we can just manually decompose it into:
`create table XXX`
and 
`insert into XXX select`.
This is the practice currently used in some test cases such as `limit`.

I think `duckdb` does not intend to `create table as select` statement in the few ones listed in #5970

**Comment by liurenjie1024** [comment]
> For the testing purpose,
> 
> we can just manually decompose it into:
> 
> `create table XXX`
> 
> and 
> 
> `insert into XXX select`.
> 
> This is the practice currently used in some test cases such as `limit`.
> 
> 
> 
> I think `duckdb` does not intend to test `create table as select` statement in the few ones listed in #5970 

LGTM

**Comment by HuaHuaY** [comment]
I think we can do this by following "create mv on mv". 
1. First we pin an epoch in storage, create a mv and let this mv get the corresponding data of `select`.
2. We change the source of this mv to a new table source.
The mv in step 1 and the source in step 2 form the new table.

In this way, if `select` fails, we will not create a new table.

**Comment by st1page** [comment]
-1, I think maybe it is not clear enough semantics in our system. "create materialized view as" is similar with "create table as " and the user does not know if the table can subscribe and maintain the changes of the query result.

**Comment by fuyufjh** [comment]
-1 for `create table as select`. The semantic is a little bit confusing as mentioned by @st1page, and I don't think this feature is necessary in real-world cases.

+1 for @lmatz's idea: https://github.com/risingwavelabs/risingwave/issues/6569#issuecomment-1330318749

**Comment by liurenjie1024** [comment]
I think it's quite clear what's the difference between table and materialized view: we can do dml directly on table while not on materialized view, otherwise we should not have table and support for `insert into table`. 

As with the motivation, it's used in duckdb test and I'm not sure the effort rewriting all statements in it.

As with `insert select`, I think we have supported it in a simple fasion, with single thread dml execution mode, which is enough for the usage.

**Comment by fuyufjh** [comment]
> As with insert select, I think we have supported it in a simple fasion, with single thread DML execution mode, which is enough for the usage.

Sounds too hacky to me. I prefer to either support or not support it, instead of 'half'-support like this...

> I think it's quite clear what's the difference between table and materialized view: we can do dml directly on table while not on materialized view, otherwise we should not have table and support for insert into table.

`insert select` is used as the command to create a **continuous** streaming job in Flink, while you are trying to make it a pure batch query. This is highly likely to lead to misuse.

I guess @st1page was talking about his proposal: [Rethink Consistency among Table, MView, and Source](https://www.notion.so/risingwave-labs/WIP-RFC-Rethink-Consistency-among-Table-MView-and-Source-e0458901721c4767b75dc2f61be6569b)

**Comment by liurenjie1024** [comment]
I mean we have already implemented `insert select`: https://www.risingwave.dev/docs/latest/sql-insert/

**Comment by lmatz** [comment]
If too hacky, we can disable it by default in production #6454

**Comment by st1page** [comment]
> I think it's quite clear what's the difference between table and materialized view: we can do dml directly on table while not on materialized view

I agree with that. What I am concern is that if a user writes a `create table t as select * from origin`, should we apply all the changes from `origin` to the `t`?

**Comment by st1page** [comment]
for `insert select` we need more discussion and I agree to make it a pure batch query... in person, I think We encourage user to use DDL to create continuous streaming jobs and don't need to follow FlinkSQL at all.

**Comment by liurenjie1024** [comment]
> > I think it's quite clear what's the difference between table and materialized view: we can do dml directly on table while not on materialized view
> 
> I agree with that. What I am concern is that if a user writes a `create table t as select * from origin`, should we apply all the changes from `origin` to the `t`?

I think no, which is compatible with most database implementation.

**Comment by liurenjie1024** [comment]
> for `insert select` we need more discussion and I agree to make it a pure batch query... in person, I think We encourage user to use DDL to create continuous streaming jobs and don't need to follow FlinkSQL at all.

+1, `insert select` and `create table as select` should all be used for test/experiment purpose, just like other dml statements.

**Comment by lmatz** [comment]
Do we agree on banning `insert select` in production until `for insert select we need more discussion`?

**Comment by liurenjie1024** [comment]
How do you plan to ban it? Use some configuration to control on/off by default?

**Comment by fuyufjh** [comment]
> I mean we have already implemented `insert select`: https://www.risingwave.dev/docs/latest/sql-insert/

Sorry I didn't know this before... But why we introduced it? For testing?

> Do we agree on banning insert select in production until for insert select we need more discussion?

+1 for it.

> How do you plan to ban it? Use some configuration to control on/off by default?

Another `unsafe_` options 😅

**Comment by liurenjie1024** [comment]
So, do we reach consensus that:
1. Add support for `create table as select`
2. Ban it on production by default?

**Comment by fuyufjh** [comment]
> So, do we reach consensus that:
> 
> 1. Add support for `create table as select`
> 2. Ban it on production by default?

Not my original proposal but acceptable to me

**Comment by ZENOTME** [comment]
There are two limit now:
1. not support assign column name using create table new_table(<column_name>), e.g. `create table new_table(i) as select * from t;` will return a error
2. not support function alias, e.g. `create table new_table as select sum(id) from t;`

But seems create-select-as not used in production(only used in test?), do we need to support limit above? If not, we can close this issue now?

**Comment by liurenjie1024** [comment]
I think it would be convenient to support 1, and we don't need to support 2.
