### ISSUE TITLE
Feat(SqlSmith): Refactor to enable correlated subquery

### ISSUE THREAD

**Issue by marvenlee2486** [risingwavelabs/risingwave#6592]
### Is your feature request related to a problem? Please describe.

Refer to https://github.com/risingwavelabs/risingwave/pull/4431#issuecomment-1327417328

Refer to https://github.com/risingwavelabs/risingwave/pull/4431#issuecomment-1327488801

**Comment by marvenlee2486** [comment]
@kwannoel, Lets continue discussion here.
From this https://github.com/risingwavelabs/risingwave/pull/4431#issuecomment-1327488801,

I think the probability of rejection are super high, Because it is like if you have nested subquery of k level,
One level use correlated subquery with agg 'Select' or 'Having', then it gonna been rejected. 

I also feel that currently the unsupported feature workaround is quite scattered also. 

Let me think about it first.

**Comment by kwannoel** [comment]
> @kwannoel, Lets continue discussion here. From this [#4431 (comment)](https://github.com/risingwavelabs/risingwave/pull/4431#issuecomment-1327488801),
> 
> I think the probability of rejection are super high, Because it is like if you have nested subquery of k level, One level use correlated subquery with agg 'Select' or 'Having', then it gonna been rejected.
> 
> I also feel that currently the unsupported feature workaround is quite scattered also.
> 
> Let me think about it first.


Seems to be ok, I set threshold to be 20% with correlated subquery enabled:
https://github.com/risingwavelabs/risingwave/blob/461ae554c74a8bc2791211f14e41dffeac959e4b/src/tests/sqlsmith/src/runner.rs#L65

However, if there's better approach feel free to suggest.

**Comment by kwannoel** [comment]
Any updates? Probably just need to ignore this error: https://github.com/risingwavelabs/risingwave/issues/6605 and correlated subquery may be enabled.

**Comment by marvenlee2486** [comment]
Let's me try to enable it now.
