### ISSUE TITLE
optimizer: hop_window's predicate push-down

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#6606]

**Comment by kwannoel** [comment]
So far I'm doing:
- Pushdown everything except `window_start`, `window_end`.
- Rewrite `window_start` and `window_end` predicates to `t.ts`, if the other side of the cond expr is literal.
   e.g. `window_start >= '1997-07-02':Varchar::Date` becomes `t.ts >= '1997-07-02'.
- Insert `Filter` above `HopWindow` for other Conditionals with `window_start` and `window_end`.

Is there anything else I'm missing?

**Comment by xxchan** [comment]
Rewriting time window predicates sounds interesting. Why did you remove that? 🤔

**Comment by kwannoel** [comment]
> Rewriting time window predicates sounds interesting. Why did you remove that? Are there any problems? 🤔
Not sure if it is common use case, seems rather ad-hoc to do it just for literals. 
Was thinking of allowing some variables, but don't have a good idea of it yet.
So I decided to just keep it simple for now 😇 and see if there are other ideas which are more general than mine.

**Comment by xxchan** [comment]
Agree to KISS

**Comment by kwannoel** [comment]
Some more idea for extension: https://github.com/risingwavelabs/risingwave/issues/6929
