### ISSUE TITLE
bug: merge iterator panics when cancelling (dropping)

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#6637]
### Describe the bug

commit: 6b3177a53ee4c50cc7098051faada224c12e7f63

https://buildkite.com/risingwavelabs/main/builds/2356#0184bea5-1058-4d0f-9a9d-06e0329a391e

```
   5: core::option::Option<T>::expect
             at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/option.rs:741:21
   6: <risingwave_storage::hummock::iterator::merge_inner::MergeIteratorInner<I,NE> as risingwave_storage::hummock::iterator::HummockIterator>::key
             at ./src/storage/src/hummock/iterator/merge_inner.rs:300:9
```

**Comment by BugenZhao** [comment]
https://github.com/risingwavelabs/risingwave/blob/15030ea76be219a5a2bd64ad28527852ded1a724/src/storage/src/hummock/iterator/merge_inner.rs#L251-L268

The `PeekMut` here crosses the `await` point. If we cancel the iterator at this point, we'll get the iterator to be in an inconsistent state. This is similar to https://github.com/risingwavelabs/risingwave/pull/1099.

cc @wenym1

**Comment by wenym1** [comment]
The problem seems irrelevant to the peek_mut. It's caused by the current code of OrderedMergeIterator, which takes all the nodes with the same user key out, do async next, and then put the node back to the heap. If we put all the nodes out, and the future gets canceled, the heap will become empty, and fail to get the key of the top node, which causes this panics. cc @hzxa21 

I will fix this issue later.

**Comment by BugenZhao** [comment]
The panic occurred when dropping the `PeekMut`. 🤔
```
  13: <alloc::collections::binary_heap::PeekMut<T> as core::ops::drop::Drop>::drop
             at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/alloc/src/collections/binary_heap.rs:297:22
  14: core::ptr::drop_in_place<alloc::collections::binary_heap::PeekMut<risingwave_storage::hummock::iterator::merge_inner::Node<risingwave_storage::hummock::iterator::HummockIteratorUnion<risingwave_storage::hummock::iterator::Forward,risingwave_storage::hummock::iterator::merge_inner::MergeIteratorInner<risingwave_storage::hummock::iterator::HummockIteratorUnion<risingwave_storage::hummock::iterator::Forward,risingwave_storage::hummock::shared_buffer::shared_buffer_batch::SharedBufferBatchIterator<risingwave_storage::hummock::iterator::Forward>,risingwave_storage::hummock::sstable::forward_sstable_iterator::SstableIterator>,usize>,risingwave_storage::hummock::iterator::merge_inner::MergeIteratorInner<risingwave_storage::hummock::sstable::forward_sstable_iterator::SstableIterator,usize>,risingwave_storage::hummock::iterator::concat_inner::ConcatIteratorInner<risingwave_storage::hummock::sstable::forward_sstable_iterator::SstableIterator>>,()>>>
             at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/ptr/mod.rs:491:1
```

**Comment by wenym1** [comment]
> The panic occurred when dropping the PeekMut

When dropping the PeekMut, it will try getting the key of the top node. When the top node is also a merge iter, it will try to get the key from an empty heap, and panics.
