### ISSUE TITLE
drop materialized view command got stuck 

### ISSUE THREAD

**Issue by sushantgupta** [risingwavelabs/risingwave#6639]
### Describe the bug

After completion of the longevity test, we issued the drop materialized view command, which got stuck for more then 20 minutes and counting.
```
╰─> psql "postgres://dev:dev@rls-apse1-eks-a.risingwave-cloud.xyz:4566/dev?options=--tenant%3Drwc-3-longevity-20221128-044939"
dev=> \dm;
                List of relations
 Schema |    Name     |       Type        | Owner
--------+-------------+-------------------+-------
 public | nexmark_q1  | materialized view | dev
 public | nexmark_q10 | materialized view | dev
 public | nexmark_q14 | materialized view | dev
 public | nexmark_q2  | materialized view | dev
 public | nexmark_q3  | materialized view | dev
(5 rows)

dev=> drop materialized view nexmark_q1;

```

job link: https://buildkite.com/risingwave-test/longevity-test/builds/179

### To Reproduce

1) run the longevity build
2) After completion try to delete materialized view.

### Expected behavior

Drop materialized view should be completed in a few seconds.

### Additional context

you can use same setup for debugging.
psql "postgres://dev:dev@rls-apse1-eks-a.risingwave-cloud.xyz:4566/dev?options=--tenant%3Drwc-3-longevity-20221128-044939"

**Comment by zwang28** [comment]
IIUC @yezizp2012 

1. [compute node 0 crash](https://github.com/risingwavelabs/risingwave/issues/6642) 
2. The drop mv barrier failed. 
3. Recovery is triggered. It [aborts previous epochs](https://github.com/risingwavelabs/risingwave/blob/c2464afd9918fb0baa4f95c3477e9fcfa807ee00/src/meta/src/barrier/schedule.rs#L251). **However, `notify_collection_failed` only notifies `collected`, not `finished`.**
4. The drop mv barrier is infinitely [waiting on `finish_rx`](https://github.com/risingwavelabs/risingwave/blob/c2464afd9918fb0baa4f95c3477e9fcfa807ee00/src/meta/src/barrier/schedule.rs#L181), thus blocks drop mv command.

**Comment by yezizp2012** [comment]
> IIUC @yezizp2012
> 
> 1. [compute node 0 crash](https://github.com/risingwavelabs/risingwave/issues/6642)
> 2. The drop mv barrier failed.
> 3. Recovery is triggered. It [aborts previous epochs](https://github.com/risingwavelabs/risingwave/blob/c2464afd9918fb0baa4f95c3477e9fcfa807ee00/src/meta/src/barrier/schedule.rs#L251). However, `notify_collection_failed` only notifies `collected`, not `finished`.
> 4. ~The drop mv barrier is infinitely [waiting on `finish_rx`](https://github.com/risingwavelabs/risingwave/blob/c2464afd9918fb0baa4f95c3477e9fcfa807ee00/src/meta/src/barrier/schedule.rs#L181), thus blocks drop mv command.~
> 
> Update: Maybe I'm wrong with step4. Because [the notifier is eventually dropped](https://github.com/risingwavelabs/risingwave/blob/c2464afd9918fb0baa4f95c3477e9fcfa807ee00/src/meta/src/barrier/schedule.rs#L253), so [here should have received an error](https://github.com/risingwavelabs/risingwave/blob/c2464afd9918fb0baa4f95c3477e9fcfa807ee00/src/meta/src/barrier/schedule.rs#L181)? According to meta node log, I believe the drop mv barrier is stuck, because I don't find [log message related to barrier cancellation](https://github.com/risingwavelabs/risingwave/blob/c2464afd9918fb0baa4f95c3477e9fcfa807ee00/src/meta/src/barrier/schedule.rs#L178).

I guess recovery had already happened by the time the drop mv barrier arrived. The entire cluster has been recovering due to the loss of the CN node, so the drop mv barrier was always in the barrier queue waiting for handling after recovery.

**Comment by yezizp2012** [comment]
#4822 will go a long way towards exposing this. I will do it in this week.
