### ISSUE TITLE
Chore: Create a `risedev download-all` task

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#6656]
### Is your feature request related to a problem? Please describe.

We currently need to download all components separately. This is fine, but I think it would be nice to also have the option to just say `risedev install-all`. 

```
risedev --help
...
RiseDev - Components
----------
download-connector - Download RisingWave Connector
download-etcd - Download and extract Etcd
download-grafana - Download and extract Grafana
download-jaeger - Download and extract Jaeger
download-kafka - Download and extract Kafka
download-mcli - Download and extract MinIO Client
download-minio - Download and extract MinIO
download-prometheus - Download and extract Prometheus
download-pubsub - Download and enable Google Pubsub Emulator
download-redis - Download and extract Redis
```

**Comment by SaumyaBhushan** [comment]
Hi @CAJan93 ! Can you please tell me how can we do this ?

**Comment by xxchan** [comment]
`pre-start-dev` already included that. So I think it's not very necessary to have another `download-all`.

https://github.com/risingwavelabs/risingwave/blob/9b77e9a78e1209a87d845641a20b790e2e11ebc7/Makefile.toml#L356-L369

**Comment by CAJan93** [comment]
I was thinking about something like this https://github.com/risingwavelabs/risingwave/pull/6671 @SaumyaBhushan 

Thank you for pointing that out @xxchan. I agree the `download-all` thing is not super necessary. Do you still want to keep the suggestion? I integrated the `download-all` task in the `pre-start-dev` task, so we do not repeat ourselves.

**Comment by CAJan93** [comment]
Should we merge the suggested change or do we not need it? Just let me know :)
