### ISSUE TITLE
Change create index to include all columns by default

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#6657]
### Is your feature request related to a problem? Please describe.

Currently, we adopt the same semantic of `create index idx on table(column)` with PostgreSQL which means we will never include other columns of the table by default. However, *Risingwave* as a cloud native streaming database has so many differences with the classical PostgreSQL. We have object store which can make the storage space cheaper.  We want make index easier to use and don't want to let users specify which columns to include if they aren't experts on the database, because once index can't cover all the columns required by the query, it needs to do a primary table lookup and in the cloud environment usually means a network communication rather than another disk access of PostgreSQL. Creating an index to include all columns by default can make our index selection for index join easier and better performance. In the future, if we enable delta join again, this default behavior can benefit streaming query too. Last but not least, we can still provide `include` syntax for users to just include what column they want if they need. E.g. If users want to create an index just include the index columns without other columns, they can write the statement like `create index idx on table(column) include(column)`.

**Comment by lmatz** [comment]
how about also 'exclude'

**Comment by twocode** [comment]
> how about also 'exclude'

`exclude` is not postgres syntax 🤣

**Comment by BugenZhao** [comment]
> how about also `exclude`

This sounds a little bit hard. For example, if we add a column to the table, should we also include this column in the index? 😨
