### ISSUE TITLE
Tracking: `DynamicFilter` Cache improvements

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#6664]
Managed `RangeCache` (https://github.com/risingwavelabs/risingwave/issues/6540):
1. `RangeLRU` for providing an oracle assigning last-accessed times to subranges  (https://github.com/risingwavelabs/risingwave/pull/6666)
2. `ManagedRangeCache` that evicts ranges from the range cache based on watermark epoch and querying the `RangeLRU`

Misc:
1. Check consistency of requested `range`s from `RangeCache` - they should be continuous (issue: ?)

**Comment by fuyufjh** [comment]
The design is not so straight-forward to me. Can you please write an RFC on it?
