### ISSUE TITLE
feat(frontend): `DynamicFilter` with monotonic-increasing optimization, includes `now()` and `TemporalFilter`

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#6670]
Frontend will add a field to DynamicFilter plannode - `monotonic_increasing` and match the pattern that would result in it. Then, we may want to use this field to optimize the cache in the future.

**Comment by soundOfDestiny** [comment]
I don't think we can do so much optimization on it.
I think current cache strategy is ok.

**Comment by jon-chuang** [comment]
Actually, we can, we can use a prefetching method instead of requesting ranges eagerly.

Anw, this is an optimization with unproven use-case, so low-priority.

**Comment by soundOfDestiny** [comment]
close this issue because there will be no cache since #7076

**Comment by jon-chuang** [comment]
Actually, this cache design is orthogonal to `RangeCache`. We can revisit if there are performance reasons to do so.
