### ISSUE TITLE
feat: throttle source throughput to limit streaming latency

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#6682]
### Is your feature request related to a problem? Please describe.

As described in #6571, the barrier latency i.e. streaming end-to-end latency can increase infinitely when the system is under heavy load.

However, streaming latency is a critical metric for streaming computing, and it must be upper-bounded according to our SLA.

We need to build some negative feedback mechanisms to bound the latency.

### Describe the solution you'd like

Currently, we allow users to set the max number of in-flight barriers, but it only controls the injection of barriers. **We can enhance it by throttling the source events as well.**

> If the number of in-flight barriers reaches the upper bound i.e. 40, we may not only stop injecting barriers but also block the source executor to generate any new events. What do you guys think?
> 
> Referenced from https://github.com/risingwavelabs/risingwave/issues/6571#issuecomment-1331582075

One possible way to block new `DataChunk` events from being generated is using `Pause/Resume` barrier. Any other simpler solutions are welcomed.

### Describe alternatives you've considered

None

### Additional context

None

**Comment by fuyufjh** [comment]
@xxhZs Please take a look 🥺  cc. @hzxa21 @BugenZhao

**Comment by BugenZhao** [comment]
> One possible way to block new `DataChunk` events from being generated is using `Pause/Resume` barrier. Any other simpler solutions are welcomed.

Do you mean throttle the throughput by the meta service? That sounds like another reasonable idea.
FYI, @yezizp2012 added the mechanism on the compute node to pause the source in case of no barrier due to meta-service failure in https://github.com/risingwavelabs/risingwave/pull/6280. Simply making this more aggressive may also help.

**Comment by fuyufjh** [comment]
> Do you mean throttle the throughput by the meta service? 

Yes, when the number of in-flight barriers hits the limit.

**Comment by yezizp2012** [comment]
Originally I think it's quite dangerous to throttle the throughput using `Pause/Resume` by the meta service, what if meta exits after sending `Pause` barrier. But since meta will trigger a recovery process after restart, it's acceptable.

> Simply making this more aggressive may also help.
+1 for this.

**Comment by BugenZhao** [comment]
> I think it's quite dangerous to throttle the throughput using `Pause/Resume` by the meta service

Issuing `Pause` by the **meta service** LGTM, while it's indeed dangerous by compute node itself. 🤤

**Comment by tabVersion** [comment]
close due to realizing adjusting inflight barrier num is futile to control barrier latency, ref #6943 .
We adjust permits as a temporary fix

**Comment by BugenZhao** [comment]
Follow up: https://github.com/risingwavelabs/risingwave/pull/6943
