### ISSUE TITLE
bug: queries with arguments not handled correctly -- allows SQL Injections

### ISSUE THREAD

**Issue by ALeitert** [risingwavelabs/risingwave#6710]
Consider we create a table as follows `Create Table T1 (id int, txt varchar);`. We now want to insert entries into it. The usual way to do that (without risking SQL injections) is the use of parameters. In golang for example, that may look like this:

```golang
// Open connection to database.
conn, _ := sql.Open("postgres", url)

// Execute query with parameter.
conn.Exec(
	"Insert Into T1 Values (0, $1);", // Query
	"Rising'), (1, 'Wave'); --" // argument
)
```
`$1` is the placeholder for an argument. Running the code above with postgres creates one entry.
```
 id |            txt            
----+---------------------------
  0 | Rising'), (1, 'Wave'); --
```
Running the same query with RW results in two entries:
```
 id |  txt   
----+--------
  1 | Wave
  0 | Rising
```

**Comment by ALeitert** [comment]
Consider the table from above. The following still works:
```golang
res, err := conn.Exec(
	"Update t1 set txt = $1 Where id = $2;",
	"bad$2",
	" Where true; -- ",
)
```
It treats the `$2` in the second string as part of the query and replaces it.

Strangely, this only happens sometimes. If I print the query given to the parser into the log, the result is not always the same.

Personally, I would suggest that we let the parser recognise the `$`-placeholders and handle them afterwards instead of doing a text replacement before parsing.

**Comment by BowenXiao1999** [comment]
Yes. Let's do a simple text replacment first.

It seems like the most standard way is to get AST in parse stage, and fill in in Bind Stage. However IIRC the sqlparser can not support parsing `$`. We can check how Mz handle this. SQL Injections is a big problem and main contain any kinds of issues, so let's solve them step by step.
