### ISSUE TITLE
bug: regress test output column name, unnecessary spaces before output item, cast

### ISSUE THREAD

**Issue by curiosityyy** [risingwavelabs/risingwave#6720]
### Describe the bug

![image](https://user-images.githubusercontent.com/28347358/205478621-002e2f6d-1db5-426c-a020-3f00ccefef30.png)
For example, if we run `SELECT '32767.4'::float4::int2;`, the outputs:
pg:
```
 int2
-------
 32767
(1 row)
```

risingwave:
```
 ?column?
----------
    32767
(1 row)
```

### To Reproduce

![image](https://user-images.githubusercontent.com/28347358/205478642-2172bd3e-9ea0-4464-b930-a5dac0afb596.png)
Enable `line 98 - line 104`, `line 106` and `line 108`, run regress test by 
```
RUST_BACKTRACE=1 target/debug/risingwave_regress_test -h 127.0.0.1 \
  -p 4566 \
  -u root \
  --input `pwd`/src/tests/regress/data \
  --output `pwd`/src/tests/regress/output \
  --schedule `pwd`/src/tests/regress/data/schedule \
  --mode risingwave
```

### Expected behavior

The test pass with no error.

### Additional context

System Software Overview:

  System Version: macOS 12.3.1 (21E258)
  Kernel Version: Darwin 21.4.0
  Boot Volume: Macintosh HD
  Boot Mode: Normal

**Comment by xiangjinwu** [comment]
This could be solved by #3812 if we match output column name deriving rules from PostgreSQL. Alternatively:
* The test runner may be updated to ignore spaces when comparing results. This may lead to false negative for string columns.
* The test queries could be updated to use explicit output column aliases.

If you have other general solutions in mind, feel free to reopen this issue.
