### ISSUE TITLE
recovery: etcdserver request is too large

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#6726]
### Describe the bug

I encounter "etcdserver: request is too large" from `batch_update_table_fragments` , during cluster recovery.

### To Reproduce

1. Create all streaming tpch MVs.
2. Trigger actor migration during recovery. My approach is expiring the original CN and later adding a new CN.
3. Recovery cannot succeed. Inspect error from https://github.com/risingwavelabs/risingwave/blob/fe8599fe51e4e19661366cff718b6ac79da1c82f/src/meta/src/barrier/recovery.rs#L130 and find
`MetadataModel error: Meta store error: internal error: grpc request error: status: InvalidArgument, message: "etcdserver: request is too large", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }`

### Expected behavior

Recovery succeed.

### Additional context

The cause is clear: https://github.com/risingwavelabs/risingwave/blob/fe8599fe51e4e19661366cff718b6ac79da1c82f/src/meta/src/manager/catalog/fragment.rs#L133 results a too large etcd transaction, because of including many table fragments.

Should we enlarge etcd's max-request-bytes, or constrain our usage of large meta store transaction? As I suspect there can be more similar cases. @yezizp2012

**Comment by yezizp2012** [comment]
I think we can only enlarge etcd's `max-request-bytes` at least for now, especially for `batch_update_table_fragments`. 🥵 Actually during migration, almost all fragments will be affected with changes only on parallel units and vnode mapping. I tried to split these informations before but find it's a little bit hard and will brings more refactoring. Anyway, let's enlarge `max-request-bytes` for now, I will keep trying on some refactoring on it.

**Comment by zwang28** [comment]
>  especially for batch_update_table_fragments
Can update_table_fragments without batching? I think it won't hurt correctness.

**Comment by yezizp2012** [comment]
> > especially for batch_update_table_fragments
> 
> Can update_table_fragments without batching? I think it won't hurt correctness.

I'm afraid not in current implementation. If we only update some of the table fragments and then meta crashes, we might need some other mechanisms to determine which CNs are new joined since recovery. Currently we treat those CNs as new which doesn't have any actors.
But it's a good direction to take to solve this problem, I will give it a try. Besides, found another possible bug in the scene I described above: #6763 🥵
