### ISSUE TITLE
feat: introduce leader and standby status for meta

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#6752]
### Is your feature request related to a problem? Please describe.

when Meta starts, it should participate in leader election. We need a status `leader` or `follower` for meta:
1. leader: initializes all managers with memory cache, starts related RPC services and sub-tasks.
2. follower: keep participating in election, should only starts a etcd member PRC service only.

**Comment by CAJan93** [comment]
As discussed we I will try to implement the following features for this issue having the following limitations: 

**Features:**

- All nodes will participate in elections 
- Nodes know if they are leaders or followers 
- Nodes will display if they are leaders or followers in the logs 
- Followers start the health service 
- Leaders start all services 

**Limitations:** 

- Clients cannot handle meta failover 
- A meta follower will never start leader services once it becomes leader 
- No fencing mechanism 
- Followers do NOT respond to clients who the current leader is
