### ISSUE TITLE
Refactor: prevent OptimizerContext from being used across await points

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#6770]
### Is your feature request related to a problem? Please describe.

Currently `OptimizerContext` is used across await points which results in `Sync` and `Send` requirement. It is hard to add fields to it. We should restrict `OptimizerContext` lifecycle.

**Comment by BugenZhao** [comment]
Long ago we're able to put non-atomic `Rc` in the context, while something breaks it later. Glad to see this refactoring! 🚀

**Comment by chenzl25** [comment]
> Long ago we're able to put non-atomic `Rc` in the context, while something breaks it later. Glad to see this refactoring! 🚀

I do want to put `Rc` (or more specifically `PlanRef`) into the context during optimization.
