### ISSUE TITLE
testing: add e2e test cases for `Now` executor and `TemporalFilter` 

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#6790]

**Comment by jon-chuang** [comment]
With implementation in: https://github.com/risingwavelabs/risingwave/issues/6790 blocked on https://github.com/risingwavelabs/risingwave/issues/6813 (we need project to have correct behaviour for watermark)

**Comment by fuyufjh** [comment]
@soundOfDestiny Can it be closed now?

**Comment by soundOfDestiny** [comment]
will reopen when watermark framework finishes
