### ISSUE TITLE
chore: Mergify should replace squashed log messages with message from PR description

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#6791]
### Is your feature request related to a problem? Please describe.

Currently we get logs like this when merging with mergify. 

<img width="697" alt="image" src="https://user-images.githubusercontent.com/15103784/206186548-adf1cb1a-c089-4f36-aa72-0b461e2b5fb1.png">

In the PR description we could have a section called PR message and mergify could get that and use it. This way you can still set your custom message.

https://docs.mergify.com/configuration/#data-type-template

**Comment by CAJan93** [comment]
Thank you very much for the implementation @fuyufjh 👍 
Maybe we could introduce a section in the PR template called `## CommitMsg`? This way a user can manually define what the commit message will be. I believe the below config should get the `## CommitMsg` section and default to the title, if the section is not defined.

```
shared:
  - commit_message_template: &commit_message_template |
     
      {{body | get_section("## CommitMsg", {{title}}) }}
      
      {% for user in approved_reviews_by %}
      Approved-By: {{user}}
      {% endfor %}
```

**Comment by fuyufjh** [comment]
> Thank you very much for the implementation @fuyufjh 👍 
> 
> Maybe we could introduce a section in the PR template called `## CommitMsg`? This way a user can manually define what the commit message will be. I believe the below config should get the `## CommitMsg` section and default to the title, if the section is not defined.
> 
> 
> 
> ```
> 
> shared:
> 
>   - commit_message_template: &commit_message_template |
> 
>      
> 
>       {{body | get_section("## CommitMsg", {{title}}) }}
> 
>       
> 
>       {% for user in approved_reviews_by %}
> 
>       Approved-By: {{user}}
> 
>       {% endfor %}
> 
> ```

If you want to write commit message per PR manually, it's natively supported in Mergify: https://blog.mergify.com/using-templates-in-your-messages/

However I don't think other people will follow the guide 😂

**Comment by fuyufjh** [comment]
Wait, perhaps we can just pick the "what's changed" section.

**Comment by CAJan93** [comment]
> Wait, perhaps we can just pick the "what's changed" section.

That could work.
