### ISSUE TITLE
Can't tumble with timestamptz

### ISSUE THREAD

**Issue by malthe** [risingwavelabs/risingwave#6793]
### Describe the bug

We're trying to `TUMBLE(table, '2022-07-12 14:00:00+00:00'::timestamptz, INTERVAL '2 MINUTES')` and the system is complaining that the tumble function takes a 2nd argument of type timestamp, timestamp with time zone or date.

But it _is_ getting a timestamp with time zone!

**Comment by lmatz** [comment]
Thanks for the report, maybe related: #6641

**Comment by malthe** [comment]
Closing as duplicate.
