### ISSUE TITLE
config: Use only one set of default values for risingwave.toml

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#6803]
Currently we have `config/risingwave.toml` (used by risedev -> used by ci) and default value defined in code. They did intentionally have some different values, e.g., https://github.com/risingwavelabs/risingwave/pull/6553. The reason is that we want to use different defaults for ci/dev & cloud.

https://github.com/risingwavelabs/risingwave/blob/533b9a966873ee06a754ca42a882e54e425845f3/src/config/README.md#L11-L15

This may be confusing and cause `risedev` need to merge `config-path` with the base one, which is a little bit hacky.

If we can only keep one set of defaults, things can be more straightforward. But I'm not sure how to decide the values.

**Comment by BugenZhao** [comment]
How about only keeping the default values in the code(binary) and merging all customized config during the runtime? 🤔

**Comment by fuyufjh** [comment]
> How about only keeping the default values in the code(binary) and merging all customized config during the runtime? 🤔
> 
> https://xuanwo.io/reports/2022-16/ https://github.com/Xuanwo/serfig

Agree. 

In theory, we should even delete the `risingwave.toml` because it's a duplication of the defaults in `RwConfig`. But I still kept it in #6814 because it's a handy example 🤣
