### ISSUE TITLE
dashboard: missing sink executor

### ISSUE THREAD

**Issue by yuhao-su** [risingwavelabs/risingwave#6824]
### Describe the bug

The sink executor will not show on our dashboard v2 (unless we `search` the exact fragment number).

The reason is the dashboard is listing the fragments based on `Table`, but the a sink executor will not be present in the `TableCatalog` (while others like mv/table/internaltable will)

### To Reproduce

Create a table
create a sink on that table
check the dashboard.

### Expected behavior

Make the sink executor visible without the need of searching the exact fragment id.

**Comment by tabVersion** [comment]
sink does not register to TableCatalog so you won't see it there. PTAL @yezizp2012 will we change the impl in meta?

**Comment by yezizp2012** [comment]
> sink does not register to TableCatalog so you won't see it there. PTAL @yezizp2012 will we change the impl in meta?

Sink is stored in a separated catalog but the streaming graphs are stored as same as mviews. I think we can list table fragments on all tables and sinks in dashboard.
