### ISSUE TITLE
compiler bug(?): daily release build takes 2 hours

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#6835]
https://buildkite.com/risingwavelabs/docker/builds/13182#0184ed58-e171-4d20-bc20-55d47cf2ce91
![SCR-20221210-54](https://user-images.githubusercontent.com/5791930/206743491-f002c528-a3fe-46c4-85a2-3111cabd5d63.png)

Normal on my laptop.

**Comment by xxchan** [comment]
https://github.com/risingwavelabs/risingwave/pull/6159
