### ISSUE TITLE
indeterministic result from ch benchmark batch query q4

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#6875]
### Describe the bug

https://github.com/risingwavelabs/risingwave/pull/6870/files#diff-593e17818d6f00077cffc0d8169d72cae0a4ad04a58ef6d3dfb65fdacd9d55e1

Execution of batch query q4 produces
![SCR-20221213-1o4](https://user-images.githubusercontent.com/5791930/207109645-838a2f1a-b267-4ee6-b754-89fd069086ac.png)
![SCR-20221213-1o9](https://user-images.githubusercontent.com/5791930/207109651-95e7d8ea-12d8-4ce0-921a-86f5e757a611.png)
![SCR-20221213-1od](https://user-images.githubusercontent.com/5791930/207109658-e5e7800c-e5d1-4b3b-9a34-59fe91339b2b.png)

There are even more random results... Just show 3 examples.

The expected results are gathered from streaming mv queries.
No matter streaming mv queries are correct or not, batch q4 should not produce different result everytime

plan:
```
 BatchSortAgg { group_key: [orders.o_ol_cnt], aggs: [count] }
 └─BatchSort { order: [orders.o_ol_cnt ASC] }
   └─BatchHashJoin { type: LeftSemi, predicate: orders.o_id = orderline.ol_o_id AND orders.o_w_id = orderline.ol_w_id AND orders.o_d_id = orderline.ol_d_id AND (orderline.ol_delivery_d >= orders.o_entry_d) }
     ├─BatchExchange { order: [], dist: Single }
     | └─BatchFilter { predicate: (orders.o_entry_d >= '2007-01-02 00:00:00.000000':Varchar) AND (orders.o_entry_d < '2199-01-02 00:00:00.000000':Varchar) }
     |   └─BatchScan { table: orders, columns: [o_id, o_d_id, o_w_id, o_entry_d, o_ol_cnt] }
     └─BatchExchange { order: [], dist: Single }
       └─BatchProject { exprs: [orderline.ol_o_id, orderline.ol_w_id, orderline.ol_d_id, orderline.ol_delivery_d] }
         └─BatchScan { table: orderline, columns: [ol_o_id, ol_d_id, ol_w_id, ol_delivery_d] }
(9 rows)
```

Pure guess: probably `left semi join`?

### To Reproduce

Sql to reproduce locally:
https://gist.github.com/kwannoel/7fde2fe122e9e71c2170033c7850ce0b

**Comment by st1page** [comment]
I am not sure if the `sortAgg`'s implementation is right, it is might not well be tested. Maybe I can add a flag `batch_enable_sort_agg` so that we can check if it is because of `sortAgg` quickly

**Comment by kwannoel** [comment]
> I am not sure if the `sortAgg`'s implementation is right, it is might not well be tested. Maybe I can add a flag `batch_enable_sort_agg` so that we can check if it is because of `sortAgg` quickly

Just some updates:
1. So far local testing shows it is not `sortAgg`, we still get indeterministic results either way.
2. Input to `BatchSort` from `BatchHashJoin` shows that output is indeterministic, so it's possible that the issue is with `BatchHashJoin` or downstream operators.

Will continue to update as I investigate.

**Comment by lmatz** [comment]
We can detect which operator is wrong if we have #688, but it has too much to do, and rarely encounter bugs of this type.

**Comment by kwannoel** [comment]
It does seem to be HashJoin (`LeftSemi`) particularly `non_equi_join`. Some relevant details on why this is the case:
q1 (original with bugs):
```sql
select	o_ol_cnt, count(*) as order_count
from orders
where o_entry_d >= '2007-01-02 00:00:00.000000'
  and o_entry_d < '2199-01-02 00:00:00.000000'
  and exists (select *
              from orderline
              where o_id = ol_o_id
                and o_w_id = ol_w_id
                and o_d_id = ol_d_id
                and ol_delivery_d >= o_entry_d)
group by o_ol_cnt
order by o_ol_cnt;
```

q1 Result:
```
 o_ol_cnt | order_count
----------+-------------
        1 |           1
        3 |           2
        4 |           1
        5 |           1
        6 |           1
        7 |           1
        8 |         399
        9 |           1
```

q2:
```sql
explain select	o_ol_cnt, count(*) as order_count
from orders
where o_entry_d >= '2007-01-02 00:00:00.000000'
  and o_entry_d < '2199-01-02 00:00:00.000000'
  and exists (select *
              from orderline
              where o_id = ol_o_id
                and o_w_id = ol_w_id
                and o_d_id = ol_d_id)
group by o_ol_cnt
order by o_ol_cnt;
``` 

q1 results:
```
 o_ol_cnt | order_count
----------+-------------
        1 |           1
        3 |           2
        4 |           1
        5 |           1
        6 |           1
        7 |           1
        8 |         274
        9 |           1
```

Notice that `ol_delivery_d >= o_entry_d` is removed. Loosening of a constraint should mean that more rows satisfy the exists predicate. Independently I have used inputs to verify this should be the result as well.

So it seems it may be an issue with non_equi part of evaluating `LeftSemi`, since that evaluates `ol_delivery_d >= o_entry_d`?

**Comment by kwannoel** [comment]
Further details:
- The number of probe side rows is correct.
- But the output rows from `process_left_semi_anti_join_non_equi_condition` has mismatch.

Looking at its logic, don't understand it yet.
