### ISSUE TITLE
Tracking: integrate with DBeaver

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#6878]
[DBeaver](https://github.com/dbeaver/dbeaver) is a widely-used database management tool, especially for JDBC-compatible databases. After #6837, we have supported the basic integration with DBeaver via native Postgres driver. Currently, we can perform DDL/DML/DQL using the DBeaver's SQL editor and view schema/database/table/MV. There are still yet-to-support features including:
- [x] #6879
- [x] #6880
- [x] #6881
- [x] #6882
- [x] #7915
- [x] #7925

**Comment by fuyufjh** [comment]
Moved to next release

**Comment by hzxa21** [comment]
I will close the issue since all works are done. Users are now able to connect to RisingWave via the standard PG connector in DBeaver.
