### ISSUE TITLE
Discussion: support canceling a query with `pg_terminate_backend/pg_cancel_backend`

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#6891]
In Postgres, a backend process is spawned for each client session and it provides a way to cancel the current query of a given backend using `pg_cancel_backend(pid)` and terminiate the backend process using `pg_terminate_backend(pid)`. The `pid` associated with a session can be retrieved from `pg_backend_pid()`.

Given that we already support using ctrl-c to cancel a batch query in #5027, I think we should also support `pg_terminate_backend/pg_cancel_backend` to be more compatible with PG. AFAIK, Supserset relies on it to cancel a running query in its SQL Lab (https://github.com/apache/superset/blob/5b67e0712d5d3c738abf3281e67755af741c5c01/superset/db_engine_specs/postgres.py#L316).

Disucssion:
1. Should we support `pg_terminate_backend/pg_cancel_backend` for batch query?
2. Should we support `pg_terminate_backend/pg_cancel_backend` for mv creation?

For 1), given that we already support using ctrl-c to cancel a batch query in #5027, I think we should also support `pg_terminate_backend/pg_cancel_backend` to be more compatible with PG. AFAIK, Supserset relies on it to cancel a running query in its SQL Lab.

For 2), I am not sure. Seems not so obvious to me so maybe no.

**Comment by hzxa21** [comment]
Example in Superset: https://github.com/apache/superset/blob/5b67e0712d5d3c738abf3281e67755af741c5c01/superset/db_engine_specs/postgres.py#L326

**Comment by fuyufjh** [comment]
> Disucssion:
>
> - Should we support pg_terminate_backend/pg_cancel_backend for batch query?
> - Should we support pg_terminate_backend/pg_cancel_backend for mv creation?

For this question, I think "yes" for both. Cancellation of MV creation is definitely a very useful function and I have discussed it with @yezizp2012 before. Not sure whether it's being worked on.

**Comment by BowenXiao1999** [comment]
Yes, the difficulty is to make it work elegantly. Some naive thoughts (w/o deep dive the code):
* Cancel is executed in Frontend, if we want to exeute it like other expressions, it must be planned as a LocalExecution in planner. I'm afraid this may break our uniform tradition for expression and make it hacky.
* Or we just hack the handler and direct execute the cancel without touching scheduler stuff. But this will become super hack... 
* Or in UDF/external function, do not investigate yet.

**Comment by yezizp2012** [comment]
Not planned, will implement as describe in #8032 .
