### ISSUE TITLE
Support to_timestamp(text, text)

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#6894]
Superset requires `to_timestamp(text, text)` to convert date time format when using time range filter, which is commonly used to generate time based charts.

See https://www.postgresql.org/docs/current/functions-formatting.html
```
to_timestamp ( text, text ) → timestamp with time zone

    Converts string to time stamp according to the given format. (See also to_timestamp(double precision) in Table 9.33.)

    to_timestamp('05 Dec 2000', 'DD Mon YYYY') → 2000-12-05 00:00:00-05
```

**Comment by fuyufjh** [comment]
@TennyZhuang Please take a look as it's marked as "high-priority"
