### ISSUE TITLE
Discussion: give a warning that links to the doc page when users do `Materialized View with ORDER BY`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#6911]
I feel we probably need to give a warning that links to the doc page when users do `Materialized View with ORDER BY`

_Originally posted by @lmatz in https://github.com/risingwavelabs/risingwave/issues/6905#issuecomment-1352519800_

**Comment by hzxa21** [comment]
+1

**Comment by kwannoel** [comment]
Some other idea: 
Is it common usecase to do `CREATE MATERIALIZED VIEW ... ORDER BY`?
If it is rare, perhaps it is easier to just disable `ORDER BY` when no `LIMIT` clause is present?

**Comment by BugenZhao** [comment]
> Is it common usecase to do `CREATE MATERIALIZED VIEW ... ORDER BY`?

Even though there seem to be no effects in our system, it indicates what the key in the storage will be (the "order key"). So later range scan with (a subset of) the order key, or sort the records again in the batch query will lead to better performance. 🤔

**Comment by lmatz** [comment]
I will just explain in my own words instead of linking to the Oracle's doc.
Heard Oracle has a very good legal team.
