### ISSUE TITLE
longevity panic: `unwrap()` in `source_executor.rs`

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#6931]
### Describe the bug

```
thread 'risingwave-streaming-actor' panicked at 'called `Option::unwrap()` on a `None` value', /risingwave/src/stream/src/executor/source/source_executor.rs:258:14
```

https://github.com/risingwavelabs/risingwave/blob/66df2f77a63458e78b0e7d6b2be1e3e69f0f5a0f/src/stream/src/executor/source/source_executor.rs#L258

Full logs:

https://rqa-logs.s3.ap-southeast-1.amazonaws.com/longevity/222_logs.txt

OR

https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logsV2:log-groups/log-group/$252Frisingwave$252Frls-apse1-eks-a$252Frwc-3-longevity-20221214-180848/log-events/ip-10-0-74-173.ap-southeast-1.compute.internal-risingwave.var.log.containers.risingwave-compute-1_rwc-3-longevity-20221214-180848_compute-5a7b1ee2a90c3f8ddf2cfea2c1993d7918d26f1aa3d199281c26bb3d4017855e.log$3FfilterPattern$3D

### To Reproduce

N/A

**Comment by fuyufjh** [comment]
Hi! Any updates? Please don’t mind to share some discoveries or handling it to someone else.

**Comment by shanicky** [comment]
#7086 just replaced the panic into the error returned to the upper layer, in fact, if there is a problem the upper layer will still panic, this issue also needs to continue to investigate, the main problem is that there is no very effective way to reproduce the scene

**Comment by fuyufjh** [comment]
Any updates?

**Comment by shanicky** [comment]
The problem has not recurred since then, so it seems that it can be closed now.
