### ISSUE TITLE
feat: Failover meta node from follower to leader

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#6936]
**Features:**
- Meta node starts follower service if it is a follower 
- Meta node starts leader services if it is a leader 
- Meta node initialises leader services only after it becomes a leader 
- Failover from follower to leader if follower dies
- unittests check if follower becomes leader on failover

**Limitations:**
- No failover from leader to follower (see [fencing](https://github.com/risingwavelabs/risingwave/issues/6786))
- Meta clients are not aware that there may be an HA 
- No [fencing](https://github.com/risingwavelabs/risingwave/issues/6786) 
- No service discovery

**Related:**

- https://github.com/risingwavelabs/risingwave/issues/6534

**Comment by yezizp2012** [comment]
And this's just a bug under your development of HA in meta. Let's record it in one of the subtasks tracked in #6936 , maybe #6936 ? Since it's not a bug in the main branch and very misleading, I will close it.

> > When we initialise the hummock manager only after the node became a leader, we will still get an error, however a slightly different one: (see [logs/stack trace](https://github.com/risingwavelabs/risingwave/files/10244557/meta-node-25690.log))
> > CC @yezizp2012
> 
> This is still related to stored results generated by the selection in the meta store. Please **ENSURE** that the leader information in MetaSrvEnv is correctly updated when follower get elected. I guess this is the main cause. 😃

**Comment by CAJan93** [comment]
> This is still related to stored results generated by the selection in the meta store. Please **ENSURE** that the leader information in MetaSrvEnv is correctly updated when follower get elected. I guess this is the main cause. 😃

Done. See https://github.com/risingwavelabs/risingwave/pull/6937/commits/30b8e4a855d60f257d612c5934255cd6ecf04b5d

**Comment by CAJan93** [comment]
The implementation is ready for review: https://github.com/risingwavelabs/risingwave/pull/6937 
- Last pipeline run looks green and failover runs as expected
- When testing this PR, please be aware that we do NOT have a working HA setup, since the meta clients can only handle a single meta node as of right now

**Comment by CAJan93** [comment]
Quick reminder that this issue and its implementation does NOT include any fencing. Fencing will be introduced in https://github.com/risingwavelabs/risingwave/issues/6786. This means that you can do failover from leader to follower by deleting the leader/lease info in ETCD. To delete the leader info, run 

```bash 
etcdctl --endpoints=127.0.0.1:2388,127.0.0.1:12388,127.0.0.1:22388 del --prefix=true cf/meta 
```

Blow you can see the logs of a meta node, which went from follower, to leader and back to follower. Highlighted text indicate node status changes

<img width="885" alt="Screenshot 2022-12-22 at 14 39 47" src="https://user-images.githubusercontent.com/15103784/209146427-4bd8a091-ef5a-45ba-a8c1-9c54b5a2d699.png">

**Comment by CAJan93** [comment]
PR is merged
