### ISSUE TITLE
bug(streaming): memory leaks in HashJoinExecutor

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#6942]
### Describe the bug

The memory usage went up gradually even if the memory limit was set to a very small number.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/10192522/208231418-8b1c7b9c-d844-43f4-9f3d-9b0fcf3db931.png">

I did some heap profiling and found the cause:

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/10192522/208231405-4b4dcd2a-101c-481d-80dc-4546b861ac68.png">

See "Additional context" section for full picture.

### To Reproduce

Run NexMark Q4 for a long time (> 1 hour)

### Additional context

```
-rw-r--r-- 1 ubuntu ubuntu 135K Dec 17 05:12 compute-node.26252.220.i220.heap
-rw-r--r-- 1 ubuntu ubuntu 144K Dec 17 07:29 compute-node.26252.2420.i2420.heap
```

- Heap captured after running for ~10min: ~~[flamegraph_220](https://user-images.githubusercontent.com/10192522/208231493-a4d48183-49d5-4b41-8d19-4fa42bb951b1.svg)~~
- Heap captured after running for ~2h30min:  ~~[flamegraph_2420](https://user-images.githubusercontent.com/10192522/208231489-16c41e41-e333-47db-970f-c3dd05d9f6b6.svg)~~

Download here: [flamegraph.zip](https://github.com/risingwavelabs/risingwave/files/10306247/flamegraph.zip)

**Comment by yuhao-su** [comment]
I can't reproduce the memory leak in hash join for now. But I noticed another unusual memory increasing in our system.
![image](https://user-images.githubusercontent.com/31772373/209106242-45fc5345-e59c-49ab-acf6-c859b4cf4f4e.png)
![image](https://user-images.githubusercontent.com/31772373/209106288-d71fd21f-25d6-487a-be50-ee8ca013a789.png)
The above figures shows the jemalloc allocated memory is increasing but the block size size is limited to 256M.
The following figure shows the most memory is taken by a generated sst data (which is extremely unusual)
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/31772373/209107098-e88752ee-82df-42a7-89eb-f40239a38ac7.png">

**Comment by fuyufjh** [comment]
😅 GitHub 'compressed' the SVG even I uploaded as files...

Sorry for that, please check this: [flamegraph.zip](https://github.com/risingwavelabs/risingwave/files/10306247/flamegraph.zip)

**Comment by fuyufjh** [comment]
The problem may be here: https://github.com/risingwavelabs/risingwave/blob/064ff7cb99febd9221357445352c75c50ecdcc63/src/stream/src/executor/managed_state/join/join_entry_state.rs#L51

While the `new_in` use `ManuallyDrop` inside...

https://doc.rust-lang.org/src/alloc/collections/btree/map.rs.html#634

**Comment by fuyufjh** [comment]
Even though #7089 worked, the https://github.com/risingwavelabs/risingwave/issues/6942#issuecomment-1365784996 above may be wrong because the allocator is dropped in `BTreeMap::drop()`, more precisely, in the `IntoIterator`'s `drop()`: https://doc.rust-lang.org/src/alloc/collections/btree/map.rs.html#406

So the cause still has yet to be investigated 😇

**Comment by fuyufjh** [comment]
The bug is inside the `BTreeMap`. Reported to Rust: https://github.com/rust-lang/rust/issues/106203

For now, I will just remove that part of code because we don't rely on Allocator API to get memory usage now.
