### ISSUE TITLE
sqlsmith: generate IMPLICIT CAST in function arguments

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#6945]
Enable implicit cast conservatively to avoid wrong type inference.

## Examples

1. Generated in explicit cast:
   Suppose we generate implicit cast from `smallint -> int`, where `int` is the expected type of the expression.
   We can end up with:
   ```
    CAST(1::smallint AS BOOLEAN)
   ```
3. Generated in function / Agg Call:
   We attempt to generate an argument to `min` of type `int`, and end up with `1::smallint`, since that can be implicit cast to `int`.
   We end up with:
   ```
   min(1::smallint)
   ```
   The type of the expression is wrong.
6. Generated in SELECT CTE:
   Column type can be wrong.

## Background

see this for context: https://github.com/risingwavelabs/risingwave/pull/6939

## Solution

Just generate for functions with fixed return type. For instance, CONCAT, CONCAT_WS.

- [ ] Generate for all locations with `enforce_bool_clause`.

Feel free to suggest other alternatives.

**Comment by fuyufjh** [comment]
Hi, any progress?

**Comment by kwannoel** [comment]
> Hi, any progress?

Nope, but will probably work on it this week. Didn't prioritize it because previously it didn't really catch any bugs.
