### ISSUE TITLE
nested window table function

### ISSUE THREAD

**Issue by yuhao-su** [risingwavelabs/risingwave#6951]
Currently the first argument of Window table function is a `table` but not complex structure (subquery, join, another table function).

We should a least support table function as the first argument.

This is needed when implement watermark TVF.
```
SELECT customer_id, window_end as order_hour, SUM(price) as sum_price
FROM TUMBLE(
  WATERMARK(orders, order_time, order_time - INTERVAL '1' MINUTE), 
  order_time, 
  INTERVAL '1' HOUR)
GROUP BY window_end, customer_id;
```

**Comment by xiangjinwu** [comment]
#3189

btw it seems watermark is not the same as WindowTableFunction in binder, but they are syntactically the same in parser.

**Comment by xxchan** [comment]
According to https://github.com/risingwavelabs/rfcs/pull/30, I think we will define watermark on source, instead of WTF? 🤔
