### ISSUE TITLE
mysql end-to-end source test: port is already allocated

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#6953]
### Is your feature request related to a problem? Please describe.

How often should we expect `port is already allocated` error?

Right now, we (re)-try three times in total. 
But if it fails, sort of waste as the end-to-end source test is one of the last ones in the test pipeline, which fails the entire pipeline at the very last.

If it fails very often, then it wastes a lot(time particularly).

### Describe the solution you'd like

Options:
1. retry a lot
2. random the port number in `scripts`/in `e2e_test/source` SQL files.

### Additional context

![SCR-20221219-l47](https://user-images.githubusercontent.com/5791930/208369586-6088a267-1f06-4eb5-801e-a5a09e9d676e.png)

**Comment by lmatz** [comment]
As discussed with @tabVersion , probably because the environment that triggers timeout is not cleaned immediately, thus a re-try leads to a `port is already allocation` error, let's see

**Comment by lmatz** [comment]
Happen in sink test: https://buildkite.com/risingwavelabs/main/builds/2571#018533ce-ea2d-48c3-b584-d4fcb874afa4
seems this time without `timeout`

**Comment by lmatz** [comment]
Happen in regress test: https://buildkite.com/risingwavelabs/pull-request/builds/14403#01853921-89e1-4cdd-827c-7b037e77f1a1
![SCR-20221222-oly](https://user-images.githubusercontent.com/5791930/209105848-470923e7-843f-4a76-9245-8ed7a9d26be3.png)

**Comment by xxchan** [comment]
Obviously my trivial attempt doesn't work https://buildkite.com/risingwavelabs/main/builds/2594#01853a6f-0745-48ba-97a4-3f242f9e3d28 😄

**Comment by huangjw806** [comment]
It feels like a issue with docker-compose itself, which was also mentioned [here](https://github.com/docker/compose/issues/9117), but it has not been resolved.

Let's try some of the methods mentioned https://github.com/docker/compose/issues/4950.

**Comment by lmatz** [comment]
Let's wait for several weeks, if it does not happen again, we close this issue.

**Comment by lmatz** [comment]
not happening again, close it now.
