### ISSUE TITLE
Three minutes recovery

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#6954]
Slack Notifcation URL:
https://risingwave-labs.slack.com/archives/C048NM5LNKX/p1671257505140079

![SCR-20221218-pj2](https://user-images.githubusercontent.com/5791930/208370688-a6386f07-b7ac-4039-99e3-7407a8cb3b3d.png)
![SCR-20221218-pja](https://user-images.githubusercontent.com/5791930/208370700-86d4ee45-9f24-4c24-a9d7-75728f721f33.png)

Question:
is it expected to take 3ish minutes to recover?

**Comment by fuyufjh** [comment]
Hopefully closed by #7082
