### ISSUE TITLE
validate compatibility between connector type and row format

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#6984]
For example:
```
create materialized source s1 (
    v1 int, 
    v2 float,
    primary key (v1)
) with (
    connector = 'datagen',
    fields.v1.kind = 'sequence',
    fields.v1.start = '1',
    fields.v1.end  = '10',
    fields.v2.kind = 'sequence',
    fields.v2.start = '11',
    fields.v2.end = '20',
    datagen.rows.per.second='15',
    datagen.split.num = '1'
) row format debezium_json;
```

The `create source` succeeds but warning for every row in the log.

Probably validating as early as possible is better?
Or the current approach is intentional?

It's a two-dimensional matrix, isn't it? 
connector type X row format type.

**Comment by fuyufjh** [comment]
related https://github.com/risingwavelabs/risingwave/issues/6948

**Comment by tabVersion** [comment]
datagen connector, after #7032 , will directly produce datachunks and ignore the row format properties.

**Comment by tabVersion** [comment]
#7612 introduces `native` as datagen's default row format. But we still accept `row format json` for test use.
We will ban other row formats from creating source with datagen connector.
