### ISSUE TITLE
Discussion: let users help to optimize the streaming queries

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7014]
If I remember correctly, we once reach the conclusion that a cost-based optimizer(CBO) is unnecessary in the near future:
1. we want to do point-select batch queries that can hit the index and finish within single/double-digits milliseconds instead of complicated ones that may run for seconds, minutes, or even hours.
2. we don't have all kinds of statistics of an input stream in advance while good statistics are needed for a CBO to work well.
3. implementing a CBO/cost model, especially because we expect CBO to work better (otherwise no point in implementing a CBO), takes a lot of effort which may not be justified.

Thus, as mentioned by many team members before, we can ask the user to help optimize the SQL plan(streaming queries as the batch ones are simple ones) because the user may have domain knowledge, e.g. which two streams among X streams should join first to produce less intermediate results.

From the perspective of user experience, to incorporate the insights from users, we can either:
1. let users express what they want in SQL or hints. For example, respecting the [explicit join order](https://www.postgresql.org/docs/current/explicit-joins.html) in the query(if any) or/and accepting [join order hints](https://oracle.readthedocs.io/en/latest/sql/hints/types/join-order.html)from users. But sometimes, `Join` is not explicit due in correlated subquery.

2. produce several plans for users to choose from. For example, suppose RW Cloud offers a nice web console, once `create materialized view` is entered, then the console shows a reasonable number of logical(?physical) plans for users to consider. Even fancier, e.g. let users enter the selectivity for several operators and produce a cost for each plan, this is probably acceptable as streaming queries are long-running and it's hard to change the plan later without running from the beginning again.

**Comment by chenzl25** [comment]
One way to display multiple physical plans for users to consider, I think we can expose some optimization session variables for the web console to turn it on or off to control the optimizer to generate different plans for users. We can provide some high level but hard to decide without statistics variables like: two-phase agg, delta join, join ordering(Left Deep or Bushy), join algorithm (if we have multiple join algorithms).

**Comment by lmatz** [comment]
> One way to display multiple physical plans for users to consider, I think we can expose some optimization session variables for the web console to turn it on or off to control the optimizer to generate different plans for users. We can provide some high level but hard to decide without statistics variables like: two-phase agg, delta join, join ordering(Left Deep or Bushy), join algorithm (if we have multiple join algorithms).

I am thinking if we need to make it more user-friendly once we have a console, although the underlying mechanism can still be:
`use a combination of different optimization session variables to generate multiple physical plans`.

Meaning that after the generation of multiple plans, plans are serialized and sent to the web console to display.
Then, after the user chooses one, the decision/plan is sent back to RW to continue processing.

Probably, this implies that RW needs to accept the physical plan as the user input in addition to SQL, although it is not exposed to other clients except our own RW Cloud console.

**Comment by chenzl25** [comment]
> > One way to display multiple physical plans for users to consider, I think we can expose some optimization session variables for the web console to turn it on or off to control the optimizer to generate different plans for users. We can provide some high level but hard to decide without statistics variables like: two-phase agg, delta join, join ordering(Left Deep or Bushy), join algorithm (if we have multiple join algorithms).
> 
> I am thinking if we need to make it more user-friendly once we have a console, although the underlying mechanism can still be: `use a combination of different optimization session variables to generate multiple physical plans`.
> 
> Meaning that after the generation of multiple plans, plans are serialized and sent to the web console to display. Then, after the user chooses one, the decision/plan is sent back to RW to continue processing.
> 
> Probably, this implies that RW needs to accept the physical plan as the user input in addition to SQL, although it is not exposed to other clients except our own RW Cloud console.

I think each physical plan can be definitely determined by the sql and the combination of the session variables together, so we don't need to accept a physical plan but the sql and the combination of the session variables.

**Comment by lmatz** [comment]
> I think each physical plan can be definitely determined by the sql and the combination of the session variables together, so we don't need to accept a physical plan but the sql and the combination of the session variables.

Make sense!

**Comment by kwannoel** [comment]
From reading discussion above and #5490, I think there is a consensus on the design, so here's my thoughts on implementing it.

I think we can have both session variables and hints since both have their usecases as mentioned by @chenzl25 https://github.com/risingwavelabs/risingwave/issues/5490#issuecomment-1367183336:
1. First, as suggested by @chenzl25: implement various optimization session variables, these are simpler implement, useful for web console, and our users can have access to these first for tuning their queries.
2. Next, as suggested by @fuyufjh in #5490: support more fine-grained hints, similar to: https://github.com/ossc-db/pg_hint_plan.
3.  Further, maybe 1. can be syntactic sugar for 2 eventually. Or internally uses functionality of 2.

Don't foresee any conflicts between 1 & 2 for now.

I shall open a tracking issue for 1. first.

**Comment by fuyufjh** [comment]
FYI. Flink's query hint

https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/sql/queries/hints/#broadcast

**Comment by fuyufjh** [comment]
See https://github.com/risingwavelabs/risingwave/issues/7491
