### ISSUE TITLE
proposal: normalize connector `WITH` properties in protobuf

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#7034]
When creating sources and sinks, we specify properties in the `WITH` clause which is parsed into a `map<string, string>`. However, we keep this type-unsafe representation in the catalog and compute node, this can be bad in some ways:

- In RPC, we cannot tell which component is responsible for validating some fields. So #7028 could happen.
- In persisted catalog, it'll be extremely hard to handle the compatibility for possible API changes. We can only resolve this by the property name, which is not robust as we're even not rejecting unrecognized fields yet.

So here I propose normalizing the connector properties in the protobuf. For those static properties, we can directly persist them in a field. For dynamic properties (like `fields.v.kind` in the data-gen connector), we can structure them in other ways.

```protobuf
message ConnectorProperties {
  oneof value {
    Kafka kafka = 1;
    Nexmark nexmark = 2;
    Datagen datagen = 3;
    Pubsub pubsub = 4;
  }
}

message Datagen {
  enum Kind {
    SEQUENCE = 1;
    RANDOM = 2;
  }
  message Field {
    Kind kind = 1;
    string start = 2;
    string end = 3;
  }

  uint32 split_num = 1;
  uint32 row_per_sec = 2;
  map<string, Field> fields = 3;
}
```

**Comment by tabVersion** [comment]
Just make sure, the proposal does not involve any user-facing change. The frontend is responsible for encoding the properties into bytes and meta and CN decodes it whenever needed.

**Comment by BugenZhao** [comment]
> Just make sure, the proposal does not involve any user-facing change. The frontend is responsible for encoding the properties into bytes and meta and CN decodes it whenever needed.

Yes. It's only related to the internal implementation to make this more type-safe.

**Comment by StrikeW** [comment]
With this refactor, it is still possible to pass through debezium properties via WITH clause for CDC connector? For example, here we set a different value for [decimal.handling.mode](https://debezium.io/documentation/reference/1.6/connectors/mysql.html#mysql-property-decimal-handling-mode).
```
create materialized source orders (
   order_id int,
   order_date timestamp,
   customer_name string,
   price decimal,
   product_id int,
   order_status smallint,
   PRIMARY KEY (order_id)
) with (
 connector = 'mysql-cdc',
 hostname = 'mysql',
 port = '3306',
 username = 'root',
 password = '123456',
 database.name = 'mydb',
 table.name = 'orders',
 server.id = '5086',
 decimal.handling.mode = 'precise'
) row format debezium_json;
```

**Comment by BugenZhao** [comment]
> With this refactor, is it still possible to pass through debezium properties via WITH clause for CDC connector?

I think so. Is there anything else to be concerned about? 🤔

**Comment by StrikeW** [comment]
> > With this refactor, is it still possible to pass through debezium properties via WITH clause for CDC connector?
> 
> I think so. Is there anything else to be concerned about? 🤔

So for these adhoc properties, we can still store them in a `map<string, string>`, am I right?

**Comment by BugenZhao** [comment]
> So for these adhoc properties, we can still store them in a `map<string, string>`, am I right?

Yes. I think we can try our best to make it type-safe, and it'll never be worse than a single large `map`.

**Comment by BugenZhao** [comment]
As we've started to provide backward compatibility, do we need to consider this issue recently? 👀

**Comment by tabVersion** [comment]
> As we've started to provide backward compatibility, do we need to consider this issue recently? 👀

Sure, but I am afraid not enough manpower for this.

**Comment by tabVersion** [comment]
will do in recent source refactoring

**Comment by tabVersion** [comment]
can close as done as normalized by https://github.com/risingwavelabs/risingwave/pull/13227
