### ISSUE TITLE
Whether the sink should include hidden columns？

### ISSUE THREAD

**Issue by huangjw806** [risingwavelabs/risingwave#7035]
create sink：
```
CREATE TABLE t (v1 int, v2 int, v3 int);
CREATE MATERIALIZED VIEW mv AS SELECT * FROM t;
CREATE SINK print_sink FROM mv WITH (connector='console', prefix='CONSOLE SINK ', suffix='XXXXXX');
INSERT INTO t VALUES (1, 2, 3);
```

cn logs:
```
CONSOLE SINK INSERT [Int32(1), Int32(2), Int32(3), Int64(228772686628278272)]XXXXXX
CONSOLE SINK COMMIT [Epoch(3574573184581632)]XXXXXX
```

Whether the sink should bring hidden columns?

Since we allow the creation of tables without primary keys, for the risingwave database itself, we can add hidden primary keys, but we can't determine where the sink goes, it may be a database or a message queue, so I don't think we need to include hidden columns in the sink.

**Comment by tabVersion** [comment]
no, sink will clip the hidden rows unless it is required by users explicitly. We will do some refractory to align the behavior, just leave it for now.

**Comment by tabVersion** [comment]
close as reaching a consensus that sink will prune all hidden columns and will down stream pk or user-defined pk.

related #8099
