### ISSUE TITLE
feat(risedev): Install redpanda in addition to Kafka

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7039]
### Is your feature request related to a problem? Please describe.

Currently, `risedev` has the option of installing Kafka.

Since Redpanda is easier to use and claims to have much better performance, 
how about also giving the option of installing Redpanda?

**Comment by tabVersion** [comment]
+1 for this proposal

from the developer side, we want to test on native kafka to achieve maximum compatibility. I don't want to count on redpanda for keeping everything aligned with kafka. For benchmark scenes, redpanda is a better choice.

**Comment by waruto210** [comment]
It's a bit difficult now. Redpanda only provides rpm/apt based installation methods and does not provide a full binary on its release page. In addition, Redpanda can only runs on Linux and requires docker/wsl to run on macOS/Windows.

**Comment by tabVersion** [comment]
close because redpanda is not cross-platform
