### ISSUE TITLE
support `RETURNING` in DML statements

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#7044]
With `RETURNING`, we're able to retrieve the changed rows in the result set instead of just the affected row numbers.

References:
- Postgres: https://www.postgresql.org/docs/15/sql-insert.html
- DuckDB: https://duckdb.org/docs/sql/statements/insert#returning-clause [[Test cases](https://github.com/duckdb/duckdb/tree/062fc98c5149584bf478546ed5b18c7930b08144/test/sql/returning)]
- Discussions about the result set: https://github.com/risingwavelabs/risingwave/issues/2678

Tasks:
- [x] Parse and bind `RETURNING` clause in DML statements.
- [x] Plan and execute DMLs with `RETURNING`.
- [ ] Support `RETURNING` in CTE.

**Comment by fuyufjh** [comment]
> Support RETURNING in CTE.

🥵

**Comment by chenzl25** [comment]
Just take a note here. Support RETURNING in CTE needs to make sure the dml will be executed exactly once.

**Comment by chenzl25** [comment]
All the following sql will execute the dml exactly once.
```sql
// ins appears 0 times.
with ins as (insert into t values (3,3,3) returning *) select 1;
// ins appears 1 times.
with ins as (insert into t values (3,3,3) returning *) select * from ins;
// ins appears 2 times.
with ins as (insert into t values (3,3,3) returning *) select * from ins union all select * from ins;
```

**Comment by fuyufjh** [comment]
> Just take a note here. Support RETURNING in CTE needs to make sure the dml will be executed exactly once.

Yes, exactly. So let's defer this feature until being requested
