### ISSUE TITLE
S3 csv source lost data

### ISSUE THREAD

**Issue by huangjw806** [risingwavelabs/risingwave#7063]
### Describe the bug

S3 csv source lost data

### To Reproduce

s3 csv file:
```
id,name,idNum
11,xx1,10341
12,xx2,20231
```
1.  lost data：
```
dev=> create materialized source s1(
    id int,
    name varchar,
    idNum varchar,
    primary key(id)
) with (
    connector = 's3',
    s3.region_name = 'ap-southeast-1',
    s3.bucket_name = 'jianwei-test',
    s3.credentials.access = 'xxxx',
    s3.credentials.secret = 'xxxx'
) row format csv delimited by ',';

dev=> select * from s1;
 id | name | idnum
----+------+-------
 11 | xx1  | 10341
(1 row)
```

**Comment by waruto210** [comment]
I guess it's because there is no line break at the end of the last line.
> A record ends at a line terminator

**Comment by fuyufjh** [comment]
> A record ends at a line terminator

I don't think that is necessary 🤔

**Comment by waruto210** [comment]
> > A record ends at a line terminator
> 
> I don't think that is necessary 🤔

The csv definition I found requires this. And the csv lib we used in the csv parser also requires this.

**Comment by huangjw806** [comment]
It does work fine after adding a line break at the end of the last line. 

If it can't be avoided maybe we should inform users in the documentation that s3 files must obey csv rules.

**Comment by fuyufjh** [comment]
@waruto210 I just tried the [official example provided by csv_core](https://docs.rs/csv-core/latest/csv_core/#example-reading-csv) and it turns out the last row is correctly parsed.

<img width="779" alt="image" src="https://user-images.githubusercontent.com/10192522/209783821-cc093ecb-bf3b-4043-b11a-f85da5c48285.png">

**Comment by waruto210** [comment]
> @waruto210 I just tried the [official example provided by rust-csv](https://docs.rs/csv/latest/csv/cookbook/index.html#reading-basic) (which is based on csv_core, developed by the same author) and it turns out the last row without new-line is correctly parsed.
> 
> 
> 
> <img width="779" alt="image" src="https://user-images.githubusercontent.com/10192522/209783821-cc093ecb-bf3b-4043-b11a-f85da5c48285.png">
> 
> 

Thank you，I'll fix that.
