### ISSUE TITLE
discussion: should `risedev` release mode set features `enable-static-log-level`, `enable-static-link`?

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#7075]
`risedev d` in release mode compiles with `cargo build -p risingwave_cmd_all -p risedev --profile release`.

Perhaps we should set features `enable-static-log-level`, `enable-static-link` just like the release build?

Some of the implications is that risedev in release mode currently defaults to producing Debug logs.

@MrCroxx

**Comment by fuyufjh** [comment]
@jon-chuang Can you take a look on this?

**Comment by jon-chuang** [comment]
Question: how come risedev build in release mode without these flags was not forbidden by https://github.com/risingwavelabs/risingwave/blob/cac383ffe444fec85954be42e1693b17d0d2fd56/src/utils/workspace-config/src/lib.rs#L16? Any ideas @MrCroxx ? Edit: seems that `cargo build --release -p risingwave_cmd` with a crate specified will not trigger the workspace hack.

**Comment by fuyufjh** [comment]
Hmmm, I think it's not necessary because the major purpose of `enable-static-log-level`, `enable-static-link` is to avoid missing libraries (e.g. `libssl`) on some Linux distributions.
