### ISSUE TITLE
`risedev c` should ignore prost

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#7077]
### Is your feature request related to a problem? Please describe.

I sometimes have errors in my autogenerated `prost` files. Can we make it that `check` ignores these files? Does it makes sense that `check` ignores everything that is in `.gitignore`? 

```
warning: unused import: `crate::plan_common::*`
 --> src/prost/src/plan_common.serde.rs:2:5
  |
2 | use crate::plan_common::*;
  |     ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default
```

**Comment by lmatz** [comment]
sounds reasonable

**Comment by BugenZhao** [comment]
It's interesting that generated files have lint errors. 🤔 I suggest adding a `allow` or `expect` attribute here if necessary.

https://github.com/risingwavelabs/risingwave/blob/831e94530e87cb0bc975ada37c40a0dc11ae85ca/src/prost/src/lib.rs#L15

**Comment by CAJan93** [comment]
@BugenZhao Yea, I was also surprised about that. Maybe it is because I am switching between branches and these branches use different protobuf messages 🤔 What I usually do is call `cargo clean`. It solves the issue, but I feel like we should not have this issue in the first place.

**Comment by fuyufjh** [comment]
So let me close it first. 🤔

**Comment by CAJan93** [comment]
Wait, why did we close this 😁 ? I though @lmatz and @BugenZhao also thought that this issue would make sense? I agree that this is not of high priority, though

**Comment by BugenZhao** [comment]
Incremental compilation of Rust is often problematic. As we always do a fresh-build on CI, I suggest we reopen this if this really occurs on CI. 🤔

**Comment by CAJan93** [comment]
Fair enough. I will go for `cargo clean` then if this happens again.
