### ISSUE TITLE
feature: telemetry

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#7105]
As mentioned in the UVP document, let's set up telemetry to collect usage information which helps to make RisingWave better. Example: https://docs.pingcap.com/tidb/dev/telemetry

**Comment by odysa** [comment]
Is it like Diagnostics reporting in Cockroach DB? 👀 
https://www.cockroachlabs.com/docs/stable/diagnostics-reporting.html

**Comment by lmatz** [comment]
> Is it like Diagnostics reporting in Cockroach DB? 👀 https://www.cockroachlabs.com/docs/stable/diagnostics-reporting.html

yes, similar

**Comment by fuyufjh** [comment]
Moved to next release.
