### ISSUE TITLE
set up benchmark for DML statements (insert, etc.)

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#7106]
### Is your feature request related to a problem? Please describe.

Some users prefer to inject data into RisingWave in a push-style manner, which is basically via the `INSERT` statements. However, so far we didn't pay much attention on its performance.

### Describe the solution you'd like

Set up a benchmark to measure and track the performance. It's similar to our Sysbench benchmark, I suppose.

**Comment by fuyufjh** [comment]
@cyliu0 Hi, any updates?

**Comment by cyliu0** [comment]
@fuyufjh We've already added the sysbench oltp_insert into daily executions. We will have the daily data on performance test dashboard from tomorrow.

**Comment by fuyufjh** [comment]
Cool!

**Comment by cyliu0** [comment]
The performance test dashboard looks good so far.
