### ISSUE TITLE
regexp_match panics when pattern is literal NULL

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#7130]
### Describe the bug

`select regexp_match('ab', NULL);` panics

### Expected behavior

```
postgres=# select regexp_match('ab', NULL);
 regexp_match
--------------

(1 row)

postgres=#
```

**Comment by xxchan** [comment]
Could sqlsmith catch such panics? 🤔 cc @kwannoel

**Comment by kwannoel** [comment]
> Could sqlsmith catch such panics? 🤔 cc @kwannoel

Currently not all table functions tested.
I shall re-open the issue for Generating table functions: https://github.com/risingwavelabs/risingwave/issues/4540.

We should be able to catch such panics.

**Comment by xxchan** [comment]
> Currently not all table functions tested.

But `regexp_match` is not a table function. `regexp_matches` is a table function.

**Comment by kwannoel** [comment]
> > Currently not all table functions tested.
> 
> But `regexp_match` is not a table function. `regexp_matches` is a table function.

I see, I think it is not generated as well. I shall create a separate issue to track it: https://github.com/risingwavelabs/risingwave/issues/7132
