### ISSUE TITLE
gaurantee the order of writes when writes come from the same session

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7134]
Due to https://github.com/risingwavelabs/risingwave/blob/main/src/source/src/table.rs#L86,
we may not know which writes will win when there are multiple ones. 
(pk conflict, and due to https://github.com/risingwavelabs/rfcs/pull/4/files#diff-73ca4924ee3c22e62b50a34acb513c5252bc3d5c44075d5b0398a2387f6d5c4dR32, the first writes win and the rest will be ignored)?

`from the same session` seems to be a reasonable setting

**Comment by BugenZhao** [comment]
A quick but working workaround might be always scheduling the DML to a fixed node and choosing a fixed parallelism here. 🥵

**Comment by lmatz** [comment]
> A quick but working workaround might be always scheduling the DML to a fixed node and choosing a fixed parallelism here. 🥵

https://github.com/risingwavelabs/rfcs/pull/4/files#diff-73ca4924ee3c22e62b50a34acb513c5252bc3d5c44075d5b0398a2387f6d5c4dR54 seems there was a plan

**Comment by xxchan** [comment]
close in favor of https://github.com/risingwavelabs/risingwave/issues/7213
