### ISSUE TITLE
bug(batch): `select now()` failed

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#7139]
### Describe the bug

```
dev=> select now();
ERROR:  QueryError: internal error: Failed to build executor: Expr error: Unsupported function: Ok(Now)
```

### To Reproduce

As above

### Expected behavior

Unlike streaming, it should evaluate `NOW()` as a function instead of an operator.

**Comment by soundOfDestiny** [comment]
do we support batch `NOW()` ?

**Comment by fuyufjh** [comment]
I suppose yes. Anyway, it shouldn't be an error like this.

**Comment by soundOfDestiny** [comment]
> I suppose yes. `NOW()` in batch query is not ambiguous - it should return the time of the current epoch.
> 
> Anyway, it shouldn't be an error like this.

a function needs to `eval()` from input rows, but `NOW()` cannot infer the time of the current epoch from input rows
Shall we expand input parameters of `Expression::eval(input: &DataChunk)`?

**Comment by soundOfDestiny** [comment]
> I suppose yes. `NOW()` in batch query is not ambiguous - it should return the time of the current epoch.
> 
> Anyway, it shouldn't be an error like this.

or shall we use a `BatchNowExecutor` to return the time of the current epoch?

**Comment by fuyufjh** [comment]
> or shall we use a BatchNowExecutor to return the time of the current epoch?

strong -1

> a function needs to eval() from input rows, but NOW() cannot infer the time of the current epoch from input rows. Shall we expand input parameters of Expression::eval(input: &DataChunk)?

Yes, this is a known issue for a long time. Previously we use [a tricky way](https://github.com/risingwavelabs/risingwave/blob/2df948ccf39b9523fc6f7438955a7a9691cc71c2/src/frontend/src/binder/expr/function.rs#L241) to solve it. Please check whether it can work.

**Comment by soundOfDestiny** [comment]
> > or shall we use a BatchNowExecutor to return the time of the current epoch?
> 
> strong -1
> 
> > a function needs to eval() from input rows, but NOW() cannot infer the time of the current epoch from input rows. Shall we expand input parameters of Expression::eval(input: &DataChunk)?
> 
> Yes, this is a known issue for a long time. Previously we use [a tricky way](https://github.com/risingwavelabs/risingwave/blob/2df948ccf39b9523fc6f7438955a7a9691cc71c2/src/frontend/src/binder/expr/function.rs#L241) to solve it. Please check whether it can work. If not, then we need a discussion.

I guess that we do not have an internal table for current epoch so we cannot rewrite NOW() as subquery. I think we need a discussion.

**Comment by fuyufjh** [comment]
> > > a function needs to eval() from input rows, but NOW() cannot infer the time of the current epoch from input rows. Shall we expand input parameters of Expression::eval(input: &DataChunk)?
> > 
> > 
> > Yes, this is a known issue for a long time. Previously we use [a tricky way](https://github.com/risingwavelabs/risingwave/blob/2df948ccf39b9523fc6f7438955a7a9691cc71c2/src/frontend/src/binder/expr/function.rs#L241) to solve it. Please check whether it can work. If not, then we need a discussion.
> 
> I guess that we do not have an internal table for current epoch so we cannot rewrite NOW() as subquery. I think we need a discussion.

I mean, can we just bind a literal timestamp to it, as what we did for `session_user()`?

**Comment by soundOfDestiny** [comment]
> what we did for `session_user()`

sorry, I followed the last link and thought you meant `pg_get_userbyid`

**Comment by soundOfDestiny** [comment]
> > > > a function needs to eval() from input rows, but NOW() cannot infer the time of the current epoch from input rows. Shall we expand input parameters of Expression::eval(input: &DataChunk)?
> > > 
> > > 
> > > Yes, this is a known issue for a long time. Previously we use [a tricky way](https://github.com/risingwavelabs/risingwave/blob/2df948ccf39b9523fc6f7438955a7a9691cc71c2/src/frontend/src/binder/expr/function.rs#L236-L240) to solve it. Please check whether it can work. If not, then we need a discussion.
> > 
> > 
> > I guess that we do not have an internal table for current epoch so we cannot rewrite NOW() as subquery. I think we need a discussion.
> 
> I mean, can we just bind a literal timestamp to it, as [what we did for `session_user()`](https://github.com/risingwavelabs/risingwave/blob/2df948ccf39b9523fc6f7438955a7a9691cc71c2/src/frontend/src/binder/expr/function.rs#L236-L240)?

sounds like #7161 ?

**Comment by jon-chuang** [comment]
I'm a little suspicious of using the `session_timestamp`. Could the session have been established for a long time before the batch query is issued?

Seems to me that the following solution is more reasonable:
1. Bind the `now()` as the time that the query is received by the frontend.

**Comment by soundOfDestiny** [comment]
> I'm a little suspicious of using the `session_timestamp`. Could the session have been established for a long time before the batch query is issued?
> 
> Seems to me that the following solution is more reasonable:
> 
> 1. Bind the `now()` as the time that the query is received by the frontend.

ok. let me replace session_timestamp with bind_timestamp

**Comment by soundOfDestiny** [comment]
> I'm a little suspicious of using the `session_timestamp`. Could the session have been established for a long time before the batch query is issued?
> 
> Seems to me that the following solution is more reasonable:
> 
> 1. Bind the `now()` as the time that the query is received by the frontend.

ok. I have just replaced `session_timestamp` with `bind_timestamp`

**Comment by soundOfDestiny** [comment]
finished by #7161
