### ISSUE TITLE
bug(frontend): name of an expression column is not comptaible with Postgres

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#7140]
### Describe the bug

RisingWave:

```
dev=> SELECT version();
      ?column?
--------------------
 PostgreSQL 13.9-RW
(1 row)
```

Expect the column name should be `version` instead of `?column?`

One additional example:

```
dev=> select length('hello');
 ?column?
----------
        5
(1 row)
```

### Expected behavior

Postgres:

(Please ignore the version value...)

```
dev=# SELECT version();
                                                            version
--------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 14.6 (Homebrew) on aarch64-apple-darwin21.6.0, compiled by Apple clang version 14.0.0 (clang-1400.0.29.202), 64-bit
(1 row)
```

```
dev=# select length('hello');
 length
--------
      5
(1 row)
```

**Comment by xiangjinwu** [comment]
Already tracked by #3812
Notably, once we implemented this, `create materialized view mv1 as select count(*) from t;` will no longer report the `An alias must be specified for an expression` error. Because the output column would get an implicit alias `count` by the same rule.

**Comment by fuyufjh** [comment]
Add some background: pgAdmin failed to log in RisingWave because it failed to get the `version` column from the result of query `select version();`.

**Comment by fuyufjh** [comment]
@xiangjinwu @st1page Can you help to work or assign it?

**Comment by xxchan** [comment]
close as duplicate
