### ISSUE TITLE
feat(expr): implement `timestamptz` functions

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#7154]
Casts (see: https://github.com/postgres/postgres/blob/e0064f0ff6dfada2695330c6bc1945fa7ae813be/src/include/catalog/pg_cast.dat#L18-L20):
- [ ] implicit cast from `DATE`
- [ ] implicit cast from `TIMESTAMP`

Functions:
- [ ] comparison (cmp)
- [ ] arithmetic (atm)

**Comment by xiangjinwu** [comment]
#5826
