### ISSUE TITLE
Add helpful error message in dashboard UI build

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#7157]
### Is your feature request related to a problem? Please describe.

I am unsure what to do if I run into below error in our CI pipeline (step `dashboard-ui-build`, [see here](https://github.com/risingwavelabs/risingwave/actions/runs/3823829701/jobs/6505412497)). 

```
...
> gen-proto
> ./scripts/generate_proto.sh

Unstaged changes after reset:
M	dashboard/proto/gen/meta.ts
Error: Generated proto files are not up to date.
Error: Process completed with exit code 1.
```

Could we do one of the following two steps?

1. Add an error message that says `run xyz.sh to generate the correct .ts files`
2. Just `cat` the files in question so a user can copy-paste the result herself/himself?

So far I tried running `generate_proto.sh` locally with some modifications, but I am running into `protoc-gen-ts_proto: program not found or is not executable`. 

Let me know what you think about the above suggestions. I would like to avoid that other people get stuck at the same point and I'd guess that this is an easy fix.

**Comment by xxchan** [comment]
> I am running into `protoc-gen-ts_proto: program not found or is not executable`.

```
npm install
```

**Comment by xxchan** [comment]
https://github.com/risingwavelabs/risingwave/pull/6629/files This PR seemed to break the error message

**Comment by CAJan93** [comment]
Amazing. Thank you very much 😁
