### ISSUE TITLE
Guidance on RisingWave configuration

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7176]
Since the machine used changes from person to person, default values may not make sense to everyone.

We can figure out a proper/"best" configuration for a particular machine, e.g. 8C 16GB.

And make a few comments about what people may need to change if they are using a machine that is XC YGB.

We may put this configuration and comments into `example.toml` and/or put them into the developer guide.

- [x] #7683

**Comment by lmatz** [comment]
Also, we may have different configurations for streaming compute nodes and batch serving compute nodes

**Comment by fuyufjh** [comment]
> Also, we may have different configurations for streaming compute nodes and batch serving compute nodes

-1, I prefer https://github.com/risingwavelabs/risingwave/issues/7203 which unified them in one cluster-level config.

**Comment by lmatz** [comment]
> It should describe the behaviors in detail. And each time a PR introduces a new config, it should update this document as well. 

Sure, hopefully, the PR can give some numbers/observation when the new config is set of a range of options

**Comment by fuyufjh** [comment]
> > Also, we may have different configurations for streaming compute nodes and batch serving compute nodes
> 
> -1, I prefer #7203 which unified them in one cluster-level config.

OK, I got the problem... As suggested by #5676, the configs that depends on particular machine hardware e.g. memory & CPU should be CLI options; while the config of "database" should be in the one cluster-level config.
