### ISSUE TITLE
bug(binder): wrong type inference for `struct` with multiple fields in `CASE` expression

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#7189]
### Describe the bug

Single field struct
```
dev=> select CASE WHEN false THEN ROW(1.1) ELSE ROW(0) END;
 case
------
 (0)
(1 row)

dev=> EXPLAIN select CASE WHEN false THEN ROW(1.1) ELSE ROW(0) END;
                                       QUERY PLAN
----------------------------------------------------------------------------------------
 BatchProject { exprs: [Case(false:Boolean, Row(1.1:Decimal), Row(0:Int32::Decimal))] }
 └─BatchValues { rows: [[]] }
(2 rows)
```

Multiple field
```
dev=> select CASE WHEN false THEN ROW(1.1, INTERVAL '1') ELSE ROW(0, INTERVAL '1') END;
ERROR:  QueryError: Bind error: types Struct(StructType { fields: [Decimal, Interval], field_names: [] }) and Struct(StructType { fields: [Int32, Interval], field_names: [] }) cannot be matched
dev=>
```

### To Reproduce

```sql
select CASE WHEN false THEN ROW(1.1, INTERVAL '1') ELSE ROW(0, INTERVAL '1') END;
```

### Expected behavior

```
postgres=# select CASE WHEN false THEN ROW(1.1, INTERVAL '1') ELSE ROW(0, INTERVAL '1') END;
     row
--------------
 (0,00:00:01)
(1 row)
```

**Comment by xiangjinwu** [comment]
It is due to the fact that we do not allow casting between the same type, so the 2nd field fails to match interval to interval 😂 
https://github.com/risingwavelabs/risingwave/blob/c479c294b5838f6ca8b601e77d79fbed188f1c19/src/frontend/src/expr/type_inference/cast.rs#L157

Maybe changing this to `src == dst || cast_ok(src, dst, allows)` would help.

**Comment by kwannoel** [comment]
Hmm... Seems like the following case is still not fixed.
```
select CASE WHEN true THEN ROW(1::int, interval '1') ELSE ROW(1.1::decimal, interval '1') END;
ERROR:  QueryError: Bind error: types Struct(StructType { fields: [Int32, Interval], field_names: [] }) and Struct(StructType { fields: [Decimal, Interval], field_names: [] }) cannot be matched
```

pg
```
postgres=# select CASE WHEN true THEN ROW(1::int, interval '1') ELSE ROW(1.1::decimal, interval '1') END;
     row
--------------
 (1,00:00:01)
(1 row)
```

Reopen to track.

**Comment by kwannoel** [comment]
> Hmm... Seems like the following case is still not fixed.
> 
> ```
> select CASE WHEN true THEN ROW(1::int, interval '1') ELSE ROW(1.1::decimal, interval '1') END;
> ERROR:  QueryError: Bind error: types Struct(StructType { fields: [Int32, Interval], field_names: [] }) and Struct(StructType { fields: [Decimal, Interval], field_names: [] }) cannot be matched
> ```
> 
> pg
> 
> ```
> postgres=# select CASE WHEN true THEN ROW(1::int, interval '1') ELSE ROW(1.1::decimal, interval '1') END;
>      row
> --------------
>  (1,00:00:01)
> (1 row)
> ```
> 
> Reopen to track.

Ignore this, it works as expected I was testing on the old branch 😶‍🌫️
