### ISSUE TITLE
discussion: introduce cluster level configs

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#7203]
## Background
In general, we have two types of config:
- Cluster-level configs: all nodes in the cluster share the same config values and these configs are not allowed to be changed after initialization.
- Node-lvel configs: different nodes in the cluster can have different config values and these configs can be tuned and changed.

After walking through all the configs we have, I think the following can be catagorized as cluster-level configs:
#### ComputeNodeOpts
- state-store
#### Config
- sstable_size_mb
- block_size_kb
- bloom_false_positive
- data_directory
- object_store_use_batch_delete
- (BackupConfig) storage_url
- (BackupConfig) storage_directory
- max_heartbeat_interval_secs?

Almost all the above configs are storage related, which makes sense since we are running with a remote shared storage.

## Problem
Currently cluster-level configs are mixed with node-lelve configs, which may cause potential risk during deployment. For example:
- If user mistakenly changes the `data_directory` or use the wrong `state-store` url when starting up a CN, wrong result or missing data will be observed without any notice.
- If user uses different `sstable_size_mb`/`block_size_kb` for different compactors/CNs, there can be performance degradation without any notice.
- If user uses different `BackupConfig` for meta node/CNs, it may fail to perform backup and fail to query backup data.

## Discussion
Shall we make cluster-level configs explicit in our codes and persist them in meta store for safety check on node join?

We can even make the cluster-level configs initialization more explicit by introducing a required "cluster init" phase during deployment. In this case, when a node join, it doesn't need to specify cluster-level configs but fetch them from meta.

Reference:
- https://www.cockroachlabs.com/docs/v22.2/cluster-settings
- https://www.cockroachlabs.com/docs/stable/cockroach-init.html

**Comment by hzxa21** [comment]
cc @zwang28 @yezizp2012

**Comment by fuyufjh** [comment]
+1. I had once discussed with @arkbriar

**Comment by Gun9niR** [comment]
+1, storing cluster config in meta also has the benefit of simplifying command line argument passing. In the process of introducing java binding, I realize that pulling config from cluster is a necessity (#7269).

**Comment by fuyufjh** [comment]
Additionally, following streaming parameters may also be included:

- barrier_interval_ms
- checkpoint_frequency

We need a complete list of parameters in the docs. While before the doc is published, I think we need to create one in Notion. Let me do it later.

**Comment by Gun9niR** [comment]
Moved to https://github.com/risingwavelabs/rfcs/pull/34
