### ISSUE TITLE
bug:  query `_rw_kafka_timestamp` returns empty result.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#7211]
### Describe the bug

Query `_rw_kafka_timestamp` returns empty result.

### To Reproduce

Run following sqls:
```
create source s1 (v1 int, v2 varchar) with (
  connector = 'kafka',
  topic = 'kafka_1_partition_topic',
  properties.bootstrap.server = '127.0.0.1:29092',
  scan.startup.mode = 'earliest'
) row format json;

select _rw_kafka_timestamp from s1;
```

Returns empty result.

### Expected behavior

It should return `_rw_kafka_timestamp` data.

### Additional context

No.

**Comment by tabVersion** [comment]
Isn't `_rw_kafka_timestamp` just for binding? We are not going to persist timestamps for every record.

**Comment by fuyufjh** [comment]
Agree. https://github.com/risingwavelabs/rfcs/pull/20/files#r1060339723

> By the way, even though these columns are used for filtering majorly, we also need to implement on the output side to make it compliant with SQL's semantics i.e. `select _rw_kafka_timestamp, _rw_kafka_partition_offset, _rw_kafka_partition, * from my_source` should give correct results.

**Comment by ZENOTME** [comment]
If we want to make it compliant with SQL's semantics, we should give every timestamps for every record? Sounds like a big cost and it depends on source can give this info @tabVersion

**Comment by liurenjie1024** [comment]
> If we want to make it compliant with SQL's semantics, we should give every timestamps for every record? Sounds like a big cost and it depends on source can give this info @tabVersion 

I think if it's explicitly required by user, we should give correct result, even if it's slow. But we should do column pruning carefully to avoid that if it's not required by user.

**Comment by tabVersion** [comment]
> If we want to make it compliant with SQL's semantics, we should give every timestamps for every record? Sounds like a big cost and it depends on source can give this info @tabVersion

Yes, and I am not sure the upstream provides this ability. Seeking a consuming position by timestamp is a common feature but getting msgs together with their timestamps is not.

**Comment by ZENOTME** [comment]
For kafka, we can get the timestamp of message, see: https://docs.rs/rdkafka/latest/rdkafka/message/trait.Message.html#tymethod.timestamp.

But there is a problem: This timestamp is a timestamp in the broker's timezone, which means that if we want to correctly parse this timestamp, we need to know what this timezone is. 

I think there are two way to get the timezone:
1. read the timezone from kafka. But I can't find the interface to do this job. Can we do this? @tabVersion 
2. Let the user to assign the timezone when create source, e.g. 
```
CREATE SOURCE IF NOT EXISTS source_abc (
   column1 varchar,
)
WITH (
   connector='kafka',
   ...
   timezone = "+08:00"
)
```

**Comment by xiangjinwu** [comment]
> This timestamp is a timestamp in the broker's timezone

Any reference for this statement?

I found this [KIP-32](https://cwiki.apache.org/confluence/display/KAFKA/KIP-32+-+Add+timestamps+to+Kafka+message):
> The good things about LogAppendTime are:
> 1. Broker is more robust.
> 1. Monotonically increasing.
> 1. Deterministic behavior for log rolling and retention.
> 1. If CreateTime is required, it can always be put into the message payload.

In time zones with daylight saving, local time without time zone is not monotonic. This suggests the LogAppendTime from broker should not be affected by local time zone settings. We can also run a simple example to confirm (or refute) this.

**Comment by ZENOTME** [comment]
Sorry, my wrong understand of the time🥵. Seems it's a unix timestamp.

**Comment by tabVersion** [comment]
negative on this proposal. 

Pulsar, kinesis, and pubsub don't provide message timestamps along with the message itself. It is more like a kafka specified feature. cc @neverchanje

**Comment by tabVersion** [comment]
> > negative on this proposal.
> > Pulsar, kinesis, and pubsub don't provide message timestamps along with the message itself. It is more like a kafka specified feature. cc @neverchanje
> 
> As the column name `_rw_kafka_timestamp ` implied, it's a kafka specific column and a virtual column in kafka source. Different sources should have different virtual columns, and we can add it when necessary.

I thought `_rw_kafka_timestamp` is a temp naming.  When it comes to other mqs, what is the expected behavior?

**Comment by liurenjie1024** [comment]
> I thought _rw_kafka_timestamp is a temp naming. When it comes to other mqs, what is the expected behavior?

Currently we only add this virtual column for kafka source. We will add other virtual columns for other sources.

**Comment by liurenjie1024** [comment]
I would vote for 1. Timestamp is just one kind of virtual column, and use unified column name for different source maybe difficult to maintain and understand.
