### ISSUE TITLE
bug / known issue: inserts may be disordered even on one session 

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#7213]
### Describe the bug

Here a random write channel will be picked.

https://github.com/risingwavelabs/risingwave/blob/314fcc73b6f1a76987d0475f289dfaa6795f547b/src/source/src/table.rs#L82-L87

As a result, even in one session, DML statements may be reordered regarding the time that they leave the write channel.

### To Reproduce

Just a technical analysis.

### Expected behavior

Writes in one session should happen in order.

**Comment by lmatz** [comment]
#7134,

And another question is that whether we ignore an insert with the same pk 
or let it overwrite the previous one 
or both make sense so user decide

**Comment by fuyufjh** [comment]
> #7134,
> 
> And another question is that whether we ignore an insert with the same pk or let it overwrite the previous one or both make sense so user decide

I once discussed with @st1page.

@st1page was considering adding a table-level option to control whether a new update should override. (upsert or ignore)

My idea is to always do upsert, similar to Flink's updatable stream.

**Comment by st1page** [comment]
FYI: https://github.com/risingwavelabs/rfcs/pull/48

**Comment by xxchan** [comment]
fixed by https://github.com/risingwavelabs/risingwave/pull/14380
