### ISSUE TITLE
bug: check_new_rows.slt fails. Result mismatch

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#7217]
### Describe the bug

[Failing CI Pipelien](https://buildkite.com/risingwavelabs/pull-request/builds/15159#018581e8-86c3-4263-ba17-10adedc1d88e) 

Seems like this is unrelated to my change. 

```
failed to run `e2e_test/source/cdc/cdc.check_new_rows.slt`
--
  |  
  | Caused by:
  | query result mismatch:
  | [SQL] select cnt from products_cnt;
  | [Diff] (-excepted\|+actual)
  | -   11
  | +   9
  | at e2e_test/source/cdc/cdc.check_new_rows.slt:2
  |  
  |  
  | Stack backtrace:
  | 0: anyhow::error::<impl anyhow::Error>::msg
  | 1: sqllogictest_bin::run_test_file::{{closure}}
  | 2: sqllogictest_bin::main_okk::{{closure}}
  | 3: tokio::runtime::park::CachedParkThread::block_on
  | 4: tokio::runtime::runtime::Runtime::block_on
  | 5: sqllogictest::main
  | 6: std::sys_common::backtrace::__rust_begin_short_backtrace
  | 7: std::rt::lang_start::{{closure}}
  | 8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
  | at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/ops/function.rs:606:13
  | 9: std::panicking::try::do_call
  | at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:483:40
  | 10: std::panicking::try
  | at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:447:19
  | 11: std::panic::catch_unwind
  | at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panic.rs:137:14
  | 12: std::rt::lang_start_internal::{{closure}}
  | at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/rt.rs:148:48
  | 13: std::panicking::try::do_call
  | at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:483:40
  | 14: std::panicking::try
  | at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:447:19
  | 15: std::panic::catch_unwind
  | at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panic.rs:137:14
  | 16: std::rt::lang_start_internal
  | at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/rt.rs:148:20
  | 17: main
  | 18: <unknown>
  | 19: __libc_start_main
  | 20: _start
```

**Comment by StrikeW** [comment]
This check relies on the correctness of the recovery process because it checks the result of MV after cluster recovery. 
But there are errors in the meta node log. Have you looked into it? cc @CAJan93 

> 2023-01-05T12:39:16.508114Z  INFO risingwave_meta::barrier::recovery: recovery start!
> 2023-01-05T12:39:16.514618Z ERROR risingwave_meta::barrier::recovery: reset compute nodes failed err=Rpc error: failed to create RPC client: TransportError(tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))))
>   backtrace of `MetaError`:
>    0: <risingwave_meta::error::MetaError as core::convert::From<risingwave_meta::error::MetaErrorInner>>::from
>              at ./src/meta/src/error.rs:66:33
>    1: <T as core::convert::Into<U>>::into
>              at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/convert/mod.rs:726:9
>    2: <risingwave_meta::error::MetaError as core::convert::From<risingwave_rpc_client::error::RpcError>>::from
>              at ./src/meta/src/error.rs:135:9

**Comment by CAJan93** [comment]
Okay. Let's close it. Seems to be temporary
