### ISSUE TITLE
discussion: source: extract user data in a case-insensitive fashion

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#7228]
### Describe the bug

Currently our source definition requires a tricky case-sensitive match between provided column names and proto or data. 

Example:

Provided

```sql
CREATE SOURCE MySource (
   DeviceId varchar
   -- will be converted to 'deviceid' (lower case) implicitly, regarding to PG's behavior
)
```

The event below will be rejected

```
{"DeviceId":"00:00:00:68:ab:b5"}
```

Because `"DeviceId"` != `"deviceid"`!

As a result, users are forced to add a double quote to make it case-insensitive, and then the data can be consumed normally. But this also makes double quotes everywhere.

### Expected behavior

Shall we just be case-insensitive when parsing source incoming data?

This, as a matter of fact, followed the PG's case-insensitive style.

### Additional context

We may also introduce a `case-sensitive` option for sources, in case that some fields in users's data have 2 fields with same name incidentally e.g. `DeviceId` and `deviceID`, but I suppose this would be a very rare cases, so may not actually do this now.

**Comment by BugenZhao** [comment]
Currently, we treat JSON records as a map and directly lookup for the key. Not sure whether there's an efficient way to index into the map ignoring the case. 🤔

**Comment by fuyufjh** [comment]
> Currently, we treat JSON records as a map and directly lookup for the key. Not sure whether there's an efficient way to index into the map ignoring the case. 🤔

A for-loop over JSON sounds as efficient as before? For each key-value pair in JSON, match and fill it into a row field.

**Comment by BugenZhao** [comment]
Yes, you're right. 🥵 All we need is a "inverted" index.
