### ISSUE TITLE
force developer give `target_size` when creating `ColIndexMapping`

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#7234]
`ColIndexMapping` is a very basic util in our optimizer, which describe a partial mapping from usize to usize. Its definition actually need three field (source_size, target_size, mapping_rules). For convenience, we provide `ColIndexMapping::new(map: Vec<Option<usize>>)` interface so that we can create a ColIndexMapping without target size. In most cases, the wrong target size does not make trouble until we get an inverse of the column mapping. E.g. before https://github.com/risingwavelabs/risingwave/pull/7231/files#diff-45300c12653f297ef88fd1bbda8c5f0ea22c56c08cafb8f4559560b2a9d17db1 our LeftsemiJoin::r2i_col_mapping will give a mapping whose source_size is not equal to the length of the right input's schema.

**Comment by st1page** [comment]
c.c. @chenzl25 @xiangjinwu

**Comment by TennyZhuang** [comment]
Any update?
