### ISSUE TITLE
bug: create mv with now() affects the outcome of select the base table

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#7247]
### Describe the bug

Newly inserted records on a base table are invisible if there is a mv with `now()` created on the based table.

Records inserted after dropping mv can be shown. See the example below.

commit: `53f7e0db772ac7e51773791bb8301624ed763ae8`

### To Reproduce

```sql
dev=> create table t(t1 timestamp);
CREATE_TABLE

dev=> create materialized view mv as select * from t where t1 < now() - interval '1 day';
CREATE_MATERIALIZED_VIEW

dev=> insert into t values('2023-01-06 18:38:00');
INSERT 0 1
dev=> flush;
FLUSH

dev=> select * from t;
 t1 
----
(0 rows)

dev=> select * from mv;
 t1 
----
(0 rows)

dev=> flush;
FLUSH

dev=> select * from t;
 t1 
----
(0 rows)

dev=> select * from mv;
 t1 
----
(0 rows)

dev=> drop materialized view mv;
DROP_MATERIALIZED_VIEW

dev=> insert into t values('2023-01-06 18:39:00');
INSERT 0 1

dev=> flush;
FLUSH
dev=> select * from t;

         t1          
---------------------
 2023-01-06 18:39:00
(1 row)
```

### Expected behavior

MV should not affect the query results on the base table.

**Comment by hzxa21** [comment]
@soundOfDestiny pleast take a look

**Comment by BugenZhao** [comment]
This is because the compute node failed at `Executor error: Chunk operation error: Unsupported function: Timestamp cmp Timestamptz` and triggered recovery (after #7223).

It seems that turning recovery on by default for developing makes a (previously) obvious bug confusing. 😟 cc @fuyufjh

**Comment by soundOfDestiny** [comment]
before #7243 , we must use timestamp with time zone for `now()`. look at discussion in #7161 for details.

**Comment by soundOfDestiny** [comment]
> Any updates on this bug? Please set an assignee as it's a critical user-reported bug.

- before https://github.com/risingwavelabs/risingwave/pull/7243 , we must use timestamp with time zone for now(). look at discussion in https://github.com/risingwavelabs/risingwave/pull/7161 for details.
- if user still wants to use timestamp without time zone, he should wait for #7243

**Comment by soundOfDestiny** [comment]
> #7243 has been merged, but the queries in description are now failing an assertion added in the PR:
> 
> https://github.com/risingwavelabs/risingwave/blob/eca954187d56997441994ad330240ded5396e7c1/src/stream/src/executor/dynamic_filter.rs#L259-L260
> 
> Likely the frontend only aligns type for `DynamicFilter` created by subquery but not `now`.

@jon-chuang
