### ISSUE TITLE
perf: nexmark q18

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#7284]
```sql
CREATE MATERIALIZED VIEW nexmark_q18 AS
SELECT auction, bidder, price, channel, url, date_time, extra
FROM (
    SELECT *, 
        ROW_NUMBER() OVER (
            PARTITION BY bidder, auction 
            ORDER BY date_time DESC
        ) AS rank_number
    FROM bid
)
WHERE rank_number <= 1;
```

<details>
<summary>CREATE SOURCE statements</summary>

```sql
CREATE SOURCE nexmark (
  event_type BIGINT,
  person STRUCT<"id" BIGINT,
                "name" VARCHAR,
                "email_address" VARCHAR,
                "credit_card" VARCHAR,
                "city" VARCHAR,
                "state" VARCHAR,
                "date_time" TIMESTAMP,
                "extra" VARCHAR>,
  auction STRUCT<"id" BIGINT,
                 "item_name" VARCHAR,
                 "description" VARCHAR,
                 "initial_bid" BIGINT,
                 "reserve" BIGINT,
                 "date_time" TIMESTAMP,
                 "expires" TIMESTAMP,
                 "seller" BIGINT,
                 "category" BIGINT,
                 "extra" VARCHAR>,
  bid STRUCT<"auction" BIGINT,
             "bidder" BIGINT,
             "price" BIGINT,
             "channel" VARCHAR,
             "url" VARCHAR,
             "date_time" TIMESTAMP,
             "extra" VARCHAR>
) WITH (
    connector = 'nexmark',
    nexmark.split.num = '2',
    nexmark.min.event.gap.in.ns = '100'
) ROW FORMAT JSON;

CREATE VIEW PERSON as select (person).* from nexmark where event_type = 0;

CREATE VIEW AUCTION as select (auction).* from nexmark where event_type = 1;

CREATE VIEW BID as select (bid).* from nexmark where event_type = 2;
```

</details>

RisingWave uses regular GroupTopN:

```
 StreamMaterialize { columns: [auction, bidder, price, channel, url, date_time, extra, _row_id(hidden)], pk_columns: [_row_id] }
 └─StreamExchange { dist: HashShard(_row_id) }
   └─StreamGroupTopN { order: "[Field(bid, 5:Int32) DESC, Field(bid, 6:Int32) ASC]", limit: 1, offset: 0, group_key: [1, 0] }
     └─StreamExchange { dist: HashShard(Field(bid, 1:Int32), Field(bid, 0:Int32)) }
       └─StreamProject { exprs: [Field(bid, 0:Int32), Field(bid, 1:Int32), Field(bid, 2:Int32), Field(bid, 3:Int32), Field(bid, 4:Int32), Field(bid, 5:Int32), Field(bid, 6:Int32), _row_id] }
         └─StreamFilter { predicate: (event_type = 2:Int32) }
           └─StreamRowIdGen { row_id_index: 4 }
             └─StreamSource { source: "nexmark", columns: ["event_type", "person", "auction", "bid", "_row_id"] }
(8 rows)

```

... while Flink uses the `Deduplicate` operator, which is a specialized GroupTopN with 1) the timestamp column (i.e. watermark column) as the first group key and 2) the row number `N` = 1.

```
== Optimized Physical Plan ==
Sink(table=[default_catalog.default_database.discard_sink], fields=[auction, bidder, price, channel, url, dateTime, extra])
+- Calc(select=[$1 AS auction, $2 AS bidder, $3 AS price, $4 AS channel, $5 AS url, dateTime, $6 AS extra])
   +- Deduplicate(keep=[LastRow], key=[$1, $2], order=[ROWTIME])
      +- Exchange(distribution=[hash[$1, $2]])
         +- Calc(select=[dateTime, bid.auction AS $1, bid.bidder AS $2, bid.price AS $3, bid.channel AS $4, bid.url AS $5, bid.extra AS $6], where=[=(event_type, 2)])
            +- WatermarkAssigner(rowtime=[dateTime], watermark=[-(dateTime, 4000:INTERVAL SECOND)])
               +- Calc(select=[event_type, bid, CASE(=(event_type, 0), person.dateTime, =(event_type, 1), auction.dateTime, bid.dateTime) AS dateTime])
                  +- TableSourceScan(table=[[default_catalog, default_database, datagen]], fields=[event_type, person, auction, bid])

== Optimized Execution Plan ==
Sink(table=[default_catalog.default_database.discard_sink], fields=[auction, bidder, price, channel, url, dateTime, extra])
+- Calc(select=[$1 AS auction, $2 AS bidder, $3 AS price, $4 AS channel, $5 AS url, dateTime, $6 AS extra])
   +- Deduplicate(keep=[LastRow], key=[$1, $2], order=[ROWTIME])
      +- Exchange(distribution=[hash[$1, $2]])
         +- Calc(select=[dateTime, bid.auction AS $1, bid.bidder AS $2, bid.price AS $3, bid.channel AS $4, bid.url AS $5, bid.extra AS $6], where=[(event_type = 2)])
            +- WatermarkAssigner(rowtime=[dateTime], watermark=[(dateTime - 4000:INTERVAL SECOND)])
               +- Calc(select=[event_type, bid, CASE((event_type = 0), person.dateTime, (event_type = 1), auction.dateTime, bid.dateTime) AS dateTime])
                  +- TableSourceScan(table=[[default_catalog, default_database, datagen]], fields=[event_type, person, auction, bid])
```

Deduplicate operator is one of our quarter objectives. This issue is just for tracking the performance issue in NexMark.

**Comment by fuyufjh** [comment]
By the way, the Q18 query in our SLT cases added an `extra` column:

https://github.com/risingwavelabs/risingwave/blob/f4abbcd0b94cb5ccf2a27f013376288eac265de6/e2e_test/streaming/nexmark/views/q18.slt.part#L2-L13

which is unnecessary for a performance test.

**Comment by lmatz** [comment]
https://github.com/risingwavelabs/kube-bench/pull/72

**Comment by BugenZhao** [comment]
I guess the major difference is that we do not have an append-only optimized group top-n. Compared to `Deduplicate`, this does not rely on the time attribute and the only extra overhead is that we emit more `Update`s. 🤔

**Comment by lmatz** [comment]
> I guess the major difference is that we do not have an append-only optimized group top-n. Compared to `Deduplicate`, this does not rely on the time attribute and the only extra overhead is that we emit more `Update`s. 🤔

IIRC, another famous streaming database has exactly this optimization, i.e. append-only and/or N=1 Group Top-N

**Comment by fuyufjh** [comment]
> I guess the major difference is that we do not have an append-only optimized group top-n. Compared to `Deduplicate`, this does not rely on the time attribute and the only extra overhead is that we emit more `Update`s. 🤔

Good point! Here what we need is actually append-only group top-N

**Comment by liurenjie1024** [comment]
I think flink's implementation is quite limited:
https://github.com/apache/flink/blob/68b37fb867374df5a201f0b170e35c21266e5d7b/flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/RowTimeDeduplicateFunction.java#L86-L86

This maybe because currently flink only allow order by time attributes in over window function.

**Comment by fuyufjh** [comment]
> This maybe because currently flink only allow order by time attributes in over window function.

IIRC, all of their over window functions must `order by time` only (or without `order by`)

**Comment by liurenjie1024** [comment]
> > This maybe because currently flink only allow order by time attributes in over window function.
> 
> IIRC, all of their over window functions must either `order by time` or no `order by`

It's mandatory: https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/dev/table/sql/queries/over-agg/

**Comment by fuyufjh** [comment]
By the way, why is there a `WatermarkAssigner` operator in the plan? It seems no one specified the watermark. cc. @st1page @yuhao-su

**Comment by yuhao-su** [comment]
> By the way, why is there a WatermarkAssigner operator in the plan? 

Is this specified when creating source? @BugenZhao

**Comment by BugenZhao** [comment]
> By the way, why is there a `WatermarkAssigner` operator in the plan? It seems no one specified the watermark. cc. @st1page @yuhao-su

I guess it's set when creating the source.

https://github.com/nexmark/nexmark/blob/master/nexmark-flink/src/main/resources/queries/ddl_kafka.sql

**Comment by st1page** [comment]
> By the way, why is there a `WatermarkAssigner` operator in the plan? It seems no one specified the watermark. cc. @st1page @yuhao-su

I think it is defined on the source when it is created. Btw, @BugenZhao has a test yesterday. If we do not define watermark on that, the flink will give an error
```
StreamPhysicalDeduplicate doesn’t support consuming update and delete changes which is produced by node TableSourceScan(table=[[bz_table_store_catalog, default, t]], fields=[v])
```

**Comment by fuyufjh** [comment]
Sorry may mistake 😇 After we have supported watermark let's also add that in NexMark source.
