### ISSUE TITLE
optimization: StreamHashJoin can fill cache on write directly without read when the join key contains input_pk

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#7290]
Maybe it is a little improvement but very general when join the dim table with pk in snowflake model or star model
such as nexmark q3, q4, q6, q8, q20

**Comment by lmatz** [comment]
seems done 

https://github.com/risingwavelabs/risingwave/blob/03c26b0bfd3a23023ffedfc1f1adb053c23af498/src/stream/src/executor/managed_state/join/mod.rs#L462
