### ISSUE TITLE
perf: high per key cache hit rate does not mean high per chunk cache hit rate

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7291]
```
dev=> create source s1 (v1 bigint)  with (                                                             
  connector = 'datagen',                                                                             
  fields.v1.kind = 'random',                                                                         
  fields.v1.min = '0',                                                                               
  fields.v1.max = '250000',                                                                          
  datagen.rows.per.second = '100000'                                                             
) row format json;
CREATE_SOURCE
dev=> create sink s1_sink as select v1, count(*) from s1 group by v1 with ( connector = 'blackhole' );                                                                                                CREATE_SINK
```

![SCR-20230109-pi3](https://user-images.githubusercontent.com/5791930/211286903-80f2cb12-a396-4e4f-bed6-2633f15fb106.png)

We see that even though the row cache hit rate is about 70-80%(`1-1.21/5.43 = 0.78`),
we still need to fetch from S3 for each chunk. Of course, the lookup may also hit the block cache, but the fundamentals do not change, i.e. one key cache miss blocks the whole chunk.

Will add more metrics to see how much time it wastes exactly.

_Originally posted by @lmatz in https://github.com/risingwavelabs/risingwave/issues/7268#issuecomment-1375395100_

**Comment by fuyufjh** [comment]
How to improve this
