### ISSUE TITLE
feat: SQL command to show internal tables (state & indexes)

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#7304]
> I am also considering to expose internal tables to users/developers in SQL besides the little-known `./risedev ctl table list`. Let me open another issue for that.

_Originally posted by @fuyufjh in https://github.com/risingwavelabs/risingwave/issues/7303#issuecomment-1378213970_

-----

## Motivations

- Even though useless for production, but it's a good way for users to learn the internals of RisingWave and for debugging.
- **Why Not?** Since we had designed the internal status & indexes as relational tables, it's trivial to show them out. Currently we have `risectl table list` but most people don't know it.

## Proposal

Hope there can be a command like:

```sql
-- list all internal tables except tables and MVs
show internal tables; 

               Name
------------------------------------
__internal_mv1_5_hashjoinleft_1004
__internal_mv1_5_hashjoinright_1006
```

Alternative: (Which one is better? Or both?)

```sql
-- list all tables including tables and MVs
show all tables;

               Name
------------------------------------
t2
t1
mv1
__internal_mv1_5_hashjoinleft_1004
__internal_mv1_5_hashjoindegreeleft_1005
__internal_mv1_5_hashjoinright_1006
__internal_mv1_5_hashjoindegreeright_1007
```

**Comment by st1page** [comment]
That is really useful! I still remember when we debug without deploying the dashboard, we try the table id from 1001 and guess which table it is with the table's schema :rofl:
