### ISSUE TITLE
Support HDFS as non-s3 object store

### ISSUE THREAD

**Issue by wcy-fdu** [risingwavelabs/risingwave#7310]
Possible roadmap:

- [x] Explore how to implement HDFS with opendal
- [x] Support JAVA environment and HADOOP environment
- [ ] support HDFS config in RisingWave Operator @arkbriar 
- [x] (micro)bench the performance of s3 and HDFS

**Comment by Xuanwo** [comment]
> * (micro)bench the performance of s3 and HDFS

I'm working on implement `webhdfs` support which uses hdfs's HTTP API so that users don't need a full hadoop environment. Are you willing to bench it too?

**Comment by wcy-fdu** [comment]
> > * (micro)bench the performance of s3 and HDFS
> 
> I'm working on implement `webhdfs` support which uses hdfs's HTTP API so that users don't need a full hadoop environment. Are you willing to bench it too?

When will the `webhdfs` available?

**Comment by Xuanwo** [comment]
> When will the `webhdfs` available?

I expect `webhdfs` will be available in the middle of Feb.

**Comment by wcy-fdu** [comment]
Benchmark HDFS with S3, single node
https://github.com/risingwavelabs/risingwave/pull/7283#issuecomment-1418686904

**Comment by Xuanwo** [comment]
FYI, webhdfs support has been released in v0.26.2. 

Reference: https://opendal.databend.rs/opendal/services/struct.Webhdfs.html

**Comment by wcy-fdu** [comment]
FYI, I re-benched again and recorded more and more detailed metrics.  cc @Xuanwo @hzxa21

**Comment by wcy-fdu** [comment]
The kernel part and environment is done, and currently only RisingWave Operator support is required. cc @arkbriar

**Comment by wcy-fdu** [comment]
## Benchmark HDFS & WebHDFS
### Environment
- region: `ap-southeast-1`
- EC2: `c5.4xlarge x86_64 AMI`
- Mode: release single node, 1CN 
- Query: nexmark q7

### Result left(17:13-17:28) webhdfs, right(17:28-17:43) hdfs
#### memory & cpu & throughput
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/58715567/221529076-6f0c61df-9b87-454d-91f0-55a608ee8612.png">
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/58715567/221529154-a9e024db-38d4-4b77-a33b-7df7e6f53ce1.png">

#### object storage
<img width="997" alt="image" src="https://user-images.githubusercontent.com/58715567/221529549-8487462e-f9e4-47e7-9ef2-096e83ec4601.png">
<img width="498" alt="image" src="https://user-images.githubusercontent.com/58715567/221529854-2bfda11c-6066-4688-8ba1-9e3c0b36b57d.png">
<img width="495" alt="image" src="https://user-images.githubusercontent.com/58715567/221529920-6ba1a5bb-48f6-40b2-9670-c9be1e22cd32.png">
<img width="500" alt="image" src="https://user-images.githubusercontent.com/58715567/221530052-42ba5e06-8177-4ffe-80bf-ee044e5181f7.png">
<img width="496" alt="image" src="https://user-images.githubusercontent.com/58715567/221530113-df88a0d1-999e-4843-9092-93bed454c3ed.png">
<img width="493" alt="image" src="https://user-images.githubusercontent.com/58715567/221530136-687c2c22-c924-4f8d-995d-7cd76d88062c.png">
<img width="501" alt="image" src="https://user-images.githubusercontent.com/58715567/221530198-3056a368-f2c9-4286-9e8c-c29be39e40c0.png">
<img width="504" alt="image" src="https://user-images.githubusercontent.com/58715567/221530289-b428e03f-0787-4312-90dc-3af982df79e3.png">


<img width="494" alt="image" src="https://user-images.githubusercontent.com/58715567/221529661-de43eed2-6497-4126-9249-1cf4151fe37e.png">
<img width="497" alt="image" src="https://user-images.githubusercontent.com/58715567/221529725-74f8dbe3-79a4-4306-91ec-c455b44ef56d.png">

**Comment by Xuanwo** [comment]
Seems the latency of HDFS is more dependable than that of WebHDFS. I shall investigate.

**Comment by wcy-fdu** [comment]
> Seems the latency of HDFS is more dependable than that of WebHDFS. I shall investigate.
This metrics `fetch meta duration` is a little strange, `p99` is basically the same, but for `pmax`, webhdfs is much longer. I guess in some extreme scenario, webhdfs reconnect. Not sure whether the http long link is open or keep alive is open.  
 <img width="639" alt="image" src="https://user-images.githubusercontent.com/58715567/221551670-e781f3f1-de39-4288-b02f-4c599c26753b.png">
 
<img width="514" alt="image" src="https://user-images.githubusercontent.com/58715567/221553189-4085e6ca-4a37-4797-b9fd-6085fecca166.png">
<img width="508" alt="image" src="https://user-images.githubusercontent.com/58715567/221553222-3c098824-35f3-479b-aa3a-48bbba3bae4f.png">

**Comment by arkbriar** [comment]
> support HDFS config in RisingWave Operator @arkbriar

It's under implementation by @yufansong https://github.com/risingwavelabs/risingwave-operator/pull/371 and will be merged soon. Hopefully will also be included in the next release.
