### ISSUE TITLE
bug(frontend): wrong cast for `NULL` in places we require `boolean`

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#7312]
### Describe the bug

```sql
dev=> SELECT 1 having null;
ERROR:  QueryError: internal error: argument of HAVING must be boolean, not type Varchar
dev=>
```

### To Reproduce

```sql
SELECT 1 having null;
```

### Expected behavior

```
postgres=# select 1 having null;
 ?column?
----------
```

**Comment by xiangjinwu** [comment]
Basically, at places where we check `expr.return_type() == Bool` (incl. `where` and `having`), we should check `expr.is_unknown()` and then `expr.cast_implict(Bool)`. Note the function is `is_unknown` rather than `is_null`, as the former also handles `SELECT 1 where 'y';`
