### ISSUE TITLE
bug: Frontend metrics not showing in grafana.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#7316]
### Describe the bug

We have the panel, but no data.
<img width="1656" alt="image" src="https://user-images.githubusercontent.com/2771941/211768499-07b014cd-8455-46cc-96ef-d218117bfe38.png">

### Expected behavior

Frontend metrics should be visualized correctly.

**Comment by liurenjie1024** [comment]
I'll start to work on this.

**Comment by liurenjie1024** [comment]
Update: It seems that this only happens on cloud, and it's fine in local dev machine.

**Comment by liurenjie1024** [comment]
After syncing with @Nebulazhang it's caused by missing job in promethues, and cloud team will support this.

**Comment by Nebulazhang** [comment]
@arkbriar has fixed the bug in the PR: https://github.com/risingwavelabs/risingwave-operator/pull/342

**Comment by liurenjie1024** [comment]
@Nebulazhang @arkbriar  Is the new operator released? I still can't see the metrics.

**Comment by arkbriar** [comment]
> @Nebulazhang @arkbriar Is the new operator released? I still can't see the metrics.
@liurenjie1024 Not yet

**Comment by liurenjie1024** [comment]
> > @Nebulazhang @arkbriar Is the new operator released? I still can't see the metrics.
> 
> @liurenjie1024 Not yet

Do we have eta for this?

**Comment by arkbriar** [comment]
> Do we have eta for this? @arkbriar

@liurenjie1024 From this month on, the operator will cut off a release at the end of each month, so I think the eta should be 2/28. Currently, I'm waiting for the following two feature changes to be merged:
- https://github.com/risingwavelabs/risingwave-operator/pull/345
- https://github.com/risingwavelabs/risingwave-operator/pull/344

**Comment by liurenjie1024** [comment]
Done
