### ISSUE TITLE
DISTINCT ON doesn't respect order for ON columns

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#7332]
### Describe the bug

`DISTINCT ON` is planned to group top n, but it seems not enough. Because for group top n, its order is only the order in each group, instead of the output order.

### To Reproduce

```sql
create table t (x int);
insert into t values(1),(2);


dev=> select distinct on(x) x from t order by x;
 x 
---
 2
 1
(2 rows)

dev=> select distinct on(x) x from t order by x;
 x 
---
 1
 2
(2 rows)
```

### Expected behavior

Output should be sorted

**Comment by xxchan** [comment]
cc @TennyZhuang

**Comment by st1page** [comment]
I think the specific implementation is just to replace the hashmap with a Btreemap. And that optimization can also be done on the HashAgg executor. But I prefer to just require order when optimizing and insert add a SortOperator above. 
1. it is not a necessary optimization.
2. I am not sure if it is better. Though we emit an extra Sort executor, the btree map is more inefficient to look up than hash map. The cost of the extra Sort executor depends on the groups number and the cost of the btree map depends on the groupExecutor's input.
