### ISSUE TITLE
Time zone: support fixed offset e.g. `UTC+8`

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#7338]
Currently, we only support geographical timezones for interpretation of timezone strings in `AT TIME ZONE` and session time zone

Note that PG supports such strings.

**Comment by jon-chuang** [comment]
Seems that postgres' implementation is quite weird. `asia/singapore` is equivalent to `utc-8`, not `utc+8`... :thinking:

**Comment by xiangjinwu** [comment]
https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-TIMEZONES
> PostgreSQL allows you to specify time zones in three different forms:
> * A full time zone name, for example `America/New_York`.
>   * PostgreSQL uses the widely-used IANA time zone data for this purpose, so the same time zone names are also recognized by other software.
> * A time zone abbreviation, for example `PST`. Such a specification merely defines a particular offset from UTC, in contrast to full time zone names which can imply a set of daylight savings transition rules as well.
>   * You cannot set the configuration parameters `TimeZone` or `log_timezone` to a time zone abbreviation, but you can use abbreviations in date/time input values and with the `AT TIME ZONE` operator.
> * In addition to the timezone names and abbreviations, PostgreSQL will accept POSIX-style time zone specifications, as described in [Section B.5](https://www.postgresql.org/docs/current/datetime-posix-timezone-specs.html). This option is not normally preferable to using a named time zone, but it may be necessary if no suitable IANA time zone entry is available.
>   * The positive sign is used for zones *west* of Greenwich. (Note that this is the opposite of the ISO-8601 sign convention used elsewhere in PostgreSQL.)

Let's stick to the first option.
