### ISSUE TITLE
Discussion: allow specifying `parallelism` for mviews

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7346]
Right now, `parallelism` is a command line config passed to compute nodes at https://github.com/risingwavelabs/risingwave/blob/main/src/compute/src/lib.rs#L103

This parameter determines how many actors/fragments will be used for each query on this compute node.

A common use case is that depending on the structure of the query and the nature of the workload, we set different `parallelism` for each query.

**Comment by kwannoel** [comment]
By default it is set to `total_cpu_available`:

https://github.com/risingwavelabs/risingwave/blob/aff23a192c76e80b351802afeecaac417524a329/src/compute/src/lib.rs#L168-L170

**Comment by fuyufjh** [comment]
> By default it is set to `total_cpu_available`

Yes, by default it will use all the CPU cores in all compute nodes.

**Comment by fuyufjh** [comment]
+1 for manual settings.

My idea is to support a session variable or query hint to specify the (initial) total parallelism for the `CREATE MATERIALIZED VIEW` command.

**Comment by lmatz** [comment]
If session variable, we can do it right away,

`query hint` itself may deserve an RFC first?

**Comment by fuyufjh** [comment]
Acceptable to me. Session variable works well. 

By the way `query hint` is sometimes called `optimizer hint` which implies that it merely takes effect on optimizer's behaviors.

**Comment by lmatz** [comment]
close by #7359 ,
query hint can be a different story.
