### ISSUE TITLE
Allow jemalloc on macOS?

### ISSUE THREAD

**Issue by ice1000** [risingwavelabs/risingwave#7358]
> > The jemalloc issue only mentions the compilation problem on Windows. Should we also allow jemalloc on macOS?
> 
> Does tikv jemalloc support macOS? Because I'm not sure about that.

Yes. It works fine on macOS since the first day we add jemalloc.

_Originally posted by @yuhao-su in https://github.com/risingwavelabs/risingwave/pull/7305#issuecomment-1379959301_

**Comment by liurenjie1024** [comment]
In general I have not bias toward it, but there is one problem with jemalloc on macos(it reports incorrect memory usage):
https://github.com/risingwavelabs/risingwave/pull/7180#issuecomment-1371895621

So given that it may cause misunderstanding, I would prefer not to enable it.

**Comment by BugenZhao** [comment]
Enabled without `ctl`.
