### ISSUE TITLE
perf: sysbench: `select_random_ranges`

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#7365]
### Describe the bug

The throughput is `2.26 per sec` is unacceptable. There must be something wrong.

PS. We set `number_of_ranges = 1` to avoid the `OR` of multiple ranges, which is not supported yet.

```
Sysbench Tasks :  select_random_ranges

Running the test with following options:
Number of threads: 16
Report intermediate results every 1 second(s)
Initializing random number generator from current time
SQL statistics:
    queries performed:
        read:                            692
        write:                           0
        other:                           0
        total:                           692
    transactions:                        692    (2.26 per sec.)
    queries:                             692    (2.26 per sec.)
    ignored errors:                      0      (0.00 per sec.)
    reconnects:                          0      (0.00 per sec.)
Throughput:
    events/s (eps):                      2.2586
    time elapsed:                        306.3879s
    total number of events:              692
Latency (ms):
         min:                                 2049.90
         avg:                                 7014.37
         max:                                28196.25
         99th percentile:                    28352.44
         sum:                              4853945.24
Threads fairness:
    events (avg/stddev):           43.2500/0.43
    execution time (avg/stddev):   303.3716/1.92
```

### Additional context

- https://risingwave-labs.slack.com/archives/C048NM5LNKX/p1673553765126969
- https://risingwave-labs.slack.com/archives/C048NM5LNKX/p1672386034114609

**Comment by fuyufjh** [comment]
Feel free to reassign to someone else 🥰 Thank you!

**Comment by liurenjie1024** [comment]
I can't reproduce the low performance report when running `select_random_ranges` only, neither using kube-ben or standalone ec2. One possible reason is that in our ci the prepare step has ran for several times and inserted duplicated data into our table, and the iter size is much larger than normal:

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/2771941/216961312-7b7e4343-528a-4052-9b50-c57aaa2ae942.png">

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/2771941/216961452-048e580d-5028-425c-b4e9-4db2b345a076.png">

**Comment by liurenjie1024** [comment]
In several tests of new pipeline without inserting too much data, the data seems normal now, let's watch several days for perf report to see the result.
