### ISSUE TITLE
test: Support producing kafka records with timestamp.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#7372]
> > Generally LGTM, please add e2e tests to this.
> 
> There is a problem: how do we add e2e test for this... We can't infer the _rw_kafka_timestamp.

Yes, it's a little difficult. We can attach a timestamp to each kafka record, but as far as I know, no tool can support this. We need to use kafka producer api for this.

https://kafka.apache.org/23/javadoc/index.html?org/apache/kafka/clients/producer/KafkaProducer.html

_Originally posted by @liurenjie1024 in https://github.com/risingwavelabs/risingwave/issues/7275#issuecomment-1381475015_

**Comment by liurenjie1024** [comment]
cc @tabVersion

**Comment by ZENOTME** [comment]
I think we can do this in simulation.

In simulation, we read record from test_data file and send it to the kafka producer.
https://github.com/risingwavelabs/risingwave/blob/main/src/tests/simulation/src/kafka.rs

So we can 
1. modify the test_data file format to contain a timestamp for each record 
e.g.
```
origin test_data format:
{"v1":1,"v2":"name0"}

new test_data format:
{"v1":1,"v2":"name0"},timestamp:2022-01-01 12:00:00
```
2. parse and construct the record

**Comment by liurenjie1024** [comment]
> In simulation, we read record from test_data file and send it to the kafka producer.

After a second thought, I still prefer to do it in normal kafka producer, so that we can test more cases in normal e2e

**Comment by liurenjie1024** [comment]
After discussion, we don't need to verify the exact kafka timestamp, but use some functions, for example:
```
select _rw_kafka_timestamp > 10000  from xxx
```
cc @ZENOTME
