### ISSUE TITLE
Remove `impl Ord for OwnedRow`

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#7392]
OwnedRow can’t be compared without the order info, otherwise we may handle the `DESC` incorrectly like #7390 

The implementation is error-prone, so we should remove that.

For [SortBuffer](#7177), the watermark is always in the ascent order, we can introduce a wrapper type OwnedRowAscent for that case.

**Comment by xiangjinwu** [comment]
Just linking a previous discussion of `Ord` on row/datum: #4272
