### ISSUE TITLE
Compute node will restart frequently when running nexmark q16

### ISSUE THREAD

**Issue by huangjw806** [risingwavelabs/risingwave#7394]
### Describe the bug

Compute node will restart frequently when running nexmark q16.

### To Reproduce

image-tag:nightly-20230112

1. Cloud deploys a single-node risingwave cluster.
2. prepare 100million messages in kafka source.
3. run nexmark query16.

k8s instance cluster pod status:
<img width="709" alt="image" src="https://user-images.githubusercontent.com/29391315/212583960-ad545ac1-63e7-4538-b7da-f44724d98366.png">

grafrna page:
https://g-2927a1b4d9.grafana-workspace.us-east-1.amazonaws.com/d/EpkBw5W4k/risingwave-benchmark?orgId=1&var-namespace=test-q16-nightly-20230112&from=1673602845449&to=1673644077104

cn logs:

[cn.log](https://github.com/risingwavelabs/risingwave/files/10422054/cn.log)

**Comment by hzxa21** [comment]
Do we still have the compute node logs?

**Comment by huangjw806** [comment]
> Do we still have the compute node logs?

The link of cn node logs has been added.

**Comment by hzxa21** [comment]
![image](https://user-images.githubusercontent.com/5518566/212587033-463db285-2bad-4ac5-907b-bfb212484cf8.png)

cc @soundOfDestiny @richardchien seems to be related to the recent changes in agg `get_output`. Can you take a look?

**Comment by richardchien** [comment]
> ![image](https://user-images.githubusercontent.com/5518566/212587033-463db285-2bad-4ac5-907b-bfb212484cf8.png)
> 
> cc @soundOfDestiny @richardchien seems to be related to the recent changes in agg `get_output`. Can you take a look?

OK, I'll take a look.

**Comment by st1page** [comment]
@richardchien when the aggregator having a filter predicate, the count is wrong. :crying_cat_face:

**Comment by richardchien** [comment]
> @richardchien when the aggregator having a filter predicate, the count is wrong. 😿

Unfortunately you're right. I'll fix this by removing the row count maintained in-memory, the root of all evil, which causes inconsistency between real state tables and state caches.
