### ISSUE TITLE
Partition assignment wrong cause sudden performance drop

### ISSUE THREAD

**Issue by KeXiangWang** [risingwavelabs/risingwave#7407]
### Describe the bug

Ideally, each source actor should be assigned only one partition when we have `n` source actors and `n` partitions. For now, for unknown reasons, the partitions are not assigned as expected.

Here's an example from a daily performance test.
![image](https://user-images.githubusercontent.com/32863625/212611237-4f229644-9b83-43ec-a83b-72e75ebd98ad.png)
Each VM has 8 cores in the test setup, so the parallelisms of fragments should be 8 and there should be 8 actors.
The partition number of the Kafka source topic is also 8. But as shown in the figure, actor_68 gets 2 partitions, but actor_71 gets no partitions.

The result of this bug is that we can observe a sudden drop in the performance test.
Here's an example:
![image](https://user-images.githubusercontent.com/32863625/212611569-2d115ae7-bac8-4cd2-8882-fdc072323ce8.png)
The reason for this sudden drop is that the actor assigned with two partitions, the "lucy actor", will read from two partitions, the "lucy partitions". And the sum of reading speed from two partitions will be the same as other actors reading one partition. So the lucy partitions' consuming speed is slower than others. When other actors finish their partition, the lucy actor still needs to consume the left data. After that, only one core will be working and the overall throughput drop.

### To Reproduce

Just check our daily performance test grafana.

**Comment by huangjw806** [comment]
My kafaka source is set to 9, but only 8 partitions are seen in the grafana dashboard, and there is a source actor occupying two partitions.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/29391315/212614203-3545b8f0-0808-4b7b-b67d-38b4b8a2e6e8.png">

<img width="1853" alt="image" src="https://user-images.githubusercontent.com/29391315/212614552-c265993c-e4d1-4aab-8e5a-77a55b61af41.png">

**Comment by huangjw806** [comment]
In addition, I found that there is source actor 40 information in cn logs, but Prometheus does not collect its metrics

<img width="1860" alt="image" src="https://user-images.githubusercontent.com/29391315/212618332-21de2d2e-01c6-4ca4-bef9-183eaa851c61.png">

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/29391315/212618418-6ccdc818-35f1-4ded-8e91-692a134e7f94.png">

**Comment by KeXiangWang** [comment]
The bug locates in the [event generator repo](https://github.com/risingwavelabs/nexmark-bench/pull/17), outside this repo. The last partition(partition_8 in the example) contains nothing, so the actor assigned with this partition read nothing.
