### ISSUE TITLE
Discussion: support the statement/query level timeout in Risingwave DB

### ISSUE THREAD

**Issue by sumittal** [risingwavelabs/risingwave#7409]
### Describe the bug

As different queries can take different timeouts based on the data processing done by the query, today we do not support such an option that can set the query level or global level timeout.

In Postgres, there is the option to support the statement/query level timeout as mentioned below:

> set statement_timeout=1000

We can do the same using python API as:
https://stackoverflow.com/questions/19963954/set-transaction-query-timeout-in-psycopg2

Do we need a similar feature in Risingwave, to support the timeout feature?

cc: @BowenXiao1999 @lmatz @fuyufjh @zwang28 @renj

**Comment by lmatz** [comment]
Good point, my understanding is that this can be piggybacked into https://github.com/risingwavelabs/risingwave/issues/6488.

**Comment by sumittal** [comment]
Yes @lmatz

**Comment by BowenXiao1999** [comment]
For batch, I think this is not very useful:

1. User are expected to run small and fast query in batch.
2. They can ctrl-c the blocking session to end the query.

For streaming, I think we can also investigate Streaming System like Mz. I'm not sure whether create a MV and it takes long time and canceled by time out is a good experience. 🤔, and cancel a running streaming job is not simple.
