### ISSUE TITLE
support uint256 and related arithemetic operations

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7410]
### Is your feature request related to a problem? Please describe.

In many crypto cases, a commonly used type is `uint256` (`uint128` if want to save some space) to represent balance. This is supported by Solidity.

### Describe the solution you'd like

Support the type natively.

### Describe alternatives you've considered

Another alternative suggested by @xiangjinwu is 
store as `bytea/bigint[]`  and then use UDF to operate it.

This can be a workaround but cumbersome for users to use it.

### Additional context

https://docs.soliditylang.org/en/v0.8.17/types.html

**Comment by lmatz** [comment]
We notice that our current decimal crate only allows `28` scale, which falls short of supporting this case.

By even using `decimal`, I believe it would be less efficient than a dedicated `uint128`, `uint256` type, which is very common in crypto cases.

**Comment by jon-chuang** [comment]
I don't think it's a good idea to support more datatypes within the kernel like these which are application specific.

I think we can offer some evaluation in WASM kernel. Many crypto-specific functions including signature verification can be performed by these WASM kernels.

**Comment by jon-chuang** [comment]
Let's investigate an arbitrary precision library based on GMP https://docs.rs/rug/latest/rug/index.html to support higher precision decimals.

**Comment by xiangjinwu** [comment]
Arbitrary precision integers / decimals are far less efficient in this use case. Even if our `decimal` had enough precision, I would still suggest `bytea/bigint[]`+UDF, if no native support is available.

Reasons to avoid native support:
* Adding too many app/domain specific types inside kernel.
* We could reduce cumbersome for users by providing these UDF implementations ourselves separately.

Reasons to add native support:
* Efficiency. Even `bytea/bigint[]` are variable length.

**Comment by jon-chuang** [comment]
> Arbitrary precision integers / decimals are far less efficient in this use case.

Is the concern the arithmetic operation performance or the storage encoding? IMO this is not such a huge concern esp. if the user is writing an MV and not an ETL.

Personally, I think we should implement the arbitrary precision decimal anyway. If the performance is not good enough, we can think about a UDF e.g. WASM-based. But I think the ser/deser overhead could make it less worth it (unless we expose an interface to work with native risingwave types).

**Comment by jon-chuang** [comment]
https://github.com/risingwavelabs/risingwave/issues/239

**Comment by lmatz** [comment]
> Previous discussion on decimal libs: #239 Not sure why we ended up using `rust_decimal`

It was `rust_decimal` since day one, introduced it before the discussion.

**Comment by fuyufjh** [comment]
Need discussion @lmatz

**Comment by lmatz** [comment]
Right now, we want to support uint256 natively.

Whether introducing Decimal 128(dynamic or static)/Arbitrary-precision Decimal and replacing the current 96bit Decimal is an independent discussion

Let's find a good crate for uint256

**Comment by xiangjinwu** [comment]
Need to figure out how to represent this type in pgwire / pg-compatible client libraries ...

**Comment by lmatz** [comment]
> Need to figure out how to represent this type in pgwire / pg-compatible client libraries ...

Is it possible to pretend it is a decimal?

**Comment by xiangjinwu** [comment]
> Is it possible to pretend it is a decimal?

I think so. Just not sure whether it is what the use case really wants

**Comment by lmatz** [comment]
As it is decided that `uint256` and `int256` will be labeled as an experimental feature in our doc (meaning we don’t guarantee anything to the users),
I think the performance is less of a concern. Having a basic implementation is fine and we can improve it later.

**Comment by lmatz** [comment]
Let's consider this one done and move discussion to #9122
