### ISSUE TITLE
Discussion: allow users be aware of the progress of consuming upstream data

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7418]
For example, if a user `create materialized view` from Kafka or Kinesis, the user may want to know whether MV has already caught up with the upstream. Only roughly, because the upstream may keep generating new data.

One approach is by exposing the current offset/seq number to determine to users. Is it nice though?

**Comment by BugenZhao** [comment]
As the user is able to access the internal table of sources, I guess we can provide some utility functions to extract a human-readable offset from it. 🤤

**Comment by lmatz** [comment]
> As the user is able to access the internal table of sources, I guess we can provide some utility functions to extract a human-readable offset from it. 🤤

BTW, do you think it is also suitable for #7317 to store them in an internal table?
