### ISSUE TITLE
Show the dependency of a source, view, materialized view.

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7424]
### Is your feature request related to a problem? Please describe.

`drop XXX cascade` may not always be an option in a production environment, e.g. disabled on purpose for safety.

People may want to see the dependencies and drop them one by one.

`select matviewname, definition from pg_matviews;` can show the raw SQL and thus find out the dependency by SQL, but it's sort of cumbersome, and we want to show the dependency by inputting the one that others depends on and show the `others`.

### Describe the solution you'd like

even recursively

**Comment by BugenZhao** [comment]
Does the dashboard applicable in this case?

**Comment by jon-chuang** [comment]
is the desired syntax `show dependencies [for object (optional)]`?

```sql
> show dependencies for v;
name | type
-------------------------
t1  |  table
w  | materialized view

> show dependencies;
object | dependencies
------------------------------
v   | [t1, w] 
```

**Comment by lmatz** [comment]
> is the desired syntax `show dependencies [for object (optional)]`?
> 
> 
> 
> ```sql
> 
> > show dependencies for v;
> 
> name | type
> 
> -------------------------
> 
> t1  |  table
> 
> w  | materialized view
> 
> 
> 
> > show dependencies;
> 
> object | dependencies
> 
> ------------------------------
> 
> v   | [t1, w] 
> 
> ```

I think this already quite good for terminal, it seems hard to demonstrate a long lineage of dependency in terminal

**Comment by fuyufjh** [comment]
Now the Dashboard UI can show the dependency as lines. Closed now.
