### ISSUE TITLE
Better column name for internal table

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#7437]
### Is your feature request related to a problem? Please describe.

Currently our internal table column name could contain dots(`.`)which are hard to select by sql unless use CTE to redefine them. I suggest to use underline(`_`) to replace them.

```
select  *from __internal_v_5_hashjoinleft_1004;
 a.a1 | a.a2 |     a._row_id
------+------+--------------------
    1 |    1 | 237825984576622592
    1 |    1 | 237825984685588480

select a.a1 from __internal_v_5_hashjoinleft_1004;
ERROR:  QueryError: Item not found: Invalid column: a1
```

**Comment by jon-chuang** [comment]
Maybe we could use `$` as `_` can be annoying to tell how many to type with e.g. `_row_id`

**Comment by jon-chuang** [comment]
Yes, I also prefer `a_a1`, `a__row_id` to alternative like `a$a1`, `a$_row_id`.
