### ISSUE TITLE
frontend: Incorrect use of block_on() on plan_fragmenter 

### ISSUE THREAD

**Issue by ZENOTME** [risingwavelabs/risingwave#7439]
### Describe the bug

In plan_fragmenter, for getting the source information(it's a async interface), we use block_on.

https://github.com/risingwavelabs/risingwave/blob/733847fb953bc206086a0db4f2fbf9fae49d0a09/src/frontend/src/scheduler/plan_fragmenter.rs#L623

But that block_on will cause the woker in runtime blocked. In deterministic simulation, the runtime seems only run in a single thread, so that will cause whole program be blocked. For the block reason, we can refer: 
[https://github.com/tokio-rs/tokio-compat/issues/23#issuecomment-573232615](https://github.com/tokio-rs/tokio-compat/issues/23#issuecomment-573232615)

### Solution:
1. change BatchPlanFragmenter.split into a async. These solution seems impossible, because PlanRef is hard to satisfy Send,Sync trait. (BatchPlanFragmenter.split need to statisfy thread safety if we change it to a async function). Lots of thing need to modify if we take it...
2. delay get source information util we schedule the fragment. (The schedule work is async so we can directly use the async operation in it) https://github.com/risingwavelabs/risingwave/blob/733847fb953bc206086a0db4f2fbf9fae49d0a09/src/frontend/src/handler/query.rs#L150
   This solution seems also impossible. We need the source information to get the parallelism, parallelism needed for creating fragment.
   https://github.com/risingwavelabs/risingwave/blob/733847fb953bc206086a0db4f2fbf9fae49d0a09/src/frontend/src/scheduler/plan_fragmenter.rs#L595
3. **I think it's a available solution.** Including split information in SourceCatalog. And that we don't need async operation to get source information(including parallelism)
   For the timestamp limit, we can delay it util we schedule the fragment.
   https://github.com/risingwavelabs/risingwave/blob/733847fb953bc206086a0db4f2fbf9fae49d0a09/src/frontend/src/scheduler/plan_fragmenter.rs#L635

**Comment by ZENOTME** [comment]
@liurenjie1024  @tabVersion PTAL

**Comment by liurenjie1024** [comment]
Solution 3 sounds great, there is a problems to resolve for this approach: 
1. The partitions of source may change(e.g. user may add/remove partition of kafka), so we a job in meta to refresh this and send it to frontend. I think the refresh is already done?

**Comment by ZENOTME** [comment]
For solution 3, it has the problem: for some source like s3, source information may be appropriate to store in catalog.

So I'm going to investiagte can we split plan_fragmenter into two phase(sync and async phase) to solve this problem.

**Comment by ZENOTME** [comment]
Solved by #7581
