### ISSUE TITLE
Discussion: make checkpoint interval a per-query configuration

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7450]
A very simple stateless query (only with MV) can have much more frequent checkpointing while a complicated state-heavy query may only be able to have a larger interval. User may issues both types of query in the same cluster.

The presumption here is that more frequent checkpointing consumes more resources and/or leads to worse performance.

**Comment by lmatz** [comment]
barrier interval probably still a cluster-level config as I sort of feel this thing is quite important, i.e. trigger operator compute, output and evict. Shouldn't set by users most of time.

**Comment by BugenZhao** [comment]
This is actually [a standing dish](https://singularity-data.quip.com/Oaz4Ajo6Stu8/RFC-MView-granularity-Partial-Checkpoint-Based-on-MView-Epoch-ReplayWIP). The main problem is that, by providing different checkpoint intervals, the checkpoints must also be done on the partial graph, so different materialized views will have different freshness. This breaks the causal relationship for query results on different materialized views in the same session, which might not be what we want.

To prevent this from happening, we can forbid users to "connect"(join) two streaming jobs with different barrier intervals. Note that in SQL we generally can't do joins across "database"s. So in SQL semantics, only allowing different checkpoint intervals for different databases, or, making "barrier manager" database-specific LGTM.

**Comment by lmatz** [comment]
> This breaks the causal relationship for query results on different materialized views in the same session, which might not be what we want.

It seems consistency breaks iff the upstreams of different materialized views share the same source(s), 
which now leads me to think if `checkpoint interval` is a per-source configuration, 
if we insist to make it apply to a scope as smaller as possible, 
whether it is necessary is another story.

> So in SQL semantics, only allowing different checkpoint intervals for different databases, or, making "barrier manager" database-specific
I think users should be happy with this, +1. 

Not urgent, let me collect more feedback from user side
