### ISSUE TITLE
dashboard: add a page for async stack trace

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#7458]
Async stack trace is used to inspect "stuck" issues and help us to check what every actor is doing or why some actor is pending.

Previously we can only obtain this by `risectl` with CLI, which is not that friendly for developers to use. Like the "Thread Dump" of the Flink dashboard, we can also provide a similar feature in our dashboard.

<img width="1624" alt="Screenshot 2023-01-18 at 1 23 41 PM" src="https://user-images.githubusercontent.com/25862682/213091105-1ed99cae-2709-4a99-95a7-c9dff7a387df.png">

cc @lmatz

**Comment by liurenjie1024** [comment]
How about we integrate with tokio console? I think this is just a web console for tokio.

**Comment by BugenZhao** [comment]
BTW, I'm working on extracting this library and polishing the implementation for ease of use in my spare time these days. :)

https://github.com/risingwavelabs/await-tree

**Comment by BugenZhao** [comment]
Done in #8330.
