### ISSUE TITLE
index can accelerate aggregation

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7481]
### Is your feature request related to a problem? Please describe.

```
dev=> create table t1(v1 int, c1 varchar);
CREATE_TABLE
dev=> create index idx1 on t1(v1) include(v1);
CREATE_INDEX
dev=> explain select max(v1) from t1;
                  QUERY PLAN                  
----------------------------------------------
 BatchSimpleAgg { aggs: [max(idx1.v1)] }
 └─BatchExchange { order: [], dist: Single }
   └─BatchScan { table: idx1, columns: [v1] }
(3 rows)

dev=> 
```

Although hitting the index, it seems still reading all of the rows in the index.

**Comment by BugenZhao** [comment]
Good catch! It'll be better if we can rewrite it like

```
dev=> explain select max(v1) from (select v1 from t1 desc limit 1);
                    QUERY PLAN                    
--------------------------------------------------
 BatchSimpleAgg { aggs: [max(idx1.v1)] }
 └─BatchLimit { limit: 1, offset: 0 }
   └─BatchExchange { order: [], dist: Single }
     └─BatchLimit { limit: 1, offset: 0 }
       └─BatchScan { table: idx1, columns: [v1] }
(5 rows)
```

**Comment by Eurekaaw** [comment]
Seems like the primary key doesn't work either
``` SQL
dev=> create table t1 (v1 int primary key, v2 int);
CREATE_TABLE
dev=> explain select max(v1) from t1;
                 QUERY PLAN                  
---------------------------------------------
 BatchSimpleAgg { aggs: [max(t1.v1)] }
 └─BatchExchange { order: [], dist: Single }
   └─BatchScan { table: t1, columns: [v1] }
(3 rows)
```

**Comment by Eurekaaw** [comment]
After a bit investigation I find there are different reasons behind why primary key/index don't work here. 

For primary keys:  https://github.com/risingwavelabs/risingwave/blob/b7ebdd17e18d99f0aafe0bd39d25c4050c6d5752/src/frontend/src/optimizer/plan_node/logical_scan.rs#L585 Even with primary key set, `self.indexes()` and `new.indexes()` are empty, therefore `to_batch` won't even try to use the pk.

For indexes:
Seems the `IndexSelectionRule` always "estimate"s a larger index_scan cost than the table_scan cost, therefore always do not change the plan.

I'm not that familiar with this part and thus cannot make deeper investigations now. If anyone could mentor me on this issue I'll be happy to work on it :wink:.

**Comment by Eurekaaw** [comment]
However, it seems like index will **NOT** help in Postgres!
``` SQL
postgres=# create index idx1 on t(v1) include (v1);
CREATE INDEX
postgres=# explain select max(v1) from t;
                      QUERY PLAN                       
-------------------------------------------------------
 Aggregate  (cost=1.04..1.05 rows=1 width=4)
   ->  Seq Scan on t  (cost=0.00..1.03 rows=3 width=4)
(2 rows)
postgres=# explain select * from t order by v1;
                      QUERY PLAN                       
-------------------------------------------------------
 Sort  (cost=1.05..1.06 rows=3 width=8)
   Sort Key: v1
   ->  Seq Scan on t  (cost=0.00..1.03 rows=3 width=8)
(3 rows)
```
OTOH, primary key will help:
```SQL
postgres=# create table t1 (v1 int primary key, v2 int);
CREATE TABLE
postgres=# explain select max(v1) from t1;
                                            QUERY PLAN                                            
--------------------------------------------------------------------------------------------------
 Result  (cost=0.19..0.20 rows=1 width=4)
   InitPlan 1 (returns $0)
     ->  Limit  (cost=0.15..0.19 rows=1 width=4)
           ->  Index Only Scan Backward using t1_pkey on t1  (cost=0.15..83.51 rows=2249 width=4)
                 Index Cond: (v1 IS NOT NULL)
(5 rows)
postgres=# explain select * from t1 order by v1;
                              QUERY PLAN                              
----------------------------------------------------------------------
 Index Scan using t1_pkey on t1  (cost=0.15..78.06 rows=2260 width=8)
(1 row)
```

**Comment by Eurekaaw** [comment]
In current risingwave, index and primary will help in `order by` but not aggregation:
```SQL
dev=> create index idx1 on t(v1);
CREATE_INDEX
dev=> explain select max(v1) from t;
                 QUERY PLAN                  
---------------------------------------------
 BatchSimpleAgg { aggs: [max(t.v1)] }
 └─BatchExchange { order: [], dist: Single }
   └─BatchScan { table: t, columns: [v1] }
(3 rows)

dev=> explain select * from t order by v1;
                      QUERY PLAN                      
------------------------------------------------------
 BatchExchange { order: [idx1.v1 ASC], dist: Single }
 └─BatchScan { table: idx1, columns: [v1, v2] }
(2 rows)
```

**Comment by Eurekaaw** [comment]
Considering those observations I believe this issue needs further discussion from you experts 😉

**Comment by liurenjie1024** [comment]
Choosing best plan in this case involves access path selection, and it's not trivial to implement it in rbo.

**Comment by lmatz** [comment]
seems in this `max` case, it is always better to use the index in RW? correct me if I am wrong,
better:
1. only need to read a single `max` row instead of reading all the rows
2. only need to read a single column. If the index includes more columns(normal cases, not weird cases such as multiple duplicated columns), it is still better than scanning the original MV(all the columns)? Hard-coded rule seems able to handle it

**Comment by Eurekaaw** [comment]
True, I'm thinking that instead of modifying the current rules would it be better if we add another rule that always uses index for "some" aggregations (basically `min` and `max`)?

**Comment by Eurekaaw** [comment]
Seems like that for `min` or `max`, Postgres will rewrite it into a form of `select xx from xx order by xx limit 1`
(https://github.com/postgres/postgres/blob/c8e1ba736b2b9e8c98d37a5b77c4ed31baf94147/src/backend/optimizer/plan/planagg.c#L362)?

If we follow that way, https://github.com/risingwavelabs/risingwave/blob/3d9077b07a8318cc0d64b25b904f0e66e1bf5c86/src/frontend/src/optimizer/plan_node/logical_scan.rs#L613 will help us use the index.

**Comment by Eurekaaw** [comment]
Since it requires a better `TopN` implementation, I'd like to work on #7656 first 😉

**Comment by Eurekaaw** [comment]
Considering the `null` problem and the output schema's name problem I'm inclining to rewrite `select min(v1) from t;` as:
```SQL
dev=> explain select min (v1) from (select v1 from t order by v1 limit 1);
                      QUERY PLAN                       
-------------------------------------------------------
 BatchSimpleAgg { aggs: [max(t.v1)] }
 └─BatchLimit { limit: 1, offset: 0 }
   └─BatchExchange { order: [t.v1 ASC], dist: Single }
     └─BatchLimit { limit: 1, offset: 0 }
       └─BatchScan { table: t, columns: [v1] }
(5 rows)
```
where `v1` is the primary key. Do you have any concerns for it?

**Comment by chenzl25** [comment]
> where v1 is the primary key. Do you have any concerns for it?
I remember the primary key column can be null in our system.

**Comment by chenzl25** [comment]
Rewrite it as:
```sql
select min(v1) from (select v1 from t where v1 is not null order by v1 limit 1);
```

**Comment by fuyufjh** [comment]
Moved to next release.
