### ISSUE TITLE
Timezone offset not working in to_timestamp()

### ISSUE THREAD

**Issue by abhyuday26** [risingwavelabs/risingwave#7510]
### Describe the bug

Adding timezone offset in to_timestamp() function gives `ERROR:  QueryError: Expr error: Parse error: input contains invalid characters`

### To Reproduce

Any query with timezone offset will give this error
`SELECT to_timestamp('2021/12/30 14:52:49 +3:30', 'YYYY/MM/DD HH24:MI:SS TZH:TZM');`

**Comment by xiangjinwu** [comment]
```
dev=> SELECT to_timestamp('2021/12/30 14:52:49 +03:30', 'YYYY/MM/DD HH24:MI:SS TZH:TZM');
NOTICE:  Your session timezone is UTC. It was used in the interpretation of timestamps and dates in your query. If this is unintended, change your timezone to match that of your data's with `set timezone = [timezone]` or rewrite your query with an explicit timezone conversion, e.g. with `AT TIME ZONE`.

       to_timestamp        
---------------------------
 2021-12-30 11:22:49+00:00
(1 row)
```

We have supported `+03:30` but not `+3:30`. The `chrono` library seems provide no way to allow omitting leading zero.
