### ISSUE TITLE
command to fetch the risingwave version is not supported

### ISSUE THREAD

**Issue by sumittal** [risingwavelabs/risingwave#7512]
### Describe the bug

From kernel v0.1.16 onwards, we are supporting the operation to fetch the risingwave version and to do so we have introduced the rw_version() function, which I do not find in the release tenant created from v0.1.16.

### To Reproduce

```
 psql "postgres://dev:dev@rls-apse1-eks-a.risingwave-cloud.xyz:4566/dev?options=--tenant%3Drwc-6-releasetenant"
psql (14.6 (Homebrew), server 9.5.0)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_128_GCM_SHA256, bits: 128, compression: off)
Type "help" for help.

dev=> select rw_version();
ERROR:  QueryError: Feature is not yet implemented: unsupported function: "rw_version"
Tracking issue: https://github.com/risingwavelabs/risingwave/issues/112
dev=> SELECT version()
dev-> ;
            version
--------------------------------
 PostgreSQL 13.9-RW-0.2.0-alpha
(1 row)

dev=> select rw_version();
ERROR:  QueryError: Feature is not yet implemented: unsupported function: "rw_version"
Tracking issue: https://github.com/risingwavelabs/risingwave/issues/112
dev=>
```

### Expected behavior

It should print the v0.1.16 which is the risingwave version.

**Comment by tabVersion** [comment]
As the pr #7314 describes, we will display rw version together with pg version in version(), instead of introducing a new function rw_version().

The behavior is expected.

**Comment by sumittal** [comment]
@xxchan Sure, the current version should be 0.1.16, how to interpret **RW-0.2.0-alpha** ?

**Comment by xxchan** [comment]
> Please keep it as `0.2.0-alpha`. The reason is that it implies `main` branch is 1) the next version (`0.2.0`) and 2) still under development (`-alpha`)

_Originally posted by @fuyufjh in https://github.com/risingwavelabs/risingwave/pull/7314#discussion_r1067037134_


The version should be changed in the release brunch. e.g., 
<img width="370" alt="image" src="https://user-images.githubusercontent.com/37948597/214005923-27345e1a-b3bb-4f0a-82cd-d8774548c77b.png">

**Comment by sumittal** [comment]
Got it, thanks @xxchan
