### ISSUE TITLE
Longevity: show mv for nexmark queries(q0, q1, q2, q3) are getting timeout after 3 minutes

### ISSUE THREAD

**Issue by sushantgupta** [risingwavelabs/risingwave#7515]
### Describe the bug

In this longevity run the "select count(*) from <MV>" command is taking more then 3 minutes and because of that Longevity test got the exception.

https://buildkite.com/risingwave-test/longevity-test/builds/332#0185da72-d34a-491b-bf92-0dffe83d0f49

Here are the step:
1) create the mv( q0', 'q1', 'q2', 'q3)
2) run the show mv first iteration and it's works fine
3) show Mv for the same queries are getting timeout(180 seconds) in 2nd iteration

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/7961084/214069147-d84e5a5d-b94a-4ec3-88aa-a38612b2d893.png">

**Comment by fuyufjh** [comment]
Maybe caused by the heavy workload.
