### ISSUE TITLE
feat(service-params): cmdline params are unclear

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#7531]
originally posted by @CAJan93 in slack:
> I am a bit confused with the different parameters. Where do we list what all these params do?
```
docker run -it --pull=always risingwavelabs/risingwave:latest compute --help

        --client-address <CLIENT_ADDRESS>
            The address of the compute node's meta client.
            
            Optional, we will use listen_address if not specified.
```
> For e.g. the compute node I found above params that are related to our discussion. listen_address  was not listed and I am not sure what the difference between --client-address  and --meta-address  is.

Let's make it clearer what the params mean and unify them with meta params

**Comment by CAJan93** [comment]
Thank you very much for posting this issue @jon-chuang. Maybe we should also have a look at the parameters from the other components. The compactor e.g. lists 

```
        --state-store <STATE_STORE>
            [default: ]
```

I would not know what are valid values here.
