### ISSUE TITLE
feat(test): Change sim tests to match meta HA setup

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#7533]
### Is your feature request related to a problem? Please describe.

For the meta HA setup we are using `3etcd-3meta-1cn-1fe`. The sim tests should reflect this setup. 

- [x] Use multiple meta nodes
- [ ] Sim tests should use multiple ETCD nodes: The current simulation test only uses a single ETCD node (see [here](https://github.com/risingwavelabs/risingwave/blob/8d99f7aedf86d7a3a43eed075c163afee6d1298e/src/tests/simulation/src/cluster.rs#L111))

**Comment by yezizp2012** [comment]
Multi-meta sim test is already included in #7389 .

**Comment by CAJan93** [comment]
For the current client failover #7248 implementation we need a service to route requests to the different meta nodes. This is currently not supported by the sim tests. 

Also, the [deterministic-recovery-test](https://github.com/risingwavelabs/risingwave/blob/main/ci/scripts/deterministic-recovery-test.sh) is currently only testing a `ci-3cn-2fe` setup. IMHO we should switch to a setup with 3 meta nodes to ensure that our HA setup actually works.

**Comment by yezizp2012** [comment]
> For the current client failover #7248 implementation we need a service to route requests to the different meta nodes. This is currently not supported by the sim tests.
> 
> Also, the [deterministic-recovery-test](https://github.com/risingwavelabs/risingwave/blob/main/ci/scripts/deterministic-recovery-test.sh) is currently only testing a `ci-3cn-2fe` setup. IMHO we should switch to a setup with 3 meta nodes to ensure that our HA setup actually works.

After #7389 , the deterministic recovery test is already working on a setup of `ci-3cn-2fe-3meta`, you can find the meta node number config here: https://github.com/risingwavelabs/risingwave/blob/main/src/tests/simulation/src/main.rs#L55 . Maybe the comments in `deterministic-recovery-test.sh` need to be updated as well. Cc @shanicky

**Comment by CAJan93** [comment]
Okay. Thank you. Updated the comments here #7651

**Comment by fuyufjh** [comment]
@CAJan93 Shall we close this?

**Comment by yezizp2012** [comment]
I will close this issue, since we don't have any plans to support simulation (and recovery) test for multi-etcd nodes yet.
