### ISSUE TITLE
Bug(frontend): referring non-existing table triggers `segv` in playground mode

### ISSUE THREAD

**Issue by Eurekaaw** [risingwavelabs/risingwave#7534]
### Describe the bug
**UPDATE**
Seems like all reference to non-existing table results in `segv`, is it intended behavior?
Minimal example:
```
dev=> select * from t;
SSL SYSCALL error: EOF detected
The connection to the server was lost. Attempting reset: Failed.
```

As titled, example:
```
dev=> create table t (v1 int);
CREATE_TABLE
dev=> create index idx1 on t1(v1);
SSL SYSCALL error: EOF detected
The connection to the server was lost. Attempting reset: Failed.
```

Error message in bash:
```
/var/folders/ys/crdc7hkd6xl1450fdkzvwgfh0000gn/T/fsio_9YSFr84Yk0.sh: line 5: 66968 Segmentation fault: 11  RUST_BACKTRACE=1 RW_NODE=playground cargo run --bin risingwave --profile "${RISINGWAVE_BUILD_PROFILE}"
```

Interestingly the deployment mode doesn't have this issue.

### Expected behavior

```
dev=> create table t (v1 int);
CREATE_TABLE
dev=> create index idx1 on t1(v1);
ERROR:  QueryError: Catalog error: table not found: t1
```

**Comment by xxchan** [comment]
What's the git version and the system are you using? I can't reproduce it yet. This was a known issue https://github.com/risingwavelabs/risingwave/issues/6205 but didn't occur for a while and I can't reproduce it now.

**Comment by xxchan** [comment]
And what's your `/opt/homebrew/opt/llvm/bin/ld64.lld --version`?

**Comment by Eurekaaw** [comment]
I've tried `cargo clean` and make again but this issue persists.
My current git log is pretty updated 
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/52417396/214614031-61f72846-9008-44cd-a571-bcebd3714cc1.png">

```
/opt/homebrew/opt/llvm/bin/ld64.lld --version
Homebrew LLD 15.0.7
```

**Comment by Eurekaaw** [comment]
The current version of `upstream/main` does not have this issue, which is really interesting given that a similar version did.
