### ISSUE TITLE
feat(frontend): `ExprRewritable` trait for `PlanNode`

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#7538]
Rewrites all expressions in a given plan tree.

For certain StreamPlanNodes and BatchPlanNodes, `rewrite_exprs` can simply reuse the `rewrite_exprs` implemented for LogicalPlanNodes or generic nodes.

We will use this to:
1. Inline session timezone
2. Eval const 

Additionally, we could:
1. Use exprewriter in non-rewrite mode to traverse all exprs and catch forbidden values. (e.g. untransformed `now()` in stream plan)

for all `ExprImpl`s at the end of the optimization phase.

Originally described: https://github.com/risingwavelabs/risingwave/issues/7175#issuecomment-1376799576

---

Plan:
1. Rewrite generic nodes, Rewrite Logical plan nodes (https://github.com/risingwavelabs/risingwave/pull/7542)
3. Rewrite Batch plan nodes (https://github.com/risingwavelabs/risingwave/pull/7541)
4. Rewrite Stream plan nodes (https://github.com/risingwavelabs/risingwave/pull/7757)
5. Add session timezone rewriter, Enable const_eval rewriter, enable `now.slt.part` (https://github.com/risingwavelabs/risingwave/pull/7761)

**Comment by xxchan** [comment]
I hoped to have similar things when I was implementing https://github.com/risingwavelabs/risingwave/blob/main/src/frontend/src/optimizer/plan_visitor/input_ref_validator.rs 🤔
