### ISSUE TITLE
dynamic filter: inconsistent delete since #7374

### ISSUE THREAD

**Issue by soundOfDestiny** [risingwavelabs/risingwave#7543]
### Describe the bug

SQL:
```
create table latest_cart(id int, created_at timestamp, updated_at timestamp);
create materialized view test as select id, created_at, updated_at from latest_cart where created_at > now() - interval '1 minute';
```
will cause error since #7374:
```
2023-01-26T10:44:07.581914Z ERROR risingwave_stream::task::stream_manager: actor exit actor=18 error=Executor error: Inconsistent Delete - current: Some(Some(Int64(1674729787580000))), delete: [Some(Int64(1674729786581000))]
```

### To Reproduce

SQL:
```
create table latest_cart(id int, created_at timestamp, updated_at timestamp);
create materialized view test as select id, created_at, updated_at from latest_cart where created_at > now() - interval '1 minute';
```

### Additional context

#7374 makes `now()` operator not single.

**Comment by jon-chuang** [comment]
> https://github.com/risingwavelabs/risingwave/pull/7374 makes now() operator not single.
This is not accurate. The now operator was not single as fragmenter requires manually specifying that fragment is_singleton.

This was not caught, and previously, we would have spawned a now() operator for as many actors as there are downstream.
