### ISSUE TITLE
Create table is taking too much time(3+ minutes)

### ISSUE THREAD

**Issue by sumittal** [risingwavelabs/risingwave#7548]
### Describe the bug

Tried to create the table having the column type of timestamp:

dev=> create table t(v1 int, t1 timestamp);

The cli is stuck and create table took around 3-5 minutes to create the table. Below is the tenant details:

>  psql "postgres://dev:dev@rls-apse1-eks-a.risingwave-cloud.xyz:4566/dev?options=--tenant%3Drwc-6-releasetenant"

**Comment by fuyufjh** [comment]
Failed to reproduce locally. Please provide more context.

**Comment by sumittal** [comment]
Unfortunately, the tenant has gone:

> $ psql "postgres://dev:dev@rls-apse1-eks-a.risingwave-cloud.xyz:4566/dev?options=--tenant%3Drwc-6-releasetenant"
psql: error: connection to server at "rls-apse1-eks-a.risingwave-cloud.xyz" (52.77.187.219), port 4566 failed: PANIC:  instance is currently unavailable. request id: a567a887-8154-4ecc-97a2-d259c1d12a66
connection to server at "rls-apse1-eks-a.risingwave-cloud.xyz" (52.77.187.219), port 4566 failed: PANIC:  instance is currently unavailable. request id: a0e23550-9494-4756-bb2d-2637df673115

Did you try on the above tenant only? @fuyufjh 
There is not much to explain as the create table with having a column on type timestamp was taking a long time.

**Comment by sumittal** [comment]
I am closing the issue as not seeing the issue with a new tenant.

**Comment by fuyufjh** [comment]
> Did you try on the above tenant only? @fuyufjh

I also tried on local deployment, and the table was created immediately. Obviously, the problem was somewhere deeper, not the creating table command.

**Comment by sumittal** [comment]
As the tenant itself has gone, so it will not reproduce now, I will reopen the issue if face again.

**Comment by sumittal** [comment]
By the time I would have collected the pods logs, tenant was down and not there.
