### ISSUE TITLE
Queries failed for the derived expr's output column names

### ISSUE THREAD

**Issue by sumittal** [risingwavelabs/risingwave#7549]
### Describe the bug

Getting the below error for the expr queries:

> dev=> create table testme as select 1;
ERROR:  QueryError: Bind error: An alias must be specified for an expression

> dev=> create table testme(v1) as select 1;
ERROR:  QueryError: Bind error: An alias must be specified for an expression

Tenant details:
` psql "postgres://dev:dev@rls-apse1-eks-a.risingwave-cloud.xyz:4566/dev?options=--tenant%3Drwc-6-releasetenant"`

Version: v0.1.16

**Comment by st1page** [comment]
IIRC, this syntax is not allowed to use in production and is only used for tests. https://github.com/risingwavelabs/risingwave/issues/6569

**Comment by xxchan** [comment]
> IIRC, this syntax is not allowed to use in production and is only used for tests

How could we ban it in production? 🤔 `#[cfg(debug_assertions)]`?

**Comment by fuyufjh** [comment]
Is it completed? @liurenjie1024 @ZENOTME

**Comment by ZENOTME** [comment]
Yes.

> > IIRC, this syntax is not allowed to use in production and is only used for tests
> 
> How could we ban it in production? 🤔 `#[cfg(debug_assertions)]`?

I think this can belong to new issue.
