### ISSUE TITLE
discussion: do we really need `client_addr`?

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#7560]
The `client_addr` is more like an identifier in the cluster, and the only use case I found for `client_addr` is to decide whether an exchange channel should be a remote exchange. This can actually be done by comparing the worker node ID.

https://github.com/risingwavelabs/risingwave/blob/4731c1b00a4a54b5bde01aba1c0a04bbf83bc7a6/src/stream/src/executor/exchange/input.rs#L248

cc @jon-chuang @Gun9niR

**Comment by BugenZhao** [comment]
Seems also applicable for the frontend client address. It's only used for registering.

**Comment by Gun9niR** [comment]
Seems also applicable for compute node and compactor 🤣

**Comment by jon-chuang** [comment]
Yes, the nodes still need to identify themselves. Hence meta will store the contact_info of each worker node. Is this used?

**Comment by BugenZhao** [comment]
> Yes, the nodes still need to identify themselves. Hence meta will store the contact_info of each worker node. Is this used?

I've checked the references and found that we're using this address for (batch) task scheduling and exchange service. However this seems incorrect, since we start all services on the `listen_addr`.

**Comment by BugenZhao** [comment]
After discussions with @arkbriar, the listen address will be like `0.0.0.0:5688`, and the "client address" will be like `compute-node-0:5688` which is the only way that it can be accessed by other worker nodes in the cluster. So it's necessary to have different configurations for them, and the problem is the confusing `client_addr` naming. Agree with @jon-chuang to rename it to `contact_addr`.

**Comment by arkbriar** [comment]
I'd prefer `advertise-address` as a commonly adopted name. Anyways, be cautious that it would be a breaking change for deployment tools.

**Comment by jon-chuang** [comment]
Let's go with advertise-address then, I've seen it elsewhere before too, and it's clear what the meaning is.
