### ISSUE TITLE
test: end-to-end sink test is flaky

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#7563]
Discussion thread [here](https://risingwave-labs.slack.com/archives/C03C8VCQ1EZ/p1673937765473319). Occurrences:
- https://buildkite.com/risingwavelabs/pull-request/builds/16360#0185f798-e00a-4a90-8b2d-ac2e9f95f484
- https://buildkite.com/risingwavelabs/pull-request/builds/15902#0185be6a-a850-43ad-9984-c739898b2c3b

It might be possibly caused by the connector node not fully booting up when the compute node tries to connect it. We need to wait for the port to be ready.

**Comment by BugenZhao** [comment]
Are we going to fix it in #7452? cc @KivenChen @tabVersion

**Comment by fuyufjh** [comment]
Need to be solved for sure.

**Comment by fuyufjh** [comment]
Kiv has ended his internship so assigned to @tabVersion . Feel free to reassign

**Comment by fuyufjh** [comment]
Only 1-second wait? Shall we increase it?

https://github.com/risingwavelabs/risingwave/blob/d4193889af95cfbceeb5232f60ef96134fd567da/ci/scripts/e2e-sink-test.sh#L65

**Comment by tabVersion** [comment]
try to fix in #7452 , leave this issue open for observation.
