### ISSUE TITLE
Export meta cluster information to grafana dashboard

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#7576]
Display all meta nodes in cluster dashboard in grafana.

**Comment by CAJan93** [comment]
Which information would you like to import? Just how many meta nodes there are or also other infos?

**Comment by yezizp2012** [comment]
> To clarify: This issue handles the issues filed in #6448
> 
> Is my assumption correct? 😁 ?

Yes, exactly.

**Comment by yezizp2012** [comment]
> Could you provide more details here how we are gonna "import" metadata to grafana?

For HA, showing all meta nodes and their roles is already enough.
