### ISSUE TITLE
Newly created user doesn't have CONNECT privilege

### ISSUE THREAD

**Issue by conghuhu** [risingwavelabs/risingwave#7596]
### Describe the bug

New created user can not connect to risingwave.
version: latest

### To Reproduce

![image](https://user-images.githubusercontent.com/56248584/215454723-05a53212-a6a8-4dff-88fd-50392d27ce9a.png)

### Expected behavior

conneted successfully

**Comment by conghuhu** [comment]
> The user name you specified was cgq while the one in your database address was "cgqq".

![image](https://user-images.githubusercontent.com/56248584/215458230-710a3ec9-ac91-4623-a185-2a2f24f4656a.png)

**Comment by xxchan** [comment]
It should be a bug.

https://www.postgresql.org/docs/current/ddl-priv.html

> PostgreSQL grants privileges on some types of objects to PUBLIC by default when the objects are created. No privileges are granted to PUBLIC by default on tables, table columns, sequences, foreign data wrappers, foreign servers, large objects, schemas, tablespaces, or configuration parameters. For other types of objects, the default privileges granted to PUBLIC are as follows: CONNECT and TEMPORARY (create temporary tables) privileges for databases;
