### ISSUE TITLE
storage: add bloom filter for immutable memtables

### ISSUE THREAD

**Issue by soundOfDestiny** [risingwavelabs/risingwave#7608]
### Is your feature request related to a problem? Please describe.

as title

**Comment by soundOfDestiny** [comment]
btw, I once thought that we might have one bloom filter for all imm memtables. However, when one of them is replaced in `ReadVersion`, it will become hard to maintain.

**Comment by CAJan93** [comment]
There is a discussion in #7406 to replace bloom filters with RIBBON filters. @Little-Wallace does it make sense to consider RIBBON filters here as well? If the memtable is immutable a XOR-based filter may be feasible, right?
