### ISSUE TITLE
feat: Support auto configuration of system parameters

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#7610]
### Is your feature request related to a problem? Please describe.

The configuration of several parameters can be inferred from available system resources.
We can use the setting `auto` to indicate this.

Currently their defaults are fixed:
https://github.com/risingwavelabs/risingwave/blob/c52e5505e1d871fbe6646176a27921c7cbdd6435/src/common/src/config.rs#L451-L453

I think it makes sense to make this the default setting as well.

### Describe the solution you'd like

Parameters:
- block_cache_capacity_mb
- meta_cache_capacity_mb
- compactor_memory_limit_mb
- shared_buffer_capacity_mb

### Additional context

Proposed by @fuyufjh originally:
- https://github.com/risingwavelabs/rfcs/pull/34#discussion_r1069061515
- https://www.notion.so/Risingwave-performance-and-cost-of-nexmark-885b505c3c084cbfb96cb160cacc7b3c?d=ea895cb0a1ef4de8b39dab5731238815#948f0997931e43d1ae6d4d0444200591
- https://risingwave-labs.slack.com/archives/C03N0B08J15/p1674719449978439?thread_ts=1674627227.771579&cid=C03N0B08J15

**Comment by fuyufjh** [comment]
cc. @hzxa21 @Little-Wallace @zwang28

**Comment by zwang28** [comment]
> block_cache_capacity_mb
> meta_cache_capacity_mb
> compactor_memory_limit_mb
> shared_buffer_capacity_mb

Note that it will result in several auto rules. Because workers may treat these configs differently, even they are of the same worker type. For example, 
- compactor node's SstableStore will [ignore block_cache_capacity_mb](https://github.com/risingwavelabs/risingwave/blob/db4f27e56a09d234de074a3acbb43bfea70825af/src/storage/compactor/src/server.rs#L95).
- compute node may or may not consider compactor_memory_limit_mb, depend on whether [embedded compactor](https://github.com/risingwavelabs/risingwave/blob/db4f27e56a09d234de074a3acbb43bfea70825af/src/compute/src/server.rs#L151) is used.

**Comment by hzxa21** [comment]
Good idea! The policy can be as simple as reserving some percentage of the available memory for storage. For example, if storage can use 4G memory, the auto config policy can be setting block_cache_compacity_mb to be 50% * 4G = 2048M.

One more annoying thing to consider for the policy: if only a subset of the configs are set to auto, what should the behavior be? Assume we have reserved 3GB memory for storage and the policy is block_cache_capacity_mb : meta_cache_capacity_mb : shared_buffer_capacity_mb = 1 : 1 : 1. Now user sets `block_cache_capacity_mb` to be 2048MB and leaves other configs auto. 

We have several options:
1. Ban it. Storage memory related configs should be set explicitly or leave to be auto together.
2. Set auto configs proportionally. In the above example, meta_cache_capacity_mb and shared_buffer_capacity_mb will all be set to 2048MB and the reserved memory for storage becomes 6GB.
3. Igore the explicitly set configs and set auto configs proportionally. In the above example, meta_cache_capacity_mb and shared_buffer_capacity_mb will all be set to 500MB and the reserved memory for storage remains 3GB.

I prefer 1 > 3 > 2.

**Comment by Gun9niR** [comment]
> I prefer 1 > 4 > 3 > 2.

1 is also my favorite option

**Comment by kwannoel** [comment]
Do we have auto setting for memory now? Seems not?

**Comment by fuyufjh** [comment]
> Do we have auto setting for memory now? Seems not?

We have. Now the CN will automatically calculate memory for each module according to `total_memory_bytes`. You can see this in CN's logs, for example,

```
Memory outline: 
> total_memory: 13.00 GiB
>     storage_memory: 4.68 GiB
>         block_cache_capacity: 1.40 GiB
>         meta_cache_capacity: 1.64 GiB
>         shared_buffer_capacity: 1.40 GiB
>         file_cache_total_buffer_capacity: 239.00 MiB
>     compute_memory: 7.02 GiB
>     reserved_memory: 1.30 GiB
```
