### ISSUE TITLE
Release `risectl` and build binaries

### ISSUE THREAD

**Issue by arkbriar** [risingwavelabs/risingwave#7617]
### Is your feature request related to a problem? Please describe.

`risectl` should be a part of the RisingWave releases.

### Describe the solution you'd like

Build and upload it to the release assets when a new release is created.

**Comment by fuyufjh** [comment]
So I guess we can close this issue?

**Comment by arkbriar** [comment]
> IIRC, we upload the all-in-one binary and one can launch risectl with ./risingwave ctl.

Can we build a standalone binary for the `risectl`? IMO, the `risingwave` binary is too large to be a client. But I'm glad to know that it's embedded in the `risingwave` binary.

**Comment by lmatz** [comment]
> > IIRC, we upload the all-in-one binary and one can launch risectl with ./risingwave ctl.
> 
> Can we build a standalone binary for the `risectl`? IMO, the `risingwave` binary is too large to be a client. But I'm glad to know that it's embedded in the `risingwave` binary.

I guess the motivation is that Cloud wants to expose `risectl` to users directly somewhere, without the user logging into the pod and using `risectl` by themselves?

**Comment by arkbriar** [comment]
> I guess the motivation is that Cloud wants to expose risectl to users directly somewhere, without the user logging into the pod and using risectl by themselves?

One of the use cases, exactly. But I believe it would be better to let also the open-source users use the `risectl` without downloading a full risingwave binary. The `risectl` serves as the backup and recovery tool, which is commonly used by ops engineers.

**Comment by BugenZhao** [comment]
> But I believe it would be better to let also the open-source users use the `risectl` without downloading a full risingwave binary.

`risectl` actually depends on the code of almost all components in RisingWave, it won't be much smaller than the all-in-one binary.

**Comment by arkbriar** [comment]
> > But I believe it would be better to let also the open-source users use the `risectl` without downloading a full risingwave binary.
> 
> `risectl` actually depends on the code of almost all components in RisingWave, it won't be much smaller than the all-in-one binary.

What's the current size under the release build?

**Comment by xxchan** [comment]
> What's the current size under the release build?

🤔

```
-rwxr-xr-x     1 xxchan  staff    53M Feb  1 13:05 risectl
-rwxr-xr-x     1 xxchan  staff   209M Feb  1 13:06 risingwave
```

**Comment by fuyufjh** [comment]
Since `risectl`'s size is acceptable, I think it's not a bad idea to release it to users in our Releases page.

(but for Docker image, since it's already contained in `risingwave`'s subcommand, no need to do any changes.)

**Comment by fuyufjh** [comment]
So I guess we can close this issue?

**Comment by arkbriar** [comment]
> So I guess we can close this issue?
Yes, as long as we promise to build and release it in the next release.

**Comment by huangjw806** [comment]
I have add risectl asset in v0.1.17 release.
