### ISSUE TITLE
simulation test: support simulate worker node heartbeat timeout

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#7626]
### Is your feature request related to a problem? Please describe.

The simulator already supports [kill_node](https://github.com/risingwavelabs/risingwave/blob/db4f27e56a09d234de074a3acbb43bfea70825af/src/tests/simulation/src/cluster.rs#L367), but it always restarts the worker immediately before worker heartbeat timeout, thus the worker rejoins [with the original identify](https://github.com/risingwavelabs/risingwave/blob/db4f27e56a09d234de074a3acbb43bfea70825af/src/meta/src/manager/cluster.rs#L136)(not expired). That is, we haven't covered cases like this: 
1. The worker crashes.
2. Then the worker is removed as expired from cluster due to heartbeat timeout.
3. Then the worker rejoins the cluster and is recognized [with a new identify](https://github.com/risingwavelabs/risingwave/blob/db4f27e56a09d234de074a3acbb43bfea70825af/src/meta/src/manager/cluster.rs#L137).

This kind of cases covers [considerable code logic](https://github.com/risingwavelabs/risingwave/blob/db4f27e56a09d234de074a3acbb43bfea70825af/src/meta/src/barrier/recovery.rs#L129).

**Comment by zwang28** [comment]
@wangrunji0408 What do you think?

**Comment by wangrunji0408** [comment]
Thanks for pointing it out. That's definitely an important case we need to cover. At present the simulated network delay is always around a small number (~10ms), which is not long enough to cover the above case. I will manually introduce a long delay to resolve this issue.

I'm also working on introducing [buggify](https://transactional.blog/simulation/buggify) to madsim. After that, each operation will have a small chance (maybe 25%) to have a long delay. It will also allow developers to intentionally introduce failures in the simulation. Hope this tool can help us better cover edge cases.

**Comment by wangrunji0408** [comment]
BTW, how long is the heartbeat timeout?

**Comment by Gun9niR** [comment]
By default, it is 10 mins. It's set in the configuration file's `[server]` section - `max_heartbeat_interval_secs`.

**Comment by wangrunji0408** [comment]
Got it. But it still seems a bit long. We could make it shorter (like 30s) in our tests in order to make it happen more easily.
