### ISSUE TITLE
feature: support aws private link in kernel

### ISSUE THREAD

**Issue by tabVersion** [risingwavelabs/risingwave#7643]
part of https://github.com/risingwavelabs/rfcs/pull/35

in this proposal we will configure aws private link settings in sql without introducing any entity in rw

ref: https://github.com/risingwavelabs/rfcs/pull/35#issuecomment-1408147761

```sql
create source/sink {{ name }} ... with (
  connector = 'kafka',
  properties.bootstrap.server = 'ip1:port1,ip2:port2',
  private.links = '[{"service_name": "xxx", "availability zones: ["a", "b", "c"]", "port": 8080}, {...}, {...}]',
  ...
)
```

**Comment by tabVersion** [comment]
> Could you provide a sample SQL that connects to a specific aws private link?

a private link has three options to configure (`service_name`, `availability zones`, and `port`). We did not reach a consensus for creating AWS_Private_Link, so we configure the link together with source/sink

**Comment by StrikeW** [comment]
Roadmap:
- Setup a VPC and create an ec2 instance in it
- Try to use the modified version of `rust-rdkafka` to write a demo program to consume MSK events from another VPC
- Implement the private link support in kernel

If you have any more input and suggestions, feel free to leave your comments. @mikechesterwang @Nebulazhang

**Comment by tabVersion** [comment]
> > the modified version of rust-rdkafka
> 
> 
> 
> What is the modification we need to make to the Kafka client?

Provide a callback func interface to modify the internal ip (in another vpc) to a private link compatible format

**Comment by tabVersion** [comment]
consider we are going to use multiple cloud providers, suggest add provider's info when creating a private link

```
private.links = '{
"provider": "aws/gcp/azure", 
"info": [{"service_name": "xxx", "availability zones: ["a", "b", "c"]", "port": 8080}, {...}, {...}]
}',
```
