### ISSUE TITLE
bug: meta does not stop as expected

### ISSUE THREAD

**Issue by tabVersion** [risingwavelabs/risingwave#7654]
### Describe the bug

![image](https://user-images.githubusercontent.com/14017336/216076767-96d09172-dd0c-421d-bc7d-c4e4018a48ac.png)

cargo make playground

after pressing ctrl_c, meta continues printing log

**Comment by wangrunji0408** [comment]
> Do you know why madsim cannot detect this type of bug? @wangrunji0408

Madsim doesn't simulate Ctrl+C. Instead, it kills nodes by dropping tasks.

**Comment by yezizp2012** [comment]
I'm not sure if it's because the service discovery in the meta client don't support graceful shutdown. Cc @shanicky please help to confirm and fix it if so. 🙏

**Comment by wangrunji0408** [comment]
Looks like we need to add graceful shutdown to the simulation test. 👀

**Comment by yezizp2012** [comment]
> Looks like we need to add graceful shutdown to the simulation test. 👀

🤔 I don't see any essential needs to support graceful shutdown simulation in madsim.
