### ISSUE TITLE
bug: meta doesn't unpin epoch when creating MV fails

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#7657]
### Describe the bug

Meta node will [pin an epoch](https://github.com/risingwavelabs/risingwave/blob/9b9e0921f8d5de2c0cd504985200b476c5a101cf/src/meta/src/barrier/command.rs#L499) for MV creation. But it doesn't unpin it if MV creation fails.
This epoch remains the min_pin_epoch and prevent storage from GC stale KVs.

Found in longevity-20230201-170952
<img width="731" alt="Screen Shot 2023-02-02 at 11 13 42 AM" src="https://user-images.githubusercontent.com/70626450/216222689-2c4c48db-0952-460c-9994-eaf21fe60916.png">

**Comment by hzxa21** [comment]
related to #5606?
