### ISSUE TITLE
refactor: await a cancelled task when necessary

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#7663]
Sometimes we call JoinHandle::abort but not await on it. But it may not match the author's original intention, ~~for example [here](https://github.com/risingwavelabs/risingwave/blob/e7fe72b0dda9379cd42e6e412bbf5a37c69ca9c4/src/stream/src/task/stream_manager.rs#L784) the aborted task actually is not guaranteed to be stopped without await on it.~~

It has caused [correctness issues](https://github.com/risingwavelabs/risingwave/pull/7263).

We can provide a common use abort and await interface for JoinHandle.

**Comment by fuyufjh** [comment]
Any ToDo items?

**Comment by zwang28** [comment]
> Any ToDo items?

Will review all usage of `JoinHandle::abort` and check if await is required.

**Comment by zwang28** [comment]
Reviewed these callsites and no action is required.
https://github.com/risingwavelabs/risingwave/blob/6a61858b2ea335b9c65a6e7785a965405d592af8/src/stream/src/task/stream_manager.rs#L787
https://github.com/risingwavelabs/risingwave/blob/6a61858b2ea335b9c65a6e7785a965405d592af8/src/meta/src/stream/source_manager.rs#L614
https://github.com/risingwavelabs/risingwave/blob/0de2ccadf76c3f873046e303e8ea39a83d8901b3/src/meta/src/rpc/election_client.rs#L190
