### ISSUE TITLE
Incorrect cast when specifying columns

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#7691]
### Describe the bug

```SQL 
create table t (v1 real, v2 int, v3 varchar);
insert into t (v2, v1, v3) values (1, 2, 'a'), (3, 4, 'b');
```

Results in 

```
thread 'risingwave-batch-tasks' panicked at 'table source write chunk schema check failed: "column 0 should be Some(\"Float32\"), while stream chunk gives Some(\"Int32\")"', src/source/src/table.rs:102:14
```

I guess that we run into this, because we first call `cast_on_insert` ([here](https://github.com/risingwavelabs/risingwave/blob/20bdb72d5ff015d736fb582918cd551563139273/src/frontend/src/binder/insert.rs#L140) or in [bind_values here](https://github.com/risingwavelabs/risingwave/blob/20bdb72d5ff015d736fb582918cd551563139273/src/frontend/src/binder/insert.rs#L121)) and afterwords resolve where to insert the value ([here](https://github.com/risingwavelabs/risingwave/blob/20bdb72d5ff015d736fb582918cd551563139273/src/frontend/src/binder/insert.rs#L153)). 

I believe that we should also provide more tests which test this issue. 

### Additional context

I am currently on `main`, commit `2eea46208210d95c1975b7ea61f37674b6d2e832`

**Comment by CAJan93** [comment]
Will keep this as a low priority issue on my TODO list for now. Please let me know if you think this is more urgent.

**Comment by kwannoel** [comment]
Btw if you're interested, there's https://github.com/risingwavelabs/risingwave/issues/3844, I think it can help to cover this case.
