### ISSUE TITLE
batch task memory leak

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#7696]
### Describe the bug

I ran the following script:

```python
import psycopg2

conn = psycopg2.connect("dbname=dev user=root port=4566 host=localhost")
cur = conn.cursor()
cur.execute(
    "drop table if exists t ;create table t (x int);"
)

for i in range(1000000):
    cur.execute(f"INSERT INTO t values ({i});")

```

And observed memory usage keep increasing. It seems the memory used by batch task is not freed. Is this normal? 

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/37948597/216714313-3c3298d2-9fd0-41de-9f82-e50efb2a84cd.png">

### Additional context

Find together with https://github.com/risingwavelabs/risingwave/issues/7694, but they seem to be different issues?

**Comment by BugenZhao** [comment]
If it's caused by the spawned task not being freed, then it's reasonable to happen along with #7694. Since the task is not freed, then
- the variables `move`d to the `async` block is not freed, so we get the backtrace of this issue,
- the guard for memory stats is not freed, so we get the backtrace of this #7694.

**Comment by xxchan** [comment]
Here's another test and I'm not sure how to interpret it 🥵 😇

Inserted 5000000 rows in the first hill. After a while the memory usage droped to 480M. Then inserted another 5000000 rows. This time the memory usage didn't drop. Then inserted again -- OOM

<img width="1447" alt="image" src="https://user-images.githubusercontent.com/37948597/217058869-6715c021-8a1d-4560-9c43-f767ae30dee5.png">


I tested using the following script: 


<details>

```sql
create table t (id int primary key,uid int,v1 int,v2 float,s1 varchar,s2 varchar,update_time timestamp);
```

`(c1,c2) = (0, 5000000)` for the first time and `(5000000, 10000000)` for the second time.

```python
import psycopg2
import random
import datetime

class InsertValue(object):
    def __init__(self):
        self.conn = psycopg2.connect(
            database="dev", user="root", host="127.0.0.1", port=4566
        )

    def parse(self, c1, c2):
        cursor = self.conn.cursor()
        for step in range(c1, c2, 10):
            li = []
            for j in range(step, step + 10):
                v2 = random.uniform(1, 1000)
                update_time = datetime.datetime.now()
                vv = """({},{},{},{},'test1','test2','{}')""".format(
                    j, j, j, v2, update_time
                )
                li.append(vv)
            v = ",".join(li)
            sql = """insert into t values {};""".format(v)
            cursor.execute(sql)
        self.conn.commit()
        cursor.close()

    def run(self, c1, c2):
        self.parse(c1, c2)
        self.conn.close()


if __name__ == "__main__":
    iv = InsertValue()
    iv.run(0, 5000000)

```
</details>

**Comment by fuyufjh** [comment]
@xxchan Can you help to run a heap profile?  https://github.com/risingwavelabs/risingwave/blob/main/docs/memory-profiling.md

**Comment by xx01cyx** [comment]
This is caused by `BatchTaskExecution` not being freed after query execution. Each batch task is stored in a hashmap in `BatchManager` and never gets removed. 
https://github.com/risingwavelabs/risingwave/blob/main/src/batch/src/task/task_manager.rs#L96-L97

**Comment by fuyufjh** [comment]
We seem to have fixed a similar problem 🤔 cc. @BowenXiao1999 @liurenjie1024

**Comment by xx01cyx** [comment]
> We seem to have fixed a similar problem 🤔 cc. @BowenXiao1999 @liurenjie1024

IIRC that's query execution, which increases memory usage in frontend: #5827

**Comment by BugenZhao** [comment]
Seems another `WeakHashMap`-like issue... 🤔

**Comment by BowenXiao1999** [comment]
Yes there will be some hashmap's problem. 

We might need a background corountine to do the clean-up. WeakHashMap or naive way may not help, as the task's upstream may keep reading from it.

**Comment by liurenjie1024** [comment]
Yes, this is an known issue for distributed mode, and we need a fix later.

**Comment by xxchan** [comment]
BTW, should we have a test for such problems (memory leak after a lot of batch tasks). e.g., in longevity test?

**Comment by liurenjie1024** [comment]
> BTW, should we have a test for such problems (memory leak after a lot of batch tasks). e.g., in longevity test?

Good idea, but currently test team has no resources for longevity test for distributed query, so we can postpone it.

**Comment by liurenjie1024** [comment]
Fixed.
