### ISSUE TITLE
feat: OverWindow in the batch mode

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#7715]
### Describe the bug

On Postgres:
```
postgres=# create table t (groupid int, username varchar);
CREATE TABLE
postgres=# SELECT row_number() OVER ( PARTITION BY t.groupid ORDER BY t.username) AS usergroupid                                                                                                       FROM                                                                                                                           t;
 usergroupid
-------------
(0 rows)
```

But it fails on RisingWave:

```
ERROR:  QueryError: internal error: OverAgg can not be transformed. Plan:
LogicalProject { exprs: [ROW_NUMBER] }
└─LogicalOverAgg { window_function: ROW_NUMBER() OVER(PARTITION BY t.groupid ORDER BY t.username ASC NULLS LAST) }
  └─LogicalScan { table: t, columns: [groupid, username, _row_id] }
```

Is it a bug or a known issue?

**Comment by xxchan** [comment]
It's a known limitation. Currently we only support TopN pattern. General OverWindow (https://github.com/risingwavelabs/rfcs/pull/8) is not implemented yet.

**Comment by fuyufjh** [comment]
@neverchanje Please reconfirm the req, thanks!

**Comment by fuyufjh** [comment]
I think this will be done in next quarter's OKR. I'll close this first and @stdrc must have more detailed plans for it.

**Comment by stdrc** [comment]
Yep we now have too many issues tracking over window🤣. Now I'm tracking batch over window feature in https://github.com/risingwavelabs/risingwave/issues/9931 and overall task list in https://github.com/risingwavelabs/risingwave/issues/9124.

BTW, FYI, batch over window will ready very soon, maybe a few days.
