### ISSUE TITLE
Implement arithematic operator `^` for double precision and numeric

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7724]

**Comment by lmatz** [comment]
maybe exclude `Decimal/Numeric` first

**Comment by MohitBansal321** [comment]
Hey I want to contribute to this project can you help me out with where are they all the numeric types
Thank you

**Comment by lmatz** [comment]
> Hey I want to contribute to this project can you help me out with where are they all the numeric types Thank you

Hi @MohitBansal321, thanks for your interest in implementing this,
I just checked again at
https://www.postgresql.org/docs/7.4/functions-math.html,
we can implement the operator for `dp`/`double precision` (64bit float) first.

**Comment by MohitBansal321** [comment]
so we need to build double precision function  for it right? @lmatz

**Comment by lmatz** [comment]
> so we need to build double precision function for it right? @lmatz

e.g. x ^ Y, we require x and Y are double precision, or cast to double precision if they are not.

**Comment by lmatz** [comment]
@MohitBansal321 
do you encounter any difficulties? Feel free to share and we are ready to help 😃

**Comment by MohitBansal321** [comment]
I didn't know about PostgreSQL and what you want I don't know about double precision @lmatz

**Comment by MohitBansal321** [comment]
Did  you want to change the size of 32 bits to 64 bits of X and Y

**Comment by lmatz** [comment]
In a previous pr https://github.com/risingwavelabs/risingwave/pull/7789, we have added a SQL function `pow`.

More specifically:
1. We introduce a function called `general_pow` which requires two input parameters able to be cast into the type of output. https://github.com/risingwavelabs/risingwave/blob/main/src/expr/src/vector_op/arithmetic_op.rs#L112
2. We use https://github.com/risingwavelabs/risingwave/blob/main/src/expr/src/expr/expr_binary_nonnull.rs#L297-L336 to declare a number of expressions. It covers all the possible types of `general_pow`.
3. And we also did something in the frontend so that RisingWave can recognize this function name and pass it to the backend to compute.

Right now, what we still need to do is mostly in the frontend. 
We want to recognize `^` as an operator and correctly let the backend build the expression, i.e. `pow`/`^`. https://github.com/risingwavelabs/risingwave/blob/main/src/expr/src/expr/build_expr_from_prost.rs#L67

We can mimic how `+`/`-`/`*`/`\` is handled in the frontend.

**Comment by MohitBansal321** [comment]
Thank you for the detailing 
I checked all code what  didn't get the syntax 
So i can't work on it
Thank You

**Comment by LiuYuHui** [comment]
I would like to try it :D
