### ISSUE TITLE
Implement `exp`/`pow` function

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7725]
https://www.postgresql.org/docs/7.4/functions-math.html:
```
Function                  | Return Type
exp(dp or numeric)        | (same as input)
pow(a dp, b dp)           | dp
pow(a numeric, b numeric) | numeric
```

- [x] pow(a numeric, b numeric) | numeric: https://github.com/risingwavelabs/risingwave/pull/7789
- [x] pow(a dp, b dp)           | dp: https://github.com/risingwavelabs/risingwave/pull/7789
- [x] exp(dp)  | dp: https://github.com/risingwavelabs/risingwave/pull/7971
- [x] exp(numeric) | numeric: https://github.com/risingwavelabs/risingwave/pull/7971

**Comment by lmatz** [comment]
maybe exclude `Decimal/Numeric` first

**Comment by snipekill** [comment]
Hey Imatz, I wanted to contribute to the project, can you help me point out right resources and code pointers for implementing this.

**Comment by lmatz** [comment]
> Hey Imatz, I wanted to contribute to the project, can you help me point out right resources and code pointers for implementing this.

Hi @snipekill , thanks for your interest in this feature! 
But since it is urgent, I am just going to implement it. Are you interested in some other issues? We are happy to help 😃

**Comment by lmatz** [comment]
If we cast them in frontend, I guess we can only support a concrete implementation (f64,f64)->f64 instead of a general one.

_Originally posted by @TennyZhuang in https://github.com/risingwavelabs/risingwave/pull/7789#discussion_r1100004997_

**Comment by lmatz** [comment]
Decimal unsupported yet, only double precision.

After choosing a new Decimal crate.
