### ISSUE TITLE
Avoid being blocked by errors when building docker image

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7734]
For example, 
![SCR-20230207-lvh](https://user-images.githubusercontent.com/5791930/217182982-c24dfdd4-e8e8-41ad-8fc0-bba15d87ee51.png)
This is the error in the source of the ubuntu packages. 

We can retry, but sometimes this problem goes away only after a period of time.

So we want to retry with delay, but this feature is not implemented by buildkite yet: https://forum.buildkite.community/t/automatic-retry-delay/1730 (this thread opened two years ago, so......)

We can also retry within the scripts, but this would require the machine to stay active for a while and seems a waste.

One way suggested by @cyliu0 is to maintain a ubuntu image by ourselves, which installs all the packages.
The benefit also includes saving network bandwidth.

Seeking more opinions on this issue.
And if you encounter other types of errors, which cannot be simply solved by retry, please leave a comment, thanks!

**Comment by lmatz** [comment]
Seems no objection to `maintain a ubuntu image by ourselves, which installs all the packages`?

**Comment by xxchan** [comment]
What about simply reuse `rw-build-env` as the builder...?

**Comment by CAJan93** [comment]
Could we not just add an extra stage like https://github.com/risingwavelabs/risingwave/pull/7919? This way we would not always need to re-build the ubuntu stage

**Comment by xxchan** [comment]
> Could we not just add an extra stage like #7919? This way we would not always need to re-build the ubuntu stage

Can the CI get the cache for the first stage? 👀 Don't know much about how docker works.

**Comment by CAJan93** [comment]
> Can the CI get the cache for the first stage? 👀 Don't know much about how docker works.

Don't know enough about the CI 😬 If we use one machine to build the docker images and we keep the cache, then yes.

**Comment by xxchan** [comment]
> If we use one machine to build the docker images

Then we can't because it's spot instance. 🤣 Let's publish the first stage (or reuse `public.ecr.aws/x5u3w5h6/rw-build-env`..?)

**Comment by xxchan** [comment]
Maybe we can also use remote docker cache (via BuildKit)...
https://docs.docker.com/build/cache/backends/

**Comment by huangjw806** [comment]
I will try it when I am free.

**Comment by CAJan93** [comment]
> Maybe we can also use remote docker cache (via BuildKit)... 

This sounds like a great Idea. I am not even sure if we need to publish any extra images/layers. [Watching this explanation](https://www.youtube.com/watch?v=77j6JFBTmTc)  it looks like that all we need to do is to say `--cache-from ghcr.io/risingwavelabs/risingwave`

**Comment by lmatz** [comment]
It seems recently it does not fail any more, and since it starts to build at 9:00pm UTC+8, if anything goes wrong, we can retry it manually before the longevity test and performance test.

But if there is an easy solution, we can still try it.

**Comment by xxchan** [comment]
`apt-update` is already cached since https://github.com/risingwavelabs/risingwave/pull/12193

**Comment by CAJan93** [comment]
So the solution was just to use `ghcr.io/risingwavelabs/risingwave-build-cache` as a remote docker backend?

**Comment by xxchan** [comment]
Yes.

CAJan93 ***@***.***>于2023年10月6日 周五17:46写道：
