### ISSUE TITLE
Meta node will restart when running nexmark q9

### ISSUE THREAD

**Issue by huangjw806** [risingwavelabs/risingwave#7753]
### Describe the bug

meta node will restart when running nexmark q9.

### To Reproduce

image-tag:nightly-20230207

1. Cloud deploys a single-node risingwave cluster.
2. prepare 1 billion messages in kafka source.
3. run nexmark q9.

pipeline link: https://buildkite.com/risingwave-test/nexmark-benchmark/builds/366#01862ca0-2a86-4bff-911a-d0178ec9287f
<img width="857" alt="image" src="https://user-images.githubusercontent.com/29391315/217415183-ea043412-b32c-480e-8abc-0dd59dc47810.png">

The environment is gone, cloudwatch logs link: https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logsV2:log-groups/log-group/$252Frisingwave$252Frls-apse1-eks-a$252Fnexmark-7-8-9-16-daily-20230207

**Comment by shanicky** [comment]
It seems that the etcd connection is frequently disconnected causing the election watch client on the meta node to be disconnected causing meta-0 to restart

**Comment by huangjw806** [comment]
The sameissue appeared in the pipeline last night, this time when it happened in drop mv：
<img width="853" alt="image" src="https://user-images.githubusercontent.com/29391315/219252412-84f7f09e-63c4-47a6-8db7-00100568e594.png">
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/29391315/219252498-b83551c0-94dd-4d7d-9a81-5c79602bee51.png">

buildkite link：https://buildkite.com/risingwave-test/nexmark-benchmark/builds/398#018655d3-beb0-4394-87e3-9b128a7a9753

cloudwatch logs link：https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logsV2:log-groups/log-group/$252Frisingwave$252Frls-apse1-eks-a$252Fnexmark-7r-8-9-16-daily-20230215

**Comment by fuyufjh** [comment]
Any updates?

**Comment by shanicky** [comment]
This issue should have been resolved with meta in new version.
