### ISSUE TITLE
Discussion:`./risedev c` does not fix warnings

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#7756]
Not sure if there was a conclusion before, but I usually prefer `./risedev c` to fix the warnings, especially since it will only fix if the meaning of the fix is unambiguous.

It will make my workflow more efficient for sure.

**Comment by jon-chuang** [comment]
Not sure if there was a conclusion before, but I usually prefer `./risedev c` to fix the warnings, especially since it will only fix if the meaning of the fix is unambiguous.

**Comment by BugenZhao** [comment]
`cargo clippy --fix` is much much slower than simply running the clippy check. I'm not sure what exactly happens, but `fix` will also try recompiling the crate after fixing issues in case of false positives.

**Comment by jon-chuang** [comment]
Hmm I see. Maybe I'll add a new command `./risedev check-fix` alias `./risedev cf`? What do you think?
