### ISSUE TITLE
bug: When I create a materialized view, I get an error.

### ISSUE THREAD

**Issue by hhy8545259** [risingwavelabs/risingwave#7760]
### Describe the bug

When I create a materialized view, I get an error.

<img width="857" alt="image" src="https://user-images.githubusercontent.com/20966345/217423120-f2c2acbc-4005-4cce-af47-20bca50fd3a0.png">

This is the error log 

`thread 'risingwave-main' panicked at 'called `Option::unwrap()` on a `None` value', src/frontend/src/utils/column_index_mapping.rs:252:9
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/panicking.rs:65:14
   2: core::panicking::panic
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/panicking.rs:115:5
   3: core::option::Option<T>::unwrap
             at ./risingwave/src/frontend/src/utils/column_index_mapping.rs:252:9
   4: risingwave_frontend::utils::column_index_mapping::ColIndexMapping::map
             at ./risingwave/src/frontend/src/utils/column_index_mapping.rs:252:9
   5: <risingwave_frontend::optimizer::plan_node::logical_join::LogicalJoin as risingwave_frontend::optimizer::plan_node::plan_tree_node::PlanTreeNodeBinary>::rewrite_with_left_right::{{closure}}
             at ./risingwave/src/frontend/src/optimizer/plan_node/logical_join.rs:527:27
   6: core::iter::adapters::map::map_fold::{{closure}}
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/iter/adapters/map.rs:84:28
   7: core::iter::traits::iterator::Iterator::fold
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/iter/traits/iterator.rs:2414:21
   8: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/iter/adapters/map.rs:124:9
   9: core::iter::traits::iterator::Iterator::for_each
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/iter/traits/iterator.rs:831:9
  10: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/alloc/src/vec/spec_extend.rs:40:17
  11: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  12: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/alloc/src/vec/spec_from_iter.rs:33:9
  13: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at ./risingwave/src/frontend/src/optimizer/plan_node/logical_join.rs:524:38
  14: core::iter::traits::iterator::Iterator::collect
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/iter/traits/iterator.rs:1836:9
  15: <risingwave_frontend::optimizer::plan_node::logical_join::LogicalJoin as risingwave_frontend::optimizer::plan_node::plan_tree_node::PlanTreeNodeBinary>::rewrite_with_left_right
             at ./risingwave/src/frontend/src/optimizer/plan_node/logical_join.rs:524:38
  16: <risingwave_frontend::optimizer::plan_node::logical_join::LogicalJoin as risingwave_frontend::optimizer::plan_node::convert::ToStream>::logical_rewrite_for_stream
             at ./risingwave/src/frontend/src/optimizer/plan_node/logical_join.rs:990:38
  17: risingwave_frontend::optimizer::PlanRoot::gen_stream_plan
             at ./risingwave/src/frontend/src/optimizer/mod.rs:444:46
  18: risingwave_frontend::optimizer::PlanRoot::gen_create_mv_plan
             at ./risingwave/src/frontend/src/optimizer/mod.rs:492:27
  19: risingwave_frontend::handler::create_mv::gen_create_mv_plan
             at ./risingwave/src/frontend/src/handler/create_mv.rs:96:23
  20: risingwave_frontend::handler::create_mv::handle_create_mv::{{closure}}
             at ./risingwave/src/frontend/src/handler/create_mv.rs:128:29
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  22: risingwave_frontend::handler::handle::{{closure}}
             at ./risingwave/src/frontend/src/handler/mod.rs:225:76
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  24: <risingwave_frontend::session::SessionImpl as pgwire::pg_server::Session<risingwave_frontend::handler::PgResponseStream>>::run_statement::{{closure}}
             at ./risingwave/src/frontend/src/session.rs:788:50
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  26: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/future.rs:124:9
  27: pgwire::pg_extended::PgPortal<VS>::execute::{{closure}}
             at ./risingwave/src/utils/pgwire/src/pg_extended.rs:160:17
  28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  29: pgwire::pg_protocol::PgProtocol<S,SM,VS>::process_execute_msg::{{closure}}
             at ./risingwave/src/utils/pgwire/src/pg_protocol.rs:468:13
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  31: pgwire::pg_protocol::PgProtocol<S,SM,VS>::do_process_inner::{{closure}}
             at ./risingwave/src/utils/pgwire/src/pg_protocol.rs:213:65
  32: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  33: pgwire::pg_protocol::PgProtocol<S,SM,VS>::do_process::{{closure}}
             at ./risingwave/src/utils/pgwire/src/pg_protocol.rs:158:41
  34: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  35: pgwire::pg_protocol::PgProtocol<S,SM,VS>::process::{{closure}}
             at ./risingwave/src/utils/pgwire/src/pg_protocol.rs:154:29
  36: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  37: pgwire::pg_server::handle_connection::{{closure}}::{{closure}}
             at ./risingwave/src/utils/pgwire/src/pg_server.rs:146:44
  38: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  39: pgwire::pg_server::handle_connection::{{closure}}
             at ./risingwave/src/utils/pgwire/src/pg_server.rs:131:1
  40: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  41: pgwire::pg_server::pg_serve::{{closure}}::{{closure}}
             at ./risingwave/src/utils/pgwire/src/pg_server.rs:118:40
  42: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  43: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  44: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:184:17
  45: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/loom/std/unsafe_cell.rs:14:9
  46: tokio::runtime::task::core::CoreStage<T>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:174:13
  47: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:480:19
  48: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/panic/unwind_safe.rs:271:9
  49: std::panicking::try::do_call
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:483:40
  50: std::panicking::try
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:447:19
  51: std::panic::catch_unwind
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panic.rs:137:14
  52: tokio::runtime::task::harness::poll_future
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:468:18
  53: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:104:27
  54: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:57:15
  55: tokio::runtime::task::raw::RawTask::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/raw.rs:134:18
  56: tokio::runtime::task::LocalNotified<S>::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/mod.rs:385:9
  57: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:421:13
  58: tokio::coop::with_budget::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:102:9
  59: std::thread::local::LocalKey<T>::try_with
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/thread/local.rs:446:16
  60: std::thread::local::LocalKey<T>::with
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/thread/local.rs:422:9
  61: tokio::coop::with_budget
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:420:9
  62: tokio::coop::budget
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:72:5
  63: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:420:9
  64: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:387:24
  65: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:372:17
  66: tokio::macros::scoped_tls::ScopedKey<T>::set
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/macros/scoped_tls.rs:61:9
  67: tokio::runtime::scheduler::multi_thread::worker::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:369:5
  68: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:348:45
  69: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/task.rs:42:21
  70: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  71: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:184:17
  72: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/loom/std/unsafe_cell.rs:14:9
  73: tokio::runtime::task::core::CoreStage<T>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:174:13
  74: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:480:19
  75: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/panic/unwind_safe.rs:271:9
  76: std::panicking::try::do_call
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:483:40
  77: std::panicking::try
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:447:19
  78: std::panic::catch_unwind
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panic.rs:137:14
  79: tokio::runtime::task::harness::poll_future
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:468:18
  80: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:104:27
  81: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:57:15
  82: tokio::runtime::task::raw::RawTask::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/raw.rs:134:18
  83: tokio::runtime::task::UnownedTask<S>::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/mod.rs:422:9
  84: tokio::runtime::blocking::pool::Task::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/pool.rs:111:9
  85: tokio::runtime::blocking::pool::Inner::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/pool.rs:346:17
  86: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/pool.rs:321:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`

### To Reproduce

I am using risingwave version 0.1.15

1.I created three tables
`create table p_d_flow_head
(
       id VARCHAR,
       pid BIGINT, 
       ver_id BIGINT,
       werks_id BIGINT,
       technology_code VARCHAR,
       technology_description TEXT,
       enable BOOLEAN,
       del_flag BOOLEAN,
       create_by VARCHAR,
       create_time TIMESTAMP,
       update_by VARCHAR,
       update_time TIMESTAMP,
       primary key (id,ver_id,werks_id,technology_code)
)

create table flow_mid
(
        id VARCHAR,
        pid BIGINT,
        technology_ver VARCHAR,
        unit VARCHAR,
        basis_qty DECIMAL,
        start_time DATE,
        end_time DATE,
        enable BOOLEAN,
        del_flag BOOLEAN,
        create_by VARCHAR,
        create_time TIMESTAMP,
        update_by VARCHAR,
        update_time TIMESTAMP,
        primary key (id,pid,technology_ver)
)

create table p_d_flow_item
(
       id VARCHAR,
       pid BIGINT,
       route_code VARCHAR,
       route_ver VARCHAR,
       layer_id VARCHAR,
       stage_id VARCHAR,
       step_id VARCHAR,
       step_seq VARCHAR,
       step_type VARCHAR,
       mkostl_id VARCHAR,
       weight VARCHAR,
       unit01 VARCHAR,
       stand_qty01 DECIMAL,
       unit02 VARCHAR,
       stand_qty02 DECIMAL,
       outsourcing BOOLEAN,
       description TEXT,
       create_by VARCHAR,
       create_time TIMESTAMP,
       update_by VARCHAR,
       update_time TIMESTAMP,
       primary key (id,pid,step_seq)
)`

2.I try to create a materialized view
`create materialized view terry8_step_rule2 as
WITH BASE_FLOW AS (
         SELECT
             FLOW_HEAD.TECHNOLOGY_CODE,
             FLOW_HEAD.VER_ID,
             FLOW_HEAD.WERKS_ID,
             FLOW_MID.TECHNOLOGY_VER,
             FLOW_MID.ID ,
             FLOW_MID.BASIS_QTY
         FROM P_D_FLOW_HEAD  FLOW_HEAD
                  LEFT JOIN FLOW_MID ON FLOW_HEAD.ID = CAST(FLOW_MID.PID AS VARCHAR)
                  LEFT JOIN P_D_FLOW_ITEM FLOW_ITEM ON FLOW_MID.ID = CAST(FLOW_ITEM.PID AS VARCHAR)
     )
select *
from BASE_FLOW;`

3.I get an error message
<img width="865" alt="image" src="https://user-images.githubusercontent.com/20966345/217421616-8d12b9f1-897a-4f3f-aedb-5b81504a08a5.png">

### Expected behavior

I hope I can successfully create the materialized view, or tell me why I can't.

**Comment by liurenjie1024** [comment]
Thanks for reporting.

**Comment by xiangjinwu** [comment]
It seems to be a bug in v0.1.14, and cannot be reproduced since v0.1.15. Could you test again with a later version?

**Comment by hhy8545259** [comment]
I rebuilt the test environment of RisingWave version 1.15, and then I can execute the sql statements.
It does seem to be a version issue, maybe I got the versions mixed up.

Thanks!

**Comment by liurenjie1024** [comment]
Feel free to reopen it if it happens again.
