### ISSUE TITLE
replace `zip_eq` with optimizable version

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#7779]
As mentioned by @BugenZhao : https://github.com/risingwavelabs/risingwave/pull/7749#issuecomment-1422133394

And previously caught by @wangrunji0408 in https://github.com/risingwavelabs/risingwave/pull/6856.

We should probably replace `zip_eq` system wide with something else. This should be optimized away in release and bench builds.

**Comment by kwannoel** [comment]
cc @jon-chuang

**Comment by BugenZhao** [comment]
In my opinion, I suggest still making it an extension method to `Iterator`, named something like `zip_debug_eq`, and returning an opaque type of `impl Iterator<..>`, so we can return `Zip` when debug assertions are off and `ZipEq` when on. We may furthermore make a pull request to the upstream about it. 🥵

**Comment by xxchan** [comment]
I failed 🥵😭

<img width="947" alt="image" src="https://user-images.githubusercontent.com/37948597/217494492-c4ee8145-32b5-454e-bdbe-e6ee52d33e34.png">

**Comment by BugenZhao** [comment]
> I failed 🥵😭

We can't do that without specialization. 😭

**Comment by xxchan** [comment]
Let me do a stupid version instead

**Comment by kwannoel** [comment]
> Let me do a stupid version instead

I'm planning to implement it in https://github.com/risingwavelabs/risingwave/pull/7749 👀

**Comment by xxchan** [comment]
Did you begin? I can finish the dirty work 🥵
