### ISSUE TITLE
test: scaling of 2-phase aggregation is not covered

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#7788]
According to [nexmark_source.yaml](https://github.com/risingwavelabs/risingwave/blob/93a8e2c7205452b8252d5adbf01c0d7ce2dada72/src/frontend/planner_test/tests/testdata/nexmark_source.yaml#L1), there's no 2-phase aggregation (but 2-phase top-n) in the current chaos-test Nexmark queries. We should make up a new query to cover it.

- #6485

**Comment by lmatz** [comment]
After #7491's `SET FORCE_TWO_PHASE_AGG TO true`, I guess we can use existing queries with this new session variable to generate one? @kwannoel

**Comment by kwannoel** [comment]
> After #7491's `SET FORCE_TWO_PHASE_AGG TO true`, I guess we can use existing queries with this new session variable to generate one? @kwannoel

Sounds good, will work on it.

**Comment by kwannoel** [comment]
FYI it is currently buggy due to https://github.com/risingwavelabs/risingwave/issues/7928.

Will be fixed by https://github.com/risingwavelabs/risingwave/pull/7929.
