### ISSUE TITLE
RFC(stream): User Errors in RisingWave Stream Jobs

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#7824]
### Background

We want to report errors originating from the user's data (and not from RisingWave itself) to the user.

Fixes 2nd part of: https://github.com/risingwavelabs/risingwave/issues/4625, subsumes: https://github.com/risingwavelabs/risingwave/issues/7803

### Design

Collect Prometheus metrics.

Define a new wrapper error type:

```rust
enum UserError {
    ExprError(String),
    ParserError(String),
    ConnectorError(String),
}
```
When defining a `UserError`, we need to ensure that the `error_msg` (`String` part) is of low cardinality.

#### Metric definition
We will collect a `user_error: Count` metric with the following labels:
1. `error_type`: currently one of `expr_error`, `parser_error`, `connector_error`
2. `error_msg`: error messages that are converted to low-cardinality versions.
3. `executor_name`: executor ids but without their actor_id (error metrics consumer should be able to group by `executor_name` without `actor_id`)
4. `fragment_id`

#### Examples of low-cardinality error msg conversion

`ExprError`s for reference: https://github.com/risingwavelabs/risingwave/blob/5938e35c02c2091d165b9fb70107d9399f86a0e0/src/expr/src/error.rs#L26

For instance, consider:

```rust
#[error("Parse error: {0}")]
Parse(Cow<'static, str>),
```

Although the strings can be very long, they are also static, and don't depend on our data, so must be finite in number. So we can use this as our error message.

On the other hand, consider the following:
```rust
#[error("Invalid parameter {name}: {reason}")]
InvalidParam { name: &'static str, reason: String },
```

In this case, we should include `name` in the error message, but remove `reason`, as `reason` could be unbounded cardinality and depend on data values.

Note that not ALL `ExprError`s may turn out to be user errors. However, they are very likely to be, and are also not caught currently by our streaming jobs. So even if they turn out to be system errors (i.e. a bug within risingwave), then the user will at least still be able to report it to us.

#### E2E Testing Plan
??

#### More Detailed Errors
We can also allow users to query for their non-truncated errors (stored in-memory e.g. in the ActorContext for last 1000 messages) via a query routed through meta node, which will collect and merge the errors on request. We may also be able to provide an error backtrace for these (not sure if this is too high cost).

#### UDF errors
It is probably better to let users handle their external function UDFs errors by themselves. But if we are required to handle it, the user can return and error enum to our system, and we will have error msg `UDFError: my_udf_function: error_code: 5`. We may also consider certain UDF errors like network errors as user errors.

**Comment by xxchan** [comment]
related?: https://github.com/risingwavelabs/risingwave/issues/4625 👀

**Comment by jon-chuang** [comment]
On further consideration, I don't think we will get high cardinality for most errors. Hence, we should have a blacklist, not a whitelist.

**Comment by lmatz** [comment]
related?: #7803 👀

**Comment by BugenZhao** [comment]
> On further consideration, I don't think we will get high cardinality for most errors. Hence, we should have a blacklist, not a whitelist.

What do you mean by cardinality here? 👀

**Comment by fuyufjh** [comment]
> > On further consideration, I don't think we will get high cardinality for most errors. Hence, we should have a blacklist, not a whitelist.
> 
> What do you mean by cardinality here? 👀

There are some example the issue description. "Low-cardinality errors" are errors that have one or a few distinct messages in all occurrences, "high-cardinality errors" are those with distinct error messages for every occurrence.

**Comment by jon-chuang** [comment]
### Error Truncation Mechanism

A truncation strategy can be:
1. choose a target truncated message number, `TARGET_NUM`

Objective: choose at most `TARGET_NUM` prefixes such:
1. that we maximize their minimum length.

Example 1: No common prefix. Prefixes found: []
Example 2:
```
TARGET_NUM = 2. 
data = ["parse error: at position 3", "parse error: at position 3", "parse error: at position 4", "parse error: at position 4", "network error: Port 5464 is unavailable"]. 
Prefixes found: ["parse error: at position ", "network error: Port 5464 is unavailable"]. 
Resultant errors: ["parse error: at position <truncated>", "parse error: at position <truncated>", "parse error: at position <truncated>", "network error: Port 5464 is unavailable"]
```

Data structure: prefix tree with e.g. 15 unique prefixes. When we reach capacity, we start deleting prefixes longest first? or in the leaves of the heaviest branches. 

When a new error string arrives, we lookup its longest prefix in the prefix tree and truncate it to that. If the capacity is not filled, we add it to the prefix tree. If the capacity is filled and we have a new value:
1. Check if there is a non-zero prefix in the prefix tree. If there is a complete match, do nothing.
2. Else, find the longest partial match. Remove all children of the partial match, and add the partial match as a leaf.
3. If there is no partial match, we add the new element as a leaf. Then we free up capacity by truncating the longest path with at least 2 descendants to that path.

When we cannot accept new non-empty entries to the prefix tree (every prefix is unique), we will simply truncate the incoming message entirely.

**Comment by fuyufjh** [comment]
Can I close this issue?
