### ISSUE TITLE
bug: Empty was read from the table created by `create table .. as select from ..` immediately after creation.

### ISSUE THREAD

**Issue by idx0-dev** [risingwavelabs/risingwave#7826]
### Describe the bug

I'm working on the dbt adapter for risingwave and try to make it pass the tests provided by dbt. A simple duplicating table test case is resulted as a failure, However, I checked the database directly and discovered those two tables were identical. Then, I executed the SQL statements generated by dbt test one by one in REPL manually and they work well as expected.

After a long period of trying, I find a way to reproduce it finally. 

### To Reproduce

```SQL
create table "a2" ("id" integer);
insert into a2 values (1),(2),(3),(4),(5);
create table b2 as (select * from a2);
select count(*) from a2;
select count(*) from b2;
```
Save SQL statements above into a file `a.sql`, for example.

Then, execute it by `psql` cli.
```shell
psql -h localhost -p 4566 -d dev -U root -f a.sql
```

And got such result below.
```
CREATE_TABLE
INSERT 0 5
INSERT 0 5
 count
-------
     5
(1 row)

 count
-------
     0       <- This is incorrect.
(1 row)
```

### Expected behavior

The `select count(*) from b2;` statement output should be **5** rather than **0**.

### Additional context

It is necessary to execute those SQL statements in a batch in order to reproduce. Copying and pasting them one by one into a REPL will result correctly.

**Comment by lmatz** [comment]
Originally, we intend to ban 'create table as select from' in production.

Now if debt requires this, it seems we cannot ban it.

**Comment by liurenjie1024** [comment]
Is `set RW_IMPLICITFLUSH TO true` enabled?

**Comment by BugenZhao** [comment]
> Is `set RW_IMPLICITFLUSH TO true` enabled?

Do you think we should make this default when interacting with some external tools? Not sure whether it's possible to recognize them.

**Comment by liurenjie1024** [comment]
> Do you think we should make this default when interacting with some external tools? Not sure whether it's possible to recognize them.

I think it's possible to make it default in adapters of those tools?

**Comment by idx0-dev** [comment]
> > Do you think we should make this default when interacting with some external tools? Not sure whether it's possible to recognize them.
> 
> I think it's possible to make it default in adapters of those tools?

Yes. I will try this, if it could be configured via connection options.

**Comment by idx0-dev** [comment]
After establishing a connection, execute `SET RW_IMPLICIT_FLUSH TO true` resolves the issue. I have implemented this behavior in the adapter. Thanks.
