### ISSUE TITLE
Exclude --feature hdfs-backend for clippy

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#7837]
i.e., avoid using `--all-features`. It will require every developer have JAVA setup.

**Comment by xxchan** [comment]
BTW, why do we have a separate `rw-build-env-hdfs`? I think include JAVA in CI build env doesn't hurt 🤔

**Comment by hzxa21** [comment]
> BTW, why do we have a separate `rw-build-env-hdfs`? I think include JAVA in CI build env doesn't hurt 🤔

I think it is because including JAVA and HADOOP in the build image will increase the image size by 50%. Not sure whether that how much it will slow down the CI pipeline.

**Comment by xxchan** [comment]
😦 That‘s quite shocking… Maybe let’s just ignore the check for hdfs features, just like that for deterministic simulation?

**Comment by xxchan** [comment]
… But maybe we will have to introduce a hdfs test env later 🤔

**Comment by hzxa21** [comment]
> 😦 That‘s quite shocking… Maybe let’s just ignore the check for hdfs features, just like that for deterministic simulation?

+1

> … But maybe we will have to introduce a hdfs test env later 🤔

Right. But the question is whether we want to compile the hdfs engine by default in all cases including the CI and public images with JAVA and HADOOP dependencies. Turning on hdfs engine in the perf/longevity test env is unavoidable.

**Comment by wcy-fdu** [comment]
Currently we just commented out the `hdfs` features to avoid everyone setup hadoop env. If cargo clippy can only exclude a certain feature, we can add it back.
