### ISSUE TITLE
`hakari verify` failed

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#7843]
After #7283, `risedev check` produced a large warning from `hakari verify`

**Comment by xxchan** [comment]
created an issue in upstream https://github.com/guppy-rs/guppy/issues/69 to see whether it's our problem

**Comment by BugenZhao** [comment]
We may also need to add `verify` to the `check.sh` on CI. 😰

**Comment by wcy-fdu** [comment]
In #7283 , we implemented `hdfs` backend. However,  adding `hdfs` in out CI image is heavy (image size raise from 2.7G to 3.7G), and we only want to compile `opendal/services-hdfs` when the user specifies hdfs. 
If this feature is added to `workspace-hack.toml`, all of our CI image need to support `hadoop` environment, so I  use `final-excludes` to remove it in `hakari`.

**Comment by wcy-fdu** [comment]
I found that maybe put `opendal/services-hdfs` in `[traversal-excludes]` can solve this issue.
