### ISSUE TITLE
Define constant relation with CTE in streaming

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#7854]
Some users want to define dimension tables with CTE when they do not have the authority to create tables.
e.g.
```SQL
create materialized view as 
WITH dim as 
(
SELECT 1 AS k, 10000 AS v union all
SELECT 2 AS k, 10000 AS v union all
SELECT 3 AS k, 10000 AS v union all
) 
SELECT * from t join dim using (k);
```

- [x] https://github.com/risingwavelabs/risingwave/issues/7857
- [x] #7858 
- [x] #7859

**Comment by BugenZhao** [comment]
Do you think we should persist the values table to support lookup?

**Comment by st1page** [comment]
> Do you think we should persist the values table to support lookup?

I think we need not do that because the downstream executors will persist the values on demand... But I agree we need a more detailed design here. How about making a chain executor here and making sure every value have been emitted when the MV's creation has been done?

**Comment by BugenZhao** [comment]
> How about making a chain executor here

Do you mean the plain one-off `Chain`? LGTM if we assume there won't be much data in the `Values` executor, as it can simplify the handling of fail-over or reporting a lot.
