### ISSUE TITLE
Support error line/column number reporting during parsing

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7863]
Considering it can make SQL debugging quite painful, especially when SQL is long, it is critical to user experience.

Wonder if chatGPT can do a good job of finding the location of this type of error. 🤣

**Comment by kwannoel** [comment]
+1 for this, I guess we will first persist it in AST and eventually in bound query for error reporting?

Are there any user facing errors that are only reported during optimization?

**Comment by BugenZhao** [comment]
This requires a lot of work as the `sqlparser-rs` does not involve any "span"s during parsing. FYI, databend has rebuilt the parser from scratch, which provides enough information for clear error reporting in both parser and planner.

https://databend.rs/blog/databend-release-v0.8#new-parser-the-best-parser
https://databend.rs/blog/new-planner

**Comment by fuyufjh** [comment]
Refactoring `sqlparser-rs` may take lots of effort. How about starting by reporting line/pos in the parser now.

**Comment by xxchan** [comment]
> Refactoring `sqlparser-rs` may take lots of effort. How about starting by reporting line/pos in the parser now?

What do you mean? I think it is reporting line/pos in the parser that requires a large refactoring 🥵

**Comment by xxchan** [comment]
For reference, some upstream issues:
- https://github.com/sqlparser-rs/sqlparser-rs/issues/524 
- https://github.com/sqlparser-rs/sqlparser-rs/issues/757

**Comment by fuyufjh** [comment]
@chenzl25 Ping, any updates?

**Comment by chenzl25** [comment]
> @chenzl25 Ping, any updates?

No updates currently.
