### ISSUE TITLE
bug: fuzzing test generates a stuck SQL

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#7889]
### Describe the bug

It's first found in fuzzing test [here](https://buildkite.com/risingwavelabs/main/builds/3049). But it's also reproducible manually in earlier main branch.
The stuck SQL is `WITH with_0 AS (SELECT ((-2147483648) - (INT '326045151')) AS col_0, t_3.ps_comment AS col_1, ((SMALLINT '5714') >> (SMALLINT '26755')) AS col_2, ((INTERVAL '0') / t_9.seller) AS col_3 FROM region AS t_1, orders AS t_2, partsupp AS t_3, nation AS t_4, m1 AS t_5, auction AS t_6, customer AS t_7, m3 AS t_8, auction AS t_9 WHERE ('eCmLGTvlUV') NOT IN ((substr('75B3GHhhEA', (INT '1424354786'))), (repeat('NY1sHcmvym', (INT '1822803048'))), 'k0irJrq3Ca') GROUP BY t_9.item_name, t_2.o_shippriority, t_9.seller, t_3.ps_partkey, t_7.c_nationkey, t_3.ps_comment, t_6.reserve, t_8.col_2, t_6.initial_bid) SELECT ((FLOAT '-214847089') / t_15.col_0) AS col_0, (SMALLINT '119') AS col_1 FROM with_0, m7 AS t_10, m1 AS t_11, m3 AS t_12, m9 AS t_13, hop(auction, auction.date_time, INTERVAL '60', INTERVAL '3600') AS hop_14, m2 AS t_15, hop(person, person.date_time, INTERVAL '60', INTERVAL '3600') AS hop_16 GROUP BY hop_14.date_time, hop_14.description, hop_14.item_name, hop_14.extra, t_11.col_1, hop_14.expires, hop_14.initial_bid, hop_16.state, t_10.col_0, hop_16.email_address, t_15.col_0, t_15.col_2, t_12.col_1, hop_16.credit_card, t_12.col_0 HAVING true LIMIT 36;`

### To Reproduce

1. Create prerequisite table/source.
2. Execute the SQL in psql and get stuck.

**Comment by kwannoel** [comment]
Probably need to set a hard limit on cross joins being generated as suggested by eric here: https://github.com/risingwavelabs/risingwave/issues/7720#issuecomment-1420035442.
