### ISSUE TITLE
Tracking refactor(nested-loop-join)

### ISSUE THREAD

**Issue by BowenXiao1999** [risingwavelabs/risingwave#789]
* [x] #790
* [x] #792

**Comment by skyzh** [comment]
Is this issue resolved? cc @BowenXiao1999

**Comment by skyzh** [comment]
If not, please describe in detail what this issue is about. "Refactor nested loop join" seems too generic for a good first issue.

**Comment by BowenXiao1999** [comment]
Done. 
Closed for now.
