### ISSUE TITLE
bug: prepared statement ignores explicit types for actual query results

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#7900]
### Describe the bug

A prepared statement can have types in the query:
```
select $1::int4 + $2::int8;
```
Or it can be specified as part of the API / extended query protocol:
```
select $1 + $2; -- API specifies [int4, int8]
```

In the latter case, when RisingWave actually executes a query with arguments, for example `[4, 5]`, the current version executes `select 4 + 5;` and returns `9` as `int4`, effectively ignoring the specified types. As the prepared statement is expecting an `int8`, the client would not be able to deserialize the query result when passed in BINARY format. (TEXT format may work because `int4` serialized in TEXT can also be deserialized as `int8`, but this is still a type mismatch.)

### To Reproduce

```
// cargo add postgres
use postgres::{Client, NoTls};
use postgres::types::Type;

fn main() {
    let mut client = Client::connect("host=localhost port=4566 dbname=dev user=root", NoTls).unwrap();

    let prepared = client.prepare_typed(
        "select $1 + $2",
        &[Type::INT4, Type::INT8],
    ).unwrap();

    let rows = client.query(
        &prepared,
        &[&4i32, &5i64],
    ).unwrap();

    println!("{}", rows[0].get::<_, i64>(0));
}
```

### Expected behavior

Client does not panic and prints `9`. (same as PostgreSQL)

### Additional context

[psycopg2](https://www.psycopg.org/articles/2012/10/01/prepared-statements-psycopg/) does not support prepared statement at protocol level, and [psycopg3](https://www.psycopg.org/psycopg3/docs/advanced/prepare.html) does not expose it. So the repro above uses a rust client.

**Comment by xiangjinwu** [comment]
@ZENOTME Is this a known limitation or a bug?

**Comment by ZENOTME** [comment]
It's a bug...

For `select $1::bigint, [10]`, we will replace it as `select 10` rather than `select 10::bigint`. So  `select $1 + $2, &[Type::INT4, Type::INT8], [4,5]` will be convert as `select 4+5` finally and the result will be consider it as int rather than bigint.

This behavior is to solve #6163.

But now seems this solution isn't correct and maybe we should solve #6163 in optimizer.
