### ISSUE TITLE
deterministic fuzzing test: stability

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#7901]
### Problem

Currently our `ci:main` fails every few days, as a result of deterministic fuzzing test failing.

### Further background / investigation

**The same set of queries may not be generated each run.** Some previous run did not generate a failing query, but the new run did.

After offline discussion with @wangrunji0408, I suspect it is because the rng behaviour can only be reproduced on the same machine. The reason is not clear at this point.

Edit: Additionally the build environment also affects rng generation.

Q: On different machines running linux will rng gen be the same?

### Current approach

The current approach has been to manually tweak weights of generating certain expressions (for instance nested loop join, zeros). Or even setting a hard limit.

### Issue with the current approach

This works for a while. But when the machine running our deterministic test changes, the queries change as well. The new queries generated then trigger new errors.

Additionally by throttling it again and again we compromise the usual coverage of sqlsmith.

### Solutions

1. Be more defensive in sqlsmith. See #7866. Even when environment changes + set of generated queries change, we won't generate invalid queries.

This will be a bit of work. Need to go through each function, and constraint their input arguments if necessary.

### Other solutions

2. Freeze queries in deterministic test by pre-generating queries. Run against CI the same set of queries. I think this is a good approach in the long term. We can curate a set of queries which have good coverage (use `codecov`).

3. Add feature to `madsim` ensure `rng` will be generated same across machines. cc @wangrunji0408 is this possible? I think this is preferred over 2. It is easier to maintain a set of seeds than a large set of queries.

If either 2 or 3 are done, we can let `main-cron` run deterministic fuzzing test with changing query set, and keep `main` pipeline stable.

<sub>[KER-1](https://linear.app/risingwave-labs/issue/KER-1/deterministic-fuzzing-test-stability)</sub>

**Comment by wangrunji0408** [comment]
> Q: On different machines running linux will rng gen be the same?

I think so, but it has not been tested.

> Add feature to madsim ensure rng will be generated same across machines. cc @wangrunji0408 is this possible?

Actually the rng is always the same across machines. But the application code may be different. For example, the std library calls `getrandom` on Linux while on macOS it calls `getentropy`. From the view of rng, they may deverge at this point. So it would be hard  to result in the same across operating systems.

**Comment by jon-chuang** [comment]
> Freeze queries in deterministic test by pre-generating queries. Run against CI the same set of queries. I think this is a good approach in the long term. 

Can we generate these to files and merge to master on a weekly basis?

**Comment by fuyufjh** [comment]
+1 for 

> Freeze queries in deterministic test by pre-generating queries. Run against CI the same set of queries. I think this is a good approach in the long term. We can curate a set of queries which have good coverage (use codecov).

**Comment by kwannoel** [comment]
> +1 for
> 
> > Freeze queries in deterministic test by pre-generating queries. Run against CI the same set of queries. I think this is a good approach in the long term. We can curate a set of queries which have good coverage (use codecov).

Working on it 👍

**Comment by kwannoel** [comment]
Tracked: https://github.com/risingwavelabs/risingwave/issues/7978

**Comment by kwannoel** [comment]
Further motivation mentioned by @fuyufjh: https://github.com/risingwavelabs/risingwave/pull/7967#issuecomment-1441188998
