### ISSUE TITLE
Failed to push down filter when condition type can't cast to input type 

### ISSUE THREAD

**Issue by ZENOTME** [risingwavelabs/risingwave#7916]
### risingwave
```
dev=> create table t(id int primary key);

dev=> explain select * from t where id=151::int;
                               QUERY PLAN
-------------------------------------------------------------------------
 BatchExchange { order: [], dist: Single }
 └─BatchScan { table: t, columns: [id], scan_ranges: [id = Int32(151)] }
(2 rows)

// We can't push down filter here because 151::bigint can't be cast to int(the type of id).
dev=> explain select * from t where id=151::bigint;
                       QUERY PLAN
--------------------------------------------------------
 BatchExchange { order: [], dist: Single }
 └─BatchFilter { predicate: (t.id = 151:Int32::Int64) }
   └─BatchScan { table: t, columns: [id] }
(3 rows)
```

### postgres 
```
test_db=> create table t(id int primary key);
CREATE TABLE

test_db=> explain select * from t where id=151;
                             QUERY PLAN
---------------------------------------------------------------------
 Index Only Scan using t_pkey on t  (cost=0.15..8.17 rows=1 width=4)
   Index Cond: (id = 151)
(2 rows)

// postgres support to push down here.
test_db=> explain select * from t where id=151::bigint;
                             QUERY PLAN
---------------------------------------------------------------------
 Index Only Scan using t_pkey on t  (cost=0.15..8.17 rows=1 width=4)
   Index Cond: (id = '151'::bigint)
(2 rows)
```

Failed to push down the filter is the main reason of #6163.

The original solution of #6163 is not correct and it caused #7900. So I should rollback it later.🥵

And we should solve #6163 by solved this issue.🤔

**Comment by chenzl25** [comment]
We still need to push down the predicate down into table scan even if they have different types. We can perform a conversion between them during calculating the `scan_range`. If there is no such valid conversion, we can use a `false` condition to replace.

**Comment by jon-chuang** [comment]
I would prefer if the generation of the plan is done in the frontend. We may need to inline the session timezone into these cast expressions. Is this currently being done?

**Comment by chenzl25** [comment]
> I would prefer if the generation of the plan is done in the frontend. We may need to inline the session timezone into these cast expressions. Is this currently being done?

Yes, the generation of the plan is done in the frontend.

**Comment by chenzl25** [comment]
> (I think yes, only hop window and lookup join will try to build `BoxedExpression` directly in executors.... lookup join will even implictly cast if datatype mismatch, we need to reuse the logic for generating conditions for `Scan` in `LookupJoin`. Agreed? @chenzl25 )

I remember we have a rule `PushCalculationOfJoinRule` to handle the case of different type of equal join, so it seems that we can remove the implicit cast from batch lookup join.

**Comment by jon-chuang** [comment]
Let me check if this still results in lookup join after pushdown into a project...
