### ISSUE TITLE
perf: optimize `to_char`

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#7924]
see https://github.com/risingwavelabs/risingwave/issues/7351#issuecomment-1429476124.

1. Bench `build_to_char_const_tmpl` w/o template string. I think what is currently benched includes compilation of template str.
2. Use rust date time formatting as baseline / find some other suitable baseline.
3. Bench date_time::date : https://github.com/risingwavelabs/risingwave/issues/7351#issuecomment-1430786247
4. ~Precompute and store in executor the tmpl pattern matching object.~ This is done already.

**Comment by kwannoel** [comment]
i.e. we call `compile_pattern_to_chrono` in frontend first, before evaluating to_char_timestamp in compute node.

Otherwise we will call it repeatedly, for each `to_char` invocation.

It is costly: see https://github.com/risingwavelabs/risingwave/issues/7351#issuecomment-1406204310

**Comment by kwannoel** [comment]
Actually this is not so straightforward. Seems like it will occur elsewhere too:
1. When there is some scalar value.
2. We evaluate the scalar value into an arbitrary in-memory object, rather than a datum. In this case, it is a `ChronoPattern`.

We can't eval it in frontend, otherwise we have to ser/de the in memory representation when scheduling it.

We have to evaluate it in compute node, so probably some evaluation phase needs to be added (or is there an existing one for this?)

**Comment by lmatz** [comment]
suspect simple because `chrono::format::StrftimeItems` is not efficient enough
https://github.com/chronotope/chrono#:~:text=(while%20not%20being%20the%20primary%20goal)%20reasonably%20efficient

**Comment by kwannoel** [comment]
Update, `to_char` is not really a performance bottleneck, only ~1% is attributed to it in q17. 

<img width="720" alt="Screenshot 2023-03-20 at 12 17 09 PM" src="https://user-images.githubusercontent.com/47273164/226264577-feeb11ee-8022-4e49-8b9f-9c8b253ba31a.png">

However, `to_char` does lead to things being represented as `varchar`, which is the real cost.
