### ISSUE TITLE
RFC: store git commit hash and validate when registering to meta

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#793]
Under some scenarios, we need to deploy and start each component manually. There might be some confusing bugs if we forget to recompile or restart some component accidentally.

We may store the git commit hash in compile-time, and then validate it against the others when registering to the meta service. If the hashes do not match, the meta service should simply refuse registration and return an error.

**Comment by xxchan** [comment]
GIT_SHA is included in `version()` query now via env var, which is set for docker images. Other parts like compile-time git sha & sha validation are not planned.
