### ISSUE TITLE
bug(frontend): pgwire binary response unimplemented for list and struct

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#7949]
### Describe the bug

pgwire binary response unimplemented for list and struct

### To Reproduce

```python
import psycopg

conn = psycopg.connect(host='localhost', port='4566', dbname='dev', user='root')
with conn.cursor() as cur:
	cur.execute("select Array[1::bigint, 2::bigint, 3::bigint]", binary=True)
	for row in cur:
		print(row)
```

### Expected behavior

No panic in frontend.

**Comment by jon-chuang** [comment]
Loading binary for array here: https://github.com/psycopg/psycopg/blob/0d2ea7648336712988206ac1dac28f01be775413/psycopg/psycopg/types/array.py#L434

**Comment by xxchan** [comment]
https://github.com/risingwavelabs/risingwave/issues/3676#issuecomment-1254826683

@ZENOTME Do we have plan to support them?

**Comment by ZENOTME** [comment]
It's not easy to support multiple demision list so there is no work for that now.

https://github.com/MaterializeInc/materialize/blob/61a82dfd8432b094189c4f839f67ab738f0f3bc1/src/pgrepr/src/value.rs#L390-L421

We can try to implement a single dimension list first. BTW, rust-postgres seems also only support to single dimension list.
