### ISSUE TITLE
Support `SHOW TRANSACTION ISOLATION LEVEL`

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#7976]
Required by metabase's official pg driver. In theory, the isolation level of risingwave should be read-committed because auto-flush is enabled by default. If disabled, I think it's read-uncommitted. But as claimed in PG's doc: 

> The SQL standard defines one additional level, READ UNCOMMITTED. In PostgreSQL READ UNCOMMITTED is treated as READ COMMITTED.

Some libraries might treat read-uncommitted as read-committed.

**Comment by cyliu0** [comment]
Hit the same issue when testing with the metabase plugin.

Metabase Error: 
```
An SQLException was provoked by the following failure: java.lang.IllegalStateException: Received resultset tuples, but no field structure for them
```

RW Frontend Error:
```
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ UNCOMMITTED:
Feature is not yet implemented: Unhandled statement: SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
No tracking issue yet. Feel free to submit a feature request at https://github.com/risingwavelabs/risingwave/issues/new?labels=type%2Ffeature&template=feature_request.yml
2023-03-01T03:15:50.643435Z  INFO risingwave_frontend::scheduler::hummock_snapshot_manager: Unpin epoch 3958724828069888 with RPC
```
