### ISSUE TITLE
bug: `explain_to_string()` is called even for non-explain queries

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#7998]
@jon-chuang `explain_to_string()` is called even for non-explain queries. This is unacceptable and might be a performance botten-neck for serving queries. 

https://github.com/risingwavelabs/risingwave/blob/58da8cac59a943bbb633932f7b66a203350e593d/src/frontend/src/optimizer/mod.rs#L444

I think you can simply run `explain` multiple times to get the output of each stage. Anyway, `explain` is for human users so the performance is not critical problem.

_Originally posted by @fuyufjh in https://github.com/risingwavelabs/risingwave/issues/7155#issuecomment-1434124404_

**Comment by jon-chuang** [comment]
We should also benchmark our frontend plan generation time

**Comment by jon-chuang** [comment]
> I think you can simply run explain multiple times to get the output of each stage

I think it's more trivial, just need to branch on an `is_explain` flag.
