### ISSUE TITLE
bug: New project explain format makes planner test unstable

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#8005]
after https://github.com/risingwavelabs/risingwave/pull/7953

              > The new project format would cause lots of existing plans changed after introducing a new rule for optimizer. 🥵 cc @fuyufjh

Is it possible to make the expression ID local and continuous? So that as long as the plan itself is not changed, we won't get diff on the explain result.

_Originally posted by @BugenZhao in https://github.com/risingwavelabs/risingwave/issues/7982#issuecomment-1434093627_

**Comment by BugenZhao** [comment]
Can we close this now?
