### ISSUE TITLE
Introduce critical alert panel in grafana dashboard

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#8019]
Some examples:
  - [ ] Node/Component failure (compactor/meta/CN/frontend node count drop to 0)
  - [ ] Recovery rate (recovery triggered too frequently)
  - [ ] Barrier latency (gap between desired barrier latency and actual barrier latency remains large)
  - [ ] Foreground error rate (object store/meta store/streaming/batch/user SQL/RPC/... error rates go up and last for long)
  - [ ] Background error rate (compaction/vacuum error rates go up and last for long)
  - [ ] Capacity issues (disk/network bandwidth/object store QPS/compaction lags)
  - [ ] Version/Epoch gap (gaps in committed/safe/pinned epoch, current/checkpoint/safepoint/pinned version)
  - [ ] Stale SST Count (stale SSTs are not cleaned in time)

**Comment by jon-chuang** [comment]
> error rates go up and last for long

Is this a fixed threshold or do we use a moving average? What is the definition of "long"? Is it 5 minutes, 30 mins, 1 hour? Does this depend on the specific error type/error source?

**Comment by hzxa21** [comment]
#9031
