### ISSUE TITLE
`exp` is not fully compatible with PG

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#8025]
For example:
`select exp(-10000000);` returns 0 in RW
but it errors `underflow` in PG

See comments at https://github.com/risingwavelabs/risingwave/pull/7971#discussion_r1109229833

PG has special logic for this: https://github.com/postgres/postgres/blob/REL_15_2/src/backend/utils/adt/float.c#L1649

**Comment by erichgess** [comment]
Just for clarification, this ticket to update RW to have the same behavior as PG when the `exp` instruction returns `0`?  In other words, the result of this ticket would be to recreate the special logic from PG within RW?

**Comment by lmatz** [comment]
Hi @erichgess, I think you are right, we intend to let RW have the same behavior as PG's, i.e. report `underflow` and `overflow` under precisely the same situation. cc: @xiangjinwu

**Comment by erichgess** [comment]
Your point on the other ticket about not artificially restricting RW to what PG can do makes a lot of sense, but in this case, certainly, I think what PG is doing is the correct path, because their goal is to have consistent behavior across all platforms.

Could I hop on this ticket?

**Comment by lmatz** [comment]
Sure @erichgess, I think your reasoning makes sense
please go ahead, thanks for your interest!

**Comment by erichgess** [comment]
Great, thank you.

**Comment by erichgess** [comment]
@lmatz PG has separate error codes for flow overflow and underflow, but RW only has `NumericOutOfRange`, which means that RW will return `NumericOutOfRange` when `exp(x) == 0`, so it will not perfectly mirror PG.

Is the long term plan to eventually have the error codes in RW have the same granularity as the error codes from PG?

**Comment by lmatz** [comment]
@erichgess 
Yes, we also try to have error codes compatible with PG ones whenever possible.

If you'd like to use overflow and underflow instead of simply out of range, feel free to change it. This is a good point!

**Comment by erichgess** [comment]
The PG implementation uses `unlikely` to hint to the compiler that some `if` branches are unlikely to be executed. Do you want to replicate the same optimizations in RW?

**Comment by lmatz** [comment]
@erichgess, sure if you'd like to, 
I just took a look, 
and it seems people have some best practice when using stable Rust:https://users.rust-lang.org/t/compiler-hint-for-unlikely-likely-for-if-branches/62102/4
without relying on the nightly feature

**Comment by erichgess** [comment]
Should this ticket be closed now that the PR is merged?

**Comment by xiangjinwu** [comment]
Thank you @erichgess
