### ISSUE TITLE
feat(frontend): Constant fold `Condition` during `const_eval` phase

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#8040]
Semantically, a `Condition` with an expression `True` is as good as it without that expression. So I think folding the expression away after rewriting it in the same phase is good enough.

_Originally posted by @jon-chuang in https://github.com/risingwavelabs/risingwave/pull/7761#discussion_r1103240779_

**Comment by xiangjinwu** [comment]
#8209
