### ISSUE TITLE
bug(frontend): pgwire binary format for interval overflows

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#8041]
### To Reproduce

Execute a query in extended mode, to force binary format to be returned:
```
SELECT ((-2147483648) * (INTERVAL '86400'));
```

### Expected behavior

No panic, return interval.

Interim workaround can be to use `checked_mul` to avoid panic.
But proper fix needs to avoid error.

### Additional context

https://github.com/risingwavelabs/risingwave/blob/f5b7fd7b92e858f74630125a67b09af99f5d669f/src/common/src/types/interval.rs#L723

https://bulidkite-artifacts-bucket.s3.amazonaws.com/9eed51d0-eaaf-4ea3-95a2-2e9e557607f6/01865e72-d4b3-425e-b291-836a1daf317c/01865e73-2536-4397-af1c-c0f6b20b9033/risedev-logs/fuzzing-4.log

**Comment by jon-chuang** [comment]
It's supposed to be a decimal type, is that correct?

**Comment by kwannoel** [comment]
> It's supposed to be a decimal type, is that correct?

Not sure, see: https://github.com/postgres/postgres/blob/517bf2d9107f0d45c5fea2e3904e8d3b10ce6bb2/src/backend/utils/adt/timestamp.c#L1014

**Comment by xiangjinwu** [comment]
#4514
It should be an overflow error during `*`, rather than during `to_sql`. I think we can `checked_mul` here first.

**Comment by xiangjinwu** [comment]
This has been fixed "automatically" by #8501, as binary formatting no longer requires any calculation, and the multiplication already handles the error reporting properly.

Before closing this issue as resolved, are there disabled test cases that we want to re-enable?

**Comment by kwannoel** [comment]
> This has been fixed "automatically" by #8501, as binary formatting no longer requires any calculation, and the multiplication already handles the error reporting properly.
> 
> Before closing this issue as resolved, are there disabled test cases that we want to re-enable?

- I have tracked it testing binary_format via sqlsmith here: https://github.com/risingwavelabs/risingwave/issues/7329.
- We should have e2e_test for binary format too, just opened an issue to track it here: https://github.com/risingwavelabs/risingwave/issues/8560.

**Comment by kwannoel** [comment]
Currently sqlsmith does not test binary format at all, since I have changed it to use `simple_query` to avoid `binary_format` errors.
