### ISSUE TITLE
meta backup: don't leave out new MetadataModel

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#8043]
During meta backup, we explicitly select which MetadataModel to include in or exclude from a [metadata snapshot](https://github.com/risingwavelabs/risingwave/blob/d88f70cde1b68362079b3490f85c0b482019f60a/src/storage/backup/src/meta_snapshot.rs#L55).
The current issue is we don't enforce a review of selected MetadataModel list, when a new type of MetadataModel is added. That is we may forget to include new MetadataModel type in metadata snapshot when they should be, e.g. currently UDF, system params are left out.

Need to enforce a check after adding new MetadataModel.

**Comment by BugenZhao** [comment]
A hack that will possible work:

- Introduce a private marker trait as a super trait of `MetadataModel`.
- Write a macro of `for_all_metadata_model` and use this to implement the marker trait for all models.

Then we ensure that `for_all` will cover all implementors of `MetadataModel`.
