### ISSUE TITLE
Run DDL in the background

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#8051]
### Is your feature request related to a problem? Please describe.

Some users want to run DDLs (usually creating a materialized view) in the background. Now we have provided a system table to show the progress of DDLs. If we plan to 
To run DDLs in the background, once these DDLs are validated, our system needs to guarantee its completeness (even if the cluster is down during execution of the DDL) unless a cancel statement is issued.
It means we need to persist the materialized view meta (invisible first) and its backfill progress.If backfilling is finished, we can make the materialized view visible.

**Comment by BugenZhao** [comment]
Related:
- #8032 
- https://github.com/risingwavelabs/risingwave/issues/7593

**Comment by TennyZhuang** [comment]
I think it shouldn't be a SQL feature.

Not only the DDLs may be slow, but also DMLs or DQLs, e.g.
* `INSERT ... SELECT ...` with a huge table.
* A batch query with large table scans and several joins.

I proposed to introduce a new background SQL execution mode.

## What's the difference?

The normal SQL execution mode:

1. User submitted the query
2. Query returned the result set and completed.

The background SQL execution mode:

1. User submitted the query
2. The server persisted the query and returned ACK.
3. The server ran the query in the background.
4. User retrieved the resultset by polling.

**Comment by TennyZhuang** [comment]
Anyway, at current time, only allow DDLs to be executed in the background mode is accepted to me.

**Comment by liurenjie1024** [comment]
Another thing is fault tolerance of background executions. For me, it would be more natural to make it fault tolerant.

**Comment by kwannoel** [comment]
@yezizp2012 are you planning to take this up as an extension of #8145 ? If not I'd like to work on it.

**Comment by yezizp2012** [comment]
> @yezizp2012 are you planning to take this up as an extension of #8145 ? If not I'd like to work on it.

Not really, just feel free to assign yourself and take it. 😊
