### ISSUE TITLE
eviction strategy can be aggressive sometimes unexpectedly

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#8065]
![SCR-20230220-ukr](https://user-images.githubusercontent.com/5791930/220140902-856c6e8b-fe9f-4386-9ae7-d16b44e59733.png)
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/5791930/220141007-c5d8b403-3c52-4edd-9b84-d7926cc1587d.png">

Slack history: 
https://risingwave-labs.slack.com/archives/C03GTKX3C8G/p1676901892312759
https://risingwave-labs.slack.com/archives/C03GTKX3C8G/p1676957678684269

> You can see the memory starts growing at about 00:53, and that is when watermark start to grow to evict cache. But the memory keeps growing until just pass 00:55. So the memory eviction start to be aggressive to prevent OOM. The memory drop to 0 because the watermark hit the upper bound (current epoch), so it evicts all cache. 
by @yuhao-su

**Comment by lmatz** [comment]
It OOMed when `The memory allocated by Jemalloc` hits 0

**Comment by yuhao-su** [comment]
> It OOMed when `The memory allocated by Jemalloc` hits 0

Is it possible the memory drop to 0 because it got killed?

**Comment by lmatz** [comment]
> > It OOMed when `The memory allocated by Jemalloc` hits 0
> 
> Is it possible the memory drop to 0 because it got killed?

I think so, it OOMed first, i.e. use more memory resources than it requested from the risingwave-operator, and then it gets killed I suppose

**Comment by lmatz** [comment]
I mean `kube-bench` never voluntarily kill a pod if it does noting wrong.
And this phenomenon almost(I manually checked 3-4 Grafana dashboards in the recent month) always happens in every performance testing pipeline every day

**Comment by huangjw806** [comment]
> I mean kube-bench never voluntarily kills a pod if the pod does noting wrong.

During the test, kube-bench will not actively kill the risingwave pod. It may be restarted by k8s only if it encounters issues.

**Comment by lmatz** [comment]
OOM may be caused by #8125

**Comment by lmatz** [comment]
Reopen if it appears again
