### ISSUE TITLE
feat: `EXPLAIN TRACE` eager option

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#8072]
### Is your feature request related to a problem? Please describe.

Currently explain happens lazily. As a result, if somewhere downstream in optimizer there is a panic, we cannot see trace at all.

We can use `explain (trace)` to debug panics too.

### Describe the solution you'd like

Add a session variable for eager explain trace.

**Comment by fuyufjh** [comment]
It might not be possible due to the limitation of PG's wire protocol.

Perhaps some `trace!()` log is easier.

**Comment by jon-chuang** [comment]
I've also faced this issue before. Agree with tracing the log.

Another way we can handle it is that we should catch all panics occuring inside a frontend task and send back the backtrace as an error. For the error case, we can also include the trace as part of a verbose error message. But it seems unnecessary, prefer trace.
