### ISSUE TITLE
bug: casting `NULL` as boolean array has wrong protobuf encoding or decoding

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#8082]
### Describe the bug

Panics at https://github.com/risingwavelabs/risingwave/blob/fef993916abdefea04cb2f236d7590a3aba90cb0/src/common/src/array/column_proto_readers.rs#L71

### To Reproduce

```
create table t(v1 int);
insert into t values(1), (2), (3);
select CAST(NULL as bool[]) from t;
```

### Expected behavior

```sql
query T
select CAST(NULL as bool[]) from t;
----
NULL
NULL
NULL
```

**Comment by xiangjinwu** [comment]
It is a bug of `ListArray::from_protobuf`. `int[]` does not have this panic because it does not have this assertion check, and it turns out that having a wrong `cardinality` is not fatal here: it is just a hint for ArrayBuilder to reverse memory.

Also reproduciable:
```
dev=> create table t (v1 int); insert into t values (1), (2), (3), (4);
CREATE_TABLE
INSERT 0 4
dev=> select array[false, false] from t;

thread 'risingwave-main' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', src/common/src/array/column_proto_readers.rs:71:5
```
