### ISSUE TITLE
metabase support

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#8087]
### Is your feature request related to a problem? Please describe.

Refer to https://github.com/risingwavelabs/risingwave-test/issues/173

I can setup the connection on Metabase w/ type PostgresSQL. But the Metabase can't get the tables like PostgresSQL by itself. And a simple query like `select * from t` doesn't work properly. Error occurs:
```
An SQLException was provoked by the following failure: java.lang.IllegalStateException: Received resultset tuples, but no field structure for them
```

**Comment by fuyufjh** [comment]
Related https://github.com/risingwavelabs/risingwave/issues/2613

**Comment by cyliu0** [comment]
Close since I did not use the plugin. https://github.com/risingwavelabs/metabase-risingwave-driver

**Comment by lmatz** [comment]
Similar bugs discovered by https://github.com/risingwavelabs/risingwave/issues/8089
seems not a metabase specific issue?
