### ISSUE TITLE
e2e iceberg sink test download spark too slow and timeout

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#8093]
### Describe the bug

![SCR-20230221-o5u](https://user-images.githubusercontent.com/5791930/220303534-9d5b58aa-dbc3-4a9c-a26e-2e05ec289a6f.png)

frequently occur in recent pr's CI

**Comment by xxchan** [comment]
still not fixed after https://github.com/risingwavelabs/risingwave/pull/8036 ? cc @wenym1

**Comment by xxchan** [comment]
We can upload the tgz to a s3 (buildkite's or ours), which can be much faster and more stable

**Comment by wenym1** [comment]
I am working on building an image specially for iceberg test. We can put the tgz file in the image.

**Comment by lmatz** [comment]
> still not fixed after #8036 ? cc @wenym1

oh, I am not aware of that, recent PR's base too old also possible, let me double check

**Comment by jon-chuang** [comment]
Not fixed in recent master: https://buildkite.com/risingwavelabs/pull-request/builds/17937#0186736d-6150-44a3-8014-515fce93b7e3
