### ISSUE TITLE
style: switch from `derivative` to `educe`

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#8103]
> IIRC derivative is unmaintained. We can switch to educe

_Originally posted by @xxchan in https://github.com/risingwavelabs/risingwave/pull/8094#discussion_r1112922366_

**Comment by xxchan** [comment]
Althought it's easy, but it's trivial chore work so I don't think it's "good first issue" 💦

**Comment by xxchan** [comment]
<img width="478" alt="image" src="https://user-images.githubusercontent.com/37948597/236463896-0a329b2f-1bc5-4e8d-ae1e-66a3e7e30c3d.png">

😲
