### ISSUE TITLE
refactor: refactor extended query mode in pgwire 

### ISSUE THREAD

**Issue by ZENOTME** [risingwavelabs/risingwave#8112]
For now the process of extended query mode in pgwire is directly operate the naive sql string, e.g
1. check if the sql is a query string 
2. replace the param 

But this kind of proccess is not so reliable (the naive string have many corrner case we need to take care),we may need to migrate it to process in parse tree.

**Comment by xiangjinwu** [comment]
would benefit: #6710 #8089

**Comment by xiangjinwu** [comment]
Just documenting a subtle PostgreSQL behavior:
```
test=# create table u (v1 int); insert into u values (10);
CREATE TABLE
INSERT 0 1
test=# create table v (v1 bool); insert into v values (true);
CREATE TABLE
INSERT 0 1
test=# prepare q as select v1 || $1 from u;
PREPARE
test=# select * from pg_prepared_statements;
 name |              statement               |         prepare_time          | parameter_types | from_sql | generic_plans | custom_plans 
------+--------------------------------------+-------------------------------+-----------------+----------+---------------+--------------
 q    | prepare q as select v1 || $1 from u; | 2023-03-10 14:22:35.613249+08 | {text}          | t        |             0 |            0
(1 row)

test=# execute q ('foo');
 ?column? 
----------
 10foo
(1 row)

test=# alter table u rename to tmp;
ALTER TABLE
test=# execute q ('foo');
ERROR:  relation "u" does not exist
test=# alter table v rename to u;
ALTER TABLE
test=# execute q ('foo');
 ?column? 
----------
 truefoo
(1 row)
```

That is, the table object `u` is not bound to the prepared `q`. It is just a name. This behavior is different from when a table is referenced by a view in PostgreSQL.

Our behavior would be different if we store the `BoundStatement`. But I am not suggesting us to match PostgreSQL here. Just making the difference clear.

**Comment by ZENOTME** [comment]
I find some things:
1. 'Prepare','Execute' statement is go on simple query protocol  
2. Parse message in extended protocol will generate prepare statement and 'Prepare' statement will generate the prepare statement too. These prepare statement will store in the same place. That means it will caused conflict if they create a prepare statement with the same name.
3. Difference between them: 
    'Prepare' statement only support specific kind of SQL  https://www.postgresql.org/docs/current/sql-prepare.html#:~:text=Any%20SELECT%2C%20INSERT%2C%20UPDATE%2C%20DELETE%2C%20or%20VALUES%20statement.
    extended protocol can support all statement

Given on this, to support 'Prepare','Execute' statement, maybe we should consider to store prepare statement and portal in frontend rather than pgwire.

**Comment by ZENOTME** [comment]
Most of work have done. Remain work: create as with parameter, create view with parameter, create sink with parameter. 

But I don't think it's worth to support them beacase:

> Can't support ddl with param like create view v as <query with param>
Actually I think it's not necessary because the param is useful for reusing a sql. But for ddl sql, it can't be reused because you can't create a view or table twice. So I think the user may rarely use ddl with param. And if we support it, it will cause the redundant and duplicate code like query handle so that it take effort to maintain or refactor them.

If this point is acceptable, this issue is done.
