### ISSUE TITLE
feat(optimizer): Pull up window table function in batch query.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#8121]
### Is your feature request related to a problem? Please describe.

Currently when we have window table function in our batch query, we can't utilize index for performance. For example, let's say we have following table definitions:

```sql
create table t1 (
c1 varchar,
c2 int,
c3 timestamp
);

create table t2 (
d1 int,
d2 varchar
);

create index idx_t1 on t1(c2) include (c1, c2, c3);
``` 

When we execute following query:
```sql
dev=> explain select * from t2 inner join tumble(t1,  c3, interval '10 minute')  on t2.d1 = t1.c2;
                                                                                    QUERY PLAN                                                                                     
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 BatchHashJoin { type: Inner, predicate: t2.d1 = t1.c2 }
 ├─BatchExchange { order: [], dist: Single }
 | └─BatchScan { table: t2, columns: [d1, d2] }
 └─BatchExchange { order: [], dist: Single }
   └─BatchProject { exprs: [t1.c1, t1.c2, t1.c3, TumbleStart(t1.c3, '00:10:00':Interval) as $expr45, (TumbleStart(t1.c3, '00:10:00':Interval) + '00:10:00':Interval) as $expr46] }
     └─BatchScan { table: t1, columns: [c1, c2, c3] }
```

Without tumble window:
```sql
dev=> explain select * from t2 inner join t1 on t2.d1 = t1.c2;
                          QUERY PLAN                           
---------------------------------------------------------------
 BatchLookupJoin { type: Inner, predicate: t2.d1 = idx_t1.c2 }
 └─BatchExchange { order: [], dist: Single }
   └─BatchScan { table: t2, columns: [d1, d2] }
```

Given that window value function is a frequently used feature in our system, we should optimize it.

### Describe the solution you'd like

Let's define tumble window as following:

$$
TUMBLE(R, time\\_col) = \\{ r \cup \(window\\_start, window\\_end\) | r \in R, window\\_start = f\(time\\_col\),  window\\_end =  g\(time\\_col\) \\}
$$

We can add following optimizer rule to our planner to utilize index lookup join:

$$
TUMBLE(R, time\\_col) \Join_p S = TUMBLE(R \Join_p S)
$$

When $p$ doesn't involve derived columns such as $window\\_start$ and $window\\_end$

Hop window function can also be viewed as union of several tumble window function in batch query, so we can have similar optimization rule:

$$
HOP(R, time\\_col) \Join_p S = HOP(R \Join_p S)
$$

### Describe alternatives you've considered

No

**Comment by liurenjie1024** [comment]
Welcome for discussion cc @st1page @chenzl25

**Comment by chenzl25** [comment]
Not quite sure whether users would write this batch sql, while the optimization LGTM.

**Comment by liurenjie1024** [comment]
> Not quite sure whether users would write this batch sql, while the optimization LGTM.

This is from concrete user requirements.

**Comment by st1page** [comment]
So not only on table function. we might also optimize all projects. (also we need to do on hop operator especially too)
```
dev=> create table t1 (k1 int primary key, v1 int);
CREATE_TABLE
dev=> create table t2 (k2 int primary key, v2 int);
CREATE_TABLE
dev=> explain select v1+1, v2 from t1,t2 where k1 = k2;
                          QUERY PLAN                           
---------------------------------------------------------------
 BatchProject { exprs: [(t1.v1 + 1:Int32) as $expr23, t2.v2] }
 └─BatchLookupJoin { type: Inner, predicate: t1.k1 = t2.k2 }
   └─BatchExchange { order: [], dist: Single }
     └─BatchScan { table: t1, columns: [k1, v1] }
(4 rows)

dev=> explain select v1_p1, v2 + 1 from (select v1+1 as v1_p1, k1 from t1),t2 where k1 = k2;
                             QUERY PLAN                              
---------------------------------------------------------------------
 BatchProject { exprs: [$expr45, (t2.v2 + 1:Int32) as $expr46] }
 └─BatchLookupJoin { type: Inner, predicate: t1.k1 = t2.k2 }
   └─BatchExchange { order: [], dist: Single }
     └─BatchProject { exprs: [(t1.v1 + 1:Int32) as $expr45, t1.k1] }
       └─BatchScan { table: t1, columns: [k1, v1] }
(5 rows)

dev=> explain select v1 +1 , v2_p1 from t1, (select v2+2 as v2_p1, k2 from t2) where k1 = k2;
                             QUERY PLAN                              
---------------------------------------------------------------------
 BatchProject { exprs: [(t1.v1 + 1:Int32) as $expr46, $expr45] }
 └─BatchHashJoin { type: Inner, predicate: t1.k1 = t2.k2 }
   ├─BatchExchange { order: [], dist: Single }
   | └─BatchScan { table: t1, columns: [k1, v1] }
   └─BatchExchange { order: [], dist: Single }
     └─BatchProject { exprs: [(t2.v2 + 2:Int32) as $expr45, t2.k2] }
       └─BatchScan { table: t2, columns: [k2, v2] }
(7 rows)
```

**Comment by liurenjie1024** [comment]
Yes, we can do hop/tumble first as it's required by our customer, and general purpose  projection later.

**Comment by st1page** [comment]
> Yes, we can do hop/tumble first as it's required by our customer, and general purpose projection later.

unfortunately, we transform tumble window into a project operator before the optimizer so we must implement a general one :crying_cat_face:

**Comment by ZENOTME** [comment]
> And because we have not seen many join can expand cardinality(the join key usually contains primary key of one side), maybe we can always pull up the calculations(hop/project) across join.

Is this behavior(pull up) will benefit other join? In other words, do we want to pull up for any join or only look up join?🤔
If we only want to pull up for look up join,  Can we directly support convert look up join when we meet project+scan? 
https://github.com/risingwavelabs/risingwave/blob/3a06226b683956b1778940328b0e3fbabc113ac8/src/frontend/src/optimizer/plan_node/logical_join.rs#L376

**Comment by chenzl25** [comment]
> 
> Is this behavior(pull up) will benefit other join? In other words, do we want to pull up for any join or only look up join?🤔 If we only want to pull up for look up join, Can we directly support convert look up join project+scan in the right side?

Our goal is to convert the SQL:

```sql
select * from t2 inner join tumble(t1,  c3, interval '10 minute')  on t2.d1 = t1.c2;
```

Into a equivalent one like this:

```sql
with cte as (select * from t2 inner join t1  on t2.d1 = t1.c2) select * from  tumble(cte,  c3, interval '10 minute');
```

I think we can implement a general `JoinProjectTransposeRule` in logical optimization to pull up the project function.

**Comment by liurenjie1024** [comment]
> Is this behavior(pull up) will benefit other join? In other words, do we want to pull up for any join or only look up join?🤔
If we only want to pull up for look up join, Can we directly support convert look up join project+scan in the right side?

The goal of this pull up rule is to let optimizer recogonize that we can utilize index to speed up this join, e.g. we can use lookup join rather enforcing hash join.

**Comment by ZENOTME** [comment]
I got it.

**Comment by liurenjie1024** [comment]
After #8772, we still need a rule to pull up tumble window function.

**Comment by ZENOTME** [comment]
I will do it later.

**Comment by ZENOTME** [comment]
This issue is completed?

**Comment by liurenjie1024** [comment]
> This issue is completed?

Yes.
