### ISSUE TITLE
bug(storage): memory leaks

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#8125]
### Describe the bug

<img width="918" alt="image" src="https://user-images.githubusercontent.com/10192522/220573819-2e4bf609-f3fd-4c93-a055-c347068cfe9f.png">

At 08:19 (last snapshot before OOM)

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/10192522/220573267-cba92d62-d46d-4676-8067-2b4fdb10bfb5.png">

Zoom in:

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/10192522/220574444-171ff1b9-f5bd-4365-832c-0bccedf821a8.png">

At 07:28 (just for comparsion)

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/10192522/220573465-c45f7e99-0e3b-4d12-9908-35972d966064.png">

### To Reproduce

Run nexmark_q4, nexmark_q5, nexmark_q7, nexmark_q8 for more than 1 hour.

### Additional context

[flamegraph_memory_leaks_20230222.zip](https://github.com/risingwavelabs/risingwave/files/10801886/flamegraph_memory_leaks_20230222.zip)

**Comment by soundOfDestiny** [comment]
@Little-Wallace and I guess that it's due to incorrect approximation of memory usage.

**Comment by fuyufjh** [comment]
> @Little-Wallace and I guess that it's due to incorrect approximation of memory usage.

Can you elaborate it?

**Comment by soundOfDestiny** [comment]
> > @Little-Wallace and I guess that it's due to incorrect approximation of memory usage.
> 
> Can you elaborate it?

RW call `let charge = sst.meta.encoded_size();` after `std::mem::take(&mut meta.bloom_filter);` so lru cache size is underestimated. Therefore the amount of available memory which RW thinks it has is more than the amount of available memory which RW actually has, which leads to OOM.
