### ISSUE TITLE
bug: CI build deterministic simulation error in m5a.4xlarge instance type

### ISSUE THREAD

**Issue by huangjw806** [risingwavelabs/risingwave#8134]
We used `m5.4xlarge` instance type machines to run ci before, but sometimes the spot instance may have insufficient resources, so I added `m5a.4xlarge` instance type, but an error occurred during build deterministic simulation:

```
error: failed to run custom build command for `ring v0.16.20`
--
  |  
  | Caused by:
  | process didn't exit successfully: `/risingwave/target/sim/ci-sim/build/ring-2d3c5b500cdbabdb/build-script-build` (signal: 4, SIGILL: illegal instruction)
  | --- stdout
  | OPT_LEVEL = Some("2")


```

occurred in #7865

**Comment by fuyufjh** [comment]
It might uses some SIMD instructions which are not supported on that EC2 instance. Is it possible to get rid of this library or that SIMD part?

**Comment by fuyufjh** [comment]
FYI. https://docs.rs/crate/ring/latest/source/build.rs

**Comment by wangrunji0408** [comment]
It looks like an edge case that disappeared after a rerun.

**Comment by huangjw806** [comment]
> It looks like an edge case that disappeared after a rerun.

That's because I removed the instance type.

**Comment by jon-chuang** [comment]
> /usr/bin/bash: line 1:   121 Illegal instruction     (core dumped) MADSIM_TEST_SEED=3 ./risingwave_simulation ./e2e_test/ddl/\*\*/\*.slt 2> $LOGDIR/ddl-3.log

Back

**Comment by jon-chuang** [comment]
I think this may be a separate issue?

**Comment by huangjw806** [comment]
Looks like `m4.4xlarge` doesn't support either.

**Comment by huangjw806** [comment]
The error seems to only happen in deterministic simulation, can you take a look? cc @wangrunji0408

**Comment by BugenZhao** [comment]
The `build.rs` will be first built to an executable, then `cargo` will run it for building the crate. Note that we always enable the SIMD feature, so there might be SIMD instruction in the output binary of the build script. 👀

m5a spec:
> † AVX, AVX2, and Enhanced Networking are only available on instances launched with HVM AMIs.
