### ISSUE TITLE
feat: Bushy tree join ordering

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#8139]
### Is your feature request related to a problem? Please describe.

Implement bushy tree join ordering to minimize the height of the join tree based on the RFC https://github.com/risingwavelabs/rfcs/pull/23.

**Comment by lmatz** [comment]
I suppose it will be optional by turning on/off session variables, and thus will not be in conflict with query hints(in the future) for join ordering?

**Comment by chenzl25** [comment]
> I suppose it will be optional by turning on/off session variables, and thus will not be in conflict with query hints(in the future) for join ordering?

Yes.

**Comment by liurenjie1024** [comment]
Will we support it in batch query?

**Comment by chenzl25** [comment]
> Will we support it in batch query?

This optimization can work for batch as well, but it might result in more memory consumption for the distributed batch queries.

**Comment by kwannoel** [comment]
Testing: https://github.com/risingwavelabs/risingwave/issues/8173

**Comment by chenzl25** [comment]
Add a bench. https://www.notion.so/risingwave-labs/Join-Ordering-Bench-fe6478688e0348249c1f12dcbd599a30

**Comment by chenzl25** [comment]
https://github.com/risingwavelabs/risingwave/pull/9394
