### ISSUE TITLE
bug(mv-on-mv): creating `count(*)` mv cause barriers pile-up

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#8177]
### Describe the bug

_This problem happened during the longevity test._

The problem seems to be the counting MV e.g.

```sql
CREATE MATERIALIZED VIEW count_nexmark_q21 AS
                SELECT count(*) AS record_count
                FROM nexmark_q21;
```

After creating it, the barrier latency soared high, which causes memory manager cannot work properly, and then OOM.

Between 02:18:37 ~ 03:34:38, the test script was creating these counting MVs for nexmark-q18/20/21.

However, I don’t know why barrier latency soared high. Even though counting MV may not be a good idea, barrier latency should be smooth and steady during its creation.

![image](https://user-images.githubusercontent.com/10192522/221113461-3682249d-0c12-4645-b8d1-aa47cc4dda78.png)

![image](https://user-images.githubusercontent.com/10192522/221113498-79d1529b-e38b-4714-bda7-dae1fa512aad.png)

### Additional context

Slack thread: https://risingwave-labs.slack.com/archives/C0423G2NUF8/p1677216659272929?thread_ts=1677185419.043819&cid=C0423G2NUF8

**Comment by BugenZhao** [comment]
Some random ideas:
- For backfill (also rearranged chain, https://github.com/risingwavelabs/risingwave/issues/5790), we always prefer and buffer the upstream side in order to get the barrier ASAP, while there’s no back-pressure for this. So we may get more upstream data than we can process downstream, each epoch.
- Backfill batches the upstream data until a barrier is received, this stalls the downstream pipelining. 🤨

**Comment by chenzl25** [comment]
It seems we can let backfill executor become barrier-latency awareness, so that we can slow down the snapshot consumption while barrier latency increases.

**Comment by fuyufjh** [comment]
> - Backfill batches the upstream data until a barrier is received, this stalls the downstream pipelining. 🤨

Actually I didn't quite understand this part. @BugenZhao From my understanding, since we do not collect barriers from these creating MVs (as well as actors), the problem should not be barriers piling up? 🤔

**Comment by BugenZhao** [comment]
> From my understanding, since we do not collect barriers from these creating MVs (as well as actors)

Nope. Once we connect it to the upstream with the `Add` mutation, it becomes a part of the streaming graph and we need to collect barriers from them even if they're marked as `CREATING`.

**Comment by fuyufjh** [comment]
> > From my understanding, since we do not collect barriers from these creating MVs (as well as actors)
> 
> Nope. Once we connect it to the upstream with the `Add` mutation, it becomes a part of the streaming graph and we need to collect barriers from them even if they're marked as `CREATING`.

Oh. I see. Thus, in summary, `BackfillExecutor` cause the invalidation of back-pressure, and we need to do something to bring it (back-pressure) back. Right?

**Comment by BugenZhao** [comment]
> Thus, in summary, `BackfillExecutor` cause the invalidation of back-pressure, and we need to do something to bring it (back-pressure) back.

Yes. This is my guess. 🥵

**Comment by fuyufjh** [comment]
Hi, any updates?

**Comment by chenzl25** [comment]
I have added a backfill throughput metric, so if it happens again, we will have more information to analyze.

**Comment by fuyufjh** [comment]
Now it is disabled in longevity test

```
skip_mvs_from_mvs=1
```

**Comment by fuyufjh** [comment]
Can't reproduce
