### ISSUE TITLE
recovery seems not triggered within a reasonable period of time in chaos mesh

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#8188]
### Describe the bug

During chaos-mesh `killing one compute pod` experiment,
the pod is killed at 04:41, but it seems meta doesn’t detect(?) the failure until 04:56.
From 04:41 -> 04:56, nothing was triggered from the chaos mesh side, simply sleeping.

Slack: https://risingwave-labs.slack.com/archives/C047W7ESWHK/p1677216498946339

LOG: [https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logsV2:log-groups/log-group/$2[…]rwc-3-chaosmesh-20230223-202909](https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logsV2:log-groups/log-group/$252Frisingwave$252Frls-apse1-eks-a$252Frwc-3-chaosmesh-20230223-202909)

Buildkite:https://buildkite.com/risingwave-test/longevity-chaos-mesh/builds/196#01867ff6-f5b7-4771-9c87-297875f206ca

![SCR-20230224-in0](https://user-images.githubusercontent.com/5791930/221464215-f1970464-72e2-414e-af67-6f57feb80034.png)
![SCR-20230224-ind](https://user-images.githubusercontent.com/5791930/221464223-b0340956-b843-4537-bdca-4dd62a4c6048.png)
![SCR-20230224-ioc](https://user-images.githubusercontent.com/5791930/221464225-943fb2a7-37e8-4282-be4e-32ebacc5f1c1.png)

**Comment by yezizp2012** [comment]
I will take a look tmr.

**Comment by lmatz** [comment]
We can take another look after re-enabling the chaos mesh test with debug-level log, close it now.
