### ISSUE TITLE
opt(agg): reuse existing `count(*)` while generating stream plan

### ISSUE THREAD

**Issue by richardchien** [risingwavelabs/risingwave#8197]

**Comment by jon-chuang** [comment]
Is this already fixed by https://github.com/risingwavelabs/risingwave/pull/8200?

**Comment by richardchien** [comment]
> Is this now fixed by https://github.com/risingwavelabs/risingwave/pull/8200?

No, the fix will be different from #8200. Will do this today😄

**Comment by jon-chuang** [comment]
Where is the performance improvement for reference?

**Comment by richardchien** [comment]
> Where is the performance improvement for reference? I guess anecdotal result is here: #7351 (comment)

Didn't do benchmark on this PR actually, cuz I think the performance increase is supposed to be minor (since it just remove one low-overhead agg call in some cases), a wild guess may be around 10% for nexmark q15/16/17? Anyway, I can do some bench later if it is necessary.😄

**Comment by jon-chuang** [comment]
Yes, I though I saw a graph about it showing throughput increase in the compute meeting but I couldn't find it after hunting a bit.

**Comment by richardchien** [comment]
> Yes, I though I saw a graph about it showing throughput increase in the compute meeting but I couldn't find it after hunting a bit.

Oh it was #8100
