### ISSUE TITLE
Support array_upper function

### ISSUE THREAD

**Issue by sumittal** [risingwavelabs/risingwave#8201]
### Describe the bug

Need the support of array_upper() from postgres:
```

This function is used to return the upper bound of the requested array dimension.

Syntax:

array_upper(anyarray, int)
```

As we are implementing the ycsb benchmark for risingwave, we needed this function to construct the dataset.

### Expected behavior

> SELECT array_upper(ARRAY[1,3,3,5], 1);

Sample Output:

```
 array_upper
-------------
           4
(1 row)
```

**Comment by jon-chuang** [comment]
Note that this has to find the upper bound of a multidimensional array. So it needs to walk each sub array.

**Comment by jon-chuang** [comment]
We are not so keen to support multi-dimensional array strictly, so we will implement this as walking ALL of the arrays of a given dimension...

Examples:
```sql
SELECT array_upper(ARRAY[[1], [2, 3]], 2);
```

@sumittal Could you point where exactly in YCSB the `array_upper` function is used?
