### ISSUE TITLE
enhancement: better hint for component names in risingwave binary 

### ISSUE THREAD

**Issue by JuchangGit** [risingwavelabs/risingwave#8211]
![image](https://user-images.githubusercontent.com/34911052/221578569-09da9b81-4819-4c69-8416-540bf6519c87.png)

**Comment by xxchan** [comment]
It seems both `-` and `_` are allowed. Also for e.g., `compute-node`, `compute_node` 🤣

I think that's ok, but maybe it's better to only suggest one style. Or put each kind of nodes in different lines.

**Comment by JuchangGit** [comment]
Yes, there should be a style

**Comment by jon-chuang** [comment]
At the very least, if we support multiple styles, they should be uniform.

(if we allow `meta-node`, we should also allow `compute-node`).

**Comment by jon-chuang** [comment]
Actually, I think it's fine to allow all, it's just that the message is confusing as the component strings are not sorted.
