### ISSUE TITLE
Difference in behaviour of Array with psql: `multidimensional arrays must have array expressions with matching dimensions`

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#8217]
### Describe the bug

psql
```sql
> select ARRAY[ARRAY[1], ARRAY[2, 3]];
ERROR:  multidimensional arrays must have array expressions with matching dimensions
```
risingwave
```sql
> select ARRAY[ARRAY[1], ARRAY[2, 3]];
    array    
-------------
 {{1},{2,3}}
(1 row)
```

### To Reproduce

as above

### Expected behavior

Should we be same as psql? Some users may have some nested list data without matching dim assumption. However, in this case, could they use jsonb as opposed to array?

We need the behaviour to be consistent at least for the purpose of implementing `array_upper`.

### Additional context
Related: https://github.com/risingwavelabs/risingwave/issues/8201
_No response_

**Comment by jon-chuang** [comment]
@xiangjinwu has suggested that we do not follow a C-type fixed dim semantic as psql does, but allow a dynamic length.

We should figure out what our multi-dim array functions should do if we implement them.

**Comment by jon-chuang** [comment]
Note that `jsonb` can handle non-matching dims (as well as arrays with any type e.g. `Any::[]` )

```sql
select '[[1], [2, 3]]'::jsonb;
     jsonb     
---------------
 [[1], [2, 3]]
(1 row)
```

**Comment by xxchan** [comment]
#3811
