### ISSUE TITLE
RisingWave Dashboard is unavailable

### ISSUE THREAD

**Issue by JuchangGit** [risingwavelabs/risingwave#8234]
is unavailable without an external network；
The reason is on line 77 of file risingwave/src/meta/src/dashboard/proxy.rs
![image](https://user-images.githubusercontent.com/34911052/221859424-34419e2b-4182-41bf-bad8-37c1bb9bc61e.png)

**Comment by xxchan** [comment]
You can download (or build) the dashboard artifact and pass `--dashboard-ui-path` to `meta-node`.

**Comment by xxchan** [comment]
BTW, could you share how are you using RisingWave? via docker?

**Comment by xxchan** [comment]
https://github.com/risingwavelabs/risingwave/pull/8241 I've updated the docker image to use the local dashboard artifact. 

You can try these images (after 03/01)
```
ghcr.io/risingwavelabs/risingwave:latest
```
or 
```
ghcr.io/risingwavelabs/risingwave:nightly-20230301
```

Feel free to reopen if this is not your use case or the problem persists.

**Comment by JuchangGit** [comment]
> BTW, could you share how are you using RisingWave? via docker?

yes, docker
