### ISSUE TITLE
Integration tests with external S3 Server

### ISSUE THREAD

**Issue by idx0-dev** [risingwavelabs/risingwave#8258]
The S3 connector should be tested automatically, but we can not depend on external services in the unit tests. 

 An integration test script should be created to be executed daily in our CI environment.
This script performs the following steps:

- Generate test data.
- Upload to S3-compatitble server. ( AWS S3, lyve cloud ... )
- Create source table in RisingWave. 
- Fetch the result and compare them with the generated data.
- Cleanup test data.

**Comment by tabVersion** [comment]
close as completed
