### ISSUE TITLE
bug(unit tests): Cache unit tests fail when `/tmp` is a `tmpfs` drive

### ISSUE THREAD

**Issue by erichgess** [risingwavelabs/risingwave#8278]
### Describe the bug

If a user's `/tmp` directory is hosted on a `tmpfs` drive (or any RAM disk) then the Hummock Cache unit tests will fail. Specifically, the unit tests in `hummock/file_cache/cache.rs` and `hummock/file_cache/file.rs` will fail when attempting to open a file with the `O_DIRECT` option.  

This failure happens because `tmpfs` and other RAM disks do not support Direct IO; so, if you attempt to open a file with `O_DIRECT` and that file is on a `tmpfs` drive the `open` function will return an error and then the call to `unwrap` will fault.

See: https://ask.fedoraproject.org/t/need-direct-io-for-ramfs-or-tmpfs-or-is-there-another-linux-ram-disk-that-supports-direct-io/3528

Tests which fail due to this issue:
- `test_cache_curd`
- `test_cache_grow`
- `test_recovery`
- `test_file_cache`

### To Reproduce

Create a `tmpfs` drive and update the `test_cache_grow` unit test to put its temporary directory on the `tmpfs` drive. Then run the `test_cache_grow` unit test. The test should then fault with an `Invalid Argument` error.

### Expected behavior

Either for the unit tests to have successfully run or for the tests to fail with an error explaining that the temporary directories cannot be on a `tmpfs` drive and instructions on how to configure the unit tests to use a different location for the temporary directories.

### Additional context

I think the fix can simply be:

1. The ability for a developer to specify a different location for temporary directories to be created when unit tests are run.
1. A note in the Developer Guide explaining that tests will fail if the location of the temporary directory is a `tmpfs` drive and instructions on how override the default location of `/tmp` and provide their own path. This note should include the error message that will be returned so that a developer can search the document if their unit tests fail and find instructions on how to get the unit tests to work.
2. (Optionally) When running a unit tests that uses a temporary directory, check if the temporary directory is on a `tmpfs` drive and, if it is, fail the test and provide an explanatory error message to the user.  You can use the `statfs` in libc to check if a file is on a `tmpfs` drive (https://stackoverflow.com/questions/26635846/how-to-tell-if-a-file-is-on-tmpfs-given-its-path-on-linux).

**Comment by liurenjie1024** [comment]
cc @hzxa21

**Comment by hzxa21** [comment]
Thanks for reporting the issue and the suggestions. Good catch! Currently the file cache relies on direct I/O by design so RAM disk indeed won't work.

We already used `statfs` to fetch the fs type when [initiliazing file cahce](https://github.com/risingwavelabs/risingwave/blob/f2389e3e36dedccfe74456dab023b90144c1d905/src/storage/src/hummock/file_cache/store.rs#L265). I think we should check whehter the tmpfs supports direct I/O as well and panic with a clear error message if it doesn't. If you are interested, feel free to open a PR for the fix.
