### ISSUE TITLE
bug: read count/size-iter always report zero

### ISSUE THREAD

**Issue by KeXiangWang** [risingwavelabs/risingwave#8279]
### Describe the bug

<img width="908" alt="image" src="https://user-images.githubusercontent.com/32863625/222282938-a8a6ea0f-0e87-44fd-b47e-2ce38ac7f9f0.png">
This is a screen shot from a running cluster. These two metrics is always zero.

We take join query based on nexmark as an example(see reproduce part).

hypothesis 1:
Since we refill cache when insert, all read-iter are reading non-exist key(especially when the join alignment are good).

To overthrow the hypothesis, I create a branch based on most recent main branch, and it does not do refilling.

https://github.com/risingwavelabs/risingwave/tree/wkx-hack-read-count-iter

In this branch, 
1. I add two lines of logs, one prints the current item counts and item sizes when updating them, the other one prints the current item counts and item sizes when reporting.
2. Use Minio as backend
3. Use grafana and promethesus
4. Do not refill cache any more when insert a row to join state table.

With this PR, all rows get into join operator will not fill cache. So when the potential matching rows come into join, they needs to iter from storage. In short, there will be some read operations are reading must-existent keys.

### To Reproduce

Run with this branch: https://github.com/risingwavelabs/risingwave/tree/wkx-hack-read-count-iter

1. build and runup cluster: `ENABLE_RELEASE_PROFILE=true  ./risedev d` for release mode or `./risedev d` for debug mode. On my Mac, both of them have this issue.
2. create query:
```
create source person
    (
    "id" BIGINT,
    "name" VARCHAR,
    "email_address" VARCHAR,
    "credit_card" VARCHAR,
    "city" VARCHAR,
    "state" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR,
)
with (
  connector = 'nexmark',
  nexmark.table.type = 'Person',
  nexmark.split.num = '1',
  nexmark.min.event.gap.in.ns = '1000000'
);
          
create source auction (
    "id" BIGINT,
    "item_name" VARCHAR,
    "description" VARCHAR,
    "initial_bid" BIGINT,
    "reserve" BIGINT,
    "date_time" TIMESTAMP,
    "expires" TIMESTAMP,
    "seller" BIGINT,
    "category" BIGINT,
    "extra" VARCHAR,
)
with (                         
  connector = 'nexmark',
  nexmark.table.type = 'Auction',
  nexmark.split.num = '1',
  nexmark.min.event.gap.in.ns = '1000000'
);
         
create source bid (
    "auction" BIGINT,
    "bidder" BIGINT,
    "price" BIGINT,
    "channel" VARCHAR,
    "url" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR
)
with (                 
  connector = 'nexmark',
  nexmark.table.type = 'Bid',
  nexmark.split.num = '1',
  nexmark.min.event.gap.in.ns = '1000000'
);

CREATE MATERIALIZED VIEW nexmark_query
AS
SELECT
  A.id,
  A.seller,
  A.extra as a_extra,
  B.extra as b_extra
FROM
  auction AS A,
  bid AS B
WHERE
  A.id = B.auction
  and B.date_time between A.date_time and A.expires;

```
3. Check your grafana, make sure the query is running. Run at least 10 minuts. Observe the `Read Item Count-Iter` and `Read Thoughput-Iter` metrics.
4. kill the cluster with `./risedev k`.
5. Check logs, we should focus on `.risingwave/log/compute-node-5688.log`. In this file there should be some extra logs that are added in the branch.

### Expected behavior

Following the above-mentioned steps, you should observe:
1. In grafana, 
a. There are data being processed. The throughput is not zero.
b. The `Read Item Count-Iter` and `Read Thoughput-Iter` is always close to zero. The correct metrics are at least not zeros.

2. In compute-node logs:
a. there are two logs  for table 1005 and table 1007:

One starts with `update table: 1007(or 1005)`, we call it `update log`. The other one starts with `report table: 1007(1005)`,  we call it `report log`.
<img width="734" alt="image" src="https://user-images.githubusercontent.com/32863625/222295955-8b2c89b4-e2b2-4617-b691-6fedb0f06b0d.png">

b. You can see, in the attached screen shot, there are a lot of `update log` says the the item sizes and counts are not zeros. But if you check the 'report log', you will find that all the report logs are reporting zero item sizes and counts.

To verify this, run the following commands:
```
cat .risingwave/log/compute-node-5688.log| grep "report table: 1007, total_item" | grep -v "report table: 1007, total_items: 0, total_size: 0"
cat .risingwave/log/compute-node-5688.log| grep "report table: 1005, total_item" | grep -v "report table: 1005, total_items: 0, total_size: 0"
```
You will find the outputs are both empty, which means although our system updates total item size and count values correctly, it only reports zeros.

**Comment by hzxa21** [comment]
I can successfully reproduced the issue in my linux box. I found that the issue can be fixed by explicitly pinning the stats:
```
async fn into_stream_inner(mut self) {
         let inner = self.inner;
+        let stats = self.stats;
+        futures::pin_mut!(stats);
         futures::pin_mut!(inner);
         while let Some((key, value)) = inner
             .try_next()
             .await
             .inspect_err(|e| error!("Failed in next: {:?}", e))?
         {
-            self.stats.total_items += 1;
-            self.stats.total_size += key.encoded_len() + value.len();
-            tracing::info!("update table: {}, total_items: {}, total_size: {}", self.stats.table_id, self.stats.total_items, self.stats.total_size);
+            stats.total_items += 1;
+            stats.total_size += key.encoded_len() + value.len();
+            tracing::info!("update table: {}, total_items: {}, total_size: {}", stats.table_id, stats.total_items, stats.total_size);
             yield (key, value);
         }
```

**Comment by hzxa21** [comment]
It seems that pinning is not the key point. Just moving out `self.stats` also fix the problem:
