### ISSUE TITLE
Discussion: Extend vnode to u16

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#8281]
The vnode field is currently stored as a u8 in Hummock storage, representing 256 vnodes. However, the u8 field is now fully utilized, which means extending it in the future without breaking backward compatibility is impossible. We even haven't a reserved bit.

Given that 256 vnodes equates to 256 cores in the whole RisingWave cluster, it may be insufficient to support a medium one. Therefore, we suggest extending the field to u16, with the first byte always set to 0x00 now. This will allow for scalability in the future.

**Comment by fuyufjh** [comment]
Agree. At least `u8` is quite unreasonable and we should increse to `u16` at least.

As for whether to increase the default #vnodes, or make the #vnodes of fragment configurable, that's another thing.

**Comment by BugenZhao** [comment]
It seems hard to provide backward compatibility for this breaking change. What about combining this with the new block format #8252 ?

**Comment by hzxa21** [comment]
> It seems hard to provide backward compatibility for this breaking change. What about combining this with the new block format #8252 ?

We actully plan to bump the sst format version and maintain compatibility by checking the version. We can extend that to use different `VirtualNode::SIZE` for different sst format version, although it is a little bit hacky to use sst format version for user key encoding.
