### ISSUE TITLE
Improve the error message prompted when the sink's schema mismatches with the MV.

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#8291]
### Is your feature request related to a problem? Please describe.

```
ERROR:  QueryError: internal error: Rpc error: gRPC error (Internal error): Actor 44 exit unexpectedly: Executor error: Sink error: Remote sink error: failed to start sink: Status { code: FailedPrecondition, message: "table schema does not match", metadata: MetadataMap { headers: {"content-type": "application/grpc"} }, source: None }
```

Not a bug but we should improve the error message.
1. It's not an internal error, so the error should be captured on the CN side and we should only output the user-facing message. (Without "QueryError: internal error: Rpc error: gRPC error (Internal error): Actor 44 exit unexpectedly: Executor error: Sink error:")
2. It should note which field causes the mismatch.

```sql
CREATE SINK seller_auctions_sink
FROM
    seller_auctions WITH (
        connector = 'iceberg',
        sink.mode = 'upsert',
        location.type = 'minio',
        warehouse.path = 'minio://hummockadmin:hummockadmin@minio-0:9301/hummock001/iceberg-data',
        database.name = 'demo_db',
        table.name = 'seller_auctions'
    );
```

**Comment by wenym1** [comment]
We will support a more general validation step with https://github.com/risingwavelabs/risingwave-connector-node/issues/31. With this feature implemented, the error message will be more user-friendly.

**Comment by wenym1** [comment]
Should be fixed after https://github.com/risingwavelabs/risingwave/pull/8508 and https://github.com/risingwavelabs/risingwave/pull/8417.
