### ISSUE TITLE
Support more data type for communication between CN and connector node for remote sink

### ISSUE THREAD

**Issue by wenym1** [risingwavelabs/risingwave#8299]
### Is your feature request related to a problem? Please describe.

In our current implementation, the data payload between CN and sink on connector node are encoded as JSON. However, we currently only support some primitive types, including integer, string and boolean.

### Describe the solution you'd like

To support more data types such as timestamp, we can either
- keep using json, and use string as payload to encode more high-level data type, such as timestamp.
- As stated in https://github.com/risingwavelabs/risingwave-connector-node/issues/75, integrate the data chunk with JNI as a new payload format for connector node.

**Comment by tabVersion** [comment]
any updates or close the issue?

**Comment by yufansong** [comment]
I will add a unit test for it. After finished, we can close it.

**Comment by yufansong** [comment]
It is already done in #11214 and #10559. I think we can closed this issue.
