### ISSUE TITLE
Discussion: Should GlobalSimpleAgg output one row immediately after created?

### ISSUE THREAD

**Issue by richardchien** [risingwavelabs/risingwave#8310]
Current behavior:

```sql
=> create table t (a int, b int);
CREATE_TABLE

=> create materialized view mv as select count(*), sum(a) from t; select * from mv;
CREATE_MATERIALIZED_VIEW
 count | sum
-------+-----
(0 rows)

=> flush; select * from mv;
FLUSH
 count | sum
-------+-----
     0 |
(1 row)
```

I'm not really sure if it's necessary to have an output row immediately after `create materialized view`. Any ideas? I remember there was a discussion on this, but can't find any link about it. And I remember someone said it's hard to implement and maybe not worth doing so, not quite sure.

**Comment by lmatz** [comment]
https://github.com/risingwavelabs/risingwave/issues/4954#issuecomment-1231276799 this one?

**Comment by richardchien** [comment]
> [#4954 (comment)](https://github.com/risingwavelabs/risingwave/issues/4954#issuecomment-1231276799) this one?

Oh yes it is! In fact the current behavior is no longer the same as the one described in #4954, while the comment seems still true for our system. Let me quote the comment here and we may discuss in this issue later if needed.

> @TennyZhuang: know the bug long long ago, but to fix this, we have to send a message to downstream when the first time we set up an actor. The SimpleAgg is the only operator who has the behavior but the fix may introduce too many efforts. I'd prefer keep the bug until we find a elegant way.

**Comment by chenzl25** [comment]
I think the current behavior is good enough and no users will notice this latency.

**Comment by fuyufjh** [comment]
Any conclusion?
