### ISSUE TITLE
discussion: shall we let Meta pass the credentials to compute nodes and compators

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#8340]
https://github.com/risingwavelabs/risingwave-operator/pull/376

Right now, they are passed directly by the operator.

**Comment by arkbriar** [comment]
cc. @Gun9niR @fuyufjh

**Comment by fuyufjh** [comment]
Looks good to me. Any controversy on this?

**Comment by lmatz** [comment]
just need to track backward compatibility I suppose

**Comment by lmatz** [comment]
I think it can decrease the chances of different compute nodes having different credentials and cause weird bugs that are confusing.

But one thing I have no knowledge of is, since it is passing secrets, does that mean we need to fulfill certain security requirements when the secrets goes through the network?

**Comment by arkbriar** [comment]
@fuyufjh Do we have an ETA for this issue?

**Comment by fuyufjh** [comment]
> @fuyufjh Do we have an ETA for this issue?

Sorry I don't know much about it. cc. @lmatz

**Comment by lmatz** [comment]
I think it is reasonable and I described the reasons above.
That being said, the complexity or the chances of having the mistakes is transferred from the operator into the kernel, but a question of to what extent, e.g. how big the refactoring will be in terms of the communication between compute nodes, compactors and meta nodes.
