### ISSUE TITLE
bug: dashboard UI doesn't work properly when started with docker-compose

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#8341]
### Describe the bug

![image](https://user-images.githubusercontent.com/10192522/223017095-92cc6099-1b89-49b7-a1e3-d92679ad949b.png)

**Comment by fuyufjh** [comment]
Cannot reproduce. Tried on both https://github.com/risingwavelabs/risingwave-demo/blob/main/docker/docker-compose.yml and https://github.com/risingwavelabs/risingwave/blob/main/docker/docker-compose.yml 🙁

**Comment by xxchan** [comment]
What about 0.1.16?

**Comment by xxchan** [comment]
Might be related to this issue https://github.com/risingwavelabs/risingwave/pull/8241
Since dashboard is proxies to GitHub, there might be breaking changes for dashboard?

**Comment by xxchan** [comment]
The user's image is `nightly-20230102`

**Comment by xxchan** [comment]
`/tables` is added on Jan 13 by @BugenZhao in https://github.com/risingwavelabs/risingwave/pull/7380

So my hypothesis looks correct.

**Comment by xxchan** [comment]
So any old image prior to `nightly-20230113` (or < `0.1.16` for stable images) would break similarly. #8241 would avoid it happen in future images.

**Comment by xxchan** [comment]
In the demo repo, the image is updated from `nightly-20230102` to `v0.1.17` 6 days ago by @neverchanje  https://github.com/risingwavelabs/risingwave-demo/pull/81
