### ISSUE TITLE
bug(parser): debezium json parser incorrectly parses datetime value from mysql

### ISSUE THREAD

**Issue by WillyKidd** [risingwavelabs/risingwave#8359]
### Describe the bug

For the mysql source, the connector node uses the debezium config `time.precision.mode=adaptive_time_microseconds(default)`, which converts the `datetime` value type to `i64` unix epoch time with a precision of milliseconds.

However, the json parser assumes the precision using the number of digits:

https://github.com/risingwavelabs/risingwave/blob/55d143839266b2bed178be74398746f2f5282cc7/src/expr/src/vector_op/cast.rs#L163-L185

The result is that dates outside of the range `[1973-03-03 09:46:40, 5138-11-16 09:46:40)` could be parsed incorrectly without a warning...

### To Reproduce

- insert a datetime `9999-12-31T23:59:59` into mysql
- obtain the cdc json from debezium (`9999-12-31T23:59:59` converted to `253402300799000`, which has 15 digits)
- the risingwave parser returns `1978-01-11T21:31:40.799` without a warning or error (since the parser uses a precision of microseconds with 15 digits)

### Expected behavior

The parser should either parse the `253402300799000` correctly to `9999-12-31T23:59:59`, or return an error.

**Comment by WillyKidd** [comment]
@wangrunji0408

**Comment by wangrunji0408** [comment]
cc @xiangjinwu Any ideas?

**Comment by xiangjinwu** [comment]
> The connector node uses the debezium config `time.precision.mode=adaptive_time_microseconds(default)`, which converts the `datetime` value type to `i64` unix epoch time with a precision of milliseconds.

As the issue itself shows, it is very easy to get microseconds vs milliseconds wrong.

We could document our `timestamptz` type as only supporting values in `[1973-03-03 09:46:40, 5138-11-16 09:46:40)`. Anyways we are already not supporting the full range as PostgreSQL's `4713 BC` - `294276 AD`.

If we do want to be more compatible here, we should keep `i64_to_timestamptz` untouched. When the parser can make sure the input is microseconds in a specific context, call something like `us_to_timestamptz` rather than `i64_to_timestamptz`.

**Comment by WillyKidd** [comment]
It is not possible for the parser to detect such an error, since the parser does not know the precision of the value (milli/micro)...

For example, `9999-12-31T23:59:59` is converted to microseconds by debezium, and the parser receives the value `253402300799000`, which has 15 digits. The parser than assumes that it is in milliseconds, and returns `1978-01-11T21:31:40.799`, and the parser has no trivial way of knowing thether this is correct or not!

Therefore I suggest that we document this issue, and ask the user to avoid `timestamp`/`datetime` values outside of our supported range `[1973-03-03 09:46:40, 5138-11-16 09:46:40)` in their source tables :)

@neverchanje

**Comment by WillyKidd** [comment]
I have opened an issue here: https://github.com/risingwavelabs/risingwave-docs/issues/957 :)
