### ISSUE TITLE
bug: Frontend crashed for large query

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#8369]
### Describe the bug

From slack community: https://risingwave-community.slack.com/archives/C02T3F7UYM6/p1678085858254619

```
dev=> select * from t;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

Need reproduce 

### Additional context

About 40 million data points in t.

**Comment by kwannoel** [comment]
Known issue? #4807

**Comment by kwannoel** [comment]
Hmm slightly different. This one was just a single table.

**Comment by chenzl25** [comment]
This type of wide-range query seems to pollute the block cache and have an impact on streaming queries as well.

**Comment by liurenjie1024** [comment]
Hmm, it weird. Currently frontend will not buffer all results before sending reply, I guess we have some unbounded buffer some place.

**Comment by liurenjie1024** [comment]
I'll take a look at this.

**Comment by liurenjie1024** [comment]
I can't reproduce this bug in current main(c51bf39e6251a964264cd93f782a9e32f6053660):
<img width="913" alt="image" src="https://user-images.githubusercontent.com/2771941/224977632-90b7df96-08d6-4b21-8e24-2537f2d67e30.png">
<img width="837" alt="image" src="https://user-images.githubusercontent.com/2771941/224977669-0500af99-5711-443a-8626-622e39ba7c0d.png">

The high memory usage(about 5G) of compute node is during insertion, and frontend node's memory usage is quite normal to me.
