### ISSUE TITLE
ci: extracting files in scaling test takes too much time

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#8374]
Before #8326, on "scaling test (deterministic simulation)":
```
_bk;t=1678035269235[32;1m   Extracted[0m [1m63[0m files to [1m/tmp/nextest-archive-oA0Tga[0m in 7.60s
```

After it:
```
2023-03-06 12:00:11 UTC | Extracted 63 files to /tmp/nextest-archive-0zQhiA in 7m 36.09s
```

~Not sure whether it's related to the debug-info... 😟 cc @fuyufjh~ Seems not relevant. `ci-sim` is based on `dev` profile and the artifacts are not built with `build.sh`.

**Comment by huangjw806** [comment]
@liurenjie1024 has increased the timeout time on main, if it is a bug, we need to change it back after we fix it. https://github.com/risingwavelabs/risingwave/pull/8409

**Comment by BugenZhao** [comment]
I believe it's a bug.

**Comment by BugenZhao** [comment]
cc @xxchan @wangrunji0408

**Comment by xxchan** [comment]
Can't reproduce locally.

**Comment by xxchan** [comment]
I know the reason

**Comment by xxchan** [comment]
https://github.com/nextest-rs/nextest/issues/830
