### ISSUE TITLE
fix & refactor(table): use `dist_key_in_pk` instead of `distribution_key` 

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#8377]
In our system, all the table's distribution keys are always in the primary key. And we are more care about the distribution key from the primary key or its prefix for partition pruning.

 https://github.com/singularity-data/risingwave/blob/main/src/stream/src/common/table/state_table.rs
https://github.com/singularity-data/risingwave/blob/main/src/storage/src/table/batch_table/storage_table.rs

Also, the distribution keys can not express the actual indices in the read prefix, especially when the primary key has duplications. https://github.com/risingwavelabs/risingwave/issues/7698

- [x] add an optional `dist_key_in_pk` field in the table's proto. use it to fix #7698 
- [ ] refactor other executors to use `dist_key_in_pk`  and remove the `distribution_key` field

**Comment by st1page** [comment]
c.c. @yuhao-su @BugenZhao @wcy-fdu

**Comment by yuhao-su** [comment]
LGTM

**Comment by lmatz** [comment]
Off the topic, it seems the concept of `distribution key` never appears in the [doc](https://github.com/risingwavelabs/risingwave/tree/main/docs), is it worth to be mentioned?

**Comment by st1page** [comment]
> Off the topic, it seems the concept of distribution key never appears in the [doc](https://github.com/risingwavelabs/risingwave/tree/main/docs), is it worth to be mentioned?
I think not.
currently, the distribution key seems an internal concept. Users can not specify the distribution key for any table/mview or internal table and they are all generated by the optimizer. Users can use create index to influence the final distribution key, but it is just physical implementation behind the logical concept such as `Index`, in other words "create a table which is optimized by the key xxx"

**Comment by yuhao-su** [comment]
> currently, the distribution key seems an internal concept

Although it is an internal concept, the user performance might be affected by dist key when it's cardinality is extremely low (e.g. the dist key is gender)

**Comment by lmatz** [comment]
> Users can not specify the distribution key

I thought the doc maintained on Github intends to be developer-facing 🤔

**Comment by st1page** [comment]
oh, sorry, I get it now.
