### ISSUE TITLE
Flexible length KeyPrefix encoding

### ISSUE THREAD

**Issue by Li0k** [risingwavelabs/risingwave#8378]

**Comment by Li0k** [comment]
Implementation:
1. support flexible len type codec for KeyPrefix
2. block iterator switches restart_point according to offset to support flexible len type
3. add BlockV2 structure
3. block iterator supports different Block types

**Comment by Li0k** [comment]
Compatibility:
1. Compatibility of two encodings in Block, differentiated by version.
2. Implement two block_iter to decode two Block types respectively
3. Implement a generic type for sstable_iterator to adapt to different block_iter

**Comment by hzxa21** [comment]
Done by #8379
