### ISSUE TITLE
Use a set instead of vec to represent the group-by clause in the Agg operator

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#8388]
> > Theoretically, the ordering in group-by clause doesn't matter, however, in our LogicalAgg implementation, we store them in a vec so the ordering matter in terms of common sub-plan detection.
> 
> Does this mean that extracting common plan node with `Eq` is too strict? It'll be nice if we can share Agg in this case with a Project automatically inserted.

Actually, I prefer to replace the group-by `vec` with a`bitmap`.

_Originally posted by @chenzl25 in https://github.com/risingwavelabs/risingwave/issues/8159#issuecomment-1442809761_

The advantages of using a set:
- Dedup group key automatically.
- Provide more opportunities for common sub-plan sharing optimization.

**Comment by liurenjie1024** [comment]
Or an ordered vec?

**Comment by chenzl25** [comment]
> Or an ordered vec?

The ordered `vec` might have duplicate keys.

**Comment by liurenjie1024** [comment]
LGTM

**Comment by st1page** [comment]
Sometimes group keys matter e.g. we need to permute the group keys with watermarkshttps://github.com/risingwavelabs/risingwave/issues/6452. or we need to break some assumption of the streaming executor( the group key is not the fitst N columns in the state table's primary key).

**Comment by chenzl25** [comment]
> Sometimes group keys matter e.g. we need to permute the group keys with watermarks #6452. or we need to break some assumption of the streaming executor( the group key is not the fitst N columns in the state table's primary key).

Yes, the group-by set defines the schema of the Agg operator, but we can choose to implement the state table with a primary key in any order you want e.g. based on the watermark information.
