### ISSUE TITLE
ci: staging changes to `main-cron.yml`, `main.yml`

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#8396]
When making PRs, only `pull-request.yaml` gets run.
If we modify `main-cron.yml`, `main.yml` we should also run the new configs to see if they work.

This feature should only be worked on after `main-cron` and `main` stabilizes to avoid blocking PRs. Currently there are still intermittent failures.

**Comment by BugenZhao** [comment]
Good point! Now developers area now to check it by manually triggering the workflow on Buildkite before merging the PR. It would be nice if we can automate it and make it required.

**Comment by kwannoel** [comment]
Resolved, can just add `ci/run-main-cron` to your pull request.
