### ISSUE TITLE
band join

### ISSUE THREAD

**Issue by soundOfDestiny** [risingwavelabs/risingwave#8454]
rfc:
https://github.com/risingwavelabs/rfcs/pull/32
doc:
https://github.com/risingwavelabs/rfcs/blob/dylan/band_join/rfcs/0032-band-join.md

- [x] #8833
- [x] #9014 
- [x] #9212
- [x] #9228

**Comment by st1page** [comment]
could you add some description on which kind of band join you will implement like this?  https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/sql/queries/joins/#interval-joins

- can the band predicate only on the time column? in another word, must it have a watermark?
- must one input is append only 
- must we have another euqal join key?

**Comment by soundOfDestiny** [comment]
> could you add some description on which kind of band join you will implement like this? https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/sql/queries/joins/#interval-joins
> 
> * can the band predicate only on the time column? in another word, must it have a watermark?
> * must one input is append only
> * must we have another euqal join key?

I think current RW shard scheme cannot handle band join without an equal join key.

**Comment by chenzl25** [comment]
I think the first version of the band join should require an equal join key and also should be general to handle updatable input and any basic types(int, varchar, time).  After that, we can implement the second version aka interval join requiring append-only inputs with a watermark on the range condition time column. Finally, we can consider implementing the emit on window closed semantics for the interval join.
