### ISSUE TITLE
bug(doc?): postgres-cdc requires Superuser role

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#8471]
### Describe the bug

postgres-cdc actually require Superuser role, otherwise

```
io.debezium.jdbc.JdbcConnectionException: ERROR: must be superuser to create FOR ALL TABLES publication
```

While the [document](https://www.risingwave.dev/docs/current/ingest-from-postgres-cdc/) says it only need REPLICATION  and CREATEDB role. I followed it and then failed.

### Additional context

See more discussion https://risingwave-labs.slack.com/archives/C03A2PSS8KU/p1678350102536159

**Comment by StrikeW** [comment]
This is related to the creation of the `Publication` in PG.
We use the default value (`all-tables`) of [publication.autocreate.mode](https://debezium.io/documentation/reference/1.9/connectors/postgresql.html#postgresql-publication-autocreate-mode) in the connector. Thus it will create a publication for all tables in the database which requires the user to have `Superuser`.
We plan to use the `filtered` config for it, then it wouldn't need to have `Superuser` role to create the publication. And I think we should suggest users create the required publication in advance before starting the connector. cc @WillyKidd
