### ISSUE TITLE
Discussion: ingest table without primary key from cdc connector

### ISSUE THREAD

**Issue by StrikeW** [risingwavelabs/risingwave#8473]
### Is your feature request related to a problem? Please describe.

Currently, the `CREATE TABLE` statement requires specifying the primary key for the table. And for the case to create a CDC table, it will validate the PK constraint with the source DB, if the PK definition doesn't match we will reject the `CREATE TABLE` request.
So if the table in the source DB doesn't have PK, we cannot load it into RisingWave now.

### Describe the solution you'd like

Candidate solutions:
1. Allow the PK constraint in `CREATE TABLE` to be optional and when users don't specify PK, we will treat the source table as an append-only table in RisingWave.

2. Allow the PK constraint in `CREATE TABLE` to be optional, and users have two options:
  - If they don't specify PK, we will use the whole row as the PK to identify a row uniquely
  - They can specify a PK for the table, and RisingWave will use the PK to identify a row although the PK doesn't exist in upstream
 
Personally, I prefer solution 2 which is more flexible.

**Comment by hzxa21** [comment]
> So if the table in the source DB doesn't have PK, we cannot load it into RisingWave now.

Quick question: for debezium connect with kafka, is it possible to create a cdc stream on a source table if the table doesn't have PK?


> - If they don't specify PK, we will use the whole row as the PK to identify a row uniquely

cc @fuyufjh I remember we have similar discussions before. 

IIUC, the concern of implicitly defining PK for the user is that it is hard for the user to understand what results are correct. 

For example, assuming the source table only have one column `c1` with no PK, there can be multiple rows with the same value on `c1` but implicitly using `c1` as the PK in our system may produce the result as if there is only one row per `c1` value.

**Comment by StrikeW** [comment]
>>So if the table in the source DB doesn't have PK, we cannot load it into RisingWave now.

>Quick question: for debezium connect with kafka, is it possible to create a cdc stream on a source table if the table doesn't have PK?

Yes. @BugenZhao has tried this with the debeizum + Kafka stack. debezium can capture CDC events on the table and publish them to the Kafka topic.

**Comment by tabVersion** [comment]
> > > So if the table in the source DB doesn't have PK, we cannot load it into RisingWave now.
> 
> > Quick question: for debezium connect with kafka, is it possible to create a cdc stream on a source table if the table doesn't have PK?
> 
> Yes. @BugenZhao has tried this with the debeizum + Kafka stack. debezium can capture CDC events on the table and publish them to the Kafka topic.

what does the message look like, got an example?

**Comment by BugenZhao** [comment]
> what does the message look like, got an example?

https://gist.github.com/BugenZhao/44c0afdcb52281354fb20ecc4df0d5a2#file-dbserver1-inventory-t-json-L781

```
mysql> show create table t;
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                           |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `v` int DEFAULT NULL,
  `v2` double DEFAULT NULL,
  `v3` char(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)


mysql> insert into t values (1111, 1111.1, '1111-1');
Query OK, 1 row affected (0.01 sec)

```

**Comment by st1page** [comment]
> Allow the PK constraint in CREATE TABLE to be optional and when users don't specify PK, we will treat the source table as an append-only table in RisingWave.

LGTM, but that still only can subscribe the changelog of upstream Append-only table which can not solve all problems.

> If they don't specify PK, we will use the whole row as the PK to identify a row uniquely

I think user can not accept that. user can insert two or more rows with the same values in the upstream system and they are duplicated int the table

**Comment by hzxa21** [comment]
> > what does the message look like, got an example?
> 
> https://gist.github.com/BugenZhao/44c0afdcb52281354fb20ecc4df0d5a2#file-dbserver1-inventory-t-json-L781
> 
> ```
> mysql> show create table t;
> +-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> | Table | Create Table                                                                                                                                                           |
> +-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> | t     | CREATE TABLE `t` (
>   `v` int DEFAULT NULL,
>   `v2` double DEFAULT NULL,
>   `v3` char(20) DEFAULT NULL
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
> +-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> 1 row in set (0.01 sec)
> 
> 
> mysql> insert into t values (1111, 1111.1, '1111-1');
> Query OK, 1 row affected (0.01 sec)
> ```

What does the dbz message look like if you issue a delete/update in mysql.

Technically CDC source without PK is not an append only source so the tricky part is how to handle detele. We basically need to know exactly what row is deleted in our system if there is no PK (require a scan or some way to look up row id?)

**Comment by BugenZhao** [comment]
Suppose that there're two same rows of `1111, 1111.1, 1111-1` and we delete them in a transaction with `DELETE FROM t`:

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/25862682/224265086-3ec89dc8-82b9-473a-9765-31eee76b7746.png">

**Comment by st1page** [comment]
> Suppose that there're two same rows of 1111, 1111.1, 1111-1 and we delete them in a transaction with DELETE FROM t:

suppose a harder situation...

```SQL
CREATE TABLE t(v int);
Insert into t values (1). (1), (1);
Delete from t where v =1 limit 2;
```

**Comment by fuyufjh** [comment]
> 1. Allow the PK constraint in CREATE TABLE to be optional and when users don't specify PK, we will treat the source table as an append-only table in RisingWave.

1 doesn't make sense to me because there are definitely updates on that table. In another words, I don't think "missing PK" means append-only. No relation between them.

> 2. Allow the PK constraint in CREATE TABLE to be optional, and users have two options:
>   - If they don't specify PK, we will use the whole row as the PK to identify a row uniquely

This won't work because there may be more than one row with all values identical.

>   - They can specify a PK for the table, and RisingWave will use the PK to identify a row although the PK doesn't exist in upstream

This seems just pretending to work...

-------

May I ask the motivation? Is it necessary or urgent?

Because in my mind, most data pipelines deoesn't support or have poor support for non-PK tables. (e.g. [DTS](https://www.alibabacloud.com/help/zh/data-transmission-service/latest/configure-one-way-data-synchronization-between-apsaradb-rds-for-mysql-instances)). Compared with doing such tricky (and low performance) solution, I would rather recommend users to just create a PK.

**Comment by yuhao-su** [comment]
Just a thought...

In postgres cdc there is a `[REPLICA IDENTITY](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-replica-identity)`. When set to default:
> If a table does not have a primary key, the connector does not emit UPDATE or DELETE events for that table. For a table without a primary key, the connector emits only create events. Typically, a table without a primary key is used for appending messages to the end of the table, which means that UPDATE and DELETE events are not useful.

Although other dbs like MySQL and SQLServer do not have such specifications, we can allow users to do CDC without primary key if they know they only append their source table. We can force our connector to ignore/warn any UPDATE/DELETE.

**Comment by StrikeW** [comment]
For now, we can draw a conclusion that users need to create a primary key for the CDC tables.
