### ISSUE TITLE
fix(local-mode): Strip the backtrace from `RwError`

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#8500]
### Describe the bug

When a frontend errors with local mode, sometimes it will return a `RwError` with a backtrace. It is too verbose for the user, so we should strip the backtrace.

### Additional context
See: https://github.com/risingwavelabs/risingwave/pull/8493 for an example

**Comment by liurenjie1024** [comment]
I'm working on some refactoring in propogating user error.

**Comment by liurenjie1024** [comment]
#8478  is expected to resolve this, feel free to reopen if it appears again.
