### ISSUE TITLE
optimizer: merge `StreamIndexScan` into `StreamTableScan`

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#8534]
`StreamIndexScan` was introduced for delta-join in https://github.com/risingwavelabs/risingwave/pull/2107. But as we refactor it, it seems there's not much difference in the implementation between `IndexScan` and `TableScan`, especially after we introduce the `ChainType`. Should we merge them into one to avoid code duplication?

cc @chenzl25 @st1page @fuyufjh

**Comment by fuyufjh** [comment]
Sounds reasonable. 🤔 What's the initial motivation of introducing StreamIndexScan?

**Comment by chenzl25** [comment]
Yes, I think they have no essential difference.

**Comment by chenzl25** [comment]
> Sounds reasonable. 🤔 What's the initial motivation of introducing StreamIndexScan?

IMO, creating a delta join on existing mv just needs to consume existing data from one data flow. FYI, N way delta join has N 
separate data flows. Previously, it is likely that the index scan use a different strategy to consume the existing data.

**Comment by Eurekaaw** [comment]
close as completed #8567
