### ISSUE TITLE
bug(madsim): Kafka mock produces EOF

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#8549]
### Describe the bug

Kafka is not meant to produce an EOF even when the data is exhausted

### To Reproduce

As seen here: https://buildkite.com/risingwavelabs/pull-request/builds/19271#0186d84a-07af-4cab-9c5b-28b8428ec29a

**Comment by wangrunji0408** [comment]
https://github.com/risingwavelabs/risingwave/pull/8493#issuecomment-1469590643
