### ISSUE TITLE
Datagen connector should support TimestampTz

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#8550]
### Is your feature request related to a problem? Please describe.

Currently, datagen always genrates `Timestamp` type with the local timezone. However the default timezone of PostgreSQL is UTC+0.

Before implementing the feature, we should discuss the behavior concisely.

**Comment by tabVersion** [comment]
how about generating some i64 with the same logic as `Timestamp`

**Comment by xiangjinwu** [comment]
I will be doing this and migrate integration tests using `timestamp` as event time to `timestamptz`.

Related: there is a golang datagen and it has been updated to support both in #12239
