### ISSUE TITLE
Separate source file and generated file for parser/planner tests

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#8557]
There are some different requirements in the test file.

For source file:
* Readability
* **Extensibility**
* Focus on the input SQL
* **Can add comments**

For generated file:
* Readability
* Detail info
* Diff introduced by each PR

Currently, we add tests to `yaml` file, and auto correct them by our programs in the same file, it's not a good practice.

**Comment by xxchan** [comment]
Once talked about this here  https://github.com/risingwavelabs/risingwave/issues/5461#issuecomment-1252722721

**Comment by xxchan** [comment]
BTW, can we directly use snapshot testing libraries like https://github.com/mitsuhiko/insta 

Is planner test special? 🤔

**Comment by TennyZhuang** [comment]
> Is planner test special? 🤔

cc @st1page

**Comment by BugenZhao** [comment]
One use case of the planner test for me is to check the plan and the original SQL together...

**Comment by st1page** [comment]
> One use case of the planner test for me is to check the plan and the original SQL together...

+1, why do we need to split them? It is hard to find the corresponding result of some specific SQL.

**Comment by st1page** [comment]
> Extensibility

extend what

> Can add comments

We can add comments now

> Currently, we add tests to yaml file, and auto correct them by our programs in the same file, it's not a good practice.

why

**Comment by yuhao-su** [comment]
> Currently, we add tests to yaml file, and auto correct them by our programs in the same file, it's not a good practice.

run `./risedev apply-planner-test` instead of `./risedev do-apply-planner-test` will correct them in a separate file.

**Comment by st1page** [comment]
> BTW, can we directly use snapshot testing libraries like https://github.com/mitsuhiko/insta
> 
> Is planner test special? thinking

I think not :thinking: we can have a try.

**Comment by TennyZhuang** [comment]
> > Can add comments
> 
> We can add comments now


You can’t. You can only add comments in SQL instead of yaml, because serde-yaml will ignore that.

**Comment by TennyZhuang** [comment]
> One use case of the planner test for me is to check the plan and the original SQL together...

We definitely can dump the SQL too.

**Comment by TennyZhuang** [comment]
> > Currently, we add tests to yaml file, and auto correct them by our programs in the same file, it's not a good practice.
> 
> run `./risedev apply-planner-test` instead of `./risedev do-apply-planner-test` will correct them in a separate tmp file.

Of course I know that, but it’s hard to edit the file.

I want to submit a small source file and a large result file for diff to git.

**Comment by TennyZhuang** [comment]
> extend what?

Extend new tests

**Comment by TennyZhuang** [comment]
Risinglight has already done the similar refactor by @skyzh 

https://github.com/risinglightdb/risinglight/tree/main/tests/planner_test

In every practices, generated file is not suitable for editting.

**Comment by xxchan** [comment]
> > One use case of the planner test for me is to check the plan and the original SQL together...
> 
> +1, why do we need to split them? It is hard to find the corresponding result of some specific SQL.

I used to think so. But I guess we can just put both input and output in the generated file.

**Comment by xxchan** [comment]
> > Currently, we add tests to yaml file, and auto correct them by our programs in the same file, it's not a good practice.
> 
> why

Conflict resolution will be much easier for separated source files. You can just ignore the conflict in the generated file.
