### ISSUE TITLE
E2e testing for binary format

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#8560]
We need to extend our e2e test framework to test binary format too.

**Comment by ZENOTME** [comment]
Extended mode will return the result as binary format and we have accroding test.🤔
https://github.com/risingwavelabs/risingwave/blob/30a8946c9d2689f19c92dcf2a6a1753b5b8da944/ci/scripts/run-e2e-test.sh#L78

**Comment by kwannoel** [comment]
> Extended mode will return the result as binary format and we have accroding test.🤔
> https://github.com/risingwavelabs/risingwave/blob/30a8946c9d2689f19c92dcf2a6a1753b5b8da944/ci/scripts/run-e2e-test.sh#L78
> 

My idea is to run all e2e queries in extended query mode too, similar to how we parameterize on distributed and local mode. So we have larger coverage.

May require extensions to our e2e test runner or maybe introduce a session variable for it?

**Comment by xxchan** [comment]
related earlier discussion https://github.com/risingwavelabs/risingwave/issues/4483

**Comment by ZENOTME** [comment]
> My idea is to run all e2e queries in extended query mode too, similar to how we parameterize on distributed and local mode. So we have larger coverage.

Agree to larger coverage for extended mode. We can reuse some test and add some specific test for extended.

// extendeds.slt 
include ./basic/*.slt.part
include ./types/*.slt.part
include ./extended_specific.slt

Now we maintain a extended.slt separatlly, I think think that will cause miss some test.🤔 Having a common basic part can decrease this possibility.

> May require extensions to our e2e test runner or maybe introduce a session variable for it?

Did you mean that add a session variable to set return format, e.g. `set return_format BINARY`
