### ISSUE TITLE
improve batch query error message when cluster is under recovery

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#8561]
When cluster is under recovery, batch query will respond with `ERROR: QueryError: internal error: Storage error: Hummock error: ReadCurrentEpoch error Cannot read when cluster is under recovery. read 4030392793300992 < min current epoch 18446744073709551615.`
I thought this message essentially has told the reason of error is "the cluster is under recovery", but it still misleads user/developers several times.

**Comment by BugenZhao** [comment]
18446744073709551615 is exactly `u64::MAX`. Do we use this as the invalid value of something? 🤔

**Comment by zwang28** [comment]
> 18446744073709551615 is exactly `u64::MAX`. Do we use this as the invalid value of something? 🤔

Yes, it means the compute node has not received any checkpoint barrier since last shared buffer clear caused by recovery.

**Comment by liurenjie1024** [comment]
I think this is similar to the difference between Display and Debug.
