### ISSUE TITLE
Review existing usages of the inverse method of ColIndexMapping

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#8600]
The `inverse()` method of `ColIndexMapping` seems to have the potential to cause bugs If the map is not invertible. It is better to remove this method if possible.

**Comment by BugenZhao** [comment]
I guess we can first make `inverse` return an `Option` and replace all current occurrences with `.unwrap()` to let misuses expose earlier. 🤔

**Comment by xxchan** [comment]
Example of bug: https://github.com/risingwavelabs/risingwave/pull/8598
