### ISSUE TITLE
unrealistic memory allocated by streaming on modified q17 with date as group key

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#8604]
### Describe the bug

Increased up to 500GB over 3 hours. This is just a screenshot of a quick repro, in a short window of time:

<img width="736" alt="Screenshot 2023-03-16 at 7 40 19 PM" src="https://user-images.githubusercontent.com/47273164/225607372-41ed5144-88c7-4072-ae9b-96f2a21a9a27.png">

### To Reproduce

Machine:
- C5.2x large. (16 GB RAM 8 vCPU)
- Linux

Commit: https://github.com/risingwavelabs/risingwave/commit/d06674b2c1c4a859abbc9bb70fddb5acdc430a14
Nexmark-bench commit: https://github.com/risingwavelabs/nexmark-bench/commit/016a9558593b2759fb3a5d63f16a698a59a76f86

1. Setup `nexmark-bench`.
2. Run gen_events = 1 billion.
3. Run nexmark_ddl: https://github.com/risingwavelabs/flink-bench/blob/nexmark/standalone/scripts/sql/nexmark_ddl.sql
4. Run stream query:
```sql
CREATE SINK nexmark_q17 AS
    SELECT auction,
           CAST(date_time AS DATE)                           AS day,
           count(*)                                                   AS total_bids,
           count(*) filter (where price < 10000)                      AS rank1_bids,
           count(*) filter (where price >= 10000 and price < 1000000) AS rank2_bids,
           count(*) filter (where price >= 1000000)                   AS rank3_bids,
           min(price)                                                 AS min_price,
           max(price)                                                 AS max_price,
           avg(price)                                                 AS avg_price,
           sum(price)                                                 AS sum_price
    FROM bid
    GROUP BY auction, CAST(date_time AS DATE)
    WITH ( connector = 'blackhole', format = 'append_only', force_append_only = 'true');
```

### Expected behavior

We need to set a cap on this in our bench environments. How is streaming memory allocated? I was under the impression it just use the machine's RAM, and won't exceed until 500GB.

Should not use so much memory too, just few hundred MB according to similar q17 query memory profiles.

### Additional context

Ctrl-f from memory allocated by streaming:
[grafana.pdf](https://github.com/risingwavelabs/risingwave/files/10990185/grafana.pdf)

**Comment by st1page** [comment]
> Another anomaly I encountered. This benchmark took 3 hours but didn't finish, even with a nearly 2x throughput of 380,000r/s compared to normal q17.
> 
> On the other hand, with normal q17, throughput was just 210,000r/s, but it finished in an hour and a half.

just to confirm. is the throughput of bid?

**Comment by kwannoel** [comment]
> > Another anomaly I encountered. This benchmark took 3 hours but didn't finish, even with a nearly 2x throughput of 380,000r/s compared to normal q17.
> > 
> > On the other hand, with normal q17, throughput was just 210,000r/s, but it finished in an hour and a half.
> 
> just to confirm. is the throughput of bid?

Source throughput. Can take a look at the grafana pdf. Although its truncated, it has the same figures.

**Comment by lmatz** [comment]
> This benchmark took 3 hours but didn't finish

Is it deployed by `risedev`? not `kube-bench`
And it didn't crash halfway and recovered, did it?

**Comment by kwannoel** [comment]
> > This benchmark took 3 hours but didn't finish
> 
> Is it deployed by `risedev`? not `kube-bench` And it didn't crash halfway and recovered, did it?

Yes, risedev with configurations listed here: https://github.com/risingwavelabs/flink-bench/blob/nexmark/standalone/scripts/risedev-profiles.user.yml

**Comment by kwannoel** [comment]
> > > Another anomaly I encountered. This benchmark took 3 hours but didn't finish, even with a nearly 2x throughput of 380,000r/s compared to normal q17.
> > > On the other hand, with normal q17, throughput was just 210,000r/s, but it finished in an hour and a half.
> > 
> > 
> > just to confirm. is the throughput of bid?
> 
> Source throughput. Can take a look at the grafana pdf. Although its truncated, it has the same figures.

![Screenshot 2023-03-16 at 8 30 06 PM](https://user-images.githubusercontent.com/47273164/225617570-c877f739-3985-4029-963a-63327fe70668.png)

**Comment by kwannoel** [comment]
> And it didn't crash halfway and recovered, did it?

Sorry I missed the second question. But I don't think so. The source throughput was consistently above 300,000r/s just before I killed it.

**Comment by kwannoel** [comment]
New grafana + heap profile: https://www.notion.so/risingwave-labs/15bd2d5182e94df7ad54077aa7abbb7b?pvs=4.

**Comment by yuhao-su** [comment]
I'm a little confused by the figure 500GB. How can the memory usage reach 500G when the EC2 has only 16 GB RAM

**Comment by BugenZhao** [comment]
+1 confused. Is this an issue of statistics?

**Comment by kwannoel** [comment]
> +1 confused. Is this an issue of statistics?

- That seems to be the issue. Let me update to issue title to reflect that.
- The other anomaly is why it took so long to run, >3 hours instead of 1.5 hours.
- The strange thing is that other similar queries, e.g. unmodified q17 does not have this issue, the memory profile looks normal:

https://www.notion.so/risingwave-labs/bd7f2868eead4ba7ae637309a3e5f014?pvs=4
 
![Screenshot 2023-03-20 at 2 43 03 PM](https://user-images.githubusercontent.com/47273164/226265942-b7a9b696-30bf-4fa6-a745-301cb8338b91.png)

**Comment by kwannoel** [comment]
Same issue on the following query:
```
CREATE SINK nexmark_q17 AS
    SELECT auction,
           count(*)                                                   AS total_bids,
           count(*) filter (where price < 10000)                      AS rank1_bids,
           count(*) filter (where price >= 10000 and price < 1000000) AS rank2_bids,
           count(*) filter (where price >= 1000000)                   AS rank3_bids,
           min(price)                                                 AS min_price,
           max(price)                                                 AS max_price,
           avg(price)                                                 AS avg_price,
           sum(price)                                                 AS sum_price
    FROM bid
    GROUP BY auction
    WITH ( connector = 'blackhole' );
```

**Comment by kwannoel** [comment]
<img width="720" alt="Screenshot 2023-03-20 at 6 57 50 PM" src="https://user-images.githubusercontent.com/47273164/226320149-0132408e-683a-41f4-b59b-00d8e90bf1ae.png">

**Comment by st1page** [comment]
> Does each source split has input incoming?
> Is it possibly related to [#8451 (comment)](https://github.com/risingwavelabs/risingwave/issues/8451#issue-1616807618), I am not entirely sure about the context though

I think not if we do not define the watermark on the source. The watermark here is the streaming system’s watermark instead of the watermark in memory management

**Comment by kwannoel** [comment]
Encountered in q5 too.

![image](https://user-images.githubusercontent.com/47273164/226523198-5cf4ff3b-3c86-4a09-8853-c71e03684359.png)

**Comment by liurenjie1024** [comment]
> I'm a little confused by the figure 500GB. How can the memory usage reach 500G when the EC2 has only 16 GB RAM

It's possible since virtual memory space is more than physical memory.

**Comment by kwannoel** [comment]
Can anyone else reproduce this? Or observe this phenomenon? Seems like on different machines with the same specs I can't reproduce it again 😕.

- Spawning a new machine to try and reproduce the same results.
- Taking a closer look, maybe there's some other difference...
