### ISSUE TITLE
optimizer: void always-false filter's upstream

### ISSUE THREAD

**Issue by Eurekaaw** [risingwavelabs/risingwave#8609]
### Is your feature request related to a problem? Please describe.

Although `LogicalScan` with always-false predicates has been specifically optimized, another case where the downstream is not a scan but e.g. a table function ( `select * from generate_series(1,  1000000000, 1) where 1= 0;`) shall also be optimized such that no real physical scan being executed.

### Describe the solution you'd like

return empty value immediately

**Comment by chenzl25** [comment]
Supported by https://github.com/risingwavelabs/risingwave/pull/8629.
