### ISSUE TITLE
Expose storage configs and metadata via SQL

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#8612]
Currently we rely on command line tool (risectl) to inspect storage configs and metadata. A more convenient and isolated way is to leverage SQL, to avoid the burden on building/copying risectl, setting up network connection, and sshing onto the box. We can create system tables under `rw_catalog` to display these information.

Configs:
- [ ] [Compaction Group Configs](https://github.com/risingwavelabs/risingwave/blob/d1a35864329fe2a045dcb78cbce38cfad687c929/src/meta/src/hummock/model/compaction_group_config.rs#L28)
- [ ] [Write Stall Limit](https://github.com/risingwavelabs/risingwave/blob/d1a35864329fe2a045dcb78cbce38cfad687c929/src/meta/src/hummock/manager/versioning.rs#L92)
- [ ] [Vacuum/GC Configs](https://github.com/risingwavelabs/risingwave/blob/d1a35864329fe2a045dcb78cbce38cfad687c929/src/meta/src/manager/env.rs#L75)

For configs, we can use the following schema to store the information:
```sql
Name           |  Type     
--------------+--------------
 config_name   | Varchar
 config_value  | Varchar
```

Metadata:
- [x] [Current/Checkpointed Hummock Version](https://github.com/risingwavelabs/risingwave/blob/d1a35864329fe2a045dcb78cbce38cfad687c929/src/meta/src/hummock/manager/versioning.rs#L70) (i.e. MANIFEST)
- [x] [Hummock Version Delta](https://github.com/risingwavelabs/risingwave/blob/d1a35864329fe2a045dcb78cbce38cfad687c929/src/meta/src/hummock/manager/versioning.rs#L97)
- [x] [Pinned Versions/Snapshots](https://github.com/risingwavelabs/risingwave/blob/d1a35864329fe2a045dcb78cbce38cfad687c929/src/meta/src/hummock/manager/versioning.rs#L98)
- [x] [Branched SST info](https://github.com/risingwavelabs/risingwave/blob/d1a35864329fe2a045dcb78cbce38cfad687c929/src/meta/src/hummock/manager/versioning.rs#L83)

For metadata, we need to decide what the suitable schema is for each of them. We can start simple by using jsonb for metadata with nested data structure.

**Comment by BanBuDu0** [comment]
may I take this task, I can do this in my weekend and  weekday late night

For this task, basically we just do:
1. define the config table schema
2. get the config from meta server by rpc.
3. return the structed config data

In this case, I found two existing rpc relations:

+ risectl_list_compaction_group -> Compaction Group Configs
+ get_current_version -> Write Stall Limit

But I can't find a rpc to get [Vacuum/GC Configs] 
can I define one by  myself?

**Comment by yufansong** [comment]
Thank you for your comments. However, I'm sorry to inform you that this task was already assigned to me the previous day. Perhaps you could take a look at other tasks that are available.

**Comment by yufansong** [comment]
> may I take this task? I can do this in my weekend and weekday late night
> 
> For this task, basically we just do:
> 
> 1. define the config table schema
> 2. get the config from meta server by rpc.
> 3. return the structed config data
> 
> In this case, I found two existing rpc relations:
> 
> * risectl_list_compaction_group -> Compaction Group Configs
> * get_current_version -> Write Stall Limit
> 
> But I can't find a rpc to get [Vacuum/GC Configs] can I define one by myself?

Thank you for your comments. However, I'm sorry to inform you that this task was already assigned to me the previous day. Perhaps you could take a look at other tasks that are available.

**Comment by hzxa21** [comment]
@yufansong Any updates?
