### ISSUE TITLE
feat: support any combination of distinct and ordered agg calls

### ISSUE THREAD

**Issue by stdrc** [risingwavelabs/risingwave#8614]
https://github.com/risingwavelabs/risingwave/blob/b862295fe4705e769c2facbaf6a81cc598c35767/src/frontend/src/optimizer/plan_node/logical_agg.rs#L456-L460

We currently have a `syntax_check` in frontend to ban some unsupported combinations of agg calls. However, after #8100, we now have backend distinct implementation for streaming, so it's possible to lift the limitation to allow any combination of agg calls. E.g.:

```sql
create table t (a int, v varchar);
select count(distinct a), string_agg(v, ',' order by a desc) from t;
select count(distinct a), string_agg(v, ',') from t;
select string_agg(distinct v, ',' order by v) from t;
```

Tasks:

- Support distinct agg calls with `MaterializedInputState`.
- Revisit the batch implementation of distinct agg, may need rewriting/refactoring.
  - #9432
- Turn `syntax_check` to sth like `can_two_phase_distinct`, and only apply `DistinctAggRule` if possible.

**Comment by xiangjinwu** [comment]
To clarify on "any combination", there is one restriction in [PostgreSQL](https://www.postgresql.org/docs/15/sql-expressions.html#SYNTAX-AGGREGATES):
> If `DISTINCT` is specified in addition to an `order_by_clause`, then all the `ORDER BY` expressions must match regular arguments of the aggregate; that is, you cannot sort on an expression that is not included in the `DISTINCT` list.
