### ISSUE TITLE
main-cron failed on e2e test(release)

### ISSUE THREAD

**Issue by wcy-fdu** [risingwavelabs/risingwave#8640]
### Describe the bug

https://buildkite.com/risingwavelabs/main-cron/builds/390#0186fdc3-0408-46fe-a388-fe5d0cbc3ce8

**Comment by fuyufjh** [comment]
@yezizp2012 @tabVersion Please take a look

**Comment by yezizp2012** [comment]
It seems like a backup test issue, Cc @zwang28 .

**Comment by zwang28** [comment]
It's caused by stale test config after some system parameter refactor.
Please merge main and it should works now. @wcy-fdu
