### ISSUE TITLE
discussion(memory-manager): control capacity (now - watermark) instead of watermark

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#8643]
### Is your feature request related to a problem? Please describe.

Is it better to let the memory manager control the physical_now - watermark_time  instead of watermark_time?

- Controlling watermark_time means that the MM must run periodically, otherwise the memory usage could explode. This is due to the nature of watermark_time - it is incrementing continously
- Controlling physical_now - watermark_time actually limits the max length of time that can be cached. Even if MM didn’t work for a short period, the total memory usage should still be bounded.

In today’s case, the streaming memory soared suddenly and caused the OOM finally. Meanwhile, the CPU usage is almost full so MM might not be able to react to it in time. I think my proposal can mitigate this.

------

Original thread: https://risingwave-labs.slack.com/archives/C03Q34JHLLC/p1679292361308189

Today's case: https://risingwave-labs.slack.com/archives/C0423G2NUF8/p1679284066099009

**Comment by kwannoel** [comment]
Seems related to: https://github.com/risingwavelabs/risingwave/issues/8604#issuecomment-1476015140
