### ISSUE TITLE
librdkafka: FAIL 127.0.0.1:XXXX/0: Connect to ipv4

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#8656]
### Describe the bug

Reported by @Zsombor Földesi from Slack: https://risingwave-community.slack.com/archives/C03BW71523T/p1679323839584629

It seems like no matter what value I set in `properties.bootstrap.server`
```
	CREATE source IF NOT EXISTS source_abc (
	   dummy varchar
	)
	WITH (
	   connector='kafka',
	   topic='my_topic_name',
	  properties.bootstrap.server='20.223.195.100:37655',
	  scan.startup.mode = 'earliest'
	
	)
	ROW FORMAT JSON;
```
The meta node throwing error:
```
meta-node-0      | 2023-03-20T14:44:58.042860Z ERROR librdkafka: librdkafka: FAIL [thrd:127.0.0.1:37655/0]: 127.0.0.1:37655/0: Connect to ipv4#127.0.0.1:37655 failed: Connection refused (after 0ms in state CONNECT, 3 identical error(s) suppressed)
```
The weird this is that I tried multiple option in `.server` value for the IP (from localhost, 127.0.0.1, or even external IP) I’m unable to setup a connection and the meta-node-0 is always looking at 127.0.0.1xxx.
The same output happens either with https://github.com/risingwavelabs/risingwave/blob/main/docker/docker-compose.yml and/or w/ the playground docker image.

**Comment by tabVersion** [comment]
close as not reproduced
