### ISSUE TITLE
Optimize `SerializedKeySerializer::append`

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#8683]
<img width="1905" alt="image" src="https://user-images.githubusercontent.com/9161438/226552503-c9ba29b4-d7b1-4d85-bc2e-d20cb15ae53c.png">
Too many CPU times are wasted on `(Vec|FixedBitSet)::grow`, we should reserve a reasonable cap.

**Comment by kwannoel** [comment]
https://github.com/risingwavelabs/risingwave/pull/8885 will fix grow from `vec`.

`FixedBitSet::grow` will be fixed in another PR.

**Comment by st1page** [comment]
done, related issue: https://github.com/risingwavelabs/risingwave/issues/9305
