### ISSUE TITLE
Optimize lru_cache get-and-put pattern in HashAgg

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#8687]
We should use `get_mut` here, although some unsafe codes are necessary.

The work was done in #7752, however it can't be merged now.

<img width="250" alt="image" src="https://user-images.githubusercontent.com/9161438/226559710-73d91fc6-cc00-4780-ba58-725d6dbdead5.png">

**Comment by kwannoel** [comment]
> We should use `get_mut` here, although some unsafe codes are necessary.
> 
> The work was done in #7752, however it can't be merged now.
> 
> <img alt="image" width="250" src="https://user-images.githubusercontent.com/9161438/226559710-73d91fc6-cc00-4780-ba58-725d6dbdead5.png">

How does `get_mut` optimize lru_cache access?

**Comment by lmatz** [comment]
> How does get_mut optimize lru_cache access?

otherwise, two extra copies and two extra O(1) operations
