### ISSUE TITLE
discussion(compaction): Concurrent l0 to base_level compaction

### ISSUE THREAD

**Issue by Li0k** [risingwavelabs/risingwave#8707]
### Background
In the compactor scale policy test, we observed that when the system faced a large number of write requests, the compactor triggers a scaling operation, but the compactor CPU is not fully utilized after scaling.
<img width="934" alt="image" src="https://user-images.githubusercontent.com/15023748/226815001-4726927a-2e9b-418c-9372-37b77a52e44a.png">

The number of l0s in Ism keeps rising and the number of sub_level layers piles up.
<img width="1867" alt="image" src="https://user-images.githubusercontent.com/15023748/226815178-0f28792c-8e82-4300-b528-d5236723552f.png">

The number of compact tasks in the system is low, and most of the l0 to base_level compaction pick fails due to pending status.
<img width="1870" alt="image" src="https://user-images.githubusercontent.com/15023748/226815536-cf72c51d-d5e3-4099-9011-d8ae87cfa38d.png">

The Compaction Task Count shows that the l0 to base_level compaction in the system is serial and the overall Compaction Through is low.
<img width="1869" alt="image" src="https://user-images.githubusercontent.com/15023748/226816172-e4909af9-9d84-4edf-a99b-4a9875fe8443.png">

The task that is performing the Compaction contains the entire number of base_level files in one task, which is processed by only one compactor.
<img width="931" alt="image" src="https://user-images.githubusercontent.com/15023748/226816482-9e798e96-f567-4abb-835c-7cb5b8a94ec3.png">

### Investigate
With the base_level_compaction_picker implementation, we will select multiple layers of sub_level compacts together to base_level within the condition, reducing the number of sub_level layers within a task as much as possible. However, when picking a task, the entire layer of sst is included in one task, which means that a huge key range is included, with a large base-level overlap range, leading to the serialization of subsequent tasks.

<img width="920" alt="image" src="https://user-images.githubusercontent.com/15023748/226817029-e10555a6-360d-4ffc-83b7-a40cbad7c077.png">

### discussion
1. make the l0 to base_level compaction parallelizable by splitting the key_range of the sub-level, how do we do the splitting? (How to select split keys)
2. should the granularity of splitting be inside the table or in the whole key range? (across table_id)
3.  if the split key is generated in the whole key range, how to update the split key when the key range changes
4. how to align files in sub level by split keys

**Comment by Li0k** [comment]
In the further plan, we plan to place tables with large amounts of data in a separate compaction group.I think the above problem will only be encountered in tables with large enough writes, so to simplify the above implementation, we can consider executing the split key logic inside the table only.
In this case, the internal data of each table is written by the upper-level CN according to different VNode, and the data is divided into different VNode according to Hash, so we can assume that the data is evenly distributed. Therefore, the split key can be generated directly inside the table based on the VNode. The advantage of this is that we can calculate the split key directly based on the TableId and VNode statically instead of changing it dynamically based on read and write requests, simplifying the implementation and providing better alignment. (Dynamic calculation of split key is more adaptive but more complex, and the alignment will be broken when the split key falls behind, which is unpredictable)

**Comment by Li0k** [comment]
### Test
- 2 hour test
- compare main branch and optimize branch

```
[benchmark.nexmark]
query = "q4,q7"

[benchmark.nexmark.source]
person = { split_num = 20, min_event_gap_in_ns = 0 }
auction = { split_num = 20, min_event_gap_in_ns = 0 }
bid = { split_num = 20, min_event_gap_in_ns = 0 }

[benchmark.risingwave.replicas]
meta = 1
frontend = 1
compute = 2
compactor = 2

[benchmark.risingwave.resources.compute]
cpu = { limit = "8", request = "7200m" }
mem = { limit = "16Gi", request = "15Gi" }

[benchmark.risingwave.resources.compactor]
cpu = { limit = "8", request = "8" }
mem = { limit = "8Gi", request = "8Gi" }
scale = { compaction_bytes = 4294967296 }
```

main on the left, branch on the right
- main 
- branch
   - partition by vnode 
   - move the big state table to the dedicated compaction group
   - pick multi l0_non_overlap_sub_level  instead of the whole level, and Concurrent l0 to base_level_comapction

#### compactor cpu
- main
<img width="734" alt="image" src="https://user-images.githubusercontent.com/15023748/232992347-b09140d2-802c-4d8b-98d5-7ae1d54682ea.png">

- branch
<img width="731" alt="image" src="https://user-images.githubusercontent.com/15023748/232992448-90fd4707-13de-43b2-afa7-72166e276db2.png">

Consistent with expectations compactor cpu resources are more fully utilized


#### source throughput
<img width="733" alt="image" src="https://user-images.githubusercontent.com/15023748/232988217-dce37f18-e5e5-44ba-968d-cb59dcce1861.png">

- main
<img width="730" alt="image" src="https://user-images.githubusercontent.com/15023748/232991400-94eb2845-9b3b-4f74-a90a-997493738da6.png">

- branch
<img width="734" alt="image" src="https://user-images.githubusercontent.com/15023748/232991511-a4c06b76-156a-45a7-b0f2-8ca657548f32.png">


#### barrier latency
<img width="731" alt="image" src="https://user-images.githubusercontent.com/15023748/232988297-83b48d4c-5a67-4460-a170-f2babdfa98ec.png">

- main
<img width="725" alt="image" src="https://user-images.githubusercontent.com/15023748/232991573-6d388282-c17d-4963-8006-227f834fa52f.png">

- branch
<img width="729" alt="image" src="https://user-images.githubusercontent.com/15023748/232991626-4a8e48a8-96db-4b45-9abe-a133bcd2d1ed.png">


Here we can observe that for the same configuration, branch has a significant increase compared to main throughput, and the barrier latency decreases accordingly

#### sst file
<img width="744" alt="image" src="https://user-images.githubusercontent.com/15023748/232989884-81ac7eeb-c0b4-4725-a203-2bf23435c64e.png">

#### compaction throughput
<img width="723" alt="image" src="https://user-images.githubusercontent.com/15023748/232990183-8c72bf95-10ee-4ef3-abf4-a4523c027fb0.png">

#### base level write
- main
<img width="724" alt="image" src="https://user-images.githubusercontent.com/15023748/232990454-fc612258-4e78-47b4-9307-5645a7d73040.png">

- branch
<img width="730" alt="image" src="https://user-images.githubusercontent.com/15023748/232990534-960d69db-0f4d-44c5-92b9-97b0c6010c22.png">

#### compacting to base task count
-  main
<img width="744" alt="image" src="https://user-images.githubusercontent.com/15023748/232991124-097dd114-f75c-4233-9f4b-8df32a877761.png">

- branch 
<img width="717" alt="image" src="https://user-images.githubusercontent.com/15023748/232991236-6d2e2f7c-67d8-4866-a474-209aad8c1f0d.png">

For Compaction, there are more sst files in the whole system in branch, which may be related to partition and move table. The to_base compaction parallelism of the branch is as expected, and the write throughput is up.


### Conclusion
1. From basic testing, the branch optimization meets our expectations, resulting in higher compactor CPU utilization, higher base level compaction parallelism, and higher throughput.
2. It also promotes higher throughput and lower barrier latency.
3. But there are so many variables introduced in branch that I'm not sure which optimization has the effect, so I'll retest to make sure each optimization works by controlling the variables added.

**Comment by Li0k** [comment]
### Test
- 40min test
- compare main branch and optimize branch

```
[benchmark.nexmark]
query = "q1"

[benchmark.risingwave.replicas]
meta = 1
frontend = 1
compute = 2
compactor = 4

[benchmark.risingwave.resources.compute]
cpu = { limit = "8", request = "7200m" }
mem = { limit = "16Gi", request = "15Gi" }

[benchmark.risingwave.resources.compactor]
cpu = { limit = "8", request = "8" }
mem = { limit = "8Gi", request = "8Gi" }
scale = { compaction_bytes = 4294967296 }
```

main on the left, branch on the right. Verify that the new picker parallel logic works in a q1 write-only workload by testing (pick multi l0_non_overlap_sub_level instead of the whole level, and Concurrent l0 to base_level_comapction)

https://g-2927a1b4d9.grafana-workspace.us-east-1.amazonaws.com/d/EpkBw5W4k/risingwave-test-dashboard?orgId=1&from=1681297888977&to=1681401258000&var-datasource=test-useast-1-rwc-prometheus&var-namespace=benchmark-mike041301&var-namespace=benchmark-mike041206

#### compactor CPU

<img width="932" alt="image" src="https://user-images.githubusercontent.com/15023748/234001060-f2712a83-c968-46a9-aa4a-bdf48e04552d.png">

compactor CPU resources are more fully utilized

#### source throughput

<img width="926" alt="image" src="https://user-images.githubusercontent.com/15023748/234001441-0ffebaee-6752-4736-8d05-b5d61c816aad.png">

In the write-only workload, the throughput is not affected.

#### barrier latency

<img width="939" alt="image" src="https://user-images.githubusercontent.com/15023748/234001749-f5be56ca-ab40-4c51-861b-98c64906543e.png">

The barrier latancy also behaves the same way

#### sst file

<img width="940" alt="image" src="https://user-images.githubusercontent.com/15023748/234002034-a8a9b749-6b56-4b9d-b576-c944b590244f.png">

The new picker better controls the number of files in l0

#### compact task number

<img width="1850" alt="image" src="https://user-images.githubusercontent.com/15023748/234002536-f1625cb7-68ef-4cbb-9b30-c76511945617.png">

#### compaction throughput

<img width="931" alt="image" src="https://user-images.githubusercontent.com/15023748/234002648-73e09f7f-73da-4747-a37e-44c2448ed0b4.png">

#### compacting task count

<img width="928" alt="image" src="https://user-images.githubusercontent.com/15023748/234002855-4676d628-e2e6-4992-8715-48e2129b8892.png">

The test results show that the total number of compacting tasks in the system is higher, and the number of concurrently compacting tasks is also higher, resulting in higher compaction throughput.

#### compacting to base level

<img width="914" alt="image" src="https://user-images.githubusercontent.com/15023748/234003719-9c54f1cd-5a0a-4970-9496-f41926f496e3.png">

**Comment by Little-Wallace** [comment]
Amazing job !

**Comment by Li0k** [comment]
### Conclusion

In our tests, we introduce different optimizations to verify which strategy is effective when the number of write requests, reaches a certain order of magnitude.

1. try to break the assumption of sub_level compaction and increase the parallelism of sub_lvel compaction by picking multiple sub_level files at once instead of picking the whole level.
2. split the l0 and base level files into specified partitions by means of vnode and so on, thus improving the efficiency of 1.
3. When there are multiple state tables in the system, move the state table data with more writes to a separate compaction group to enable the above optimization and thus improve the system throughput.

I believe that the above optimizations are implemented independently of each other, but they can be used in conjunction with each other, and I have verified this through the above tests.

In the q1 write-only workload, I verified that using the new pick logic alone, within a single state table, can also increase parallelism to reduce the l0 buildup and solve the problem of underutilized compactor cpu in the previous scale test by comparing it with the main branch.

In the q4,q7 read-write worload, I performed three comparisons. The introduction of the new picker logic alone brings some improvement, but since there are multiple state tables in the system, the sst is not aligned and the effect is not as obvious as in the q1 test, which is as expected. Therefore, the optimization of sst partition and split compaction group was introduced to split the separate state tables into separate compaction groups, and to align the sst files better, similar to q1, to verify the effectiveness of these two optimizations.

**Comment by Li0k** [comment]
support flush as non-overlapping-level  https://github.com/risingwavelabs/risingwave/pull/9794
