### ISSUE TITLE
feat: StreamProject Merge for two phase plans

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#8742]
Use this regex to search our testcases for these cases: `StreamProject.*\n.*StreamProject \{`.

Example:
https://github.com/risingwavelabs/risingwave/blob/96aa23dd0dc04c869a2ea5fdb4b7b1fc8fbcbf6d/src/frontend/planner_test/tests/testdata/agg.yaml#L1182-L1183

It occurs because `Project` is inserted (during `to_stream_dist`) to add `vnode`, after our optimization pass for `ProjectMergeRule` (during `gen_optimized_logical_plan_for_stream`.)

**Comment by lmatz** [comment]
This blocks saving one `compact` in a final Project: https://github.com/risingwavelabs/risingwave/issues/8712#issuecomment-1480802152
which looks significant for stateless query

**Comment by kwannoel** [comment]
Working on it now, should workaround https://github.com/risingwavelabs/risingwave/issues/8577 as well, which I think is the real issue #8712 faces.

**Comment by st1page** [comment]
> This blocks saving one compact in a final Project: https://github.com/risingwavelabs/risingwave/issues/8712#issuecomment-1480802152
which looks significant for stateless query

I think not. the `compact` will not be costly on a compacted chunk.

**Comment by lmatz** [comment]
I mean for q0, there can be no compact at all. The existing compact is done in the first project right after the filter, taking 10% of the flame graph.

**Comment by st1page** [comment]
Yes... in fact I think the ProjectExecutor should not compact the chunk because most of the expression is not computing heavy.
