### ISSUE TITLE
Fill in the description of all the metrics shown on Grafana

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#8780]
The description of some metrics is missing.

And IIRC, many people have complained that the title/description is not clear enough to indicate what the metrics are really measuring.

We remark that part of the reason is due to the intrinsic complex nature of the metrics, but we try to make it as much easy-to-understand as possible.

When there is a non-empty description, the text entered in this field appears in a tooltip in the upper-left corner of the panel as you hover your mouse over it.

![SCR-20230327-lw4](https://user-images.githubusercontent.com/5791930/227874865-2fdf3a70-3631-4b81-81d6-0f30286c4052.png)

Some user-facing metrics panel:
- Node Count
- Node Memory
- Node CPU
- Source Throughput(rows) (bytes)
- Barrier Number
- Barrier Latency (Freshness)
- Executor Throughput (If enabled)
- Join Executor Cache
- Join Cached Entries
- Aggregation Executor Cache Statistics For Each Key/State
- Aggregation Cached Keys
- Hummock: Cache Size
- Hummock: Read Duration - Get
- Hummock: Read Duration - Iter
- Compaction: SST Count
- Compaction: KBs level sst
- Object Store: Estimated S3 Cost(Real time)
- Object Store: Estimated S3 Cost (Monthly)
- Frontend: Query Per Second (Local/Distributed)
- Frontend: Query Latency (Local/Distributed)
- Frontend: The number of running queries, rejected queries and completed queries (Local/Distributed)
- Memory Manager: The memory allocated by Jemalloc
- Memory Manager: The memory allocated by streaming

Missing ones: 
- Node Network Usage (wonder if it is necessary to show on Grafana or use some metrics directly collected by AWS)?

**Comment by CAJan93** [comment]
Hey, with above example could you please say how an ideal description would look like? `The memory usage of each component of RisingWave` seems pretty clear to me. Below it states which line refers to which component :)

**Comment by lmatz** [comment]
> Hey, with above example could you please say how an ideal description would look like? `The memory usage of each component of RisingWave` seems pretty clear to me. Below it states which line refers to which component :)

The figure serves as an example of `the text entered in this field appears in a tooltip in the upper-left corner of the panel as you hover your mouse over it.`.

Some other metrics have incorrect descriptions which seem to be copied directly from other metrics.
