### ISSUE TITLE
doc: Status Page that shows us which SQL functions are supported and which are missing

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#8790]
### Describe the solution you'd like

A `supported_functions.md` with the functions we support and that we can update automatically. 

We can pull the PSQL functions from the Postgres docs (see e.g. [here](https://www.postgresql.org/docs/current/functions-array.html#ARRAY-FUNCTIONS-TABLE)) and then just check if a function is mentioned in one of our `*.slt.*` test files. 

Think this would be nice to have and it would aid our dev process. 

Or to get all PSQL functions: 

```
SELECT
    n.nspname,
    p.proname
FROM 
    pg_catalog.pg_namespace n
JOIN 
    pg_catalog.pg_proc p ON 
    p.pronamespace = n.oid
WHERE 
    p.prokind = 'f'
```

**Comment by xxchan** [comment]
Similar idea discussed before https://github.com/risingwavelabs/risingwave/issues/3919
I think the idea is generally OK, but not on the schedule. Are you willing to implement it?

**Comment by xiangjinwu** [comment]
Updated the tracking page of builtin functions #112
