### ISSUE TITLE
parser: better error message for `CREATE SOURCE` without connector

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#8792]
### To Reproduce

```
dev=> create source s() row format json;
ERROR:  QueryError: Protocol error: connector  is not supported
```

### Expected behavior

Report missing required field `connector` like this
```
dev=> create source s() with (connector='kafka') row format json;
ERROR:  QueryError: internal error: missing field `properties.bootstrap.server`
```

And/or report missing `WITH`

**Comment by gengteng** [comment]
Hi, I would like to solve this issue. Based on the issue description, it seems like the appropriate error message to report could be :
```
ERROR:  QueryError: internal error: connector is missing
```
Is that correct?

**Comment by xxchan** [comment]
> it keeps getting blocked due to check timeouts

Sorry for the inconvenience. I've observed the problem frequently occurring and submitted a fix https://github.com/risingwavelabs/risingwave/pull/8887
