### ISSUE TITLE
ObjectStore failed with IO error: HTTP connect timeout

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#8796]
We have witnessed several occurrences of the following error in recent weeks.
```
Storage error: Hummock error: ObjectStore failed with IO error Internal error: read "...." in block Some(BlockLocation { offset: ... , size: ... }) failed, error: timeout: error trying to connect: HTTP connect timeout occurred after 3.1s
```
This has caused batch query to fail in the following scenarios:
- Parallel e2e failed when we turn off block cache refill for batch query with large range scan https://github.com/risingwavelabs/risingwave/pull/8688#issuecomment-1479004023
- In cloud deployment with insufficient compactor resources and many L0 SSTs, running a simple `SELECT * FROM ... LIMIT 5` batch query failed.

A possible explanation of the cause is that when there are a large number of concurrent I/O happening on a single CN, many new http connections are created all at once, causing some connection limit to be hit or tokio may not be able to handle it in time. We need a more serious investigation and solution to this error.

Possible solutions:
- Investigate aws client and see whether we can enable single-flight for http connection creation or control the behavior of connection pool.
- Catch the timeout error. Backoff and retry until the request succeeds.
- Throttle the number of concurrent I/O allowed in a single storage merge iterator.

**Comment by hzxa21** [comment]
I wonder whether aws rust sdk supports http connection pool at the beginning. Based on what I saw in the [aws rust sdk timeout configuration RFC](https://awslabs.github.io/smithy-rs/design/rfcs/rfc0014_timeout_config.html):

> Connect Timeout: A limit on the amount of time after making an initial connect attempt on a socket to complete the connect-handshake.
> TODO: the runtime is based on Hyper which reuses connection and doesn't currently have a way of guaranteeing that a fresh connection will be use for a given request.

It seems to indicate that the sdk leverage hyper for connection reuse so I guess connection pool should be included by default. I didn't carefully check the code though.

**Comment by wcy-fdu** [comment]
How to reproduce this error?

**Comment by wcy-fdu** [comment]
I think this error is due to the limitation of http connect counts of aws EC2, and I use a simple test code to stably reproduced this problem. (50W read requests at the same time will trigger this problem)
```rust
use std::{path::Path, io::Write};
use std::sync::Arc;

use aws_sdk_s3::Client;

use futures::future::try_join_all;

use clap::Parser;
use std::fs::File;
const BUCKET: &str = "rw-bench-wcy-risingwave-hummock";
const PARTITION:u16 = 256;
const PATH_PREFIX: &str = "temp";

#[derive(Parser, Debug)]
struct Args {
    #[clap(short, long, default_value_t = 1)]
    parallelism: u64,
    #[clap(short, long, default_value_t = 1)]
    repeat: u64,
    #[clap(short, long, default_value_t = 0)]
    interval_ms: u64,
}

async fn create_objects(client: &Client) {
    for i in 0..10 {
        let s = "test";
        let path = &format!("/home/ubuntu/temp/{}.txt", i);
        let mut f = File::create(Path::new(path)).unwrap();

        f.write_all(s.as_bytes()).unwrap();
    }
    for i in 0..10 {
        let body = aws_sdk_s3::types::ByteStream::from_path(Path::new(&format!("/home/ubuntu/temp/{}.txt", i))).await.unwrap();
        client
            .put_object()
            .bucket(BUCKET)
            .key(format!("{PATH_PREFIX}/{i}"))
            .body(body)
            .send()
            .await
            .unwrap();
    }
    println!("finish put object");
}

async fn read(client: &Client, path: &str) {
    match client.get_object().bucket(BUCKET).key(path).send().await {
        Ok(_) => {
        }
        Err(e) => {
            eprintln!("read {} FAIL. {}", path, e);
        }
    }
}

#[tokio::main]
async fn main() {
    let args = Args::parse();
    let retry_conf =
            aws_config::retry::RetryConfig::standard().with_max_attempts(10);
    let shared_config = aws_config::from_env().retry_config(retry_conf).load().await;
    // let shared_config = aws_config::from_env().load().await;
    let client = Arc::new(Client::new(&shared_config));
    // create_objects(&client).await;
    println!("{:#?}", args);
    let mut futures = vec![];
    for i in 0..500000 {
        let path = format!("{PATH_PREFIX}/{}", i % (PARTITION as u64));
        let client_ = client.clone();
        futures.push(tokio::spawn(async move {
            read(&client_, &path).await;
        }));
    }
    try_join_all(futures).await.unwrap();
}
```

And I have tried set a large retry times for aws client, timeout will not be triggered, but the code run very slow.

Editing...

**Comment by wcy-fdu** [comment]
After some discussion, we decide to cache this timeout error, and execute retry(not aws client retry) for some specific requests. This solution is relatively easier than throttling ing the number of concurrent I/O. 
This error is sporadic, and it's hard to decide the upper limit of  concurrent I/O, which may impact system throughput seriously. Passive handling it as a special case is better. 
So next, we need to 

- [ ] catch this error
- [ ] set retry stragegy

**Comment by wcy-fdu** [comment]
> After some discussion, we decide to cache this timeout error, and execute retry(not aws client retry) for some specific requests. This solution is relatively easier than throttling ing the number of concurrent I/O. This error is sporadic, and it's hard to decide the upper limit of concurrent I/O, which may impact system throughput seriously. Passive handling it as a special case is better. So next, we need to
> 
> * [ ]  catch this error
> * [ ]  set retry strategy

After catch this error and use specific retry strategy, another error occurs:
```
thread ‘tokio-runtime-worker’ panicked at ‘called `Result::unwrap()` on an `Err` value: DispatchFailure(ConnectorError { err: hyper::Error(Connect, ConnectError(“dns error”, Custom { kind: Uncategorized, error: “failed to lookup address information: Temporary failure in name resolution” })), kind: Io })’,
```

I think this is the DNS restriction on the server side, so solution 3(retry) is not the best solution. Thus, we can catch this error, and then throttle the number of concurrent I/O. After the error disappears, concurrent I/O can be retuned.

**Comment by kwannoel** [comment]
How was it fixed 👀
