### ISSUE TITLE
investigate the performance of HashKey

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#8802]
After #8733, we have a benchmark.

It is suspected that its performance, hashing `varchar` in particular,  has a big impact on AggExecutor.

Some comments made in Slack: https://risingwave-labs.slack.com/archives/C04MD3Z2VJR/p1679466789211899
Feel free to join the channel

> Essentially there are two kinds of HashKey : FixedSizeKey and SerializedKey
SerializedKey is used for keys whose size is not fixed(e.g. key which contains dynamic size types such as str), and it’s in fact a wrapper of Vec<u8>
FixedSizeKey is used for keys whose size is fixed(e.g., whose sizes are fixed, such as int, bigint), and it’s a fixed sized array. In this case use FixedSizeKey  can help avoid allocation, and speeds up hash table lookup

> anyway, I think we can remove the null_bitmap in the SerializedKeySerializer and its HashKey?

> Does HashKey contain a Hashed value? Or the value we want to hash by?
It contains both raw data and hash code, otherwise we can’t use vectorized hash
See https://github.com/risingwavelabs/risingwave/blob/86ffe994cc32f3032443fce8498272c75d1b0180/src/common/src/hash/key.rs#L107

**Comment by st1page** [comment]
- [ ] reserve the buffer (tuples' size and encoding size) in the `HashKeySerializer::from_hash_code` 
- [ ] change the null bit map from FixedBitSet into `smallbitset`(https://docs.rs/smallbitset/latest/smallbitset/) or our self-maintained bitset to avoid memory in the heap. 
- [ ] `SerializedKeySerializer` can use a special value encoding which do not serialize if the field is NULL and depend on the null bit map

**Comment by kwannoel** [comment]
> BTW, after some investigation,I think some computation logic depends on the null_bitmap and we can not simply remove it and depends on the value encoding's null encoding.

I'm wondering if there's really no way to remove this null encoding? What logic depends on it?

**Comment by kwannoel** [comment]
- [ ] Try small vec https://github.com/risingwavelabs/risingwave/pull/8941#issuecomment-1498479355
- [ ] Implement key format for mixed fixed + serialized keys.
- [ ] Add larger fixed key sizes: 512, 1024, 2048.
