### ISSUE TITLE
Missing tests for replace() function

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#8815]
Example:

```sql
replace(str, ',', '')
```

**Comment by xiangjinwu** [comment]
Already supported
```
dev=> select replace('a,b,c', ',', '-');
 replace 
---------
 a-b-c
(1 row)

```

**Comment by xiangjinwu** [comment]
Covered by unit tests and PostgreSQL regress tests:

https://github.com/risingwavelabs/risingwave/blob/80c477fac2a30c48590463fa2b2a598bf8bafef7/src/expr/src/vector_op/replace.rs#L40

https://github.com/risingwavelabs/risingwave/blob/80c477fac2a30c48590463fa2b2a598bf8bafef7/src/tests/regress/data/sql/strings.sql#L547
