### ISSUE TITLE
bug(frontent): `generate_series` not compatible with PSQL 

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#8826]
### Describe the bug

https://www.postgresql.org/docs/current/functions-srf.html

Postgres supports 2 forms of `generate_series`: One with 2 params and one with 3 params. The 3rd params is the stepping distance between the generated numbers

```
SELECT * FROM generate_series(2,4);
 generate_series
-----------------
               2
               3
               4
(3 rows)

SELECT * FROM generate_series(5,1,-2);
 generate_series
-----------------
               5
               3
               1
(3 rows)
```

We only support the version with 3 params. Should we also support the one with 2 params? 

It just defaults to 1 for the stepping distance.

### Expected behavior

Compatibility with PSQL

**Comment by xxchan** [comment]
> Should we also support the one with 2 params

Yes

**Comment by xiangjinwu** [comment]
Supported by #9949
