### ISSUE TITLE
 PG-incompatibility: alias of set returning function in FROM

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#8829]
### Describe the bug

This works in both PostgreSQL and RisingWave:
```sql
select id from generate_series(1, 5, 1) as t(id);
```

This only works in PostgreSQL but not in RisingWave:
```sql
select id from generate_series(1, 10, 1) as id;
```

**Comment by xiangjinwu** [comment]
Hi @CAJan93, I have updated the issue description based on my testing. Does it reflect the original bug you intend to report?

About this issue, it seems PostgreSQL is handling set returning function which outputs a single column specially, that `as id` would rename both the table and its only column to `id`:
```
test=# select id.id from generate_series(1, 5) id;
 id 
----
  1
  2
  3
  4
  5
(5 rows)

test=# select id.id from jsonb_each('{"a":1,"b":true}') id;
ERROR:  column id.id does not exist
LINE 1: select id.id from jsonb_each('{"a":1,"b":true}') id;
               ^

test=# select id.key from jsonb_each('{"a":1,"b":true}') id;
 key 
-----
 a
 b
(2 rows)
```

**Comment by CAJan93** [comment]
Yap, new title works @xiangjinwu. Thank you very much for changing it and looking into the solution already 👍
