### ISSUE TITLE
feat: limit push down

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#8844]
### Describe the bug

query:
```
select cast(UDF(CONSTANT_1, Column_1) as jsonb)  from TABLE1 where name like '%ZZZ%' limit 1;
```
plan:
```
BatchLimit { limit: 1, offset: 0 }
 └─BatchExchange { order: [], dist: Single }
   └─BatchLimit { limit: 1, offset: 0 }
     └─BatchProject { exprs: [UserDefinedFunction { ... }::Jsonb as $expr1] }
       └─BatchFilter { predicate: Like(TABLE1.name, '%ZZZ%':Varchar) }
         └─BatchScan { table: TABLE1, columns: [COLUMN1, name] }
(6 rows)
```
Is it a bug or is `limit 1` doing what it is supposed to do?

### Additional context

Reported by a design partner

**Comment by lmatz** [comment]
Oh, now I remembered, we count on the early termination of limit to early terminate the scan.

The scan probably did a read to fetch 1024 rows anyway in this case.

**Comment by xxchan** [comment]
So are  you making a feature request to pushing limit to the lowest level? 🤔

**Comment by lmatz** [comment]
Yes, not a bug but a feature request

**Comment by Eurekaaw** [comment]
I think I've done similar things when optimizing `TopN`. https://github.com/risingwavelabs/risingwave/blob/83f1e9d9f5b44f7d64fc4586a6b392e82e0f1ef1/src/frontend/src/optimizer/rule/top_n_on_index_rule.rs#L64-L66
Do you want more cases that set `chunk_size` for scan?

**Comment by xxchan** [comment]
Woo I don't know we have that :eyes:. But I don't think limit push down is like that. I think we just need to blindly push limit down until a leaf node 🤔

**Comment by Eurekaaw** [comment]
Oh I see, then IIUC it's pushing down until leaf or filter?

**Comment by xxchan** [comment]
Oh yes and no... By mentioning filter you also remind me of other cases, like join or agg.

**Comment by Eurekaaw** [comment]
I find the case is more tricky that it might seem...

A solvable problem is the project set generates multiple rows for each row input, e.g., `select generate_series(1, 1000, 1) from t limit 1;`, although we can have a limit directly following the scan, we have to keep the original limit to guarantee our output is limited as desired.

A more tricky case is that, say one UDF generates 0 records for the first row in TABLE1 and generate 1 records for the second row in TABLE1, we cannot push down the limit to the scan as then no records will in the output.

Therefore I find the use case where we can push the limit down is very limited, could you please reconfirm this feature?

**Comment by Eurekaaw** [comment]
Cool, then we can do something. Could you please provide a runnable use case of UDF? I cannot find any in our e2e or planner tests😄

**Comment by xxchan** [comment]
I don't have any other concerns, but can also only imagine Limit -> Project case. 😅 So it seems too limited and ad-hoc. Wanted @lmatz to elaborate the use cases. 

cc @wangrunji0408

**Comment by wangrunji0408** [comment]
> Could you please provide a runnable use case of UDF?
You can find them [here](https://github.com/risingwavelabs/risingwave/blob/main/e2e_test/udf/python.slt).

I think pushing `Limit` down through `Project` should be no concern, as `Project` always produces chunks with the same number of rows as the inputs.

**Comment by st1page** [comment]
it is not a very big optimization because the LimitExecutor can stop the stream early when the input achieves the limit row count. But generally LGTM.

**Comment by lmatz** [comment]
My input comes from one user who complains about why a query with `limit 1` and `UDF` is so slow. That's all.

**Comment by Eurekaaw** [comment]
completed by #8971
