### ISSUE TITLE
Implement sha512, sha384, sha256, sha224

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#8846]
https://www.postgresql.org/docs/15/functions-binarystring.html

Note that both of input and output are `bytea`. This is inconsistent with #8847:
> For historical reasons, the function `md5` returns a hex-encoded value of type `text` whereas the SHA-2 functions return type `bytea`. Use the functions [encode](https://www.postgresql.org/docs/15/functions-binarystring.html#FUNCTION-ENCODE) and [decode](https://www.postgresql.org/docs/15/functions-binarystring.html#FUNCTION-DECODE) to convert between the two. For example write `encode(sha256('abc'), 'hex')` to get a hex-encoded text representation, or `decode(md5('abc'), 'hex')` to get a `bytea` value.

**Comment by BanBuDu0** [comment]
I think it's LGTM.
Could you plz assign this to me? As well as https://github.com/risingwavelabs/risingwave/issues/8845
