### ISSUE TITLE
Implement md5

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#8847]
https://www.postgresql.org/docs/15/functions-string.html
https://www.postgresql.org/docs/15/functions-binarystring.html

There are 2 variants in PostgreSQL:
* [x] `md5(text)` -> text
* [ ] `md5(bytea)` -> text

Note that both returns a string with hexadecimal encoding. This is inconsistent with #8846:
> For historical reasons, the function `md5` returns a hex-encoded value of type `text` whereas the SHA-2 functions return type `bytea`. Use the functions [encode](https://www.postgresql.org/docs/15/functions-binarystring.html#FUNCTION-ENCODE) and [decode](https://www.postgresql.org/docs/15/functions-binarystring.html#FUNCTION-DECODE) to convert between the two. For example write `encode(sha256('abc'), 'hex')` to get a hex-encoded text representation, or `decode(md5('abc'), 'hex')` to get a `bytea` value.

**Comment by BanBuDu0** [comment]
Hi, it's LGTM, please assign this issue to me.
