### ISSUE TITLE
perf(encoding): reserve memory before the row encoding.

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#8877]
after https://github.com/risingwavelabs/risingwave/pull/8692 we can get the row encoding size before we really encode a row. So we can reserve the buffer before encoding.

optimizing target: `Row::value_serialize` https://github.com/singularity-data/risingwave/blob/main/src/common/src/row/mod.rs#L80

bench:
```bash
cd ./src/common
cargo bench --bench bench_row -- basic
```

**Comment by st1page** [comment]
c.c. @BugenZhao feel free to comment if you have any idea, thanks!

**Comment by fuyufjh** [comment]
If `estimate_size()` is most likely to be **more than** the actual length, then it would be perfect, but I guess currently `estimate_size()` gives a average approximating size, which means, it could be more or less than the actuall length.

Please make sure to cover all data types in this micro-benchmark.
