### ISSUE TITLE
`SHOW SOURCES` should not show table with connector

### ISSUE THREAD

**Issue by Ad-Bean** [risingwavelabs/risingwave#8879]
### Describe the bug

create a multiple source table in Risingwave via this command:
```sql
CREATE TABLE auction (
    "id" BIGINT,
    "item_name" VARCHAR,
    "description" VARCHAR,
    "initial_bid" BIGINT,
    "reserve" BIGINT,
    "date_time" TIMESTAMP,
    "expires" TIMESTAMP,
    "seller" BIGINT,
    "category" BIGINT,
    "extra" VARCHAR,
    PRIMARY KEY (id)
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Auction',
    nexmark.split.num = '12',
    nexmark.min.event.gap.in.ns = '500000'
);
```

`show tables` and `show sources` both have the result "auction", but it is not possible to use `drop source` to delete "auction".

![image](https://user-images.githubusercontent.com/54789193/228748959-a3108ace-a66a-44dd-90ce-91a68a90b531.png)

### To Reproduce

```sql
show tables;
show sources;
drop source auction;
drop table auction;
```

### Expected behavior

not sure if it is a bug or feature

### Additional context

cc @chenzl25

**Comment by fuyufjh** [comment]
I think `auction` should not be in the results of `show sources`
