### ISSUE TITLE
`state_store_write_build_l0_bytes` as a metric used in grafana scripts does not exist

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#8889]
### Describe the bug

https://github.com/risingwavelabs/risingwave/blob/main/grafana/risingwave-dashboard.dashboard.py#L695

Do we want to correct it or delete it?

### Additional context

![SCR-20230404-mhq](https://user-images.githubusercontent.com/5791930/229729811-c1e36fba-0161-4d6b-a33b-39c1afef0861.png)

**Comment by hzxa21** [comment]
Seems this has already be fixed. I no longer see `state_store_write_build_l0_bytes` in the dashboard definition.
