### ISSUE TITLE
jsonb get converted to all lowercase characters after source ingestion

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#8894]
### Describe the bug

example:
```
{"blockNumber": 16938734}
```
in upstream message queues
->
once ingested
```
{"blocknumber": 16938734}
```

### Additional context

Reported by a design partner

**Comment by xxchan** [comment]
Is it possible it's the column name case sensitivity problem 👀 ? Please provide a reproducible example

**Comment by lmatz** [comment]
fixed by #9086
