### ISSUE TITLE
Implement the `sign` function

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#8900]
## Purpose
The sign() function returns the sign of the specified argument.

## Parameters
The sign() function takes one parameter:

dp or numeric: The argument to compute the sign for.

## Return Value
The sign() function returns an integer that represents the sign of the specified argument, according to the following rules:

- If the argument is positive, 1 is returned.
- If the argument is negative, -1 is returned.
- If the argument is zero, 0 is returned.

## Example
```sql
SELECT sign(5); -- Returns 1
SELECT sign(-5); -- Returns -1
SELECT sign(0); -- Returns 0
```

## Regress test to enable

https://github.com/risingwavelabs/risingwave/blob/ac104a751161586a1e1b8dcd02e0ca5fa60e96b4/src/tests/regress/data/sql/float8.sql#L102-L103

https://github.com/risingwavelabs/risingwave/blob/ac104a751161586a1e1b8dcd02e0ca5fa60e96b4/src/tests/regress/data/expected/float8.out#L322-L330

**Comment by broccoliSpicy** [comment]
there are actually some bit hacks we could utilize for this function.
for example:
`    sign = (v > 0) - (v < 0);`

[bit_hack](https://graphics.stanford.edu/~seander/bithacks.html#CopyIntegerSign)


do we care about performance that much here?
to implement these hacks we might need to introduce C to risingwave, seems too trivial a reason to mess up the current compilation/build 
what about assembly, what if doing so limits risingwave's supporting architecture

**Comment by xxchan** [comment]
Hmmm, why can't this hack be done in Rust? :eyes:

**Comment by xxchan** [comment]
And actually, there's `i32::signum` https://doc.rust-lang.org/std/primitive.i32.html#method.signum

**Comment by broccoliSpicy** [comment]
ha, my bad, I thought casting from boolean to integer is disallowed in Rust

```rust
// Type your code here, or load an example.
pub fn sign(num: i32) -> i32 {
    ((num > 0) as i32) - ((num < 0) as i32)
}

// If you use `main()`, declare it as `pub` to see it in the output:
// pub fn main() { ... }
```

```
example::sign:
        mov     ecx, edi
        sar     ecx, 31
        xor     eax, eax
        test    edi, edi
        setne   al
        or      eax, ecx
        ret
```
rustc's optimization is doing quite a good job here(all 'cause of llvm?)
Rust is cool here

this result is produced by [this tool](https://rust.godbolt.org/) rustc-nightly 
-C opt-level=3 -C target-cpu=cannonlake

**Comment by xxchan** [comment]
Hmmm, is this bit hack better? :eyes: You might find a chance to contribute to Rust std! 😄 

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/37948597/232231170-689f3bdb-cebf-4e3e-b1d7-64ff42e58ffb.png">

**Comment by xxchan** [comment]
Oh, things become different in nightly... 🤔 

<img width="401" alt="image" src="https://user-images.githubusercontent.com/37948597/232231297-fedee474-e67b-4344-afa2-31dd74d0ff4d.png">

**Comment by broccoliSpicy** [comment]
haha:smile:, we might be a few months late.

I am sure there will be plenty of other chances for us

this signum function's implementation is lit, I think we should use it

**Comment by broccoliSpicy** [comment]
[Rust PR for signum optimizition](https://github.com/rust-lang/rust/pull/106798)
