### ISSUE TITLE
Implement `degrees` / `radians`

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#8901]
## Description

The `radians(dp)` function converts an angle measured in degrees to radians.

## Syntax

radians(dp)

## Arguments

- `dp`: A numeric value that specifies the angle in degrees.

## Examples

Convert 90 degrees to radians:

```sql
SELECT radians(90);
```

Output:
1.5707963267949

## Return Type
The radians(dp) function returns a double precision floating point number.

**Comment by gengteng** [comment]
Hi, I have implemented the `degrees` and `radians` functions with the following parameter and return value types:

```rust
#[function("degrees(float64) -> float64")]
pub fn degrees(input: F64) -> F64 {
    input.to_degrees()
}

#[function("radians(float64) -> float64")]
pub fn radians(input: F64) -> F64 {
    input.to_radians()
}
```

I would like to confirm if this implementation meets your design requirements so that I can submit a pull request.

Thank you!
