### ISSUE TITLE
Implement `exp` / `ln` / `log` / `log10` (missing decimal / `ln` / `log` / `log10`)

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#8903]
# PostgreSQL Operator: ln(dp or numeric)

The `ln` operator calculates the natural logarithm of a given number.
The `log` / `log10` operator calculates the base 10 logarithm of a given number.

## Syntax

```sql
ln(dp)  -- returns double precision
ln(numeric)  -- returns numeric
```
## Return Value
- same as input

Examples
```sql
-- Returns the natural logarithm of 10 as a double precision value.
SELECT ln(10.0::double precision);

-- Returns the natural logarithm of 10 as a numeric value.
SELECT ln(10.0);
```

## Regress test to enable

https://github.com/risingwavelabs/risingwave/blob/ac104a751161586a1e1b8dcd02e0ca5fa60e96b4/src/tests/regress/data/sql/float8.sql#L155-L161

**Comment by xiangjinwu** [comment]
#9991
