### ISSUE TITLE
Support string functions `left` and `right`

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#8934]
# Function: right

The `right` function returns the rightmost `n` characters from the given
`text` string.

``` sql
right(str text, n int) RETURNS text
```

## Parameters

  - `str` - The `text` value from which to extract the rightmost
    characters.

  - `n` - The number of rightmost characters to extract.

## Return Value

The function returns the rightmost `n` characters of the `text` input as
a `text` value.

## Example

To extract the last 3 characters from a given `text` value:

``` sql
SELECT right('hello', 3); -- Output: 'llo'
```

**Comment by nachiketkanore** [comment]
I would like to take this!

**Comment by xiangjinwu** [comment]
Thank you @nachiketkanore

**Comment by xiangjinwu** [comment]
You can refer to some recent PRs, for example #9760

As for the function logic, it would be similar to the `substr` function:
https://github.com/risingwavelabs/risingwave/blob/main/src/expr/src/vector_op/substr.rs

**Comment by azdxdy** [comment]
I would like to work on  this issue. May I take it?

**Comment by xiangjinwu** [comment]
> I would like to work on this issue. May I take it?

Yes. Thank you for willing to help!
