### ISSUE TITLE
Support string function `btrim`

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#8935]
# Syntax

``` sql
BTRIM(string text [, characters text])
```

# Description

The `btrim` function in Postgres is used to remove specified characters
from both the beginning and the end of a given text string. If no
characters are provided, the function removes whitespace characters by
default.

# Parameters

  - `string` (text): The input text string from which characters will be
    removed.

  - `characters` (text) \[optional\]: The characters to remove from the
    beginning and end of the input text string. If not provided, the
    function will remove whitespace characters by default.

# Returns

The function returns a text string with the specified characters removed
from the beginning and end.

# Examples

``` sql
SELECT BTRIM('   PostgreSQL   '); -- Returns 'PostgreSQL'
SELECT BTRIM('$$$PostgreSQL$$$', '$'); -- Returns 'PostgreSQL'
```

# See Also

  - `ltrim`: Removes specified characters from the beginning (left side)
    of a given text string.

  - `rtrim`: Removes specified characters from the end (right side) of a
    given text string.

# Compatibility

The `btrim` function is compatible with PostgreSQL and is part of the
SQL standard.

**Comment by xiangjinwu** [comment]
We have already supported `trim`, which has 3 modes: `ltrim`, `rtrim`, `btrim`. This is just missing an alias.
