### ISSUE TITLE
Implement `encode` / `decode`

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#8937]
# Syntax

``` sql
ENCODE(data bytea, format text) → text
```

# Description

The `encode` function in Postgres is used to encode binary data into a
textual representation. Supported formats are *base64*, *hex*, and
*escape*. The *escape* format converts zero bytes and high-bit-set bytes
to octal sequences (\\nnn) and doubles backslashes.

# Parameters

  - `data` (bytea): The input binary data to be encoded into a text
    string.

  - `format` (text): The format to be used for encoding the binary data.
    Supported formats include *base64*, *hex*, and *escape*.

# Returns

The function returns a `text` value, which is the encoded textual
representation of the input binary data.

# Examples

``` sql
SELECT ENCODE(E'123'::bytea, 'base64'); -- Returns the string 'MTIz'
```

In this example, the `encode` function encodes the binary data
equivalent to the string *123* using the base64 format, returning the
text *MTIz*.

# See Also

  - `decode`: Decode binary data from a textual representation using a
    specified format.

  - `convert`: Convert a string from one character set to another.

# Compatibility

The `encode` function is compatible with PostgreSQL.

**Comment by BanBuDu0** [comment]
Hi all, can this issue assigned to me?
I will do this in my weekend

**Comment by lmatz** [comment]
I feel it's a bit risky.🤔

**Comment by BanBuDu0** [comment]
> I feel it's a bit risky.🤔

+1.
What bothered me before was that pgsql's escape was different from what I used.
Such as   `\"` in pgsql escape encode is  `\\"` rather `\\\"`.
I find the pgsql doc now, and I will try to code by myself follow these rules.

https://www.postgresql.org/docs/current/functions-binarystring.html#ENCODE-FORMAT-ESCAPE
