### ISSUE TITLE
support `POSITION(substring IN string) → integer`

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#8938]
# Syntax

``` sql
POSITION(substring IN string) → integer
```

# Description

The `position` function in Postgres is used to find the location of the
first occurrence of a specified substring within a given string. The
result is an integer representing the character position of the
substring’s first occurrence, counting from 1. If the substring is not
found, the function returns 0.

# Parameters

  - `substring` (text): The substring to search for within the given
    string.

  - `string` (text): The string in which to search for the specified
    substring.

# Returns

The function returns an `integer` value representing the position of the
first occurrence of the substring within the string, or 0 if the
substring is not found.

# Examples

``` sql
SELECT POSITION('world' IN 'hello world'); -- Returns 7
SELECT POSITION('abc' IN 'hello world'); -- Returns 0
```

In these examples, the `position` function finds the location of the
specified substring within the given string.

# See Also

  - `strpos`: Finds the location of a specified substring within a given
    string.

  - `substring`: Extracts a substring from a given string based on a
    specified starting position and length.

  - `overlay`: Replaces a portion of a string with a specified
    substring.

# Compatibility

The `position` function is compatible with PostgreSQL and is part of the
SQL standard.

**Comment by xiangjinwu** [comment]
Just need to alias / bind to `strpos(string, substring)`. Note the reversed argument order.
