### ISSUE TITLE
bug(expr): `lpad` never returns

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#8949]
### To Reproduce

```
SELECT lpad('hi', 5, '');
```

### Expected behavior

In PostgreSQL:
```
test=# SELECT lpad('hi', 5, '');
 lpad 
------
 hi
(1 row)

test=# SELECT length(lpad('hi', 5, ''));
 length 
--------
      2
(1 row)
```

### Additional context

found by regress test

**Comment by TennyZhuang** [comment]
https://github.com/risingwavelabs/risingwave/pull/8767
GPT wrote an infinite loop bug and passed our review 😨

**Comment by wangrunji0408** [comment]
> GPT wrote an infinite loop bug and passed our review 😨

This case is not documented so it's not surprising that GPT was not aware of it. 🥲
