### ISSUE TITLE
state_store_write_batch_tuple_counts metrics missed for 40s

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#8951]
### Describe the bug

This is the first time we hit this issue in the daily performance test. Maybe it's not easy to reproduce this issue. I filed this issue to record the bug in case we hit this again in the future.

The data from Prometheus shows that there are 40 seconds without this metrics data. The scrape interval is 5 seconds. This metrics is empty between `[1680452011.803,\"8161\"],[1680452051.804,\"8161\"]`

```
[1680452001.803,\"8161\"],[1680452006.803,\"8161\"],[1680452011.803,\"8161\"],[1680452051.804,\"8161\"],[1680452056.804,\"8161\"]
```

The promql is `state_store_write_batch_tuple_counts{namespace="nexmark-bs-0-1-2-3-4-daily-20230402"}[24h]`. 

### To Reproduce

Run nexmark q0 and q1.

[The buildkite pipeline job](https://buildkite.com/risingwave-test/nexmark-benchmark/builds/709#01874283-fa4e-4d44-9c41-11f5a5ca4d43)

### Expected behavior

The metrics data interval should be 5 seconds.

### Additional context

![image](https://user-images.githubusercontent.com/5791930/229443991-1a0098dd-d121-4c64-ac40-5d8487c819b1.png)

**Comment by lmatz** [comment]
Did it ever happen again?

**Comment by cyliu0** [comment]
Closed since never happen again
