### ISSUE TITLE
Support `first_value`, `last_value` per partition

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#8964]
In PostgreSQL, the `FIRST_VALUE` and `LAST_VALUE` window functions can
be used to retrieve the first and last values in a specific window
frame, respectively. These functions are commonly used in analytical
queries to retrieve the first or last value of a column within a group
or partition.

The syntax for using `FIRST_VALUE` and `LAST_VALUE` functions is as
follows:

``` sql
FIRST_VALUE(expression) OVER (
    [PARTITION BY partition_expression, ... ]
    ORDER BY sort_expression [ASC | DESC]
)

LAST_VALUE(expression) OVER (
    [PARTITION BY partition_expression, ... ]
    ORDER BY sort_expression [ASC | DESC]
)
```

Here is a brief description of each of the parameters:

  - `expression`: The column or expression for which you want to
    retrieve the first or last value.

  - `PARTITION BY partition_expression, ...`: Specifies the column or
    columns to partition the result set by. This is useful when you want
    to compute the first or last value for each group within a larger
    dataset.

  - `ORDER BY sort_expression [ASC | DESC]`: Specifies the order in
    which the rows are processed. The default order is ascending.

Here is an example of using `FIRST_VALUE` to retrieve the first value of
a column within each
group:

``` sql
SELECT name, year, value, FIRST_VALUE(value) OVER (PARTITION BY name ORDER BY year) as first_value
FROM my_table
```

This query calculates the first value of the `value` column within each
group of `name`, ordered by `year`.

Similarly, you can use `LAST_VALUE` to retrieve the last value of a
column within each
group:

``` sql
SELECT name, year, value, LAST_VALUE(value) OVER (PARTITION BY name ORDER BY year) as last_value
FROM my_table
```

This query calculates the last value of the `value` column within each
group of `name`, ordered by `year`. Note that this query assumes that
the `year` column represents a time series and that the data is ordered
by `year`.

**Comment by stdrc** [comment]
Done by https://github.com/risingwavelabs/risingwave/pull/10740
