### ISSUE TITLE
Implement `[NOT] SIMILAR TO`

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#8966]
# Syntax

``` sql
string SIMILAR TO pattern [ESCAPE escape-character]
```

# Description

The `SIMILAR TO` predicate in Postgres is used to determine if a string
matches a specified pattern using SQL regular expressions. The pattern
can include various metacharacters, such as `|`, `*`, `+`, and others.
Optionally, you can specify an `ESCAPE` character to treat
metacharacters as literals within the pattern.

# Parameters

  - `string`: The input string to be compared against the pattern.

  - `pattern`: The SQL regular expression pattern to match against the
    input string.

  - `escape-character` \[optional\]: The character to be used as an
    escape character when you want to treat metacharacters as literals
    in the pattern.

# Returns

The predicate returns `true` if the input string matches the specified
pattern, and `false` otherwise.

# Examples

``` sql
SELECT 'abc' SIMILAR TO 'a|b|c'; -- Returns false
SELECT 'abc' SIMILAR TO '(a|b|c)+'; -- Returns true
SELECT 'a_b' SIMILAR TO 'a$_b' ESCAPE '$'; -- Returns true
```

# See Also

  - `LIKE`: Tests if a string matches a pattern using simple pattern
    matching with wildcards.

  - `ILIKE`: Case-insensitive version of the `LIKE` operator.

  - `POSIX Regular Expressions`: For more complex pattern matching, you
    can use POSIX regular expressions with operators like `~`, `!~`,
    `~*`, and `!~*`.

# Compatibility

The `SIMILAR TO` predicate is compatible with PostgreSQL and is part of
the SQL standard.

**Comment by xiangjinwu** [comment]
FYI https://github.com/postgres/postgres/blob/REL_15_4/src/backend/parser/gram.y#L15889

> `x SIMILAR TO y     ->    x ~ similar_to_escape(y)`

**Comment by TennyZhuang** [comment]
> Since we have supported `~` and `!~`, [NOT] SIMILAR TO should be easy. It's just an alias.

It’s not an alias, but it’s not very hard. We should do a transform like pg.
