### ISSUE TITLE
feat: Support functional indexes

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#8975]
### Is your feature request related to a problem? Please describe.

Functional indexes are useful when users want to create an index on a field of `jsonb` column. 

Example:
```sql
create table t (j jsonb);
create index idx on t(j->'k');
create index idx2 on t(j->>'k');
select * from t where j->>'k' = 'abc';
```

- [x] Support functional indexes creation. https://github.com/risingwavelabs/risingwave/pull/8976
- [x] Support functional indexes selection. https://github.com/risingwavelabs/risingwave/pull/9067
- [x] Support indexes on expressions. https://github.com/risingwavelabs/risingwave/pull/9142
- [x] Index distributed columns support functional columns. https://github.com/risingwavelabs/risingwave/pull/9489

References:
- https://www.postgresql.org/docs/current/indexes-expressional.html
- https://dev.mysql.com/doc/refman/8.0/en/create-index.html#create-index-functional-key-parts

**Comment by st1page** [comment]
should we need to support the expression in the `INCLUDE` clause? It might be useful if the json is big.
```SQL
create table t (j jsonb);
create index idx on t(j->'k') include(j->'v1', j->'v2', (j->'abc')->'abcv1');
```

**Comment by chenzl25** [comment]
> should we need to support the expression in the `INCLUDE` clause? It might be useful if the json is big.
> 
> ```sql
> create table t (j jsonb);
> create index idx on t(j->'k') include(j->'v1', j->'v2', (j->'abc')->'abcv1');
> ```

PG doesn't support expressions in included columns, so I think we don't need to support it as well. BTW, you can always put these expressions at the end of the index columns to achieve the same goal.
