### ISSUE TITLE
Non-Null Default Value for DML

### ISSUE THREAD

**Issue by Eurekaaw** [risingwavelabs/risingwave#8999]
doc: [Non-NULL Default Value (Outline)](https://www.notion.so/risingwave-labs/Non-NULL-Default-Value-Outline-0c4338912df348fc992a9dd876e6c15f)

- [x] Basic Version: support `create table` with with non-null default columns and corresponding `insert`
	#9521 
- [ ] Refine1: corner cases like `now()`
- [x] Refine2: `update`
- [x] Refine3: `alter`
	#9762

**Comment by broccoliSpicy** [comment]
![Screenshot from 2023-04-29 21-31-27](https://user-images.githubusercontent.com/93440049/235305582-27398ea4-92e0-4b7d-b6ed-bfb556a3e46a.png)


This is not very kind of you...

**Comment by lmatz** [comment]
I can copy paste the content to GitHub if Eurekaaw wants me to do so🤣

**Comment by broccoliSpicy** [comment]
that's okay, 
slightly felt that this might be your guys' trick to allure people to apply for a job...
haha, just kidding, 
that being said, I am sure that risingwave community could benefit a lot if we have a open source design/RFC process

**Comment by lmatz** [comment]
We have https://github.com/risingwavelabs/rfcs, but sometimes only big changes go into this I guess.🤔

**Comment by BugenZhao** [comment]
Close this issue and move to https://github.com/risingwavelabs/risingwave/issues/11021.
