### ISSUE TITLE
feat: defensive measures in UDF servers

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#9002]
### Is your feature request related to a problem? Please describe.

UDF servers allow users to involve their own bussiness logic into our streaming pipeline, which seems to be a fragility and prone to bugs and errors.

- [x] #10828
- [x] #11022

### Describe the solution you'd like

We need to introduce sufficient defensive measures on UDF servers to keep RisingWave safe, including 

- Validation for returning data
- Performance-related metrics

**Comment by fuyufjh** [comment]
Hey, any updates?

**Comment by fuyufjh** [comment]
ping

**Comment by wangrunji0408** [comment]
We have finished the bug fixes by adding data validation. Metrics of UDF server have not been added yet, and can be tracked in the following issue #10321. Maybe we can close this issue for now?
