### ISSUE TITLE
`returning` fails matching specified target columns

### ISSUE THREAD

**Issue by Eurekaaw** [risingwavelabs/risingwave#9012]
### To Reproduce

```SQL
dev=> create table tn (v1 int, v2 int);
CREATE_TABLE
dev=> insert into tn (v2) values (1) returning *;
 v1 | v2 
----+----
  1 |   
(1 row)

INSERT 0 1
```

### Expected behavior

```SQL
dev=> create table tn (v1 int, v2 int);
CREATE_TABLE
dev=> insert into tn (v2) values (1) returning *;
 v1 | v2 
----+----
   | 1  
(1 row)

INSERT 0 1
```

**Comment by broccoliSpicy** [comment]
when binding returing_list: the InputRef's index is derived from the original table's column layout
https://github.com/risingwavelabs/risingwave/blob/e2942500149f4aea2f4965da5bdf824aaa50a0bf/src/frontend/src/binder/insert.rs#L133

we can rearrange the inserted values to align with the original table's column layout, but this kind of memory shuffle may drag performance.
I suppose we can address the issue by rewire the returning InputRef's index and then disable column pruning for insertion -> projection(or disable all optimization for insertion->projection?)


 if we decided to disable column pruning for insertion -> projection, the LogicalProject's logic can be entangled, can we just add a new type of PlanNode called InsertionReturningProject?

**Comment by Eurekaaw** [comment]
Excellent analysis👏 That said I find introducing a new PlanNode maybe somewhat overkill?
I'm wondering if add one more `LogicalProject::with_mapping` here above L43 is sufficient?
https://github.com/risingwavelabs/risingwave/blob/5a619444bb93dc5f2db78a72d34a2e6e316639fe/src/frontend/src/planner/insert.rs#L42-L44

**Comment by broccoliSpicy** [comment]
I implemented InputRef index rewiring and found some tricky bug. 
this approach won't work.
```sql
 dev=> create table tn (v1 int, v2 int);                                     
CREATE_TABLE
dev=> insert into tn (v2) values (1) returning v2 + 1;
 ?column? 
----------
        2
(1 row)

INSERT 0 1
dev=> insert into tn (v2) values (1) returning v2+1. v1;
 v1 
----
  2
(1 row)

INSERT 0 1
dev=> insert into tn (v2) values (1) returning v2+1, v1;
 ?column? | v1 
----------+----
        2 |   
(1 row)

INSERT 0 1
dev=> insert into tn (v2) values (1,5) returning v2+1, v1;                  
ERROR:  QueryError: Bind error: INSERT has more expressions than target columns
dev=> insert into tn (v2) values (1.5) returning v2+1, v1;                  
 ?column? | v1 
----------+----
        3 |   
(1 row)

INSERT 0 1
dev=> insert into tn (v2) values (1.5) returning v2+1, v1;
 ?column? | v1 
----------+----
        3 |   
(1 row)

INSERT 0 1
dev=> insert into tn (v2) values (1.5) returning v2 + 1.1;           │ 0:psql │                                                                     │
│  ?column?                                                            └────────┘                                                                     │
│ ----------                                                                                                                                          │
│       3.1                                                                                                                                           │
│ (1 row)   

```


I didn't check it through but I guess during function binding, we infer the function's input and return type based on the target table's schema, then do some type coercion
I am afraid more and more subtle bug will emerge with this approach...
index rewiring was supposed to be a hack but I guess it requires a lot of delicate patches.

I am thinking about mock a binding context before we bind returning list now

**Comment by st1page** [comment]
I used to be unfamiliar with this grammar and I find it is more powerful than I thought :hot_face: 

```SQL
dev=# with cte as (insert into t values (1, 20, 400, 5000), (2,60,600,6000) returning x,z) select sum(x) from cte;
 sum 
-----
  80
(1 row)

dev=# explain with cte as (insert into t values (1, 20, 400, 5000), (2,60,600,6000) returning x,z) select sum(x) from cte;
                                 QUERY PLAN                                 
----------------------------------------------------------------------------
 Aggregate  (cost=0.07..0.08 rows=1 width=8)
   CTE cte
     ->  Insert on t  (cost=0.00..0.03 rows=2 width=16)
           ->  Values Scan on "*VALUES*"  (cost=0.00..0.03 rows=2 width=16)
   ->  CTE Scan on cte  (cost=0.00..0.04 rows=2 width=4)
(5 rows)

```

**Comment by fuyufjh** [comment]
> ha, my bad, the above behavior is actually in conform with postgres.
I guess both index rewiring and mock binding context would work.
still implemented mock binding context though

Hey, may I ask any new updates?
