### ISSUE TITLE
More bugs when binding `insert` with unaligned source schema

### ISSUE THREAD

**Issue by Eurekaaw** [risingwavelabs/risingwave#9036]
### Describe the bug

We may need to better deal with unaligned source and insert schema.

### To Reproduce

```SQL
dev=> create table tn (v1 int, v2 int);
CREATE_TABLE
dev=> create table ipt (v1 int);
CREATE_TABLE
dev=> insert into tn select * from ipt;
ERROR:  QueryError: Bind error: INSERT has more target columns than expressions
dev=> insert into tn (v1) select * from ipt;
ERROR:  QueryError: Bind error: INSERT has more target columns than expressions
```

### Expected behavior

The two `insert` should be executed per Postgres.

**Comment by Eurekaaw** [comment]
I don't see a solution under current design and maybe some discussion is needed🥲

**Comment by BugenZhao** [comment]
Good point. Actually, I think it's okay that we only support a subset of the DML syntax from Postgres. For example, not supporting only providing the values for a prefix of columns. However, it makes no sense that the second statement cannot be executed. 😄

Would you mind issuing a fix for this?

**Comment by Eurekaaw** [comment]
Yes I'd love to, yet I haven't figured out a way.😭 Can we pad manual `Exprimpl`s (in this case, nulls) to `BoundQuery`? If so, how?

**Comment by Eurekaaw** [comment]
I think this is a side effect of #8770. This PR actually forced the input schema to be _aligned_ with the table schema (by _align_ I mean the field at corresponding index can be casted), while it shouldn't, if the input is a query rather than values. Above is a failed case while I find one more interesting one:
```SQL
dev=> create table t2 (v1 int, v2 int);
CREATE_TABLE
dev=> insert into t2 values (1, 2);
INSERT 0 1
dev=> insert into t2 (v1) select * from t2;
INSERT 0 1
dev=> select * from t2;
 v1 | v2 
----+----
  1 |  2
  1 |  2
(2 rows)
```

**Comment by Eurekaaw** [comment]
My idea is that https://github.com/risingwavelabs/risingwave/blob/5a619444bb93dc5f2db78a72d34a2e6e316639fe/src/frontend/src/binder/insert.rs#L315-L326 shall be removed and the "padding nulls" logic in `values` shall be recovered. Do you have any concerns or points to add? @xxchan @broccoliSpicy

**Comment by Eurekaaw** [comment]
Actually I'd prefer postpone the logic of padding nulls to the executor and the binder just gives a list of column indices that need to filled with null (or maybe other non-null default value as I'm working on😇). Otherwise I don't see a way to solve the insert from query case. cc. @BugenZhao

**Comment by broccoliSpicy** [comment]
> 



> I think this is a side effect of #8770. This PR actually forced the input schema to be _aligned_ with the table schema (by _align_ I mean the field at corresponding index can be casted), while it shouldn't, if the input is a query rather than values. Above is a failed case while I find one more interesting one:
> 
> ```sql
> dev=> create table t2 (v1 int, v2 int);
> CREATE_TABLE
> dev=> insert into t2 values (1, 2);
> INSERT 0 1
> dev=> insert into t2 (v1) select * from t2;
> INSERT 0 1
> dev=> select * from t2;
>  v1 | v2 
> ----+----
>   1 |  2
>   1 |  2
> (2 rows)
> ```

I don't see  how schema alignment gets involved here...
but our current behavior for this query here is semantically wrong, I suppose?
it might helpful if we have a comprehensive picture of postgres's insert semantic and a conclusion of to what degree risingwave conforms

**Comment by Eurekaaw** [comment]
#9208
