### ISSUE TITLE
Compile failed on Windows WSL2 Ubuntu 18.04.5

### ISSUE THREAD

**Issue by garyli1019** [risingwavelabs/risingwave#9037]
### Describe the bug

Hello, I followed the README and try to compile the project with `./risedev configure`, but got this error `collect2: fatal error: cannot find 'ld'`. I tried many solutions through Google with no luck, but chatgpt got the answer for me :) 

change this line https://github.com/risingwavelabs/risingwave/blob/8038315ebf6a24f48b473feb82effab4299c8570/.cargo/config.toml#L10 to `[target.'cfg(target_os = "linux")'.'linker="/usr/bin"']` works for me. I am new to rust so I don't know how to make a generic fix at this point. So if anyone can pick this up is greatly appreciated. 

### To Reproduce

compile on Windows WSL2

**Comment by xxchan** [comment]
Have you installed the required dependencies: https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#set-up-the-development-environment

I suspect it's `lld` not installed.

**Comment by garyli1019** [comment]
@xxchan `lld` is installed. It's somehow not found by the build system.

**Comment by xxchan** [comment]
The `.'linker="/usr/bin"'` looks weird. It doesn't seem to be valid https://doc.rust-lang.org/cargo/reference/config.html#targettriplelinks

So I suspect it is just equivalent to removing `[target.'cfg(target_os = "linux")']`, which means using default linker... That definitely works. We use `lld` to speed up build, but that's optional.

**Comment by xxchan** [comment]
I'm not sure why it doesn't work on your machine. Is `lld` available in your PATH?

**Comment by garyli1019** [comment]
> I'm not sure why it doesn't work on your machine. Is `lld` available in your PATH?

yes, `usr/bin` is in my PATH. This is a strange error and I have no clue why this happened. Probably just me. 

<img width="608" alt="image" src="https://user-images.githubusercontent.com/23007841/230611428-92127e0b-2527-4f68-9994-16d947110cd2.png">


Anyway, thanks for helping @xxchan . I will close this issue for now.
