### ISSUE TITLE
refactor(telemetry): avoid backtrace in `TrackingId::from_meta_store` error

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#9042]
Capturing a backtrace may segfault on Apple silicon #6205. We are still not able to find the root cause and fix it. In most cases, the issue would disappear after some random code change, usually in the next commit.

However, as another layer of safeguard, we should try to avoid capturing unnecessary backtrace, especially when the error is recoverable. This is the case for `TrackingId::from_meta_store`. The function can return an `Option` or a custom error type rather than `anyhow::Error`.
https://github.com/risingwavelabs/risingwave/blob/36dd239aa288ec196c37240b36eb7ada64633ff4/src/meta/src/telemetry.rs#L61-L68

This has caused #9038, although it is not blocking the latest commit, as explained above.

**Comment by odysa** [comment]
Closed since #9059 merged
