### ISSUE TITLE
longevity test fail when using lyvecloud storage

### ISSUE THREAD

**Issue by wcy-fdu** [risingwavelabs/risingwave#9054]
### Describe the bug

https://buildkite.com/risingwave-test/longevity-kubebench/builds/238#01875ada-8dbc-4ff2-8625-876beeaa50b3 

log:
![image](https://user-images.githubusercontent.com/58715567/230620979-f04c06d8-caa1-45ed-8e8a-466191dfe56b.png)

**Comment by lmatz** [comment]
@wcy-fdu rerun the test,
https://buildkite.com/risingwave-test/longevity-kubebench/builds/244#01876ede-19a1-4b9d-b977-d66ba35f9035
this time, it works fine.

**Comment by wcy-fdu** [comment]
This error is because compactor read a deleted sst/object:
>  "log": "2023-04-07T08:53:22.053740256Z stdout F 2023-04-07T08:53:22.053493Z ERROR risingwave_meta::barrier::recovery: inject_barrier failed err=Rpc error: gRPC error (Internal error): Actor 2 exit unexpectedly: Executor error: Storage error: Hummock error: ObjectStore failed with IO error Internal error: read \"hummock_001/245/194.data\" in block Some(BlockLocation { offset: 23848589, size: 469971 }) failed, error: NoSuchKey: The specified key does not exist."


However, after searching log, this object is not deleted by RisingWave(compactor), there is no log about `Finish vacuuming SSTs 194`. So I believe this is because this object is mistakenly deleted by others manually.

Just rerun the longevity test for lyvecloud storage for an hour, and it works fine, so let's close this issue.
