### ISSUE TITLE
bug: `decimal` ordering of `nan`, `-infinity` is wrong

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#9055]
### Describe the bug

In [PostgreSQL](https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL:~:text=In%20order%20to%20allow%20numeric%20values%20to%20be%20sorted%20and%20used%20in%20tree%2Dbased%20indexes%2C%20PostgreSQL%20treats%20NaN%20values%20as%20equal%2C%20and%20greater%20than%20all%20non%2DNaN%20values.) the `decimal` type supports special values `nan`, `infinity` and `-infinity` similar to those in `real` and `double precision`. Their ordering should be `-infinity` < normal values < `infinity` < `nan`.

Our wrapper type `Decimal` is not handling these special values properly.

### To Reproduce

```
dev=> values ('nan'::decimal), ('inf'), ('-inf'), ('2.') order by 1; -- wrong: nan is expected to be largest but is actually smallest
 *VALUES*_0.column_0 
---------------------
                 NaN
           -Infinity
                   2
            Infinity
(4 rows)

dev=> values ('nan'::float8), ('inf'), ('-inf'), ('2.') order by 1; -- correct behavior in float8
 *VALUES*_0.column_0 
---------------------
           -Infinity
                   2
            Infinity
                 NaN
(4 rows)

dev=> select '-inf'::decimal > 2; -- wrong during comparison, which is also inconsistent with ordering above
 ?column? 
----------
 t
(1 row)
```

### Expected behavior

```
test=# values ('nan'::decimal), ('inf'), ('-inf'), ('2.') order by 1;
  column1  
-----------
 -Infinity
         2
  Infinity
       NaN
(4 rows)

test=# values ('nan'::float8), ('inf'), ('-inf'), ('2.') order by 1;
  column1  
-----------
 -Infinity
         2
  Infinity
       NaN
(4 rows)

test=# select '-inf'::decimal > 2;
 ?column? 
----------
 f
(1 row)
```

### Additional context

The ordering bug is likely originated from memcomparable encoding.

The comparison bug is because of `derive(Ord)` on `enum`:
https://github.com/risingwavelabs/risingwave/blob/de6c5a352ab6cfbc034452e9a97006cde23a411b/src/common/src/types/decimal.rs#L33-L43

**Any idea of maintaining the consistency between memcomparable encoding and `Ord`?**

**Comment by murex971** [comment]
@xiangjinwu could you review this :eyes:
