### ISSUE TITLE
bug(expr): `SUBSTR` of unicode produces error: "byte index _ is not a char boundary"

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#9065]
We should not calculate by bytes, but by unicode character:

To reproduce:
Risingwave:
```sql
=> select substr('Mér', 1, 2);
SSL SYSCALL error: EOF detected
```

PSQL:
```sql
=> select substr('Mér', 1, 2);
 substr 
--------
 Mé
(1 row)
```

Similar for `''Mér'::char(3)`

---

resources:

src/expr/src/vector_op/substr.rs:48:23
https://github.com/risingwavelabs/risingwave/blob/95ab15c4dfa3b4b15086b4692812589b1b50bfc8/src/expr/src/vector_op/substr.rs#L37
https://stackoverflow.com/questions/4249745/does-postgresql-varchar-count-using-unicode-character-length-or-ascii-character

**Comment by xiangjinwu** [comment]
Similar problem exists for other string functions:
* overlay
* ascii
