### ISSUE TITLE
 The same UDF appearing in the `having` clause and `select` gets executed twice

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#9068]
For example:
```
SELECT   
a, 
b                                                                                                                                       
To_timestamp(b_timestamp) AS c,                                                                                   
UDF(Array_agg(XXX::varchar), 5) AS reentrancy_tag 
FROM  (select * from SomeSource limit 1) 
GROUP BY 
a, 
b, 
c
HAVING  UDF(Array_agg(XXX::varchar), 5) IS true;
```

The log added in `UDF` will print twice
but `(select * from SomeSource limit 1)` will only input one row into the `UDF`.

This could be inefficient.

To some extent, by only executing once, it also helps in some cases where UDF is indeterministic, although we don't encourage users to write such UDF.

**Comment by BugenZhao** [comment]
I think we may prefer correctness instead of efficiency here. Considering that `UDF` can be a volatile function (#9030), we should not deduplicate the function calls.

Take this query in Postgres as an example...
```sql
postgres=# select a, random(), random() from t0410 group by a having random() > 0.5;
 a |        random        |       random        
---+----------------------+---------------------
 3 |   0.8457575863625415 | 0.20531351263375086
 2 |   0.2681860763503394 | 0.05103449567782903
 1 | 0.027769006883058722 |  0.4268373359400002
(3 rows)
```

The `random` in `HAVING` is actually not referring to any other `random` calls in the select list, which can be proven by the third row in the result set.

> although we don't encourage users to write such UDF.

Agree. We should encourage users to write `WITH .. select * from cte where <condition>` instead of using `HAVING`.

**Comment by lmatz** [comment]
I see,
```WITH .. select * from cte where <condition>``` seems to be what I am looking for,
let me close this one

**Comment by wangrunji0408** [comment]
If the function is IMMUTABLE or STABLE ("is guaranteed to return the same results given the same arguments for all rows within a single statement"), then it should be safe to do [common subexpression elimination](https://en.wikipedia.org/wiki/Common_subexpression_elimination) at frontend?

**Comment by lmatz** [comment]
> If the function is IMMUTABLE or STABLE ("is guaranteed to return the same results given the same arguments for all rows within a single statement"), then it should be safe to do [common subexpression elimination](https://en.wikipedia.org/wiki/Common_subexpression_elimination) at frontend?

let me reopen it, I think it makes sense if we can separate different types of UDF by syntax/definition

**Comment by BugenZhao** [comment]
> If the function is IMMUTABLE or STABLE...

Agree, but we should take another discussion about whether specifying `IMMUTABLE` or `STABLE` for UDF is allowed, since it may [corrupt](https://dba.stackexchange.com/questions/108393/intentionally-corrupting-an-index-in-postgresql) our system. 😄

**Comment by wangrunji0408** [comment]
This sounds horrible. 🤯 It truly needs careful discussion. We should never let users crash our system. I think if there's a chance of crash, we'd better to ignore the volatility and assume them to be volatile. But if the fake immutable function only results in data errors, then optimization can be considered.

**Comment by xxchan** [comment]
> let me reopen it, I think it makes sense if we can separate different types of UDF by syntax/definition

close in favor of https://github.com/risingwavelabs/risingwave/issues/9030
