### ISSUE TITLE
double free or corruption, free(): invalid pointer

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#9075]
### Describe the bug

![SCR-20230405-lvq (1)](https://user-images.githubusercontent.com/5791930/230841140-6f3abfcc-edbe-496b-a101-7c646b224f2e.png)
![SCR-20230410-j3x](https://user-images.githubusercontent.com/5791930/230841177-11061a97-1893-492a-9a7d-c8d55d17581e.png)

separate deployment.

After the error message, the CN quit.

**Comment by liurenjie1024** [comment]
We may need to full stack to help identify this issue.

**Comment by lmatz** [comment]
Both happened in the prod cluster.


Enable https://doc.rust-lang.org/beta/unstable-book/compiler-flags/sanitizer.html#addresssanitizer in production? 
Does anyone know if this is common practice?

**Comment by xxchan** [comment]
<img width="648" alt="image" src="https://user-images.githubusercontent.com/37948597/230964739-7c00e02a-b6fd-4bb6-9e5d-0d4bd363e948.png">

**Comment by lmatz** [comment]
maybe we enable `core dump` in the production environment

**Comment by liurenjie1024** [comment]
How about we disable `task_local_alloca` and have a try? This is the first thing that comes up to my mind which my cause this issue.

**Comment by lmatz** [comment]
> How about we disable `task_local_alloca` and have a try? This is the first thing that comes up to my mind which my cause this issue.


This is also my first thought, I don't remember any bugs similar to these two have ever appeared before 4/5.

**Comment by lmatz** [comment]
We will enable core dump https://github.com/risingwavelabs/risingwave-test/issues/316

After that, we can re-enable `task_alloc` in our testing environment and try to reproduce and investigate.

I remove this from the 0.19 milestone.

**Comment by lmatz** [comment]
I see, I am just not aware of that, let's see how the new mechanism works
