### ISSUE TITLE
feat: SELECT * EXCEPT [columnA,columnB,...] 

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#9092]
It is a SQL grammar supported by Snowflake 
It can improve the usability of GroupTopN pattern https://www.risingwave.dev/docs/current/sql-pattern-topn/
Still need discussion. 
```SQL
SELECT * EXCEPT(rank)
  FROM (
    SELECT [column_list], 
      function_name() OVER ([PARTITION BY col1[, col2...]] 
        ORDER BY col1 [ ASC | DESC ][, col2 [ ASC | DESC ]...]) AS rank 
    FROM table_name)
WHERE rank <= N [AND conditions];
```

**Comment by xxchan** [comment]
This syntax is from BigQuery. It seems more reasonable for an AP system to support convenient syntax for ad-hoc queries 🤔, and less reasonable for us.

**Comment by xxchan** [comment]
Similar request for adding new syntax: https://github.com/risingwavelabs/risingwave/issues/7506

> My main concern is that adding new things may break other things in unexpected ways, especially for SQL, a complex and not well-designed language.
>
> Anyway, such topic might unavoidably involve a lot of bikeshedding, and I agree we should decide the general attitude before talking about specific sugars.

**Comment by lmatz** [comment]
I think it appears to be some dbt-level stuff, like a macro and users write that and get translated automatically, but still send the original to our Frontend to process. No changes need to be made on our side.

I do agree that it improves user experience.

**Comment by TennyZhuang** [comment]
> -1. It sounds very ad-hoc and not part of SQL standard, and it's very easy to work around.

I'm modifying a query related to a 35-cols table, and I think it's hard to work around :(

**Comment by st1page** [comment]
> > #9092
> 
> In all well-known database, only BigQuery supports that, but they use `EXCEPT` keyword :(

Sorry it is my typo :hot_face: :crying_cat_face:

_Originally posted by @st1page in https://github.com/risingwavelabs/risingwave/issues/10265#issuecomment-1584336311_

**Comment by TennyZhuang** [comment]
So at least both Snowflake and BigQuery support similar things.

**Comment by TennyZhuang** [comment]
https://cloud.google.com/spanner/docs/reference/standard-sql/query-syntax#select_list And Spanner

**Comment by TennyZhuang** [comment]
https://clickhouse.com/docs/en/sql-reference/statements/select#except
Clickhouse

**Comment by xxchan** [comment]
BTW, duckdb/snowflake use `EXCLUDE`

**Comment by st1page** [comment]
> BTW, duckdb/snowflake use `EXCLUDE`

we can implement it too :eyes:

**Comment by xxchan** [comment]
What do you mean? Isn't `EXCEPT` the same as `EXCLUDE`? We need to choose one name. 👀

**Comment by st1page** [comment]
> What do you mean? Isn't `EXCEPT` the same as `EXCLUDE`? We need to choose one name. eyes

You see, in SQL we can use different word for the same feature, such as "EXCEPT" and "MINUS"
