### ISSUE TITLE
bug(batch): `select ... limit 1` should not consume lots of memory

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#9093]
### Describe the bug

I know that we are working on batch query’s memory control, but for this case, I don’t think it needs so much memory. On the contrary, it should take zero operator memory + some limited network buffering memory in the pipeline.

Since our WIP batch memory management only address the operator memory, I suspect it won’t fix this case as well.

Thus, can we investigate the reason of this memory spike? 

Fig: The OOMKill happened at 21:58:27 (UTC)

![image](https://user-images.githubusercontent.com/10192522/231075294-a3a650a4-a56b-4ef8-a078-f3a9d55a482f.png)

Fig: …which is exactly the time of that select limit 1 query

![image](https://user-images.githubusercontent.com/10192522/231075309-767b62d2-eefd-4680-a386-012e9ef84540.png)

### Additional context

See more context in Slack: https://risingwave-labs.slack.com/archives/C03Q34JHLLC/p1681193626086009

**Comment by chenzl25** [comment]
In the worst case, it is possible that table scans kept generating data for channels (IIRC, at most 64 chunks per parallel unit). There could be a large amount of memory requirement for just a simple `limit 1` query.

**Comment by liurenjie1024** [comment]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/2771941/231361160-aba96802-cd7e-4565-a6d6-3848ac08b701.png">
<img width="398" alt="image" src="https://user-images.githubusercontent.com/2771941/231361197-e458bf2a-5487-478a-8fad-6b2469eb0329.png">
<img width="572" alt="image" src="https://user-images.githubusercontent.com/2771941/231361457-55caa5c0-dac1-442f-a395-61b1914d2328.png">


After checking grafana more carefully, it seems that jemalloc memory didn't increase much.

**Comment by liurenjie1024** [comment]
After @huangjw806 helped to remove manually specified storage memory and use default memory for storage, now all queries in recent days succeeded, but we still have oom for streaming query and mv on mv. See analysis here:
https://risingwave-labs.slack.com/archives/C048NM5LNKX/p1681703624838129?thread_ts=1681666156.283539&cid=C048NM5LNKX
https://risingwave-labs.slack.com/archives/C048NM5LNKX/p1681667607310329
