### ISSUE TITLE
feat: GroupTopN support output ranks

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#9094]
Currently, We have supported Top-N by groups. https://www.risingwave.dev/docs/current/sql-pattern-topn/ But we expose restrictions and do not allow users to get the `rank` or `row_number` in the column_list.
> `rank` cannot be included in column_list.

And that is recommended optimization by FlinkSQL https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/sql/queries/topn/#no-ranking-output-optimization. But FlinkSQL also supports the general case.

To achieve that, we must let our GroupTopN executor support maintain the rank/row_number in the output.
 
It is a small feature but can bring big changes on streamGroupTopN and we need more discussion to determine if we need that.

**Comment by BugenZhao** [comment]
I guess this can be hard to implement and large diffs might be yielded from small changes. 🥵

**Comment by st1page** [comment]
closed by https://github.com/risingwavelabs/risingwave/pull/10990
