### ISSUE TITLE
enhance integration test: Kafka CDC Sink + Debezium Json

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#9099]
There is an existing integration test: https://github.com/risingwavelabs/risingwave/tree/main/integration_tests/kafka-cdc-sink

We'd like to cover all the data types in the test with a relatively larger amount of data.
Also, we want to cover more `data change types`: https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-events

And we need to add a data correctness check since we lack one currently.

Integration tests are executed once per day.

**Comment by cyliu0** [comment]
Closed by https://github.com/risingwavelabs/risingwave/pull/13607
