### ISSUE TITLE
perf: optimize json parser

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#9113]
For q17

Now:
<img width="717" alt="Screenshot 2023-04-11 at 7 33 02 PM" src="https://user-images.githubusercontent.com/47273164/231352982-12e7e2af-d1b6-410e-bc5f-968f237ac527.png">

Before:
<img width="717" alt="Screenshot 2023-04-11 at 7 32 52 PM" src="https://user-images.githubusercontent.com/47273164/231352971-c02f8df5-5547-4339-9d60-4ef6126bcba1.png">

1. After investigation, we should setup some benchmarks for json parser which can catch this regression. (Or ignore this comment if they already do).
2. Overall, source throughput increased to 244,000 from 225,000. As such, normalized regression may be around 6% instead of 7%.
3. @tabVersion mentioned investigating #9086 may be helpful.
    > @tabVersionI don’t know if it is caused by this pr https://github.com/risingwavelabs/risingwave/pull/9086
it adds a loop for all keys when parsing every row to match the column names and the json keys ignoring cases

Here's the flamegraph:
![Screenshot 2023-04-12 at 12 55 22 PM](https://user-images.githubusercontent.com/47273164/231353721-b2c4a2bd-5502-418a-9ddf-6df62288c141.png)
[
Interactive version](https://file.notion.so/f/s/ed8cd62b-6297-40eb-9781-8c47f85c0335/perf.svg?id=d7fecaf1-b3e6-49ba-a6ce-16b46ee06553&table=block&spaceId=a409f923-73d6-4f09-a08a-7edd6555138b&expirationTimestamp=1681361687507&signature=QcnM4WyiaoGlSOdnNX0-jcLeb9qi41OsolI2tptx8co&downloadName=perf.svg&x=71.9966%25&y=837)

**Comment by tabVersion** [comment]
bench https://github.com/risingwavelabs/risingwave/pull/9195

**Comment by lmatz** [comment]
Went through the flame graphs generated in https://buildkite.com/risingwavelabs/main-cron/builds/458#0187c454-58bd-439a-bf57-6f774ea41b80

For queries q0,q1,q2,q3,q7,q8,q10,q14,q15,q17,q18,q20,q21,q22, json parser takes more time than other executors.

**Comment by kwannoel** [comment]
<img width="1146" alt="Screenshot 2023-04-28 at 1 18 28 PM" src="https://user-images.githubusercontent.com/47273164/235060497-9cc8657a-38ca-4da3-8f92-7cd61020b50b.png">

Likely need to optimize `append_datum_n`

**Comment by kwannoel** [comment]
Investigating it

**Comment by st1page** [comment]
The `SourceStreamChunkRowWriter` here only append one row to the `ArrayBuilderImpl` and it will take dynamic dispatch for each row. Maybe we can append a batch of data each time?

**Comment by kwannoel** [comment]
Another potential cost https://github.com/risingwavelabs/risingwave/blob/5fabd2a3dad4c30916c8c65b4052acabaf77234d/src/common/src/array/mod.rs#L481-L496

The inner match under the `Some` branch can also cost lots.
<img width="1492" alt="Screenshot 2023-04-28 at 1 40 29 PM" src="https://user-images.githubusercontent.com/47273164/235063758-c1f54359-c205-460c-9f2a-bf4f413a56fa.png">

**Comment by st1page** [comment]
> https://github.com/risingwavelabs/risingwave/blob/060b2334a4cfd4c9756ddb36dbb33fe8adabd934/src/common/src/array/mod.rs#L486

The `match` here leads to too many branches(`O(n^2)`) do you have any idea? @BugenZhao

**Comment by kwannoel** [comment]
> > https://github.com/risingwavelabs/risingwave/blob/060b2334a4cfd4c9756ddb36dbb33fe8adabd934/src/common/src/array/mod.rs#L486
> 
> The `match` here leads to too many branches(`O(n^2)`) do you have any idea? @BugenZhao

IMO we can just assert here for safety. Submitting a fix

**Comment by kwannoel** [comment]
> > > https://github.com/risingwavelabs/risingwave/blob/060b2334a4cfd4c9756ddb36dbb33fe8adabd934/src/common/src/array/mod.rs#L486
> > 
> > 
> > The `match` here leads to too many branches(`O(n^2)`) do you have any idea? @BugenZhao
> 
> IMO we can just assert here for safety. Submitting a fix

Sorry I misunderstood the macro syntax... Yeah it's doing dynamic dispatch as you mentioned @st1page. Probably need a bigger refactor to fix this.

**Comment by st1page** [comment]
closed with https://github.com/risingwavelabs/risingwave/pull/17146 and related PRs
cc @BugenZhao
