### ISSUE TITLE
Discussion: set streaming_parallelism in e2e tests

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#9117]
Currently we never set streaming_parallelism in e2e tests, thus tests may fail to reveal batch scheduling bugs, e.g. #9104.

One possible solution is randomize the streaming_parallelism in simulation test. @wangrunji0408

**Comment by wangrunji0408** [comment]
How is it set in normal e2e tests? 👀

**Comment by zwang28** [comment]
> How is it set in normal e2e tests? 👀

It's not set. So by default MV will use all available parallel units.

**Comment by wangrunji0408** [comment]
In simulation test, we have a config option to mock the return value of `std::thread::available_parallelism` in CN.
https://github.com/risingwavelabs/risingwave/blob/1cee7970842001cf7306ec996aae29822cb5c082/src/tests/simulation/src/main.rs#L58-L62
https://github.com/risingwavelabs/risingwave/blob/1cee7970842001cf7306ec996aae29822cb5c082/src/tests/simulation/src/cluster.rs#L284

IIRC we can set the default `streaming_parallelism` through it. Do you think it would be helpful?

**Comment by zwang28** [comment]
> IIRC we can set the default streaming_parallelism through it. Do you think it would be helpful?

I think it's different. We want to test the case that MV only use partial available PUs.
