### ISSUE TITLE
remove useless data_memory_limitor in compactor

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#9137]
Currently we allocate compactor_memory_limit_mb / 2 memory to the data memory limiter in compactor initialized here:
https://github.com/risingwavelabs/risingwave/blob/a002e05911b0d62ac001dab2f3054db93f36632c/src/storage/compactor/src/server.rs#L139

However, there is no usage of this limiter.

**Comment by Li0k** [comment]
Cloud we close this Issue? @hzxa21
