### ISSUE TITLE
validate compaction configuration on compactor startup

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#9139]
Otherwise, it can cause a stuck in compaction. 

For example, we use [`compactor_memory_limit_mb / 2` ](https://github.com/risingwavelabs/risingwave/blob/a002e05911b0d62ac001dab2f3054db93f36632c/src/storage/compactor/src/server.rs#L132) as the memory quota for a compaction task and a compaction task acquires [`sstable_size_mb + block_size_kb` ](https://github.com/risingwavelabs/risingwave/blob/a002e05911b0d62ac001dab2f3054db93f36632c/src/storage/src/hummock/compactor/compaction_utils.rs#L63) before proceeding. Therefore, `compactor_memory_limit_mb = 512MB, sstable_size_mb = 256MB, block_size_kb = 64KB` (which is the default config values) is not a valid combination.

**Comment by hzxa21** [comment]
cc @Little-Wallace @Li0k

**Comment by Li0k** [comment]
In the current implementation, memory_limiter is based on quota, so we still let the first task pass even if the configured memory is not enough to serve the task.

So `validate compaction configuration on compactor startup` is not a solution, it can only help us find configuration problems quickly
So I think there are a few more things we can do
1. validate compaction configuration on compactor startup
2. automatically configure the compactor_memory_limit_mb based on the node/container memory available for the compactor
3. detect memory and actively cancel tasks when there is not enough memory available

**Comment by Li0k** [comment]
Cloud we close this Issue? @hzxa21

**Comment by hzxa21** [comment]
> Cloud we close this Issue? @hzxa21 

sure
