### ISSUE TITLE
ApplyProjectTransposeRule should consider the impure expression

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#9167]
> > Oh my - this is scary. Are there any other optimizations we should be careful about?
> 
> I am not sure 🥵 I think we can only find them case by case currently. Do you have any idea to handle the impure function in the optimizer? @chenzl25

Another concern is `ApplyProjectTransposeRule` where impure functions could be used in the subquery.

_Originally posted by @chenzl25 in https://github.com/risingwavelabs/risingwave/issues/9133#issuecomment-1506633980_

**Comment by chenzl25** [comment]
If an apply is blocked by an impure expression it could lead to a query that cannot be untested, so I intend to don't consider impure expression in ApplyProjectTransposeRule
