### ISSUE TITLE
feat: support array_dims function

### ISSUE THREAD

**Issue by BanBuDu0** [risingwavelabs/risingwave#9177]
Support of array_dims() from postgres:

This function returning a text representation of an array's dimensions

Syntax:：
 ```array_dims ( anyarray ) → text```

SQL Example:

INPUT:
```SELECT array_dims(ARRAY[ [1,2,3],[4,5,6],[7,8,9] ]); ```

OUTPUT:
```
 array_dims 
------------
 [1:3][1:3]
(1 row)
```

**Comment by xiangjinwu** [comment]
Thanks for your interest. However, `array_dims` may not be an easy or proper one. As stated in ths tracking page:

> A significant difference between PostgreSQL array and RisingWave array/list is that the former requires multi-dimensional ones to be rectangular (like in C), while the latter allows jagged ones (like vector or list).

That means, we have no proper output to return for this query:
```
SELECT array_dims(ARRAY[ [1,2,3],[4,5],[6] ]);
```

We could report an error, but this also means we would have to recursively check all subarrays at each layer. At the same time, it just outputs a text representation, which is not easy to be combined with other functions and less frequently used.

If you are interested in extending the expression support, do you mind taking a look at #8937?

**Comment by BanBuDu0** [comment]
> Thanks for your interest. However, `array_dims` may not be an easy or proper one. As stated in the tracking page:
> 
> > A significant difference between PostgreSQL array and RisingWave array/list is that the former requires multi-dimensional ones to be rectangular (like in C), while the latter allows jagged ones (like vector or list).
> 
> That means, we have no proper output to return for this query:
> 
> ```
> SELECT array_dims(ARRAY[ [1,2,3],[4,5],[6] ]);
> ```
> 
> We could report an error, but this also means we would have to recursively check all subarrays at each layer. At the same time, it just outputs a text representation, which is not easy to be combined with other functions and less frequently used.
> 
> If you are interested in extending the expression support, do you mind taking a look at #8937?

Thinks, LGTM.
I will try  https://github.com/risingwavelabs/risingwave/issues/8937 first. 
And for this issue, I will try it later after https://github.com/risingwavelabs/risingwave/issues/8937, or others can also assign to themselves

**Comment by xiangjinwu** [comment]
#10197
