### ISSUE TITLE
bug: malloc(): unaligned tcache chunk detected.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#9225]
### Describe the bug

![image](https://user-images.githubusercontent.com/2771941/232416814-fb5ae384-b24b-401f-b9a9-e2948296d67d.png)

Found in our longetivty test's error report.

### To Reproduce

Not sure

### Expected behavior

It should not happend

### Additional context

More details can be found in slach channel: https://risingwave-labs.slack.com/archives/C048NM5LNKX/p1681667607310329

**Comment by fuyufjh** [comment]
Related https://github.com/risingwavelabs/risingwave/issues/9075

Agree with https://github.com/risingwavelabs/risingwave/issues/9075#issuecomment-1505183227. It's almost impossible to investigate with only a error message. We need to enable the core dump at longevity test

**Comment by liurenjie1024** [comment]
Duplicate with #9075
