### ISSUE TITLE
bug: frontend need restart to recover from breakdown

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#9239]
### Describe the bug

We encounter frontend breakdown, as below:
```
dev=> set visibility_mode to all;
SET_VARIABLE
dev=> select * from xxx limit 1;
ERROR:  QueryError: internal error: error trying to connect: deadline has elapsed
dev=> set visibility_mode to all;
SET_VARIABLE
dev=> select * from xxx limit 1;
ERROR:  QueryError: internal error: error trying to connect: dns error: failed to lookup address information: Name or service not known
```

After restarting frontend, the breakdown is gone.

### Additional context

There has been compute node leaving/joining the cluster. Can it be related to frontend's compute node client pool?

**Comment by ZENOTME** [comment]
Is possible following case happen🤔:
A compute node leaving but the worker_node_manager didn't update yet. And then the query try to get a rpc client using the outdated worker node so that the connect failed.

**Comment by zwang28** [comment]
> Is possible following case happen🤔:
A compute node leaving but the worker_node_manager didn't update yet. And then the query try to get a rpc client using the outdated worker node so that the connect failed.

The error remains for a long time until restart.

**Comment by ZENOTME** [comment]
> There has been compute node leaving/joining the cluster. 
Do we have a way to test this locally? E.g. leave/join a compute node manually using ctl.

**Comment by ZENOTME** [comment]
Do we have more concrate log to reproduce this bug? Such as what reschedule happen before compute join or leave the cluster.

**Comment by zwang28** [comment]
> Any more information can be provided?

Informed @ZENOTME it occurred again recently.
No other information from my side.
