### ISSUE TITLE
clearer error message: `Parse error: invalid digit found in string, executor: ProjectExecutor`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#9242]
![SCR-20230418-dg1](https://user-images.githubusercontent.com/5791930/232647665-ac6de170-fa55-4d9e-a22b-ac579f01c19a.png)

Hard to know the context. Maybe there is some wrong source data or......
A query from a design partners

**Comment by xiangjinwu** [comment]
Maybe this?
```
dev=> select hex_to_int256('1');
ERROR:  QueryError: Expr error: Parse error: invalid digit found in string
dev=> select hex_to_int256('0x1');
 hex_to_int256 
---------------
 1
(1 row)
```

**Comment by lmatz** [comment]
I think it is 
![SCR-20230418-g3e](https://user-images.githubusercontent.com/5791930/232664524-d1f88724-5bc0-4b66-96a6-1fa35d0764f9.png)

**Comment by lmatz** [comment]
![SCR-20230418-gd2](https://user-images.githubusercontent.com/5791930/232666116-5a5471d7-731b-4306-8ba8-e80d0d93ad74.png)
