### ISSUE TITLE
misassumption on the payload type in the debezium format

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#9243]
### Describe the bug

![image](https://user-images.githubusercontent.com/6970676/232648194-80a3ea38-fd70-415e-b118-72f867b49543.png)

We currently assume the `after `(as well as `before`) in the debezium record is ought to be a struct, while it also could be a string. This is found when we built the demo for mongodb cdc.

The standard mysql debezium event:
![image](https://user-images.githubusercontent.com/6970676/232648203-89e096c6-76fc-4d8a-a11c-7c1b9d56ab6c.png)

The mongodb debezium event:
![image](https://user-images.githubusercontent.com/6970676/232648221-ab9a7aa8-bbcb-40a0-8145-17114f7f5a5b.png)

We didn't expect the body could be a string instead of a struct.

### To Reproduce

I've built two demos that can reproduce the issue: https://github.com/risingwavelabs/risingwave/pull/9235

**Comment by hzxa21** [comment]
It feels like we should be aware of the specific type of the debezium source and parse the payload accordingly :(
