### ISSUE TITLE
sysbench performance regression

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#9251]
![SCR-20230418-kjs](https://user-images.githubusercontent.com/5791930/232729105-8da94f41-d8c8-4d41-bde4-e26114f59020.png)

http://risingwave-perf-test-dashboard-metabase.us-west-2.elasticbeanstalk.com/dashboard/29-sysbench-qps-history?start_date=2023-03-10&namespace=daily

**Comment by lmatz** [comment]
https://github.com/risingwavelabs/risingwave/pull/9125 related？

**Comment by chenzl25** [comment]
This PR https://github.com/risingwavelabs/risingwave/pull/9125 seems to have affected the performance of the sysbench, because the size of the block cache will be reduced. Will we change it back later? @liurenjie1024

**Comment by liurenjie1024** [comment]
> This PR #9125 seems to have affected the performance of the sysbench, because the size of the block cache will be reduced. Will we change it back later? @liurenjie1024

Yeah, after we figured out OOM issue.

**Comment by fuyufjh** [comment]
@liurenjie1024 any updates?

**Comment by lmatz** [comment]
I will reopen one issue later after sysbench + standalone mode + customized configuration for serving is done
