### ISSUE TITLE
bug: nexmark recovery test in scaling test (deterministic simulation) fails

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#9256]
### Describe the bug

One of many examples from `main`: https://buildkite.com/risingwavelabs/main/builds/3797#01877b12-330d-408c-8d5e-06616cdee163
One example from `main-cron`: https://buildkite.com/risingwavelabs/main-cron/builds/426

**Comment by lmatz** [comment]
Occasionally, it passes https://buildkite.com/risingwavelabs/main/builds/3853

**Comment by zwang28** [comment]
I suspect it's related to madsim's network connection delay/failure injection? @wangrunji0408 

Example 1: madsim unwrap on failed request
`thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Status { code: Unavailable, message: "connection reset", source: None }', /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-tonic-0.2.20/src/client.rs:164:22`

Example 2: worker node fails, because it sends request to meta when the worker node is already heartbeat timeout.
`thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GrpcStatus(Status { code: Internal, message: "Worker node does not exist!", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Thu, 10 Mar 2022 04:31:16 +0000"} }, source: None })', src/storage/compactor/src/server.rs:82:49`

**Comment by wangrunji0408** [comment]
Example 1 is a bug of madsim which has been fixed last Friday.
Example 2, seems like the error should be ignored instead of panicked.

**Comment by zwang28** [comment]
> Example 2, seems like the error should be ignored instead of panicked.

I see several unwrap() during compute node/frontend/compactor startup. They are kind of reasonable because it's cheap to restart for an uninitialized node.

**Comment by BugenZhao** [comment]
> They are kind of reasonable because it's cheap to restart uninitialized node.

Agree. This is reasonable for deployment in reality. 🥵

BTW, may I ask how we handle panics in `madsim`? Does the test case fail immediately after a panic occurs?

**Comment by wangrunji0408** [comment]
Madsim supports auto restarting nodes on panic. We used to enable it when error handling on CN was not completed. But soon it was disabled. Currently the test fails on any panic. 🥵

**Comment by BugenZhao** [comment]
> Madsim supports auto restarting nodes on panic. We used to enable it when error handling on CN was not completed. But soon it was disabled. Currently the test fails on any panic. 🥵

Maybe we can match `"Worker node does not exist!"` for an exception? 🥵🥵🥵

**Comment by wangrunji0408** [comment]
> > Madsim supports auto restarting nodes on panic. We used to enable it when error handling on CN was not completed. But soon it was disabled. Currently the test fails on any panic. 🥵
> 
> Maybe we can match `"Worker node does not exist!"` for an exception? 🥵🥵🥵

This is feasible. I'll add support in madsim.

**Comment by zwang28** [comment]
I'm afraid catching the error doesn't solve all cases, for example [this error](https://buildkite.com/risingwavelabs/pull-request/builds/21866#018798ec-ead5-442c-a609-b5ecb8515e63) is from frontend's `MetaClient::activate`.
`thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: internal error: connection refused`

**Comment by wangrunji0408** [comment]
> I'm afraid catching the error doesn't solve all cases, for example [this error](https://buildkite.com/risingwavelabs/pull-request/builds/21866#018798ec-ead5-442c-a609-b5ecb8515e63) is from frontend's `MetaClient::activate`.
> 
> ```
> 
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: internal error: connection refused
> 
> ...
> 
> /risingwave/src/frontend/src/session.rs:259
> 
> ```

We can change unwrap to expect and put certain error messages.

**Comment by wangrunji0408** [comment]
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: 
GrpcStatus(Status { code: Internal, message: "Worker node does not exist!", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Thu, 10 Mar 2022 04:31:16 +0000"} }, source: None })', 
src/storage/compactor/src/server.rs:82:49
```

For this error, after another thought I suspect there may be a problem and the panic shouldn't be allowed.
The `register_new` and `activate` functions should be called continuously, without a long gap between them in the simulation.
cc @yezizp2012  Do you have any idea on why this happened?

**Comment by yezizp2012** [comment]
> ```
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: 
> GrpcStatus(Status { code: Internal, message: "Worker node does not exist!", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Thu, 10 Mar 2022 04:31:16 +0000"} }, source: None })', 
> src/storage/compactor/src/server.rs:82:49
> ```
> 
> For this error, after another thought I suspect there may be a problem and the panic shouldn't be allowed. The `register_new` and `activate` functions should be called continuously, without a long gap between them in the simulation. cc @yezizp2012 Do you have any idea on why this happened?

Oh, I think I know what's happening. After #7460 , the heartbeat timeout is already applied for scaling test. 🥵  In this case the compactor was killed and just happened to be restarted near the expiry time. The compactor was kicked out right between `register_new` and `activate`. Currently `register_new` won't advance its TTL time, for this case I will submit a PR to fix it.

**Comment by yezizp2012** [comment]
New error found in this run: https://buildkite.com/risingwavelabs/main/builds/3902
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: internal error: service not found: /meta.NotificationService/Subscribe
--
  | 0: <risingwave_common::error::RwError as core::convert::From<risingwave_common::error::ErrorCode>>::from
  | at /risingwave/src/common/src/error.rs:174:33
  | 1: <T as core::convert::Into<U>>::into
  | at /rustc/28a29282f6dde2e4aba6e1e4cfea5c9430a00217/library/core/src/convert/mod.rs:727:9
```
The root case could be: meta was killed and restarted after a downtime of 20s+, a new meta got elected but the RPC service   In new leader haven't had time to initialize when receiving subscribe request. Even though there's a retry logic in subscribe, but the config `max_heartbeat_interval_secs` is `10s` in scaling test, which is the same as the lease expire duration and used as retry upper bound. But the possible killing downtime is set to 20s+, so it is possible to reach the retry upper bound for subscribe and still not have the leader meta node running. 🥵  Cc @shanicky

**Comment by shanicky** [comment]
Now the `max_heartbeat_interval_secs` has been adjusted to 15s in scaling recovery test, and the restart delay is adjusted to 20s. Currently, the CI on the main branch looks good.

**Comment by lmatz** [comment]
Since it hasn't happened again since 3 weeks ago, let's close this issue. We will open a new one if it appears again.
