### ISSUE TITLE
Tracking: Executor Microbenchmark Dashboard

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#9272]
Many performance related PRs recently. To avoid regression we should do the following in CI:

- [x] Run performance micro benchmark for **critical** components in CI daily. It should be "high-level" components. For instance `executor` benchmarks. https://github.com/risingwavelabs/risingwave/pull/9307
- [x] Publish results to our performance dashboard.

cc @cyliu0 may need your help for step 2.

Extras: https://github.com/risingwavelabs/risingwave/issues/8906

**Comment by kwannoel** [comment]
> related to #9216 ?

Nope, this is specific to microbenchmarks, will not generate flamegraph, just graph the `time taken` per benchmark on performance dashboard.

In contrast, #9218 runs nexmark benchmarks and obtain a flamegraph from there.

**Comment by lmatz** [comment]
Went through the flame graphs generated in https://buildkite.com/risingwavelabs/main-cron/builds/458#0187c454-58bd-439a-bf57-6f774ea41b80

For queries q0,q1,q2,q3,q7,q8,q10,q14,q15,q17,q18,q20,q21,q22, json parser takes more time than other executors.
