### ISSUE TITLE
implement `bit_and` / `bit_or` / `bit_xor` for smallint / int / bigint

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#9281]
```
bit_xor ( smallint ) → smallint
bit_xor ( integer ) → integer
bit_xor ( bigint ) → bigint
```
Computes the bitwise exclusive OR of all non-null input values. 

Can be useful as a checksum for an unordered set of values. This is useful for testing.

**Comment by st1page** [comment]
I thingk it is trival to implement xor, toucan just xor the result and the coming value no matter it is insert or delete.
