### ISSUE TITLE
Implement `string_to_array`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#9283]
aka `split`, a fundamental operation,
wonder if there is any other workaround?

**Comment by Eurekaaw** [comment]
> string_to_array ( string text, delimiter text [, null_string text ] ) → text[]
Splits the string at occurrences of delimiter and forms the resulting fields into a text array. If delimiter is NULL, each character in the string will become a separate element in the array. If delimiter is an empty string, then the string is treated as a single field. If null_string is supplied and is not NULL, fields matching that string are replaced by NULL. See also [array_to_string](https://www.postgresql.org/docs/current/functions-array.html#FUNCTION-ARRAY-TO-STRING).
string_to_array('xx~~yy~~zz', '~~', 'yy') → {xx,NULL,zz}

Do we need to support both 2-parameter and 3-parameter version?

**Comment by lmatz** [comment]
it seems only the last parameter, null string, is optional, not sure if I understand you correctly?

The first two input arguments are necessary. We can first support the basic one without the last parameter if the last one introduces much complexity. It is the most common use case.

**Comment by Eurekaaw** [comment]
Yes, my bad. The third parameter isn't a big problem yet I'm trying to solve the case where the second parameter is `NULL`...

**Comment by Eurekaaw** [comment]
closed by merged #9289
