### ISSUE TITLE
perf(hashkey): refine the memory reserving for SerializedKey

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#9305]
> I think it is not good enough, we can get each row's value encoding size like https://github.com/risingwavelabs/risingwave/pull/8924. And after that, we can avoid any grow of the vec

_Originally posted by @st1page in https://github.com/risingwavelabs/risingwave/pull/8885#discussion_r1162656430_

**Comment by kwannoel** [comment]
More info from @st1page offline:
> In nexmark q17, it works well because all the string have the same length and they comes from date, but we need to optimize it in more case :h

**Comment by kwannoel** [comment]
Additionally:
- Fixed size key should use different estimation, it does not use value encoding.
- Serialized key can use value encoding estimation, since that's how its currently encoded.
