### ISSUE TITLE
Add an integration test for debezium + cassandra

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#9331]
the intention is to enhance the feature completeness of our debezium connector support. we have already added a test for MySQL https://github.com/risingwavelabs/risingwave/tree/main/integration_tests/debezium-mysql 

refer to the pr for details

**Comment by lmatz** [comment]
@sumittal Feel free to assign an owner, thanks!

**Comment by fuyufjh** [comment]
@abhyuday26 Hi, any updates?

**Comment by abhyuday26** [comment]
It is on hold right now, someone with more expertise in cassandra is required to finish this.
