### ISSUE TITLE
feat(batch): Observability of batch engine

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#9367]
### Is your feature request related to a problem? Please describe.

Currently, due to some unkown reason, the batch engine's metrics is empty.

Todo list:

- Support metrics in Grafana:
  - [ ] QPS by nodes
  - [ ] QPS by type of commands
  - [ ] QPS by execution mode
- Query logs
  - [ ] #9368

**Comment by lmatz** [comment]
![SCR-20230423-jmr](https://user-images.githubusercontent.com/5791930/233822936-61826c2f-1fd1-4ab3-8544-be4b5056e1b4.png)

There are a few(not enough) metrics under the `Frontend` panel.
