### ISSUE TITLE
estimate jsonb size

### ISSUE THREAD

**Issue by yuhao-su** [risingwavelabs/risingwave#9377]

**Comment by st1page** [comment]
very similar but different https://github.com/risingwavelabs/risingwave/issues/8915

**Comment by BanBuDu0** [comment]
In our system, we define a max_len, and simply use the last batch's len as the  estimated size for string or other uncertain length type if the size less than max_len

**Comment by xiangjinwu** [comment]
would be trivial after #11805

**Comment by yuhao-su** [comment]
#12952
