### ISSUE TITLE
string starting with "-0x" not working in hex_to_int256

### ISSUE THREAD

**Issue by abhyuday26** [risingwavelabs/risingwave#9388]
### Describe the bug

As title

### To Reproduce

Execute simple query
`select hex_to_int256('-0x11');`
![image](https://user-images.githubusercontent.com/70817539/233910028-0fe41229-45d2-4629-a157-4b53bedbc69e.png)

### Expected behavior

We should have got
```
select hex_to_int256('-0x11');
----
-17
```
But we got
```
select hex_to_int256('-0x11');
ERROR:  QueryError: Expr error: Parse error: failed to parse hex '-0x11', invalid digit found in string
```

### Additional context

Implemented in #9146

**Comment by lmatz** [comment]
I think we don't expect users to use `-` to represent negative numbers, cc @shanicky

**Comment by shanicky** [comment]
For our `hex_to_int256`, we put the sign bit in hex after "0x", so we do not support representations such as "-0xff" as it can cause confusion.

**Comment by abhyuday26** [comment]
Please update it into e2e_test https://github.com/risingwavelabs/risingwave/blob/66bab914e4396c0a55bf441f694acdd3cfc0d49f/e2e_test/batch/types/int256.slt.part#L65

**Comment by shanicky** [comment]
> Please update it in e2e_test
> 
> https://github.com/risingwavelabs/risingwave/blob/66bab914e4396c0a55bf441f694acdd3cfc0d49f/e2e_test/batch/types/int256.slt.part#L65

It seems to be an outdated branch. Which branch did you see the test?

**Comment by abhyuday26** [comment]
I got it in https://github.com/risingwavelabs/risingwave/pull/9146/files#diff-bc958632e02167d83b4fb100daac1827e12ada7308c4ddad53d82dc4d1ef07a4
