### ISSUE TITLE
Discussion: ability to enable debug logs in release build

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#9401]
> We have enabled [release_max_level_info](https://github.com/risingwavelabs/risingwave/blob/415b0701fc59915b818e2b2e30c0682e8cb472d0/src/utils/workspace-config/Cargo.toml#L21) but IIUC it just means that we DEBUG/TRACE logs will not be included in the binary.

which means setting `RUST_LOG=debug` does not work for a release build? 
then https://github.com/risingwavelabs/kube-bench/pull/100/files will have no effect I suppose, right?

https://github.com/risingwavelabs/risingwave/pull/9258#issuecomment-1519409396

_Originally posted by @lmatz in https://github.com/risingwavelabs/risingwave/issues/9258#issuecomment-1519364434_

**Comment by lmatz** [comment]
Although #9414 enabled the debug level log in release build, let's keep this issue for a while and see if there is any concern

**Comment by BugenZhao** [comment]
Can we close this issue?

**Comment by hzxa21** [comment]
done by #9414
