### ISSUE TITLE
bug: The dbz format is allowed to be created when using backhole sink.

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#9440]
### Describe the bug

```sql
create table t (v1 int, v2 int);
create sink invalid_dbz_type_sink from t with (connector = 'blackhole', type = 'debezium');
```

### Expected behavior

It's supposed to fail but actually succeeded.

### Additional context

**NOTE**:
Once fixed, please add the above test case in `e2e_test/sink/append_only_sink.slt`.

**Comment by xx01cyx** [comment]
I believe we should introduce a better framework to check sink configurations in the connector node. We should be able to define fields as `optional` or `required` and specify possible values for each field in an easy way. cc @wenym1

**Comment by fuyufjh** [comment]
@tabVersion Can you please take a look?

**Comment by tabVersion** [comment]
> @tabVersion Can you please take a look?

@neverchanje what `type` is accepted in blackhole sink? or blackhole sink should not work with `type` attr
