### ISSUE TITLE
bug: the with clause accepts non-existing option

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#9450]
### Describe the bug

```
create sink s5 from t with (connector = 'blackhole', abc = 'true');
```

If `abc` is an option that has been deprecated and deleted, the user's old DDL statement that uses this option may still be able to work. This is unexpected. We should only allow the options that are handled in the code.

### Expected behavior

Most databases reject unrecognized params. For example:

```
postgres=# create table t () with (abc = '123');
ERROR:  unrecognized parameter "abc"
```

**Comment by BugenZhao** [comment]
Related: #7034

**Comment by tabVersion** [comment]
there gonna be a refactor in the source part, may include this proposal
