### ISSUE TITLE
bug(kafka source): the `upsert` option allows illegal value

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#9470]
### Describe the bug

```
dev=> create source invalid_upsert_source with (
dev(>   connector = 'kafka',
dev(>   topic = 'kafka_1_partition_topic',
dev(>   upsert = 'invalid',
dev(>   properties.bootstrap.server = '127.0.0.1:29092'
dev(> ) row format json;
CREATE_SOURCE
```

The statement with `upsert = 'invalid',` is allowed, which is illegal in fact.

### Expected behavior

We should only allow 'true' or 'false'.

### Additional context

Add the above test case to e2e_test/source/basic/ddl.slt after fixed.

**Comment by idx0-dev** [comment]
This option has been removed. #9457
