### ISSUE TITLE
Per actor metrics: should be cleaned when the actor is dropped or moved.

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#9492]
## Porblem

The leaked actor memory not only consumes extra memory but also affect the metrics. As the screenshot shows, the Actor 24 has already been dropped, but the metrics still exist.

<img width="815" alt="image" src="https://user-images.githubusercontent.com/10192522/234563913-514feb33-25ac-4eb3-bd75-685b1148d89e.png">

## Cause

The is caused by the design of `MetricVec` (actually a hashmap of `labels -> single metrics`) in the Prometheus client library.

For example, 

```rust
pub agg_cached_keys: GenericGaugeVec<AtomicI64>,
```

which is actually backed by `MetricVec`

```
/// The underlying implementation for [`GaugeVec`] and [`IntGaugeVec`].
pub type GenericGaugeVec<P> = MetricVec<GaugeVecBuilder<P>>;
```

When call it with `with_label_values`, a new key (`label`) will be created in that hashmap e.g.

```rust
this.metrics
    .agg_cached_keys
    .with_label_values(&[&table_id_str, &actor_id_str])
    .set(vars.agg_group_cache.len() as i64);
```

But it's never been removed. 

## Solution

Similar to `LockGuard`, one solution I can tell is to wrap the `MetricVec` varaibles e.g. `agg_cached_keys` within a handler object, and remove itselves' key (label) from `MetricVec`'s hashmap when being dropped.

**Comment by fuyufjh** [comment]
Quite annoying when investigating problems... 🥲 Hope to be fixed

**Comment by MrCroxx** [comment]
IMO, the streaming actor metrics imitate how the batch task metrics are cleaned (with customized `Collector`). Related issues: #3832 #4844 #5742. What are your opinions? @fuyufjh @ZENOTME

**Comment by MrCroxx** [comment]
And currently `StreamingMetrics` contains metrics of task level, actor level, executor level, etc, which can be split into multiple metrics for better lifetime management.

**Comment by fuyufjh** [comment]
> IMO, the streaming actor metrics imitate how the batch task metrics are cleaned (with customized `Collector`). Related issues: #3832 #4844 #5742. What are your opinions? @fuyufjh @ZENOTME

Sounds good to me. Similar to the solution that I imagined before (described in the PR's desciption) i.e. using something to hold the lifetime of these actor-level metrics

**Comment by ZENOTME** [comment]
> IMO, the streaming actor metrics imitate how the batch task metrics are cleaned (with customized Collector). Related issues: #3832 #4844 #5742. What are your opinions? @fuyufjh @ZENOTME

+1. I think it's the same problem and it solved in #9378.

**Comment by fuyufjh** [comment]
@MrCroxx Any further updates?

**Comment by MrCroxx** [comment]
Worked on the new file cache engine before. Let me get back to this PR these days.

**Comment by lmatz** [comment]
![SCR-20230818-oj4](https://github.com/risingwavelabs/risingwave/assets/5791930/13598d0b-060f-4457-a4ad-7b2b081c01d1)
The example above is an aggregation.
Als have a case for join.
