### ISSUE TITLE
The CSV parser needs to differentiate between an empty cell and an empty string.

### ISSUE THREAD

**Issue by idx0-dev** [risingwavelabs/risingwave#9506]
### Describe the bug

For parsing a CSV table like below,
```
a,b,c
1,"",2
,,4
```
and a table with schema 
```
create table (a int, b varchar,c int) ...
```
our parser will produce rows like:
```
1,"",2
NULL,"",4
```

It works fine for non-string type (like int), produces a `NULL` when cell is blank.
But the parser can not distint between an empty string ("" in L2) and an blanck cell (L3).

### Expected behavior

The empty cell should be parsed to NULL instead of an empty string.

**Comment by waruto210** [comment]
fixed by #8709
