### ISSUE TITLE
bug(kafka source): security properties are unhandled when protocol is not specified

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#9519]
### Describe the bug

When properties.security.protocol is not specified, RisingWave will just ignore other security properties.

### To Reproduce

```
dev=> create source s with (
dev(>   connector = 'kafka',
dev(>   topic = 'kafka_1_partition_topic',
dev(>   properties.bootstrap.server = '127.0.0.1:29092',
dev(>   properties.sasl.mechanism= 'SCRAM-SHA-512',
dev(>   properties.sasl.username = 'alice',
dev(>   properties.sasl.password = 'alice-secret'
dev(> ) row format json;
CREATE_SOURCE
```

### Expected behavior

Technically, the command should fail and warn that 'properties.security.protocol' is not specified.

**Comment by tabVersion** [comment]
according to https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md , `properties.security.protocol` has a default value `plaintext`
