### ISSUE TITLE
lease keeper failed grpc request error: status: Unavailable, message: etcdserver: request timed out, waiting for the applied index took too long

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#9530]
Not a bug as explained by @yezizp2012  that it can be a performance issue of `etcd`.

Open an issue to track it.

Slack: https://risingwave-labs.slack.com/archives/C048771BGKF/p1682665115090129

**Comment by yezizp2012** [comment]
Cc @shanicky

**Comment by shanicky** [comment]
It seems that after we switched the disk where etcd is mounted to a more advanced model, this issue hasn't occurred, has it? cc @lmatz

**Comment by lmatz** [comment]
You are right, I am not aware of any in recent tests
Let's close it. We can reopen it if it appears again.


Just leave a record:
We now use EBS gp3 default configuration(3000IOPS 125MB/s) for `etcd`.
Originally, we use EBS gp2. The performance of gp2 depends on its volume size. Since we allocate small size, its performance is terrible.
