### ISSUE TITLE
feat: support scale-in of upstream sources such as kinesis(shard) and kafka(partition)

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#9531]
We have supported the scale-out case.

https://www.confluent.io/blog/project-metamorphosis-elastic-kafka-clusters-in-confluent-cloud/
https://docs.aws.amazon.com/streams/latest/dev/kinesis-record-processor-scaling.html

**Comment by shanicky** [comment]
We are attempting to support in-place split reduction, which means that when split reduction occurs, it will not affect the distribution of other splits, even if split increase and reduction occur simultaneously. Only the clearing of the source executor's state needs to be handled in this case. However, if split migration is necessary in the future, we still need to use the pause/resume + reschedule command. Also, if split reduction occurs during scaling, we will ignore it and perform split reduction after scaling is completed.
