### ISSUE TITLE
Investigate process memory difference from heap memory.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#9535]
From some longevity test, we find that  the gap between node(process) memory and heap memory is almost nearly 3G:
<img width="805" alt="image" src="https://user-images.githubusercontent.com/2771941/235103934-890c3c49-d087-4277-a461-9599fa2c48d3.png">

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/2771941/235104019-11b991b1-d47b-4831-8134-f29813996780.png">

This is quite interesting and may affect our memory management policy. Some tools maybe used to find the gap:
1. size can be used find the size of different segment of elf file.
2. pmap command can be used to find the size of different segments of a running process.

**Comment by ZENOTME** [comment]
duplicated with #9669.
