### ISSUE TITLE
insert returning panic when returning implicit padded NULL values

### ISSUE THREAD

**Issue by broccoliSpicy** [risingwavelabs/risingwave#9539]
### Describe the bug

perhaps we shouldn't punt the NULL padding logic to the batch executor.

### To Reproduce
```sql
dev=> create table t (v1 int, v2 real);
CREATE_TABLE
dev=> insert into t (v2) values (1) returning *;
SSL SYSCALL error: EOF detected
The connection to the server was lost. Attempting reset: Failed.
```

### Expected behavior
```sql
postgres=# create table t1 (v1 int, v2 real);
CREATE TABLE
postgres=# insert into t1 (v2) values (1) returning *;
 v1 | v2 
----+----
    |  1
(1 row)

INSERT 0 1
postgres=# 
```

**Comment by broccoliSpicy** [comment]
@BugenZhao PTAL

**Comment by broccoliSpicy** [comment]
I think revert the NULL padding punt we did earlier is the easiest way to fix this.

[NULL padding punt PR](https://github.com/risingwavelabs/risingwave/pull/9208)

**Comment by broccoliSpicy** [comment]
just out of curiosity, do we have a design to handle `create table td (v1 int default 1, v2 int);` ?

in the case of `create table t( a int, b timestamp default current_timestamp);`, we may want to evaluate the function as soon as the prompt arrives I suppose?
so we need to handle it in the frontend?
in a distributed system like risingwave, there might be some inconsistency if we handle `create table t( a int, b timestamp default current_timestamp);` in the batch executor.

**Comment by Eurekaaw** [comment]
> just out of curiosity, do we have a design to handle `create table td (v1 int default 1, v2 int);` ?

Yes! See #8999

**Comment by broccoliSpicy** [comment]
![Screenshot from 2023-04-29 21-31-27](https://user-images.githubusercontent.com/93440049/235305784-2b2bb5fd-ea00-4e46-bbf0-aa044d9afb12.png)

this is not very kind of you ...
