### ISSUE TITLE
build: try to optimize compile time

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#9553]
A while ago we used `sccache` to reduced *a lot of* compile time in CI, but didn't really look into our codebase and dependencies to improve it. So the local DX is not improved.

We haven't optimized it for long and it also bloated *a lot*, so it's worth to at least take a look to see if there's any low-hanging fruits.

<details><summary>One year ago (~90s)</summary>
<p>

![image](https://user-images.githubusercontent.com/37948597/235655092-a4802960-1609-414f-bef5-f548b7b2c247.png)

</p>
</details> 

<details><summary>Now (~210s)</summary>
<p>

<img width="923" alt="image" src="https://user-images.githubusercontent.com/37948597/235656848-ce01b240-6b57-4433-8814-ea7a541d6968.png">

</p>
</details> 

---

Some simple observations:
- `risingwave_common` - `risingwave_expr` - `risingwave_connector` is the pipeline breaker
- `aws-sdk-ec2` is the 2nd largest monster dependency (70+s!!🫠), but we only have very simple usage of it (https://github.com/risingwavelabs/risingwave/blob/main/src/meta/src/rpc/cloud_provider.rs). It's not very economical and may be worth to build HTTP request manually with [`reqsign`](https://github.com/Xuanwo/reqsign) (or use `aws-sigv4` since we already have that dependency by `aws-sdk-s3`)

**Comment by xxchan** [comment]
- [Profile on my Mac (full debug build)](https://github.com/risingwavelabs/risingwave/files/11372662/cargo-timing-20230502T100112Z.html.zip)
- [Profile on CI (debug build - all sccache hit)](https://buildkite.com/organizations/risingwavelabs/pipelines/pull-request/builds/22739/jobs/0187dc61-3d7f-489a-9a48-862777d329c1/artifacts/0187dc65-860f-42e0-adf3-b0091103c351)

**Comment by xxchan** [comment]
How to interpret and optimize this 🤔 
```
❯ cargo llvm-lines -p risingwave_meta | head -n 20
   Compiling risingwave_meta v1.0.0-alpha (/Users/xxchan/Projects/risingwave/src/meta)

    Finished dev [unoptimized + debuginfo] target(s) in 1m 12s
  Lines                  Copies                Function name
  -----                  ------                -------------
  6130075                154730                (TOTAL)
   110282 (1.8%,  1.8%)    1044 (0.7%,  0.7%)  alloc::alloc::box_free
    84098 (1.4%,  3.2%)     258 (0.2%,  0.8%)  tokio::runtime::task::core::Cell<T,S>::new
    65258 (1.1%,  4.2%)    1298 (0.8%,  1.7%)  std::panicking::try
    59840 (1.0%,  5.2%)     176 (0.1%,  1.8%)  alloc::raw_vec::RawVec<T,A>::grow_amortized
    57498 (0.9%,  6.1%)     160 (0.1%,  1.9%)  tonic::server::grpc::Grpc<T>::unary::{{closure}}
    57408 (0.9%,  7.1%)     128 (0.1%,  2.0%)  tokio::util::trace::task
    56393 (0.9%,  8.0%)     476 (0.3%,  2.3%)  <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
    53218 (0.9%,  8.9%)    1298 (0.8%,  3.1%)  std::panicking::try::do_catch
    50505 (0.8%,  9.7%)     105 (0.1%,  3.2%)  hashbrown::raw::RawTable<T,A>::reserve_rehash
    49456 (0.8%, 10.5%)    1370 (0.9%,  4.1%)  core::result::Result<T,E>::map_err
    42445 (0.7%, 11.2%)      83 (0.1%,  4.1%)  tonic::server::grpc::Grpc<T>::map_request_unary::{{closure}}
    40418 (0.7%, 11.9%)     638 (0.4%,  4.5%)  core::iter::traits::iterator::Iterator::fold
    36943 (0.6%, 12.5%)     413 (0.3%,  4.8%)  core::iter::traits::iterator::Iterator::try_fold
    36900 (0.6%, 13.1%)     258 (0.2%,  5.0%)  tokio::runtime::task::harness::poll_future
    36864 (0.6%, 13.7%)     256 (0.2%,  5.1%)  tokio::runtime::task::list::OwnedTasks<S>::bind
    36757 (0.6%, 14.3%)     971 (0.6%,  5.8%)  tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
    35380 (0.6%, 14.8%)     938 (0.6%,  6.4%)  core::option::Option<T>::map
```

**Comment by xxchan** [comment]
Only 122.9s on CI now https://buildkite.com/organizations/risingwavelabs/pipelines/pull-request/builds/23051/jobs/0187f61b-41ca-4488-89e1-08f6904047f8/artifacts/0187f61e-9e8b-4d6e-81a8-15ecc740ef35

**Comment by xxchan** [comment]
This is the output of `cargo llvm-lines -p risingwave_compute`. In monomorphization, HashJoin's code got copied hundreds of times. 🤡

```
  Lines                  Copies                Function name
  -----                  ------                -------------
  6032075                130402                (TOTAL)
   612192 (10.1%, 10.1%)    224 (0.2%,  0.2%)  risingwave_stream::executor::hash_join::HashJoinExecutor<K,S,_>::eq_join_oneside::{{closure}}
   215208 (3.6%, 13.7%)     112 (0.1%,  0.3%)  risingwave_stream::executor::hash_join::HashJoinExecutor<K,S,_>::into_stream::{{closure}}
   206640 (3.4%, 17.1%)     112 (0.1%,  0.3%)  risingwave_stream::executor::hash_join::HashJoinExecutor<K,S,_>::new
   192648 (3.2%, 20.3%)    1949 (1.5%,  1.8%)  <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
   140801 (2.3%, 22.7%)    1422 (1.1%,  2.9%)  alloc::vec::Vec<T,A>::extend_trusted
   129255 (2.1%, 24.8%)    1961 (1.5%,  4.4%)  core::iter::traits::iterator::Iterator::fold
    99288 (1.6%, 26.5%)     112 (0.1%,  4.5%)  risingwave_stream::executor::hash_join::HashJoinExecutor<K,S,_>::handle_watermark::{{closure}}
    91769 (1.5%, 28.0%)    1422 (1.1%,  5.6%)  alloc::vec::Vec<T,A>::extend_trusted::{{closure}}
    74118 (1.2%, 29.2%)    1645 (1.3%,  6.9%)  core::iter::adapters::map::map_fold::{{closure}}
    70769 (1.2%, 30.4%)    1645 (1.3%,  8.1%)  <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
    69755 (1.2%, 31.5%)     536 (0.4%,  8.5%)  alloc::vec::Vec<T,A>::extend_desugared
    69660 (1.2%, 32.7%)      60 (0.0%,  8.6%)  risingwave_stream::executor::top_n::utils::TopNExecutorWrapper<E>::top_n_executor_execute::{{closure}}
    61629 (1.0%, 33.7%)     453 (0.3%,  8.9%)  <dyn risingwave_expr::expr::Expression>::eval_row_infallible::{{closure}}
    59198 (1.0%, 34.7%)     578 (0.4%,  9.4%)  alloc::alloc::box_free
    56918 (0.9%, 35.6%)     459 (0.4%,  9.7%)  <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
    50819 (0.8%, 36.5%)    1425 (1.1%, 10.8%)  core::option::Option<T>::map
    48406 (0.8%, 37.3%)    1751 (1.3%, 12.2%)  core::iter::traits::iterator::Iterator::for_each
    48384 (0.8%, 38.1%)    1792 (1.4%, 13.5%)  risingwave_stream::executor::hash_join::HashJoinExecutor<K,S,_>::eq_join_oneside::{{closure}}::{{closure}}
    41820 (0.7%, 38.8%)     123 (0.1%, 13.6%)  alloc::raw_vec::RawVec<T,A>::grow_amortized
    40432 (0.7%, 39.5%)    1344 (1.0%, 14.7%)  risingwave_stream::executor::hash_join::HashJoinExecutor<K,S,_>::new::{{closure}}

```

**Comment by xxchan** [comment]
ergonomic proc macros are quite slow to compile 🤡 

<img width="475" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/9742ee56-9570-46d0-ba2c-d61cb8ebe901">

**Comment by xxchan** [comment]
## Full debug build

After recent optimization (mostly removing/unifying dependencies), there are -- no much improvement  🚀

Because the bottleneck protobuf-src is not improved.

<img width="401" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/7945b8f9-f1fe-4181-8349-4ce183e65e70">

We might need to either dynamic link it, or opt-out it (see also https://github.com/risingwavelabs/risingwave/issues/9852)

## Incremental debug build
- #9629 Should helped quite some by removing a pipeline breaker.
- Why meta compiles slow is unknown yet.

**Comment by xxchan** [comment]
Very interesting, why the "codegen" time reduced a lot?

Now
<img width="800" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/9d36bc89-3b32-41fe-9278-35aee11c1b36">

Before
![Uploading image.png…]()

**Comment by xxchan** [comment]
`cargo rustc -p risingwave_meta -- -Z self-profile` and summarize https://github.com/rust-lang/measureme

```
+---------------------------------------+-----------+-----------------+
| Item                                  | Self time | % of total time |
+---------------------------------------+-----------+-----------------+
| LLVM_module_codegen_emit_obj          | 14.95s    | 34.593          |
+---------------------------------------+-----------+-----------------+
| LLVM_passes                           | 6.29s     | 14.549          |
+---------------------------------------+-----------+-----------------+
| codegen_module                        | 4.59s     | 10.625          |
+---------------------------------------+-----------+-----------------+
| evaluate_obligation                   | 2.14s     | 4.961           |
+---------------------------------------+-----------+-----------------+
| typeck                                | 1.92s     | 4.452           |
+---------------------------------------+-----------+-----------------+
| monomorphization_collector_graph_walk | 1.19s     | 2.750           |
+---------------------------------------+-----------+-----------------+
| codegen_select_candidate              | 1.10s     | 2.540           |
+---------------------------------------+-----------+-----------------+
```

[summarize.txt](https://github.com/risingwavelabs/risingwave/files/11519042/summarize.txt)

**Comment by BugenZhao** [comment]
> In monomorphization, HashJoin's code got copied hundreds of times. 🤡

#9618 may help, but I'm not sure if there's coverage decrease (just like #9659).

**Comment by xxchan** [comment]
https://github.com/risingwavelabs/risingwave/issues/2833

**Comment by xxchan** [comment]
I think the slowness of meta is largely (also) because of async-trait. It takes a lot of time to tyck. e.g., `ddl_controller.run_command`

<img width="1262" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/54d9cf09-4e5f-43c3-9f4f-f42733d0e163">

**Comment by xxchan** [comment]
Why some dependencies are compiled twice??

<img width="831" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/a6e7ac3f-574e-4a95-9114-eaa0a58e77dd">

<img width="895" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/65f73907-8ae2-4273-bf96-706a11729312">

**Comment by xxchan** [comment]
After removing `workspace-hack`, there are no duplicates anymore, and total time (fresh debug build) dropped from 400s to 300s 🤡

**Comment by xxchan** [comment]
If we use `resolver=1`, then we have only 991 pkgs to build 🤡

**Comment by xxchan** [comment]
> Why log is compiled once with and once without release_max_level_debug

I think this is because `release_max_level_debug` is only used as normal dependency (in `workspace-config`, which is excluded by hakari), so the feature is not unified with `build-dependency`. 

If we add `log` and `tracing` to `workspace-config`'s `[build-dependencies]`, there will only be 1037pkgs built.

---

But things like `aws-sdk-s3` and `zstd-sys` are still compiled twice.

**Comment by xxchan** [comment]
> But things like `aws-sdk-s3` and `zstd-sys` are still compiled twice.

This is because `workspace-hack` is compiled twice, which is because `workspace-hack` is depended by proc macro crates `risingwave_common_proc_macro` and `prost_helpers`. 

After removing `workspace-hack` from them, there will only be 1019 pkgs compiled. (1016 crates if we also add log and tracing to workspace-config's [build-dependencies])

**Comment by xxchan** [comment]
Although the issue above isn't it's fault, I'm pondering whether `workspace-hack` is generally beneficial for us 🤔️. 

It can be very helpful if we `-p` different packages frequently (maybe also help `cargo test`?). Don't know whether it's the case for our developers. I mainly only `risedev p`, `risedev test`, and `risedev dapt`. 🤣 

But it doesn't have any large drawbacks (unless used wrongly...).

---

But if we want to unify features, why don't we simply use `resolver=1`. I think we don't depend on any stuff that needs different features on build dependencies...

**Comment by BugenZhao** [comment]
> Although the issue above isn't it's fault, I'm pondering whether `workspace-hack` is generally beneficial for us 🤔️.
> 
> It can be very helpful if we `-p` different packages frequently (maybe also help `cargo test`?). Don't know whether it's the case for our developers. I mainly only `risedev p`, `risedev test`, and `risedev dapt`. 🤣

+1. We may survey how many developers are accustomed to clicking "Run Test" in their IDE.
