### ISSUE TITLE
bug: should not allow `NOW` in generated columns

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#9571]
In RisingWave, the `NOW` function under streaming execution behaves like an updatable stream of the latest timestamp, while the `PROCTIME` function means a snapshot of the timestamp when the record is processed.

Currently, we can create a source or table with a generated column of `NOW`, which has some semantics issues as above. We should not allow this from happening and encourage users to use `PROCTIME` here.

```
dev=> CREATE TABLE t3 (v INT, t timestamptz as now()) WITH (
    connector = 'datagen',
    fields.v.kind = 'sequence',
    fields.v.start = '1',
    fields.v.end  = '10',
    datagen.rows.per.second='15',
    datagen.split.num = '1'
) ROW FORMAT JSON;
ERROR:  QueryError: internal error: Rpc error: gRPC error (Internal error): Expression error: Unsupported function: Ok(Now)


dev=> CREATE SOURCE t3 (v INT, t timestamptz as now()) WITH (
    connector = 'datagen',
    fields.v.kind = 'sequence',
    fields.v.start = '1',
    fields.v.end  = '10',
    datagen.rows.per.second='15',
    datagen.split.num = '1'
) ROW FORMAT JSON;
CREATE_SOURCE
dev=> create materialized view mv as select * from t3;
ERROR:  QueryError: Expr error: Unsupported function: Ok(Now)
```

Note that we do report errors here but it's not that intuitive. Instead, the error messages reveal another issue of the frontend. Previously we handled these time-related expressions by rewriting them with constants during the binding phase. However, it's now possible that some expressions reside in the table's catalog, so we fail to catch them. This may also affect select-from-source of `PROCTIME`, or these functions in default column values.

cc @yuhao-su @Eurekaaw

**Comment by fuyufjh** [comment]
Any updates? cc. @yuhao-su

**Comment by yuhao-su** [comment]
It will panic now... I'll take a look
