### ISSUE TITLE
ERROR:  QueryError: internal error: error trying to connect: dns error: failed to lookup address information: Name or service not know

### ISSUE THREAD

**Issue by mneedham** [risingwavelabs/risingwave#9591]
### Describe the bug

I was trying to create a sink:

```
CREATE SINK orderItems_sink FROM orderItems_view 
WITH (
   connector='kafka',
   type='append-only',
   properties.bootstrap.server='redpanda:29092',
   topic='orderItems'
);
```

And I got this error:

```
ERROR:  QueryError: internal error: error trying to connect: dns error: failed to lookup address information: Name or service not known
```

So I was thinking that maybe it couldn't access my Redpanda server.

Looking at the compute node logs I saw the underlying error:

```
compute-node-0    | 2023-05-04T13:25:41.261614Z  WARN risingwave_rpc_client::meta_client: failed to fetch members from http://meta-node-0:5690: status: Unavailable, message: "error trying to connect: dns error: failed to lookup address information: Name or service not known", details: [], metadata: MetadataMap { headers: {} }
```

### Expected behavior

Can we bubble up to the user that this is a problem trying to fetch members (does that mean worker nodes) and maybe indicate what they should do about it.

**Comment by StrikeW** [comment]
Hi @mneedham, it seems that you have given an unexpected hostname to the Kafka server `properties.bootstrap.server='redpanda:29092'`, you should specify a public accessible host to the server. The `redpanda` doesn't seem to be a valid one.

**Comment by yezizp2012** [comment]
```
compute-node-0    | 2023-05-04T13:25:41.261614Z  WARN risingwave_rpc_client::meta_client: failed to fetch members from http://meta-node-0:5690: status: Unavailable, message: "error trying to connect: dns error: failed to lookup address information: Name or service not known", details: [], metadata: MetadataMap { headers: {} }
```
It indicates that the compute node can't connect to the meta node due to some dns resolving problem. Did this log always appear? Could you please describe in detail how you started the cluster and provide the configuration of the cluster?
