### ISSUE TITLE
ERROR risingwave_rpc_client::meta_client: worker expired: Invalid worker: 1

### ISSUE THREAD

**Issue by mneedham** [risingwavelabs/risingwave#9594]
### Describe the bug

Not sure if this is a bug, but I've seen all of my nodes shut down with this error message:

```
ERROR risingwave_rpc_client::meta_client: worker expired: Invalid worker: 1
```

It seems like this happens if we get back a heartbeat status of 'UnknownWorker'. But how am I getting these unknown workers?!

### Expected behavior

Is it the correct behaviour to shutdown the node if there's an unknown worker? If so then I guess I can just set the pod/container to automatically restart if it's shutdown.

**Comment by zwang28** [comment]
> But how am I getting these unknown workers?!

If the worker (compute node/frontend/compactor) fails to send heartbeat timely, meta node will remove them from cluster. Any further heartbeat request from these worker will be responded with "UnknownWorker", which subsequently tells the worker to shutdown.

> Is it the correct behaviour to shutdown the node if there's an unknown worker? If so then I guess I can just set the pod/container to automatically restart if it's shutdown.

Yes.
