### ISSUE TITLE
feat(catalog): support rw_catalog.rw_sources/rw_materialized_views etc

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#9607]
### Is your feature request related to a problem? Please describe.

In order to support the display of some richer information of different relations including mv, source, sink, index etc. i.e. support for columns including `name`, `connector type`, `data format` for `source`.

**Comment by yezizp2012** [comment]
Cc @Gogomoe , I have introduced some system tables under `rw_catalog`, could you please check and help to switch those queries on system tables under `pg_catalog` to these ones in cloud side? Feel free to ping me if you find any missing requirements like more columns or tables that could be added under `rw_catalog`. After that, I will do some refactoring on current implementation of system tables under `pg_catalog` to to ensure they are fully compatible with PostgreSQL. 🙏

**Comment by Gogomoe** [comment]
Thanks @yezizp2012 !  corresponding cloud issue is created 
![image](https://github.com/risingwavelabs/risingwave/assets/12986936/9538b3bf-592c-4d98-9a6a-41ed1dd506a0)
