### ISSUE TITLE
report error when schema not specified for ROW FORMAT JSON

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#9620]
### Is your feature request related to a problem? Please describe.

More user friendly

### Additional context

https://risingwave-community.slack.com/archives/C02T3F7UYM6/p1683289234402609

**Comment by Harry-Gao-H** [comment]
Hi, can I check that the current behavior is 
```
dev=> CREATE SOURCE IF NOT EXISTS source_test
WITH (
   connector='kafka',
   topic='demo_topic',
   properties.bootstrap.server='localhost:29092',
   scan.startup.mode='latest',
   scan.startup.timestamp_millis='140000000'
)
ROW FORMAT JSON;
CREATE_SOURCE
```
and the expected behavior is
```
dev=> CREATE SOURCE IF NOT EXISTS source_test
WITH (
   connector='kafka',
   topic='demo_topic',
   properties.bootstrap.server='localhost:29092',
   scan.startup.mode='latest',
   scan.startup.timestamp_millis='140000000'
)
ROW FORMAT JSON;
ERROR:  QueryError: schema not specified
```

**Comment by xxchan** [comment]
Yes. Ideally maybe with a more user-friendly error message. And this also applies to `CREATE TABLE`

**Comment by Harry-Gao-H** [comment]
Hi @xxchan, I have added the error message and tried to create test cases in planner test accordingly (#10483).
When I run `./risedev do-apply-planner-test`, the output for create_source_test is created successfully, while it fails for create_table_test, with the error 
```
failures:
    create_table_test

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 65 filtered out; finished in 0.04s


--- STDERR:              risingwave_planner_test::planner_test_runner create_table_test ---
Test #0 (id: create_table_without_schema_in_json) failed, SQL:
create table t with(connector='kafka') row format json;

Error: Invalid input syntax: Json schema definition not specified
```

It confuses me because I think the two SQLs will throw the same error. 
Can I get some suggestions from you on how to solve this problem?

**Comment by xxchan** [comment]
@Harry-Gao-H, I guess this might be a bug of the planner test framework. You can use e2e test instead, or try to fix it if you are interested. cc @st1page now I agree slightly more with your motivation to refactor planner test. 😅

**Comment by Harry-Gao-H** [comment]
Thanks :)  I will add e2e test instead.
