### ISSUE TITLE
bug(storage): panic: inserted new level is not the newest

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#9655]
### Describe the bug

Log: [https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Fri[…]843c94eb.log$3Fstart$3D1683474600000](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Frisingwave$252Ftest-useast1-eks-a$252Fusrlngvty-20230507-093744/log-events/ip-10-0-53-25.ec2.internal-risingwave.var.log.containers.benchmark-risingwave-meta-m-0_usrlngvty-20230507-093744_meta-eec865d381f243748ca86409405b29deb647b432af908970c468476d843c94eb.log$3Fstart$3D1683474600000)

### To Reproduce

Can be steadily reproduced by running longevity test for more than 8 hours

### Additional context

See more discussions in Slack: https://risingwave-labs.slack.com/archives/C034TRN6A49/p1683509737106699

**Comment by hzxa21** [comment]
relevant fix: #9600

**Comment by hzxa21** [comment]
fixed by #9600
