### ISSUE TITLE
feat(telemetry): indicate if cluster was spawned via cloud or standalone

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#9681]
### Is your feature request related to a problem? Please describe.

To compare number of cloud users compared to number of standalone users.

Can further help to diagnose if any ci / benchmark pipelines are running with telemetry enabled.

### Describe the solution you'd like

> @odysa: There is currently no way to know where clusters are launched. Maybe we can add a flag to it.

**Comment by odysa** [comment]
Maybe we can set an environment variable to indicate where the clusters are running.
