### ISSUE TITLE
Create a materialized view which contains several joins

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#9687]
Tpch q2 would be a good candidate.

**Comment by fuyufjh** [comment]
@lmatz Could you please take a look?

**Comment by lmatz** [comment]
![SCR-20230718-tb3](https://github.com/risingwavelabs/risingwave/assets/5791930/e4aaaad0-6305-4ff2-a37c-b74c721320f7)
![SCR-20230718-tbd](https://github.com/risingwavelabs/risingwave/assets/5791930/61c2f43f-cff9-4c30-a30d-04044755c1b2)

We have executed tpch q2 for a period of time now:http://risingwave-perf-test-dashboard-metabase.us-west-2.elasticbeanstalk.com/collection/97-modified-tpch-q2-bs-medium-1cn

As the figure shows, the source throughput and sink throughput are both quite high, i.e. enough to saturate the throughput of an iceberg sink in the short term I suppose (without concurrent writes?).

But we need to integrate it with the sink. If the sink is ready, we can work in the `kube-bench` repo to construct the end-to-end pipeline.
