### ISSUE TITLE
Tracking: Split SST by Partition inside compaction

### ISSUE THREAD

**Issue by Li0k** [risingwavelabs/risingwave#9698]
Related to https://github.com/risingwavelabs/risingwave/issues/8707

This issue proposes a solution to make the compaction have better parallelism and lower write amplification by aligning the bounds of sst by partition. 

#### Implementation
- If we use partition, we will no longer split by size at l0 and base level, ensuring that each vnode has fewer files, which is more efficient for the picker.  https://github.com/risingwavelabs/risingwave/pull/9614
- Introducing split by node partition on meta and compactor https://github.com/risingwavelabs/risingwave/pull/8759
- Static vnode partition https://github.com/risingwavelabs/risingwave/pull/9750
- Dynamic vnode partition

#### Test
- MultiBuilder Micro Bench
- Benchmark https://github.com/risingwavelabs/risingwave/pull/9750
I have conducted three nexmark benchmark tests, with q7, 'q4+q7' and q20, respectively.
In q4, q7 and q20 benchmark tests, we did not find any improvement except that compaction throughput of vnode partition scheme is higher than that of main.
We also found performance regression of vnode partition scheme in q20.
Performance reports and grafana can be found in https://github.com/risingwavelabs/risingwave/pull/9750

**Comment by soundOfDestiny** [comment]
I have conducted three nexmark benchmark tests, with q7, 'q4+q7' and q20, respectively.
In q4, q7 and q20 benchmark tests, we did not find any improvement except that compaction throughput of vnode partition scheme is higher than that of main.
We also found performance regression of vnode partition scheme in q20.
Performance reports and grafana can be found in https://github.com/risingwavelabs/risingwave/pull/9750
