### ISSUE TITLE
Enable the query log in cloud environment

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#9710]
### Is your feature request related to a problem? Please describe.

Enabling the query log in a cloud environment is crucial for analyzing users' issues. The kernel will determine whether to enable the query log or not by checking an environment variable called `RW_QUERY_LOG_PATH`. To illustrate, execute `RW_QUERY_LOG_PATH=/the/path/to/log/ ./risedev d full`, and two logs - `query.log` and `slow_query.log` - will be generated in `/the/path/to/log/`. Additionally, it's worth noting that recording more information (such as timestamp) is necessary to make the query log practical enough for use in a product environment.

**Comment by Nebulazhang** [comment]
cc @arkbriar @fuyufjh 
can we print the query log into stdout? and we can label the kernel/query logs with different regex by the log collector.

**Comment by BugenZhao** [comment]
> cc @arkbriar @fuyufjh
> can we print the query log into stdout? and we can label the kernel/query logs with different regex by the log collector.

Do you mean #10793 ?

**Comment by fuyufjh** [comment]
> can we print the query log into stdout? and we can label the kernel/query logs with different regex by the log collector.

I don't think this is a best practice... But as required by @arkbriar , #10793 has been added
