### ISSUE TITLE
Meta node in chaos mesh tests takes 10~15 minutes to detect the failure of CN node

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#9712]
### Describe the bug

CN-1 Pod killed around 22:18, but meta detect the failure around 22:32 and starts to recover. The recovery is successful though.

![SCR-20230509-o6a](https://github.com/risingwavelabs/risingwave/assets/5791930/88c894a5-dde9-4121-8141-f5ad65b01ea7)
![SCR-20230509-o9l](https://github.com/risingwavelabs/risingwave/assets/5791930/36612f26-4200-4dd9-8257-2b6ea8610a09)
![SCR-20230509-o3s](https://github.com/risingwavelabs/risingwave/assets/5791930/426bd051-6828-4bd1-a4e0-205031a0de77)

https://risingwave-labs.slack.com/archives/C048NM5LNKX/p1683558910090979

**Comment by yezizp2012** [comment]
Since the recovery process is triggered by failure of inject and collect barrier, so if meta didn't detect the CN gone (and no hang about the network issue in k8s env), it must be hang somewhere other than injection and collection barrier with CNs. After looking at the detailed logs and reviewing the code related to the barrier handling process, here are just some random guess about it:
1. CN-1 pod killed around 22:18.
2. barrier manager is handling a success barrier complete response and somehow hang, otherwise it should be dealing with barrier injection and trigger recovery immediately.
3. after 10~15mins, barrier manager turned to handle a failed barrier complete response in the buffered channel and recovery triggered.

**Comment by yezizp2012** [comment]
![image](https://github.com/risingwavelabs/risingwave/assets/14160025/f890df0e-adfa-4f79-b688-7006a9fc210e)

During the downtime, the barrier numbers were not updated, nor were all the barrier latencies. At the time of the recovery trigger, the timer for the barrier latency recorded up to 10+ minutes. It indicates that the barrier manager hanged for 10mins+ during the timer, when it was handling the result of a successful barrier complete response. After that `complete_barrier` returns ok and then failed at handling a failed buffered barrier complete response.

https://github.com/risingwavelabs/risingwave/blob/21e01135d6a688a17a89654de4f1395037cba79d/src/meta/src/barrier/mod.rs#L880

**Comment by yezizp2012** [comment]
There’s one thing that quite confusing: if it was cause by some hang issues in kernel side, the deterministic recovery test should have already covered and found it. The failover situation in the test is more random and demanding than chaosmesh. 🥵

**Comment by lmatz** [comment]
> if it was cause by some hang issues in kernel side, the deterministic recovery test should have already covered and found it.

Not sure if I understand Madsim correctly,

since meta eventually detects the failure and recovers successfully, it seems it does not hang forever. 
If it does not hang forever, then in Madsim, even a long period of time will be compressed into several milliseconds in the simulation, which is unable to expose this hang-for-a-while problem. 🤔

**Comment by yezizp2012** [comment]
> since meta eventually detects the failure and recovers successfully, it seems it does not hang forever. If it does not hang forever, then in Madsim, even a long period of time will be compressed into several milliseconds in the simulation, which is unable to expose this hang-for-a-while problem. 🤔

Actually each run of a test statement in the deterministic recovery will be retried up to 5 times with a maximum time of about 31s in Madsim world. Unless the run is also hang-for-a-while in frontend, but I don't find any slow query logs in longevity test and deterministic recovery test. So this retry strategy will expose the hang-for-a-while problem.

**Comment by yezizp2012** [comment]
updates: 
After some further investigation, I found some more clues. Different from deterministic recovery test, the kill pod operation is different: it will start a new CN firstly and then kill the original one. Use the case in this issue as example:
1. start to kill pod, new `compute-c-1` started at `2023-05-08T22:16:57` and start to serve, there were no actors running in this pod.
2. old `compute-c-1` received shutdown signal and finally exited at `2023-05-08T22:17:24`, which is roughly 30 seconds after the new one started. DNS resolution would continue to point to it until it exited.

So it indicates that there were two different states of CN co-existing during the kill-pod operation. At that time, the old CN was in a status of graceful shutdown and the new one was serving without any running actors. So meta was somehow hang-for-a-while during handling the result of a successful barrier complete response.

**Comment by fuyufjh** [comment]
Reopened. This case (https://github.com/risingwavelabs/risingwave/issues/9712#issuecomment-1543642491) also needs to be handled correctly. 

> > It will try to register for like 5m if using the default configuration.
> Is 5m too long? I think in any cases recovery should be done in seconds.
>
> Also we may continue to work on https://github.com/risingwavelabs/risingwave/issues/9712, no matter it’s SIGKILL or SIGTERM or even 2 compute nodes coexists shortly

**Comment by yezizp2012** [comment]
Related: https://github.com/risingwavelabs/risingwave-test/issues/440

**Comment by fuyufjh** [comment]
It seems that killing CN pod with `--grace-peroid 0` can reproduce the problem

**Comment by yezizp2012** [comment]
> It seems that killing CN pod with `--grace-peroid 0` can reproduce the problem

More infos:

> To delete a pod forcefully, you can use the kubectl delete pod command with the --force and --grace-period=0 options. The --force option will delete the pod immediately, and the --grace-period=0 option will terminate the pod immediately without waiting for the grace period.
