### ISSUE TITLE
bug: barrier stuck for minutes 

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#9723]
### Describe the bug

The metrics diagram looks broken, because no barriers are collected during a long time.

Both barrier number and latency are very high.

<img width="1850" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/19fba0b3-1759-4843-bde8-47d21b86af36">

During the whole running [https://g-2927a1b4d9.grafana-workspace.us-east-1.amazonaws.com/d/EpkBw5W4k/risingwave-test-dashboard?org[…]90631&from=1683537069000&to=1683623809000](https://g-2927a1b4d9.grafana-workspace.us-east-1.amazonaws.com/d/EpkBw5W4k/risingwave-test-dashboard?orgId=1&var-namespace=usrlngvty-20230508-090631&from=1683537069000&to=1683623809000)

![image](https://github.com/risingwavelabs/risingwave/assets/10192522/c068a7eb-8bd4-4a0d-a51c-f102c5e90e2c)

### To Reproduce

Longevity test

### Additional context

[Await-Tree Dump of Compute Node 3.txt](https://github.com/risingwavelabs/risingwave/files/11430869/Await-Tree.Dump.of.Compute.Node.3.txt)
[Await-Tree Dump of Compute Node 4.txt](https://github.com/risingwavelabs/risingwave/files/11430877/Await-Tree.Dump.of.Compute.Node.4.txt)
[Await-Tree Dump of Compute Node 5.txt](https://github.com/risingwavelabs/risingwave/files/11430871/Await-Tree.Dump.of.Compute.Node.5.txt)

See more context in Slack channel: https://risingwave-labs.slack.com/archives/C034TRPKN1F/p1683627627166979

**Comment by kwannoel** [comment]
Slack notification: https://risingwave-labs.slack.com/archives/C048NM5LNKX/p1683623832327539
Buildkite: https://buildkite.com/risingwave-test/longevity-kubebench/builds/302

**Comment by kwannoel** [comment]
Test configuration:

<img width="661" alt="Screenshot 2023-05-12 at 1 48 54 PM" src="https://github.com/risingwavelabs/risingwave/assets/47273164/2ed6638b-eb3d-417d-bcab-6c2b90a3ce65">

**Comment by fuyufjh** [comment]
The problem is caused by:

1. The state of distinct table of aggregation has bad locality
2. When the amount of data reached become larger than meta cache, the meta cache miss caused high read latency
3. The read latency caused longer barrier latency, since the number of rows in one epoch is constant (not well backpressured, which may be a potential problem to be improved)
