### ISSUE TITLE
bug(batch): distributed query holds hummock version/snapshot for long time

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#9732]
### Describe the bug

We observer both min version and min snapshot being stuck for days, co-occurrence with `distributed_running_query_num` change. Is it just very slow query, or something wrong with the execution?
<img width="1440" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/70626450/ae45937f-74dc-4e4f-b746-25d88ca3fd11">

**Comment by zwang28** [comment]
In the log we see `risingwave_frontend::scheduler::hummock_snapshot_manager: Unpin epoch ??? with RPC` where ??? is the stuck min pin epoch shown in dashboard, meanwhile we don't see `Request meta to unpin snapshot failed`. 🤔 

```
tracing::info!("Unpin epoch {:?} with RPC", min_epoch);
match meta_client.unpin_snapshot_before(min_epoch).await {
    Ok(()) => last_unpin_epoch.store(min_epoch, Ordering::Release),
    Err(e) => error!("Request meta to unpin snapshot failed {:?}!", e),
}
```

**Comment by zwang28** [comment]
We do observe indication of batch task leaked in compute node: the running task num is not zero in compute node, while the query num is zero according to frontend.

<img width="1447" alt="Screenshot 2023-05-16 at 17 36 43" src="https://github.com/risingwavelabs/risingwave/assets/70626450/a26f0535-3155-4f44-b2dc-8335fcecc756">


<img width="1442" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/70626450/926f970e-6cef-445d-bc5f-67401f9056fd">

**Comment by zwang28** [comment]
> this may cause pinning of hummock version?

Discussed offline. #9848

**Comment by zwang28** [comment]
#9953

**Comment by zwang28** [comment]
We encounter another unexpected pinned version by compute node:
1. A long running batch query held hummock version. That's expected.
![image](https://github.com/risingwavelabs/risingwave/assets/70626450/01a4c5c0-e35b-48fa-bed9-314c2eca992d)

2. We restarted frontend, which subsequently finished batch heartbeat workers in compute nodes. That's expected. 
<img width="754" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/70626450/56ce695c-5e7c-4b77-a30f-45152d0f4490">

3. However, although [cancel_task had been called by heartbeat workers](https://github.com/risingwavelabs/risingwave/blob/b3a419537835ea7ada51354abbfe7f496445676e/src/batch/src/task/task_manager.rs#L184), the compute node still held the hummock version. That's unexpected.

```
Worker 144004 type COMPUTE_NODE min_pinned_version_id 5592335
Worker 145005 type COMPUTE_NODE min_pinned_version_id 5592660
```

@liurenjie1024 @ZENOTME Let's dig into this.

**Comment by liurenjie1024** [comment]
So this means that SeqScanExecutor not dropped? You can add some logs in it to see if it's dropped.

**Comment by liurenjie1024** [comment]
Did some investigation with no clue. Add https://github.com/risingwavelabs/risingwave/pull/13589 to make the metrics to be more accurate to see if it's really caused by mpp task.

**Comment by liurenjie1024** [comment]
Some more hints:
1. The metrics shows that there is a long running mpp query, but it can't be detected by show process list (they have 3 fe nodes), I think this maybe possible
2. The query lasted for 5 hours

**Comment by zwang28** [comment]
No occurrence recently after introducing statement_timeout.
