### ISSUE TITLE
feat: Nats integration support for Source and Sink

### ISSUE THREAD

**Issue by enthusiva** [risingwavelabs/risingwave#9742]
Please add feature to create sources and sinks using Nats (nats.io)

**Comment by enthusiva** [comment]
Hi @neverchanje ,

We use Nats to collect data from IoT devices through MQTT and our front-end applications use Nats for real-time data through websockets. NATS has greatly helped to reduce the cost and complexity in development and operation of our IoT projects. 

IMHO, Nats is a light-weight alternative to Kafka. Like Risingwave, it is simple, minimalistic, performant and cost effective.

https://docs.nats.io/nats-concepts/overview/compare-nats

As part of our R&D, we came across Risingwave and impressed by its valuable features.

Currently, risingwave demands us to use either Kafka or Debezium to use the streaming capabilities of Risingwave, which might add complexity and additional dependencies to our projects.

I personally see, the nats-kafka-bridge as a migration tool for existing projects that wants to move from Kafka to NATS or vice versa. The maintenance of topic mappings between NATS and Kafka will become a chore.

So, I believe that by adding built-in support for NATS, risingwave will embrace NATS ecosystem and helps to build cost effective solutions.

**Comment by yufansong** [comment]
Closed. Finished at #12015 and #11924
