### ISSUE TITLE
rename the `primary_key` field to `key` in our Kafka sink

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#9768]
### Is your feature request related to a problem? Please describe.

Originally, the primary_key field was only designed for cases where the downstream supports PK uniqueness. However, we soon discovered that the key could also be used for partitioning. For example, Pinot can take advantage of the partitioning scheme to improve performance (see https://docs.pinot.apache.org/operators/operating-pinot/tuning/routing#data-ingested-partitioned-by-some-column). In this case, the "key" field can have a more general indication that it can emit changes with certain fields as the Kafka key.

### Describe the solution you'd like

`key`  is not limited to Kafka. Kinesis also supports a partition key: [https://docs.aws.amazon.com/streams/latest/dev/key-concepts.html](https://docs.aws.amazon.com/streams/latest/dev/key-concepts.html), and Pulsar has a similar concept: [https://pulsar.apache.org/docs/3.0.x/concepts-messaging/](https://pulsar.apache.org/docs/3.0.x/concepts-messaging/).

Alternatively, we could name this field `kafka_key`. However, since these systems all support the key model, naming it `key` would ensure consistency with other connectors.

**Comment by tabVersion** [comment]
I would keep the original naming to make consistency with other sink connectors.
