### ISSUE TITLE
proposal(source): Support retrieving keys for message queue sources

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#9774]
### Is your feature request related to a problem? Please describe.

Most message queue systems have the key concept for either partitioning or ensuring data uniqueness. We now provide no means to get the key.

```
{"city":"los angeles"} | {"credit_card":"4591 5419 7260 8350","email_address":"siqjtnt@tjjek.com","id":1005,"name":"sarah smith"}
```

Given a Kafka record like the above, there is no way to pass the key through the source.

### Describe the solution you'd like

 I expect that we can provide a syntax like this:

```sql
CREATE SOURCE city (
    "id" int,
    "name" varchar,
    "email_address" varchar,
    "credit_card" varchar,
    "city" VARCHAR
) WITH (
    connector = 'kafka',
    properties.bootstrap.server = '127.0.0.1:29092',
    topic = 'city',
    key.fields = 'city',
    key.format = 'JSON'
) ROW FORMAT JSON
```

This design could also cover the upsert_json case.

```sql
CREATE TABLE city (
    "id" int,
    "name" varchar,
    "email_address" varchar,
    "credit_card" varchar,
    "city" VARCHAR PRIMARY KEY
) WITH (
    connector = 'kafka',
    properties.bootstrap.server = '127.0.0.1:29092',
    topic = 'city',
    key.fields = 'city',
    key.format = 'JSON'
) ROW FORMAT JSON
```

There will be no need for upsert_json anymore.

It will be a little more complex when it comes to Avro, which requires a schema registry:

```
```sql
CREATE TABLE city (
    "id" int,
    "name" varchar,
    "email_address" varchar,
    "credit_card" varchar,
    "city" VARCHAR PRIMARY KEY
) WITH (
    connector = 'kafka',
    properties.bootstrap.server = '127.0.0.1:29092',
    topic = 'city',
    key.fields = 'city',
    key.format = 'AVRO',
    key.schema_registry_location = 'localhost:8081'
) ROW FORMAT JSON
```

**Comment by tabVersion** [comment]
thats what `key as column` try to fix https://github.com/risingwavelabs/risingwave/pull/9386

**Comment by tabVersion** [comment]
expect to resolve in new source syntax https://github.com/risingwavelabs/rfcs/pull/64

**Comment by tabVersion** [comment]
now we support retrieving keys as `bytea` as default behavior
close as completed
