### ISSUE TITLE
q5-rewrite hits the same issue twice in the same time in two days.

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#9788]
### Describe the bug

We found a bizarre issue recently in our daily performance test q5-rewrite. The logs show that we may hit the same network issue this morning and last Friday morning. The meta node couldn't connect to the kafka and there were some failures during the communications between risingwave components according to the logs. So I think it was a network issue last Friday. But it happened twice since last Friday.

Is this a coincident network issue or a real production issue? Should we involve someone in the cloud team? @huangjw806 @fuyufjh @lmatz 

Last Friday's detail
```
exec-url: https://buildkite.com/risingwave-test/nexmark-benchmark/builds/1035
grafana-url: https://g-2927a1b4d9.grafana-workspace.us-east-1.amazonaws.com/d/EpkBw5W4k/risingwave-test-dashboard?orgId=1&from=1683818590000&to=1683820396000&var-namespace=nexmark-blackhole-q105
log-url: https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Frisingwave$252Ftest-useast1-eks-a$252Fnexmark-blackhole-q105

```

This morning's detail
```
exec-url: https://buildkite.com/risingwave-test/nexmark-benchmark/builds/1037
grafana-url: https://g-2927a1b4d9.grafana-workspace.us-east-1.amazonaws.com/d/EpkBw5W4k/risingwave-test-dashboard?orgId=1&from=1683828594000&to=1683828597000&var-namespace=nexmark-bs-3-4-5-5r-daily-20230511
log-url: https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Frisingwave$252Ftest-useast1-eks-a$252Fnexmark-bs-3-4-5-5r-daily-20230511
```

![image](https://github.com/risingwavelabs/risingwave/assets/35356271/129ab238-264a-41ef-a968-3c552d38bf15)
![image](https://github.com/risingwavelabs/risingwave/assets/35356271/4c5ef4b9-24d3-438a-ab17-7bb3d80dfd5c)

**Comment by hzxa21** [comment]
I saw a lot of in dns errors in the log:
## meta
```
2023-05-11T18:09:50.515831Z  INFO risingwave_meta::stream::source_manager: spawning new watcher for source 1036
2023-05-11T18:11:09.962612Z ERROR risingwave_meta::rpc::election_client: lease keeper failed grpc request error: status: Unknown, message: "error reading a body from connection: stream closed because of a broken pipe", details: [], metadata: MetadataMap { headers: {} }
2023-05-11T18:11:09.962612Z  WARN risingwave_meta::rpc::election_client: error grpc request error: status: Unknown, message: "error reading a body from connection: stream closed because of a broken pipe", details: [], metadata: MetadataMap { headers: {} } received from leader observe stream
2023-05-11T18:11:10.195246Z ERROR librdkafka: librdkafka: FAIL [thrd:benchmark-kafka-0.benchmark-kafka-headless.nexmark-bs-3-4-5-5r-]: benchmark-kafka-0.benchmark-kafka-headless.nexmark-bs-3-4-5-5r-daily-20230511.svc.cluster.local:9092/0: Failed to resolve 'benchmark-kafka-0.benchmark-kafka-headless.nexmark-bs-3-4-5-5r-daily-20230511.svc.cluster.local:9092': Name or service not known (after 3ms in state CONNECT)
```
## frontend
```
WARN risingwave_rpc_client::meta_client: force refresh meta client failed gRPC error (The service is currently unavailable): error trying to connect: dns error: failed to lookup address information: Name or service not known
WARN risingwave_rpc_client::meta_client: Failed to send_heartbeat: error gRPC error (The service is currently unavailable): error trying to connect: dns error: failed to lookup address information: Name or service not known
```

It seems that there is a network partitioning between meta node and all other nodes including CN/frontend/kafka. I suspect the same underlying issue is also causing #9157.

cc @arkbriar any ideas?

**Comment by arkbriar** [comment]
DNS errors might happen when the Pod itself is not in an available status, e.g., restarting, crash loop or some other abnormal status where the availability probes keep failing. Did the meta or Kafka restart during the test?

**Comment by hzxa21** [comment]
> DNS errors might happen when the Pod itself is not in an available status, e.g., restarting, crash loop or some other abnormal statuses where the availability probe keeps failing. Did the meta or Kafka restart during the test?

I didn't see the startup related logs in the meta pod so I believe meta didn't restart. Same for kafka. Is there any way to check the failure rate or count for the availablity probe?

**Comment by arkbriar** [comment]
> Is there any way to check the failure rate or count for the availablity probe?

It can be checked with `kubectl describe pod <pod name>` in the events section. But the events are not durable so they might have been deleted.

> 2023-05-11T18:11:09.962612Z  WARN risingwave_meta::rpc::election_client: error grpc request error: status: Unknown, message: "error reading a body from connection: stream closed because of a broken pipe", details: [], metadata: MetadataMap { headers: {} } received from leader observe stream

> It seems that there is a network partitioning between meta node and all other nodes including CN/frontend/kafka.

Seems you are right. The connections disconnected and the DNS could not be resolved. These should be signs of a network partition instead of a simple DNS failure. I have no idea what happened. 

Ping me if this happens again so we can inspect the environment carefully.

**Comment by cyliu0** [comment]
Seems like we hit this again. @arkbriar 
```
risingwave_meta::barrier::recovery: reset compute nodes failed err=Rpc error: gRPC error (The service is currently unavailable): error trying to connect: dns error: failed to lookup address information: Name or service not known
```
```
Execution 3603 for benchmark tpch-q2-bs-medium-1cn failed.
Execution URL: https://buildkite.com/risingwave-test/tpch-benchmark/builds/818
Grafana: https://g-2927a1b4d9.grafana-workspace.us-east-1.amazonaws.com/d/EpkBw5W4k/risingwave-test-dashboard?orgId=1&from=1684912446000&to=1684912808000&var-namespace=tpch-bs-daily-20230523
Log: https://g-2927a1b4d9.grafana-workspace.us-east-1.amazonaws.com/explore?left=%7B%22datasource%22:%22Logging(tenant):%20test-useast1-eks-a%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22tpch-bs-daily-20230523%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%221684912446000%22,%22to%22:%221684912808000%22%7D%7D&orgId=1
```

**Comment by arkbriar** [comment]
> Seems like we hit this again. @arkbriar
> 
> ```
> risingwave_meta::barrier::recovery: reset compute nodes failed err=Rpc error: gRPC error (The service is currently unavailable): error trying to connect: dns error: failed to lookup address information: Name or service not known
> ```
> 
> ```
> Execution 3603 for benchmark tpch-q2-bs-medium-1cn failed.
> Execution URL: https://buildkite.com/risingwave-test/tpch-benchmark/builds/818
> Grafana: https://g-2927a1b4d9.grafana-workspace.us-east-1.amazonaws.com/d/EpkBw5W4k/risingwave-test-dashboard?orgId=1&from=1684912446000&to=1684912808000&var-namespace=tpch-bs-daily-20230523
> Log: https://g-2927a1b4d9.grafana-workspace.us-east-1.amazonaws.com/explore?left=%7B%22datasource%22:%22Logging(tenant):%20test-useast1-eks-a%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22tpch-bs-daily-20230523%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%221684912446000%22,%22to%22:%221684912808000%22%7D%7D&orgId=1
> ```

For the details, kindly refer to the slack channel here: 
https://risingwave-labs.slack.com/archives/C04R6R5236C/p1684912809880659

**Comment by fuyufjh** [comment]
I think this issue has disappeared for some time. I'll close it now and please feel free to reopen.
