### ISSUE TITLE
use navicat connect to risingwave , open connection failure.

### ISSUE THREAD

**Issue by milkdrink** [risingwavelabs/risingwave#9800]
### Describe the bug

i want to use navicat to convert mysql ddl to risingwave  auto .

as the title say open connection failure, but test connection can success.

the error is : ERROR: QueryError: Item not found: Invalid column: dattablespace.

**Comment by lmatz** [comment]
Thank you for trying Risingwave!

This error is because `pg_catalog` in Risingwave has not supported this column `dattablespace` yet.

```
dev=> select * from pg_database;
 oid | datname | datdba | encoding | datcollate | datctype | datistemplate | datallowconn | datconnlimit | datacl 
-----+---------+--------+----------+------------+----------+---------------+--------------+--------------+--------
   0 | dev     |        |        6 | C          | C        | f             | t            |           -1 | 
(1 row)
```
