### ISSUE TITLE
CDC source data type mapping to RisingWave data type

### ISSUE THREAD

**Issue by StrikeW** [risingwavelabs/risingwave#9840]
Check whether the data type of the CDC source is correctly mapped to the data type of RisingWave. We may not support some data types from the upstream database.
- Write unit tests to cover all supported upstream data type
- Denote upstream data types that we don't support right now

https://www.notion.so/risingwave-labs/Debezium-Datatype-Mappings-Source-a79f9c1f8ab94e39beba565edc1cb11b

The above doc targets the Debzium JSON format.

**Comment by WillyKidd** [comment]
we have now added unit tests for the debezium json parser for most supported types in Postgres/Mysql, see the notion doc here https://www.notion.so/risingwave-labs/Debezium-Datatype-Mappings-Source-a79f9c1f8ab94e39beba565edc1cb11b

**Comment by StrikeW** [comment]
@hengm3467 Do we have a plan to deliver a data type mapping user doc? related: https://github.com/risingwavelabs/risingwave/discussions/10129

**Comment by fuyufjh** [comment]
Hi, any updates?

**Comment by StrikeW** [comment]
Oh, doc team has a PR for the data type mapping doc.  You can also take a look https://github.com/risingwavelabs/risingwave-docs/pull/1103
