### ISSUE TITLE
dynamic linking is still not good enough

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#9852]
I added feature for dynamic linking OpenSSL and zstd for *better DX* (>30s less compile time for full debug build). However, that's still not good enough in terms of DX. The main reason seems to be that cargo feature is very invasive. 

Since currently the feature is on `risingwave_cmd_all`, Cargo commands with `-p` (e.g., `cargo test -p risingwave_stream`) doesn't work perfectly. This also include `Run Test` button in VSCode. 

For `-p risingwave_stream`, we can't configure the features at all! The only possible configuration is the defaults, which is dynamic-link OpenSSL (This is where the most trouble come from) and static-link zstd.

I can come up with these solutions now:
1. Add feature flags for every crate.
2. Force static linking in the first crate introducing the dependency (e.g., `risingwave_connector` - `rdkafka` - `openssl`). This is actually the case before my recent changes. Note that in this case, `workspace-config/rw-static-link` is basically useless. We don't configure at all. Everyone uses the  same setting.
3. Make dependencies to e.g., OpenSSL, zstd completely optional (i.e., add feature flags to enable them). Would this be a better way than dynamic linking? I think this can compile even faster, but need to make code changes.

--- 

In terms of DX, my considerations include:
1. Compilation speed (which is why I initiated the changes). 
2. Whether need to install external dependencies, and whether need to set up env.
3. Whether works well with tools like `cargo`, `rust-analyzer`

It's good if it can work out of the box (2 & 3), but it conflicts with 1. 😩 

BTW, although "full debug build" sounds a rare situation, but
- I do `cargo clean` from time to time to avoid `target` being too large. (Not sure whether static-linking makes this problem more serious)
- Not sure whether the startup time of `rust-analyzer` is related. It seems to rebuild many things on startup.

**Comment by BugenZhao** [comment]
Directly passing `--cfg` could be the ultimate solution regardless of package dependency relationships. 🥵 But I'm not sure whether we're abusing it in this case.

**Comment by xxchan** [comment]
> Force static linking in the first crate introducing the dependency (e.g., risingwave_connector - rdkafka - openssl). This is actually the case before my recent changes.

A little embarrassing change: previously, only `openssl` is forced to static link, but not `sasl2-sys`, but now under the default option it's statically linked. 😇😇😇

![image](https://github.com/risingwavelabs/risingwave/assets/37948597/bde404b0-5e79-49a6-b849-b78007a58cbf)

**Comment by xxchan** [comment]
Another idea: force static linking. The only drawback is slow fresh build. In CI, we build these deps beforehand and cache them ourselves in s3/build image. 🥸

**Comment by xxchan** [comment]
> In CI, we build these deps beforehand and cache them ourselves in s3/build image.

This is not as easy as I thought (https://github.com/risingwavelabs/risingwave/pull/11097)... Why it doesn't work? Is it because of sccache?? 🥲

**Comment by xxchan** [comment]
Maybe we can fork https://github.com/Swatinem/rust-cache as a buildkite plugin.

**Comment by fuyufjh** [comment]
Hey, any updates here?

**Comment by xxchan** [comment]
Considering the limited benefit of speeding up fresh debug build, it seems not worth the complexity to improve the status.
