### ISSUE TITLE
protobuf sint32 support

### ISSUE THREAD

**Issue by wafe001** [risingwavelabs/risingwave#9856]
### Is your feature request related to a problem? Please describe.

Our kafka protobuf source schema contains sint32 which isn't currently supported:
ERROR:  QueryError: Feature is not yet implemented: unsupported field type: sint32

### Describe the solution you'd like

protobuf support for sint32

**Comment by tabVersion** [comment]
I thought sint convertion is handled by prost. But unfortunately, the lib we rely on has no support on this https://docs.rs/prost-reflect/0.11.4/prost_reflect/enum.Value.html
