### ISSUE TITLE
Compactor: Reduce Compactor Cpu usage with Block Copy

### ISSUE THREAD

**Issue by Li0k** [risingwavelabs/risingwave#9857]
### Is your feature request related to a problem? Please describe.

Hummock turns on the compression algorithm at high level, and the compression algorithm incurs significant cpu overhead. When we deal with blocks without overlap, the key by key method may not be necessary, and we can use the direct copy method to avoid the compression and decompression of blocks and reduce the CPU usage.

According to the above, we can use a more aggressive compression algorithm to reduce the read/write traffic during Compaction and further improve the speed of Compaction.

### Describe the solution you'd like

1. Monitor the percentage of data that can be block copied
2. Implement Block Copy on the Compactor side
3. Use a more aggressive compression algorithm in Hummock
4. Test with different sst sizes

**Comment by Li0k** [comment]
Thanks for @Little-Wallace 

In the daily nexmark q20 test, we found that l0 files were heavily stacked. However, in wallace's test, when we used 2cn-2compactor, the compactor was able to control the number of l0 files better.

<img width="731" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/15023748/717438c0-4701-48c7-a413-56e52f569ac0">

<img width="734" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/15023748/4921f71e-62f1-4419-a4e1-34cae8ff5149">

<img width="735" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/15023748/5d8f6d5a-b613-49a3-bc94-bef9f4fed74f">

In the above test, we can see from the traffic and cpu situation that the traffic has not reached the bottleneck yet, but the cpu has been exhausted, so Block Copy may be an advantage for this scenario.

**Comment by Li0k** [comment]
<img width="1605" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/15023748/71d39236-e00b-474f-b1bf-6567a0d7d2da">

By analyzing the block distribution of the high level compaction task, we find that the number of blocks eligible for Block Copy is as expected under the existing picker policy and configuration.

Moreover, the statistical algorithm is rough, and by checking the algorithm more accurately, we can achieve a higher Block Copy rate and save more resources in high level compaction, so I think this optimization is feasible.

**Comment by Li0k** [comment]
- https://github.com/risingwavelabs/risingwave/pull/10673

**Comment by hzxa21** [comment]
@Li0k @Little-Wallace I think this issue has been done and merged to main. We are testing it before officially releasing this feature so I will move this issue to the next milestone.
