### ISSUE TITLE
agg: reduce agg state size and memory allocation

### ISSUE THREAD

**Issue by wangrunji0408** [risingwavelabs/risingwave#9900]
### Is your feature request related to a problem? Please describe.

In #9864 we found that the aggregator state size was incredibly high.

A simple `sum(int64)` state consumes up to 96 bytes memory and has 3 mallocs:
```rust
BoxedAggState {                 // 16
    inner: BoxedAggState {      // 16
        return_type: DataType,  // 16
        state: Option<i64>,     // 16
    },
    indices: Vec<usize> [       // 24
        i                       // 8
    ],
}
```

This results in high memory consumption and allocation overhead in `HashAggExecutor`, since there is at least one agg state for each group key.

### Describe the solution you'd like

First, the `indices` vector for projection could be removed. We should project chunks in the executor before feeding them into the aggregator. This method can save 48 bytes.

```rust
BoxedAggState {             // 16
    return_type: DataType,  // 16
    state: Option<i64>,     // 16
}
```

Second, the `return_type` could be omitted as long as it is not composite type (list or struct). This can save another 16 bytes.

```rust
BoxedAggState {             // 16
    state: Option<i64>,     // 16
}
```

Finally, we may further inline common aggregators to completely eliminate allocation in most cases.
```rust
enum AggState {
    Box(BoxedAggState),
    SumI16(Option<i16>),
    SumI32(Option<i32>),
    SumI64(Option<i64>),
    ...
}
```
The state size could be compressed to a limit of 16 bytes.

**Comment by fuyufjh** [comment]
Hi, any progress?

**Comment by wangrunji0408** [comment]
#10753 has reduced size of some states in streaming agg. But optimizations for the batch side have not done yet.
