### ISSUE TITLE
Write tool or doc on how to do full cluster stack trace

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#9905]
Example usecase:
1. Run a sql query.
2. See the stack trace from frontend -> compute -> meta -> etc...

Maybe I should just be using await-tree in dashboard for this. Haven't tried that tool out yet.

But my idea is slightly different.
1. Just use a single threaded all in one binary (madsim bin?).
2. Then get stack trace on that.

**Comment by BugenZhao** [comment]
The design goal of await-tree is to improve the observability of async tasks by exposing the execution with a logical tree. For this reason, it only functions within a single task and does not extend across threads or processes.

I suppose what you want is *distributed tracing* (for example, PingCAP's [blog](https://www.pingcap.com/blog/how-we-trace-a-kv-database-with-less-than-5-percent-performance-impact/)). I'm considering implementing a similar idea in our system these days, which could be mainly beneficial for batch/serving queries. 🤔

**Comment by kwannoel** [comment]
https://github.com/risingwavelabs/risingwave/issues/10000
