### ISSUE TITLE
enhancement: current streaming hash join eviction strategy may not be enough for intensive queries such as tpch-modified-q2

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#9934]
It is now just an speculation, and we may add some metrics to join the operator to validate this.

When running TPC-H queries(currently we only run those with a high number of joins), they are all good.

But when running the variants(by removing `XXX = Constant1` type of filter condition) of TPC-H queries, TPC-H Q2 crashed due to OOM. This query has 9 hash joins in the query. 
https://github.com/risingwavelabs/risingwave/blob/main/src/frontend/planner_test/tests/testdata/tpch_variant.yaml#L88-L130

It is suspected that 
https://github.com/risingwavelabs/risingwave/blob/main/src/stream/src/executor/hash_join.rs#L850
`evict_cache` is not enough to just consider the number of input rows
but also the number of rows produced by this join operator since the beginning of the latest barrier/chunk.

**Comment by fuyufjh** [comment]
I think we have made the HashJoin being able to evict JoinEntry when processing each N rows. I'll close it for now.
