### ISSUE TITLE
tracking: support native integration with superset via the postgres driver

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#9938]
- [x] #7736
- [x] #9939
- [x] #2954 fully support the `pg_type` system table.
- [x] #2954 fully support the `pg_namespace` system table

~~Seems risingwave has been added to superset's official support list, but we didn't utilize it yet.~~
~~https://github.com/apache/superset/blob/master/superset/db_engine_specs/risingwave.py~~

Superset's PostgreSQL driver native support: connection function test completed, platform capability basic test completed, all datatype can be recognized.

**Comment by fuyufjh** [comment]
Hi, @jetjinser @neverchanje May I close this issue? Seems done

**Comment by jetjinser** [comment]
I think it's okay to close
