### ISSUE TITLE
missing `typarray`  in the `pg_type` table

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#9939]
```sql
SELECT t.oid, typarray FROM pg_type AS t JOIN pg_namespace AS ns ON typnamespace = ns.oid WHERE typname = 'hstore';
```

Required by superset.

**Comment by xiangjinwu** [comment]
> WHERE typname = 'hstore'

Note that we do not support the [hstore extension](https://www.postgresql.org/docs/15/hstore.html) (map data type) right now

**Comment by lmatz** [comment]
link #11145
