### ISSUE TITLE
test client libraries in the main-cron test

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#9958]
https://www.notion.so/risingwave-labs/client-libraries-215dccb91503473787a4ddfe0aa2b422

Please write the tests and run them in the main-cron test so that we can verify them on a daily basis.

Feel free to assign the owner to each test. @sumittal 

Please open a PR once the implementation of tests starts so that people can help.

- [x] Java PostgreSQL JDBC driver(https://jdbc.postgresql.org/)
- [x] node.js node-postgres(https://www.npmjs.com/package/pg)
- [x] python psycopg2 (https://pypi.org/project/psycopg2/)
- [x] go pgx(https://github.com/jackc/pgx)
- [x] PHP pdo-pgsql(https://www.php.net/manual/en/ref.pdo-pgsql.php)
- [x] Ruby ruby-pg(https://github.com/ged/ruby-pg)

**Comment by xxchan** [comment]
BTW, here's a prior art: https://github.com/risingwavelabs/risingwave/pull/7113

**Comment by lmatz** [comment]
>Basically sqllogictest --engine=external can create a subprocess as the driver (with this protocol https://github.com/risinglightdb/sqllogictest-rs/blob/27eb9f50993e10b36c1f4f68ad3afe499adbbb49/sqllogictest-engines/src/external.rs#L16-L36), so we can test any client library with all our slt test suites in this way. Although I'm not sure whether we want to do so, or just some simple tests are enough.

cc: @abhyuday26
