### ISSUE TITLE
s3-compatible storage don't handle state store's data_directory consistently with s3

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#9974]
### Describe the bug

With regard to state store's `data_directory`, s3-compatible storages don't always behave consistently with s3. 
For example, `data_directory="///"` works fine for s3, but results in incorrect result for list op for minio. Another case is `data_directory=""`.

### Additional context

We may require data_directory to be in the minimal valid set of all supported s3-compatible storages.

@wcy-fdu @arkbriar @hzxa21

**Comment by hzxa21** [comment]
> We may require data_directory to be in the minimal valid set of all supported s3-compatible storages.

+1

**Comment by arkbriar** [comment]
Please kindly share the algorithm for validating the data directory once you get one. I would like to also implement it in the operator to prevent from passing down invalid values.

**Comment by wcy-fdu** [comment]
> 

Right now we can first add some simple verification for `data_directory`, such as not null, not end with "//". In the future we can add more strict constraint(length, ...)
